### ISSUE TITLE
Appending newlines does not scroll editor

### ISSUE THREAD

**Issue by jhchen** [quilljs/quill#1]
Adding newlines at the end from user input should scroll the editor to keep the cursor in view

**Comment by jcludwig** [comment]
This still repros for me on the Quill site as of v0.19.14

**Comment by jhchen** [comment]
What browser + os are you using?

**Comment by jcludwig** [comment]
Windows 8.1, Chrome 43.0.2357.134 m & IE 11.0.21

As soon as you type any other characters the it scrolls to your cursor.

**Comment by jhchen** [comment]
Duplicate of #433. Closing this one since the other issue has the associated PR.
