### ISSUE TITLE
Show Bubble theme toolbar on double click

### ISSUE THREAD

**Issue by artaommahe** [quilljs/quill#1002]
It would be useful to have double click/tap action on empty line or at any space without selection that shows tooltip for Bubble theme. It's required for easy embed things adding.
Currently this can be achieved only if there is some text, new line after this and careful double click at the text line end (to avoid text selection).

**Comment by artaommahe** [comment]
> A detailed description of the feature

Show tooltip on doubleclick in editor with Bubble theme.

> A quick background of where and how you are using Quill

Articles writing like medium editor.

> The use case that would be enabled or improved for your product, if the feature was implemented

Adding images/embeds that does not require text selection with Bubble theme.

> Considerations and behavior differences for other use cases that may benefit from the feature

-

**Comment by steverob** [comment]
@artaommahe were you able to get this done?
