### ISSUE TITLE
Custom classes being stripped out on initialization

### ISSUE THREAD

**Issue by JohnColvin** [quilljs/quill#1008]
I've overridden the built in align class formatter to use existing classes in a project. On initialization, quill is stripping those classes out. It does properly apply the custom classes when using the align function, though.

Thanks for the help!

```javascript
var Parchment = Quill.import('parchment');
var alignOptions = { scope: Parchment.Scope.BLOCK, whitelist: ['right', 'center'] };
var AlignClass = new Parchment.Attributor.Class('align', 'text', alignOptions);
Quill.register(AlignClass, true);

var quill = new Quill('#editor-container', {
  formats: ['align'],
  modules: {
    toolbar: [
      [{ 'align': [false, 'center', 'right'] }]
    ]
  },
  theme: 'snow'
});
```

**Steps for Reproduction**

1. Visit codepen example http://codepen.io/anon/pen/gwWoWV
2. Note that the editor's container HTML does not have the text-center class from the given HTML
3. Center the text using the toolbar button
4. Note that the text-center class is properly applied

**Expected behavior**:
Editor does not strip out custom classes on initialization

**Actual behavior**:
Editor does strips out custom classes on initialization

**Platforms**:
Chrome 53.0.2785.116
OS X 10.11.6

**Version**:
1.0.4

**Comment by jhchen** [comment]
The problem is the name `text` is special internally and this appears to be unexpectedly having effect externally. If you change the key name and corresponding prefix from `text` to `tex` for example the code works fine.

There are a few more special names and it's rather difficult to unreserve them so it seems the best route might be to just add a `console.warn`?

**Comment by JohnColvin** [comment]
Oh, thanks! A console warning would be great in this case.

I have one more question about customizing classes. I want to override the indent class, but there is logic for that one on top of the base parchment class. Is this the proper way to do that without having to recreate the class?

```javascript
var Parchment = Quill.import('parchment');
var indentOptions = { scope: Parchment.Scope.BLOCK, whitelist: [1,2,3,4] };
var IndentAttributor = Quill.import('formats/indent').constructor;
var IndentClass = new IndentAttributor('indent', 'text-indent', indentOptions);
Quill.register(IndentClass, true);
```

This also works, but I'm not sure if it's risky to overwrite the properties of the built in indent class.

```javascript
var IndentClass = Quill.import('formats/indent');
IndentClass.keyName = 'text-indent';
IndentClass.whitelist = [1,2,3,4];
Quill.register(IndentClass, true);
```

Thanks for the help!

**Comment by jhchen** [comment]
Do you just want to overwrite the whitelist or other behaviors too?

**Comment by JohnColvin** [comment]
I want to overwrite the whitelist and the class name and leave the other logic as it is.

**Comment by jhchen** [comment]
If you're modifying the keyName I would inherit from the indent class like in your first example.

**Comment by JohnColvin** [comment]
Great! Thanks again for all the help!

**Comment by dynothunder** [comment]
How can I change indent class into indent inline style.

**Comment by webberig** [comment]
We encountered the same problem and I ended up here googling for a solution.

CSS frameworks happen to use that class:

Bootstrap: https://getbootstrap.com/docs/4.3/utilities/text/#text-alignment
tailwind css: https://tailwindcss.com/docs/text-align/
Foundation: https://foundation.zurb.com/sites/docs/v/5.5.3/utility-classes.html

I think it would be beneficial to reconsider and find a solution to allow this class convention for alignment.
