### ISSUE TITLE
Select menus don't work on custom toolbars without theme 

### ISSUE THREAD

**Issue by saw** [quilljs/quill#1009]
Quill adds `preventDefault()` on mousedown to the toolbar container, which prevents select menus from opening on mousedown. With a theme this doesn't matter because you have the picker. I understand this is done to keep the editor from blurring, but it would be nice to be able to use quill without a theme at all without having to re-implement the toolbar completely.

**Steps for Reproduction**

1. Visit http://codepen.io/saw-1473371988/pen/NRjzJz
2. Try and pick a size.

**Comment by jhchen** [comment]
Yes this has been fixed and should be in the next release #997

**Comment by saw** [comment]
Thanks! sorry for the noise.
