### ISSUE TITLE
Link Button Not working (Unless there is sufficient space underneath)

### ISSUE THREAD

**Issue by KenoLeon** [quilljs/quill#1013]
The link button won't show the input box unless there's at least 2 lines underneath.

**Steps for Reproduction**

1. Visit http://codepen.io/k3no/pen/gwRwJb
2. Type text 
3. click link button

**Expected behavior**:
An input box for the link should appear ?

**Actual behavior**:
An input box for the link does not appear, unless there is 2 lines underneath and you select the text 

**Platforms**:

Safari 9.1.3 Mac OS X El Capitan

**Version**:
v 1.0.0 &  v1.0.4

**Comment by KenoLeon** [comment]
Edit: Container needs a minimum height, something like 100 px and it works, not sure if this is mentioned in the docs, but it threw me off while first trying the quick start example.

**Comment by jhchen** [comment]
#851
