### ISSUE TITLE
Version 1.0.5 missing from NPM

### ISSUE THREAD

**Issue by chuckh** [quilljs/quill#1015]
Version 1.0.5 missing from NPM packages

**Steps for Reproduction**

Go to https://www.npmjs.com/package/quill

**Expected behavior**:
1.0.5 is the latest of 46 releases

**Actual behavior**:
1.0.4 is the latest of 45 releases
npm ERR! No compatible version found: quill@^1.0.5

**Platforms**:
npm install quill

**Version**:
1.0.5

**Comment by jhchen** [comment]
Published thanks!
