### ISSUE TITLE
NPM v1.0.5 differs from 1.0.5 tag in github

### ISSUE THREAD

**Issue by saw** [quilljs/quill#1017]
when I npm install quill the file in node_modules is not the same as what I get when I npm build that tag in the quill repo. This results in an error when using quill from npm: `property 'bind' of undefined` (undefined var is `_this.onDrop`, you can see it is not present in the source version)

Diff is here: https://gist.github.com/saw/d4a0b7829f9c4516b84285459f9c9b38

**Comment by jhchen** [comment]
Apologies there was a build issue with some local code changes that NPM picked up and published. 1.0.5 has been removed and 1.0.6 should be the same thing without the build issue.

**Comment by saw** [comment]
Thanks!
