### ISSUE TITLE
Delta has wrong information when using alignment

### ISSUE THREAD

**Issue by nicohvi** [quilljs/quill#1018]
It seems the `align` attribute is set on the wrong element in the Delta object when using alignment. It's set on the following newline rather than the text itself (is this intended?)

**Steps for Reproduction**

1. Go to: http://codepen.io/anon/pen/mArQpm
2. Type in a title you want to align centrally
3. Specify the correct alignment
4. Click the "Save" button, and check the developer console.

**Expected behavior**:
The title text should have `attributes: align: 'center'`.

**Actual behavior**:
The newline text has the attribute.

**Comment by benbro** [comment]
Yes, this is intended.
Some formats like alignment, direction and list act on the whole line while others like bold act on characters. You can't have one character with left alignment and another with center alignment on the same line. The new line character is the perfect place to store formats that affect the whole line.

**Comment by nicohvi** [comment]
Thank you very much for the quick response @benbro 👍
