### ISSUE TITLE
Undo issue

### ISSUE THREAD

**Issue by cutteroid** [quilljs/quill#1019]
Still having issues with undo.
Likely related to #889 but not sure.

**Steps for Reproduction**

1. Visit [playground](http://quilljs.com/playground/#autosave)
 (autosave example chosen because it had some text, nothing more)
2. Select part of content and input some text
3. Change text format and input some more text (without format changing undo works as intended)
4. Hit undo several times
5. Notice changes on each undo.

**Expected behavior**:
Content correctly restored to initial state

**Actual behavior**:
Initial content altered. Different browsers generate different results.

**Platforms**:

Windows, OS X. Latest Chrome, Firefox, Safari.

**Version**:

1.0.6

![undo_bug](https://cloud.githubusercontent.com/assets/20125880/18988265/83724646-870e-11e6-939f-0ac7033e548b.gif)
P.S. multiple cursors are some kind of gif compression issue.

**Comment by benbro** [comment]
I can reproduce with the following steps:
1. Visit http://quilljs.com/playground/
2. Type: "111 222"
3. Place the cursor before the first "2"
4. Press the Bold button and type "aaa "
5. Press the Bold button and type "bbb "
6. Click undo several times.

After step 5 we have:
111 <b>aaa</b> bbb 222

After the first undo I'm getting:
111 <b>aaa</b> bbb22222

After the second undo I'm getting:
111 <b>aaa</b> 222
22
22
2

The result after undo depends on the browser.

Firefox 49 on Windows 7
Version: 1.0.6
