### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by ncammarata** [quilljs/quill#102]
Similar to 
````html
<input type="text" placeholder="Type here">
````

This seems very simple so there is definitely a chance I'm just missing it in the docs.

**Comment by radiart** [comment]
Any progress with that?

**Comment by amerikan** [comment]
Would be a nice feature to have.

**Comment by jhchen** [comment]
The beta release has a [placeholder configuration option](http://beta.quilljs.com/docs/configuration/#placeholder).

**Comment by brettimus** [comment]
:tada:
