### ISSUE TITLE
On mouse over editor, BOLD is highlighted always

### ISSUE THREAD

**Issue by idansh** [quilljs/quill#1022]
When I put the mouse over the area of the editor, the BOLD attribute for making a text in tags strong B is highlighted in blue, when I move the cursor out, it goes back to be black.

When I click a text in the editor, it automatically BOLD it. For some reason the mouse over on the editor acts like the cursor is always on the B and even when I click in the editor area not on the B button, the BOLD is initiated and operates on the text in the editor as well.

Version: 1.0.6
Chrome v53.0.2785.116
Windows 7

**Comment by idansh** [comment]
I tested it and it happens when the DIV of the editor is surrounded with label tags.

**Comment by benbro** [comment]
Can you reproduce in codepen?
http://quilljs.com/playground/
