### ISSUE TITLE
Calling formatText() sometimes leads to the format extending upon more text input

### ISSUE THREAD

**Issue by jc4p** [quilljs/quill#1023]
I'm really enjoying Quill, I've been messing around with adding some minor real time formatting to it. My first attempt is to automatically embolden text wrapped in asterisks, like: `*text*`.

A minimal version of my code is here: http://codepen.io/jc4p/pen/dpVgjA?editors=1010

I'm using `.on('text-change')` to continuously run the editor's contents through a simple regex which looks for `\*.+?\*`. I'm calling `.formatText(start, length, 'bold', true);` to format the text captured then immediately afterwards `.format('bold', false)` so this part of the API docs kicks in:

>  If the user’s selection length is 0, i.e. it is a cursor, the format will be set active, so the next character the user types will have that formatting.

This works for the most part, and without it any text typed after the second `*` extends to be bold (not what I want).

But (and here's the bug) when it's the beginning of the line of text, the bolding still extends.

**Steps for Reproduction**
1. Visit http://codepen.io/jc4p/pen/dpVgjA
2. In the Quill area, type `I am typing some *bold* text`.
3. Delete all the text. (Sometimes I've been able to repro by just hitting new line, sometimes not. Deleting everything always repros though)
4. Type `*bold* text`.

**Expected behavior**:
- In step 2, new input is plain after the `*bold*`.
- In step 4, new input is plain after the `*bold*`.

**Actual behavior**:

In step 4, text input after the `*bold*` is still formatted bold, even though `.format('bold', false)` has just been called.

Since it only happens when the formatted region begins on the line.. I think it's due to the "active" format per API docs looking backwards from the format that just ended, and yeah.

**Platforms**:

I'm testing on Chrome 53 using Debian 8.

**Version**:

1.0.6

**Comment by benbro** [comment]
You are using 1.0.0
Can you try with the recent 1.0.6 release?

I'm trying to reproduce with a simpler test:
http://codepen.io/anon/pen/dpVQGb

How is this different from what you are doing above?

**Comment by jc4p** [comment]
I have updated my codepen to use 1.0.6, the same issue occurs.

I believe the difference between my test and your test is the timing involved with inserting text manually in the Quill nodes vs key press events. Since this seems to be a timing related issue, I've put the contents of my `.on('text-change')` in a `.setTimeout({}, 1)` and it seems to work.

**Comment by jhchen** [comment]
The issue is sometimes during modification the selection is lost or displaced, so Quill saves and restores it. But this happens after the `text-change` event is fired. So the setTimeout is the correct workaround at the moment.

**Comment by jhchen** [comment]
I think the timeout should no longer be necessary in 1.1.1. Can you check and confirm?

**Comment by benbro** [comment]
Fixed for me in 1.1.3 with both Firefox 49 and Chrome 54.
