### ISSUE TITLE
Paragraph dispappears while removing words via Ctrl+Backspace and undo'ing

### ISSUE THREAD

**Issue by antonlabunets** [quilljs/quill#1028]
Paragraph worth of data disappears after 3 Ctrl + Backspace and 2 Ctrl + Z to undo the word removal.

**Steps for Reproduction**
1. Visit http://quilljs.com/playground
2. Copy the text non-column text blocks from http://lipsum.com/ [START with the header "The standard Lorem Ipsum passage, used since the 1500s" and END at "to avoid worse pains." before the help@limpsum.com block]
3. Use Ctrl + Backspace to remove 3 words ("Unable to get property 'mutations' of undefined or null reference" shows up in the console at _blot.update(blot.domNode[Registry.DATA_KEY].mutations || []);_). Then Ctrl + Z to undo 2 times (See "Unable to get property 'length' of undefined or null reference" now in the console on _keydown var curContext = { range..._)

**Expected behavior**: Words are re-added back one by one until we get back to full paragraph

**Actual behavior**: After 2nd redo, the whole paragraph disappears and "Cannot read property 'mutations' of undefined" throws at

**Platforms**: IE 11.0.9600.18450 windows 10, 8 or 2012 R2

Include browser, operating system and respective versions

**Version**: We see it on 1.0 final internally and 1.0.6 from playground

Run `Quill.version` to find out

**Comment by anindara** [comment]
This might help: Looks like when trying to update the underlying TextBlot with the mutations in its domNode, we are unable to find the Registry.DATA_KEY in this blot's domNode. Enclosed

![image](https://cloud.githubusercontent.com/assets/22333452/19168213/f7aac786-8bc3-11e6-90e2-9ffbba73c70f.png)

Now, ShadowBlot attaches the Registry.DATA_KEY to every Blot instance's domNode. So not sure why this is not available in this case?

**Comment by jhchen** [comment]
Fixed in Parchment 1.0.8.
