### ISSUE TITLE
Support tab and arrow key navigation through dropdowns

### ISSUE THREAD

**Issue by robomalo** [quilljs/quill#1031]
**Steps for Reproduction**
1. Visit http://quilljs.com/playground/
2. Attempt to use tab key to select a headline format or normal
3. The options are in `<span>` tags which cannot be focused

**Expected behavior**:
1. Tab into format selector for heading, normal, etc.
2. Hit enter or space bar
3. Use tabs or arrow keys to select formatting
4. Hit enter select formatting

**Actual behavior**:

Tabs pass over span tags because they cannot be focused

**Platforms**:

Everywhere

**Version**:

All versions

**Note**:

This actually failed our accessibility audit within LinkedIn for Slate

**Comment by scottsheffield** [comment]
If I'm remembering correctly, you guys are actually constructing the markup for the toolbar in Slate. Is that markup not usable if it doesn't use spans for the dropdown items, say if you switch to something focusable (button, whatever)?

**Comment by jhchen** [comment]
Not sure Slate's exact implementation but the default picker does create `<span>`s. The quick solution is to change the label `<span>` into a `<a>` but then the obvious next Issue report would be inability to down arrow and select.

**Comment by robomalo** [comment]
Anchors aren't totally semantically correct. Would it be possible to
control it with the actual select form item?

**Comment by jhchen** [comment]
What is? A button? I'd rather get it right then make it configurable so other people can get it wrong.

**Comment by robomalo** [comment]
Buttons would be correct in the presentation side but I was wondering if we
could do something with the actual select element already in the page.
Isn't there one?
On Tue, Oct 11, 2016 at 11:25 PM Jason Chen <notifications@github.com>
wrote:

What is? A button? I'd rather get it right then make it configurable so
other people can get it wrong.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/quilljs/quill/issues/1031#issuecomment-253129898>, or mute
the thread

**Comment by jhchen** [comment]
There is but the current state of HTML technology does not allow us to style `<select>` and `<option>`

**Comment by robomalo** [comment]
Oh, I know... I was thinking like positioning it off the page with CSS but
still have it in the markup to be controlled by tabs. But then that
wouldn't help with the focused elements on the screen. Seems like no
getting around the buttons maybe.
