### ISSUE TITLE
Cannot read property 'dangerouslyPasteHTML' of undefined

### ISSUE THREAD

**Issue by pavneet9** [quilljs/quill#1034]
I am trying to insert some HTML at a specific position in the quill editor.

```
`var fullEditor = new Quill('#m_wiki_textarea', {
              modules: {
                'toolbar': { container: '#toolbar' },
                 'image-tooltip': true,
                'link-tooltip': true
              },
              theme: 'snow'
            });
            fullEditor.setHTML(m_wiki_current);
           //added by pavneet
            console.log("added by pavneet");

          $(document).keypress("q",function(e) {
          if(e.ctrlKey)
         {
           var range = fullEditor.getSelection();
           var index = range.start;
                console.log(range);
            console.log(index);
 fullEditor.clipboard.dangerouslyPasteHTML(index,'&nbsp;<b>World</b>');
         }`
```

But i am getting this error , Cannot read property 'dangerouslyPasteHTML' of undefined. But i have defined fullEditor already

**Comment by benbro** [comment]
You have custom code in your example so it's hard to know where there problem is.

Here is a working codepen with clipboard..dangerouslyPasteHTML:
http://codepen.io/anon/pen/JRLpGY

**Comment by benbro** [comment]
Asked on [Stackoverflow](http://stackoverflow.com/questions/39949496/insert-a-link-in-a-specific-index-in-quill-editor/39950299#39950299) as well.
Please don't double post.
