### ISSUE TITLE
Add anchor links with specific class to the editor

### ISSUE THREAD

**Issue by pavneet9** [quilljs/quill#1035]
Is there any way of appending a anchor text such as "<a class="wiki_link_details" data-l_id="3698">Learn more from this resource</a>"

in the editor at a specific index

**Comment by benbro** [comment]
You can use [updateContents](http://quilljs.com/docs/api/#updatecontents)
example:
http://codepen.io/anon/pen/ORvQXQ

**Comment by pavneet9** [comment]
but can you add a class or data attribute to the anchor tag?

**Comment by benbro** [comment]
Please continue the discussion on [Stackoverflow](http://stackoverflow.com/questions/39949496/insert-a-link-in-a-specific-index-in-quill-editor/39950299?noredirect=1#comment67181064_39950299).
