### ISSUE TITLE
Clean up Quill.js instance from page

### ISSUE THREAD

**Issue by r24y** [quilljs/quill#1040]
Based on reading [core/quill.js](https://github.com/quilljs/quill/blob/develop/core/quill.js), it seems that there's no `.destroy()` method that releases resources, DOM elements, etc. From my understanding, this means one of two things: either

1. no cleanup is necessary, meaning when the `Quill` instance is no longer referred to, everything related to that instance is removed from the heap; or
2. some cleanup is necessary (i.e. if you create/destroy multiple Quill instances, the page will leak memory).

If (1) is true, it would be helpful to add to the documentation. If (2) is true, it would be helpful to add a `destroy()` (or similar) method to the Quill class.

**Comment by jhchen** [comment]
1 is intended to be true, as that is a language feature of Javascript. Are you seeing leaks somewhere?

**Comment by r24y** [comment]
No; I'm evaluating Quill for use in a project that would commonly see several Quill instances created and destroyed over the course of a user session. I suppose proper cleanup would be to drop all references to the `Quill` instance and remove the related containing element from the DOM (to clean up all the event handlers bound to DOM nodes).

By the way, Quill looks really slick, and I'm excited about using it 😄  I'm just making sure to do my due diligence before I commit to using it.

**Comment by jhchen** [comment]
Thanks. Yes Quill is not special with regards to cleanup. Just do what you would normally do to garbage collect anything else in Javascript, which is as you say remove references.
