### ISSUE TITLE
Quilljs depends on the document of the same page it was loaded

### ISSUE THREAD

**Issue by fernandogmar** [quilljs/quill#1042]
Hi,

I have noticed that the implementation of Quilljs (1.0.6) uses directly the instance document (window.document). So this means Quilljs uses the document of the page where it is loaded... what implies that it has to be loaded/executed in the same page.

It can not be executed from a different iframe.
It can not be loaded in an independent page just once and  used in different iframes.

Maybe this doesn t make too much sense for you... but the case is when you have templates that needs to be rendered and shown in an iframe (applying different styles)... it could be very handy just to have the javascript logic loaded just once.... allowing just to show the interactive template in the iframe.

It  would be awesome to have an option to indicate the document where it is going to be executed... ;) as you can do with bounds

Thanks in advance

**Comment by jhchen** [comment]
This is tough since Quill refers to document in a lot of places and Parchment does as well, so both libraries would have to accept this option. Why not just load Quill in the iframe? If caching is set up correctly there should be minimal/nonexistent performance burden.

**Comment by fernandogmar** [comment]
Hi @jhchen 

yes, we have that working that way on the iframes.... but I was trying to refactor and clean up the code... and this was one of the "annoying" points.

Anyway, please reconsider not having direct dependencies of window or document. Or dependencies of global variables in general ;) I think that would be a good practice and it will save some headaches later. It will make it a more robust flexible marvellous piece of code :smile:
