### ISSUE TITLE
Update documentation to reveal what browsers you support

### ISSUE THREAD

**Issue by twakjaco** [quilljs/quill#1048]
Buried in your issues tracker you say that you no longer support IE10.  ([https://github.com/quilljs/quill/issues/474]).  What you support and don't support should be front and center in your documentation so people don't waste their time.

**Comment by jhchen** [comment]
It is front and center on the README

**Comment by twakjaco** [comment]
README is frequently just change log.  Put it in the docs so it's discoverable by search engines.

**Comment by jhchen** [comment]
No the README.md file is a readme file. The CHANGELOG.md file is the changelog.

**Comment by kidfribble** [comment]
After first searching the documentation, then reading the [README](https://github.com/quilljs/quill/blob/develop/README.md), I am unable to find what the browser support is.

**Comment by jemhuntr** [comment]
@kidfribble Are you kidding?
![image](https://user-images.githubusercontent.com/6434778/38468271-04bd159c-3b76-11e8-9daf-6d829cb46ae4.png)

**Comment by HarshInvader** [comment]
IE does not show up at all anymore. Does this mean that IE 11 is also not supported now?
