### ISSUE TITLE
Quill overriding paragraph margin to zero, will result in empty paragraphs

### ISSUE THREAD

**Issue by bkno** [quilljs/quill#1058]
Hi,

I'm using version 1.0.6.

Just wondering what the reasoning is for Quill's CSS setting `p` margin and padding to zero - why not keep the site's existing styling?

By default this means someone is going to inadvertently insert a blank paragraph to visually separate the paragraphs, which then need to be detected and stripped out when showing content elsewhere. Alternatively we can fix this with CSS to re-add my site's margin-bottom: 15px but seems a bit messy to override your override with something already defined in the base styles.

Every other aspect has been great.

Kind regards,

Ben

**Comment by benbro** [comment]
Quill styles are scoped under .ql- namespace so they don't leak to other elements on your page . The margin and padding you are referring to are only applied to paragraphs under the .ql-editor CSS class.
You can either override the paragraph margin or create a custom Quill theme.
