### ISSUE TITLE
Generating externs

### ISSUE THREAD

**Issue by smogg** [quilljs/quill#1059]
I'm trying to generate externs (for example, using [this tool](https://github.com/jmmk/javascript-externs-generator)) but the generated output is missing all the API methods.
In addition, some parts are also not vali JavaScript (e.g. `Quill.imports.formats / list.prototype = { ...`)

Did someone run into similar issues and knows of a better tool/created externs manually?
I'm using file that can be found here to generate the externs: http://cdn.quilljs.com/1.1.0/quill.js, is there maybe a source code better suited for the purpose?

**Comment by benbro** [comment]
You can create a Closure Compiler extern file manually and add missing functions when you need them.
This is not complete and maybe not 100% correct but can be used as a starting point:

``` javascript
/**
 * @constructor
 * @param {string|Element} element
 * @param {Object} config
 */
var Quill = function(element, config) {};

/**
 * @param {string} module
 * @return {Object}
 */
Quill.import = function(module) {};

/**
 * @return {Quill.Delta}
 */
Quill.prototype.getContents = function() {};

/**
 * @param {Quill.Delta|Array} delta
 */
Quill.prototype.setContents = function(delta) {};

/**
 * @param {Quill.Delta} delta
 * @param {string=} source
 */
Quill.prototype.updateContents = function(delta, source) {};

/**
 * @constructor
 */
Quill.Op = function() {};

/** @type {number} */
Quill.Op.prototype.retain;

/**
 * @constructor
 * @param {Array} ops
 */
Quill.Delta = function(ops) {};

/** @type {Array.<Object>} */
Quill.Delta.prototype.ops;

/**
 * @param {Quill.Delta} delta
 * @return {Quill.Delta}
 */
Quill.Delta.prototype.compose = function(delta) {};
```

**Comment by smogg** [comment]
I'm working on a PR for cljsjs and I need a 100% coverage in  the extern. Does that mean manual labor is the only way to go at this point?

**Comment by benbro** [comment]
You'll probably want to ask about externs generation on the Closure Compiler or cljsjs mailing list.

[Quill's API](http://quilljs.com/docs/api/) isn't too large so you should be able to generate extern manually.
You'll might want to add the [Delta API](https://github.com/quilljs/delta)
If you are going to extend Quill, you'll also need the [Parchment API](https://github.com/quilljs/parchment)

**Comment by smogg** [comment]
I'll write the externs manually then. Thanks for the tips. Unless someone has something else to add, I think this can be closed
