### ISSUE TITLE
Bubble toolbar doesn't appear on selecting the last line when the vertical scrollbar is shown

### ISSUE THREAD

**Issue by fuffalist** [quilljs/quill#1060]
Bubble toolbar doesn't appear on selecting the last line when the vertical scrollbar is shown.

**Steps for Reproduction**

1. Visit quilljs.com
2. Swipe left to go to the first bullet (bubble theme)
3. Insert some dummy text until the vertical scrollbar on the right appears (about 19 rows)
4. Selecting some row but last the bubble toolbar appears correctly
5 Selecting the last row, the bubble toolbar is not visible (it's hidden below the text, out of the scrolling area)

**Expected behavior**:
The bubble toolbar should appear also selecting the last line.

**Actual behavior**:
The bubble toolbar is not visible when selecting the last line

**Platforms**:
Windows, Mac

Include browser, operating system and respective versions
IE11, Chrome 54, Firefox 49

**Version**:
Quill 1.1.0 on online demo

**Comment by mastito03** [comment]
> Platforms:
> Windows, Mac

actualy it happen on ubuntu too

**Comment by zangab** [comment]
struggled the same prob - quickfix would be a "padding-bottom" of at least 50px on the "ql-editor" class

**Comment by jhchen** [comment]
I'll go with the quick fix for now but #851 and the associated PR is related.
