### ISSUE TITLE
1.1.0 rises error on insertEmbed() usage like in Medium example

### ISSUE THREAD

**Issue by artaommahe** [quilljs/quill#1064]
Quill 1.1.0 rises error on insertEmbed() usage like in Medium editor [example](http://codepen.io/quill/pen/qNJrYB?editors=0110)
```js
  let range = quill.getSelection(true);
  quill.insertEmbed(range.index, 'image', {
    alt: 'Quill Cloud',
    url: 'http://quilljs.com/0.20/assets/images/cloud.png'
  }, Quill.sources.USER);
```

1. Visit example page http://codepen.io/quill/pen/qNJrYB?editors=0110
2. Change used Quill version in settings to 1.1.0 (//cdn.quilljs.com/1.1.0/quill.core.js)
3. Press run to update
4. Open console
5. Add new empty line and click add image action
6. See error
```
Uncaught TypeError: Cannot read property 'position' of null
```

**Expected behavior**:
no error

**Actual behavior**:
error

**Platforms**:

Chromium version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Version**:

1.1.0

**Comment by jhchen** [comment]
This is fixed in v1.1.1
