### ISSUE TITLE
Pasting doesn't work well with formatted text

### ISSUE THREAD

**Issue by hallaathrad** [quilljs/quill#1066]
Whenever we try to paste any formatted text (html, not just raw text), it's only showing an empty `<p>` element, but no sign of the content to be pasted.
It sometimes works if you use the contextual menu's paste option, rather than +V. 
But it's sort of hit or miss.

Getting these errors:
![screen shot 2016-10-21 at 11 41 41](https://cloud.githubusercontent.com/assets/2107110/19605596/57d682aa-9789-11e6-8b6e-30ee4210bf07.png)

Also, the field (user bio, in this case) somehow does detect the insertion, as seen in this character counter (which before the pasting would say 0/5000, and was properly positioned underneath the editor's border).
![screen shot 2016-10-21 at 12 25 30](https://cloud.githubusercontent.com/assets/2107110/19605631/c27ab630-9789-11e6-8da8-6ac8f56dd72d.png)
If it helps, the number displayed accounts also for the html elements themselves i.e. raw html.

**Expected behaviour**:
Text should appear as it was copied (either from the same quill editor or an external source)

**Actual behaviour**:
Blank/empty paragraph is created instead 

**Platforms**:
MacOS 10.12.1
Chrome 54.0.2840.59 (64-bit)
Safari 10.0.1

**Version**:
1.1.1

**Comment by benbro** [comment]
What exactly are you trying to paste? Please add it here as HTML string.
Can you reproduce on the [playground](http://quilljs.com/playground/)?

**Comment by hallaathrad** [comment]
Hmm interesting! I didn't think of checking in the playground before posting and it seems to work fine. It must be some secondary effect of another component. Odd. Thank you, @benbro 👍

**Comment by mrcasals** [comment]
@caravinci I'm having the same issue, but I can't reproduce it in the playground... I know it's old, but do you happen to remember what caused it on your side?

Thanks!

**Comment by buruguduys** [comment]
@caravinci @mrcasals am having the issue and I cant seems to find the cause. Do you guys have any idea?

Thank you
