### ISSUE TITLE
[Regression in 1.1.1] Uncaught TypeError: Cannot read property '0' of undefined(…) when using backspace to remove a character

### ISSUE THREAD

**Issue by eamodio** [quilljs/quill#1067]
Since I've updated to 1.1.1 I get this error: (1.1.0 was fine)

```
quill.js:2890 Uncaught TypeError: Cannot read property '0' of undefined(…)
fix_cursor @ quill.js:2890
diff_main @ quill.js:2531
Delta.diff @ quill.js:2397
(anonymous function) @ quill.js:3549update @ quill.js:3558
(anonymous function) @ quill.js:1702modify @ quill.js:2083
(anonymous function) @ quill.js:1701
emit @ quill.js:4913emit @ quill.js:4801
update @ quill.js:6043
(anonymous function) @ quill.js:1141
```

**Steps for Reproduction**

1. Enter some text
2. Hit `backspace` to delete the text
3. Observe the error :)

**Expected behavior**:
No error

**Actual behavior**:
Error

**Platforms**:
macOS Sierra, Chrome Version 54.0.2840.71 (64-bit)

**Version**:
1.1.1

**Comment by benbro** [comment]
Caused by this PR:
https://github.com/jhchen/fast-diff/pull/2
