### ISSUE TITLE
Move the "modules" into their own repos?

### ISSUE THREAD

**Issue by TooTallNate** [quilljs/quill#107]
I think it would make sense to move out the "modules" into their own repositories under the [quilljs](https://github.com/quilljs) organization. This would help us be more… modular, haha.

**Comment by butsjoh** [comment]
+1

**Comment by jhchen** [comment]
There is an standardized API for adding new modules in 1.0 but organizationally Quill will follow the examples set by React, Babel and others and keep all officially supported code in one repository, including modules.
