### ISSUE TITLE
bubble toolbars not show when readOnly: true

### ISSUE THREAD

**Issue by mastito03** [quilljs/quill#1072]
when using snow themes, toolbars is showing when quill in readOnly. but bubble toolbars not.
i think readOnly mean user input is disable but not API. 

i need this as I make custom toolbar that can insert comment on certain part of post. I cant use snow themes as it look like post is editable but it isn't.

**Steps for Reproduction**

1. visit  http://codepen.io/anon/pen/wzNQKw
2. try interact with toolbars
3. change theme to bublle
3. try interact again

**Expected behavior**:

toolbars is showing when text selected

**Actual behavior**:

toolbar not showing

**Comment by jhchen** [comment]
Tooltips are meant to be hidden. You can overwrite this with CSS:

```css
#editor-container.ql-disabled .ql-tooltip {
  visibility: inherit;
}
```
