### ISSUE TITLE
Adding a new link fails

### ISSUE THREAD

**Issue by metsavir** [quilljs/quill#1073]
When a link is added right after checking some other link's URL, checked link is updated. Adding a new link fails.

**Steps for Reproduction**

1. Visit http://quilljs.com/playground/ (add `'link'` to the toolbar)
2. Write `link1 link2`
3. Select `link1` text, click the link button in the toolbar, save
4. Click `link1` text to see the URL
5. Select `link2` text, click the link button in the toolbar, save

**Expected behavior**:

`link2` should be a link to URL `link2`.

**Actual behavior**:

`link2` isn't a link. `link1`'s URL is now `link2`.

**Platforms**:

Google Chrome 53.0.2785.143 (64-bit), OS X El Capitan

**Version**:

v1.0.6

**Comment by benbro** [comment]
I can reproduce. 
Step 4 is the important step. A new link is ignored after viewing a link.
http://codepen.io/anon/pen/BLrEZY

v1.1.2
