### ISSUE TITLE
Markup stripped when initialized on an element before insertion

### ISSUE THREAD

**Issue by leppert** [quilljs/quill#1075]
### Tags stripped when initialized before insertion

https://jsfiddle.net/uwku530y/
### Correct rendering when initialized after insertion

https://jsfiddle.net/t4rpkbh0/1/

**Comment by benbro** [comment]
Please provide the requested info like Browser, OS and Quill version.
What do you mean by markup stripped?
In Firefox both examples look the same.
In Chrome the first example is only missing a new line between Foo and Bar.

What's your use case for initializing an editor in an element not attached to the DOM?

**Comment by leppert** [comment]
@benbro Tested in Chrome `54.0.2840.71` and Safari `10.0 (12602.1.50.0.8)`; Firefox does work as expected. It's stripping a paragraph in the example above. Here's a more pronounced one:
https://jsfiddle.net/uwku530y/1/

**Comment by benbro** [comment]
What is the use case?

**Comment by kylebragger** [comment]
@benbro Hi, I'm working with @leppert on this. Our use case is that Exposure.co is replacing its current editor with Quill, and being that we are a somewhat complex Backbone app, the Quill instances are instantiated before Backbone finally inserts rendered templates into the DOM. 

And to his examples, if you inspect their markup, the original <p> tags are stripped out in the example where the parent element is not yet attached to the DOM.

**Comment by jhchen** [comment]
Using the DOM API to make arbitrary changes to Quill is not supported. HTML is far too ambitious and inconsistent for this to be reasonably achievable. Quill favors consistency instead, and has its own set of APIs that guarantee this. You can either initialize Quill after you have made your arbitrary DOM changes, or use one of its Quill's APIs if it is already initialized. `pasteHTML` may be of interest here.

**Comment by kylebragger** [comment]
Hi @jhchen, the element passed to Quill's constructor isn't modified after being turned into an editor instance, but rather already in its final form (i.e. populated with the content we want to be editable) by the time it's passed to Quill. Nor are we in any way using DOM APIs to make changes to Quill's generated markup. The only difference is that elements not yet attached to the DOM (which would be the only modification we're talking about) seem to trigger this bug. When the element is attached to the DOM (unmodified) shouldn't, at least to me, have an impact on how its content is sanitized/handled by Quill. That was the gist of why we thought this was worth reporting.

**Comment by jhchen** [comment]
My mistake. I thought you were inserting a node into Quill but actually the node is the Quill container. The issue is before a node is in the document, no rendering or related calculations are done the paragraphs appear to be on the same line and only until it is added into the actual document are these values updated.

Can you just insert the contents with pasteHTML or initialize the Quill instance after everything is ready?

**Comment by kylebragger** [comment]
No worries. We managed to refactor enough of our Backbone code to get it working. Should have it deployed in the next week after testing is complete. And makes sense re: calculations. Thanks!

**Comment by buffpojken** [comment]
Thank you, @leppert for those jsfiddles - I thought I was going crazy with the same editor, with the same code, with the same plugins rendering the exact html-string differently on two different pages in a non-deterministic way - subtle race condition in the order of init events was to blame. 

Many thanks!
