### ISSUE TITLE
Windows 10 Edge, backspacing to beginning of line makes text re-appear

### ISSUE THREAD

**Issue by peterweck** [quilljs/quill#1078]
This is a Microsoft Edge only issue. I'm not seeing this problem with IE 11. I also did not see the problem in the 1.0 version of Quill. 

**Steps for Reproduction**
1. Visit: https://jsfiddle.net/zgk7qkrp/
2. Click into the text box to put the cursor at the end of the first line (after the '!').
3. Press backspace until all of the text has been deleted. When you delete the first 'H' character, the text "ello World!" reappears.

**Expected behavior**:

The 'H' should be deleted and no text should re-appear

**Actual behavior**:

The text "ello World!" appears when the 'H' is deleted. I also see the following error message in the console when I load the Fiddle:

SCRIPT5022: e: [Parchment] Unable to create [object Text] blot
quill.min.js (7,12417)

**Platforms**:

Windows 10 Home, Version 1607, OS Build: 14393.321
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

**Version**:  1.1.3

**Comment by benbro** [comment]
I can reproduce on version 1.1.3 but also on 1.0.0.
@peterweck you can check with this codepen that you are getting the same error with 1.0.0
http://codepen.io/anon/pen/jrRBGL

**Comment by peterweck** [comment]
@benbro, I now get the same behavior in 1.0.0 and I can reproduce it in the codepen link you sent. Between the 1.1.3 release and the 1.0.0 release, I installed the windows update which also updated Edge. Maybe that caused it to break.

**Comment by jhchen** [comment]
Are you two still getting the issue? I'm not seeing it on either the fiddle or codepen but do have the latest Windows updates.

**Comment by benbro** [comment]
I can still reproduce.
[Screencast](https://drive.google.com/open?id=0B12AhxvnYHrAZEhwMHRfVWRXYzA) of the bug
Tested with [Edge 14.14393](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and Quill 1.1.3

**Comment by oliverw** [comment]
I can confirm this using the latest version of both Quill and Edge (Anniversary Update).

Unfortunately I can only tell you where it happens:

Its the following line in <code>TextBlot.split</code>:

`this.domNode.splitText(index))`

For some reason splitText() returns a Node for which the following check returns false:

```
else if (query instanceof Text) {
 match = types['text'];
}
```
