### ISSUE TITLE
Trouble when using quill with gulp-inject

### ISSUE THREAD

**Issue by thomas-leroy** [quilljs/quill#1079]
I have trouble with quilljs when when updating from 0.20.1 to 1.x.

My project use _gulp-inject_ to push sources to my index file.

After upgrading (with bower) from 0.20.1 to 1.1.3 (or every other 1.x version) the bower_components/quill/quill.js file is not included anymore in my index.html file by gulp-inject.

**Expected behavior**:
I'd wish to have quill injected like other bower components.

**Actual behavior**:
I have to had `"main": "quill.js"` to the bower_components/quill/.bower.json

**Platforms**:
Ubuntu 14.04 LTS

**Version**:
0.20.1 to 1.X
gulp  3.9.1
gulp-inject 4.1.0

**The working .bower.json file**
Based on : https://github.com/bower/spec/blob/master/json.md#main
`{
  "name": "quill",
  "homepage": "https://github.com/quilljs/quill",
  "version": "1.0.0",
  "_release": "1.0.0",
  "main": "quill.js",
  "_resolution": {
    "type": "version",
    "tag": "v1.0.0",
    "commit": "556a5c1bc58e4dd6f61a1eb9706dcc81c17ae01b"
  },
  "_source": "https://github.com/quilljs/quill.git",
  "_target": "1.0.0",
  "_originalSource": "quill"
}`

**Comment by jhchen** [comment]
If Quill is doing something wrong in being a bad citizen in the NPM ecosystem, please say how. Otherwise this does not seem to be a Quill specific issue.
