### ISSUE TITLE
Customize Delta item

### ISSUE THREAD

**Issue by AaricChen** [quilljs/quill#1080]
it's very powerful and nice tool that I have been used.

one more thing need you help.

it is possible to customize delta when we use setContents method ?

e.g.
how can we add some class attribute in the <img> element ?

could you please proposal some solution for me, thanks

**Comment by benbro** [comment]
Delta docs:
http://quilljs.com/docs/delta/
https://github.com/quilljs/delta

You can use the delete insert and retain methods to customize a delta.
For example, to add a color attribute to the first 5 characters:
```javascript
delta.retain(5, { color: '#0c6' });
```
