### ISSUE TITLE
Quill cannot be unfocused with left click

### ISSUE THREAD

**Issue by abelousov** [quilljs/quill#1085]
After being focused, quill doesn't let any outer element to be focused by left click

**Steps for Reproduction**
1. Visit [this pen](http://codepen.io/abelousov/pen/XjwqBq) (or open Quill playground and add a text input below Quill)
2. Click on Quill to make it focused
3. Left click on input below

**Expected behavior**:
Input gets focused

**Actual behavior**:
Quill stays focused

**Platforms**:
Chrome 54 on Mac OS X

**Version**:
1.1.3 (current)

**Additional info**
back focus is caused by [Selection.js#52](https://github.com/quilljs/quill/blob/develop/core/selection.js#L52)

**Comment by jhchen** [comment]
I'm not able to reproduce. The selection.js only occurs when Quill's content changes, which does not occur in any steps for reproduction. Was a step missed?

![quill](https://cloud.githubusercontent.com/assets/192974/19872505/5b38608a-9f77-11e6-991b-016087e33d8e.gif)

**Comment by abelousov** [comment]
My bad - the issue is caused by [Lazarus](https://chrome.google.com/webstore/detail/lazarus-form-recovery/loljledaigphbcpfhfmgopdkppkifgno) chrome extension - it looks like I didn't check it with extensions disabled

**Comment by benbro** [comment]
Thanks for the update.
