### ISSUE TITLE
Feature request: Toggle HTML mode in editor

### ISSUE THREAD

**Issue by pixelbandito** [quilljs/quill#1086]
Our users are composing HTML emails, and right now we're just giving them textareas.

I'd like to use Quill, but sometimes our users have pre-existing email templates they need to paste in, attributes included (style tags and such, for browser compatibility).

Is there a way to achieve that with Quill? I noticed I can copy/paste rendered HTML content, but a clean "Edit source" view would sure be handy. Even if it did some sanitizing of the pasted / typed code, it would be a big step forward.

**Comment by benbro** [comment]
Previous discussion about HTML mode:
https://github.com/quilljs/quill/issues/128#issuecomment-215263950
