### ISSUE TITLE
Save and restore state from HTML

### ISSUE THREAD

**Issue by aletorrado** [quilljs/quill#1088]
Hi, I cannot find how it's supposed to do this. I don't want to persist to Delta at the moment. Thanks

**Comment by benbro** [comment]
Previous discussion:
https://github.com/quilljs/quill/issues/903#issuecomment-243844178

**Comment by jhchen** [comment]
As stated in the linked comment you can get the HTML with `quill.root.innerHTML` or `document.querySelector(".ql-editor").innerHTML` and to set it you can either have it already in the container before passing the container into Quill (like in the [Quickstart](http://quilljs.com/docs/quickstart/#quickstart)) or use [`quill.clipboard.dangerouslyPasteHTML`](http://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml).

**Comment by ramsuthar305** [comment]
I want to store the`quill.root.innerHTML` in my database how can I do it??
