### ISSUE TITLE
Auto format links (on type and paste)

### ISSUE THREAD

**Issue by ncammarata** [quilljs/quill#109]
If I paste http://google.com into a Quill editor, it would be nice if it would (perhaps optionally) create a link out of it.

**Comment by MrShaneH** [comment]
Hi,
Was this request was ever developed, either in the core code or as a custom module?

Thanks

**Comment by jhchen** [comment]
No I think this is still an open request.

**Comment by jhchen** [comment]
You can add a [custom matcher](http://beta.quilljs.com/docs/modules/clipboard/) for this behavior in 1.0. One of the [unit tests](https://github.com/quilljs/quill/blob/develop/test/unit/modules/clipboard.js#L114) is a useful example for this but of course you might want different logic or regex to determine what a link is.

**Comment by jhaddow** [comment]
The custom matcher works for pasting. What's the solution for typing a link?

**Comment by weavermedia** [comment]
@jhaddow Do you have a working example of a custom matcher for pasting? I'm struggling to get it working.

@jhchen +1 for having this functionality in the core.

**Comment by weavermedia** [comment]
Got a custom matcher working. Documenting it here in case it's helpful to anyone else:

```
quill_editor.clipboard.addMatcher(Node.TEXT_NODE, function(node, delta) {
  var regex = /https?:\/\/[^\s]+/g;
  if (regex.exec(node.data) != null) {
    delta.ops = [{ insert: node.data, attributes: { link: node.data }}];
  }
  return delta;
});
```

Note: this is a very minimal implementation (reduced down from the [test case](https://github.com/quilljs/quill/blob/develop/test/unit/modules/clipboard.js#L114) linked above) that just solves my use-case. I'm only dealing with single links pasted in and just returning the whole pasted value as a clickable link.

Beware that it overwrites any other `ops` in `delta`. This may or may not work for you.

**Comment by schneidmaster** [comment]
I'm not sure why this issue is closed -- you can use a matcher to autolink pasted URLs but that doesn't help with autolinking while the user is typing. If it helps anyone else, I wrote code to handle both cases.

For pasting, the matcher above got me on the right track but didn't work for pasting more than just an URL, e.g. `this is https://www.google.com a string with an URL`. I changed it to:

```javascript
quill.clipboard.addMatcher(Node.TEXT_NODE, function(node, delta) {
  var regex = /https?:\/\/[^\s]+/g;
  if(typeof(node.data) !== 'string') return;
  var matches = node.data.match(regex);

  if(matches.length > 0) {
    var ops = [];
    var str = node.data;
    matches.forEach(function(match) {
      var split = str.split(match);
      var beforeLink = split.shift();
      ops.push({ insert: beforeLink });
      ops.push({ insert: match, attributes: { link: match } });
      str = split.join(match);
    });
    delta.ops = ops;
  }

  return delta;
});
```

And for typing, I wrote this:

```javascript
// Autolink URLs when typing
quill.on('text-change', function(delta, oldDelta, source) {
  var regex = /https?:\/\/[^\s]+$/;
  if(delta.ops.length === 2 && delta.ops[0].retain && isWhitespace(delta.ops[1].insert)) {
    var endRetain = delta.ops[0].retain;
    var text = quill.getText().substr(0, endRetain);
    var match = text.match(regex);

    if(match !== null) {
      var url = match[0];

      var ops = [];
      if(endRetain > url.length) {
        ops.push({ retain: endRetain - url.length });
      }

      ops = ops.concat([
        { delete: url.length },
        { insert: url, attributes: { link: url } }
      ]);

      quill.updateContents({
        ops: ops
      });
    }
  }
});
```

I haven't tested super extensively but that seems to do the trick.

**Comment by Masum06** [comment]
@schneidmaster Thanks for the code. The pasting code is working perfectly, but I couldn't make it work while typing. Could you please look into that?

**Comment by schneidmaster** [comment]
@Masum06 My code is working fine for me, both when typing a link and when pasting multiple times.

I'd suggest making sure you're using a recent version of quill (I'm on 1.1.3) but I posted the code as a general favor to folks trying to solve this problem; I'm not going to debug your specific setup & use case.

**Comment by chuckh** [comment]
@schneidmaster thanks for sharing the code! I got it to work.  The Autolink URLs when typing did not work at first because `isWhitespace` function was not include.  I added the below isWhitespace function then it worked fine.  @schneidmaster you might give this a try.

```
function isWhitespace(ch) {
  var whiteSpace = false
  if ((ch == ' ') || (ch == '\t') || (ch == '\n')) {
    whiteSpace = true;
  }
  return whiteSpace;
},
```

**Comment by schneidmaster** [comment]
Oh yeah, I imported `isWhitespace` from the `is-whitespace` npm package (e.g. `import isWhitespace from 'is-whitespace'` at the top of the file where you're configuring quill).

**Comment by Igor912** [comment]
thank you @schneidmaster!
Good job!

**Comment by ilvalerione** [comment]
Recognition works well, Is it possible to add target="_blank" property during node creation?
 I tried adding target attribute here

`{ insert: url, attributes: { link: url , target: '_blank'} }`

but it doesn't work.

Do you know how to achive this?
Thanks

**Comment by kilgarenone** [comment]
Inspired by @schneidmaster, this is how i fixed it in the keyboard module instead for the converting link when typing functionality:

```javascript
spaceToLink: {
    collapsed: true,
    key: ' ',
    prefix: /https?:\/\/[^\s]+/,
    handler: (() => {
      let prevOffset = 0;
      return function (range, context) {
        let url;
        const regex = /https?:\/\/[^\s]+/g;
        const text = this.quill.getText(prevOffset, range.index);
        const match = text.match(regex);
        if (match === null) {
          prevOffset = range.index;
          return true;
        }
        if (match.length > 1) {
          url = match[match.length - 1];
        } else {
          url = match[0];
        }
        const ops = [];
        ops.push({ retain: range.index - url.length });
        ops.push({ delete: url.length });
        ops.push({ insert: url, attributes: { link: url } });
        this.quill.updateContents({ ops });
        prevOffset = range.index;
        return true;
      }
    })()
  }
```

**Comment by shyamal890** [comment]
Can anybody please share a working plunker here..

**Comment by shyamal890** [comment]
This should be an inbuilt feature with help of a library like autolinker.js

**Comment by n1ghtmare** [comment]
@kilgarenone How do you use this snipped, I'm a bit lost?

**Comment by kilgarenone** [comment]
Hi @n1ghtmare, it's been awhile since I worked with quilljs, but you could have a look how I did it here https://github.com/kilgarenone/haven/blob/master/src/app/shared/editor/modules/keyboard.ts
Hope that helped!

**Comment by n1ghtmare** [comment]
@kilgarenone Thanks, I appreciate the response. Sorry to bump such an old thread. Will try to figure it out from the code in the link.

**Comment by hsource** [comment]
I mostly used @kilgarenone's version, but had some minor simplifications. Here's my code (in Typescript - simply remove the type hints to use it in vanilla JS)

```
  quill.keyboard.addBinding({
    collapsed: true,
    key: ' ',
    prefix: /https?:\/\/[^\s]+/,
    handler: (range: RangeStatic, context: { prefix: string }) => {
      const prefixMatch = context.prefix.match(/https?:\/\/[^\s]+$/);
      if (prefixMatch === null) return true;
      const prefixLength = prefixMatch[0].length;
      const prefixStart = range.index - prefixLength;
      const url = quill.getText(prefixStart, prefixLength);

      const ops: DeltaOperation[] = [];
      if (prefixStart > 0) {
        ops.push({ retain: prefixStart });
      }
      ops.push({ delete: prefixLength });
      ops.push({ insert: url, attributes: { link: url } });
      quill.updateContents(new Delta(ops) as any);
      return true;
    },
  });
```

**Comment by hsource** [comment]
For pasting, I also used @schneidmaster 's code. I cleaned it up to accept more than 1 URL pattern. Here it is!

```TypeScript
function createUrlKeyboardHandler(urlRegexp: RegExp, quill: Quill) {
  return (range: RangeStatic, context: { prefix: string }) => {
    const prefixMatch = context.prefix.match(urlRegexp);
    if (prefixMatch === null) return true;
    const prefixLength = prefixMatch[0].length;
    const prefixStart = range.index - prefixLength;
    const url = quill.getText(prefixStart, prefixLength);
    quill.formatText(prefixStart, prefixLength, { link: url }, 'user');
    return true;
  };
}
```

```TypeScript
  // Put the below somewhere with access to Quill
  const urlPatterns = [/https?:\/\/[^\s]+/, /www\.[^\s]+/];

  // Typing space after a URL matching these formats will turn it into a link
  for (const baseUrlPattern of urlPatterns) {
    const urlPattern = new RegExp(`${baseUrlPattern.source}$`);
    quillKeyboard.addBinding({
      collapsed: true,
      key: ' ',
      prefix: urlPattern,
      handler: createUrlKeyboardHandler(urlPattern, quill),
    });
  }

  // Pasting URLs adds a link
  quill.clipboard.addMatcher(Node.TEXT_NODE, (node: Text, delta) => {
    const combinedPattern = urlPatterns
      .map(pattern => `(${pattern.source})`)
      .join('|');
    const combinedRegexp = new RegExp(combinedPattern, 'g');

    const ops: DeltaOperation[] = [];
    const str = node.data;
    let lastMatchEndIndex = 0;
    let match: RegExpExecArray | null = combinedRegexp.exec(str);
    while (match !== null) {
      if (match.index > lastMatchEndIndex) {
        ops.push({ insert: str.slice(lastMatchEndIndex, match.index) });
      }
      ops.push({ insert: match[0], attributes: { link: match[0] } });
      lastMatchEndIndex = match.index + match[0].length;
      match = combinedRegexp.exec(str);
    }

    if (lastMatchEndIndex < str.length) {
      ops.push({ insert: str.slice(lastMatchEndIndex) });
    }

    delta.ops = ops;
    return delta;
  });
```

**Comment by jhoughjr** [comment]
2020 here, links still broken. Documentation is unclear as to what the latest version is.
Is the project even still maintained?

**Comment by cmditch** [comment]
@jhoughjr 
Check this out https://github.com/visualjerk/quill-magic-url

**Comment by mijnnaamisramon** [comment]
Eventhough magic url works nicely... it doesn't offer a callback... which would be a great help ;)

**Comment by namvhvnist** [comment]
this is my code:

let insert = null;
if (e && e.ops && e.ops.length !== 0) {
    e.ops.map(item => {
        if (item?.insert && !item?.attributes) {
            insert = item?.insert
        }
    })
}

// Insert URL tự động
if (insert === " ") {   // Bắt sự kiện gõ dấu cách
    let text, temp = selection - 2;
    while (temp >= 0) {
        text = quill.getText(temp, 1);
        if (text?.toString() === " ") {
            break;
        } else {
            temp--;
        }
    }

    text = quill.getText(temp + 1, selection - temp - 2);
    if (text?.startsWith("http://") || text?.startsWith("https://") && (text !== "https://") && (text !== "http://")) {
        quill.deleteText(temp + 1, selection - temp - 2);
        quill.insertText(temp + 1, text, 'link', text);
    }
} else if (insert && insert.length > 1) {   // Bắt sự kiện paste text to quill
    if (insert?.startsWith("http://") || insert?.startsWith("https://") && (insert !== "https://") && (insert !== "http://")) {
        quill.deleteText(selection, insert.length);
        quill.insertText(selection, insert, 'link', insert);
    }
}

**Comment by namvhvnist** [comment]
`let insert = null;
                    if (e && e.ops && e.ops.length !== 0) {
                        e.ops.map(item => {
                            if (item?.insert && !item?.attributes) {
                                insert = item?.insert
                            }
                        })
                    }
                    
                    // Insert URL tự động
                    if (insert === " ") {   // Bắt sự kiện gõ dấu cách
                        let text, temp = selection - 2;
                        while (temp >= 0) {
                            text = quill.getText(temp, 1);
                            if (text?.toString() === " ") {
                                break;
                            } else {
                                temp--;
                            }
                        }

                        text = quill.getText(temp + 1, selection - temp - 2);
                        if (text?.startsWith("http://") || text?.startsWith("https://") && (text !== "https://") && (text !== "http://")) {
                            quill.deleteText(temp + 1, selection - temp - 2);
                            quill.insertText(temp + 1, text, 'link', text);
                        }
                    } else if (insert && insert.length > 1) {   // Bắt sự kiện paste text to quill
                        if (insert?.startsWith("http://") || insert?.startsWith("https://") && (insert !== "https://") && (insert !== "http://")) {
                            quill.deleteText(selection, insert.length);
                            quill.insertText(selection, insert, 'link', insert);
                        }
                    }
                    `

**Comment by namvhvnist** [comment]
`// Auto Insert URL 
    let insert = null;
    if (e && e.ops && e.ops.length !== 0) {
        e.ops.map(item => {
            if (item?.insert && !item?.attributes) {
                insert = item?.insert
            }
        })
    }
                    
      if (insert === " ") {   // Handle event type space
          let text, temp = selection - 2;
          while (temp >= 0) {
              text = quill.getText(temp, 1);
              if (text?.toString() === " ") {
                  break;
              } else {
                  temp--;
              }
          }

          text = quill.getText(temp + 1, selection - temp - 2);
          if (text?.startsWith("http://") || text?.startsWith("https://") && (text !== "https://") && (text !== "http://")) {
              quill.deleteText(temp + 1, selection - temp - 2);
              quill.insertText(temp + 1, text, 'link', text);
          }
      } else if (insert && insert.length > 1) {   // Handle event paste
          if (insert?.startsWith("http://") || insert?.startsWith("https://") && (insert !== "https://") && (insert !== "http://")) {
              quill.deleteText(selection, insert.length);
              quill.insertText(selection, insert, 'link', insert);
          }
      }`

**Comment by namvhvnist** [comment]
`// Auto Insert URL 
    let insert = null;
    if (e && e.ops && e.ops.length !== 0) {
        e.ops.map(item => {
            if (item?.insert && !item?.attributes) {
                insert = item?.insert
            }
        })
    }`

` if (insert === " ") {   // Handle event type space
    let text, temp = selection - 2;
    while (temp >= 0) {
        text = quill.getText(temp, 1);
        if (text?.toString() === " ") {
            break;
        } else {
            temp--;
        }
    }

    text = quill.getText(temp + 1, selection - temp - 2);
    if (text?.startsWith("http://") || text?.startsWith("https://") && (text !== "https://") && (text !== "http://")) {
        quill.deleteText(temp + 1, selection - temp - 2);
        quill.insertText(temp + 1, text, 'link', text);
    }
} else if (insert && insert.length > 1) {   // Handle event paste
    if (insert?.startsWith("http://") || insert?.startsWith("https://") && (insert !== "https://") && (insert !== "http://")) {
        quill.deleteText(selection, insert.length);
        quill.insertText(selection, insert, 'link', insert);
    }
}`

**Comment by namvhvnist** [comment]
`// Auto Insert URL 
        let insert = null;
        if (e && e.ops && e.ops.length !== 0) {
            e.ops.map(item => {
                if (item?.insert && !item?.attributes) {
                    insert = item?.insert
                }
            })
        }`

` if (insert === " ") {   // Handle event type space
      let text, temp = selection - 2;
      while (temp >= 0) {
          text = quill.getText(temp, 1);
          if (text?.toString() === " ") {
              break;
          } else {
              temp--;
          }
      }

      text = quill.getText(temp + 1, selection - temp - 2);
      if (text?.startsWith("http://") || text?.startsWith("https://") && (text !== "https://") && (text !== "http://")) {
          quill.deleteText(temp + 1, selection - temp - 2);
          quill.insertText(temp + 1, text, 'link', text);
      }
  } else if (insert && insert.length > 1) {   // Handle event paste
      if (insert?.startsWith("http://") || insert?.startsWith("https://") && (insert !== "https://") && (insert !== "http://")) {
          quill.deleteText(selection, insert.length);
          quill.insertText(selection, insert, 'link', insert);
      }
  }`

**Comment by namvhvnist** [comment]
` // Auto Insert URL 
                    let insert = null;
                    if (e && e.ops && e.ops.length !== 0) {
                        e.ops.map(item => {
                            if (item?.insert && !item?.attributes) {
                                insert = item?.insert
                            }
                        })
                    }
                    
                    if (insert === " ") {   // Handle event type space
                        let text, temp = selection - 2;
                        while (temp >= 0) {
                            text = quill.getText(temp, 1);
                            if (text?.toString() === " ") {
                                break;
                            } else {
                                temp--;
                            }
                        }

                        text = quill.getText(temp + 1, selection - temp - 2);
                        if (text?.startsWith("http://") || text?.startsWith("https://") && (text !== "https://") && (text !== "http://")) {
                            quill.deleteText(temp + 1, selection - temp - 2);
                            quill.insertText(temp + 1, text, 'link', text);
                        }
                    } else if (insert && insert.length > 1) {   // Handle event paste
                        if (insert?.startsWith("http://") || insert?.startsWith("https://") && (insert !== "https://") && (insert !== "http://")) {
                            quill.deleteText(selection, insert.length);
                            quill.insertText(selection, insert, 'link', insert);
                        }
                    }`

**Comment by Aaron723** [comment]
> @schneidmaster thanks for sharing the code! I got it to work. The Autolink URLs when typing did not work at first because `isWhitespace` function was not included. I added the below isWhitespace function then it worked fine. @Masum06 you might give this a try.
> 
> ```
> function isWhitespace(ch) {
>   var whiteSpace = false
>   if ((ch == ' ') || (ch == '\t') || (ch == '\n')) {
>     whiteSpace = true;
>   }
>   return whiteSpace;
> },
> ```

I found that this function doesn't work well as the ```ch == ' '``` doesn't work, so I use re to detect white space :
```javascript
const isWhitespace = (char) => {
  const whiteSpaceRegex = /\s/;
  return typeof char === 'string' && whiteSpaceRegex.test(char);
};
const whiteSpaceRegex = /\s/;
```

**Comment by lenhhoxung32** [comment]
@schneidmaster  I have to login to say thank you!!!!

**Comment by rifandani** [comment]
Thank you @schneidmaster & @kilgarenone and everyone here.
I'm using `react-quill` library. If any of you guys like me, this is what I did:

> NOTE: to reference `this` correctly, we can't use arrow function and `this` is available in the first parameters of the handler

```ts
const wysiwygModules: ReactQuillProps['modules'] = {
  clipboard: {
    matchers: [
      [
        Node.TEXT_NODE,
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (node: any, delta: DeltaStatic) => {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
          if (typeof node.data !== 'string') return;

          // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
          const data = node.data as string;
          // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
          const matches = data.match(simpleUrlRegex);
          console.log('🚀 ~ file: input.type.ts:198 ~ matches:', matches);

          if (matches && matches.length > 0) {
            const ops = [];
            let str = data;

            matches.forEach((match) => {
              const split = str.split(match);
              const beforeLink = split.shift();
              ops.push({ insert: beforeLink });
              ops.push({ insert: match, attributes: { link: match } });
              str = split.join(match);
            });

            ops.push({ insert: str });
            // eslint-disable-next-line no-param-reassign
            delta.ops = ops;
          }

          // eslint-disable-next-line @typescript-eslint/no-unsafe-return, consistent-return
          return delta;
        },
      ],
    ],
  },
  keyboard: {
    bindings: {
      spaceToLink: {
        collapsed: true,
        key: ' ',
        prefix: /https?:\/\/[^\s]+/, // call handler only when matched this regex
        handler: (function spaceToLink() {
          let prevOffset = 0;
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          return function handler(this: any, range: RangeStatic) {
            let url;
            // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
            const text = this.quill.getText(prevOffset, range.index) as string;
            const match = text.match(simpleUrlRegex);

            if (!match) {
              prevOffset = range.index;
              return true;
            }
            if (match.length > 1) {
              url = match[match.length - 1];
            } else {
              [url] = match;
            }

            const ops = [];
            ops.push({ retain: range.index - url.length });
            ops.push({ delete: url.length });
            ops.push({ insert: url, attributes: { link: url } });
            // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
            this.quill.updateContents({ ops });
            prevOffset = range.index;

            return true;
          };
        })(),
      },
    },
  },
};
```
