### ISSUE TITLE
Remove empty p tag after invoke innerHTML method 

### ISSUE THREAD

**Issue by IceWilder** [quilljs/quill#1092]
I got html  from server side,and I want to insert it in quill editor. When I  used `dangerouslyPasteHTML` , I found format is wrong. So I use `quill.root.innerhtml=${myhtml}` ,but quill add so many empty `<p></p>` inner my html . How should I remove  that?

**Comment by benbro** [comment]
Please show a minimal example of HTML you are trying to paste and a [codepen](http://codepen.io/quill/pen/KzZqZx) reproducing the issue.
Add the requested information like browser, OS and Quill verison

**Comment by nikhil-hp** [comment]
bfxbgfxb
