### ISSUE TITLE
Why quill using class in html?

### ISSUE THREAD

**Issue by ibrahimyilmaz7** [quilljs/quill#1093]
I'm using quill for getting html on web and use its on mobile app. But some properties (align, size) not working because html value is:

`<p class="ql-align-center">Hakkımızda Sayfası Başlığı</p>`

I need pure html without any class dependencies. Any suggestion?

**Comment by benbro** [comment]
See SizeStyle as an [example](http://quilljs.com/guides/how-to-customize-quill/#content-and-formatting) of how to use inline style.

**Comment by ibrahimyilmaz7** [comment]
How about colors, text align vs? Also size array like: 

`["10px", "13px", "15px" ,"18px", "20px", "30px", "50px" ]`

**Comment by benbro** [comment]
Color use inline style by default.
You can replace the default align class format with a [style format](https://github.com/quilljs/quill/blob/develop/formats/align.js#L10)
I don't understand what you mean by size array.

**Comment by ibrahimyilmaz7** [comment]
I mean using custom font-size array (except 13px, normal, 18px, 32px).

**Comment by benbro** [comment]
The [SizeStyle](https://github.com/quilljs/quill/blob/f75ff2973f068c3db44f949915eb8a74faf162a8/formats/size.js#L7) format has a whitelist with ['10px', '18px', '32px'].
You can create a custom format if you need other options.
