### ISSUE TITLE
Quill Bubble Theme Issue!

### ISSUE THREAD

**Issue by ahmadawais** [quilljs/quill#1094]
In `bubble` theme of Quill, the toolbar stops appearing after adding an image, or h1 or lists. Also the shortcuts do not work. E.g. I cannot make a word bold by ⌘ + B.

**Steps for Reproduction**
![image](https://i.imgur.com/dc44r5y.gif)

1. Visit this [codepen](http://codepen.io/ahmadawais/pen/RGXMao)
2. Step Two: Add an image and press enter to move on the new line
3. Step Three: Add some text and select it to make the tooltip appear but it won't

**Expected behavior**:
Tooltip should appear
**Actual behavior**:
Tooltip won't appear now.
**Platforms**:

Include browser, operating system and respective versions

**Version**: 
Latest Chrome, macOS El Captian

Run `Quill.version` to find out
`1.1.3`

**Comment by ahmadawais** [comment]
@benbro Sorry for the tag, but can you take a look? I think it is a real bug.

**Comment by benbro** [comment]
Try to create some empty lines below the text and select it again.
Related:
https://github.com/quilljs/quill/issues/851
https://github.com/quilljs/quill/pull/941

**Comment by ahmadawais** [comment]
@benbro Yes, after adding some empty lines it starts working. It's a bug. How do I fix that? Always have some empty lines or is it fixed in the dev release?

**Comment by ahmadawais** [comment]
When it goes out of the view and I add two empty lines at the end then the toolbar appears again. How do I fix it?

**Comment by jhchen** [comment]
It's showing up but being covered. The simple solution is to add some bottom padding: http://codepen.io/quill/pen/vyYNaX. The 2nd PR has issues needing resolution before merger as stated in my comment.
