### ISSUE TITLE
Quill doesn't play nice with MaterializeCSS Modals

### ISSUE THREAD

**Issue by ixdoodla** [quilljs/quill#1097]
[Describe the issue]

Quilljs doesn't render a white background.
Certain changes made don't reflect on the editor.

**Steps for Reproduction**

1. Visit http://codepen.io/anon/pen/zoYabW
2. Open Modal
3. Select Text. Bold
4. Select Text. Heading
5. Selext Text. Link
6. Selext Text. Formula

**Expected behavior**:

Bold
Text is bolded.

Heading
Heading is applied

Link,Formula
Tooltip is properly visible.

Text Color, Text Background
Text remains selected when applying styles.

Editor Background Color is White
**Actual behavior**:

Bold, Heading
No formatting applied.

Formula, Link
Tooltip out of bounds. ( If selecting text at the edge)

TextColor, Text Background
Text gets unselected while selecting color.

Editor Background Color is Grey

**Platforms**:

Chrome 54, Windows 10 Professionsal

**Version**:

1.1.3

**Comment by jhchen** [comment]
I don't know how MaterializeCSS works specifically but it looks like it's putting Quill in an iframe. That iframe does not have the necessary stylesheet Quill requires that makes things bold. Interestingly materialize.css loads its own stylesheet that makes `strong` tags not bold.

This seems like a case Materialize should already cover as a lot of front end UI libraries require a stylesheet. I would consult their documentation and support.

**Comment by ixdoodla** [comment]
The iFrame might be codepen. Not materialize. This is the first time I'm
heading about modals in iFrames. I'll check and let you know.

**Comment by sridoodla** [comment]
@jhchen Materialize doesn't load in an iframe. That was codepen. Check out their modals at http://materializecss.com/modals.html .

And I checked the iframe source. It looked like the styles were loading. Otherwise, the tooltips wouldn't show up, eh?

**Comment by jhchen** [comment]
Yes that's my mistake. It looks like the issue is just materialize stylesheet is styling strong to not be bold. So the fix is just for formats that that is happening to, change it back.

**Comment by sridoodla** [comment]
@jhchen The background isn't white(relatively easy CSS fix). Also, any tooltip based elements ( hyperlinks and formula ) get cut-off by the modal edge.

This is happening for modals by JqueryUI also. Is there any fix/workaround?

**Comment by jhchen** [comment]
http://quilljs.com/docs/configuration/#bounds

**Comment by sridoodla** [comment]
How do I use that? Not quite sure what to do here.

On Dec 4, 2016 2:48 AM, "Jason Chen" <notifications@github.com> wrote:

http://quilljs.com/docs/configuration/#bounds

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/quilljs/quill/issues/1097#issuecomment-264689692>, or mute
the thread
