### ISSUE TITLE
Disable tab

### ISSUE THREAD

**Issue by adhsu** [quilljs/quill#110]
I didn't see this anywhere in the documentation, sorry if I missed it. I'd like to be able to disable tabbing, so that I can type a message and tab to a submit button/etc.

**Comment by kmoe** [comment]
Would you appreciate a PR to add this as an option in the config? So you could do
```javascript
var editor = new Quill('#editor', {
  tab: 'disabled'
});
```

or similar.

**Comment by kmoe** [comment]
Actually it would be a module option rather than a top-level one. But you get the idea. Preparing PR now in case you do want this.

**Comment by jhchen** [comment]
In this case I think a module might be too heavyweight. The best approach might just be to add an easy to use `removeHotkey` function to the keyboard module. Do you want to give this route a try?

**Comment by kmoe** [comment]
Yes, sorry, by 'module option' I meant an option you can pass into a module rather than a new module! `removeHotkey` makes sense and would be easy to do.
Do you think it should just take the raw key number (`removeHotkey(9)`) or a string mapped using the dom module (`removeHotkey('TAB')`)?

**Comment by jhchen** [comment]
Yes I think it should either take a hotkey object or string. If it's a string it should look up Keyboard.hotkeys and use that hotkey object.

**Comment by LeZuse** [comment]
Just noticed that `removeHotkey` nicely solves the problem for the `TAB` keystroke, but does not work for `Shift+TAB` which is a bummer, because you obviously will not `removeHotkey` `Shift`. Any workaround suggestions?

**Comment by jhchen** [comment]
You can pass in `removeHotkeys({ key: dom.KEYS.TAB, shiftKey: true })`

**Comment by acidjazz** [comment]
Why isn't this functionality documented anywhere after a year? I tried to find removeHotKeys or removeHotKey in the keyboard module and was unable to call it, I ended up finding I could

```javascript
var keyboard = editor.getModule('keyboard');
delete keyboard.bindings[9];
```
I honestly think tab: 'disabled' or tabs: false is a more understandable and guessable option, especially with the mess for shift+tab as well

**Comment by benbro** [comment]
The keyboard module is documented [here](http://quilljs.com/docs/modules/keyboard/)
You can use quill.keyboard.addBinding() to add a binding.

You can override the default bindings in the config:
http://codepen.io/anon/pen/JRJgQB

**Comment by acidjazz** [comment]
@benbro thank you, I thought I had read through everything, but googling this instead brought me to this issue, maybe we can add examples of `removeHotKey` or `removeHotKeys`? Or were they removed and this is a more proper example now?

Glad to see this issue now ends w/ a link to the proper page now for future visitors.

**Comment by hhubik** [comment]
I have the opposite problem.  I have an app with a few input elements, one of which is quill.  I specified the tab order using the tabindex on each input element.  That works fine, except when I tab to the quill element, the focus seems to be on the border of the element.  How do I force the focus be in the text input area of quill so that when I start typing, the text goes in the right place?  Thanks.

**Comment by benbro** [comment]
@hhubik can you please fork the [codepen example](http://codepen.io/quill/pen/KzZqZx), modify it to reproduce your case and open a new github issue describing it?

**Comment by aguynamedben** [comment]
I'm having the same problem @hhubik observed and re-created it in Codepen: http://codepen.io/aguynamedben/pen/KNBNBP

Is tabbing into a Quill instance from a previous form input supposed to work?

**Comment by eddieherm** [comment]
I worked around this by adding the following JQuery code after instantiating quill:

```
var inputTabIndex = $('#first-input').attr('tabindex');
$('.ql-editor').attr('tabindex', parseInt(inputTabIndex) + 1);
```

The idea is to get the previous input from which you are tabbing from and get its tabindex. Then set the class for the actual editor object which is .ql-editor, and set its tabIndex to +1 of the previous input's tabindex.

**Comment by p10shinde** [comment]
Try this...

`delete quill.getModule('keyboard').bindings["9"]`

**Comment by maxant** [comment]
> delete quill.getModule('keyboard').bindings["9"]

in Quill 2.0, use "Tab" instead of "9":

    delete quill.getModule('keyboard').bindings['Tab']

**Comment by TheNaderio** [comment]
> Try this...
> 
> `delete quill.getModule('keyboard').bindings["9"]`

For users who came here via a search engine:

I got an older project with quill `1.3.7` where this doesn't work.
I solved it with:
```javascript
delete quill.keyboard.bindings[9]
```
