### ISSUE TITLE
Bubble theme toolbar shows up underneath element

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#1100]
The bubble toolbar shows up underneath a the side menu. How can I change it so the toolbar loads into the body container instead of inside the quill document container? Otherwise the toolbar gets cut off like so:

<img width="759" alt="screen shot 2016-11-05 at 5 50 32 am" src="https://cloud.githubusercontent.com/assets/3514912/20029177/fe703c80-a31b-11e6-96d9-836eeca9e1e0.png">

**Expected behavior**:

The quill toolbar should always be on top of everything. Should load toolbar into body container to make this happen. 

**Actual behavior**:

The toolbar loads underneath elements on the screen since the toolbar is inside the quill container.

**Comment by jhchen** [comment]
Quill can only guarantee to be on top of other Quill UI (which it does), but short of making users place the Quill container at the root, it cannot guarantee other UI in your application will not cover it.

Take a look at [Understanding CSS z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index) and in particular [this example](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_context_example_2). Even though DIV 4 has the highest z-index, it cannot escape its relative parent's place in the DOM hierarchy.

**Comment by sferoze** [comment]
@jhchen your right, I actually found out that I had a mistake in my design which was causing this. I fixed it now and the toolbar works as expected. Not an issue with Quill.

**Comment by ajoshi31** [comment]
@sferoze : I am using angular material that has fixed sidebar, how can I fix this issue I am also having the same issue.
Even I tried z-index but as said it won't help.

**Comment by sferoze** [comment]
@ajoshi31 if z-index doesn't work then you will have to look at the layout of your dom elements and try adjusting the order of dom elements in html. Also check the overflow of the quill container and make sure its set to visible. 

In my case I did a ton of restructuring of how the menu works and I noticed that the toolbar issue was resolved when I did.

**Comment by APengue1** [comment]
I have solved this problem using the `bounds` configuration option as mentioned in #1124

**Comment by shyamal890** [comment]
I frankly believe the tooltip component should be appended to the body instead. This would solve a lot of issues. This is how medium-editor works too.

**Comment by letitfly** [comment]
Same here. Sometime it's difficult to set the right bounds, and the drop down menu from the bubble toolbar does not observe the bounds option.

**Comment by shyamal890** [comment]
@jhchen Should have a look if the tooltip can be appended to the body instead.

**Comment by rajuashok** [comment]
Has this been looked into? I've used bounds to fix this for the popup toolbar in Bubble, but the link preview for any linked text doesn't seem to follow these bounds :(.

**Comment by Carl012** [comment]
Indeed, the link tooltip in Bubble seems broken.

I just posted here: https://github.com/quilljs/quill/issues/360

**Comment by douglasdc** [comment]
I solve that using `z-index` on `.ql-bubble .ql-tooltip`

```css
.ql-bubble .ql-tooltip {
  z-index: 1;
}
```

**Comment by FenoRC** [comment]
I found a solution for my situation:
when create the configuration object, set property _'bounds'_ with the **selector of quill container**.

**Example:**
```
const SELECTOR_CONTAINER = '#quill-container-2';
const DEFAULT_CONFIG = {
        theme: 'bubble',
        bounds: SELECTOR_CONTAINER
};

new Quill(SELECTOR_CONTAINER, DEFAULT_CONFIG);
```

**Comment by Itsmaqsud** [comment]
> I found a solution for my situation:
> when create the configuration object, set property _'bounds'_ with the **selector of quill container**.
> 
> **Example:**
> 
> ```
> const SELECTOR_CONTAINER = '#quill-container-2';
> const DEFAULT_CONFIG = {
>         theme: 'bubble',
>         bounds: SELECTOR_CONTAINER
> };
> 
> new Quill(SELECTOR_CONTAINER, DEFAULT_CONFIG);
> ```

You saved my day! Thank you!

**Comment by Seemeile** [comment]
We had the problem, that the tooltip was placed inside the quill editor box:
![image](https://user-images.githubusercontent.com/38246841/104448721-ce0b3700-559d-11eb-8bc7-6137544b0705.png)
turns out the problem was the "preserveWhitespace" property. We removed it and the tooltip was displayed above the editor box again.

**Comment by mkamalkayani** [comment]
I also faced this problem and removing the `overlfow: auto` from a parent element solved it.

**Comment by nikkhah63** [comment]
overlfow: visible or use bounds

**Comment by ayelen3976** [comment]
Does anyone know how I can put the tooltip in the top position?

**Comment by hsiaalex** [comment]
> Does anyone know how I can put the tooltip in the top position?

When I set the bounds as per https://github.com/slab/quill/issues/1100#issuecomment-584788894, my tooltip showed at the top, and was not under other elements. Without the setting, it showed below and under elements.

**Comment by pablopissoni** [comment]
"I solved it by limiting it to the container with bounds={'.app'} and in className='app'

<div className=`relative app`>
  <ReactQuill
    theme="bubble"
    value={editor}
    onChange={handleEditorChange}
    modules={modules}
    bounds={".app"}
  />
</div>
