### ISSUE TITLE
Link tooltip cut off by edge of editor

### ISSUE THREAD

**Issue by glennfu** [quilljs/quill#1103]
Hello there! This is a recreation of #360 which was closed with a fix but is still possible to reproduce the scenario where a tooltip is cut off:

<img width="367" alt="quilltooltipcutoff" src="https://cloud.githubusercontent.com/assets/20549/20068197/d7d1ab10-a4e5-11e6-9a70-df0f5778eb11.png">

**Steps for Reproduction**

Codepen: http://codepen.io/anon/pen/PbqqKx

**Expected behavior**:

1. Click Video embed
2. See tooltip fully visible

**Actual behavior**:

1. Click Video embed
2. See only half of the tooltip

**Platforms**:

On macOS Sierra 10.12.1, using Safari, Chrome, and FireFox

**Version**:

Quill version 1.1.4

**Comment by glennfu** [comment]
I'm assuming this is a bug since the commit that closed the last issue was referenced with the text "The tooltip placement has been reverted to be within the editor". However in this instance you can see it's not contained by the editor.

A reasonable workaround is to pass `{ bounds: element }` where `element` is the same element being passed as the first argument that Quill is created on. Then the reference bounds are indeed set to be that of the Quill form.

**Comment by jhchen** [comment]
You have intentionally set the `#right-stuff` overflow to be hidden so the overflow will be hidden.

**Comment by glennfu** [comment]
OK I understand. I think my trouble was not being able to figure out the expected behavior. All I could find was your words: "The tooltip placement has been reverted to be within the editor" so I thought I would expect it to be within the editor in my layout. From that it wasn't clear to me that this wasn't a bug, sorry!

Obviously in my Codepen it was overly simplified but in my real use case there are other elements and columns and floats and such causing the overlap. I couldn't figure out why the tooltip wasn't appearing within the editor for a while. In my layout as well as the Codepen, the editor is fully visible and unobstructed, but the tooltip is chopped off. I didn't have an option to remove overflow rules on all containers and parents above the editor so unfortunately It wasn't as simple as "if you want it to show, don't hide it". I would really like and prefer to be able to unhide it in that case like you recommend, but I can't!

**Comment by jhchen** [comment]
A DOM node being able to confine a descendent node visually is a DOM thing so there's not much Quill can do here unfortunately. Similar issue: #1100

**Comment by jziggas** [comment]
This can still be a problem if the editor is within with a z-index stacking context where something to the left has higher z-index than the element that the editor is contained in. Can the position of the link popover be controlled or disabled?

**Comment by jhchen** [comment]
The easiest way to hide it completely is just add a `display: none` CSS rule. The `bounds` config allows it to be automatically moved intelligently given containing boundaries.

**Comment by FenoRC** [comment]
I found a solution for my situation:
when create the configuration object, set property _'bounds'_ with the **selector of quill container**.

**Example:**
```
const SELECTOR_CONTAINER = '#quill-container-2';
const DEFAULT_CONFIG = {
        theme: 'bubble',
        bounds: SELECTOR_CONTAINER
};

new Quill(SELECTOR_CONTAINER, DEFAULT_CONFIG);
```

**Comment by mirmehdi5** [comment]
> aps you can point me in the right direc

I am having a similar issue with bounds working fine for left/right, but not for top/bottom for quill bubble theme alone

**Comment by marcoancona** [comment]
Is there any workaround to render this tooltip _outside_ the Quill DOM tree? As popover usually work?

**Comment by bhumikabhatia** [comment]
Any workaround for bounds for top/bottom for the bubble theme in quill?
