### ISSUE TITLE
Selection is temporarily lost while selection in dropdown

### ISSUE THREAD

**Issue by tipenko** [quilljs/quill#1104]
Selection is temporarily lost while selection in dropdown. User sees formatting values as if nothing was selected.

1. Visit http://codepen.io/ne_tipenko/pen/vyNZQw
2. Select word "sixth". See that "Large" option is selected in size selector.
3. Click on the leftmost option (heading). Dropdown is opened

Expected behavior:
While choosing in dropdown, selection is visible and toolbar icons reflect formatting state

Actual behavior:
Selection disappears while dropdown is open. Once the value is selected, selection comes back.

Platforms:
Windows 10, Chrome 54.0.2840.71 and other browsers

Version: 
Quill 1.1.4

**Comment by tipenko** [comment]
Guys, any comments? Is it a good idea for me to dig in and try to fix it myself?

**Comment by jhchen** [comment]
Yes I don't think anyone else is working on it so feel free to dig in.

**Comment by jhchen** [comment]
Consolidating with #879 as it is the same root cause.

**Comment by vadim-isakov** [comment]
You can check the solution here: https://github.com/slab/quill/issues/1591#issuecomment-2677224027
