### ISSUE TITLE
Change tagName for <ul>

### ISSUE THREAD

**Issue by joli84** [quilljs/quill#1106]
Trying to change the tagName for a unordered list. Want to change from "ul" to e.g. "list"
Can't find any other documentation about this. So using same technique as changing tagName for bold. Not sure if it is the correct way.

```
var List = Quill.import('formats/list');
List.tagName = 'list';
Quill.register(List, true);
```

**Steps for Reproduction**

1. Visit https://quilljs.com/playground/
2. Add the following
```
var List = Quill.import('formats/list');
List.tagName = 'list';
Quill.register(List, true);

var quill = new Quill('#editor-container', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      [{ 'list': 'bullet' }],
      ['bold', 'italic', 'underline'],
      ['image', 'code-block']
    ]
  },
  placeholder: 'Compose an epic...',
  theme: 'snow'  // or 'bubble'
});
```

3. Step Three

**Expected behavior**:
Same behaviour as when using default list

**Actual behavior**:
Makes a list but you cant remove the list.

**Platforms**:
Chrome: 53.0.2785.143 m
Windows 8.1

**Version**:
The version playground is using.
Also tried on local project installed from npm
Version: 1.1.5

**Comment by benbro** [comment]
<list> is not a valid HTML element.

**Comment by joli84** [comment]
Ahh, got the impression you could customize your own tags. Thats not the case then. Ty.
