### ISSUE TITLE
How to disable images when pasting?

### ISSUE THREAD

**Issue by mscreenie** [quilljs/quill#1108]
I want to make sure no images are pasted inside the text area and pasting images seems to work. How can i prevent this?

**Comment by benbro** [comment]
Use the [formats config](http://quilljs.com/docs/configuration/#formats) to define a whiltelist of formats to allow in the editor. By default all formats are allowed.
You can see the [list of supported formats](http://quilljs.com/docs/formats/).

For [example](http://codepen.io/anon/pen/ObMweL), to allow all formats except for image and video:

```javascript
  var formats = [
    'background',
    'bold',
    'color',
    'font',
    'code',
    'italic',
    'link',
    'size',
    'strike',
    'script',
    'underline',
    'blockquote',
    'header',
    'indent',
    'list',
    'align',
    'direction',
    'code-block',
    'formula'
    // image
    // video
  ];
var quill = new Quill('#editor-container', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
      ['image', 'code-block']
    ]
  },
  placeholder: 'Compose an epic...',
  theme: 'snow',  // or 'bubble'
  'formats': formats
});
```

**Comment by mscreenie** [comment]
Thanks! Great stuff. I noticed when changing the font family the editor attaches a class as opposed to a style or <font> like other editors. Is this behavior changeable, as in my case it is not desirable. I searched and it seems it possible for font sizes not sure about font family.

**Comment by benbro** [comment]
Explained in the  [guide](http://quilljs.com/guides/how-to-customize-quill/#class-vs-inline).
```javascript
var FontStyle = Quill.import('attributors/style/font');
Quill.register(FontStyle, true);
```

**Comment by mscreenie** [comment]
Any pointers on how to add an additional data-font-fetch when a font is selected / changed for text?  Thank you.

**Comment by mscreenie** [comment]
shamefully requesting help here. @benbro would you be able to assist me in modifying the font selector to add a attribute like the above?

**Comment by kevinrichard31** [comment]
it doesn't work for me, when i copy paste an img, it is displayed on screen and in the Delta

**Comment by anivaliant** [comment]
> It took a minute but I was running into a similar issue as @kevinrichard31 where I would make sure that image tags weren't whitelisted, which worked perfectly if you were trying to copy/paste an image in, it wouldn't allow it. But if you dragged/dropped an image into the text editor it would still display it/make an image tag for it.
> 
> My solution ended up being to just continually make sure that if any img tags were being created we'd remove them:
> `editor.on('text-change', function (delta, oldDelta, source) { $('#editor img').remove(); });`

My solution : add editor div  ondragover="return false;"

**Comment by mbareta** [comment]
> > It took a minute but I was running into a similar issue as @kevinrichard31 where I would make sure that image tags weren't whitelisted, which worked perfectly if you were trying to copy/paste an image in, it wouldn't allow it. But if you dragged/dropped an image into the text editor it would still display it/make an image tag for it.
> > My solution ended up being to just continually make sure that if any img tags were being created we'd remove them:
> > `editor.on('text-change', function (delta, oldDelta, source) { $('#editor img').remove(); });`
> 
> My solution : add editor div ondragover="return false;"

This won't help in case when someone copy-pastes the image from (for example) Google Docs. Those you can just copy-paste and it gets formatted as img with base64 source.

**Comment by Aidenbuis** [comment]
This worked for me:
```
editor.clipboard.addMatcher(Node.ELEMENT_NODE, function (node, delta) {
            const plaintext = node.innerText
            const Delta = Quill.import('delta')
            return new Delta().insert(plaintext)
        })
```

**Comment by VelinGeorgiev** [comment]
Thanks @Aidenbuis that is a great solution! Here is how I did mine by using the `addMatcher` so I can keep the rest of the pasted html like parahraphs, headers, but skip the images.

```
editor.clipboard.addMatcher('IMG', (node, delta) => {
            const Delta = Quill.import('delta')
            return new Delta().insert('')
        })
        editor.clipboard.addMatcher('PICTURE', (node, delta) => {
            const Delta = Quill.import('delta')
            return new Delta().insert('')
        })
```
