### ISSUE TITLE
How to insert a custom html tag, like <x-video> ,into the content?

### ISSUE THREAD

**Issue by awpsawps12** [quilljs/quill#1109]
quill works well, but when I use the code,
`editor.clipboard.dangerouslyPasteHTML(rang.index, '<x-video>test</x-video'>)`,
it didn't work, I want to know is there any way to insert a custom html tag into the content?
thx

**Comment by mscreenie** [comment]
Not sure but you could try whitelisting the tag like @benbro described in my issue: https://github.com/quilljs/quill/issues/1108#issuecomment-260060670

**Comment by benbro** [comment]
The [Cloning Medium with Parchment](http://quilljs.com/guides/cloning-medium-with-parchment/) guide explains how to add custom blots.

[Example](http://codepen.io/anon/pen/QGNKpK):
```javascript
let Inline = Quill.import('blots/inline');

class XVideoBlot extends Inline { }
XVideoBlot.blotName = 'xvideo';
XVideoBlot.tagName = 'x-video';

Quill.register(XVideoBlot);
```

**Comment by awpsawps12** [comment]
@benbro this way works, it helps me to insert the custom tag of `<x-video>` into the content, thanks a lot.

but meanwhile another problem appears, after I insert it and start from a new line, this new line will keep on inserting new `<x-video>` and use the same style of `<x-video>`,but I may just want a new line with a `<p>` tag, is there any way to stop it?

**Comment by kalluu-ck** [comment]
If you are using Angular with ngx-quill, you can check this article to implement a custom blot:
https://kalcancode.wordpress.com/2025/03/31/how-to-implement-custom-embed-blot-in-ngx-quill/
