### ISSUE TITLE
Deltas line break

### ISSUE THREAD

**Issue by raphaelkoszalka** [quilljs/quill#1110]
Hello everyone,

I'm currently working in a reports module and utilizing Quill as a wysiwyg editor in the front end.
I'm working with Quill Deltas, sending the object via REST to my backend where i convert it into a PDF file.
I want to know if it's possible for Quill to insert a line break ('\n') when every line reaches the right margin of the quill editor element, not only when the users press enter. 

I'm having some troubles about the assertiveness of what the user sees inside the editor and the generated PDF from the delta object.

Thank you in advance.

**Comment by jhchen** [comment]
It is possible to insert a line break wherever you want. To figure out where the right visual margins are depends on the user's screen width and/or the width the application using Quill.
