### ISSUE TITLE
Embeds/BlockEmbeds with Attributes using insertEmbed

### ISSUE THREAD

**Issue by danielschwartz** [quilljs/quill#1111]
Hi,

We're trying to create a couple custom formats that require multiple attributes for them to be useful. 

For instance, imagine we wanted to change the way the Image embed works to be able to specify a particular size (or alt text) at the time of creation. We can't do this with insertEmbed because the value argument is expected to be a string, and there is no attributes argument. 

What would be the correct way of instantiating an embed that has associated attributes? Would I just generate my own Delta and use updateContents instead of doing insertEmbed? 

Would love some guidance, thanks!

**Comment by jhchen** [comment]
The value argument for [insertEmbed](http://quilljs.com/docs/api/#insertembed) can be any type. But the default Image blot understands its value to be a string. If you create your own blot or extend an existing one, you do not have to a use a string as the value.

For size specifically, the Image blot actually understands width and height: http://codepen.io/quill/pen/VmbKdm

**Comment by danielschwartz** [comment]
@jhchen thanks for the confirmation on this. Makes total sense.

**Comment by Tofandel** [comment]
Well the problem with this, is even though you can add attributes, the delta doesn't contain those attributes when doing `quill.getContents()` so effectively they can't be saved other than by html
