### ISSUE TITLE
Header1,2,3 inserts unwanted br tags when clipboard dangerouslyPasteHTML

### ISSUE THREAD

**Issue by yuchentseng** [quilljs/quill#1112]
I used clipboard.dangerouslyPasteHTML to re-edit quill-edited article that I saved before.
But if I paste the following html:
	`<p>Some normal words</p><h2>Header2</h2>`
it would become this:
	`<p>Some normal words</p><p><br></p><h2>Header2</h2>`
in quill editor.

It always inserts a `<br>` tag berfore the header tag.
I'v tried other toolbar buttons like bold or italicize, but this problem only occurs at headers.

**Comment by jhchen** [comment]
This is because Quill tries to visually match pasted content. Because paragraphs and headers have spacing, and Quill does not, it adds a newline to compensate. If this is undesirable, you can add a CSS rule to get rid of the spacing: http://codepen.io/quill/pen/dOWpJX.
