### ISSUE TITLE
Non-Default formats are lost in 2 cases

### ISSUE THREAD

**Issue by ghost** [quilljs/quill#1113]
I've noticed that non-default formats are lost in two different cases. I'm just curious if they are by design or a bug.

*Case 1*
**Steps for Reproduction**

1. Visit quilljs.com
2. Clear all text out of the editor
3. Change the format (bold, italic, font, etc)
4. Type text
5. Backspace so all text is deleted

**Expected behavior**:
Non-default formats are persisted

**Actual behavior**:
All non-default fonts are cleared

**Platforms**:
Chrome 54.0.2840.87, Windows 10

**Version**:
1.1.5

*Case 2*
**Steps for Reproduction**

1. Visit quilljs.com
2. Clear all text out of the editor
3. Change the format (bold, italic, font, etc)
4. Type text
5. Press enter twice
6. Press up arrow to go to the 2nd line

**Expected behavior**:
Non-default formats are persisted

**Actual behavior**:
All non-default fonts are cleared

**Platforms**:
Chrome 54.0.2840.87, Windows 10

**Version**:
1.1.5

**Comment by jhchen** [comment]
They are not by intentional design but manifests because of the implementation. Looks like Docs and Word both exhibit the expected behavior, so an argument could be made Quill should too.

**Comment by prokilogrammer** [comment]
Both MS Word and Google Docs handle these cases as expected. It is a very bad UX if Quill lost the user's formatting after just deleting a line. What do you think? 

I will be happy to send out a PR for it.

**Comment by ersommer** [comment]
@prokilogrammer - If you could create a PR for this I'd be very grateful
