### ISSUE TITLE
Text cursor is displayed when interacting with the scrollbar

### ISSUE THREAD

**Issue by ersommer** [quilljs/quill#1114]
When you interact with the scrollbar on an editor, the selection cursor is still shown. It probably should be the "default" cursor instead.

**Steps for Reproduction**
1. Visit [quilljs.com](quilljs.com)
2. Select the editor
3. Interact with the editor scrollbar (scroll up/down)

**Expected behavior**:
Cursor changes to the "default" cursor that's normally used for interacting with scrollbars

**Actual behavior**:
Cursor remains the selection cursor that's typically displayed when typing

**Platforms:**
Chrome 54.0.2840.87, Windows 10

**Version:**
1.1.5

**Comment by mscreenie** [comment]
Present on Windows 7 also. Same Chrome version.

**Comment by jhchen** [comment]
When you scroll down on quilljs.com, the cursor will hover over the Youtube video, which will display the clickable `cursor: pointer`. If you scroll further, it goes back to the `cursor: text`. Is this what you are seeing?

**Comment by sbevels** [comment]
I'm not sure if this is the same thing as was originally reported, but here is a related annoyance we are seeing.  When your cursor is at the top of the document, you scroll down to the bottom of the document.  If another user types in the document you are immediately scrolled back up to your cursor.  This makes reading the document difficult when others are typing in it.

Perhaps there is a way to not scroll to the cursor if the user's last action was scrolling.

**Comment by jhchen** [comment]
@sbevels That sounds unrelated. Can you open a separate Issue?

**Comment by sbevels** [comment]
Yep, I opened [#1152](https://github.com/quilljs/quill/issues/1152)

**Comment by ersommer** [comment]
I'm referring to the actual scrollbar on the right side. When you mouseover it in other places the cursor changes to `cursor: pointer`. However, when you mouseover the one in Quill, you still get `cursor: text`.

**Comment by jhchen** [comment]
I see thanks for the clarification. This appears to be a Chrome only issue.

**Comment by henry-luo** [comment]
The follow CSS rules solve the problem for me:
```
.ql-editor { cursor:default; }
.ql-editor * { cursor:text; }
```
In other words, cursor:text style rule should not be set on ql-editor, which will confuse Chrome browser.

**Comment by jhchen** [comment]
Thanks for the tip @henry-luo
