### ISSUE TITLE
Creating a Quill editor from DOM creates extra content

### ISSUE THREAD

**Issue by teusbenschop** [quilljs/quill#1116]
When creating a new Quill editor from existing DOM content, the Quill-based editor injects extra content into the editor. This content was not available in the original DOM content.

**Steps for Reproduction**

1. Visit https://jsfiddle.net/teusbenschop/gcgx6x1k/
2. Run it

**Expected behavior**:
The Quill editor will have two paragraphs.

**Actual behavior**:
The Quill editor inserts one extra paragraph in the middle, and then has three paragraphs.

**Platforms**:
Google Chrome Version 53.0.2785.101 (64-bit)
macOS Sierra Version 10.12.1

**Version**:
Quill version 1.1.5

**Notes**:
The included CSS causes this behaviour.
When the CSS is changed or removed, the behaviour changes also.
In my case the CSS is necessary to give the desired visual presentation of the content within the Quill editor.

The Quill code is right at the bottom of the included javascript on fiddle. It's only this:

```
quill = new Quill ('#editor', { });
quill.focus ();
```

The entire minimal case for this issue is also available here: https://github.com/bibledit/playground/tree/master/quill-mini

**Comment by jhchen** [comment]
It's because there is spacing from the `.d` class. Quill `<p>` tags do not have spacing so it tries to more closely match the input content with a newline.

Also JSFiddle allows you to attach external resources on the left side so you don't have to paste the entire built library.
