### ISSUE TITLE
An extra delimiter before the embed

### ISSUE THREAD

**Issue by kundius** [quilljs/quill#1118]
Did the divider for this [example](http://quilljs.com/guides/cloning-medium-with-parchment/#dividers). After connecting the editor to block content between the block (`<p></p>`) and separator (`<hr>`) is added `<p><br></p>`

**Steps for Reproduction**
This code:
`<p>text</p><hr>`
Turns out this content:
`{"ops":[{"insert":"text\n\n"},{"insert":{"hr":true}}]}`

Why adding the second `\n`?

**Version**: 1.1.5

_P.S. Sorry for the translator._

**Comment by jhchen** [comment]
I'm not sure I follow the steps for reproduction. Where are you putting `<p>text</p><hr>`?
