### ISSUE TITLE
Quill nodes and listeners leaks

### ISSUE THREAD

**Issue by artaommahe** [quilljs/quill#1119]
Quill editor does not properly cleanup on destroy, so using it with single page applications causing nodes and listeners leaks.

**Steps for Reproduction**

1. Open example http://codepen.io/anon/pen/qqRRmz?editors=1010. Toggle button creates parent element for editor and instantiate it or removes this element with editor markup on each click.
2. Open Chrome devtools, run Timeline record
3. Click 'toggle' buttons 10-20 times and Timeline Collect garbage button after this
4. Stop Timeline record, toggle Memory graphs

**Expected behavior**:
Heap, nodes and listeners graphs reset to minimum after Collect garbage event

**Actual behavior**:
Nodes and listeners graphs shows just small cleanup and a lot of missed 
![image](https://cloud.githubusercontent.com/assets/1944061/20451158/6abb7300-ae07-11e6-8713-7eb73619efa1.png)

**Platforms**:

Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Version**:

//cdn.quilljs.com/1.1.4/quill.js

**Comment by benbro** [comment]
Where is the 'Timeline Collect garbage' button in step 3?
I don't see it in Chrome 54 and I don't see the graph above.

Did you have a chance to test it in Firefox to see if it's specific to Chrome or not?
It will be interesting to disable all Quill modules and comment parts of the core until the leak disappears.

**Comment by artaommahe** [comment]
@benbro garbage icon to the right of Paint checkbox 
![image](https://cloud.githubusercontent.com/assets/1944061/20458441/70a06a46-aeb6-11e6-8a7b-1227731b754c.png)

**Comment by benbro** [comment]
I see it thanks.
Did you test on a separate page not on codepen and without an iframe?

**Comment by benbro** [comment]
Removing the toolbar module with "toolbar: false" brings the nodes graph to the baseline.
The listeners graph is still high.

**Comment by artaommahe** [comment]
> Did you test on a separate page not on codepen and without an iframe?
yep, same for standalone test page, code http://pastebin.com/JqVGfeKy

> Removing the toolbar module with "toolbar: false" brings the nodes graph to the baseline. The listeners graph is still high.
yep, same

**Comment by benbro** [comment]
I think your code hold a reference to the old div and quill in a closure.
I modified your code and now the nodes and listeners graphs goes to minimum:
http://codepen.io/anon/pen/ENZGRK?editors=1010

Seems like there is no leak in Quill.

**Comment by artaommahe** [comment]
@benbro `console.log()` makes it :fp: just remove it in my first example and everything fine. Thx
