### ISSUE TITLE
How do I modify font selection to add an extra attribute?

### ISSUE THREAD

**Issue by mscreenie** [quilljs/quill#1122]
My application allows users to use all of Google's fonts. Instead of loading every font on the front end I wanted to load them dynamically.  

I've already configured quill to use css styles instead of classes. But wanted to add an additional attribute containing a key or identifier of the font used so I can detect it and load it as it's used.

Something like this.

`<span style="font-family:Roboto;" data-fetch-font="Roboto">Quill is cool</span>`

Notice the data attribute **data-fetch-font="Roboto"** I'll eventually use a numeric key to refer to the font but for demonstration sake I have used the name.  Any pointers?

**Comment by jhchen** [comment]
I'm not sure this editor contents itself is the right abstraction layer to put caching information. I would suggest capture this on input. For example when the user clicks on the dropdown item that adds a font, and when the document is initially loaded, run [`reduce`](https://github.com/quilljs/delta#reduce) over the Delta.
