### ISSUE TITLE
Make bubble tooltip stay within the bounds

### ISSUE THREAD

**Issue by Kivylius** [quilljs/quill#1124]
I have a small problem with a bobble theme as I want to have a overflow: scroll box that can be edited, its better to show then talk all day, maybe this is possible with css but i'm no expert.

**Steps for Reproduction**

1. Visit [https://jsfiddle.net/ptts0afd/](https://jsfiddle.net/ptts0afd/)
2. Click on a word left/right of content
3. Bubble tooltip is obstructed.

**Expected behavior**: Show
**Actual behavior**: Hidden
**Platforms**: Chrome
**Version**: 1.1.5

Thanks.

**Comment by jhchen** [comment]
This is an available configuration [option](http://quilljs.com/docs/configuration/#bounds).

**Comment by Kivylius** [comment]
I have set the container but there still a problem, any text at the bottom (select the last few words) the bubble is not showing up, i check the inspector its placed in correct location but not showing up; here a gif to explain:

![bubble-fail-on-bottom](https://cloud.githubusercontent.com/assets/1041335/20528083/bd08610a-b0c2-11e6-9d43-36698ebe8d2d.gif)

You can see the updated code here: [https://jsfiddle.net/ptts0afd/2/](https://jsfiddle.net/ptts0afd/2/)
