### ISSUE TITLE
Is there anyway to save and load seperate history stacks as data that can be put lets say in an html tag with the "data" tag?

### ISSUE THREAD

**Issue by devplex57** [quilljs/quill#1128]
I want to save the current history stack into the data attribute of an html tag, clear the stack, and reload it from the html tag. Can I do that and how?

**Comment by jhchen** [comment]
There's not an API to retrieve or set history stack information. But since the undo/redo functionality is a module, you can extend it to add this functionality. See the [module](http://quilljs.com/docs/modules/) docs for details.
