### ISSUE TITLE
Link dialog doesn't appear when last line

### ISSUE THREAD

**Issue by GimpArm** [quilljs/quill#1131]
The link dialog does not work when it is done to the last element in the document and there are at least 13 other lines above it. Adding a few blank lines below the element you wish to add a link to will suddenly cause the link dialog to start working.

**Steps for Reproduction**

1. Visit quilljs.com
2. Use the center example (or anything with the link button)
3. Scroll down and select the last position
4. Press enter to make a new line and type anything
5. Highlight what was just typed and press the link button

**Expected behavior**:
The link dialog should appear so you can assign the highlighted text a link

**Actual behavior**:
Nothing happens

**Platforms**:
I have test on Windows 8.1 with Chrome 54.0.2840.99  and Firefox 50.0 with the same results

**Version**:
1.1.5

**Comment by rquast** [comment]
It's caused by the .ql-out-bottom style that will hide the dialog automatically if it extends past the editor bounds. As a workaround, you can override it with this in your own css:

.ql-out-bottom {
  visibility: initial !important;
}﻿

**Comment by jhchen** [comment]
Not condoning use of `!important` but overwriting CSS rules is the right way to go. Changing the visibility is one way though depending on your use case (if the editor auto grows or not for example) you may want other rules. The main approach though is just CSS.
