### ISSUE TITLE
Link without target - how to?

### ISSUE THREAD

**Issue by maku** [quilljs/quill#1139]
How can I add an additional link behaviour with no target  '_blank':

Do I have to develop my own "Blot"?
Can anybody give a hint?

**Comment by benbro** [comment]
You can [override the link format](http://codepen.io/anon/pen/GNMXZa) with a custom format that doesn't create the target attribute.

You can't have two formats acting on the same A tag name.

**Comment by maku** [comment]
@benbro thank you for the hint. But I would really need two kind of links inner app links (-> the html is for a SPA and the link should be with no target) and external links (which should be opened in a new tab)

What about inserting the html programmatically? Is this the way to go? (and how would I do this?)

**Comment by benbro** [comment]
Remove the target attribute only from you inner app links:
http://codepen.io/anon/pen/GNMXZa

**Comment by maku** [comment]
@benbro great - now I get it how I can do it basically. 

The only one remaining problem is how to translate this in typescript (because of MyLink extends Link which is imported in a non module specific manner)

**Comment by benbro** [comment]
The link is [exported](https://github.com/quilljs/quill/blob/develop/formats/link.js#L40) as a normal Javascript class.
Should be possible to use the [Quill Typescript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/quill/quill.d.ts).

**Comment by maku** [comment]
@benbro in this Typescript definition there is no Link definition. So I do not know how to use this and I have also no idea how tho write one (at least in this constellation)

The problem, from my point of view,  is the import of the Link class which acts as base class for the sublclass. 

```
var Link = Quill.import('formats/link');
class MyLink extends Link {
  ...
} 
```

I would rather expect something like: 

```
import {Link} from 'quill';
```

I had to go the "hard" way. Which means translation of the es6 source code with babel and manually inserting the result in my typescript project. (135 lines of ugly code )

**Comment by jhchen** [comment]
We have to use ES5 exports at that moment since if we use ES6, you can't do `import Quill from 'quill';` in an ES5 environment, and importing Quill is the most important import. I don't believe any browser has implemented ES6 imports yet either. So for now it's `Quill.import('formats/link');`

**Comment by maku** [comment]
@jhchen yes you are right, browsers don't suppport import. But that's why we have to use babel / typescript and so on...

**Comment by jhchen** [comment]
Yes not everyone is using Babel or Typescript. Many build systems are just using ES5.

**Comment by letanure** [comment]
Something like this

```
const Link = Quill.import('formats/link')
class linkType extends Link {
  static create (value) {
    let node = super.create(value)
    value = this.sanitize(value)
    if (validations.isNumeric(value)) {
      node.setAttribute('href', 'tel:' + value)
      node.className = 'link--tel'
    }
    if (validations.isEmail(value)) {
      node.setAttribute('href', 'mailto:' + value)
      node.className = 'link--mail'
    }
    if (value.startsWith('https://') || value.startsWith('http://')) {
      node.className = 'link--external'
    } else {
      node.removeAttribute('target')
    }
    return node
  }
}
Quill.register(linkType)
````

**Comment by Poky85** [comment]
In Link extension you have to add format() method. So link editing (not only creation) works https://codepen.io/Poky85/pen/PQoPrV

**Comment by cash0151** [comment]
If you also need to be able to format the link you have to make a small change to the solution given by poky85. https://codepen.io/anon/pen/VqdyVX

**Comment by loonydevil** [comment]
> Something like this
> 
> ```js
> const Link = Quill.import('formats/link')
> class linkType extends Link {
>   static create (value) {
>     let node = super.create(value)
>     value = this.sanitize(value)
>     if (validations.isNumeric(value)) {
>       node.setAttribute('href', 'tel:' + value)
>       node.className = 'link--tel'
>     }
>     if (validations.isEmail(value)) {
>       node.setAttribute('href', 'mailto:' + value)
>       node.className = 'link--mail'
>     }
>     if (value.startsWith('https://') || value.startsWith('http://')) {
>       node.className = 'link--external'
>     } else {
>       node.removeAttribute('target')
>     }
>     return node
>   }
> }
> Quill.register(linkType)
> ```

hey man, this one looks great. do you know how to do that in ES5 environment? :)

**Comment by Gladskih** [comment]
@Poky85
> In Link extension you have to add format() method. So link editing (not only creation) works
Could you explain please what exactly case will not work without format override?

**Comment by webberig** [comment]
I got this working in Typescript by simply using this:

```
const Link = Quill.import("formats/link");

class MyLink extends Link {
    static create(value) {
        const node = Link.create(value);
        value = Link.sanitize(value);
        node.setAttribute('href', value);
        node.removeAttribute('target');
        return node;
    }

    format(name, value) {
        super.format(name, value);
        this["domNode"].removeAttribute("target");
    }
}

Quill.register(MyLink);
```

**Comment by chriskuech** [comment]
This doesn't seem to be working anymore
