### ISSUE TITLE
How to set default values

### ISSUE THREAD

**Issue by mma7** [quilljs/quill#1140]
It will be really good if it possible to set default values to ql-format elements, for instance setting the default text direction to rtl, setting the default text alignment to center etc.
if the majority of my website users are arab so why not set the default text direction for them.
thanks

**Comment by jhchen** [comment]
Something like this? http://codepen.io/quill/pen/VmxKqM

**Comment by ddemolina** [comment]
Hello, 

How can i do to set default formats in this case?
I define a whitelist for color format.
Then I paste from outside quill a text which color aren't in the whilist. 
quill remove this color but how can i say to quill: "when remove a format which it's not in the whitelist put this default format value instead".

Thanks!

**Comment by devteam-pw** [comment]
you can default values in react quill by accessing ref object.

`this.state.ref.editor.format('header',2)
`
