### ISSUE TITLE
Small videos with no resize option?

### ISSUE THREAD

**Issue by rquast** [quilljs/quill#1141]
Trying to adjust the size of a video that you get from youtube and put into quill.

**Steps for Reproduction**

1. Visit youtube and find a video, then copy the url.
2. Visit quilljs.com, go to the editor and click the video icon. Paste the youtube url.
3. Small video.

**Expected behavior**:

Something a bit bigger, or resizable.

**Actual behavior**:

Something tiny.

**Platforms**:

Include browser, operating system and respective versions

Mac OS X, 10.12
Chrome 54 and Firefox 50

**Version**:

Latest one running on website

<img width="918" alt="screen shot 2016-11-28 at 1 02 00 pm" src="https://cloud.githubusercontent.com/assets/1103891/20655141/6598e590-b56b-11e6-9019-1c3b6fb90146.png">

**Comment by rquast** [comment]
how do we adjust the size of that iframe??

**Comment by artaommahe** [comment]
@rquast just add custom css for any styling or redefine Video blot with your custom params/classes/etc

**Comment by rquast** [comment]
@artaommahe Yeah I think I will have to redefine it. Also think I need to plug in my own dialogs for configuration. It's not practical for an end user without the ability for them to resize it.

**Comment by jhchen** [comment]
Videos (and images) understand the width and height format. So you can also call `formatText(0, 1, 'width', '400px');`.

**Comment by rquast** [comment]
I understand that you can code this yourself. Where is the GUI option for that without having to code a custom solution?

**Comment by rquast** [comment]
Sorry, specifically: Create a video properties popup that allows a user to change the size of the embedded iframe.

**Comment by rquast** [comment]
No longer interested in debating simple issues.

**Comment by tinhlv** [comment]
how do we adjust the size of that iframe??

**Comment by nfabacus** [comment]
I have the same issue.  @jhchen Could you help with more specifics?
Thank you.

**Comment by lancetipton04** [comment]
I added a little repo to allow video resize. I just started messing Quill this week so there may be better ways to do it, like make it a module. But it works so that's nice.
https://github.com/lancetipton04/quill-video-resize

**Comment by nfabacus** [comment]
@lancetipton Thank you for that.  I am not sure how I can use it in a react component.  I will also investigate...

**Comment by xoapit** [comment]
Does anyone have a solution for this problem in ReactJs?
