### ISSUE TITLE
Support High DPI image embedding

### ISSUE THREAD

**Issue by rquast** [quilljs/quill#1142]
Quill doesn't support High DPI images

**Steps for Reproduction**

1. Visit quilljs.com
2. Click the image button in the menu, select a high dpi image.
3. Image is twice the size of what it should be, since there is no flag for high dpi, or ability to adjust the image size that gets rendered by the browser.

**Expected behavior**:

Should support high dpi images, so it doesn't look pixelated on retina macs or high dpi windows pcs (like surface)

**Actual behavior**:

As discussed above.

**Platforms**:

All.

Include browser, operating system and respective versions

**Version**:

Latest on website.

**Comment by rquast** [comment]
This is a must for any modern website. You should always upload raster images at twice the resolution, but set the size to half. Either that or use SVG.

**Comment by jhchen** [comment]
Please provide a more specific and technical description for what "support high DPI images" means. Keep in mind Quill supports a wide variety of browsers so any suggestion must be implementable and supported by all platforms Quill supports.

**Comment by rquast** [comment]
It means that images you upload in don't display in high resolution on retina and high dpi displays. They look pixelated (unprofessional). If you want to learn more about this, wysiwyg editors such as webflow have this as a feature when you upload an image. Since an end user can't adjust any of the properties of the image that gets displayed, workaround code is needed.

**Comment by rquast** [comment]
An educational video on it: https://www.youtube.com/watch?v=yzLHswkUXJY

**Comment by jhchen** [comment]
I'm still looking for technical specifics. For example if we were talking about accessibility, it would be something like adding a aria-role attribute, not "make Quill more accessible" or "support screen readers".

**Comment by rquast** [comment]
<img width="476" alt="screen shot 2016-11-29 at 11 48 52 am" src="https://cloud.githubusercontent.com/assets/1103891/20693402/e682f902-b629-11e6-95b5-20fdde4584a2.png">

On a mac (with retina.. most macs these days), or a surface 4 pro (and a few other PCs), the left image is what a low resolution image looks like when the image width and height are set in the DOM.

If quill were to be used in a reputable blog, particularly a design blog where image quality mattered, people may point out the low quality images when they are viewed on a mac, etc.

I assume, since technology is getting better, that High DPI displays will become more frequently used. Being able to set the width and height in the DOM for the image is important for that reason.

**Comment by jhchen** [comment]
Yes I've owned a MacBook Retina since they came out years ago and currently have a 4k Dell monitor. I'm not asking about what high resolution images are or what kind of websites could benefit from showing high resolution images. Please re-read and reconsider my original question and following clarification.

**Comment by rquast** [comment]
The ability to change the width and height properties of the uploaded image?

**Comment by rquast** [comment]
Here is a mockup of what it could sort of look like (from webflow). 
<img width="354" alt="screen shot 2016-11-29 at 12 46 03 pm" src="https://cloud.githubusercontent.com/assets/1103891/20694572/eeb8a592-b631-11e6-862d-07feda23e9f2.png">
