### ISSUE TITLE
using third party text marking tools

### ISSUE THREAD

**Issue by olop01** [quilljs/quill#1147]
Third party plugins for text formatting won't work with QuillJS, even if they just try to change the HTML markup (adding a span around content which should be marked).

**Steps for Reproduction**

1. Setup QuillJS on a demo page
2. implement jQuery
3. implement mark.js or highlight.js
4. setup a keyword, which should be marked by the marker plugin
5. setup a button which calls the action to mark certain keyword

**Expected behavior**:
Keywords on the page will get marked correctly. Also Keywords found in the editor (typed by the user) will get marked.

**Actual behavior**:
Keywords on the page will get marked correctly. Keywords found in the editor will NOT get marked. If you look it up in the Inspector, the concerned lines will flash (to indicate there was something happening) but they won't get the span which is needed to mark the words.

**Platforms**:
Windows 7 Firefox & Chrome

**Version**:
Quill 1.1.5

**Demo page can be found here**
http://stackoverflow.com/questions/40869669/access-written-text-in-quilljs

**Comment by benbro** [comment]
Same question:
http://stackoverflow.com/questions/40869669/access-written-text-in-quilljs

**Comment by jhchen** [comment]
Duplicate content from StackOverflow
