### ISSUE TITLE
proper usage to obtain autosize editor

### ISSUE THREAD

**Issue by gotibhai** [quilljs/quill#1148]
I'm sorry, I've been fiddling with this problem for a long while. Can someone explain the proper usage to obtain autosize? Right now I have a Container div which gives the margins for my editor and no height property specified. I'm using the bubble theme where the ql-container class and ql-editor have height set to 100% ( by default).

Right now, After reaching about the 100% which is ~ 979px the scrollbar appears. I think this is because the container div isn't expanding. Any help would be appreciated! Thanks! @jhchen

**Comment by jhchen** [comment]
http://quilljs.com/playground/#autogrow-height
