### ISSUE TITLE
How to avoid extra lines to be inserted after headings?

### ISSUE THREAD

**Issue by ozanhazer** [quilljs/quill#1157]
Quill is adding an extra newline after headings when content is set.

See: https://jsfiddle.net/2kj4ezd4/

I added margins to p tags to make it more visible...

**Comment by jhchen** [comment]
This is because of the extra margins. Quill is expecting its paragraph tags to not have margins so when it sees content with spacing it tries to compensate visually by adding newlines.

**Comment by ozanhazer** [comment]
Well, this creates problems when the content is persisted. It keeps adding newlines every time the content is saved. I think spacing should not be adjusted by newlines, we have CSS for that, would be much flexible with CSS.

Or at least it should avoid adding more than one newline somehow...

**Comment by GoldenRust** [comment]
I'm having this same issue, when content inside the editor is styled new lines are being added.

Is there any solution/workaround for this, or do we just not add margins for now?

**Comment by tygeng** [comment]
Same here, any recommended workaround for this? In our system we have html stored in the db and we are calling dangerouslyPasteHTML to show the doc in Quill. But Quill keeps inserting newlines.

**Comment by GoldenRust** [comment]
@tygeng I've found that the styling can cause newlines to be added by the quill renderer.

In my tests if I've initialised quill starting from html where the p styles were `p{margin-bottom: 60px}`, an extra line would be added. I've not found any work around for this.

**Comment by emulbreh** [comment]
Here's a workaround that works for us:
```javascript
document.querySelectorAll('.ql-editor p > br:first-child:last-child').forEach((br) => {
    br.parentNode.remove();
});
```

**Comment by jhchen** [comment]
You can now configure the visual matching that adds the space in the most recent version of Quill 1.3.1: https://jsfiddle.net/zhmgLtuf/
