### ISSUE TITLE
Quill instance and complex Blots interaction

### ISSUE THREAD

**Issue by artaommahe** [quilljs/quill#1158]
There is two issues with complex Blots and Quill instance:
- accessing from Blot Quill instance options for readonly/smth else detection and proper markup creating
- updating Quill instance delta on inner changes (changed caption in `<textarea>` in further example)

There is some use-cases where some Blot should be displayed differently in edit and readonly modes or in other situations. And there is no way to pass quill instance options/state in blot create method for changing display markup for different cases.
Currently this can be achieved with ugly-hack: in Blot constructor check for `ql-disabled` class on parent editor node and change part of Blot DOM.

For second issue i cant find proper solution now - there is no access to quill instance methods and also test call `update()` on it does not trigger any Blot instance methods to update real blot value.

Real world example from our project - image/video blot with optional caption. This Blot extends BlockEmbed and represented by `div.article__figure`  with value object `{ src: string, caption?: string }`
```html
<div class="article__figure">
    <!-- wrapper with image or video here -->
    <div class="article__image">
        <img src="{{ src }}" />
    </div>

    <div class="article__caption">
        <!-- view mode only, created in static create() by default -->
        {{ caption }}
        <!-- edit mode only, replaces plain text in constructor() -->
        <textarea rows="1">{{ caption }}</textarea>
    </div>
</div>
```

Changing caption in textarea does not reflect on Quill instance Delta.

Such markup is used by [Telegraph](http://telegra.ph/), that uses Quill editor. On save they directly parse editor HTML and collect nodes, so they dont face with second issue. First issue they passed by editor node class check.

**Comment by benbro** [comment]
Please create two separate issues.

Please include a simple real world use case for rendering Blots in edit/readonly mode.
Adding CSS with the .ql-disabled class is probably the best solution. I don't think Quill should render a Blot differently in readonly mode.

Please simplify the description of your second issue.
Quill doesn't transform a textarea but a div.
Quill doesn't have two-way data bindings. It uses the markup inside the div to initialize the editor content.

**Comment by artaommahe** [comment]
@benbro created separate issues #1162 and #1163. Close this one.
