### ISSUE TITLE
Add support for code

### ISSUE THREAD

**Issue by jhchen** [quilljs/quill#116]
Could be just supporting `<code>` but may be possibilities for richer support for example with syntax highlighting.

**Comment by navneet35371** [comment]
+1

**Comment by scott** [comment]
+1

**Comment by Gregoor** [comment]
+1

**Comment by icarusion** [comment]
+1

**Comment by c0cky** [comment]
+1

**Comment by jhchen** [comment]
This has been added in the [beta](http://beta.quilljs.com/) release

**Comment by jamesgibson14** [comment]
I see that there is a module code-highlighter in the beta, how would we go about hightlight css or javascript?

**Comment by jhchen** [comment]
Docs will be filled out soon at http://beta.quilljs.com/docs/modules/code-highlighter/

**Comment by maz123** [comment]
+1

**Comment by mrmishmash** [comment]
+1

**Comment by joshoconnor89** [comment]
+1
