### ISSUE TITLE
Configured Clipboard matcher work but is ignored

### ISSUE THREAD

**Issue by berndschimmer** [quilljs/quill#1161]
My configured clipboard matcher work but is ignored. 

The "is working" is tested with chrome inspector by evaluation 
`return delta.compose(new Delta().retain(delta.length(), { h1: false }));`
while beeing in the context of pasting the h1.

**Steps for Reproduction**

1. Visit http://codepen.io/anon/pen/oYqbMG
2. Step Two
Paste Text with a h1 (from word or a html page)
3. Step Three
see, that the h1 is rendered in the editor

**Expected behavior**:
h1 should be stripped out

**Actual behavior**:
h1 is rendered. (and some empty space characters are inserted at the beginning of the editor when pasting word text)

**Platforms**:
Tested on Chrome 54, Safari 10 on Mac

**Version**:
1.1.5 and 1.1.3 (perhaps all?)

**Comment by benbro** [comment]
Use {header: false} instead of {h1: false}
http://codepen.io/anon/pen/jVzqmr

**Comment by berndschimmer** [comment]
thx!

**Comment by berndschimmer** [comment]
btw: is there a list for all html tags? next thing is that i want to strip <code> and I don't want to bother you again and again :-)

**Comment by benbro** [comment]
List of supported formats:
http://quilljs.com/docs/formats/

**Comment by benbro** [comment]
If you want to disable formats, using the 'formats' config option might be better:
http://quilljs.com/docs/configuration/#formats

**Comment by berndschimmer** [comment]
OK, thx!
It would be great if the header could be configured like in the toolbar {header: [2,3,false]}
