### ISSUE TITLE
Toolbar Not Showing Up

### ISSUE THREAD

**Issue by linusx** [quilljs/quill#1164]
I'm trying to use this in a meta box in a WordPress plugin. In my meta box code I have:
```<div id="quill-toolbar-container"></div><div id="quill-editor-container">```

In my JS I have: 
```
var options = {
            debug: 'info',
            modules: {
                toolbar: {
                    container: '#quill-toolbar-container',
                }
            },
            placeholder: 'Compose an epic...'
        };
        var editor = new Quill('#quill-editor-container', options);
```

In the code I see the toolbar container and the content is showing up, but non of the toolbar items are showing up.

**Version**:

1.1.5

**Comment by benbro** [comment]
If you are using your own toolbar container you also need to create the buttons inside it.
http://quilljs.com/docs/modules/toolbar/

View the source of this page as an example:
http://quilljs.com/standalone/full/

**Comment by linusx** [comment]
Thanks. The buttons are now showing up, but they are blank and don't do anything. BTW do you have a WordPress plugin to use Quill instead of TinyMCE?
![screen shot 2016-12-06 at 11 20 22 am](https://cloud.githubusercontent.com/assets/110362/20933481/2952b73c-bba6-11e6-89b7-ecffe9dac9bd.png)

**Comment by benbro** [comment]
Are you missing quill.snow.css?
Please fork the [codepen](http://codepen.io/quill/pen/KzZqZx) and show your code.

I'm not familiar with a WordPress plugin.

**Comment by linusx** [comment]
It's a little difficult to follow to change the editor in WordPress, but quill.snow.css, katex.min.css, and monokai-sublime.min.css is being included. Also the following JS is being included: katex.min.js, highlight.min.js, quill.min.js. I'm not seeing any JS errors. Here is my code:

```<div id="standalone-container">
			<div id="toolbar-container">
		<span class="ql-formats">
		<select class="ql-font"></select>
		<select class="ql-size"></select>
		</span>
				<span class="ql-formats">
		<button class="ql-bold"></button>
		<button class="ql-italic"></button>
		<button class="ql-underline"></button>
		<button class="ql-strike"></button>
		</span>
				<span class="ql-formats">
		<select class="ql-color"></select>
		<select class="ql-background"></select>
		</span>
				<span class="ql-formats">
		<button class="ql-script" value="sub"></button>
		<button class="ql-script" value="super"></button>
		</span>
				<span class="ql-formats">
		<button class="ql-header" value="1"></button>
		<button class="ql-header" value="2"></button>
		<button class="ql-blockquote"></button>
		<button class="ql-code-block"></button>
		</span>
				<span class="ql-formats">
		<button class="ql-list" value="ordered"></button>
		<button class="ql-list" value="bullet"></button>
		<button class="ql-indent" value="-1"></button>
		<button class="ql-indent" value="+1"></button>
		</span>
				<span class="ql-formats">
		<button class="ql-direction" value="rtl"></button>
		<select class="ql-align"></select>
		</span>
				<span class="ql-formats">
		<button class="ql-link"></button>
		<button class="ql-image"></button>
		<button class="ql-video"></button>
		<button class="ql-formula"></button>
		</span>
				<span class="ql-formats">
		<button class="ql-clean"></button>
		</span>
			</div>
			<div id="editor-container"></div>
		</div>
		<script type="text/rocketscript">
		  var quill = new Quill('#editor-container', {
		    modules: {
		      formula: true,
		      syntax: true,
		      toolbar: '#toolbar-container'
		    },
		    placeholder: 'Compose an epic...',
		    theme: 'snow'
		  });
		</script>```

**Comment by benbro** [comment]
A [working example](http://codepen.io/anon/pen/gLzmXo) of a toolbar container.
Compare with your code and find what is missing.

**Comment by linusx** [comment]
I was finally able to get it to show the toolbar. Thanks for the help. Now I'm trying to save it to the DB. Do you have examples of getting the formatted html to save it to the database?

**Comment by ergo** [comment]
@linusx as far as i can tell quill doesn't expose any api for that and the makers don't plan this to change.

**Comment by pravinpokharkar** [comment]
You need to import the quill theme CSS and core CS on your own. Import the CSS Files in your CSS/scss or If you are using angular+cli add them to Styles in the angular CLI json. Or simply load them in your index.HTML. check my demo repo for an example put: ``` @import '~quill/dist/quill.core.css'; @import '~quill/dist/quill.bubble.css'; @import '~quill/dist/quill.snow.css'; ``` at the beginning of your styles.(s)css to get the quill styles globally or only in the (s)css file of a specific component
