### ISSUE TITLE
Drag and Drop is not supported for videos

### ISSUE THREAD

**Issue by olop01** [quilljs/quill#1167]
I was trying to insert a video and adjust its position by dragging it around in the text. This does not work for videos, but for images.

**Steps for Reproduction**
1. Insert a video by using the "add video" button.
2. Try dragging it to another position in the text.

**Expected behavior**:
Change video position in the text by dragging it (like images)

**Actual behavior**:
Nothing happens.

**Platforms**:
Windows 7 Chrome & FF

**Version**:
1.1.5

**Comment by jhchen** [comment]
Yes video drag and drop is not a feature of Quill. If you'd like to request it, please create a [feature request](https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#feature-requests).

**Comment by nelsonpecora** [comment]
What actually makes the image draggable? Is it only allowed on certain Inline blots, or is there something specific to images? I don't see anything in the [image format](https://github.com/quilljs/quill/blob/66c9a57af849ac8dd87f23d72fa43d1e1c6047ce/formats/image.js), or in Parchment.

Is it piggybacking off the browser's native drag+drop for contenteditable images?

**Comment by jhchen** [comment]
Yes it is a part of native contenteditable.
