### ISSUE TITLE
Add 'self' value to bounds config.

### ISSUE THREAD

**Issue by weavermedia** [quilljs/quill#1168]
FR: **Enable passing `'self'` to `bounds` config.**

If I'm passing the Quill editor into the `bounds` config how about being able to pass a string like `'self'`instead of having to re-specify the same DOM element?

Instead of this:
```
var quill = new Quill('#quill-editor', {
  modules: {toolbar: [ 'bold', 'italic', 'underline' ]},
  bounds: document.getElementById('#quill-editor')
});
```
something like this:
```
var quill = new Quill('#quill-editor', {
  modules: {toolbar: [ 'bold', 'italic', 'underline' ]},
  bounds: 'self'
});
```

**Comment by jhchen** [comment]
Looks like I need to update the docs but you can also pass in a selector so this works:

```js
var quill = new Quill('#quill-editor', {
  modules: {toolbar: [ 'bold', 'italic', 'underline' ]},
  bounds: '#quill-editor'
});
```

I think the concept of something to mean "within itself" would be beneficial but I don't like using a [magic](https://en.wikipedia.org/wiki/Magic_number_(programming)) value. If there is a way to obtain the former without the latter we can reconsider.

**Comment by weavermedia** [comment]
Great, that works. Thanks.

I understand, and agree, you don't want to use a magic string like `'self'`. In Ruby I'd suggest `:self` as a symbol. Passing the same selector is very reasonable though.
