### ISSUE TITLE
Error building quilljs for development locally

### ISSUE THREAD

**Issue by justiceo** [quilljs/quill#1174]
Running the command 'npm run build' throws an error with webpack.

Below is the full error log:

====== Begin Error ======
webpack --config _develop/webpack.config.js; rm dist/quill.core dist/quill.bubble dist/quill.snow;

module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Users\Me\Code\Redactor\quill2\_develop\webpack.config.js;'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\Users\Me\Code\Redactor\quill2\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (C:\Users\Me\Code\Redactor\quill2\node_modules\webpack\bin\webpack.js:39:40)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! quill@1.1.6 build: `webpack --config _develop/webpack.config.js; rm dist/quill.core dist/quill.bubble dist/quill.snow;`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quill@1.1.6 build script 'webpack --config _develop/webpack.config.js; rm dist/quill.core dist/quill.bubble dist/quill.snow;'.
npm ERR! This is most likely a problem with the quill package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config _develop/webpack.config.js; rm dist/quill.core dist/quill.bubble dist/quill.snow;
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs quill
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls quill
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Me\Code\Redactor\quill2\npm-debug.log

====== End Error ======

When I run the culprit commands `webpack --config _develop/webpack.config.js; rm dist/quill.core dist/quill.bubble` , they succeed however.

**Steps for Reproduction**

1. Cone quilljs master from github.com/quilljs/quilljs
2. Confirm npm and ruby is installed and up to date
3. run 'npm install' - which should complete successfully
4. run 'gem ....' which should complete successfully
5. run 'npm run build' and the error above should happen

**Expected behavior**:
The source should be compiled to a dist directory and a server started at localhost for accessing the examples

**Actual behavior**:
The build doesn't complete

**Platforms**:
Tried both widows and linux.

**Version**:
Fresh installs of nodejs, npm, and ruby gem

**Comment by jhchen** [comment]
From the error message: 

```
Error: Cannot find module 'C:\Users\Me\Code\Redactor\quill2_develop\webpack.config.js;'
```

It seems the problem is the path is being concatenated into `quill2_develop`. Why this is happening on Windows I'm not sure. I spun up a DigitalOcean instance of Ubuntu 16.04 and everything builds as expected.

**Comment by justiceo** [comment]
Yes I tried it on Ubuntu 16 and it worked as well. But why not Ubuntu 14 and Windows (10)

**Comment by jhchen** [comment]
Ubuntu 14.04 on a fresh DigitalOcean instance works for me too.

**Comment by justiceo** [comment]
Okay, here is the ubuntu error log

```
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! quill@1.1.6 start: `npm run build; foreman start -f _develop/procfile`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the quill@1.1.6 start script 'npm run build; foreman start -f _develop/procfile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the quill package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build; foreman start -f _develop/procfile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs quill
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls quill
npm ERR! There is likely additional logging output above.
```

**Comment by jhchen** [comment]
What happens when you run `which node`?

**Comment by justiceo** [comment]
`$which node` returns /usr/bin/node
`$/usr/bin/node` returns v6.9.2

**Comment by jhchen** [comment]
Can you post the output for `npm run build`. If that fails can you also post the output for `./node_modules/.bin/webpack --config _develop/webpack.config.js`

**Comment by saitai0802** [comment]
I have the same issues as well... any solutions?

**Comment by saitai0802** [comment]
my error is 
Error: Cannot find module 'C:\Users\Me\Code\Redactor\quill\_develop\webpack.config.js;'

**Comment by saitai0802** [comment]
When I tried to install those dependence, I got this error.
npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by adeguntoro** [comment]
still not solved ? because i have same issue.

**Comment by laszlo-tenki** [comment]
Same here. No wonder it doesn't find the webpack.config.js file as the entire _develop directory is missing.
`Error: Cannot find module '/Users/msh/Documents/projects/mindscope/node_modules/quill/_develop/webpack.config.js'`
I installed Quill as a node module (current, 1.3.6) with a simple npm i quill --save.

Is the _develop directory supposed to be in there?
