### ISSUE TITLE
Can't import quill modules in build process

### ISSUE THREAD

**Issue by CoenWarmer** [quilljs/quill#1175]
I'm trying to build a module that extends the Quill editor, and integrate it with my project.

When I try to import specific Quill modules within my custom Quill module, webpack throws an error:

```
Uncaught Error: Cannot find module "quill/core/quill"
    at webpackMissingModule (QuillLinkTooltip.js:15)
    at eval (QuillLinkTooltip.js:15)
```

and then later on:

```
./~/quill/core/quill.js
Module parse failed: /Users/path_to_my_app_folder/node_modules/quill/core/quill.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import './polyfill';
| import Delta from 'quill-delta';
| import Editor from './editor';
```

Here's an excerpt from the custom Quill module that I am building and that throw errors:

```
import Quill from 'quill/core/quill';
import { Range } from 'quill/core/selection';
import Keyboard from 'quill/modules/keyboard';
import LinkBlot from 'quill/formats/link';
import Tooltip from 'quill/ui/tooltip';
```

I am using Webpack, babel and babel es2015 preset within my project. I can import other node modules such as lodash by using something like `import get from 'lodash/get';`.

I'm suspecting webpack can find the module, but is having difficulty in parsing it. Here's an excerpt of my webpack.config.js file:

```
module: {
    loaders: [
        {
            test: /.*\.js$/,
            loader: 'babel-loader',
            exclude: [ /node_modules/, /frontend/ ],
            query: {
                presets: [ 'babel-preset-es2015' ].map(require.resolve),
                plugins: [ 'babel-plugin-add-module-exports' ].map(require.resolve)
            }
        },

```

I've read [https://quilljs.com/guides/adding-quill-to-your-build-pipeline/](https://quilljs.com/guides/adding-quill-to-your-build-pipeline/) which mentions that Webback, Babel and Babel ES2015 preset are needed, so it seems I have the right webpack setup. But maybe I'm missing something?

**Steps for Reproduction**

See above

**Expected behavior**:

Importing Quill modules works correctly.

**Actual behavior**:

Webpack refuses to import Quill modules.

**Platforms**:

MacOS.

**Version**:

Quill 1.1.5

**Comment by CoenWarmer** [comment]
Managed to get this to work. Turned out my webpack.config.js file was excluding node_modules from the babel-loader definition, so Webpack would try to resolve quill files placed in /node_modules, but wouldn't be able to parse them as they were excluded from the babel-loader.

Fixed it by adding an exception to my exclude statement:

```
	module: {
		loaders: [
			{
				test: /.*\.js$/,
				loader: 'babel-loader',
				exclude: [ /node_modules(?!\/quill)/, /frontend/ ],
				query: {
					presets: [ 'babel-preset-es2015' ].map(require.resolve),
					plugins: [ 'babel-plugin-add-module-exports' ].map(require.resolve)
				}
			},
```

**Comment by robertlight** [comment]
I don't have a webpack.config.js but I am getting the following error:

can you give me the full webpack.config.js that you are using??

```
Failed to compile.

./node_modules/quill/themes/bubble.js 13:18
Module parse failed: Unexpected token (13:18)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| }, 'blockquote']];
| class BubbleTooltip extends BaseTooltip {
>   static TEMPLATE = ['<span class="ql-tooltip-arrow"></span>', '<div class="ql-tooltip-editor">', '<input type="text" data-formula="e=mc^2" data-link="https://quilljs.com" data-video="Embed URL">', '<a class="ql-close"></a>', '</div>'].join('');
|   constructor(quill, bounds) {
|     super(quill, bounds);
```
