### ISSUE TITLE
when open text alignment label, the selectedIndex always be 0

### ISSUE THREAD

**Issue by JoenZhu** [quilljs/quill#1177]
text alignment cannot select the first option.
I'm using `npm install quill` in my project. 
After installed, I found a different between path module/toolbar.js and dist/quill.js
in path modules/toolbar.js line 114
```
let option;
if (range == null) { // different
  option = null;
} else if (formats[format] == null) { 
  option = input.querySelector('option[selected]');
} else if (!Array.isArray(formats[format])) {
  let value = formats[format];
  if (typeof value === 'string') {
    value = value.replace(/\"/g, '\\"');
  }
  option = input.querySelector(`option[value="${value}"]`);
}
```
but in path dist/quill.js line 9116
```
var option = void 0;
if (range == null || formats[format] == null) {  // different
  option = input.querySelector('option[selected]');
} else if (!Array.isArray(formats[format])) {
  var value = formats[format];
  if (typeof value === 'string') {
    value = value.replace(/\"/g, '\\"');
  }
  option = input.querySelector('option[value="' + value + '"]');
}
```
the condition of option's assignment is different.

And I also try a example using cdn
```
<link href="https://cdn.quilljs.com/1.1.6/quill.snow.css" rel="stylesheet">
<script src="https://cdn.quilljs.com/1.1.6/quill.js" type="text/javascript"></script>
```
I found in cdn line 9114
```
var option = void 0;
if (range == null) {
  option = null;
} else if (formats[format] == null) {
  option = input.querySelector('option[selected]');
} else if (!Array.isArray(formats[format])) {
  var value = formats[format];
  if (typeof value === 'string') {
    value = value.replace(/\"/g, '\\"');
  }
  option = input.querySelector('option[value="' + value + '"]');
}
```
it's the same as in path module/toolbar.js .

so, what my found is: 
1, When using cdn, it's OK.
2, When using `npm install quill`, it's not OK. 
3, But if you change the code in dist/quill.js line 9116 to the same as in cdn line 9114, it's OK too.

so, I'm wondering if there is anything wrong with these code.

**Steps for Reproduction**

1. Add `[{align: [false, 'right', 'center', 'justify']}]` to toolbar
2. select one option in align dropdown list, then close options 
3. reopen the align dropdown list, found that the first option always in selected state (which is value `false` option), so you cannot select the first option again.

**Expected behavior**:
when reopen the align dropdown list, the selected option will remove or remember the last selected option
**Actual behavior**:
the first option always in selected state
**Platforms**:
macOS Sierra, Chrome 55.0.2883.87 (64-bit)

**Version**:
quill v1.1.6

**Comment by jhchen** [comment]
[This](http://codepen.io/quill/pen/mOGogg) using v1.1.6 seems to be working fine. The code differences look like a difference in versions.

**Comment by JoenZhu** [comment]
@jhchen both the cdn and `npm install` is version 1.1.6
