### ISSUE TITLE
Typing using Chinese IME only inserts the English character and the IME's popup appears and disappears in a flash.

### ISSUE THREAD

**Issue by f15gdsy** [quilljs/quill#1178]
Typing using Chinese IME only inserts the English character and the IME's popup appears and disappears in a flash.

**Steps for Reproduction**

1. Visit http://quilljs.com/playground/
2. Type some Chinese words using Chinese IME
3. Press return button for new lines
4. Type some Chinese words using Chinese IME again
5. Go back to the first line to type some Chinese words and the problem appears.

**Expected behavior**:
The Chinese words are input as usual and the IME popup won't automatically disappear when I type a character.

**Actual behavior**:
Only the English characters are inserted, and the IME popup appears and disappears automatically in a flash.

**Platforms**:
- OS: OS X EI Capitan 10.11.6 (15G31)
- Browser: Chrome Version 54.0.2840.98 (64-bit)
- Chinese IME: The default simplified Chinese input IME in Mac OS X EI Capitan 10.11.6

**Version**:
Quill 1.1.6

**Comment by f15gdsy** [comment]
A screenshot of what the bug is.

![quill-bug](https://cloud.githubusercontent.com/assets/1439942/21095221/6f826330-c095-11e6-8e8d-5350aa367310.gif)

**Comment by f15gdsy** [comment]
Strangely, it works fine in [form submit playground](http://quilljs.com/playground/#form-submit)

**Comment by jhchen** [comment]
Can anyone else reproduce this? I'm not able to on Chrome 54.0.2840.98 on Sierra 10.12.1 with Quill 1.1.16.
