### ISSUE TITLE
Content Folding

### ISSUE THREAD

**Issue by matthiasg** [quilljs/quill#1179]
Is there a way to perform code/text/content folding based on e.g. `highlight.js` inside of quill ? I could not find a straightforward way using the standard API yet. I did try to ask on http://stackoverflow.com/questions/41019824/region-folding-with-quill but the question wasn't received well it seems.

if this is something quill doesn't want to address that is fine of course, but considering the great flexibility already contained in it, it would enable a number of use cases.

**Comment by jhchen** [comment]
Quill does not support content folding as it is primarily a rich text editor that recognizes code snippets but is not a full blown code editor itself. It does not look like highlight.js supports content folding either.

**Comment by matthiasg** [comment]
thanks for the update. That means we are still stuck with two text editors in our environment :) But I would not have wanted quill to directly implement that anyway , just wanted to know whether rendering content in lines and then selectively hiding sections of those was something quill might be offering somehow.

**Comment by mbilliodeaux** [comment]
Pretty disappointing that the issue @matthiasg opened wasn't even entertained as either:
1. a future feature/module released by Quill
2. a module that @matthiasg could have developed with a little generous guidance from the quill team

seems like if the quill team would have played nicer, he might have shared code he developed with quill and other users...expensive #OpportunityCost due to poor customer management

**Comment by matthiasg** [comment]
@mbilliodeaux thanks for the support :) 

Of course I would have shared that back indeed. A problem with using other peoples base libraries such as Quill here, is that it is difficult to judge how hard a required feature would be to implement on top, and whether it aligns in any way with the existing architecture. Someone directly involved in the project can often judge on the feasibility within seconds. That is why I opened the ticket.

I read @jhchen's feedback as they do not see quill to ever go into this direction or offer any low level extensibilty that would allow for that. This could be because the editor does not, architecturally, think in lines just spans for example which used to limit a feature like that (Of course nowadays code-folding is not really line based anymore anyway).

In general the project is not very active code wise it seems, which is fine if it fulfills Slab's requirements.
