### ISSUE TITLE
Add support for nested lists/bullets and indents

### ISSUE THREAD

**Issue by jhchen** [quilljs/quill#118]

**Comment by matthewsot** [comment]
Hello! Is anyone currently working on this?

It's a fairly important feature for a site I'm working on to have indented bullets, and Quill seems to fit every other requirement I have for an editor.

If nobody else is working on it I'd love to give this a go myself, though being new to the Quill source I'd appreciate any pointers :)

**Comment by jhchen** [comment]
I don't know of anyone working on this so feel free to have a shot at it. I will warn you it would probably touch a lot of internals and the format system is currently being reimplemented to support custom formats.

**Comment by kishorenc** [comment]
This is the only feature preventing me from using Quill. I maintain a project used by many writers and researchers, and this is definitely a very important feature for them. How difficult would this be to implement?

**Comment by jhchen** [comment]
It's very difficult to do correctly and semantically; many other editors simply end up taking shortcuts. The ongoing work on custom formats will provide a much better foundation to implement complex formats like tables and nested lists.

**Comment by scamden** [comment]
@jhchen +1 here, are you close on custom formats?

**Comment by whather** [comment]
+1, we'd love this

**Comment by mschrepel** [comment]
+1 for me too. I miss this feature desperately.

**Comment by FredKSchott** [comment]
+1 would love this. @jhchen how is the work on custom formats going? Is there a way to do this independently of that work? I might be able to take a crack at it.

**Comment by wdamien** [comment]
+1, for nested lists
and another +1 for tables

**Comment by michael-ts** [comment]
Why won't ExecCommand work for indention?  I tried this code:
    document.execCommand('indent',false,null)

And it appears to momentarily indent, but then it reverts back to the un-indented form.  Is there something in Quill that is detecting and resisting this attempt?

**Comment by JewelsJLF** [comment]
+1, I really want to use quill, as so far it seems lightweight, easy to use, with a modern design.  However, I really need it to be able to indent and support nested ordered lists or it's a non-starter.

**Comment by romainbessugesmeusy** [comment]
+1 here !

**Comment by jhchen** [comment]
This has been added in the [beta](http://beta.quilljs.com/) release

**Comment by LeZuse** [comment]
@jhchen Any plans to also parse nested lists from the clipboard?

**Comment by benbro** [comment]
@LeZuse are you referring to this issue?
https://github.com/quilljs/quill/issues/673

**Comment by LeZuse** [comment]
@benbro Yes, that's indeed the same issue. I have this problem with pasting from GDocs. Thanks for the link.

**Comment by AyushiBShah** [comment]
@jhchen,@community : Anywhere I could find something on custom image bullets ?
