### ISSUE TITLE
Quill text editor not working - display issues

### ISSUE THREAD

**Issue by dheerajsk** [quilljs/quill#1180]
Using quill quickstart guide I am trying to use quill text editor.

Below is the code.

```
<html>
<head>
    <title></title>
  <link href="https://cdn.quilljs.com/1.1.6/quill.snow.css" rel="stylesheet">
        <script src="Scripts/jquery-3.1.1.min.js"></script>
    <script src="Scripts/jquery-3.1.1.js"></script>
   <script src="https://cdn.quilljs.com/1.1.6/quill.js"></script>

<!-- Initialize Quill editor -->
<script>
    var quill = new Quill('#editor', {
        theme: 'snow'
    });
</script>
    <style>

        #editor-container {
  height: 375px;
}
        </style>

</head>
<body>
<!-- Create the editor container -->
<div id="editor">
  <p>Hello World!</p>
  <p>Some initial <strong>bold</strong> text</p>
  <p><br></p>
</div>

</body>
</html>
```

**But I am not getting expected output. Ouput I am getting is below:** 

Hello World!
Some initial **bold** text

What am I missing?

Thanks for your help.

I have also raised this on stackoverflow.
http://stackoverflow.com/questions/41096017/quill-text-editor-not-working/41096383#41096383

**Comment by nikparo** [comment]
I've answered on stackoverflow.
http://stackoverflow.com/questions/41096017/quill-text-editor-not-working/41105266#41105266
(Quill initialized before the container existed.)
