### ISSUE TITLE
Specifying a Class Attributor with one of predefined Blot names breaks formatting

### ISSUE THREAD

**Issue by voroshkov** [quilljs/quill#1182]
I create new Calass Attributor with the class name that matches one of the predefined blot names ('text', 'block', 'scroll', etc from here: https://github.com/quilljs/parchment/tree/master/src/blot) like this:

`const myColor = new Parchment.Attributor.Class(
    'bcolor', 
    'text', 
    {  scope: Parchment.Scope.INLINE,
       whitelist: ['a', 'b', 'c']
    }
);`

then register with Quill and use it in toolbar.

See codepen: http://codepen.io/anon/pen/dOqZLQ

Then in runtime I apply this class to entered text like this:
1. Enter a row of characters in quill editor
2. Select the entire row and apply class 'text-a' by selecting "a" in the toolbar
3. Select a couple of characters in the middle of the row and apply 'text-b' by selecting "b" in the toolbar 

Expected behavior: I have 3 formatted spans:
```
<p>
<span class="text-a">ssssssss</span>
<span class="text-b">ss</span>
<span class="text-a">ssssssss</span>
</p>
```

Actual behavior: Last span is not formatted:
```
<p>
<span class="text-a">ssssssss</span>
<span class="text-b">ss</span>
sssssss
</p>
```

Windows 10
Browser: Chrome v 55.0.x
Quill version: 1.1.6

**Comment by jhchen** [comment]
Yes Attributors and Blots share a namespace. Please name your custom attributor something else.
