### ISSUE TITLE
Cursor not updating when writing just before a custom inline embed

### ISSUE THREAD

**Issue by emanuelbsilva** [quilljs/quill#1183]
Hi,

I'm using a custom inline embed (an hashtag in the example beneath) and when trying to write text just before the embed, the cursor position is not being updated.

**Steps for Reproduction**

1. Visit http://codepen.io/emanuelbsilva/pen/gLdXyV
2. Position the cursor (using mouse or arrow keys) just before the hashtag, at index 4.
3. Start writing.

**Expected behavior**:
The cursor should be updated with every key press, always staying after the last entered char.

**Actual behavior**:
The cursor is always at the original position, only being updated when either using the arrow keys or clicking in another place with the mouse .

**Platforms**:
Chrome 55.0.2883.75 (OSX)

**Version**:
Quill 1.1.6

**Comment by jhchen** [comment]
This appears to have been fixed in the latest version of Quill.
