### ISSUE TITLE
How to clear text formatting on paste

### ISSUE THREAD

**Issue by fpavlic** [quilljs/quill#1184]
Hi,

Short question, is there a way to clear content before pasting?
I do not want user to paste html content with different style, but want him to keep bullets, indent etc...

Thanks

**Comment by jhchen** [comment]
For custom paste behavior you can either supply the appropriate [matchers](http://quilljs.com/docs/modules/clipboard/), or supply your own clipboard [module](http://quilljs.com/docs/modules/#extending).

**Comment by fpavlic** [comment]
Thank you for quick reply

**Comment by gileneusz** [comment]
Hi, I'm trying to configure matcher of clipboard module  (for clearing formatting on paste) in my editorOption but without success. It would be much easier to see any example on documentation on this particular case because. It would be very helpful for many beginners like me - beacuse it's not easy to do at first time... :)

**Comment by talik077** [comment]
I agree. I am trying too to set matcher do clean clipboard styling but I can't get any success. 
Could you show us please an example of how doing this? 
this is what I tried: 

`vm.quillEditor.clipboard.addMatcher(Node.TEXT_NODE, function (node) {
                        return new Delta().insert(node.data);
 });`

Thanks!

**Comment by visualjerk** [comment]
This works quite well for me:

```javascript
this.quill.clipboard.addMatcher(Node.ELEMENT_NODE, (node, delta) => {
  delta.ops = delta.ops.map(op => {
    return {
      insert: op.insert
    }
  })
  return delta
})
```

The only issue that is still remaining is the ability to paste iframes. Has anyone got a solution to this?

**Comment by ryanhaney** [comment]
How about this?

https://gist.github.com/ryanhaney/d4d205594b2993224b8ad111cebe1a13

**Comment by sandroden** [comment]
@ryanhaney I have tried your solution but probably didn't understand how to apply, the toolbar and the editro disappeard... I'm from whithin vuejs so I initialized as follows:

```js
import Quill from 'quill'
import VueQuillEditor from 'vue-quill-editor'

Quill.register('modules/clipboard', PlainClipboard, true)
Vue.use(VueQuillEditor, {
  format: ['bold', 'italic', 'list', 'header'],
  theme: 'snow',
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'list'],
      [{ list: 'bullet' }],
    ],
  },
})
```
and the editor that was as this:

![immagine](https://user-images.githubusercontent.com/752776/50628338-00f2ad00-0f38-11e9-948e-f11589dfbd9f.png)

turned into this:

![immagine](https://user-images.githubusercontent.com/752776/50628389-36979600-0f38-11e9-92c6-d674d5f5da4e.png)

Does this say anything to you? does yout snippet also strip bold and italics ofr just colors and fonts? I'd rather keep bold and italics as thoso are legitimate in my contest.

**Comment by ryanhaney** [comment]
My snippet strips all formatting when content is pasted.

I suspect `vue-quill-editor` is doing something not desired.

Check out this jsfiddle: https://jsfiddle.net/hmfgvwx5/

**Comment by sandroden** [comment]
On Thu, Jan 03, 2019 at 10:06:03AM -0800, ryanhaney wrote:
>    My snippet strips all formatting when content is pasted.
>
>    I suspect vue-quill-editor is doing something not desired.
>
>    Check out this jsfiddle: [1]https://jsfiddle.net/hmfgvwx5/

Mmh, this fiddleseems totally empty... didn't youforget saving?

sandro
*:-)

**Comment by ryanhaney** [comment]
My bad. Updated: https://jsfiddle.net/hmfgvwx5/1/

**Comment by nirvana72** [comment]
if i want to remain the img tag, how to modify? thanks

**Comment by rtpHarry** [comment]
It would help to post more code examples to the documentation. For me, I was interested to strip everything but a certain whitelisted set of tags but it's not intuitive what I should do from this or the linked documentation.

I think for casual users it's a lot of inner concepts that need to be understood.

From what I'm reading it sounds like the matchers is more like playing whack a mole. You can paste in any amount of html and then you can write specific ones to swap `b` for `strong`, or blanket destroy all formatting. 

For a simple integration where you might just have b, i, quote, list, numbered list, in the toolbar you would want to strip everything but those tags. I can't see a way of doing that.

**Comment by JxDarkAngel** [comment]
I encapsulate the component in a div and use the onPaste event and generate a node and insert it. Could be another alternative.

`    <div
                onPaste={(event) => this.onPaste(event)} ...`

Code event:
 
```
     onPaste(event) 
     {
        var brRegex = /\r?\n/g;
        let paste = (event.clipboardData || window.clipboardData).getData('text/plain');
        let divText = paste.split(brRegex)

        const selection = window.getSelection();
        if (!selection.rangeCount)
            return false;

        let div = document.createElement('div');
        divText.forEach(text =>
        {
            div.appendChild(document.createTextNode(text));
            div.appendChild(document.createElement("br"));
        });

        selection.deleteFromDocument();
        selection.getRangeAt(0).insertNode(div);

        event.preventDefault();
     }
```

**Comment by Artem-Schander** [comment]
Hi everyone,
based on some of your ideas i created a plugin, that removes all tags and attributes that are not supported. Out of the box it detects that by looking into the toolbar module, but it can also be configured manually.
I thought I post it here so others will not have to struggle :)

https://www.npmjs.com/package/quill-paste-smart

**Comment by massan0314** [comment]
Hello everyone,
I had the same problem with the editor and found an easy solution for my case:

In the "formats" option I define the formats I want to allow in general to my editor.
These are the formats I want the user to be able to use on text in the editor. 
Other formats are automatically removed when pasted into the editor.

After that I added clipboard matchers in the options which remove the previous allowed formats when pasting into the editor.
Works great for me. 
All formats to set false or true are listed on this page: [Quill formats](https://quilljs.com/docs/formats/)

I hope this helps someone.

`	
		
                    var Delta = Quill.import('delta');
			var editor = new Quill('#' + element_id, {
				formats: [
					'bold',
					'strike',
					'underline',
					'color',
					'background'
				],
				modules: {
					toolbar: [
						['bold', 'strike', 'underline'],     
						[{ 'color': [] }, { 'background': [] }]
					],
					clipboard: {
						matchers: [
							[ Node.ELEMENT_NODE, function(node, delta) {
								return delta.compose(new Delta().retain(delta.length(), 
								{ color: false,
								  background: false,
								  bold: false,
								  strike: false,
								  underline: false
								}
								));
							  }
							] 
						]
					}
				},
				placeholder: "ここにメモを入力",
				theme: "snow"
			});`

**Comment by raisusmita** [comment]
> How about this?
> 
> https://gist.github.com/ryanhaney/d4d205594b2993224b8ad111cebe1a13
> 
> ```js
> import Quill from 'quill'
> const Clipboard = Quill.import('modules/clipboard')
> const Delta = Quill.import('delta')
> 
> class PlainClipboard extends Clipboard {
>   onPaste (e) {
>     e.preventDefault()
>     const range = this.quill.getSelection()
>     const text = e.clipboardData.getData('text/plain')
>     const delta = new Delta()
>     .retain(range.index)
>     .delete(range.length)
>     .insert(text)
>     const index = text.length + range.index
>     const length = 0
>     this.quill.updateContents(delta, 'silent')
>     this.quill.setSelection(index, length, 'silent')
>     this.quill.scrollIntoView()
>   }
> }
> 
> export default PlainClipboard
> ```

Hello @prodrammer, I tried using your code but this.quill.getSelection() returns null value every time I paste the content.

**Comment by m-demydiuk** [comment]
For quill version 2.0.0-dev.4 I used this code
```js
import Quill from 'quill'
const Clipboard = Quill.import('modules/clipboard')
const Delta = Quill.import('delta')

class PlainClipboard extends Clipboard {
    onPaste(range, { text }) {
        const delta = new Delta()
            .retain(range.index)
            .delete(range.length)
            .insert(text);
        this.quill.updateContents(delta, Quill.sources.USER);
        this.quill.setSelection(
            delta.length() - range.length,
            Quill.sources.SILENT,
        );
        this.quill.scrollIntoView();
    }
}

export default PlainClipboard
```

and then register it as
```js
import PlainClipboard from "./modules/PlainClipboard";
Quill.register(
  {
    "modules/clipboard": PlainClipboard,
  },
  true
);
```

**Comment by vansu99** [comment]
> Hi everyone, based on some of your ideas i created a plugin, that removes all tags and attributes that are not supported. Out of the box it detects that by looking into the toolbar module, but it can also be configured manually. I thought I post it here so others will not have to struggle :)
> 
> https://www.npmjs.com/package/quill-paste-smart

Hi, Does the package support Nextjs?

**Comment by Artem-Schander** [comment]
@vansu99 
It's a bit off topic and you could've asked at the linked repo.. but I see no reason why it would not run on Next.js
I never used it that way though.

**Comment by madhuriy7** [comment]
@vansu99  @Artem-Schander  I tried in next js but **quill-paste-smart** isn't working.

for react-quill import I tried dynamic import like this

`const ReactQuill = dynamic(() => import('react-quill'), { ssr: false });`

but **quill-paste-smart** not sure about how to import this cause Ii tried importing in dynamic way as above but throws error.

Any help for this will be highly appreciated. Thanks in advance.

**Comment by Wagratom** [comment]
Com muito esforço conseguir pelo js

quill.clipboard.addMatcher(Node.ELEMENT_NODE, function(node, delta) {
				if (node.children.length > 0) { //opcional
					node.textContent += '\n'
				}
				return new Delta().insert(node.textContent);
			});

**Comment by loktar00** [comment]
> Hello everyone, I had the same problem with the editor and found an easy solution for my case:
> 
> In the "formats" option I define the formats I want to allow in general to my editor. These are the formats I want the user to be able to use on text in the editor. Other formats are automatically removed when pasted into the editor.
> 
> After that I added clipboard matchers in the options which remove the previous allowed formats when pasting into the editor. Works great for me. All formats to set false or true are listed on this page: [Quill formats](https://quilljs.com/docs/formats/)
> 
> I hope this helps someone.
> 
> ```
>                 var Delta = Quill.import('delta');
> 		var editor = new Quill('#' + element_id, {
> 			formats: [
> 				'bold',
> 				'strike',
> 				'underline',
> 				'color',
> 				'background'
> 			],
> 			modules: {
> 				toolbar: [
> 					['bold', 'strike', 'underline'],     
> 					[{ 'color': [] }, { 'background': [] }]
> 				],
> 				clipboard: {
> 					matchers: [
> 						[ Node.ELEMENT_NODE, function(node, delta) {
> 							return delta.compose(new Delta().retain(delta.length(), 
> 							{ color: false,
> 							  background: false,
> 							  bold: false,
> 							  strike: false,
> 							  underline: false
> 							}
> 							));
> 						  }
> 						] 
> 					]
> 				}
> 			},
> 			placeholder: "ここにメモを入力",
> 			theme: "snow"
> 		});
> ```

This worked wonderfully. The documentation seems to be a bit all over the place when it comes to pasted formats but this saved the day for me, VERY appreciated.  Using 2.x

**Comment by axsgustavo** [comment]
For anyone trying to remove formatting when pasting content with React Quill, here’s what worked for me:

```ts
import ReactQuill, { RangeStatic } from 'react-quill-new'
import Delta from 'quill-delta'

const Clipboard: any = ReactQuill.Quill.import('modules/clipboard')

class PlainClipboard extends Clipboard {
  onPaste(range: RangeStatic, content: { html: string; text: string }) {
    const text = content.text
    const delta = new Delta().retain(range.index).delete(range.length).insert(text)

    const index = text.length + range.index
    const length = 0

    this.quill.updateContents(delta, 'silent')
    this.quill.setSelection(index, length, 'silent')
    this.quill.scrollIntoView()
  }
}

ReactQuill.Quill.register('modules/clipboard', PlainClipboard, true)
```

**Comment by Gjoce** [comment]
The best way I think is to create a new Delta only with the insert property, stripping the formatting. Here is what worked for me:
```
var Delta = Quill.import('delta');
                const quill = new Quill('#' + editorId, {
                modules: {
                    toolbar: [
                            ['bold', 'italic', 'underline', 'blockquote'],
                            [{ 'header': 1 }, { 'header': 2 }],
                            [{ 'list': 'ordered' }, { 'list': 'bullet' }],
                        ],
                    clipboard: {
                        matchers: [
                            [Node.ELEMENT_NODE, function (node, delta) {
                                const ops = delta.ops.map(op => {
                                    return {
                                        insert: op.insert
                                    };
                                });
                                return new Delta(ops);
                            }]
                        ]
                    }
                },
```
