### ISSUE TITLE
How to prevent parchment from creating new node, instead update closest node

### ISSUE THREAD

**Issue by mdoaie** [quilljs/quill#1189]
Hi,

I have created two simple parchment to add bold and underline style to the text, it will generates the following html code:

     <p>
           <span style="font-weight: bold;">
                <span style="text-decoration: underline;">
                       Tell your story...
                </span>
           </span>
     </p>

Is it possible to combine the style of the SPAN instead of adding new one?

Codepen: http://codepen.io/Cyrus80/pen/BQqdQN

Many thanks,

**Comment by jhchen** [comment]
You want to be using [Attributors](https://github.com/quilljs/parchment#attributors) not [Blots](https://github.com/quilljs/parchment#blots).
