### ISSUE TITLE
Toggle readonly option

### ISSUE THREAD

**Issue by jbrooksuk** [quilljs/quill#119]
I can't find any documentation that would let me toggle the `readonly` option. Is there such a thing?

**Comment by malko** [comment]
:1: should be made clear in the doc

**Comment by jhchen** [comment]
http://quilljs.com/docs/configuration/

**Comment by malko** [comment]
Yes found the page already but no mention of editor.editor.enable or
editor.editor.disable

**Comment by karim10** [comment]
Hello, it doen't work for me, has this changed? ´_this.quill.editor.disable is not a function´

**Comment by arslnb** [comment]
> Hello, it doen't work for me, has this changed? `_this.quill.editor.disable is not a function`

@karim10 If you've done something like `var myEditor = newQuill('#editor, {...})` then doing `myEditor.enable()` or `myEditor.disable()` should work.

**Comment by DevdudeSami** [comment]
It seems that `myEditor.disable()` will completely hide the entire Quill component. Anyone else experiencing this? Still need a way to toggle readonly...

**Comment by stouch** [comment]
disable()  is not exactly like a readOnly. disable() prevents the user to select the text. While readonly allows it.

**Comment by Jprusa610** [comment]
Any updates on how to toggle Readonly?

**Comment by jvekariya064** [comment]
Is there any function to toggle display the toolbar also?

**Comment by jvekariya064** [comment]
Or any way to dynamically(maybe on button clicks) change the editor's 'modules' property?
