### ISSUE TITLE
Highlight issue

### ISSUE THREAD

**Issue by amitguptagwl** [quilljs/quill#1190]
I get "[Uncaught SyntaxError: Invalid regular expression](http://stackoverflow.com/q/39770652/453767)" error if I don't use following optional configuration.

```
hljs.configure({   // optionally configure hljs
	  languages: ['javascript', 'ruby', 'python']
	});
```

**Comment by jhchen** [comment]
https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#bug-reports

**Comment by amitguptagwl** [comment]
This is the issue with highlight js. I have reported [there](https://github.com/isagalaev/highlight.js/issues/1387).
