### ISSUE TITLE
Toolbar (bubbles) shouldn't show when setSelection() is called with 'api'

### ISSUE THREAD

**Issue by eamodio** [quilljs/quill#1193]
When using the bubbles theme, calling `quill.setSelection({ index: 0, length: quill.getLength() }, 'api')` causes the toolbar to show up. The same thing happens if `silent` is used. It shouldn't unless caused by the user.

**Steps for Reproduction**

1. https://codepen.io/eamodio/pen/JbeXEQ?editors=0010

**Expected behavior**:

The toolbar doesn't show

**Actual behavior**:

The toolbar shows

**Platforms**:

macOS, Chrome

**Version**:

`1.1.7`

I also haven't been able to reproduce this in a sample yet but might be very related. I have intermittently seen that if quill is `readOnly` then sometimes you can still get the toolbar to show up.

**Comment by eamodio** [comment]
The use-case is to focus and pre-select all the text in an input to allow the user easy replacement (i.e. adding a new item to a list or something along those lines). And with having the toolbar automatically pop up makes it a jarring experience -- as the user pressed an add button (or the like), but now all of a sudden a toolbar pops up. If `source` isn't a good signal (though feels like it could be, though agree that closing the toolbar should probably happen regardless), maybe there could be a specific option to `setSelection` that avoids the toolbar opening?

**Comment by jhchen** [comment]
Thank you for the details. The simplest route given the use case might just be to somewhat diverge open / close behavior like you suggested, where close always hides the tooltip but open will only show if the source is `user`.
