### ISSUE TITLE
Not able to add new fonts

### ISSUE THREAD

**Issue by amitguptagwl** [quilljs/quill#1199]
When I try to add new fonts as follow, neither they are added to drop down  nor the existing fonts from dropdown work.

```
var FontAttributor = Quill.import('attributors/class/font');
FontAttributor.whitelist = [
 'sofia', 'slabo', 'roboto', 'inconsolata', 'ubuntu'
];
Quill.register(FontAttributor, true);

quill = new Quill('#editor-container', {
	modules: {
	  formula: true,
	  syntax: true,
	  toolbar: '#toolbar-container'
	},
	theme: 'snow'
});
```

**Expected behavior**: New fonts should be shown in font drop down.

**Actual behavior**: No new font is being added to list. Existing 3 font style also stop working. No error on console

**Platforms**: Ubuntu, Chrome 54

**Version**: 1.1.7

**Comment by amitguptagwl** [comment]
In addition to above issue;
**Issue 1**
When I copy paste some HTML or some text from one place to another place within the editor, it applies default font style.

1. open [document](https://docs.google.com/document/d/1nsto_2JcJ3BrW5a5DIajEkUn9_RnYuz_F0GRU2HP_3g/edit?usp=sharing)
2. copy 1st paragraph and unordered list.
3. goto quilljs.com
4. paste in editor. It looses font style for text in unordered list.
5. apply some font style to this text again.
6. cut the whole text and paste.
7. again it looses the font style.

**Issue2**
Some other issue related to font style can also be reproduced on quilljs.com
1. Go to quilljs.com
2. apply some font, say roboto, to some words in first paragraph
3. Select and cut the complete paragraph
4. again paste

**Expected Behaviour**: Paragraph with previous formatting should be pasted.

**Note**: The issue doesn't occur when you try 2nd time. So fresh load the page.

**Comment by benbro** [comment]
[Custom font example](http://quilljs.com/playground/#custom-fonts)

**Comment by benbro** [comment]
Please open separate issue for each problem you see.
It's hard to discuss several issues at one place.

**Comment by amitguptagwl** [comment]
Created 2 separated issues. mentioned in 2nd comment.
Trying to create demo for 1st issue. But unfortunately when I click on any drop down box, text is not selected anymore. 

https://jsfiddle.net/ry2dor1v/

Some weired behaviour. Should I create another card for this issue as well?

**Comment by benbro** [comment]
Is there original issue still valid after you saw the [custom font example](http://quilljs.com/playground/#custom-fonts)?

**Comment by amitguptagwl** [comment]
Yes original problem still exist. But I am not able to demo it because drop down are not working in above example.

**Comment by jhchen** [comment]
Only answering the original question: Just registering the format allows Quill to recognize it. The toolbar and what appears in it is separate. As already suggested a full example showing all the parts exists http://quilljs.com/playground/#custom-fonts
