### ISSUE TITLE
Copying and pasting with all text selected via <control>+<a> leads to one less line being pasted

### ISSUE THREAD

**Issue by CoenWarmer** [quilljs/quill#1202]
Copying and pasting with all text selected via `<control>+<a>` or `<command>+<a>` followed by `<control>+<v>` / `<command>+<v>` leads to the last line not being pasted.

**Steps for Reproduction**

1. Visit quilljs.com and go to any Playground instance.
2. Type some text over multiple lines (multiple paragraphs)
3. Select all text by pressing `<control>+<a>` or `<command>+<a>` on keyboard
4. Paste with `<control>+<v>` or `<command>+<v>` on keyboard
5. Notice the last line of the text selected in step 2 hasn't been pasted.

**Expected behavior**:

All lines in the selection are pasted.

**Actual behavior**:

Last line is not included in paste action.

**Platforms**:

Firefox 49.0.2, Internet Explorer 11, Edge

Chrome is not affected.

**Version**:

1.1.7

**Comment by dalipkumar703** [comment]
@jhchen reason for closing?
