### ISSUE TITLE
Clicking header button loses text selection

### ISSUE THREAD

**Issue by rokkamokka** [quilljs/quill#1203]
When clicking the header button, any selection of text is lost. Seems to be a reccurrence of #665.

**Steps for reproduction**:

1. Visit quilljs.com
2. Select some text
3. Click on the header button and choose 'Heading'.

**Expected behavior**:
The selected paragraph should switch to h1

**Actual behavior**:
Heading isn't set.
The editor loses focus.

**Platforms**:
Windows 10, Chrome 55

**Version**:
1.1.7

**Comment by rokkamokka** [comment]
This is actually a dupe of #1191

**Comment by Igor912** [comment]
Fixed this issue with so simple solution with help of selection-change and click event. 
Please see attached file.
[index.txt](https://github.com/quilljs/quill/files/1099918/index.txt)
