### ISSUE TITLE
How to get current value of editor

### ISSUE THREAD

**Issue by NekR** [quilljs/quill#1204]
Right I see only `getContents()` method which return `Delta` which by some reason cannot be transformed to simple string. At least there is no docs about such API. 

Also I see this topic: https://github.com/quilljs/quill/issues/774 where it's suggested to use `innerHTML`, but `innerHTML` doesn't return the same code in all browsers. So what's the to consistently get the value from editor with the same input?

**Comment by benbro** [comment]
Quill makes the HTML is consistent on all browsers.

**Comment by NekR** [comment]
That isn't possible because you cannot override browser behavior. Very simple example: IE return html in ALL CAPS.

**Comment by benbro** [comment]
CAPS doesn't change the semantics.
