### ISSUE TITLE
Ability to mark text

### ISSUE THREAD

**Issue by danielschwartz** [quilljs/quill#1205]
Wondering if there has been any discussion around the concept of "marking text" similar to the way [CodeMirror](https://codemirror.net/doc/manual.html#api_marker) does it?

In my scenario, marking text is useful for tying an external comment to a specific piece of text in a collaborative editing environment. Example below:

1. User A highlights a section of a document to write a comment about it
2. While User A is typing out their comment, User B enters the document and starts making edits to it
3. User A completes their comment and submits it

In the above example, saving a range wouldn't work as you would have to continually transform the saved range across the deltas coming through whatever OT adapter you have. Additionally, saving a range wouldn't allow you to style the marked text in any way (e.g. by highlighting the text that is being commented about in yellow). 

The only thought I had that might work was to somehow call formatText on your current selection using Quill.sources.SILENT as the source, however, it would be extremely difficult to make sure that the silent format application doesn't somehow make it back to the OT adapter and get sent to the other users. If anyone has any thoughts on how to accomplish this without creating new code in Quill, let me know!

**Comment by benbro** [comment]
Look at the [authorship module](https://github.com/quilljs/quill/pull/1049).

**Comment by danielschwartz** [comment]
@benbro took a look at this Authorship module you wrote and had a question: 

In my testing, binding directly to the TEXT_CHANGE event rather than the EDITOR_CHANGE event, it is fired after the content is already inserted into document tree. Are the modifications that you make to the delta in the Authorship module respected in any other functions bound to the TEXT_CHANGE event because EDITOR_CHANGE is called before TEXT_CHANGE (within Quill core)? If not, i'm having a hard time trying to wrap my head around how the Authorship module modifies the operations of the outgoing delta.

**Comment by benbro** [comment]
From the docs, the difference between the [editor-change](http://quilljs.com/docs/api/#editor-change) event and the [text-change](http://quilljs.com/docs/api/#text-change) event:
- editor-change is called before text-change.
- editor-change is also called for silent source.

This can be verified in the [code](https://github.com/quilljs/quill/blob/develop/core/quill.js#L408).

The PR is an update of the module from Quill 0.2.

**Comment by danielschwartz** [comment]
Awesome, this is super helpful. Appreciate the quick replies!

**Comment by danielschwartz** [comment]
@jhchen, @benbro I have this basically working. Ill try and post a PR in the next week or two so y'all can review and let me know what you think

**Comment by danielschwartz** [comment]
@jchen just created #1217 with my code for marking text
