### ISSUE TITLE
Custom Attributor with INLINE scope causes rtl text direction when updating existing text

### ISSUE THREAD

**Issue by sbevels** [quilljs/quill#1206]
I used the PR code for authorship as an external module.  In order to get Quill to accept the userId attribute, I had to register it in parchment.  For now, I'm not adding this as a class, but rather as a custom attribute.

`let customAttr = new Parchment.Attributor.Attribute("userId", "userId", { scope: Parchment.Scope.INLINE });
Quill.register(customAttr);`

The result of adding that to the authorship module is:
`<span userid="testuser1">Some text here</span>`

If I am a different user and I update the text, with "added" in the middle, I should get:
`<span userid="testuser1">Some text</span>
<span userid="testuser2">added</span>
<span userid="testuser1">here</span>`

However, what happens is that the new span for testuser2, has the text direction set to rtl instead of ltr.  If I move the focus away from that span and come back to it, then the text direction is correct.

I tried using different Parchment scopes, but they didn't break up the spans when multiple users edited the same line.

This is with Quill version 1.1.6 and Firefox browser.

**Comment by benbro** [comment]
Please share a [codepen](http://codepen.io/quill/pen/KzZqZx) that reproduce this.
