### ISSUE TITLE
How to render Style Sizes on toolbar without custom toolbar html?

### ISSUE THREAD

**Issue by SilverSting** [quilljs/quill#1207]
Trying to use inline styles for Size and Align.
Align options are shown on Toolbar fine, but having trouble with rendering Size options.

Following setup gets me closest to what I want. But the labels for all sizes are set to 'Normal'. Is there a way to list the size options as 'Small', 'Normal', 'Large' and 'Huge' **without using custom toolbar html**?

**Code**:
```javascript
var styleSize = Quill.import('attributors/style/size'),
  styleAlign = Quill.import('attributors/style/align');

Quill.register(styleSize, true);
Quill.register(styleAlign, true);

var quill = new Quill(element, {
  theme: 'snow',
  formats: ['size', 'bold', 'italic', 'color', 'background', 'list', 'align', 'link'],
  modules: {
    toolbar: [
      [{'size': ['10px', false, '18px', '32px']}],
      [{ 'align': [] }],
      ['bold', 'italic'],
      [{ 'list': 'ordered'}, { 'list': 'bullet' }],
      [{ 'color': [] }, { 'background': [] }],
      ['link'],
      ['clean']
    ]
  }
});
```

**Platforms**:
Ubuntu, Chrome

**Version**:
1.1.7

**Comment by jhchen** [comment]
You need to add the sizes to the whitelist as shown http://quilljs.com/playground/#custom-fonts and then add CSS rules to show the text that you want.

**Comment by SilverSting** [comment]
@jhchen thanks for your suggestion, but I'm not sure if we are on the same page.

Please note I need to work with inline styles for sizes (i.e. `<span style="font-size:10px"></span>`).
```javascript
var styleSize = Quill.import('attributors/style/size');
styleSize.whitelist = ['10px', '18px', '32px'];
```

What I'm stuck at is how to render these size options in the toolbar **without using my own toolbar html**. Is it possible to render the size options as below with just configuration?
```html
<select class="ql-size">
  <option value="10px">Small</option>
  <option selected="selected">Normal</option>
  <option value="18px">Large</option>
  <option value="32px">Huge</option>
</select>
```

I was kind of expecting something like this:
```javascript
modules: {
  toolbar: [
    [ {'size': [{'10px':'Small'}, {'':'Normal'}, {'18px':'Large'}, {'32px':'Huge'}]} ],
    ...
  ]
}
```

If this is not supported, then I will just look into building toolbar html.

Thanks!

**Comment by jhchen** [comment]
The purpose of the playground example I linked was because you were missing whitelisting which was one problem. The other problem is showing the right text which could either be solved with CSS like I suggested, which does not require custom HTML. The easiest way to do this is just use the developer console to find out which rule is causing "Normal" to show up and write a more specific rule.

**Comment by Sky-Li** [comment]
Hi @jhchen , I think you still misunderstood @SilverSting ,
I have the same problem, and I make an example [here](https://codepen.io/anon/pen/boWRQal) .
You can find, I remove the html


        <div id="toolbar-container">
          <select class="ql-font">
            <option selected>Aref Ruqaa</option>
            <option value="mirza">Mirza</option>
            <option value="roboto">Roboto</option>
          </select>
        </div>



and use ` toolbar: [{font: ['mirza', 'roboto']}] ` instead.

Then I got the fonr-family dropdown list like this
![result](https://user-images.githubusercontent.com/9549072/30956852-17920ce2-a46b-11e7-910e-33449c3ec656.png)
