### ISSUE TITLE
Not able to add custom font sizes

### ISSUE THREAD

**Issue by Tca1107** [quilljs/quill#1208]
Is there a way to add font sizes apart from small, normal, large, and huge?

I have tried to add <option> elements and have them classes that I added to the library but it didn't work:

in html:
<select class="ql-size">
   <option value="smaller"></option>
</select>

in lib:
.ql-editor .ql-size-small {
  font-size: 0.4em;
}

Thanks for your help!

**Comment by benbro** [comment]
Custom font size [example](http://quilljs.com/playground/#class-vs-inline-style).

**Comment by jhchen** [comment]
The custom font family [example](http://quilljs.com/playground/#custom-fonts) might also be useful.

**Comment by DualWield** [comment]
@jhchen this is really hard to add custom font size!!!

**Comment by DualWield** [comment]
for example:
```
var Size = Quill.import('attributors/style/size');
Size.whitelist = ['12px', '16px', '18px'];
Quill.register(Size, true);
this.editor = new Quill('#editor', {
                theme: 'snow',
                placeholder: '请输入内容',
                modules: {
                    toolbar: [
                        [{ 'size':  ['12px', '16px', '18px'] }]
                    ]
                }
            });
```

but it doesn't work. I've searching for google,stackoverflow, and finded no right solution.

**Comment by 2guti2** [comment]
We are using Quill for one of our projects and struggled with this same thing for a full day, here the solution:
**JS:**
```

var fontSizeStyle = Quill.import('attributors/style/size');
fontSizeStyle.whitelist = ['24px', '48px', '100px', '200px'];
Quill.register(fontSizeStyle, true);
announcementEditor = new Quill('#announcementEditor', {
                    modules: {
                        toolbar: '#announcementEditorToolbar'
                    },
                    placeholder: '...',
                    theme: 'snow'
                });     
```

**HTML:**
```
        <div id="announcementEditorToolbar">
            <span class="ql-formats">
                <select class="ql-size">
                    <option selected>Default</option>
                    <option value="24px">Small</option>
                    <option value="48px">Medium</option>
                    <option value="100px">Large</option>
                    <option value="200px">Huge</option>
                </select>
            </span>
        </div>
        <div name="announcementEditor" id="announcementEditor" ></div>
```

**Comment by nikohosn** [comment]
@2guti2 how are you referencing Quill in react? I am attempting to define some custom font sizes in my react component and it is not working.
`export class CustomToolbar extends Component {
  componentWillMount() {
    const SizeStyle = ReactQuill.import('attributors/style/size');
    ReactQuill.register(SizeStyle, true);
  }
  render() {
    return (
  <div id="toolbar">
    <select className="ql-size">
      <option value="normal">10</option>
      <option value="large">12</option>
      {/* <option value="small">8</option>
      <option value="normal">10</option>
      <option value="large">12</option>
      <option value="huge">14</option>
      <option value="small">18</option>
      <option value="small">24</option>
      <option value="huge">36</option> */}
    </select>
    <select className="ql-color"></select>
    <button className="ql-bold"></button>
    <button className="ql-italic"></button>
    <button className="ql-underline"></button>
    <button className="ql-strike"></button>
    <button className="ql-code-block"></button>
    <button className="ql-list" value="ordered"></button>
    <button className="ql-list" value="bullet"></button>
    <button className="ql-indent" value="-1"></button>
    <button className="ql-indent" value="+1"></button>
    <button className="ql-link"></button>
    <button className="ql-image"></button>
    {/* <button className="custom-button" onClick={this.onClickButton}>Download Me</button> */}
    <select id="custom-more-bar" title="more">
      <option>Download goes here</option>
    </select>

  </div>
)
  }
}

const wrapperStyle = { width: 100, margin: 50 };

class NoteEditor extends React.Component {

  constructor(props) {
    super(props);

    this.state = {
      user: Session.getSession('prg_lg'),
      wordcount:0,
      pdfContent: ''
    }

    this.quillRef = null;
    this.reactQuillRef = null;

    var socketAddress = 'wss://' + window.location.host + '';

    // if (window.location.host == 'dev.ambi.work' || true) socketAddress = 'wss://dev.ambi.work:444';

    sharedb.types.register(richText.type);
    this.socket = new WebSocket(socketAddress);
    this.connection = new sharedb.Connection(this.socket);

    window.disconnect = function() {
      this.connection.close();
    };

    window.connect = function() {
      this.socket = new WebSocket(socketAddress);
      this.connection.bindToSocket(this.socket);
    };

    this.modules = {
          toolbar: {
          container: "#toolbar",
      }
      // toolbar: [
      //   [{ 'font': [] }],
      //   [{ 'size': [
      //       {label: '8', value: '8px'},
      //       {label: '10', value: '10px'},
      //       {label: '12', value: '12px'},
      //       {label: '14', value: '14px'},
      //       {label: '18', value: '18px'},
      //       {label: '24', value: '24px'},
      //       {label: '36', value: '36px'}
      //     ]
      //   }],
      //   [{'color': [] }, { 'background': [] }],
      //   ['bold', 'italic', 'underline','strike', 'blockquote'],
      //   [{'list': 'ordered'}, {'list': 'bullet'}, {'indent': '-1'}, {'indent': '+1'}],
      //   ['link', 'image'],
      //   ['clean']
      // ],
    };

    this.formats = [
      'font',
      'size',
      'color', 'background',
      'bold', 'italic', 'underline', 'strike', 'blockquote',
      'list', 'bullet', 'indent',
      'link', 'image'
    ];

    this.onClickButton = this.onClickButton.bind(this);
    this.toDataUrl = this.toDataUrl.bind(this);
  }

  componentDidMount() {
    this.attachQuillRefs();
    let that = this;

    this.doc = this.connection.get('collab-notes', this.props.note.doc_id);
    this.doc.subscribe(function(err) {
      if (err) throw err;

      that.quillRef.setContents(that.doc.data);

      that.doc.on('op', function(op, source) {
        if (source === that.quillRef) return;

        that.quillRef.updateContents(op);
      });
    });
  }

  componentDidUpdate() {
    this.attachQuillRefs();
  }

  attachQuillRefs() {
    // Ensure React-Quill reference is available:
    if (typeof this.reactQuillRef.getEditor !== 'function') return;
    // Skip if Quill reference is defined:
    if (this.quillRef != null) return;

    const quillRef = this.reactQuillRef.getEditor();
    if (quillRef != null) this.quillRef = quillRef;
  }

  handleChange(e) {
    this.setState({[e.target.name]: e.target.value});
  }

  handleTextChange(content, delta, source, editor) {
    // console.log(this.quillRef.editor.delta.ops[0].insert);
    // this.setState({ pdfContent: this.quillRef.editor.delta.ops[0].insert })
    if (source !== 'user') return;

    this.doc.submitOp(delta, {source: this.quillRef});
    this.wordCountUpdate();
  }

  getNoteEditor() {
    return (
      <div>
        <CustomToolbar />
        <ReactQuill ref={(el) => { this.reactQuillRef = el }} theme='snow' value={this.state.text} modules={this.modules} formats={this.formats} onChange={this.handleTextChange.bind(this)} />
      </div>
    );
   //
  }

  wordCountUpdate() {
    // let wordNumber = JSON.stringify(this.quillRef.editor.delta.ops[0].insert);
    // console.log('wordCountUpdate content log: ' + wordNumber);
    // let nodeText = $(this.quillRef.editor.delta.ops[0].insert).contents().filter(function(){
    //   return this.nodeType === 3 && $.trim(this.nodeValue) !== '';
    // }).text()
    // console.log(nodeText);
    // this.setState({ wordcount: wordcount(nodeText) })
  }

  toDataUrl(url, callback) {
    var xhr = new XMLHttpRequest();
    xhr.onload = function() {
      var reader = new FileReader();
      reader.onloadend = function() {
        callback(reader.result);
      }
      reader.readAsDataURL(xhr.response);
    };
    xhr.open('GET', url);
    xhr.responseType = 'blob';
    xhr.send();
  }

  onClickButton() {
      var doc = new pdfConverter('p','pt','letter');
      var docTitle = this.props.note.title;
      var docContent = this.quillRef.editor.delta.ops[0].insert;
      //console.log(doc.getFontList() );
      this.toDataUrl('images/background.jpg', function(base64Img) {
        var imgData = base64Img;
        console.log(imgData);
        console.log('Adding to doc.');
        doc.addImage(imgData, 'JPEG', 0, 0, 612, 792);
        console.log('Image added.');
        doc.setFont('Times', 'Roman');
        doc.setFontSize(22);
        doc.text(20, 50, docTitle);
        doc.setFontSize(16);
        doc.text(20, 80, docContent);
        console.log('About to save');
        doc.save("test.pdf");
      });
  }

  // onClickWordButton() {
  //   var docContent = this.quillRef.editor.delta.ops[0].insert;
  //   var converted = HtmlDocx.asBlob(docContent, {orientation: 'portrait', margins: {top: 720}});
  //   saveAs(converted, 'test.docx');
  // }

  render() {
    let note = this.props.note;
    let noteCreator = note.creator.first_name + ' ' + note.creator.last_name
    let noteImg = '/images/default-profile-pic.png';

    return(
      <div>
        <ModalContainer zIndex={9999} >
          <ModalDialog width="642px" className="note-popup-dialog" style={{transform : "none"}} >
            <div className="popup-holder">
              <section className="edit-note-popup clearfix">
                <section className="inner-header clearfix">
                  <div className="info-wrapper">
                    <img className="user-image img-circle" src={noteImg} alt="User"/>
                      <p className="note-owner">by {noteCreator}</p>
                      <p className="time-wrapper">{note.created_at}</p>
                  </div>
                  <div className="options-wrapper">
                    <span className="delete-note"></span>
                    <span className="note-info"></span>
                    <div className="search-wrapper">
                      <input type="text" className="form-control search-note" placeholder="search"/>
                      <span className="search-ico"></span>
                    </div>
                    <span className="maximize"></span>
                  </div>
                </section>
                <section className="note-body clearfix">
                  <div className="title-wrapper">
                    <input defaultValue={note.title} type="text" className="note-title" value={this.state.noteTitle} onChange={ this.handleChange.bind(this) } />
                  </div>
                  <div className="rich-editor-holder">
                    { this.getNoteEditor() }
                  </div>
                </section>
              </section>
              <span className="close-note" onClick={this.props.dismissModal}></span>
              <div className="note-words-count">
                <span className="count">{this.state.wordcount}</span> <span className="def">words</span>
                {/* <div><button onClick={this.onClickButton}>Download Me</button></div> */}
              </div>
              <div>
                <Slider min={0} max={20} defaultValue={3} handle={this.handle} />
              </div>
            </div>
          </ModalDialog>
        </ModalContainer>
      </div>
    );
  }
}

export default connect(null, actions)(NoteEditor);
`

**Comment by mbenjamin618** [comment]
@nikohosn import Quill from react-quill like this:

`import ReactQuill, {Quill} from 'react-quill'`

**Comment by DarnellSh** [comment]
@jhchen I see I can change the font size by using `this.editor.format('size', '16px');`. But if I want to use '17px' instead of '16px', is there a workaround where I don't have to `fontSizeStyle.whitelist`? I want that size to be user defined.

**Comment by valentinbdv** [comment]
Same thing here! I don't want to set a whitelist because I need my user to enter any font size he wants.

**Comment by nuno360** [comment]
Is there some way to use rem instead of px?

Thanks.

**Comment by Jewcub** [comment]
same issue. I can get it to work with this solution, but can only have 3 custom sizes no matter how many i add to whitelist.
<img width="653" alt="Screen Shot 2020-02-07 at 11 28 09 PM" src="https://user-images.githubusercontent.com/52448067/74042166-fa1f4f00-4a01-11ea-8d92-6964173c7020.png">
<img width="639" alt="Screen Shot 2020-02-07 at 11 28 26 PM" src="https://user-images.githubusercontent.com/52448067/74042172-fe4b6c80-4a01-11ea-8be0-61c6530e21b2.png">

**Comment by Sankartw** [comment]
@Jewcub
maybe u can set some css like this
```
.ql-snow .ql-picker.ql-size .ql-picker-label::before, 
.ql-snow .ql-picker.ql-size .ql-picker-item::before {
  content: attr(data-value);
```

**Comment by WellGin** [comment]
> for example:
> 
> ```
> var Size = Quill.import('attributors/style/size');
> Size.whitelist = ['12px', '16px', '18px'];
> Quill.register(Size, true);
> this.editor = new Quill('#editor', {
>                 theme: 'snow',
>                 placeholder: '请输入内容',
>                 modules: {
>                     toolbar: [
>                         [{ 'size':  ['12px', '16px', '18px'] }]
>                     ]
>                 }
>             });
> ```
> 
> but it doesn't work. I've searching for google,stackoverflow, and finded no right solution.

@DualWield 
You missed to add a 'false' item in toolbarOptions of size and the style of your customed item
try  [{ 'size':  [false, '12px', '16px', '18px'] }]
and css:
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="12px"]::before {
  content: '12px';
  font-size: 12px !important;
}

**Comment by chimiwangchuk** [comment]
![Screen Shot 2020-06-24 at 5 48 18 PM](https://user-images.githubusercontent.com/36373715/85550668-015a9880-b643-11ea-8dd2-72765adf902f.png)
`const [QuillImport] = await this.getQuill();
    var Size = Quill.import('attributors/style/size');
    Size.whitelist = ['28px', '30px', '32px'];
    Quill.register(Size, true);
    const colorList = ['#001f3f', '#0074D9', '#7FDBFF', '#39CCCC', '#3D9970', '#2ECC40', '#01FF70', '#FFDC00', '#FF851B', '#FF4136', '#85144b', '#F012BE', '#B10DC9', '#111111', '#AAAAAA', '#DDDDDD', '#FFFFFF'];
    this.quillEditor = new QuillImport(`#${this.editorUniqueId}`, {
      modules: {
        toolbar: [
          ['bold', 'italic', 'underline'],
          ['link'],
          [{ 'color': [...colorList] }, { 'background': [...colorList] }],
          [{ 'size': Size.whitelist }, false],


        ]
      },
      theme: 'bubble'`

i couldn't show my custom fonts in dropdown.

**Comment by eBitzu** [comment]
But how do you make the default value of the size to be for example 14px or 28px? I don't want to put "normal"

**Comment by jc-wow** [comment]
> We are using Quill for one of our projects and struggled with this same thing for a full day, here the solution:
> **JS:**
> 
> ```
> 
> var fontSizeStyle = Quill.import('attributors/style/size');
> fontSizeStyle.whitelist = ['24px', '48px', '100px', '200px'];
> Quill.register(fontSizeStyle, true);
> announcementEditor = new Quill('#announcementEditor', {
>                     modules: {
>                         toolbar: '#announcementEditorToolbar'
>                     },
>                     placeholder: '...',
>                     theme: 'snow'
>                 });     
> ```
> 
> **HTML:**
> 
> ```
>         <div id="announcementEditorToolbar">
>             <span class="ql-formats">
>                 <select class="ql-size">
>                     <option selected>Default</option>
>                     <option value="24px">Small</option>
>                     <option value="48px">Medium</option>
>                     <option value="100px">Large</option>
>                     <option value="200px">Huge</option>
>                 </select>
>             </span>
>         </div>
>         <div name="announcementEditor" id="announcementEditor" ></div>
> ```

thank you! that's help me a lot!

**Comment by KhaledAbdelfattah** [comment]
> ![Screen Shot 2020-06-24 at 5 48 18 PM](https://user-images.githubusercontent.com/36373715/85550668-015a9880-b643-11ea-8dd2-72765adf902f.png)
> 
> ```
>     var Size = Quill.import('attributors/style/size');
>     Size.whitelist = ['28px', '30px', '32px'];
>     Quill.register(Size, true);
>     const colorList = ['#001f3f', '#0074D9', '#7FDBFF', '#39CCCC', '#3D9970', '#2ECC40', '#01FF70', '#FFDC00', '#FF851B', '#FF4136', '#85144b', '#F012BE', '#B10DC9', '#111111', '#AAAAAA', '#DDDDDD', '#FFFFFF'];
>     this.quillEditor = new QuillImport(`#${this.editorUniqueId}`, {
>       modules: {
>         toolbar: [
>           ['bold', 'italic', 'underline'],
>           ['link'],
>           [{ 'color': [...colorList] }, { 'background': [...colorList] }],
>           [{ 'size': Size.whitelist }, false],
> 
> 
>         ]
>       },
>       theme: 'bubble'```
> 
> i couldn't show my custom fonts in dropdown. 
> ```

Same Here

**Comment by kevindcode** [comment]
I was a confused by this too, but looking at the docs in the **[Toolbar Container](https://quilljs.com/docs/modules/toolbar/#container)** section, they say this:
> "Dropdowns are similarly specified by an Object, but with an array of possible values. **CSS is used to control the visual labels for dropdown options.**"

So it looks like we'll need to use CSS to update the `content` [property](https://www.w3schools.com/cssref/pr_gen_content.asp):

![Screenshot 2020-10-20 at 22 21 56](https://user-images.githubusercontent.com/34057567/96645627-c29fcb00-1322-11eb-8597-19ca58b7933d.png)

**Comment by niketdave-codal** [comment]
Your CSS
```
.ql-snow{
  .ql-picker{
      &.ql-size{
          .ql-picker-label,
          .ql-picker-item{
              &::before{
                  content: attr(data-value) !important;
              }
          }
      }
  }
}
```
Your TS file
```
Size = Quill.import('attributors/style/size');
Size.whitelist = ['12px', '14px', '16px', '18px','20px'];
Quill.register(this.Size, true);
    this.editorOptions = {
      toolbar: [
        [{ size: ['12px','14px', '16px','18px','20px'] }],
      ]
    }
```

**Comment by keivansahebdelfard** [comment]
quill snow with full toolbox and custom font size for angular cli :
```
APP.MODULE.TS :
 
var Size = Quill.import("attributors/style/size");
Size.whitelist = [
  "9px",
  "10px",
  "11px",
  "12px",
  "14px",
  "16px",
  "18px",
  "20px",
  "22px",
  "24px",
  "26px",
  "28px",
];
Quill.register(Size, true);

@NgModule({
  imports: [
    QuillModule.forRoot({
      modules: {
        toolbar: [
          ["bold", "italic", "underline", "strike"], // toggled buttons
          ["blockquote", "code-block"],

          [{ header: 1 }, { header: 2 }], // custom button values
          [{ list: "ordered" }, { list: "bullet" }],
          [{ script: "sub" }, { script: "super" }], // superscript/subscript
          [{ indent: "-1" }, { indent: "+1" }], // outdent/indent
          [{ direction: "rtl" }], // text direction

          [
            {
              size: [
                "9px",
                "10px",
                "11px",
                "12px",
                "14px",
                "16px",
                "18px",
                "20px",
                "22px",
                "24px",
                "26px",
                "28px",
              ],
            },
          ], // custom dropdown
          [{ header: [1, 2, 3, 4, 5, 6, false] }],

          [{ color: [] }, { background: [] }], // dropdown with defaults from theme
          [{ font: [] }],
          [{ align: [] }],

          ["clean"], // remove formatting button

          ["link", "image", "video"], // link and image, video
        ],
      },
    }),
  ],

CSS : 
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="9px"]::before {
  content: "9";
  font-size: 9px !important;
}

.ql-snow .ql-size .ql-picker-item[data-value="10px"]::before {
  content: "10";
  font-size: 10px !important;
}

.ql-snow .ql-size .ql-picker-item[data-value="11px"]::before {
  content: "11";
  font-size: 11px !important;
}
.ql-snow .ql-size .ql-picker-item[data-value="12px"]::before {
  content: "12";
  font-size: 12px !important;
}

.ql-snow .ql-size .ql-picker-item[data-value="14px"]::before {
  content: "14";
  font-size: 14px !important;
}

.ql-snow .ql-size .ql-picker-item[data-value="16px"]::before {
  content: "16";
  font-size: 16px !important;
}
.ql-snow .ql-size .ql-picker-item[data-value="18px"]::before {
  content: "18";
  font-size: 18px !important;
}

.ql-snow .ql-size .ql-picker-item[data-value="20px"]::before {
  content: "20";
  font-size: 20px !important;
}

.ql-snow .ql-size .ql-picker-item[data-value="22px"]::before {
  content: "22";
  font-size: 22px !important;
}
.ql-snow .ql-size .ql-picker-item[data-value="24px"]::before {
  content: "24";
  font-size: 24px !important;
}

.ql-snow .ql-size .ql-picker-item[data-value="26px"]::before {
  content: "26";
  font-size: 26px !important;
}

.ql-snow .ql-size .ql-picker-item[data-value="28px"]::before {
  content: "28";
  font-size: 28px !important;
}

```

**Comment by BansiBrainerHub** [comment]
.ql-snow .ql-size .ql-picker-item&::before{
         content: attr(data-value) !important;
  }

instead you can simply this snippet

**Comment by amanVcbay** [comment]
but font-size of selected text are not changing

**Comment by BansiBrainerHub** [comment]
you should have give important to font-size and it works  for me!

**Comment by riceshan23** [comment]
How to fix it? 28px is selected but label still display 'normal'

![image](https://github.com/quilljs/quill/assets/48287132/52301d0e-e1cf-439d-935f-2155b4374e27)

**Comment by BansiBrainerHub** [comment]
var Size = Quill.import("attributors/style/size");

**Comment by ElsaOOo** [comment]
> How to fix it? 28px is selected but label still display 'normal'
> 
> ![image](https://private-user-images.githubusercontent.com/48287132/268677283-52301d0e-e1cf-439d-935f-2155b4374e27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzU2MjEsIm5iZiI6MTcwNDQzNTMyMSwicGF0aCI6Ii80ODI4NzEzMi8yNjg2NzcyODMtNTIzMDFkMGUtZTFjZi00MzlkLTkzNWYtMjE1NWI0Mzc0ZTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2MTUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MjIyZTFmOGNmYTNiNjc5Mzg2ZWU0ZjcyMjgxYjhjNmJlYmNlZTdhOTA2NmIxNjU4OTc5MzBmZmFhMzA3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RisNYmmHIu7FbAZUDziqwJ1KVslIsaHLQQDmvJURF8M)

.ql-snow{
  .ql-picker{
      &.ql-size{
          .ql-picker-label,
          .ql-picker-item{
              &::before{
                  content: attr(data-value) !important;
              }
          }
      }
  }
}

**Comment by savogajic** [comment]
> > How to fix it? 28px is selected but label still display 'normal'
> > ![image](https://private-user-images.githubusercontent.com/48287132/268677283-52301d0e-e1cf-439d-935f-2155b4374e27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzU2MjEsIm5iZiI6MTcwNDQzNTMyMSwicGF0aCI6Ii80ODI4NzEzMi8yNjg2NzcyODMtNTIzMDFkMGUtZTFjZi00MzlkLTkzNWYtMjE1NWI0Mzc0ZTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2MTUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MjIyZTFmOGNmYTNiNjc5Mzg2ZWU0ZjcyMjgxYjhjNmJlYmNlZTdhOTA2NmIxNjU4OTc5MzBmZmFhMzA3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RisNYmmHIu7FbAZUDziqwJ1KVslIsaHLQQDmvJURF8M)
> 
> .ql-snow{ .ql-picker{ &.ql-size{ .ql-picker-label, .ql-picker-item{ &::before{ content: attr(data-value) !important; } } } } }

Wroks for me
