### ISSUE TITLE
Failing to build with browserify

### ISSUE THREAD

**Issue by candronikos** [quilljs/quill#1215]
Using the npm package to try Quill
`browserify -t [ browserify-css ] -t [ babelify --presets [ es2015 ] ] src/index.js -o root/app.js --debug
`

Yields the following error:
```
import Parchment from 'parchment';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Here's the code I'm trying to run

```
import Quill from 'quill/core';
//var Quill = require('quill/core');

let editor = new Quill('#editor');
```

**Comment by jhchen** [comment]
If there is an actual bug with Quill and not with your script please provide details why. Otherwise please consult the Browserify docs on proper usage.

**Comment by candronikos** [comment]
I should have worded it better than that. I'm not building from source. Just did a `npm install quill` I assumed that I could just `require` it after that. Here's the package.json file.

```
{
  "name": "app",
  "version": "0.0.0",
  "description": "Insert description",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "browserify -t [ browserify-css ] -t [ babelify --presets [ es2015 ] ] src/index.js -o root/app.js --debug"
  },
  "author": "Author Name",
  "license": "UNLICENSED",
  "dependencies": {
    "quill": "^1.1.7"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.18.0",
    "babelify": "^7.3.0",
    "browserify": "^13.1.1",
    "browserify-css": "^0.9.2"
  }
}
```

**Comment by ninjabiscuit** [comment]
@candronikos FWIW I have the same problem. Haven't found the answer in the babelify docs yet

**Comment by candronikos** [comment]
@ninjabiscuit What I ended up doing was cloning the quilljs repo as a submodule and importing the .js file directly. That seems to work fine
