### ISSUE TITLE
Overlapping single format with multiple values

### ISSUE THREAD

**Issue by danielschwartz** [quilljs/quill#1216]
There are certain scenarios in which i'd like to be able to have multiple values for the same type of format. Explanation below:

I have a custom inline format of Comment. The value provided to the Comment blot is an ID of a comment thread associated with that piece of text. However, a user should be able to have multiple comments tied to any piece of text. For example (in HTML to make it easy to read):

```html
<span class="ql-comment ql-comment-1">
    The quick <span class="ql-comment ql-comment-2">brown</span> fox jumps over the lazy dog
</span>
```

However, given my understanding of the Inline blot provided by Parchment (and in my testing), setting the Comment ID of 2 on the word `brown` would unwrap the Comment blot with ID 1 so that resulting html would look like the following:

```html
<span class="ql-comment ql-comment-1">The quick </span>
<span class="ql-comment ql-comment-2">brown</span>
<span class="ql-comment ql-comment-1"> fox jumps over the lazy dog</span>  
```

I have a super hacky solution currently, where the value provided to my Comment blot is an array (e.g. `[1,2]`), however that requires me to externally manage what comments are tied to what nodes, and correct reassign them dynamically as new comments are added or removed. 

Any help would be appreciated, thanks!

**Comment by jhchen** [comment]
A solution that worked for me was to overwrite `add` to store a serialized list of IDs. For example:

```js
class Comment extends Parchment.Attributor.Attribute {
  constructor(attrName = 'comment', keyName = 'data-comment') {
    super(attrName, keyName, { scope: Parchment.Scope.INLINE })
  }

  add(node, value) {
    if (this.canAdd(node, value)) {
      let ids = []
      if (node.hasAttribute(this.keyName)) {
        ids = node.getAttribute(this.keyName).split(',')
      }
      if (ids.indexOf(value) < 0) {
        ids.push(value)
      }
      node.setAttribute(this.keyName, ids.join(','))
      return true
    } else {
      return false
    }
  }

  remove(node) {
    node.removeAttribute(this.keyName)
  }

  value(node) {
    return node.getAttribute(this.keyName)
  }
}
```

This is using an attribute Attributor but I think the same approach could work for class Attributors.

**Comment by danielschwartz** [comment]
@jchen awesome, ill give this a try and report back. Really awesome how on top of this developer community you are. Hopefully I can contribute back with some PRs once I get my custom version of Quill in a stable place. 

Thanks again!

**Comment by danielschwartz** [comment]
@jhchen wanted ot quickly follow up on this. The solution you posted above works at the time of formatting and correctly handles the overlap.

However, when reinstantiating the document from a Delta the multiple attributes get extended incorrectly. For example:

What should be output as:

```html
<span data-comment="1">Some </span>
<span data-comment="1,2">words</span>
<span data-comment="1"> here</span>
```

Actually gets output as:

```html
<span data-comment="1">Some </span>
<span data-comment="1,2">words here</span>
```
Notice that the comment with ID=2 got extended to the word "here" when it shouldn't have been (and wasn't upon initial formatting)

I took a look into the quill internals, and noticed that something is happening around here: https://github.com/quilljs/quill/blob/develop/core/editor.js#L40 when extending the leaf and bubblingFormats. The attribute diff on line 44 happens correctly, but it seems like because `applyDelta` does `this.scroll.insertAt` first it does something to screw up

**Comment by jhchen** [comment]
This was answered on StackOverflow: https://stackoverflow.com/questions/45359148/overlapping-inline-annotations-with-quill.

**Comment by Quach2502** [comment]
@danielschwartz hi I have encountered the same problem when trying to make overlapping format ( which means it works at the time of formatting and extends incorrectly when refresh). I have tried the code in the above StackOverflow link and the problem is still the same. Do you solve this problem? Any suggestion/ workaround is appreciated.
