### ISSUE TITLE
a delta with retain: 0 cause an internal error

### ISSUE THREAD

**Issue by TheMightyPope** [quilljs/quill#1218]
Using a delta with retain: 0 cause an internal error

var delta= { ops: [
  { retain: 0 },
  { insert: "Dolly"}
  ]};

Uncaught TypeError: Cannot read property 'length' of undefined
    at https://cdn.quilljs.com/1.1.8/quill.js:3871:58
    at Array.reduce (native)
    at Delta.reduce (https://cdn.quilljs.com/1.1.8/quill.js:2506:20)
    at Editor.applyDelta (https://cdn.quilljs.com/1.1.8/quill.js:3870:14)
    at https://cdn.quilljs.com/1.1.8/quill.js:2144:32
    at Quill.modify (https://cdn.quilljs.com/1.1.8/quill.js:2239:17)
    at Quill.updateContents (https://cdn.quilljs.com/1.1.8/quill.js:2142:22)
    at pen.js:43:7

**Steps for Reproduction**

1. Visit https://codepen.io/TheMightyPope/pen/Lboxow

**Expected behavior**:
Insert at position 0

**Actual behavior**:
Internal error.

**Platforms**:

Chrome v 55.0.2883.87 M
IE: V 11

**Version**:

1.1.8

**Comment by benbro** [comment]
{retain: 0} is not a [valid op](https://github.com/quilljs/delta/blob/master/lib/delta.js#L38).
Delta [docs](http://quilljs.com/docs/delta/) says:
```
It is not recommended to construct Deltas by hand—
rather use the chainable insert(), delete(), and retain() methods to create new Deltas.
```
```javascript
var delta = new Delta();
delta.retain(0);
delta.ops.length == 0;
```

**Comment by TheMightyPope** [comment]
Thanks Ben !!

As a followup question you might know the answer to, I'm copying a delta from one editor (The entire content), to another editor (to be inserted in the middle of that content). 

Editor 1: ABCDE
Editor 2: 123
Result: AB12345DE
C is replaced by 123

To do this, I get the delta from the second editor, Run through the delta OPS to manually remove the last return. If I don't then I end up with it being included when inserted:
AB123
DE
To remove it, I assume the last ops is ALWAYS an Insert (since it includes the last newline), and I either remove it completely from the delta list, or I edit the 'insert" if it's longer than 1 character.

Once that is done, I create a new delta, now using your answer:
 var newdelta = new Delta().retain(startIndex);

and then I concat the modified editor 2 delta into it, like this:
 newdelta = newdelta.ops.concat(delta.ops);

Finally, I add that to editor 1 to make the 'insertion' complete.

Is there any better way to do all this? It seems rather prone to errors the way I'm doing it now, but?

Sorry if this is not the right place to ask this...?

**Comment by benbro** [comment]
If you know that the last char is always a new line, you might do (untested):
```javascript
delta.retain(delta.length()-1).delete(1);
```

**Comment by TheMightyPope** [comment]
Ah yes, now I have the delta from your fist post, of course I can. Thanks. Duh.

I know the last character is always a newline because always inserts a newline at the end, as per documentation: 

"All Quill documents must end with a newline character, even if there is no formatting applied to the last line. This way, you will always have a character position to apply line formatting to."

I wish it wasn't so, but alas.
