### ISSUE TITLE
Left align option not working

### ISSUE THREAD

**Issue by prokilogrammer** [quilljs/quill#1219]
In [http://quilljs.com/docs/formats/](http://quilljs.com/docs/formats/), after I center align a paragraph, clicking on the left align button does left align the paragraph. This is not a toolbar issue because I noticed this behavior in my website which uses `formatLine()` API

**Steps for Reproduction**
1. Visit http://quilljs.com/docs/formats/
2. Write a couple of lines
3. Select all lines and click on the "align" button to open the dropdown. Click on the Center Align button. Your text should be center aligned now
4. Select all lines and click on the "align" button to open the dropdown. Click on the "Left Align" button. 

**Expected behavior**:
Selected Text should left aligned

**Actual behavior**:
Selected text alignment did not change

**Platforms**:
Mac OSX 10.11.6, Chrome  55.0.2883.95

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out
1.1.7

**Comment by jhchen** [comment]
This should be fixed in 1.1.8. Documentation site just updated.
