### ISSUE TITLE
Add image popup confusing UX

### ISSUE THREAD

**Issue by philfreo** [quilljs/quill#122]
Even though it says "Preview", a first time user could expect that the large empty dashed border box looks like a file could be dropped in it, and try to drag their uploaded image there... since many other editors have a similar UI for accepting uploads of images. 

The quick suggestion would be to just hide the empty box if you don't have an image preview to show.

![screenshot 2014-05-24 19 04 52](https://cloud.githubusercontent.com/assets/97612/3076087/144eb6ee-e3b1-11e3-9869-40fa4801bb79.png)

**Comment by zhougch5** [comment]
I wish quill can add DropzoneJS as the third part. So that it can be more powerful because insert can be seen everywhere

**Comment by jhchen** [comment]
Quill as of 1.0.0-beta.8 now no longer has a custom image tooltip in favor of a simpler flow where the image button opens the file picker dialog and converts this into base64 image to be inserted.
