### ISSUE TITLE
Select all + cut + paste only pastes first line

### ISSUE THREAD

**Issue by amitguptagwl** [quilljs/quill#1222]
**Steps for Reproduction**

1. Visit quilljs.com
2. Go to editor
3. Ctrl+A --> Ctrl+X --> Ctrl+V

**Expected behavior**: Whole contents should be pasted and formatting should be preserved.

**Actual behavior**: Only the 1st heading is pasted.

**Platforms**: Tested on Chrome 54 and ubuntu machine

**Comment by CoenWarmer** [comment]
Duplicate of https://github.com/quilljs/quill/issues/1202

**Comment by jhchen** [comment]
Thanks for taking a look @CoenWarmer but I think while this issue is very similar it's actually different. This one does a cut before a paste, instead of overwriting with paste. Also this issue is affecting Chrome.

**Comment by CoenWarmer** [comment]
Ah, spoke too soon. :)
