### ISSUE TITLE
Size, alignment, color, font dropdowns not working after modification to EventTarget prototype

### ISSUE THREAD

**Issue by GaurangTandon** [quilljs/quill#1227]
Doing specific modification to EventTarget prototype completely breaks QuillJS dropdowns.

This is a valid pen - http://codepen.io/anon/pen/GNbmjy - showcasing the issue. Just type some text and select the text size/alignment/color/font dropdown to change some styles. You'll notice that you _can_ select a different value in the dropdown, but the _changes to the formatting of the text are **not** applied._

This is the only code needed to cause this bug:

```
function hasEvent(elm, type) {
  return type in elm.pEvents;
}

function addRemoveEvent(elm, type, callback, isAdder) {
  if (isAdder) elm.pEvents[type] = callback;
  else delete elm.pEvents[type];
}

function makeListener(name, isAdder) {
  var f = EventTarget.prototype[name + "EventListener"];

  return function (type, callback, capture) {
    // pEvents -> prokeys events
    if(!this.pEvents) this.pEvents = {};

    var has = hasEvent(this, type);

    // event has already been added with
    // another or same listener
    // so first remove it
    if (isAdder && has)
      this.removeEventListener(type, this.pEvents[type]);			

    f.call(this, type, callback, capture);
    addRemoveEvent(this, type, callback, isAdder);

    return true;
  };
}

EventTarget.prototype.addEventListener = makeListener("add", true);
EventTarget.prototype.removeEventListener = makeListener("remove", false);
```

All this code does is make sure that multiple listeners for the same event are _not_ added. So, if an event listener function `A` was previously registered with `onmouseover`, and you call `.addEventListener` to register `B` also, _`A` will get removed and then B will be added._ It does so by maintaining a register (`.pEvents`) for events and functions that have been assigned for each element.

This piece of code is essential for my applications working, but QuillJS is also the most suitable editor for my application. Any regular member has any idea how I could get both to work together?

Thank you! :)

_[Archive of the previous unrelated issue this post earlier contained](http://pastebin.com/Mb94nDwY)_

**Comment by GaurangTandon** [comment]
I just delinked all my js files at once together, and somehow quill worked. I will try hunting the bug more. Sorry to disturb you guys. Closing for now.

**Comment by benbro** [comment]
You are probably overriding event handlers needed by Quill core.

Overriding EventTarget.prototype.addEventListener is considered a bad practice.
This is a bug in your code or wrong architecture and not something related to Quill.
