### ISSUE TITLE
Editor for the textarea

### ISSUE THREAD

**Issue by Purus** [quilljs/quill#1231]
I am developing a plugin for a CMS to use the QuillJs editor. The CMS expects the editor toolbar to be attached to a textarea and later the contents are submitted via the form.

I don't see any examples where the editor is linked to the textarea. Any help?

I could not find any helpful link in the search.

**Comment by benbro** [comment]
Form submit [example](http://quilljs.com/playground/#form-submit)

**Comment by Purus** [comment]
Thanks for your response.

I have already seen this example. But the example does not deal with
textarea element in the form.

Thanks,
R.Purusothaman

**Comment by benbro** [comment]
Quill doesn't work directly with textarea.
The example show you how to get the delta contents from Quill and add it to a form field.

**Comment by benbro** [comment]
See previous discussion https://github.com/quilljs/quill/issues/87

**Comment by gowda1991** [comment]
Quill doesn't work directly with textarea, any one help me on this.

**Comment by be-next-hotdog** [comment]
+1

**Comment by CrandellWS** [comment]
https://github.com/quilljs/quill/issues/1694#issuecomment-328634796

**Comment by trickymast3r** [comment]
this is the reason why i not use this editor

**Comment by windware** [comment]
What is its primary use when it doesn't directly work with textarea?

**Comment by yujialian** [comment]
It's a bit work especially I originally using `ckeditor` which perfectly support textarea, quill has a nice looking but it would be perfect if we have `getHTML()` and add support to `<textarea>`

**Comment by augnustin** [comment]
Yup, and this shouldn't be too hard:

Simply transform the textarea into the div with content at initialization and live update a hidden field with the same name while editing.

**Comment by tangien** [comment]
Checkout this,

[(https://github.com/tangien/quilljs-textarea)]

I thought it might be helpful!

**Comment by vince83110** [comment]
10 minutes lost, what is the point of a rich text editor to not work easily with a textarea input... It's like "hey, now you wrote your text, you would like to save or submit it ?! not with our plugin !"

**Comment by dennercpt** [comment]
Simple solution

`function form_submit(){`
`	$('#content').val($('.ql-editor').html()); #content is the hidden input that will receive the text`
`	$('#form').submit();`
`}`

**Comment by philippejadin** [comment]
It would be nice to warn the developer on the console when attempting to instantiate quill on a textarea. Instead I got a very weird error involving "Obsolete mutation events"

**Comment by LipeTuga** [comment]
This solved my problems:
```
<div id="quill_editor"></div>
<input type="hidden" id="quill_html" name="name"></input>

<script>
    	var quill = new Quill('#quill_editor', {
        		theme: 'snow'
    	});
   quill.on('text-change', function(delta, oldDelta, source) {
        document.getElementById("quill_html").value = quill.root.innerHTML;
    });
</script>
```

**Comment by GWeber1** [comment]
I resolved with a js script that rewrite the content from the div for a hidden textarea in the form. See below the code using JS and HTML:

**HTML**
```
<div class="form-group row">
            <label for="desc" class="col-sm-4 col-form-label">Description</label>
              <div class="col-sm-12">
                  <div id="desc"><p>Just a test</p></div>
              </div>
          </div>
          <br />
          <textarea style="display: none;" name="textarea_desc" id="textarea_desc" class="form-control"></textarea>
```
 
**JS**
```
 var quill = new Quill('#desc', {
  modules: {
    toolbar: true
  },
  theme: 'snow'
});

$("#save").on('click', function() {
  $("#textarea_desc").html($("#desc div").html());
  $("#editfrmContent").submit();
```

**Comment by pjnw1236** [comment]
thanks i can solve this trouble shooting by https://github.com/tangien

[before] 
      <textarea th:field="*{content}" class="form-control" rows="10" id="editor"></textarea>

[after] 
      <textarea **_data-quilljs_** th:field="*{content}" class="form-control" rows="10" id="editor"></textarea>

https://github.com/tangien/quilljs-textarea

i can solve problem by only add "data-quilljs"

**Comment by pjnw1236** [comment]
## Here is my Tip for Trouble Shooting 

[1] cdn setting (Quill & jQuery) 
```html
    <!-- Quill -->
    <link href="https://cdn.quilljs.com/1.0.0/quill.snow.css" rel="stylesheet" />
    <script src="https://cdn.quilljs.com/1.0.0/quill.js"></script>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
```

[2] make div tag for use quill editor and hide the textarea with hidden field
```html
      <div id="editor"></div>
      <textarea th:field="*{content}" class="form-control" style="display:none" id="hiddenTextarea"></textarea>
```

[3] JavaScript Setting with Quill
```javascript
// Initialize Quill
    var quill = new Quill('#editor', {
      modules: {
        toolbar: [
          ['bold', 'italic'],
          ['link', 'blockquote', 'code-block', 'image'],
          [{ list: 'ordered' }, { list: 'bullet' }]
        ]
      },
      theme: 'snow'
    });

// transfer div "editor" To textarea "hiddenTextarea"
    $("form").on("submit", function() {
      $(".ql-clipboard").remove(); // because automatically generated
      $(".ql-tooltip").remove(); // because automatically generated
      $("#hiddenTextarea").val($("#editor").html());
    });
```

I don't know why **ql-clipboard** and **ql-tooltip** created 
If someone knows, please let me know
