### ISSUE TITLE
Extending BlockEmbed with typescript

### ISSUE THREAD

**Issue by pixelpax** [quilljs/quill#1233]
I'd like to be able to extend native blots as seen in [cloning medium w/ parchment](https://quilljs.com/guides/cloning-medium-with-parchment/). I am using angular2 with typescript, and typescript does not believe that `BlockEmbed` is a real constructor. 
**Steps for Reproduction**

Using the following code (pretty much directly from above tutorial):
    let BlockEmbed = Quill.import('blots/block/embed');

    class DividerBlot extends BlockEmbed { }
    DividerBlot.blotName = 'divider';
    DividerBlot.tagName = 'hr';

**Expected behavior**:
I expected this to extend BlockEmbed blots.

**Actual behavior**:
I get `TS2507: Type 'any' is not a constructor function type.`

**Version**:
1.1.9

**Comment by iblank** [comment]
We ran into the same issue and were able to get around it by importing the embed blot from quill and setting the type of the block embed to that type. Also, had to set the class properties within the new class.

`import EmbedBlot from 'quill';`

```
let BlockEmbed: EmbedBlot = Quill.import('blots/block/embed');
class DividerBlot extends BlockEmbed {
      static blotName = 'divider';
      static tagName = 'hr';
}
Quill.register(DividerBlot);
```

**Comment by rajivchugh** [comment]
@iblank I am facing the same issue. However, I am unable to import EmbedBlot from quill. I am getting the following error:
```
Module '"quill"' has no exported member 'EmbedBlot'.)
```

Can you please help. Thanks.

**Comment by Percipient24** [comment]
I had trouble with this, also.

The best I was able to do was work in (the more forgiving) ES6 when defining the CustomBlock:

```
// in some CustomBlock.js file:

import * as Quill from 'quill';

const BlockEmbed = Quill.import('blots/block/embed');

export class CustomBlock extends BlockEmbed {
  // whatever you need your block to do
}
CustomBlock.blotName = 'custom';
CustomBlock.tagName = 'div';

export default CustomBlock;
```

And then use `require()` on the TypeScript side:

```
// in some Editor.ts file:
// (these are the relevant parts of a larger file)

import * as Quill from 'quill';
const customBlockModule = require('path/to/CustomBlock');

Quill.register(customBlockModule.CustomBlock);
this.editor = new Quill(someElement, someOptions);
this.editor.insertEmbed(someIndex, 'custom');
```

Is it ideal? No.

Does it work? Yes.

**Comment by noomz** [comment]
In my Angular 2 typescript environment,`Quill.import()` return `any` type which cannot be extended. So this is my approach:

```typescript
import * as Quill from 'quill';
import * as Parchment from "parchment";
const QuillBlockEmbed = Quill.import('blots/block/embed');

class BlockEmbed extends Parchment.default.Embed {}
BlockEmbed.prototype = QuillBlockEmbed.prototype;

class Video extends BlockEmbed {

}
```

**Comment by amccampos** [comment]
Thanks @noomz. I took several hours to figure out how to get Quill and Parchment working together in Typescript (Angular 2 env). Your approach saved the day.
It would be much easer if parchment typescript definitions were inside quill ts definitions.

**Comment by splodingsocks** [comment]
@noomz's solution helps my code to type check, but I get a runtime error from webpack when I use it:

<img width="984" alt="vivaldi_2017-04-18 14 32 04" src="https://cloud.githubusercontent.com/assets/1227109/25151711/cf0d92f4-2443-11e7-9deb-4a19cf39fe10.png">

**Comment by splodingsocks** [comment]
I was able to appease the compiler and avoid the runtime errors by declaring the type of BlockEmbed as Parchment.default.Embed:

```
import * as Parchment from "parchment"
const BlockEmbed = Quill.import("blots/block/embed") as typeof Parchment.default.Embed;

class Foo extends BlockEmbed {
    ...
}
```

**Comment by Percipient24** [comment]
I had been using @noomz's approach ( https://github.com/quilljs/quill/issues/1233#issuecomment-288968965 ) - but ran into an error when reading in a saved delta:

```
ERROR TypeError: Cannot read property 'length' of undefined
```
(Which seemed to have something to do with the `prototype` shenanigans.)

After switching to @splodingsocks' approach ( https://github.com/quilljs/quill/issues/1233#issuecomment-294973856 ) that error went away!

**Comment by noomz** [comment]
Is it related to tsconfig ? Below is mine:

```json
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2015",
      "dom"
    ],
    "mapRoot": "./",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5"
  }
}

```

**Comment by LouisWayne** [comment]
Try this:

```javascript
import * as Quill from 'quill';
import * as Parchment from "parchment";
const Block = Quill.import('blots/block') as typeof Parchment.default.Block;

export class CustomBlockBlot extends Block {
	static blotName: string = 'customBlock';
	static tagName: string = 'span';
}
```

**Comment by antonyboom** [comment]
I extended emded block as described below, but still getting an error 

> Error: [Parchment] Unable to create marker blot

what am I doing wrong? 

`...
import {Editor} from 'primeng/editor';

import * as Quill from 'quill';
import * as Parchment from 'parchment';
const Block = Quill.import('blots/block/embed');
class BlockEmbed extends Parchment.default.Embed {}
BlockEmbed.prototype = Block.prototype;

export class Variable extends BlockEmbed {

  static blotName = 'marker';
  static tagName = 'marker';

  static create(value: any) {
    console.log(value);
    const node = (super.create(value) as any);
    node.innerHTML = '<span contenteditable=false>' + value + '</span>';
    node.setAttribute('contenteditable', false);
    return node;
  }

}

Variable.blotName = 'marker';
Variable.tagName = 'marker';

Quill.register('formats/marker', Variable);

@Component({
  selector: 'manager',
  templateUrl: './manager.component.html',
  styleUrls: ['./manager.component.css']
})

export class ManagerComponent implements OnInit, AfterViewInit {

   private quill: any;
  @ViewChild(Editor) editorComponent: Editor;

  ngOnInit() {}

 // based on primeng github issue this how we can get references to quill 
  ngAfterViewInit() {
    this.quill = this.editorComponent.quill;
  }

 variableSelected(event) {
    // grubbing string variable from event 
    this.quill.insertEmbed(this.cursor.index || 0, 'marker', event.value);
  }

}`

**Comment by iblank** [comment]
Ok, I tried experimenting with your code in my own project and was able to reproduce the error you are getting. Try changing this:
```
import * as Quill from 'quill';
import * as Parchment from 'parchment';
const Block = Quill.import('blots/block/embed');
class BlockEmbed extends Parchment.default.Embed {}
BlockEmbed.prototype = Block.prototype;
```
to this:
```
declare var Quill: any;
const BlockEmbed = Quill.import('blots/block/embed');
```

**Comment by antonyboom** [comment]
@iblank Ian, I'm giving up to understand it.... Why does it work ?

**Comment by iblank** [comment]
It took a lot of trial and error for me to figure out too. This might not be exactly right but here goes...

Since `Quill` is defined globally from the JS file, you can use it here. `declare var Quill: any;` just let's typescript know that the variable is defined from outside of the scope of this file. Then your custom blot needs to extend BlockEmbed, so that is the only class you need to import from quill.

**Comment by antonyboom** [comment]
@iblank my respect to you, thanks a lot!

**Comment by xiehongyang** [comment]
is there anyone who meet this problem?
`ERROR TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.`

**Comment by chutuan1126** [comment]
`<table align="center" cellpadding="0" cellspacing="0" width="700" style="min-width:700px;max-width:700px;margin:0 auto">
    <tbody style="font-family: 'Roboto', Helvetica, Arial, sans-serif; margin: 0px auto; font-size: 0.875rem; overflow-x: hidden;">
    <tr>
        <td>
            <div class="website" style="max-width: 1280px; margin: auto; background: #f5f6fa;">
                <div class="login_top"
                     style="width: 100%; background-position: top left; background-repeat: no-repeat; background-size: contain; text-align: center; padding-bottom: 64px;">
                    <div class="logo" style="padding: 32px;  display: flex; justify-content: space-between">
                    </div>
                    <div class="login_box"
                         style="width: 80%; box-shadow: 0 2px 8px 0 rgba(112, 112, 112, 0.08); background-color: #ffffff; text-align: center; margin: auto; border-bottom: 1px solid #f5f6fa; border-radius: 12px;">
                        <div class="logo"
                             style="border-top: 4px solid #019bfa; border-top-left-radius: 3px; border-top-right-radius: 3px ;padding: 24px 32px; display: flex; justify-content: space-between; align-items: center;">
                            <a href="#" style="display: flex; width: 50%;"><img
                                    src="{{logo_url}}"
                                    alt="" style="height: 20px; margin: auto 0;"/></a>
                            <div style="display: flex;  width: 50%;">
                                <span style="display: flex; margin: auto;">Hotline: 0899 909 868</span>
                                <div style="margin: auto 16px; background-color: rgba(73, 73, 73, 0.2); width: 1px; height: 20px;"></div>
                                <a href="https://www.facebook.com/Omicall"
                                   style="margin: 5px 16px 5px 0px; height: 20px;">
                                    <img src="https://minio.infra.omicrm.com/omi-resource/icon_facebook@2x24_24.png"
                                         alt="" style="width: 20px; height: 20px;"/>
                                </a>
                                <a href="https://www.youtube.com/channel/UCNO5UuGCuqL8EOJEYSOqxqg"
                                   style="margin: 5px 0px 5px 0px; height: 20px;">
                                    <img src="https://minio.infra.omicrm.com/omi-resource/icon_youtube@2x24_24.png"
                                         alt="" style="width: 20px; height: 20px;"/>
                                </a>
                            </div>
                        </div>
                        <div class="login_text"
                             style="font-size: 0.875rem; text-align: center; color: #494949; padding: 0 32px; margin: auto;">
                            <h2 style="text-align: left;">Giao dịch trừ tiền</h2>
                            <p style="margin-bottom: 0;margin-top: 0; text-align: left;">
                                Chào {{fullName}}, doanh nghiệp <strong>{{tenantName}}</strong> đã phát sinh giao dịch
                                <b style="color: #e94440; text-align: left;">-{{deductionAmount}} {{tenantCurrency}}</b> với lý do <b>{{paymentMethod}}</b>.</p>
                            <p style="color: #267aff; font-style:italic; text-align: left;">Số dư tài khoản hiện tại <b>{{tenantBalance}} {{tenantCurrency}}</b>.</p>
                            <br/>
                            <br/>
                            <hr style="opacity: 0.2; color:#494949; margin: 0"/>
                            <div class="login_textend" style="text-align: left; margin-bottom: 10%;">
                                <br/>
                                <p style="margin-bottom: 0; font-size: 0.875rem; color: #494949;">
                                    {{mailHaveAGoodDay}}</p>
                                <p style="margin-bottom: 0; font-size: 0.875rem; color: #494949;"><strong>
                                    {{mailDeveloperTeam}}</strong></p>
                            </div>
                        </div>
                        <div class="logo"
                             style="border-bottom-left-radius: 3px; border-bottom-right-radius: 3px ;padding: 24px 32px; background-color: #267aff; display: flex; justify-content: flex-start;">
                            <div><img src="https://minio.infra.omicrm.com/crm/logo-6-min.png" alt=""
                                      style="width: 40px; text-align: left;"/>
                            </div>
                            <div style="text-align: left; margin-left: 20px;">
                                <p style="margin: 0; margin-bottom: 5px; color: #ffffff">Công ty TNHH Công Nghệ
                                    VIHAT</p>
                                <p style="margin: 0; color: #ffffff; opacity: 0.5;">Số 06, đường 16, Hiệp Bình Chánh,
                                    Thủ Đức, TPHCM</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </td>
    </tr>
    </tbody>
</table>
`

**Comment by benbro** [comment]
v2.0.0-beta.2 provides TypeScript definitions.

**Comment by SCWR** [comment]
@benbro Do you have any documentation? I couldn't find a description in the documentation 
[https://quilljs.com/docs/guides/cloning-medium-with-parchment#tweets](https://quilljs.com/docs/guides/cloning-medium-with-parchment#tweets)

**Comment by mattes3** [comment]
Today, in 2024 with Quill V2, I am using this:

```ts
import { EmbedBlot } from 'parchment';

class Foo extends EmbedBlot {
...
}
```
