### ISSUE TITLE
TypeScript classes not compatible with quill dist

### ISSUE THREAD

**Issue by arahansen** [quilljs/quill#1236]
I'm having issues extending Parchment blots (specifically Inline, and Block) using TypeScript's class definition transpilation to ES5.

When TypeScript is configured to output ES6 code (ie, does not transpile class definitions) the following code works as expected (`should be called when formatting` is logged to the console).

But when TypeScript is configured to output ES5 code (and *does* transpile class definitions), the formats method in `SampleBlot` is not called.

**Steps for Reproduction**

```js

// editor.ts (TypeScript file)
import * as Quill from 'quill';

let Inline = Quill.import('blots/inline');

class SampleBlot extends Inline {
  static formats(node) {
    console.log('should be called when formatting');
    return 'H1'; // just returning an h1 tag for demonstration purposes
  }
}
HeaderBlot.blotName = 'sample';
HeaderBlot.tagName = 'H1';

setTimeout(() => {
  quill.format('sample', 1);
}, 1000); // arbitrarily update format after 1 second (for demonstration)

Quill.register('formats/sample', SampleBlot); // have also tried Quill.register(SampleBlot);
const quill = new Quill(document.querySelector('#editor');
```

**Expected behavior**:
formats method is called and `should be called when formatting` is logged to the console.

**Actual behavior**:
formats method is not called and the console is empty.

**Platforms**:
Quill 1.1.5
TypeScript 2.1.4
Chrome 55

**Comment by arahansen** [comment]
One workaround may be to forego using class definitions for my extension and use ES5 the whole way through. However, I'm struggling to find documentation on how this might be accomplished.

**Comment by davidye** [comment]
I'm also seeing this issue:

```
import * as Quill from 'quill';

const Block = Quill.import('blots/block');

class TestBlot extends Block {
  public static blotName = 'test';
  public static tagName = 'blockquote';
}

console.log(Block.scope) // => 10
console.log(TestBlot.scope) // => undefined

```

**Comment by davidye** [comment]
When I try this same code with babel, it works:

```
import Quill from 'quill';

const Block = Quill.import('blots/block');

class TestBlot extends Block {
  public static blotName = 'test';
  public static tagName = 'blockquote';
}

console.log(Block.scope) // => 10
console.log(TestBlot.scope) // => 10
```

//  in parchment package
class BlockBlot extends FormatBlot { ... }

// in quill package
class Block extends Parchment.Block { ... }

Consuming the dist file with typescript is broken but with babel it is fine? I wonder if it's because the parchment package is transpiled by typescript but quill package is transpiled by babel?

**Comment by arahansen** [comment]
I was able to get TypeScript compilation to work correctly with the following example:

```js
const Block: IBlock = Quill.import('blots/block');
const Parchment: IParchment = Quill.import('parchment');

class LineHeightBlot extends Block {
	static blotName = 'lineHeight';
	static tagName = 'SPAN';
	static scope = Parchment.Scope.BLOCK;

	static create(value) {
		const node = super.create();
		node.style['line-height'] = value;
		return node;
	}

	static formats(node) {
		return $(node).css('line-height');
	}
}
```

**Comment by rfruesmer** [comment]
Same problem here while trying to implement a table blot based on BlockEmbed. 

In a plain Babel setup with ES2015 preset the blot is correctly registered and called after invocation of quill.insertEmbed(), but in our real environment (Angular 2.3/TypeScript 2.0/Webpack 1.13) it's not - regardless of transpiling from ts->es6->es5 with babel at the end or with tsc only from ts directly to es5. 

Error Message: "[Parchment] Unable to create table blot"

Stacktrace:

"Error: [Parchment] Unable to create table blot
    at ParchmentError.ZoneAwareError (eval at <anonymous> (http://localhost:8090/polyfills.js:3140:2), <anonymous>:738:33)
    at new ParchmentError (eval at <anonymous> (http://localhost:8090/app.js:814:2), <anonymous>:734:25)
    at Object.create (eval at <anonymous> (http://localhost:8090/app.js:814:2), <anonymous>:765:16)
    at BlockBlot.insertAt (eval at <anonymous> (http://localhost:8090/app.js:814:2), <anonymous>:1496:34)
    at Block.insertAt (eval at <anonymous> (http://localhost:8090/app.js:814:2), <anonymous>:4522:124)
    at Scroll.ContainerBlot.insertAt (eval at <anonymous> (http://localhost:8090/app.js:814:2), <anonymous>:279:20)
    at ScrollBlot.insertAt (eval at <anonymous> (http://localhost:8090/app.js:814:2), <anonymous>:1265:36)
    at Scroll.insertAt (eval at <anonymous> (http://localhost:8090/app.js:814:2), <anonymous>:6413:104)
    at Editor.insertEmbed (eval at <anonymous> (http://localhost:8090/app.js:814:2), <anonymous>:4034:20)
    at eval (eval at <anonymous> (http://localhost:8090/app.js:814:2), <anonymous>:2025:31)
    at Quill.modify (eval at <anonymous> (http://localhost:8090/app.js:814:2), <anonymous>:2249:17)
    at Quill.insertEmbed (eval at <anonymous> (http://localhost:8090/app.js:814:2), <anonymous>:2024:22)
    at InsertTableCommand.execute (eval at <anonymous> (http://localhost:8090/app.js:982:2), <anonymous>:51:24)
    at ToolbarButton.onClick (eval at <anonymous> (http://localhost:8090/app.js:1084:2), <anonymous>:61:30)
    at CompiledTemplate.proxyViewClass.View_ToolbarButton0.handleEvent_0 (/AppModule/ToolbarButton/component.ngfactory.js:87:34)
    at CompiledTemplate.proxyViewClass.eval (eval at <anonymous> (http://localhost:8090/vendor.js:104:2), <anonymous>:12778:41)
    at HTMLAnchorElement.eval (eval at <anonymous> (http://localhost:8090/vendor.js:212:2), <anonymous>:3216:55)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8090/polyfills.js:3140:2), <anonymous>:275:35)
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:8090/vendor.js:104:2), <anonymous>:4396:41)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8090/polyfills.js:3140:2), <anonymous>:274:40)
    at Zone.runTask (eval at <anonymous> (http://localhost:8090/polyfills.js:3140:2), <anonymous>:151:47)
    at HTMLAnchorElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:3140:2), <anonymous>:345:33)"


Entry point:

import {Injectable} from "@angular/core";
import {Command} from "../../../../common/command/command";
import {SelectionService} from "../../../../common/selection/selection.service";
import Parchment from "parchment";
import {TableBlot} from "./table-blot";

@Injectable()
export class InsertTableCommand implements Command {
    private initData = [
        ["Column A", "Column B", "Column C"],
        ["value 1", { "options": { "style": "color: red" }, "value": "value 2" }, "value 3"],
        ["value 4", { "options": { "colSpan": 2, "style": "font-weight: bold" }, "value": "value 5" }]
    ];

    constructor(private selectionService: SelectionService) {
        // do nothing
    }

    execute(): any {
        try {
            Parchment.register(TableBlot);

            let editor = this.selectionService.getEditor();
            editor.insertEmbed(1, "table", this.initData);
        }
        catch (e) {
            console.error(e);
        }
    }

    canExecute(): boolean {
        return !!this.selectionService.getEditor();
    }
}

Blot:

import Parchment from "parchment";
const Quill = require("quill");

const BlockEmbed: IBlock = Quill.import("blots/block/embed");

interface IBlock {
    new(someParam: any): IBlock;
    create(values: any): any;
}

export class TableBlot extends BlockEmbed {
    public static blotName = "table";
    public static tagName = "TABLE";
    public static scope = Parchment.Scope.BLOCK;


    static create(values: any) {
        return super.create(values);
    }

    static value(node: any): any {
        return [];
    }
}

Please advise.

**Comment by rajivchugh** [comment]
@arahansen I am facing the same issue. Where did you get reference to IBlock and IParchment. Can you show your complete code please.

**Comment by arahansen** [comment]
Those interfaces are stubbed out as 

```
interface IBlock extends ObjectConstructor {
	create(...any): HTMLElement;
}
```

**Comment by rajivchugh** [comment]
@arahansen This fixed my issue.

**Comment by sumitkm** [comment]
@rajivchugh @arahansen when using TypeScript are you referencing type-definitions for Parchment as well?
I maintain the quill type def on DefinitelyTyped and I have not included the Parchment definitions because Parchment is written in TS and now exposes its own definitions.

I am going to give your code a spin and see if I can help with the Quill Definitions in any way. They need an upgrade anyways.

**Comment by jhchen** [comment]
Thank you for your work on Quill + DefinitelyTyped @sumitkm by the way!

**Comment by sumitkm** [comment]
Thanks @jhchen, happy to make a tiny contrib to the awesome "Quill" :-)

**Comment by vad3x** [comment]
@arahansen The workaround does not work when I try to extend `Container` for example (actually when I try to use `this` or `super` on the not static methods).
@jhchen Any plans to rewrite `quill` to TS? :)

**Comment by maku** [comment]
@arahansen Any idea how to write an specific LinkBlot in typescript. 
I am trying for hours without success...

BTW, using quill with typescript is really hard!!!

**Comment by rh78** [comment]
I have the sample problem when trying to customize the Link Blot using TypeScript. It is simply a nightmare. Will try to continue tomorrow but did not yet find solution.

**Comment by maku** [comment]
@rh78 I ended up with something like this. I think it is suboptimal but it works:

```
import * as Quill from 'quill';
const Link = Quill.import('formats/link');

export function registerCustomLinkBehaviour(): void {

  Link.sanitize = function (url): string {
    ....

    return url;
 };

  Link.create = function (value): HTMLAnchorElement {
    let link: HTMLAnchorElement = document.createElement('a');
    ....
    return link;
  };

}

```

**Comment by rh78** [comment]
Hi we today got it. Let me show you:

const ReactQuill = require('react-quill');
const Quill = ReactQuill.Quill;
import * as Parchment from "parchment";

const QuillBlockInline = Quill.import('blots/inline');

class BlockInline extends Parchment.default.Inline {}
BlockInline.prototype = QuillBlockInline.prototype;

...

class Link extends BlockInline {

  static blotName = 'link';
  static tagName = 'A';
  static SANITIZED_URL = 'about:blank';

  static create(value: any) {
    let node = (super.create(value) as any);
    let href: string = this.sanitize(value);
    node.setAttribute('href', href);

...

    return node;
  }

  static formats(domNode: any) {
    return domNode.getAttribute('href');
  }

  static sanitize(url: string) {
    return sanitize(url, ['http', 'https', 'mailto', 'ftp', 'tel']) ? url : this.SANITIZED_URL;
  }

  static value(node: any) {
    return node.getAttribute('href');
  }

  format(name: string, value: string) {
    if (name !== this.statics.blotName || !value) return super.format(name, value);
    value = Link.sanitize(value);
    this.domNode.setAttribute('href', value);
  }
}

function sanitize(url: string, protocols: string[]) {
  let anchor = document.createElement('a');
  anchor.href = url;
  let protocol = anchor.href.slice(0, anchor.href.indexOf(':'));
  return protocols.indexOf(protocol) > -1;
}

export default Link;

**Comment by DrewLandgrave** [comment]
So this is almost 2 years later but I came on this due to similar issues. 
@maku you're receiving the not _blot message is because of the constructor missing arguments. When quill calls new on your blot it passes 2 arguments, and you, in turn, need to pass them to your super call.

Like this

`export class ImageShortcodeBlot extends BlockShortcodeBlot {

  static blotName: string = 'imageShortcode';

  static tagName: string = 'DIV';

  /** @inheritdoc */
  static create(domNode: HTMLElement) {
    if (this.isImageShortcode(domNode)) {
      const data = domNode.dataset;
      const img = document.createElement('IMG') as HTMLImageElement;
      img.src = `some url`;
      img.setAttribute('data-shortcode', 'image');
      return img;
    }

    return super.create(domNode);
  }

  /**
   * Checks for the presence of the data-shortcode=image attribute
   * @param {HTMLElement} domNode
   * @returns {boolean}
   */
  static isImageShortcode(domNode: HTMLElement): boolean {
    return domNode.dataset && domNode.dataset.shortcode === 'image';
  }

  actionSheet: ImageShortcodeActionSheet;

  constructor(public domNode: HTMLElement, value?: HTMLElement) {
    super(domNode, value);
    if (ImageShortcodeBlot.isImageShortcode(domNode)) {
      this.actionSheet = AppInjector.get(ImageShortcodeActionSheet);
      this.data = value.dataset;
      this.modelTag = value;
      domNode.addEventListener('click', () => {
        this.actionSheet.present({});
        this.actionSheet.onRemove.subscribe(() => {
          this.hRemove();
        });
      });
    }
  }
}`
