### ISSUE TITLE
I want to extend the List format to a new container class but I am having issues

### ISSUE THREAD

**Issue by xavierbloemen** [quilljs/quill#1237]
I want to make a new format that uses a container <div> and contain blocks (<p>) so I copied List and ListItem to adjust it, so I tried to change List itself to get the desired functionality but It doesn't work and I need some help to figure out what i am doing wrong. Any help would be greatly appreciated!

so I wrote a pen on codepen so show you what I want to do and what error I get. 

**Steps for Reproduction**

1. http://codepen.io/X4VIER/pen/rjarWg
2. Run pen
3. Check console to see error

**Expected behavior**:
create a custom list with 1 item, then a paragraph and add another custom list with 1 item
**Actual behavior**:
throws `Uncaught TypeError: Cannot read property 'emitter' of undefined` during attempt to create second List
**Platforms**:
MacOS Sierra 10.12.2, Chrome 55.0.2883.95

**Version**: 1.1.9

**Comment by seekforwings** [comment]
- [ ] 

- [x ]  kjhkjh

**Comment by rikh42** [comment]
You're not overriding the default ListItem I think...

```
Quill.register(List, true);
Quill.register(ListItem); // Should also have a 'true' parameter
```

Try registering them more like this...

```
Quill.register({
    'formats/list/item': ListItem,
    'formats/list': List,
}, true);
```

**Comment by XavierBloemen** [comment]
That didn't fix it, but I did found another weird thing.

when I call `quill.format('list', false)` doesn't seem to work. only when I exit the list format and make a new text block with only a `<br>` in it and call

```
quill.removeFormat(range.index, range.index + 1);
 quill.format('list', true);
```

then it works

**Comment by XavierBloemen** [comment]
I made an example of the behavior written above. I am guessing that something is going wrong with closing two tags (`</p>, </div>`) when I am calling `quill.format('list', false);` but I can't find where the problem is so any hints would be very welcome.

https://codepen.io/X4VIER/pen/xgwgeG

**Comment by jhchen** [comment]
The way List and ListItem works is ListItem does the formatting and sometimes it has to split its parent List, for example going from 

```html
<ul>
  <li>1</li>
  <li>2</li>
  <li>3</li>
</ul>
```

to

```html
<ul>
  <li>1</li>
</ul>
<ol>
  <li>2</li>
</ol>
<ul>
  <li>3</li>
</ul>
```

Looking at the your stack trace, ListItem's parent is not a List but the root Scroll itself, so splitting it will cause problems. Why that is occurring is not clear.

**Comment by XavierBloemen** [comment]
I sort of fixed it. By change `Block.tagName = 'DIV'` My custom list works see http://codepen.io/X4VIER/pen/RKrbOz?editors=0010

I suspect that because Block tagName was <p> and my custom ListItem's tagName was also <p> something went wrong there and I suspect It also has something to do that List is a container class, but can't find any proof.

**Comment by billyshena** [comment]
@XavierBloemen Did you figure out a fix for the 'emitter of undefined' error ?
I posted an issue here: https://github.com/quilljs/quill/issues/2309 if you have any ideas, would be really helpful !

**Comment by billyshena** [comment]
```
let ListItem = Quill.import('formats/list/item')
ListItem.tagName = 'P'
Quill.register('formats/list', ListItem)

```
If I replace my <li> tags by <p> tags I have the error "emitted of undefined" but If I use `ListItem.tagName = 'DIV'` it works well, no errors.

Any ideas how I can replace all <li> by <p> tags ? Or maybe a way to disable the auto-list feature of the editor (which puts <ul> + <li> when I type a "-")

Best,

**Comment by XavierBloemen** [comment]
@billyshena We had to move on from Quill because of these issues. You can find stories like [these](https://stackoverflow.com/questions/43530207/quill-js-extending-blot-parchment-changes-not-captured-in-delta) that architecture has some hard choices (most based in Parchment) that tags have inherit logic that is hidden, causing these weird bugs. 

Quill is good when you don't try to change/extend it IMHO

**Comment by billyshena** [comment]
@XavierBloemen I see, well I am gonna keep trying, thanks for the answer !
@jhchen Any ideas ?

**Comment by billyshena** [comment]
I just checked Slack and they are doing it pretty well (converting <li> to <p> tags using quill)

<img width="1280" alt="capture d ecran 2018-09-18 a 12 13 58" src="https://user-images.githubusercontent.com/6057397/45680927-8050a200-bb3c-11e8-9537-bb5daaf350f9.png">

**Comment by thiswhy** [comment]
It's very helpful ,but i need more complexity request .I need the dom tree like this .
<p>
    <span>
        <span>a</span>
        <span>b</span>
    </span>
    <span>c</span>
    <span>
        <span>d</span>
    </span>
</p>

How can I implement it ,THX

**Comment by thiswhy** [comment]
`It's very helpful ,but i need more complexity request .I need the dom tree like this .
<p>
    <span>
        <span>a</span>
        <span>b</span>
    </span>
    <span>c</span>
    <span>
        <span>d</span>
    </span>
</p>

How can I implement it ,THX `
