### ISSUE TITLE
Top Position of ql-tooltip is incorrect when creating a link and scrolling is set on the quill container

### ISSUE THREAD

**Issue by sbevels** [quilljs/quill#1238]
I've set overflow-y: auto on the Quill container and overflow-y: unset for ql-editor.  This appears to cause the Edit link div to have the wrong position in the Quill editor.  I noticed there is a scrollingContainer option and I've set that to the container, but it doesn't resolve this issue.

Looking at the position function for ui/toolbar.js, I noticed that in this scenario, this.quill.root.scrollTop === 0, whereas this.quill.scrollingContainer has the correct value.  Is it possible to use scrollingContainer instead of root if it is set?

**Steps for Reproduction**

1. Visit http://codepen.io/sbevels/pen/JEovaL
2. Scroll to the bottom.
3. Select a word and click the link button.

**Expected behavior**:
Edit link ql-tooltip div appears near the highlighted word.

**Actual behavior**:
The position of the ql-tooltip is not correct and cause the page to scroll up to its position.

**Platforms**:
Firefox

**Version**:
1.1.9

**Comment by jhchen** [comment]
I'm not sure the right fix for this at the moment but a workaround for your specific codepen scenario is to get rid of the `bounds` config option (or set it to document.body).

**Comment by jhchen** [comment]
Upon closer inspection the CSS rules in codepen seems to be confusing Quill. If you use the same rules as demonstrated in the Quill [autogrow](http://quilljs.com/playground/#autogrow-height) example, there is no issue adding a scrollContainer config.

It looks like you started from that example but then made changes to use the Snow theme with the toolbar persistent. If this is the intention the recommended way to go about it is something like this: http://codepen.io/quill/pen/apmWXm. This does have the downside that you have to provide your own toolbar markup as unfortunately right now the toolbar either allows you to specify your own container or it will build one. The one it builds will not be placed in the right location for your use case so you must provide your own.

**Comment by NishantVerma12** [comment]
http://codepen.io/quill/pen/apmWXm @jhchen how we create and save the link because I was trying to save the link but it is given there.
