### ISSUE TITLE
Provide a way to control the order that keyboard bindings are executed

### ISSUE THREAD

**Issue by rikh42** [quilljs/quill#1239]
I have been extending Quill with new formats, such as tables, and have needed to add many keyboard bindings as part of this process.

However, it has always been very difficult to override the default built in handlers and maintain control over the order that key bindings are handled by the Keyboard module. I'd like to start a discussion on improving this.

For example. when editing tables it is desirable for TAB to advance the cursor to the next table cell. This is what happens in Google Docs and MS Word for example. Quill provides a default TAB handler that inserts a tab character into the document. On pressing TAB, the default handler is executed and additional handlers added using addBinding() are never reached (as the default one completes successfully). 
It is possible to replace the default handler with one that does nothing, but this has to be during the creation of the Quill object. In the example above, I actually still want the default behaviour outside of tables, so I have to add it back in again with a different name. All in all, it's rather messy and hard to manage.

**Suggested options**

- Update addBinding to take an additional parameter that indicates if the new binding should be pushed to the end of the list of available binding, or inserted at the start of the list of key bindings. This would make it simple to add a key binding that is executed ahead of the bindings already registered. Developers would have basic control over the order of execution and would still be able to full override bindings using the existing approach.
- or Update the Keyboard module so that bindings have a 'sort order' property that controls the order they are executed. This would also make it simple for developers to add new bindings ahead of the defaults, or at any stage in the list of bindings. Defaults could be applied to ensure no back compatibility problems.
- or Update the Keyboard module to take into account specificity of the binding, with more specific bindings being executed first. For example, a binding on TAB when Shift is pressed, in an empty list item is very specific and is executed ahead of a binding on just TAB (assuming all its criteria are met). This option would likely have back-compat. issues though.

**Comment by jhchen** [comment]
Quill's event handlers are all inserted at once. If you want yours to run before Quill's, you can add it to the initialization configuration. If you want to run after, you can call addBinding after initialization. If you want to selectively run it before (like the tab use case described) you can `return true` to "continue" to the next binding.

I think this covers all the bases relative to Quill's handlers. How you order your calls to addBindings is completely under your control and organizing this should fall outside of Quill.

Given the lack of comments I'm not sure there is a strong need for this and I'm not personally a fan given the increase in API surface and complexity. Are there other use cases that necessitate the creation of these APIs?
