### ISSUE TITLE
Is quill not supported for IE8?

### ISSUE THREAD

**Issue by seekforwings** [quilljs/quill#1243]
@jhchen Hello, I found that someone said, quill is supported on IE9+, but not for IE8. Well, I wonder if it is because that quill uses es6. And I wonder if I use babel, can I make it supported for IE8?

**Comment by jhchen** [comment]
No. Browser support is determined by availability of DOM APIs and lack of bugs. Also the lowest version of IE Quill supports is 11, not 9.
