### ISSUE TITLE
VueJs and Quill instanceof Error

### ISSUE THREAD

**Issue by DeKugelschieber** [quilljs/quill#1246]
While integrating Quill into my VueJs application, I faced an error when initializing it wihin a VueJs directive:

`TypeError: Right-hand side of 'instanceof' is not callable
    at _clone (quill-1.1.9.js:5583)
    at clone (quill-1.1.9.js:5679)
    at Selection.update (quill-1.1.9.js:6158)
    at new Selection (quill-1.1.9.js:5856)
    at new Quill (quill-1.1.9.js:1788)
    at inserted (app.js:86)
    at $t (vue.min.js:6)
    at Object.u [as insert] (vue.min.js:6)
    at $ (vue.min.js:6)
    at Ie.__patch__ (vue.min.js:6)`

This is caused by this line within the clone method (you can find it on https://cdn.quilljs.com/1.1.9/quill.js by searching for "instanceof Error"):

`} else if (parent instanceof Error) {`

And can be solved by checking against the constructor instead:

`} else if (parent instanceof Error.constructor) {`

You may want to consider to change this, since it shouldn't affect anything, except Vue applications.

**Steps for Reproduction**

1. create a custom Vue directive for Quill:

`Vue.directive('editor', {
	inserted: function(el){
		new Quill(el, {
			theme: 'snow'
		});
	}
});`

2. use it within a component:

`<div v-editor></div>`

3. see console output

**Expected behavior**:

Quill is initialized successfully.

**Actual behavior**:

Error is thrown (see above).

**Platforms**:

Chrome 50 on Ubuntu 16.04 64bit.

**Version**:

1.1.9

**Comment by jhchen** [comment]
This line is actually from the [clone](https://www.npmjs.com/package/clone) library. I'm not going to encourage taking it up with them because it's not clear this is a clone issue or vue issue or just an issue with your application and the claim that the fix would not have adverse side affects is unsubstantiated.

**Comment by DeKugelschieber** [comment]
Ah I see and may talk to them, thank you.
