### ISSUE TITLE
Last line with format uses retain:1 instead of newline causing confusion

### ISSUE THREAD

**Issue by g-borgulya** [quilljs/quill#1247]
I use custom line formats, my own blot, and apply them to the lines with the formatLine API call. If I set a line format in the last line, the op will contain a `retain: 1` and the `attribute`, and not the otherwise usual `insert: '\n'` and the attribute. This op remains the like this even if other text is put after the line in question, so it's possible, that the line attributes are sometimes not assigned to a `'\n'` but to a `retain: 1`, where there's no `'\n'`.

This used to cause the the editor to fail, but https://github.com/quilljs/quill/commit/2df224a9eff8adae724100d3c1f8ab7594ffcfe6 corrected the problem. 

But still, this puts a lot of twist and complication in my custom scripts processing the ops like for html rendering. And for example also makes the quill-renderer fail: https://github.com/UmbraEngineering/quilljs-renderer

I'm not sure if this is intentional, I decided to ask about it.

**Steps for Reproduction**

Hard to say, how to do that in a non customized quill, but my guess is below. I'm not 100% sure that it's not caused by my custom blot. I simply don't understand quill's op-mechanisms deep enough to say.

1. Open a quill editor
2. Make sure you can check the deltas produced by quill, for example
`quill.on('text-change'(delta, oldDelta, source) => { ... })`
3. Set the last line as a header, and see delta

**Expected behavior**:
I'd expect that the last op in the delta would be `{insert:'\n',attribute:{...}}`

**Actual behavior**:
Actually it's `{retain:1,attribute:{...}}`
There's no new line for the line in question even if it gets in to the middle of the doc later by editing the text. The cause of the confusion is the missing `'\n'`, as it's hard to say if a `retain: 1` should mean a newline or not.

**Platforms**:

Chromium Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04 (64-bit)

**Version**:
1.1.9

**Comment by jhchen** [comment]
> and not the otherwise usual insert: '\n' and the attribute

In what scenario have you called formatLine with one of the core formats and gotten an insert '\n'? The expected behavior is actually a retain.
