### ISSUE TITLE
Caret position not preserved when applying delta that affects caret's line.

### ISSUE THREAD

**Issue by danfuzz** [quilljs/quill#1251]
If one applies a delta to a document that affects the line that the caret is on, the caret gets moved to the beginning of the line instead of maintaining its effective position across the edit. For example, let's say the document is:

```
first line
stuff >|< more >< stuff
third line
```

where `|` represents the caret. If I apply a delta which just inserts `x` between the second `><`, then the result is:

```
first line
|stuff >< more >x< stuff
third line
```

That is, the caret gets moved to the start of the line. This behavior is _not_ present in version 1.1.6 of Quill and _is_ present in versions 1.1.7 through 1.1.9.

**Steps for Reproduction**

1. Install and run the Bayou (formerly Quillex) project. <https://github.com/danfuzz/bayou>

   ```
   $ git clone git@github.com:danfuzz/bayou.git
   $ cd bayou
   $ ./develop
   ```

2. Open two browser windows, pointing at `http://localhost:8080`.
3. Paste `stuff >< more >< stuff` into one of the editors.
4. Place the caret in one of the windows between the first `><`.
5. Place the caret in the other window between the second `><`.
6. Type `x`.
7. Observe the caret position in the window not typed into.

**Expected behavior**:

The caret remains between the `><`.

**Actual behavior**:

The caret gets moved to the start of the line.

**Platforms**:

Tested on macOS, running Chrome 55.0.2883.95.

**Version**:

1.1.7, 1.1.8, and 1.1.9

**Notes**:

Taking the actions as described above results in Bayou making a call to the Quill method `updateContents`, with a "source" of `doc-client`. Changing this to a source of `api` does _not_ affect the behavior.

**Comment by danfuzz** [comment]
Here's a screencap of the problem happening as described:

![caret-move](https://cloud.githubusercontent.com/assets/1090235/21782851/c9a2983c-d669-11e6-8e52-2630123eecb7.gif)

**Comment by danfuzz** [comment]
I narrowed the introduction of the problem down to the commit <https://github.com/quilljs/quill/commit/0ff7d3dcaf477a793b292e168d9e461756f6987b>, which is the following one-line change to line 394:

```
   let range = index == null ? null : this.getSelection();
    let oldDelta = this.editor.delta;
    let change = modifier();
 -  if (range != null) {
 +  if (range != null && source === Emitter.sources.USER) {
      if (index === true) index = range.index;
      if (shift == null) {
        range = shiftRange(range, change, source);
```

Undoing this change fixes the problem described by this bug. Ironically, the description of issue #1152, which this commit is supposed to fix, implies that the fix should _prevent_ cursor jumping.

**Comment by danfuzz** [comment]
I think this bug is describing the same issue described in the comment <https://github.com/quilljs/quill/issues/1152#issuecomment-271008503>.

**Comment by jhchen** [comment]
This should be fixed by https://github.com/quilljs/quill/commit/51c03ba60d4c27d66ade7b7ff505c24ebd943fff and will go out in the next release.
