### ISSUE TITLE
NS_ERROR_FAILURE in Firefox

### ISSUE THREAD

**Issue by drozdzynski** [quilljs/quill#1262]
browser: Firefox 39.0
system: Windows 7
quill: 1.1.9

Error code:
```
NS_ERROR_FAILURE: 
  at func (~/quill/dist/quill.js:2403)
```

At line:
`document.execCommand("enableObjectResizing", false, false);`

Issue just after page loaded.

**Comment by jhchen** [comment]
Firefox 39 is no longer supported. I'm not seeing it happening on the latest two versions.

**Comment by drozdzynski** [comment]
Which is minimal supported? @jhchen

**Comment by jhchen** [comment]
The latest two versions. They are also posted on the README.
