### ISSUE TITLE
Unable to change back to default font.

### ISSUE THREAD

**Issue by ivanstefan17** [quilljs/quill#1263]
Unable to change back to default font. 

**Steps for Reproduction**

1. Visit https://codepen.io/anon/pen/pRbbGr
2. Add any text in the quill editor and set the font to Serif or Monospace
3. Attempt to change it back to Sans-serif

**Expected behavior**:

The font should be set back to Sans Serif.

**Actual behavior**:

The font doesn't change back to Sans Serif after having a different font.

**Platforms**:

Windows 8.1 Pro 
Tested in Chrome Version 55.0.2883.87 m (64-bit)

**Version**:
Tested on both Quill 1.1.6 && Quill 1.1.9

**Comment by jhchen** [comment]
To disambiguate between setting a format to the default value and removing that format, only the latter is allowed. So instead of `{ font:['serif', 'sans-serif', 'monospace']}` it should be { font:['serif', false, 'monospace']}`
