### ISSUE TITLE
can not insert input inside editor div at cursor position

### ISSUE THREAD

**Issue by prajapati-gautam** [quilljs/quill#1264]
i am tried to add input in editor to show as blank filler sentence.
but there were no option  found  to insert HTML input tag at cursor pointer. 

```
$('.add-input').on("click",function(){ 
     var range = quill.getSelection(!quill.hasFocus());
     var inputBox = '<input type="text"/>'
      quill.insertHtml(range.index,inputBox,'','',null,'api'); 
});

<button class="add-input">______</button>
```
and or any other option how to show input type text in output.

**Comment by jhchen** [comment]
https://github.com/quilljs/quill/blob/master/.github/CONTRIBUTING.md

**Comment by prajapati-gautam** [comment]
hey my issue is simple can you help me please??
can plugin parse HTML i want to add just input box or textarea in editor.
is that possible please replay as soon as.
thanks again




*Gautam b prajapati* <prajapatig42@gmail.com>

**Comment by PeterDias55** [comment]
@prajapati-gautam   any solution so far?

**Comment by solaimanshadin** [comment]
@prajapati-gautam Any solution so far?
