### ISSUE TITLE
Open image dialog is very slow in Chrome 

### ISSUE THREAD

**Issue by bigggge** [quilljs/quill#1265]
Steps for Reproduction
Visit quilljs.com and go to editor, click select image button

Expected behavior: Opened immediately.

Actual behavior: It takes 6~10s.

Platforms: Chrome 55.0.2883.95, macOs 10.12.1

Version: 1.1.9

**Comment by Joeao** [comment]
At first it was taking up to about 0.5 seconds to pop up, however it seems the longer I leave the page open, the longer it takes.
Am now getting roughly 6-10 seconds before it triggers, as you are.

Platform: Chromium 55.0.2883.87 Ubuntu 16.04 (64-bit)

**Comment by jhchen** [comment]
It is opening nearly immediately for me on Chrome 55 macOS 10.12.2 ever since #1090. The Chrome [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=638874) is still outstanding it seems but the PR added to workaround described in the bug report. Can you guys try with all extensions disabled?

**Comment by laosb** [comment]
On my computer it takes roughly about 10s, within Chrome Incognito Window with no extension. 

Chrome: 55.0.2883.95 (64-bit)
OS: 10.12.3 Beta (16D17a)

**Comment by ryanlin1986** [comment]
Me too:
Win10 x64+chrome 56

**Comment by hongmomanu** [comment]
@jhchen 
i think the problem is  the accept attr  image/svg+xml ,if you delete it , it will be fine

**Comment by jhchen** [comment]
@hongmomanu You were able to reproduce the 10s slowdown and removing the image/svg+xml fixed it? I've never been able to reproduce since #1090.

**Comment by hongmomanu** [comment]
@jhchen  .right!    chromium  56.0.2924.87 (64-bit) for linux

**Comment by jhchen** [comment]
Great thanks--can someone else who has been able to reproduce this confirm this fix?
