### ISSUE TITLE
How to handle foucs out / blur events

### ISSUE THREAD

**Issue by fpavlic** [quilljs/quill#1269]
Hi Jason,

Here is the case, I am currently using event "selection-change", when range is null I assume that editor is focused out and for normal use-case this works fine.

However, when I paste something in editor and then focus out, range is not null in selection-change function.

So here are two options:
a) create on paste event - so I can use flag for selection-change
b) do something so that on paste "selection-change" returns range null

Thanks,
Filip

**Comment by jhchen** [comment]
> then focus out

What do you mean by this? Clicking away? Also please fill out all the requested information in the [Contributing Guide](https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#bug-reports).
