### ISSUE TITLE
Right to left support

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#127]
This is a feature request to add right-to-left and left-to-right buttons.

Right-to-left languages like Hebrew and Arabic need buttons to change direction to rtl.
The button should set the text direction similar to how alignment work.
```html
<p id="line-1" class="line" style="direction: rtl;">
```
tinymce has left-to-right and right-to-left buttons:
http://www.tinymce.com/tryit/classic.php

Please see the gmail toolbar for icon example:
![rtl](https://cloud.githubusercontent.com/assets/75841/3102102/9ce8070c-e641-11e3-891d-44613f7693b3.png)

Thanks

**Comment by jhchen** [comment]
This has been added in the [beta](http://beta.quilljs.com/) release
