### ISSUE TITLE
Placeholder still displayed after setContents in 'silent' mode

### ISSUE THREAD

**Issue by ThibaultFriedrich** [quilljs/quill#1270]
I want to load a file stored on a server as a delta. So the delta is sent through websockets to the browser then load in a initialized editor with method `setContents`. However, since 'user' mode and 'api' mode trigger new delta sent to the server, I use `setContents` with 'silent' in order to update the editor without triggering new delta.

However in this situation, the placeholder keeps beeing displayed. Is it the good behavior ?

I found that this bug happens as soon as I use setContents in 'silent' mode.

Visit http://codepen.io/anon/pen/jyMXqB to reproduce the bug.

**Comment by jhchen** [comment]
This bug has been fixed in the latest version of Quill, not sure since when.

**Comment by ThibaultFriedrich** [comment]
Ok thanks. I could be useful to update cnd links in documentation. I thought that 1.0.0 was the last version available in cdn.
