### ISSUE TITLE
API formatText: Left alignment doesn't work when run after a different alignment.

### ISSUE THREAD

**Issue by lance13c** [quilljs/quill#1275]
After an alignment (center, right) is set using the method formatText(). Trying to assign the alignment to 'left' doesn't work.

**Steps for Reproduction**

1. Visit: https://jsfiddle.net/lance13c/c9c40rst/2/

**Expected behavior**:
The method call formatText (0, 4, 'align', 'left') will align that specific section to the left.

**Actual behavior**:
The method call formatText (0, 4, 'align', 'left')  does not align the text value to the left.

**Platforms**:
Windows 7 64bit, Chrome 55.0.2883.87

**Version**:
1.1.10

**Comment by jhchen** [comment]
From the docs for http://quilljs.com/docs/api/#formattext "To remove formatting, pass `false` for the value argument"
