### ISSUE TITLE
Add a simple HTML editor and toggle system

### ISSUE THREAD

**Issue by benwasser** [quilljs/quill#128]
See button on far left of control bar on Redactor: http://imperavi.com/redactor/

**Comment by andrewsauder** [comment]
Upvote. @benwasser  - I'm curious how you managed to add a toggle ontop? Until there's an official method to toggle between a raw HTML view and the WYSIWYG mode, I need to hack something to together also.

**Comment by kapouer** [comment]
Hi,
it is actually useful in a very specific case: for a developer to see if Quill creates html marmelade or not.
Such a button would be useful in the demo.

**Comment by jocoolie** [comment]
It's pretty easy to see the up-to-date HTML output.

I use code like:

var editor = new Quill('#editor', { ... });

        editor.on('text-change', function() {
var html = editor.getHTML();
HTML_Container.value = html; // make this a <textarea>
});

Just stack the two areas and toggle opacity with a button.

**Comment by garygreen** [comment]
+1 any news on this @jhchen ? It would be nice as an option to enable / disable in the toolbar. Often you have 'advanced users' in your system who feel confident dealing with raw HTML. As mentioned it will be nice to see the generated HTML by quill at a glance. All wysiwyg I've used before have this, it's the only feature Quill is missing....

**Comment by jhchen** [comment]
If you want to simply output Quill’s contents in HTML this is already possible with DOM’s innerHTML, as others have already mentioned.

If you want to edit the HTML directly, then you may make some change that Quill does not allow. Editors deal with this by cleaning this up, which Quill 0.20 also does, but this communicates nothing about why your edit was not accepted or cleaned. Sometimes the reason is obvious and even welcome like merging adjacent identical tags, but sometimes the reason is very elusive, particularly because often the reason you are extorting to editing HTML is precisely because you are trying to make a modification not supported or understood by the editor. If this is acceptable user experience then you can certainly implement a custom module but Quill is not in that camp and will not condone this use case with an official module.

Some editors do not attempt to understand its contents and let the browser take care of everything through contenteditable, so they can accept any HTML edit, but then they suffer from all the issues from letting browsers take care of everything like non-determinism, inconsistent behavior across browsers, and cannot offer an API beyond what the DOM already offers. Most new editor do not take this approach and Quill does not either but if this is not the tradeoff choice you would have made then Quill is probably not the best solution for your needs.

**Comment by aguynamedben** [comment]
@jhchen I wish you would reconsider your stance on this. I'm in the same boat as @garygreen, where I have advanced internal admin users that are confident and allowed to edit our HTML directly. Those advanced users sometimes need to paste embed links like the [ones from Wistia](https://wistia.com/doc/embedding). I agree it's an "edit at your own risk, for advanced users only", but it's still a real use case that you shouldn't just ignore or write off as invalid.

**Comment by aguynamedben** [comment]
You mention that Quill already cleans up HTML that it doesn't allow. A practical solution could be to show an alert when HTML is cleaned up so advanced users are aware they added code that wasn't allowed. I.e. "Some of the HTML you entered in Advanced Mode wasn't allowed, so had to be removed. Please double-check the results of your edits."

**Comment by AidasK** [comment]
This feature is a must! 👍

**Comment by maximelafarie** [comment]
Always nothing about that awesome new feature ? It has to be implemented !

**Comment by erw13n** [comment]
Here's what I did to make it happen
https://codepen.io/anon/pen/ZyEjrQ

**Comment by LESARQ** [comment]
I'm using react-quill and quill, how may I create something like this?
I wasn't able to transpile the code given by @erw13n to the react environment and ended hacking all the script until the buttons stopped working.

Shouldn't this be one of core features? Or is it too hard too implement (time wise)?
Almost all the customers I've know html and they use it very often using editors like this.

One simple example is when they edit an email template using html or when they just copy templates from the web into the editor.

I've tried tiny-mce, and they have this feature, but it's a cluster of problems integrating with react/webpack...

This lib seems pretty and simple (just what I want), however it misses this key feature (at least for me).

**Comment by mbenjamin618** [comment]
@LESARQ [check this out](https://github.com/zenoamaro/react-quill/issues/219)

**Comment by LESARQ** [comment]
Hey @mbenjamin618 thank you, but I think I've seen all the resources available online 😄 
I've done something similar and created a button on the toolbar, then on click I show my textarea and the user may change it.

Following @erw13n  [script](https://codepen.io/anon/pen/ZyEjrQ), if you paste:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title#### - Invoice Submitted #21E1B3FA7D</title>

    <style>
        p {
            font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
        }
    </style>

</head>

	<body bgcolor="#FFFFFF">
		<table>
			<tr>
				<td><p>example</p></td>
			</tr>
		</table>
	</body>
</html>
```

And then if you change it back to the editor and again to the source, you will see that all the code was erased.

Perhaps I'm confused and RichText Editor != Html Editor.

**Comment by erw13n** [comment]
@LESARQ please read @jhchen comment above 

> If you want to edit the HTML directly, then you may make some change that Quill does not allow. Editors deal with this by cleaning this up, which Quill 0.20 also does

Any element tags which Quill does not allow will automatically clean up, so if you paste such as Div or Table, Quill will replace it with Paragraph.

**Comment by LESARQ** [comment]
Ok, I see. What a shame 😞

**Comment by Miindaugas** [comment]
FeelsBadMan..

**Comment by imnithin** [comment]
https://quilljs.com/standalone/full/

**Comment by yangwen2** [comment]
Ok so it looks like quill is not designed to be used as an web editor for HTML layouts.  We need a richtext editor to create and edit E-mail templates.  It doesn't look quill allows for div elements..  Delete.

**Comment by qq403925754** [comment]
453453

**Comment by odahcam** [comment]
Ignoring community voice with success, congrats! That's the way to become the next CKEditor 4.

**Comment by odahcam** [comment]
Community voice ignored with success! 🎉

**Comment by Eddcapone** [comment]
Any progress on this?

**Comment by 5slight** [comment]
Would it be possible to have a setting to disable automatic code cleaning so we can handle this outside of quill.

It would be quite easy to have a toggle above the editor like in wordpress where you can go between RichText and PlainText as long as quill doesn't just remove anything done in PlainText. 

Some kind of html pretty printer would be needed to solve @Eddcapone issue of everything on one line but again thats something that can be handled outside of quill. It can always be concatenated back if the pretty printed code messes with quill.

**Comment by hberton** [comment]
@Eddcapone I have the same problem

any other solution?

**Comment by mintymatt** [comment]
+1

**Comment by nzolore** [comment]
While the interface is perfect for editing simple text, a way to preserve custom code would allow a lot more applications.

Here's another "source-button" attempt with external prettifier: https://jsfiddle.net/nzolore/1jxy58vn/

**Comment by RevealedFrom** [comment]
If source code editor is available, it will take pressure off the urgency of delivering other features such as tables. Most people who can use raw Html knows all about the `<table>` tag.

Just have a clean up to remove incompatible or dangerous tags such as `<script>`.

**Comment by Denny966** [comment]
+1

**Comment by jbaydar** [comment]
+1

**Comment by RevealedFrom** [comment]
I want to add `marquee` or css animations.  It would be too much to ask for these in Quill JS.  But if there is  source Html edit, they're all there.

**Comment by mintyPT** [comment]
+1

**Comment by aaclayton** [comment]
Just want to say I had put about an hour into building quill into my new platform and was loving the developer friendliness so far until I discovered there is no support for raw HTML editing. Complete deal-breaker, had to go in a different direction.

**Comment by RevealedFrom** [comment]
I am now looking at [summernote](https://summernote.org/).

**Comment by egorsergeevichw** [comment]
Module for use with ngx-quill.

**html-editor.ts:**

`export class HtmlEditor {
    quill: any;
    options: any;
    textarea: any;

    constructor(quill: any, options = {}) {
        this.quill = quill;
        this.options = options;

        this.addTextarea();
        this.bindEditorBehavior();
        this.bindButtonBehavior();
    }

    addTextarea() {
        let container = this.quill.addContainer('ql-custom');

        this.textarea = document.createElement('textarea');
        this.textarea.className = "ql-edit-html-textarea";
        this.textarea.style.display = "none";

        container.appendChild(this.textarea);
    }

    bindEditorBehavior() {
        let editor = document.querySelector('.ql-editor');

        this.quill.on('text-change', () => {
            if (editor) {
                let html = editor.innerHTML;

                this.textarea.value = html;
            }
        });
    }

    bindButtonBehavior() {
        let button = document.querySelector('.ql-edit-html');

        if (button) {
            button.addEventListener('click', () => {
                if (this.textarea.style.display === '') {
                    let html = this.textarea.value;

                    this.quill.pasteHTML(html);
                }

                this.textarea.style.display =
                    this.textarea.style.display === 'none'
                        ? ''
                        : 'none';
            });
        }
    }
}`

**quill-config.ts:**

`import Quill from 'quill';
import { HtmlEditor } from './html-editor'

Quill.register('modules/htmlEditor', HtmlEditor);

export class QuillConfig {
    constructor() {
        this.modules = {
            htmlEditor: true
        }
    }

    public modules = {};
}`

**Comment by izzygld** [comment]
Here is a component i made for Quill showing a "Source" show Html option to the Wysiwyg. 
See - https://gist.github.com/izzygld/0762dce7292baf2168f9c7b2aa99b535

**Comment by Vishnupriya112** [comment]
@erw13n But its removing div , If am adding code like

`<div>Hello</div>`

Its showing `<p>Hello</p>`

Is any other way to do

**Comment by dokicro** [comment]
@Vishnupriya112 I have the same problem, it removes even`<br>`

**Comment by sarang-naico** [comment]
Hi, 
are there any plans to implement this feature?

**Comment by mayesgr** [comment]
Glad I found this issue before I decided on a text editor.  Scratch this one off my list!

**Comment by marcelo-amorim** [comment]
Such a great project but it makes no sense have to import Quill just to show what you've build with the editor with preserved styles (to render Delta operations).

I think some warning should be added to git's page saying Quill is not an HTML Editor and some about its dependency on Delta to render what you've stored

**Comment by rkarroll** [comment]
Agree with @marcelo-amorim.  Just integrated Quill, it's working great and now the customer wants to add more complex HTML tags beyond what is supported.  Now having to move to something else or hacking together my own thing.

**Comment by brankoiliccc** [comment]
This is a deal breaker. Our users need to create responsive content with custom elements. Why would u not allow code editor just to add bootstrap classes for example?

**Comment by aswzen** [comment]
Any update to this absolutely very very basic feature?
