### ISSUE TITLE
Spaces not preserved on cut/paste in Quill

### ISSUE THREAD

**Issue by mmmmmmaya** [quilljs/quill#1280]
If I type `testing  testing` with one "regular" space (char#32) and one non-breaking space (char#160) between the words, then when I cut/paste this message the regular is preserved but the nbsp is not preserved.

**Steps for Reproduction**
1. Visit http://codepen.io/ainjii/pen/egvJQG?editors=0010
2. Enter a message with both regular and non-breaking spaces in the middle into the message box.
3. Cut/paste the message from/to quill.
4. Compare text in console before/after replacement applied.
5. Note some spaces have been removed.

**Expected behavior**:
Both spaces are kept when I cut/paste this message.

**Actual behavior**:
Half the spaces are removed with each cut/paste cycle until only a single regular space remains. In the case where there is only one nbsp, it is not removed, though it is converted into a regular space.

**Platforms**:
Mac OS Sierra, Google Chrome Version 55.0.2883.95 (64-bit)

**Version**:
Quill version 1.1.9

**Comment by benbro** [comment]
Related https://github.com/quilljs/quill/issues/996

**Comment by ainjii** [comment]
@jhchen Did you get a chance to take a look at this/the PR?

**Comment by jhchen** [comment]
It's not clear changing the white-space property is safe from side effects. Also how exactly do you enter a non-breaking space from the keyboard?

**Comment by ainjii** [comment]
In most user cases, non-breaking spaces will be added when the user is copy/pasting from a source that uses non-breaking spaces in their HTML. If you are just trying to test using an Apple computer, you can also add a non-breaking space from the standard US keyboard by typing option+space.

**Comment by spectras** [comment]
And on my system, one enters a non-breaking space using `shift+space`.
