### ISSUE TITLE
How to set the inserted video width and height?

### ISSUE THREAD

**Issue by fhefh2015** [quilljs/quill#1283]

**Comment by weavermedia** [comment]
The inserted video is an `iframe` tag and is given the CSS class of `'ql-video'` so you can customize that class for your needs.

**Comment by lancetipton04** [comment]
I added a little repo to allow video resize. I just started messing Quill this week so there may be better ways to do it, like make it a module. But it works so that's nice.
https://github.com/lancetipton04/quill-video-resize

**Comment by listar** [comment]
https://github.com/sky40280/quill-video-resize

**Comment by abishekrsrikaanth** [comment]
@listar do you have the installation steps? Is this on NPM?

**Comment by pateldhruv1993** [comment]
@lancetipton I couldn't get your video-resize to work. It gives me an error saying "e is not a constructor" while running quill's theme class on your module. I've used the default settings for videoresize module
