### ISSUE TITLE
Can't use CSS :hover selector on editor

### ISSUE THREAD

**Issue by JLShrago** [quilljs/quill#1286]
I want to apply my own styling to the editor on focus in my own CSS but the pseudo class selector doesn't work.
:active and :hover both work.

**Steps for Reproduction**

Add pseudo selector to loaded CSS with some styling.

**Expected behavior**:

Should add styling when the editor is focused.

**Actual behavior**:

There is no change in the styling.

**Platforms**:

Latest Chrome and FF

**Version**:

1.2.0

**Comment by benbro** [comment]
Working for me.
In [this CodePen](http://codepen.io/anon/pen/GrmGjV) :hover paint the background in red.

**Comment by benbro** [comment]
[This CodePen](http://codepen.io/anon/pen/Kameaa) use the :focus selector.
