### ISSUE TITLE
Insert Audio & Video like inserting Image

### ISSUE THREAD

**Issue by mustafaekim** [quilljs/quill#1288]
I would like to know whether you are planning to add a feature that will allow users to insert a video/audio file? I like the feature that quill saves the image as code. I would be very - very glad to be able to do the save for audio & video. (I actually need audio)

**Comment by superevanzhu** [comment]
I agree with it.

**Comment by jhchen** [comment]
You can already support video as of 1.0. The main editor on Quill's homepage demonstrates this. There are no plans on adding audio as supporting every format and embed type is not a goal. Instead Quill has an API to allow custom definitions. Take a look at http://quilljs.com/guides/cloning-medium-with-parchment/.
