### ISSUE TITLE
Links with user:pass fail on IE11

### ISSUE THREAD

**Issue by zarr** [quilljs/quill#1291]
Entering a link with user:pass part on IE11 causes a security exception. The issue is more problematic when loading Quill as editor to existing data with such links -- the exception leaks out breaking the parsing of the data.

Catching the exception at https://github.com/quilljs/quill/blob/master/formats/link.js#L35 would probably suffice.

**Steps for Reproduction**

1. Visit http://codepen.io/anon/pen/bgRPpg with IE11 (or add 'link' to the official playground at http://codepen.io/quill/pen/KzZqZx )
2. Add a link to http://user:password@whatever

**Expected behavior**:
No exception should escape and parsing should continue.

It's ok if the link doesn't actually work as it's against IE's security model, see https://support.microsoft.com/en-us/help/834489/internet-explorer-does-not-support-user-names-and-passwords-in-web-site-addresses-http-or-https-urls

**Actual behavior**:
A popup with "Error: A security problem occurred" appears. Link text disappears.

**Platforms**:

Internet Explorer 11.0.9600.18524

**Version**:

Quill 1.2.0

**Comment by jhchen** [comment]
I'm no longer able to reproduce this in IE 11.103.10586.0

**Comment by benbro** [comment]
IE 11 is not supported any more.
