### ISSUE TITLE
Some of the CodePen examples in the documentation use old versions of the library

### ISSUE THREAD

**Issue by MichaelTontchev** [quilljs/quill#1294]
I was playing around with some of the CodePens on the website and trying different features, and I was failing to use some of the features mentioned in the website in the examples, and it seems like this is because some of the CodePens use older versions of the library.

For example, at the bottom of http://quilljs.com/docs/delta/ it links to a codepen, but when I try to use the keyboard bindings found on http://quilljs.com/docs/modules/keyboard/ in that codepen, they fail. This appears to be caused by the fact that it's using an older version of the library, because if I use the codepen linked from https://quilljs.com/playground/ , the feature works.

**Comment by jhchen** [comment]
There are too many Codepen examples for Quill to update every one on every release so unfortunately the feature specific ones are only guaranteed to work for the specific feature.

We do manually all the general purpose ones on the playground page.
