### ISSUE TITLE
unremovables  inline blots ?

### ISSUE THREAD

**Issue by DaneelOliwan** [quilljs/quill#1295]
Hi,

First of all, I must congratulate you for quill. It is really wonderful. 

Then, is it possible to make some inline blot unremovables even if empty ?

Because I would like to do something similar to this :

```bash
First text                        second text                 third text
 ```

With some constraints:
* When I create this line, it automatically creates the 3 blots,
* I cannot delete one of them without the others
* The blots still remain even if their own content are empty

I tried with 3 inlines in a block : there is no problem with the 3 elements in the line but it is hard to maintain when user removes temporarily the content of an inline.

I tried with 3 blocks in a container but only one element is the default item so the 2 others elements may be deleted. Moreover, it is not on the same line.

Do you have some leads how to do it ?
Thank you from before

**Comment by jhchen** [comment]
What's the use case?

**Comment by DaneelOliwan** [comment]
I would like to get a blot with 3 fields because I am creating a blot to add task so there are 3 information to add: the task to do, the assignee and the deadline.

**Comment by DaneelOliwan** [comment]
I have seen the table PL but unfortunetaly, I cannot use embed because I would like to use formats in these fields.

**Comment by jhchen** [comment]
Makes sense thanks for the context. There's not a way to do what you are describing currently. I will leave this open as a feature request and for others to upvote.
