### ISSUE TITLE
Toolbar Disappearing

### ISSUE THREAD

**Issue by SOEL86** [quilljs/quill#1296]
Quill toolbar disappears when typing at the bottom of a long document when height is 100% of viewport.

**Steps for Reproduction**

1. Visit http://codepen.io/MichaelMC/pen/NdjMyZ
2. Press return until scroll bar appears
3. Type some characters

**Expected behavior**: toolbar remains visible

**Actual behavior**: toolbar disappears, moving up by its exactly its height to have a top position of -42.

**Platforms**: Tested on Windows 10 chrome and android chrome.

**Version**: 1.2.0

**Comment by jhchen** [comment]
You are not correctly setting the height of the editor in a full page scenario with the Snow toolbar. This can be observed after step 2 with the Chrome inspector. You can use flexbox, but it is not being used correctly either in the linked codepen. You can also use other methods like `calc`, but there are many many ways to do this all of it having to do with HTML/CSS and not Quill.
