### ISSUE TITLE
Directional keys don't always work in editor

### ISSUE THREAD

**Issue by rmadziya** [quilljs/quill#1297]
[Describe the issue]

**Steps for Reproduction**

Any Quill editor v. 1.1.3. Type something in the editor and try using directional keys (laptop or desktop) to move to the beginning or end of the text. It's not working all the time. Works fine on MOST machines in our office but not all. They're all Windows 9 machines, laptops and desktops, Firefox browser. Quill version 1.1.3

**Expected behavior**:
Move the cursor along the text to get the cursor where you want it.
**Actual behavior**:
Cursor stays in the same place....doesn't move at all.
**Platforms**:
Windows 7, firefox, Quill version 1.1.3
Include browser, operating system and respective versions

**Version**:

Version 1.1.3

**Comment by jhchen** [comment]
For the machines that experience this issue do they consistently experience it? Also for most of the machines where they work fine on, is it just that you've never observed this issue on these machines or have you tried enough or for some other reason think these machines are for some reason immune to the issue?

**Comment by rmadziya** [comment]
The machines that experience the issue get this problem consistently. The directional keys just don't work at all for those. On the ones with no issue it works consistently fine all the time. We haven't updated to 1.2.0 yet

**Comment by jhchen** [comment]
Do you have steps for us so to reproduce consistently? We can't fix bugs we cannot observe.

**Comment by rmadziya** [comment]
Sorry for delayed response, update to Version 1.2.0 seems to have solved the problem for us. It's working fine now across all the machines. Still testing but seems consistent and stable. Thanks, great work.

**Comment by jhchen** [comment]
Great to hear!
