### ISSUE TITLE
[UX] Hyperlink button does nothing if no text highlighted

### ISSUE THREAD

**Issue by benwasser** [quilljs/quill#130]
This could be solved with a separate modal for clicking the hyperlink button without text selected in which there would be an input box for the display text as well as the URL.

**Comment by beno-dlabs** [comment]
Is this enhancement still considered? 
Working on a project that would really need the ability to insert links in this manner. Any way to extend the current functionality to allow this?

**Comment by jhchen** [comment]
Customizability is core to Quill and the default link tooltip is simply a module which does not have to be included. You can create your own (from scratch or inheriting the existing tooltip with this modification). The [custom module guide](http://quilljs.com/blog/building-a-custom-module/) or the [link](https://github.com/quilljs/quill/blob/0.20.1/src/modules/link-tooltip.coffee) and [image](https://github.com/quilljs/quill/blob/0.20.1/src/modules/image-tooltip.coffee) tooltips may also be helpful as an example to extend.

**Comment by jhchen** [comment]
In Quill 1.0, the toolbar has configurable [handlers](http://quilljs.com/docs/modules/toolbar/#handlers). Right now when the link button is clicked, it only opens the tooltip when with text highlighted. But you can add your own toolbar [handler](http://quilljs.com/docs/modules/toolbar/#handlers) to do something else when the link button is clicked.

As far as extending the core Quill UI, I'm happy to take a look at a PR if someone wants to add a mode where the user can enter both text and url for the link.
