### ISSUE TITLE
Hidden blot / Comment blot which doesn't render in dom

### ISSUE THREAD

**Issue by cray0000** [quilljs/quill#1300]
Hi, 
thanks for the Quill.js, it's awesome!

Is it possible to make an inline blot which is not going to render anything but still going to be present in the delta? It doesn't matter whether it's going to be deletable or not.

The usecase I have is that I'm working on a Word-like tracking changes module for Quill, which is basically the authorship module which also shows deletions. 

I was able to implement a working solution by undoing any `delete` ops which are happening and applying `retain` operations instead which just add a `deleted` inline format. And I hide the dom elements of this format using `display: none`. 

And everything works great in most situations except of the browser spellchecking. Since the dom elements are actually in the dom tree it tricks the browser into thinking that they are part of the text which is visible.

So the solution to that problem would be to somehow not render the `deleted` blots at all. Or if that is not possible maybe there is a way to use html comments `<!- ->` instead of the regular dom elements for blots. If changes to Parchment are required to achieve it, I'll be happy to hack on it and make a pull-request, I just need some directions on whether it's possible and how to approach it.

I'm also going to move it out into a separate public repo. I saw some old issue in quill asking to develop that kind of functionality (https://github.com/quilljs/quill/issues/196), so I think it should be useful to some folks out there.

**Comment by jhchen** [comment]
There needs to be a 1:1 consistent predictable mapping between a Delta and DOM tree so the answer to the question specifically is no. You can however use CSS to hide elements in the DOM. Would that work?

I'm not sure I follow your workaround but modifying Deltas by hand is very error prone.

**Comment by cray0000** [comment]
Well, initially I implemented it by hiding elements through css. But it leads to the browser spellchecking functionality to work incorrectly in pretty much all the browsers (because the browser still treats the hidden elements as a part of the word).

So I ended up implementing a completely different solution. I'm using ShareDB for the OT. What I do now is I store the full document (with tracking changes -- text marked with attributes 'delete' and 'insert') in ShareDB. And I wrote a plugin which transforms update deltas flowing from ShareDB to Quill and from Quill to ShareDB -- to ignore the characters in the full document which are marked as 'delete'.

So the Quill renders delta without any 'delete' ops. But any operations you do in Quill, flow into ShareDB with the 'delete' ops in mind (I just add the additional "whitespace" ops in places where the 'delete's are located in the full document).

Actually while I have your attention, @jhchen, I want to thank for the great library and the OT design of delta -- it's awesome to work with. 

It would also be really awesome to hear your opinion on one API proposal I had on my mind for a long time. I think there is need for some kind of a `store` abstraction in the Quill API.

When dealing with the OT usecases the transformations for the delta flow between Quill and OT-db are pretty common. I would suggest introducing some kind of a "middleware chain" of delta transformations tied to the `store` abstraction. 

For example I have 3 `middleware`s like that in my project -- *track changes*, *search*, *selection*.
I briefly described the *track changes* transformation above. *Search* transformation removes the `search` attribute (it's used for doing the global text search on the webpage) from getting to ShareDB. And *selection* transformation removes `selection` attribute (used for showing what other users are selecting in real-time, part of the sharedb-tied multicursor module).

I think if we have this kind of a `store`/`middleware` abstraction in the API it would be much easier to release the standalone OT-oriented Quill plugins. Right now they end up being tied too much to the implementation details of a particular end-project.

**Comment by jhchen** [comment]
Are you thinking this would be on the top level Quill layer or a lower layer? How would it affect existing APIs?

**Comment by sri8484** [comment]
> Hi, thanks for the Quill.js, it's awesome!
> 
> Is it possible to make an inline blot which is not going to render anything but still going to be present in the delta? It doesn't matter whether it's going to be deletable or not.
> 
> The usecase I have is that I'm working on a Word-like tracking changes module for Quill, which is basically the authorship module which also shows deletions.
> 
> I was able to implement a working solution by undoing any `delete` ops which are happening and applying `retain` operations instead which just add a `deleted` inline format. And I hide the dom elements of this format using `display: none`.
> 
> And everything works great in most situations except of the browser spellchecking. Since the dom elements are actually in the dom tree it tricks the browser into thinking that they are part of the text which is visible.
> 
> So the solution to that problem would be to somehow not render the `deleted` blots at all. Or if that is not possible maybe there is a way to use html comments `<!- ->` instead of the regular dom elements for blots. If changes to Parchment are required to achieve it, I'll be happy to hack on it and make a pull-request, I just need some directions on whether it's possible and how to approach it.
> 
> I'm also going to move it out into a separate public repo. I saw some old issue in quill asking to develop that kind of functionality (#196), so I think it should be useful to some folks out there.

Hi [cray0000](https://github.com/cray0000),
Did you get any solution to this problem? I am curious to know about it..
As I am also having similar requirement to append some custom tag to quill and does not show up on UI.
