### ISSUE TITLE
Color pallette and input option

### ISSUE THREAD

**Issue by recepkutuk** [quilljs/quill#1302]
One useful and important feature Quill.js is missing is color options. I will be using Quill.js most of the time without knowing what my users need and sometimes they can be really picky about their brand guidelines. I was wondering if its possible to merge Quill.js and Spectrum (  https://bgrins.github.io/spectrum/ ) which is as awesome as Quill. It has all the possible options and more. It would be a great addition to Quill.

**Comment by jhchen** [comment]
You can add your own color picker and use the API to format text once selected. Integrating another library into Quill core does not seem appropriate.
