### ISSUE TITLE
Quill not returning html entities

### ISSUE THREAD

**Issue by alex2102** [quilljs/quill#1306]
When I use this:
about.value = JSON.stringify(quill.getContents());

It returns this:
{"ops":[{"insert":"Add the "},{"attributes":{"bold":true},"insert":"body"},{"insert":" of the answer...\n\n"}]}

Instead I need it to return html entities!!

**Comment by benbro** [comment]
Answered [here](https://github.com/quilljs/quill/issues/903#issuecomment-243844178).
Please read the docs and search before asking.
