### ISSUE TITLE
Bug: Js error when deleting list items with ctrl+backspace

### ISSUE THREAD

**Issue by MichaelTontchev** [quilljs/quill#1307]
**Steps for Reproduction**

1. Visit quilljs.com
2. Delete existing text in the quill editor on the main page
3. Create a bullet list with a single list item (you don't even need text on that item)
4. Delete with ctrl+backspace (which deletes an entire word)

**Expected behavior**:
No error, everything is deleted

**Actual behavior**:
Text is deleted, but error is thrown

![image](https://cloud.githubusercontent.com/assets/12261336/22665241/e5991312-ec68-11e6-91d7-cd9154727c27.png)

**Platforms**:

Windows Server 2012 R2,
Chrome 56 (latest as of writing)

**Version**:
Whatever the latest version on the website is, but can also repro on my project with version 1.1.10

**Comment by MichaelTontchev** [comment]
The commit message for the fix specifies ctrl + backspace is a no-op in Word/Docs. I tried to reproduce this but found ctrl+backspace to behave as generally accepted, which is to delete the previous word, meaning it's not a no-op. Should this issue be reopened?

**Comment by jhchen** [comment]
It was a no-op for me in Word/Docs but maybe it is a Windows vs Mac thing

**Comment by jhchen** [comment]
Had to revert the fix--will look at a more ideal fix for Windows regardless.

**Comment by MichaelTontchev** [comment]
Thanks! :)
