### ISSUE TITLE
Weird cursor behavior for Math Formula when using backspace

### ISSUE THREAD

**Issue by whykushal93** [quilljs/quill#1308]
When backspace is pressed after a formula, the cursor goes to the end of the line. Pressing backspace again does the intended action, but still think this is a bug. See the GIF below.

![quillbug](https://cloud.githubusercontent.com/assets/2162858/22666567/e83b8078-ec6d-11e6-84a6-0e46cbc470c2.gif)

**Steps for Reproduction**

1. Visit quilljs.com
2. In the editor, click on a line with a math formula.
3. The cursor should appear after the formula with **some white-space** in between.
4. Press backspace once. 

**Expected behavior**:
The cursor removes the white-space or deletes the formula

**Actual behavior**:
The cursor moves to the end of the line. 

**Platforms**:
Windows, Chrome
**Quill Version**: 1.1.10

**Comment by c-w** [comment]
Sounds like the same issue as #1181.

**Comment by jhchen** [comment]
Yes this is the same issue.
