### ISSUE TITLE
Handler to transform final Delta on paste

### ISSUE THREAD

**Issue by montlebalm** [quilljs/quill#1309]
It would be helpful if the Clipboard module had an option for a "final matcher" that could modify the paste Delta before it's applied to the Quill instance. There are instances where individual node matchers are insufficient and it's necessary to see the full picture.

Something that receives the delta produced by `traverse` would be ideal. For example:

https://github.com/quilljs/quill/blob/develop/modules/clipboard.js#L75
```
let delta = traverse(this.container, elementMatchers, textMatchers);
// ...
delta = this.handlerThatHasTheFinalSay(delta);
```

I can submit a PR if it's agreed this is a worthwhile addition.

**Comment by jhchen** [comment]
What's an example use case?

**Comment by montlebalm** [comment]
I'd like to convert formatted text to Markdown on paste. I'd like to copy **bold** text and paste it as `**bold**`. Here's an example:

1. Browse to https://codepen.io/montlebalm/pen/bgQWoz and open the browser console
2. Copy `addMatcher(String: selector, (Node: node, Delta: delta) => Delta)` from https://quilljs.com/docs/modules/clipboard/#addmatcher and paste into Quill
3. Verify Quill generates 25 distinct "top-level" deltas and none of them include code formatting.

I understand Quill is separating the deltas by attributes. In this case, I'm going to see that the associated node has a `fontFamily` that includes "monospace", remove the current attributes, and add `code: true`. The deltas can be combined now that the attributes are the same, but my matcher can only see one at a time. The Markdown translation would wind up wrapping each delta with backticks. 

You can achieve my proposal manually by adding:

```javascript
let pasteDelta = null;
quill.clipboard.addMatcher('*', (node, delta) => {
  if (node.parentElement.classList.contains('ql-clipboard')) {
    if (!pasteDelta) pasteDelta = new Delta();
    pasteDelta = pasteDelta.concat(delta);

    if (!node.nextSibling) {
      /* 
       * All the deltas have been accounted for and be processed
       * - combine deltas
       * - process as one
       */
    }
  }

  return delta;
});
```

Quill could expose an option like this that would make it easier to do complex transforms of pasted text.

**Comment by jhchen** [comment]
I think this use case is better solved with an extended Clipboard. The [Extending Modules](http://quilljs.com/docs/modules/) has an example of this but in your case you would overwrite `convert()` and probably call `super.convert()` before returning.
