### ISSUE TITLE
Todo List Items Can Be Checked/Unchecked with Quill Disabled

### ISSUE THREAD

**Issue by danielschwartz** [quilljs/quill#1312]
If Quill is in readOnly mode (either by supplying `readOnly: true1) in the constructor, or by doing `quill.disable()` todo list items can still be checked/unchecked

**Steps for Reproduction**
1. Create a readOnly Quill instance with todo list items 

**Expected behavior**:
With the editor in the disabled state you should not be able to modify it's contents. 

**Actual behavior**:
With the editor disabled, the todo list item click handler doesn't check if quill is disabled, so it's possible to check/uncheck items

**Version**:
v.1.2.0

**Solution**
It doesn't seem like the quill instance is available at the blot level, but it would be fairly trivial to check if it was disabled in the click handler if it was.

**Comment by sferoze** [comment]
@danielschwartz 

ive been looking through the docs and cannot find any support for Todo List Checkbox items. I search other issues and I see it's currently a work in progress. 

Are you using a specific plugin? If you are and it is something I can take a look at, please let me know. I am looking to integrate this feature. 

As this comment may be off topic for this thread I will eventually delete it.

**Comment by jhchen** [comment]
@sferoze The current status is on this issue #759

**Comment by akhilaudable** [comment]
Any progress in this?
