### ISSUE TITLE
nested lists are not WYSIWYG

### ISSUE THREAD

**Issue by luisrudge** [quilljs/quill#1314]
WYSIWYG stands for *what you see is what you get*.
When you create nested lists, instead of actually creating html nested lists, quill creates juts regular lists and adds a `ql-indent-*` class to the items.

expected:
```html
<ul>
  <li>test</li>
  <li>
    <ul>
      <li>second level list</li>
    </ul>
  </li>
</ul>
```

actual:
```html
<ul>
  <li>test</li>
  <li class"ql-indent-1">second level list</li>
</ul>
```

**Comment by JoshuaDoshua** [comment]
#979

**Comment by jhchen** [comment]
Issues is not the place for philosophical debates of existentialism or purpose. Please include practical reasons, or indulge elsewhere.

**Comment by luisrudge** [comment]
@jhchen I'm truly sorry with the approach I used. I could make up some crazy story about it, but the truth is that I was an idiot. Again, sorry! I'll follow up in #979

**Comment by jhchen** [comment]
All good thank you.

**Comment by tuancaraballo** [comment]
My issue was the following:
  I was saving the html returned by the onChange handler and displaying it into a different component. Everything was displaying fine except for nested list. What I ended up doing was importing quill's css into my other component or at the root and that solved my issue. 

`
   import 'react-quill/dist/quill.core.css'
   import 'react-quill/dist/quill.bubble.css'
   import 'react-quill/dist/quill.snow.css'

`

**Comment by rbonomo** [comment]
@jhchen 

Using css to indent conveys the nesting of the list item to people using eyes to read the content.

Using css to indent does not convey the nesting of the list item to people using accessibility devices such as screen readers.

Using css to indent does not convey the indenting of the list item when the HTML markup from the editor is taken out of the QuillJS CSS context (rendered elsewhere).

**Comment by Micheal-Prisila-Fernando** [comment]
1. d
d

- [ ] 

1. 

-

**Comment by twickstrom** [comment]
> 1. d
>    d
> 
> * [ ]

I am running across exactly this issue

**Comment by ajj-siraj** [comment]
> @jhchen
> 
> Using css to indent conveys the nesting of the list item to people using eyes to read the content.
> 
> Using css to indent does not convey the nesting of the list item to people using accessibility devices such as screen readers.
> 
> Using css to indent does not convey the indenting of the list item when the HTML markup from the editor is taken out of the QuillJS CSS context (rendered elsewhere).

I was about to say the same thing. I'm using quill as the editor in the CMS but now it seems I need to add the quill stylesheets to get the actual WYSIWYG content I added on the website that is fetching data from the CMS. Not to mention like you said it's not conveyable to screen readers.

Is there a reason quill doesn't simply use HTML markup for nested lists? If there's a reason then it's alright I suppose, but I don't agree that it's not an issue.

**Comment by JoshuaAYoung** [comment]
@jhchen I love Quill and am appreciative of the time and effort that must go into something like this, so take my comment with a grain of salt. Just wanted to +1 to @rbonomo 's comment about accessibility. Flat lists styled with a margin to make them appear nested work for sighted users. For non-sighted users, all of the semantics you're trying to impart by nesting list items disappears. So all other things being equal, seems like actually nesting the html elements would be the way to go. But that's probably a large change with a lot of work for a feature that many people may never use... so yeah. Grain of salt.

**Comment by Haegin** [comment]
We've just run into this issue when trying to use the rich text data in an email. Unfortunately while emails support nested lists just fine, they don't support the CSS counters Quill uses to control the numbering so with the Quill CSS added to the email all the numbers and bullets are lost.

**Comment by rbonomo** [comment]
> We've just run into this issue when trying to use the rich text data in an email. Unfortunately while emails support nested lists just fine, they don't support the CSS counters Quill uses to control the numbering so with the Quill CSS added to the email all the numbers and bullets are lost.

As a workaround, I disabled TAB within Quill so that nested lists are not possible to create within the editor.

**Comment by coolgoodfriend** [comment]
Also copy pasting from quill to anyother word processor / notes breaks the nested lists.

**Comment by ggaidelevicius** [comment]
6 years on and this is still an issue. This is not semantically correct usage of HTML, nor is it WYSIWYG.

**Comment by Sliffcak** [comment]
Any updates on this? Interested in this also.

**Comment by jeygeethan** [comment]
6.5 years...

**Comment by Sliffcak** [comment]
> 6.5 years...

@jeygeethan  I had to switch to TipTap. A LOT less pain.

**Comment by RichMatthews** [comment]
still waiting here...

**Comment by xChristine7714** [comment]
> Issues is not the place for philosophical debates of existentialism or purpose. Please include practical reasons, or indulge elsewhere. And remove the attitude or assumption that just because an implementation surprised you, it must be wrong or lazy.

You are everything that's wrong with the world of software engineering. What a garbage attitude.

**Comment by xChristine7714** [comment]
Yeah, my issue is with utilizing the markup in emails. It just displays as one long bullet list. But, @jhchen doesn't see why this approach might be an issue, so I guess that means it isn't an issue... and anyone who brings it up or suggests that it _is_ an issue should be ridiculed.

**Comment by milelo** [comment]
I've just replaced my google editor with Quill. It was looking great however I've just come across this issue in testing, unfortunately, not being able to have true nested lists is a deal breaker for me. Its back to google or find a better alternative.

**Comment by milelo** [comment]
> @milelo Can you give me a link to the google editor? I am looking for a quill replacement. TIA

Its in the google closure library goog.editor. It still works fine but unfortunately its being phased out:

[Closure Library is in Maintenance Mode · Issue #1214 · google/closure-library (github.com)](https://github.com/google/closure-library/issues/1214)

[The online demo no longer functions](https://google.github.io/closure-library/source/closure/goog/demos/editor/editor.html).

**Comment by jorgsiegel** [comment]
One of our clients just noticed this, because an email was sent with the wrong format.
Unfortunately this is a dealbreaker for us as we need a WYSIWYG editor.

**Comment by wunmiji** [comment]
Guys it is working.
Add <link href="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css" rel="stylesheet" /> to the page.
Add "ql-editor" class to your custom component.

Example : 
<div class="ql-editor">
                
</div>
