### ISSUE TITLE
[Toolbar] Link binding dialog does not display with floating parent.

### ISSUE THREAD

**Issue by mikegwhit** [quilljs/quill#1317]
If has parent tag that has float property, then link binding dialog does not dispaly.

**Steps for Reproduction**

1. `<div style="float: left;"><div class="editor"></div></div>`
2. new Quill('.editor', {modules: {toolbar: [['link']]}});
3. Type some text, highlight, hit link button

**Expected behavior**:
Link dialog should appear.
**Actual behavior**:
Link dialog does not appear.

**Platforms**:

Seems to occur only when positions are horizontally stacked via a float.

**Version**:

1.2.0

**Comment by jhchen** [comment]
The float does mess up Quill's positioning calculations. The workaround is to specify the bounds config:

```js
var quill = new Quill('.editor', {
  modules: {
    toolbar: [['link']]
  },
  bounds: '.editor',
  theme: 'snow'
});
```
