### ISSUE TITLE
Editor jumps, when removing line-brake.

### ISSUE THREAD

**Issue by d-ark** [quilljs/quill#1321]
**Steps for Reproduction**

1. Visit https://jsfiddle.net/b19s72wv/
2. Scroll down
3. Remove the line-brake (for example before "But I must explain to.."). Please note that the start of previous paragraph should not be seen (should be scrolled)

**Expected behavior**:
The paragraphs should merge, the text before removal should not change and should not scroll.

**Actual behavior**:
Editor jumps. After removal the start of previous paragraph appears on the line where cursor was. The cursor is now moved to the bottom of screen

**Platforms**:

Chrome 56. Tested on Mac OS Siera, on Win 10.

**Version**:
1.2.0

**Notes**
This issue disappears, if we append absolute-positioned item before editor. If it is inserted after editor - issue is still reproducible:

With absolute elementw
https://jsfiddle.net/xm4fs14g/1/

With absolute element after editor
https://jsfiddle.net/wja508fo/1/

With wrapped absolute element
https://jsfiddle.net/dtzfxjty/1/

**Comment by jhchen** [comment]
This is not what's causing the issue but you do need to at least use the minimal quill.core.css stylesheet.

**Comment by jhchen** [comment]
If you want the editor to autogrow in height you have to add some CSS styles as demonstrated in this [example](https://quilljs.com/playground/#autogrow-height). Otherwise assigning a height fixes this issue.
