### ISSUE TITLE
Bubble theme toolbar placement bug? (Multiple editors)

### ISSUE THREAD

**Issue by jayarc** [quilljs/quill#1322]
I'm using Quill  #with these conditions:
 - 5 Quill's inside a one page ember app, they're all on the same page and they have separate toolbar configurations/objects. Each editor has an individual ID
 - I'm using the bubble theme
 - I'm using Quill 1.2.0
 - I'm using flexbox for grid layout around the editors but they're directly surrounded by floated div that escapes them from flexing.

Here are three of the editors I've defined and initialized on the page, they appear and work fine except for the bubble/popover toolbar placement which is seemingly sporadic-but-above-editor by 2-300px.
`
var letterHeaderToolbar = [
      ['bold', 'italic', 'underline'],
    ];

    var letterHeaderQuill = new Quill('#letter-header-quill', {
      theme: 'bubble',
      modules: {
        toolbar: letterHeaderToolbar
      }
    });

    letterHeaderQuill.setText('DEPARTMENT OF THIS, THAT AND OTHER THING\n278 Canvas Circle\nLongston, MI 73212-0126');
    letterHeaderQuill.formatLine(0, 30000, 'align', 'right');
    letterHeaderQuill.formatText(0,30000,'size', 'large');

    var letterAddressToolbar = [
      ['bold', 'italic', 'underline'],
    ];

    var letterAddressQuill = new Quill('#letter-address-quill', {
      theme: 'bubble',
      modules: {
        toolbar: letterAddressToolbar
      }
    });

    letterAddressQuill.setText('Thomas Jefferson\n123 Main St.\nFredricksburg, VA 32873-1826');
    letterAddressQuill.formatText(0,30000,'size', 'large');
    letterAddressQuill.formatText(0,30000,'bold', 'true');

    var letterBodyToolbar = [
      ['bold', 'italic', 'underline', 'strike'],
      [{ 'list': 'ordered'}, { 'list': 'bullet' }],
      [{ 'indent': '-1'}, { 'indent': '+1' }],
      [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
      [{ 'color': [] }, { 'background': [] }],
      [{ 'align': [] }],
      [{ 'size': [] }],
      ['clean'],
    ];

    var letterBodyQuill = new Quill('#letter-body-quill', {
      theme: 'bubble',
      modules: {
        toolbar: letterBodyToolbar
      }
    });

    letterBodyQuill.setText('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi in euismod nunc, non pretium turpis. Duis porta ullamcorper ligula, vitae condimentum sem eleifend nec. Vestibulum pharetra nec diam eget condimentum. Nullam ut gravida tortor, eu egestas metus. Morbi eget ipsum vestibulum, egestas ligula vitae, sollicitudin ipsum. Phasellus dapibus, ipsum et ultricies pellentesque, libero augue tincidunt odio, eget pellentesque diam orci et turpis. Mauris eros dui, laoreet sed tellus in, semper lobortis sapien. Praesent aliquet sem id leo dapibus tincidunt. Curabitur sagittis ligula a nibh viverra, nec tincidunt purus ultrices. In non molestie nunc, at suscipit erat. Aenean aliquet, dolor id semper porttitor, lectus diam dignissim libero, ac pellentesque metus purus vel velit. Pellentesque non ex pulvinar, commodo dui sit amet, scelerisque nisi. Integer rutrum fringilla mi, rhoncus fringilla arcu auctor in. Fusce semper nisi nulla, a rhoncus elit pharetra ac. Ut nec est molestie, ullamcorper nunc ac, dapibus elit.');
    letterBodyQuill.formatText(0,30000,'size', 'large');`

Here's a screenshot of the bubble toolbar much above the main letter body editor area I've selected some text (grey) in: http://imgur.com/a/OyTQl

Each time I re-select some new text in that editor the toolbar moves, it's always up high there but it does not seem like it's always the same amount off, odd. Sometimes it's higher on a lower piece of selected text, so it's not just 300px up and 35px right every single time.

Some things I've tried:
 - Setting a CSS height on the editor container divs
 - Made sure each editor has an individual toolbar js object for itself.
 - Disabling all flexbox based CSS around it, didn't help.

Things I think may help?
 - Only enabling one editor at a time, disabling the editor after click-out so the next can init on click etc..

I've seen examples of 1.2.0 with multiple editors working without my toolbar positioning bug like this codepen I have to test the case:

http://codepen.io/jayarc/pen/jyRzOp

That seems to work just fine... Any thoughts would help me much, thanks!

**Comment by jayarc** [comment]
The first editor initiated on the page seems to work ok, making me suspect multiple editors could be a contributing factor.

**Comment by jhchen** [comment]
Can you reduce your case issue to a reproducible codepen or jsfiddle?

**Comment by shofman10** [comment]
I'm having this same issue in my angular 2 project. I've have many quill editors on one page, but each is initialized with a unique ID and I can see that each editor has its own toolbar. 

Everything that is at the top of the page (viewable in the window without scrolling) works perfectly with the bubble toolbar aligning correctly. However as soon as I scroll down and select text in the next quill editor (that wasn't initially visible in the window), the toolbar isn't aligned correctly.

The 'left' position in the css is always correct for all of them, but the 'top' css position is stuck at a certain spot in the page no mater what editor I'm selecting text in. It stays a few pixels above the bottom of the initial view window.

Here's an example:
![quill-position1](https://cloud.githubusercontent.com/assets/19490191/24427905/992f4b92-13da-11e7-98c0-b9813381e730.jpg)

Top position doesn't change, but left does correctly:
![quill-position2](https://cloud.githubusercontent.com/assets/19490191/24427911/a12ed09c-13da-11e7-94dc-6411e141a219.jpg)

If I scroll even further down the page, it will stay at that same top position (left will change correctly based on what I select).
