### ISSUE TITLE
Empty paragraph before ol

### ISSUE THREAD

**Issue by ramk18** [quilljs/quill#1326]
# Empty paragraphs are added before ol

**Steps for Reproduction**

Check out this pen 
http://codepen.io/anon/pen/ggVwQj

**Expected behavior**:
No empty line after Hello in the pen

**Actual behavior**:
There is an empty line after Hello in the pen

**Comment by jhchen** [comment]
Quill's clipboard attempts to visually match the content pasted, not the markup. Since paragraphs have bottom margin generally and Quill's paragraphs do not, a newline is added to compensate.

**Comment by mikeesouth** [comment]
I know this issue is closed but is there any way to disable this "feature"?

**Comment by shayaulman** [comment]
> found this new feature that disables this behaviour: https://quilljs.com/docs/modules/clipboard/#matchvisual

`matchVisual` [was removed in v 2.0](https://github.com/quilljs/quill/blob/ee827ffb605ba491246f201d497ce0e7d9e193a0/docs/guides/upgrading-to-2-0.md#configuration).

Does anyone know about another solution?
