### ISSUE TITLE
Your website is down.

### ISSUE THREAD

**Issue by cviebrock** [quilljs/quill#1330]
**Steps for Reproduction**

1. Visit quilljs.com

**Expected behavior**:

See the website.

**Actual behavior**:

Receive an error from Cloudflare:

> ## CNAME Cross-User Banned
> ### What happened?
> You've requested a page on a website that is part of the Cloudflare network. The host is configured as a CNAME across accounts on Cloudflare, which is prohibited by security policy.

**Comment by caiotarifa** [comment]
Same here.

**Comment by jhchen** [comment]
Already contacted Cloudflare support and now on Twitter--no response yet. The difficulty in switching DNS providers is quilljs.com forces SSL and so you'd have to set up a proxy endpoint to terminate as well as get a cert. Hopefully they will respond soon.

**Comment by jhchen** [comment]
I have set up Route53 but it could take days for caches to expire.

**Comment by leocaseiro** [comment]
Thanks @jhchen.

Just for curiosity, why not use `gh-pages` for demo, docs and so on?

**Comment by jhchen** [comment]
Looks like this Cloudflare issue is resolved though some caches may not be expired. Not sure what you mean @leocaseiro ?

**Comment by leocaseiro** [comment]
Thanks @jhchen,

Yep! I meant a `gh-pages` branch for the demo, docs and so on.

**Comment by jhchen** [comment]
We prefer to put it in the docs/ folder so they are more easily synced with the rest of the codebase.
