### ISSUE TITLE
Character composition fails in empty editor with web clipper unless inside an iframe

### ISSUE THREAD

**Issue by ainjii** [quilljs/quill#1331]
In Chrome, using the Evernote [Web Clipper](https://chrome.google.com/webstore/detail/evernote-web-clipper/pioclpoplcdbaefihamjohnefbikjilc) extension, an empty Quill editor cannot complete character compositions unless Quill is inside an `<iframe>`. Note that this bug does not occur if there is _anything_ else inside the editor.

**Steps for Reproduction**
1. Install Evernote Web Clipper as a Chrome extension
2. Create an account to activate web clipper
3. Visit https://angieroscioli.com/quill to see my simple setup using a plain `contenteditable` vs Quill  vs Quill inside an `<iframe>`***
4. Make sure your editor is empty
5. Begin a simple character composition by pressing [alt + u] (should insert ¨).
6. Press [u] to complete the character composition (should replace umlaut with ü).

*** This bug does not occur in your Codepen playground. It seems anything inside an iframe is safe from the effect (you can also see Quill inside an iframe at https://www.angieroscioli.com/quill for comparison)

**Expected behavior**:
- Character composition completes as expected
- The second `compositionupdate` event occurs and the fully completed character is added to the editor. For example, ¨ gets replaced with ü.
- Cursor maintains position.

**Actual behavior**:
- Fully composed character is not reinserted in the editor. Instead, the editor is cleared.
- Cursor is removed, although the editor element stays in focus.

**A note about character composition**:
As far as I can tell, during the second half of a character composition event, the partially constructed character (for example, ¨) is removed in one `compositionupdate` event, and then the fully assembled character (ü) is inserted in it's place in another `compositionupdate` event. I believe the "clearing" of the editor I mentioned above is, in reality, a failure of this insertion after the partially assembled character is properly removed.

**Platforms**:
Mac 10.12.3, Chrome 56.0.2924.87, Evernote Web Clipper 6.11

**Version**:
Quill 1.2.0

**Comment by jhchen** [comment]
Composition is working on a [standalone](http://quilljs.com/standalone/snow/) Quill demo without an iframe. If the Evernote extension is doing something with the event it would make a lot of sense why it does not occur in an iframe as iframes do afford protection. It seems like an issue that should be filed with Evernote as Quill is just a standalone agnostic library that cannot favor a particular vendor.
