### ISSUE TITLE
[suggestion] In-line inputs

### ISSUE THREAD

**Issue by benwasser** [quilljs/quill#134]
This one is far out of left field but wanted to put it on your radar: There's currently a use-case I have for putting input boxes of some sort in the editor, so that users could "fill-in-the-blanks" while they edit instead of having to select strings like "________" and replace them manually (which is quite difficult to do on mobile).

**Comment by jhchen** [comment]
Quill 1.0 now lets you add custom formats and embeds so you can use this new version to add this input you are describing. [Cloning Medium with Parchment](http://quilljs.com/guides/cloning-medium-with-parchment/) might be a good guide to look at. Just as an honest assessment however, I do not see this being built into core Quill by the core team.
