### ISSUE TITLE
Use <br/> instead of <br> when break line

### ISSUE THREAD

**Issue by apiweb** [quilljs/quill#1343]
I think it would be interesting to use `<br/>` instead of `<br>` when break line.
Use XHTML notation, allows libraries that generate content coming from an html like Mustache, iText XMLWorker, etc ... understand the tag normally.
I am currently using iTextSharp XMLWorker to generate pdf, based on a template that the user creates using the Quill editor, however whenever the user breaks a line, XMLWorker can not understand that `<br>` is equal to `<br/>` and throw an exception.
I'm having to replace every `<br>` tag with `<br />` whenever the user saves the contents of the editor.
I think it would be a change that would not impact the operation of the editor, and would bring some benefits to anyone who uses it to generate content using some processor.

**Steps for Reproduction**

1. Visit the quilljs.com interactive playground
2. Write a line
3. Enter line break

**Expected behavior**:
Use `<br/>` for breakline

**Actual behavior**:
Using `<br>`

**Platforms**:
Chrome 56 on WIndows 10
Chrome 56 on OS X Yosemite 10.10
Microsoft Edge on Windows 10

**Version**:
1.2.0

**Comment by jhchen** [comment]
First this is a browser behavior: http://codepen.io/quill/pen/EWKzBG. Second, `/` is optional by HTML5, which Quill follows. It should be trivial to convert from one internet specification to another.
