### ISSUE TITLE
Custom blot does not store values properly into editor state

### ISSUE THREAD

**Issue by puopg** [quilljs/quill#1345]
When creating my own custom blot inheriting from Inline, I provide an object which is not saved in the editor's state. Instead, it simply saves a value of 'true'.

**Steps for Reproduction**

Create a custom blot and provide an object for it to use as its value. 
Here is an example:

    class MentionBlot extends Inline {
          static create(value) {
            let node = super.create();
            node.setAttribute('email', value.email);
            return node;
          }

          static value(node) {
            return { email: node.getAttribute('email') };
          }
        }

        MentionBlot.blotName  = 'mention';
        MentionBlot.tagName   = 'p';
        MentionBlot.className = 'mention';

        Quill.register(MentionBlot);

        _quill.insertText(0, 'This is a first Michael Chen I want you to have');
        _quill.formatText(16, 12, { mention: { email: 'useremail@email.com'} });

**Expected behavior**:

quill.getContents() shows the attributes stored as that object.

**Actual behavior**:

quill.getContents() shows the attribute simply stored as the value 'true'.

**Platforms**:

Chrome, OSX

**Version**:
1.2.2

**Comment by puopg** [comment]
In the HTML, I get an attribute named email which has the correct email, but if I remove that line and undo that action, the editor rebuilds the blot and since it never saved the data, it renders it in as undefined as the email attribute.

**Comment by puopg** [comment]
Going to answer my own question, need to use the formats method to do this. I added to the above:

          static formats(node) {
            return { email: node.getAttribute('data-email') };
          }

and now it properly stores that object into the editor state.

**Comment by anztrax** [comment]
thanks @puopg , save my day 👍

**Comment by bill13996** [comment]
@puopg you are genius!! How did you find out the way to solve this problem?

**Comment by anhnt-mageplaza** [comment]
I came here after this demo did not work out: https://codepen.io/emanuelbsilva/pen/Zpmmzv?editors=1111
For any one who encountered the same issue, here is the solution!

**Comment by 64jcl** [comment]
Used a whole day to finally get this to work. So you need both "static formats" and "static value" implemented (and basically identical code for each) if you want your custom blot to manage more than just the content of the tag. You have to create an object then to contain all values.
