### ISSUE TITLE
Theoretical saving question

### ISSUE THREAD

**Issue by WriterStat** [quilljs/quill#1346]
Hi!

Hoping to get some opinions from the experienced creators in the crowd.

Better to save a user document from Quilljs in a whole html on the database or as separate individual changes?

Currently a user creates a written document here in the editor. We save the entire doc locally every 1/3 of sec for them and then save a backup copy on the server on doc close or page close. Always running on the local copy.

But realized we can't reconstitute a document later as a document can be overwritten on the server from the local.

If deltas are saved, how much load is put on the server to both save and load/reconstitute deltas? And what happens when user usage of editor is high?

Are there code snippets available for reconstituting deltas into a document? Thanks!

I realize this is off-topic a bit. But wanted to draw on people's experiences. Wish you guys had a user forum. =)

And what sort of load is put on a server from saving deltas and reconstituting deltas for many users?

Thanks!

**Comment by benbro** [comment]
Quill was designed for Operational Transformation so it is optimized for such a use case. You don't need to save the whole doc each time.

The [text-change](http://quilljs.com/docs/api/#text-change) event gives you the change as a delta. You can find more info [here](http://quilljs.com/docs/delta/#changes).
You can [compose](https://github.com/quilljs/delta#compose) several deltas into a single delta either on the client or on the server.

You can save each change on the server, or collect several changes and save them, either in RAM or DB/disk.

You'll need to test the load on your own system.

**Comment by WriterStat** [comment]
I got this note from BenBro which helps a lot, thanks:

> Quill was designed for Operational Transformation so it is optimized for such a use case. You don't need to save the whole doc each time.

The text-change event gives you the change as a delta. You can find more info here.
You can compose several deltas into a single delta either on the client or on the server.

You can save each change on the server, or collect several changes and save them, either in RAM or DB/disk.

You'll need to test the load on your own system.
