### ISSUE TITLE
Adding tab handler does not propagate event to default handler even when return true

### ISSUE THREAD

**Issue by puopg** [quilljs/quill#1347]
Attaching a handler to tab before quill is instantiated as mentioned does not honor the return true statement to allow the event to continue firing the other handlers. 

**Steps for Reproduction**

http://codepen.io/puopg/pen/zZqzxX

**Expected behavior**:
Notice enter works, but when you hit tab, the default event is suppressed and the handler attached is fired.

**Actual behavior**:
No tab is entered into the editor

**Platforms**:

Chrome, OSX

**Version**:

1.2.2

**Comment by jhchen** [comment]
What is the expected behavior? That a tab *is* entered into the editor?

**Comment by puopg** [comment]
I would expect that the tab key works just like the enter key. So lets take the example of enter first in the codepen:

1. I hit enter
2. Quill runs my callback first, console logs 'enter'
3. Since I returned true, quill runs the next handler which is its default and adds a newline

Now lets see what happens with tab
1. I hit tab
2. Quill runs my callback
3. I return true thinking it will run its own handler to add the TAB character, but it doesn't.

**Comment by jhchen** [comment]
The difference is there is a default binding called `tab` and so yours completely overwrites it whereas there is no default binding called `enter`. If you name it something else, it will do what you are expecting. Details are in the comments in the example code in the [Configuration](http://quilljs.com/docs/modules/keyboard/#configuration) section.
