### ISSUE TITLE
How to get content by container's name using $_POST

### ISSUE THREAD

**Issue by Serpentsoft** [quilljs/quill#1349]
I thought that I can apply Rich Text on a textarea or even any input type to use $_POST and get data and save it but I discovered later that you use a div ( by the way no example for your HTML code and I waste a lot of time to understand that 'cause I supposed that you should apply on textarea ), anyway Is there any possible method to get DIV content using $_POST ??

Thanks

**Version**:
1.2.2 

Run `Quill.version` to find out

**Comment by benbro** [comment]
[Form submit](http://quilljs.com/playground/#form-submit) example.

Previous discussion https://github.com/quilljs/quill/issues/87

**Comment by Serpentsoft** [comment]
Very BAD, 

I have a huge controls array ' array[1][repeater][1][RichTextEditor] ' and user can add more editors .. How to save ?? I'm using $_POST to collect all page values .. How to break it and get value from js??

Anyway, Thanks for your work and hope to fix this.
