### ISSUE TITLE
Tags within the quill editor start refreshing and that prevents any selection in that tag. (Video) 

### ISSUE THREAD

**Issue by nikhil4092** [quilljs/quill#1351]
When I run the quill editor and copy paste content from Microsoft Word, All seems fine till I click on a few elements and start selecting them. The problem doesn't occur with all the tags. Only some span/p tags get the issue. 

Check out this video - [https://youtu.be/O4SxnzAYfhA](https://youtu.be/O4SxnzAYfhA)

This error doesn't occur when I host the code locally, It only occurs when I launch it on a remote server or if I launch it on a server on my ip.

Browser: Chrome - Version 56.0.2924.87 (64-bit)
MacOS Yosemite
Quill version 1.2
Please ask me if you need any other info.

**Comment by jhchen** [comment]
Can you reproduce this with an editor on the quilljs.com documentation site?

**Comment by nikhil4092** [comment]
No. This doesn't happen on the quilljs site. I wondered if it was an error on my side so I stripped out all extra code other than the initialization of Quill and tried it. The same problem occurs. What could be the problem? Something specifically I should look at?

**Comment by jhchen** [comment]
If you have stripped out the extra code other than initialization, please post an example on Codepen or JSFiddle. Otherwise the specific part you should look at for the culprit is your application code.

**Comment by nikhil4092** [comment]
Hey @jhchen.
I tried as much a possible to reproduce the issue on JSFiddle or on Codepen but the issue seems to happen only when quill is on a remote server.  I tried everything to debug my code so i thought ill just create a new rails project from scratch and try. I created a new project from scratch which has nothing but the implementation of quill. 

The layout - [https://github.com/nikhil4092/Quilltest/blob/master/app/views/layouts/application.html.erb](url)

The view - [https://github.com/nikhil4092/Quilltest/blob/master/app/views/test/test.html.erb
](url)
The full test rails app - [https://github.com/nikhil4092/Quilltest](url)

I have deployed the test app to a heroku server here - [https://frozen-tundra-71946.herokuapp.com/](url)

Try pasting this test from [https://docs.google.com/document/d/1FU5Dx9CNixa3PCn4AwYvzQ1jcOY1OfdHqLc-GltWorg/edit?usp=sharing](url) to the test editor.

The issue doesn't occur when I use a localhost, it only occurs when I put it on a remote server. As you can see the, The rails app has nothing but the initialization of Quill but still has the same issue.

**Comment by nikhil4092** [comment]
@jhchen Hey. If you could check this out when you are free, that would be great. Thanks.

**Comment by jhchen** [comment]
I'm not able to reproduce with your examples.

**Comment by nikhil4092** [comment]
Did you try it here  https://frozen-tundra-71946.herokuapp.com/  Are you able to reproduce it there? You need to click around a bit and then some paragraphs have that issue.
I have put up the whole code on git hub without any changes. https://github.com/nikhil4092/Quilltest

**Comment by nikhil4092** [comment]
**UPDATE:**
If any one else is facing the same issue, Its because the grammarly plugin is installed. It causes some crazy behaviour on Quill. Disabling it will solve the issues.
