### ISSUE TITLE
Link breaks wrapped in paragraph tags are not preserved after paste

### ISSUE THREAD

**Issue by timeiscoffee** [quilljs/quill#1352]
If you have more than one `<br/>` tag at the end of the content and use `dangeoruslyPasteHTML` or paste, it will collapse the last 2 `<br/>` into a single one: http://codepen.io/anon/pen/BWQxBR

**Steps for Reproduction**
1. Paste 2 line breaks, i.e. `<br/><br/>`

**Expected behavior**:
Both line breaks are preserved

**Actual behavior**:
Only one line break remains

**Platforms**:
Chrome 56, Mac OS Sierra

**Version**:
1.1

**Comment by timeiscoffee** [comment]
@jhchen is this an expected behavior?

**Comment by benbro** [comment]
Fixed in v1.3.7 and v2.0.0-rc.0
