### ISSUE TITLE
prompt for Link Handling (for Edit | Remove)

### ISSUE THREAD

**Issue by maku** [quilljs/quill#1353]
I know how to define a customized prompt for the input of a link:

e.g.

```
toolbar.addHandler('link', (value) => {
      if (value) {
        var href = prompt('Enter the URL');
        this.quillEditor.format('link', href);
      } else {
        this.quillEditor.format('link', false);
      }
    });
```

What is the equivalent for the prompt for an existing link (Visit URL .... Edit | Remove).
Is it possible to provide a customized version of this??

**Comment by jhchen** [comment]
There is not a way to customize the Snow link tooltip at the moment.

**Comment by lauzis** [comment]
Is there now way how to add handlers for edit/remove link?

**Comment by kangax** [comment]
+1 for adding handlers for edit/remove. In my case, I'd like to encode URI before setting link value to it.

**Comment by bvv218** [comment]
Is there a way to add class name to this?

**Comment by ncovercash** [comment]
I'd love to add an option for opening in a new tab or opening in current window to the tooltip
