### ISSUE TITLE
href tel has been deleted 

### ISSUE THREAD

**Issue by fabienbranchel** [quilljs/quill#1355]
Insert href tel isn't possible.

**Steps for Reproduction**

1. Visit https://codepen.io/fabienpopup/pen/zZoevq?editors=1010

2. Click on URL button : it's insert href mailto in quill editor and you can see above the editor the HTML get from quill after the insert. As you can see, the result is nearly fine.

3. Click on TEL button : it's insert href tel in quill editor and you can see above the editor the HTML get from quill after the insert. As you can see, the result isn't correct, the phone number has been deleted.

**Platforms**:

Chrome 56.0.2924.87 (64-bit)
Mac OSX 10.11.5

**Version**:

Quill 1.2.2

**[EDIT]** : I guess it's because of using dangerouslyPasteHTML, and you probably can't do anything. Thank you for reading.

**Comment by timeiscoffee** [comment]
@fabienbranchel this is because only `http`, `https`, and `mailto` are whitelisted: https://github.com/quilljs/quill/blob/develop/formats/link.js#L18

If you want to support tel, you can create a custom format that extends off Link that has a custom whitelist.

**Comment by fabienbranchel** [comment]
How can I get the whitelist of link formats ?

I found this in your doc : 

`var FontAttributor = Quill.import('attributors/class/font');`
`FontAttributor.whitelist = [
  'sofia', 'slabo', 'roboto', 'inconsolata', 'ubuntu'
];`
`Quill.register(FontAttributor, true);`

I want to replicate this, doing :

`var LinkFormats = Quill.import('formats/link');`
`console.log(LinkFormats.whitelist);`

But LinkFormats.whitelist is undefined, so it's probably not the good way.

**Comment by jhchen** [comment]
@timeiscoffee is correct. You can simply overwrite the method

```js
var LinkBlot = Quill.import('formats/link');
LinkBlot.sanitize = function(url) {
  // return sanitized url
};
```

or you can create and register your own

```js
var LinkBlot = Quill.import('formats/link');
class MyLink extends LinkBlot {
  // overwrite whatever you want
}
Quill.register(MyLink, true);
```
