### ISSUE TITLE
Inserting a link while retaining at index 0 yields error

### ISSUE THREAD

**Issue by jziggas** [quilljs/quill#1358]
**Steps for Reproduction**

1. Visit https://jsfiddle.net/ookmgoqj/3/ and press button

**Expected behavior**:

Insert a link while retaining content at the programmatically provided index value. Under other conditions the provided selection index will have a non-zero value and work as expected.

**Actual behavior**:

`Uncaught TypeError: Cannot read property 'length' of undefined` from
`var length = op.retain || op.delete || op.insert.length || 1;` in quill.js:2201

**Platforms**: Chrome 56

Include browser, operating system and respective versions 

**Version**: 1.2.2

**Comment by benbro** [comment]
updateContents() expects a valid delta and {retain: 0} is not a valid op.
Try to use the delta API to build a valid delta:
https://jsfiddle.net/vLpx5oo5/

```javascript
let selection = {index: 0, length: 0};
  var delta = new Delta().retain(selection.index)
                         .insert('https://www.google.com', { link: 'https://www.google.com' });
  quill.updateContents(delta, 'user');
```

**Comment by jziggas** [comment]
Interesting, I was just following how https://quilljs.com/docs/api/#updatecontents was building out an array or objects but I guess doing it that way has created this gotcha? Should the documentation updateContents be updated to provide an example using the Delta API?

**Comment by benbro** [comment]
Let's ask @jhchen  if he thinks another Delta example will be useful.

The updateContents doc point to the[ Delta doc](https://quilljs.com/docs/delta/) which has the following notice:
```
Note: It is not recommended to construct Deltas by hand
—rather use the chainable insert(), delete(), and retain() methods to create new Deltas.
```

**Comment by jziggas** [comment]
Yeah so it seems like the example for `updateContents` is not the recommended implementation prescribed by the Delta documentation.

**Comment by benbro** [comment]
Quill already includes delta.
The modified version of your code already demonstrate it:
```javascript
var Delta = Quill.import('delta');
```
