### ISSUE TITLE
`dangerouslyPasteHTML` erratic behavior with consecutive newlines

### ISSUE THREAD

**Issue by GaurangTandon** [quilljs/quill#1363]
As I have observed while typing in Quill editor, this is the default structure of multiple newlines:

![image](https://cloud.githubusercontent.com/assets/6308683/23832799/891be32a-0762-11e7-8088-2fa0c0931735.png)

The text contains two newlines in between and two at the end. The markup correctly represents this structure by having `<p><br></p>` at the required position. However, the same does NOT happen when using `dangerouslyPasteHTML`. **_It deletes the last newline of the editor for no reason._**

**Steps for Reproduction** Visit http://codepen.io/anon/pen/GNbmjy?editors=1010

**Expected behavior**:
This text:
```


Hi




```
**Actual behavior**:

```


Hi



```
_(last new line missing)_

------

Is this expected behavior or is there some implementation mistake?

**Comment by jhchen** [comment]
This is expected behavior. `dangerouslyPasteHTML` just passes the snippet through the clipboard matchers which may or may not produce the snippet provided.

**Comment by GaurangTandon** [comment]
@jhchen aren't the matches incorrectly implemented then? I mean, why's the matcher configured to delete the last newline?

**Comment by jhchen** [comment]
If you paste multiple blocks (like two paragraphs), for many sources it is indistinguishable whether or not you pasted part or all of the 2nd block. There could be a long debate on which case should be favored but Quill favors the former and removes up to one unformatted newline on paste. For those that disagree, one could always provide their own matchers and/or clipboard module to modify this behavior.
