### ISSUE TITLE
Unable to bind metaKey + enter on macOS

### ISSUE THREAD

**Issue by montlebalm** [quilljs/quill#1365]
It looks like you're unable to bind `metaKey + enter` in the Quill keyboard module. It appears that you _can_ bind `shortKey + enter`. It would be helpful to have the former when targeting macOS specifically.

**Steps for Reproduction**

1. On macOS, visit https://quilljs.com/playground/
2. Use the following configuration:

```
var quill = new Quill('#editor-container', {
  modules: {
    keyboard: {
      bindings: [{
        key: 13, // enter
        metaKey: true,
        handler: function() {
          console.log('meta enter');
        },
      }, {
        key: 13, // enter
        shortKey: true,
        handler: function() {
          console.log('short enter');
        },
      }]
    }
  },
});
```

3. Hit `cmd + enter`

**Expected behavior**:

You should see "meta enter" in the console.

**Actual behavior**:

You see "short enter" in the console.

**Platforms**:

macOS: Safari, Chrome 56

**Version**:

Version 1.2.2.

**Comment by SahilPatel2349** [comment]
keyboard: {
        bindings: {
          tab: false,
          // list: {
          //   key: "backspace",
          //   context: { format: ["list"] },
          //   handler(range, context) {
          //     backspaceHandler(range, context);
          //   },
          // },
          enter:
            portal?.parentSection === "credit"
              ? {
                  key: 13,
                  handler: () => {},
                }
              : null,
          shiftEnter:
            portal?.parentSection === "credit"
              ? {
                  key: 13,
                  shiftKey: true,
                  handler: () => {},
                }
              : null,
          controlB: {
            key: 66,
            handler: () => {
              console.log("Hello from Control B");
            },
          },
          commandB: {
            key: 66,
            metaKey: true,
            handler: (event) => {
              console.log("hello");
              // Check if it's Mac and Command key is pressed
              if (event.code === "KeyB" && event.metaKey) {
                console.log("Command + B key pressed");
              }
            },
          },
        },
      },
      
      control + B is working for me, But command + B is not working on mac. 
      
      What am I doing wrong here?
