### ISSUE TITLE
Android WebView (chromium)

### ISSUE THREAD

**Issue by volser** [quilljs/quill#1366]
[Describe the issue]

**Steps for Reproduction**
Open Quill in Android WebView.
Press enter from a Header (H1, H2, ...), cursor goes all the way to top

**Expected behavior**:
Should just go to next line with normal text.

**Actual behavior**:
Cursor goes all the way to top and next error in console:

I/chromium: [INFO:CONSOLE(8)] "Uncaught Error: [Parchment] Cannot insert block into inline", source: file:///android_asset/quill/quill.min.js (8)
I/chromium: [INFO:CONSOLE(11)] "Uncaught TypeError: Cannot read property 'emit' of undefined", source: file:///android_asset/quill/quill.min.js (11)
I/chromium: [INFO:CONSOLE(11)] "Uncaught TypeError: Cannot read property 'emit' of undefined", source: file:///android_asset/quill/quill.min.js (11)

**Platforms**: Android 6.0,  WebView (chromium)

**Version**:
1.2.2

**Comment by benbro** [comment]
Can you make a screen capture of the cursor going up when you press Enter?

**Comment by volser** [comment]
The issue was with that style:

-webkit-user-modify: read-write !important;

**Comment by volser** [comment]
Without this styles - all ok ))

**Comment by volser** [comment]
Android app for tests
https://github.com/volser/quilljs_android_test

**Comment by jhchen** [comment]
I'm not sure what's being reported or asked here. It kind of sounds like you solved your own issue? Please clarify and we may re-open if needed.
