### ISSUE TITLE
Cursor position after calling setContents(delta)

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#1367]
I'm calling quill.setContents(delta) with a delta from OT server.
If the op is before the cursor, it moves the cursor forward or backwards as expected.

If the op is after the cursor, it moves the cursor to the end. For example, if a user is typing and another user is clicking Enter at the end of the doc, the cursor will jump to the new line and will break the current line in the middle.

Should Quill keep the cursor at the current position if the op is at or after the cursor?
Or maybe I should transform the local selection as part of applying the remote delta?

**Steps for Reproduction**

1. Visit http://codepen.io/anon/pen/KWXwgw
2. Focus the editor at the end of the word "Hello" (before setTimeout is called)
3. Wait 5 seconds, for the timeout to fire. updateContents will add 3 new lines and a word.

**Expected behavior**:
Cursor should stay at the same position, after the word Hello.

**Actual behavior**:
Cursor jumps to the end of the document.

**Platforms**:
Firefox 52, Windows 7

**Version**:
1.2.2

**Comment by nipunjain87** [comment]
Resolving this issue has created another issue.
If we add an image to rich-text-editor using image toolbar, the cursor should move at end of image. But it is maintaining it's position.
This is not user friendly as user normally moves forward and he/she will have to manually click after the image to continue adding content.

**Comment by jhchen** [comment]
Can you make a separate issue @nipunjain87
