### ISSUE TITLE
How to know if Quill is already instanciated on a container?

### ISSUE THREAD

**Issue by lowi** [quilljs/quill#1368]
I have a single page application and I would like to make sure that I am not creating Quill on the same container multiple times.

What would be the easy way to detect it? Or should I track my instanciation in a variable?
I have also noticed that the destroy method has been removed. So I just trust the garbage collector to clean up?

**Comment by benbro** [comment]
You should track the Quill instance in your code.

Please see this about the destroy method: https://github.com/quilljs/quill/issues/1040
