### ISSUE TITLE
Backspace not working in html child node of Embed

### ISSUE THREAD

**Issue by lowi** [quilljs/quill#1369]
I am trying to create an Embed with two HTML nodes.
I would like the user to be able to edit one of the HTML node.

The text is editable, but the backspace is not registered

**Steps for Reproduction**
1. Visit http://codepen.io/lowi/pen/xqXBEv
2. Double-click a word and try backspace => it doesn't work
3. Double-click a word and type some text => it works

**Summary of code on codepen**
```
var Embed = Quill.import("blots/embed");
class CommentBlock extends Embed {
        static create(value) {
          const node = super.create(value);
          const label = document.createElement("span");

          label.classList.add("input-group-addon");
          label.classList.add("label-success");
          label.setAttribute("contenteditable", false);
          label.textContent = value.text;
          const commentNode = document.createElement("span");
          commentNode.classList.add("form-control");
          commentNode.textContent = "I can type, select and overwrite, but backspace doesn't work. Double-click on a word and type backspace";

          commentNode.setAttribute("contenteditable", true);

          node.appendChild(label);
          node.appendChild(commentNode);

          node.setAttribute("contenteditable", true);
          return node;
        }
  }
  CommentBlock.blotName = "commentblock";
  CommentBlock.tagName = "div";
  CommentBlock.className = "input-group";
  Quill.register(CommentBlock);
```

**Expected behavior**:

1. I think it should work with the backspace.

**Platforms**:
MacOS with Chrome Version 56.0.2924.87 (64-bit)

**Version**:
Quill 1.2.2

**Comment by TkTech** [comment]
Still an issue with 1.3.6. It's blocking a lot of otherwise neat & trivial uses of Embed :(

**Comment by haris-appifytech** [comment]
@TkTech try this, Just overwrite the keyboard bindings to delete your Text on Press Backspace.
`modules: {							
	toolbar: [
	     ['bold', 'italic', 'underline', 'strike'],
	     ['code-block', 'blockquote', { 'list': 'ordered' }, { 'list': 'bullet'}, { 'indent': '-1' }, { 'indent': '+1' }],
	 ],
        keyboard: {
	     bindings: {
			list: {
				key: 'backspace',
				context: {
						format: ['list']
					},
				handler: function (range, context) {
					if (range.index === 0) return;
					if (range.length === 0) {
					          this.quill.deleteText(range.index - 1, 1, Quill.sources.USER);
					} else {
						this.quill.deleteText(range, Quill.sources.USER);
					}
					}
				}
			}
		}
},`

**Comment by TkTech** [comment]
@haris-appifytech appreciate it (btw, use triple ticks \``` to format multiline codeblocks), unfortunately we've since moved on to something custom built on top of Prosemirror.
