### ISSUE TITLE
Size format is lost on paste

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#1372]
The ql-size-large class is lost when pasting in Chrome

**Steps for Reproduction**

1. Visit http://quilljs.com/docs/formats/
2. Change text size to Large
3. Type "test"
4. Copy the word "test" and paste it.

**Expected behavior**:
The pasted text should have large text size.

**Actual behavior**:
The pasted text has normal text size.

**Platforms**:
Chrome 57.0.2987.110 on Windows 7
Can't reproduce on Firefox 52.0.1

**Version**:
1.2.2

**Comment by jhchen** [comment]
Duplicate #1083
