### ISSUE TITLE
Security in terms of injecting javascript?

### ISSUE THREAD

**Issue by zys5945** [quilljs/quill#1375]
So I'm planning to use quill in my website to get user input. I will use getContents() to get the Delta object and save it directly as in a TEXT field in my database, and later on when it needs to be rendered, I load the Delta object and directly pass it to the client and render it use the setContents() function.

Now I'm just wondering if it is possible to inject javascript into the editor (and not lost when saved and set)?

I tried playing around by adding event handler attributes, but seems like they are not returned by the getContents, but I just want to make sure by asking it here in case there's anything that I'm missing

Thanks in advance

**Comment by jhchen** [comment]
None of Quill's core formats will inject to execute javascript.
