### ISSUE TITLE
undo the first time,but the history.stack.redo.length = 0?

### ISSUE THREAD

**Issue by OnlyBreak** [quilljs/quill#1376]
monitor 'Quill.events.EDITOR_CHANGE',  and undo the first time, but the history.stack.redo.length = 0?

**Expected behavior:**
undo the first time I expect the history.stack.redo.length !=0 , and i can do something...

**Actual behavior:**
quill.history.stack.redo.length = 0

**Platforms:**
chrome

**Version**
1.2.2

**Comment by sferoze** [comment]
@OnlyBreak I am using the quill history module and I do not see this issue. It works as expected...

**Comment by nikparo** [comment]
This is the relevant code from `history.js`:
``` js
change(source, dest) {
  if (this.stack[source].length === 0) return;
  let delta = this.stack[source].pop();
  this.lastRecorded = 0;
  this.ignoreChange = true;
  this.quill.updateContents(delta[source], Quill.sources.USER);
  this.ignoreChange = false;
  let index = getLastChangeIndex(delta[source]);
  this.quill.setSelection(index);
  this.stack[dest].push(delta);
}
```

The destination stack length (redo when undoing, and vice versa) is updated after `updateContents` and `setSelection`. As such the history stack is not quite correct during any `editor-change` events.

Should maybe `this.stack[dest].push(delta);` be moved up a few lines?
