### ISSUE TITLE
Is this editor good for writing custom emails?

### ISSUE THREAD

**Issue by mehulcse** [quilljs/quill#1378]
Hi
This is not an issue as such I just want to know if this editor can be used as custom email editor?

Because the output HTML consist of quill specific classes for alignment and that won't be reflected in email if I send this html as an email.

**Comment by benbro** [comment]
You can use [inline styles](https://quilljs.com/playground/#class-vs-inline-style) instead of classes.

**Comment by Noor0** [comment]
Not all styles can be inlined though. I want to inline styles for indented lists but I don't think that that's possible with quill
