### ISSUE TITLE
An extra P is inserted between two lines if there is sufficient whitespace

### ISSUE THREAD

**Issue by kylebragger** [quilljs/quill#1379]
When initializing the Quill editor with existing markup, if there is sufficient whitespace between two lines (e.g. a P and BLOCKQUOTE), Quill inserts an extra P between them.

Also, it appears to only happen when the preceding line wraps.

It was mentioned in my previous, semi-related ticket (#1341) that deltas should be used and that it may be necessary to play with clipboard matchers to affect how Quill is initializing data. Could that be elaborated on insofar as how it might render this (possible) bug a nonissue?

**Steps for Reproduction**

1. Visit https://jsfiddle.net/y500jh11/11/
2. Observe the extra P inserted (I've set it up to have a red bg color)
3. Edit the first P's contents to be only a few words and thus not wrap
4. Save and refresh the JSFiddle
5. Observe no extra line is inserted
6. Add in a bunch of text to the first P so that it wraps again
7. Update the blockquote CSS margin-top to 1%
8. Re-run the JSFiddle; no extra line is inserted

**Expected behavior**:
The paragraph and blockquote are rendered as-is, with no additional lines injected between them, regardless of CSS styling.

**Actual behavior**:
There is an extra, empty paragraph inserted between the P and BLOCKQUOTE tags.

**Platforms**:

Chrome 57, Mac OS Sierra, Latest stable Quill (1.2.2)

**Version**:

1.2.2

**Comment by mbrainiac** [comment]
+1

**Comment by jtomaszewski** [comment]
Yeah, I encounted the same problem; using quill 1.2.3 . Seems like the problem is `margin-top: 1%`. When using px or no margin its okay. Other demo: https://jsfiddle.net/y500jh11/11/

**Comment by jhchen** [comment]
You can now use a new config in 1.3.0 [`matchVisual`](https://quilljs.com/docs/modules/clipboard/#matchvisual) to disable Quill's visual paste matching.

**Comment by tinacious** [comment]
@jhchen adding the `matchVisual` config as you said worked to strip out the unnecessarily-injected `<p><br></p>`:

```js
modules: {
  clipboard: {
    matchVisual: false
  },
}
```

`matchVisual: false` should probably be the default configuration since it's unintuitive to expect extra `<p><br></p>` to have been injected by default. It gets injected between paragraphs and list elements.

**Comment by loopmode** [comment]
For me, `matchVisual: false` solved most of the cases, but there is still one exception. (I use it in React)
When the content provided to Quill is an empty string, it still makes `<p><br></p>`.
However, I got around that with this smelly hack on my end:
```
handleChange({ content }) {
    if (content === '<p><br></p>' && selectedItem.get('content') === '') {
        return;
    }
    ...
```

**Comment by reinisg** [comment]
> @jhchen adding the `matchVisual` config as you said worked to strip out the unnecessarily-injected `<p><br></p>`:
> 
> ```js
> modules: {
>   clipboard: {
>     matchVisual: false
>   },
> }
> ```
> 
> `matchVisual: false` should probably be the default configuration since it's unintuitive to expect extra `<p><br></p>` to have been injected by default. It gets injected between paragraphs and list elements.

This helped me only after when I was migrate from react-quill 2.0.0-beta.4 to 2.0.0. Thanks!!

**Comment by danuja01** [comment]
> @jhchen adding the `matchVisual` config as you said worked to strip out the unnecessarily-injected `<p><br></p>`:
> 
> ```js
> modules: {
>   clipboard: {
>     matchVisual: false
>   },
> }
> ```
> 
> `matchVisual: false` should probably be the default configuration since it's unintuitive to expect extra `<p><br></p>` to have been injected by default. It gets injected between paragraphs and list elements.

Damn you saved my day! Thanks for million times!

**Comment by omarthisside** [comment]
.ql-editor.ql-blank::before {
  left: 0px !important;
}

I did it using css.
