### ISSUE TITLE
Parchment Error When Removing DOM Node

### ISSUE THREAD

**Issue by caal-15** [quilljs/quill#1382]
Hello!, I'm having an issue developing a simple React Component using Quill, this is the sample code:

```javascript
import Quill from 'quill'

export default class RichTextEditor extends Component {
  componentDidMount () {
    this.editor = new Quill(this.quillContainer, {
      modules: {
        toolbar: [
          [{ header: [1, 2, 3, false] }],
          ['bold', 'italic', 'underline'],
          [{ list: 'ordered' }, { list: 'bullet' }]
        ]
      },
      placeholder: 'Añade una descripción para completar los pagos...',
      theme: 'snow'
    })
  }

  render () {
    return (
      <div>
        <div ref={c => { this.quillContainer = c }} />
      </div>
    )
  }
}
```
The Text Editor Component is instantiated inside a Toggle Component which makes the content inside it appear and disappear (returns a container with its children or null), sample code:

```javascript
class Toggle extends Component {
  constructor (props) {
    super(props)
    this.state = {show: props.show}
    this.toogle = this.toogle.bind(this)
  }

  toogle (event) {
    event.preventDefault()
    event.stopPropagation()
    this.setState({show: !this.state.show})
  }

  render () {
    const { show } = this.state
    const { title } = this.props

    return (
      <div class="toggle" role="region" aria-labelledby={title}>
        <a
          href="#Productos"
          onClick={this.toogle}
          className="toggle-header" role="heading"
        >
          {title}
        </a>
        {show
          ? <div className="toggle-content">{this.props.children}</div>
          : null
        }
      </div>
    )
  }
}
```
The Component instantiation looks somewhat like this

```javascript
<Toggle show title="A Tittle">
  ...
  <RichTextEditor />
  ...
</Toggle>
<Toggle title="Another Title">
  ...
</Toggle>
```

Which should work fine, however as soon I close the Toggle this error shows up `Error: [Parchment] Cannot insert block into inline`, followed by this other errors every time I trigger some change in one of the React Components `TypeError: this.emitter is undefined` and `TypeError: this.observer is undefined` (also the React app basically stops working as intended), which leads me to believe a reference is being left somewhere which still tries to access the now non-existent component onto which the Quill instance was mounted.

**Steps for Reproduction**

1. Create a React app with the previously described workflow.
2. Toggle and Untoggle The editor.
3. Try to trigger any change in another of your components.
4. The Errors Mentioned Above appear.
5. Weird things start to happen.

**Expected behavior**:

Should not error, and the React app stops working as intended

**Actual behavior**:

 It errors, and the React App stops working as intended

**Platforms**:

Debian 9 Stretch, Firefox 45.8.0, Chrome 57.0.2987.110

**Version**:

1.2.2

**Sidenote**

Curiously, if I add this lines to the `RichTextEditor` Component, the other errors do not show up:

```javascript
componentWillUnmount () {
    this.editor.destroy()
}
```

However `TypeError: this.editor.destroy is not a function` shows up (as it should).

**Comment by temich666** [comment]
I have the same problem

**Comment by jhchen** [comment]
Can either of you provide a stack trace?

**Comment by caal-15** [comment]
I'm sorry, this happened on a project I was working on for another company, I no longer have access to the code, I Will try to provide one later if I have time
