### ISSUE TITLE
Adding a hyperlink to an image?

### ISSUE THREAD

**Issue by arist0tl3** [quilljs/quill#1385]
So after tooling around for quite a while, I'm still struggling with this one. 

I'm aiming to have similar functionality for an image as for text -- highlight the image, click the link button in the toolbar, and set the link. A subsequent click on the image would bring up the link tooltip, with the option to view/remove/edit.

I'm already using a custom ImageBlot class, that extends BlockEmbed so that we can pull from our own internal libraries of images. Feels like without extending Inline, this isn't possible?

I've been able to set the href outside of the editor by providing a text input when the user initially selects the image, but I'd prefer an in-editor experience, especially for viewing/editing/removing the link.

Thaks in advance for any advice!

**Comment by jhchen** [comment]
> I'm already using a custom ImageBlot class, that extends BlockEmbed so that we can pull from our own internal libraries of images. Feels like without extending Inline, this isn't possible?

Can you clarify this part?

**Comment by ywmail** [comment]
Add b blank space after the image and then select the image and the blank space, then you can add hyperlink to the image.

**Comment by pradeepkumawat2112** [comment]
[https:www.goog;e](url)

**Comment by pradeepkumawat2112** [comment]
[www.google.com](url)
