### ISSUE TITLE
Bubble Toolbar is instantiated if an empty array of toolbar options is given

### ISSUE THREAD

**Issue by christianhg** [quilljs/quill#1389]
**Steps for Reproduction**
Create a new Quill RTE using the bubble theme and an empty list of toolbar options:
```
 var quill = new Quill('#editor', {
   modules: {
     toolbar: []
   },
   theme: 'bubble'
 });
```

http://codepen.io/christianhg/pen/NpJEBR

**Expected behavior**:
No toolbar appears when selecting text.

**Actual behavior**:
An empty toolbar appears.

![screen shot 2017-04-04 at 14 15 34](https://cloud.githubusercontent.com/assets/4602382/24656082/4192b984-1941-11e7-840e-6d53485a7538.png)

I expected that the toolbar to not be instantiated when given an empty list of options.

**Comment by christianhg** [comment]
On a related note, the Bubble Toolbar is instantiated with bold, italic, link, h1, h2 and blockquote if the toolbar is set to `undefined`:

http://codepen.io/christianhg/pen/bqZQPg

**Comment by jhchen** [comment]
This behavior is consistent with the documentation. Omitting the option means default button set, false means no toolbar, any array mean toolbar with elements of array as controls.

**Comment by christianhg** [comment]
Thanks for the answer @jhchen. I'm unable to find this in the documentation but at least I'm now able to get rid of the floating empty toolbar :)

**Comment by jhchen** [comment]
https://quilljs.com/docs/modules/toolbar/

**Comment by christianhg** [comment]
Naturally that is the page I have been looking at. I'm not trying to be difficult here, but I still don't see where it's stated that
- `[]` results in an empty toolbar,
- `undefined` results in the default toolbar
- and `false` results in no toolbar.

Should we improve the documentation?
