### ISSUE TITLE
Trying to set editor to autogrow before overflow below the window limits.

### ISSUE THREAD

**Issue by ggCS** [quilljs/quill#1394]
I have my Quill Editor autogrowing and scrolling handled by the window because I want the editor to grow as much as the user wants. However, from a UX/UI perspective I don't like how the height and scrollToView() seem to be adjusted and called, respectively, when the text exceeds the bottom limit of the window. The text has to disappear before the height can be extended and the editor automatically scrolled to the bottom. I would prefer the bottom border of the editor to never go deeper than 20px from the bottom limit of the window. I'm not sure where in Quill the handling is for the autogrow, but I have looked for a while now. 

Overall, I just want the height and scrolling to update before the text goes off screen so the user can still see what he/she is typing.

**Comment by jhchen** [comment]
Did you check out the autogrow example? https://quilljs.com/playground/#autogrow-height

**Comment by ggCS** [comment]
So I have an idea of using a custom scroll-container of sorts but I'm not sure how to change when overflow will trigger the scrolling. This may be a limitation or strictly a CSS problem that outside of Quill but I'm not entirely sure. This example does look better than the default however.

**Comment by jhchen** [comment]
Not sure what scrollToView() function you are referring to but pressing does scroll to the new line. If it does not please file an Issue and fill out the requested fields. `insertText()` does not by design as Quill does not want to assume why users are calling it. You can call `focus()` to scroll to the selection if it is out of view.
