### ISSUE TITLE
Quill Bubble Toolbar on iOS/Mobile does not work well

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#1396]
Tested on iOS device but might also apply to all mobile devices. These issues are seen in the quill example editors. 

When using the bubble theme and after selecting some text the toolbar does not show right away. After selecting text, you have to scroll the window a tad bit, and then the quill toolbar shows. 
Then once the toolbar is shown, the first time you select a formatting button, the text does not get formatted, the selection disappears but the toolbar stays open, and the selection collapses to blinking cursor.

Since the toolbar is still open you can try tapping the formatting button again, and this time the text does get formatted. And the selection re-selects the text that collapsed after the first tap.  

Just try using the bubble toolbar on an iOS device you will notice all these issues when trying any formatting command like Bold. 

**Steps for Reproduction**

1. Visit https://quilljs.com/playground/#autogrow-height on an iOS device
2. Select some text
3. Attempt to format the selected text with the quill toolbar that is suppose to show

**Expected behavior**:

The toolbar should show itself after selecting text, and format the text on the first tap of any formatting button. 

**Actual behavior**:

All the issues described above...

**Platforms**:

iOS

**Version**:

Quill 1.2.3

**Comment by jhchen** [comment]
There seems to be two issues described here:

1. The toolbar does not always show up when a selection is made
2. With a selection and toolbar shown, touching a format button like bold does not apply the formatting.

I've never been able to produce 1) so more guidance on here would be helpful. On 2) it seems to be largely a case of the touch target not being very large for mobile devices. To confirm this every time it does work you should see the button darken for a split second (indicating the button press). If not that means your finger missed the button. Another way to check this is just to make the button a lot bigger.

**Comment by jhchen** [comment]
Quill now uses selectionchange in 1.3.0 which should always accurately update the selection which may cause 1. Please try on the latest version to see if it is fixed.

**Comment by sferoze** [comment]
@jhchen The toolbar pops up nicely and works as expected on mobile! I tested on an iOS device. Thanks!
