### ISSUE TITLE
How to insert an undeletable block-level element?

### ISSUE THREAD

**Issue by awpsawps12** [quilljs/quill#1402]
Here I customize a block element by `Quill.import('blots/block/embed')` which I insert into the editor content. I would like to know that if there is any way to make it undeletable, therefore the user could not delete it or edit it? Thanks a lot.

**Comment by DawidLoubser** [comment]
Hi, I have the same issue, as well as a related one: If I initialise Quill with some HTMl content, what is the easiest way to support "protected" regions, i.e. based on a particular pattern (such as CSS class name) such that Quill will not allow the editing of those elements.

With my limited understand of Quill's architecture, it seems that it should be fully possible to do this. However, I can't find any information about whether any of the standard modules can be configured to support this kind of functionality, or whether anybody has perhaps made some extensions that simply support "locked" regions.

Any insight would be much appreciated.

**Comment by jspaine** [comment]
It's easy to make a blot undeletable by overriding the base class deleteAt method with one that just returns false. To prevent editing I've been using a nested span with contenteditable="false" set on it. It's still a little buggy but seems to work better than just setting contenteditable directly on the blot element.

The hard part is preventing replacement when the blot's part of a selection. I've got some progress by listening to keypress and making a list of any of my blots in the selected range and just reinserting them. It sort of works when the selection is confined to one block element but fails when it spans multiple blocks.

Here's a [pen to try it out](https://codepen.io/jspaine/pen/dRXgjm?editors=0011)

**Comment by jonathanfishbein1** [comment]
@jspaine thank you

**Comment by karim10** [comment]
You can add an event listener for the backspace button in the modules like that:
`this.quill = new Quill(this.contentElement, {
  modules: {
    keyboard: {
      bindings: {
        video: {
          key: 'backspace',
          handler: function(range, keycontext) {
            let format = _this.quill.getFormat(range.index - 1);
            if (!format.video && !keycontext.format.video) {
              // propogate to Quill's default
              return true;
            } // else do nothing to prevent deleting video
          }
        }
      }
    }
  },
  theme: 'snow'
});`

**Comment by hakonleung** [comment]
> It's easy to make a blot undeletable by overriding the base class deleteAt method with one that just returns false. To prevent editing I've been using a nested span with contenteditable="false" set on it. It's still a little buggy but seems to work better than just setting contenteditable directly on the blot element.
> 
> The hard part is preventing replacement when the blot's part of a selection. I've got some progress by listening to keypress and making a list of any of my blots in the selected range and just reinserting them. It sort of works when the selection is confined to one block element but fails when it spans multiple blocks.
> 
> Here's a [pen to try it out](https://codepen.io/jspaine/pen/dRXgjm?editors=0011)
> 
> edit - fixed the spanning multiple paragraphs, it's still pretty buggy though

thx,  how can i define a user-undeletable blot, which means i can delete it by updateContents method?

**Comment by kosty4** [comment]
> It's easy to make a blot undeletable by overriding the base class deleteAt method with one that just returns false. To prevent editing I've been using a nested span with contenteditable="false" set on it. It's still a little buggy but seems to work better than just setting contenteditable directly on the blot element.
> 
> The hard part is preventing replacement when the blot's part of a selection. I've got some progress by listening to keypress and making a list of any of my blots in the selected range and just reinserting them. It sort of works when the selection is confined to one block element but fails when it spans multiple blocks.
> 
> Here's a [pen to try it out](https://codepen.io/jspaine/pen/dRXgjm?editors=0011)
> 
> edit - fixed the spanning multiple paragraphs, it's still pretty buggy though

Hey, any tips how to make the blot deletable via an event (and undeletable on selection/backspace)? I was thinking to call super.deleteAt once the event is catched, but this does not do the trick.

**Comment by kosty4** [comment]
I have found a way to remove the blot via an event - it has nothing to do with quill, but more html-style access of DOM element: 

`
      class MyBlot extends BlotEmbed {
        static create(value) {
          const node = super.create();
          node.setAttribute("class", "ti-myblot myblot-success");

          EventBus.$on("eventfromoutside", ()=> {
            node.parentNode.removeChild(node)
          });

          return node;
        }
        length() {
          return 1;
        }
//here i overwrite the possibility to delete the blot with backspace
        deleteAt() {
          console.log('try')
          return;
        }

      }
`

**Comment by yattias** [comment]
Add:
```
    deleteAt() {
      return false
    }
```

to your custom blot class

**Comment by ivictbor** [comment]
I used next approach in my custom suggested to make it undeletable: https://github.com/devforth/vue-suggestion-input/blob/main/lib/suggestion-input.vue#L25

This code:

```
  p:has(+ [completer]) {
    // background: rgb(255 227 227);  // debug
    display: inline;
  }
```
 allowed to make last p before blot inline

Super-important stuff to make text unselectable is display: contents;, otherwise wrapping contenteditable div behaves extra weird:

```
 .ql-editor [completer] {
    // important to keep pointer-events non none for cursor position on completer click

    // text is not selectable
    user-select: none;
    color: gray;

    // if inline or inline used then user-select: none brakes triple click
    display: contents;

    font-style: italic;
  }
  ```
