### ISSUE TITLE
Characters typed before an EmbedBlot are inserted inside that EmbedBlot.

### ISSUE THREAD

**Issue by Percipient24** [quilljs/quill#1403]
I insert a BlockEmbed blot into the page and move the cursor to be just before it. Instead of behaving like the Twitter Embed (from https://quilljs.com/guides/cloning-medium-with-parchment/#tweets ) where content is inserted before or after the blot ... it adds characters as children of the BlockEmbed.

What's curious about this is: it works as expected in Firefox. (So either it's a bug in Firefox, or a bug everywhere else...)

**Steps for Reproduction**

1. Visit http://codepen.io/percipient24/pen/MmWbPr
2. Click the big red "Insert Sample" button. (will insert a red div `.sample`)
3. Hit the up-arrow key once to position the cursor at the start of the red line.
4. Type some characters. (in the screenshot, I typed asdf)

**Expected behavior**:

I expect the characters from 4. to be inserted before the SampleBlot. Like this:

![screen shot 2017-04-12 at 12 14 00 pm](https://cloud.githubusercontent.com/assets/1882129/24967889/89ebcca0-1f79-11e7-9022-cfe7a1878271.png)

With this markup:

```
<div class="ql-editor" contenteditable="true" data-placeholder="Compose an epic...">
  <p>asdf</p>  
  <div class="sample"></div>
  <p><br></p>
</div>
```

**Actual behavior**:

The characters from 4. are inserted as content of the SampleBlot. Like this:

![screen shot 2017-04-12 at 12 10 38 pm](https://cloud.githubusercontent.com/assets/1882129/24967847/655bc8a4-1f79-11e7-8d31-b6bec1136a4b.png)

With this markup:

```
<div class="ql-editor" contenteditable="true" data-placeholder="Compose an epic...">
  <div class="sample">asdf</div>
  <p><br></p>
</div>
```

**Platforms**:
OS: Mac OS X 10.11.2 64-bit

##### Breaks In:
Chrome : 57.0.2987.133 (64-bit)
Opera : 44.0.2510.1218
Safari : 9.0.2 (11601.3.9)

##### Works in:
Firefox : 52.0.2 (64-bit)

**Version**:

1.2.3

**Comment by Percipient24** [comment]
Setting contentEditable to be false on the node seems to help (at least in the browsers I mentioned above):

```
// excerpt : for full context see http://codepen.io/percipient24/pen/GmRMRe
static create(data) {
  var node = super.create(data);
  node.setAttribute('contentEditable', 'false');
  return node;
}
```
http://codepen.io/percipient24/pen/GmRMRe

But I imagine (having read around in other issues) that this is a quagmire for browser support.

**Comment by jhchen** [comment]
If you don't want content inside the blot then contenteditable=false is the way to do it.

**Comment by terpimost** [comment]
Guys, thats got to be in the documentation. I was looking for that solution for couple of days.
