### ISSUE TITLE
Use Quill to build a textbox like in keynote or microsoft powerpoint

### ISSUE THREAD

**Issue by zhangbobell** [quilljs/quill#1405]
I want to use quill to build a **textbox** like in keynote or microsoft powerpoint, my preliminary ideas are as follows:

1. instantiate a new Quill when double click a html element.
2. when Quill editor blured, exit edit and destroy the instance.

But there still a problem:
Since actions like choose font-size or font-family will also blur the editor, program itself could not judge the user's intend properly : want to exit edit or just change the font-size?

**It is possible to use quill to achieve my purpose?**

Could someone give me some inspirations?

It would be much appreciated for you!

**Comment by benbro** [comment]
You can listen to click events on the document and check if the event target is inside or outside of the editor and toolbar container.

**Comment by zhangbobell** [comment]
Thanks for you reply, I solve it in you way. 👍
