### ISSUE TITLE
[Feature request] Ability to limit the size of image?

### ISSUE THREAD

**Issue by crizant** [quilljs/quill#1409]
I see there are lots of discussions about implementing image upload function instead of using base64 encoded url.

I agree that when user need to insert large images, store base64 url in database is not a good idea.
But in some use case, when the image size is not too big, base64 is perfect!

To ensure the image won't be too large, I think we need to have an option to limit the size of image.

I know I can implement my own image handler to do it, but to do so I need to implement also a file select prompt, insert image logic etc., it would be a duplication of the original implementation.

So it would be better to include this feature into quill core.

**Comment by harrison0723** [comment]
Anybody has a good solution to this?

**Comment by nedvadim** [comment]
Would be great, to have that feature
