### ISSUE TITLE
Cannot input Asian characters in some special case

### ISSUE THREAD

**Issue by ericmm** [quilljs/quill#141]
Jason,

I used the demo page for testing, and made some changes below.
I cannot input the Asian characters into the first place, if I input an English letter in the first place, then I can input Asian characters.

e.g. 
你好  --can't be input
n你好 --can be input

    <script type="text/javascript">
      var editor = new Quill('#editor-container', {
        modules: {
          'toolbar': { container: '#formatting-container' },
          'image-tooltip': true,
          'link-tooltip': true,
          'multi-cursor': true
        }
      });

      var cursorManager = editor.getModule('multi-cursor');
      var authorship = editor.addModule('authorship', {authorId: 'eric', color: 'yellow'});
      authorship.enable();
      
      editor.on('selection-change', function(range) {
        console.log('selection-change', range)
      });
      editor.on('text-change', function(delta, source) {
        console.log('text-change', delta, source)
      });
    </script>

Thanks,
Eric

**Comment by e-jigsaw** [comment]
I have similar bug. Any progress on this issue?

Thanks

**Comment by jhchen** [comment]
Merging with #626
