### ISSUE TITLE
a tags are not clickable

### ISSUE THREAD

**Issue by oldlam** [quilljs/quill#1413]
it seems a tag in quill editor is not opening the link,
even trying to create link with the last [codepen example](http://codepen.io/quill/pen/qNJrYB) from [Cloning Medium with Parchment](https://quilljs.com/guides/cloning-medium-with-parchment/).
it's still not opening the link in new tab.

is this a bug or intended to be not clickable?

**Comment by jhchen** [comment]
Clicking in it is intended to place the cursor at the target, not navigate to the URL -- otherwise it would be very hard to edit link text. A fuller [Quill](https://quilljs.com/) editor has a tooltip come up.

**Comment by jhoughjr** [comment]
bump. Is there any way to make links left clickable?
Having my users right click every time is not something my client wants.
My quill editor embedded in WKWebView Quill 1.3.7 shows no tooltip.
