### ISSUE TITLE
Development Environment - npm run start|test

### ISSUE THREAD

**Issue by StefanNeuser** [quilljs/quill#1414]
A general question: What should happen if i run `npm run start`?

I expected to get quill running within a dev-server on any localhost port.

> [OKAY] Forward Proxy Started in Port NaN

i think i need to setup some of these variables but how?

```
var ports = {
  proxy: parseInt(process.env.npm_package_config_ports_proxy),
  jekyll: parseInt(process.env.npm_package_config_ports_jekyll),
  karma: parseInt(process.env.npm_package_config_ports_karma),
  webpack: parseInt(process.env.npm_package_config_ports_webpack)
};
```

Another question is how to run a single (unit) Test?

**Comment by jhchen** [comment]
The ports are set in package.json. Configuring them would be useful (especially the main proxy 9000) but no one has gotten to it. If you'd like to submit a PR for this, I'd be happy to review it.

**Comment by StefanNeuser** [comment]
Thank you very much for your reply. I was attempting access port 9080 but without success.

It seems that the package.json port config is not available:

```
[WARN] No ENV file found
[WARN] ENOENT: no such file or directory, open 'Procfile'
[OKAY] package.json file found - trying 'npm start'
[OKAY] Forward Proxy Started in Port NaN
[OKAY] Intercepting ALL requests through forward proxy
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDR
```

I'm trying to get a deep dive into quill because we will develop some modules like autocompletion/typeahead to generate links and a chart.js (canvas) BlotType. I like to do that test driven but first i need to get the dev env running on my machine. I have a OSX el captian running with ruby version of foreman version 0.84.0 and npm 3.5.3

I will appreciate if somebody can help me to get in running
