### ISSUE TITLE
code-block attribute is not in the correct place

### ISSUE THREAD

**Issue by maheshmurthy** [quilljs/quill#1416]
**Steps for Reproduction**

1. Visit https://quilljs.com/playground/#form-submit
2. Add a code block and add "alert('hello');" inside it
3. Hit save

**Expected behavior**:
If you see the output in the browser console for value, it is like this:

`"{"ops":[{"insert":"\n\nalert('hello');"},{"attributes":{"code-block":true},"insert":"\n"}]}
`

**Actual behavior**:
Since alert('hello') is in the code block, shouldn't the output be like this?

`"{"ops":[{"insert":"\n\nalert('hello');", "attributes":{"code-block":true}},{"insert":"\n"}]}
`
i.e, attributes code-block should be associated with alert() text and not "\n" text. 

If not, on form submit, how would you know alert() was part of a code block?

**Comment by benbro** [comment]
code-block is block level blot. It is assigned on the whole line, not just part of it.
The new line characters \n is the correct place to put block level attributes.
If you'll test the same with inline attribute like bold, you'll see that it's applied to the text.

**Comment by maheshmurthy** [comment]
So, on form submit I have to store this content in the database. When I am looping through the 'ops' array, when I encounter "insert" key, I get 'alert()' text as it's value. Do I have to look for next element in the ops array to check if the current element is a code block? That doesn't sound right. How do I check if the text is a code block? Thanks!

**Comment by benbro** [comment]
If the attribute is set on a new line character (\n) it's a block blot.
If the attribute is set on a text span, it's inline blot.
