### ISSUE TITLE
Exporting Quilljs doc to other document types

### ISSUE THREAD

**Issue by WriterStat** [quilljs/quill#1419]
Hi! Thanks for the great editor!

I have a need to get the document out of Quilljs and put it in different document types.

When I grab the html out of the root, it has Quilljs specific tags in it and while it recognizes all spaces made while inside the Quilljs editor, it doesn't recognize all the spaces in html. Example type 5 spaces in the editor and then grab the html using root and well 4 of those spaces disappear.  There are other html discrepancies.

Is there a way to get clean wysiwyg html out of the Quill editor? Like a get html option? Thanks ahead!

Without it, how are people exporting from Quilljs to other document types?

Any suggestions are super appreciated. We use javascript on the front end and php on the server side back end.

Guide to exporting from Quilljs?  Thx!

Export suggestions greatly appreciated.  What do people do when they want to get documents out of Quilljs?  For another document type?

Cheers,

**Comment by benbro** [comment]
Asked and [answered](https://github.com/quilljs/quill/issues/903#issuecomment-243844178) before.
Quill use the Delta format.
You can get HTML with quill.root.innerHTML.
If you need other formats you'll have to implement them.

**Comment by WriterStat** [comment]
Hi! Feels like a sore spot, but this is a different question. I guess I was polling the audience to see what they are doing for exports to other document types.

And no...it hasn't been answered. Jeez...

I'd like to use quilljs for large documents 6000+words.

I need to be able to export them to other document types. I am using root as I said.

As a user I'm voicing something here, killing the question means I don't get any feedback.

Your answer, not all that helpful.

I can ask the group.  And see what they are doing for this. And get insight or answers I might not have thought of on how to go about it. I'm asking the group. This is the only place to do that.

So suggestions?

This is the only place to ask as there's not another user forum for these questions.

How are people exporting to other document types using root or Deltas on large documents?

**Comment by WriterStat** [comment]
Looks like I will try and contribute on item #993 Render quill delta.

Thanks!
