### ISSUE TITLE
Best way to access contenteditable div?

### ISSUE THREAD

**Issue by ncammarata** [quilljs/quill#142]
I'm working on integrating @mention functionality(#81) and need direct access to use https://github.com/ichord/At.js.

I'm temporarily doing 

``` javascript
setTimeout(function() {
  var el = element.find('iframe').contents().find(".editor-container");
  // do stuff with el
}, 100)
```

which is clearly bad.

**Comment by lakinmohapatra** [comment]
How to achieve the same in anguar 2 + ? Please advise. 

Thanks
