### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blotName' of undefined

### ISSUE THREAD

**Issue by ericbets** [quilljs/quill#1428]
Uncommenting:
import Align from 'quill/formats/align'; 
Quill.register('formats/align': Align);

causes: 
Uncaught TypeError: Cannot read property 'blotName' of undefined

**Steps for Reproduction**

git clone https://github.com/ericbets/quillpack

**Expected behavior**:
Little alignment widget works

**Actual behavior**:
App crashes

**Platforms**:
Chrome

**Version**:
1.2.4

**Comment by benbro** [comment]
Can you please fork the [codepen](http://codepen.io/quill/pen/KzZqZx) and create a simple test case and steps required to reproduce the bug?

https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#bug-reports

**Comment by ericbets** [comment]
@benbro Did you notice I provided a link to a simple test case in the original comment? Because it's based on: https://github.com/quilljs/webpack-example

Here it is again pasted into codepen: http://codepen.io/anon/pen/aWBLOK

**Comment by benbro** [comment]
Please simplify the test case to the minimum required to reproduce the issue and explain what steps are required to see it.

**Comment by ericbets** [comment]
I removed the custom blot from the proj:
http://codepen.io/anon/pen/eWBeGw

The repo has also been updated.

To see it: load app and look in chrome inspector when it doesn't load.
