### ISSUE TITLE
Typing using Chinese IME, extra character appers before.

### ISSUE THREAD

**Issue by gfafei** [quilljs/quill#1429]
**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two Type Chinese (even number)words using Chinese, and extra character appear appears.

**Expected behavior**: get '啊'

**Actual behavior**: get 'a啊'

**Platforms**:
WIN10
Chrome 58.0.3029.81

**Version**: 1.2.3

**Comment by gfafei** [comment]
When type noting, and call `quill.getText()`， I got `\n`。Why? I expect `''`

**Comment by gfafei** [comment]
I guess the bug is from win10, it just disappear after the latest win10 update.

**Comment by transtone** [comment]
I got the bug in  mac osx 10.11.6，Chrome-58.0.3029.81 。but not in chrome-58.0.3029.110
It seems a chrome bug.

**Comment by gfafei** [comment]
have you try other browser?

**Comment by transtone** [comment]
I do tried the other browser and os, the result is : 

mac-10.11.6: opera/opera-beta   bug,  chrome good, firefox good
windows10: chrome good
archlinux: opera bug, chrome-58.0.3029.110 bug

**Comment by gfafei** [comment]
This bug appear again, and I tried other browser, it only appeared in Chrome.When I last Time update my Chrome， the bug just disappear, hope this help debugging.
