### ISSUE TITLE
Pasting will jump the back to the top

### ISSUE THREAD

**Issue by jbrooksuk** [quilljs/quill#143]
After pasting something into the editor, it'll jump the view back to the top (if it's scrolling). The cursor will remain where it was, but it looks as though you're at the top again.

Quill 0.13.3 (slightly customised to allow stylesheet URL's)

**Comment by LinusMelb** [comment]
Hi there. Actually I encountered the same issue. Can you fix it in the next release?

**Comment by dzagorovsky** [comment]
We are experiencing the same issue with the latest 1.3.4 release even with small text portions. The issue could be easily reproduced in the demo editor on https://quilljs.com/
Why do yo close this issue?

**Comment by jhchen** [comment]
@dzagorovsky It was closed because it was fixed. The commit hash is referenced. If you think there is a regression please fill out a separate issue with all the details requested.

**Comment by dcsaszar** [comment]
#2027

**Comment by skale0181** [comment]
Use following component structure to resolve this => 


import React, { useRef } from "react";
import ReactQuill, { Quill } from "react-quill";
import "react-quill/dist/quill.snow.css";
import { Tooltip } from "antd";
import { UndoOutlined, RedoOutlined } from "@ant-design/icons";
// Override Quill's Clipboard module
const Clipboard = Quill.import("modules/clipboard");
class CustomClipboard extends Clipboard {
  onPaste(e) {
    e.preventDefault(); // Prevent the default paste handling
    // Capture the scroll position before any changes
    const scrollPos = this.quill.root.scrollTop;
    const clipboardData = e.clipboardData || window.clipboardData;
    const text = clipboardData.getData("text/plain");
    const range = this.quill.getSelection();
    if (range) {
      // Insert text manually at the cursor's position
      this.quill.insertText(range.index, text);
      // Move the cursor to the end of the inserted text
      this.quill.setSelection(range.index + text.length, 0);
    }
    // Restore the scroll position right after insertion
    setTimeout(() => {
      this.quill.root.scrollTop = scrollPos;
    }, 0);
  }
}
// Register the custom clipboard module
Quill.register("modules/clipboard", CustomClipboard, true);


const MyEditor = ({
  initialContent,
  onChange,
  toolbarId,
  readOnly = false,
  error = "",
}) => {
  const quillRef = useRef(null);
  const handleUndo = () => {
    const editor = quillRef.current.getEditor();
    editor.history.undo();
    editor.focus(); // Ensure the editor remains focused
  };

  const handleRedo = () => {
    const editor = quillRef.current.getEditor();
    editor.history.redo();
    editor.focus(); // Ensure the editor remains focused
  };

  const modules = {
    toolbar: {
      container: `#${toolbarId}`,
    },
    history: {
      delay: 1000,
      maxStack: 50, // Adjust maxStack as needed
      userOnly: true,
    },
    // No need to add an onPaste handler here,
    // since our custom Clipboard module handles paste events.
  };

  return (
    <>
      <div id={toolbarId}>
      {/* Header dropdown */}
        <select className="ql-header" defaultValue="">
          <option value="1" />
          <option value="2" />
          <option value="3" />
          <option value="4" />
          <option value="5" />
          <option value="6" />
          <option selected />
        </select>
        {/* Bold */}
        <Tooltip title="Bold">
          <button className="ql-bold" />
        </Tooltip>
        {/* Italic */}
        <Tooltip title="Italic">
          <button className="ql-italic" />
        </Tooltip>
        {/* Underline */}
        <Tooltip title="Underline">
          <button className="ql-underline" />
        </Tooltip>
        {/* Blockquote */}
        <Tooltip title="Blockquote">
          <button className="ql-blockquote" />
        </Tooltip>
        {/* Ordered List */}
        <Tooltip title="Ordered List">
          <button className="ql-list" value="ordered" />
        </Tooltip>
        {/* Bullet List */}
        <Tooltip title="Bullet List">
          <button className="ql-list" value="bullet" />
        </Tooltip>
        {/* Link */}
        <Tooltip title="Link">
          <button className="ql-link" />
        </Tooltip>
        {/* Undo */}
        <Tooltip title="Undo">
          <button className="ql-undo" onClick={handleUndo}>
            <UndoOutlined />
          </button>
        </Tooltip>
        <Tooltip title="Redo">
          <button className="ql-redo" onClick={handleRedo}>
            <RedoOutlined />
          </button>
        </Tooltip>
      </div>

      <ReactQuill
        readOnly={readOnly}
        theme="snow"
        placeholder="Enter your content here..."
        modules={modules}
        value={initialContent}
        onChange={onChange} // Update content on change
        ref={quillRef} // Use ref to access the quill instance
      />

      {error && (
        <span className="text-sm text-red-700 font-normal absolute left-0">
          {error}
        </span>
      )}
    </>
  );
};

export default MyEditor;

**Comment by skale0181** [comment]
Use following component to resolve this issue


```
import React, { useRef } from "react";
import ReactQuill, { Quill } from "react-quill";
import "react-quill/dist/quill.snow.css";
import { Tooltip } from "antd";
import { UndoOutlined, RedoOutlined } from "@ant-design/icons";
// Override Quill's Clipboard module
const Clipboard = Quill.import("modules/clipboard");
class CustomClipboard extends Clipboard {
  onPaste(e) {
    e.preventDefault(); // Prevent the default paste handling
    // Capture the scroll position before any changes
    const scrollPos = this.quill.root.scrollTop;
    const clipboardData = e.clipboardData || window.clipboardData;
    const text = clipboardData.getData("text/plain");
    const range = this.quill.getSelection();
    if (range) {
      // Insert text manually at the cursor's position
      this.quill.insertText(range.index, text);
      // Move the cursor to the end of the inserted text
      this.quill.setSelection(range.index + text.length, 0);
    }
    // Restore the scroll position right after insertion
    setTimeout(() => {
      this.quill.root.scrollTop = scrollPos;
    }, 0);
  }
}
// Register the custom clipboard module
Quill.register("modules/clipboard", CustomClipboard, true);


const MyEditor = ({
  initialContent,
  onChange,
  toolbarId,
  readOnly = false,
  error = "",
}) => {
  const quillRef = useRef(null);
  const handleUndo = () => {
    const editor = quillRef.current.getEditor();
    editor.history.undo();
    editor.focus(); // Ensure the editor remains focused
  };

  const handleRedo = () => {
    const editor = quillRef.current.getEditor();
    editor.history.redo();
    editor.focus(); // Ensure the editor remains focused
  };

  const modules = {
    toolbar: {
      container: `#${toolbarId}`,
    },
    history: {
      delay: 1000,
      maxStack: 50, // Adjust maxStack as needed
      userOnly: true,
    },
    // No need to add an onPaste handler here,
    // since our custom Clipboard module handles paste events.
  };

  return (
    <>
      <div id={toolbarId}>
      {/* Header dropdown */}
        <select className="ql-header" defaultValue="">
          <option value="1" />
          <option value="2" />
          <option value="3" />
          <option value="4" />
          <option value="5" />
          <option value="6" />
          <option selected />
        </select>
        {/* Bold */}
        <Tooltip title="Bold">
          <button className="ql-bold" />
        </Tooltip>
        {/* Italic */}
        <Tooltip title="Italic">
          <button className="ql-italic" />
        </Tooltip>
        {/* Underline */}
        <Tooltip title="Underline">
          <button className="ql-underline" />
        </Tooltip>
        {/* Blockquote */}
        <Tooltip title="Blockquote">
          <button className="ql-blockquote" />
        </Tooltip>
        {/* Ordered List */}
        <Tooltip title="Ordered List">
          <button className="ql-list" value="ordered" />
        </Tooltip>
        {/* Bullet List */}
        <Tooltip title="Bullet List">
          <button className="ql-list" value="bullet" />
        </Tooltip>
        {/* Link */}
        <Tooltip title="Link">
          <button className="ql-link" />
        </Tooltip>
        {/* Undo */}
        <Tooltip title="Undo">
          <button className="ql-undo" onClick={handleUndo}>
            <UndoOutlined />
          </button>
        </Tooltip>
        <Tooltip title="Redo">
          <button className="ql-redo" onClick={handleRedo}>
            <RedoOutlined />
          </button>
        </Tooltip>
      </div>

      <ReactQuill
        readOnly={readOnly}
        theme="snow"
        placeholder="Enter your content here..."
        modules={modules}
        value={initialContent}
        onChange={onChange} // Update content on change
        ref={quillRef} // Use ref to access the quill instance
      />

      {error && (
        <span className="text-sm text-red-700 font-normal absolute left-0">
          {error}
        </span>
      )}
    </>
  );
};

export default MyEditor;

```
