### ISSUE TITLE
Scrolling with two editors causes them to be linked and affecting z-index's

### ISSUE THREAD

**Issue by ggJSC** [quilljs/quill#1430]
I've got two editors where one is a notebook of sorts and the other is a sticky notes type `div` where it has the style `position: sticky`. The sticky notes div maintains its fixed position until the notepad's editor, _not the toolbar which is also sticky'd_ top margin matches up with the sticky notes editor. Even when I define one editor without a `scrollingContainer` paramemeter and one with a parent as the `scrollingContainer` the error persists.

**Comment by jhchen** [comment]
You might have more luck getting help by following the suggestions when you clicked "New Issue" such as providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve).
