### ISSUE TITLE
Error: container required for toolbar

### ISSUE THREAD

**Issue by hoppities** [quilljs/quill#1431]
When working with Quill on my local machine, everything works fine, but when I deploy to our staging environment, Quill breaks. It never seems to create the editor, and then it throws the following error:

Error: container required for toolbar.

We're using a directive to create Quill, so we pass elem to Quill to create a new instance. The element is there when I log it, but it doesn't seem to see the toolbar, and when I check the html in staging, the toolbar element does not exist.

**Expected behavior**: Quill will create the editor and the toolbar

**Actual behavior**: Quill never creates the editor and throws this error: "Error: container required for toolbar."

**Platforms**: Production environment, minified code.

Include browser, operating system and respective versions: Chrome, Windows

**Version**: 1.2.4

**UPDATE: ** The error happens when the code is minified.

**Comment by benbro** [comment]
Try to fork the [CodePen](http://codepen.io/quill/pen/KzZqZx) and reproduce your issue there.
If it doesn't happen in the CodePen, it's something wrong on your side.

**Comment by hoppities** [comment]
I ended up figuring it out. The issue had to do with the order in which the element was created by the directive and when quill tried to attach itself to that element.

**Comment by benbro** [comment]
Good.

**Comment by sagarchoudhary96** [comment]
@hoppities how did you fixed this > i'm facing same issue in react project.

**Comment by SharanReddi** [comment]
@sagarchoudhary96 @hoppities  were you able to figure out the solution to this issue ?. can you please share the solution
