### ISSUE TITLE
Win10: Typing Vietnamese results in Quill error

### ISSUE THREAD

**Issue by haugstrup** [quilljs/quill#1435]
When typing using Vietnamese keyboard on Windows 10 you can type sequences that results in Quill starting to throw errors on every text change.

I'm happy to spend time debugging this, but I don't know where to start. What does the error mean and how would a text addition result in a "non-document" delta?

**Steps for Reproduction**

1. Install Vietnamese keyboard: http://typingvietnamese.blogspot.com/p/typing-vietnamese-for-windows.html
2. Visit playground: https://quilljs.com/playground/
2. Hit the keys 4, 5, 6, 7 in sequence

**Expected behavior**:
Nothing happens.

**Actual behavior**:

`Error: diff() called with non-document`

**Platforms**:

Windows 10, Chrome.

**Version**:

1.2.4

**Comment by jhchen** [comment]
https://github.com/quilljs/quill/commit/0e7a10c6ad865fa9075636787b1dac09d767bf06 appears to have fixed this as well.

To answer your question though, Deltas can be made of inserts, retains, and deletes, but only those that are made up of solely inserts are document deltas.
