### ISSUE TITLE
[Safari macOS Sierra] Korean character composition not work correctly

### ISSUE THREAD

**Issue by silverprize** [quilljs/quill#1437]
[Describe the issue]

**Steps for Reproduction**

1. Visit quilljs.com
2. Set caret position at the beginning of the line
3. Set Korean ime
4. Do typing 가나다라

**Expected behavior**:
가나다라

**Actual behavior**:
ㄱㅏ나다라
![edyzaebw2h](https://cloud.githubusercontent.com/assets/860087/25551902/5f060874-2cc7-11e7-8eaa-f3e0676bd9f8.gif)

**Platforms**:
macOS sierra 10.12.4(16E195)
Safari 10.1(12603.1.30.0.34)

**Version**:
1.2.4

**Comment by mave99a** [comment]
Same for Chinese. Looks like it always take the first character entered. 

Expected behavior:
测试

Actual behavior:
c测试

c was entered，because 'c' is the first char entered for Chinese Pin Yin IME.

**Comment by transtone** [comment]
https://github.com/quilljs/quill/issues/1429

**Comment by kidlj** [comment]
Same problem like @mave99a above, with Windows 10/ Chrome 60/ Microsoft Pin Yin IME

**Comment by hackftz** [comment]
so how to fix it ? I try to upadte version to 1.3.6, but the question still exist.
