### ISSUE TITLE
Feature Request: Better placeholders

### ISSUE THREAD

**Issue by krabbypattified** [quilljs/quill#1443]
The current `placeholder` function behaves unexpectedly and doesn't have any features.

For instance, if I do `quill.format('header', '2');` the placeholder disappears. (this might be a bug)

Also I want the placeholder to inherit the font style of the editor's current format, except be a lighter color.
(i.e. if I loaded up the editor and did `quill.format('header', '3');`, I would expect the placeholder to be a light gray `h3`)

More importantly, I have a feature request.
I'd like to have the ability to replicate how Medium.com has several placeholders (See https://medium.com/new-story). I hope this could be achieved with some manipulation of the `:before` pseudo-selector.

The api would look like `quill.format('placeholder', 'Title');`
Or it could look like `placeholder: '<h1>Title</h1><p>Compose an epic...</p>',`

If this doesn't seem like it'd be used frequently, perhaps it can become a module.

Browser: Chrome 57
OS: Mac OS Sierra
Quill version 1.2.4

**Comment by benbro** [comment]
The placeholder is [styled with css](https://github.com/quilljs/quill/blob/develop/assets/core.styl#L170)
You can override it with your custom style.

**Comment by krabbypattified** [comment]
What about this:

"For instance, if I do quill.format('header', '2'); the placeholder disappears. (this might be a bug)"

Do I need to file another issue for you to address this?

**Comment by jhchen** [comment]
The opposite behavior has been reported as a bug (not removing the placeholder when the line formatting has changed) so this is working as designed. Sounds like the other concern has been addressed as well.

You can modify the text with `:before` css but an easier way might be to modify the `data-placeholder` attribute through DOM APIs. Inspect the placeholder text with the browser developer console to see more on how this works.

In the future please follow the [Contributing](https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md) guide when submitting a bug report or feature request.
