### ISSUE TITLE
issues in bootstrap modal

### ISSUE THREAD

**Issue by kessanro** [quilljs/quill#1446]
[Describe the issue]

**Steps for Reproduction**

1. have a bootstrap modal
2. use a button and the rich text editor
3. place alot of stuff on the toolbar
**Expected behavior**:
meant to ajust to all the buttons and items in the modal
**Actual behavior**:
moves all the buttons and stuff off the modal
screenshot:
![image](https://cloud.githubusercontent.com/assets/21036927/25775601/ca70c4f8-32a0-11e7-8cfb-5fa99373176c.png)

**Platforms**:
firefox

**Version**:
latest
1.2.4

**Comment by kessanro** [comment]
bt i did use a theme for bootstrap and i tested it without the theme still the same result

**Comment by benbro** [comment]
Quill doesn't control the DONE and POST buttons in your screenshot.
It's a problem with your CSS, not related to Quill.
