### ISSUE TITLE
Pasting content into long editor scrolls to top and stays.

### ISSUE THREAD

**Issue by ggJSC** [quilljs/quill#1448]
Similar to issues I found from 2014, there are issues with pasting content in the editor after it has gotten to be long enough that the top of the editor is beyond the screen. 

Same movement and scrolling occurs when the editor focuses programmatically and it's currently scrolled down. I have an eventListener for the container where `ql-editor` is a child and if I click on the contained and not the editor itself, my code calls `editor.focus()`. If the editor has been scrolled down at all focusing causes the view to jump to the top.

**Comment by jhchen** [comment]
Please use the issue template. It is not a suggestion.

https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md
