### ISSUE TITLE
Mobile Device Text Formatting (Adding Bold / Italics / Changing Fonts...)

### ISSUE THREAD

**Issue by jbhorsewriter7** [quilljs/quill#1450]
Has anyone tried using this with a mobile device (I have this issue in iOS and on Android).

Whenever I try and format the text in my box - it seems to work the first time (if my selection includes the first word) but from then on NONE of my formatting changes are listened to.

**Steps for Reproduction**

1) Launch a quill editor on a mobile device (Android seems to be worse than iOS but either are adequate)

2) Type a sentence.

3) Select the first word in the sentence and choose to make it BOLD.

4) Select the same word that you just made bold and now make it ITALIC as well.

The word remains bold.  Try any other formatting changes... the word doesn't change.

**Expected behavior**:

I would like the fonts and formatting to be updated.

**Actual behavior**:

The formatting seems to not "hear" what I have specified.  I have alerted the value of the "get selection" function and noticed that the first time (when it worked) it returns values 0 (meaning it's the beginning of my string) and 5 (meaning it was a five-letter word).

From then on it returns 11 (?) and 0 (meaning that nothing is selected in my string)... which is strange.

**Platforms**:

iOS safari.  Android Chrome... etc.

**Version**:  NEWEST

Run `Quill.version` to find out

**Comment by jbhorsewriter7** [comment]
Has anyone else run into this?

@jhchen do you have any ideas or further tests that I could run?

**Comment by bjentsch** [comment]
I can confirm this behaviour.

**Comment by jhchen** [comment]
Does this occur on Quill's website quilljs.com, particularly the standalone editors for example https://quilljs.com/standalone/snow? I'm not able to reproduce on a Safari 10 on iPad.

**Comment by bjentsch** [comment]
My steps for reproducing:

1. I inserted some paragraphs with text by typing on the keyboard.
2. I highlighted the first word in the third paragraph and formatted it to bold, it worked.
3. I highlighted the first word in the first paragraph and formatted it to bold - it didn't work.
4. Also, formatting other selections now didn't work as expected.
5. I tapped the first word, autocorrect told me it had no suggestions for it. I pressed bold, it worked.

I noticed that after "selecting" a word with the Apple autocorrect function just by tapping it, formatting would always work. When selecting a word with the "select" functionality, also when expanding the selection, there's a high chance that formatting won't work. After trying to format, Safari resets the caret to some point that appears to be the center of my previous selection.

![ipad_quill_1](https://cloud.githubusercontent.com/assets/2751045/26192119/c66f8c72-3bb0-11e7-8d18-ac0e264cd03c.png)
![ipad_quill_2](https://cloud.githubusercontent.com/assets/2751045/26192120/c66ffec8-3bb0-11e7-880e-6c1924ab0f40.png)
![ipad_quill_3](https://cloud.githubusercontent.com/assets/2751045/26192121/c671ddec-3bb0-11e7-816b-b788b2f26186.png)

**Comment by jbhorsewriter7** [comment]
I've done it with Safari 10 in iPad.  On iPhone.  And on android...

Moved on to CKEditor - it already works on mobile devices.

**Comment by homerlex** [comment]
I've experienced formatting issues as well.  I'm on iOS 10 with an external keyboard.  This is my repro:

- Hit https://quilljs.com/standalone/snow
- Type: "This is a test"
- Using the arrow keys on the keyboard move the cursor to the work "This" and shift+arrow to highlight the word "This".
- Tap the "B" (bold) button in the toolbar and the word turns bold.
- Us the arrow keys to get the cursor to the word "is"
- shift+arrow to select the word "is"
- Tap the "I" (italic) button in the toolbar - at this point the selection moves back to the word "This" and makes it italic.  The word "is" should have been made italic.

Here are some screen shots:

Highlight "This":
![iosquill1](https://cloud.githubusercontent.com/assets/296630/26314278/7e5b5730-3edb-11e7-9446-7c4d12a016b4.png)

Hit B to make it bold:
![iosquill1b](https://cloud.githubusercontent.com/assets/296630/26314299/9019a364-3edb-11e7-8b73-cbb2a74adef5.png)

Highlight "is":
![iosquill2](https://cloud.githubusercontent.com/assets/296630/26314313/9b27ee6e-3edb-11e7-8b79-e4b39fdb824f.png)

Hit "I" and it changes selection to "This" and makes it italic:
![iosquill3](https://cloud.githubusercontent.com/assets/296630/26314336/ae8e71b2-3edb-11e7-80c4-991a67557bdd.png)

**Comment by bjentsch** [comment]
Any news on this?

**Comment by jhchen** [comment]
I've never been able to repro on my iPad but can you guys try on the latest version of Quill 1.3.0? Some selection code was changed that fixed some other mobile bugs.

**Comment by homerlex** [comment]
FYI - I tested my repro case using  https://quilljs.com/standalone/snow (which now uses Quill 1.3.0) and could not reproduce the problem.  I'll have to get this version into our application and test there as well.

**Comment by linyize** [comment]
@jbhorsewriter7  I started another project https://github.com/hivecms/quillview. QuillView is to display quill format on iOS native views. Your comments are welcome.
