### ISSUE TITLE
How can I get styled HTML from Quill for display in an email?

### ISSUE THREAD

**Issue by crowdwave** [quilljs/quill#1451]
Quill outputs nice plain HTML.

But when I display this in an HTML email it looks rather clunky because it is effectively unstyled.

It would be good if it looked similar to the way it is displayed in the Quill editor control.

I've seen this link which maybe seems to be talking about the same topic?  https://quilljs.com/playground/#class-vs-inline-style

So I modify my code to include this:

```
      let AlignStyle = Quill.import('attributors/style/align')
      let BackgroundStyle = Quill.import('attributors/style/background')
      let ColorStyle = Quill.import('attributors/style/color')
      let DirectionStyle = Quill.import('attributors/style/direction')
      let FontStyle = Quill.import('attributors/style/font')
      let SizeStyle = Quill.import('attributors/style/size')    

      Quill.register(AlignStyle, true);
      Quill.register(BackgroundStyle, true);
      Quill.register(ColorStyle, true);
      Quill.register(DirectionStyle, true);
      Quill.register(FontStyle, true);
      Quill.register(SizeStyle, true);

```

There's no errors and it seems to run OK, but the output from Quill is precisely the same.

Is there mean to be some way to render Quill output in a manner similar to the editor control display?

Is there meant to be a way that I can get the HTML out in a way suitable for display in an HTML email which requires inline styling?

thanks

**Comment by benbro** [comment]
In this [CodePen](http://codepen.io/anon/pen/LyQxXW) the initial HTML and new elements has background, color and size styles.

**Comment by andlcool** [comment]
Great, the example does work as intended. I am also looking to get the html output to be sent as email and requires all styling to be inline.

How do we get a list of items that we can configure to be inline? The example shows for size only and I am searching for the whole list.

Thanks.

**Comment by drego** [comment]
I'm having the exact same problem. There's some features which I don't know how to force them to use inline styling, like:
- font family
- indentation
- lists
- alignment
- code-block's
- blockquote

**Comment by BilalHalayqa** [comment]
I still have the same issue, any solution or workaround for this ?

**Comment by dschreij** [comment]
Same issue here. The documentation on this particular topic is very sparse. Where can we find a list of attributors that we can set to inline?

**Comment by benbro** [comment]
You can find the list of formats in [docs](https://quilljs.com/docs/formats/) and [code](https://github.com/quilljs/quill/tree/develop/formats).
The [font attributor](https://github.com/quilljs/quill/blob/develop/formats/font.js) for example has FontStyle FontClass.

**Comment by dschreij** [comment]
Thanks for that!

**Comment by UprightBeats** [comment]
This solution doesn't work for me. What is worse - after I added this imports the editor stopped working itself. Does anyone have the working code?

**Comment by Finesse** [comment]
How to do only for a single `Quill` instance, not for a whole `Quill` class?

**Comment by pppglowacki** [comment]
Did anyone get this working? I included the imports and then registered them but in the Quill editor I still get classes. Any help would be appreciated.

**Comment by kaziupir** [comment]
Did you create custom toolbar element?

**Comment by inzinga** [comment]
For those that might stumble across this in the future, here is what I added to enable Quill styling attributes to be inline.  I needed inline style attributes so that Quill created documents sent via email would maintain the formatting defined in Quill.

First, using `console.log(Quill.imports);` (discovered when reading [this Quill documentation page](https://quilljs.com/guides/how-to-customize-quill)), I was able to list all the imported attributors Quill imported.

Adding the following for all of those listed by the logging of `Quill.imports`, the result was inline html styles rather than Quill classes.

```
        // configure Quill to use inline styles so the email's format properly
        var DirectionAttribute = Quill.import('attributors/attribute/direction');
        Quill.register(DirectionAttribute,true);

        var AlignClass = Quill.import('attributors/class/align');
        Quill.register(AlignClass,true);

        var BackgroundClass = Quill.import('attributors/class/background');
        Quill.register(BackgroundClass,true);

        var ColorClass = Quill.import('attributors/class/color');
        Quill.register(ColorClass,true);

        var DirectionClass = Quill.import('attributors/class/direction');
        Quill.register(DirectionClass,true);

        var FontClass = Quill.import('attributors/class/font');
        Quill.register(FontClass,true);

        var SizeClass = Quill.import('attributors/class/size');
        Quill.register(SizeClass,true);

        var AlignStyle = Quill.import('attributors/style/align');
        Quill.register(AlignStyle,true);

        var BackgroundStyle = Quill.import('attributors/style/background');
        Quill.register(BackgroundStyle,true);

        var ColorStyle = Quill.import('attributors/style/color');
        Quill.register(ColorStyle,true);

        var DirectionStyle = Quill.import('attributors/style/direction');
        Quill.register(DirectionStyle,true);

        var FontStyle = Quill.import('attributors/style/font');
        Quill.register(FontStyle,true);

        var SizeStyle = Quill.import('attributors/style/size');
        Quill.register(SizeStyle,true);

        // create new Quill instance here...
```

**Comment by benwinding** [comment]
@inzinga thankyou!! Working perfectly

**Comment by chuckle123** [comment]
This comment describes how to specify indentation of lists inline...
https://github.com/quilljs/quill/issues/1274#issuecomment-303619625

**Comment by weirdyang** [comment]
how do I implement this in a browser?

**Comment by weirdyang** [comment]
> how do I implement this in a browser?

for those who are still struggling with it; https://codepen.io/helloCaptMomo/pen/WNdGOJB
