### ISSUE TITLE
Truly Disable Disabled Formats?

### ISSUE THREAD

**Issue by saw** [quilljs/quill#1452]
I've noticed that a registered blot is not truly a no-op in an editor where that blot is disabled via formats, and I'm wondering if this is the ideal behavior.

We've had a few issues lately where a blockEmbed that is defined by a tag (no class) results in the contents being empty when pasted where that blot is disabled. Digging in I determined that this happens because matchBlot is called for that element, even though the format is disabled. 

This [part](https://github.com/quilljs/quill/blob/develop/modules/clipboard.js#L240-L243) specifically checks to see if the `value` was null, if it was not null it creates the Delta which is ultimately discarded when `updateContents` is called. 

For example, if I had an embed that contained html that looks like this:

```
class MyEmbed extends BlockEmbed {

  static create(value) {
    let node = super.create(value);
    node.innerHTML = `<div>I love ${value}</div>`;
    return node;
  }

  static value(domNode) {
    return 'bananas';
  }
}

MyEmbed.blotName = 'section';
MyEmbed.tagName = 'SECTION';
```

If I later copy and paste some html that looks like this:
```
<section><div>I love bananas</div></section>
```
into an editor with `MyEmbed` registered, but not enabled, the result will be a blank editor. In the case of a single tag embed like `<image>` make sense and is the desired behavior, but in the other case it seems like the editor should be have as if the blot was never registered if it is disabled.

**Comment by jhchen** [comment]
Can you please fill out the Steps for Reproduction, Expected Behavior, and Actual Behavior. It is very difficult to follow the pronouns used especially in the last paragraph.
