### ISSUE TITLE
Custom blots/embed throws `Cannot insert block into inline` on drag and drop

### ISSUE THREAD

**Issue by neversun** [quilljs/quill#1455]
I try to implement a `blot/embed` with structure of 
```html
<div>
    <img src="...">
</div>
```
I also added a click-to-select handler to this blot, which selects the complete structure. Drag and drop works (at best **once**).
It does work if you drop the image at the very end of the line. But then all information of blot-structure is lost. Just plain `<img src="...">` left.

**Steps for Reproduction**

1. Visit http://codepen.io/neversun/pen/GmGGgG?editors=1010
2. Enter some text `foooooooooooo` in the first line. Press Enter/newline
3. Click `Insert Img`
4. **Click on the img** to select it. 
5. Drag the img in the middle of `foooooooooooo`

**Expected behavior**:
The line gets split where img was dropped. 3 Lines: first line with text left of drop, middle line with img, the third line with rest of text. 
**Actual behavior**:
As _expected_ but with error `[Parchment] Cannot insert block into inline`

**Platforms**:
Chrome 57, Windows 10
Vivaldi 1.10.838.7, Mac OS 10.12.4

**Version**: 1.2.4

**Comment by matthiasg** [comment]
Dragging right away will duplicate the image, selecting first (as described in step 4) will indeed cause this issue (Chrome Version 58.0.3029.110 (64-bit))

**Comment by DmitrySkripkin** [comment]
No errors on Google Chrome Version 58.0.3029.96 (64-bit) Ubuntu 16.04.

That's not a Quill bug. It's browser regular behavior. I had same case. So my realization of D&D looks like that:
1. I disable any native default D&D for element (ex. `<img src="..." draggable="false" />`). Then add `draggable="true"` to root element of my custom blot.
2. Then I listen to `dragstart` event to add blot data to event `dataTransfer`:
```
// I know code is useless without context but
node.addEventListener('dragstart', function(e) {
  e.dataTransfer.effectAllowed = 'move';
  e.dataTransfer.setData('blot', JSON.stringify(data));
});
```
3. Then I handle drop and create a new embed with `insertEmbed` and data I passed. And also remove original blot.

You have to make your own realization. I believe Quill won't have any build in D&D feature - it requires too much customization for each individual case.
