### ISSUE TITLE
How to load table tag into Quill ?

### ISSUE THREAD

**Issue by despreju** [quilljs/quill#1459]
Hello,

I need to load an HTML content with a table into my editor, the problem is that Quill can't understand it.

HTML content loaded into Quill : 
 ```
<table style="width:100%">
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Age</th>
  </tr>
  <tr>
    <td>Jill</td>
    <td>Smith</td>
    <td>50</td>
  </tr>
  <tr>
    <td>Eve</td>
    <td>Jackson</td>
    <td>94</td>
  </tr>
</table> 
```

Quill transform it : 
`<p>FirstnameLastnameAgeJillSmith50EveJackson94</p>`

I have this problem on all browsers, and Im using Quill 1.2.4.
I search and found a lot of issue about how to add table, but it's not my kind of problem here ...

Any ideas guys ?

**Comment by benbro** [comment]
Discussion about table support: https://github.com/quilljs/quill/issues/117

**Comment by KrisMerckx** [comment]
Put it on your front page: "NO TABLE SUPPORT!"
