### ISSUE TITLE
Creating a new line on android firefox does not move the caret position to the new line

### ISSUE THREAD

**Issue by simonsandglaz** [quilljs/quill#146]
Tested on Android Firefox v30.0

To reproduce.
1. Open the demo http://quilljs.com/examples/
2. Tap the editor anywhere on a line
3. Press enter

The caret position will not consistently move to the newly created line. It will sometimes move to the middle of the following line, or stay at the previous caret position.

**Comment by jhchen** [comment]
This is working in the latest Android 6.0.1 + Firefox 46.
