### ISSUE TITLE
Google Input Tools not working with QuillJS

### ISSUE THREAD

**Issue by cksachdev** [quilljs/quill#1462]
I have Google Input Tools installed in the browser, which allows to type in many different languages.
![image](https://cloud.githubusercontent.com/assets/37770/26236472/20e244d2-3c8e-11e7-95ba-081a623dca5b.png)
https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab
It works with any other input but doesn't seem to work with QuillJS. I have tried it on "Playground" as well as using it locally. 
I need to make a choice for a library and QuillJS looks promising, but Google Input Tools not working is a blocker for me. 

Let me know if there is a workaround available.

**Comment by benbro** [comment]
Please provide all the requested info in the issue template.

What does it mean that it's not working?

**Comment by benbro** [comment]
Did you try to report your issue to the extension developers?

**Comment by cksachdev** [comment]
@benbro Google Input Tools work with all other inputs, even on the github comments. It may be related to the implementation of quilljs.

**Comment by benbro** [comment]
https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md

**Comment by YingbingGit** [comment]
I have tried, it works
