### ISSUE TITLE
IE11 & Edge - cursor glitch if font is selected before editing starts

### ISSUE THREAD

**Issue by lerayne** [quilljs/quill#1463]
[Describe the issue]

**Steps for Reproduction**

1. Go to https://codepen.io/anon/pen/xdyQdr with IE (tried edge and IE11)
2. Place cursor in quill's input field
3. Start typing

This bug is related to this line: `quill.format('font', 'sans-serif')`
The same happens if I don't select the font programmatically, but select the font with UI before starting input

**Expected behavior**:

All input symbols appear in correct sequence from first to last. Cursor is placed after the last symbol.
Example: abcde|

**Actual behavior**:

First input symbol is displayed the last and it's being placed _after_ the cursor
Example: bcde|a

**Platforms**:

IE11, MS Edge

**Version**:

1.2.4

**Comment by benbro** [comment]
I can reproduce with bold in the official codepen:
1. Visit http://codepen.io/anon/pen/xdQxrr
2. Click on the editor (don't just start typing).
3. Type 'test'.

Expected behavior:
test

Actual behavior:
estt

Platforms:
IE 11, Windows 7

Version:
1.2.4
