### ISSUE TITLE
Quill Port on iOS With Native Toolbar

### ISSUE THREAD

**Issue by saggarwal92** [quilljs/quill#1464]
Hello Everyone, 
this is not an issue but I have started the porting of QuillJS on iOS with Native Toolbar. You can view the github project here: https://github.com/saggarwal92/iOSQuillEditor

**Comment by jhchen** [comment]
Thanks!

**Comment by joshoconnor89** [comment]
@saggarwal92 please update your quill.js to the most recent release.  You cant do several formats such as subscript, superscript, etc. b/c your version does not support it.  Otherwise thank you for your help it is appreciated

**Comment by saggarwal92** [comment]
Thank you for informing me @joshoconnor89  and Thanks @jhchen 
I have updated quill.js and new one gives a pretty much feel to the native toolbar on iPhone. I hope if you won't mind adding a link for the native toolbar quill editor: https://github.com/saggarwal92/iOSQuillEditor in your Readme.md

Thanks,
Shubham

**Comment by linyize** [comment]
Great job! @joshoconnor89 

I started another project https://github.com/hivecms/quillview. QuillView is to display quill format  on iOS native views. Your comments are welcome.
