### ISSUE TITLE
can't create multiline `blockquote` with `p` inside with parchment and blot.

### ISSUE THREAD

**Issue by liqites** [quilljs/quill#1465]
I tried to create a multiline blockquote. like below:

```html
<blockquote>
    <p>This</p>
    <p>is</p>
    <p>a</p>
    <p>blockquote</p>
</blockquote>
```

So, I created a new `block` called `BlockquoteItem`, and a `container` called `BlockquoteContainer`, which encouraged by `fromats/list`.

Here are the codes for the multiline blockquote:

```js
var Parchment = Quill.import('parchment');
var Block = Quill.import('blots/block');
var Container = Quill.import('blots/container');

class BlockquoteItem extends Block {
  ......
}

BlockquoteItem.blotName = 'blockquote-item';
BlockquoteItem.tagName = 'P';

class BlockquoteContainer extends Container {
  ......
}
BlockquoteContainer.blotName = 'blockquote-container';
BlockquoteContainer.tagName = 'blockqupte';
BlockquoteContainer.scope = Parchment.Scope.Block_BLOT;
BlockquoteContainer.defaultChild = 'blockquote-item';
BlockquoteContainer.allowedChildren = [BlockquoteItem];

Quill.register(BlockquoteItem);
Quill.register(BlockquoteContainer);
```

Now the problems is, the domNode `p` (not in the tag `<blockquote>` ) is recognized as `BlockquoteItem` not `Block`, and leading some problems when editing.

**Am I mis-using the parchment and blot?**

**Steps for Reproduction**

1. Visit  [jsfiddle.net](https://jsfiddle.net/teslalee/3k03y4gm/8/)

**Expected behavior**:
tag `P` not inside `blockquote` is recognized as `Blokc` not `BlockquoteItem`

**Actual behavior**:

tag `P` is reconized as `BlockquoteItem`

**Platforms**:

Include browser, operating system and respective versions
Chrome Version 58.0.3029.110 (64-bit)
macOS Version 10.12.5(16F71b)

**Version**:

1.2.4

**Comment by benjismith** [comment]
I've been having the same problem lately. I need to redesign my handling of blockquotes to allow nested paragraphs. Can you provide any guidance for how to do that?

**Comment by lwyj123** [comment]
same problem

**Comment by paullaffitte** [comment]
Same issue

**Comment by nikhil-ponduri** [comment]
hey @liqites  did you find any solution for this.I am having the same issue. It would be great if you could help me.

**Comment by luin** [comment]
You can try adding `className` to `BlockquoteItem` so Quill should be able to differentiate it from normal blocks.
