### ISSUE TITLE
The first letter of the Chinese word will be additionally inserted when using Chinese input

### ISSUE THREAD

**Issue by HuMonkey** [quilljs/quill#1466]
[Describe the issue]
When i start typing in a new line using Chinese input, the first letter of the Chinese word will be additionally inserted to the editor. I was using the newest version of Sougou input.

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**:

**Actual behavior**:

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by jhchen** [comment]
https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md
