### ISSUE TITLE
`getBounds()` returns incorrect value for extra-BMP Unicode characters

### ISSUE THREAD

**Issue by meantime** [quilljs/quill#1467]
For BMP characters the `getBounds(index, offset)` function works as expected. For extra-BMP characters it returns only the bounds of the first unit of the composed character.

**Steps for Reproduction**

1. Add the character `U+1F607 (SMILING FACE WITH HALO)` to a Quill document
2. call `.getBounds()` on that character

**Expected behavior**:
I expected to get bounds for the entire printable area of the character.

**Actual behavior**:
I got bounds equal to just the leading half. (screenshot attached)

**Platforms**:
Fails on Safari 10.1.1
Works correctly on Chrome 58
Tested on macOS 10.12.5

**Version**:

Run `Quill.version` to find out
It just said "dev"
<img width="178" alt="getbounds issue" src="https://cloud.githubusercontent.com/assets/283153/26332037/2035d6c0-3f09-11e7-9003-6cd95e5cac0a.png">

**Comment by jhchen** [comment]
The inconsistency is an issue but I would actually say Safari's behavior is correct since extra-BMP characters are length 2 in Javascript?
