### ISSUE TITLE
cant bind multiple binding keyboard event 

### ISSUE THREAD

**Issue by f3ltron** [quilljs/quill#1469]
Hello i am using the 1.2.4 version of quill (the last one ?)

Its fkin awesome thannks for the work !

But i actually facing a problem. 

```
  var bindings = {
    custom: {
      key: 'backspace',
      handler: function(range, context){
        var possible = variablesTab.find(function(elem){
          return range.index > elem.start && range.index <= elem.end;
        });
        if(possible){
          console.log(possible);
          console.log(range);
          console.log(possible);
          quill.deleteText(possible.start, possible.end);
        }
        else{
          if(range.index === 1){
            quill.deleteText(0, 1);
          }else{
            quill.deleteText(range.index - 1, range.index - 1);
          }
        }
      }
    }
  };
```
I would like to bind more than just one key keyboard. But i dont know hot do this when i trying an array its not working.

Maybe i just miss understand something on the doc...

Thanks a lot for the answear and again great job :)

**Comment by benbro** [comment]
There is an [example](https://quilljs.com/docs/modules/keyboard/#configuration) in the docs showing how to add multiple bindings.

Try to fork the [CodePen](https://quilljs.com/playground/), add one keyboard bindings, test it and than add another one.

Github issues are for bugs. If you have a question, please use StackOverflow.

**Comment by f3ltron** [comment]
thanks ye you right thank's a lot
