### ISSUE TITLE
scroll into view function in selections.js does not work if quill is set to auto grow

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#1471]
If quill is set to autogrow, and does not use internal scroll bars the `scrollIntoView` function does not work. It actually makes the page jump to random scroll position. 

I have set my scrollingContainer to be `'body'`

This is because the `scroller.getBoundingClientRect()` value is of the body and if the page is scrolled down from the top, the top value is negative. 

If quill is set to autogrow, what you really want is the inner bounds of the window. 

I have adjusted the code and the following code fixes the problem for me:

```javascript
scrollIntoView(range = this.lastRange) {
    if (range == null) return;
    let bounds = this.getBounds(range.index, range.length);
    if (bounds == null) return;
    let limit = this.scroll.length()-1;
    let [first, ] = this.scroll.line(Math.min(range.index, limit));
    let last = first;
    if (range.length > 0) {
      [last, ] = this.scroll.line(Math.min(range.index + range.length, limit));
    }
    if (first == null || last == null) return;
    let scroller = this.scroll.scrollingContainer;
    // let scrollBounds = scroller.getBoundingClientRect();
    let headerHeight = 65;
    let windowHeight = window.innerHeight - 20;
    if (bounds.top < headerHeight) {
      scroller.scrollTop -= (headerHeight - bounds.top);
    } else if (bounds.bottom > windowHeight) {
      scroller.scrollTop += (bounds.bottom - windowHeight);
    }
  }
```

**Expected behavior**:

The cursor should be scrolled into view. 

**Actual behavior**:

The page seemingly jumps to random scroll position. 

**Platforms**:

Chrome/Mac

**Version**:

1.2.4

**Comment by jhchen** [comment]
What are the steps to reproduce the issue? Perhaps using https://quilljs.com/playground/#autogrow-height as a starting point?

**Comment by sferoze** [comment]
@jhchen try `console.log(scroller.getBoundingClientRect()) ` with default quill, and using body as scrolling container. Paste a lot of text in the editor. Scroll down to middle of page. Start typing near the bottom and as the cursor goes offscreen watch the scroll position jump to incorrect positions. 

This is because `scroller.getBoundingClientRect()` is not a static value getBoundingClientRect returns different values depending on the scroll position. I believe you have written the code with the expectation that `scroller.getBoundingClientRect()` always returns the same values corresponding to the container. But the values change...

**Comment by jhchen** [comment]
There was another issue #1571 where scrollingContainer set to body did not work so I will just add a note in the docs. If this is still not working for you even using a non-body container, please provide specifics in your steps for reproduction and I can take another look.
