### ISSUE TITLE
Infinite loop when using Cloudcall

### ISSUE THREAD

**Issue by patrick172** [quilljs/quill#1473]
Infinite loop when adding <img> tags via chrome extension

**Steps for Reproduction**

1. Install cloudcall chrome plugin https://chrome.cloudcall.com/
2. Visit https://quilljs.com/playground/
3. Type in the editor 1234567890

**Expected behavior**:
none

**Actual behavior**: 
Infinitely appending to the editor section like:

`<img cloudcallclick2call="+441234567890" number="+441234567890" id="telephone_number_0" src="chrome-extension://fgfcgceddeblecdcgjpckjfbnnpkjdad/images/logo.png" class="cloudcall-click-to-call cloudcall-image" clicktitle="Call +441234567890" data-tooltip="Call +441234567890">`

After some time crashes the browser.

**Platforms**:
Windows 7/8/10 with Chrome

**Comment by jhchen** [comment]
There seems to be a compatibility issue with Cloudcall and Quill. Unfortunately as an open source project Quill cannot support every browser extensions that may interact with it, especially commercial ones with specialized usage. Please reach out to their support team to let them know of the incompatibility. If someone from the Cloudcall team would like guidance on how to play more nicely with Quill feel free to comment.
