### ISSUE TITLE
Problem with Quill in bootstrap modal (IE11)

### ISSUE THREAD

**Issue by VadymMakhonin** [quilljs/quill#1474]
**Steps for Reproduction**

1. Visit https://jsfiddle.net/8d1gh7rn/5/
2. Open bootstrap modal
3. Select the whole text using mouse and move cursor out of popup border
4. Press 'delete' btn / type some text / paste text
 
**Expected behavior**:

text is not deleted / changed /pasted

**Actual behavior**:

text should be deleted / changed / pasted

**Platforms**:

IE11

**Version**:

1.2.4

**Comment by jhchen** [comment]
Seems to be working for me in 1.2.6. Can anyone else reproduce?
![ie11](https://user-images.githubusercontent.com/192974/27362123-f4e98072-55e0-11e7-9764-559b2fe7f37c.gif)

**Comment by VadymMakhonin** [comment]
Yes, it's reproduce in 1.2.6.
You just select text and not moving cursor out of popup border.
http://g.recordit.co/MuwJzDj3KV.gif

**Comment by jhchen** [comment]
Still working for me even if I move the mouse out.
![ie11](https://user-images.githubusercontent.com/192974/27558914-92663c6e-5a73-11e7-8240-3ad2ab1aea16.gif)

**Comment by VadymMakhonin** [comment]
You move cursor out of iframe, move cursor out of popup, but stay in iframe where page rendered.

**Comment by jhchen** [comment]
Thanks for the clarification. It looks like Bootstrap is stealing the focus. If you log the active element:

```js
setInterval(function() {
  console.log(document.activeElement);
}, 1000);
```

Perform the drag you described and you can see when it moves outside the modal the focus shifts to some other element. I'm not sure why/where this occurs but Quill does and should allow external code to take focus. You can easily re-focus Quill with `quill.focus()` and text entry will work again.
