### ISSUE TITLE
`Quill.getBounds(range)` returns wrong height for some line styles

### ISSUE THREAD

**Issue by meantime** [quilljs/quill#1476]
Certain line types, such as `code-block:true`, are inserted into the document model as individual lines, but aggregated together as a single element for presentation purposes (e.g. all adjacent `code-block` lines are aggregated together into a single `<pre>` element in the DOM). When `getBounds(range)` is called on a range within one of these aggregate elements the height returned is that of the aggregate element and not of the characters specifically referenced in the range.

**Steps for Reproduction**

1. Load the following Delta into a new Quill instance:
```
[
      {
        "insert": "Object.prototype.getName = function() { "
      },
      {
        "insert": "\n",
        "attributes": {
          "code-block": true
        }
      },
      {
        "insert": "   var funcNameRegex = /function (.{1,})\\(/;"
      },
      {
        "insert": "\n",
        "attributes": {
          "code-block": true
        }
      },
      {
        "insert": "   var results = (funcNameRegex).exec((this).constructor.toString());"
      },
      {
        "insert": "\n",
        "attributes": {
          "code-block": true
        }
      },
      {
        "insert": "   return (results && results.length > 1) ? results[1] : \"\";"
      },
      {
        "insert": "\n",
        "attributes": {
          "code-block": true
        }
      },
      {
        "insert": "};"
      },
      {
        "insert": "\n",
        "attributes": {
          "code-block": true
        }
      },
      {
        "insert": "\n"
      }
]

```
2. call `quillInstance.getBounds(0, 1)`

**Expected behavior**:
I expected the height of the resultant bounds to be the height of just the single character in the range.

**Actual behavior**:
The height returned is that of the entire `<pre>` block wrapping the coalesced lines.

**Platforms**:
macOS 10.12.5
    * Chrome 58
    * Safari 10
    * Did not test IE

![screen shot 2017-05-30 at 3 35 19 pm](https://cloud.githubusercontent.com/assets/283153/26608364/20b33a8c-4550-11e7-97dd-76f8eff81a7a.png)

**Comment by jhchen** [comment]
Apologies for the delay. I've been trying to reproduce this here: https://codepen.io/anon/pen/NgmwBV

It seems to always correctly report the height in Chrome and Safari. What context are you calling `getBounds`?
