### ISSUE TITLE
[Feature] Interactive input - highlight links, replace emoji, create widgets for applications links

### ISSUE THREAD

**Issue by denisoby** [quilljs/quill#1478]
Hello, guys.

First of all thank you for this great app. I'd like you to review my plugin that makes Quill a little bit more functional.

I'd like to use it in web app, but currently editor is missing some features that customers are used to in other online editors.

1. Links in text are not auto highlighted

2. No emoji

3. Replacing links to concrete web applications with custom widgets that contains info about this link, for example link to google sheets may be replaced with sheet icon + sheet name
For example (first found) link
https://docs.google.com/spreadsheets/d/19khEGozqREIoAN6hd440o4qrzS2ADMVokv8G5FWmWSk/edit#gid=488708073
should be replaced with "Supercharge Time Calculator"

4. No possibility to address to other users through "@" sign (not done in this plugin, but possible with the same way)

I'd like to make some kind of standard way to handle such cases. The code is still sometimes buggy and not 100% completed, but the ideas should be clear. I'm new to Quill and would really appreciate if you confirm if I'm going right way, or not.

Thank you very much in advance.

https://github.com/denis-aes/quill-interactive-input

=========================================================================

# Quill Interactive input example

Sample of plugins for quill that automatically highlights links in text, replace smiles in text with emoji.

## Demo
https://jsfiddle.net/ox5ty132/

*Before*
![Before plugin](https://raw.githubusercontent.com/denis-aes/quill-interactive-input/master/demo/0_without_plugin.png)

*After*
![After plugin](https://raw.githubusercontent.com/denis-aes/quill-interactive-input/master/demo/1_with_plugin.png)

The main idea is to automatically detect and customly render specific content to be more user friendly, without changing document delta or with changes in formats.    

In this example - there are three types of such auto replaced content:    
- smiles / emojies replaced with images
- normal links that are highlighted
- google sheets links are replaced with hardcoded possible widget example

**This code is experimental and is not expected for production use at the moment.***

## Run
```bash
npm install
npm run build
```

## Debug run
./node_modules/.bin/webpack-dev-server

open http://localhost:8080 

### License

MIT

**Comment by denis-aes** [comment]
One of the questions I need you support with is how to deal with the length of embedded objects?

From the delta docs - embed should be with length = 1. But in my case - embed are represented in delta with string values. Smiles have at least two chars, and links are also long.
I've rendered them with contenteditable=false, but still has issues with cursor and deleting chars from them. How should I process it, if I don't want to change delta value?
