### ISSUE TITLE
Bug: when writing in RTL mode,  lists with more than 9 items missing a space

### ISSUE THREAD

**Issue by amitm02** [quilljs/quill#1481]
**Steps for Reproduction**

1. Set write direction to RTL
2. Enter a numbered list with more than 9 items

**Expected behavior**:

The content of each item in the list will have separated from the item index.

**Actual behavior**:

Starting with item index 10, there is no separation between the content of the item and the item index. Bug appears in either english or Hebrew fonts. 
[english fonts img](https://www.dropbox.com/s/pkw1uvxr743xhpj/Screenshot%202017-06-02%2009.36.59.png?dl=0)
[hebrew fonts img](https://www.dropbox.com/s/kisln368j4x4kxh/Screenshot%202017-06-02%2009.56.55.png?dl=0)

**Platforms**:
OSx, Chrome v58. 
Include browser, operating system and respective versions

**Version**:
quill@1.2.5'.

**Comment by benbro** [comment]
The RTL style should be the opposite of the LTR style.
https://github.com/quilljs/quill/blob/master/assets/core.styl#L76
This style:
```
li::before
    display: inline-block
    margin-right: LIST_STYLE_MARGIN
    text-align: right
    white-space: nowrap
    width: LIST_STYLE_WIDTH
li:not(.ql-direction-rtl)::before
    margin-left: -1*LIST_STYLE_OUTER_WIDTH
```
Should probably changed to something like:
```
li::before
    display: inline-block
    white-space: nowrap
    width: LIST_STYLE_WIDTH
li.ql-direction-rtl::before
    margin-left: LIST_STYLE_MARGIN
    margin-right: -1*LIST_STYLE_OUTER_WIDTH
    text-align: left
```

I'll test it locally and create a PR.
