### ISSUE TITLE
Multiple editors performance

### ISSUE THREAD

**Issue by DmitrySkripkin** [quilljs/quill#1482]
**What case I have**: multiple editors on a same page (1 - 200 and even more). I have to initialize them all because user can focus any content and start editing. Page performance is not good in this case.

Before I migrate to Quill I used old-fashioned text editor so I could render HTML and do not initialize anything before mouse down. So I have only one editor instance same time.

As I understand I can't render delta without initializing Quill.

Is there any way to make performance better?

**Comment by jhchen** [comment]
You can convert a Delta into HTML. I have not gotten around to writing an official one but there are a several community created projects available on Github. Or you can write your own. Delta is just structured JSON, which is the easiest format there is to process.
