### ISSUE TITLE
Extra space between paragraph and list when pasting.

### ISSUE THREAD

**Issue by stevebeisner** [quilljs/quill#1483]
An extra blank line is inserted when pasting a normal paragraph
followed by a list.

**Steps for Reproduction**

1. Starting with an empty text area insert (by keyboard) a normal paragraph
containing "one", followed by a unordered list containing
"two".

2. The innerHTML is now `<p>one</p><ul><li>two</li></ul>`,
which displays correctly in the editor.

Start again with an empty text area, only this time, instead of
typing, do a programmatic clipboard.dangerouslyPasteHTML to paste
the same HTML (i.e. `<p>one</p><ul><li>two</li></ul>`).
Now it displays in the editor with extra lines, and the innerHTML
is now `<p>one</p><p><br></p><ul><li>two</li></ul><p><br></p>`

**Expected behavior**:

Whether keyboarding or pasting what was earlier keyboarded, the
result should be the same.

**Actual behavior**:

See above, under **Steps for Reproduction**

**Platforms**:

OSX 10.12, Chrome 58

**Version**:

Quill 1.2.4

**Comment by jhchen** [comment]
You can now use a new config in 1.3.0 [`matchVisual`](https://quilljs.com/docs/modules/clipboard/#matchvisual) to disable Quill's visual paste matching which was causing this.

**Comment by drjackson** [comment]
It's not working on ordered lists for me.  The editor is still adding <p><br/></p> before each of them.
