### ISSUE TITLE
Adding attachment to quill editor

### ISSUE THREAD

**Issue by taoHanhNguyen** [quilljs/quill#1484]
Hi,
Is toolbar support attachment? For now you have image but I don't need images, I need all different kinds of files to upload like the upload  button in Gmail. How to I get this work for ng2-quill-editor.

Thanks

**Comment by jhchen** [comment]
https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md

**Comment by cg-deepali** [comment]
[https://content.careergraph.com/webapp/assets/img/cg-webinar_speaker/img-12786174906_1603380063199.jpeg
](url)
