### ISSUE TITLE
Does quill support multi-map upload?

### ISSUE THREAD

**Issue by heyanlong** [quilljs/quill#1487]
I want to upload multiple images to the server at once and show the picture

**Steps for Reproduction**

1. Select multiple images
2. Ajax upload images
3. Insert image url to quill

**Expected behavior**:
Support multi-map uploads based on configuration file
**Actual behavior**:
Not support
**Platforms**:
Any

**Version**:
latest

**Comment by jhchen** [comment]
No this is outside Quill's project scope.

**Comment by bujji1** [comment]
> 
> 
> I want to upload multiple images to the server at once and show the picture
> 
> **Steps for Reproduction**
> 
>     1. Select multiple images
> 
>     2. Ajax upload images
> 
>     3. Insert image url to quill
> 
> 
> **Expected behavior**:
> Support multi-map uploads based on configuration file
> **Actual behavior**:
> Not support
> **Platforms**:
> Any
> 
> **Version**:
> latest

Hello @heyanlong - did you get any solution to select multiple images ? Thank You . I know the drag and drop we can drop more than 1 image , but using the toolbar image Icon I am able to select only one . Thanks for your help

**Comment by Sotatek-TienMong** [comment]
@heyanlong @bujji1 
Try my solution:
<img width="604" alt="Screen Shot 2019-05-31 at 10 33 11 AM" src="https://user-images.githubusercontent.com/48423503/58679930-b7e04100-838f-11e9-85b4-8888f52c9e16.png">
`this.quill` is `this.$refs.myQuillEditor.quill`
