### ISSUE TITLE
setSelection not working

### ISSUE THREAD

**Issue by flozero** [quilljs/quill#1488]
Version : 1.2.4

What my functionnality do. I insert a tag/variable in my quill editor. Like \<Nom> After if you try to copy past or just write in it. It delete what you do with updateContents by creating a new Delta deleting.

codepen:  https://codepen.io/f3ltron/pen/MoYwrz?editors=0011#0

[Describe the issue]

**Steps for Reproduction**

- write \<Nom>
- try to write on it
- copy past some text on it

**Actual behavior**:

When i do this the cursors just go at the last characater position i delete.

**Expected behavior**:

I want to set the cursor selection not on last character i delete but on the last char from my variable. My core function (the quill.on text-change) has all data needed. You can see that with the console.log. 

I tried to manually add a button with a setSelection and its working. But with the updateContents maybe its not working ?

my core functionnality where the delete and the setSelection are

```
        if((check = isInVariable(index, maxValue, options, oldValue))){
          if(delta.ops[1].insert){
            console.log("i am the length of the text add for delete: ",delta.ops[1].insert.length);
            console.log("i am on the index: ", index);
            console.log("i am on delete: ", check);
            quill.updateContents(new Delta().retain(index).delete(delta.ops[1].insert.length));
            quill.setSelection(check.index, 0);
          }
        }
```

Thanks for the help, love your work !

**Comment by benbro** [comment]
Please provide all the info requested in the template.

Try to fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) with a minimal test case that reproduce your issue.

**Comment by f3ltron** [comment]
https://codepen.io/f3ltron/pen/MoYwrz?editors=0011#0

i put all my code in this. But it can't use my variables modules... any ideas i missed?

**Comment by f3ltron** [comment]
it's update @benbro :) thanks for the help

**Comment by benbro** [comment]
I don't understand your description.
Your code example in the codepen is still very complex and you didn't include the info requested in the template.

**Comment by f3ltron** [comment]
you give me hardtime @benbro ^^ sorry if i am not explaing good i trying my best with my sick english.

I update again

**Comment by benbro** [comment]
Answered
