### ISSUE TITLE
How does Header know that it needs to act on <h /> - tags?

### ISSUE THREAD

**Issue by lustoykov** [quilljs/quill#1495]
So I'd like to replace all `<h* />` tags by `<h4 />`

---------

Approach

```
this.Header = Quill.import('formats/header');

class MyHeader extends this.Header {
  // Replace default tagName [H1, ..., H6] with H4 => convert each <h* /> tag to h4
  static tagName = ['H4', 'H4', 'H4', 'H4', 'H4', 'H4'];
  // sets data-value in CSS to 4 (which stands for H4) so that quill knows how to style
  // the toolbar when <h4 /> element is clicked
  static formats(_domNode: Node) {
    return 4;
  }
}

Quill.register('formats/header', MyHeader);
```

This works... question is why? 

How does Quill figure out that the Header is responsible for `<h1 />`  so that it manages to convert them properly if tagNames are only `H4`'s? 

What would be the correct approach to achieve that at all?

**Comment by jhchen** [comment]
Do you just want to replace it when the editor is initialized, or prevent any additions as well (like if the user copies and pastes h1 you want this to become h4)?

**Comment by lustoykov** [comment]
Everything - setConents, copy-paste... etc. I'll also need to generally do major customization for the editor to fit our brand - so general hints would be very much appreciated!!! 

I'd like to understand well what is going on there, since we depend very much on this editor (that is amazing, thanks!), we can even imagine doing PR's.

**Comment by lustoykov** [comment]
OK, now I have a solution that feels more logical, but when I do setConents with h1, it still remains h1 instead of h4. On the other hand, copy-paster works fine (h1 -> h4).

```
 class GFHeader extends this.Header {
      static tagName = ['H1', 'H2', 'H3', 'H4', 'H5', 'H6'];

      static formats(_domNode: Node) {
        return this.tagName.indexOf('H4') + 1;
      }
  }
```

So why `setContent` fails to convert h1 to h4? I'm puzzled.

**Comment by jhchen** [comment]
Thank you for the kind words and apologies for the delay on the followup.

Essentially in formats/header, the tagName specifies all tags that would match the header format. Then the `formats` function tells it specifically the mapping.

I think for your use case the best way would be to overwrite the static [create](https://github.com/quilljs/parchment#blots) function to always create an h4:

```js
let Header = Quill.import('formats/header');
Header.create = function(value) {
  // ignore value, always create h4
  return document.createElement('h4');
};
```
