### ISSUE TITLE
Documentation clarification of the selector for scrollingContainer

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#1496]
From the documentation on the scrolling container

```
scrollingContainer

Default: null

Specifies which container has the scrollbars (i.e. overflow-y: auto), if changed with CSS from the default ql-editor. Necessary to fix scroll jumping bugs when Quill is set to auto grow its height, and another ancestor container is responsible from the scrolling.
```

But it does not clarify what can be passed in. Can it be the actual element or only a string? From testing I see it can only be a string. 

@jhchen Would passing `'html, body'` work as the selector for scrollingContainer?

**Comment by jhchen** [comment]
It can take a DOM element or a CSS selector so yes `html, body` should work.
