### ISSUE TITLE
Use of style attribute violates Content-Security-Policy inline style prevention.

### ISSUE THREAD

**Issue by changelogsorg** [quilljs/quill#1499]
When using Content Security Policy restricting inline style modifications, the style will not be applied and Developer Tools will return a warning:

> Refused to apply inline style because it violates the following Content Security Policy directive: (etc)

The line responsible:

`var contents = this.clipboard.convert('<div class=\'ql-editor\' **style="white-space: normal;"**>' + html + '<p><br></p></div>');`

**Steps for Reproduction**
1. Can't demonstrate it on something like Codepen, but this should do it:
`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src https://cdn.quilljs.com; script-src 'self' https://cdn.quilljs.com;" />`

2. Initialize as normal.

**Expected behavior**:
That is expected behaviour.

**Actual behavior**:
n/a

**Platforms**:
Chrome/Windows 10/Cross-platform.

**Version**:
1.2.6

**Comment by jhchen** [comment]
`clipboard.convert` is an internal method not meant for public consumption. The public interface for this functionality is `dangerouslyPasteHTML`, which allows arbitrary HTML input, and as its name suggests it may be dangerous and trip security warnings.

**Comment by GarrettGeorge** [comment]
This should be reopened, because even if it's not for public consumption, the function is still called which causes a CSP error.

**Comment by oliverniessen** [comment]
I'm running in the same problem with recent version of quill. Currently looking for a workaround or a solution. This should indeed be reopened.

**Comment by GarrettGeorge** [comment]
@oliverniessen Unfortunately the only workaround is to change the code yourself and use `npm patch-package` to have your changes checked into source control for your application. This also means that you'll have to include Quill into your build pipeline. With Webpack 4, you also get some reduced build size from this.

**Comment by leo-terratrue** [comment]
@jhchen any plans to replace this with a stylesheet or <style/> tag? Advantage of the latter would be that it could be incorporated into a CSP via hash/nonce; as it is currently, there is not a way to use Quill with a secure CSP short of patching the library. Thanks.

**Comment by JMitnik** [comment]
This is becoming a rather important point to more users as CSP is becoming more common in most applications. Is there any work that is done on this?

**Comment by mattdeacon** [comment]
Agreed - this is a problem!

**Comment by dmigo** [comment]
Any plans on moving forward with supporting `nonce`?

**Comment by martijnvankekem** [comment]
I have no idea why this issue hasn't been resolved after 6(!) years.

The line at the top is called by the constructor of Quill, and we're therefore not able to not call it, as @jhchen suggests above.

This really needs to be fixed.

**Comment by dgiessing** [comment]
Also +1 on reopening and solving this issue. Since Angular is now supporting Nonces too there will be a lot more of applications running into this problem.

**Comment by Santhosh-Hanabi** [comment]
+1

**Comment by Lakai4eg** [comment]
up

**Comment by pmartinezga** [comment]
+1
