### ISSUE TITLE
createObjectURL(file) not work in quill.insertEmbeb()?

### ISSUE THREAD

**Issue by tzx119wade** [quilljs/quill#1503]
hey,guy
when i user createObjectURL to get the local file path, and i pass the url in the quill.insertEmbeb(),but it's doesn't work

the img tag like this  <img src="//:0"> ...

so ,any one know that's the issue?

thk.

**Comment by jhchen** [comment]
What have you tried in attempting to debug?

**Comment by tzx119wade** [comment]
hey , i got the image tag <img str="//0">
Does the quill.insertEmbeb() only support data:/image, not the file url?

**Comment by tzx119wade** [comment]
hey i got the image tag
`<img src="//0`>
Does the quill.insertEmbed() only support data:image,but not file url?

**Comment by pronghuang** [comment]
The file schema isn't supported by quill. However, you can add file schema in quill.js. There is an array-"['http', 'https', 'data']". Change it to ['http', 'https', 'data', 'file']. It's worked.

**Comment by jhchen** [comment]
Thanks for the help @pronghuang !

**Comment by Yehuda-Zvi** [comment]
pronghuan, jhchen; 
where do you change the file schema in ReactQuill?
wish file or folder to accsse?

**Comment by Yehuda-Zvi** [comment]
found it.
but it didnt help, nothing change, still dont work for me

using it like this:

      editorRef.current.editor.insertEmbed(
          cursorPosition,
          "image",
          window.URL.createObjectURL(file) // here image base64 or url from server work fine
        )

**Comment by Yehuda-Zvi** [comment]
without changing anything in the files, just add sanitize. works great!!

const Image = Quill.import("formats/image")
        const url = window.URL.createObjectURL(file)
        Image.sanitize = function (url) return url
        
        editorRef.current.editor.insertEmbed(cursorPosition, "image", url)
