### ISSUE TITLE
quill.find() returns undefined

### ISSUE THREAD

**Issue by amitm02** [quilljs/quill#1505]
"Model" category api function "find()" does not exist. rest of the "Model" functions works.

**Steps for Reproduction**
call find method.
[example](https://jsfiddle.net/amitm02/5h4xpazq/)

**Expected behavior**:

function should work

**Actual behavior**:

returns undefined

**Platforms**:

chrome

**Version**:

1.2.6

**Comment by jhchen** [comment]
`find` is a static method so it would be `Quill.find` not `var editor = new Quill(); editor.find()`
