### ISSUE TITLE
Error integrating Quill in Salesforce: Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by EmilioMN92** [quilljs/quill#1507]
Hello,
I included the quill.js file into my Salesforce org in order to use it. I'm displaying the editor properly, but when I'm about to use it, when I'm gonna click on it, everytime that I key down, this error appears in the console:

> aura_prod.js:887 Uncaught TypeError: Cannot read property 'length' of undefined
> throws at /resource/1497359755000/QuillJS:2774:32 TypeError: Cannot read property 'length' of undefined
>     at Array.forEach (native)
>     at Selection.normalizeNative (/resource/1497359755000/QuillJS:2774:32)
>     at Selection.getNativeRange (/resource/1497359755000/QuillJS:2716:24)
>     at Selection.getRange (/resource/1497359755000/QuillJS:2723:29)
>     at Selection.update (/resource/1497359755000/QuillJS:2917:28)

Also, when I click the spacebar or trying to use any button in the toolbar, an error raises as an alert saying:

> Uncaught TypeError: Cannot read property 'length' of undefined throws at /resource/1497359755000/QuillJS:2774:32

Can anyone help me? 
Thanks in advance!

**Comment by jhchen** [comment]
This Github is for Quill only and is agnostic to any integrations that may use it like Salesforce. Please contact them for Salesforce integration questions or support.
