### ISSUE TITLE
Deeply customize a blot that wrapping blots, and handle selection and keyboard events for it without pain.

### ISSUE THREAD

**Issue by gztchan** [quilljs/quill#1510]
**Steps for Reproduction**

![image](https://user-images.githubusercontent.com/6322366/27115766-7bac0684-50ff-11e7-89c9-d57c521e1ebd.png)

1. Create a blot extending Container/Block/BlockEmbed, named HyperVideoBlot, tagName is DIV
2. Reuse built-in Video
3. Create a blot named CaptionBlot, you can find that in the picture above, tagName is SPAN
4. Now, when insert HyperVideoBlot, Video and CaptionBlot will be appended into HyperVideoBlot as children blots.

**Expected behavior**:

- Selection system works well in both HyperVideoBlot(parent) and CaptionBlot(child). I can decide the selection after insertion and deletion.
- Handle keyboard event in HyperVideoBlot, override all default built-in handlers even basic Enter event.

**What I have done**

1. For now, I just store default keyboard handlers and remove those in a module when HyperVideoBlot is focus or selected, restore those handlers when it lose focus. And I add my listeners to handle the customized logic. Is this a right way?

2. Which blot I should use in this situation, a blot wrapping two customized blots and inserted as a block element to occupy a whole line. The reason I ask for suggestion is that I found that different blot built-in as a wrapper blot lead to different behaviors in scenarios, for example deletion, some will change the selection into the wrapper blot(such as Block, Container), some will remove it directly(such as BlockEmbed, Embed).

![image](https://user-images.githubusercontent.com/6322366/27116685-2bd537c4-5105-11e7-8782-724aaa677d63.png)

**Actual behavior**:

- Selection system fail(return `Range { index: -1, length: 0 }` or `Range { index: 0, length: 0 }` when CaptionBlot selected)
- When I insert HyperVideoBlot, two different situation as follow come up:
  1. If the selection is in the line with content(mainly text), it will be changed to the end of the line(same line to Video)

![image](https://user-images.githubusercontent.com/6322366/27116817-de4c7a2a-5105-11e7-9df1-cdb0c8e00993.png)

  2. if the selection is at the beginning of a new line without anything, it will be changed to the end of the CaptionBlot.

![image](https://user-images.githubusercontent.com/6322366/27116733-6d48e1ce-5105-11e7-9367-f23b4b4ed65a.png)

**Platforms**:

- Chrome latest 2
- Safari latest 2

**Version**:

1.2.6

**Comment by jhchen** [comment]
There are lots of ways to go about this. What do you want your data to look like? For example, the last screenshot, if it were just a video would look like this:

`[{ insert: "Some text here\n" }, { insert: { video: "youtube.com/url" } }]`

How would it look with the caption?
