### ISSUE TITLE
Feature Request: Emit an `EDITOR_CHANGE` when `enable()` or `disable()`

### ISSUE THREAD

**Issue by guillaumepotier** [quilljs/quill#1512]
Hi there,

I created a module and that one should update when Quill is enabled or disabled. Unfortunately, there is no event triggered when state change, and currently I only rely on a css `ql-disabled` parent class, which is a bit smelly IMO.

Don't you think that changing that property should emit an `EDITOR_CHANGE` event?

If so, I'd be glad to submit a PR.

Best

**Comment by jhchen** [comment]
How does one enable or disable the editor without your application being aware of it? The only way to do so is through the `enable` and `disable` APIs, which your application has to explicitly call.

**Comment by guillaumepotier** [comment]
Hi, thanks for your answer.

Yes indeed my application knows how/when to disable Quill, and use the `enable`/`disable` API.

Quill modules are already listening Quill `emitter`, I find it more handy to listen a change here rather than listening on top of that my own application `emitter` to catch the event. One emitter seems better than two right?

**Comment by jhchen** [comment]
`editor-change` as [documented](https://quilljs.com/docs/api/#editor-change) is meant to combine `text-change` and `selection-change`. Neither text nor selection is being changed here so it would not be correct to fold that into either and adding it to `editor-change` would move it beyond its role as an event aggregator. If this were to be added there would have to be a third event say `readonly-change` and `editor-change` would include that as well. 

What you are asking for is already possible, and I would even say easy and the addition just makes that easier. I'm not seeing the justification for adding complexity to the API surface or library for this purpose. If others need this in the future feel free to upvote the issue and it may be reconsidered.

**Comment by guillaumepotier** [comment]
Ok I understand your point. Best
