### ISSUE TITLE
How i get the content

### ISSUE THREAD

**Issue by WUSO01** [quilljs/quill#1513]
Be different from other editors,  use <textarea> element, I want to know what should I do and I can get this content in the backend. if I use <textarea>  I could use the name attribute. Submit the form.
![f aw o w 7u5w qqsvqrj6](https://user-images.githubusercontent.com/21070775/27173916-cd7244a4-51ec-11e7-8319-8f8bbe4a0aeb.png)

**Comment by benbro** [comment]
Quill doesn't use textarea.
This [example](https://quilljs.com/playground/#form-submit) explains how to access the content.
