### ISSUE TITLE
Is there a way to force a Blot to contain a specific prefix (# hash tag)?

### ISSUE THREAD

**Issue by chanphillip** [quilljs/quill#1515]
I'm implementing an editor which supports using # hash tag for something by showing an autocomplete drop down menu.
I want to wrap the content with a custom element (e.g. <x>) so I can change its styles.
So when I type #, the drop down menu should show. On the other hand, if the # character was removed by the user no matter how, the <x> should be removed.

I did use keyboard bindings to apply the format when # key is pressed. However, I have no ideas how to remove the format when the # character is removed.

Maybe text-change?

**Comment by DmitrySkripkin** [comment]
Check this codePen https://codepen.io/ivanalejandro0/pen/LbyNYW it has similar behavior.
1. You add mention
2. You change text. Add characters, don't remove (but you can modify it for your case)
3. Mention becomes plain text

**Comment by chanphillip** [comment]
@DmitrySkripkin Thanks for your reply!
Unfortunately, what I'm looking for may be a little more complex.

User should be allowed to trigger the Blot by typing the syntax "#" and also edit the text in the Blot.
The Blot will be cancelled only when the syntax "#" is deleted.

Currently I'm checking all the lines every text-change, which does not seem like a good approach.

**Comment by magicdvd** [comment]
textchange event. test the delta data with single insert string '#'. then do anything you like.  test the last op of delta is delete op to handle '#'  remove.

getSelection   setSelection  format  are the key functions

**Comment by benbro** [comment]
Answered.
