### ISSUE TITLE
Add style  in images ATTRIBUTES

### ISSUE THREAD

**Issue by VivekIot** [quilljs/quill#1518]
Currently we are not able to use image  which have style attributes in it

var ATTRIBUTES = ['alt', 'height', 'width','style'];

**Comment by mxgr7** [comment]
@VivekIot, have you tried adding e.g. `'width`' to the `formats: [...]` option?

**Comment by borodean** [comment]
@mxgr7 could you please help figuring out why does the thing you suggested help?s How does that magic works?
