### ISSUE TITLE
How to Override tooltip of active theme (snow) ?

### ISSUE THREAD

**Issue by triawarman** [quilljs/quill#1520]
How do i override tooltip on the active theme (snow) ?, i want to replace the default html element and hooks a particular javascript function, but all I know is calling
```javascript
Var tooltip = Quill.import ('ui / tooltip');
```
Even after trying to understand the source code, it remains difficult for me if there is no sample

**Comment by jhchen** [comment]
Can you elaborate on what you are trying to do and what you mean by override?

**Comment by triawarman** [comment]
Hy @jhchen 
i want to change the tooltip
![ss](https://user-images.githubusercontent.com/10298895/27275789-9717619c-550b-11e7-9e21-9261857009c1.png)
into something like
![ss2](https://user-images.githubusercontent.com/10298895/27275859-cf219c92-550b-11e7-900f-0901d443c1a6.png)
and hook javascript function (ex. event click).

**Comment by guillaumepotier** [comment]
I would have suggested to create your own theme, that extends the snow default, but I'm currently trying to do the same with bubble and facing a weird problem [I posted on StackOverflow](https://stackoverflow.com/questions/44625868/es6-babel-class-constructor-cannot-be-invoked-without-new?noredirect=1#comment76237734_44625868) so I cannot help you much more.

**Comment by triawarman** [comment]
@guillaumepotier I just created my own theme (after days of trying and still fail)

**Comment by guillaumepotier** [comment]
@triawarman yould you care sharing here your code? I'm having hard time to do extend bubble one.

**Comment by triawarman** [comment]
@guillaumepotier i dont do something like import or extend any class, i copy function module 63 and paste as function module 109, then add line code in module 62
```
'themes/owntheme': _owntheme.default,
```
its hard for me if there's no guide, or sample code.

**Comment by boldwade** [comment]
Can we re-open this issue? It is not at all clear how one create's their own theme.

**Comment by philippkuehn** [comment]
Please re-open!

**Comment by guillaumepotier** [comment]
Hi @boldwade & @philippkuehn 

I had issues too to import and override default bubble theme. **Documentation is perfect to create a new theme from scratch** (no need to re-open issue for that IMO).

**_However_**, if you want to extend `snow` or `bubble`, you'll have to play a bit with your project configuration in order to call Quill `src` files and not `dist` ones since it does not export enough :(

[Here is my really useful stackoveflow issue.](https://stackoverflow.com/questions/44625868/es6-babel-class-constructor-cannot-be-invoked-without-new)

Hope that helps

**Comment by e-monson** [comment]
To anyone coming here from Google, I don't believe there is any supported way to override the tooltips from either theme, as they are not available as exports. There also doesn't seem to be any official guidance on creating one's own theme. Even Quill's `BaseTheme` is not made available to import. I can only speculate as to why.

**Comment by e-monson** [comment]
If anyone knows of a workaround or hack to extend the themes' tooltips or to create a new theme, I would love to know. Suggestions for an alternative to Quill are also very welcome.
