### ISSUE TITLE
[Feature Request] Scrollable toolbar in mobile devices 

### ISSUE THREAD

**Issue by Balaji-Sankar** [quilljs/quill#1523]
Currently, in mobile devices ql-toolbar is displayed one by one which occupies much space.The project I am working on require quill toolbar in the single line i.e) in the case of mobile devices ql-toolbar must be scrollable which will also look good in UI.

![image](https://user-images.githubusercontent.com/20572335/27228623-f9efef0c-52c5-11e7-9b94-f5bc47bd8d86.png)

I suggested the scrollable toolbar in the case of mobile devices.Refer the screenshot

![image](https://user-images.githubusercontent.com/20572335/27228717-5de91f38-52c6-11e7-90ab-9fedafe2d7bf.png)

I have already implemented it.If its ok I will submit a PR.

**Comment by jhchen** [comment]
I'm happy to look at a PR but I can't guarantee it will be merged -- it depends on the complexity of the solution. Quill's themes provide reasonable defaults but is built to allow users to customize this and additional features and complexity may be counterproductive to users' ability to customize.

**Comment by Rhonun** [comment]
@ibalajisankar did you ever submit a PR for this? or could I look at your implementation. I'm having trouble with getting the dropdowns to show

**Comment by ibalajisankar** [comment]
Hi @Rhonun . I didn't submit PR request. For the scrollable toolbar just include `overflow:scroll` in the `ql-toolbar` class. And then write a javascript function to toggle between overflow scroll and initial for the ql-toolbar..When User clicks on the `ql-format` class that function need to be triggered.
