### ISSUE TITLE
Quill editor line break not rendering for output

### ISSUE THREAD

**Issue by taoHanhNguyen** [quilljs/quill#1529]
I am using quill editor to provide users ability to edit rich text and have it saved to DB.
The application should also able to load the saved text from database and have it output for users to see.
So when text is loaded from DB, no line break showed on the editor for <p></p>
For example:
text from Database: <p>testing render paragraph.</p><p>This should work.</p>
Output on User interface: testing render paragraph.This should work. 
No line break at all and output is very weird looking.

How do I get the line break rendering work when output data.
Thanks

**Comment by jhchen** [comment]
Can you include steps for reproduction, expected output, actual output and what platforms you are observing this issue on?

**Comment by oz-freeman** [comment]
> Can you include steps for reproduction, expected output, actual output and what platforms you are observing this issue on?

this happens on a Yii model field editor rendering
`$form->field($model, 'description')->widget(\bizley\quill\Quill::class, ['toolbarOptions' => 'FULL'])`

2 lines in a description field. But no line breaks in a editor control value

Quill 2.3.0 as a Yii2 extension
