### ISSUE TITLE
Handling copy-pasting (moving/duplicating of content) in the delta

### ISSUE THREAD

**Issue by mitar** [quilljs/quill#1531]
It seems that current delta format does not handle moving or duplicating content in any special way. But by having that information encoded in delta, we could handle cases where one user moves part of the content and another user at the same time changes some part of that content. Then the result would be that the moved content at the end has another user's content change there as well.

**Comment by jhchen** [comment]
What specifically are you proposing?

**Comment by mitar** [comment]
That the delta contains something like: move these elements to that other location. Currently there are only `insert`, `retain` and `delete` operators.

So one option would be to add a new operator. The other would be that `insert` operator which represent a paste would have an attribute referencing the original cont

**Comment by jhchen** [comment]
At present I do not see a big need for this to merit it's costs. Conflict resolution itself is a rare case to hit (<1%) but the consequence is disastrous (different documents seen by different clients) in a collaborative environment. 

Here the benefit is not averting disaster, but just preserving intent in a case that is a fraction of an already rare case. When the case is hit, it is very clear what just happened to the user and very easy to remedy. Furthermore the cost of designing and implementing a new operation is high.

That being said if one is particularly interested in this case and would like to design and implement it, I would suggest starting with spec'ing out specifically what the new operation would be and how they would interact with existing operations and I will give feedback.
