### ISSUE TITLE
How to add custom tags, such as <my-tags></my-tags>

### ISSUE THREAD

**Issue by DC921115** [quilljs/quill#1532]
I'm sorry for the strange question;

but I want to customize a label,Use it in Quill,

the quill remove all my tags, Except for its own tags;

Who can help me with a little thought?

Many thanks!

**Comment by DawidLoubser** [comment]
I would start with reading the basic documentation. A given Quill editor supports a specific, strict document structure, defined using [Parchment](https://github.com/quilljs/parchment). To support custom tags, you have to create and register your own `Blot` - for example, to support a "link':

```
class LinkBlot extends Inline {
  static create(url) {
    let node = super.create();
    node.setAttribute('href', url);
    node.setAttribute('target', '_blank');
    return node;
  }
  
  static formats(node) {
    return node.getAttribute('href');
  }
}
LinkBlot.blotName = 'link';
LinkBlot.tagName = 'a';

Quill.register(LinkBlot);
```
By logically **defining** a concept (like a link) here, and telling Quill how to bi-directionally convert between its HTML representation, and the blot (in the Parchment document model) you can now freely include this in your markup.

You tell Quill how to identify your custom blot in HTML markup, by either specifying a `tagName` or a `className`.

*Hope that helps!*

**Comment by jhchen** [comment]
Thanks for the help @DawidLoubser !

**Comment by DC921115** [comment]
Many Thanks  @DawidLoubser !
