### ISSUE TITLE
Asynchronous call in Link.sanitize

### ISSUE THREAD

**Issue by aliciawood** [quilljs/quill#1534]
Is it possible to make an asynchronous call in the link.sanitize and return the new url in a promise?  I am trying to return the new url in a promise and it's setting the url to undefined when I try to click on it?

**Comment by jhchen** [comment]
The function does not return a promise. There are many generalized approaches to turn a synchronized function to an asynchronous one or to "promisify" a function but they are not specific to Quill.

**Comment by aliciawood** [comment]
That's what I'm confused about.  The Link.sanitize function doesn't wait for the promise to return.  Is there a way to get it to wait?  I am only able to ever have the link be undefined or a promise object.
