### ISSUE TITLE
text direction in setContents doesn't work

### ISSUE THREAD

**Issue by udaraweerasinghege** [quilljs/quill#1535]
Passing in textDirection as an attribute in setContents does not work.

**Steps for Reproduction**

1. Visit https://codepen.io/anon/pen/OggPNa?editors=1010
2. Notice passing in 'direction' as an attribute on line 11 does not cause the text to be RTL. In console getFormat does not have the direction attribute.
3. Uncomment line 17/18 and run, it'll be RTL as intended

**Expected behavior**:
Passing `{attributes: {direction: 'rtl'}}` should set text direction to rtl for those contents
**Actual behavior**:
Contents are still ltr
**Platforms**:
Firefox 54.0 OSX
Include browser, operating system and respective versions

**Version**:
1.2.6

**Comment by jhchen** [comment]
Text direction is a block level format so you need to have attributes on the newline character. If this was not the case `[{ insert: "Hel", attributes: { direction: "ltr" }}, { insert: "lo", attributes: { direction: "rtl" }}]` would be ambiguous.

If you are interested more details are here: https://quilljs.com/guides/designing-the-delta-format/#line-formatting
