### ISSUE TITLE
Unable to setup dev environment

### ISSUE THREAD

**Issue by jmzhang** [quilljs/quill#1536]
I was following the guide to setup the dev environment on a mac, but jekyll gives me an error while generating docs:

`jekyll 3.5.0 | Error:  undefined method 'registers' for nil:NilClass`

and then everything just get killed altogether.

**Steps for Reproduction**

1. did a fresh install of ruby using `brew install ruby`
2. clone the quill repo and `npm install`
3. make sure webpack and webpack-dev-server are installed globally
4. run `gem install foreman jekyll kramdown rouge jekyll-sitemap jekyll-redirect-from jekyll-feed` as written in the guide
5. `npm start`

**Expected Behavior**
the proxy should start serving

**Actual behavior**:
Everything get killed due to the jekyll error. Here is the log output from foreman:
```
14:00:17 jekyll.1  | started with pid 45453
14:00:17 karma.1   | started with pid 45454
14:00:17 webpack.1 | started with pid 45455
14:00:17 proxy.1   | started with pid 45456
14:00:17 proxy.1   | Proxy listening on 9000
14:00:17 jekyll.1  | Configuration file: ../docs/_config.yml
14:00:17 jekyll.1  | Configuration file: jekyll.yml
14:00:17 jekyll.1  |        Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
14:00:17 jekyll.1  |             Source: ../docs
14:00:17 jekyll.1  |        Destination: ../docs/_site
14:00:17 jekyll.1  |  Incremental build: disabled. Enable with --incremental
14:00:17 jekyll.1  |       Generating... 
14:00:17 jekyll.1  | jekyll 3.5.0 | Error:  undefined method `registers' for nil:NilClass
14:00:18 webpack.1 | Project is running at http://localhost:9080/
14:00:18 webpack.1 | webpack output is served from /
14:00:18 webpack.1 | Content not from webpack is served from path-to-quill/dist
14:00:18 jekyll.1  | exited with code 1
14:00:18 system    | sending SIGTERM to all processes
14:00:18 proxy.1   | terminated by SIGTERM
14:00:18 webpack.1 | exited with code 0
14:00:18 karma.1   | terminated by SIGTERM
```

**Platforms**:

macOS Sierra
Ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
Ruby Gem 2.6.11
Jekyll 3.5.0
jekyll-feed 0.9.2
jekyll-redirect-from-0.12.1
jekyll-sitemap-1.1.1
kramdown-1.13.2
rouge-1.11.1
foreman-0.84.0

Is this related to the version of jekyll being used? I'm not familiar with ruby stuffs so I have no clue on how to debug this error :(

**Comment by mdpye** [comment]
Installing a previous version of jekyll works. I added the following Gemfile to my clone and used bundler:

```
source 'https://rubygems.org'

gem 'jekyll', '3.2.1'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem 'jekyll-feed'
gem 'foreman'                                                                                                                                                                       
```

More recent versions of jekyll might work, but I just jumped back far to be sure.

I'd suggest to the Quill maintainers that they should include a `Gemfile` in the main distribution in order to specify their expect versions.

**Comment by jmzhang** [comment]
That rocks man! I used 3.3.0 instead, in order to meet the dependency requirements of the plugins, and everything seems good so far. 

And I also agree that the versions should be explicitly set in the repo, hopefully someone familiar with ruby could submit a PR.
