### ISSUE TITLE
Is it possible that setContents(bigDelta) is slower than setText("")+setContents(bigDelta)

### ISSUE THREAD

**Issue by amitm02** [quilljs/quill#1537]
On my project i've noticed that if the editor already contains large chunk of content and I apply setContents() with a another big Delta object, It can be very slow. up to a few seconds.
The profiler showed that most of the time goes to some inner diff function of quill.
So I've attempted to reset the editor first with setText("") and than set the large content with setContents(bigDelta). Indeed it seems to be much faster.

**Comment by DmitrySkripkin** [comment]
This may be related to https://github.com/quilljs/quill/issues/627#issuecomment-207662188

**Comment by jhchen** [comment]
If you go from largeChunkOfContentA -> largeChunkOfContentB, one diff will be generated and emitted to text-change. This diff could be expensive.

If you go from largeChunkOfContentA -> "", this diff is trivial. Then going from "" -> largeChunkOfContentB is also a trivial diff.

**Comment by amitm02** [comment]
Is there a more efficient/elegant way to reset the editor content than setText("")?

**Comment by jhchen** [comment]
I mean you can do setContents([]) if you'd like. Like I said the performance difference is rooted in the diff. When you do setContents([]) and then setContents(bigDelta) you avoid this big calculation.

**Comment by isaaclyman** [comment]
I'd like to see this as a first-class feature in Quill - just a flag that says "please set the content without calculating a diff." I don't need the diffs emitted by the editor, my app only requires the complete state at various moments. As simple as it is to create my own abstraction over setContents it would be great to integrate this feature and save other users with similar use cases the trouble.
