### ISSUE TITLE
Create/Populate a 'new' toolbar .ql-picker

### ISSUE THREAD

**Issue by kwikbitz** [quilljs/quill#1543]
I am trying to create a new toolbar .ql-picker for a web project.  I can create the picker like `this:`

```
 var toolbarOne = [[{'header':[1,2,3,4,5,6,false]}],['bold','italic','underline'],[{'list':'ordered'},{'list':'bullet'}],['link','blockquote'],['image'],[{'align':[]}],[{'newPicker':[array_of_ picker_options]}],['clean']];
```
I can attach the picker to the toolbar like this:

```
var toolbar = quill.getModule('toolbar');
toolbar.addHandler('newPicker',function(){ });
```
So far so good.

**Now how do I populate the newPicker?**

The picker items will be a simple 'text menu list' of options e.g:
```
var array_of_ picker_options = ['option 1','option 2','option 3','etc']
```
The purpose of the picker & picker options is to 'trigger' a specific action/s when the option is selected.

e.g. 

Select 'option 1' - firstly a short code will be inserted at the cursor e.g. [myshortcode][/myshortcode] and a secondly a modal will open that creates 'options' for the shortcode.

To explain further - other than insertion the short code will have no further 'action' within the Quill editor the shortcode will 'insert' specific uneditable html into the actual editor result.

Example - [myshortcode][/myshortcode] is inserted into the editor - NP with doing that on option click (once can populate the ql-picker:))

When the text is rendered on a webpage the [myshortcode][/myshortcode] would be replaced with say <div id="id_created_in_the_modal"></div>

The concept being to insert a div (as above) that is related to a jQuery plugin.

Example:
Option 1 might be a calendar plugin
Option 2 might be a n other plugin
etc.

The plugins would all be pre-defined  

So far so good?

I am about 90% certain that I can do all this ONCE I have the .ql-picker populated

**Platforms**:

Web and mobile

Include browser, operating system and respective versions

**Version**:

Current CDN version

Thanks in advance

**Comment by jhchen** [comment]
Please include the specific browser + OS and the version of Quill.

**Comment by armellarcier** [comment]
@russell-parrott did you manage to do what you wanted? I'm looking for advice to do the same. Thanks in advance!

**Comment by russell-parrott** [comment]
Hi Armel,

Gosh ... that was some time ago .. the answer is yes but not sure where the
code is ...

I'm very busy for couple days (yes over weekend too) but when I get 5mins
I'll dig it out - it has to be somewhere😁

Aside, if you give me some clue as to "what you want to populate with" I
may even have that coded - again somewhere

Cheers

**Comment by armellarcier** [comment]
Thank you for the quick reply! I'm trying to implement something similar to how wordpress shortcodes work.
Currently I need to insert a link/button to an existing page in my db. The placeholder could be something like `{page:2}My text{/page:2}` and will get replaced by a link upon rendering.

**Comment by russell-parrott** [comment]
OK ... so "click button" xhr request to db? or run a php function to get
the URL?

Might be a bit slow depending on server config and number of pages.

If its not many pages then xhr "overkill", you could store the page info in
say localStorage or sessionStorage the quickly populate a drop down in the
toolbar of fire say a modal if the page list is too long then a simple JS
regex replace in the quill

Just a thought or two
