### ISSUE TITLE
getLeaf().next and getLeaf().prev

### ISSUE THREAD

**Issue by DmitrySkripkin** [quilljs/quill#1545]
I know `getLeaf()` is tagged as _experemental_.

I have content:
1. Text blot
2. Custom blot (block embed)
3. Text blot

When I call `getLeaf()` with index inside Custom blot - it's ok. I have `prev` and `next`.
When I call `getLeaf()` with index inside any of Text blots - both `prev` and `next` are `undefined`.

I have no idea, but maybe I just didn't configure my Custom blot correctly.

**Comment by DmitrySkripkin** [comment]
Magically it works at the moment, I need some time to figure out what was the reason.

**Comment by jhchen** [comment]
It should work. Can you post a [MCVE](https://stackoverflow.com/help/mcve). Otherwise it's hard to say what is going wrong.

**Comment by DmitrySkripkin** [comment]
I tried to create MCVE, but no success. Looks like it was something wrong in my code.
