### ISSUE TITLE
List index counter does not change size with the font size

### ISSUE THREAD

**Issue by amitm02** [quilljs/quill#1547]
When making a list with a font size different than normal, the index counter of the list does not match the font size.

**Steps for Reproduction**

[Example](https://jsfiddle.net/amitm02/7h8ot9vx/2/)

**Expected behavior**:

[Expected](https://jsfiddle.net/amitm02/55qtca78/)

**Actual behavior**:

see [example](https://jsfiddle.net/amitm02/7h8ot9vx/2/) from above

**Version**:

1.2.6

**Comment by benbro** [comment]
Related https://github.com/quilljs/quill/issues/409
