### ISSUE TITLE
Error on Paste text (Android, Chromium )

### ISSUE THREAD

**Issue by volser** [quilljs/quill#1548]
on Android Chromium I have next code
```
quill.on('editor-change', function(eventName, args) {
  //console.log(JSON.stringify(quill.getSelection()));   
  console.log(JSON.stringify(quill.getFormat()));
});
```
On paste from buffer I'm getting next error
"Uncaught TypeError: Cannot read property 'index' of null", source: file:///android_asset/quill/quill.min.js (7)

Because, on paste quill.getSelection() is null on Android

```
 getFormat(index = this.getSelection(), length = 0) {
    if (typeof index === 'number') {
      return this.editor.getFormat(index, length);
    } else {
      return this.editor.getFormat(index.index, index.length); **<-- bug here "index" is null**
    }
  }
```

**Comment by kfedorov91** [comment]
bump

Also experiencing this issue on Chrome 61 on macOS 10.12 Sierra.
