### ISSUE TITLE
Anyway to hook into Link.format function?

### ISSUE THREAD

**Issue by aliciawood** [quilljs/quill#1549]
I have hooked into the Link.create method by doing

```
var originalLinkCreate = Link.create.bind(Link);
Link.create = function(value){
	var node = originalLinkCreate(value);
	return node;			
}
```

I am wanting to do the same thing for the Link.format function to hook into when they click on the "Edit" button.  I do not want to hook into the sanitize function because I want do something before the sanitize function then have the sanitize function run.  Does anyone know how I can do this?

I tried hooking into Link.formats but it seems to behave differently than the Link.format and Link.create functions.  Any ideas on how to do this?  Thanks.

**Comment by jhchen** [comment]
Overwriting function definitions is not particularly safe. I would suggest creating your own Link blot, possibly by inheriting from Quill's and overwriting whatever you want in the inherited class.
