### ISSUE TITLE
is there an approach for determining if Quill.js has loaded/rendered.

### ISSUE THREAD

**Issue by seandearnaley** [quilljs/quill#1552]
I'm trying to extend the toolbar on Quill.js 1.2.6 and I have pretty good working logic but I need to wait until the toolbar has loaded into the dom before I can update it... I have looked through the code and I see no events to determine if Quill has loaded, is there a good way to determine if Quill.js has fully loaded/rendered?.   I suspect there may be a more modern way of doing this but it hasn't crossed my mind yet.. if I find a solution I will post it here but if anyone has any ideas, it'd be really appreciated... thanks.

**Comment by benbro** [comment]
Do you have a reason to assume the call to new Quill () isn't synchronous?

**Comment by seandearnaley** [comment]
not really, I call my new quill in an es constructor the standard way, I'm developing a universal plugin, which is designed to run in a Vue.js env and a old school jquery app with a script tag... after the new Quill declaration I attempt a simple:

document.querySelector('.ql-' + option).innerHTML = icons[option];

(I'm using an svg loader to apply the raw svg icon), in the jquery app, document.querySelector('.ql-' + option)   is undefined, if I wait a moment it becomes available leading me to believe I have a synchronization problem.

I have a hacky workaround that works listening for the first editor-change event:

```

    //NOTE: hacky way to determine to load additional toolbar options,
    //the first editor-change event indicates quill has loaded.
    let toolbarLoaded = false;

    this.quill.on('editor-change', (event) => {
      if (!toolbarLoaded) {
        this.addToolbarOptions(additionalToolbarOptions[0]);
        toolbarLoaded = true;
      }
    });
```

**Comment by benbro** [comment]
The toolbar is ready after calling 'new Quill()' as shown in this [example](https://codepen.io/anon/pen/jwaxQQ).

It doesn't matter if you are using Quill in a vue.js, angular or reactjs app. You are the one instantiating the editor so you have a way to know when the editor and toolbar are ready.

**Comment by seandearnaley** [comment]
sorry, perhaps this is beyond my limited comprehension but I still have an issue:

to be clear:

```

    this.quill = new Quill(editorContainer, {
      // debug: 'log',
      modules: {
        history: {
          delay: 1000,
          userOnly: false
        },
        toolbar: {
          container: toolbarOptions.concat(additionalToolbarOptions),
          handlers: {
            undo: (value) => {
              this.quill.history.undo();
            },
            redo: (value) => {
              this.quill.history.redo();
            }
          }
        }
      },
      scrollingContainer: scrollingContainer,
      placeholder: 'Compose an epic...',
      theme: 'snow'
    })

    var toolbar = this.quill.getModule('toolbar');

    document.querySelector('.ql-undo').innerHTML = icons.undo;
```

    document.querySelector('.ql-undo') is undefined.

**Comment by benbro** [comment]
There is no undo button in the toolbar. You'll need to add it yourself.
If you'll try the bold button instead it'll work.
https://codepen.io/anon/pen/QgOVRz

**Comment by seandearnaley** [comment]
sry again, the line: 

    document.querySelector('.ql-undo').innerHTML = icons.undo;

is what sets the undo button svg, I'm trying to add the button myself, and the toolbar container doesn't exist

**Comment by seandearnaley** [comment]
also the ql-undo button is created by quill in the definition, it is simply the icon that is not added... the query selector line is to embed the svg in the button, which quill does create.

**Comment by seandearnaley** [comment]
@benbro  FYI

https://codepen.io/SDearnaley/pen/zzPmwK

the technique works fine--- and in codepen is np... but I am finding situations where the toolbar hasn't run yet and that's why i had to devise this hacky solution:

https://codepen.io/SDearnaley/pen/KqyGqP

this seems to be real issue to me.
