### ISSUE TITLE
How to edit the content with theme bubble when we set quill.enable(false)

### ISSUE THREAD

**Issue by gondar00** [quilljs/quill#1554]
Hi, in the codepen https://codepen.io/quill/pres/WGVrRe, we are still able to edit the content suppose we had added some content into the editor before disabling user input like 
`quill.setText('random text')
quill.enable(false);`
And all the bold, italic, underline are getting applied on the text.

But if we change the theme to bubble then we are not able to apply the styles and the pop up also is not visible due to visibility:none css being applied.

Even though i want to disable user input i want to still let him be able to edit the contents. How can i acheive this?

**Comment by jhchen** [comment]
I'm not able to edit the content from that codepen.

**Comment by gondar00** [comment]
Hi, 
suppose in the above URL you have set some static text using `quill.setText('random text')`
and the theme is set to snow `theme: 'snow'`. You can use all the editing attributes from the available  theme that is bold, italic etc from the quill header.

But, If you change the theme to `theme: 'bubble'` you cannot see the bubble pop up.

I have figured out how to solve it by using the below line instead of `quill.enable(false)` 
`quill.root.setAttribute('contenteditable', false)` by doing this the bubble pop up was coming as expected and the static content set was uneditable too. 

Thank you so much for your reply.
