### ISSUE TITLE
Custom attribute for delta image insert at position.

### ISSUE THREAD

**Issue by bogdaniel** [quilljs/quill#1556]
Based on 

```
var Parchment = Quill.import('parchment');
var offsetAttributor = new Parchment.Attributor.Attribute('offset', 'data-offset', { 
  scope: Parchment.Scope.INLINE
});
Quill.register(offsetAttributor);

var quill = new Quill('#editor');
quill.setText('Gandalf the Grey');
quill.formatText(0, 7, 'offset', '0');
quill.getContents();  // should have a delta with offset attributed
```

I'm trying to add a custom attribute for the img something like this

```
var Parchment = Quill.import('parchment');
var offsetAttributor = new Parchment.Attributor.Attribute('nameClass', 'class', { 
  scope: Parchment.Scope.INLINE
});
Quill.register(offsetAttributor);
```

```
    quill.updateContents(
        new Delta()
            .retain(index)
            .insert(
                {
                    image: 'http://loremflickr.com/320/240'
                },
                {
                    width: '350',
                    nameClass: 'else',
                    alt: 'no working',
                    offset: 3,
                }
            ));
```

but it seems that based on that example i couldn't figure it out how to add the class. 

The rendered code is 
`<p><span class="else"><img src="http://loremflickr.com/320/240" width="350" alt="no working"></span></p> `

And i wanted the class else to be on the img :D ( New to quill still trying to figure it out how it works)

**Comment by bdurand** [comment]
👍 I'm running into a similar issue trying to add a `style` attribute to `img` tags. I traced the issue to the whitelisted attributes in this code:

```javascript
var ATTRIBUTES = ['alt', 'height', 'width'];

var Image = function (_Embed) {
  _inherits(Image, _Embed);

  function Image() {
    _classCallCheck(this, Image);

    return _possibleConstructorReturn(this, (Image.__proto__ || Object.getPrototypeOf(Image)).apply(this, arguments));
  }

  _createClass(Image, [{
    key: 'format',
    value: function format(name, value) {
      if (ATTRIBUTES.indexOf(name) > -1) {
        if (value) {
          this.domNode.setAttribute(name, value);
        } else {
          this.domNode.removeAttribute(name);
        }
      } else {
        _get(Image.prototype.__proto__ || Object.getPrototypeOf(Image.prototype), 'format', this).call(this, name, value);
      }
    }
  }], [{
    key: 'create',
    value: function create(value) {
      var node = _get(Image.__proto__ || Object.getPrototypeOf(Image), 'create', this).call(this, value);
      if (typeof value === 'string') {
        node.setAttribute('src', this.sanitize(value));
      }
      return node;
    }
  }, {
    key: 'formats',
    value: function formats(domNode) {
      return ATTRIBUTES.reduce(function (formats, attribute) {
        if (domNode.hasAttribute(attribute)) {
          formats[attribute] = domNode.getAttribute(attribute);
        }
        return formats;
      }, {});
    }
  }, {
    key: 'match',
    value: function match(url) {
      return (/\.(jpe?g|gif|png)$/.test(url) || /^data:image\/.+;base64/.test(url)
      );
    }
  }, {
    key: 'sanitize',
    value: function sanitize(url) {
      return (0, _link.sanitize)(url, ['http', 'https', 'data']) ? url : '//:0';
    }
  }, {
    key: 'value',
    value: function value(domNode) {
      return domNode.getAttribute('src');
    }
  }]);

  return Image;
}(_embed2.default);
```
Is there any particular reason the attributes on images (and videos) need to be whitelisted? And is there any way via the runtime API to add more attributes to the whitelist?

**Comment by rifkegribenes** [comment]
I am not sure if this is related, but I am trying to add `alt` attribute to images. I couldn’t do it with `insertEmbed` so I am trying to get it to work with `dangerouslyPasteHTML`, which I suspect is probably the wrong way to do it so please let me know if there’s a better solution.

I am using a custom Image handler (which is working fine with `insertEmbed` but it will only insert the URL and not the alt text) so that I can upload the images to Firebase and return the storage URL to insert into Quill. 

This works fine to insert the URL (`resized` is my image URL with the resize params added):

`this.props.quillRef.insertEmbed(range.index, 'image', resized, 'user’);`

I’m trying this to insert the html with `alt` attribute:

`this.props.quillRef.clipboard.dangerouslyPasteHTML(range.index, imgHtml, 'user’);`

where `imgHtml` = `<img src="${resized}" alt="${alt}" />`

when I console.log `imgHtml` it gives me exactly what I want, but the editor seems to be stripping out the alt attribute and returning only the <img> tag with src attribute.

is there something I can do to keep the editor from stripping out the `alt` attribute? is there a better way to do this than `dangerouslyPasteHTML` ?

**Comment by nitaskenderi** [comment]
@rifkegribenes I am not sure if this will help, but why don't you try creating your own image `BlockEmbed` and set the `alt` attribute in its constructor? I do this for my own custom Emoji and adding the `alt` attribute is very easy in this way...

**Comment by rifkegribenes** [comment]
@nitaskenderi thanks I will give it a try, do you have any example code I could look at to get started?

**Comment by jhchen** [comment]
The approach I would recommend is most similar to @nitaskenderi 's suggestion which is to create your own Image blot. Quill's [default one](https://github.com/quilljs/quill/blob/develop/formats/image.js) is inline so inherits from a normal Embed, not a BlockEmbed, but you can use the latter if you want an image to take up the whole line. You can then choose in your implementation if you want to whitelist or not. I would strongly recommend whitelisting however as it keeps the content and thus user experience consistent and predictable.

**Comment by rifkegribenes** [comment]
thanks all, I got it figured out using a custom image blot, which works just fine.

**Comment by SinnerAiZ** [comment]
What I do to fix it is rewriting the image format. In order to sanitize style preventing from attacks such as XSS Or unexpected style, I also add white list for style.
Environment: React-quill

Like this:
```javascript
import {Quill} from 'react-quill';
const Parchment = Quill.import('parchment');
const BaseImage = Quill.import('formats/image');

const ATTRIBUTES = [
  'alt',
  'height',
  'width',
  'style'
];

const WHITE_STYLE = ['margin', 'display', 'float'];

class Image extends BaseImage {
  static formats(domNode) {
    return ATTRIBUTES.reduce(function(formats, attribute) {
      if (domNode.hasAttribute(attribute)) {
        formats[attribute] = domNode.getAttribute(attribute);
      }
      return formats;
    }, {});
  }
  
  format(name, value) {
    if (ATTRIBUTES.indexOf(name) > -1) {
      if (value) {
        if (name === 'style') {
          value = this.sanitize_style(value);
        }
        this.domNode.setAttribute(name, value);
      } else {
        this.domNode.removeAttribute(name);
      }
    } else {
      super.format(name, value);
    }
  }

  sanitize_style(style) {
    let style_arr = style.split(";")
    let allow_style = "";
    style_arr.forEach((v, i) => {
      if (WHITE_STYLE.indexOf(v.trim().split(":")[0]) !== -1) {
        allow_style += v + ";"
      }
    })
    return allow_style;
  }
}

export default Image;

```

**Comment by nitink66** [comment]
@MidaAiZ where do i need to add those above snippet of code ?

**Comment by raclen** [comment]
复制的时候，如果图片有自定义属性
```javascript
    quill1.clipboard.addMatcher('IMG', function (node, delta) {
      // console.log('node',node)
      // console.log('delta',delta)
      let imageId = node.getAttribute('imageid');
      let src = node.getAttribute('src');
      let sourcehight = node.getAttribute('sourcehight');
      let sourcewidth = node.getAttribute('sourcewidth');
      return new Delta().insert({
        image: {
          src: src,
          imageId: imageId,
          sourceHight: sourcehight,
          sourceWidth: sourcewidth,
        }
      });
    });
```
在image.js中
```javascript
import Parchment from 'parchment';
import { sanitize } from '../formats/link';

const ATTRIBUTES = [
  'alt',
  'height',
  'width',
];


class Image extends Parchment.Embed {
  static create(data) {
    let node = super.create(data);
    if (typeof data === 'string') {
      node.setAttribute('src', this.sanitize(data));
    }else if(typeof data==='object'){
      node.setAttribute('src', this.sanitize(data.src));
      data.imageId && node.setAttribute('imageid', data.imageId);
      data.sourceWidth && node.setAttribute('sourcewidth', data.sourceWidth);
      data.sourceHight &&node.setAttribute('sourcehight', data.sourceHight);
    }
    return node;
  }

```

**Comment by Samsoninfection** [comment]
> [@rifkegribenes](https://github.com/rifkegribenes) I am not sure if this will help, but why don't you try creating your own image `BlockEmbed` and set the `alt` attribute in its constructor? I do this for my own custom Emoji and adding the `alt` attribute is very easy in this way...





https://stackdev.space/questions/extracting-embedded-image-data-from-a-quill-delta-a-step-by-step-guide
