### ISSUE TITLE
getText() return "\n" at the end of the result string

### ISSUE THREAD

**Issue by simonemazzoni** [quilljs/quill#1559]
Hello,
this isn't exactly an issue, but still gives me some problems.

If I call the `getText()` method on a quill editor, it returns the content of the editor followed by a `\n` character (increasing also by 1 the length of the string).

**Steps for Reproduction**

1. Visit [https://codepen.io/simomazzoni/pen/RgQdzO](https://codepen.io/simomazzoni/pen/RgQdzO)
2. Look the alert dialog, it contains the quill `getTexT()` result

**Expected behavior**:
I expect to see the string `dummy` without the final `\n`

**Actual behavior**:
It alert the string `dummy\n` with the final `\n`

**Platforms**:
Any browser

**Version**:
1.2.6

Is that `\n` so important?

**Comment by bitmapdata** [comment]
Read this [API - getText](https://quilljs.com/docs/api/#gettext) article.

**Comment by benbro** [comment]
Thanks @bitmapdata 

Also answered here
https://github.com/quilljs/quill/issues/1105

**Comment by simonemazzoni** [comment]
@bitmapdata @benbro thanks a lot, I missed the #1105 closed issue!

I was more interested in understanding why it return that `\n`, anyway I will take in to account when using that method.

**Comment by benbro** [comment]
Just search for 'newline' in the closed issues:
https://github.com/quilljs/quill/issues/890#issuecomment-244524128

**Comment by veronika-2009** [comment]
jkl
