### ISSUE TITLE
quill:toolbar ignoring attaching to nonexistent format :: and font

### ISSUE THREAD

**Issue by QuinDennis** [quilljs/quill#1560]
[Describe the issue]  added two buttons to toolbar but getting the above message

**Steps for Reproduction**
///***index.html**************************************************************
<!DOCTYPE html>
<html>
<head>
  <title>Full Editor - Quill</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="./css/quill.snow.css" />
  <link rel="stylesheet" href="./css/ce.css" />
</head>
<body>
<div id="editor"></div>
<script type="text/javascript" src="./js/quill.min.js"></script>
<script type="text/javascript" src="./js/index.js"></script>
</body>
</html>

///***ce.css******************************************************************
#editor {
  height: 375px;
}
.ql-chord:after {
  content: "VII";
  color: blue;
}
.ql-play:after {
  content: '\25B6';
}

///***index.js***************************************************************
var toolbarOptions = [
  ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
  ['blockquote', 'code-block'],

  [{ 'header': 1 }, { 'header': 2 }],               // custom button values
  [{ 'list': 'ordered'}, { 'list': 'bullet' }],
  [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
  [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
  [{ 'direction': 'rtl' }],                         // text direction

  [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
  [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

  [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
  [{ 'font': [] }],
  [{ 'align': [] }],

  ['clean'],                                         // remove formatting button
  ['chord'],
  ['play']
];

var quill = new Quill('#editor', {
  modules: {
    toolbar: toolbarOptions
  },
  theme: 'snow'
});

var toolbar = quill.getModule('toolbar');
toolbar.addHandler('chord', function() {
  console.log('chord')
});
toolbar.addHandler('play', function() {
  console.log('play')
})

var chordButton = document.querySelector('.ql-chord');
chordButton.addEventListener('click', function() {
  var range = quill.getSelection();
  if (range) {
    var col = quill.getFormat(range.index,0).color
    if (!col) col = 'black'
    quill.insertText(range.index, 'VIII')
    quill.formatText(range.index,4,{'color':'blue', 'font':'Monospace', 'italic': true, 'bold': true})
    quill.insertText(range.index+4, ' ')
    quill.formatText(range.index+4,1,{'color':col})
  }
});
var playButton = document.querySelector('.ql-play')
playButton.addEventListener('click', function() {
  var range = quill.getSelection()
  if (range) {
    quill.insertText(range.index, '\u25B6',{'format':'utf-16'})
    //quill.insertText(range.index,'\25B6')
  }
})

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**:
no error messages, 
  quill.insertText(range.index, 'VIII')
  quill.formatText(range.index,4,{'color':'blue', 'font':'Monospace', 'italic': true, 'bold': true}) should set font
        of VIII to Monospace

**Actual behavior**:
quill errors - ignoring attaching (per below)
no font change

**Platforms**:
Ubuntu17, Chrome 59.0.3071.115

Include browser, operating system and respective versions

**Version**: 1.2.6

// quill Editor with two additional buttons - 'chords' and 'play'
![image](https://user-images.githubusercontent.com/816529/27774018-a95b5b14-5f4d-11e7-9812-4e203c226ccb.png)

// quill error messages
quill.min.js:7 quill:toolbar ignoring attaching to nonexistent format chord <button type=​"button" class=​"ql-chord">​…​</button>​
quill.min.js:7 quill:toolbar ignoring attaching to nonexistent format play <button type=​"button" class=​"ql-play">​…​</button>​

![image](https://user-images.githubusercontent.com/816529/27774027-e0ba6032-5f4d-11e7-9a01-7c12e45983f6.png)

**Comment by jhchen** [comment]
At the time of initialization (when `new Quill...` is called) chord and play look like buttons but have no handlers, hence the warning. Quill does not know that in the future you will attached handlers. To avoid this you can add handlers to the [toolbar config](https://quilljs.com/docs/modules/toolbar/) like in the example `'formula': customFormulaHandler`.

**Comment by isaaclyman** [comment]
How do you declare a custom handler at initialization without using a completely custom toolbar? I'd like to use the built-in UI, as in `toolbar: [['bold', 'italic'], ['customControl']]` and also use the `handlers` property if possible.

**Comment by isaaclyman** [comment]
Never mind, I looked at the module and figured it out. For anyone else who wants to know:

```javascript
new Quill(element, {
  ...
  modules: {
    toolbar: {
      container: [['bold', 'italic'], ['customControl']],
      handlers: {
        'customControl': () => { console.log('customControl was clicked') }
      }
    }
  }
})

```

**Comment by pdcmoreira** [comment]
Thank you! The docs are not clear on this.

**Comment by Hatteron** [comment]
Awesome, thank you!

**Comment by apgsn** [comment]
I had the same warning on a Quill component built with the `react-quill` library and presenting a customised toolbar. @isaaclyman's solution wasn't working for me, so I set the `value` property in the button tag and it worked fine.

```javascript
onCustomControlClick = () => {
    console.log('customControl was clicked');
}

...
modules: {
    toolbar: {
      container: this.renderContainer(),
      handlers: {
        customControl: this.onCustomControlClick,
      }
    }
  }
```
In renderContainer's returned jsx:
```html
<button className="custom-control" value="customControl" />
```

**Comment by ericandrewscott** [comment]
I actually did this with `react-quill` and *without* creating a custom toolbar...

handler function:
```
function handleTags() {
    console.log('HANDLE TAG CLICK');
}
```

Icon insertion:
```
    const icons = ReactQuill.Quill.import('ui/icons');
    icons.tags = '<svg width="18" height="18" xmlns="http://www.w3.org/2000/svg"><path d="M6.3 13.7l-4-4.2 4-4.2L5 4 0 9.5 5.1 15l1.2-1.3zm4.4 0l4-4.2-4-4.2L12 4 17 9.5 11.9 15l-1.2-1.3z" /></svg>';
```


React component:
```
    <ReactQuill
        id="message"
        placeholder="Type a message"
        theme="snow"
        value={content}
        onChange={handleQuillChange}
        className={quillClasses}
        modules={MessageInput.modules}
        formats={MessageInput.formats}
        ref={theInput}
    />
```

API Modules Definition:
```
MessageInput.modules = {
    toolbar: {
        container: [['tags']],
        handlers: {
            tags: handleTags,
        },
    },
};
```

**Comment by teja463** [comment]
Hi @ericandrewscott I tried the same but I am getting the error `quill:toolbar ignoring attaching to nonexistent format tags <button type=​"button" class=​"ql-tags">​…​</button>​`

Here is my code, what am I missing here
```javascript
import React, { useState, useRef } from "react";
import ReactQuill from "react-quill";
import "react-quill/dist/quill.snow.css";

function Editor({ value, setValue }) {
  const reactQuillRef = useRef();
  var icons = ReactQuill.Quill.import("ui/icons");
  icons["undo"] = `<svg viewbox="0 0 18 18">
    <polygon class="ql-fill ql-stroke" points="6 10 4 12 2 10 6 10"></polygon>
    <path class="ql-stroke" d="M8.09,13.91A4.6,4.6,0,0,0,9,14,5,5,0,1,0,4,9"></path>
  </svg>`;

  function handleTags() {
    console.log("HANDLE TAG CLICK");
  }

  const modules = {
    toolbar: {
      container: [
        ["undo"],
        
      ],
      handler: {
        undo: handleTags,
      },
    },
  };
  return (
    <ReactQuill
      theme={"snow"}
      value={value}
      onChange={setValue}
      placeholder="Start editing... asdfsadf sdaf sdaf"
      //   preserveWhitespace
      className="myeditor"
      id="test_1"
      modules={modules}
      ref={reactQuillRef}
    />
  );
}

export default function AppQuill(props) {
  const [value, setValue] = useState("");
  const [show, setShow] = useState(true);
  return (
    <div className="App">
      <div>
        <button onClick={() => setShow(!show)}>Toggle</button>
      </div>
      {show && (
        <div>
          <Editor value={value} setValue={setValue} />
        </div>
      )}
      <div>
        <button onClick={() => localStorage.setItem("t", value)}>Save</button>
        <button onClick={() => setValue(localStorage.getItem("t"))}>
          Restore
        </button>
      </div>
      <div>{value}</div>
      <div
        className="editor-content"
        dangerouslySetInnerHTML={{ __html: value }}
      ></div>
    </div>
  );
}

```

**Comment by pavittar95** [comment]
> Hi @ericandrewscott I tried the same but I am getting the error `quill:toolbar ignoring attaching to nonexistent format tags <button type=​"button" class=​"ql-tags">​…​</button>​`
> 
> Here is my code, what am I missing here
> 
> ```js
> import React, { useState, useRef } from "react";
> import ReactQuill from "react-quill";
> import "react-quill/dist/quill.snow.css";
> 
> function Editor({ value, setValue }) {
>   var icons = ReactQuill.Quill.import("ui/icons");
>   icons["tags"] = `<svg viewbox="0 0 18 18">
>     <polygon class="ql-fill ql-stroke" points="6 10 4 12 2 10 6 10"></polygon>
>     <path class="ql-stroke" d="M8.09,13.91A4.6,4.6,0,0,0,9,14,5,5,0,1,0,4,9"></path>
>   </svg>`;
> 
>   function handleTags() {
>     console.log("HANDLE TAG CLICK");
>   }
> 
>   const modules = {
>     toolbar: {
>       container: [["tags"]],
>       handlers: {
>         tags: handleTags,
>       },
>     },
>   };
>   return (
>     <ReactQuill
>       theme={"snow"}
>       value={value}
>       onChange={setValue}
>       placeholder="Start editing... asdfsadf sdaf sdaf"
>       className="myeditor"
>       id="test_1"
>       modules={modules}
>     />
>   );
> }
> 
> export default function AppQuill(props) {
>   const [value, setValue] = useState("");
>   return (
>     <div className="App">
>       <Editor value={value} setValue={setValue} />
>     </div>
>   );
> }
> ```

I'm facing the same issue

**Comment by adrianszablowski** [comment]
I use icons from materialUI and to use them you have to use them in `renderToStaticMarkup` 

import CodeIcon from '@mui/icons-material/Code';
import ImageIcon from '@mui/icons-material/Image';
```
    const localIcon = ReactDOMServer.renderToStaticMarkup(<ImageIcon />);
    const socialIcon = ReactDOMServer.renderToStaticMarkup(<CodeIcon />);
    const icons = Quill.import('ui/icons');
    icons['loacalImage'] = localIcon;
    icons['socialLink'] = socialIcon;
```

```
    const modules = useMemo(
        () => ({
            toolbar: {
                container: [
                    ['bold', 'italic', 'underline', 'strike'],
                    [{ header: 1 }, { header: 2 }],
                    [{ list: 'ordered' }, { list: 'bullet' }],
                    [{ script: 'sub' }, { script: 'super' }],
                    [{ direction: 'rtl' }],
                    [{ header: [1, 2, 3, 4, 5, 6, false] }],
                    [{ color: [] }, { background: [] }],
                    [{ font: [] }],
                    [
                        {
                            size: fontSizeArray,
                        },
                    ],
                    [{ align: [] }],
                    ['link', 'image'],
                    ['loacalImage'],
                    ['socialLink'],
                ],
                handlers: {
                    loacalImage: openElfinder,
                    socialLink: handleOpenModal,
                },
            },
        }),
        // eslint-disable-next-line react-hooks/exhaustive-deps
        []
    );
```
