### ISSUE TITLE
Toolbar disappears in IE11

### ISSUE THREAD

**Issue by Paisiol** [quilljs/quill#1561]
*** SORRY I just realized that it's still there but I have to scroll. Please ignore this ***

In IE11, when clicking the Bold, Underline, etc toolbar buttons, the toolbar disappears.

**Expected behavior**: like in Firefox, Chrome and Edge, the toolbar doesn't hide

**Actual behavior**: in IE11 the toolbar disappears upon clicking for example the Bold button 

**Platforms**:

IE 11, Windows 7 and Windows 10

**Version**: 1.1.5

Here is the codepen. Run it in IE11 and click on the Bold button.

https://codepen.io/paisiol/pen/OgZmXW

Thank you,
Pablo

**Comment by jhchen** [comment]
Assuming the edit means we can close this...
