### ISSUE TITLE
Plain Text Mode

### ISSUE THREAD

**Issue by scottfr** [quilljs/quill#1562]
Is it possible to have a Quill editor that only support plain text editing? E.g. no shortcuts for styling (bold, italics, ...) should be supported, pasting formatted text should convert it to plain text, etc...

The use case for this is I have an editing control that can toggle between a plain text and formatted text mode. Currently I use a textarea for the plain text and Quill for the formatted text.

I would like to add syntax highlighting to both versions of this control. For the Quill side I will use code based on the Syntax module. I would like to reuse this code in the Plain Text mode, but to do that I have to convert my textarea to a quill control without allowing any formatting.

Is this possible?

**Comment by benbro** [comment]
Try to disable the toolbar and pass empty list to the [formats](https://quilljs.com/docs/configuration/#formats) config.

**Comment by benbro** [comment]
A working [example](https://codepen.io/anon/pen/BZVjNE).

**Comment by jsmelcher** [comment]
Thank you @benbro . I needed it to change to markdown, and when I typed 1. it stylized it and got rid of the '1.' in text, but this is what I needed.
