### ISSUE TITLE
Quill isn't working with Web Components and ShadowDOM

### ISSUE THREAD

**Issue by pkaske** [quilljs/quill#1563]
I'm trying to use quill inside a web component with [ShadowDOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM) but currently this seems to be really broken.

See this [codepen](https://codepen.io/anon/pen/YQvqVz)

I've commented the toolbar and palceholder out, because they're not working at all. The themes is all over the place.

There are probably many places that need modification to make quill work like expected inside web components (or more precise ShadowDOM).

For starters the code would need to look for the right root (#document or #shadowroot) to operate in.

For example `getNativeRange` needs to look out if the editor is inside SD with something like:
```js
getNativeRange() {
    // Instead of document.getSelection()
    let selection = this.root.getRootNode().getSelection();
    ...
}
```

With the web component spec at 1.0 and most major browsers in the progress of shipping them, I figured I bring this into attention.

**Comment by jhchen** [comment]
#1472
