### ISSUE TITLE
Bubble theme: impossible to open links in new page

### ISSUE THREAD

**Issue by guillaumepotier** [quilljs/quill#1565]
With bubble theme, when one insert a link, it creates it. Then, impossible to open that link. Clicking on it does nothing, nor in the bubble tooltip.

**Steps for Reproduction**

1. Visit quilljs.com
2. Use bubble theme example (left)
3. Try to click on any link

**Expected behavior**:

I would expect that clicking on the bubble (or directly on the link in the page) would open a new tab and get me there

**Actual behavior**:

Nothing happens

**Platforms**:

On my chrome `Version 59.0.3071.115 (Official Build) (64-bit)` for mac at least

**Version**:

`1.2.6`

**Comment by jhchen** [comment]
The bubble link tooltip is currently a display only tooltip. If you'd like to help add link navigation functionality, taking a look at how it's implemented in `themes/bubble.js` and `assets/bubble.styl` is a good place to start.

**Comment by guillaumepotier** [comment]
Hi @jhchen,

Thanks for your answer. I pulled down the repo and started working on it. Unless I realized

1) It would take way too much time for me to dive into Theme, UI, Tooltip, etc.. to replace a mere css selector by something evolved as snow theme (+ tests!) 
2) In our product, we decided to fix it independently of theme, by directly allowing clicking on link in the editor. I use a custom module I registered that listen for every `selection-change` and open link if `formats/link`

I don't think 2) would be a direction you'd share for Quill right? Otherwise, you'd already allowed the click directly, in snow or bubble?

Since I'm not going into 1) maybe someone could grab this issue later. Maybe close it meanwhile.

On a sidenote, I'm not sure it is a "feature" rather than a "bug", this is quite disturbing to have links (with target _blank and all) in the editor, and no way to open them other than copy-pasting it or right-click-open-in-a-new-tab :)

Best

**Comment by jhchen** [comment]
It is far easier to spend other people's time than one's own. I have my own list of priorities for Quill and as an open source project it can only be sustainable if people work on the things that matter for their use cases. You are correct I do not agree with 2) as I think users should be able to click in the middle of a link to edit it. The difference between a bug and feature often depends on one's perspective of what is acceptable and/or urgent. Again I have made my own determination but it sounds like this is not that important for you either.

**Comment by guillaumepotier** [comment]
I understand perfectly, did not wanted to be rude or something in my previous message. As I also owned a OS project and I perfectly understand how you have to sort priorities.

Be sure I'll try my best to contribute here since I'm using now Quill and that it gonna be the major part of our application.

Just you're right, doing an edit/click tooltip like for snow theme is not my priority too.

Best
