### ISSUE TITLE
Inline styling lost after loading/pasting html

### ISSUE THREAD

**Issue by drego** [quilljs/quill#1566]
Hi!
I'm currently trying to use Quill to create an editor and be able to format an email in HTML.
In order to allow the styling of the email content I'm using only inline styling attributes instead of the quill classes.
However, when I try to load or paste the html content into the editor, some of the inline styles are removed. I noticed that some of the inline styles (like `color`, `background-color`,` text-align`) are kept but others are just removed (for instance `font-family`, `text-indent`).
Is there any reason for this to happen? Why does this happen just for some types of inline styles?
Is there any way to overcome this problem?

**Comment by drego** [comment]
Also, there are some fonts that are not removed from the inline styling. For instance:
- Impact, Charcoal, sans-serif
- Tahoma, Geneva, sans-serif
- Verdana, Geneva, sans-serif

For other fonts, they are just removed from the inline style. For instance:
- Arial, Helvetica, sans-serif
- "Arial Black", Gadget, sans-serif
- "Comic Sans MS", cursive, sans-serif
- "Lucida Sans Unicode", "Lucida Grande", sans-serif
- "Trebuchet MS", Helvetica, sans-serif

All this mentioned fonts are safe fonts according to [this](https://www.w3schools.com/cssref/css_websafe_fonts.asp), so I don't understand why some work and some don't...

**Comment by jhchen** [comment]
Please fill out the Issue Template you were presented with when the "New Issue" button was clicked. It is otherwise very hard to figure out what is being talked about.
