### ISSUE TITLE
CSS Resize

### ISSUE THREAD

**Issue by QuinDennis** [quilljs/quill#1567]
Making quill respond to CSS resize

**Steps for Reproduction**
place quill #editor in a div with 'resize: both; overflow: auto;....'

**Expected behavior**:
expect editor and toolbar to resize when the enclosing div is resized

**Actual behavior**:
quill toolbar doesn't change;
editor body resizes vertically, not horizontally

**Platforms**:
Ubuntu17, Chrome 59.0.3071.115

**Version**:  1.2.6

**Comment by jhchen** [comment]
The word "responsive" carries particular meaning in web development, which I don't think is what you are talking about here. This is specifically about the CSS resize feature.

**Comment by jfradley** [comment]
A key point is it doesn't resize properly horizontally but does vertically. "CSS horizontal resizing not working" might be a better title.
