### ISSUE TITLE
Preserving active selection when contents are updated

### ISSUE THREAD

**Issue by callum** [quilljs/quill#1569]
I'm currently implementing something that applies a format as the selection changes in realtime. I'm finding that the state of the active selection is interrupted somehow causing it to break when moving back beyond the origin of the selection.

**Steps for reproduction**:
1. Visit https://codepen.io/anon/pen/BZPJpv
2. Begin selecting text
3. Move selection to before the starting point

**Expected behavior**:
Normal selection behaviour is maintained when moving in either direction from the starting point

**Actual behavior**:
Selection is collapsed when moved before the starting point

**Platforms**:
Google Chrome 59
macOS Sierra 10.12.5

**Version**:
1.2.6

**Comment by jhchen** [comment]
Can you be explicit in the steps for reproduction and expected and actual behavior? Ex. Place cursor on this specific word, select left 5 characters, etc. 

The issue right now is I get the general impression the demo code doesn't really work but at the same time I'm not sure what it's supposed to do and if Quill is supposed to just handle these cases for your demo and what that would even mean.

**Comment by callum** [comment]
Hey @jhchen - thanks for coming back. Let me have another go at explaining...

---

**Steps to reproduce:**
1. Place the caret at the beginning of the word 'suscipit' (index 22).
2. Mouse down and expand the selection to the whole word (index 30) and note that the selection appears as normal with a blue background.
3. With the mouse still held down, drag to the left so the destination index of the selection is less than the origin index (e.g. beginning of the word 'elit', index 14) and see that the selection is collapsed (length 0) and shows just the caret with no blue background.

**Expected behaviour:**
The selection does not collapse and maintains its length, adjusting its index accordingly. (I believe this involves swapping the value of length and index.)

**Actual behaviour:**
The selection is collapsed and shows just the caret with no blue background.

---

If the content isn't changed during selection this works absolutely as expected.

**Comment by jhchen** [comment]
Thank you for the clarification. I believe what is happening is Quill's selection implementation does not have the concept of forwards or backwards. When Quill modifies the DOM it will save and restore the selection but always in the forward direction. This would explain why dragging forwards in this example works just fine but backwards does not.

I'm not sure supporting backwards selections is a complexity I want to introduce into Quill core at the moment so the suggestion I would make is handle the save and restore of the selection in your application using native selection APIs. If you'd like feel free to create a separate feature request issue to support backwards selection ranges. If enough support and use cases are gathered from the community Quill may reconsider official core support.
