### ISSUE TITLE
Scrolling issue when quill has `position: absolute`

### ISSUE THREAD

**Issue by madbence** [quilljs/quill#1571]
Quill goes crazy when the editor is positioned with `position: absolute` (or it has a parent that has absolute position)

**Steps for Reproduction**

1. Visit https://codepen.io/lennoff/pen/zzLjaZ
2. Press enter around the 60th line

**Expected behavior**:

Quill should not scroll to the bottom of the page, the cursor should stay visible.

**Actual behavior**:

Quill jumps to the bottom of the page

**Platforms**:

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36`

**Version**:

1.2.6

**Comment by jhchen** [comment]
You're also changing the overflow behavior in CSS which is conflating. I assume it's to get Quill to autogrow? There's a specific way to do that as seen in this [example](https://quilljs.com/playground/#autogrow-height). If there's some other reason, please clarify.

**Comment by madbence** [comment]
https://codepen.io/lennoff/pen/MoqoqZ

it seems that the problem is when you set `body` as the `scrollingContainer`. might be related to #1570

**Comment by jhchen** [comment]
Can you not just add the extra scrollingContainer div in your application? What's the use case in requiring body to be the scroller?

**Comment by madbence** [comment]
i managed to remove the `position: absolute` in our app, so it's not a problem for us anymore. feel free to close this issue if you think that it's _wontfix_!
