### ISSUE TITLE
No innerHTML for a custom picker's ql-picker-item

### ISSUE THREAD

**Issue by neversun** [quilljs/quill#1572]
Using a not built-in `<select>` class like `<select class="ql-emoji">` with an option like `<option value=":D" label=":D" title=":D">:D</option>` I expect the created `<span class=".ql-picker-item"></span>` to have some kind of content in it. Currently it is just empty.

Is there currently any (built-in) way to provide an innerHTML based on the `<option>` tag?

**Steps for Reproduction**

1. Visit https://codepen.io/neversun/pen/dRqvVV/
2. Click on `:)` select-element to open picker

**Expected behavior**:
![image](https://user-images.githubusercontent.com/9157500/27949452-0ea4c600-62fe-11e7-9b10-f1e92f9c057f.png)

Picker displayed with all items and some kind of content within the `.ql-picker-item`'s innerHTML. Just like the [ui/color-picker](https://github.com/quilljs/quill/blob/master/ui/color-picker.js) does for background-color (via CSS styling).

**Actual behavior**:
![image](https://user-images.githubusercontent.com/9157500/27949368-c2cd5242-62fd-11e7-8fe4-1eed63a75d8a.png)

Picker displayed with all items, but no innerHTML/content on these elements.

Can be fixed by either CSS (with a fixed value) or JS (`element.innerHTML = element.getAttribute('data-value')`). Both "fixes" can be found in CodePen.
```css
.ql-picker-item:after {
  content: "!?"
}
```

```javascript
const options = $(".ql-emoji.ql-picker")[0].querySelectorAll(".ql-picker-item");
options.forEach(option => {
  const value = option.getAttribute("data-value");
  if (value) {
    option.innerHTML = value;
  }
});
```

**Platforms**:

- Vivaldi 1.10.867.42 (Stable channel) (64-bit) - Mac OS X
- Chrome 59.0.3071.115 (Official Build) (64-bit) - Mac OS X

**Version**:

1.2.6

**Comment by alexkrolick** [comment]
For reference, this is where the icon-toolbar mapping happens: https://github.com/quilljs/quill/blob/develop/ui/icons.js

**Comment by jhchen** [comment]
This is not presently a feature of Quill. If you'd like to help add a good place to start looking is how the current pickers work in `ui/`.

**Comment by andresinaka** [comment]
@jhchen @alexkrolick guys, I'm trying to do exactly this. Is there a new way of doing this or I have to follow @neversun way of doing it??

**Comment by jhchen** [comment]
I don't believe there have been updates.
