### ISSUE TITLE
Convert to a web component

### ISSUE THREAD

**Issue by lastmjs** [quilljs/quill#1574]
My opinion is that Quill must become a web component. It would make it so much easier to work with, and it would then become interoperable across all browsers and frameworks. No initialization script with separate style and script tags...unfortunately, because Quill was so difficult to try and integrate into my web components project, I decided to give up for now.

I hope Quill will become a web component in the future.

**Comment by jhchen** [comment]
Kind of hard to become interoperable across all browsers and frameworks through Web Components when the browsers themselves have not even implemented it. I see you posted a comment in the main PR for web components. It would be more productive to help than just open a duplicate to complain.

**Comment by lastmjs** [comment]
Sorry to complain, I think Quill is awesome, I mostly want to add my voice to moving to web components to prepare for the future, which I believe will be web components.

**Comment by robhicks** [comment]
Currently, I don't think Quill can be put into a web component which uses shadowDOM. It makes some assumptions about being able to access DOM elements using document, which won't work with shadowDOM. It would be much better if Quill provided as part of its configuration api to provide it the proper DOM context.
