### ISSUE TITLE
relate blots to getContents?

### ISSUE THREAD

**Issue by QuinDennis** [quilljs/quill#1575]
[Describe the issue]
getContents() returns ops[], which have attributes[]
'selection-change' returns blot[]
How can a blot[] be related to an ops[] so that attributes[] can be accessed?

**Steps for Reproduction**

1. quill.insertText(0,'Stuff',{'color':'blue'})
2. quill.on('selection-change', function(rng,oldRng,src) {
        if (rng)
           var blot = quill.getLeaf(rng.index)   // blot[0] has no relation to ops[]
    }
3. Step Three

**Expected behavior**:
          some way to get to attributes[] of selected blot
**Actual behavior**:

**Platforms**:       Ubuntu17, Chrome 59.0.3071.115

**Version**:           1.2.6

**Comment by jhchen** [comment]
I think you want [getFormat()](http://quilljs.com/docs/api/#getformat)? If not please provide an explicit example. Not sure what you mean by "blot[] be related to an ops[]" either. Multiple blots may be responsible for a single ops item.
