### ISSUE TITLE
Dynamically change the editor theme.

### ISSUE THREAD

**Issue by mohakmaheshwari** [quilljs/quill#1578]
Is there any way that the theme can be switched to and fro between 'snow' and 'bubble' without disturbing the text area ?

I want to create a button which can hide the toolbar in snow theme and wish to make it appear it just like in bubble theme. But then I also want to be able to switch back whenever desired.

**Comment by jhchen** [comment]
There is not. The homepage https://quilljs.com approximates this by just creating multiple editors and syncing the content. Take a look at that through your favorite browser inspecting tool or the code in the docs/ folder.

**Comment by ZiadJ** [comment]
Would be nice to have a way to do this by just clicking an assigned button.
