### ISSUE TITLE
Extra new line added when copy/pasting from Quill.JS to a notepad

### ISSUE THREAD

**Issue by Natim** [quilljs/quill#1579]
**Steps for Reproduction**

1. Visit https://quilljs.com/playground/
2. Enter a multiline text (You can use the Expected behavior content)
3. Copy the content of the pad and paste it somewhere (The github comment textarea for instance)

**Expected behavior**:

The content of the pad is pasted as is:

```
Type something
And then something else
And then again something
```

**Actual behavior**:

A new line is inserted between each lines:

```
Type something

And then something else

And then again something
```

**Platforms**:

[Firefox](http://nightly.mozilla.org/) / Ubuntu

**Version**:

1.2.6

**Comment by jhchen** [comment]
Can you check what HTML is being copied? All Quill can control is what it outputs, not how Notepad or any other application interprets that.

**Comment by Natim** [comment]
Yes it seems that the fact a `<p>` is pasted into text as two linebreaks.
A way to fix that would be to allow `<br/>` instead of `<p>` everywhere.

**Comment by jhchen** [comment]
What HTML is being copied from Chrome? It does not appear Chrome has this issue.

**Comment by Natim** [comment]
You are right, I can't reproduce the error with Chrome, but I can with Firefox.

**Comment by Natim** [comment]
For instance this HTML:
```
<p>Hello</p>
<p>World</p>
```

**Comment by Natim** [comment]
This fixes the issue https://github.com/quilljs/quill/issues/861
