### ISSUE TITLE
Overriding hotKeys in keyboard module?

### ISSUE THREAD

**Issue by thejchap** [quilljs/quill#158]
What is the recommended way for overriding predefined hotkeys? Tab for example...it appears the callback passed to `addHotkey` gets executed in tandem with any that have already been defined.

My particular use case being tab-completion, ie if a suggested item is available, tab should select that item, otherwise proceed with the predefined behavior.

Maybe callbacks defined with `addHotkey` get executed first and if any return false then the chain stops? Something like that?

**Comment by unhammer** [comment]
What's the current solution to this? The docs at http://quilljs.com/docs/modules/keyboard/#configuration don't show how to add a keybinding for tab to act as the "prioritised" handler that can then decide whether or not to propagate to the built-in handlers.

**Comment by jhchen** [comment]
To overwrite the handler you would define a binding in the configuration with the same name as the default. The default behaviors are either simple or essential so there's not an API to insert a binding before a default one to be prioritized like I think you are suggesting.

**Comment by unhammer** [comment]
OK, I just did
```
quill.keyboard.addBinding({
  key: 9,
}, function(range, context) {
  console.log("tab!");
  return true;
});
quill.keyboard.bindings[9].unshift(quill.keyboard.bindings[9].pop())
```
An optional `prepend` bool-arg to `addBinding` might be useful? Unless this kind of thing leads to more breakage than it's worth :-)

**Comment by julianlam** [comment]
@unhammer For what it's worth, your trick works quite well to override a default binding without actually removing the default behaviour completely. My use case was exactly the same as yours, I wanted to integrate a textcomplete dropdown.

**Comment by satyapendem** [comment]
Hi,

How i can override the **CMD+B**. And I want to make changes like when user selects a text and **CMD+B** then it should convert to markdow.

**Comment by trainbolt** [comment]
> Hi,
> 
> How i can override the **CMD+B**. And I want to make changes like when user selects a text and **CMD+B** then it should convert to markdow.

Did you get this sorted?

**Comment by yesyves** [comment]
[https://quilljs.com/docs/modules/keyboard/](https://quilljs.com/docs/modules/keyboard/)
