### ISSUE TITLE
getSelection returning wrong index for first character inside text-change event

### ISSUE THREAD

**Issue by mitjaz** [quilljs/quill#1583]
After typing first character inside Quill editor, getSelection will return wrong index inside text-change event. Index that's returned is 0, although it should be 1. Note that after typing the second character returned index is 2. So the sequence of characters is 0 0 2. Note that when deleting characters sequence is correct. 2 1 0.

**Steps for Reproduction**

1. Visit this [https://jsfiddle.net/p3zu2qnc/4/](https://jsfiddle.net/p3zu2qnc/4/)
2. Type some characters

**Expected behavior**:
getSelection index to  return 1 after first character, 2 after second ...

**Actual behavior**:
getSelection index returns 0 after first character and 2 after second character

**Platforms**:
Chrome 59.0.3071.115
MacOs 10.12.5

**Version**:
1.2.6

**Comment by jhchen** [comment]
From the docs for [text-change](https://quilljs.com/docs/api/#text-change):

> Changes to text may cause changes to the selection (ex. typing advances the cursor), however during the text-change handler, the selection is not yet up updated, and native browser behavior may place it in an inconsistent state. Use selection-change or editor-change for reliable selection updates.
