### ISSUE TITLE
Japanese input on Android device

### ISSUE THREAD

**Issue by hiendistance** [quilljs/quill#1585]
When I type the line, the first letter has been entered independently

**Steps for Reproduction**
1. Visit quilljs.com on Android device, Chrome v.43
2. Input "かぞくでの"

**Expected behavior**:
Display suggest "家族での"、line 1
**Actual behavior**:
Display "かぞくでの"、line 2
"か" letter has been entered independently

**Platforms**:
Sony Xperia C6602
Android 5.1.1

![ezgif-4-47f5a4dfdd](https://user-images.githubusercontent.com/30113675/28114156-bfbecd8a-6729-11e7-86ac-3cfd5f21f0d3.gif)

**Comment by jhchen** [comment]
Can you try with the latest versions of Chrome 58 or 59? Version 43 is quite old an no longer supported.
