### ISSUE TITLE
Add persistent attributes to blocks

### ISSUE THREAD

**Issue by jhartma** [quilljs/quill#1586]
Hi there, thanks for the great editor!

I am new to Quill and I am struggling with adding a custom block type. I basically want to add a unique id tag to each block, e.g. h1 or p, when they are created. This I got working with
```js
class HeaderBlot extends Block {
  static create(value) {
    let node = super.create(value);
    node.setAttribute('id', Math.random());
    return node;
  }
  static formats(node) {
    return HeaderBlot.tagName.indexOf(node.tagName) + 1;
  }
}
```
Now, the id tag should persist when the block type changes, e.g. from h1 to h2. Ideally, when the block is split, the new block would also get a unique id. How would I start to implement this?

**Comment by jhartma** [comment]
Okay, solved it. Here is how

1. Define a CustomBlock that replaces the p block and generates a unique id for each p tag
```js
const Quill = require("quill")
const Block = Quill.import("blots/block")
const uuid = require("uuid")

class CustomBlock extends Block {
  static create() {
    const node = super.create()
    node.setAttribute("id", uuid.v4())
    return node
  }

  split(index, force = false) {
    if (force && (index === 0 || index >= this.length() - 1)) {
      const clone = this.clone()
      clone.domNode.id = uuid.v4()
      if (index === 0) {
        this.parent.insertBefore(clone, this)
        return this
      }
      this.parent.insertBefore(clone, this.next)
      return clone
    }
    const next = super.split(index, force)
    next.domNode.id = uuid.v4()
    this.cache = {}
    return next
  }
}
CustomBlock.blotName = "block"
CustomBlock.tagName = "p"
```
2. Add an attributor that adds header classes which can be css styled
```js
const Quill = require("quill")
const Parchment = Quill.import("parchment")

module.exports = new Parchment.Attributor.Class("custom", "header", {
  scope: Parchment.Scope.BLOCK,
})
```

**Comment by ericls** [comment]
Having the same issue.
If you load from a Delta the uuids saved in the delta would be replaced by new uuids.

**Comment by ryaninvents** [comment]
Yes, the above solution attaches the IDs to the DOM nodes, but does not associate them in the document. I have a [half-baked CodePen](https://codepen.io/ryaninvents/pen/ExEqqNQ) that can be used to refine this idea
