### ISSUE TITLE
Incompatible with Vue.js

### ISSUE THREAD

**Issue by TylerMills** [quilljs/quill#1587]
**Steps for Reproduction**

1. Visit https://jsfiddle.net/0xxy9y0o/1/ and run
2. Verify that there are no debug logs after initial load and no events logged and you are unable to utilize toolbar or update formatting
3. Visit https://jsfiddle.net/0xxy9y0o/2/ and run
4. Verify that removing instantiation of Vue.js allows proper use

**Expected behavior**: You are able to utilize Quill editors inside Vue.js containers

**Actual behavior**: Unable to interact with toolbar, no events or debug logs are created.

**Platforms**: Google Chrome 59.0.3071.115, macOS High Sierra

**Version**: 1.2.6

**Comment by jhchen** [comment]
Check out https://github.com/surmon-china/vue-quill-editor, the current top Google search result for "vue quill" ...

**Comment by TylerMills** [comment]
It seems unreasonable to require importing a library as a solution, especially for such a basic example as above, where I'm not using templates and components.

**Comment by jhchen** [comment]
It is entirely reasonable two independent and complex libraries don't "just work" with each other out of the box in the precise way you assume. It may be the case a separate library is *not* required but someone has already done the hard work of making it easy. It only has 5 open issues for a 700+ star project so unclear about the numerous blocking issues comment. I'm sorry that's not enough for you, but if you want to make it even easier, feel free to contribute.

**Comment by luthfimasruri** [comment]
**Quill Editor For Vue 3 Component**
Check out [https://github.com/vueup/vue-quill](https://github.com/vueup/vue-quill) if you're using Vue 3
