### ISSUE TITLE
Override DOM.DEFAULT_BLOCK_TAG?

### ISSUE THREAD

**Issue by whather** [quilljs/quill#159]
We're using Quill to produce email HTML and seems like a lot of email clients (at least Gmail) have excessive padding on paragraph tags. Wrapping lines in a <div/> instead of a <p/> seems to be the fix. 

Would be great to have the ability to override DOM.DEFAULT_BLOCK_TAG

**Comment by pmarreck** [comment]
Quill is still using p tags when you hit Return in an editor, and it's (still) messing up my attempts to have people edit an html email signature (due to the aforementioned issues)... what's the deal?
