### ISSUE TITLE
Selected text loses highlight

### ISSUE THREAD

**Issue by factsfinder** [quilljs/quill#1591]
When I select some text and try to change the text format/font, the text loses highlight. But in normal, the text should be highlighted all the time. I might be missing something here. 
Thanks for the help in advance.

1) Visit http://quilljs.com/playground/
2) Type some text inside the editor.
3) Select/highlight the entire text and try to change font.
4) Click on font picker on toolbar
 
Expected behaviour:
The text should be highlighted, when trying to select a font.

Actual behaviour
The text loses its highlight when trying to select a font. But regains its highlight once a font is selected.

**Comment by benbro** [comment]
Please provide all the info requested in the issue template.

**Comment by kurtwilliam** [comment]
I am having this issue too - it can be confusing for users when the text selection goes away. It seems to happen for any select tags with a drop-down menu. Is there any known fix for this?

Thank you.

**Comment by shuckster** [comment]
Same issue here.

**Comment by jhchen** [comment]
This is a duplicate #879.

**Comment by jurerick** [comment]
Got the same issue. In my case, I'm not able to select the text from the start. Holding the text for longer seconds will appear the quill bubble but will disappear upon release of my finger from iphone screen.

**Comment by jguitarz** [comment]
Noticing this same issue on any `.ql-picker` after the first selection change is made.

There should be a class `.ql-selected` applied to the active item in the dropdown but it gets removed everytime I open the dropdown. Only on the initial load can you see the `.ql-selected` class correctly applied. It does add the class when you make a selection but opening the dropdown again removes it for some reason.

What is triggering it to remove the class?

**Comment by sachin-smartfood** [comment]
what is the solution of this issue

**Comment by ujjwalsharma98** [comment]
This worked for me!

const quillRef = useRef();

useEffect(() => {
    // To keep the text highlighted
    if (quillRef.current) {
      const quill = quillRef.current.getEditor();
      const handleClickOutside = (event) => {
        if (!quill.container.contains(event.target)) {
          quill.format('background', false);
        }
      };
      quill.on('selection-change', function (range, oldRange, source) {
        if (range !== null) {
          quill.formatText(range.index, range.length, 'background', '#ACCEF7');
        } if (range && oldRange && range.length == 0) {
          quill.formatText(oldRange.index, oldRange.length, 'background', false);
        }
      });
      document.addEventListener('click', handleClickOutside);
      return () => {
        document.removeEventListener('click', handleClickOutside);
      };
    }
  }, []);
  
   <ReactQuill
          modules={modules}
          theme='snow'
          ref={quillRef}
        />

**Comment by MiaChanQ** [comment]
Same issue when quill is used in vue, clicking the toolbar dropdown button will cause quill editor to lose focus/highlights on text

JS solution -- add event listener:

```
      this.editor = new Quill(this.$refs.editorContainer, {
        theme: 'snow',
        modules: {
          toolbar: {
            container: toolbarOptions
          }
        }
      })
      ......
      this.addDropdownEventListeners()
      
      addDropdownEventListeners() {
      const toolbar = this.editor.getModule('toolbar')
      const dropdowns = toolbar.container.querySelectorAll('.ql-picker')
      dropdowns.forEach((dropdown) => {
        dropdown.addEventListener('mousedown', this.handleDropdownClick)
      })
    }
    
    handleDropdownClick(event) {
      event.preventDefault()
      setTimeout(() => {
        this.editor.focus()
      }, 0)
    }
      
```
