### ISSUE TITLE
After 1.3.0 updated I started getting these console errors "Cannot read property range of undefined"

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#1593]
For some reason after updating to the most recent quill 1.3.0 from 1.2.6 I started noticing console errors when I entered a new line and started to type. 

"Cannot read property range of undefined"

And it pointed to this line

https://github.com/quilljs/quill/blob/develop/blots/cursor.js#L103

it seems that context is undefined

not sure why this started popping up but I did want to mention it just incase. 

I do not notice this issue in the quill playground. 

Could this be related to the scrollingContainer selector not found? 

**Platforms**:

Chrome on Mac OSX

Include browser, operating system and respective versions

**Version**:

1.3.0

**Comment by jhchen** [comment]
Hmm well the whole line is `if (range && context) context.range = range;` so it's not possible for context to not be defined. Maybe sourcemaps is pointing to the wrong line?

**Comment by sferoze** [comment]
@jhchen oops sorry I had linked to my fork of quill where I added that change

here is where it pointed to in the original quill

https://github.com/quilljs/quill/blob/develop/blots/cursor.js#L103

**Comment by jhchen** [comment]
Okay makes sense -- can you post a stack trace? The context should always be provided and is defaulted to {} at a higher layer so the issue would be that is not being passed on somewhere.

**Comment by edisonator** [comment]
```javascript
cursor.js:110 Uncaught TypeError: Cannot set property 'range' of undefined
  at Cursor.update (cursor.js:110)
  at eval (parchment.js:1406)
  at Array.forEach (<anonymous>)
  at ScrollBlot.update (parchment.js:1403)
  at Scroll.update (scroll.js:160)
  at MutationObserver.eval (parchment.js:1292)
```

the function `update` is called in `parchment.js` and I'v seen that just one parameter is sent in.

the way to reproduce is:
1. input some words
2. input `enter` at the end of the line
3. input anything will trigger the error

**Comment by edisonator** [comment]
I'v tried to upgrade the `parchment` and now I'm on `1.1.0`, but the error is still there.
I'v tried to write the function `update(mutations, context)` to `update(mutations, context = {})` but it will trigger other bugs, just like after inputting `enter`, the cursor will return to the end of last line, and so on.

**Comment by jhchen** [comment]
Thanks for the stack trace @edisonator . Unfortunately the line numbers do not correspond to source so I'm not going to be able to track things down with it. Not sure where eval is coming from either since Parchment does not call eval.

The steps for reproduction are also not reproducible for me.

**Comment by edisonator** [comment]
Well, I'm so sorry that it may be a little misunderstanding episode.
I'v upgrade my parchment to `1.1.0` but the file in my webpack-dev-server is `1.0.9` yet.
After I solved this problem, it works well.

@sferoze I consider that you can upgrade your `parchment` to `1.1.0`.

**Comment by edisonator** [comment]
Well, I'm so sorry that it may be a little misunderstanding episode.
I'v upgrade my parchment to 1.1.0 but the file in my webpack-dev-server is 1.0.9 yet.
After I solved this problem, it works well.

@sferoze I consider that you can upgrade your parchment to 1.1.0.
