### ISSUE TITLE
Placeholder absent when pad is emptied

### ISSUE THREAD

**Issue by Natim** [quilljs/quill#1594]
**Steps for Reproduction**

1. Visit https://quilljs.com/playground/
2. The placeholder is present
3. Type something and delete it

**Expected behavior**:

The placeholder comes back

**Actual behavior**:

The placeholder doesn't show.

**Platforms**:

Firefox

**Version**:

1.3.0

However it does work with Quill 1.2.6

**Comment by eamodio** [comment]
@jhchen will there be a `1.3.1` (or something) release with this fix coming very soon? Would love to not maintain a fork if so (this is a blocker for us)

**Comment by jhchen** [comment]
Yes trying to get a few other bugs in but will release this weekend.

**Comment by Natim** [comment]
@eamodio do you have a fix for that in your fork already?

**Comment by eamodio** [comment]
@Natim I haven't forked it (since the next release is nice and close), but the above commit should have fixed it

**Comment by Natim** [comment]
Oh neat I missed it :) thanks https://github.com/quilljs/quill/commit/eb7f33bb9fbb6b7222840571b8cad06481dfb2dd

**Comment by StreetStrider** [comment]
Can anyone confirm that this works on `1.3.6`? I setup `placeholder` but it doesn't show up when editor is empty. I'm using minimal css scheme.

**Comment by mrowles** [comment]
Still doesn't work, using `^1.3.6` here

**Comment by GJMAC** [comment]
Is there going to be a fix applied to this?  I just tried to assign a placeholder, but still nothing shows when editor is empty.
