### ISSUE TITLE
Quill instance inside custom blot class

### ISSUE THREAD

**Issue by henriqemalheiros** [quilljs/quill#1599]
I'm creating a custom blot for images. This blot has a wrapper div inside. When the user clicks inside, I want to set a new selection. For this, I must have access to the current Quill instance of the clicked blot. How can I achieve this _inside_ the new blot class?

**Comment by abramz** [comment]
Since we don't have direct access to the `new` call, I think it is a bit of a hack. But I solved this by passing `quill` as a field in `data` when calling `insertEmbed` or creating a `delta`

**Comment by henriqemalheiros** [comment]
@abramz that is a pretty doable workaround! Thanks!
