### ISSUE TITLE
Problems with Quill and Firebase

### ISSUE THREAD

**Issue by journalindoor** [quilljs/quill#1602]
I'm using Firebase to store the data of my project.

It's a Editor of documents with pre-formatted styles to be applied using custom buttons.

**The steps:** 

1. Write the Text;
2. Select the Text;
3. Click on the custom button.

The code will be like this:

`<customTag class="customTag">Example Text</customTag>`

This code will be sent to Firebase without problem.

**The problem is:**

I'm using Javascript to make customizations in the <customTag> element when the user click on them, example:

_Before the click event:_
`<customTag class="customTag">Example Text</customTag>`

_After the click event:_
`<customTag class="customTag" style="background:red;">Example Text</customTag>`

The customization goes to Firebase like this:

```
<span style="background:red;">
<customTag class="customTag" style="background:red;">Example Text</customTag>
</span>
```

When i reload the Editor the code come from Firebase like this:

```
<span style="background:red;">
<customTag class="customTag">Example Text</customTag>
</span>

```

**Comment by benbro** [comment]
"background:red;" isn't valid CSS. you probably mean "background-color: red;"
