### ISSUE TITLE
ERROR Error: Formula module requires KaTeX.     at new Formula (quill.js?c8f1:10718)

### ISSUE THREAD

**Issue by TaylorPzreal** [quilljs/quill#1604]
BlogEditComponent.html:1 ERROR Error: Formula module requires KaTeX.
    at new Formula (quill.js?c8f1:10718)
    at SnowTheme.addModule (quill.js?c8f1:5120)
    at SnowTheme.addModule (quill.js?c8f1:6546)
    at eval (quill.js?c8f1:5112)
    at Array.forEach (<anonymous>)
    at SnowTheme.init (quill.js?c8f1:5110)
    at new Quill (quill.js?c8f1:1242)
... ...

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Actual behavior**:

**Platforms**:
Linux Mint18, vscode,angular4,typescript,quill@1.3.0,Chrome@latest

**Comment by TaylorPzreal** [comment]
i imported katex:
<script src="katex.js"></script>

or

import 'katex';

are not success.

**Comment by benbro** [comment]
Did you download katex locally?
You need to load it from you server or CDN. It's not included in Quill.
https://codepen.io/quill/pen/KzZqZx

**Comment by TaylorPzreal** [comment]
@benbro thx, CDN is success

**Comment by 91iron** [comment]
xzczxcz
