### ISSUE TITLE
Ember + Quill array find polyfill conflict 

### ISSUE THREAD

**Issue by jgelens** [quilljs/quill#1607]
When using Quill on a site running Ember in IE11 (and possibly other older browsers). The Ember polyfill for `Array.prototype.find` is applied first. But Quill is not able to use this one and fails to run correctly.

The error in the IE debugger:
```
TypeError: Object doesn't support property or method 'nextObject'
   at find (http://10.0.1.10:4200/assets/vendor.js:55196:9)
   at value (http://10.0.1.10:4200/assets/vendor.js:73492:140500)
   at Anonymous function (http://10.0.1.10:4200/assets/vendor.js:73492:140134)
   at e (http://10.0.1.10:4200/assets/vendor.js:73492:139892)
   at value (http://10.0.1.10:4200/assets/vendor.js:73492:89042)
   at value (http://10.0.1.10:4200/assets/vendor.js:73492:103396)
   at Anonymous function (http://10.0.1.10:4200/assets/vendor.js:73492:88938)
   at value (http://10.0.1.10:4200/assets/vendor.js:73492:88864)
   at t (http://10.0.1.10:4200/assets/vendor.js:73492:24873)
   at didInsertElement (http://10.0.1.10:4200/assets/vendor.js:93749:7)
```
The polyfill in Ember can be found here: https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/mixins/enumerable.js#L503

It fails on this line in Quill toolbar.js:
```
 let format = [].find.call(input.classList, (className) => {
```

I tried to solve this issue myself, but the only way I found was updating the Quill source to copy the polyfill to `Array.prototype.find2` and use that instead in Quill. Which is obviously a really dirty hack but it works.

Does anyone have a different idea to solve or otherwise monkeypatch this?

**Platforms**: IE 11 and possibly other older browsers
**Version**: Quill 1.3.0

**Comment by shuckster** [comment]
I had a sort-of-similar issue with Prototype, and you can find the trail on this issue: https://github.com/quilljs/quill/issues/1261

**Comment by leimig** [comment]
Any news on this issue? I have the same problem

**Comment by KeerthiHarish** [comment]
Any update on this? I have attached the screenshot(IE) and the options I'm using in quill editor.

```
options: {
    theme: "snow",
    modules: {
      toolbar: [
        [{header: [2, 3, 4, false]}],
        ["bold", "italic", "underline", "strike"],
        [{"color": []}],
        [{"list": "ordered"}, {"list": "bullet"}],
        [{"indent": "-1"}, {"indent": "+1"}],
        [{"align": []}],
        ["link"],
        ["clean"]
      ]
    }
  }
```

![quill-editor](https://user-images.githubusercontent.com/14280256/45011703-7e152080-b031-11e8-90f9-43e5b5eb8fdc.png)

**Comment by benbro** [comment]
New browsers and libraries shouldn't require Array.prototype.find polyfill.
