### ISSUE TITLE
Pasting HTML content from copied data removes formatting

### ISSUE THREAD

**Issue by jbrooksuk** [quilljs/quill#161]
Sorry about the weird title.

We add some very basic HTML content into our database, it's effectively some bold tags wrapped around plain text.

It renders fine when it's pulled into Quill, but if you copy the content then paste it back in, it removes all of the line breaks.

See [this](https://dl.dropboxusercontent.com/u/7323096/Screeny%20Video%202%20Jul%202014%2020.38.14.mov) video for a better example.

**Comment by khizarmanzoor** [comment]
Steps to reproduce: 

1. Empty all editor text. 
2. Place one empty new-line at start.
3. Add some bullets.  (e.g. 2 or 3). any other format would work too :)
4. Select all content e.g. Ctrl+A and copy Ctrl + C.
5. Place some empty new lines at end of editor. 
6. Now paste content. 
7. Notice no formats to newly pasted content are applied. 


I've updated the jsfiddle http://jsfiddle.net/khizarmanzoor/Fend4/1/

**Comment by jhchen** [comment]
This actually seems like the issue from recent webkit changes #306.
