### ISSUE TITLE
Inline Display style is always removed

### ISSUE THREAD

**Issue by Humni** [quilljs/quill#1610]
**Steps for Reproduction**

1. Visit the [Codepen](https://codepen.io/humni/pen/OjPevJ)
2. Run the example
3. Note that the display style does not render on the object once the editor has initialized

**Expected behaviour**:
The inline display to remain on the image tag, due to the explicit allowance of the parchment attribute style
**Actual behaviour**:
The style is dropped from the image element
**Platforms**:
Chrome - Latest (untested on others), Windows 10

Include browser, operating system and respective versions

**Version**: 1.3.0

_Note: This issue came up when trying to use the Quill Image Resizer Module, as the resizer module for alignment uses inline styles_

**Comment by benbro** [comment]
See this comment for explanation:
https://github.com/quilljs/quill/issues/1325#issuecomment-282526907

**Comment by Humni** [comment]
@benbro While I understand that Quill strips content that it doesn't understand, I would have thought that registering the parchment style would allow for this inline style to be applied.

**Comment by benbro** [comment]
Probably removed by the Clipboard module which supports custom matchers.
What's the use case of including hidden image in a text editor?

**Comment by Humni** [comment]
I have tried with `display: inline` and `display:block` also without success. The `display:none` is just an example which is easier to see the result of.

**Comment by Humni** [comment]
Essentially, the goal is to be able to have `style="display: inline; float: right; margin: 0px 0px 1em 1em;"` on the image, which is applied by using https://github.com/kensnyder/quill-image-resize-module

**Comment by Humni** [comment]
This is a work around (see the comments), however, I believe that you should be able to enable these styles using the method specified in the CodePen https://github.com/kensnyder/quill-image-resize-module/issues/10

**Comment by NGyc** [comment]
怎么在编辑器中插入<div></div>标签，并给标签添加一个class，例如<div class='box'></div>
