### ISSUE TITLE
IE browser Freezes when using Japanese Hiragana Windows IME autosuggest in editor

### ISSUE THREAD

**Issue by sfdcrshah** [quilljs/quill#1611]
1. Enable [Japanese Hiragana IME](https://www.coscom.co.jp/learnjapanese801/msime_win8_en1.html)
2. Visit quilljs.com/playground
3. type "ultimate sosho" or "kem che"

Expected behavior:
result: うlちまてそしょ

Actual behavior:
result: IE browser freezes up, issue seems to be when there is autosuggest 

Platforms:
Windows 8.1/ IE 11

**Comment by vbhargavmbis** [comment]
I have observed a pattern with the words which cause the browser to freeze.
It looks like if the word contains a combination of Hiragana and Kanji or Katakana and Kanji, it causes the freeze.

Examples of such words:
kanji ->感じ
tanaka ->棚か
nishida ->西だ
okuremasu ->送れます
okane ->お金

**Comment by vbhargavmbis** [comment]
@jhchen Looks like this issue is on the radar. Do you have an ETA for a fix for this issue?

**Comment by vbhargavmbis** [comment]
@jhchen Would really love to know the progress on this issue and a timeframe for a fix.
This is affecting Japanese users on IE11. The entire browser goes into an unusable state, not just the editor. It is therefore is a high impact issue.

**Comment by EirikBirkeland** [comment]
Could be an unfulfilled condition in a while loop? Suggesting to add a break condition (e.g. break out after 1000 attempts)

**Comment by micmmakarov** [comment]
I have the same issue, maybe there's an ETA or how can I help?
