### ISSUE TITLE
NPM Quill breaks Meteor Testing With Mocha

### ISSUE THREAD

**Issue by SevenZark** [quilljs/quill#1612]
I understand this may be outside of the scope of what Quill wishes to support, but it does rule out Quill for those using Meteor, a very popular app framework.

**Steps for Reproduction**

1. In any Meteor app file, include Quill like so: import Quill from 'quill'
2. On command line, run meteor test: meteor test --driver-package practicalmeteor:mocha

**Expected behavior**: Tests run normally

**Actual behavior**: Get the following error: 

> ReferenceError: document is not defined
>     at Object.defineProperty.value (/Users/[redacted]/Source/[redacted]/node_modules/quill/dist/quill.js:6795:12)
>     at __webpack_require__ (/Users/[redacted]/Source/[redacted]/node_modules/quill/dist/quill.js:36:30)
>     at Object.defineProperty.value (/Users/[redacted]/Source/[redacted]/node_modules/quill/dist/quill.js:1109:1)
>     at __webpack_require__ (/Users/[redacted]/Source/[redacted]/node_modules/quill/dist/quill.js:36:30)
>     at Object.defineProperty.value (/Users/[redacted]/Source/[redacted]/node_modules/quill/dist/quill.js:5011:14)
>     at __webpack_require__ (/Users/[redacted]/Source/[redacted]/node_modules/quill/dist/quill.js:36:30)
>     at Object.defineProperty.value (/Users/[redacted]/Source/[redacted]/node_modules/quill/dist/quill.js:9554:13)
>     at __webpack_require__ (/Users/[redacted]/Source/[redacted]/node_modules/quill/dist/quill.js:36:30)
>     at Object.<anonymous> (/Users/[redacted]/Source/[redacted]/node_modules/quill/dist/quill.js:11266:18)
>     at __webpack_require__ (/Users/[redacted]/Source/[redacted]/node_modules/quill/dist/quill.js:36:30)
> Exited with code: 1
> 

**Platforms**: Meteor, Mocha, mac CLI (can't test if it happens in Windows)

**Quill Version**: 1.3.0

**Comment by jhchen** [comment]
What have you tried?

**Comment by SevenZark** [comment]
I really don't know what I could try, since just importing Quill causes the test to break. The only way I could fix it was to not import Quill, i.e. not use Quill.

**Comment by SevenZark** [comment]
It looks like simply having the Quill library present makes it want to immediately render something in the DOM. This won't work in a unit test since there is no actual DOM.

**Comment by SevenZark** [comment]
I should add, it does not matter what part of the code I am testing. In fact, I had no test code that dealt with the page where I wanted to use Quill. Just importing Quill in an app file caused the test process to bail and show the error.

**Comment by abramz** [comment]
Does mocha create a browser environment?

**Comment by SevenZark** [comment]
Not if you don't request one. Trouble is, I get this error when NOT loading templates in mocha; just loading server modules to test. The mere fact that the files exist in the project causes this error.

**Comment by abramz** [comment]
You are importing Quill though, @SevenZark, and that requires the DOM. As you can see [here](https://github.com/quilljs/quill/blob/05ab94c38b0c8711d5e673d2c341541a42132298/core/quill.js#L1), [`core/polyfill`](https://github.com/quilljs/quill/blob/05ab94c38b0c8711d5e673d2c341541a42132298/core/polyfill.js) is imported.

**Comment by jhchen** [comment]
Yes Quill needs the DOM to work. There are too many places where Quill references document that it would be silly to guard against for an environment (server node) it is not built for.

**Comment by SevenZark** [comment]
I'm sorry, this is a bit hard to describe, I guess. Of course I understand Quill needs the DOM to work when Quill is invoked, and in files in which it is called. Please try to understand, maybe don't assume I know nothing at all even if I don't know as much as you or much about the inner complexities of the libraries in question.

What I am trying to tell you is that I am NOT importing Quill in any of the modules I am TESTING. They are NOT loaded in my test script, period. Nonetheless, the test fails right on the command line when trying to invoke it, complaining about the error I mentioned. The fact that Quill appears in an import statement in a file at all in the source code causes this error to happen even when I AM NOT LOADING THAT FILE IN THE TEST. It seems that something about Quill loads very, very eagerly, in some way...? Whatever is going on, the fact is, if I wish to use best practices and test, I cannot have an import of Quill appear anywhere in any file in my code base, whether or not I am actually writing test script against that file.

This is not a problem with any other UI library I use, including React. I guess React must be doing something pretty "silly," then? And all those other libraries are just "silly" too?

As I stated in the original post, I fully realize this may be outside the scope of what Quill wishes to accommodate. That's fine. It's an external, sorta "dependency." But I thought it was surprising and thought it was worth mentioning. I don't have any expectation that it would be a high priority or anything. But please don't just call the concern "silly."

**Comment by abramz** [comment]
> Of course I understand Quill needs the DOM to work when Quill is invoked, and in files in which it is called.

@SevenZark, Quill requires the DOM when it is `import`ed, not when it is invoked. I think this may be what you are missing. The very fact that you `import` Quill, which you say you did in repro step #1, will cause breakage in an environment that does not provide the DOM. If you review the files in my previous reply, you will see that `core/polyfill` runs on **import**.

**Comment by SevenZark** [comment]
> Quill requires the DOM when it is imported, not when it is invoked. I think this may be what you are missing.

@abramz  Yeah, I do understand that. What I'm trying to tell you is that, for that reason, I DON'T load any of the files which import quill, in my test scripts. For some reason mocha throws up over it anyway. Do you get me? I'm not loading any client side modules in my server tests in the first place, because I'm not testing the client. For some strange reason they fail anyway with errors from Quill complaining that there is no doc object. It's a surprising problem, and maybe that's why it's hard for me to explain it(?)

It could very easily be some strange, esoteric mocha bug that only Quill has triggered for me. I have no idea. I mean, it doesn't make any sense that mocha would be loading modules I'm not telling it to. A library like mocha doesn't normally eagerly load any resources you don't tell it to, which is why you have to stub and mock things sometimes.

Sorry I can't provide more insight about it. And like I said, I understand if it isn't something the Quill team can address. I might try asking about it in the Mocha world as well.

**Comment by SevenZark** [comment]
I can see 'invoke' was poor wording on my part. Let me attempt to clarify.

- I DO have files in my project which import Quill
- However, I DO NOT include those files in the Mocha tests
- I get errors from Quill about a missing document object anyway

Regarding this strange situation:
- I get that supporting Mocha isn't necessarily a priority for Quill since it's not a Quill dependency, and,
- I get that it could be some esoteric Mocha bug too, so I may inquire in that world as well

**Comment by abramz** [comment]
How would an error get thrown from Quill if it were not imported?

**Comment by SevenZark** [comment]
Exactly! No idea, but it is.

**Comment by abramz** [comment]
Exactly, so, let's use [Occam's razor](https://en.wikipedia.org/wiki/Occam%27s_razor) and say that QuillJS is getting imported somewhere.

What would the parameters of a scenario where this is not the case?

**Comment by SevenZark** [comment]
Darn you and your logic! ;) I get your point. The problem is either something in how I'm configuring my test, or something weird that Mocha is doing.
