### ISSUE TITLE
Remove onclick from embed blot

### ISSUE THREAD

**Issue by stinoga** [quilljs/quill#1613]
I have a custom blot that extends `embed`. It returns a span with some text in it, and is called inside a read-only instance of Quill. When the embed is clicked on, the text is selected. Seems like that click code comes from [here](https://github.com/quilljs/quill/blob/d30e36d7a8e32d680b54ed47b40a79b839603fc9/core/selection.js#L41).

I have a parent onClick function I'd like recognized rather than this. Is there a way to disable this click callback?

**Comment by jhchen** [comment]
There is not a way to disable that specifically but you can attach a handler in the constructor of your custom blot so its gets called first (and then not propagate).

**Comment by stinoga** [comment]
Interesting, that didn't seem to work. The click event still doesn't bubble up to the parent. Here's my code:
```js
class Variable extends Embed {
  static create(value) {
    let node = super.create();
    node.textContent = value;
    node.setAttribute('contenteditable', false);
    node.addEventListener('click', function(ev) {
      ev.preventDefault();
    }, false);

    return node;
  }

  static value(node) {
    return node.textContent; //now text will show up in the delta
  }
}

Variable.blotName = 'variable';
Variable.tagName = 'SPAN';

Quill.register(Variable);
```

**Comment by stinoga** [comment]
@jhchen Seems like event bubbling is prevented in the embed select function here:
https://github.com/quilljs/quill/blob/d30e36d7a8e32d680b54ed47b40a79b839603fc9/core/selection.js#L47-L53

**Comment by jhchen** [comment]
But your event handler should be called first as it is lower in the DOM tree.

**Comment by LouisWayne** [comment]
@jhchen is it safe to remove HTML dom node by JQuery (or just vanila JS) - instead of using `quill.removeFormat()`?

**Comment by stinoga** [comment]
Closing as https://github.com/quilljs/quill/commit/6528f2a3a0bdae1f26c968aaf8fe27cbb17c05ed fixed the issue.
