### ISSUE TITLE
Enter header lose 'align'

### ISSUE THREAD

**Issue by stephenLYao** [quilljs/quill#1616]
Hi,  when i press enter after the header which be formated at 'align',  it's tricky that the align text will be removed.A screenshot like this:

![demo](https://user-images.githubusercontent.com/11830681/28819172-f46479a6-7672-11e7-8c13-7b8385df3028.gif)

is there any idea for this？Very thx :)

**Steps for Reproduction**

1. Visit [quilljs.com](https://quilljs.com/)
2. Focus the editor behind header
3. press enter

**Expected behavior**:
The header still align center

**Actual behavior**:
The header lose align

**Platforms**:
macOS Sierra 10.21
Chrome Canary 61.0.3162.0

**Version**:
Version 1.3.0

**Comment by boomyao** [comment]
@jhchen Hi,  This fix has created a new bug .
[https://codepen.io/boomyao/pen/OJLoQvx?editors=1111](https://codepen.io/boomyao/pen/OJLoQvx?editors=1111)
- step1: Use blockquote style.
- step2: Enter new line.
- step3: Unable to cancel new line's blockquote style.
