### ISSUE TITLE
Disable check-spelling in quill

### ISSUE THREAD

**Issue by sigoden** [quilljs/quill#1617]
The check-spelling is a very useful tool, but there are times when I want to be stressed by the words underlined in red. Especially if we are not fans of diacritics.  Maybe it's better to give an option to turn it off .

**Comment by jhchen** [comment]
This is a built in browser feature. From this [SO](https://stackoverflow.com/questions/5601431/spellcheck-false-on-contenteditable-elements) post, you can do:

```js
var quill = new Quill(container);
quill.root.spellcheck = false;
quill.root.focus();
quill.root.blur();
```
