### ISSUE TITLE
No way to import InlineEmbed

### ISSUE THREAD

**Issue by abramz** [quilljs/quill#1623]
Searching the repo for `InlineEmbed`, I do not see it registered with `Quill.register` anywhere, when extending `Quill.import('blots/embed');` `leftGuard` and `rightGuard` are undefined, meaning it is not `InlineEmbed`

Using ES6 to import `InlineEmbed` does not work, you get the error:
`Uncaught TypeError: Class constructor InlineEmbed cannot be invoked without 'new'`

**Steps for Reproduction**

1. Go [here](https://github.com/quilljs/quill/search?utf8=%E2%9C%93&q=InlineEmbed&type=)
2. See that `InlineEmbed` is not `Quill.register`ed
1. Go [here](https://www.webpackbin.com/bins/-KqjcKsUAzJtklxqU0gt)
2. Open log
3. See `boosh` inserted via `insertEmbed`
4. See `undefined undefined` logged as the values of `this.leftGuard` and `this.rightGuard`
5. Go [here](https://www.webpackbin.com/bins/-Kqjc2TXFVSjIVgxaqmh)
6. Open log
7. See `Uncaught TypeError: Class constructor InlineEmbed cannot be invoked without 'new'`

**Expected behavior**:
I should be able to extend `InlineEmbed`

**Actual behavior**:
I can't extend `InlineEmbed`

**Platforms**:
All

**Version**: 
1.2.4, 1.3.0

**Comment by jhchen** [comment]
InlineEmbed is combine into a normal embed now in 1.3.1 so you should be able to just use that.

**Comment by abramz** [comment]
Thanks @jhchen
