### ISSUE TITLE
Pasting Multiple Lines into a Code Block Breaks the Code Block

### ISSUE THREAD

**Issue by ValueBerry** [quilljs/quill#1624]
**Steps for Reproduction**

1. Copy the following text to your clipboard:
```
This
is some
text
spanning
multiple lines.
```
2. Go to [the Playground](https://quilljs.com/playground/).
3. Create a code block.
4. Paste the text into the code block.

**Expected behavior**:

The text, when pasted into a code block, should be added inside the code block as code.

**Actual behavior**:

Only the last line of multi-line text is added to the code block, with the preceding lines being added above the code block as regular text.

This also occurs if there's already text inside the code block.  If you paste somewhere in the middle of a populated code block the single code block is broken in two.

**Platforms**:

Safari 10.1.2 and Chrome 59.0.3071.115 on macOS 10.12.6

**Version**:

1.3.0

**Comment by ValueBerry** [comment]
Looking through the other issues, I think this might be related to https://github.com/quilljs/quill/issues/898.

**Comment by utizr** [comment]
I was running into the same issue. Also on Mac chrome and firefox. I will try it tonight on linux, but I suspect it is not browser/os related.

**Comment by aFaya** [comment]
The blockquote block has the same problem as well

**Comment by aFaya** [comment]
seems customizing own blockquote format can solve this problem related to #1056
