### ISSUE TITLE
isEmpty()

### ISSUE THREAD

**Issue by ncammarata** [quilljs/quill#163]
It would be nice to have an isEmpty function that returns a boolean.

I originally went with this

``` javascript
var empty = $(scope.ngModel).text().length == 0
```

but then if someone posted only an image it would report empty even though it isn't. 

There might be some ambiguity over what exactly is empty, but this seems like a generalized feature that many forms would need.

**Comment by ayalpani** [comment]
Just a note:

> What about something like quill.getLength() === 0? Or if you want to ignore whitespace quill.getText().trim().length === 0.

If I only add an image, but no text, `quill.getText().trim().length` returns 0 too.

**Comment by nvdhunter** [comment]
This is what i end up using.
`isQuillEmpty(){`
`return this.quill.getContents().ops[0].insert == '\n' && this.quill.getLength() < 2;`
`}`
Use getContents() since it doesn't ommit image delta.
If its a newline check op length.
--if there's only one op, than that's quill's default newline and it is considered empty.
--otherwise that's probably user's newline because quill creates new op when you press enter.

**Comment by alexdoronin** [comment]
Suppose we have an image upload. Images are inserted as IMG tags. 
Cases:
"Hit Enter or several Enters" = Quill is empty = Don't save/submit.
"Only image uploaded (no any text)" = Quill is not empty = Save/Submit.

```js
isQuillEmpty() {
  return this.quill.getText().trim().length === 0 && this.quill.container.firstChild.innerHTML.includes("img") === false;
}
``

**Comment by nathanieltagg** [comment]
@alexdroronin That won't work if there's a formula.  We need a solution that's a bit more general...

**Comment by bologer** [comment]
@nathanieltagg I would suggest using some regex to validate content. I use [this](https://regex101.com/r/tlvIcV/1), quite reliable.

```js
/**
 * Check whether editor content is empty or not.
 * @return {Bool}
 */
isEmpty = () => {
    const commentText = this.quill.getText().trim();
    const re = /^<p>(<br>|<br\/>|<br\s\/>|\s+|)<\/p>$/gm;
    return re.test(commentText);
};
```

**Comment by human-a** [comment]
I ended up with something like this:

```javascript
const isEmpty = htmlString => {
    const parser = new DOMParser();

    const { textContent } = parser.parseFromString(htmlString, "text/html").documentElement;

    return !textContent.trim();
}
```

**Comment by pltrant** [comment]
I ended up going with:

`function isQuillEmpty(quill) {
    if (JSON.stringify(quill.getContents()) == "\{\"ops\":[\{\"insert\":\"\\n\"\}]\}") {
        return true;
    } else {
        return false;
    }
}`

That should catch if there is any text, images, or combination thereof.

**Comment by corgus** [comment]
Empty for my use case is both: 

1. nothing but text inserted (no media, formulas, etc, so only one op) _and_ 
2. no text except potentially spaces/tabs/returns/etc (text removed via js trim()) 

```
isQuillEmpty(quill) {
  if ((quill.getContents()['ops'] || []).length !== 1) { return false }
  return quill.getText().trim().length === 0
}
```

**Comment by eddieherm** [comment]
> ```
> isQuillEmpty(quill) {
>   if ((quill.getContents()['ops'] || []).length !== 1) { return false }
>   return quill.getText().trim().length === 0
> }
> ```

This is the proper solution. Thanks.
