### ISSUE TITLE
What I See Isn't What I Get

### ISSUE THREAD

**Issue by maximeozenne** [quilljs/quill#1631]
I am currently implementing a bubble theme instance of quilljs 1.3.0 on Google Chrome.

My editor is rendering as following : 

```
<div class="page" id='page'>
	HEADER
	<div class="subpage" id='editor-container'>
		CONTENT
	</div>
</div>
```

Which give me something like this :

![onstart](https://user-images.githubusercontent.com/12842987/29029023-841d96fa-7b86-11e7-96dd-07944680c45f.PNG)

So when I copy/paste a few times the "CONTENT" to fill up the page, I see the following :

![what i see](https://user-images.githubusercontent.com/12842987/29029048-9a941698-7b86-11e7-8354-62dccc83d95c.png)

But when I try to render the html code I got with `quill.root.innerHTML` I get the following result :

![what i get](https://user-images.githubusercontent.com/12842987/29029083-be231640-7b86-11e7-932c-3eb34e6f55a8.png)

As you can see the result isn't the same. All the line breaks (maybe symbolized by `<p></p>` in the editor) have a bigger padding than the line breaks rendered in the editor.

How can I get the exact same result as html code ? I also tried to add the quilljs css to the printed page but it doesn't change anything.

**Comment by seandearnaley** [comment]
You can't nest block level element within block level elements in quill.js, it's one of its biggest gotchas, effects most people that try to extend it.

**Comment by maximeozenne** [comment]
Not sure I nested them. I displayed the html code I got from my copy/paste and I got the following result :

![image](https://user-images.githubusercontent.com/12842987/29031235-d956dee0-7b8d-11e7-8d7c-93bd9f669c63.png)

But maybe I misunderstood what you told me

**Comment by seandearnaley** [comment]
did you put a ```<p>``` tag inside a ```<div>``` tag?

**Comment by maximeozenne** [comment]
The editor is the div with the "subpage" id inside the "page" id so yes I guess all the <p> contained by the editor are in a div

**Comment by seandearnaley** [comment]
yeah I've found it automatically splices block level elements into the next in line block on the same level so its not surprising how it renders, could you paste the html you get from quill.root.innerHTML

**Comment by jhchen** [comment]
@maximeozenne I think the issue is Quill's editor uses `<p>` tags to be more semantic but by default `<p>` tags have margin. Quill gets rid of this with css but if you display the same HTML outside of Quill then you will get the margin as that is the browser default. A couple ways to solve this are:

- Add the margin: 0 rule to `<p>` in your application.
- Add a the .ql-editor class to the container you are using to render Quill contents so its CSS will apply to it.

> You can't nest block level element within block level elements in quill.js, it's one of its biggest gotchas, effects most people that try to extend it.

I acknowledge documentation could be better on how to do this but it is not true Quill does not have this capability. Lists which nest two block level elements `<ul>` and `<li>` are a counterexample that works perfectly well in Quill.

**Comment by maximeozenne** [comment]
@seandearnaley I pasted the html I a previous comment.

@jhchen Thanks ! I added `<style>p {margin:0;}</style>`  and now it's rendering perfectly (at least for the paragraphs)

Which CSS file can I add to get the exact same result than the editor ? I mean I used the "indent+1" button on an image to center it. It worked great on the editor but the image still at the left on the render. It comes from the `<p class="ql-indent-2">` which is not part of any css I import during the render process.

**Comment by maximeozenne** [comment]
My bad, as you said I had to add the ".ql-editor" class to the container I'm using to render with the bubble css linked to make looks like the editor. Thanks for your help !

**Comment by loagit** [comment]
@jhchen Could you demonstrate a simple example of how you can add block elements within other block elements? For example. Would it be possible to create a wrapper for all or part of the content present in Quill? I think it would be interesting to demonstrate how this can be done as there are gazillions of people in need of this feature.

**Comment by asiehmokarian** [comment]
@jhchen Would you please advise how can solve this issue when we are passing the content through another app where we cannot  adjust styling? For example getting the quill.root.innerHTML and send it via and email, what I get as the email content  is not same as what I see in editor.

**Comment by asiehmokarian** [comment]
@jhchen Would you please advise how can solve this issue when we are passing the content through another app where we cannot  adjust styling? For example getting the quill.root.innerHTML and sending it via an email, what I get as the email content  is not same as what I see in editor.
