### ISSUE TITLE
Set default direction to RTL

### ISSUE THREAD

**Issue by mort3za** [quilljs/quill#1632]
I think it's better to have an option to set default direction of editor to `RTL`.

In websites that have only one RTL language, Users dont want to click on RTL button everytime they start typing on editor and it has a bad sense because website is RTL and editor should be RTL.

Also I saw the generated code of editor and it set's a class for every node (`ql-align-right ql-direction-rtl`), this causes adding unneeded classes to text.

**Comment by jhchen** [comment]
In those cases do you want the option to make it left-to-right, or would you prefer it always be right-to-left?

**Comment by mort3za** [comment]
I want an option to make editor RTL by default, but users can change direction by 'direction' button in toolbar everytime they need it. 

Another issue is toggling direction to LTR by button  should add a class to element (at the moment, setting direction of an element to LTR by clicking 'direction' button, does not add any class to it, So it's impossible to detect elements with forced LTR direction)

**Comment by mohammad-aqajani** [comment]
Hey ?
what's the solution ??

**Comment by caryuval** [comment]
You can add a p element inside the Quill container, then write the following jquery:
$("#quillContainer p").addClass("ql-align-right ql-direction-rtl");

**Comment by de-Generation** [comment]
@mort3za did you find any solution?

**Comment by mort3za** [comment]
@de-Generation No. I just removed 'alighn to left' button, But I know it's not a solution.

**Comment by AugustusZ** [comment]
@mort3za did you have any new solution? Thanks!

**Comment by tegola** [comment]
> I think it's better to have an option to set default direction of editor to RTL.

This would be handy, but you can fix by initializing the editor and set the text direction and alignment:

```javascript
var node = document.getElementById('editor');
var editor = new Quill(node, { theme: 'snow' });

editor.format('direction', 'rtl');
editor.format('align', 'right');
```

> Also I saw the generated code of editor and it set's a class for every node (ql-align-right ql-direction-rtl), this causes adding unneeded classes to text.

Quill works with the [Delta format](https://quilljs.com/docs/delta/), which can be read back and formatted as you wish. It is not supposed to output compatible html. If you need to tweak html output, you need to tinker with Parchment. See some examples [here](https://quilljs.com/guides/how-to-customize-quill/#content-and-formatting).

**Comment by alihasaniGit** [comment]
> ```css
> .ql-editor {
>   direction: rtl;
>   text-align: right;
> }
> ```

we want to make it rtl _initially_ and also make it selectable (changeable), but with your idea it will be locked in rtl direction and the direction option in toolbar will be useless ..

**Comment by sonaye** [comment]
@alihasaniGit Yes this assumes a fixed direction, in my use case there was no need for it (all rtl). You should be able to dynamically change/append classes to the editor's DOM node though.

```js
.ql-editor-ltr {
  direction: ltr;
  text-align: left;
}

.ql-editor-rtl {
  direction: rtl;
  text-align: right;
}

`<div class="${isRtl ? 'ql-editor-rtl' : 'ql-editor-ltr'}">`
```

Side note: Full details of my work (with React) can be found [here](https://github.com/sonaye/react-quill-wysiwyg) ([demo](https://sonaye.github.io/react-quill-wysiwyg/)), change https://github.com/sonaye/react-quill-wysiwyg/blob/master/src/Wysiwyg/factory.js#L7 to import the rtl stuff.

**Comment by kivi2020** [comment]
I Prefer These Lines Of Code : 
`
  ngAfterViewInit() {
    let elem = this.quill.editorElem.getElementsByClassName("ql-blank")[0];
    
    let child = elem.children[0];
    child.classList.add("ql-align-right");
  }

**Comment by keivansahebdelfard** [comment]
I Prefer These Lines Of Code : 
```
  ngAfterViewInit() {
    let elem = this.quill.editorElem.getElementsByClassName("ql-blank")[0];
    
    let child = elem.children[0];
    child.classList.add("ql-align-right");
  }

**Comment by sajadjafari** [comment]
After you initialized Quill, you can simply use the **format**  method to change the **direction** and **align** and it would be **RTL** by default and won't affect direction toggle action.

```
quill.format('align', 'right');
quill.format('direction', 'rtl');
```

**Comment by amirHossein-Ebrahimi** [comment]
@tegola 
Thanks, it works properly.
But, is there a way to keep the direction of ltr-in-mind designed elements e.g. `code block` & `formula`?

**Comment by tegola** [comment]
> But, is there a way to keep the direction of ltr-in-mind designed elements e.g. `code block` & `formula`?

@amirHossein-Ebrahimi sorry for the delay. I'm afraid I don't know the answer.

**Comment by amirHossein-Ebrahimi** [comment]
@tegola thanks :pray:
Custom registered formula and code-block handler should fix it, shouldn't it?

**Comment by ArbazIrshad** [comment]
This doesn't change the placeholders direction. Any way to change it's direction? I tried adding dir attribute to ql-editor but it doesn't work.

**Comment by Guilherme-Valle** [comment]
There is some way to use the `dir="auto"` property on Quill? E.g. if the user is using hebrew, then the RTL option will be automatically selected.

**Comment by v-dale** [comment]
> After you initialized Quill, you can simply use the **format** method to change the **direction** and **align** and it would be **RTL** by default and won't affect direction toggle action.
> 
> ```
> var quill = new Quill('#editor', {...});
> quill.format('align', 'right');
> quill.format('direction', 'rtl');
> ```

This solution works but it automatically adds the `class="ql-align-right"` to all the paragraphs.



> ```css
> .ql-editor {
>   direction: rtl;
>   text-align: right;
> }
> ```

This solution also works, but the issue is that if the user changes the direction to LTR, nothing happens. 

We need a default content alignment-direction. If the user selects LTR, the required classes "ql-align-left" should be added. but no class is needed for the RTL.

**Comment by Pizza1** [comment]
Is there a fix around switching between languages?

**Comment by thisordered** [comment]
**React users**

works in react.

```
const [currentEditor, setEditor] = useState(null);

  useEffect(() => {
    if (ref?.current) {
      const editor = ref.current.getEditor();
      setEditor(editor);
    }
    if (currentEditor) {
      currentEditor.format("direction", "rtl");
      currentEditor.format("align", "right");
    }
  }, [currentEditor, ref]);


const quillModules = useMemo(
    () => ({
      toolbar: {
        container: [
          [{ header: [1, 2, 3, false] }],
          ["bold", "italic", "underline"],
          [{ list: "ordered" }, { list: "bullet" }],
          ["link", "image"],
          [{ direction: "rtl" }], // Add both RTL and LTR
        ],
      },
    }),
    []
  );


    <ReactQuill
      ref={ref}
      theme="snow"
      value={editorContentRef.current}
      onChange={handleChange}
      modules={quillModules}
      defaultValue={"<p dir='rtl'></p>"}
      style={{
        height: "100%",
        color: "#inherit",
        marginBottom: 20,
      }}
    />
```

**Comment by thisordered** [comment]
**React users**

works in react.

```
const editorContentRef = useRef(value); 
const [currentEditor, setEditor] = useState(null);

  useEffect(() => {
    if (ref?.current) {
      const editor = ref.current.getEditor();
      setEditor(editor);
    }
    if (currentEditor) {
      currentEditor.format("direction", "rtl");
      currentEditor.format("align", "right");
    }
  }, [currentEditor, ref]);


const quillModules = useMemo(
    () => ({
      toolbar: {
        container: [
          [{ header: [1, 2, 3, false] }],
          ["bold", "italic", "underline"],
          [{ list: "ordered" }, { list: "bullet" }],
          ["link", "image"],
          [{ direction: "rtl" }],
        ],
      },
    }),
    []
  );


    <ReactQuill
      ref={ref}
      theme="snow"
      value={editorContentRef.current}
      onChange={handleChange}
      modules={quillModules}
 
    />
```

**Comment by ganeshnewpen** [comment]
lkmlk
