### ISSUE TITLE
Two problems with InlineEmbed blot input

### ISSUE THREAD

**Issue by yetson** [quilljs/quill#1635]
**InlineEmbed** blot seems not friendly to input,  when input around the InlineEmbed blot, result is weird. Take formula blot for example as below:  

## Problem 1: left-side English letter input

**Steps for Reproduction**

1. Visit [quilljs.com](https://quilljs.com/)
2. focus left-side of the formula in the editor
3. type 'ab' with keyboard

**Expected behavior**:
'ab' is on the left-side of the formula

**Actual behavior**:
'a' is on left, but 'b' right 

![2017-08-08 17 11 25](https://user-images.githubusercontent.com/6120964/29064807-c47211dc-7c5c-11e7-8557-3d5846783a8b.gif)

## Problem 2: right-side Chinese letter input

**Steps for Reproduction**

1. Visit [quilljs.com](https://quilljs.com/)
2. focus **right-side** of the formula in the editor
3. type 'zhong' to input '中'  with Chinese input method

**Expected behavior**:
'中' is behind the formula blot

**Actual behavior**:
'z中' is behind the formula blot

![2017-08-08 17 11 53](https://user-images.githubusercontent.com/6120964/29064811-c917103e-7c5c-11e7-8c0c-e81cd8187616.gif)

**Platforms**:
Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)
Mac OS X EI Capitan Version 10.11.6

**Version**:
`Quill.version`  is `1.3.1`

**Comment by abramz** [comment]
Your 2nd example seems to be working as intended.

The `z` is not made a part of the formula, that is not how embed blot works. You placed the cursor after the guard character, so the `z` comes after the formula. If you were expecting a space between the formula and the `z`, you have to type that yourself based on where you placed the cursor position.

**Comment by qpxtWhite** [comment]
![3136640D-71AF-4FE5-97DA-22E88BFAF046](https://user-images.githubusercontent.com/4169498/220571027-9aa3ac34-d341-44f0-99c1-197054ec8496.gif)
I want “这是”, but it becomes “zh这是z”
How to fix the bug
