### ISSUE TITLE
Issue with the jQuery UI Sortable plugin

### ISSUE THREAD

**Issue by slightGT** [quilljs/quill#1636]
Dear all,

I'm trying to create a sortable list of text editor using the [jQuery UI sortable plugin](http://api.jqueryui.com/sortable) and QuillJS, but I'm facing some issues.

I created the following HTML sortable elements (sortable-box) inside a DIV used as a container (sortable-container). In each element there is DIV with class "text-area" that is the text editor create by QuilJS.
```
<div id="sortable-container">
  <div class="box-container sortable-box">
    <div id="text-1" class="text-area">test</div>
  </div>
  <div class="box-container sortable-box">
    <div id="text-2" class="text-area">test</div>
  </div>
</div>
```
Then I initialized all the objects as follow:
```
$("#sortable-container").sortable();

 $(".text-area").each(function(index,el){
      var editor = new Quill(el, {
                              modules: {
                                    toolbar: [
		                                   [{ header: [1, 2, false] }],
		                                   ['bold', 'italic', 'underline'],
		                                   [{ 'align': [] }],
			                                   [{ 'list': 'ordered'}, { 'list': 'bullet' }],
			                                   ['image', 'code-block']
		                                   ]
		              },
		              theme: 'snow'
	                 });
  	}))
```
Graphically everything is fine, the text editor is correctly created and the sortable function works well without any errors in console, but I'm not able to edit the "textarea". The cursor is not placed inside the blank space, it seems that the text editor doesn't take the focus.

I've tried to apply the same script without the sortable function and, in this case everything is fine, for what concerns the "textarea".

Thank you for the support

**Platforms**:
Windows 10, Chrome 59.0.3071.115, 64 bit

**Version**:
Quill Editor v1.2.6

**Comment by benbro** [comment]
The sortable plugin is probably blocking the mousedown event from reaching quill.
There is a [handle](http://api.jqueryui.com/sortable/#option-handle) option which let you define an element that will control the drag.
Anyway, this is a jQuery UI question and not a Quill issue.

**Comment by slightGT** [comment]
Thank you for your reply, I've already tried to use handle option without any result... I'll ask clarification to the jQuery UI team.

Thank you
