### ISSUE TITLE
Retrieving HTML from a stored Delta

### ISSUE THREAD

**Issue by kokujin** [quilljs/quill#1637]
Can someone point me to the documentation entry which shows how to retrieve HTML from a stored Delta object? Thanks

**Comment by DmitrySkripkin** [comment]
You have to initialize Quill and use `setContent()` to load your data and then use `innerHTML` or something like that to get html. Or you can look for third-party repos like that:
https://www.npmjs.com/package/quill-delta-to-html
https://www.npmjs.com/package/delta-to-html
https://www.npmjs.com/package/delta-transform-html

Quill doesn't have a "build in, easy and fast" method to do that. You can see discussion here https://github.com/quilljs/quill/issues/993

**Comment by papac** [comment]
Thank guys.

**Comment by fghhfg** [comment]
> Quill doesn't have a "build in, easy and fast" method to do that. 

:-1:
