### ISSUE TITLE
Selected word will be invisible when add link

### ISSUE THREAD

**Issue by reply2future** [quilljs/quill#1638]
I select a word and click the link button,when I finished inputting the website and click save button,the selected word is **invisible**.

**Steps for Reproduction**

1. Visit [quilljs official website](https://quilljs.com/docs/themes/)
2. Go to **Snow** demo editor
3. Add a word 'test' and then select it.
4. Click **link** button and add the website **http://example.com** to the popup window,then click **save** button.

**Expected behavior**:
The color of selected word will be blue and add underline.
**Actual behavior**:
The selected word is invisible.
**Platforms**:
browser: Chrome Version 60.0.3112.90 (Official Build) (64-bit)   and FireFox 54.0
OS: Ubuntu 16.04(64-bit)

**Version**:
quill: 1.3.1

**Comment by frabnt** [comment]
Any news on this?
