### ISSUE TITLE
Adding contenteditable false div in editor

### ISSUE THREAD

**Issue by astr0junk** [quilljs/quill#1640]
Hi, I have a prodblem. I create custom blot class, which extends from embed class. I need to attach div block, with contenteditable false attribute, but it must be able to selected and removed by keyboard event. Now I have new paragraph after my inserted <div> element. I append element by insertEmbed, and clearing previous line programmatically. But, then I setting up quill on text, with this block (my custom blot with div tag) i have the same automatically adding new <p> tag after it. Before I enable quill there is no p tag in block with text.

**Comment by jhchen** [comment]
Please include the information the issue template asked for. The issue template was designed so others can get enough context to be helpful so you might in turn get a helpful response.
