### ISSUE TITLE
ERROR: container required for the toolbar

### ISSUE THREAD

**Issue by Nemsae** [quilljs/quill#1641]
I get this error, ERROR: container required for the toolbar, when trying to setup a basic boilerplate Quill,
```
modules: {
        toolbar: [
          [{ header: [1, 2, false] }],
          ['bold', 'italic', 'underline'],
          ['image', 'code-block']
        ]
      },
```

I realize that Quill is trying to find a container for the toolbar (by targeting a specific element).

When I change the modules by specifying a custom container, like this:

```
modules: {
        toolbar: {
          container: '#toolbar'  // Selector for toolbar container
        }
      },
```

The Quill does work, but now I can't add custom toolbar options.

Where in the docs can I find more detailed information regarding the toolbar module. I have already looked at https://quilljs.com/docs/modules/toolbar/ but found nothing.

**Version**:
1.3.1

**Comment by jhchen** [comment]
Currently it is one or the other: You can either supply a custom toolbar and build it yourself (selector option) or you can let Quill build it. The latter is controlled by the theme so snow will build it into the persistent toolbar above the editor and bubble will build it into a tooltip.

**Comment by beratcelik** [comment]
You may use jQuery to overcome the issue. Basically move the tool bar to any other div that you want.
```
<html>
<div id="editor" />
<div id="toolbar" />
</html>

<script>
var toolbarOptions = [
			  ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
			  ['blockquote', 'code-block'],

			  [{ 'header': 1 }, { 'header': 2 }],               // custom button values
			  [{ 'list': 'ordered'}, { 'list': 'bullet' }],
			  [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
			  [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
			  [{ 'direction': 'rtl' }],                         // text direction

			  [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
			  [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

			  [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
			  [{ 'font': [] }],
			  [{ 'align': [] }],

			  ['clean']                                         // remove formatting button
			];
var quill = new Quill('page', {
			  modules: {
				toolbar: toolbarOptions,				
			  },
			  placeholder: 'Compose an epic...',
			  theme: 'snow'  // or 'bubble'
			});
$("#toolbar").append($(".ql-toolbar"));
</script>
```

**Comment by Dinesh-Badavath** [comment]
> `mn`

**Comment by bdkoder** [comment]
> 

Thank you. It's working. 

If anyone got the proper solution, please don't forget to share.
