### ISSUE TITLE
Unable to delete link text in Edge

### ISSUE THREAD

**Issue by ghost** [quilljs/quill#1643]
Trying to delete text that is a link using the backspace key in Edge seems to be pretty inconsistent. If the link is the 1st span of text, backspacing will remove the link format, but you can't continue to backspace and remove the actual text. If the text is somewhere in the middle and you backspace, it removes the link and moves the text to some other location.

**Steps for Reproduction**

***Repro 1***
1. Visit quilljs.com using Edge
2. Put your cursor at the end of the "open source" link
3. Press backspace to remove the link

****Expected behavior****:

Text stays in place

****Actual behavior****:

Link is removed, text moves to after "With its"

***Repro 2***
1. Visit quilljs.com using Edge
2. Clear all content in the editor
3. Enter text, highlight it, and make it a link
4. Move your cursor to the end of the link
5. Press backspace to remove the link
6. Press backspace again to start removing the text.

****Expected behavior****:

Some text is deleted

****Actual behavior****:

Link is removed, text is not deleted

**Platforms**:

Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063
Windows 10

**Version**:

1.3.1

**Comment by thinksaydo** [comment]
I can confirm this is still a bug in 1.3.2

**Comment by wags1999** [comment]
This also occurs in IE 11.

**Comment by DJShump08** [comment]
@jhchen any news about fixing this?
