### ISSUE TITLE
Consider creating an Awesome-Quill repo.

### ISSUE THREAD

**Issue by patleeman** [quilljs/quill#1646]
I just created a module for Quill ([quill-markdown-shortcuts](https://patleeman.github.io/quill-markdown-shortcuts/)) and I realized there is no where to share my module with the community nor is there an easy way to find what other projects people have worked on.

I think the creation of an awesome-quill repository which contains links to projects and resources around quill could help strengthen the community and offer people using Quill a resource to find useful code bits.

Here are a few examples:

- [Awesome Vue](https://github.com/vuejs/awesome-vue)
- [Awesome React](https://github.com/enaqx/awesome-react)
- [Awesome D3](https://github.com/wbkd/awesome-d3)

I think recruiting several community members to review merge requests would take the burden off of @jhchen having to approve all the merge requests.

Thoughts?

**Comment by jhchen** [comment]
I think this is a great idea. Just getting back from an overseas trip and going through issues but I will get a repo set up soon. Please comment with additional awesome quill repos in the meantime. Thank you for the markdown module too!

**Comment by patleeman** [comment]
Here's a few from searching github

Modules
- [Image Resize](https://github.com/kensnyder/quill-image-resize-module)
- [Image Drop](https://github.com/kensnyder/quill-image-drop-module)
- [Image URL Drop](https://github.com/riencroonenborghs/quill-image-url-drop-module)
- [Cursors](https://github.com/reedsy/quill-cursors)
- [Emoji](https://github.com/contentco/quill-emoji) 
- [Markdown Shortcuts](https://github.com/patleeman/quill-markdown-shortcuts)
- [Word Counter](https://github.com/ghosthelland/quill-wordcounter)
- [Image Splitter](https://github.com/cmbankester/quill-image-splitter)
- [Local Storage](https://github.com/brettimus/quill-local-storage)
- [Placeholders](https://github.com/jspaine/quill-placeholder-modulehttps://github.com/jspaine/quill-placeholder-module)

Components
- React
  - [react-quill](https://github.com/zenoamaro/react-quill)
- Vue
  - [vue-quill-editor](https://github.com/surmon-china/vue-quill-editor)
  - [vue-quill](https://github.com/CroudSupport/vue-quill)
- Angular 2
  - [ngx-quill-editor](https://github.com/surmon-china/ngx-quill-editor)
- Polymer
  - [quill-element](https://github.com/dmonad/quill-element)
  - [polymer-quill](https://github.com/arsnebula/polymer-quill)

**Comment by jhchen** [comment]
The initial list is up at https://github.com/quilljs/awesome-quill. Thank you for seeding the list @patleeman! I've added you as a collaborator so you can continue to contribute if you have the time and interest. A couple suggestions did not look actively maintained so I excluded them. Otherwise I mostly used D3's contributor guidelines and license choice and some of the formatting vue used.

**Comment by patleeman** [comment]
Awesome, I'll be sure to add any modules I come across.  Thanks for setting this up @jhchen!
