### ISSUE TITLE
Adding binding for TAB doesn't call handler

### ISSUE THREAD

**Issue by ggCS** [quilljs/quill#1647]
Setup
- Quill 1.2.4
- Chrome Version 60.0.3112.101 (Official Build) (32-bit)

Using the `addBinding` function I attempted to modify functionality for tab using the format and that didn't work. I then tried to simply verify my tab binding was even working and alas it was not. 

    mainEditor.keyboard.addBinding({  
      key: 9,
        handler: function(range, context) {
          console.log("tab pressed");
          return true;
        }
      });

Can't get anything to print out of console

**Comment by DmitrySkripkin** [comment]
I have a suggestion. Quill has default binding for tab, so if you want it to work you have to overwrite the default one (https://quilljs.com/docs/modules/keyboard/#configuration).
According to docs you can not overwrite default bindings with `addBinding`. I took following code from docs.
```
var bindings = {
  // This will overwrite the default binding also named 'tab'
  tab: {
    key: 9,
    handler: function() {
      // Handle tab
    }
  },

  // There is no default binding named 'custom'
  // so this will be added without overwriting anything
  custom: {
    key: 'B',
    shiftKey: true,
    handler: function(range, context) {
      // Handle shift+b
    }
  }
};

var quill = new Quill('#editor', {
  modules: {
    keyboard: {
      bindings: bindings
    }
  }
});
```

**Comment by jhchen** [comment]
Thanks for the help @DmitrySkripkin !

**Comment by pmlord** [comment]
Does anyone have advice on how to listen for the ENTER or TAB keys from a custom module? As far as I know, the module's initialization happens after Quill's, so my only option in the custom module constructor is to use the quill.addBinding function.
