### ISSUE TITLE
Quill doesn't work consistently with riot.js

### ISSUE THREAD

**Issue by 0nix** [quilljs/quill#1648]
Hello everyone. I'm using Quill to build a web component / x-tag using a library called Riot. However, the plugin doesn't work consistently. The toolbar buttons work with odd conditions: After rendering the component and creating a Quill editor, if you type some text and then try to style it (bold, italics, etc), the buttons are unresponsive. If you set the format, and then type, the format is applied to the text. If any further changes are attempted (clearing the style, adding a new one, etc.) , the buttons still remain unresponsive. 

This behavior is only limited to the buttons, the dropdown Heading menu works in all possible uses.

**Steps for Reproduction**

1. [Visit minimal viable plunkr](http://plnkr.co/edit/DowiYHUwsXwvTdq6yJAQ?p=preview) 
2. Click Run if the Plunkr is not running yet.
3. Type something in the editor, then try to format it.
4. Try formatting then editing.

**Expected behavior**:
Being able to apply any combination of formatting to a text.

**Actual behavior**:
Only being able to set a style once, then typing the text.

**Platforms**:
Browser: Vivaldi, Chrome, Firefox.
OS: Ubuntu Trusty
Include browser, operating system and respective versions

**Version**:

1.3.1

**Comment by benbro** [comment]
I can't reproduce.

Try to reproduce the issue with the [CodePen](https://codepen.io/quill/pen/KzZqZx) without riot.js.
If there is something wrong only when using riot.js, that's not a Quill bug.
