### ISSUE TITLE
After prolong usage "selection-changed" stop firing

### ISSUE THREAD

**Issue by amitm02** [quilljs/quill#1654]
After some prolog usage, selection-changed" events stop firing.
probably related to #1584

I've manage to track to problem to the following:

```
this.emitter.listenDOM('selectionchange', document, function () {
      if (mouseCount === 0) {
        setTimeout(_this.update.bind(_this, _emitter4.default.sources.USER), 1);
      }
    });

```

A breakpoint on that method revealed that mouseCount has a value > 0 (it was 8) and going up with each click.

the mouse-up event handler, that was suppose to keep mouseCount at 0 does not fired, but I couldn't figure out why:

```
this.emitter.listenDOM('mouseup', document.body, function () {
      mouseCount -= 1;
      if (mouseCount === 0) {
        _this.update(_emitter4.default.sources.USER);
      }
    });
```

**Comment by HWliao** [comment]
root cause: mousedown was triggered,but the museup was not triggered.
an operation causes this problem:
1.Press the mouse in the browser and do not release it
2.Move the mouse outside the browser
3.Release the mouse
Maybe we can write it like this:
``` javascript
    let mouseCount = 0;
    this.emitter.listenDOM('mousedown', document.body, () => {
      mouseCount  = 1;
    });
    this.emitter.listenDOM('mouseup', document.body, () => {
      mouseCount  = 0;
      if (mouseCount === 0) {
        this.update(Emitter.sources.USER);
      }
    });
    this.emitter.listenDOM('selectionchange', document, () => {
      if (mouseCount === 0) {
        setTimeout(this.update.bind(this, Emitter.sources.USER), 1);
      }
    });

```
The next time the mouse is uped, it can fix the `mouseCount  = 0`
But not perfect`

**Comment by jhchen** [comment]
Thanks for looking into the cause @HWliao !

**Comment by shaneshearer-andculture** [comment]
Is there any idea on the timing for the next version with this commit?
