### ISSUE TITLE
Quill strips out harmless html with dangerouslyPasteHTML

### ISSUE THREAD

**Issue by christopherbauer** [quilljs/quill#1657]
I am probably misunderstanding something about the library, but all I want to do is add a span that contains some information that I can use to "tag" a user from a list. Everything is working except for pasting a span that contains the information I need to link the post to the user that is being tagged.

**Steps for Reproduction**

1. Visit [Example Codepen Here](https://codepen.io/anon/pen/rzpEWq)
2. Inspect the Element
3. No HTML

**Expected behavior**:

1. HTML

**Actual behavior**:

1. No HTML

**Platforms**:

1. All

**Version**:

1.3

**Comment by christopherbauer** [comment]
I have tried to implement a "pass all html through" matcher here: [Attempt to Fix](https://codepen.io/anon/pen/dzJBZo)

I am getting "Delta() is undefined". I used the logic from the documentation so I'm a bit confused, do I need to add a special CDN library to access Delta?

**Comment by f3ltron** [comment]
you have to import it 	

var Delta = Quill.import('delta');

**Comment by f3ltron** [comment]
I found this problem too when i tried to add a div that corresponding to an embed value. It suck it can be good to have two differents way to dangerouslyPasteHtml.

But what i understand about that is quill cannot properly create the ops table if we do it like this. So that's why it delete all div etc.

**Comment by jhchen** [comment]
Quill does not allow arbitrary HTML so it may change or strip markup. As stated in the docs for `dangerouslyPasteHTML`:

> The snippet is interpreted by Clipboard matchers, which may not produce the exactly input HTML.

**Comment by christopherbauer** [comment]
@jhchen I understand that, I read the docs and stated as such clearly in the second comment in which I'm attempting to add a matcher that will allow passthrough of html. All I need is to understand why my node insert below doesn't work properly:

https://codepen.io/anon/pen/ZJmXxo

**Comment by f3ltron** [comment]
i am like him dont really understand the add matcher. I have an embed data i want to re insert when its match but its not working and get the same error as him...

Maybe more information and examples in doc could be great....

**Comment by jhchen** [comment]
Quill itself does not allow arbitrary HTML by design. It it not safe from a bug free and user experience perspective, not just a security one. Vanilla contenteditable and previous generation of rich text editors earned their notoriety because of this and part of the reason Quill was born. If you nevertheless prefer the flexibility of arbitrary HTML modifications, other editors with this support still exist.

If you accept this part then the matchers are just obliging at the paste layer what Quill's underlying data model wants which is a consistent deterministic markup. You can make deep customizations to the data model through Parchment and this [guide](https://quilljs.com/guides/cloning-medium-with-parchment/) is a good place to start but this is not just at the paste layer.

**Comment by f3ltron** [comment]
i have an answear for him. I will write it tommorrow. @jhchen can we have more efficent doc (more example, more explanation in depth) about addmatcher in doc and maybe other like video support maybe ? Maybe i can help you

**Comment by igorbuts** [comment]
While using Quill in my app I also need to add some arbitrary HTML, that is - adding ids to tags that are allowed by quill. I need this to link some items in the editor with other parts of my application.

@jhchen, is adding ids also `not safe from a bug free and user experience perspective`?
If not, if there any possibility that such type of arbitrary HTML as this will be allowed?

**Comment by uptownhr** [comment]
@f3ltron any possibility for that example or response?

**Comment by tungvn-vieted** [comment]
Hmm. Seems that function remove all table tags. Why the table tags is not safe?

**Comment by chadwickmeyer** [comment]
I find it extraordinary that Quill strips out valid HTML like elements `table`, or valid attributes like `class`, and that there is no way to turn off the stripping or providing our own custom white list. This makes the product completely unusable in any environment (e.g. a CMS) where users may have tabular data, or designers edit the HTML and add custom classes, etc. How is that even possible?

**Comment by sri8484** [comment]
> I find it extraordinary that Quill strips out valid HTML like elements `table`, or valid attributes like `class`, and that there is no way to turn off the stripping or providing our own custom white list. This makes the product completely unusable in any environment (e.g. a CMS) where users may have tabular data, or designers edit the HTML and add custom classes, etc. How is that even possible?

Hey [chadwickmeyer](https://github.com/chadwickmeyer)
Did you get any solution to this problem?
any way to prevent quill from removing table tags?

**Comment by sri8484** [comment]
> var Delta = Quill.import('delta');

Hi [christopherbauer](https://github.com/christopherbauer), 
Did the "pass all html through" matcher worked?

**Comment by mrfalak** [comment]
any update?

**Comment by ishaiavrahami** [comment]
any update?

**Comment by vgarcia007** [comment]
Same Problem here. Need to insert a Table.  Quill strips out table tags. What would be an alternative solution to dangerouslyPasteHTML ?

**Comment by christopherbauer** [comment]
> > var Delta = Quill.import('delta');
> 
> Hi [christopherbauer](https://github.com/christopherbauer), Did the "pass all html through" matcher worked?

Sorry I didn't see this - the issue is 5 years old now and I don't have access to the codebase to verify any of the debugging steps from 5 years ago.

**Comment by ardicoetzee** [comment]
Did anyone find a solution? Starting to seriously dislike Quill. THIS IS A BASIC REQUIREMENT THAT SHOULD BE A SIMPLE SETTING!

**Comment by timotheedorand** [comment]
Same issue here

**Comment by christopherbauer** [comment]
The library maintainer has been pretty clear about their stance. Quill is an opinionated library and this as far as I know will not change.

I vaguely remember using fckeditor or something else.

**Comment by timotheedorand** [comment]
Using custom StyleAttributor from parchment fixes this issue for me. Inline styles are now rendered.

```
import { StyleAttributor, Scope, type LeafBlot } from 'parchment';

export const SizeStyle = new StyleAttributor('size', 'font-size', { scope: Scope.INLINE });
export const WidthStyle = new StyleAttributor('width', 'width', { scope: Scope.INLINE });
export const HeightStyle = new StyleAttributor('height', 'height', { scope: Scope.INLINE });
export const FontWeight = new StyleAttributor('font-weight', 'font-weight', { scope: Scope.INLINE });
...
Quill.register(FontWeight, true);
Quill.register(SizeStyle, true);
Quill.register(HeightStyle, true);
Quill.register(WidthStyle, true);
```
