### ISSUE TITLE
List of Suggested Words Doesn't Display on IE11 on Character Reconversion

### ISSUE THREAD

**Issue by vbhargavmbis-zz** [quilljs/quill#1658]
**Steps for Reproduction**

1. Enable [Japanese Microsoft IME](https://www.coscom.co.jp/learnjapanese801/msime_win8_en1.html)
2. Navigate to [http://quilljs.com/playground/](http://quilljs.com/playground/)
3. Enable Japanese input and type the word 'ringo' into the editor. The word りんご　appears and a suggestion box opens up underneath.
4. Press space -> The word is converted to Katakana/Kanji and the suggestion box closes.
5. Press space again 

**Expected behavior**:
The word is converted again, but the suggestion box opens up.
If you press space multiple times thereafter, the word cycles through the options in the suggestion box. The suggestion box remains open.

**Actual behavior**:
The word is converted again, but the suggestion box does not open up. 
If you press space multiple times thereafter, the word appears to cycle through the options and the suggestion box opens up at random times and rarely.

***Note***: 
1. While cycling through the options in IE11, there are some words which cause the browser to freeze and it becomes unusable. I believe that problem is captured in this issue: https://github.com/quilljs/quill/issues/1611
2. I noticed that this problem happens when it is the first word on the line. If there are any other words/characters before the current one, it works better, but not fully correctly.

**Platform**:
OS: `Windows 8.1`
Browser: `IE11`

**Version**:
Quill Version - `1.2.4`

**Comment by vbhargavmbis** [comment]
Here are screenshots of the expected and actual behaviour:

**Expected**
Screenshot taken on `Chrome` in `Windows 8.1`
<img width="1050" alt="screen shot 2017-08-17 at 5 02 38 pm" src="https://user-images.githubusercontent.com/6249105/29438829-27c0fab0-836e-11e7-966b-39336e271a6b.png">

**Actual**
Screenshot taken on `IE11` in `Windows 8.1`
<img width="1147" alt="screen shot 2017-08-17 at 5 01 50 pm" src="https://user-images.githubusercontent.com/6249105/29438840-3cd36172-836e-11e7-9c0d-941de90f794a.png">

**Comment by timamura2017** [comment]
What is the status?
When will this bug be fixed?
