### ISSUE TITLE
The line before code block will be removed when press backspace at the first of empty code block

### ISSUE THREAD

**Issue by zhipengyan** [quilljs/quill#1659]
This is the [screenshot](http://7vzpi4.com1.z0.glb.clouddn.com/QQ20170818-145445-HD.gif)
**Steps for Reproduction**

1. Visit quilljs.com
2. empty the code block
3. press backspace at the first of code block

**Expected behavior**:
clear the format of code block and delete the code block

**Actual behavior**:
the code block is cleared but the line before code block also been removed

**Platforms**:
macOS Sierra 10.12.6
chrome 60.0.3112.90

**Version**:
1.3.1

**Comment by jhchen** [comment]
This has been fixed in https://github.com/quilljs/quill/commit/9bc217ff725504e2762b8bffda51b0a2960ffb43 and will go out in the next release. Thanks for the report!
