### ISSUE TITLE
Declare span format with class attribute

### ISSUE THREAD

**Issue by rchrd2** [quilljs/quill#166]
Quill is amazing and has enabled us to develop a feature we never thought possibly with other Rich Text Editors. 

It has every feature we need, except the ability to assign CSS classes. I understand that using classes isn't ideal in terms of copy and pasting, but for our purposes, we want to dynamically add and remove classes so we can have many different types beyond the built-in formats.

We (@openhouse) tried this:

```
editor.addFormat('cssClass', {
    tag: 'span',
    attribute: 'class'
});
```

But then we started to get weird nested spans in the dom when removing and adding classes. 

Does anyone have insight in how to achieve this? Or did we discover a bug?

**Comment by KrisMerckx** [comment]
Quill is indeed great, but I don't understand why it's removing all h1-6-tags, p-tags, video-tags etc. What's the purpose of an editor when he removes everything he can create? 
Or maybe I don't understand the API enough. How can I prevent most tags from being removed and replaced by a terrible "div"?

**Comment by mariohd** [comment]
@KrisMerckx i do have the same issue =/ 

When i try to add a video tag, it is replaced by a div, the workaround that i did, was to add on other container and when i do submit the text, i do append the video tag. 

Maybe not the best solution, but it is working to add videos. I am trying to figure out how i will edit the content with video tags.

**Comment by jhaenchen** [comment]
I'm also looking to implement this sort of functionality. I'm trying to wrap every word in a span to highlight individual words on hover. I'd like to do this by adding a class to each wrapping span. Is this possible?

**Comment by jhaenchen** [comment]
@DunniAdenuga Yes I did, I believe I used some of the code found in https://github.com/quilljs/quill/issues/1036 to create a custom class attribute formatter.

**Comment by jhaenchen** [comment]
Pasted a code example in the other ticket

**Comment by jasonhoo95** [comment]
Hi i found out that when i copy paste inline format span, the class name will gone just show inline style, anyone had any idea whats wrong with it?

**Comment by thavus** [comment]
Same issue here. I only want to add a span with a class and quill strips it out every time.

**Comment by ardicoetzee** [comment]
Same issue here. If I have to type that again, my next conclusion will be that Quill sucks and no one should use it.

**Comment by boostani** [comment]
+1 - need to wrap certain content in a span and give it a css class.
