### ISSUE TITLE
Provide KeyboardEvent.key Support in Keyboard Module

### ISSUE THREAD

**Issue by weltenweber** [quilljs/quill#1660]
### Feature Request

Considering KeyboardEvent.which, KeyboardEvent.charCode, and KeyboardEvent.keyCode are deprecated and causing issues with international keyboard layouts (see use case below), maybe the Keyboard module could use KeyboardEvent.key for registering and handling keyboard events?

### Personal Use Case

I have a Quill instance with a keyboard handler that replaces the inch mark (") with the appropriate typographical quotation mark (“/”) depending on the position in the word. For a German keyboard the handler is registered for KeyCode 50 if the Shift-key is pressed, since this is how the inch mark is inserted on German keyboards. However, this wouldn’t work for US keyboard layouts since on those the inch mark is inserted using a different key. Being able to specify the inch mark (") as the key to handle (and checking its appearance with KeyboardEvent.key) would alleviate this issue.

**Comment by benbro** [comment]
I think it's part of the 2.0 branch:
https://github.com/quilljs/quill/commit/1c52076155e704fa35e19794b0b6e73930ec09a4

**Comment by weltenweber** [comment]
You are right. I missed that bug report while searching for one.
