### ISSUE TITLE
selection-change event not consistently emitted

### ISSUE THREAD

**Issue by abramz** [quilljs/quill#1661]
**Steps for Reproduction**

1. Visit [this codepen](https://codepen.io/abramz/pen/mMXKjg)
2. Observe the text `blured`
3. Focus the editor
4. Observe the text change to `focused`
5. Click outside of the editor
6. Observe the text change to `blured`
7. Focus the editor
8. Click the button that says "CLICKING ME DOESN'T UNFOCUS"
9. Observe that the cursor doesn't show up in the editor(meaning it was blured) but the text remains `focused`

**Expected behavior**:
As laid out [here](http://quilljs.com/docs/api/#selection-change), clicking anywhere on the page outside of the editor should fire a `selection-change` event, this includes clicking other UI elements like buttons.

**Actual behavior**:
Clicking on a button does not fire the `selection-change` event

**Platforms**:

Chrome: Version 60.0.3112.101 (Official Build) (64-bit)
OS: macOS 10.12.6 (16G29)

**Version**:

1.3.1

**Comment by jhchen** [comment]
Merging with #1397

**Comment by pavel06081991** [comment]
@jhchen, why did you close the issue when pull request is still not merged?
