### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by jasperf** [quilljs/quill#1662]
I have seen that Safari is not supported by Quill. What I have not seen anywhere in the old tickets is why it is not supported. I do see many people still using it with Safari nonetheless. And without issues it seems.

**Steps for Reproduction**

1. Visit https://github.com/quilljs/quill/
2. See crosses with Safari for Browser support
3. Check issues with Safari
4. No specific ones found

**Expected behavior**:
Explanation somewhere why Safari is not supported
**Actual behavior**:
None found
**Platforms**:
OSX MacOS Sierra
Include browser, operating system and respective versions
Safari
**Version**:
10.1.2

**Comment by jasperf** [comment]
My bad. It is supported for some versions. Got confused by x-es and check marks.

**Comment by arju1503** [comment]
does safari browser support Quill Editor ?
Here in my case the SlideIn page having quill editor is getting stuck. And needs one browser level activity( as minimize or maximize) to properly load.
