### ISSUE TITLE
Feature: Option to float the tooltip above the selection

### ISSUE THREAD

**Issue by petemcfarlane** [quilljs/quill#1666]
I'm trying to find a nice way to change the position of the tooltip to float _above_ the selected text. The only way I've managed to achieve this so far is by writing my own theme, and reimplementing (via copy/pasta) the BubbleTheme and BubbleTooltip classes. All I really want to change is the `position` method on `ui/tooltip`. I wondered if anyone else had this request, and if it would be useful to make it an option if the tooltip floats above/below the selection in Quill. I'm happy to try and submit a PR if the consensus is this would be useful, or does anyone have a better way I could implement this without re-creating the base bubble themes again?

**Comment by DmitrySkripkin** [comment]
What do you mean? Bubble theme toolbar is already has some kind of this behavior. You just have to specify `bounds` https://quilljs.com/docs/configuration/#bounds .
![bubble-theme screencast](https://s3-eu-west-1.amazonaws.com/fs.dev-lds.ru/files/f09914bf-78b8-e85d-ab75-3441e3ec1c43/toolbar.gif)

**Comment by petemcfarlane** [comment]
Thanks @DmitrySkripkin, that is almost exactly what I'm trying to achieve - when you hovered over "five" - but I want the bubble to always be above the selected text, not just when the bubble would appear out of the bounds.
<img width="291" alt="screen shot 2017-08-24 at 22 34 01" src="https://user-images.githubusercontent.com/3472717/29705300-47112fae-8975-11e7-92ea-5ac6b4f8b64e.png">

I tried to configure Quill by setting `bounds` to an element above the editor, and this seems to work! might this have any other side effects I should be wary of?

**Comment by DmitrySkripkin** [comment]
I didn't try to setting bound to anything expect `.ql-editor` or it's parent. Setting it to some element above editor sounds like a good idea to achieve "always above selection" behavior. But I'd rather test it more :)

**Comment by petemcfarlane** [comment]
Perhaps I can be the guinea pig then :)
