### ISSUE TITLE
Incorrect handling of code block when using inline styling

### ISSUE THREAD

**Issue by drego** [quilljs/quill#1669]
I'm currently trying to use Quill to create an editor and be able to format an email in HTML.
To allow the styling of the email content I'm using only inline styling attributes instead of the quill classes.
In order to use inline styling with the code-block feature, i'm using the following code:
```
var CodeBlock = Quill.import('formats/code-block'); 

class InlineStyleCodeBlock extends CodeBlock {
    static create(value) {
      	let node = super.create();
      	$(node).attr("style", "background-color: #23241f; color: #f8f8f2;"
        	+ " margin: 5px 0px; padding: 5px 10px;"
         	+ " border-radius: 3px; overflow: visible; white-space: pre-wrap;"
         	+ " counter-reset: list-1 list-2 list-3 list-4 list-5 list-6 list-7;");   
      	return node;
    }
} 
  
InlineStyleCodeBlock.blotName = "code-block";
InlineStyleCodeBlock.tagName = "pre";
Quill.register(InlineStyleCodeBlock, true);
```
This solution seems to work well for the most cases, except for the following one:

**Steps for Reproduction** (can be reproduced [here](https://codepen.io/djrego/pen/MvPmar))
1. Click on the _Code Block_ button **</>**
2. Write some text (optional)
3. Press enter to get a new code line
4. Click again on the _Code Block_ button **</>** to deactivate the code block

**Expected behavior**
After reaching the step 4, the result should be the following:
 ![Code Block 1](https://cld.pt/dl/download/283e7cbb-3767-45a6-89dd-c32f51021b65/code_block_1.png)

**Actual behavior**
After reaching the step 4, the result is the following:
 ![Code Block 2](https://cld.pt/dl/download/c80b8311-64e5-43da-9611-51e17f99cdfb/code_block_2.png)

**Platforms**
Google Chrome Version 58.0.3029.110 (64-bit)

**Version**
1.2.6

**Comment by mahmoudeljiddawi** [comment]
anyone find a solution for that?

**Comment by mahmoudeljiddawi** [comment]
Does anyone find a solution for that?
