### ISSUE TITLE
Modifying toolbar elements at runtime

### ISSUE THREAD

**Issue by wiiiteek** [quilljs/quill#1670]
Hello,

First of all sorry, for leaving question here, but a week ago I left same question tagged `quill` on StackOverflow but received no response.

So,  I am using QuillJS and I need to add some controls to toolbar at runtime. Is there any way to make it from code after whole Quill has  been initialized?

This is how I make it now.

```js
quillEditor.getModule('toolbar').addHandler('color', (value) => {
    if (value == 'new-color') {
        value = prompt('Type hex color!');

        // unfortunately this code does not work    
        let n = toolbar.querySelector('select.ql-color');
        n.innerHTML += '<option value="'+value+'"></option>';
    }

    quillEditor.format('color', value);
    console.log("Color handler", value);
});

```

**Comment by Silhm** [comment]
Hi there!
I had the same need. The solution I got for now is to create a toolbar with an html container.
Then add or remove a css class _.visible_ at runtime. 
Might not be the 'cleanest' way to do it, but it works ;)

**Comment by jhchen** [comment]
Duplicate #1891
