### ISSUE TITLE
Sometimes bold/italic/underline/link etc. does not work

### ISSUE THREAD

**Issue by h657070128** [quilljs/quill#1671]
**Steps for Reproduction**

1. Visit quilljs.com
2. Select some text, e.g. "Text Editor" in the title
3. Click Bold/Italic/Underline/Link icon

**Expected behavior**: The selected text get corresponding format

**Actual behavior**: Sometimes the cursor jumps to a strange place and the text does not get the requested format. In my example, the cursor jumps to the very beginning. I repeatedly refresh the page to try to reproduce the issue and almost 1 in 5 times it occurs. That is, refresh the page and do step 2 and step 3, if it works fine, refresh again until it occurs. Note that if it works fine, it will be all fine before the next refresh. If the bug occurs, the misbehavior will be there until the next refresh. In addition, not only the bold/italic/underline/link will stop work in that case, but also those which relies on a range of selection or cursor position will stop working.

**Platforms**:

With Chrome 60 and OS X 10.11.4
I tested in Chrome 60 on Win10, it has the same problem, also the Safari 9.x and IE 11.

**Version**:

Run `Quill.version` to find out: 1.3.1

Attached is the gif of the bug (1.7M, 30 seconds, a little bit large, may take several seconds to load). Hope it clears. The issue really bothers me. I am not sure if other people encounter the same.

![2017-08-29_21-00-12](https://user-images.githubusercontent.com/6769465/29823795-449c3382-8d02-11e7-8c98-12801a51d0bb.gif)

**Comment by Lufan** [comment]
Have the same issue.

**Comment by calepsol** [comment]
I have this bug in verison 1.3.6

**Comment by ten-nis** [comment]
I am also getting this bug in 1.3.5. Please provide the solution for this.

**Comment by GasdeX44** [comment]
im facing this issue even on 1.3.7. for me cursor jumps to the end of the document every time im selecting something Bold with button.

**Comment by benbro** [comment]
Please test with v2 beta
https://v2.quilljs.com/
