### ISSUE TITLE
Error with addMatcher

### ISSUE THREAD

**Issue by CWBudde** [quilljs/quill#1672]
I've been trying to add a matcher for a custom HTML tag ('B' in my case, as also given in the documentation). Unfortunately, it doesn't seem to work.

**Steps for Reproduction**:
Run pen at https://codepen.io/CWBudde/pen/dzQXNX

**Expected behavior**:
The output should be "Hello World!" with "World" being bold.

**Actual behavior**:
It throws the error: "Uncaught ReferenceError: Delta is not defined"

**Platforms and Versions**:
Windows 7, Chrome 60.0.3112.113
Quill v1.3.1 (see CodePen)

**Comment by f3ltron** [comment]
https://github.com/quilljs/quill/issues/1573 

you need to import it after load quill.js

var Delta = Quill.import('delta');

**Comment by CWBudde** [comment]
Thanks, I have missed that.
