### ISSUE TITLE
Insert embed + addmatcher doesnt work got undefined for attributes and value

### ISSUE THREAD

**Issue by f3ltron** [quilljs/quill#1675]
Hello and thank you a lot for your work

I want to create a add matcher for dangerouslyPasteHtml function. The matcher catch good my embed value. But when he recreate it. The embed is create but god undefined everywhere

** Reproduce **

click on 'write me' button

https://jsfiddle.net/5jco1eqc/1/

Expected behavior:

when the matcher match re create completely the embed

Actual behavior:

re create the embed but got undefined for all attributes

Platforms:

chrome

Version:

1.3.1

**Comment by f3ltron** [comment]
i got the same error on copy past

**Comment by CWBudde** [comment]
In your example you're passing true to the matcher instead of the expected node. I guess changing:

```
quill.clipboard.addMatcher('variable', function(node, delta) {
  return new Delta().insert({
    variable: true,
    ...
```
to something like

```
quill.clipboard.addMatcher('variable', function(node, delta) {
  return new Delta().insert({
    variable: node,
    ...
```

would already help.

**Comment by f3ltron** [comment]
not working. But i resolve it by modifying my embed blot

[https://jsfiddle.net/xghht8py/2/](https://jsfiddle.net/xghht8py/2/)
