### ISSUE TITLE
cursors visual position broken after insert an embed at the end of line

### ISSUE THREAD

**Issue by f3ltron** [quilljs/quill#1678]
When i insert an embed at most right side possible the cursor is put at the totally right side of the container.

**Steps for Reproduction**

1. Visit [https://jsfiddle.net/fmsx01b5/3/](https://jsfiddle.net/fmsx01b5/3/)
2. or see [http://imgur.com/a/RfnqD](http://imgur.com/a/RfnqD)
3. click on Prenom button
4. watch where the cursor is

**Expected behavior**:

the cursor must be just at the right fo the embed

**Actual behavior**:

the cursor is at the full right of the container. What is strange here. Is that the cursors is at the good place because if you write on it he will be just at the good position after.

**Platforms**:

chrome/firefox

**Version**:

1.3.1

**Comment by jhchen** [comment]
Don't make your Embed contenteditable=false. The native embed already does and this is interfering with a fix the Embed has built in for this issue.

**Comment by pedrosanta** [comment]
That comment saved my life. Searched for 'selection' at a first instance, but then 'cursors' did the trick. Use search folks! #protip 😎

**Comment by pedrosanta** [comment]
Though, I feel the cursor should end up after the embed - it's currently ending before the embed, see https://codepen.io/pedrosanta/pen/NwgWOJ.

**Comment by jhchen** [comment]
You can just call setSelection after insertEmbed

**Comment by pedrosanta** [comment]
@jhchen Yep, true, fair enough. 🙂
