### ISSUE TITLE
Font style and size is not respected

### ISSUE THREAD

**Issue by chinshr** [quilljs/quill#168]
I want Quill to respect my font style and size or at least let me initialize it  e.g.

``` HTML
<div class="editor" style="font-size: 24px;  font-family: Arial">
  My text to edit.
</div>
```

``` JavaScript
/* or let the constructor take care of it */
var editor = new Quill("#editor", {
  'css': {
    "font-size": "24px",
    "font-family": "Arial"
  }
});
```

**Comment by devtimi** [comment]
I can't get this configuration to work.  I've confirmed that some configurations work like background-color, but font-size is overridden by a mysterious .ql-line style set at 15px!important

**Comment by jhchen** [comment]
What version of Quill are you using? I can't find any !important rules in Quill's source.

**Comment by devtimi** [comment]
Version 0.19.8
Here's what Inspect Element is showing
![screen shot 2015-04-11 at 16 54 52](https://cloud.githubusercontent.com/assets/2067469/7103230/8b7013a0-e06b-11e4-9146-64893e670b8d.png)

**Comment by jhchen** [comment]
If I'm not mistaken that says the style is coming from a user defined file called quil.html. The Quill library styles should come from a `quill.css` or `quill.snow.css`. Also a `/*ffs*/` comment would not have passed code review.

**Comment by devtimi** [comment]
Line 1 is `<!DOCTYPE html>`
The comments look sequential, so I'm not sure `/*ffs*/` is intentionally offensive from wherever it originated.  I'm going to try updating to 0.19.10 to see if that helps, but I'm not very confident it will.
