### ISSUE TITLE
Which method will call when blot changes?

### ISSUE THREAD

**Issue by szobov** [quilljs/quill#1683]
I create this issue because i did't get answer on same my question on [stackoverflow](https://stackoverflow.com/questions/44864211/quill-which-method-called-when-blot-changed).
Copied from SO:
I need to do something when text, wrapped with my own blot, changes.

From [parchment documentation](https://github.com/quilljs/parchment/#blots) i got that method `update` will call when blot changes. I try to use it in code, but this method wasn't called when text, wrapped with my blot, changes.

May be I use this method incorrect? Or I should use another method?

**Steps for Reproduction**

1. [Visit](https://codepen.io/szobov/pen/vZRmGK)
2. Change text in editor

**Expected behavior**:
Method `update` will execute and in console we will can see `>> updated` and debugger will be open.

**Actual behavior**:
Method update didn't executed.

**Version**:

Latest

**Comment by DmitrySkripkin** [comment]
I don't know how it works and why update is not called. But there is method called `optimize()` which work ok for me. But I feel really uncomfortable and hope anyone can explain it.

**Comment by szobov** [comment]
@DmitrySkripkin yep, but method `optimize()` called for all blots which has the same class. For [example](https://codepen.io/szobov/pen/yowKyM), if you open the console and change text, which wrapped with custom blot class, you will see that method `optimeze()` called twice for both blots, although only one has changed. It's not suitable for me.

**Comment by szobov** [comment]
@jhchen Sorry for disturb you, but maybe i asked my question not so clear?
Can you guide me, where i can read about how this function should work?

**Comment by MartinMalinda** [comment]
Can confirm, `update` on `blot` does not get called on text change, `optimize` gets called basically all the time. In my case I can get away with updating all of blots on any text change in my whole editor because the change is lightweight but it doesn't feel right at all.

So I'm doing this workaround:

```ts
editor.on('text-change', (delta) => {
  // handle timestamp edit
    const selectionIndex = editor.getSelection()?.index;
    const leaf = selectionIndex && editor.getLeaf(selectionIndex)?.[0];
    const getTimestampLeaf = (leaf) => leaf instanceof TimestampBlot ? leaf : leaf?.parent ? getTimestampLeaf(leaf.parent) : undefined;
    const timestampLeaf = getTimestampLeaf(leaf);
    if (timestampLeaf) {
      timestampLeaf.update(); 
    }
});
```

I guess it could be modified to call `update()` on any blot affected, but I need it only for the timestamp really.

Also I'm just now playing with this. This works for calling `update()` but I'm not sure manipulating the DOM in `update` is the right thing to do and if it will get synced with delta accordingly. Will see.

**Comment by szobov** [comment]
Hi @MartinMalinda 

Thanks for the reply, tbh I gave up working with quill, but before I left I asked a question on StackOverflow about this thing. Someone even [answered](https://stackoverflow.com/a/51978998/6822425) me, but I didn't have a chance to check it.
Maybe it could somehow help you.

Best regards,
Sergei
