### ISSUE TITLE
Cannot display certain types of toolbar buttons

### ISSUE THREAD

**Issue by AndrewIsh** [quilljs/quill#1684]
When manually defining the buttons to be used in the toolbar module, it seems that certain ones do not display, for example:

![image](https://user-images.githubusercontent.com/9194223/30032865-065cc9b4-9190-11e7-88e2-d38e7409b95d.png)

I have replicated this for `list`, `size`, `script`, `indent` it may affect others.

**Steps for Reproduction**

1. Visit https://quilljs.com/playground/
2. Change the `bold` button in the array to `list`
3. Observe that the `list` button does not display

**Expected behavior**:

The specified button should display

**Actual behavior**:

The specified button does not display

**Platforms**:

Tested on Chrome 60.0.3112.101 (Official Build) (64-bit) on Debian Jessie 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15) x86_64 GNU/Linux

**Version**:

1.2.0

**Comment by DmitrySkripkin** [comment]
That's not an issue.
You can see icons list here [icons.js](https://github.com/quilljs/quill/blob/develop/ui/icons.js).
So Quill has list, script and indent icons, but you need to pass more then just `list`. Also you can modify icons yourself if there is no icon in the list (like `size`).
Please, check this [CodePen example](https://codepen.io/DmitrySkripkin/pen/jLjQGO)

**Comment by AndrewIsh** [comment]
Oh, that's embarrassing. Sorry for the non-issue, I'll read the docs more carefully next time!

Many thanks for your help @DmitrySkripkin
