### ISSUE TITLE
Status for iOS?

### ISSUE THREAD

**Issue by danielchristopher1** [quilljs/quill#1688]
Looking through these issues, I notice there are many uncertainties for compatibility with iOS devices.

As of now, is there a known range of iOS versions that would work with Quill?

Thank you.

**Comment by benbro** [comment]
You can find the list of supported browsers and versions on the [README](https://github.com/quilljs/quill/blob/develop/README.md).
If you found a bug please report it.

**Comment by danielchristopher1** [comment]
Currently, it states that iOS supports versions 9.3 and 10.2.
Does this include all versions between those?

**Comment by benbro** [comment]
Yes

**Comment by danielchristopher1** [comment]
Thank you :)
