### ISSUE TITLE
Quill 1.3.2 - There is a max indent level for lists at 9 indents... why is this?

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#1692]
Quill limits the amount of indents you can make. Here is the relevant code:

```
let IndentClass = new IdentAttributor('indent', 'ql-indent', {
  scope: Parchment.Scope.BLOCK,
  whitelist: [1, 2, 3, 4, 5, 6, 7, 8]
});
```

The whitelist array makes it so the max indent level is 9. If I expand that array, or just comment it out, there is no max indent. I tested this and indeed increasing whitelist array or commenting out allows more indents. My users would like to indent more than 9 levels. So I guess I will have to increase the whitelist array. Or just comment it out.

But @jhchen  why was this done in the first place?

**Steps for Reproduction**

1. Visit quill demo
2. Try and indent a bullet list more than 9 levels

**Expected behavior**:

No max indent level, or max level much higher

**Platforms**:

Chrome on Mac

**Version**:

1.3.2

**Comment by jhchen** [comment]
While the data layer would allow it, CSS controls the visual output so beyond a certain point they would look the same without additional CSS rules. We could set this to a very high number like 25 but rules that control which numbering style to use (1. vs a. vs i.) would contribute to a significant increase in the stylesheet size.

**Comment by sferoze** [comment]
@jhchen ah I see, I noticed that in the code you have a MAX_TABS value set to 9. So I increased the white space array to 12 and MAX_TABS value to 12 and then I rebuilt quill. 

Seems to be working, the css generated for indent level 12 and the class is applied. Let me know if this is wrong to do

**Comment by jhchen** [comment]
Yup that should be right

**Comment by SuperAL** [comment]
> MAX_TABS

MAX_INDENT in packages/quilljs/assets/core.styl
