### ISSUE TITLE
Quill Js not working inside a form.

### ISSUE THREAD

**Issue by RageItalic** [quilljs/quill#1694]
I am trying to use Quill Js on a blog so that I can allow users to format their text and display it. I am including the script tags and everything that I need (from the official site) in my html and I've added the class "editor" to a textarea inside a form. The toolbar shows up on the page now and I can select all the options, but those options have not effect on my text and I do not know why.

**Here is my code**
```     
<form method="post" action="/submitArticle" id="blogForm" enctype="multipart/form-data">
        <div class="file">
          <label class="file-label">
            <input class="file-input" type="file" name="image">
          </label>
        </div>
        <div class="field">
          <label class="title is-4">Title</label>
          <div class="control">
            <input class="input" name="title" type="text" id="Title" placeholder="Give your story a title..." required>
          </div>
        </div>
        <div class="field">
          <label class="title is-4">Story</label>
          <div class="control">
            **<div id="toolbar"></div>
            <textarea class="textarea editor" name="story" id="story" rows="7" placeholder="Tell your story here..." required></textarea>**
          </div>
        </div>
        <div class="field is-grouped is-grouped-right">
          <p class="control">
            <input class="button is-primary" type="submit" id="button">
            </input>
          </p>
        </div>
      </form>
```

**Expected behavior**:
Changes that I make through the toolbar should be reflected in the text.

**Actual behavior**:
Nothing happens to the text when I select options and type

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
Quill works with a div, not textarea.
[This example](https://quilljs.com/playground/#form-submit) show how to sync the editor with a form field.
