### ISSUE TITLE
I want to insert a nested HTML snippet

### ISSUE THREAD

**Issue by Kanchil** [quilljs/quill#1695]
![image](https://user-images.githubusercontent.com/20110220/30421366-23c5593a-996f-11e7-86c4-11f87c783faa.png)
this.editor.clipboard.dangerouslyPasteHTML(range.index,html);

# Is there any good way

**Comment by Patricklea** [comment]
Does this way work?

**Comment by Kanchil** [comment]
yes

**Comment by benbro** [comment]
Only a subset of HTML elements is supported.
See
https://quilljs.com/docs/formats/
https://quilljs.com/docs/modules/clipboard/
