### ISSUE TITLE
Formula insertion does not work

### ISSUE THREAD

**Issue by tarjei** [quilljs/quill#1696]
**Steps for Reproduction**
1.Visit this fiddle https://codepen.io/anon/pen/ZXYqRa
2. press insert formula
3. write something in the input
4. press "save"

**Expected behavior**:
A formula should appear
**Actual behavior**:
Quill just inserts an empty space

**Platforms**:
Tested on current chrome and firefox on Ubuntu 17.04.

**Version**:
Tested with quill 1.2.6 and 1.3.2

**Comment by shashank-sharma** [comment]
Hi
I was testing this feature in your codepen fiddle and then I notice that if we add 'formula' inside formats array then it will work fine else it will add white space. 
I tested this in chrome/firefox on Ubuntu 16.04.
Fiddle: https://codepen.io/shashank-sharma98/pen/BwoRde

**Comment by tarjei** [comment]
Duh! 

Thanks. I'll see if I can suggest a PR for the docs.

**Comment by tarjei** [comment]
Duh! 

Thanks. I'll see if I can suggest a PR for the docs.
