### ISSUE TITLE
Support custom values in buttons in the toolbar

### ISSUE THREAD

**Issue by jhchen** [quilljs/quill#170]
Currently buttons in the toolbar can only toggle a value on/off. It should be support custom values. For example to implement a UI where each text alignment icon is a button.

The concept of grouping/exclusivity will also have to be introduced for this feature to be useful. For example, the text align left and text align right buttons cannot be simultaneously on.

**Comment by renancouto** [comment]
Has this feature being implemented yet? I couldn't find anything about this on the docs.

**Comment by jhchen** [comment]
No this is still an open Issue.

**Comment by jbhamilton** [comment]
Any progress on this?

**Comment by wpscholar** [comment]
I'd like to see this as well.  Is this moving forward?

**Comment by jhchen** [comment]
This has been added in the [beta](http://beta.quilljs.com/) release by setting a `data-value` attribute on buttons.
