### ISSUE TITLE
Does the quill editor support table?

### ISSUE THREAD

**Issue by asktalk** [quilljs/quill#1700]
Same as above

**Comment by stephenLYao** [comment]
discussed [117](https://github.com/quilljs/quill/issues/117)

**Comment by soccerloway** [comment]
Hi, I really like the extensibility of Quill a lot.
I implement a module [quill-better-table](https://github.com/soccerloway/quill-better-table) to add support for tables.
Online demo is here: [quill-better-table demo](https://codepen.io/soccerloway/pen/WWJowj)
Hope that quill-better-table could help someone who need to edit/render table in quilljs.

Requirements: quill.js v2.0.0-dev.3
