### ISSUE TITLE
WebDriver unable to test/interact with image upload

### ISSUE THREAD

**Issue by ryancastro** [quilljs/quill#1701]
WebDriver isn't able to interact with the Image Upload feature of QuillJS. This makes it difficult to test, and difficult to consume.

Each implementation of WebDriver has native magic to work with file inputs. You send your filepath to it, and it magically throws the file in there. QuillJS has a cool image upload feature that uses file inputs to grab jpg data and put it into a datastream and stick it into the DOM. Unfortunately, it also calls "click" on the file field so a user can select a file to upload. The "file upload" selection box popped up by the browser can't be interacted with by WebDriver, according to W3C specifications. So, the box simply remains open during testing, and depending on browsers, also fails your test.

**Steps for Reproduction**

Using WebDriver, attempt to upload a file to QuillJS. I have tried sending keys to the fileinput created by the .ql-image button, as well as a variety of other interaction points.

```ruby
  require 'selenium-webdriver'
  browser = Selenium::WebDriver.for :chrome
  browser.navigate.to "https://quilljs.com/playground/"
  browser.manage.window.maximize
  browser.switch_to.frame 0
  browser.switch_to.frame "result-iframe"
  sleep 2

  #Scenario 1
  image_button = browser.find_element(css:".ql-image")
  image_button.send_keys "c:\\test.jpg"
  #OR
  #Scenario 2
  file_upload = browser.find_element(css:"[type = 'file'][class = 'ql-image']")
  file_upload.send_keys  "c:\\test.jpg"
```
**Expected behavior**:
WebDriver is able to consume the image upload feature of QuillJS. QuillJS is fully testable with W3C-spec industry standard WebDriver.

**Actual behavior**:
WebDriver has a limited ability to use this feature - the browser's file upload dialog box sits in the way and per W3C spec, there is no way to interact with that box.

**Platforms and Versions**:
Windows 10
ChromeDriver 2.32.498550
ruby 2.2.5p319
Selenium WebDriver 3.4.0
Whatever version of Quill is on "https://quilljs.com/playground/"

**Comment by jhchen** [comment]
What is your suggestion? I would like the file input to open for usability reasons.

**Comment by parikshithk** [comment]
@ryancastro How did you resolve this issue?
