### ISSUE TITLE
Display quill format on iOS native views

### ISSUE THREAD

**Issue by linyize** [quilljs/quill#1703]
I started a project https://github.com/hivecms/quillview. QuillView is to display quill format on iOS native views. Your comments are welcome.

**Comment by DmitrySkripkin** [comment]
That is great. Sorry I don't know much about iOS development, but I see something called "CSSParser". What about custom blots and formats (mentions hashtags and etc.)?

**Comment by linyize** [comment]
The example project use CSSParser to read cssstyle and turn into QuillView styles.
QuillView v0.1.0 currently support official formats in https://quilljs.com/docs/formats/.

You can ask for  custom formats support on quillview/issues, I will consider it.

**Comment by NGyc** [comment]
怎么在编辑器中插入<div></div>标签，并给标签添加一个class，例如<div class='box'></div>

**Comment by benbro** [comment]
Consider sharing on [awesome-quill](https://github.com/quilljs/awesome-quill) thanks.
