### ISSUE TITLE
AWS hosting quilljs package build fails

### ISSUE THREAD

**Issue by dbsdragon** [quilljs/quill#1704]
The quilljs is being hosted on aws s3 which github redirects to, this causes this build to fail on a corporate server due to firewall issues, can we host it within github like most other packages?

**Comment by dbsdragon** [comment]
println "curl -x http://someproxy:8080 https://github.com/quilljs/quill" redirects to https://github-production-release-asset-blabla.s3.amazonaws.com

**Comment by jhchen** [comment]
If you are talking about the source code Quill is clearly hosted on Github like most other packages. If not please clarify.
