### ISSUE TITLE
Background-color: #fff and color: #000 are not added to inline styles

### ISSUE THREAD

**Issue by lukaszptr** [quilljs/quill#1708]
Setting background color to white and forecolor to black just resets those values. Suppose we have a div with black bg. We are unable to set font forecolor to white.

**Steps for Reproduction**

1. Visit https://codepen.io/anon/pen/mBPoaZ
2. Write something in a editor
3. Change font color to black and background color to white.

No inline styles are added.

**Comment by jhchen** [comment]
Then the default values need to be changed in Quill as well. Take a look at how this is done for [fonts](https://quilljs.com/playground/#custom-fonts) and the same technique can be applied to colors.
