### ISSUE TITLE
How to Programmatically Apply Syntax Highlighting

### ISSUE THREAD

**Issue by jmquigley** [quilljs/quill#1709]
How do I programmatically apply syntax highlighting to a selected region?  If I make a region like:

    function test() {
    }

I highlight it with the mouse and click the code button it will change the region.  If I use:

    this.quill.formatText(start, len, {
        code: true
    }, 'silent');

It doesn't apply the code, it just puts `<code>` tags around each line.  Is there a way in the api to apply highlighting from the syntax module?

Using Quill v1.3.2.

**Comment by jhchen** [comment]
`code` is the inline code format, you want to do `code-block`.

**Comment by jmquigley** [comment]
Thank you for the quick response.  That fixed the issue I was having.
