### ISSUE TITLE
Setting scrollingContainer not working

### ISSUE THREAD

**Issue by ggCS** [quilljs/quill#1714]
**Steps for Reproduction**

1. Set `scrollingContainer` to `#mainQuillEditor` the container which holds `ql-editor`.

**Expected behavior**:
Scrolling is handled within `mainQuillEditor`
**Actual behavior**:
Scrolling is handled by `ql-editor`

Include browser, operating system and respective versions
Chrome Version 60.0.3112.113
Quill Version 1.2.4

**Comment by jhchen** [comment]
That's not what scrollingContainer does please see its documentation.
