### ISSUE TITLE
Quill can't open editor content containing </script>

### ISSUE THREAD

**Issue by TheMightyPope** [quilljs/quill#1715]
If the document contains the text "</script>", quill fails to load it. This happens if you set the placeholder (Shown below), or using insertText. It works fine if the content is initially set in html. and the </script> also shows up in the editor when writing it. It only fails while loading the deltas back. The example below should be enough to reproduce it I hope.

**Steps for Reproduction**
Run this on the quill playground. Note that other </xxx> tags work just fine, it seems to only fail on </script>.

----- PLACEHOLDER EXAMPLE -----

var quill = new Quill('#editor-container', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
      ['image', 'code-block']
    ]
  },
  **placeholder: '</script>',**
  theme: 'snow'  // or 'bubble'
});

----- insertText EXAMPLE -----

var quill = new Quill('#editor-container', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
      ['image', 'code-block']
    ]
  },
  placeholder: 'Compose an epic...',
  theme: 'snow'  // or 'bubble'
});

quill.insertText(0, '</script>', 'bold', true);

**Expected behavior**: 
Load the document or the placeholder correctly

**Actual behavior**: 
Quill fails.

**Platforms**: 
Chrome

**Version**: 
1.3.2

**Comment by jhchen** [comment]
This appears to be a codepen issue: https://codepen.io/quill/pen/QqGYXr. I'll file a support ticket with them.

**Comment by TheMightyPope** [comment]
Thanks, it might very well be codepen also has this issue (surprisingly) :-). 

However, when my production code saves a branch with </script> and loads it back in (literally loading the deltas back), the same happens.  I can add it in the editor, but reloading it seems to trigger this too.

**Comment by TheMightyPope** [comment]
You know, I tried just now creating a test case for this in my code, and it worked OK. So I'm going to go debug some more, and basically Codepen write this off until I have some code that can do it, or not. Maybe CodePen coincidentally had the same bug MY code had, and not quill... I'll open another ticket if I can reproduce this. Thanks again.
