### ISSUE TITLE
Quill  & contenteditable embeds w/ collaborative edition

### ISSUE THREAD

**Issue by guillaumepotier** [quilljs/quill#1720]
**Steps for Reproduction**

1. [https://codepen.io/guillaumepotier/pen/WEqrBd](https://codepen.io/guillaumepotier/pen/WEqrBd)

**Expected behavior**:
I'd expect not to loose focus and caret position in my embed while other users collaborate on the document

**Actual behavior**:
Due to cursor operations, I loose my focus and caret position

**Platforms**:
Latest Chrome

**Version**:

1.2.6

** What I tried **

I thought that if I focused out the editor and clear the current Selection, there would not be caret and focus manipulation by Quill on new content. **Was that a correct assumption?**

I detect that I'm in a content editable embed inside quill, and then do a `quill.setSelection(null)` to blur/focus out the editor an reset range. But It seems that `quill.getSelection()` is not erased/cleared :s

**Comment by jhchen** [comment]
This looks like a bug in Quill. Normally, content changes may cause the selection to be lost so Quill saves and restores it. However the restoring sees Embeds as an atomic unit so it cannot place the cursor inside it.

**Comment by guillaumepotier** [comment]
> However the restoring sees Embeds as an atomic unit so it cannot place the cursor inside it.
I noted that when I place cursor in my RichElements/Embeds Quill puts the cursor on the index before it. Quill `selection` is not `null`, we have an `index` and a `range` defined. What is the expected behaviour? 

I'd be glad to help on that one next week, I'll have some time.
