### ISSUE TITLE
After sup tag insertion, sup tag button is not highlighted in the toolbar

### ISSUE THREAD

**Issue by pavel06081991** [quilljs/quill#1721]
Here is example:
https://codepen.io/anon/pen/LzxGYj

When there is no text in editor and you press custom button ★, it add ★ and tag sup around this character. The sup button in the toolbar is highlighted. But when there is text in the editor, for example "hello" and you press custom button ★, the sup button in the toolbar is not highlighted.

**Comment by alexkrolick** [comment]
Tracking in React Quill at https://github.com/zenoamaro/react-quill/issues/271

I _think_ this is an issue with RQ only, TBD.

**Comment by alexkrolick** [comment]
Confirmed that this does not affect Quill itself: https://codepen.io/alexkrolick/pen/yzbVXV?editors=0010

**Comment by jhchen** [comment]
Cool thanks for taking a look @alexkrolick !
