### ISSUE TITLE
Inserting a hyphen deletes text

### ISSUE THREAD

**Issue by altschuler** [quilljs/quill#1723]
**Steps for Reproduction**

1. Visit quilljs.com
2. In the editor place cursor after first paragraph
3. Turn on bold
4. Type "foo" (or anything else)
5. Turn off bold
6. Type `<space><hyphen><space>` (actual spaces " " and hyphen "-")

**Expected behavior**:
No text should be deleted

**Actual behavior**:
The first three characters of the _paragraph_ are deleted.

**Platforms**: all
**Version**: latest

**Comment by benbro** [comment]
I can reproduce with:
Firefox 55, Windows 7
Quill 1.3.2

**Comment by benbro** [comment]
Also happens with Quill 1.30.
In Quill 1.2.1 - 1.2.6 the characters aren't deleted but a bullet is created instead of adding the hyphen.
Quill 1.2.0 works as expected.

**Comment by altschuler** [comment]
Thank you for testing that! :)
