### ISSUE TITLE
Quill auto-saver with MongoDB : Best practices

### ISSUE THREAD

**Issue by phenric** [quilljs/quill#1726]
Hi,

I wonder what are the best practices to use Quill auto-saver with Mongo. In other words, I try to implement Quill in a personal project using MongoDB. I use the [auto-saver](https://quilljs.com/playground/#autosave) for that.

I would like to know how proceed to load Delta in Mongo. Do you translate Delta to html each time the auto-saver runs ? Do you replace all the file in Mongo ? What are your advices ?

It could sound like a silly question but I'm not sure how to proceed.

Thanks for your help

**Comment by jhchen** [comment]
Since Deltas is JSON and MongoDB stores JSON I don't see why one would convert to something not JSON.
