### ISSUE TITLE
How to add a css class to an img element

### ISSUE THREAD

**Issue by ModPhoenix** [quilljs/quill#1728]
img src="" class="img-fluid" alt="Responsive image"

const range = quill.getSelection();
quill.insertEmbed(range.index, 'image', `${url}`);
quill.pasteHTML(range.index, `<img src="${url}" class="img-fluid" alt="Responsive image">`);

**Comment by benbro** [comment]
you need to add a custom class attributor:
https://codepen.io/anon/pen/PGRQrx

**Comment by ModPhoenix** [comment]
```
var Image = Quill.import('formats/image');
Image.className = 'img-fluid';
Quill.register(Image, true);
```

**Comment by NGyc** [comment]
问题解决了吗？求解决办法

**Comment by ModPhoenix** [comment]
@NGyc yes 
```
var Image = Quill.import('formats/image');
Image.className = 'img-fluid';
Quill.register(Image, true);
```

**Comment by benbro** [comment]
@ModPhoenix looks like you found how to do it.
Closing

**Comment by NGyc** [comment]
抱歉，我是初学者，看不太懂具体是怎么去设置，可不可以再写详细一点呢，谢谢了！

**Comment by ModPhoenix** [comment]
```
var Image = Quill.import('formats/image');
  Image.className = 'img-fluid';
  Quill.register(Image, true);

  const quill = new Quill('#editor-container', {
    modules: {
      toolbar: '#toolbar-container'
    },
    placeholder: 'Compose ansdfdsfsdf epic...',
    theme: 'snow'
  });
```

**Comment by NGyc** [comment]
比如我现在要插入一个<img src='./1.jpg'/>, 怎么给插入的img添加一个class呢？

**Comment by zhoushuren** [comment]
@ModPhoenix alt属性以及width或者自定义的属性怎么破？在线等，急！

**Comment by Mkluas** [comment]
@zhoushuren 请问width属性找到方法了吗

**Comment by zhoushuren** [comment]
@Mkluas 我是重写Image组建实现的。

**Comment by rasxod** [comment]
для добавления `class` при `quill.pasteHTML(range.index, _img_html);`

нужно добавить `class` в массив пропускаемых атрибутов
**quil.js** string _10721_
```
var ATTRIBUTES = ['alt', 'height', 'width', 'class'];
```

**Comment by EduardoRdzNeavez** [comment]
> ```
> var Image = Quill.import('formats/image');
> Image.className = 'img-fluid';
> Quill.register(Image, true);
> ```

dude you're my friday 7pm hero lol, thanks alot
