### ISSUE TITLE
Editor does not preserve super text when pasted from itself

### ISSUE THREAD

**Issue by pavel06081991** [quilljs/quill#1729]
I guess it is the same issue like https://github.com/quilljs/quill/issues/306 but for tag "sup". When I copy text which contain "sup" tag and paste it again, "sup" tag is removed. This issue is reproduced only in Chrome. In Firefox there is no issue.

**Comment by benbro** [comment]
I can reproduce with Chrome 121, Quill v1.3.7 
Can't reproduce with Chrome 121, Quill v2.0.0-beta.2
