### ISSUE TITLE
I can add data attribute to html tags?

### ISSUE THREAD

**Issue by ModPhoenix** [quilljs/quill#1733]
I want to add support for PhotoSwipe, for this I need to add data-size = "600x400" attribute.

example:
```
<a href="https://farm4.staticflickr.com/3894/15008518202_c265dfa55f_h.jpg" data-size="1600x1600"
       <img src="https://farm4.staticflickr.com/3894/15008518202_b016d7d289_m.jpg" alt="">
</a>
```
example code that I use:

```
function insertToEditor(data) {
    // push image url to rich editor.
    const range = quill.getSelection();
    // quill.insertEmbed(range.index, 'image', `${data.link}`);
    quill.pasteHTML(range.index, `<a href="${data.link}"><img src="${data.link}" class="img-fluid" alt="${data.name}"></a>`);
  }
```

**Comment by guillaumepotier** [comment]
Hi there,

I think you should create a custom Blot (eg. PhotoSwipeBlot) that extend Embed blot and set your attribute to it.

The [cloning Medium tuto](https://quilljs.com/guides/cloning-medium-with-parchment/) should help you doing so I think.

Best

**Comment by ModPhoenix** [comment]
Thanks for the advice, could you give an example of implementation for such a template:
```
<a href="https://farm4.staticflickr.com/3894/15008518202_c265dfa55f_h.jpg" data-size="1600x1600"
 <img src="https://farm4.staticflickr.com/3894/15008518202_b016d7d289_m.jpg" alt="">
</a>
```
it would be very cool thanks
