### ISSUE TITLE
Lists from dangerouslyPasteHTML do not nest properly.

### ISSUE THREAD

**Issue by jxbaker** [quilljs/quill#1736]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit https://quilljs.com/playground/
2. Enter the following js:
```
var quill = new Quill('#editor-container', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
      ['image', 'code-block']
    ]
  },
  placeholder: 'Compose an epic...',
  theme: 'snow'  // or 'bubble'
});

quill.clipboard.dangerouslyPasteHTML(`<ol>
  <li>Level 1
    <ol>
      <li>Level 2
        <ol>
          <li>Level 3</li>
        </ol>
      </li>
    </ol>
  </li>
  <li>Level 1 again</li>
</ol>`);
```

**Expected behavior**:

![image](https://user-images.githubusercontent.com/13337985/31090150-a36cd9f2-a774-11e7-94ba-491aafeaf582.png)

**Actual behavior**:

![image](https://user-images.githubusercontent.com/13337985/31090133-902bc6b4-a774-11e7-948f-8ad4cd6b79b0.png)

NOTE: if you arrange the html as follows, it does display correctly:

```
<ol>
  <li>Level 1</li>
    <ol>
      <li>Level 2</li>
        <ol>
          <li>Level 3</li>
        </ol>
    </ol>
  <li>Level 1 again</li>
</ol>
```

**Platforms**:

Include browser, operating system and respective versions

Google Chrome | 61.0.3163.91 (Official Build) (64-bit)
-- | --
Revision | 2f544949507dc5330b714cb017e3f584e791a1bf-refs/branch-heads/3163@{#1194}
OS | Linux
JavaScript | V8 6.1.534.37

Ubuntu 16.04 LTS

**Version**:

1.3.2

**Comment by jxbaker** [comment]
Note: the same thing happens if you creates the nest structure in LibreOffice Writer and paste it into the editor.

**Comment by jhchen** [comment]
As it states in the docs "The snippet is interpreted by Clipboard matchers, which may not produce the exactly input HTML." It is not a project goal to perfectly interpret HTML input.
