### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>

### ISSUE THREAD

**Issue by asolopovas** [quilljs/quill#1739]
Hi, 
If I follow the guide that you have specified here [adding quill to you build pipeline](https://quilljs.com/guides/adding-quill-to-your-build-pipeline/#entry ) I am receiving an error `Cannot assign to read only property 'exports' of object '#<Object>`  when importing the package.

The issue is probably related to https://github.com/webpack/webpack/issues/4039, and is due to that quill.js and core.js use `module.exports = Quill`. If I replace  `module.exports = Quill` with `export default Quill` the error disappears.
 
Unlike the  webpack example that you provided my project utilises typescript and babel so Quill is imported into babel js files which results in the error described above. Do you know a way around it? Or would you be kind enough to accept pull request for replacing it to  export default instead?

**Comment by jhchen** [comment]
Duplicate #1377
