### ISSUE TITLE
How to use in develop mode and contribute?

### ISSUE THREAD

**Issue by guillaumepotier** [quilljs/quill#1740]
I feel a bit ashamed by this question.

But I'm a bit lost on how to update Quill and contribute. I mean, in my project, webpack loads the minified `dist/quill.js` file, and I don't want to make modifications on it. How to tell my webpack to use `./quill.js`?

This is in my project. If I fork and pull `quilljs/quill` here, I face the same problem. `npm/start` does build dist files. How should I do? Compile minified file on each modification and reload my page (like tests in codepen ?).

Won't be great to have a `webpack-dev-server` working configuration allowing us to benefit from hot reloading and stuff?

Maybe I missed something here, If you could ease my contributing life I'd be more happy to help here :)

Best

**Comment by benbro** [comment]
Does this help?
http://quilljs.com/guides/adding-quill-to-your-build-pipeline/
https://github.com/quilljs/webpack-example

**Comment by guillaumepotier** [comment]
Man, this is exactly what I needed... Sorry not beeing able to find it by myself O_o

I managed to integrate Quill in my webpack pipeline [thanks to that file](https://github.com/quilljs/webpack-example/blob/master/webpack.conf.js), not parchment though. I'm having this kind of error:

```
ERROR in ./~/parchment/src/parchment.ts
Module not found: Error: Can't resolve './registry' in '/Users/guillaumepotier/Sites/loop-front/node_modules/parchment/src'
 @ ./~/parchment/src/parchment.ts 15:15-36
 @ ./~/quill/core.js
 @ ./~/quill/quill.js
```

**Comment by guillaumepotier** [comment]
Other question @benbro. Now I integrate properly Quill in my pipeline, suppose I make changes and want to make a PR here, how should I do? copy/paste my changes on my quill fork (not very handy)? Should I use a git submodule of my fork in my project to avoid that?

Thanks for your tips

**Comment by benbro** [comment]
Pull requests:
https://github.com/quilljs/quill/blob/master/.github/CONTRIBUTING.md#pull-requests

If you only want to experiment with Quill, you can follow this:
https://github.com/quilljs/quill/blob/master/.github/DEVELOPMENT.md

**Comment by benbro** [comment]
Looks like you managed to setup up the development environment.
