### ISSUE TITLE
Custom button with text to disable Quill on a React component

### ISSUE THREAD

**Issue by harmeetjaipur** [quilljs/quill#1742]
Hi, I would first like to say that I really like your text editor. It works smoothly even with strings containing html in them, which has been a challenge for me to overcome with other rich text editors.

Currently I am running into two issues. First, I am trying to find an option where I can create a custom button with text 'Submit' on the toolbar; and second, that button needs to remove (or disable or unbind) the editor from a React component.

The component:

`const EditableClause = ({ id, initalValue, clauseId, handleChange }) =>
  ce(ReactQuill, {
    value: initalValue,
    onChange: handleChange,
    modules: {
      toolbar: ['bold', 'italic', 'customSubmit'],
    },
    handlers: {
      'customSubmit': function() {
        quill.enable(false);
      }
    },
  });`

When that component is rendered, there is an invisible button beside the Bold and Italic buttons with no value and I get the following warning in console: `quill:toolbar ignoring attaching to nonexistent format customSubmit`.

**Comment by benbro** [comment]
The [toolbar docs](https://quilljs.com/docs/modules/toolbar/) explain how to define it in HTML.
You can create custom toolbar button, listen to the click event and add your custom submit logic::
https://codepen.io/anon/pen/PGRQrx

You can [disable](https://quilljs.com/docs/api/#disable) the editor with the API.

Quill doesn't have a 'destroy' method. You just need to delete all references to editor instance:
```javascript
var quill = new Quill('#editor-container', {config});
// delete the reference to the editor
quill = null;
```
Removing the editor HTML from the DOM is out of the scope of Quill. You should use react, vanilla JavaScript or whatever you use.

**Comment by harmeetjaipur** [comment]
Thanks for the quick reply. The code is failing on Reactquill.register().

Is Register another package similar to Parchment?

`const CustomClass = new Parchment.Attributor.Class('custom', 'ql-custom', {
  scope: Parchment.Scope.INLINE
});
ReactQuill.register(CustomClass, true);
const customButton = document.querySelector('#custom-button');
customButton.addEventListener('click', function() {
  ReactQuill = null;
});`

**Comment by benbro** [comment]
Please follow the [docs](https://quilljs.com/docs/quickstart/) and [examples](https://quilljs.com/playground/).
Try to make it work with Javascript first, without using reactjs.
Then, try to add it to reactjs.

github issues are for bugs and development. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/quill) for questions.

**Comment by harmeetjaipur** [comment]
Thanks, I will debug React on my own. I have modified the pen if you could just look at the `quill = null` statement that doesn't disable the editor on click, I'd be grateful.

**Comment by benbro** [comment]
Call disable to disable the editor
https://quilljs.com/docs/api/#disable

**Comment by harmeetjaipur** [comment]
I tried using disable() and enable(false), but those two only disable the userinput. How do I destroy the editor and return the div to its original state, the content inside the div doesn't matter. I only need to remove the text editor once editing is done.

**Comment by harmeetjaipur** [comment]
I resolved it through React. Thanks for all the quick replies. I hope you guys add a destroy() method sometime soon!
