### ISSUE TITLE
How to handle keyboard events on custom blot

### ISSUE THREAD

**Issue by szobov** [quilljs/quill#1744]
I've already asked my question on [StackOverFlow](https://stackoverflow.com/questions/46620371/quill-how-to-handle-keyboard-events-on-custom-blot), but I suppose I have to create same issue.

**Steps for Reproduction**

1. [Visit](https://codepen.io/szobov/pen/ZXrVzW)
2. Open console
3. Click on text in editor (will see "clicked" in console)
4. Type some buttons on keyboard, e.g. arrows.

**Expected behavior**:
Keyboard event should be handled and you see "key was pressed" in console.

**Actual behavior**:
Keyboard event wasn't handled.

**Platforms**:

Chromium
Version 61.0.3163.100 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Version**:

Latest

**Comment by jhchen** [comment]
No you definitely do not need to duplicate content across StackOverflow and Issues.

**Comment by szobov** [comment]
But nobody answer me there. :(
