### ISSUE TITLE
How to disable default wrap into p tags?

### ISSUE THREAD

**Issue by elessariel** [quilljs/quill#1745]
Hello I would like to know, how I can disable the default wrapping into p tags.
I am using the editor to edit translations e.g. for labels and the p tags are screwing with the layout.
Is there an easy way to do it?

**Comment by benbro** [comment]
Quill need to wrap lines with a tag.
You can try setting [matchVisual:false](https://quilljs.com/docs/modules/clipboard/#matchvisual)

You can try to remove spacing with CSS:
https://github.com/quilljs/quill/issues/1631#issuecomment-320782792

You can also try to replace the default p tag with a div tag:
https://github.com/quilljs/quill/issues/861#issuecomment-239961806

**Comment by elessariel** [comment]
replacing p tags with divs is unforunately only a workaround that works so far.
Are you saying there is no way to just load content let's say "my one line content" and without changes save it without creating a "<defaultTag>my one line content</defaultTag>" ?

**Comment by benbro** [comment]
As I said, Quill need to wrap each line with a tag. You can configure this tag and change the spacing with CSS.
You can remove the p tag on your server after the user finish editing.

**Comment by elessariel** [comment]
Thanks for the information.

**Comment by nnayzawkhant** [comment]
gggggg

**Comment by PlatoSys** [comment]
You can replace and set tags manually, so the component will not render infinitely and the output is a clean string.
In this way, the ReactQuill component thinks that there are already <p> and <br> tags and won't set them automatically.


```
          value={!value ? '<br>' : `<p>${value}</p>`}
          onChange={(val: string) => {
            handleUpdate(val.replaceAll(/<\/?p[^>]*>/g, '').replace('<br>', ''));
          }}
```

**Comment by hellokanhaiya** [comment]
thank you so much because i trouble in last 3 hour this is working

**Comment by TanbirHasan** [comment]
How can I remove the default margin or every p tag ? And I want to do it by modifying the HTML before sending or displaying the content. Is there any way?
