### ISSUE TITLE
Only allow a list sublevel if the previous level was used.

### ISSUE THREAD

**Issue by Natim** [quilljs/quill#1753]
If you keep pressing the tab key on a list you end-up having a lot of levels.
Can we limit it to one level more than the last one used? ![](https://user-images.githubusercontent.com/26000308/31017329-bdf65faa-a530-11e7-8c35-39cfca9e24f0.gif)

**Comment by jhchen** [comment]
I don't think this should be core Quill behavior but you can overwrite the indent key binding to check the previous indent level and not apply in your case. Ex.

```js
var quill = new Quill('#editor-container', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
      [{list: 'ordered'}]
    ],
    keyboard: {
      bindings: {
        indent: {
          key: 9,
          format: ['blockquote', 'indent', 'list'],
          handler: function(range, context) {
            // check indent level
            // this.quill.format('indent', '+1', Quill.sources.USER);
          }
        },
      }
    }
  },
  placeholder: 'Compose an epic...',
  theme: 'snow'  // or 'bubble'
});

```

**Comment by Natim** [comment]
To check the indent level, you use the offset property of the context ?

**Comment by jhchen** [comment]
[`getFormat`](https://quilljs.com/docs/api/#getformat) is one option
