### ISSUE TITLE
Change can't handle mobile typing method

### ISSUE THREAD

**Issue by DrustZ** [quilljs/quill#1756]
I used the delta to tell the text change on mobile, it is correct when I'm using selection and paste, but when I use auto-correction or prediction, the change doesnt show correctly

**Steps for Reproduction**
Visit https://quilljs.com/docs/delta/ on your phone and type in the playground with a third part input method like flexboard
type "I li"
and select "like" in the input method(It's word prediction)

**Expected behavior**:
the change should be: "retain": 4, "insert": "ke "
**Actual behavior**:
 "retain": 6, "insert": " "
**Platforms**:
newest Chrome, android 7.1

**Version**:
Quill on the documentation website

**Comment by jhchen** [comment]
The demo only shows the last change and the keyboard autocomplete performs two operations, the last being inserting a space. If you modify the code to show all changes you will see the insert "ke" is being emitted as well.

**Comment by DrustZ** [comment]
thank you! I'll play with it
