### ISSUE TITLE
The "Numbered List" is wrongly rearranged when removing an item from it

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [quilljs/quill#1758]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v2.0.0a2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Notes build version (2.0.0a2) installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a website.
2. Create a "Numbered list" that contains several items.
3. Click on one item, select the "Numbered list" button and observe how the list is rearranged.

[Expected result]:
- The "Numbered list" is correctly rearranged.

[Actual result]:
- The "Numbered list" is rearranged by continuing the numbering of the items.

[Notes]:
- Here is a screen recording of this issue:
![rearranging - notes](https://user-images.githubusercontent.com/31244235/31450292-bfb4dcec-aeb1-11e7-986b-bceb56bed977.gif)

**Comment by jhchen** [comment]
The expected behavior is when an list is broken up the numbering restarts at 1. which is what the gif is showing. I'm a bit confused though since in your Actual Result says it continues numbering of the items, which is not what it does. It restarts numbering which is what is expected.

**Comment by Softvision-CristinaBadescu** [comment]
Hello @jhchen ,
I was thinking that after removing an item from the "Numbered list", the numbering will go on, without creating a new one from the start. You can see below the described behavior:
![ordering](https://user-images.githubusercontent.com/31244235/31599793-8c378b7c-b25c-11e7-922f-386de6679fd0.gif)
