### ISSUE TITLE
How to add template functionality to Quill?

### ISSUE THREAD

**Issue by ankitrg** [quilljs/quill#1759]
I am trying to build something similar to what HubSpot and Facebook do with templating. I was not able to find any resource on the web on how to go about building this. At my company, we are planning to use Quill.js for our editors. Is building such an interface possible?

### HubSpot

![HubSpot](https://image.prntscr.com/image/vDh8a9dCQBW9mAvPB522RQ.png)

### Facebook
![Facebook](https://image.prntscr.com/image/2glK-WjtT-SQiWdx_DXELw.png)

I know this might not be the right place to ask this. If you could just point me in the right direction that would be very helpful.

**Comment by LFDM** [comment]
This is definitely possible, albeit a bit of work. I can tell you what we did at my company for something similar than this on highlevel:

- Create a new blot which represents a nice tag like `Contact First name` in your first screenshot.
Something like this:

```
const ATTRS = {
    SERIALIZATION: 'data-serialization',
    VALUE: 'data-value',
};

class TemplateBlot extends Parchment.Embed {
    static create(value) {
        const node = super.create(value);
        node.setAttribute(ATTRS.SERIALIZATION, value.serialization);
        node.setAttribute(ATTRS.VALUE, value.value);
        node.setAttribute('contenteditable', false);
        node.textContent = value.value;
        return node;
    }

    static value(node) {
        return {
            value: node.getAttribute(ATTRS.VALUE),
            serialization: node.getAttribute(ATTRS.SERIALIZATION),
        };
    }
}
```

- You see there is something like a display value and then a serialized version of it - a data attribute you later use to parse your HTML string and replace it with whatever content you want (like the real first name of a contact
- You then need to provide some capabilities for people to insert such a blot. We provide this through a toolbar button, which triggerrs then an autocompletion menu within quill and a keyboard shortcut which also triggers the autocompletion menu.
- People choose then the template string they want and you insert it into quill as the blot you defined earlier.

**Comment by nikolov-tmw** [comment]
@LFDM I wish I had found this back when I was implementing the same functionality :joy: .

However, I'm having some issues with the embeds and the cursor, so I'm wondering if you've experienced that too.

Here's the situation:

1. The cursor is one character after an embed: ![](https://nidus.paiyakdev.com/screens/Screenshot-at-2018-01-11_14:35:43.png)
2. Pressing the left arrow to move the cursor towards the embed, it moves up from where it is for normal text: ![](https://nidus.paiyakdev.com/screens/Screenshot-at-2018-01-11_14:35:55.png)
3. If I then move to the left again, the cursor is still next to the embed and matches it's height: ![](https://nidus.paiyakdev.com/screens/Screenshot-at-2018-01-11_14:36:06.png)
4. Another move to the left and the cursor finally moves to in front of the embed: ![](https://nidus.paiyakdev.com/screens/Screenshot-at-2018-01-11_14:39:57.png)

Additionally, if an embed is all by itself on one line, moving the cursor left towards it from the next line, the cursor will end up at the end of the line, instead of next to the embed.

In other cases, the editor looses focus if two embeds are right next to each other and I try moving the cursor left to right through the embeds.

Not sure if those are issues with my setup specifically, or if you/anyone else is experiencing them too.

**Comment by LuisReinoso** [comment]
@dearsina Thanks to shared you implementation but I found an issue when try to copy and paste some content that has styles or links. Do you have this trouble?.

**Comment by do-web** [comment]
> @LFDM I took your idea and ran with it, and came up with the following solution that works for my templating needs. It depends on jQuery (but that can be changed if you don't like jQuery) and assumes you're running Bootstrap CSS, but again, totally optional, however their badge CSS works very well with the templating design.
> 
> ```
> var Embed = Quill.import('blots/embed');
> 
> class TemplateMarker extends Embed {
>     static create(value) {
>         let node = super.create(value);        
> 
>         node.setAttribute('class', 'badge badge-' + value.colour);
>         //Set up the (Bootstrap) badge, and badge colour        
> 
>         node.setAttribute('data-marker', value.marker);
>         //The marker is the (hidden) template marker reference        
> 
>         node.innerHTML = value.title;
>         //The title is what the user sees in their editor        
> 
>         return node;
>     }
>     
> 	static value(node) {
>         return {
>             marker: node.getAttribute('data-marker')
>         };
>     }
> }
> 
> TemplateMarker.blotName = 'TemplateMarker';
> TemplateMarker.tagName = 'span';
> 
> Quill.register({
>     'formats/TemplateMarker': TemplateMarker
> });
> ```
> 
> And then the trigger function:
> 
> ```
> $('.ql-insertCustomTags').on('change', function() {
> 	//This is designed to trigger on a dropdown change, replace it with click for a button
> 
> 	let range = quill.getSelection(true);
> 	
> 	quill.insertEmbed(
> 	    range.index,
> 	    //Insert the TemplateMarker in the same range as the cursor is
> 	    
> 	    'TemplateMarker',
> 	    //This is the name of the Embed
> 	    
> 	    {
> 			colour: $(this).find(':selected').data('colour'),
> 			marker: $(this).find(':selected').data('marker'),
> 			title: $(this).find(':selected').data('title')
> 		},
> 		//These are the variable values to feed to the editor
> 	);
> 	
> 	quill.insertText(range.index + 1, ' ', Quill.sources.USER);
> 	//Add a space after the marker
> 	
> 	quill.setSelection(range.index + 2, Quill.sources.SILENT);
> 	//Take the cursor to the end of the inserted TemplateMarker
> 	
> 	$(this).val("");
> 	//Reset the dropdown
> });
> ```
> 
> Finally, here is the dropdown itself:
> 
> ```
> <select class="custom-select ql-insertCustomTags">
> 		<option value="">Guest</option>
> 		<option value="first_name" data-marker="first_name" data-title="FIRST NAME" data-colour="warning">First Name</option>
> 		<option value="last_name" data-marker="last_name" data-title="LAST NAME" data-colour="warning">Last Name</option>
> 		<option value="full_name" data-marker="full_name" data-title="FULL NAME" data-colour="warning">Full Name</option>
>   </select>
> ```
> 
> You can change the dropdown to be a toolbar menu button, as Quill's implementation of custom dropdowns is, how to say it politely, creative.
> 
> As an added bonus, here's a function that stores two different versions of the editor output, one as a Delta JSON array that can be used when re-opening the template in Quill, and the other, the HTML output with the markers as they're expected to be written on your backend.
> 
> ```
> quill.on('text-change', function(delta, oldDelta, source) {
> 	var delta = quill.getContents();
> 	var delta_json = JSON.stringify(delta);
> 	console.log(delta_json);	
>   // This is what you store in the DB so that you can edit the template later
> 	
> 	var qdc = new window.QuillDeltaToHtmlConverter(delta.ops, window.opts_ || {});
> 	// This requires the Quill Delta to HTML converter js
>   
> 	// customOp is your custom blot op
> 	// contextOp is the block op that wraps this op, if any. 
> 	// If, for example, your custom blot is located inside a list item,
> 	// then contextOp would provide that op. 
> 	qdc.renderCustomWith(function(customOp, contextOp){
> 		if (customOp.insert.type === 'TemplateMarker') {
> 			let val = customOp.insert.value;
> 			return val.marker;
> 		}
> 	});
> 	
> 	var html = qdc.convert();
> 	//Convert the Delta JSON to HTML
> 	
> 	console.log(html);
> 	//This is what will be used to render the template
>   //You also need to store this in your DB
> });
> ```
> 
> Here's one I prepared earlier:
> https://codepen.io/dearsina/pen/GBOpPy
> 
> Hope this saves someone a day of scavenging around the internet trying to cobble together a solution!

Thanks but copy and paste did not work with that.

**Comment by kaetsmjau** [comment]
Hi, when I insert a template marker, the index seems to revert back to 0. I cannot use backspace to delete template markers. And when I press enter, the break is always at the beginning of the editor, above all existing text. When '##' is detected, a template marker should appear after '##', a space will be added after the template marker and the text cursor is behind the space, but this is what I got.

![Screenshot from 2020-06-04 09-13-30](https://user-images.githubusercontent.com/40970323/83826324-35126480-a70e-11ea-8923-81bb4572ca4c.png)

The second template marker is supposed to be behind the second '##', even though the text cursor was at the end of the second '##'.

```
  watch: {
    content: {
      handler() {
        const delta = this.editor.getContents();

        // create qdc instance
        const qdc = new QuillDeltaToHtmlConverter(delta.ops, {});

        // render custom ops
        qdc.renderCustomWith((customOp) => {
          console.log('CUSTOM OP: ', customOp);
          // set rendering for TemplateMarker
          if (customOp.insert.type === 'TemplateMarker') {
            const val = customOp.insert.value;
            return `<span id="${val.marker}">${val.title}</span>`;
          }
          return '';
        });

        // convert the delta json to html
        const html = qdc.convert();
        this.content = html;
        console.log('HTML >>>', html);
      },
    },
  },

  methods: {
    watchForHash(char) {
      if (char === '#' && this.tag !== '') {
        console.log('CLOSED');
        this.insertTag();
        this.tag = '';
      } else if (char === '#' && this.tag === '') {
        this.tag += char;
      } else if (this.tag !== '') {
        console.log('TAG: ', this.tag);
        this.tag += char;
      }
    },
    insertTag() {
      const dummyVariable = { colour: 'warning', marker: 'full_name', title: 'FULL NAME' };
      const range = this.editor.getSelection();
      console.log(range, '#########');
      // // insert embedded content into the editor like image
      this.editor.insertEmbed(
        range.index, // insert the marker in the same range as the cursor is
        'TemplateMarker', // the name of embed
        dummyVariable, // variables to enter
      );
      // // add a space after the marker
      this.editor.insertText(range.index + 1, ' ', Quill.sources.USER);
      // // take the cursor to the end of the inserted marker
      this.editor.setSelection(range.index + 2, Quill.sources.SILENT);
    },
  },

  mounted() {
    const ToolBarOptions = ['bold', 'italic', 'underline', 'strike'];
    const editor = new Quill('#editor', {
      modules: { toolbar: ToolBarOptions },
      placeholder: 'Write something..',
      theme: 'snow',
    });
    this.editor = editor;
    console.log(editor);
    editor.on('text-change', (delta, oldDelta, source) => {
      console.log(delta, '---------');
      const char = delta.ops[1].insert;
      this.watchForHash(char);
      console.log(oldDelta, '---------');
      console.log(source, '---------');
      this.source = source;
      this.content = JSON.stringify(oldDelta);
    });
  },
```

Thanks

**Comment by prakulj** [comment]
I am also looking for something similar.
My backend uses Flask. I am planning to use Jinja Template. 
How can I replace the placeholders in the text editor on the frontend which uses Vue.js?
I am a beginner and have absolutely no idea. I am not able to research very effectively. 
Can someone point me in the right direction?

**Comment by mateodecu** [comment]
What is a blot?

**Comment by benbro** [comment]
Answered.
