### ISSUE TITLE
Copy/Cut embed when multiple embeds in row copies/cuts more then selected

### ISSUE THREAD

**Issue by DmitrySkripkin** [quilljs/quill#1761]
![gif](https://s3-eu-west-1.amazonaws.com/fs.dev-lds.ru/files/317f11fb-d2fe-a93e-d1e4-18a57d764eaa/copy.gif)

**Steps for Reproduction**

1. Visit [CodePen](https://codepen.io/DmitrySkripkin/pen/ZXjyLr)
2. Select and copy first formula
3. Paste anywhere (even not quill)

**Expected behavior**:
Selected formula pasted

**Actual behavior**:
Selected formula + extra content pasted

**Platforms**:
Linux, MacOS - latest Chrome

**Version**:
1.3.3

P.S. You can select formula and run this code:
```
var selection = window.getSelection();
var  range = selection.getRangeAt(0);
range.cloneContents();
```
Only one embed is cloned. How does quill handle copy/paste? Can't find anything that can help me to solve this issue.

P.P.S. `quill.getContents()` returns only one embed too.

**Comment by rywall** [comment]
Cutting/Pasting an embed also seems to throw away the embed formatting, leaving only the inner text. You can replicate this on the quilljs.com homepage by cutting/pasting the formula at the bottom.

![image](https://user-images.githubusercontent.com/7904/31839692-3c24ff1e-b5b0-11e7-87f9-66cd2f4d45d1.png)
