### ISSUE TITLE
Off-by-one error in selection index

### ISSUE THREAD

**Issue by benjismith** [quilljs/quill#1763]
It looks like the Quill selection object has an off-by-one error on the first character after a newline.

Here's a minimal failure case, where I setup an empty Quill object and logged the selection index every time the text changes:

```
let quill = new Quill('#editor-container');
quill.on(Quill.events.TEXT_CHANGE, function() {
  let selection = quill.getSelection();
  if (selection !== null && selection.length === 0) {
    console.log("SELECTION INDEX: " + selection.index);
  }
});
```

As you type, you can see updated selection index in the console. You'd expect it to increment by exactly one whenever you add a new character to the editor (including normal text characters and whitespace characters, like newlines). But there's some weird off-by-one behavior on the first character entered into an empty editor, as well as the first character after any newline.

**Steps for Reproduction**

1. Visit https://codepen.io/benjismith/pen/OxwoaE
2. Type the text "xxx" and then hit the ENTER key
3. Repeat step 2 twice (total of 9 x's and 3 ENTER's)

**Expected behavior**:

I would expect to see following output on the console:

```
SELECTION INDEX: 1
SELECTION INDEX: 2
SELECTION INDEX: 3
SELECTION INDEX: 4
SELECTION INDEX: 5
SELECTION INDEX: 6
SELECTION INDEX: 7
SELECTION INDEX: 8
SELECTION INDEX: 9
SELECTION INDEX: 10
SELECTION INDEX: 11
SELECTION INDEX: 12
```

**Actual behavior**:

I actually see this output on the console:

```
SELECTION INDEX: 0
SELECTION INDEX: 2
SELECTION INDEX: 3
SELECTION INDEX: 3
SELECTION INDEX: 4
SELECTION INDEX: 6
SELECTION INDEX: 7
SELECTION INDEX: 7
SELECTION INDEX: 8
SELECTION INDEX: 10
SELECTION INDEX: 11
SELECTION INDEX: 11
```

**Platforms**:

Chrome 61.0.3163.100, Mac OS High Sierra

**Version**:

1.3.3

**Comment by jhchen** [comment]
I think this is a case of the last paragraph in [`text-change`](https://quilljs.com/docs/api/#text-change) that the selection does not update before the text does.

**Comment by benjismith** [comment]
Ahhhh yes, now I see...

Do you think it would be possible to change the lifecycle so that the selection object is always updated before the `text-change` event fires?

Here's one small example of what I'm building with this...

https://codepen.io/benjismith/pen/jGQYQY

In this example, I've created an editor that replaces standard (straight) apostrophes and quotation marks with curly quotes, while still letting the user insert straight quotes by invoking `CTRL-'` and `CTRL-"`

If you play around with this example a little bit, you can see that the replacements don't work when the quotation character is at the beginning of a new line:

```
# THIS WORKS:
John smiled and said "hello."

# THIS DOESN'T WORK:
"Oh, it's you," she replied.
```

This is just a toy example of a more generalized auto-correct system, which lets users define their own custom auto-correct dictionaries (which might contain hundreds of entries). So I can't just hard-code a few replacements into the `keyboard` module. The mechanism I'm using now is actually working really nicely, except for the problem with those pesky newlines.

So, if it's possible to enforce an accurate selection object before the `text-change` event fires, that'd be great. Otherwise, I'm open to suggestions for an alternate implementation.

**Comment by benjismith** [comment]
Based on your feedback I took a closer look at the [docs](https://quilljs.com/docs/api/#text-change) for the `text-change` event, which say:

> Changes to text may cause changes to the selection (ex. typing advances the cursor), however during the `text-change` handler, the selection is not yet updated, and native browser behavior may place it in an inconsistent state. Use `selection-change` or `editor-change` for reliable selection updates.

So I thought I should try listening for the `editor-change` event instead of the `text-change` event, like this:

```
let quill = new Quill('#editor-container');
quill.on(Quill.events.EDITOR_CHANGE, function(eventName, ...args) {
  if (eventName === Quill.events.TEXT_CHANGE) {
    let selection = quill.getSelection();
    if (selection !== null && selection.length === 0) {
      console.log("SELECTION INDEX: " + selection.index);
    }
  }
});
```

But the results were exactly the same as my original test:

```
SELECTION INDEX: 0
SELECTION INDEX: 2
SELECTION INDEX: 3
SELECTION INDEX: 3
SELECTION INDEX: 4
SELECTION INDEX: 6
SELECTION INDEX: 7
SELECTION INDEX: 7
SELECTION INDEX: 8
SELECTION INDEX: 10
SELECTION INDEX: 11
SELECTION INDEX: 11
```

You can try it out yourself here: https://codepen.io/benjismith/pen/OxwoaE

**Comment by benjismith** [comment]
Does this count as a bug? Or would you consider this working-as-designed? I'm trying to decide how to move forward with this feature on my side, and your guidance would be really helpful...

**Comment by jhchen** [comment]
The events are working as designed based on information supplied.

The `editor-change` event is just a combination of text and selection change. So what is meant by "Use selection-change or editor-change for reliable selection updates" is that you should look at the selection-change events inside of editor-change. It does not change text-change's behavior.

The simple workaround is wrap your handler with a setTimeout or _.defer.

> Do you think it would be possible to change the lifecycle

Anything is possible given enough benefit. Text changes can cause selection changes so it would make sense for it to get fired first. Quill has a modular architecture so the selection and editor modules has limited control over one another. So I'm not sure I'm sold yet on why this is the right move.

**Comment by benjismith** [comment]
Sounds good. Using `setTimeout` works just fine for my use case. Thanks again for your help!
