### ISSUE TITLE
Please help me with how to convert a class to an inline style

### ISSUE THREAD

**Issue by ZooTopiaGG** [quilljs/quill#1765]
hello:
I konw some class can convert to inline-style like this:
I used the following for align:

Quill.register(Quill.import('attributors/style/align'), true);

eg:
`<p class='ql-align-center'>123123123</p>`
covert to
`<p style="text-align:center">123123123</p>`
But this doesn't work for me.
So there is a way to solve this problem?
And is there any way to force Quill to use only inline styles (instead of classes)?

**Comment by benbro** [comment]
Follow the live example:
https://quilljs.com/playground/#class-vs-inline-style

**Comment by ZooTopiaGG** [comment]
@benbro I was doing that， but this doesn't work for me 
![image](https://user-images.githubusercontent.com/23115938/31530642-7eb70468-b014-11e7-9a49-18facc0654ed.png)
