### ISSUE TITLE
How to do for quill do not remove font classes?

### ISSUE THREAD

**Issue by nunoguerra** [quilljs/quill#1769]
When quill load the content him removes the font classes from the content.

**Steps for Reproduction**
https://codepen.io/anon/pen/KXxGwE

**Expected behavior**
Maintain the font classes

**Platforms**
Google Chrome 61.0.3163.100
MacOS 10.11.6 

**Version**
1.3.3

**Comment by nunoguerra** [comment]
Do you have any estimate of when this bug will be fixed?

**Comment by MikeAski** [comment]
@nunoguerra Just has to me merged & embedded in Quill, now 🙂

**Comment by nunoguerra** [comment]
This bug is not fixed.

https://codepen.io/anon/pen/eVpXPQ

**Comment by timothyallan** [comment]
Doesn't seem like it, I'm running into this as well. 
Send in
 `<p class="ql-align-center"><span style="font-size:38px;color:rgb(230,0,0);" class="ql-font-arial-black">test</span></p>`

and it gets changed to 

`<p class="ql-align-center"><span style="color: rgb(230, 0, 0); font-size: 38px;">test</span></p>`

**Comment by chawes13** [comment]
I'm having still encountering this issue with `1.3.6`

**Comment by m4rtinpf** [comment]
> I'm having still encountering this issue with `1.3.6`
> 
> UPDATE: I was able to get around this issue by using a **single word** for the font. So in [#1769 (comment)](https://github.com/quilljs/quill/issues/1769#issuecomment-366580257), you need to have `ql-font-arialblack` (and update your `css` files and whitelist accordingly).
> 
> https://codepen.io/chawes13/pen/YzzvVZd

Bug still there, this workaround still works.

Thanks!

**Comment by boradakash** [comment]
> I'm still encountering this issue with `1.3.6`
> 
> UPDATE: I was able to get around this issue by using a **single word** for the font. So in [#1769 (comment)](https://github.com/quilljs/quill/issues/1769#issuecomment-366580257), you need to have `ql-font-arialblack` (and update your `css` files and whitelist accordingly).
> 
> https://codepen.io/chawes13/pen/YzzvVZd

this workaround works for me, thanks!
