### ISSUE TITLE
Feature Request: HTML editing

### ISSUE THREAD

**Issue by theskillwithin** [quilljs/quill#1770]
With react-quill I am able to accomplish html editing like this:

https://codepen.io/theskillwithin/pen/yzErmN

This works, however I need to use quill as what is referred to as an uncontrolled component in react, one where the react-quill wrapper does not use state to determine its value. 

The best and only way I see to really accomplish this is to bake this feature right into quill itself.

I am sure this feature would benefit a lot of people

**Comment by benbro** [comment]
You asked the same question several days ago:
https://github.com/quilljs/quill/issues/1754

This question was answered in the past:
https://github.com/quilljs/quill/issues/128#issuecomment-215263950
