### ISSUE TITLE
Group some icons to gain place

### ISSUE THREAD

**Issue by Petrouchka** [quilljs/quill#1771]
I would like to suggest some modifications to gain place in the menus. Some of the icons could be grouped :

    Code and Quote with Headers :
 
![31583366-9e84a3ae-b19a-11e7-9ec1-b3e68a87256f](https://user-images.githubusercontent.com/3955499/31584785-667ad558-b1b5-11e7-81e1-84ab5626026e.png)

    Indentation icons with left/right/center/justify icons :

![31583368-a280403a-b19a-11e7-8ac2-2abd1d0e0f3f](https://user-images.githubusercontent.com/3955499/31584786-6b7f95b6-b1b5-11e7-8c2b-c54beca3cab0.png)

**Comment by jhchen** [comment]
Not 100% what this is asking but pretty sure the toolbar already allows this: https://quilljs.com/docs/modules/toolbar/
