### ISSUE TITLE
dangerouslyPasteHTML collapses block styles if newlines are between html elements

### ISSUE THREAD

**Issue by ckoppelman** [quilljs/quill#1774]
`dangerouslyPasteHTML` does not properly add newlines into deltas.  In the below example, the delta becomes a single bullet instead of a h3 and then a bullet.

**Steps for Reproduction**

1. Run 

```js
quill.getModule('clipboard').dangerouslyPasteHTML("<h3>test header</h3>\n<ul>\n<li>bullet</li>\n</ul>");
```

**Expected behavior**:
delta output should be:

```js
{
  ops: [
    { insert: "test header\n", attributes: { header: 1 } },
    { insert: "bullet\n", attributes: {list: "bullet"} }
  ]
}
```

**Actual behavior**:

```js
{
  ops: [
    { insert: "test header", attributes: { header: 1 } },
    { insert: "bullet\n", attributes: {list: "bullet"} }
  ]
}
```

**Platforms**:

Include browser, operating system and respective versions
Chrome 61.0

**Version**:
1.3.3

**Comment by benbro** [comment]
\n isn't HTML syntax:
https://codepen.io/anon/pen/YrdoKV

**Comment by benbro** [comment]
Quill does create a title and a list with one bullet:
https://codepen.io/anon/pen/qPLzEa

**Comment by ckoppelman** [comment]
I wonder, then, what happened in my project.  I'll try to nail it down but I'm glad it's not so simple.
