### ISSUE TITLE
 When the code is entered, the cursor can not be moved down for other formatting

### ISSUE THREAD

**Issue by setLylToxlx** [quilljs/quill#1775]
when I inserted code snippet, the cursor can not be moved down for next line.I try to clicked other object, pressed the enter, but it doesn't work at all!But through clicked three times the enter ,I successed.

version 1.3.2

my project website:
[](https://pockr.org/guest/activity?activity_no=act_017d460d4e5988dad2&speech_no=sp_940aedc9e73b0a79a6)

Hope that a friend can give me some help

**Comment by jhchen** [comment]
Please fill out the issue template as requested including your platform and detailed steps for reproduction: https://github.com/quilljs/quill/blob/master/.github/CONTRIBUTING.md
