### ISSUE TITLE
Is the 'list' toolbar item broken?

### ISSUE THREAD

**Issue by ActualAl** [quilljs/quill#1778]
On the interactive playground I added the 'list' format to the toolbars module

```
var quill = new Quill('#editor-container', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
      ['image', 'code-block', 'list']
    ]
  },
  placeholder: 'Compose an epic...',
  theme: 'snow'  // or 'bubble'
}); 
```

The toolbar renders a blank button with no list SVG - 

**Steps for Reproduction**

1. Visit [https://quilljs.com/playground/]
2. Add 'list' to the toolbar formats
3. View the button with no SVG

**Expected behavior**:
The toolbar renders a list SVG

**Actual behavior**:
Empty button

**Platforms**:
FF/ Chrome
Mac OSSierra / Windows 10

**Version**:
1.3.3

<img width="1247" alt="screen shot 2017-10-20 at 11 46 03" src="https://user-images.githubusercontent.com/22451/31817807-688b616a-b58d-11e7-8e71-7edcd7ecb4f8.png">

**Comment by benbro** [comment]
This is the correct config:
```javascript
var quill = new Quill('#editor-container', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
      ['image', 'code-block'],
      [{ 'list': 'ordered'}, { 'list': 'bullet' }]
    ]
  },
  placeholder: 'Compose an epic...',
  theme: 'snow'  // or 'bubble'
});
```
