### ISSUE TITLE
Choose between using ql-indent and regular nesting of <ul> inside <li>

### ISSUE THREAD

**Issue by mariojankovic** [quilljs/quill#1781]
I really enjoy quill! It's the perfect plugin for all my WYSIWYG needs. I would very much like to avoid adding any classes to my HTML, so if there's an option to do so globally (at least for the lists) that'd be amazing.

1. Add a regular list
2. Indent second list item for example

**Expected behavior**:
The `<ul>` should be nested inside `<li>`

**Actual behavior**:
`<li>` items become a ql-indent class instead

**Platforms**:
I use Qull inside Vue

Include browser, operating system and respective versions
OSX, latest Chrome

**Comment by jhchen** [comment]
I don't think the benefits are worth the implementation complexity involved. At least one big design assumption Quill build on that would need to be addressed is block level elements cannot mix with inline. But if you have nested lists you can have `<ul><li>One<ul><li>Two</li></ul></li></ul>`. In many cases there are drawbacks as well such as not easily being able to tell how many items are in the nested list so overall the net benefits are even smaller.
