### ISSUE TITLE
HTML Code Preview

### ISSUE THREAD

**Issue by Graphettion** [quilljs/quill#1786]
Hello Quill Editor Team,

This is a feature request.

I wanted to know if you could add an HTML Code Preview as a feature for the editor and reflect changes in the normal editor preview.

Thank you,

**Comment by benbro** [comment]
This question has been answered before:
https://github.com/quilljs/quill/issues/128#issuecomment-215263950

**Comment by Graphettion** [comment]
Ah, didn't see this thread. Thank you @benbro. This non-issue can be closed then.

**Comment by Graphettion** [comment]
I wonder if someone has created a module for this yet.

**Comment by alpinista82** [comment]
Deal breaker for an otherwise great project.
