### ISSUE TITLE
为什么在苹果微信浏览器进行复制粘贴的时候，页面会发生连续滚动

### ISSUE THREAD

**Issue by wy930208** [quilljs/quill#1788]
为什么在苹果浏览器复制粘贴的时候，页面会发生连续滚动，是因为不能用浏览器自带的复制粘贴嘛？要用编辑器自带的复制粘贴？还是说本身就是一个bug

**Comment by iSuslov** [comment]
really?

**Comment by jhchen** [comment]
Please follow the contributing guide: https://github.com/quilljs/quill/blob/master/.github/CONTRIBUTING.md
