### ISSUE TITLE
The text formatting options wrongly reset to default after the formatted content is erased

### ISSUE THREAD

**Issue by Softvision-MariusComan** [quilljs/quill#1790]
From: mozilla/notes#329

**[Notes]:**
- On Google Docs, Libre Office and Mozilla Thunderbird after the formatted text is erased the options persist.

**[Affected versions]:**
- Firefox Notes 2.0.0a4
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0a4) installed.

**[Steps to reproduce]:**
1. Open Firefox with the first profile from prerequisites.
2. Select any formatting option from the "Firefox Notes" toolbar (Bold, Italic, Underline etc.).
3. Write a string in the "Firefox Notes" sidebar.
4. Select all content and delete it.
5. Observe the formatting options.

**[Expected result]:**
- The formatting options persist.

**[Actual result]:**
- The previously selected formatting options persist.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/31668300-8064001a-b35a-11e7-8c28-5c966ad4745b.gif)

**Comment by chris-equis** [comment]
@jhchen Any updates for this issue?

**Comment by spencer516** [comment]
@Softvision-MariusComan — were you ever able to make a workaround for this?

**Comment by pgrocks** [comment]
@jhchen Is there a plan to fix this issue?

**Comment by Felwin** [comment]
Any workaround would be nice
