### ISSUE TITLE
Duplicate code-block for other toolbar icons and replace class name

### ISSUE THREAD

**Issue by supernoggins** [quilljs/quill#1791]
Current Version 1.3.3

I know there is a lot of debate and requests for soft line breaks. So I am not trying to start a new thread regarding that. However, I have blocks of text I want to stylize like adding a background color as well as margins etc..  Now, I can add a toolbar that sort of gets me there, but when I select multiple lines it applies my class to several p tags .

The code-block does exactly what I want (i.e include soft line breaks), but I would like to duplicate it and replace the class tag it uses
```
Suedo Code
 var MyBlock1 =Quill.import("./codeblock.js");
 MyBlock1.className = "highlightred";
 MyBlock1.tagname = "PRE";
 Quill.register(MyBlock1,true);
```
Is this possible?

**Comment by jhchen** [comment]
The code block's current implementation does not follow usual patterns so I would not suggest extending it unless you have really dug into Parchment.
