### ISSUE TITLE
img insertEmbed get <img src="//:0"> instead of real url.

### ISSUE THREAD

**Issue by fghhfg** [quilljs/quill#1795]
```js
  this.quill.insertEmbed(range.index, 'image', value, Quill.sources.USER);
```
If `insertEmbed` can't get real image, it will insert `<img src="//:0">` instead of real url.

---

my code from https://github.com/quilljs/quill/issues/863#issuecomment-240579430
```js
var quill = new Quill('#editor-container', {
    theme: 'snow',
    modules: {
        toolbar: {
          container: 'image',
          handlers: {
            image: imageHandler
          }
        }
    },
}); 

function imageHandler() {
  var range = this.quill.getSelection();
  var value = prompt('What is the image URL');
  this.quill.insertEmbed(range.index, 'image', value, Quill.sources.USER);
}
```

then you input a local image. (ex: apple.jpg)

**Expected behavior**:
```html
<img src="apple.jpg">
```

**Actual behavior**:
```html
<img src="//:0">
```

**Platforms**:
win7 chrome, firefox... anywhere?

**Version**:
Quill 1.3.1

---
I try to make it read local image, 
ex: img/apple.jpg, img/banana.jpg...

I want quilljs generate :
```html
<img src="img/apple.jpg">
...
<img src="img/banana.jpg">
...
```

1. quilljs can't read local images via url, how should I do?
2. If `insertEmbed` can't get real image, it will insert `<img src="//:0">` instead of real url. How can I change this behavior?

**Comment by jhchen** [comment]
Besides changing 'image' to ['image'], the example code you posted is working for me: https://codepen.io/quill/pen/xPbbyB. Quill does change urls to `//:0` if it fails sanitization but your example 'apple.jpg' does not. You can change the sanitization logic if you want to but do consider security in your own function.

```js
var Image = Quill.import('formats/image');
Image.sanitize = function(url) {
  return url; // You can modify the URL here
};
```

**Comment by zabihy** [comment]
I'm using Quill in PrimeNG and this is my method. I don't know how I should use your code:
```
editorCreated(quill) 
{
        const toolbar = quill.getModule('toolbar');
        toolbar.addHandler('image', this.imageHandler.bind(this));
        this.editor = quill;
}

pushImageToEditor(url: string) {
        const range = this.editor.getSelection(true);
        const index = range.index + range.length;

        var ImageBlot = Quill.import('formats/image');
        ImageBlot.sanitize = function (url) {
            return url;  // No sanitization
        };

        this.editor.insertEmbed(range.index, 'image', url);
}
```

**Comment by brospars** [comment]
Failing silently by replacing URL is not great imo. Should at least trigger a warning of some sort
