### ISSUE TITLE
Save link when clicking out (bubble theme)

### ISSUE THREAD

**Issue by nelsonpecora** [quilljs/quill#1797]
I was wondering if anyone had proposed this feature, but couldn't find any discussion of it.

On Medium.com (and in a number of other WYSIWYG editors), clicking out of the link creation dialog (after you've typed a valid link) will save the link (as if you pressed `enter`), rather than discarding it (the current Quill behavior). What do you think of that functionality change? (If people are into it, I could whip up a quick PR to implement)

**Steps for Reproduction**

1. Double-click text
2. Select "link" from the toolbar
3. Type a valid link
4. Click out

**Expected behavior**:

Link is added successfully.

**Actual behavior**:

Link creation dialog closes without adding.

**Platforms**:

Chrome 61, Mac OS 10.13

**Version**:

Quill 1.3.3

**Comment by jhchen** [comment]
Have not heard of this before so feel free to take it on. A PR would be welcome thanks!
