### ISSUE TITLE
pasteHTML Not Working Properly

### ISSUE THREAD

**Issue by Graphettion** [quilljs/quill#1798]
I have a custom button that uses `pasteHTML()` in the quill toolbar. When I click the button <html> twice, I get an error saying, "Cannot read property 'pasteHTML' of undefined."

**Steps for Reproduction**

1. Go to https://codepen.io/Graphettion/pen/OxezbO
2. Type text into the editor
3. Click the `<html>` button twice

Note: In codepen under the JS settings (cog wheel) when I switch JavaScript preprocessor to babel, it works. Not sure exactly why this is.

**Expected behavior**:
The editor should switch back to preview text view.

**Actual behavior**:
It gives an error saying, "Cannot read property 'pasteHTML' of undefined."

**Platforms**:
Windows 10, Chrome v62.0.3202.75 , FF v54.0.1, Edge v15.15063

**Version**:
Quill v1.3.3

**Comment by benbro** [comment]
There is an error in your code. You didn't defined the self variable.
```
TypeError: self.quill is undefined
```

Please ask this type of questions in StackOverflow and reduce the test case to the minimum possible.
