### ISSUE TITLE
Hammer.js conflict with quill on Safari mac and OS

### ISSUE THREAD

**Issue by portapro** [quilljs/quill#1799]
The issue of using Hammer.js and quill.js appears when we initialise swipe using hammer.js it and it adds the style: -webkit-user-select: none; in the HTML element. This issue can be solved by adding the style -webkit-user-select: text; to the element with .ql-editor.

**Expected behavior**:
Field for text editing has got a usual behaviour

**Actual behavior**:
There is no focus in the field for text editing

**Platforms**:
Safari, macOS Sierra, iOS 10.3.3

**Version**:
version 1.3.3

**Comment by benbro** [comment]
That's not a Quill bug.
If you changed the editor element to be unelectable with CSS, obviously, the editor won't work.

https://github.com/hammerjs/hammer.js/issues/919
