### ISSUE TITLE
Can I use this with an HTML file that has been integrated with Foundation framework?

### ISSUE THREAD

**Issue by maz123** [quilljs/quill#1800]
Hi there,

Can this WYSIWYG editor be integrated with an HTML template that has Foundation framework built in?

Here is one of the example files: [https://goo.gl/o5C9yr](https://goo.gl/o5C9yr)

Cheers

**Comment by benbro** [comment]
Yes, you should be able to use Quill with any HTML template or CSS framework.
You'll might need to make small styling and adjustments depending on what you use.
I suggest you try it and see.

**Comment by maz123** [comment]
Thank you fro the reply. What do you mean by "small styling and adjustments depending on what you use"?...
