### ISSUE TITLE
Switch editing mode on and off?

### ISSUE THREAD

**Issue by maz123** [quilljs/quill#1801]
Hi there,

Great product! What I'd like to know is, is it possible to switch editing mode on and off? When the page initially loads, the page is ready to edit. But I am using the Foundation framework, so I'd like my client to be able to edit the page, and then switch of editing so that they can see the page also in the format I sent it to them, and see how them editing it affects it etc.

Cheers

**Comment by benbro** [comment]
This question has been answered before:
https://github.com/quilljs/quill/issues/128#issuecomment-215263950

**Comment by benbro** [comment]
This question has been answered before:
https://github.com/quilljs/quill/issues/128#issuecomment-215263950
