### ISSUE TITLE
Use key Enter to submit instead of Ctrl + Enter

### ISSUE THREAD

**Issue by feedgit** [quilljs/quill#1804]
In Quill default, Ctrl Enter is submit an editor block or do anyevent. But I want to use key Enter to submit instead of Ctrl + Enter. How can I fix this. I use VueJS and package Vue Quill Editor: https://github.com/surmon-china/vue-quill-editor/

**Comment by benbro** [comment]
You can add key bindings:
https://quilljs.com/docs/modules/keyboard/

**Comment by devbazilio** [comment]
Did not work, there is a "handleEnter" function which prevents use of any added later handlers of Enter

**Comment by andrody** [comment]
asdasd

**Comment by forefy** [comment]
Any solution?

**Comment by chrisbekas** [comment]
Good solution here https://www.gitmemory.com/issue/quilljs/quill/479/821830835

**Comment by felixrydberg** [comment]
I havnt had time to test this but this thread might have a working solution:
https://stackoverflow.com/questions/48775485/listen-to-key-press-enter-in-quill-js
