### ISSUE TITLE
extractVideoUrl is not override-able.

### ISSUE THREAD

**Issue by Rgghgh** [quilljs/quill#1806]
Hello all,
I need to change something in the [extractVideoUrl ](https://github.com/quilljs/quill/blob/1a5bebb0f2b67c2eaba6c1aec34c1d5d21993bd8/themes/base.js#L239) function, that is called when adding a video in the editor.

sadly the function is not override-able or configurable.

**Comment by pateldhruv1993** [comment]
If someone could help with this it would be great! The default extractVideoUrl function strips away video start time and all the other parameters that are commonly used while embedding videos.
