### ISSUE TITLE
Please pass Access-Control-Allow-Origin header in CDN script

### ISSUE THREAD

**Issue by hwhelchel** [quilljs/quill#1807]
When 3rd party scripts have an error, they show up in error trackers like rollbar, sentry, honeybadger as `Script error.` with no information by default.

This can be much improved.

By passing the Access-Control-Allow-Origin header with the value "*" it will allow applications to have visibility into errors occurring in the quill js script on their site.

This is a common practice in CDNs. Please see this blog post with more information on the issue:

https://blog.sentry.io/2016/05/17/what-is-script-error.html

**Comment by jhchen** [comment]
So following this guide the access-control-allow-origin header is now working: 

```
curl -sI -H "Origin: example.com" -H "Access-Control-Request-Method: GET" https://cdn.quilljs.com/1.3.3/quill.js
HTTP/2 200 
content-type: application/javascript; charset=utf-8
content-length: 431275
date: Mon, 06 Nov 2017 01:01:06 GMT
access-control-allow-origin: *
access-control-allow-methods: GET
access-control-max-age: 3000
last-modified: Mon, 09 Oct 2017 06:02:29 GMT
etag: "b9ca33663edf213fab5ad1ab191badf4"
cache-control: max-age=604800
accept-ranges: bytes
server: AmazonS3
vary: Accept-Encoding
x-cache: Miss from cloudfront
via: 1.1 23172d761378a3865feafcda78328053.cloudfront.net (CloudFront)
x-amz-cf-id: 1HYRkSEGw0RbSdeN72rI146jq_yqc-zuj4BYkdy_Rq7bIzFn_iNd2g==
```

Note from the guide:

> Turns out, for a really complicated reason, you can't simply hit a URL in your S3 bucket from within your browser and check the "Network" tab in your dev tools. That would be too easy. No, you need to ensure that you specify certain extra headers in your request. **Now, it turns out that browsers send this with CORS requests anyway, so you are covered in the real-world, but it's crazy that the dev-experience for the common case isn't what you'd expect.** You could use a tool like curl to specify the additional headers needed for a "correct" CORS request
