### ISSUE TITLE
Create a bullet with *, in addition to -

### ISSUE THREAD

**Issue by LFDM** [quilljs/quill#1808]
Hey, would you be opposed to trigger a bullet list not only with `-` but also with `*`?

When we used an older version of Quill we implemented this behavior ourselves - these days the auto-transformation to start a list with `-` is already part of Quill, which allows us to get rid of our custom code.

We however also allowed to trigger the list with `*`, a functionality that's now lost.

There are several options here:
- Duplicate quite some code and add an own keybinding to trigger the list with `*`
- Add this to Quill that `*` just works
- Allow to configure the list trigger within Quill through some kind of config constant, which allow to opt-in to use `*` as well.

What do you guys think?

PS: I can of course open a PR for this if you want!

**Comment by jhchen** [comment]
Yes a PR would be very helpful. I think the right place to change is the regex and switch statement in https://github.com/quilljs/quill/blob/d21db45f66245a55f6b8cafc1110823a351c4fd5/modules/keyboard.js#L249 and as long as the other autofills still works should be good thanks!

**Comment by LFDM** [comment]
Cool, thx - PR coming!
