### ISSUE TITLE
CSS display style none and dangerouslyPasteHTML

### ISSUE THREAD

**Issue by frankpepermans** [quilljs/quill#1810]
First off, thanks for creating Quill! It's awesome to use.

I have encountered a very weird issue in my app, I was seeing Quill render HTML differently when using dangerouslyPasteHTML when certain CSS rules were active (or not).

Short explanation: I use custom Quill blots to set certain attributes to, for example block nodes.
Now in my app, I can toggle the display style to 'none' for any elements that contain this attribute. If I wish to display it again, the css is removed.

Now when in my app, I activate the toggle that sets display to 'none'  and then load the HTML to Quill, I can see that all my HTML content is suddenly altered to a single line for example.

Take this example:
```
<p data-id="blah">
    <span data-id="blah">aaa</span>
</p>
<p data-id="blah">
    <span data-id="blah">bbb</span>
</p>
<p data-id="blah">
    <span data-id="blah">ccc</span>
</p>
```
It becomes: (when I have an active CSS selector applying display:none)
```
<p>
    <span data-id="blah">aaa</span>
    <span data-id="blah">bbb</span>
    <span data-id="blah">ccc</span>
</p>
```

I've tracked it down to Parchment, this line specifically: 
https://github.com/quilljs/quill/blob/64910cdbaf87e4079caeb8aa69a8189627842efb/modules/clipboard.js#L187

Where computeStyle finds display:none, and the element is not being processed correctly as a new line.

Is there a way to have the CSS active and not have Quill change the HTML?

**Comment by benbro** [comment]
You can try to extend the clipboard module or hide elements only after they are added to the editor.
