### ISSUE TITLE
this bind

### ISSUE THREAD

**Issue by sven1** [quilljs/quill#1812]
> Handler functions will be bound to the toolbar (so using this will refer to the toolbar instance) and passed the value attribute of the input if the corresponding format is inactive, and false otherwise. 

This is actually a problem for me and i dont know how to resolve it in a clean and "right" way. I built an angular application and i have written a custom handler for image uploading. This custom image handler should upload the image with the help of an angular service to the server. The data service is globally provided in the app and a member of my component and i can access it with `this.dataService`. But after `this` is bound to the toolbar i can't access my data service anymore. Can i avoid this boundary to the toolbar?

Best regards,
Sven

**Comment by benbro** [comment]
I suggest you ask this question in StackOverflow with a simple code example. It's probably not specifically related to Angular so you might want to explain it in plain JavaScript.

**Comment by sven1** [comment]
I've created a post on [stackoverflow](https://stackoverflow.com/questions/47178210/this-is-pointing-to-the-quill-editor-toolbar) but after a very lot of research i can't find a really clean solution and im pretty sure and convinced that the problem is that quilljs bound `this` to the toolbar instance. I looked to some other modules and packages and none of them do the same what quilljs did with the toolbar (externally).

**Comment by benbro** [comment]
If you think this is a bug in Quill, you should create a simple minimal example that reproduce it without using Angular.
You can fork this [CodePen](https://quilljs.com/playground/).

You probably just have JavaScript scope issue.
Try to change:
```javascript
this.editor.getModule("toolbar").addHandler("image", imageHandler);
```
To:
```javascript
this.editor.getModule("toolbar").addHandler("image", this.imageHandler.bind(this));
```
