### ISSUE TITLE
Trying to get Quill to play nicely with existing Angular project

### ISSUE THREAD

**Issue by andycwk** [quilljs/quill#1814]
Hi Guys!

Hopefully some kind person will help me out.. as I'm really struggling to get Quill playing in my solution :(

I've spent a day reading through various possible solutions notably https://github.com/quilljs/quill/issues/777

I even looked at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18947 (linked from above) but trying to change the typescript module format caused my entire project to bomb out during compile :(

At the moment when I try to use the component I get what appears to be a common quill_1.default is not a constructor error message in the browser console!

Instead of pasting all the various config files etc in this message I've created a gist --> https://gist.github.com/andycwk/270cd4a618baa46254f45d630502748b

I know that my version management for both Anuglar & Webpack are way behind, I'm planning on bringing both up to date but just not had time - hopefully I can introduce Quill without having to rebuild my entire world :/

Any help would be gratefully received  :)

Thanks in advance!

**Comment by benbro** [comment]
"@types/quill": "0.0.31" might work for you.
Recent versions [require](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18947#issuecomment-324433538) "es2015" instead of "commonjs".

**Comment by andycwk** [comment]
Thanks... I'll give that version a shot and let you know how it goes :)

**Comment by andycwk** [comment]
That seems to have done the trick... many thanks 👍
