### ISSUE TITLE
help me  Change other languages in quill 

### ISSUE THREAD

**Issue by tinhlv** [quilljs/quill#1815]
I not change other languages in quill. 
I do not see option  for it

Thanks

**Comment by benbro** [comment]
What exactly do you want to change?

**Comment by tinhlv** [comment]
I want it to work with the national language.

**Comment by benbro** [comment]
What does it means?

**Comment by benbro** [comment]
https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md
