### ISSUE TITLE
@mentions support in the editor

### ISSUE THREAD

**Issue by sujeetbuddiga** [quilljs/quill#1816]
Is there a module which helps me getting @mentions support in the existing quill editor.

I desperately need it.

**Comment by oliveratgithub** [comment]
+1
I‘m going to look into mention.js: https://github.com/jakiestfu/Mention.js/

**Comment by sujeetbuddiga** [comment]
@oliveratgithub any leads on how can this be quickly achieved ?

**Comment by sujeetbuddiga** [comment]
@jhchen any help in this direction is highly appreciated.

**Comment by oliveratgithub** [comment]
@sujeetbuddiga Tribute.js acutally works quite well "out-of-the-box" with Quill!
I'll try to give you a more detailed feedback later this week

**Comment by sujeetbuddiga** [comment]
@oliveratgithub, but I wasn't able to get that working.

Will be great if u can share a snippet for the same.

**Comment by oliveratgithub** [comment]
@sujeetbuddiga here you go - as I said, quite straight-forward...

### First add the Tribute resources to your site
```html
<!-- Tribute - Native @mentions: https://github.com/zurb/tribute/ -->
<link rel="stylesheet" href="/js/tribute/tribute.css" />
<script src="/js/tribute/tribute.min.js"></script>
```

### Then initiate & attach it to the Quill editor as follows
```javascript
<script type="text/javascript">
// Tribute - Native @mentions
var tribute = new Tribute({
  values: [
    {key: 'Phil Heartman', value: 'pheartman'},
    {key: 'Gordon Ramsey', value: 'gramsey'}
  ],
  lookup: 'key',
});
tribute.attach(document.getElementsByClassName('ql-editor'));
</script>
```

**Note:**
you will get a strange behaviour with the cursor position resetting before the `@`, when you attach it like this:
`tribute.attach(document.getElementById('.editor'));`
So that's why you have to attach it to the Quill editor using it's class `.ql-editor`. This issue was covered and resolved here: zurb/tribute#86

There is still a bug open regarding the Enter/Return key not working in combination of Tribute & Quille, see here (and upvote if you need it ;) ): zurb/tribute#87

But yeah, above code is basically it! Go to your website where the Quill editor is integrated and try it by typing `@p` in the richtext editor.

**Comment by sujeetbuddiga** [comment]
@oliveratgithub firstly, thanks a lot for sharing the code snippet.
This looks to be broken when using enter key for selection.

**Comment by oliveratgithub** [comment]
@sujeetbuddiga yeah that‘s an aknowledged issue which I pointed out in my previous comment:

> There is still a bug open regarding the Enter/Return key not working in combination with Tribute & Quill, see here (and upvote if you need it ;) ): zurb/tribute#87

**Comment by sujeetbuddiga** [comment]
@oliveratgithub  done, looks like the old fiddles shared in the bug are working.
As a workaround used the old library in the jsfiddle.

**Comment by benbro** [comment]
Seems like you found a solution.

**Comment by MadSpindel** [comment]
I have made a Quill module for this:
afconsult/quill-mention

**Comment by preveew** [comment]
@MadSpindel does that support remote json ?

**Comment by MadSpindel** [comment]
@preveew Yes you can do something like this:

```javascript
source: function (searchTerm) {
  $.getJSON('/remote/url/json/', { q: searchTerm}, function(data){
    this.renderList(data, searchTerm);
   }});
}
```

**Comment by preveew** [comment]
@MadSpindel Thanks. will try and update.

**Comment by abelski21** [comment]
@MadSpindel the module is great! I've been looking for this and trying it now. May I know how should I properly use this on react-quill? I'm getting an 'Uncaught TypeError: moduleClass is not a constructor'.

**Comment by syadiqfaliq** [comment]
@MadSpindel , Thanks, I managed to call quill mention values from json. But, do you have idea on how can I control the number of value listed on quill mention. I can't find the property of that,.

**Comment by MadSpindel** [comment]
@syadiqfaliq Yes, you can slice the values before sending it to renderList:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

**Comment by satyapendem** [comment]
Hi @MadSpindel 
I'm using **Quill-Mentions** with **MarkdownShortCuts**(https://github.com/patleeman/quill-markdown-shortcuts). 
``` <!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="quillMention.css">
    <link href="https://cdn.quilljs.com/1.0.0/quill.snow.css" rel="stylesheet">
</head>

<body>
    <div class="container">
        <div id="editor"></div>
        <script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.js'></script>
        <script src="https://cdn.jsdelivr.net/npm/quill-markdown-shortcuts@latest/dist/markdownShortcuts.js"></script>
        <script src="quillMention.js"></script> <!-- quill mention dist file-->

        <script>
            Quill.register('modules/markdownShortcuts', MarkdownShortcuts);
            const atValues = [
                { id: 1, value: 'satya' },
                { id: 2, value: 'sandy' }
            ];
            const hashValues = [
                { id: 3, value: 'Fredrik Sundqvist 2' },
                { id: 4, value: 'Patrik Sjölin 2' }
            ]
            var quill = new Quill('#editor', {
                theme: 'snow',
                modules: {
                    markdownShortcuts: {},
                    mention: {
                        allowedChars: /^[A-Za-z\sÅÄÖåäö]*$/,
                        mentionDenotationChars: ["@", "#"],
                        source: function (searchTerm, renderList, mentionChar) {
                            let values;

                            if (mentionChar === "@") {
                                values = atValues;
                            } else {
                                values = hashValues;
                            }

                            if (searchTerm.length === 0) {
                                renderList(values, searchTerm);
                            } else {
                                const matches = [];
                                for (i = 0; i < values.length; i++)
                                    if (~values[i].value.toLowerCase().indexOf(searchTerm.toLowerCase())) matches.push(values[i]);
                                renderList(matches, searchTerm);
                            }
                        },
                    }

                }
            });
        </script>
    </div>
</body>

</html>``` 

here is my code. https://cl.ly/ad07c5ee8c53 . I'm facing problem first if do mention

**Comment by sverdier** [comment]
> @preveew Yes you can do something like this:
> 
> ```js
> source: function (searchTerm) {
>   $.getJSON('/remote/url/json/', { q: searchTerm}, function(data){
>     this.renderList(data, searchTerm);
>   }});
> }
> ```

I tried your code but I have this error : this is not defined...

**Comment by sverdier** [comment]
@MadSpindel  @preveew 
source: function (searchTerm) {
  $.getJSON('/remote/url/json/', { q: searchTerm}, function(data){
    this.renderList(data, searchTerm);
  }});
}
I tried your code but I have this error : this is not defined...

**Comment by sverdier** [comment]
@MadSpindel 
> @preveew Yes you can do something like this:
> 
> ```js
> source: function (searchTerm) {
>   $.getJSON('/remote/url/json/', { q: searchTerm}, function(data){
>     this.renderList(data, searchTerm);
>   }});
> }
> ```

I tried your code but I have this error : this is not defined...

**Comment by Ilijan91** [comment]
@MadSpindel Hi is there a possibility to have a nested array of values instead of a single value array
Something like this ->
[
  { id: 2, value: { label: 'Product', values: ['Product 1', 'Product 2'] } },
  { id: 2, value: { label: 'Customer', values: ['Customer 1', 'Customer 2'] } }
];
and at the end choose Product 1, or Product 2 as a single value
