### ISSUE TITLE
Checked list item loses indentation

### ISSUE THREAD

**Issue by DmitrySkripkin** [quilljs/quill#1818]
When you hit Enter/Return after checked list item, it loses indentation.

**Steps for Reproduction**

1. Visit [codepen.io](https://codepen.io/DmitrySkripkin/pen/qVmGLE)
2. Set caret after "two"
3. Hit Enter/Return (BTW Shift + Enter/Return works ok)

**Expected behavior**:
New empty list item with same indent created

**Actual behavior**:
New empty list item with same indent created, but old list item lose indentation

**Ubuntu 16.04, latest Chrome (but I think it doesn't matter)**:

**Version**:
1.3.4

**Comment by DmitrySkripkin** [comment]
`checklist enter` keyboard handler is the reason, don't know what is the usecase for it. But it works in a different way for `checked` and `unchecked` list items.

**Comment by jhchen** [comment]
The purpose of the handler was to make new checklist items unchecked, but the logic was losing the indent.
