### ISSUE TITLE
Wrapping OL/UL tags in DIV's causes null exception 

### ISSUE THREAD

**Issue by whather** [quilljs/quill#182]
Our app allows the user to reply to an email, and the parent message portion we wrap in a `<div class="quote">` to style it a little differently in other places of the app. I noticed some issues assigning the editor certain HTML involving `<ol>` and `<ul>` tags. I broke it down into strings that work and don't work.

Does NOT work:

``` javascript
editor.setHTML('<div><ul><li>line</li></ul></div>')
editor.setHTML('<div><ul></ul></div>')
```

DOES work:

``` javascript
editor.setHTML('<div><ol><li>line</li></ol></div>')
editor.setHTML('<div><ol></ol></div>')
editor.setHTML('<div>test<ul></ul></div>')
```

This is the stack trace of the error:

```
Uncaught TypeError: Cannot read property 'tagName' of null
Normalizer.wrapInline 
Normalizer.normalizeLine 
forEach 
Document.rebuild
```

I stepped through the code a bit, but you guys could probably fix it faster. I'm on v0.16.0. Any clue?

**Comment by Atheehub** [comment]
how to set default bullet list active on or if   i type something that content auto wrap ul li tag is that possible
