### ISSUE TITLE
How can I prevent nesting of formatting tags?

### ISSUE THREAD

**Issue by zaplachinsky** [quilljs/quill#1820]
For example, I have paragraph like this:

Lorem <b>ipsum</b> dolor sit amet.

And on selecting a part of "ipsum" word I don't want it to behave like this:

Lorem <b>ips<i>um</b> do</i>lor sit amet.

But like this:

Lorem <b>ips</b><i>um do</i>lor sit amet.

Thanks.

**Comment by b0g3r** [comment]
I have the same question. I use only two elements of the toolbar - bold and italic, and I want that they can not be simultaneously applied. Any ideas how to do this?

**Comment by benbro** [comment]
List step for reproduction is requested in the issue template.
Try to use the [CodePen](https://codepen.io/quill/pen/KzZqZx).

**Comment by zaplachinsky** [comment]
@benbro That's not an issue, that's just a question.

**Comment by benbro** [comment]
Your question is unclear, that's why I asked you to provide a live example and a better explanation.

**Comment by benbro** [comment]
@b0g3r  you can listen to the [text-change event](https://quilljs.com/docs/api/#text-change) and remove the old attribute.
