### ISSUE TITLE
How to clear the contents in the editor?

### ISSUE THREAD

**Issue by sujeetbuddiga** [quilljs/quill#1821]
I need a way to clear the contents in the editor on the press of a button.

What is the clean way of doing this ??

![screenshot from 2017-11-14 14-22-06](https://user-images.githubusercontent.com/3041104/32770970-5051942a-c947-11e7-836d-fd03cda88c2d.png)

**Comment by benbro** [comment]
[quill.setContents([]);](https://quilljs.com/docs/api/#setcontents)

**Comment by sujeetbuddiga** [comment]
Thanks a lot @benbro ,
Was expecting a much clear way todo

**Comment by jhchen** [comment]
You can also `setContents([])` and `setText('')` which will clear the text. Internally Quill's data model requires at least \n so this will be added for you.

**Comment by AbdullahElamir** [comment]
You can use DOM to clear the Editor 
var element = document.getElementsByClassName("ql-editor");
 element[0].childNodes[0].remove();

**Comment by robogeekcanada** [comment]
AbdullahElamir thank you. This works

**Comment by amircb1367** [comment]
Hello
Delete with api
quill.deleteText(0,quill.getLength());

**Comment by asmatqatea** [comment]
Thanks

**Comment by amirdbt** [comment]
Incase this does not work (var element = document.getElementsByClassName("ql-editor");
element[0].innerHTML = "";)
you do try this instead
const qlEditor = document.getElementsByClassName("ql-editor");
 qlEditor[1].innerHTML = "";

**Comment by Jenrikk** [comment]
thanks

**Comment by biswajitsohom** [comment]
dfsfsfs
