### ISSUE TITLE
Is there a way to prevent editing for a selection of Quill without disabling the editor?

### ISSUE THREAD

**Issue by ggJSC** [quilljs/quill#1822]
I have a way for my users to keep track of "to do's" based on selections they make inside of their Quill editor text contents. So, for example, when they are in a meeting they can create an action item after highlighting a portion of the text so that when viewing the action item there is some mental reference and context for that action item. 
Due to certain limitations I want to disable changes inside the highlighted selection (determined based on a specific background-color) but obviously enable those outside.

**Comment by benbro** [comment]
Can you fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) and show example of what you are trying to do?
