### ISSUE TITLE
How can I extract Quill plain HTML WITHOUT any class="ql-xxx" information?

### ISSUE THREAD

**Issue by oliveratgithub** [quilljs/quill#1827]
Hi there,
I'm quite happy with Quill - but getting to the final stage of implementation, I realised, that saving Quill's Editor HTML contains Quill-specific classes, such as...

#### current result
  * For `code` blocks *:
`<pre class="ql-syntax" spellcheck="false"><span class="hljs-attribute">code</span></pre>`

  * For `size` paragraphs:
`<span class="ql-size-huge">This is not a h1 but a huge title</span>`

_* does Quill follow [highlight.js' recommended implementation](https://highlightjs.org/usage/) with that syntax for code-blocks it is using at the moment?_

#### expected result
  * For `code` blocks:
`<pre spellcheck="false"><code>code</code></pre>`
    * => no `class="ql-syntax" ` & `<span class="hljs-attribute">`

  * For `size` paragraphs:
`<span style="24px">This is not a h1 but a huge title</span>`
    * => no `class="ql-size-huge" `

I mean, I can simply disable Nr. 2 the custom sizes... But for the Code Syntaxing, I would miss that.

The challenge here is, that I'll pass the HTML to store the text in our DB. And honestly, those `class`-information make the HTML messy...

**Is there any oob solution for this?**

P.s.: using Quill.js v1.3.4

**Comment by benbro** [comment]
You are supposed to use Quill's [Delta](https://quilljs.com/docs/delta/) format with 
```javascript
var delta = quill.getContents();
quill.setContents(delta);
```

If you insist on using the insecure HTML output you can use [inline styles instead of classes](https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline) or post-process the HTML on your server.

**Comment by oliveratgithub** [comment]
@benbro thanks for your feedback - unfortunately this does not help me.

I'm not using jQuery so working with .getContents() is cumbersome, as far as I can tell. I made good results by just using `quill.root.innerHTML` as recommended [here at SO](https://stackoverflow.com/questions/39519950/convert-quill-delta-to-html)

Thanks for the links regarding changing to inline styles. Can you give me an example, how one can change that for the `code-block`? The examples are pretty for simple tags like Bold, or even Code itself - but the "code-block" is not covered and didn't work like this:

```javascript
var Codeblock = Quill.import('formats/code-block');
Codeblock.className = '';   // '' because I don't want it to write class="ql-syntax"...
Quill.register(Bold, true);
```
That's actually the last challenge I'm facing - and I'm still in the opinion, that highlight.js is implemented wrongly - for both, the `code-block`- and the regular `code`-markups... ;)

**Comment by benbro** [comment]
The code-block is annotated by an external library so you'll have to check there. You'll probably need to replace classes with inline styles manually inside the code block.

**Comment by oliveratgithub** [comment]
@benbro this is not really something I can follow and agree to. Highlight.js is "officially" part of and integrated into QuillJS - and, as mentioned twice in previous comments, in my opinion the markup for Highlight.js is wrongly adapted by Quill.

**Comment by benbro** [comment]
highlit.js is an external library. If you want it to support inline styles, you should ask there.

The quill module calls window.hljs.highlightAuto(text). It doesn't rely on <pre><code> tags.

**Comment by gweinfurther** [comment]
What good is a text editor if you can't use the content in your page? You need to be able to export HTML.

**Comment by weiweizhang** [comment]
could someone give me an example for how to customize code-block to **<pre><code>xxxx</code></pre>**

**Comment by faribajpr** [comment]
hi i'm using angular 2 and quill. when i'm typing in quill and make a text bold or... every thing is ok but when i want to save the text to database it's not bold anymore in my tables. what should i do?

**Comment by NalaGinrut** [comment]
Folks, not so hard, put this code to the end of your HTML template before ```</html>```

```html
<script>                                                       
 document.querySelectorAll("pre.ql-syntax").forEach(block => { 
     hljs.highlightBlock(block);                               
 })                                                            
</script>                                                      
```

**Comment by aacassandra** [comment]
@NalaGinrut thanks bro

**Comment by McFcologne** [comment]
This is in my case a complete showstopper for quill, because i want to use the content for emails. I definitely need inline styles and no classes.

**Comment by mshahzaib101** [comment]
i used it like this in React.js..
To display quil content in a div i use class "ql-editor" because through this our div can use the quil default classes...works..

    import ReactQuill from "react-quill";
    import "react-quill/dist/quill.snow.css";

    const ReactMarkdown = require("react-markdown/with-html"); //for displaying html

    function editorContent() {
      <div className="ql-editor" style={{ padding: 0 }}>
            <ReactMarkdown escapeHtml={false} source={quilGeneratedHtml} />
      </div>
    }

**Comment by dharmatv** [comment]
This is in my case a complete showstopper for the quill, because I want to use the content for emails. I definitely need inline styles and no classes.

**Comment by leventdeniz** [comment]
@McFcologne what alternative did you end up using?
