### ISSUE TITLE
Return html of selected text

### ISSUE THREAD

**Issue by hotdko** [quilljs/quill#1829]
Hello, I have a question how to return selected text from editor in HTML format? getSelection method can be used for text only. I've been struggling with this for few days now. Any help would be highly appreciated.

**Comment by DmitrySkripkin** [comment]
Quill doesn't works with HTML, it works with own Delta format. But you can get HTML from selection easily with plain js and browser API (you can paste this snippet to your browser console to test it):
```
var selection = window.getSelection();
if (selection.rangeCount > 0) {
  var range = selection.getRangeAt(0);
  var documentFragment = range.cloneContents();
}
console.log(documentFragment || 'nothing selected');
```

**Comment by hotdko** [comment]
@DmitrySkripkin thank you for your time. Your code doesn't seems to be doing what I was hoping for. It works for content outside of Quill but not for its content:
You can see an example I trying it on here: https://codepen.io/anon/pen/EbRVxV 
result for me:
![image](https://user-images.githubusercontent.com/28820606/33186607-f626c876-d08a-11e7-82b4-039d1651321b.png)

**Comment by DmitrySkripkin** [comment]
Check this [CodePen](https://codepen.io/DmitrySkripkin/pen/yPEzbE)

I was sure I posted comment with the link same day you add your last comment. Sorry.

**Comment by benbro** [comment]
DmitrySkripkin, thanks. The above example seems to work.
