### ISSUE TITLE
Placeholder reappears when text has been entered

### ISSUE THREAD

**Issue by devingoble** [quilljs/quill#1831]
**Steps for Reproduction**

Here's the problem I'm having, and I've spent half the day tearing things apart in order to get a repro in codepen, or the playground, and for some reason it only happens in the context of my application.
I'm initializing Quill using the code copied and pasted from the playground:

```
<div id="editor"></div>
```

```
this.quill = new Quill("#editor-" + this.id(), {
	modules: {
		toolbar: [
			[{ header: [1, 2, false] }],
			['bold', 'italic', 'underline'],
			['image', 'code-block']
		]
	},
	placeholder: "Click to edit...",
	theme: "snow"
});

```
**Expected behavior**:
When nothing is entered, the editor should display the placeholder.
When you click in the editor and begin typing, the placeholder should disappear.
Moving focus out of the editor should leave behind only the typed text.

**Actual behavior**:
When the editor loses focus, the placeholder reappears, and the text that was entered is pushed to the end of the placeholder string. The placeholder and entered text both retain their respective formatting.

![image](https://user-images.githubusercontent.com/2547980/33102843-86c5ab5e-ced3-11e7-9410-1832c8b5d118.png)

**Platforms**:
Windows 10 1703, Chrome 62, EdgeHTML 15.15063

**Version**:
1.3.4

**Comment by benbro** [comment]
The placeholder is using the before before pseudo element when the editor has the ql-blank class:
```csss
.ql-editor.ql-blank::before {
    content: attr(data-placeholder);
}
```

Check in your code if the ql-blank class is removed when you start typing.
Try to start from a clean page with Quill editor, verify that you can't reproduce the placeholder issue and start adding CSS and JS until you see it.
