### ISSUE TITLE
How do quill  start a new range?

### ISSUE THREAD

**Issue by liSong5713** [quilljs/quill#1833]
as title , how do i start a new range ?

**Comment by benbro** [comment]
[Selection API](https://quilljs.com/docs/api/#selection)

**Comment by liSong5713** [comment]
@benbro  thanks , i wang to upload pictures every time ,the 'img' in a single line  
`<p></p>
<p><img  src=" "/></p>
<p></p>`

**Comment by benbro** [comment]
It's unclear what you are trying to do, what you mean by range and how it is related to an image.
Please use StackOverflow for general questions.

**Comment by liSong5713** [comment]
@benbro  tranks man ！ i solve this problem. use this
  ```
 this.quill.updateContents(
                                            new Delta()
                                                .retain(range.index)
                                                .delete(range.length)
                                                .insert('\r')                                   
                                                .insert({image: item.url})
                                                .insert('\r'))  
```
