### ISSUE TITLE
Custom keyboard binding propagate to Quill's default binding is not working

### ISSUE THREAD

**Issue by rohusan** [quilljs/quill#1835]
Binding configuration should leave quill's default behaviour as described in the [docu](https://quilljs.com/docs/modules/keyboard/#configuration). Despite returning true quill's default behaviour is not fired.

**Steps for Reproduction**

1. Visit [jsfiddle](https://jsfiddle.net/cao82a3c/5/)
2. Use Tab in Quill editor

**Expected behavior**:
- range and context are logged to console
- cursor moves one tab

**Actual behavior**:
- range and context are logged to console, ok
- **cursor is not moving, nok**

**Version**:

1.3.4, OS Linux, FF 57

**Comment by jhchen** [comment]
It's logging for me. What browser / os are you using? This is why we ask in the issue template.

**Comment by rohusan** [comment]
I updated **actual behavior** to be clear what is not working. OS and browser is now mentioned as well, sorry about that.
