### ISSUE TITLE
Extend background ColorAttributor with more inline style

### ISSUE THREAD

**Issue by mchicasigler** [quilljs/quill#1836]
Hello,

I have a problem with the background-color (_Highlight_) in Quill, is more high than I would like because of line-height, this causes an overlap:

![01](https://user-images.githubusercontent.com/11419825/33314911-5d060cda-d42f-11e7-944f-bb33b2cf7823.png)

I can't change the line-height value, so I would like to extend the default format background style and include 'display: inline-block' in the inline style. 

Is this posible? Is there other correct way to add more inline style to a default inline style?

I'm using version 3.4.3.

**Comment by benbro** [comment]
I can't reproduce [here](https://quilljs.com/docs/formats/).
CSS in your website is probably affecting the editor style.
Try to compare the applied styles in the demo and on your website.

**Comment by mchicasigler** [comment]
I can reproduce there if I change font-size and line-height like in my case:

![03](https://user-images.githubusercontent.com/11419825/33365319-2559a396-d4e8-11e7-8aa8-d6e746a151e5.jpg)

![02](https://user-images.githubusercontent.com/11419825/33365305-195fb616-d4e8-11e7-9d5c-f88c3398b4fa.jpg)

**Comment by benbro** [comment]
Why are you changing the font-size and line-height if it breaks the display?

Please follow the issue template, fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) and show the problem.

**Comment by mchicasigler** [comment]
I change the font-size and line-height because in mi app I have a **_huge_** style size with this values.

If you write a text with **huge** size and background, you can see the problem: https://codepen.io/anon/pen/pdQLxV

**Comment by benbro** [comment]
I can't reproduce in your codepen.
Anyway, if you change the default Quill styles, it's your job to ensure it doesn't break.
