### ISSUE TITLE
Extend Link tooltip and use it, without Snow theme and toolbar

### ISSUE THREAD

**Issue by mchicasigler** [quilljs/quill#1841]
Hello,

I would like to use the **Link Tooltip** that Quill have in Snow theme, but I'm not using in my app the toolbar either the snow theme. Is there any way to use this component anyway and extend this to add muy own apparience?

I'm using version 3.4.3.

**Comment by benbro** [comment]
You can use the [snow theme without the toolbar](https://codepen.io/anon/pen/vpOvZL) and create a custom button that will trigger the link tooltip.
If you want to change the style of the snow theme, just override it.
