### ISSUE TITLE
Can I customize much more about the editor, not only the toolbar, thank u 

### ISSUE THREAD

**Issue by LXMin** [quilljs/quill#1842]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**:
Hello
I want to realize the result like this .
![image](https://user-images.githubusercontent.com/20547898/33470621-3bb77c72-d6a4-11e7-8302-2adf2ff80bb0.png)
But the content props of Quill-editor can't be fill by the input or textarea.
So that, I want to know how can I  achieve that result .
thank u.

**Actual behavior**:
Please help me, thank u
**Platforms**:
windows7
Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
https://quilljs.com/playground/#form-submit
