### ISSUE TITLE
Bubble is opening on the top of the line, not on the bottom

### ISSUE THREAD

**Issue by zaplachinsky** [quilljs/quill#1843]
Is there an option to select where to open the bubble if using bubble theme? In all [official examples](https://quilljs.com/) bubble appearing on bottom of the line, but in my editor, it is appearing on the top (it is bad thing for mobile devices):

![fireshot capture 413 - posts - http___127 0 0 1_9000_posts](https://user-images.githubusercontent.com/20682149/33527263-4edf3d4a-d856-11e7-9e77-b95454e990d6.png)

**Comment by benbro** [comment]
In this [example](https://quilljs.com/standalone/bubble/) the tooltip appears on the bottom.
You keep ignoring the issue template which specifically requests you to provide further info. Closing.
