### ISSUE TITLE
Creating link in Firefox.

### ISSUE THREAD

**Issue by kuzniets** [quilljs/quill#1845]
After creating link on some string and continue typing, the new string is still highlighting as a link. 

**Steps for Reproduction**

1. Open playground in Firefox 57.0.1, type some string and add some link to this string, press save.
2. Then press right arrow or put the caret after this word.
3. Start typing some string. You also can make break firstly.

**Expected behavior**:
New strings do not become the link.
**Actual behavior**:
Link continues with new strings
**Platforms**:
Firefox 57.0.1, MacOS High Sierra.
Include browser, operating system and respective versions

**Version**:
1.3.2
Run `Quill.version` to find out

**Comment by leimig** [comment]
This is being discussed in https://github.com/quilljs/quill/issues/1248

**Comment by benbro** [comment]
Closing as duplicate. Please add more info to https://github.com/quilljs/quill/issues/1248 if needed.
