### ISSUE TITLE
Need to close the image tags with />

### ISSUE THREAD

**Issue by zdraganov** [quilljs/quill#1850]
When inserting image element from the demo on https://quilljs.com/ there isn't closing tags on the images. I want to ask is there way to implement it at all, extending the base image format `Quill.import('formats/image')`

**Expected behavior**: Inserted image tags to be self closing

**Actual behavior**: Inserted image tags are not self-closed

**Platforms**: MacOSx

Include browser, operating system and respective versions

**Version**:  1.3.4

Run `Quill.version` to find out

**Comment by zhuharev** [comment]
This is valid html5 tag http://w3c.github.io/html/syntax.html#void-elements

**Comment by shuckster** [comment]
Yes, the `/>` closer for `br`, `img`, and such are XHTML specific, and only absolutely required for XHTML Strict modes.

It's been a few years since this was ever going to be a thing, so if you're still rocking XHTML you'll be pleased to know you can relax now.

Saying that, old habits die hard, and I always close those tags myself when hand-writing them. :D

**Comment by jhchen** [comment]
Yes the image format is just using document.createElement so the doctype is controlling for tag closing, which quilljs.com specifies as html5

**Comment by jatolmed** [comment]
Sorry, but that many responses doesn't answer the question. I have the same problem. I'm very aware that in HTML5 there is not need to close some tags explicitly, but I have to parse the HTML generated by Quill with third party libraries that requires closing tags everiwhere.

**Comment by daimant** [comment]
> Sorry, but that many responses doesn't answer the question. I have the same problem. I'm very aware that in HTML5 there is not need to close some tags explicitly, but I have to parse the HTML generated by Quill with third party libraries that requires closing tags everiwhere.

i found solution! use: <div innerHTML={ HTML5 }/>

**Comment by apostololeg** [comment]
The problem with unclosed tags reveals when using DOMParser.
```js
const htmlStrig = '<p><img src=""><div></div></p>';
const domParser = new DOMParser();
const tree = domParser.parseFromString(htmlStrig, 'text/html');
(new XMLSerializer()).serializeToString(tree);

tree.body.innerHTML; // '<p><img src=""></p><div></div><p></p>'
```

I love Quill and i would like to have it compliant with DOMParser API.

**Comment by LuisHenriqueJung** [comment]
Hi! Any solution for this situation? I encountered the same problem on a project
