### ISSUE TITLE
Allow quill to retain some arbitrary HTML on calling `dangerouslyPasteHTML()`

### ISSUE THREAD

**Issue by igorbuts** [quilljs/quill#1856]
While using Quill in my app I need to add some arbitrary HTML, that is - adding ids to tags that are allowed by quill (strong, u, ....). I need this to link some marked items in the editor with other parts of my application. It works ok and quill doesn't remove them. But then, when I retrieve this saved editor content from the server and paste it back to the editor using dangerouslyPasteHTML(), quill cuts the id attribute.

**Steps to reproduce:**
```javascript
1. ...dangerouslyPasteHTML("<p>Hello <strong id="4ede4c10-dad">bold</strong> text</p>")
```

**AR (DOM of editor container):** 
```html
<div class="ql-editor" data-gramm="false" contenteditable="true">
  <p>Hello <strong>bold</strong> text</p>
</div>
```

**ER (DOM of editor container):** 
```html
<div class="ql-editor" data-gramm="false" contenteditable="true">
  <p>Hello <strong id="4ede4c10-dad">bold</strong> text</p>
</div>
```

**Platform**
Mac OS X El Capitan v. 10.11.6,  Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Version** quill 1.3.4

Is adding ids (or other attributes) also not safe from a bug-free and user experience perspective?
If not, if there any possibility that such type of arbitrary HTML as this will be allowed?

**Comment by benbro** [comment]
You'll have to extend the clipboard module for this:
https://github.com/quilljs/quill/blob/develop/modules/clipboard.js#L97

**Comment by jhchen** [comment]
The way to safely add customization to Quill's contents is through [Parchment](https://github.com/quilljs/parchment). I would suggest looking at the attributors section.
