### ISSUE TITLE
Support blob urls for images

### ISSUE THREAD

**Issue by fabioelia** [quilljs/quill#1857]
We use blobified url's for images, and would like to use this inside of quiljs.

Example of a blobified image url:
https://codepen.io/anon/pen/BJBgoL

**Steps for Reproduction**

1. Provide an blobified image url to quiljs
2. Image src is now transformed to "//:0"

**Expected behavior**:
See the blobified image

**Actual behavior**:
Seeing a broken image

**Platforms**:
All platforms

**Version**:
1.3.4

**Comment by jhchen** [comment]
There's a long list of potential protocols so I would rather Quill support just a few common ones and allow the end user to modify.

```js
var Image = Quill.import('formats/image');
Image.match = function(url) { /* ... */ };
Image.sanitize = function(url) { /* ... */ };
```
