### ISSUE TITLE
How to get and set the caret position programatically?

### ISSUE THREAD

**Issue by PedroVinicius** [quilljs/quill#1861]
I don't know if here is the correct place to ask this, but there we go. I liked a lot this editor, but before inserting it into my project, I need to know if it provides the functionality I need. For my project, the users need to be able to create document templates and put some placeholders into the text. All the placeholders will be contained in a `select` tag. When the user select one of the options, its `value` attribute need to be put at the last caret position known and surrounded by curly brackets. 

For example, if the options are

````
<select>
  <option value='Choose a field'></option>
  <option value='lawsuit'>Lawsuit Number</option>
  <option value='customer'>Customer Name</option>
</select>
```` 

and  the user choose the `Lawsuit Number` option, the text "{LAWSUIT}" should be put at the last caret position known. But in order to achieve that, I need a way to get the position.

Does this library provide a way to do that? If no, do you know another way?

**Comment by benbro** [comment]
API:
https://quilljs.com/docs/api/#getselection
https://quilljs.com/docs/api/#inserttext
