### ISSUE TITLE
Is there a way to access button data-* data from an Inline subclass?

### ISSUE THREAD

**Issue by andresinaka** [quilljs/quill#1863]
I have this toolbar: 

    <div id="toolbar">
      <button class="ql-something" data-info="INFO">Something</button>
    </div>

And I want to be able to access to "data-info" from this extension so I can make a blot that behaves differently based on the data-info.

    class SomethingBlot extends Inline {}
    DoubleBlot.blotName = 'something';
    DoubleBlot.tagName = 'u';

Is this possible?

**Comment by benbro** [comment]
buttonEl.dataset.info
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
