### ISSUE TITLE
Is there a way to implement URL validation

### ISSUE THREAD

**Issue by lil25** [quilljs/quill#1864]
Hello

I'm trying to implement links validation to show error if user enters invalid URL for weblink and not to close creation link popup.
So how can i control link popup?

Thanks in advance.

**Comment by lil25** [comment]
I managed to do url validation, the code is not perfect, but works.

`var tooltipSave = quillInstance.theme.tooltip.save;

                quillInstance.theme.tooltip.save = function() {
                    // overwrite save link functionality
                    var url = this.textbox.value;

                    if(url.indexOf('http') === -1) {
                        url = 'http://' + url;
                    }

                    $(this.textbox).removeClass('ql-error');

                    if(util.validateURL(url)) {
                        tooltipSave.call(this);
                    }
                    else {
                        // show error in tooltip
                        $(this.textbox).addClass('ql-error');
                    }
                };`

**Comment by benbro** [comment]
Looks like you've found a solution. Closing.

**Comment by sahilsakhiya11** [comment]
handlers: {
        link: function (value) {
          if (value) {
            const editorInstance = focusRef.current;
            let range = editorInstance.editor.getSelection();
            if (range == null || range.length === 0) return;
            let preview = editorInstance.editor.getText(range);
            const tooltip = editorInstance.editor.theme.tooltip;
            console.log(tooltip);
            tooltip.save = function () {
              const val = tooltip.textbox.value;
              console.log(tooltip.textbox.value);
              const linkValidityRegex =
                /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/gi;

              if (val.match(linkValidityRegex)) {
                console.log("success");
                editorInstance.editor.format('link', val)
              } else {
                console.log("fail");
                
              }
            };
            tooltip.edit("link", preview);
          } else  {
          }
        },
      },

**Comment by sahilsakhiya11** [comment]
handlers: {
        link: function (value) {
          if (value) {
            const editorInstance = focusRef.current;
            let range = editorInstance.editor.getSelection();
            if (range == null || range.length === 0) return;
            let preview = editorInstance.editor.getText(range);
            const tooltip = editorInstance.editor.theme.tooltip;
            console.log(tooltip);
            tooltip.save = function () {
              const val = tooltip.textbox.value;
              console.log(tooltip.textbox.value);
              const linkValidityRegex =
                /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/gi;
              if (val.match(linkValidityRegex)) {
                console.log("success");
                editorInstance.editor.format('link', val)
              } else {
                console.log("fail");
                
              }
            };
            tooltip.edit("link", preview);
          } else  {
          }
        },
      },

**Comment by sahilsakhiya11** [comment]
handlers: {
        link: function (value) {
          if (value) {
            const editorInstance = focusRef.current;
            let range = editorInstance.editor.getSelection();
            if (range == null || range.length === 0) return;
            let preview = editorInstance.editor.getText(range);
            const tooltip = editorInstance.editor.theme.tooltip;
            console.log(tooltip);
            tooltip.save = function () {
              const val = tooltip.textbox.value;
              console.log(tooltip.textbox.value);
              const linkValidityRegex =
                /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/gi;
              if (val.match(linkValidityRegex)) {
                console.log("success");
                editorInstance.editor.format('link', val)
              } else {
                console.log("fail");
              }
            };
            tooltip.edit("link", preview);
          } else  {
          }
        },
      },
