### ISSUE TITLE
IE11 only - quill.getText returns wrong value when replacing text in editor

### ISSUE THREAD

**Issue by shlomki** [quilljs/quill#1865]
When selecting and replacing text using the editor, quill.getText() returns the wrong text. 
Returned text is different from what is visible in the editor.

**Steps for Reproduction**
1. Visit https://codepen.io/anon/pen/dJPOXZ **on IE 11** (not chrome).

2. Click F12 to open Developer Tools, and select the Console tab.

3. Using your mouse, highlight the following text in the editor (located in the middle of the fourth line of text):
"line of text
5 fifth line of text
6 sixth line of text"

4.  Press "a" on your keyboard (without the quotes) in order to replace the text you've selected.

**Expected behavior**:
Console prints:
"text-change event fired. quill.getText returned:
1 first line of text
2 second line of text
3 third line of text
4 fourth a"

**Actual behavior**:
Console prints:
"text-change event fired. quill.getText returned:
1 first line of text
2 second line of text
3 third line of text
_**5 fifth line of text**_
4 fourth a"

**Platforms**:
Internet Explorer 11.0.9600.18837IS on Windows 7
Does not reproduce on Chrome, on the same machine.

**Version**:
Latest version used from Quill Playground (1.3.4).

**Comment by alexsurg** [comment]
Also encountered this issue, can you please help with a fix.

**Comment by benbro** [comment]
IE11 is not supported.
