### ISSUE TITLE
Output markdown instead of html

### ISSUE THREAD

**Issue by GildedHonour** [quilljs/quill#1867]
Does it support outputting markdown instead of html?

**Comment by benbro** [comment]
Previous discussion: https://github.com/quilljs/quill/issues/74

**Comment by GildedHonour** [comment]
I've seen that, but what they've ended up with is unclear.

**Comment by benbro** [comment]
https://github.com/quilljs/quill/issues/74#issuecomment-230180168
Markdown related modules might help:
https://github.com/quilljs/awesome-quill

**Comment by duhaime** [comment]
@benbro any chance you could add a minimal example of how one can render to markdown with quill?
