### ISSUE TITLE
How to strip off formatting in Quill image editor

### ISSUE THREAD

**Issue by izzatz** [quilljs/quill#1870]
Currently quill editor will save the image in base64 image format. That is fine for now. But how do I make sure quill save the base64 content only and without those formatting?

This is how it would look like after the image has been saved in the db.

`<p><img src="data:image/png;base64,iVBXXXXXXXXXXXXXXXXXXXXXXXXXXX"></p>`

Basically I want to strip off `<p>` and `<img src= tags`

I would like to retain `data:image/png;base64,iVBXXXXXXXXXX` only. Is there any setting that I can do on quill modules?

**Comment by jhchen** [comment]
Don't duplicate content from Stackoverflow please.

**Comment by izzatz** [comment]
It was me who submitted in stackoverflow. Just thought posted it here and get some feedback from the developer.
