### ISSUE TITLE
quill.focus();does not work in ios uiwebview

### ISSUE THREAD

**Issue by Smart-AI** [quilljs/quill#1871]
quill.focus();does not work in ios uiwebview
keyboard could not turn up
ios version 11.1.2
quill version 1.3.4

**Comment by benbro** [comment]
Did you try to set keyboardDisplayRequiresUserAction in UIWebView to NO as explained [here](https://stackoverflow.com/a/12923898)?

**Comment by benbro** [comment]
Related:
https://bugs.webkit.org/show_bug.cgi?id=142757

**Comment by Smart-AI** [comment]
thank you for reply me , it works。

**Comment by Smart-AI** [comment]
self.webView.keyboardDisplayRequiresUserAction = NO
