### ISSUE TITLE
Quill not compatible with Gridster

### ISSUE THREAD

**Issue by HemantSinghEdu** [quilljs/quill#1872]
Hello. It seems that Quill doesn't work if you have the editor inside a gridster div. You can't type text or see the cursor.
Please find the issue here http://jsfiddle.net/md1xztks/17/
Anything that can be done to fix this? :)

**Comment by benbro** [comment]
You should fill all the info requested in the template.
Anyway, this is not a Quill bug. If you combine two tools together you need to figure out how to make them work.

**Comment by HemantSinghEdu** [comment]
Apologies for the wrong format. I did find the solution for this issue here https://github.com/ducksboard/gridster.js/issues/345

Adding the below code does it for me:
var gridster = $(".gridster ul").gridster().data('gridster');
$('ql-editor').mousedown(function () {
        gridster.disable().disable_resize();
        $(this).attr("contenteditable", "true");
        $(this).focus();
    }).blur(function () {
        gridster.enable().enable_resize();
    });
