### ISSUE TITLE
Spaces are not accepted at all on firefox

### ISSUE THREAD

**Issue by mahadazad** [quilljs/quill#1874]
While using QuillJs on firefox spaces are not accepted at all. On other hands, it works pretty fine on chrome.

**Steps for Reproduction**

1. https://codepen.io/anon/pen/jYqmba
2. Open Firefox
3. Try to type some sentence

**Expected behavior**:
It should accept spaces like a normal textbox.

**Actual behavior**:
Spaces are not accepted.

**Platforms**:
Firefox Quantum 57.0.1 (64-bit), macOs High Sierra.

**Version**:
1.3.4

**Comment by benbro** [comment]
In your example, you didn't include Quill's CSS.
I can't reproduce on the original [codepen](https://codepen.io/quill/pen/KzZqZx).

**Comment by benbro** [comment]
With the core or theme CSS it works fine:
https://codepen.io/anon/pen/OzNmBO

**Comment by rtivital** [comment]
If someone else would have this issue while trying to create custom theme: `white-space: pre-wrap;` is required on `.ql-editor` to make it work in Firefox
