### ISSUE TITLE
click the button in toolbar,the selection cannot be collapsed.

### ISSUE THREAD

**Issue by shengxiuzhou** [quilljs/quill#1875]
I use quill in my project and add my own buttons in toolbar. Now I met a problem ,  click one button then click another ,all the selections are showed instead of collapse.(showed in image) How can solve this problem? Thanks very much;
![image](https://user-images.githubusercontent.com/17645952/34200742-21c46d26-e5ad-11e7-85f2-ae0381554eab.png)

**Comment by benbro** [comment]
Please include all the info requested in the info template.
Fork the [codepen](https://codepen.io/quill/pen/KzZqZx) with the minimum code required to reproduce the issue.
