### ISSUE TITLE
Midword "ENTER" press behaves in unpredictable ways on Android / Multiple Browsers

### ISSUE THREAD

**Issue by derekaug** [quilljs/quill#1876]
On Android (tested on 7.1 and 8.1) in Chrome and Firefox, pressing "ENTER/RETURN" in the middle of a word behaves in odd and unpredictable ways.

**Steps for Reproduction**

1. Visit https://codepen.io/derekaug/full/MrjdLV
2. Tap to position cursor after the letter "o" in "copy"
3. Press "Enter"

**Expected behavior**:

Insert a new line / paragraph after the "o" with the cursor on the new line with "py here." sitting behind the cursor.

_Expected Visual Output:_
Test co
py here.

**Actual behavior**:
New line inserted after the word "copy". " here." is on a new line. And cursor is placed after the "p" in "copy"

_Actual Visual Output:_
Test copy
 here.

**Platforms**:

Tested in Android 7.1 and 8.1.
Chrome 63.0.3239.11 and Firefox 57.0.1

**Version**:

Quill version 1.3.4

**Comment by derekaug** [comment]
I have a feeling this is related to the keyboard being used as well, in my case I'm using GBoard.

**Comment by ivanalejandro0** [comment]
I'm not able to reproduce this issue on Android 7.0, Chrome 66.0.3359.158. I've tested it with both Gboard and Samsung keyboards.
