### ISSUE TITLE
Check if it's in browser environment in the constructor of Quill class

### ISSUE THREAD

**Issue by dannyzhan** [quilljs/quill#1877]
I am using asp.net core 2.0 + angular 4 with angular universal enabled by default.
after I added a quill editor to my component, the page complains "document not defined" error in main-server.js and so the page cannot be displayed.

I added the below line to the constructor of Quill class and the error disappeared:
`if(typeof window === 'undefined') return;`

I understand quilljs is tied to browser, but it's better to have a check.
what do you think?

**Comment by benbro** [comment]
You can add this check before creating the editor in your code:
```javascript
// verify that we are running in a browser:
if(typeof window === 'undefined') {
  return;
} else {
  var quill = new Quill('#editor-container', {
    modules: {
      toolbar: [
        [{ header: [1, 2, false] }],
        ['bold', 'italic', 'underline'],
        ['image', 'code-block']
      ]
    },
    placeholder: 'Compose an epic...',
    theme: 'snow'  // or 'bubble'
  });
}
```

**Comment by dannyzhan** [comment]
Sorry, but your solution doesn't work.
I noticed my error was reported at first line of core\polyfill.js

`let elem = document.createElement('div');`

but after I added browser check to it, it doesn't work too.
The only way works to me is to add browser check in the distributed quill.js as I updated in the original comment.

Angular Universal(server side rendering) is enabled by default.
So I expect all the Angular 4 users will come across my issue.

**Comment by guillaume-ro-fr** [comment]
@dannyzhan If you solve the problem with Angular Universal and the global `document`, you will have another problem with DOMTokenList just after.

In your `server.ts` file, you can add : 

```ts
// imports ...

const template = readFileSync(join(DIST_FOLDER, 'browser', 'index.html')).toString();
const domino = require('domino');
const win = domino.createWindow(template);
global['window'] = win;
global['window']['Promise'] = global['Promise'];
global['document'] = win.document;
global['navigator'] = win.navigator;
global['Event'] = domino.impl.Event;
global['Node'] = domino.impl.Node;
global['DOMTokenList'] = domino.impl.DOMTokenList;

// express configuration ...
```
