### ISSUE TITLE
dangerouslyPasteHTML()

### ISSUE THREAD

**Issue by ghost** [quilljs/quill#1881]
Hello, I am having a problem with using `dangerouslyPasteHTML()`. I know using it is dangerous (from the name mostly), but I think I really have no choice, unless I am missing something. What I'm trying to do is grab original HTML code that was created by Quill that I posted onto my mySQL database. However, it doesn't show most of the time. Sometimes if I refresh several times it will work though. I have a feeling it's because of the fact that when I have an image in the HTML, it might break it a bit since Quill stores the entire data of the image, instead of like storing it locally on my server.

**Steps for Reproduction**
1. `$content` variable: https://pastebin.com/raw/dG6vjtAP
2. Run `quill.clipboard.dangerouslyPasteHTML("<?php echo addslashes($content);?>");`

**Platforms**:

Google Chrome 63.0.3239.84 on macOS X High Sierra

**Version**:

1.1.6

**Comment by jhchen** [comment]
This is very consistently working for me https://codepen.io/quill/pen/baByrd. Please clarify your expected and actual results too.
