### ISSUE TITLE
Cursor moves back when typing first character on new row

### ISSUE THREAD

**Issue by rssluca** [quilljs/quill#1882]
Hi all,

I am implementing Quill on formbuilder js. As per the title when I type the first character on a new row the cursor moves back to the start of the row. It does only for the first if I keep typing the cursor stays behind the last (first entered) character.

I It looks like the first character is removed to add a new <p> then reinserted with the cursor on its left though.

Version: latest 1.3.4
Browsers: Chrome - Safari

Codepen: https://codepen.io/anon/pen/PEWqEM
Steps:

1. Add a new paragraph, mouse over the new field and click the edit button in the fields top right corner
2. Add a new row and type anything in the Quill editor 

Thanks in advance.
![dec-26-2017 17-40-28](https://user-images.githubusercontent.com/11591556/34349908-e7932bea-ea63-11e7-9103-4356b6641c06.gif)

![image](https://user-images.githubusercontent.com/11591556/34349505-56367f32-ea61-11e7-86e7-642911d4ba8b.png)

**Comment by benbro** [comment]
Please include all the info requested in the issue template.
Try to reproduce it on the [CodePen](https://quilljs.com/playground/).

**Comment by rssluca** [comment]
Was this closed because it has been solved? I did search before and could not find anything related.

**Comment by benbro** [comment]
It was closed because this doesn't look like a bug in Quill but with the way you integrate it with a third party tool.

If you think that there is a bug in Quill, fork the CodePen with the **minimal code** required to reproduce the issue and explain how to reproduce it.

**Comment by marciodsousa** [comment]
@rssluca I also have this issue currently. were you able to figure it out?

**Comment by rssluca** [comment]
@marciodsousa Are you having this issue with Quill and Formbuilder.js or a different implementation? In my case I ended up moving the editor outside of the field edit window because I could not figure out what was causing the issue.

**Comment by marciodsousa** [comment]
Different implementation, but exactly the same issue

Although i'm using quill in another part of the app and it works great.

But thank you!

**Comment by marciodsousa** [comment]
so @rssluca and @benbro I was able to reproduce it very easily in codepen.

You just need to add `contenteditable="true"` to the only div on the HTML and you can see this behaviour. At least for me this was the issue, but I don't know how/if quill can prevent this or if it qualifies as bad integration (probably).

**Comment by shengxiuzhou** [comment]
@marciodsousa  I met the same problem when I add contenteditable = "true"  attribute in element with 'ql-container'.  How do your solve it?

**Comment by marciodsousa** [comment]
Well, in my case, and I believe in general, it didn't make sense to have both `.ql-container` and `.ql-editor` as `contenteditable`. Also because this might lead to the user being able to delete the whole `.ql-editor` element (place cursor in the first position and press backspace).
