### ISSUE TITLE
inline style lose

### ISSUE THREAD

**Issue by ReAlign** [quilljs/quill#1883]
![](http://olz3b8fm9.bkt.clouddn.com/17-12-26/94567759.jpg)

font `bold`, `italic`, `underline` use inline style, but, when add link, inline style will be lost

[DEMO](http://realign.pw/vue-rich-editor/)

[github](https://github.com/ReAlign/vue-rich-editor/blob/master/src/vue-rich-editor/rewrite/bold.js)

by the way, how to change the placeholder in link input

![](http://olz3b8fm9.bkt.clouddn.com/17-12-26/87188941.jpg)

**Comment by benbro** [comment]
https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#bug-reports

**Comment by benbro** [comment]
I can't reproduce in Chrome and Firefox.
Reopen if you can reproduce in the [codepen](https://codepen.io/quill/pen/KzZqZx) or [quilljs.com](https://quilljs.com/) and add all the info requested in the info template.

**Comment by ReAlign** [comment]
May be the site access restrictions, I neglected.

I put it into codesandbox:

[rich-editor-demo](https://codesandbox.io/s/w0m20jjxrl)

and the custom formats github file is: 

[custom bold formats](https://github.com/ReAlign/vue-rich-editor/blob/master/src/vue-rich-editor/rewrite/set-style-method/bold.js)

about faulty behavior, Added a few words:

Bold, italic, underline the font, I use custom formats, but when set one or more of the above, then to set the link, inline style is lost.

thanks

**Comment by benbro** [comment]
We are not going to debug your code and check your website.
Please include all the info requested in the issue template.
Please fork the [codepen](https://codepen.io/quill/pen/KzZqZx) with minimal example and explain how to reproduce.

**Comment by ReAlign** [comment]
amazing, delete the third argument when create `new Parchment.Attributor.Style`, the problem disappears

[Quill Inline Style OK](https://codepen.io/realign/pen/Vypboq)
[Quill Inline Style Lost](https://codepen.io/realign/pen/dJvRow)

**Comment by ReAlign** [comment]
what about this？ ↓
![](http://olz3b8fm9.bkt.clouddn.com/17-12-28/63621734.jpg)

**Comment by benbro** [comment]
https://github.com/quilljs/quill/blob/develop/themes/snow.js#L112
Please use StackOverflow for questions.
