### ISSUE TITLE
Error: Uncaught TypeError: clipboard.addMatcher is not a function

### ISSUE THREAD

**Issue by zzzgit** [quilljs/quill#1884]
```javascript
import Quill from 'quill'
let clipboard = Quill.import("modules/clipboard")
clipboard.addMatcher('TABLE', function (node, delta) {
	console.log(node)
	table_id = random_id();
	return delta;
});
```

Uncaught TypeError: clipboard.addMatcher is not a function

I got this error in console when trying to import a third party module

**Comment by benbro** [comment]
https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#bug-reports

**Comment by benbro** [comment]
I can't reproduce in this [codepen](https://codepen.io/anon/pen/OzpXNV).
