### ISSUE TITLE
how can i focus the editor where the place i want

### ISSUE THREAD

**Issue by Smart-AI** [quilljs/quill#1885]
first, thanks very much
1.i use quill in ios on uiwebview, how can i focus the editor at the place after i insert a image.when i insert a image , i focus at the end of text not after image
2.how can i focus the editor at the end of the text, the text is request from backend, i request the text and show in the editor, but when i focus it ,it focus at the first of the text, i want to focus it at the end

the method  of mine

function restoreRange() {
                var selection = window.getSelection();
                selection.removeAllRanges();
                var range = document.createRange();
                range.setStart(currentSelection.startContainer, currentSelection.startOffset);
                range.setEnd(currentSelection.endContainer, currentSelection.endOffset);
                selection.addRange(range);
}

function insertImageUrl(url) {
                restoreRange();
                var begin = currentSelection.startOffset;
                quill.insertEmbed(begin.index, 'image', url);
                backupRange();
                focusEditor();
}

function focusEditor() {
                quill.focus();
}

**Comment by benbro** [comment]
https://quilljs.com/docs/api/#setselection
