### ISSUE TITLE
reopen issues#1883

### ISSUE THREAD

**Issue by ReAlign** [quilljs/quill#1888]
[issues#1883](https://github.com/quilljs/quill/issues/1883)

May be the site access restrictions, I neglected.

I put it into codesandbox:

[rich-editor-demo](https://codesandbox.io/s/w0m20jjxrl)

and the custom formats github file is: 

[custom bold formats](https://github.com/ReAlign/vue-rich-editor/blob/master/src/vue-rich-editor/rewrite/set-style-method/bold.js)

about faulty behavior, Added a few words:

Bold, italic, underline the font, I use custom formats, but when set one or more of the above, then to set the link, inline style is lost.

thanks

**Comment by benbro** [comment]
duplicate
