### ISSUE TITLE
add attr target='_blank'

### ISSUE THREAD

**Issue by spirityy** [quilljs/quill#189]
when i insertText use formats 'link'
how can i add attr target='_blank' into the link tag?

**Comment by JWesorick** [comment]
+1

**Comment by brettimus** [comment]
+1

**Comment by Joeao** [comment]
I made an attempt at adding this as an option when initiating a Quill object. I'm not completely happy with the implementation as it involves passing the option through a number of functions. As I'm not too familiar with the plugin, it's possible that there's a better way of achieving the results. It's a starting point at least.

Here's my commit:
https://github.com/Joeao/quill/commit/802fccb14b92716a76de54329bd94ad6ed0c2b68

Compiled file:
https://gist.github.com/Joeao/0c33f63c6aba38e8e80f

Let me know how it can be improved. Link targeting is a feature that I'd like to see in a future version.

**Comment by Joeao** [comment]
Thoughts on this @jhchen?

**Comment by jhchen** [comment]
I agree with the concern with solving this by special casing an additional parameter. I think once the ongoing effort to support custom formats is complete, this customization will be trivial to implement.

**Comment by amerikan** [comment]
Any updates on this? Seems like a handy feature.

**Comment by shikolay** [comment]
+1

**Comment by scottsheffield** [comment]
The recently announced beta of Quill does this now. For those who need further customization, modification of the Link blot is as easy as extending it and modifying the `create` function.

**Comment by bobmagicii** [comment]
so dumb question, did this ever become an /option/ or is it now instead of all links are same tab all links are new tabs? kinda lolling to myself over here trying to use it in a cms and every single link on the site to internal pages opens in new tabs.
