### ISSUE TITLE
How to change UI of the toolbar?

### ISSUE THREAD

**Issue by shengxiuzhou** [quilljs/quill#1890]
1.I want to rewrite the editor toolbar UI, for example quill's default  color picker is like this
![image](https://user-images.githubusercontent.com/17645952/34431297-e8b98b58-eca8-11e7-8182-bf25b4fd791e.png)

 it's html structure is this:
![image](https://user-images.githubusercontent.com/17645952/34431367-92565984-eca9-11e7-85c7-a31431ee9cde.png)

the way of use like this:
![image](https://user-images.githubusercontent.com/17645952/34431389-b9a9cda4-eca9-11e7-81a0-fd4363ea24d3.png)

I want to change the color picker like this .
![image](https://user-images.githubusercontent.com/17645952/34431419-059935b0-ecaa-11e7-8ff4-6f7a85944744.png)

How can I do , do I need write a color picker myself?  I want to know which is the simplest way? 

2. Besides I find that ,when I click link button , it response nothing,what's wrong with it?
![image](https://user-images.githubusercontent.com/17645952/34431470-84c62dd4-ecaa-11e7-82e6-fdadad70858c.png)

Thanks very much.

**Comment by benbro** [comment]
This question is better for StackOverflow. Github issues are for bugs.

Try to override the color picker style with CSS.
[colorItemSize = 16px](https://github.com/quilljs/quill/blob/develop/assets/base.styl#L8)
```css
.ql-snow .ql-color-picker .ql-picker-item {
    width: 32px;
}
```

Don't mix several issues/questions.
If the link button works in the demo on https://quilljs.com, you have something missing in your code.

**Comment by shengxiuzhou** [comment]
link button does't work in the demo?what's wrong?

**Comment by benbro** [comment]
You need to select some text before you click on the link button.
Please ask question on StackOverflow.

**Comment by shengxiuzhou** [comment]
Ok ,"You need to select some text before you click on the link button",I think it's  a bug,   I think when I click the link button ,It should response like insert image.
