### ISSUE TITLE
Adding or removing items from Quill toolbar dynamically

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#1891]
I cannot figure this out and am surprised no one else has mentioned this in the issues.

I just want to be able to dynamically choose which items are in the toolbar. 

Right now upon initialization, I pass in which toolbar options are needed. 

But post-initialization, how can I change this?

**Comment by DmitrySkripkin** [comment]
Here is [codePen](https://codepen.io/DmitrySkripkin/pen/EoLyBJ), a bit tricky but it updates toolbar dynamically.
In order to show/hide buttons you have to extend and re-register theme and modify `buildButtons()` and `buildPickers()`.

But yep, that's a terrible workaround.

**Comment by jhchen** [comment]
Post initialization changes to the toolbar is not a supported feature. If you would like to request it can you provide suggestions on what the API would look like?

**Comment by sagarpatil** [comment]
**Use case:**
In my app there are a list of colors and font styles that the user can customize. When the fonts or colors are updated, the items should be simultaneously updated in the toolbar.

I dynamically create my toolbar by defining a set of defaults and then pushing these into a defaultToolbar Array:
 
```
qlTB_BasicFormatting : ['bold', 'italic', 'underline', 'strike']
qlTB_Lists : [{ 'list': 'ordered'}, { 'list': 'bullet' }],
qlTB_Align : [{ 'align': [] }],
qlTB_TypeStyles : [{ 'typo': [] }],
qlTB_Buttons : [{ 'buttons': [] }],
qlTB_Colors : [{ 'color': ['white','red','green','blue'] }]

defaultToolbar : [
	// this.qlTB_Colors,
        // this.qlTB_TypeStyles
]
```

My idea was to be able to update the individual arrays and then use `quill.update()` to update the respective toolbar. My app allows for multiple quill editors on the same page. I've also tried updating the HTML of the toolbar using something like:

```
$('.ql-toolbar .ql-color .ql-picker-item:eq('+_.indexOf(colorsList, oldColor)+')').attr('data-value', color).css('backgroundColor',color);
```

This is just a cosmetic fix though. Ideally, I was hoping to be able to define and update the individual arrays and these changes would be reflected in the toolbar. The API should return true if update was successful.

**Comment by mrowles** [comment]
**Use case:**
Populating with dynamic lists (as above). I use the [placeholder module](use https://github.com/jspaine/quill-placeholder-module) and would love to populate this via http request.

**Comment by sagarpatil** [comment]
UPDATE:
I'm storing all content in arrays, deleting all instances of quill and related UI elements, re-initialising Quill instances, and then loading content from the array back into the respective Quill elements. Expensive and time consuming but works. This process adds extra paragraphs occasionally.

@mrowles This post helped me - https://stackoverflow.com/questions/45877323/how-to-close-the-quill-editor-when-done-with-editing?rq=1

**Comment by anumysore5** [comment]
**Use case:**
I am using quill in `bubble` theme and have customized the `color` and `background` formats in the toolbar to show a set of colors when quill initializes. But when the user changes the website them, I want to be able to dynamically show a different set of color palette for `color` and `background` without having to reinitialize the editor.
