### ISSUE TITLE
Does the getContents method return Delta arrays having non-insert ops?

### ISSUE THREAD

**Issue by dchenk** [quilljs/quill#1892]
I'm trying to use Quill to allow users to create rich text that will be output as rendered HTML when the text is published, but this rendering needs to be done by the server, not dynamically by the browser upon every request. However, I don't like the `editor.root.innerHTML` trick to extract the HTML generated by Quill—in fact that trick won't really work well for what I'm doing. So my question is _When you call the `getContents` method on a Quill instance do you get an array that only has `insert` operations?_

The documentation about the Delta format does not say anything about how Quill handles the entire body of the text created in an editor when that body is retrieved using `getContents`. Since Deltas can be used to represent _changes_, how do I get just the Delta constructed out of the sum of the changes?

If the Delta returned by `getContents` only includes `insert` operations, it'll be easy to create an HTML rendering library in any language on the server side. Is this how `getContents` works?

Thanks!

**Comment by benbro** [comment]
Yes, please read:
https://quilljs.com/docs/delta/#document
