### ISSUE TITLE
Functionality questions

### ISSUE THREAD

**Issue by tssobe** [quilljs/quill#1893]
Hi

I would like to know if the quill editor supports the following:

1.Add line numbers in the left side of the editor.
2.Find - Find and highlight a text being searched by the user.
3.Go to line - Jump to a specific line.
4.Color text from start character to end character,

Thanks

**Comment by benbro** [comment]
You can try the [demo](https://quilljs.com/) and read about the api in the [docs](https://quilljs.com/docs/api/).
