### ISSUE TITLE
Object.prototype clash

### ISSUE THREAD

**Issue by KangfuChen** [quilljs/quill#1894]
Object.prototype.mymethod = function(){};

TypeError: undefined is not an object (evaluating 'Object.keys(_this.options.bindings)')

**Comment by benbro** [comment]
Please fill all the info requested in the issue template.

**Comment by KangfuChen** [comment]
```
    Object.prototype.mymethod = function(){};
    var quill = new Quill('#snow-container', {
      placeholder: 'Compose an epic...',
      theme: 'snow'
    });
```
Quill Editor v1.3.4
我在下载的例子里面加了一行 Object.prototype.mymethod = function(){}; 就会报错，取消就没有问题。我的项目里面有扩展了Object，才出现的问题。
(不好意思，我不太会用英语。)
