### ISSUE TITLE
IE11 only - deleting the first formatted character doesn't invoke the "editor-change" event

### ISSUE THREAD

**Issue by eladt81** [quilljs/quill#1895]
If you try to delete a formatted (Bold/Italics/Underline) character from the beginning of the line, it won't invoke the "editor-change"/"text-change" event and the getText() won't get updated

**Steps for Reproduction**

1. Visit https://codepen.io/anon/pen/JMKyxB on Internet Explorer 11
2. Try to delete the letter "T" in the first word ("Try")
3. Notice that the quill.getText() doesn't get updated (see "Results of quill.getText()" above the textbox)
4. Delete the last letter in the sentence to notice the difference between quill.getText() and the actual text

**Expected behavior**:

The text of quill.getText() should be the same as the text in the div:

_ry in IE11 to delete this sentence one character at a time from the first lette_

**Actual behavior**:

The text of quill.getText() still contains the word "Try" at the beginning:

_Try in IE11 to delete this sentence one character at a time from the first lette_

**Platforms**:

Internet Explorer 11.786.15063.0 on Windows 10
Does not reproduce on Chrome, on the same machine.

**Version**:

Latest version used from Quill Playground (1.3.4).

**Comment by jabro86** [comment]
I would also be interested in a fix or workaround for this issue. :)

**Comment by alexsurg** [comment]
Same here, can you please find a fix for this issue.

**Comment by zengyuangai** [comment]
1.3.6 no problem

**Comment by benbro** [comment]
IE 11 not supported.
