### ISSUE TITLE
IE11 only - wrong background-color handling 

### ISSUE THREAD

**Issue by dunchan** [quilljs/quill#1897]
The  background-color handling works wrong in IE11

**Steps for Reproduction**

1. Visit https://quilljs.com/playground/#class-vs-inline-style
2. change the background-color of a one letter inside a word
3. Select the whole word 
4. copy it to clipboard
5.. Move cursor to end of a line 
5. Paste from clipboard

**Expected behavior**:
word inserted with background color for one letter

**Actual behavior**:
word inserted w/o bg color style

**Platforms**:
IE11

**Version**:
Any version - 1.3.4

**Comment by benbro** [comment]
IE11 not supported.
