### ISSUE TITLE
Determine if an <img> is  is being deleted on user keypress

### ISSUE THREAD

**Issue by brianmcdonough** [quilljs/quill#1898]
I have successfully implemented upload to AWS for images in quill, and when user selects the image before deleting, I can remove the image from AWS before Quill deletes the <img> tag.

No problem thanks to the fine direction on creating a Medium clone.

But, what I have not been able to do is to listen for and identify the *specific* event where the user presses the delete key and quill removes an img element as if it's just so much text.

The image is embedded using ImageBlot per the instructions.

From there, I need to retrieve the src of the img element to call deleteObject on AWS. So, I need access to the img element before Quill deletes it. 

I've been studying keybindings (https://quilljs.com/docs/modules/keyboard/), and have been experimenting with them, but am writing now to solicit guidance as it seems like a common use case and it will be great to do it in the _proper Quill way_.

**Comment by El-Mahbub** [comment]
I have same problem

**Comment by Nolence** [comment]
Just in case anyone needs this, here's what I did. I'm using `firebase` and the `vue-quill-editor` but I'll try to make this general:

```javascript
quill.on("text-change", (delta, oldDelta, source) => {
  if (source === "user") {
    let currrentContents = quill.getContents();
    let diff = currrentContents.diff(oldDelta);
    try {
      console.log(diff.ops[0].insert.image);
    } catch (_error) {}
  }
});
```

**Comment by TaylorHorn** [comment]
> Just in case anyone needs this, here's what I did. I'm using `firebase` and the `vue-quill-editor` but I'll try to make this general:
> 
> ```js
> quill.on("text-change", (delta, oldDelta, source) => {
>   if (source === "user") {
>     let currrentContents = quill.getContents();
>     let diff = currrentContents.diff(oldDelta);
>     try {
>       console.log(diff.ops[0].insert.image);
>     } catch (_error) {}
>   }
> });
> ```

This somewhat works, so thank you! To improve I would recommend iterating over `diff.ops` since `{insert: {image:}}` could be somewhere other than the first iteration of the `diff.ops` array. I applied that to the solution in my use case in Angular and it worked great!

**Comment by atownley** [comment]
Thanks, @stargazing-dino and @TaylorHorn for this example!!

I was trying to figure out how to detect mention removal playing around evaluating quill+quill-mentions for replacing another component I'm using, and thanks to Google and your example, I've incorporated your advice and this seems to work.  I added the looping, and here's my skeleton example:

```
      quill.on('text-change', function(delta, oldDelta, source) {
        if(source !== 'user')
        {   
          return;
        }   
   
        var curr = quill.getContents();
        var diff = curr.diff(oldDelta);

        // look to see the delete
        curr = quill.getContents();
        for(var i = 0; i < diff.ops.length; ++i)
        {   
          var op = diff.ops[i];
          if(op.insert && op.insert.mention)
          {   
            console.log("mention removed");
            console.log(op.insert.mention);
          }   
        }   
      }); 
```

I'm adding this here, because it seems like any blot with a custom property will work the same, and this was one of the top hits. It also doesn't do the try/catch, which I think will actually result in poorer performance generating the stack trace if it's not an insert event.

Anyway, thanks again, and hopefully this helps anyone else looking to detect blot removal
