### ISSUE TITLE
how can i insert <br/> after i quill.insertEmbed() image

### ISSUE THREAD

**Issue by Smart-AI** [quilljs/quill#1899]
how can i insert <br/> after i quill.insertEmbed() image,because after i insert a image i want to wrap
and focus at the line after image
ios uiwebview

**Comment by mhdhamouday** [comment]
You can add this after insertEmbed
`			quill.insertEmbed(range, 'block', '<p><br></p>');
`

**Comment by DerDemystifier** [comment]
@mhdhamouday Comment is correct, however you need to move selection before inserting the block:
```javascript
let range = QuillEditor.getSelection();
QuillEditor.insertEmbed(range.index, 'image', `${dataURL}`);
QuillEditor.insertEmbed(range.index+1, 'block', '<p><br></p>');
```
