### ISSUE TITLE
Firefox is selecting every custom element in embedBlot

### ISSUE THREAD

**Issue by blaadje** [quilljs/quill#1900]
**Steps for Reproduction**

1) https://codepen.io/blaadje/pen/eyEqdG?editors=0110

2) Click somewhere in the embed (rectangle)

**Expected behavior**:

It shouldnt be any selected element when clicking in an embed blot (like in Chrome browser)

**Actual behavior**:

By clicking on an embed blot with custom content, every element is selected.

**Platforms**:

Firefox 57.0.3 (64-bit)
MacBook Pro (Retina, 13-inch, Early 2015) 
MacOS (Version 10.12.4)

**Version**:

Latest Quill version (Version 1.3.4)

**Comment by blaadje** [comment]
Hi @jhchen did u have time to take a look? I'd be glad to give you more informations about the issue if you need to.

**Comment by jhchen** [comment]
Seems like Firefox native behavior to select the contenteditable=false node. I do not think this is necessarily wrong behavior (actually I would think this is desired sometimes) so I would not consider this a bug. If you would like to prevent it one way is in `create` add an event listener for mousedown and cancel it:

```js
  static create ({ _id, _type }) {
    const node = super.create()

    node.setAttribute('_id', _id)
    node.setAttribute('_type', _type)
    node.setAttribute('data-blot', true)

    node.setAttribute('contenteditable', false)
    node.addEventListener('mousedown', (e) => {
      e.preventDefault();
    })
    
    return node
  }
```

**Comment by blaadje** [comment]
Thank you, it did perfectly what i wanted !
