### ISSUE TITLE
Support for Gist (script tags)

### ISSUE THREAD

**Issue by isaac2004** [quilljs/quill#1901]
This is more of a feature request than an issue and I am not sure the complexity involved. One thing that is pretty valuable is the ability to add a GitHub Gist to your editor. A Gist is a script file so not sure if Quill would be able to transpose the script into the html that is rendered, but it would be helpful.

Here is a sample of a gist.

  <script src="https://gist.github.com/isaac2004/b76c594709130d146a752d550c1ce770.js"></script>

**Comment by Jagadeeswarh** [comment]
Any solution to embed Gist in quill?
