### ISSUE TITLE
Where to look for user delete keystroke event and check what's being deleted before it's deleted by user?

### ISSUE THREAD

**Issue by brianmcdonough** [quilljs/quill#1902]
What title says.

I want to check for images being deleted from the interface to remove them from AWS.

Is this possible through the quill API? If not, is there a chance it will be added as a feature? 

Any explanation will help.

**Comment by brianmcdonough** [comment]
When I add:

`this.data.quill.keyboard.addBinding({
  key: 8,
  shortKey: false,
  handler: function(range, context) {
    console.log(context)
    }
  });
  console.log(this.data.quill.keyboard)`

The handler only fires when text is deleted and prevents the default delete action, but not when a newline or image element is deleted.

**Comment by brianmcdonough** [comment]
The following is documented by Quill. Apologies for not digging deeper:

     let bindings = {
         // This will overwrite the default binding also named 'delete'
         delete: {
           key: 8,
           offset: 0,
           handler: function(range, context) {
             console.log(this)
           }
         }
       }

**Comment by babaiwan** [comment]
Note: Since Quill’s default handlers are added at initialization, the only way to prevent them is to add yours in the [configuration](https://quilljs.com/docs/modules/keyboard/#configuration).
