### ISSUE TITLE
Insert blots/embed and typing Chinese, the first letter will appear in the editor.

### ISSUE THREAD

**Issue by zhuowenli** [quilljs/quill#1904]
```js
let BlockEmbed = Quill.import('blots/embed');

class CustomBlock extends BlockEmbed {
    static create(value) {
        let node = super.create();
        node.innerText = value;
        return node;
    }
    static value(node) {
        return node.innerText;
    }
}

CustomBlock.blotName = 'custom-block';
CustomBlock.tagName = 'mark';

Quill.register(CustomBlock);
```

**Steps for Reproduction**

1. Visit https://codepen.io/zhuowenli/pen/GyyqwQ?editors=0010
2. Click `#` button
3. Input any word and submit.
4. Move the cursor behind the embed, then input Chinese

![2018-01-08 15 12 15](https://user-images.githubusercontent.com/9620783/34662023-acdba64c-f488-11e7-8a60-10934a3d241b.gif)

Other selection range is OK:

![2018-01-08 15 12 48](https://user-images.githubusercontent.com/9620783/34662045-c567b782-f488-11e7-8722-62db9630c977.gif)

**Platforms**:
OS: macOS High Sierra 10.13.1
Chrome: 64.0.3282.71

**Version**:
1.3.4

**Comment by jayrom123** [comment]
i have same problem
Mac OS: 11.5.2  
chorme: 94.0.4606.61

**Comment by OldDream** [comment]
> 2021-10-14.17.15.12.mov

same here，with Chrome/94.0.4606.81 ,quill 1.3.7. Any solution here ？

**Comment by foriacus** [comment]
sad, same problem.
