### ISSUE TITLE
Quill is not showing a the last return / new line if entered by API 

### ISSUE THREAD

**Issue by TheDominik** [quilljs/quill#1907]
By executing the following script, it should display a single new line in the quill editor, but it seems not to work. The getContents shows the new line, but it is not shown in the browser.

```javascript
window.quill = new Quill('#editor', {
        theme: 'snow'});
    var delta = [];
    var test = {ops: [{insert: "\n"}]};
    window.quill.setContents(test, 'api');
    console.log(window.quill.getContents());
```
I am using the newest Chrome Version 63.0.3239.132 (64-Bit) and quill 1.3.4.

EDIT:
Basically, every last return is not shown in the browser if added by setContent() method.

**Comment by DmitrySkripkin** [comment]
Here is [codePen](https://codepen.io/DmitrySkripkin/pen/PEeojN) and I don't see any problem. Maybe you're missing something in your issue so I can't reproduce it.

**Comment by DmitrySkripkin** [comment]
`{ops: [ {insert: '\n'} ]}` is rendered as `<p><br></p>` and It's correct. 
When Quill is empty it has this empty paragraph  with the breakline, so i has height and user can click it. Basically `setContents({ops: [{insert: '\n'}]})` has same result as `setText('')`.

**Comment by TheDominik** [comment]
Oh okay. That's a little bit confusing that two different inputs lead to the same result. I would have expected that if you enter
```javascript
{ops: [{insert: ""}]}
```
you get an empty document and if you enter 
```javascript
{ops: [{insert: "\n"}]}
```
that you receive an actual return / line break.

**Comment by DmitrySkripkin** [comment]
Yep, here is better explanation [issue comment link](https://github.com/quilljs/quill/issues/1235#issuecomment-273044116). Sorry, was't able to find it before.

**Comment by benbro** [comment]
@DmitrySkripkin thanks for the help.
