### ISSUE TITLE
Method setSelection not working after user input

### ISSUE THREAD

**Issue by wiiiteek** [quilljs/quill#1908]
Method `setSelection` seems to not working after user type any text, but it works when user format text

**Steps for Reproduction**

1. Visit https://codepen.io/anon/pen/JMvKoa
2. You should see selected "me te". Now type anything it editor - nothing unusual will happen
3. Try to select some text and bold it - selection should change back to "me te"

**Expected behavior**:

Selection should change to "me te" every time text changes - since method `setSelection` is used in 'text-chage' event.

**Actual behavior**:

Actual `setSelection` works only when user format text (eg. set bold) or when api make changes.

**Tested on Platforms**:

* Firefox 57 @ Linux Mint
* Chrome 63 @ Linux Mint

**Version**:

1.3.4

**Comment by benbro** [comment]
https://quilljs.com/docs/api/#text-change

> Changes to text may cause changes to the selection (ex. typing advances the cursor), however during the text-change handler, the selection is not yet updated, and native browser behavior may place it in an inconsistent state. Use selection-change or editor-change for reliable selection updates.

**Comment by Jaimies** [comment]
@benbro It does not appear to work with "editor-change" event either. See [CodePen](https://codepen.io/anon/pen/JMvKoa)

**Comment by Jaimies** [comment]
The workaround I have discovered is to wrap `setSelection` call into a `setTimeout` with a timeout of 0:

```js
setTimeout(() => quill.setSelection(2, 5), 0)
```
This solution will work, but the cursor may sometimes flicker. See this [CodePen](https://codepen.io/jaimies/pen/JjYXRJo)
