### ISSUE TITLE
How to copy/export/import the history stack in a deep clone manner?

### ISSUE THREAD

**Issue by ggJSC** [quilljs/quill#1909]
**Setup**: Single Page Application using VueJS + Vuex.

**Use case**: I have meeting topics that are stored in state using Vuex. Each topic has its own delta object corresponding to its topic content. They all use the same quill editor and I simply load the current topic's delta when the currentTopic changes. However, since it's the same quill editor the history stack represents changes from all the topics. I can't simply pass `quill.history.stack` because it'll be passed by reference and changes to the history stack will cause red flags to go off with Vuex for editing the store outside of a mutation. 

I need a way to deep copy the undo/redo arrays in a manner that works. I've tried deep copy functions and copying only the arrays corresponding to redo and undo but nothing works. Undo seems to work occasionally but redo doesn't seem to ever work right. Redo after loading the history stack often causes `delta.reduce is not a function` errors.

**Comment by benbro** [comment]
Why not use a separate editor per topic and show only the active editor?

Share a minimal [CodePen](https://codepen.io/quill/pen/KzZqZx) of what you are trying to do and what doesn't work without depending on external libraries like VueJS.

**Comment by ggJSC** [comment]
I managed to figure it out. I'm not sure what was causing problems to be honest, but the previous errors I had weren't showing up.

**Comment by benbro** [comment]
Great.
