### ISSUE TITLE
FontSize style doesn't applied by clipboard IE11

### ISSUE THREAD

**Issue by dunchan** [quilljs/quill#1911]
If you have a text with different font sizes , and you copy and paste it , you will lose the font size

**Steps for Reproduction**

1. Visit https://quilljs.com/docs/formats/
2. enter and format a text to have :<p><span class="ql-size-small">a</span>b<span class="ql-size-large">c</span><span class="ql-size-huge">d</span></p>
3. select the word "abcd"
4. copy it to clipboard
5.paste it

**Expected behavior**:
Two word should be seen with different sizes

**Actual behavior**:
the pasted text loses the font size

**Platforms**:
win10
ie11.674.15063.0

**Version**:

Quill Editor v1.3.4

**Comment by Siebe** [comment]
This behavior also seems to occur in Chrome. Firefox works fine though. I can even copy from Firefox and paste in Chrome and the layout is copied as well.

Tested on Ubuntu 16.04 and Win7
Chrome  67.0.3396.99 
Firefox 60.0.2
Quill Editor v1.3.6
