### ISSUE TITLE
Editor fills value with class ql-cursor

### ISSUE THREAD

**Issue by ladygarnet00** [quilljs/quill#1915]
**Steps for Reproduction**

1. Write some text at the editor
2. Put de mouse cursor on the middle (or at some point) of the text
3. Use some toolbar controls (example: italic)
4. Mark some part of the text
5. Use the control over the selected text

It happens with most toolbars controls.

**Expected behavior**:
Add the italic tag over the selected text.

**Actual behavior**:
It adds this span  <span class="ql-cursor">﻿ over the selected text.

**Platforms**:

Tested on Google Chrome.

<img width="504" alt="captura de pantalla 2018-01-15 a la s 11 32 57" src="https://user-images.githubusercontent.com/24942857/34947113-e6284806-f9e7-11e7-90c5-78a9160b26f5.png">

**Comment by benbro** [comment]
[This comment](https://github.com/quilljs/quill/issues/1682#issuecomment-326686565) explains the ql-cursor element.

What is the real issue here?

**Comment by ladygarnet00** [comment]
i did not see that issue before, but it's the same case. it puts some span lines on my editor value when i use the toolbar controls. i'll use getContents and see what happens. This is an issue for me, the output it needs to be raw html .

**Comment by benbro** [comment]
Quill works with Delta and not with raw HTML. If you decide to use HTML despite the problems just filter this element.
This isn't a bug.
