### ISSUE TITLE
IE11 Only > Quill editor adds extra new lines (<p></p>) when text is copied from Outlook

### ISSUE THREAD

**Issue by stas-kh** [quilljs/quill#1917]
Hi guys,

I really like the tool you are contributing to. We have an Angular 5 application and found the issue with the editor.

**Steps for Reproduction**

1. Visit quilljs.com from IE 11
2. Copy any text with line breaks from Outlook (tested on 2010 and 2013 versions)
![outlook-quill](https://user-images.githubusercontent.com/10476834/34986111-04910990-fabf-11e7-8bab-8f27c4a1e162.png)
3. Paste the text from clipboard to any editor on the editor's home page
4. See that it contains 3 times more extra lines than in Outlook
![ie11-quill](https://user-images.githubusercontent.com/10476834/34986109-045b4be8-fabf-11e7-8356-ddbda15b179c.png)
![ie11-incorrect-html](https://user-images.githubusercontent.com/10476834/34986108-043ecaea-fabf-11e7-878b-446b5d6834c1.png)
5. Perform steps 1-4 in Chrome and see the results
![chrome-quill](https://user-images.githubusercontent.com/10476834/34986110-0476a262-fabf-11e7-8e95-0c564d09e27a.png)
![chrome-correct-html](https://user-images.githubusercontent.com/10476834/34986112-04acf844-fabf-11e7-9c93-3fc39b4ff86e.png)

**Expected behavior**:
The result is expected to be the same in all browsers

**Actual behavior**:
Displayed on the screenshots

**Platforms**:
IE11 only, Edge works fine

**Quill**:
"ngx-quill": "^2.0.4"

Guys, I would appreciate any workaround that you could propose.

**Comment by jhchen** [comment]
Have you tried the [matchVisual](https://quilljs.com/docs/modules/clipboard/#matchvisual) configuration option?

**Comment by stas-kh** [comment]
Yes, I've tried.

The same result:
![ie-test-with-match-visual](https://user-images.githubusercontent.com/10476834/35092552-6fdbf518-fc48-11e7-8db4-de6ee58443be.png)

**Comment by stas-kh** [comment]
Yes, I've tried.

The result is the same:
![ie-test-with-match-visual](https://user-images.githubusercontent.com/10476834/35092649-bc73457a-fc48-11e7-97e3-3ed8641f273f.png)

**Comment by stas-kh** [comment]
Guys, any suggestions?

**Comment by stas-kh** [comment]
We've switched to another editor because of this problem and lack of tables support in the editor.

**Comment by benbro** [comment]
IE11 not supported.
