### ISSUE TITLE
How to prevent XSS attacks

### ISSUE THREAD

**Issue by ReAlign** [quilljs/quill#1918]
How to prevent XSS attacks，like this：

`<img src="http://www.erorerer.com/a.jpg" onerror="alert(1)" />`

`<script>alert(1)</script>`

**Comment by DmitrySkripkin** [comment]
It's already prevented by clipboard module by default. Do you have any specific case or codePen example? You can't paste it to quill without sanitation and it won't be stored at delta anyway.

**Comment by tuomassalo** [comment]
I'd like to amend @DmitrySkripkin's comment, since it can be confusing and even dangerous for inexperienced developers.

Client-side modules can never prevent XSS attacks, even in theory. A malicious user can craft a http request that sends an XSS payload to the server, bypassing any client-side sanitation.

The correct way to prevent XSS attacks with rich-text editors is to enforce a whitelist of sanitation rules on the server, before storing the content. See #510 and eg. https://github.com/punkave/sanitize-html.

**Comment by xiegeo** [comment]
I just started using quill recently. Here is the workflow for my user content:

- A user submits quill edited text as a string of HTML.
- Server stores HTML as string/bytes.
- Other users can view the submitted text; this is done by setting the innerHTML of a div element.

I realize this leaves a vulnerability if a malicious user reverses engineers my API and submit dangers HTML. The service I'm building is only for in-house use so a malicious user should not be able to log-in, but I would like to do this correctly.

The easiest solution I can think of is to have quill sanitize the HTML string before including it in the page. Such that the allowed content matches quill formats. But I have not found any documentation to accomplish this.

**Comment by tuomassalo** [comment]
@xiegeo It is impossible to sanitize stuff on the client, since you have no control over the client. A malicious user can modify the client to send whatever payload to the server. You *must* sanitize the user input on the server.

The issue I referenced above (https://github.com/quilljs/quill/issues/510) has been deleted. Can @DmitrySkripkin or @jhchen shed some light on why?

**Comment by xiegeo** [comment]
@tuomassalo I don't need to protect what gets on the server, only what is displayed by well behaving clients.

**Comment by Gladskih** [comment]
@tuomassalo It's really _possible_ sanitaze stuff on the client before rendering.

**Comment by eladcandroid** [comment]
Any solution for that?

**Comment by vdechef** [comment]
Just in case someone still looks for a solution, the package [sanitize-html](https://www.npmjs.com/package/sanitize-html) is quite efficient for this.

**Comment by dfenerski** [comment]
The following `sanitize-html` whitelist configuration works for me. Tags are quite strict; no `img` or `video`s are allowed. Only the quill classes, attributes & styles are allowed. This list may be incomplete as I wrote it up based on the src code so I might've missed something.

```js
{
        allowedTags: [
            'a',
            'p',
            'span',
            'div',
            'h1',
            'h2',
            'h3',
            'h4',
            'h5',
            'h6',
            'ul',
            'ol',
            'li',
            'b',
            'i',
            'u',
            'em',
            'strong',
            'strike',
            'sub',
            'sup',
            'hr',
            'br',
            'blockquote',
            'caption',
            'code',
            'pre',
            'col',
            'colgroup',
            'table',
            'tbody',
            'td',
            'tfoot',
            'th',
            'thead',
            'tr',
        ],
        allowedAttributes: {
            a: ['href', 'name', 'target', 'rel'],
            span: ['style'],
            p: ['class'],
            li: ['class'],
            pre: ['class'],
        },
        allowedStyles: {
            '*': {
                'background-color': [
                    /^rgb\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*\)$/,
                ],
                color: [
                    /^rgb\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*\)$/,
                ],
            },
        },
        allowedClasses: {
            '*': [
                'ql-align-right',
                'ql-align-center',
                'ql-align-justify',
                'ql-code-block',
                'ql-code-block-container',
                'ql-syntax',
                'ql-direction-rtl',
                'ql-font-serif',
                'ql-font-monospace',
                'ql-formula',
                'ql-indent-1',
                'ql-indent-2',
                'ql-indent-3',
                'ql-indent-4',
                'ql-indent-5',
                'ql-indent-6',
                'ql-indent-7',
                'ql-indent-8',
                'ql-size-small',
                'ql-size-large',
                'ql-size-huge',
            ],
        },
    }
```

**Comment by vdechef** [comment]
I think you are still vulnerable to XSS : try inserting `<a href="javascript:alert(0)">`.

The easiest way is to rely on sanitize-html default settings, and amend them to allow only what you need.  
For example, if you want to allow inline images, and some inline style for colors:

```javascript
sanitizeOptions() {
    return {
        allowedTags: sanitizeHtml.defaults.allowedTags.concat(["img"]),
        allowedSchemesByTag: { img: ["data"] },
        allowProtocolRelative: false,
        allowedAttributes: Object.assign({ "*": ["style"], "ol": ["type"] }, sanitizeHtml.defaults.allowedAttributes),
        allowedStyles: {
            "*": {
                // Match HEX and RGB
                "background-color": [/^#(0x)?[0-9a-f]+$/i, /^rgb\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*\)$/],
                color: [/^#(0x)?[0-9a-f]+$/i, /^rgb\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*\)$/]
            }
        },
        // when returning true, element will be removed
        exclusiveFilter: elem => {
            // remove images that have no src attribute or not supported src
            return (elem.tag === "img" && (!elem.attribs.src || !elem.attribs.src.match(/^data:image\/(png|jpg|jpeg|gif);base64,/)))
        }
    }
}
```

**Comment by dfenerski** [comment]
The posted config only **_shrinks_** the defaults of **_some_** configuration properties. For the unchanged ones, the defaults kick in, meaning 
![image](https://github.com/quilljs/quill/assets/48520530/e25dd758-f35a-48ec-a906-ee73b1711467)
is active in the config above

**Comment by kochul2000** [comment]
on create: no sanitize
browser: POST request (delta) -> Server (delta)

on retrieve: do sanitize
Server (delta) -> browser: GET response (delta) -> delta to HTML convert -> `sanitize-html` -> show
