### ISSUE TITLE
Trigger bold action into text manually

### ISSUE THREAD

**Issue by ialex90** [quilljs/quill#1919]
Hi there,

Thanks for building this nice tool, we appreciate it.

Wondering if there is any way of triggering the bold, italic and other functions manually from js. I am trying to build a toolbar out of the editor, and having few editor on the screen, so the idea is to have one toolbar and based on the selected text, bold or style the right content.

Thanks,

**Comment by benbro** [comment]
https://quilljs.com/docs/api/#formattext

**Comment by Alzavio** [comment]
Is there a way of doing this without needing to specify a start and end? Just turn it on for future text the user writes?
