### ISSUE TITLE
Custom Module Issue - Quill being notified of style changes

### ISSUE THREAD

**Issue by danielmhair** [quilljs/quill#1920]
Below I explain my reasoning behind my question, but to be clear, here is what I'm hoping to know:
**How can I manually notify Quill that there have been style updates within my custom module?**

Here is my use case. I need to have an editor and a viewer that stay synced with each other (both are quill components). I'm currently using the quill-image-resize-module and then I made my custom video-module that allows you to resize a video. I am able to resize it in the first quill object just fine, but the changes do not propagate to my viewer (it listens to the change and updated the other quill viewer).

Here is a GIF showing the behavior (ignore the large scroll bar -- that is a computer resolution issue lol):

![video-resizing-no-propagation](https://user-images.githubusercontent.com/7373734/35015796-3fd3d0be-fad3-11e7-99b9-a608ffff1749.gif)

**Operating System**: Windows 10
**Browser**: Chrome 63.0.3239.132
**Quill Version**: 1.3.4

**Comment by benbro** [comment]
Please ask general questions on StackOverflow. Github issues are for bugs.
Check [events](https://quilljs.com/docs/api/#events), [updateContents](https://quilljs.com/docs/api/#updatecontents) and [formatting](https://quilljs.com/docs/api/#formatting).
