### ISSUE TITLE
Typing using Chinese keyboard in iOS9.3.3  if inline style is active will double the input result.

### ISSUE THREAD

**Issue by icewind7030** [quilljs/quill#1921]
Typing using Chinese keyboard in iOS9.3.3  if inline style is active will double the input result.

**Steps for Reproduction**

1. Visit quilljs.com with safari in iOS9.3.3.
2. Toggle 'bold' style active.
3. Typing using Chinese keyboard.
See the video of reproduction.
https://youtu.be/4M7eAV0eVB0

**Expected behavior**:
Get the only one copy of word in IME to editor. 
**Actual behavior**:
The word in IME got doubled and show in the editor.
**Platforms**:
iOS9.3.3 Safari

**Version**:
1.3.4

**Comment by hiYoHoo** [comment]
请问你有解决这个问题吗

**Comment by icewind7030** [comment]
@hiYoHoo 
![quilljs](https://user-images.githubusercontent.com/7500226/43239459-dedd92d0-90c4-11e8-8421-a67be8fc1939.png)

我好像是修改了[core/selection.js](https://github.com/quilljs/quill/blob/develop/core/selection.js)这个文件解决的，时间太久了，你可以试试

**Comment by WinMinTun** [comment]
@icewind7030 @hiYoHoo Is it ok now? Can someone tell me pls? My Chinese sucks. I m having the similar problem in #2305

**Comment by icewind7030** [comment]
@WinMinTun I tweak the [core/selection.js](https://github.com/quilljs/quill/blob/develop/core/selection.js) a little just like the image I posted, it seems fixed the problem, and I chose not to update my *quill.js* file together with the origin repository any more. So I can not be sure it works for now or is it still a problem since the origin repository changes a lot. 
The code I added is below:
```javascript
this.emitter.emit(Emitter.events.TEXT_CHANGE, null, null, Emitter.sources.USER);
if(/iPhone OS 9/i.test(navigator.userAgent) || /iPhone OS 10/i.test(navigator.userAgent)) return;
```
