### ISSUE TITLE
How are default/custom attributors registered? Every attributor seems to just pass through Quill.register.

### ISSUE THREAD

**Issue by ggJSC** [quilljs/quill#1922]
I'm trying to add a custom attributor for images and I'm struggling to see where they even get registered because I have a custom module and I want to access the AttributorStyle so I can format the image with `.add()`. I tried using `Parchment.query` but the only things that appear are the default attributors so I have no idea how they're being registered if they're being passed through the static `register` in `core/quill.js`.

**Comment by jhchen** [comment]
Please include all the details we ask for in the issue template.
