### ISSUE TITLE
Any way to have backspace (key) remove a block of text?

### ISSUE THREAD

**Issue by homerlex** [quilljs/quill#1923]
I'm playing with using TributeJS for mentions within Quill.  Mentions come up fine but when the user backspaces over the mention it would be desirable for the entire mention to be deleted (as opposed to one character at a time being removed).

Is this doable within Quill?

**Comment by icewind7030** [comment]
You can use the "Embed" blot.

**Comment by DmitrySkripkin** [comment]
You can use keyboard module bindings. Just check that caret position and context and remove whatever is needed. How does your delta with mentions look like?

**Comment by homerlex** [comment]
Thanks for the replies.  Using an embed blot does exactly what I want.
