### ISSUE TITLE
Inconsistent (or incomplete) documentation for Quill.register method

### ISSUE THREAD

**Issue by vk2sky** [quilljs/quill#1924]
(Disclaimer: Quill noob)

The [API documentation for the Quill.register method](https://quilljs.com/docs/api/#register) lists the following usages:

> Quill.register(path: String, def: any, supressWarning: Boolean = false)
> Quill.register(defs: { [String]: any }, supressWarning: Boolean = false)

while *[How to Customize Quill - Extending Blots](https://quilljs.com/guides/how-to-customize-quill/)* shows a different usage:

> class PlainListItem extends ListItem { ... }
> 
> Quill.register(PlainListItem, true);

It would be useful if the above usage (and any others if they exist) were documented in the API.

**Comment by vk2sky** [comment]
Also, if I'm looking in the right source file (quill.core.js), the method *sometimes* returns various types of value, but these are not listed on the API page for the method.

**Comment by vk2sky** [comment]
Hi @jhchen thanks for the documentation update.

Something I just noticed. In the Quill.register example:

> class CustomModule extends Module {}
> Quill.register('modules/custom-module', **_Module_**);

Should the second line be:
 > Quill.register('modules/custom-module', **_CustomModule_**);

?

**Comment by jhchen** [comment]
Yes you are right -- updated!
