### ISSUE TITLE
how to prevent delete text from removing the selected inline format

### ISSUE THREAD

**Issue by icewind7030** [quilljs/quill#1925]
I can't say this is a bug, but it's a problem to me.
After active a certain inline style, like 'bold',  I can type in words with expect style. But after I delete all the text in this line, my selected inline style disappear, how to prevent it?

**Steps for Reproduction**

1. Visit quilljs.com
2. active bold style
3. type in words with style 'bold'
4. delete all the word in this line
5.retype words

**Expected behavior**:
bold style still active and I can still type in words with style 'bold'
**Actual behavior**:
the 'bold' style was removed
**Platforms**:
chrome and safari

**Version**:
1.3.4

**Comment by jhchen** [comment]
#1790
