### ISSUE TITLE
How can I insert local image url with Quill in iOS WKWebView or UIWebView

### ISSUE THREAD

**Issue by hulala1210** [quilljs/quill#1927]
I was using Quill Editor in my own iOS App with both WKWebView and UIWebView. System Version is iOS 10.3.3 and device is iPhone6.  I tried to insert an Image URL with this API——quill.insertEmbed(3, 'image', '%@' ,Quill.sources.USER); and "%@" instead of my local image URL just like "/private/var/mobile/Containers/Data/Application/44C9D0FF-E028-434A-873B-2C53D164354E/tmp/StoreSource/IMG_1358.JPG" and "file:///private/var/mobile/Containers/Data/Application/D28B8376-8B3F-4F76-9220-DF842CCCC640/tmp/StoreSource/IMG_1358.JPG".

but the content seems like changed my URL.
Here is the content:
{
    ops =     (
                {
            retain = 1;
        },
                {
            insert =             {
                image = "//:0";
            };
        },
                {
            insert = "\n";
        }
    );
}

**Steps for Reproduction**

1.  Step One
Load https://quilljs.com/standalone/full/ and restore Quill html, CSS, JS source code files into my sandbox's /tmp/StoreSource/ document.

2. Step Two
Load the html in this document. BaseURL I also set sandbox's /tmp/StoreSource/. So that webView can access files in sandbox's /tmp/StoreSource/.
[_webView loadHTMLString:htmlString baseURL:baseURL];
BaseURL I also set sandbox's /tmp/StoreSource/. So that webView can access files in sandbox's /tmp/StoreSource/.
3. Step Three
[UIImageJPEGRepresentation(image,1) writeToFile:imagePath options:NSDataWritingAtomic error:&error];
imagePath is an Image in sandbox's /tmp/StoreSource/.

4. Step Four
NSString *jsCode = [NSString stringWithFormat:@"quill.insertEmbed(3, 'image', '%@' ,Quill.sources.USER);",urlString];
[_webView evaluateJavaScript: jsCode completionHandler:^(id _Nullable obj, NSError * _Nullable error) {        
        if (error) {
            NSLog(@"%@",error);
        }
        else {
            NSLog(@"%@",obj);
        }                
}];

**Expected behavior**:
The Expected result should have been the Quill display the image on its own container. And obj in Step4 should have been logged like this:
ops =     (
                {
            retain = 1;
        },
                {
            insert =             {
                image = "/private/var/mobile/Containers/Data/Application/44C9D0FF-E028-434A-873B-2C53D164354E/tmp/StoreSource/IMG_1358.JPG"
            };
        },
                {
            insert = "\n";
        }
    );

**Actual behavior**:
But Quill display nothing. obj in Step4 logged like:
ops =     (
                {
            retain = 1;
        },
                {
            insert =             {
                image = "//:0";
            };
        },
                {
            insert = "\n";
        }
    );

**Platforms**:
iOS 10.10.2      iPhone6    WKWebView

**Version**:
I don't know what the version I used. I loaded https://quilljs.com/standalone/full/ and saved html css & JS files and then loaded them in local. These tags may contains the info of Quill version.
<script src="//cdn.quilljs.com/1.3.5/quill.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/monokai-sublime.min.css">
<link rel="stylesheet" href="//cdn.quilljs.com/1.3.5/quill.snow.css">

**Comment by liulinbo** [comment]
`static match(url) {
    return /\.(jpe?g|gif|png)$/.test(url) || /^data:image\/.+;base64/.test(url);
  }

  static sanitize(url) {
    return sanitize(url, ['http', 'https', 'data']) ? url : '//:0';
  }`

it likes not support "file://" type

**Comment by mokai** [comment]
Can I open as `Image.PROTOCOL_WHITELIST`?

**Comment by arcelan** [comment]
try below
```
const Image = Quill.import('formats/image')
Image.sanitize = function (url) { return url }
```
