### ISSUE TITLE
how can i move cursor after image

### ISSUE THREAD

**Issue by codercoin** [quilljs/quill#1929]
i use quill on uiwebview
i insert image by use quill.insertEmbed(currentSelection.index, 'image', url);
but the cursor is still before image, how can i move cursor after image？or move cursor to the next line after image?

**Comment by benbro** [comment]
Please include all the info requested in the issue template.

Did you check latest release.
This is probably fixed:
https://github.com/quilljs/quill/commit/a30b2e1aa011075150514737922cc8935104bb72

**Comment by daniuwo** [comment]
> i use quill on uiwebview
> i insert image by use quill.insertEmbed(currentSelection.index, 'image', url);
> but the cursor is still before image, how can i move cursor after image？or move cursor to the next line after image?

Have you solved it
