### ISSUE TITLE
Replacing indentation classes with inline styles -- RTL support

### ISSUE THREAD

**Issue by tegola** [quilljs/quill#1930]
I'm trying to rewrite the indentation attributor to to use styles instead of classes, i.e. `style="margin-left: 2em"` instead of `class="ql-indent-1"`.

This is what I've come up with:

```javascript
import Parchment from 'parchment';

const levels = [1, 2, 3, 4, 5];
const multiplier = 2;

class IndentAttributor extends Parchment.Attributor.Style {
	add(node, value) {
		return super.add(node, `${value * multiplier}em`);
	}

	value(node) {
		return parseFloat(super.value(node)) / multiplier || undefined; // Don't return NaN
	}
}

const IndentStyle = new IndentAttributor('indent', 'margin-left', {
	scope: Parchment.Scope.BLOCK,
	whitelist: levels.map(value => `${value * multiplier}em`)
});

export default IndentStyle;
```

This is working nicely, but I need to support right text alignment, and so I need to switch `margin-left` with `margin-right` when the current line is right aligned or when the line `direction` attribute is 'rtl`.

How can I do it?

**Comment by dynothunder** [comment]
where I use these code in angular2

**Comment by WxSwen** [comment]
> I'm trying to rewrite the indentation attributor to to use styles instead of classes, i.e. `style="margin-left: 2em"` instead of `class="ql-indent-1"`.
> 
> This is what I've come up with:
> 
> ```js
> import Parchment from 'parchment';
> 
> const levels = [1, 2, 3, 4, 5];
> const multiplier = 2;
> 
> class IndentAttributor extends Parchment.Attributor.Style {
> 	add(node, value) {
> 		return super.add(node, `${value * multiplier}em`);
> 	}
> 
> 	value(node) {
> 		return parseFloat(super.value(node)) / multiplier || undefined; // Don't return NaN
> 	}
> }
> 
> const IndentStyle = new IndentAttributor('indent', 'margin-left', {
> 	scope: Parchment.Scope.BLOCK,
> 	whitelist: levels.map(value => `${value * multiplier}em`)
> });
> 
> export default IndentStyle;
> ```
> 
> This is working nicely, but I need to support right text alignment, and so I need to switch `margin-left` with `margin-right` when the current line is right aligned or when the line `direction` attribute is 'rtl`.
> 
> How can I do it?

why i copy your code and then occur this error: Uncaught TypeError: BlotClass.create is not a function?

**Comment by danielmhair** [comment]
I made this same `IndentAttributor` and am receiving the same `BlotClass.create` is not a function. https://github.com/quilljs/quill/issues/2351#issuecomment-433495029

**Comment by nancyvgb** [comment]
Wow, I spend like two days looking for this solution in angular! It works !! Thanks!

**Comment by nancyvgb** [comment]
> For angular 2+:
> 
> Create file quill.d.ts: (you can try using `@types/quill` module, but it doesn't work for me because getting some error)
> `declare module 'quill';`
> 
> Add import in your component:
> `import * as Quill from 'quill';`
> 
> Add class:
> 
> ```
> class IndentAttributor extends Quill.import('parchment').Attributor.Style {
>   multiplier = 2;
> 
>   constructor(name: string, style: string, params: any) {
>     super(name, style, params);
>   }
> 
>   add(node, value) {
>     return super.add(node, `${value * this.multiplier}rem`);
>   }
> 
>   value(node) {
>     return parseFloat(super.value(node)) / this.multiplier || undefined;
>   }
> }
> ```
> Add function in your component:
> 
> ```
>   createCustomIndent(): void {
>     const levels = [1, 2, 3, 4, 5];
>     const multiplier = 2;
>     const indentStyle = new IndentAttributor('indent', 'margin-left', {
>       scope: Quill.import('parchment').Scope.BLOCK,
>       whitelist: levels.map(value => `${value * multiplier}rem`),
>     });
> 
>     Quill.register(indentStyle);
>   }
> ```
> And run it in constructor for example:
> 
> ```
>   constructor() {
>     this.createCustomIndent();
>   }
> ```

Wow I spend like two days looking for this solution, Thanks!!!

**Comment by issamalshamaly** [comment]
Hello guys,
I did some workaround on it, and it's worked for rtl and ltr, I added event listener on .ql-direction when the editor created

`    editorCreated(quill) {
        const toolbar = quill.getModule('toolbar');
        toolbar.addHandler('image', this.imageHandler.bind(this));
        this.quillEditor = quill;
        this.changeQuillDirection();
        //////////////
        document.querySelector('.ql-direction').addEventListener('click', (e) => {
          this.createCustomIndent();
        })
      ////////////
      }`

and I modified this function:

`
    createCustomIndent(): void {
        const levels = [1, 2, 3, 4, 5];
        const multiplier = 2;
        let indentStyle;
        if(document.querySelector('.ql-direction.ql-active')){
            indentStyle  = new IndentAttributor('indent', 'margin-right', {
                scope: Quill.import('parchment').Scope.BLOCK,
                whitelist: levels.map(value => `${value * multiplier}rem`),
              }); 
        }else{
            indentStyle = new IndentAttributor('indent', 'margin-left', {
                scope: Quill.import('parchment').Scope.BLOCK,
                whitelist: levels.map(value => `${value * multiplier}rem`),
            });
        }

        Quill.register(indentStyle);
      }`

so .ql-direction button has class ql-active only if the direction was rtl and in this case I will register margin-right not left.

Thank you

**Comment by tegola** [comment]
Unfortunately, your solutions does not apply to a class based instantiation like the original one (mine).

Thanks though, might help others.

**Comment by brandnpatterson** [comment]
You can do this by overriding the default `IndentClass`. Below is the default class from [indent.js](https://github.com/quilljs/quill/blob/develop/formats/indent.js) with inline styles added as a side effect. Using margin works for email

```javascript
class IdentAttributor extends Parchment.Attributor.Class {
    add(node, value) {
        if (value === '+1' || value === '-1') {
            let indent = this.value(node) || 0;
            value = value === '+1' ? indent + 1 : indent - 1;
        }
        
        // list of styles added by .ql-indent
        const indentList = [
            '4.5em',
            '7.5em',
            '10.5em',
            '13.5em',
            '16.5em',
            '19.5em',
            '22.5em',
            '25.5em',
        ];
       
        // remove padding from element
        node.style.paddingLeft = 0;

        if (value === 0) {
            // remove margin when element no longer has .ql-indent
            node.style.marginLeft = 0;

            this.remove(node);
            return true;
        } else {
            // add margin to element
            node.style.marginLeft = indentList[value - 1];

            return super.add(node, value);
        }
    }

    canAdd(node, value) {
        return super.canAdd(node, value) || super.canAdd(node, parseInt(value));
    }

    value(node) {
        return parseInt(super.value(node)) || undefined; // Don't return NaN
    }
}

let IndentClass = new IdentAttributor('indent', 'ql-indent', {
    scope: Parchment.Scope.BLOCK,
    whitelist: [1, 2, 3, 4, 5, 6, 7, 8],
});

Quill.register(IndentClass, true);
```
