### ISSUE TITLE
Add link to image, when click, does not work.

### ISSUE THREAD

**Issue by ethanzhoujie** [quilljs/quill#1931]
**Steps for Reproduction**

1. Add an image to quill.
2. Add a link to the image.

**Expected behavior**:
When I click the image,  should directive to google.com or pop up link information.

**Actual behavior**:

No reaction. But when I click the right space of image instead of image, it could pop up link information

**Platforms**:

Chrome 63, win7

**Version**:
In my project, I use v1.1.6. Problem exists.
And also, I use your playground. Problem exists.

Please see https://codepen.io/ethanzhou/pen/MrRGZM

**Comment by ethanzhoujie** [comment]
It seems I can't save a codepen with an image, please flow the steps to produce it. Thanks.

**Comment by FranckFreiburger** [comment]
@ethanzhoujie, have you solved this issue on your side ? any workaround ?

**Comment by Hamdan85** [comment]
same here!

**Comment by ethanzhoujie** [comment]
> @ethanzhoujie, have you solved this issue on your side ? any workaround ?

Not solved
