### ISSUE TITLE
There is  an error in "Cloning Medium with Parchment" guide.

### ISSUE THREAD

**Issue by mrold** [quilljs/quill#1932]
I follow the step  in the guide, and tried to create a 'Divider' format.
```
$('#divider-button').click(function() {
  let range = quill.getSelection(true);
  quill.insertText(range.index, '\n', Quill.sources.USER);
  quill.insertEmbed(range.index + 1, 'divider', true, Quill.sources.USER);
  quill.setSelection(range.index + 2, Quill.sources.SILENT);
});
```
But, the editor just inserted a string 'n'.
So I update my code  from `\n` to `\\n`, and then it works.
```
 quill.insertText(range.index, '\\n', Quill.sources.USER);
```
Excuse my bad English.

I install quill by `script` tag, not webpack or something.

**Comment by jhchen** [comment]
The guide is accompanied by a minimal live Codepen demo and it works without issue. Just reading the Javascript it make no sense that `\\n` would be correct and not `\n`. This likely means there is something misstep in following the guide. If you do not believe this to be the case please post a minimal example (on Codepen or JSFiddle) demonstrating this claim.
