### ISSUE TITLE
Custom font changes back to default font after enter key is clicked

### ISSUE THREAD

**Issue by ghost** [quilljs/quill#1933]
Please see the example provided by "quilljs.com":
[https://codepen.io/quill/pen/gLBYam](https://codepen.io/quill/pen/gLBYam)

When I select "mirza" and type some text and click enter, the selected option in drop down turns back to "ArefRuqaa" (it should stay as mirza). 

Can you suggest a work around if this is the intended behavior or will not be resolved in the near future..

Thanks

**Comment by jadams760** [comment]
@dalsword I am running into this issue as well. Were you able to find a solution?

**Comment by dalsword** [comment]
@jadams760 

Nope. Evaluating other alternatives : 

https://textbox.io/
https://summernote.org/
https://www.tinymce.com/
https://ckeditor.com/
