### ISSUE TITLE
Subscript/Superscript formatting lost when pasting

### ISSUE THREAD

**Issue by nick4501** [quilljs/quill#1935]
Copying and pasting subscript and superscript text causes the formatting to be lost.

**Steps for Reproduction**

1. Visit https://quilljs.com/docs/formats/
2. Enter two random bits of text and make one subscript and the other superscript.
3. Copy the selection into your clipboard, then delete the text and paste from your clipboard.

**Expected behavior**: Formatting for both subscript and superscript is maintained during copy/paste.

**Actual behavior**: Formatting is lost and the text is pasted without subscript/superscript styling.

**Platforms**: This only seems to be apparent in Chrome (tested on v63), and only when copying FROM a Chrome instance of Quill - copying from an instance of Quill in a different browser (or even from an external source, e.g. Microsoft Word) works fine when pasted INTO Chrome.

**Version**: 1.3.5

**Comment by nick4501** [comment]
After further investigation, this is actually a bug in Chrome, not specifically with Quill.  Closing and raising with the Chrome team.

**Comment by anthonyto** [comment]
@nick4501 Were you ever able to resolve this issue with Chrome?

**Comment by nick4501** [comment]
> @nick4501 Were you ever able to resolve this issue with Chrome?

No - as far as I'm aware, this is still an issue.  We just accepted it as a known limitation.
