### ISSUE TITLE
can't get programmatic syntax highlighting to work reliably

### ISSUE THREAD

**Issue by starpit** [quilljs/quill#1937]
i am trying to create a quill, insert some javascript code, and then have it displayed with syntax highlighting. i've tried quill.setText() followed by quill.formatText with 'code-block': true, and a few other things. nothing seems to work reliably.

if i add a 'code-block' toolbar entry, then things work as expected. but i need to be able to do this programmatically.

**Steps for Reproduction**

1. Visit https://codepen.io/starpitter/pen/MQYXVQ
2. Observe that there is no syntax highlighting
3. click on Variant 2
4. observe that there is now syntax highlighting
5. click on Variant 1, 3 or 4  (1 is the default)
6. observe that there is no syntax highlighting

calling setText(txt) seems to be at odds with the syntax highlighter. also, if you look at the `var3` variant, and how it differs from `var2`... i don't understand what's going on. it took me many iterations to find the right balancing act to get syntax highlighting to work

**Expected behavior**:

the code block receives syntax highlighting

**Actual behavior**:

it does not, unless the API is called in a very specific way

**Platforms**:

Include browser, operating system and respective versions

**Version**:

1.3.5

Run `Quill.version` to find out

**Comment by jhchen** [comment]
`code-block` is a block level format similar to text-align. Block level format behavior is described in https://quilljs.com/docs/api/#formattext.

**Comment by starpit** [comment]
I've switched to something else, but I think it'd be valuable to your users to document why variant 2 works, but variant 3 does not. Your linked documentation doesn't explain this to me.

**Comment by jhchen** [comment]
From the docs: "For line level formats, such as text alignment, target the newline character or use the formatLine helper."
