### ISSUE TITLE
NPM package bundles Parchment and quill-delta but also depends on them in package.json

### ISSUE THREAD

**Issue by kayahr** [quilljs/quill#1941]
When installing Quill with `npm install quill` then `parchment` and `quill-delta` are installed as separate dependencies but are not used by Quill because Quill contains a bundled copy of the two libraries.

This duplication is confusing because a developer intuitively imports the `parchment` module with `require` or ES6 imports to write custom attributors for example. But this can't work and ends in an error like `BlotClass.create is not a function` because wrong classes are passed around. So the libraries must be imported through Quill instead (With `Quill.import("parchment")` and `Quill.import("delta")`). Especially when using TypeScript this is annoying because Parchment itself is perfectly typed but when importing it through Quill then no type information is present.

It would be nice if this could be cleaned up somehow. Maybe you could ignore `parchment` and `quill-delta` in Webpack so these two libs are referenced as external dependencies? If that's not possible then it would be nice if you could at least reference the libs as dev-dependencies so they are not installed together with Quill.

I haven't checked the other dependencies (`clone`, `deep-equal`, `eventemitter3` and `extend`). When these libs are also bundled into `dist/quill.js` then this could be cleaned up as well by excluding them from the bundle or marking them as dev dependencies.

**Version**: 1.3.5

**Comment by jhchen** [comment]
What is your suggested solution? Agree the drawbacks of the current approach are there but an alternative with both its pros and cons need to be compared, not just the pros and ignoring the cons or else we may be taking a step backwards.

**Comment by kayahr** [comment]
My suggested solution is doing it right and that means: Don't bundle any external libs into your lib. Creating a self-contained bundle is fine for classic web programming where people just add a script tag referencing the bundle and that's it. That's the advantage of your current approach and that would be fine for a library which can be simply downloaded from your website. 

But you uploaded this bundle to the NPM registry and there it doesn't fit so well. In the NPM world modules don't bundle other modules, they depend on external modules. The top-level application, which uses Quill in the end, is responsible for creating a distribution bundle (With tools like Webpack) and publishing it to a webserver or even an offline application using Electron. But Quill is already bundled and this means the application bundles a bundle together with other libs which may already be in the Quill bundle.

For small libs like clone or extend this isn't really a problem. The bundle gets a little bit larger because the libs may end up twice in the bundle but technically they are separated so this simply works. 

But for Parchment this is a different story. If the application is already using Parchment for example then it can't inter-operate with Quill because quill bundles its own copy and the classes are not compatible. Workaround: Application must not import Parchment itself but must import it through Quill. For TypeScript this means loosing the type information. Currently I use this workaround and wrote a nasty hack where I import the external parchment lib just for the type information, import the real parchment through Quill and then cast both together and re-export the result so I have a typed and Quill-compatible Parchment in the end. That's really ugly and this can only be fixed by not bundling parchment into Quill.

So you want a list of pros and cons, here it comes:

**Solution 1 (The real one):**

Create two different bundles. A self-contained bundle (the current one) for classic web programming and one bundle which just contains the Quill code and `require`s  the other libraries as normal external NPM dependencies. This second bundle must be the one referenced as `main` in `package.json`. This second bundle don't have to be a bundle at all. Maybe it would be enough to transpile all your ES6 files to ES5 and then reference the quill.js entry point as  `main` in `package.json`. That is what I do in my projects. Source is TypeScript in `src`, the TypeScript compiler transpiles everything to ES5 into a `lib` folder, this `lib` folder is then used by Node. For web publishing I use webpack to create a a self-contained bundle in the `dist` folder.

Pros:

* Still allows people to simply include the self-contained bundle because it is still there.
* Allows applications to import the Parchment module itself and inter-operate with Quill without problems. Both libraries (parchment and quill) are simply loaded with `require` and can work together as expected.
* Makes applications smaller by eliminating duplicate imports if application already uses stuff like eventemitter3, deep-equal and so on.

Cons:

* I don't see any disadvantage except maybe some significant amount of work. I don't know the Quill internals good enough to make any estimations here.


**Solution 2 (The easy one)**

Simply move all the dependencies which you bundle into Quill from the `dependencies` section into the `devDependencies` section.

Pros:

* For applications which only use Quill and none of the other libraries this means that `npm install quill` just installs Quill and nothing else.
* By not installing a separate unused parchment module developers may not accidentally use it and run into problems.  That's what happened to me and [this guy](https://stackoverflow.com/questions/41207637/whats-the-correct-way-of-defining-style-attributes-in-quill-parchment) and also [this guy](https://stackoverflow.com/questions/44709030/receiving-the-error-blotclass-create-is-not-a-function-in-reactquill).

Cons:

* None. But it is still not possible to use the parchment module from the NPM registry together with Quill.

Sooo... What about using both solutions? I'm pretty sure solution 2 has no negative impact and you just need to move some lines in `package.json`. This could be a short-term improvement. Maybe solution 1  can be kept in mind for some future mayor release if it is too complicated to do with the current architecture.

**Comment by jhchen** [comment]
You don't need to spend four paragraphs rehashing what you already said in the original comment...

Solution 2 seems to pretty much breaks Quill for the average user? If a casual user just came along added Quill as a dependency in their app, and did `import Quill from 'quill';` it will no longer just work. They will also have to be aware of Parchment, etc and add those as dependencies too.

**Comment by kayahr** [comment]
Solution 2 doesn't break anything. Your bundle already contains parchment and quill-delta (and most likely all the other runtime dependencies as well, haven't checked them explicitly) so there is no need to install a second copy of it. As I explained (two times) it is even wrong to import the external parchment module which is automatically (and unnecessarily) installed by `npm install quill` because we have to import the bundled parchment with `Quill.import()`.

**Comment by jhchen** [comment]
`Quill.import()` was added so people in just the browser environment can get access to Parchment and Delta. You do not have to use it in a build environment. I wrote a [guide](https://quilljs.com/guides/adding-quill-to-your-build-pipeline/) for properly adding Quill to the build with an example [repo](https://github.com/quilljs/webpack-example/).

Parchment is truly a library dependency regardless of how the build shakes out it should still be listed in npmjs.com as a dependency. If there is a reference that NPM has put out that supports your claim please link that.

**Comment by kayahr** [comment]
Ah, so you say that in a Node environment it is wrong to use `require("quill")` and instead I have to use `require("quill/core")` (And more requires for the stuff I need)? Well that would be fine if these files would not use ES6 imports which Node doesn't support yet. So you say I'm responsible for transpiling the quill code to ES5 in my own build system? That approach is quite unusual. It's like publishing TypeScript code in a NPM module and telling the user he has to compile it himself. Not all projects have a custom build system where Babel can be plugged in. Or even no build system at all (Like your quill-delta project).

But actually that's good news for solution 1 which doesn't seem so difficult any longer. I think all problems could be solved by splitting the build process into two steps. One which does the transpilation to ES5 and the second which creates the bundle. So what about this suggestion:

1. Move the ES6 source files into a src folder.
2. First build step uses Babel to transpile the stuff from the src folder to the root folder. The files there can now be required in a Node environment directly without dictating specific build steps.
3. Second build step uses Webpack to pack the transpiled files into dist/quill.js for web environment. 
4. Remove the main entry from package.json so people don't accidentally load the web bundle in a Node environment.

**Comment by jhchen** [comment]
> so you say that in a Node environment it is wrong to use require("quill") and instead I have to use require("quill/core") (And more requires for the stuff I need)

Where did I say that?

**Comment by kayahr** [comment]
In the guide you mentioned. As shown in the [example](https://quilljs.com/guides/adding-quill-to-your-build-pipeline/#entry).

So again (Sorry, if I repeat myself again and again, but looks like we misunderstand each other, maybe it's because of my bad english):

* Doing `require("quill")` in Node environment imports the web bundle which already includes its own copy of parchment so the external parchment module which is also installed by `npm install quill` can't be used.
* Doing `require("quill/core")` (or `require("quill/quill")` when I'm fine with the defaults) in Node environment works because in this way the external parchment module is used. So this approach is better for Node environment but unfortunately dictates using a special build workflow because of the ES6 imports, which are not directly supported by Node. 

This could be solved by doing this necessary transpilation in the build process of quill so the published NPM module already contains the transpiled JavaScript files instead of the ES6 source files.

**Comment by jhchen** [comment]
There is a difference between you have to do and you can do. The example is an example of what you can do, which is one of many options.

I do have a difficult time understanding you because half of the claims made I do not believe is true, for example what I just pointed out, so it makes me not optimistic we can have a discussion that will lead to a solution.

Either way your concern is noted and well documented in this Issue and I will take another look when I have time and come up with my own solution.

**Comment by kayahr** [comment]
And which claims I made are the ones you don't believe to be true? My claims are pretty much summarized by the two bullet points in my previous comment. Which claim is false and why? Anything else is just me trying to suggest a solution to improve the current situation. And its totally clear that it is your decision IF and HOW to do it.
