### ISSUE TITLE
Empty lines can't be styled

### ISSUE THREAD

**Issue by kayahr** [quilljs/quill#1942]
Looks like it is currently not possible to configure the font-size of an empty line and therefore the height of empty lines always depends on the fixed font-size of the container. To workaround this issue the user has to enter a space character in each empty line.

Would it be possible to change the HTML output of Quill so the `<br>` tag in empty lines is always wrapped with a `<span>`? I did this manually by manipulating the DOM and after adding this span element I was able to change the font size of the empty line and the style also appeared correctly in the delta. So on first glance it looks like this could work.

**Steps for Reproduction**

1. Visit quilljs.com and go to the third (right-most) demo which has a combobox for the font size.
2. Clear the document (Ctrl-A, Del)
3. Enter some text for line 1, press Enter multiple times to add empty lines and enter another text for the last line.
4. Select all text (Ctrl-A)
5. Set the font size to huge.

**Expected behavior**:

All lines should be styled with font size huge.

**Actual behavior**:

Only the non-empty lines are styled. The empty lines are not styled and stay at default font size and therefore have a fixed height.

**Platforms**:

Firefox 58.0.1 and Chrome 63.0.3239.132 on Debian Linux 9.3

**Version**: 1.3.5

**Comment by jhchen** [comment]
No unfortunately this is not a feature / a limitation of Quill at the moment. #943

**Comment by kayahr** [comment]
This other task is about the line height of non-empty lines. And I can't even reproduce this problem explained there. The line height is correctly getting smaller when a small font is used.

My problem is the font size style on empty lines (or any other inline style. The font size is simply just the only one which can make a visual difference for empty lines). Because an empty line just contains a `<br>` tag and no `<span>` this empty line can't be styled. Formatting an empty line simply does nothing and the Delta just contains an `insert: '\n'` property without attributes. But when there is a `<span><br></span>` in the line instead then it can be formatted and the attributes are even appearing in the Delta so I have some hope that this can be easily fixed somehow.

So if this is really not possible at the moment then I'm fine with it. Just wanted to make sure that my problem was correctly understood because I don't see any similarity to #943.

**Comment by jhchen** [comment]
You are right that is a different issue. However styling empty lines with inline formatting is still not supported in Quill so this is not a bug. If you would like to make a feature request please take a look at https://github.com/quilljs/quill/blob/master/.github/CONTRIBUTING.md#feature-requests and file another issue.
