### ISSUE TITLE
Quill links are relative by default. How to make them absolute?

### ISSUE THREAD

**Issue by usmanl** [quilljs/quill#1946]
When the links added in the quill editor are displayed on the page, they are relative by default.
How can we make the links absolute?

**Comment by tmtron** [comment]
When the url contains the protocol `http://` or `https://` it will be an absolute link.

When you want to change the default to absolute, I think you could change the [link blot](https://github.com/quilljs/quill/blob/develop/formats/link.js): see this [StackOverflow answer](https://stackoverflow.com/a/52275503/1041641)

**Comment by luin** [comment]
Closing as this is answered. Feel free to reopen if the issue persists.
