### ISSUE TITLE
Problems with creating links in Chrome

### ISSUE THREAD

**Issue by mik01aj** [quilljs/quill#195]
Observed in Chrome 36 and 38 (Mac):
https://www.dropbox.com/s/6ulwutarhlgi5pg/Quill%20link%20bug.mov

![screenshot 2014-08-13 12 41 38](https://cloud.githubusercontent.com/assets/3027415/3904223/6d26dc9c-22d6-11e4-8f69-45704cfb7730.png)

**Comment by steviesama** [comment]
This is happening to me to on quilljs.com front page as well.

**Comment by jhchen** [comment]
Can you provide more details @steviesama? I can't reproduce the issue on Chrome 43 on my Mac.

**Comment by steviesama** [comment]
@jhchen There's really only a couple of possibly characterizing details I could offer. First, if you goto the quilljs.com front page using that demo, if you select any text anywhere inside the document, clicking bold, or the link icon, will deselect whatever you had and move the cursor to just after "Quill Rich Text Editor". I thought maybe one of my extensions was causing it so I disabled them all. For a moment after I disabled them, it let me bold and link something, but at some undetermined short amount of time after, it resumed the same behavior, with the extensions still off.

**Comment by steviesama** [comment]
@jhchen I went back and tried all the other formatting controls, and they all have that same behavior. I feel like something is interfering with it, but I haven't a clue what.

**Comment by jhchen** [comment]
What browser and version and OS are you using and do you see any errors in the console with all extensions disabled?

**Comment by steviesama** [comment]
@jhchen Chrome Version 43.0.2357.130 m, Windows 8.1, and no errors in console. Just the welcome to quilljs message.

**Comment by furcino** [comment]
Hello, I have the sae problem as described by steviesama. Chrome Version 50.0.2661.102 m and windows 10.

**Comment by jhchen** [comment]
If this is occurring in the 1.0 beta please create a new issue following the [new issue guidelines](https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#bug-reports). Linking to this issue will not be a sufficient description.
