### ISSUE TITLE
Question: Turn off delta computation for perf gains?

### ISSUE THREAD

**Issue by Aaronik** [quilljs/quill#1952]
Hello,

Long story short, I've been having big performance problems with long documents with large numbers of delta operations.

I've tried many, many things, and am not looking for a generalized performance solution with this question as I've asked that before and scoured the web for answers theoreof.

I have one simple question that would allow me to speed things up a bunch. _Can I turn off delta computation altogether?_ I would just save HTML. I believe Quill not having to compute delta information may supply the perf increases I need.

**Comment by DmitrySkripkin** [comment]
That's make no sense, delta is core format for storing data in quill.
Don't if it can help you. But
```
quill.setContents(<big delta>);
quill.setContents(<another big delta>);
```
is much more slower then:
```
quill.setContents(<big delta>);
quill.setContents([]);
quill.setContents(<another big delta>);
```
Can you provide some example or just describe what methods or operations are executed when you see performance problems.

**Comment by Aaronik** [comment]
Yes, I've seen this answer before, and specifically asked against a generalized performance solution to avoid polluting this thread with answers that are irrelevant to the question.

I have a document with a long delta, and every time the user types, the delta has to get recomputed. For my use case, this is unnecessary.

Your answer insinuates "no", but it's not clear you're answering my actual question.

**Comment by benbro** [comment]
Quill uses Delta to represent the document.
