### ISSUE TITLE
Bug: starting to write in RTL doesn't auto-align to right

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [quilljs/quill#1955]
1. Visit quilljs.com
2. Start typing RTL language characters (Hebrew for example) in an empty text, 

**Expected behavior**:
Should auto-align to the right

**Actual behavior**:
Stays on left.

**Platforms**:
Chrome 64.0.3282.137 on Android 8.1

**Version**:
No idea how to get it.

See attached video:
[device-2018-02-12-171806.zip](https://github.com/quilljs/quill/files/1716772/device-2018-02-12-171806.zip)

**Comment by miladmeidanshahi** [comment]
same issue
