### ISSUE TITLE
Bug: putting image from camera doesn't put it in correct orientation

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [quilljs/quill#1957]
**Steps for Reproduction**

1. Visit quilljs.com
2. choose to add a photo from camera
3. take photo from camera

**Expected behavior**:
Should look fine

**Actual behavior**:
Has bad orientation for the photo.

**Platforms**:
Chrome 64.0.3282.137 on Android 8.1

**Version**:
No idea how to get it.

See attached video:
[device-2018-02-12-172707.zip](https://github.com/quilljs/quill/files/1716807/device-2018-02-12-172707.zip)

**Comment by arathipanya** [comment]
It's about EXIF set by devices.
I had the same issue and fixed it with a custom handler for image (https://github.com/manoj-makkuboy/fix-image-rotation helped a lot) : 

`
import loadImage from 'blueimp-load-image';

function fixRotationOfFile(file) {
  return new Promise((resolve) => {
    loadImage(file, (img) => {
      resolve(img.toDataURL('image/jpeg'));
    }, { orientation: true });
  });
}

function ImageHandler() {
  const quill = // your quill editor
  const input = document.createElement('input');
  input.setAttribute('type', 'file');
  input.setAttribute('accept', 'image/*');
  input.click();
  input.onchange = () => {
    const file = input.files[0];
    if (/^image\//.test(file.type)) {
      const range = quill.getSelection();
      fixRotationOfFile(file).then((img) => {
        quill.insertEmbed(range.index, 'image', img);
        quill.setSelection(range.index + 1);
      });
    }
  };
}`
