### ISSUE TITLE
Request: allow to put audio 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [quilljs/quill#1958]
Currently it allows to put videos and images, but I don't see audio.

Please add audio too.

**Comment by cryolynx** [comment]
You can add audio by implementing an audio handler function as a slightly modified version of the image handler in the [base theme](https://github.com/quilljs/quill/blob/develop/themes/base.js) (just change the accepted MIME types), and creating a new format similar to the [video format](https://github.com/quilljs/quill/blob/develop/formats/video.js).

You can then add the audio handler to your Quill config object and register the audio format.
```javascript

const audioHandler = function() {
  // ...
};

class Audio extends BlockEmbed {
  // ...
};

Audio.blotName = 'audio';
Audio.tagName = 'DIV';  // you can use other elements

const options = {
  // ...
  modules: {
    toolbar: {
      // ...
      handlers: {
        audio: audioHandler,
      },
    },
  },
  formats: [
    // ...
    'audio',
  ],
};

Quill.register(Audio);

const quill = new Quill('#editor', options);
```

**Comment by AndroidDeveloperLB** [comment]
OK.
Say, do you have a port to Android ?
