### ISSUE TITLE
IE 11: Placeholder text bug on focus

### ISSUE THREAD

**Issue by kandyba** [quilljs/quill#1962]
I'm having trouble with the Placeholder in IE 11.
I'm using it with the Primeng (Angular5 components) [](https://www.primefaces.org/primeng/#/editor) which is rich text editor component based on Quill.
**Please have a look at my video**:
https://www.screencast.com/t/ch3MaozO

**Expected behavior**: Placeholder should have the same behaviour as it has in chrome, ff and safari 

**Actual behavior**: The Placeholder in IE can be clicked without _cursor: move;_ and _cursor: resize;_ and resizing of existed text inside of editor

**Platforms**: Windows 10, Windows 7
**Version**:  IE 11

**Comment by benbro** [comment]
IE11 not supported.
