### ISSUE TITLE
Toolbar DIV ID and contents in JavaScript?

### ISSUE THREAD

**Issue by johnnymaxwell** [quilljs/quill#1963]
Thank you for open sourcing Quill and the detailed response for my original question
  Placing Toolbar into existing DIV - Possible Approach    https://github.com/quilljs/quill/issues/1949

The reason I suggested a 'containerDiv' option is that I was specifying the toolbar's contents in JavaScript

```    this.quill = new Quill('#editor', {
        modules: {
          'toolbar': {
        	containerDiv: 'quillToolbar',
	        container: [
	            [{ 'font': this.font.fontNames}, { 'size': this.fontSize.whitelist }], . . .
```
and not in the HTML

```<div id="toolbar">
   <div class="ql-toolbar ql-snow">
      <span class="ql-formats">
         <select class="ql-size"> . . .
```

I understand the latter was what you kindly suggested in 1949.
 "In the toolbar container make sure your HTML syntax is built correctly" with JavaScript like,
```
  modules: {
    toolbar: '#toolbar'     // Equivalent to { toolbar: { container: '#toolbar' }}
  }
```
I'm looking for a bit more control over things via JavaScript. I did not see a way in JavaScript to specify both the toolbar container DIV and the toolbar contents. Maybe I am just missing something here?
Thank you in advance.

**Comment by ighea** [comment]
Until there is a better solution I simply moved the toolbar which contents were created using JS to another container:
```javascript
anotherContainer.appendChild(quill.theme.modules.toolbar.container);
```
