### ISSUE TITLE
Adjusting behavior of an Embed's DOM element

### ISSUE THREAD

**Issue by johnnymaxwell** [quilljs/quill#1964]
It seems that the node within an Embed's constructor that gets its innerHtml set
```
class WhateverObject extends Embed {
    static create(myObj) {
        let node = super.create(myObj);
        node.innerHTML = "hello";
        return node
       }; 
```
is not yet in the DOM tree (parent is null). I would like to do some things with that
node once it is in the DOM. Currently I have a setTimeout() to adjust things
```
class WhateverObject extends Embed {
    static create(myObj) {
        let node = super.create(myObj);
        node.innerHTML = "hello";
        setTimeout( function( ) {...}, 1000);
        return node
       }; 
```
Is there a better approach? I thought about doing something with text-changed or selection-changed event callbacks but that seemed like a bad alternative. Thank you for any thoughts.

**Comment by Charrondev** [comment]
If you're looking to do something DOM you'll need to do it after `attach()` is called (Where it actually get's insert into the DOM).

attach get's called at the of base Blot implementations `insertInto()` call https://github.com/quilljs/parchment/blob/master/src/blot/abstract/shadow.ts#L105

If it's not something that changes the length of the blot though (length never changes), then you'll want to do it inside of optimize(). If it does change the length or only needs to run once, overriding `insertInto()` and placing your code after the `super.insertInto()` call would make more sense.

I provide addition assistance though without knowing what you're trying to do exactly.
