### ISSUE TITLE
Links in bubble mode are not opened on click and their tooltip is hidden behind other elements.

### ISSUE THREAD

**Issue by devozerov** [quilljs/quill#1966]
Looks like "link" feature is unusable at the moment due to several critical usability issues - click on a link does nothing and tooltip with href field is hidden behind other elements and does not respect "bounds" property. To the contrast, tooltip during creation works fine because at first basic tooltip is opened (correct stacking context and correct behavior of "border") and when link button is clicked basic tooltip is replaced with link tooltip.

Both issues should be very easy to fix. I am not JS professional, but I am likely to be able to fix it. Would appreciate if you point me on relevant code pieces where I could start. Having this issue at the heart of 

**Steps for Reproduction**

1. Open https://quilljs.com/standalone/bubble/
2. Type a word
3. Select that word, then click on a link button and add some hyperlynk
4. Hover a mouse pointer on the link and try clicking it

**Expected behavior**:
1. When link is clicked page is opened in a new window
2. Tooltip is visible

**Actual behavior**:
1. Chrome - pointer appears, but click on a link does nothing, other browser - no pointer, click does nothing
2. Tooltip is not visible

**Platforms**:
Windows 10, Chrome/Mozilla/IE (all latest)

**Version**:
1.3.5

**Comment by devozerov** [comment]
Another problem mentioned in another PRs - when pointer is clicked somewhere else, link is not saved. Proposed fix:
1) Remove current link tooltip 
2) Hovering a link should convert cursor to pointer
3) Click on a link does nothing because user typically doesn't want to navigate to the link in edit mode
4) Double click should make "ql-tooltip" visible and switch it to "ql-editing" mode right away showing current href
5) Ctrl+click on the link should navigate user to the link in a new window (Word-like behavior).

Thoughts?

**Comment by timothyallan** [comment]
The initial tooltip on the first line is cut off because of the overflow settings on `.ql-editor`. If you go down a line (or turn off the `overflow-y`) and repeat the same steps, you can see the tooltip.

**Comment by shyamal890** [comment]
+1

**Comment by lucsky** [comment]
@devozerov Here's a temporary hack that I am using to make links clickable, it's a short module which injects an event listener on the Quill container which disables the `contenteditable` property of `<a>` tags on mouseover (and re-enables it whenever another element is `mouseover`-ed).

```javascript
Quill.register('modules/clink', (quill) => {
    let currentLink = null;
    quill.container.addEventListener('mouseover', (evt) => {
        if (evt.target.tagName === 'A') {
            currentLink = evt.target;
            evt.target.setAttribute('contenteditable', false);
        } else if (currentLink) {
            currentLink.removeAttribute('contenteditable');
        }
    });
});

const quill = new Quill('#container', {
    modules: {
        clink: true,
    }
});
```

It does make it a bit harder to _remove_ links since simply clicking on them triggers the href, but it is still possible by selecting from the left or right boundary.

**Comment by AlesJiranek** [comment]
another possible approach is to override default link and add content editable attribute from beginning, not only on mouseover, because that will not work for touch devices 

```
const Link = Quill.import('formats/link');

class ClickableLink extends Link {
  public static create(value: string): ClickableLink {
    const node = super.create(value);
    node.setAttribute('href', Link.sanitize(value));
    node.setAttribute('target', '_blank');
    node.setAttribute('contenteditable', 'false');

    return node;
  }
}

Quill.register('formats/link', ClickableLink, true);
```

**Comment by cliftonlabrum** [comment]
@AlesJiranek I need links to work on iOS devices, so I'm trying to use your fix. I'm using Quill as raw JS in a web browser. Do you know how your `class` can be incorporated in a `<script>...</script>` environment?

**Comment by cliftonlabrum** [comment]
Shouldn't the link tooltip (popup) just be clickable somehow instead of the link itself? It looks like the popup is generated purely in CSS which is likely the problem. 

The **Snow** link functionality seems like it should also be used with **Bubble** since it provides link editing options and a separate `Visit URL:` link.

![image](https://user-images.githubusercontent.com/2513753/77206652-ad28a100-6ab4-11ea-85d7-a809ba753591.png)

**Comment by wooolfgang** [comment]
> Shouldn't the link tooltip (popup) just be clickable somehow instead of the link itself? It looks like the popup is generated purely in CSS which is likely the problem.
> 
> The **Snow** link functionality seems like it should also be used with **Bubble** since it provides link editing options and a separate `Visit URL:` link.
> 
> ![image](https://user-images.githubusercontent.com/2513753/77206652-ad28a100-6ab4-11ea-85d7-a809ba753591.png)

Agree, in terms of functionality the current link tooltip (for bubble) is pretty much useless. I'd argue that most people would rather have the snow link functionality as default for **both** snow and bubble themes.

**Comment by abdulsattar-docstack** [comment]
ASasASasASa[sSas]([ccccc](url)

**Comment by introvert** [comment]
Are there any news in regards to fixing this issue? @wooolfgang has a good point.

**Comment by VictorLeach96** [comment]
My solution to a clickable tooltip above the link.

```
Quill.register('modules/linkTooltip', (quill: any) => {
  quill.container.addEventListener('click', (evt: any) => {
    if (evt.target.tagName === 'A' && evt.offsetY < -5) {
      window.open(evt.target.href)?.focus()
    }
  })
})
```

**Comment by TivoSoho** [comment]
This is still very much an issue and none of the solutions above work anymore

**Comment by aimerie** [comment]
I couldn't agree with @TivoSoho more. What's the status on this??

**Comment by ajbraus** [comment]
I'm still having this issue. Anyone else?
