### ISSUE TITLE
Key listener for Tab doesn't work

### ISSUE THREAD

**Issue by moonpatroller** [quilljs/quill#1967]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

                    editor.keyboard.addBinding({
                        key: 'Tab'
                    }, function(range, context) {
                        console.log("HELLO");
                    });

**Expected behavior**:
That code doesn't print to the console.  Changing 'Tab' to 9 or '9' doesn't work.  It does work for other keys.

**Actual behavior**:
That code should print to the console.

**Platforms**:

Mac 10.13.3 (17D47) and Chrome Version 64.0.3282.167 (Official Build) (64-bit)

**Version**: 1.3.5

It appears as though a pre-existing handler runs first and prevents my handler from running.  Is there a way to put my handler first?

**Comment by moonpatroller** [comment]
This appears to work:

editor.keyboard.bindings[9].unshift({
                        key: 9,
                        handler: function(range) {
                            console.log('user hit tab');
                            return true;
                        }
                    });

**Comment by DmitrySkripkin** [comment]
> It appears as though a pre-existing handler runs first and prevents my handler from running. Is there a way to put my handler first?

Yes. You can overwrite the default binding, problem is you can't do with `addBinding()` but only with configuration just like this docs example: [Keyboard Module configuration](https://quilljs.com/docs/modules/keyboard/#configuration)

**Comment by moonpatroller** [comment]
@DmitrySkripkin When I use the example you pointed to it prevents the tab character from appearing in the quill editor or it prevents anything from happening at all, depending on whether I return true or not.  Is there a way to get the default behavior, where the tab appears in the editor, but my code also runs?

**Comment by DmitrySkripkin** [comment]
I dig a bit deeper. [Default tab handler](https://github.com/quilljs/quill/blob/develop/modules/keyboard.js#L193
) does not return anything. So even if you add a new binding it won't be executed anyway.

This means you have to rewrite it - basically copy/paste it or use method with `unshift() you mentioned above`.

P.S. Quill is not perfect, I would like to have more flexible bindings with some kind of weights to sort them.

**Comment by DanielKucal** [comment]
The problem is `key` has to be a number... It's even against type declared in `@types/quill`
