### ISSUE TITLE
align left button does not appear on toolbar

### ISSUE THREAD

**Issue by gileneusz** [quilljs/quill#1969]
**Steps for Reproduction**

writing custom editorOption such as below:
 editorOption: {
	modules: {
		toolbar: [
                    [{ 'align': 'left'}, {'align': 'center'}, {'align': 'right'}, {'align': 'justify'}]		        			
		 ],

**Expected behavior**:
all four align icons available

**Actual behavior**:
only align: center, right and justify available
align left option missing

**Comment by jhchen** [comment]
Please take a look at the font-size example in https://quilljs.com/docs/modules/toolbar/#container

**Comment by gileneusz** [comment]
I'm sorry but I want to have all buttons to choose on editor toolbar, not as a menu to choose. I tried:
[{ 'align': false}, {'align': 'center'}, {'align': 'right'}, {'align': 'justify'}]
with no luck again

**Comment by jhchen** [comment]
In that case `[{ 'align': null}, {'align': 'center'}, {'align': 'right'}, {'align': 'justify'}]` should work. Ex. https://codepen.io/anon/pen/JpeKbL

**Comment by gileneusz** [comment]
That's it! Thank you for help. My small suggestion - your documentation is great, but I was unable to find this configuration on toolbar section. Maybe it will be good idea to add this example to documentation

**Comment by jhchen** [comment]
What you tried `false` should have worked but I didn't have time then to dig in why `null` does but `false` did not till now. I'll reopen this as a small change to make in 2.0.

**Comment by AugustusZ** [comment]
In case any people need to have the dropdown for alignment, an empty string is for left alignment:

```
[{ 'align': ['', 'right', 'center']}],
```

![image](https://user-images.githubusercontent.com/8922602/40148978-cfad540c-5925-11e8-92e6-b8f81947220a.png)


https://codepen.io/AugustusZ/pen/mLzKmW

**Comment by mikepictor** [comment]
with respect....why is left represented by null? 
What if I want to explicitly align left (in an interface that is RTL)

The problem is that if the editor is RTL, picking left align doesn't do anything, since it's interpreting left as "no alignment", trusting that left is a default. Is there not a way to specify align left, and have it actually do an explicit text-align:left ?

**Comment by haoksam** [comment]
> with respect....why is left represented by null?
> What if I want to explicitly align left (in an interface that is RTL)
> 
> The problem is that if the editor is RTL, picking left align doesn't do anything, since it's interpreting left as "no alignment", trusting that left is a default. Is there not a way to specify align left, and have it actually do an explicit text-align:left ?

Worked for me:
In configuration:
```
var Align = Quill.import('attributors/style/align');
var Icons = Quill.import('ui/icons');
Icons.align['left'] = Icons.align['']; // set icon for 'left' option, otherwise it's replaced with 'undefined' text
Align.whitelist = ['left', 'center', 'right', 'justify']; // add explicit 'left' option
Quill.register(Align, true);
```

In toolbar:
`[{'align': ['left', 'center', 'right', 'justify']}]`

**Comment by NikitaDuritsyn** [comment]
For now, { 'align': null} removes the "text-align" CSS styles by press this button. But sometimes need to enforce the {text-align: start} style. Please answer this question. Is there such a possibility? If not, then it is worth adding omething like button { 'align': 'start'}, please)

**Comment by NikitaDuritsyn** [comment]
> What you tried `false` should have worked but I didn't have time then to dig in why `null` does but `false` did not till now. I'll reopen this as a small change to make in 2.0.

For now, { 'align': null} removes the "text-align" CSS styles by press this button. But sometimes need to enforce the {text-align: start} style. Please answer this question. Is there such a possibility? If not, then it is worth adding omething like button { 'align': 'start'}, please)

**Comment by BasudevKhati** [comment]
For the text align: 
👍= [{ align: '' }, { align: 'center' }, { align: 'right' }, { align: 'justify' }],
