### ISSUE TITLE
Line Spacing

### ISSUE THREAD

**Issue by leo-zhao** [quilljs/quill#197]
Does quill have customizable line spacing ability?

**Comment by ravidtanami** [comment]
it's not working for me:/

**Comment by jhchen** [comment]
It should now be:

```js
quill.theme.addStyles({
  'div': { 'line-height': '24px' }
});
```

**Comment by ravidtanami** [comment]
1. The html does change.. i would like to save my html and open it later..
    i tried:
    quill.theme.addStyles({
        'div': { 'line-height': '24px' }
    });
   var html = quill.getHTML();
   $('#myHtml').val(html);       // does not contains line-height

2. how can i change it? i would like to change the line-height

**Comment by jhchen** [comment]
This API does not change the editor's HTML

**Comment by Jiiun** [comment]
it seems like the latest version dose not exist the addStyle api. I can not setup the line height style.
![image](https://cloud.githubusercontent.com/assets/13991287/26612650/c334b8ec-45e8-11e7-8598-2642b97c1b52.png)

**Comment by benbro** [comment]
@Jiiun addStyle isn't required anymore. You can override the line-height or any other style with CSS.
```css
.ql-editor {
    line-height: 1.42;
}
```

**Comment by Jiiun** [comment]
@benbro thanks for your replying. how can i set line-height in each line just like below
![image](https://cloud.githubusercontent.com/assets/13991287/26619069/6a4fd6e0-460f-11e7-8ec1-486770e27753.png)

**Comment by benbro** [comment]
@Jiiun you need to create a attributor and a custom toolbar button.
You can use the [direction attributor](https://github.com/quilljs/quill/blob/develop/formats/direction.js) as an example.
https://quilljs.com/guides/how-to-customize-quill/#content-and-formatting
If you have further questions please use StackOverflow. github issues are for bugs.

**Comment by Jiiun** [comment]
thank you very much~

**Comment by Jiiun** [comment]
![image](https://cloud.githubusercontent.com/assets/13991287/26769146/1bc87fa8-49df-11e7-85c4-3066e62318d3.png)
haha! I fixed it

**Comment by tomcon** [comment]
@benbro whatever I try nothing works and I've spent a couple of hours on this already. Everything looks fine but it is always received in Outlook or GMail with large line-spacing (see pic below). 
```
   -webkit-margin-after: 1em;
   -webkit-margin-before: 1em;
```
seem to be the culprits but I set them in the css but no luck. 
Is the way around this to add inline styles & if so, is it easy to add them?

Is it a Quill issue or has anyone else come across this one? Any help much appreciated.

```
.ql-editor  {
   line-height: 1.20 !important;
   font-family: Calibri, Helvetica !important;
   font-size: 15px !important;
   -webkit-margin-after:0px;
   -webkit-margin-before:0px;
}
.ql-editor p {    line-height: 1.2;}
```

![image](https://user-images.githubusercontent.com/647145/27837925-3a799402-60df-11e7-9152-29ef10592e39.png)

**Comment by benbro** [comment]
@tomcon Quill uses classes by default. To make the output work in email you need to use inline styles instead.
Read this [guide](https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline) about using inline style attributes.

**Comment by tomcon** [comment]
@benbro 
with respect: "Does quill have customizable line spacing ability?" is completely related to my question.

I've read the guide quite a bit in the past and again just now but it is not very clear on this topic plus I am using ES5 and all examples are ES6. 

Can anyone help with an example please of how to simply add a default line-height inline rule to all <p> tags? Thanks

**Comment by tomcon** [comment]
For anyone else that may come here with a similar problem:
best short term solution was to replace <p> with <br> and removing </p> on editor save (adding inline-styles still had issues).

See also: https://stackoverflow.com/questions/38024698/html-email-how-do-you-remove-webkit-margin-before-1em-webkit-margin-after

**Comment by xiechao1211** [comment]
@Jiiun 你好，我想问下，你的行高功能具体是怎么实现的？
toolbar里如何定义?

**Comment by Malenconiaprincep** [comment]
Set line-height is not real LineSpacing; It is not like MSoffice word's it

**Comment by miracle9312** [comment]
> ![image](https://cloud.githubusercontent.com/assets/13991287/26769146/1bc87fa8-49df-11e7-85c4-3066e62318d3.png)
> haha! I fixed it
still does not work

**Comment by miracle9312** [comment]
> @tomcon This issue is old and unrelated to your question.
> Quill uses classes by default. To make the output work in email you need to use inline styles instead.
> Read this [guide](https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline) about using inline style attributes.
``` import Parchment from 'parchment';
    import _Quill from 'quill';
    import { sizeWhiteList, alignWhiteList } from './formats'
    const Quill = window.Quill || _Quill;
    let config = {
        scope: Parchment.Scope.INLINE,
        whitelist: ['1.0em','1.1em','1.2em','1.3em','1.4em','1.5em','1.6em']
    }
    var lineHtStyle = new Parchment.Attributor.Style('lineheight','line-height', config);

    Quill.register(lineHtStyle, true);```
i want to set custom lineheight, but it dose not work

**Comment by miracle9312** [comment]
> Hi,
> this @Jiiun codes its working, but you need to create a css too.
> 
> this is my js code:
> 
> ```js
> var Parchment = Quill.import('parchment');
>     var lineHeightConfig = {
>       scope: Parchment.Scope.INLINE,
>       whitelist: [
>         '1.0',
>         '1.2',
>         '1.5',
>         '1.6',
>         '1.8',
>         '2.0',
>         '2.4',
>         '2.8',
>         '3.0',
>         '4.0',
>         '5.0'
>       ]
>     };
>     var lineHeightClass = new Parchment.Attributor.Class('lineheight', 'ql-line-height', lineHeightConfig);
>     var lineHeightStyle = new Parchment.Attributor.Style('lineheight', 'line-height', lineHeightConfig);
>     Parchment.register(lineHeightClass);
>     Parchment.register(lineHeightStyle);
> ```
> 
> And my css:
> 
> ```css
> .ql-snow .ql-picker.ql-lineheight{
>   width: 58px;
> }
> 
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.0']::before {content: '1.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.0']::before {content: '1.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.2']::before {content: '1.2';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.2']::before {content: '1.2' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.5']::before {content: '1.5';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.5']::before {content: '1.5' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.6']::before {content: '1.6';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.6']::before {content: '1.6' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.8']::before {content: '1.8';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.8']::before {content: '1.8' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.0']::before {content: '2.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.0']::before {content: '2.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.4']::before {content: '2.4';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.4']::before {content: '2.4' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.8']::before {content: '2.8';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.8']::before {content: '2.8' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='3.0']::before {content: '3.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='3.0']::before {content: '3.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='4.0']::before {content: '4.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='4.0']::before {content: '4.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='5.0']::before {content: '5.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='5.0']::before {content: '5.0' !important;}
> ```
it works!!! thank you very much

**Comment by enterpub** [comment]
> Hi,
> this @Jiiun codes its working, but you need to create a css too.
> 
> this is my js code:
> 
> ```js
> var Parchment = Quill.import('parchment');
>     var lineHeightConfig = {
>       scope: Parchment.Scope.INLINE,
>       whitelist: [
>         '1.0',
>         '1.2',
>         '1.5',
>         '1.6',
>         '1.8',
>         '2.0',
>         '2.4',
>         '2.8',
>         '3.0',
>         '4.0',
>         '5.0'
>       ]
>     };
>     var lineHeightClass = new Parchment.Attributor.Class('lineheight', 'ql-line-height', lineHeightConfig);
>     var lineHeightStyle = new Parchment.Attributor.Style('lineheight', 'line-height', lineHeightConfig);
>     Parchment.register(lineHeightClass);
>     Parchment.register(lineHeightStyle);
> ```
> 
> And my css:
> 
> ```css
> .ql-snow .ql-picker.ql-lineheight{
>   width: 58px;
> }
> 
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.0']::before {content: '1.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.0']::before {content: '1.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.2']::before {content: '1.2';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.2']::before {content: '1.2' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.5']::before {content: '1.5';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.5']::before {content: '1.5' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.6']::before {content: '1.6';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.6']::before {content: '1.6' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.8']::before {content: '1.8';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.8']::before {content: '1.8' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.0']::before {content: '2.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.0']::before {content: '2.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.4']::before {content: '2.4';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.4']::before {content: '2.4' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.8']::before {content: '2.8';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.8']::before {content: '2.8' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='3.0']::before {content: '3.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='3.0']::before {content: '3.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='4.0']::before {content: '4.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='4.0']::before {content: '4.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='5.0']::before {content: '5.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='5.0']::before {content: '5.0' !important;}
> ```

Can you explain how to force quill create correct deltas for "lineheight" attribute?
In my case it is always empty. Looks like:
`"{\"ops\":[{\"attributes\":{\"lineheight\":\"\"},\"insert\":\"line 1\"},{\"insert\":\"\\n\"},{\"attributes\":{\"lineheight\":\"\"},\"insert\":\"line 2\"},{\"insert\":\"\\n\"}]}"`

Please, note, that value of `{\"lineheight\":\"\"}` is empty.
P.S. in Quill editor itself in html it works,  I mean I can visually see the spacing between lines. The issue is only in quill deltas

**Comment by clpacheco90** [comment]
@enterpub,
I never used Delta before but if it still does not work try to get value by css and then insert to your Delta JSON.

**Comment by ever-dev** [comment]
> Hi,
> this @Jiiun codes its working, but you need to create a css too.
> 
> this is my js code:
> 
> ```js
> var Parchment = Quill.import('parchment');
>     var lineHeightConfig = {
>       scope: Parchment.Scope.INLINE,
>       whitelist: [
>         '1.0',
>         '1.2',
>         '1.5',
>         '1.6',
>         '1.8',
>         '2.0',
>         '2.4',
>         '2.8',
>         '3.0',
>         '4.0',
>         '5.0'
>       ]
>     };
>     var lineHeightClass = new Parchment.Attributor.Class('lineheight', 'ql-line-height', lineHeightConfig);
>     var lineHeightStyle = new Parchment.Attributor.Style('lineheight', 'line-height', lineHeightConfig);
>     Parchment.register(lineHeightClass);
>     Parchment.register(lineHeightStyle);
> ```
> 
> And my css:
> 
> ```css
> .ql-snow .ql-picker.ql-lineheight{
>   width: 58px;
> }
> 
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.0']::before {content: '1.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.0']::before {content: '1.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.2']::before {content: '1.2';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.2']::before {content: '1.2' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.5']::before {content: '1.5';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.5']::before {content: '1.5' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.6']::before {content: '1.6';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.6']::before {content: '1.6' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.8']::before {content: '1.8';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.8']::before {content: '1.8' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.0']::before {content: '2.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.0']::before {content: '2.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.4']::before {content: '2.4';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.4']::before {content: '2.4' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.8']::before {content: '2.8';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.8']::before {content: '2.8' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='3.0']::before {content: '3.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='3.0']::before {content: '3.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='4.0']::before {content: '4.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='4.0']::before {content: '4.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='5.0']::before {content: '5.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='5.0']::before {content: '5.0' !important;}
> ```

How can I prevent getting initialized for this line-height setting?
It gets initialized for next paragraphs.

**Comment by ocole836** [comment]
> > Hi,
> > this @Jiiun codes its working, but you need to create a css too.
> > this is my js code:
> > ```js
> > var Parchment = Quill.import('parchment');
> >     var lineHeightConfig = {
> >       scope: Parchment.Scope.INLINE,
> >       whitelist: [
> >         '1.0',
> >         '1.2',
> >         '1.5',
> >         '1.6',
> >         '1.8',
> >         '2.0',
> >         '2.4',
> >         '2.8',
> >         '3.0',
> >         '4.0',
> >         '5.0'
> >       ]
> >     };
> >     var lineHeightClass = new Parchment.Attributor.Class('lineheight', 'ql-line-height', lineHeightConfig);
> >     var lineHeightStyle = new Parchment.Attributor.Style('lineheight', 'line-height', lineHeightConfig);
> >     Parchment.register(lineHeightClass);
> >     Parchment.register(lineHeightStyle);
> > ```
> > 
> > 
> > And my css:
> > ```css
> > .ql-snow .ql-picker.ql-lineheight{
> >   width: 58px;
> > }
> > 
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.0']::before {content: '1.0';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.0']::before {content: '1.0' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.2']::before {content: '1.2';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.2']::before {content: '1.2' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.5']::before {content: '1.5';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.5']::before {content: '1.5' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.6']::before {content: '1.6';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.6']::before {content: '1.6' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.8']::before {content: '1.8';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.8']::before {content: '1.8' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.0']::before {content: '2.0';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.0']::before {content: '2.0' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.4']::before {content: '2.4';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.4']::before {content: '2.4' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.8']::before {content: '2.8';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.8']::before {content: '2.8' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='3.0']::before {content: '3.0';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='3.0']::before {content: '3.0' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='4.0']::before {content: '4.0';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='4.0']::before {content: '4.0' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='5.0']::before {content: '5.0';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='5.0']::before {content: '5.0' !important;}
> > ```
> 
> Can you explain how to force quill create correct deltas for "lineheight" attribute?
> In my case it is always empty. Looks like:
> `"{\"ops\":[{\"attributes\":{\"lineheight\":\"\"},\"insert\":\"line 1\"},{\"insert\":\"\\n\"},{\"attributes\":{\"lineheight\":\"\"},\"insert\":\"line 2\"},{\"insert\":\"\\n\"}]}"`
> 
> Please, note, that value of `{\"lineheight\":\"\"}` is empty.
> P.S. in Quill editor itself in html it works, I mean I can visually see the spacing between lines. The issue is only in quill deltas

If anyone stumbles across this issue, the reason to why it was empty was because `lineHeight` style prop with value like `"3.0"`, `"2.0"` gets converted to number `3` and `2` respectively, which is not in the whitelist defined above - so [here](https://github.com/quilljs/parchment/blob/067c392fe1e6f9b2c480bf4cc00a2e10a72e5ef1/src/attributor/style.ts#L40) condition of `canAdd` failed and returned empty line

```
class LineHeightStyleAttributor extends Parchment.Attributor.Style {
  // Original canAdd condition failed, as lineHeight 3.0 was converted to number 3, and it is not present in whitelist above
  value(node: HTMLElement) {
    const value = node.style.lineHeight;
    const prepared = Number.parseFloat(value).toFixed(1);
    return this.canAdd(node, prepared) ? prepared : '';
  }
}

const lineHeightStyle = new LineHeightStyleAttributor(
  'lineheight',
  'line-height',
  lineHeightConfig,
);
```
After redefining value method like that, to conver `3` to `"3.0"` from style value, it works flawlessly now

**Comment by keivansahebdelfard** [comment]
> Hi,
> this @Jiiun codes its working, but you need to create a css too.
> 
> this is my js code:
> 
> ```js
> var Parchment = Quill.import('parchment');
>     var lineHeightConfig = {
>       scope: Parchment.Scope.INLINE,
>       whitelist: [
>         '1.0',
>         '1.2',
>         '1.5',
>         '1.6',
>         '1.8',
>         '2.0',
>         '2.4',
>         '2.8',
>         '3.0',
>         '4.0',
>         '5.0'
>       ]
>     };
>     var lineHeightClass = new Parchment.Attributor.Class('lineheight', 'ql-line-height', lineHeightConfig);
>     var lineHeightStyle = new Parchment.Attributor.Style('lineheight', 'line-height', lineHeightConfig);
>     Parchment.register(lineHeightClass);
>     Parchment.register(lineHeightStyle);
> ```
> 
> And my css:
> 
> ```css
> .ql-snow .ql-picker.ql-lineheight{
>   width: 58px;
> }
> 
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.0']::before {content: '1.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.0']::before {content: '1.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.2']::before {content: '1.2';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.2']::before {content: '1.2' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.5']::before {content: '1.5';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.5']::before {content: '1.5' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.6']::before {content: '1.6';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.6']::before {content: '1.6' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.8']::before {content: '1.8';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.8']::before {content: '1.8' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.0']::before {content: '2.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.0']::before {content: '2.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.4']::before {content: '2.4';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.4']::before {content: '2.4' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.8']::before {content: '2.8';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.8']::before {content: '2.8' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='3.0']::before {content: '3.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='3.0']::before {content: '3.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='4.0']::before {content: '4.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='4.0']::before {content: '4.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='5.0']::before {content: '5.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='5.0']::before {content: '5.0' !important;}
> ```

additional thing is to set lineHeight?:string[] in QuillToolbarConfig type
code snip : 
```
export declare type QuillToolbarConfig = Array<Array<string | {
    indent?: string;
    list?: string;
    direction?: string;
    header?: number | Array<boolean | number>;
    color?: string[] | string;
    background?: string[] | string;
    align?: string[] | string;
    script?: string;
    font?: string[] | string;
    size?: Array<boolean | string>;
    lineHeight?:string[]
}>>;

```

**Comment by KiritoXF** [comment]
Besides @clpacheco90 's code, also add following code to quill's toolbar option, otherwise lineHeight select bar won't be shown on the toolbar.
```
options: {
  modules: {
    toolbar: [
      [{ lineheight: ['1.0', '1.2', '1.5', '1.6', '1.8', '2.0', '2.4', '2.8', '3.0', '4.0', '5.0'] }],
    ]
  }
}

```

> Hi,
> this @Jiiun codes its working, but you need to create a css too.
> 
> this is my js code:
> 
> ```js
> var Parchment = Quill.import('parchment');
>     var lineHeightConfig = {
>       scope: Parchment.Scope.INLINE,
>       whitelist: [
>         '1.0',
>         '1.2',
>         '1.5',
>         '1.6',
>         '1.8',
>         '2.0',
>         '2.4',
>         '2.8',
>         '3.0',
>         '4.0',
>         '5.0'
>       ]
>     };
>     var lineHeightClass = new Parchment.Attributor.Class('lineheight', 'ql-line-height', lineHeightConfig);
>     var lineHeightStyle = new Parchment.Attributor.Style('lineheight', 'line-height', lineHeightConfig);
>     Parchment.register(lineHeightClass);
>     Parchment.register(lineHeightStyle);
> ```
> 
> And my css:
> 
> ```css
> .ql-snow .ql-picker.ql-lineheight{
>   width: 58px;
> }
> 
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.0']::before {content: '1.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.0']::before {content: '1.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.2']::before {content: '1.2';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.2']::before {content: '1.2' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.5']::before {content: '1.5';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.5']::before {content: '1.5' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.6']::before {content: '1.6';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.6']::before {content: '1.6' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.8']::before {content: '1.8';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.8']::before {content: '1.8' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.0']::before {content: '2.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.0']::before {content: '2.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.4']::before {content: '2.4';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.4']::before {content: '2.4' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.8']::before {content: '2.8';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.8']::before {content: '2.8' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='3.0']::before {content: '3.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='3.0']::before {content: '3.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='4.0']::before {content: '4.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='4.0']::before {content: '4.0' !important;}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='5.0']::before {content: '5.0';}
> .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='5.0']::before {content: '5.0' !important;}
> ```

**Comment by babaiwan** [comment]
> > Hi,
> > this @Jiiun codes its working, but you need to create a css too.
> > this is my js code:
> > ```js
> > var Parchment = Quill.import('parchment');
> >     var lineHeightConfig = {
> >       scope: Parchment.Scope.INLINE,
> >       whitelist: [
> >         '1.0',
> >         '1.2',
> >         '1.5',
> >         '1.6',
> >         '1.8',
> >         '2.0',
> >         '2.4',
> >         '2.8',
> >         '3.0',
> >         '4.0',
> >         '5.0'
> >       ]
> >     };
> >     var lineHeightClass = new Parchment.Attributor.Class('lineheight', 'ql-line-height', lineHeightConfig);
> >     var lineHeightStyle = new Parchment.Attributor.Style('lineheight', 'line-height', lineHeightConfig);
> >     Parchment.register(lineHeightClass);
> >     Parchment.register(lineHeightStyle);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And my css:
> > ```css
> > .ql-snow .ql-picker.ql-lineheight{
> >   width: 58px;
> > }
> > 
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.0']::before {content: '1.0';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.0']::before {content: '1.0' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.2']::before {content: '1.2';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.2']::before {content: '1.2' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.5']::before {content: '1.5';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.5']::before {content: '1.5' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.6']::before {content: '1.6';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.6']::before {content: '1.6' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='1.8']::before {content: '1.8';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='1.8']::before {content: '1.8' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.0']::before {content: '2.0';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.0']::before {content: '2.0' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.4']::before {content: '2.4';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.4']::before {content: '2.4' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='2.8']::before {content: '2.8';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='2.8']::before {content: '2.8' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='3.0']::before {content: '3.0';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='3.0']::before {content: '3.0' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='4.0']::before {content: '4.0';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='4.0']::before {content: '4.0' !important;}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-item[data-value='5.0']::before {content: '5.0';}
> > .ql-snow .ql-picker.ql-lineheight .ql-picker-label[data-value='5.0']::before {content: '5.0' !important;}
> > ```
> 
> How can I prevent getting initialized for this line-height setting? It gets initialized for next paragraphs.

you need to define a class yourself just like
https://zhuanlan.zhihu.com/p/448416744

**Comment by Evgeni67** [comment]
Guys, what if I have multiple Quill editors open? Overwriting the quill classes will be applied to all of them and the solution wont be a solutin anymore

**Comment by MarianoJP** [comment]
@Evgeni67, I am using Quill.JS 2.0 in Blazor environment, needless to say I had a bit of trouble with the 'pre-render' functionality of Blazor and thus similar to having multiple Quill editors in one page. My solution that applies to Blazor is to have a bool that on the 'pre-render' stage not to load/create the editor in JavaScript. Blazor has a OnParametersSet functionality that when the component is passed parameters, I then pass the bool with a true to load/create the Quill editor. This solution has proven useful to me in the Blazor environment. I hope it points you to the right direction.

That aside, The above solution of the extending of the Class, I have the following solution that works on Quill 2.0.

`class LineHeightStyleAttributor extends Parchment.StyleAttributor {
value(node) {
        const value = node.style.lineHeight;
        const prepared = Number.parseFloat(value).toFixed(1);
        return this.canAdd(node, prepared) ? prepared : '';
    }
}`

Hope this helps.
