### ISSUE TITLE
can not attach event handler in custom blot

### ISSUE THREAD

**Issue by dadaowuwei** [quilljs/quill#1971]
created an atmention format blot and try to attach the click event listener to the blot. 
However, the event handler is not get called when the blot is clicked .  
the main event handler attach code looks like following:
`static create(value) {
    let node = super.create(value);
    node.setAttribute(AtMention.blotName, JSON.stringify(value));
    node.setAttribute('href', '');
    node.setAttribute('tabIndex', '-1');
    node.setAttribute('style', 'text-decoration:none; color:blue; pointer-events: none; cursor: default;');
    node.addEventListener('click', function(e) {
    console.log("blot clicked");
  });
    return node;
  }`

**Steps for Reproduction**

1. Visit https://codepen.io/anon/pen/NyWgzo
2. click the @TestMention text 

**Expected behavior**:
should print out "blot clicked" 
**Actual behavior**:
nothing print out
**Platforms**:
windows10 chrome

**Version**:
quill 1.3.5

**Comment by Charrondev** [comment]
You're issue is pretty clear. You're setting `pointer-events: none` when you set your inline attributes.

```js
 node.setAttribute('style', 'text-decoration:none; color:blue; pointer-events: none; cursor: default;');
    return node;
  }
```

This causes the browser to ignore any click events on that element. You'll find that this is not just related to quill, but will happen with any DOM Node.

Remove that style, and the click handler works.

**Comment by dadaowuwei** [comment]
arh, got it, Thanks @Charrondev !
