### ISSUE TITLE
register module to specific quill instance

### ISSUE THREAD

**Issue by talik077** [quilljs/quill#1973]
In our application we use various quill editors in the same page. Each one of them has different functionality and styling. I wrote a module that handle clipboard functionality that removes all predefined styles. I would like to apply this module only to one of the quill editors but 
the problem is that the `Quill.register` function is global and changes the functionality in all editors. How can I use it for specific instance of Quill?   

**Expected behavior**: Be able to register module to some instances of Quill in the same page

**Actual behavior**: register function apply the module useability to all Quill elements 

**Version**: 1.2.6

**Comment by volser** [comment]
`Quill.register` only add module to available list but not turn on, then you should turn on module for instance in `config: { modules: {...}}`. You can have different configs for your instances

**Comment by benbro** [comment]
@volser thanks.
