### ISSUE TITLE
binding to special characters in different languages

### ISSUE THREAD

**Issue by volser** [quilljs/quill#1975]
I saw this answer https://github.com/quilljs/quill/issues/961

But ':' has different code in other languages, for example in ukrainian /russian ':' is Shift + 6 (key: 54), german Shift + > (key: 190), ...

How to bind not by key code but by symbol?
key: ':' not working

**Comment by volser** [comment]
for german  evt.which = 190, evt.key = ':'
`let which = evt.which || evt.keyCode;`
in code only uses `this.bindings[which]`
so need some solution to bind not only by `which`, but by 'keyCode' as well

**Comment by jhchen** [comment]
It is a 2.0 feature which is not stable at the moment (no public timeline). Just being honest I do not see myself having the bandwidth to hotfix for 1.x.
