### ISSUE TITLE
Enhancement request: ability to exit a block using down arrow

### ISSUE THREAD

**Issue by aral** [quilljs/quill#1977]
**Steps for Reproduction**

1. Visit https://patleeman.github.io/quill-markdown-shortcuts/
2. Select the editor
3. Type: ` ``` ` + \<return\> to start a code block
4. Type some code
5. Press down arrow

**Expected behavior**:

You should be able to exit the code block.

**Actual behavior**:

Nothing happens. It feels like you’re stuck and there’s no way to exit the code block.

I only discovered later, by accident, that you can exit the block by pressing \<return\> _three times_ in a row. That's not intuitive.

**Platforms**:

Tested on latest Safari, on latest macOS. On latest iOS.  

**Version**:

Not sure what version the online demo is running.

**Original issue (closed) on the module’s issue tracker**:

https://github.com/patleeman/quill-markdown-shortcuts/issues/9#issuecomment-368898924

**Comment by Charrondev** [comment]
I'd like to elaborate a little bit more on the expected solution.

**Comment by Charrondev** [comment]
If you take a look [here](https://github.com/vanilla/vanilla/blob/feature/better-block-blots/plugins/rich-editor/src/scripts/QuillTheme.jsx#L202-L232) I have a functioning implementation of this behaviour for  multiple of our Custom Blots for both the beginning and end of the document with all arrow keys.

@jhchen Is this something you would accept a PR for, for the built in CodeBlock and BlockQuote Blots?

**Comment by charrondev** [comment]
I realize now that the link I shared has been made defunct after some reorganizing. I'm willing to submit a PR for both this and #1978 with tests, but was looking for acknowledgement form @jhchen first.

In the meantime you can find [our implementation](https://github.com/vanilla/rich-editor/blob/master/plugins/rich-editor/src/scripts/quill/KeyboardBindings.ts) and [tests](https://github.com/vanilla/rich-editor/blob/master/plugins/rich-editor/src/scripts/quill/KeyboardBindings.ts)

Those files also use a few utilities I've written for:
- [Inserting a new line after a block and trimming extra whitespace](https://github.com/vanilla/rich-editor/blob/master/plugins/rich-editor/src/scripts/quill/utility.ts#L212)
- [Multiple others](https://github.com/vanilla/rich-editor/blob/master/plugins/rich-editor/src/scripts/quill/utility.ts)

They are written in typescript though, but it should be easy enough to read through. We have a decent amount of custom blots, and don't use all of the built in ones though, so there is probably a lot of extra code happening there. Our [for quotes](https://github.com/vanilla/rich-editor/blob/master/plugins/rich-editor/src/scripts/quill/blots/blocks/BlockquoteBlot.ts) supports multiple lines, so we have some additional handlers for better UX in that department.

**Comment by divyanalluri** [comment]
Hi team,

Any update related to this issue?
