### ISSUE TITLE
Enhancement request: ability to delete a block by backspacing when it is empty

### ISSUE THREAD

**Issue by aral** [quilljs/quill#1978]
**Steps for Reproduction**

1. Visit https://patleeman.github.io/quill-markdown-shortcuts/
2. Select the editor
3. Type: ` ``` ` + \<return\> to start a code block
4. Type some code
5. Press backspace to delete what you’ve typed
6. Keep pressing backspace when the block is empty

**Expected behavior**:

The block should be deleted.

**Actual behavior**:

Nothing happens. It feels like you’re stuck and there’s no way to delete the code block.

The current way to delete the code block is to press \<return\> three times to exit the block and then press backspace to delete it.

**Platforms**:

Tested on latest Safari, on latest macOS. On latest iOS.  

**Version**:

Not sure what version the online demo is running.

**Related to original issue (closed) on the module’s issue tracker**:

https://github.com/patleeman/quill-markdown-shortcuts/issues/9#issuecomment-368898924

Also related to #1977

**Comment by Charrondev** [comment]
I've actually run into this myself recently and ended up using some custom keyboard events to handle it. I'll update here in the next couple days with the my solution if it interests you.

I'm not sure if your (and my) desired behaviour lines up with the intention of the author though. Looking at from a slightly higher level concept the Code Block could be handled a couple of different ways (and for my use case, some Custom Blots behave similarly - Spoilers and Blockquotes).

## Current Implementation

Hitting backspace when inside of a CodeBlock or BlockQuote actually applies the backspace to the line before the current one. This is consistent with how backspaces from the the beginning of a line is handled in every other Blot.

To illustrate:

```
Line 1\n
[codeblock][CURSOR]Line 2\n[\codeblock]
Line 3\n
```

The newlines sit at the end of each line, and backspace will delete the newline at the end of the previous line (and remove the codeblock format). So clicking backspace in this example would result in the following.

```
Line 1[CURSOR]Line 2\n
Line 3\n
```

The issue really tends to show it's head when the situation looks like the following:

```
[codeblock][CURSOR]Line 1\n[\codeblock]
Line 2\n
Line 3\n
```

There is no newline at line 0 to delete, so nothing happens.

## Alternate Implementation

Backspace at the beginning of a newline for a blockquote or codeblock strips the format of their Container/Block Blot.

The behaviour we ended up settling on after some lengthy and debate and consideration of some of the edge cases ended up like the following:

```
[codeblock][CURSOR]Line 1\nLine2\n[\codeblock]
Line 3\n
Line 3\n
```

In this situation clicking backspace would result in the following:

```
[CURSOR]Line 1\nLine2\n
Line 3\n
Line 3\n
```

For consistency this behaviour occurs everywhere, not just at the start of the document. We ended up implementing it using some custom handlers on the keyboard module.

**Comment by Charrondev** [comment]
For reference our custom handler for backspacing looks like the following:

```js
this.options.modules.keyboard.bindings["Block Escape Backspace"] = {
    key: Keyboard.keys.BACKSPACE,
    collapsed: true,
    format: ['spoiler-line'],
    handler: (range) => {
        const [line] = this.quill.getLine(range.index);

        // Check if this is the first line in the SpoilerContentBlot.
        const isFirstLine = line === line.parent.children.head;

        if (isFirstLine) {
            // The fact that this is always the grandparent of the line is enforced at the Blot level.
            const spoilerBlot = line.parent.parent;

            const delta = new Delta()
                .retain(spoilerBlot.offset())
                .retain(spoilerBlot.length(), { 'spoiler-line': false });
            this.quill.updateContents(delta, Emitter.sources.USER);

            // Return false to prevent default behaviour.
            return false;
        } else {
            // Return true to allow default behaviour.
            return true;
        }
    },
};
```

**Comment by aral** [comment]
@Charrondev Thanks so much, Adam, that’s very useful and will no doubt help others also. I’m going to draw attention to your response on the module’s issue board now. Appreciate your time in writing this up.
