### ISSUE TITLE
Calling `getFormat` when the editor doesn't have focus restore focus

### ISSUE THREAD

**Issue by manu-st** [quilljs/quill#1980]
**Steps for Reproduction**
I have an event handler on `selection-change`. If during the execution of the handler I call `getFormat` while the quill's editor doesn't have focus, then my editor gets the focus back.

**Expected behavior**:
`getFormat` should not change focus.

**Actual behavior**:
My editor which doesn't have focus gets the focus.

**Platforms**:
Windows with Electron 1.7.9

**Version**:
1.3.5

**Comment by jhchen** [comment]
I assume you are calling with no parameters. In that case it focuses the editor to get the current selection.

**Comment by manu-st** [comment]
That's correct. It seems that `selection-change` is called when getting out of focus and I'm mostly calling `selection-change` to get the format. I added a protection to make sure that the quill's editor has focus before asking for the format. However it would have been better to return a null/undefined format instead of having the side effects of focusing the editor.

**Comment by DarnellSh** [comment]
@jhchen @manu-st any work around for this? I am running into the same issue. I need to call `getFormat()` and not set the selection.

**Comment by manu-st** [comment]
@DarnellSh The one I made is to disable my handler for `selection-change` whenever I know for sure that the quills editor doesn't have focus.

**Comment by zzjzz9266a** [comment]
Another workaround:
``` typescript
getFormat(): { [keys: string]: any } {
  const hasFocus = this.quillEditor.hasFocus();
  const format = this.quillEditor.getFormat();
  if (hasFocus === false) {
    this.quillEditor.blur();
  }
  return format;
}
```

**Comment by MarcDAFrame** [comment]
this issue is still present in version 2.0.2



> Workaround I found is call quill.getSelection(false) first and then call getFormat with params like below:
> 
> ```js
> const currentSelection = quill.getSelection(false);
> if (currentSelection === null) return // I added this line to prevent errors
> const currentFormat = quill.getFormat(currentSelection.index, currentSelection.length);
> ```

this workaround from @Hanho-Kim worked

**Comment by Agtevoase** [comment]
Please reopen as this issue is still present in the latest.

**Comment by Halt001** [comment]
Same here, I'm on version 2.0.3. onSelectionChangeHandler is called when loosing focus and calling getFormat  in that handler will restore the focus.
