### ISSUE TITLE
throw error when I return a delta async in an  addMatcher handler

### ISSUE THREAD

**Issue by zhatongning** [quilljs/quill#1981]
```
 this.quill.clipboard.addMatcher('img', function (node, delta) {
        let d = new Delta().insert('Hello', { bold: true })
            .insert({ image: 'https://octodex.github.com/images/labtocat.png' })
            .insert('World!')
          return d
      })
```
when I ran codes like above, It worked perfectly. BUT when I changed to something like:

```
     this.quill.clipboard.addMatcher('img', function (node, delta) {
        setTimeout(() => {
          let d = new Delta().insert('Hello', { bold: true })
            .insert({ image: 'https://octodex.github.com/images/labtocat.png' })
            .insert('World!')
          return d
        }, 1000)
      })
```
the process failed, and threw error like:

![2018-02-28 3 30 02](https://user-images.githubusercontent.com/20442118/36775267-63a4c0bc-1c9c-11e8-851d-531e4fabc604.png)

**Comment by volser** [comment]
because you handler returns undefined, your return inside setTimeout

**Comment by zhatongning** [comment]
@volser I need reset the delta after server's response. How could I solve the problem ?

**Comment by volser** [comment]
You can update content after request
```
quill.updateContents(
    new Delta()
      .retain(quill.getSelection().index)
      .insert('Hello', { bold: true })
      .insert({ image: 'https://octodex.github.com/images/labtocat.png' })
      .insert('World!')
));
```

**Comment by benbro** [comment]
@volser thank you for answering the question.

**Comment by lizy0329** [comment]
> You can update content after request
> 
> ```
> quill.updateContents(
>     new Delta()
>       .retain(quill.getSelection().index)
>       .insert('Hello', { bold: true })
>       .insert({ image: 'https://octodex.github.com/images/labtocat.png' })
>       .insert('World!')
> ));
> ```

Amazing! this answer should be show on FAQ for quilljs documenation
