### ISSUE TITLE
delta output with mixed attributes resulting in diffed delta loses intent.

### ISSUE THREAD

**Issue by rhysbrettbowen** [quilljs/quill#1982]
When there is a block attribute such as a header set and we put a newline which includes an attribute, the deepEquals fails and instead a diff is performed (https://github.com/quilljs/quill/blob/57a4247a0aeba200dec5286f2e7c2d971ee93c5c/core/editor.js#L217)

In the fiddle The diff loses the intent from the delta, as it will grab the last \n as the change (which means things like transform cursor position is wrong).

**Steps for Reproduction**

1. https://jsfiddle.net/Lnyyyvhp/25/
2. place cursor after the "a"
3. press ENTER

**Expected behavior**:

output delta should be: [
  {"retain":1},
  {"insert":"\n", "attributes":{"header":1}},
  {"retain":1,"attributes":{"header":null}}
]

**Actual behavior**:

[{"retain":5},{"insert":"\n"}]

**Platforms**:

Chrome

**Version**:

1.3.4

**Comment by rhysbrettbowen** [comment]
I looked in to this more and looks like this is the issue:

https://github.com/quilljs/quill/blob/develop/modules/keyboard.js#L241

Suggested fix would be to change context.format to looking each key up in parchment and only including those on the block scope.

**Comment by salami-art** [comment]
+1
