### ISSUE TITLE
Disallow "inconsistent" indentation

### ISSUE THREAD

**Issue by lelit** [quilljs/quill#1986]
Quill, like many other editors, allows to introduce "inconsistent" indentation, and I would like to disallow that.

With "inconsistent" I mean that you can for example:
- write a paragraph, indent it at level 5
- add a bullet list, deindent it at level 3
- add a second item, deindent at level 1
- add a third item, indent it at level 6
- ...

Is there a way to prevent such actions, for example constraining the indentation level difference between two consecutive elements to be at maximum 1?

Thanks for any hint!

**Comment by benbro** [comment]
Did you try to use [API events](https://quilljs.com/docs/api/#events) or a [keyboard binding](https://quilljs.com/docs/modules/keyboard/) to prevent unwanted indentation?

**Comment by lelit** [comment]
Am I missing something, or given that those events are emitted "after the fact" they cannot be used to reject the action?
As to keyboard bindings, maybe yes: I could remove the indent/dedent buttons from the toolbar, and intercepts TABs... less than ideal, but I will try that, thanks.

**Comment by benbro** [comment]
Maybe you can revert unwanted indentation with a new delta. Logic will probably not be simple.
```
quill.on(Quill.events.EDITOR_CHANGE, (eventName, delta, oldDelta, source) => {
  if (eventName == Quill.events.TEXT_CHANGE && source == 'user') {
    let myDelta = new Delta();
    // revert indentation here
    this.quill.updateContents(myDelta, Quill.sources.SILENT);
  }
});
```

**Comment by jhchen** [comment]
This seems too specific to be added to Quill core. As @benbro mentioned you can look at creating and enforcing the constraint for your own use case through keyboard bindings.
