### ISSUE TITLE
Selecting all and Deleting does not clear CodeBlock or BlockQuote in first position

### ISSUE THREAD

**Issue by charrondev** [quilljs/quill#1987]
Selecting all and deleting should result in an empty editor. Currently blockquotes and codeblocks in the first position of the editor are undeletable with backspace key, even if you select all and press delete.

**Steps for Reproduction**

1. Visit https://codepen.io/anon/pen/eVXNXa
2. Select all of the text in the editor 
3. Click backspace

**Expected behavior**:

All of the content of the editor is deleted.

**Actual behavior**:

An empty blockquote remains in the first position.

**Platforms**:

Chrome, Firefox latest on Windows and MacOS

**Version**:

1.3.5

**Comment by creeperyang** [comment]
And If the first line is a BlockQuote, you delete the character one by one, You can never delete the **empty BlockQuote**.

**Comment by charrondev** [comment]
We've added some custom keyboard events in our in editor, to handle some of the various things like this, but it would be nice to put together a more robust solution in core.

**Comment by camsjams** [comment]
This doesn't appear to exist in Quill 1.3.0, but does in 1.3.5 and 1.3.6.

I haven't looked into it too much but downgrading to 1.3.0 solved this issue for me.

While downgrading package version isn't the best solution, just commenting here for others :+1: 

@jhchen There were a lot of changes between 1.3.0 and 1.3.5, so not sure when this broke.
