### ISSUE TITLE
Cursor skips over code block with up arrow

### ISSUE THREAD

**Issue by charrondev** [quilljs/quill#1988]
When using the up arrow to navigate the document, if the previous blot is an empty CodeBlock Blot the cursor will skip over the code block.

**Steps for Reproduction**

1. Visit https://quilljs.com/
2. Delete all text in the editor.
3. Enter a newline
4. Create a code block
5. Click enter until you have created a newline after the code block (3 times).
6. Click the up arrow

**Expected behavior**:
The cursor will be inserted in the empty code block.

**Actual behavior**:
The cursor will be inserted above the empty code block.
**Platforms**:

MacOS High Sierra, Google Chrome 64.

**Version**:
1.3.5

**Comment by poshest** [comment]
We're also having this issue.  Pretty much if we have any code block, and the caret (cursor) is below it, up arrow jumps over all the lines of the block.  

The weird thing is if you add syntax highlighting, eg as it is on quilljs.com, this issue doesn't arise.  We don't want syntax highlighting for now, because it's a big heavy package, but we're scratching our heads about why syntax highlighting is required to make arrow navigation work properly.

**Comment by charrondev** [comment]
@poshest We just ended up adding the syntax highlighting. Our editor is dynamically imported anyways and is a good bit larger than the syntax highlighting. I'm sorry I don't have a better answer for you here.

**Comment by marsielko** [comment]
@charrondev There is no need to add syntax highlighting to your editor, if you don't want to. When I was trying to solve this issue I realized, that highlight.js fixed it with creating extra <span> tags in code-block content. But I also noticed, when there were only one <span> and it was in the middle of the content, this was place where caret were placed after "navigating into code-block by up arrow". So in my opinion, the best workaround @poshest  asked for, is to "mock" highlight.js and create <span> around last "non whitespace character". All you need is include **"syntax": true** in Quill's config and execute this function before Quill loads.

```
(function(hljs){
  hljs.highlightAuto = function(text) {
    var noTrailing = text.replace(/\s+$/, '');
    var lastNonWhitespaceIdx = noTrailing.length -1;
    var start = text.substr(0, lastNonWhitespaceIdx);
    var span = '<span class="hljs-caretcatcher">' + text[lastNonWhitespaceIdx] + '</span>';
    var end = text.substr(lastNonWhitespaceIdx + 1);

    return {"value": start + span + end };
  }
  window.hljs = hljs;
})(/*hljs object*/{}); 
```
