### ISSUE TITLE
syntax highlight issue with text color

### ISSUE THREAD

**Issue by volser** [quilljs/quill#1993]
When remove code block format, text keeps highlighted color without ability to clear

**Steps for Reproduction**
http://recordit.co/4hKevIAiqU

add code block
type some keyword (should be highlighted)
remove code block

**Expected behavior**:
clear color (class) when remove code format

**Actual behavior**:
keeps color

**Platforms**:
any

**Version**:
1.3.5

**Comment by volser** [comment]
I don't see here related issues.
it's not format issue.
Highlightjs add own classes to DOM elements, but after deleting code-block, DOM elements are not restored

**Comment by benbro** [comment]
OK, so the issue is that highlight.js classes aren't removed when removing the code block.
Clicking the code button and than the clear-format button does clear the highlight.js classes.
Clicking the clear-format button twice also removes the code block and highlight.js classes.

**Comment by volser** [comment]
is it intentional behavior?

**Comment by benbro** [comment]
I don't think so, probably a bug.

**Comment by volser** [comment]
any ideas how to fix that? thanks

**Comment by pReya** [comment]
Hmm, this is pretty major bug. I hope someone will tackle this soon.

**Comment by geekcap-pluralsight** [comment]
Did anyone find a solution to this bug? I'm running 1.3.7 and this is still a problem..

Thanks!

**Comment by ArsalanSavand** [comment]
I'm still observing this issue.

**Comment by dropmann** [comment]
So I worked out a hack around. The issue I found was that the children of the CodeBlock blot were being internally copied over to the Text blot during the replaceWith method call. So I made this work around and it seems to be ok. I am reasonably new to the quilljs code base so there maybe a better way to do this... it might also introduce other issues... but it works for my purposes.

```javascript
let _get = function get(object, property, receiver) { if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { return get(parent, property, receiver); } } else if ("value" in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } };
const CodeBlock = Quill.import('formats/code-block');
class NewCodeBlock extends CodeBlock {
    replaceWith(block) {
        this.domNode.textContent = this.domNode.textContent;
        this.attach();
        let newItem = _get(CodeBlock.prototype.__proto__ || Object.getPrototypeOf(CodeBlock.prototype), 'replaceWith', this).call(this, block);
        newItem.domNode.textContent = newItem.domNode.textContent;
        this.scroll.update('silent');
    }
}
NewCodeBlock.className = 'ql-syntax';
Quill.register(NewCodeBlock, true);
```

**Comment by mashuDuek** [comment]
I've run into this issue as well and I'm working on a fix. I just got a hacky fix for it in my keyboard bindings, and will use this same one in a custom code-block blot. Keeping this hacky fix for the time being because it appears my deltas are looking like expected. 

Below is the code: 

```  
// use quill.getLine method to access domNode
const { domNode } = this.quill.getLine(range.index)[0];
// setup queue to make sure we remove highlight classes from 
// current node and all its children
const nodes = [domNode];
while (nodes.length > 0) {
  const node = nodes.shift();
            
  // first append children to queue
  for (let i = 0; i < node.children.length; i++) {
    const child = node.children[i];
    nodes.push(child);
  }

 // go through class list of current node removing its "hljs" classes
  for (let i = 0; i < node.classList.length; i++) {
    const c = node.classList[i];
    if (c.indexOf('hljs') >= 0) {
       node.classList.remove(c);
       i--;
    }
  }
}
```
If there is any issue with this solution I would start by making sure the `getLine` method is returning the line in question, and not the parent. Sometimes you want to unhighlight only one line from a code-block, and in your keyboard binding function you may be referencing the whole code-block, so beware of that.

**Comment by AshanFernando** [comment]
Not the best solution but if you need to format multiple lines and clear multiple lines in code blocks, you can use the following

```
        const range = this.quill.getSelection(true);
        const formats = this.quill.getFormat(range);
        // if its not a code-block yet, turn it into one.
        if (!formats['code-block']) {
            return this.quill.formatLine(range.index, range.length, 'code-block', 'user');
        };

        // if it was a code-block, and the user meant to remove it
        this.quill.removeFormat(range.index, range.length, 'user');
        // running it twise to remove colors
        this.quill.removeFormat(range.index, range.length, 'user');
```
