### ISSUE TITLE
Bug: Bubble tooltip should be appended to the body

### ISSUE THREAD

**Issue by shyamal890** [quilljs/quill#1994]
Currently Quill is appending bubble tooltip inline to `quill-editor` element. Instead the tooltip should be appended to the body directly. This would solve a lot of overflow, bubble being hidden behind the container issues.

This is how [medium-editor](https://yabwe.github.io/medium-editor/) works too!

Here's an example of the issue: https://stackblitz.com/edit/ngx-quill-cut-off

**Comment by shyamal890** [comment]
I already checked out the bounds option and it doesn't solve the issue. It just superficially addresses the issue. All information needed is already in the description.

**Comment by benbro** [comment]
Closing the issue because you refuse to add the requested info.

**Comment by shyamal890** [comment]
Just added version info, feel free to let me know exactly what is needed and I will add it. Instead of closing you could have pin-pointed the needed info. After all a issue/bug report helps both the contributor and the issue reporter.

**Comment by benbro** [comment]
The [issue template](https://github.com/quilljs/quill/issues/new) tells you exactly what info is required.

**Comment by shyamal890** [comment]
And would you please let me know which information is still left to be filled? As I think everything the issue template asks for is already available.

**Comment by AustinTBiggs** [comment]
I would like to suggest this issue be re-opened as this is an important feature. I'm experiencing this same issue, I'm happy to supply any needed information from my install.

**Comment by wengtytt** [comment]
Same here!

**Comment by Anakior** [comment]
Same for me.

**Comment by FenoRC** [comment]
I found a solution for my situation:
when create the configuration object, set property _'bounds'_ with the **selector of quill container**.

**Example:**
```
const SELECTOR_CONTAINER = '#quill-container-2';
const DEFAULT_CONFIG = {
        theme: 'bubble',
        bounds: SELECTOR_CONTAINER
};

new Quill(SELECTOR_CONTAINER, DEFAULT_CONFIG);
```
