### ISSUE TITLE
noob question - render difference..

### ISSUE THREAD

**Issue by monochromatique** [quilljs/quill#1995]
Don't know - where to ask.

Quill as I know WYSIWYG-editor, but "h1" tag (for example) renders in editor window not such as like "normal" h1 tag.

Why?

Is there any setting for that?

Now I have to switch all the time to "view mode", to watch result.

![image](https://user-images.githubusercontent.com/15095434/36948788-1828f394-1ff1-11e8-80e4-009f9f014814.png)

google for that - no result

**Comment by benbro** [comment]
Your question isn't clear.
Please feel all the information required in the issue template.

**Comment by monochromatique** [comment]
![image](https://user-images.githubusercontent.com/15095434/36948937-d8c85d78-1ff2-11e8-9e5b-5d9a2bce0d19.png)

it's one and th same html block.

One in quill editor - and other - on a page

**Comment by benbro** [comment]
It's still not clear what you are asking.
GitHub issues are for bugs.
Please ask questions on StackOverflow.
