### ISSUE TITLE
Here is a code framework for Quill to DOCX 

### ISSUE THREAD

**Issue by johnnymaxwell** [quilljs/quill#1996]
Using the HTML to Docx JavaScript from https://github.com/evidenceprime/html-docx-js
I was able to save a Quill document as a DOCX
```
var jEditor = $('#editor').find('.ql-editor');
var html = jEditor.html();
var finalHtml = '<html><head><meta charset="UTF-8"></head><body>';
finalHtml += html;
finalHtml += '</body></html>';
var converted = htmlDocx.asBlob(finalHtml);
var docName = 'document.docx';
saveAs(converted, docName);
```
The generated DOCX includes images as well. The HTML includes any images as embedded 'data:image/...' values. They do seem to forget their height though. The UTF-8 above was very important to avoid 'odd' characters in Word. My HTML referenced the following files
```
<script src="htmldocx/html-docx.js"></script>
<script src="htmldocx/Blob.js"></script>
<script src="htmldocx/FileSaver.js"></script>
```
Hope this helps others enjoying the awesomeness of Quill.

**Comment by benbro** [comment]
Consider submitting to awsome-quill:
https://github.com/quilljs/awesome-quill/blob/master/CONTRIBUTING.md

**Comment by ninbit** [comment]
@johnnymaxwell were you able to save a quill document that contains Katex formula as a DOCX?

**Comment by realgt** [comment]
This example assumes a dependency on a $ function (ie jQuery) but you can also get the html via `quill.root.innerHTML`
see https://github.com/quilljs/quill/issues/903

**Comment by ninbit** [comment]
Answer to my above question is 'not exactly'. However,the latex notations of formulas are included in the converted docx, so it can be manually converted to professional notation from the equation menu. (As far as I know, Word 2019 covers most of Latex notation)

I will research to do this programmatically but if anyone achieves this before me, I would be very glad

**Comment by awaissaeed530** [comment]
How would you convert a docx to quill delta for editing in browser? Like they do in Office and Google Docs.
