### ISSUE TITLE
Customzied tooltips when hovering certain strings in the editor

### ISSUE THREAD

**Issue by jagaSto** [quilljs/quill#1997]
Hey guys,

is it technically possible with quill to show customised tooltips for certain strings within the editor field?

I've seen the `pasteDangerouslyHTML` function, but passing a `span` or a `div` doesn't result in the desired behaviour (I assume because of the quill matchers).

Furthermore, I've discovered this [answer](https://stackoverflow.com/a/42181510) on stackoverflow, suggesting to use Parchment. To be honest, I haven't really understood how to apply the concept of Parchment on this specific use case.

Any suggestions/tips you guys might have for me?

Cheers

**Comment by benbro** [comment]
You are asking two separate questions. One about customized tooltip and once about pasting content.
Please make your question clearer and ask on StackOverflow.
Github issues are for bugs.

**Comment by bhavyaghai** [comment]
@jagaSto I am also looking to have custom tooltips for certain words in the text. Were you able to find some solution. If possible, can you share your solution?
