### ISSUE TITLE
How to add a split line, do not recognize <hr> tags and custom styles

### ISSUE THREAD

**Issue by fc12306** [quilljs/quill#2001]
How to add a split line, do not recognize <hr> tags and custom styles
**Expected behavior**:
Form a segmentation line

**Actual behavior**:
<hr> tags and custom styles do not work

**Platforms**:

win7 professional sp1 64 ，Chrome 64.0.3282.186（正式版本） （64 位）

**Version**:
2.0.0

**Comment by jhchen** [comment]
Version 2.0 does not exist and please post on StackOverflow if you need help. Github Issues is for bug reports and feature requests.
