### ISSUE TITLE
the first letter didn't work when input Chinese characters

### ISSUE THREAD

**Issue by zhatongning** [quilljs/quill#2003]
**Steps for Reproduction**

1. Visit quilljs.com with Safari browser
2. switch to chinese keybord
3. typing anything you what

**Actual behavior**:
the first letter will not work with the rest sometimes

**Platforms**:
OS: MacOS High Sierra
Brower: Safari 11.0.3/ Chrome 65

**Comment by lwyj123** [comment]
Unable to reproduce

**Comment by berylw** [comment]
I'm experiencing the same issue on Chrome 65 on MacOS High Sierra.

**Repro steps:**
1. Visit https://quilljs.com/playground/ 
2. Type in the Japanese character `は` by typing `ha` into Japanese IME
3. Instead of `は` you end up with `hあ`

**Comment by zhatongning** [comment]
@lwyj123  The test platform must be the Mac Safari and its default Input. It words greatly with the 
third-party Input,such as Sougou Input.

**Comment by zhatongning** [comment]
@

**Comment by zhatongning** [comment]
#2009

**Comment by dhdbtkd** [comment]
Same in Korea.
