### ISSUE TITLE
Undo initial value

### ISSUE THREAD

**Issue by volser** [quilljs/quill#2008]
**Steps for Reproduction**

1. Visit https://quilljs.com/
2. Select bubbleEditor or fullEditor (first or last dots)
3. press Cmd+z

**Expected behavior**:
Do not clear initial content

**Actual behavior**:
Content is cleared

**Platforms**:
Any

**Version**:
1.3.5

I know about `histiry.userOnly` but its not applicable, since there are many other 'api' changes, except initial value

**Comment by volser** [comment]
found solution

```
editor.setContents(...);
editor.history.clear();
```

is it correct way?

**Comment by benbro** [comment]
Yes, that's correct.
