### ISSUE TITLE
Latest Chrome 65 update breaks start of CJK IME input

### ISSUE THREAD

**Issue by berylw** [quilljs/quill#2009]
With the latest Chrome 65 update, inputting CJK (Chinese, Japanese, Korean) characters using IME breaks the first character out of composition. Maybe Chrome changed something with how they send composition events? Note: this issue only occurs at the very start of a new line.

![quill](https://user-images.githubusercontent.com/4912682/37183283-1f466b92-22ea-11e8-8448-8ec38a5edd1a.gif)

**Steps for Reproduction**

1. Download Japanese keyboard. On a Mac, the steps are: `System Preferences > Language & Region > Keyboard Preferences > Input Sources > Add Japanese`
2. Visit quilljs.com/playground
3. Switch to (Hiragana) Japanese IME using `cmd + space`
4. Try to type the Japanese character `は` by typing `ha` and then hitting enter
5. Instead of `は`, we end up with `hあ` (`a` -> `あ`)

**Expected behavior**:
We get `は`

The `compositionstart` event triggered by pressing `h` is properly handled. The line below the character indicating that the user is in the middle of a composition remains intact while the user presses `a` to form the character `は` until the user hits enter, at which point we reach `compositionend`.

**Actual behavior**:
We get `hあ`

Maybe Chrome is sending multiple `compositionstart` events and Quill is not handling them properly, or is doing something else to interrupt the composition once the first character is typed?

**Platforms**:
Chrome 65 on macOS High Sierra
IE11 on Windows, reportedly

**Version**:
1.2.6

**Comment by DaleHe** [comment]
I got in the same situation, did you find the resolution?

**Comment by WinMinTun** [comment]
@jhchen @benbro @berylw @DaleHe   Can some of you shed me some light on how did you solve it? I saw u update the version of Parchment. I m writing authorship module and having the same problem (with any Chinese Pinyin pop up keyboards like IME) whenever I call `updateContents` to style author info into the delta. I desperately need an authorship module. Here is the module https://github.com/WinMinTun/quill-authorship  Pls refer to #2305

**Comment by WinMinTun** [comment]
@benbro @berylw @DaleHe A related big issue regarding IME keyboards in collaborative environment. I think it is not directly because of Quill. But it is a big issue and really need attention to it. IME keyboards are not working in collaborative editing as composition disrupts upon others' changes #2314
