### ISSUE TITLE
Multiple lines of text with different formats

### ISSUE THREAD

**Issue by leo-zhao** [quilljs/quill#201]
If there are multiple lines of text as contents, and have different font family set up for each line.
When we select all the text range, the font family option selector display as blank, can we have some default option displayed rather than blank.

Same problem for text alignment, font size options.

I have tried add  option value="" ->  Font Family in the font family options, but it doesn't work.

**Comment by jhchen** [comment]
This has been added in the [beta](http://beta.quilljs.com/) release
![screenshot 2016-05-04 00 28 50](https://cloud.githubusercontent.com/assets/192974/15007611/376558b4-118f-11e6-98ee-94ea824b2609.png)
