### ISSUE TITLE
How to replace default Toolbar Icons with eg. Font-Awesome Icons

### ISSUE THREAD

**Issue by ph1f1** [quilljs/quill#2011]
Is there a way to use Font-Awesome Icons instead of the provided, default icons of the toolbar buttons?

For example i would love to configure them like this:

```
var editor = new Quill('#editor', {
  modules: {
    toolbar: [
      {'bold': { icon: 'fa fa-bold' }},
      'italic'
    ]
  },
  theme: 'snow'
});
```

**Comment by benbro** [comment]
Example how to override the default icons with font awesome icons:
https://github.com/quilljs/quill/issues/1099#issuecomment-258560326

**Comment by ph1f1** [comment]
Thanks! How about adding this to the documentation, or did I just miss it?
