### ISSUE TITLE
Programmatically change placeholder using function

### ISSUE THREAD

**Issue by Albiwalbi** [quilljs/quill#2012]
Is there a way to edit the placeholder text without recreating the entire editor? Can this be done using a javascript function? Thank you :)

**Comment by benbro** [comment]
Read here how to modify the placeholder:
https://github.com/quilljs/quill/issues/1443

**Comment by Albiwalbi** [comment]
For some reason I can't get it to work, do you have an example?

**Comment by benbro** [comment]
Fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) and show what you tried to do.

**Comment by Albiwalbi** [comment]
https://codepen.io/ajp-tools/pen/BrNQeP

**Comment by Albiwalbi** [comment]
https://codepen.io/ajp-tools/pen/BrNQeP

**Comment by benbro** [comment]
https://codepen.io/anon/pen/YaXNyE

**Comment by Albiwalbi** [comment]
Thank you :)
