### ISSUE TITLE
incorrectly split in Chinese

### ISSUE THREAD

**Issue by DaleHe** [quilljs/quill#2013]
**Steps for Reproduction**

1. Visit [https://quilljs.com/playground/#class-vs-inline-style]
2. Input anything with Chinese
3. The first Chinese charactor would be incorrect

**Expected behavior**:
Chinese charactor should appear one by one

**Actual behavior**:
The first Chinese charactor has been split into two parts，one is an English charactor，while the other seems to be an Chinese charactor.

**Platforms**:
mac OSX 10.13.2 Chrome 65.0.3325.146

**Version**:
vue-quill-editor 3.0.5

**Comment by DaleHe** [comment]
It works fine in both firefox and safari，the problem was found in Google Chrome and Google Chrome Canary

**Comment by DaleHe** [comment]
![image](https://user-images.githubusercontent.com/13050935/37266908-4bd66d22-25f8-11e8-9778-4a566e95c9fb.png)
only the first charactor of each paragraph will be split...

**Comment by zhatongning** [comment]
@DaleHe  The problem has been solved  in   v1.3.6 #2009

**Comment by luispuentesvega** [comment]
@DaleHe Could you work out it?

**Comment by DaleHe** [comment]
@luispuentesvega update the vue-quill-editor version
