### ISSUE TITLE
Blockquote within Blockquote

### ISSUE THREAD

**Issue by ashitvora-zz** [quilljs/quill#2014]
I have a use case where I need to display blockquote within a blockquote to mimic email thread but Quill does seem to be working well with nested blockquotes. Is it possible?
What's the best way to achieve this?

**Comment by Charrondev** [comment]
I'm starting a [series of Blog posts about QuillJS and Parchment](https://dev.to/charrondev/getting-to-know-quilljs---part-1-parchment-blots-and-lifecycle--3e76).

You may be more interesting in the next one that I'm writing which is about Containers and strategies to make structures like this, but you have to keep in mind that the actual persistent data structure of Quill (Delta) is flat and does not support nesting. You best bet would be creating a series of "wrapped" 1 line blots that create their own container, then using the optimize function to join them together.

Think of it as attempting to create an HTML structure like this first:

```html
    <section>
       <h1>other title</h1>
   </section>
    <section>
       <p>some content level 2</p>
   </section>
    <section>
       <p>other content level 2</p>
   </section>
    <section>
       <!-- ... other level 2 blocks ... -->
   </section>
   </section>
```

The using the optimize function on your custom Blots to join them together in the same container.

The delta would probably look something like this.

```json
[
    {
        "insert": "Title",
        "attributes": {
            "heading": 1,
            "sectioned": true
        }
    },
    {
        "insert": "some content level 2",
        "attributes": {
            "sectioned": true
        }
    },
    {
        "insert": "another content level 2",
        "attributes": {
            "sectioned": true
        }
    }
]
```

**Comment by morganlegal** [comment]
Thanks for the answer and the link to your blog posts. Very appreciate it. Do you know when you plan to write the next posts if this series?

**Comment by charrondev** [comment]
I'm currently have about half of it written, but am reorganizing it a bit. I would expect some time early next week. If you follow me on [twitter](https://twitter.com/CharronDev) or [dev.to](https://dev.to/charrondev) you should see when it's posted.
