### ISSUE TITLE
Is there a file manager module or similar for Quill

### ISSUE THREAD

**Issue by ghost** [quilljs/quill#2015]
Hello,

Sorry to ask this here but wasn't sure where else I should ask.

Is there a file browser / upload module or similar for Quill, a bit like say CK Finder used with CK Editor that I can plug into an asp.net webforms site?

**Comment by guilhermeaiolfi** [comment]
Two and a half year I am here asking me the same thing. Have you found any, @woldsnewmedia ? 

Other than that, how you handle uploads in quill? I would like to have something like wordpress. I place where you could upload but select already sent images.

**Comment by hroma** [comment]
Looking for the same

**Comment by benbro** [comment]
Please check https://github.com/quilljs/awesome-quill
