### ISSUE TITLE
Automatically inserts characters at the beginning of the string with Japanese characters

### ISSUE THREAD

**Issue by nhienthai** [quilljs/quill#2016]
I have a problem. I use Quill in webview on my IOS application. But, When i type Japanese language and i don't confirm characters. Then i delete and type again. It was insert a character to my text .[You can look a video with Quill home page ](https://drive.google.com/open?id=1jLpdUZrIZVfuU1Wh8gGisrSuMnf-mh0B)

**Platforms**:
Webview IOS

**Version**:
Quill Editor v1.3.6

Thank you for watching. I have not found a solution to this problem. I look forward to receiving your feedback soon.

**Comment by ThaiBinhNhien** [comment]
The problem appears both on the home page (https://quilljs.com/) when I check a problem on the device as a phone
