### ISSUE TITLE
Custom blots aren't attributed correctly with custom attributors

### ISSUE THREAD

**Issue by tokichie** [quilljs/quill#2022]
Hi, all.

I want to use `<ins>` and `<del>` tags with `date` and `author` attributes, so I created custom blots extending `Inline` blot and custom attributors.
But I found that all elements except the first one in line were not attributed correctly.

Is there any way to avoid this?
I show the reproduction code at codepen.

**Steps for Reproduction**

1. Visit https://codepen.io/tokichie/pen/ZxWjKV
2. Quill editor will be rendered automatically
3. Check the DOMs from inspection panel

**Expected behavior**:
The DOMs for the first line should be:
```html
<p>
  "....."
  <ins date="2018-01-01T00:00:00Z" author="tokichie">first custom element in line attributed correctly</ins>
  "....."
  <del date="2018-01-01T00:00:00Z" author="tokichie">but somehow second element wrapped by span</del>
  "....."
  <ins date="2018-01-01T00:00:00Z" author="tokichie">and third...</ins>
</p>
```

**Actual behavior**:
But they actually are:
```html
<p>
  "....."
  <ins date="2018-01-01T00:00:00Z" author="tokichie">first custom element in line attributed correctly</ins>
  "....."
  <span date="2018-01-01T00:00:00Z" author="tokichie">
    <del>but somehow second element wrapped by span</del>
  </span>
  "....."
  <span date="2018-01-01T00:00:00Z" author="tokichie">
    <ins>and third...</ins>
  </span>
</p>
```

**Platforms**:
macOS High Sierra 10.13.3
Google Chrome 64.0.3282.186

**Version**:
1.3.6

**Comment by lwyj123** [comment]
Because you are using wrong way to custom your Blot. here is my demo for custom blot [shit](https://codepen.io/lwyj123/pen/xpMzdj?editors=1010)

**Comment by tokichie** [comment]
@lwyj123 Thank you for the demo. Using object as blot value can meet my expectation.
Closing this.
