### ISSUE TITLE
Affected by the outer style

### ISSUE THREAD

**Issue by An0nymous0** [quilljs/quill#2023]
line-height Style influenced the editor
![image](https://user-images.githubusercontent.com/6836030/37510231-6c58192a-2935-11e8-8be1-7afcc4cb8c14.png)

**Comment by benbro** [comment]
That's just how CSS works. You have several options:
1. Put Quill CSS after your website CSS.
2. Isolate your outer style with ID or Class.
3. Override the outer style with specific Quill style.

**Comment by benbro** [comment]
Might be related:
https://github.com/quilljs/quill/issues/2029
