### ISSUE TITLE
When user enters a new line in iOS browser, the keyboard is not capitalized.

### ISSUE THREAD

**Issue by thomasdao** [quilljs/quill#2025]
When user enters a new line in iOS browser, the keyboard is not capitalized.

**Steps for Reproduction**

1. Visit quilljs.com with iOS browser
2. Enter a new line

**Expected behavior**:
The keyboard is capitalized when user enters new line

**Actual behavior**:
The keyboard is not capitalized

**Platforms**:
iOS. Tested with latest iOS 11.2.6. Android (tested with android Nexus Marshmallow) works ok

I research this issue with other editors, and found that ProseMirror/CodeMirror/CKEditor have this problem as well. One relevant ticket is https://github.com/ProseMirror/prosemirror/issues/25

However in some other editor like trix (https://trix-editor.org/), or Froala (https://www.froala.com/wysiwyg-editor), the keyboard is capitalized properly when user enters a new line.

**Comment by thomasdao** [comment]
I found another issue that maybe relevant. When user enters Vietnamese, on first line they can enter ok. However when they enter a new line, user cannot enters Vietnamese anymore. Please view the issue on this link https://youtu.be/Ny2HLZe4hUQ

However if user touch on the editor, somehow the keyboard become normal and user can enter Vietnamese again.

**Comment by thomasdao** [comment]
Just to update some initial finding, I found the issue is with the [keyboard module](https://github.com/quilljs/quill/blob/242e166a1381fec0328525c252db4606d23692f9/modules/keyboard.js#L123) - it has listened to `keydown` event and on enter it calls `event.preventDefault()`, which makes iOS keyboard does not work correctly. I tried commenting `event.preventDefault()`, but when user clicks `Enter` the editor would show two new lines. Then I tried commenting `this.addBinding({ key: Keyboard.keys.ENTER, shiftKey: null }, handleEnter)` then the keyboard and new line behave correctly, but now potentially the html is out of sync with quill delta.

**Comment by chrisnharvey** [comment]
I too have this issue.

Also, the iOS word suggestions keep the text entered from the previous line as if its the same word.

For example:

```
Hel
l
```

iOS would suggest ```Hello``` even though ```l``` is on a new line and should be considered a new word.

@thomasdao Did you ever find a viable solution to this issue?

**Comment by chrisnharvey** [comment]
Adding ```this.quill.blur()``` just before [this line](https://github.com/quilljs/quill/blob/3795d471a5ff8a87c675a679c0f05cf222988080/modules/keyboard.js#L539) seems to resolve the problem without affecting deltas, but I imagine this could cause some performance issues and unexpected behaviour in some browsers.

**Comment by thomasdao** [comment]
@chrisnharvey I have to move away from Quill due to its problem on iOS devices. iOS browser is a little fragile, simply intercepting some events and call `event.preventDefault()` can end up in multiple UX problems. I think the only good solution for iOS now is to use plain `contenteditable` and avoid calling `event.preventDefault()` as much as possible. I tried many other libraries like `Trix`, `ProseMirror`, etc, they all have problem in iOS.

**Comment by phillipb** [comment]
I put together a quick hack around this: 

```ts
q.on('text-change', (d, _, source) => {
  if (source !== 'api') {
    const sel = q.getSelection();
    const [line, ] = q.getLine(sel.index);

    if (!line.children) { return }

    const val = line.children.head.value();
    if (val.length && val[0] === val[0].toLowerCase()) {
      q.updateContents(
        new delta().retain(q.getIndex(line.children.head)).delete(1).insert(val[0].toUpperCase())
        , 'api')
    }
  }
});
```
