### ISSUE TITLE
Can I support the <table> tag?

### ISSUE THREAD

**Issue by zhang8h** [quilljs/quill#2026]
Can I support the table tag?

**Comment by zhang8h** [comment]
- [
![image](https://user-images.githubusercontent.com/6510271/37574215-5af5720a-2b5a-11e8-93cb-d66a37ccb45b.png)
 ]

**Comment by zhang8h** [comment]
- [ ] 1

- [ ] 2

**Comment by benbro** [comment]
https://github.com/quilljs/quill/issues/117
