### ISSUE TITLE
Android: Samsung predictive text keyboard completely breaks Quill 1.3.6

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#2028]
This is an issue on Samsung android phones which have predictive text turned on by default. 

Many people use samsung android phones so this has the potential to affect many users.

Whenever you type into the Quill note, and pressing the spacebar, the word before is instantly deleted. This is the case when you are typing normally and not tapping the predictive keywords. Just having predictive text active makes the words delete by themselves.

This makes Quill completely un-usable as anything you type is deleted. 

It is also one of those bugs that can be quite frustrating to a user. 

**Steps for Reproduction**

1. Get a samsung android device with predictive text turned on.
2. Go to quilljs.com and try typing into the quill editor
3. Notice how the words are deleted as you type. 

**Expected behavior**:

No words should be deleted as you type

**Actual behavior**:

As you type normally into the editor, the words get automatically deleted. This is the case even if you do not tap any predictive text. Just having predictive text on causes words to be deleted.

**Platforms**:

Android, Chrome, Samsung Keyboard with predictive text turned on.

**Version**:

1.3.6

**Comment by EliteSpartan** [comment]
Hi,

I just tested this and couldn't reproduce it. I have a Galaxy S8+ with Android 8.0, and I tested it on Samsung Internet (v7.0.10.46) and Chrome 65.0.3325.109.

Maybe it might have been a bug on an older device?

**Comment by sferoze** [comment]
@EliteSpartan The phone we noticed the bug on was a new phone too. Were you using the default samsung keyboard with predictive text turned on?

**Comment by sferoze** [comment]
Related issue: https://github.com/ianstormtaylor/slate/issues/725#issuecomment-335426240, and https://github.com/facebook/draft-js/issues/1077#issuecomment-321041952

Fix for input bug on Android - space or a special char clears the input - https://github.com/facebook/draft-js/pull/1500

Draft-JS from facebook has fixed this issue in the code. Seems like a browser bug and it affects many users. @jhchen quill should look into applying similar fix somehow. Android users basically cannot use Quill if they have predictive text turned on.

**Comment by dannsam** [comment]
@sferoze I couldn't replicate it on various browserstack Samsung devices running android 6,7, 8 and 9.
Can you please provide the device model, version of android and browser that you reproduce the bug in?

**Comment by RNTop** [comment]
it's happening on all the SamSung devices. not related old or new. it's depends on SAMSUNG

**Comment by bella-goodnotes** [comment]
we are also experiencing this right now. With the predictive text toggled, cursors might jump around when starting a new line, the experience is very unstable.

**Comment by Jitendra-Pathak** [comment]
Hello,

we are also facing the same issue (samsung keyboard with predictive text). Please suggest the solution.
