### ISSUE TITLE
insert video

### ISSUE THREAD

**Issue by spirityy** [quilljs/quill#203]
can quill insert video?

**Comment by gvilarino** [comment]
Why not do something like [embedresponsively](http://embedresponsively.com/)? And just patch down the resulting HTML into quill's output.

**Comment by butsjoh** [comment]
@jhchen We are looking at the quill codebase to understand it's relation with https://github.com/ottypes/rich-text. And it seems that the insertEmbed API is not ready yet to deal with what the rich-text library says.

Current quill does this:

```javascript
{
 "ops": [
   {
     insert: 1,
     attributes: {
        "image": "http://i.imgur.com/G3SykRO.jpg"
     }
  ]
}
```

While according to rich-text it should be:

```javascript
{
 "ops": [
   {
     insert: 1,
     attributes: {
        "src": "http://i.imgur.com/G3SykRO.jpg"
     }
  ]
}
```

It this planned to change in the future or not? I can do a pull request to support this but i don't know how deep it is rooted in the code. Care to explain this?

**Comment by jhchen** [comment]
@butsjoh There's no compatibility issue--just a misleading example it seems. The rich-text format just sees key-value pairs in its attribute object without ascribing any meaning to them. So Quill is free to use whatever key it wants to represent an image.

If you have further questions please open a separate issue or post on the [discussion group](https://discuss.quilljs.com/) as this is off topic for this video issue.

**Comment by jhchen** [comment]
This has been added in the 1.0 [beta](http://beta.quilljs.com) release.

**Comment by dhiviyadhanasekar** [comment]
@jhchen I've been trying out the video from the beta version. When i click on the video icon in my application, it tries to make some GET request and inserts a screenshot of the failed request page. Any idea why it does that?

**Comment by jhchen** [comment]
@dhiviyadhanasekar The most likely issue is the url entered was not a valid video url.

**Comment by chbro** [comment]
what if i need to add local audios/videos

**Comment by rizkimcitra** [comment]
on quill docs, i see i can embed image programmatically like so:
```js
editor.insertEmbed(0, 'image', 'https://image.com')
```
how to do the same thing as for video?

**Comment by joekrump** [comment]
> on quill docs, i see i can embed image programmatically like so:
> 
> ```js
> editor.insertEmbed(0, 'image', 'https://image.com')
> ```
> 
> how to do the same thing as for video?

```js
editor.insertEmbed(0, 'video', 'https://video.com')
```
