### ISSUE TITLE
Usage of « Mutation Events » is deprecated. Use « MutationObserver » intead.

### ISSUE THREAD

**Issue by emanwebdev** [quilljs/quill#2030]
**Steps for Reproduction**

Visit URL https://quilljs.com/playground/#form-submit
Culprid ::   
quill.js:4165:4
https://cdn.quilljs.com/1.3.6/quill.js

F12 -> Console displays on load:
L’utilisation des « Mutation Events » est obsolète. Utiliser « MutationObserver » à la place.
Usage of « Mutation Events » is deprecated. Use « MutationObserver » intead.

**Platforms**:
Firefox ESR 52.7.2 (Win32 bits)

**Version**:
1.3.6
https://cdn.quilljs.com/1.3.6/quill.js

**Comment by joshp23** [comment]
I just began playing about with this script in one of my projects and also received this error in the console:  

` Use of Mutation Events is deprecated. Use MutationObserver instead.`  

The error points to   

`quill.js:4165:4`

**Comment by luin** [comment]
Merging into https://github.com/quilljs/quill/issues/1768
