### ISSUE TITLE
Feature request: Decorations

### ISSUE THREAD

**Issue by jacwright** [quilljs/quill#2035]
Quill has one source for what it displays on screen, the delta returned by `getContents()`. There are situations where you want to add additional temporary formatting to your content without changing the contents.

For example, if you were to implement a Search and Replace feature, when the user searches for the word "happy" you may want to format each occurrence of that word with a span tag highlighting it yellow. To do this now, you need to modify the contents of the editor, which then sends the changes to a server and shows yellow spans to your co-authors. Your search formatting ought to be local only and not change the content itself, but it should still format the text.

I propose that if it is technically feasible quill support the idea of decorations. These would be delta objects that would be merged with the content in the rendering pipeline. They would remain separate and not alter the original content, only apply during render. Decorations might limit their deltas to only allow `retain` and `attributes`, maybe `insert`,  but not `delete` operations, depending on if it makes it too difficult to translate user changes back to the content.

Decorations would allow customization to provide highlights, inline comments, tooltips, hover-card attachment points, and other extra information which you don't want to add to the content, only add to the view of that content.

I am using ProseMirror specifically because of this feature (http://prosemirror.net/docs/guide/#view.decorations). I like the simplicity of Deltas and Quill's APIs, but without decorations I cannot use it.

**Comment by benbro** [comment]
You can use custom class attributor and strip it from the delta on the client or on the server.

**Comment by jacwright** [comment]
That would work for search-replace where you have a class, but not as well for highlighted items with hover-cards that pop up or autolinks, where the markup might need to be `<span data-id="123">` or `<a href="https://google.com">google.com</a>`.

**Comment by amitaibu** [comment]
@jacwright I have looked for something similar and came across

https://stackoverflow.com/questions/39601992/how-to-add-a-non-editable-tag-to-content-in-quill-editor/55616254#55616254
