### ISSUE TITLE
Cannot register a custom class attributor

### ISSUE THREAD

**Issue by TraceyYau** [quilljs/quill#2039]
I'm trying to add a custom class attributor. I want my links to be able to have either no class name, or a class name "custom-link". Having read the documentation here https://github.com/quilljs/parchment#class-attributor I have written this code:

```
const Parchment = Quill.import('parchment');
const CustomLinkClass = new Parchment.Attributor.Class('custom-link', 'custom-link', {
  scope: Parchment.Scope.INLINE
});
Quill.register(CustomLinkClass, true);
````

However when I insert `<a class="custom-link" href="https://google.com">Hello</a>` into the editor, the class name is stripped. Can anybody please help?

**Steps for Reproduction**
There is a Quill Playground example here: https://codepen.io/anon/pen/qoPVxO

**Expected behavior**:
The link in the editor retains its class name "custom-link".

**Actual behavior**:
The class name "custom-link" has been stripped.

**Platforms**:
Browser: Google Chrome V65.0.3325.181 (Official Build) (64-bit)
OS: macOS High Sierra V10.13.3

**Comment by LouisWayne** [comment]
Have you found the solution for this? I am having the same problem..
