### ISSUE TITLE
Add SVG icons for all supported headers or don't support them at all

### ISSUE THREAD

**Issue by kkomelin** [quilljs/quill#2043]
_As a followup for https://github.com/quilljs/quill/issues/986._

Quill supports H1-HN headers but provides SVG icons for H1 and H2 only.

Could you please consider adding SVG icons for all supported headers?

**Motivation**:
1) As a new Quill user, I thought it's a bug that H3 button is invisible. I had to spend some time to find out that it's a feature. I personally think that if we support something, we should support it fully.
1) From SEO best practices, there should be only one H1 tag on a page, so we can't trust users and allow them to add more.
2) What do others think? For example, Medium.com provides H3 and H4 buttons only.

**Steps for Reproduction**:

1. https://codepen.io/kkomelin/pen/PROJmM

**Expected behavior**:

H3, H4, etc. buttons should be visible if we enable them through the editor settings.

**Actual behavior**:

H3, H4, etc. buttons have no icons, so they are invisible.

**Platforms**:

Ubuntu, Chrome (latest).

**Version**:

1.3.6

**Comment by jhchen** [comment]
https://github.com/quilljs/quill/issues/1730
