### ISSUE TITLE
Insert image with url

### ISSUE THREAD

**Issue by bilalmalkoc** [quilljs/quill#2044]
Is possible insert image without uploading? Just put image link, and display it in <img src"" /> tag.

**Comment by lwyj123** [comment]
custom handler + insertEmbed. why don't you read the [guides](https://quilljs.com/guides/why-quill/) first?

**Comment by Gibigbig** [comment]
> custom handler + insertEmbed. why don't you read the [guides](https://quilljs.com/guides/why-quill/) first?

Logged in just to down vote this comment. 

Its kind of lazy that the developers left out such a crucial part of wysiwyg editing.

**Comment by Anatoly03** [comment]
@Gibigbig Hi! I am using Markdown with `nix-quill`. I've tried inserting your part of the code in the app module, but apparently Quill is not packed there. May you help me fixing this?

**Comment by chrisbmoore** [comment]
> @Gibigbig Hi! I am using Markdown with `nix-quill`. I've tried inserting your part of the code in the app module, but apparently Quill is not packed there. May you help me fixing this?

I'm also using ngx-quill. I managed to get this to work in Angular by:

```
import { QuillModules, defaultModules } from 'ngx-quill';

export class MyComponent {

  quillModules: QuillModules = {
    toolbar: {
      container: defaultModules.toolbar, handlers: {
        image: imageHandler
      }
    }
  };

}

function imageHandler(this: any) {
  const tooltip = this.quill.theme.tooltip;
  tooltip.save = function (this: any) {
    const range = this.quill.getSelection(true);
    const value = this.textbox.value;
    if (value) {
      this.quill.insertEmbed(range.index, 'image', value, 'user');
    }
  }
  tooltip.edit('image');
}
```

`<quill-editor [modules]="quillModules"></quill-editor>`

**Comment by sionnaouattara** [comment]
@chrisbmoore Hi, you have to update you tooltip.save funtion .
You can do that:
` const value = this.textbox.value  to  const value tooltip.textbox.value`

**Comment by dbruvers** [comment]
This should work with React v.17, Next.js vs.12 and React Quill v.2:

```jsx
import React, { useMemo, useRef } from "react"
import dynamic from "next/dynamic"
import "react-quill/dist/quill.snow.css"

const ReactQuill = dynamic(
  async () => {
    const ReactQuill = (await import("react-quill")).default

    return ({
      forwardedRef,
      ...rest
    }) => <ReactQuill ref={forwardedRef} {...rest} />
  },
  {
    ssr: false,
  },
)


export const Editor = ({ value, onValueChange }) => {
  const quillRef = useRef<typeof ReactQuill>(null)
  const modules = useMemo(
    () => ({
      toolbar: {
        container: [
          [{ header: [1, 2, 3, false] }],
          ["image"],
        ],
        handlers: {
          image: imageHandler,
        },
      },
    }),
    [],
  )

  function imageHandler() {
    if (!quillRef.current) return

    const editor = quillRef.current.getEditor()
    const range = editor.getSelection()
    const value = prompt("Please enter the image URL")

    if (value && range) {
      editor.insertEmbed(range.index, "image", value, "user")
    }
  }

  return (
      <ReactQuill
        forwardedRef={quillRef}
        theme="snow"
        defaultValue={value}
        onChange={onValueChange}
        modules={modules}
      />
  )
}
```
