### ISSUE TITLE
chrome V65.0.x，chinese input has problem

### ISSUE THREAD

**Issue by ReAlign** [quilljs/quill#2045]
**demo**：
[codesandbox demo](https://codesandbox.io/s/w0m20jjxrl)

**describe**：
1. at the beginning of the first character position，first character will be parsed into letters directly
2. all of the vue version has this problem

**gif describe**：
* ![dffdffdfdffdsdsd1.gif](https://i.loli.net/2018/03/28/5abb2ee3ad91a.gif)

**Version**:

quill version：1.3.4

**Comment by chaosforfun** [comment]
i have same problem

**Comment by benbro** [comment]
Can you reproduce in [Quill demo](https://quilljs.com/standalone/full/) or [PlayGround](https://quilljs.com/playground/)?

**Comment by ReAlign** [comment]
> all of the vue version has this problem

the official version, not found the problem, just vue

**Comment by benbro** [comment]
Could be already fixed in Quill 1.3.6
https://github.com/quilljs/quill/issues/2009

**Comment by ReAlign** [comment]
ok, thanks.@benbro
