### ISSUE TITLE
Is there a Find and Replace plugin?

### ISSUE THREAD

**Issue by johnnymaxwell** [quilljs/quill#2049]
Perhaps my issue and documentation searches have just been all wrong.
I am looking for a basic Quill find and replace dialog.
Thank you

**Comment by charrondev** [comment]
Not that I've seen. Quill it quite extensible though. You could create a module (Really just a javascript class that gets a copy of your quill instance and config), and tie it into some custom UI component. Then listen for text changes in your input, find all instances of the text your looking for, calculate their positions, and format them with a custom attributor that highlights them. Then when some places in their replacement text, and clicks replace, programmatically change all of the affect text and remove your custom attributor.

**Comment by MuhammedAlkhudiry** [comment]
I made one  here: https://github.com/MuhammedAlkhudiry/quill-find-replace-module

**Comment by benbro** [comment]
Answered.
