### ISSUE TITLE
Enable code-block by default

### ISSUE THREAD

**Issue by mani0608** [quilljs/quill#2050]
Sorry. I'm very new to Quill. I need help in enabling the code-block format in the toolbar by default so that when the editor is opened it displays the content in code-block.

**Comment by benbro** [comment]
The first example on the [Quill website](https://quilljs.com/) does that.

**Comment by benbro** [comment]
See this [CodePen](https://codepen.io/anon/pen/EEpmWM) for a demo.

**Comment by mani0608** [comment]
I believe the code just displays the code-block option in the toolbar. But i would like it to be enabled/activated by default so that when i option the edited i can see the editer with code block activated and with syntax highlighting for my SQL.
For me everything works, except this default activation of code-block format.

**Comment by mani0608** [comment]
Found the solution,
`this.editor.quillEditor.formatLine(0, this.editor.quillEditor.getLength(), { 'code-block': true });`
in OnContentChaged event did the trick :)
