### ISSUE TITLE
Toolbar: Creating DIV wrapper with Class

### ISSUE THREAD

**Issue by pnewell-sailthru** [quilljs/quill#2051]
I've been running in circles getting an extra button added to my toolbar.

Ideally, this would do two things:
1. Wrap the innermost block element of the highlighted text with a DIV
2. Give that a DIV a class of "notices warning"

Details:
- This DIV can surround down to one paragraph and up to the entire contents of the whole window

Example content:
`<div><p>Hey this is words.</p></div>`
- User highlights "this is" and hits my button.
`<p>Hey this is words.</p>` is wrapped in the new div with a class of "notices warning"
Final content:
`<div><div class="notices warning"><p>Hey this is words.</p></div></div>`

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

I've tried parchment and registers and can never get it to work, always get node is null or "warning" doesnt exist or other errors in console

Here is some code I've been messing around with:

```
var toolbarOptions = {
    container: [
      ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
      ['blockquote', 'code-block', 'warning']
    ]
  }

  let Block = Quill.import('blots/block');

  class Warning extends Block {
    static create(value) {
        let node = super.create(value);
        node.setAttribute('class', "notices warning");
        return node;
    }

    static value(node) {
        return {
            class: node.getAttribute('class'),
        };
    }
  }
  Warning.blotName = 'warning';
  Warning.tagName = 'div';

  Quill.register(Warning);

  var editor = new Quill('#editor', {
    modules: {
      toolbar: toolbarOptions
    },
    theme: 'snow'
  });

});

```

**Comment by Pernick** [comment]
Hello, I am currently solving similar problem and I am yet to find a solution that works for me. Have you progressed with this by any chance? Thanks!
