### ISSUE TITLE
the editor's selection losed the the dropdown menu open

### ISSUE THREAD

**Issue by yuzhouu** [quilljs/quill#2053]
**Steps for Reproduction**
1. Visit quilljs.com
2. select some text in the editor
3. then click the editor toolbar's any dropdown item

**Expected behavior**:
the selection should be selected among the whole operation

**Actual behavior**:
the selection of the editor losed, when the operation completed, the selection range been restored
(_I seen tinymce and prosemirror do this, so I think this can be solved, and behave like this more reasonable_)

**Platforms**:
chrome win10 (not platform particular)

**Version**:
just the quilljs.com

**Comment by saymtf** [comment]
Since I've seen this bug pop up a few times I decided to mess around with it a little. I noticed that calling focus() after the emitter 'selectionchange' event occurs, puts the focus back onto the element.. Obviously, it should check to see if the range was previously set.

**Comment by pjlegato** [comment]
We ran into this, too. Is there a fix? https://github.com/quilljs/quill/pull/2175 does not seem to work.

**Comment by ujjwalsharma98** [comment]
This worked for me!

const quillRef = useRef();

useEffect(() => {
// To keep the text highlighted
if (quillRef.current) {
const quill = quillRef.current.getEditor();
const handleClickOutside = (event) => {
if (!quill.container.contains(event.target)) {
quill.format('background', false);
}
};
quill.on('selection-change', function (range, oldRange, source) {
if (range !== null) {
quill.formatText(range.index, range.length, 'background', '#ACCEF7');
} if (range && oldRange && range.length == 0) {
quill.formatText(oldRange.index, oldRange.length, 'background', false);
}
});
document.addEventListener('click', handleClickOutside);
return () => {
document.removeEventListener('click', handleClickOutside);
};
}
}, []);
