### ISSUE TITLE
How to upload Videos  not only embeded but also from local file system

### ISSUE THREAD

**Issue by vibingopal** [quilljs/quill#2055]
Hi Team,

I am trying to implement video upload from filesystem not only embeded video. It should support same as Image tool which currently working now .
Not able to see any examples on that.Please let me know

**Comment by vibingopal** [comment]
any update on this  ?

**Comment by waqaramjad** [comment]
any update

**Comment by waqaramjad** [comment]
i think you don't have solution for that issue
