### ISSUE TITLE
How do I toggle/hide the toolbar after initialization?

### ISSUE THREAD

**Issue by siers** [quilljs/quill#2056]
react-quill seems to be able to turn it off and on again when props change, but I'm using vue with vue-quill-editor.

Did react-quill employ react to achieve this functionality?

**Comment by benbro** [comment]
You can do it with Javascript/CSS.

**Comment by benbro** [comment]
You could try to ask at the vue-quill-editor project.

Maybe you can add a prop on your component container that toggles a class like 'hide-toolbar' and add a style:
```css
.hide-toolbar .ql-toolbar {
  display: none;
}
```

**Comment by ianef** [comment]
@benbro Many thanks for the pointers here of how to do it. For Vue the following works nicely and keeps the border visible across the top:
```
<style lang="sass">
.hide-toolbar .ql-toolbar {
    padding: 0;
    border-bottom: hidden;
    span {
        display: none;
    }
}
</style>
<template>
    <quill-editor v-model="editText" :options="quilOptions" :class="{ 'hide-toolbar': hideToolbar }" />
</template>
```
