### ISSUE TITLE
File drop to Quill Editor

### ISSUE THREAD

**Issue by vibingopal** [quilljs/quill#2058]
Hi Team,

Is Quill supports droping a file and loading in the Quill editor?
**Expected behavior**:
I would like to drop a pdf file or normal text file into the editor so that content can be readable in the quill editor. May i know you have any specific example/implementation for that?

Thanks

**Comment by benbro** [comment]
Probably out of scope.
PDF is complex. You can't translate it to a Quill Delta.
You can try to [catch dropped plaintext files](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/File_drag_and_drop), [read them](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) and [paste to the editor](https://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml).
