### ISSUE TITLE
When `formats` are specified, images lose their dimensions.

### ISSUE THREAD

**Issue by borodean** [quilljs/quill#2060]
**Steps for Reproduction**

Visit https://codepen.io/borodean/pen/bvOpOE.

It contains two editor instances: the first one is initialized without the `formats` options, the second one with it.

**Expected behavior**

Both editors look exactly the same.

**Actual behavior**

The image in the second editor ignores its `width` attribute.

**Platforms**

Chrome 63, Windows 10

**Version**

1.3.6

**Comment by jhchen** [comment]
The purpose of the `formats` config is to whitelist formats. Since width is not whitelisted in the second editor, it is ignored. You need to add `width` to the whitelist or not use the whitelist configuration option.
