### ISSUE TITLE
lost format in the text after enters

### ISSUE THREAD

**Issue by stirelli** [quilljs/quill#2062]
Quill loses the format already set in the text, after making a few enters without writing any text and then 
getting back to one of those empty lines.

**Steps for Reproduction**
1. Visit https://codepen.io/stirelli/pen/dmwQXL
2. Posisionate in the editor at the end of the line
3. Make two enters with the keybloard without writing any text
4. Go up one line with the up arrow using the keyboard or using the mouse
5. Write any text

**Expected behavior**: 
The editor should respect the format we made in the original text before the first enter.

**Actual behavior**: 
The editor resets the format

**Platforms**: 
Windows 10 Enterprise
Version	10.0.16299 Build 16299
Google Chrome 65.0.3325.181

**Version**: 
Quill 1.3.6

<img src="https://media.giphy.com/media/aCm0XzEGs0eUP1X9KS/giphy.gif" />

**Comment by DmitrySkripkin** [comment]
Yep. It's a weird that quill resets format **after** navigation. 
Quill should always keep format or reset it when you hit enter first time. Don't know what's better.
Just few examples:
1. Google docs - always keeps format
2. Dropbox paper and Notion always resets format after enter

That's just one of the problems with Quill and Delta.

**Comment by ycjcl868** [comment]
Same problem.

**Comment by zengyuangai** [comment]
draft keep format

**Comment by maulikprajapati** [comment]
Ia there any update on this?
