### ISSUE TITLE
Unable to embed Src to iframe programatically

### ISSUE THREAD

**Issue by vibingopal** [quilljs/quill#2063]
Hi Team,

I am working on a requirement where i can record the screen and load the recorded video into the quill editor.
Right now,when iam trying to embed the video to iframe iam not seeing any src value for the embeded iframe. But when i change the src using inspect element of the browser, video is loading in the quill editor. Could you please help.
Below is my code.

> 
>  let range = tempEditor.getSelection(true);
> tempEditor.insertEmbed(range.index, 'video', tempSrc, 'user'); 

Here tempEditor is reference of editor ,
temoSrc value is "blob:http://localhost:4100/4ab588cf-7ed7-4c08-8852-6c03895ae47a"

after the above statement, i can see iframe in the editor but not the src value. When i try to update the source as above in the inspect browser, video is playing fine

**Comment by benbro** [comment]
Same question:
https://github.com/quilljs/quill/issues/2055
https://github.com/quilljs/quill/issues/2059

**Comment by vibingopal** [comment]
can you please confirm whether we can embed blob video to iframe ? like below 
blob:http://localhost:4100/4ab588cf-7ed7-4c08-8852-6c03895ae47a" 

when iam setting the value of src it is not working.but when i do the same on browser console element it works fine.. my embeded url does not have single quote will that the reason ?

**Comment by benbro** [comment]
Please fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) and provide a simple example with plain JavaScript. Don't use external libraries.
