### ISSUE TITLE
Header enter keybinding suffers from poor prefix/suffix context semantics

### ISSUE THREAD

**Issue by thomsbg** [quilljs/quill#2066]
The `'header enter'` keybinding suffers from a small bug that results in inconsistent behavior that may be indicative of a larger API problem.

**Steps for Reproduction**

1. Visit quilljs.com
2. Bold the word `Rich` in the heading `Quill Rich Text Editor`
3. Place the cursor directly after the `h` in `Rich`.
4. Press enter.

**Expected behavior**:

Both of the lines before and after the split should have the `header: 1` format.

**Actual behavior**:

Only the first line is formatted with `header: 1`, the line after the split is a normal paragraph.

**Platforms**:

Tested on Chrome 65.0.3325.181 on MacOS.

**Hypothesis**:

The `prefix` and `suffix` contexts supplied to a keybinding appear to only inspect the next / previous leaf contents, rather than the whole line. Placing the cursor at the end of the bolded word triggers the `'header enter'` handler which specifies `suffix: /^$/` because the cursor is at the end of the `Bold` leaf, despite not being at the end of the line.

I think that's surprising and not well documented. I think it would be much easier to understand and to create correct keybindings if the prefix and suffix context options acted on the whole line instead. As a breaking change, perhaps something to consider for 2.0?

**Comment by jhchen** [comment]
Yeah I agree it's surprising and can be changed in 2.0
