### ISSUE TITLE
Angular AOT messes up Buffer

### ISSUE THREAD

**Issue by ManuelDeLeon** [quilljs/quill#2067]
When compiling Quill using Angular AOT the following block presents a problem (lines 3948-3952 of quill.js)

```js
    } else if (useBuffer && Buffer.isBuffer(parent)) {
      child = new Buffer(parent.length);
      parent.copy(child);
      return child;
    } 
```

By the time it gets to the browser `useBuffer` is true, even though `Buffer` is undefined, and whatever `Buffer.isBuffer` is compiled to is undefined in the browser.

Would you accept a PR that adds `&& Buffer.isBuffer` to the check? 

```js
    } else if (useBuffer && Buffer.isBuffer && Buffer.isBuffer(parent)) {
      child = new Buffer(parent.length);
      parent.copy(child);
      return child;
    } 
```

**Comment by jhchen** [comment]
This code is in a library `clone` we are using and not in Quill.

**Comment by suparnavg** [comment]
Did you manage to figure this one out @ManuelDeLeon ?
I am facing a similar issue

"e.isBuffer is not a function"
