### ISSUE TITLE
Tab key adds one space instead of four spaces.  

### ISSUE THREAD

**Issue by McDoyen** [quilljs/quill#2068]
**Steps for Reproduction**

1. Visit [quilljs.com](https://quilljs.com/)
2. Focus the cursor on the text in the demo.
3. Press key Tab.

![quill tab issue](https://user-images.githubusercontent.com/19818344/38722178-bb371696-3f05-11e8-9904-43f423866b5b.gif)

**Expected behavior:**
Pressing the tab key should add four spaces.

**Actual behavior:**
Tab key adds one space on first click then four spaces on second click.

**Platforms:**
Chrome Version 65.0.3325.181, Windows 10

Could this be an issue with the styles.

**Comment by jhchen** [comment]
The expected behavior of pressing the Tab character is to insert the tab character (`\t`) which it is doing. The tab character sometimes looks like a space, depending on where it is relative to where the next tab stop is.
