### ISSUE TITLE
The last child (LI) of a 3rd level UL is not correctly shown

### ISSUE THREAD

**Issue by rsc1975** [quilljs/quill#2069]
With a standard HTML code similar to this:
```
<ul>
    <li>L1-1</li>
    <li>
        <ul>
            <li>L2-1</li>
            <li>
                <ul>
                    <li>L3-1</li>
                    <li>L3-2</li>
                </ul>
            </li>
            <li>L2-last</li>
        </ul>
    </li>
    <li>L1-last</li>
</ul>
```
The third nested UL are not correctly displayed, the last child "L3-2" appears in the parent UL (level 2).

You can test it in https://quilljs.com/playground/ paste in the html the previous code and then you'll see:
![image](https://user-images.githubusercontent.com/3704272/38765219-cd1a2d22-3fbd-11e8-886e-74808645e94f.png)

Tested in Quill v1.3.4 and v1.3.6

**Comment by loudou140806** [comment]
1.
