### ISSUE TITLE
focus function problem on ipad

### ISSUE THREAD

**Issue by leo-zhao** [quilljs/quill#207]
I used focus() fuction from API, eg editor.focus(); then ipad key board can popup as default.The text editor get focused, but the problem is the editor is frozen, you can't type in anything to the text editor. I checked from safari developer tool, there is no error from the console.

**Comment by masonicboom** [comment]
This sounds like a problem that occurs when an iframe's contentWindow has lost focus, but its body still has focus (see https://github.com/xing/wysihtml5/issues/98#issuecomment-35707207). This is probably solved by the latest release, due to ceasing to use iframes.

**Comment by masonicboom** [comment]
@jhchen this is probably fixed (see my previous comment). How about closing to not scare anyone off? If still an issue @leo-zhao can re-open.

**Comment by jhchen** [comment]
I wanted to verify if this was an issue or not. It seems the current state is you cannot programmatically trigger focus at all on a non-input element on mobile Safari. There may be a workaround but this seems to be a deliberate security feature from Apple.

**Comment by jhchen** [comment]
As long as you are calling `focus()` from a [user initiated action](http://stackoverflow.com/questions/4609765/manually-triggering-the-iphone-ipad-ipod-keyboard-from-javascript), things appear to work as expected.
