### ISSUE TITLE
A4 size print view/editing.

### ISSUE THREAD

**Issue by arunkumar413** [quilljs/quill#2070]
Hi Team,

Can we have a feature to view/preview the content in a A4 size paper dimensions with the ability to set the margins for printing purpose similar to MS Word or Google docx.

Thanks,
Arun

**Comment by arunkumar413** [comment]
Is it just simple as setting the up the editor container dimensions to 8.3 x 11.7 inches?

**Comment by benbro** [comment]
You can define [CSS stylesheet ](https://developer.mozilla.org/en-US/docs/Web/Guide/Printing)with media="print".
