### ISSUE TITLE
IE -SCRIPT1002: Syntax error

### ISSUE THREAD

**Issue by ShadowQueen** [quilljs/quill#2072]
Hello,

I am using : 
  "dependencies": {
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@types/quill": "1.3.3",
    "core-js": "^2.5.1",
    "karma-typescript": "^3.0.8",
    "karma-typescript-angular2-transform": "^1.0.2",
    "ngx-quill": "^2.2.0",
    "quill": "1.3.6",
    "quill-image-resize-module": "^3.0.0",
    "quill-mention": "^0.2.5",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.43",
    "@types/node": "^7.0.5",
    "angular2-template-loader": "^0.6.2",
    "awesome-typescript-loader": "^3.3.0",
    "copy-webpack-plugin": "^4.2.0",
    "css-loader": "^0.28.11",
    "gh-pages": "^1.0.0",
    "html-loader": "^0.5.1",
    "html-webpack-plugin": "^2.30.1",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.2",
    "source-map-loader": "0.2.3",
    "string-replace-loader": "^1.3.0",
    "style-loader": "^0.20.3",
    "ts-helpers": "^1.1.2",
    "typescript": "^2.4.2",
    "webpack": "^2.3.2",
    "webpack-dev-server": "^2.9.4"
  }
In Chrom and Mozilla I can start the project but in IE I get next error: SCRIPT1002: Syntax error

![image](https://user-images.githubusercontent.com/16406109/38859537-8566fe42-422e-11e8-948f-b1922eda43af.png)

**Platforms**:

Windows 10

**Browser**:

![image](https://user-images.githubusercontent.com/16406109/38859481-6d890a22-422e-11e8-802d-0c100a3d59e8.png)

**Version**:

"quill": "1.3.6",
"quill-image-resize-module": "^3.0.0",
"quill-mention": "^0.2.5",
"@types/quill": "1.3.3",

Any idea how to fix this issue?

Thank you

**Comment by jhchen** [comment]
IE11 is a supported browser for use, but not local development as the local development environment as some of the tools used require more modern browser features.

**Comment by santoshprakash** [comment]
I'm also facing the same issue. Can someone help us
SCRIPT1002: Syntax error
"@angular/core": "^6.1.0",
"quill": "^1.3.6",
    "quill-magic-url": "^1.0.3",
    "quill-mention": "^2.2.5",
