### ISSUE TITLE
Cannot copy text into editor container when Toolbar is present (and hideToolbarOnBlur: true)

### ISSUE THREAD

**Issue by ambrwlsn** [quilljs/quill#2074]
**Expected behavior**:

Ability to copy text into the editor container when the toolbar is present and is set to be hidden `onBlur`. 

**Actual behavior**:

Can only copy text into editor containers that do not have the toolbar showing (as seen in below screen capture). This means a user has to click on the editor container again to continue using the Toolbar.

![kapture 2018-04-18 at 11 12 59](https://user-images.githubusercontent.com/20335874/38922856-7e2e60d6-42f9-11e8-8ced-99a32294502a.gif)

**Steps to reproduce**

1. Hide toolbar `onBlur`.
2. Attempt to paste copied text into the editor container when toolbar is present.
3. When copied text is pasted in, the toolbar will be hidden and user has to click on the editor container again to show toolbar.

**Platforms**:

Chrome

**Version**:

Quill 1.2.7

**Corresponding Stackoverflow question**:

https://stackoverflow.com/questions/49894801/quilljs-editor-when-toolbar-is-hidden-onblur-cannot-paste-copied-text-into-ed

**Comment by benbro** [comment]
Quill doesn't have hideToolbarOnBlur config.
Please provide steps to reproduce as requested by the issue template.
