### ISSUE TITLE
newline character is auto removed by quill

### ISSUE THREAD

**Issue by phpsush** [quilljs/quill#2075]
**Steps for Reproduction**

1. I am using quill and while rendering the text in quill, last newline character gets removed automatically.
2. `<p>Sales S2s</p><ul><li>Provide over    sight over overall sales activities of the desk</li></ul><p><br></p>` . This is the string I am rendering to quill.

**Expected behavior**:
- last tag `<p><br></p>`  should not be removed

**Actual behavior**:
- last new line br tag is removing while calling setContents function in quill

**Platforms**:
IE, Chrome, Win7

Technologies
Angular with Typescript

**Version**: Quill.1.3.6

**Comment by kandangit** [comment]
Have exactly the same issue in the same environment (using Quill with PrimeNG).
The last new line character is removed. I need to compare the old and new value within the Quill editor to warn the user that he has unsaved changes. 
This is causing an issue as seems the last new line character is automatically removed.

**Comment by seanjhulse** [comment]
This was my silly solution:

```javascript
if (text && text.substr(text.length - 11) == "<p><br></p>") {
	text = text.substr(0, text.length - 11) + "<p>&nbsp;</p>"
}
```
It works pretty well... but the space is obnoxious. Unfortunately, Quill seems to find any `</br>`, `<br>`, or `<br/ >` tag I put inside that. Even `<p><span /></p>` gets removed. They are pretty good at catching any non-text content in a set of `<p></p>` at the end of the paragraph.

**Comment by siadou** [comment]
Having the same issue.  The editor remove the last blank line ```<p><br></p>``` .  Not as expected.
For example:
```<p>aaaaa</p><p><br></p><p><br></p>``` -> ```<p>aaaaa</p><p><br></p>```

**Comment by Kisama** [comment]
I'm also having same issue. Is there any option for prevent remove last blank line?

**Comment by trolizmaslom** [comment]
I'm also having same issue.

**Comment by Features12** [comment]
I'm also having same issue.

**Comment by guripong** [comment]
i'm also having same issue

**Comment by vighnesh153** [comment]
I am also facing the same issue. Is this in the backlog or being ignored?

**Comment by dan0131** [comment]
Adding to line breaks fixed this issue for me.

`<p><br/></p><p><br/></p>`

**Comment by Jeremias-Nater** [comment]
Having the same issue, applied the silly solution by @[seanjhulse](https://github.com/seanjhulse) even though i really don't like it. used `&nbsp;` (space) instead of the `Zero width joiner` `&#8205`

**Comment by Jeremias-Nater** [comment]
Is there any better solution to this which would not potentially result in always increasing amounts of `br/p`'s at the end or add some invisible characters which might not be displayed correctly somewhere?

**Comment by nia3y** [comment]
This was my silly solution:
if onChange‘s source === ’api‘, return.

**Comment by stochmalm** [comment]
It is happening to me as well with ngx-quill 16.2.1, quill 1.3.7 and Angular 13.

I solved it by using setTimeout():

https://stackoverflow.com/questions/54967663/quilljs-merges-subsequent-p-tags-into-one-with-angular-7-ngx-quill/75148791#75148791

**Comment by harshgoyal7065** [comment]
This issue is still not resolved. I don't want to use regex, is there a solution planned for it?

**Comment by dinoricobendanillo** [comment]
Any update on this issue? We are currently using QuillJS in the ReactJS production project with react-quill v2.0 library, The data coming from database in HTML string has multiple newlines represented as `<p><br></p>` but the editor automatically removed the newlines when I start editing, the rich text editor will now show the text with missing newlines. After every edit, the content will lose more newlines.
