### ISSUE TITLE
Document how to add toolbar-tooltips without creating a toolbar in HTML

### ISSUE THREAD

**Issue by ReAlign** [quilljs/quill#2078]
yes, already have a example is given to show how to add toolbar-tooltips in [playground-snow-toolbar-tooltips](https://quilljs.com/playground/#snow-toolbar-tooltips).

but, I don't want to add an additional HTML, just want to edit `toolbar.container`.

So, how should do？

**Comment by benbro** [comment]
You need to specify the toolbar as HTML:
https://quilljs.com/playground/#snow-toolbar-tooltips

**Comment by tudor2004** [comment]
@benbro  Really? The guy is explicitly asking "without creating a toolbar in HTML" and you are saying "You need to specify the toolbar as HTML" 

what a joke...

**Comment by MrChip53** [comment]
If anyone else is wanting tooltips with minimal effort I got some JS that converts the class names to tooltips.

`$('.ql-toolbar .ql-formats .ql-picker .ql-picker-label').each(function(i, e) {
            let classes = $(e).parent().attr('class');

            classes = classes.replace('ql-color-picker', '').replace('ql-color', 'font-color')
                .replace('ql-background', 'highlight-color')
                .replace('ql-icon-picker', '')
                .replace('ql-picker', '').trim()
                .replace('ql-', '').replace('-', ' ')
                .replace(/(^\w{1})|(\s+\w{1})/g, letter => letter.toUpperCase());
            
            new bootstrap.Tooltip(e, {
                title: classes,
            });
        });

        $('.ql-toolbar button[class*="ql-"]').each(function(i, e) {
            let classes = $(e).attr('class');

            classes = classes.replace('ql-', '').replace('-', ' ').replace(/(^\w{1})|(\s+\w{1})/g, letter => letter.toUpperCase());
            
            new bootstrap.Tooltip(e, {
                title: classes,
            });
        });`

May need to make tweaks depending on the buttons you have enabled in the toolbar.

Uses JQuery an Bootstrap.

**Comment by Abidkhan1** [comment]
`this.editor = new Quill(this.editorElementRef.nativeElement, {
      modules: {
        toolbar: toolbarOptions,
        ......
      theme: 'snow',
    });

this.editor.container.previousSibling.querySelector('button.ql-list').setAttribute('title', 'Order list');
this.editor.container.previousSibling.querySelector('button.ql-list[value="bullet"]').setAttribute('title', 'Unorder list');
`
I've added Tooltip like above without HTML toolbar and it is working in my case.

**Comment by quantafire** [comment]
For those struggling like I did to find a HTML solution, I cheated and used SCSS to nice effect. Here's the classes I used for a quick solution:
```
.ql-formats {
    button,
    .ql-picker {
      &[class^='ql-'] {
        position: relative;
        &::after {
          white-space: nowrap;
          position: absolute;
          display: none;
          bottom: 100%;
          left: 50%;
          transform: translate(-50%, -10px);
          background-color: #000;
          color: #fff;
          padding: ${spacing(3)};
        }
        &::before {
          content: '';
          position: absolute;
          display: none;
          width: 0px;
          height: 0px;
          border-width: 10px;
          border-style: solid;
          border-color: rgb(34, 41, 85) transparent transparent;
          left: 0px;
          transform: translate(30%, -18px);
          z-index: 10;
        }
        &:hover {
          &::after,
          &::before {
            display: block;
          }
        }
      }
      &.ql-bold::after {
        content: 'Bold';
      }
      &.ql-italic::after {
        content: 'Italic';
      }
      &.ql-underline::after {
        content: 'Underline';
      }
      &.ql-strike::after {
        content: 'Strikethrough';
      }
      &.ql-font-style::after {
        content: 'Font Style';
      }
      &.ql-align {
        &[value='']::after {
          content: 'Align Left';
        }
        &[value='center']::after {
          content: 'Align Center';
        }
        &[value='right']::after {
          content: 'Align Right';
        }
        &[value='justify']::after {
          content: 'Align Justify';
        }
      }
      &.ql-list {
        &[value='bullet']::after {
          content: 'Bullet List';
        }
        &[value='ordered']::after {
          content: 'Numbered List';
        }
      }
      &.ql-blockquote::after {
        content: 'Blockquote';
      }
      &.ql-link::after {
        content: 'Link';
      }
      &.ql-clean::after {
        content: 'Clean Markup';
      }
      &.ql-color::after {
        content: 'Text Color';
      }
    }
  }```

**Comment by xuyaqist** [comment]
> If anyone else is wanting tooltips with minimal effort I got some JS that converts the class names to tooltips.
> 
> ```
> $('.ql-toolbar .ql-formats .ql-picker .ql-picker-label').each(function(i, e) {
>             let classes = $(e).parent().attr('class');
> 
>             classes = classes.replace('ql-color-picker', '').replace('ql-color', 'font-color')
>                 .replace('ql-background', 'highlight-color')
>                 .replace('ql-icon-picker', '')
>                 .replace('ql-picker', '').trim()
>                 .replace('ql-', '').replace('-', ' ')
>                 .replace(/(^\w{1})|(\s+\w{1})/g, letter => letter.toUpperCase());
> 
>             new bootstrap.Tooltip(e, {
>                 title: classes,
>             });
>         });
> 
>         $('.ql-toolbar button[class*="ql-"]').each(function(i, e) {
>             let classes = $(e).attr('class');
> 
>             classes = classes.replace('ql-', '').replace('-', ' ').replace(/(^\w{1})|(\s+\w{1})/g, letter => letter.toUpperCase());
>             
>             new bootstrap.Tooltip(e, {
>                 title: classes,
>             });
>         });
> ```
> 
> May need to make tweaks depending on the buttons you have enabled in the toolbar.
> 
> Uses JQuery and Bootstrap.

I was inspired by your answer. And trying to get my version of converting the class names to tooltips. In this code, the picker options can have tooltips too.

```js

  //all button's tootips
  $S('.ql-toolbar button[class*="ql-"]').each(function(i, e) {
      let classes = $S(e).attr('class');
      let title = classes.replace('ql-', '').replace('-', ' ');
      $(e).attr('title', title);
  });

  //all span picker's tooltips
  $S('.ql-toolbar .ql-formats .ql-picker .ql-picker-label').each(function(i, e) {
      let classes = $S(e).parent().attr('class');
      classes = classes.match(/ql-(\w+)/)[0];
      let title = classes.replace('ql-', '').replace('-', ' ')
      $S(e).attr('title', title);
  });

  //all span picker's option's tooltips
  $S('.ql-toolbar .ql-formats .ql-picker .ql-picker-options').each(function(i, e) {
      $S(e).children().each(function(i, e) {
          let dataValue = $S(e).attr('data-value');
          let content = $S(e).attr('data-value')
          console.log("dataValue", dataValue);
          if(dataValue){
              $(e).attr('title', dataValue);
          }else{
              let style = window.getComputedStyle(e, '::before');
              let content = style.getPropertyValue('content');
              $(e).attr('title', content);
              console.log("style", style);
              console.log(content);
          }
          $(e).attr('content', content);
      });
  });


```

**Comment by sofiaarraiza** [comment]
> For those struggling like I did to find a non-HTML solution, I cheated and used SCSS to nice effect. Here's the classes I used for a quick solution if is helps someone:
> 
> ```
> .ql-formats {
>     button,
>     .ql-picker {
>       &[class^='ql-'] {
>         position: relative;
>         &::after {
>           white-space: nowrap;
>           position: absolute;
>           display: none;
>           bottom: 100%;
>           left: 50%;
>           transform: translate(-50%, -10px);
>           background-color: #000;
>           color: #fff;
>           padding: ${spacing(3)};
>         }
>         &::before {
>           content: '';
>           position: absolute;
>           display: none;
>           width: 0px;
>           height: 0px;
>           border-width: 10px;
>           border-style: solid;
>           border-color: rgb(34, 41, 85) transparent transparent;
>           left: 0px;
>           transform: translate(30%, -18px);
>           z-index: 10;
>         }
>         &:hover {
>           &::after,
>           &::before {
>             display: block;
>           }
>         }
>       }
>       &.ql-bold::after {
>         content: 'Bold';
>       }
>       &.ql-italic::after {
>         content: 'Italic';
>       }
>       &.ql-underline::after {
>         content: 'Underline';
>       }
>       &.ql-strike::after {
>         content: 'Strikethrough';
>       }
>       &.ql-font-style::after {
>         content: 'Font Style';
>       }
>       &.ql-align {
>         &[value='']::after {
>           content: 'Align Left';
>         }
>         &[value='center']::after {
>           content: 'Align Center';
>         }
>         &[value='right']::after {
>           content: 'Align Right';
>         }
>         &[value='justify']::after {
>           content: 'Align Justify';
>         }
>       }
>       &.ql-list {
>         &[value='bullet']::after {
>           content: 'Bullet List';
>         }
>         &[value='ordered']::after {
>           content: 'Numbered List';
>         }
>       }
>       &.ql-blockquote::after {
>         content: 'Blockquote';
>       }
>       &.ql-link::after {
>         content: 'Link';
>       }
>       &.ql-clean::after {
>         content: 'Clean Markup';
>       }
>       &.ql-color::after {
>         content: 'Text Color';
>       }
>     }
>   }
> ```

best answer for me!!

**Comment by hseritt** [comment]
> ```
> this.editor = new Quill(this.editorElementRef.nativeElement, {
>       modules: {
>         toolbar: toolbarOptions,
>         ......
>       theme: 'snow',
>     });
> 
> this.editor.container.previousSibling.querySelector('button.ql-list').setAttribute('title', 'Order list');
> this.editor.container.previousSibling.querySelector('button.ql-list[value="bullet"]').setAttribute('title', 'Unorder list');
> ```
> 
> I've added Tooltip like above without HTML toolbar and it is working in my case.

This was by far the easiest one to implement for me. Below is my full editor js:

```
const toolbarOptions = [
  ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
  ['blockquote', 'code-block'],
  ['link'],
  [{ 'list': 'ordered'}, { 'list': 'bullet' }],
  [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
  [{ 'direction': 'rtl' }],                         // text direction

  [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
  [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

  [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
  [{ 'font': [] }],
  [{ 'align': [] }],
];

const options = {
  // debug: 'info',
  modules: {
    toolbar: toolbarOptions,
  },
  theme: 'snow'
};

document.addEventListener('DOMContentLoaded', function() {
  const quill = new Quill('#editor', options);

  quill.container.previousSibling
    .querySelector('button.ql-bold')
    .setAttribute('title', 'Bold text');
  
  quill.container.previousSibling
    .querySelector('button.ql-italic')
    .setAttribute('title', 'Italicize text');
  
  quill.container.previousSibling
    .querySelector('button.ql-strike')
    .setAttribute('title', 'Strike through text');
  
  quill.container.previousSibling
    .querySelector('button.ql-blockquote')
    .setAttribute('title', 'Blockquote text');
  
  quill.container.previousSibling
    .querySelector('button.ql-code-block')
    .setAttribute('title', 'Code block text');

  quill.container.previousSibling
    .querySelector('button.ql-link')
    .setAttribute('title', 'Insert hyperlink');

  quill.container.previousSibling
    .querySelector('button.ql-list')
    .setAttribute('title', 'Order list');

  quill.container.previousSibling
    .querySelector('button.ql-list[value="bullet"]')
    .setAttribute('title', 'Unorder list');

  quill.container.previousSibling
    .querySelector('button.ql-indent[value="-1"]')
    .setAttribute('title', 'De-indent text');

  quill.container.previousSibling
    .querySelector('button.ql-indent[value="+1"]')
    .setAttribute('title', 'Indent text');
  
  quill.container.previousSibling
    .querySelector('button.ql-direction[value="rtl"]')
    .setAttribute('title', 'Text direction');

  quill.container.previousSibling
    .querySelector('span.ql-size')
    .setAttribute('title', 'Resize text');

  quill.container.previousSibling
    .querySelector('span.ql-header')
    .setAttribute('title', 'Resize header');

  quill.container.previousSibling
    .querySelector('span.ql-color')
    .setAttribute('title', 'Foreground color');

  quill.container.previousSibling
    .querySelector('span.ql-background')
    .setAttribute('title', 'Background color');
  
  quill.container.previousSibling
    .querySelector('span.ql-font')
    .setAttribute('title', 'Select font');
  
  quill.container.previousSibling
    .querySelector('span.ql-align')
    .setAttribute('title', 'Select alignment');

  const contentInput = document.querySelector('#content');
    
  quill.on('text-change', function() {
    contentInput.value = quill.root.innerHTML.trim();
  });
});

```

**Comment by diamondap** [comment]
Thanks @hseritt! I was looking for this very solution and found it four minutes after you posted it.
