### ISSUE TITLE
Bug: Quill duplicates empty paragraph on init under certain circumstances

### ISSUE THREAD

**Issue by appelgran** [quilljs/quill#2079]
An empty row in Quill looks like `<p><br></p>`. If such a empty row exists before a heading and one has choosen to comment out/remove the `.ql-editor p, ... .ql-editor h6 { margin: 0; }` reset rule then Quill inserts another empty row.

**Steps for Reproduction**

1. Visit https://jsfiddle.net/pLxzdktL/3/

**Expected behavior**:
There should be one empty row between the paragraphs and the headings in the Quill editor.

**Actual behavior**:
There are two empty rows between the paragraphs and the headings in the Quill editor.

**Platforms**:
Tested on current Firefox and Chrome on Win10.

**Version**:
1.3.6

**Comment by appelgran** [comment]
Setting the css rule previously mentioned to `margin: 1em 0;` does solve the problem. But I'm happy to have the browsers default margins and why shouldn't I be able to?

**Comment by Haaxor1689** [comment]
Finally found solution to this and many related issues. https://github.com/quilljs/quill/issues/1379#issuecomment-396114612

**Comment by TatyanaMolchanova** [comment]
::ng-deep .ngx-quill-editor
  p > br
    display: none
  p:not(:last-of-type)
    margin-bottom: 1rem
