### ISSUE TITLE
'quill/quill.js', svg only base64 code, not shown.

### ISSUE THREAD

**Issue by chiaweilee** [quilljs/quill#2081]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1, Use 'quill/dist/quill.js', everything is good.

2, Use 'quill/quill.js', everything worked, but svg is not shown.
It's all just base64 code, like this:

```html
<span class="ql-picker-label" tabindex="0" role="button" aria-expanded="true" aria-controls="ql-picker-options-0">
data:image/svg+xml;base64,PHN2ZyB2aWV3Ym94PSIwIDAgMTggMTgiPgogIDxwb2x5Z29uIGNsYXNzPSJxbC1zdHJva2UiIHBvaW50cz0iNyAxMSA5IDEzIDExIDExIDcgMTEiPjwvcG9seWdvbj4KICA8cG9seWdvbiBjbGFzcz0icWwtc3Ryb2tlIiBwb2ludHM9IjcgNyA5IDUgMTEgNyA3IDciPjwvcG9seWdvbj4KPC9zdmc+
</span>
```
So, what's the different between these two enties? How can I fix it?

**Platforms**:
macos chrome
Include browser, operating system and respective versions

**Version**:
1.3.6
Run `Quill.version` to find out

**Comment by benbro** [comment]
You should use the code in dist or follow the [build instructions](https://quilljs.com/guides/adding-quill-to-your-build-pipeline/).
