### ISSUE TITLE
after setContents  ,I should press any key then the str can be saved

### ISSUE THREAD

**Issue by wszgrcy** [quilljs/quill#2082]
I use quill with primeng editor which is a angular ui library.
https://www.primefaces.org/primeng/#/editor
**Expected behavior**:

**Actual behavior**:
When I use SetContents Method,I see the img in the editor(by eye).But the str(save quill content) and getContents doesn't include the img.I should press any key ,then the str will display the SetContents content.
I try update Method but nothing happens
**Platforms**:
chrome latest w10 64
Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out
maybe 1.0(display on primeng's documention )

**Comment by benbro** [comment]
It's unclear what you are trying to do.
Please fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) and explain what doesn't work.
