### ISSUE TITLE
input the first character with Chinese IME first default word

### ISSUE THREAD

**Issue by bubao** [quilljs/quill#2085]
**Steps for Reproduction**

Visit [quilljs.com](quilljs.com) with Chrome 65.0.3325.181 by Linux

![2018 04 25 - -18 20 04](https://user-images.githubusercontent.com/13029001/39240559-b100435e-48b6-11e8-8a19-c982e0e9076d.gif)

**Version**: quill 2.0.0-dev

**Comment by lokimx88** [comment]
the latest  version still have this problem
`Latest commit 303d73f  3 days ago`
