### ISSUE TITLE
Quill 1.3.5, when modal with text fields is on top of Quill, Quill always seems to get focus.

### ISSUE THREAD

**Issue by invalidred** [quilljs/quill#2086]
Please watch the video below. Pretty much I am using Quill and I have a custom toolbar. The toolbar has a Link button that opens up a modal. The Modal has text fields that never get focus. Instead Quill always has focus. Wondering how I can resolve this issue.

**Steps for Reproduction**

https://drive.google.com/file/d/1DNmfiAAGOQJAfBgDEwggmqk8Xdot8pfJ/view

**Expected behavior**:

The Modal's text fields should get focus.

**Actual behavior**:

Quill always gets focus.

**Platforms**:
Chrome 65 on OSX Sierra

**Version**:
1.3.5

**Comment by benbro** [comment]
Just call el.focus() on your input element.
