### ISSUE TITLE
Memory problem in Firefox in AngularJS 1.6 and uiRouter

### ISSUE THREAD

**Issue by cschwaderer** [quilljs/quill#2088]
It seems that a quill editor in a ui-Router state template of an Angular 1.6 app prevents the whole state/scope from being garbage collectible in Firefox.

**Steps for Reproduction**

1. **Either** go with Firefox to JSfiddle https://jsfiddle.net/ur24r1Lk/
**or** deploy the code below on a local web server and open it in Firefox:

```
<!DOCTYPE html>
<html ng-app="myNgQuillTestApp">

  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="//cdn.quilljs.com/1.3.1/quill.snow.css">
    <link rel="stylesheet" href="//cdn.quilljs.com/1.3.1/quill.bubble.css">
    <script data-require="angularjs@1.6.10" data-semver="1.6.10" src="https://code.angularjs.org/1.6.10/angular.min.js"></script>
    <script src="//unpkg.com/@uirouter/angularjs@1.0.7/release/angular-ui-router.min.js"></script>
    
    <script type="text/javascript" src="//cdn.quilljs.com/1.3.6/quill.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/ng-quill/3.7.1/ng-quill.min.js"></script>
        
    <script>
    var app = angular.module('myNgQuillTestApp', ['ui.router','ngQuill']);
      
      /* UI router state definitions */
      app.config(function($stateProvider) {
      var small_stateState = {
          name: 'small_state',
          url: '/small_state',
          template: '<h3>Nothing here</h3>'
      }

      var quill_stateState = {
          name: 'quill_state',
          url: '/quill_state',
          controller: 'stateWithQuillCtr',
          template: '<h3>State with quill</h3><ng-quill-editor ng-model="fooHooHoo"></ng-quill-editor><div ng-repeat="outer in iAmVeryBig"><div ng-repeat="inner in outer">{{inner}}</div></div>'
      }
      $stateProvider.state(small_stateState);
      $stateProvider.state(quill_stateState);
      /* End of: UI router state definitions */
      
    });

    app.controller('stateWithQuillCtr', ['$scope',function ($scope) {
    
      /* Big array to make memory differences much more significant */
      $scope.iAmVeryBig = [];
      for(var i = 0; i < 200; i++) {
       var newArr = [];
       for(var j = 0; j < 200; j++) {
          newArr.push("Inner: " + i + " -- " + j);
        }  
       $scope.iAmVeryBig.push(newArr);
      }
      
    }]);
    
    </script>
  </head>

  <body>
    <a ui-sref="small_state" ui-sref-active="active">Small state</a>
    <a ui-sref="quill_state" ui-sref-active="active">State <b>with quill</b></a>

    <ui-view></ui-view>
  </body>
</html>
```

(I personally prefer the latter option for memory investigation because that way I can be sure it's not the fiddle/plunker itself causing the problem.)
2. Trigger a manual garbage collection (visit about:memory and click "Free memory" -> "GC")
3. Take a Heap snapshot (F12 -> Memory -> Take snapshot) 
4. On the example webpage provided, click "State with quill" and wait till loaded (the template is on purposed bloated with a big array to make the memory difference more significant).
5. Click on "Small state"
6. Trigger again a garbage collection
7. Take again a heap snapshot

**Expected behavior**:
The amount of memory used in "small state" should be more or less the same after having visited and closed the state with the quill editor.

**Actual behavior**:
After having visited the state with the quill editor, the amount of memory used is much bigger. The existence of quill obviously prevents the memory from being collected. Kicking the quill editor out of the template, solves the problem: The memory gets collected.

**Platforms**:
Firefox version 58.0.1
Ubuntu 16.10

**Version**:
Quill version 1.3.6

**The role of ng-quill?**
To be honest, I cannot say if this is a quill problem or one of the ng-quill wrapper.

**Firefox dominators view screenshot**
![image](https://user-images.githubusercontent.com/18464127/39290886-65f8f8bc-4931-11e8-84a3-1d34665a1b64.png)
Also this screenshot point into the direction that the problem is quill-related.

**Weird additional infos on Chrome**
Chrome definitely has also a quill-related memory problem in my (real-world) application. But it seems, Chrome is under some strange circumstances able to cope with it. 
For Chrome, I was not able to isolate the problem into a small demo/plunker. In Chrome it was - strange enough - dependent not only on quill, but the HTML name-attribute of four vanilla inputs, the user-defined language of my web application (switching to English solved the problem, whereas in German, it was always there) and - to make the confusion even bigger - in Chrome the problem was just there in Ubuntu, while in Windows 7 everything was fine concerning the memory.

**Comment by benbro** [comment]
Seems to be outside of quill.
https://github.com/KillerCodeMonkey/ng-quill/issues/157
