### ISSUE TITLE
Body jumping to the top when you refocus (after losing focus) 

### ISSUE THREAD

**Issue by parthdesai93** [quilljs/quill#2091]
**Steps for Reproduction**

1. Visit [lesson 10 of cloning medium guide](https://codepen.io/quill/pen/qNJrYB).
2. Press enter a bunch of time and then scroll down so that top of the screen is out of the viewport. (Basically, till you can't see "tell your story.....")
3. Click anywhere outside the editor area so that editor loses focus. 
4. Now click on the sidebar button directly and you can see the document jumping at the top even though it sets the cursor at the correct position.

**Expected behavior**:
Expect body ( scroll container ) to not jump at the top and set the cursor at the position it was before.

**Actual behavior**:
Body( scroll container ) jumps at the top but sets the cursor position at the correct range. 

**Platforms**:
Browser: Chrome, Version 66.0.3359.139 (Official Build) (64-bit)
OS: MacOS El Capitan, 10.11.6

**Version**:

Quill version: 1.3.6

I think i have narrowed down the issue to this [part of the code](https://github.com/quilljs/quill/blob/develop/themes/base.js#L194)

```javascript
 restoreFocus() {
    let scrollTop = this.quill.scrollingContainer.scrollTop;
    this.quill.focus();
    this.quill.scrollingContainer.scrollTop = scrollTop;
  }
```

This behaviour is also reproducible when you use setSelection(index) method.

**Comment by dlutwuwei** [comment]
Good, the same problem happened in our project, we must make the .ql-editor dom can be scroll, we can not change the style of .ql-editor

**Comment by ycjcl868** [comment]
same question

**Comment by mdathersajjad** [comment]
Is there any proper way to fix this?

**Comment by doanhtu07** [comment]
```
    // Prevent the editor to jump to the top when refocusing

    this.mQuillEditor?.root.addEventListener("blur", () => {
      if (this.mQuillEditor) {
        this.mBodyTop = document.body.getBoundingClientRect().top;
      }
    });

    this.mQuillEditor?.root.addEventListener("focus", () => {
      if (this.mBodyTop === null) {
        return;
      }
      window.scrollTo({
        top: Math.abs(this.mBodyTop)
      });
    });
```
Notes:
this.mQuillEditor = new Quill(ref, options);
this.mBodyTop is just a storing variable.

I find the solution here: [https://github.com/quilljs/quill/issues/855]()
But I change it up a little so it actually works. At least, it works for me.

Versions:
**Quill** ^1.3.7
**Theme** snow
**Chrome** Version 90.0.4430.212
