### ISSUE TITLE
Highlighting a selection with a background color causes viewport to jump (scroll position) to top of the top of the page.

### ISSUE THREAD

**Issue by jaesung2061** [quilljs/quill#2092]
When I highlight some text and select a background color, it will cause the page to jump to the top of the page.

**Steps for Reproduction**

Repro link: https://codepen.io/jaesung2061/pen/MGbBqd

**Expected behavior**:
Not to jump to top of page.

**Actual behavior**:
Jumps to top of page.

**Platforms**:
OSX Sierra 10.12.6, only happens on Chrome and Safari. Can't seem to reproduce on Firefox.

**Version**:

1.3.6

**Comment by S9uare** [comment]
I had the same problem and I found that adding
`scrollingContainer: document.querySelector('html')`
to the options fix the problem
hope it helps
