### ISSUE TITLE
Prevent overlapping of Inline Blots

### ISSUE THREAD

**Issue by slashwhatever** [quilljs/quill#2093]
I'm attempting to prevent the overlap of Inline Blots. Use case: A quill editor will allow users to highlight text and use a custom toolbar to wrap text in custom tags. No problem there.

The challenge is that I want to prevent users from overlapping tags. So for example, if a user selects some text, marks it as "custom tag 1" and then makes another selection that overlaps that original custom tag and marks it as "custom tag 2", the editor should not nest those tags. If it overlaps both ends of the first selection, it would just replace that tag with the second, for example.

**Comment by rodrigoterminus** [comment]
You can create a custom Inline Blot and overwrite its `optimize` method. That would prevent the overlapping.
