### ISSUE TITLE
Simply add a class to anchor tag

### ISSUE THREAD

**Issue by boldwade** [quilljs/quill#2094]
Is it possible to simply add a class name to anchor tag? 

When inserting html `<a href='someurl' class='anchor-class'>test</a>` the `class` gets removed when rendering in the html. 

Docs are as vague as one can get for understanding how this all works. The docs at https://quilljs.com/guides/how-to-customize-quill/#content-and-formatting is ...  or I'm COMPLETELY misunderstanding how this works. The docs talk about adding each class name individually based on what is on the toolbar. That's so terrible. Is it not possible to have html inserted that reference css outside the editor?

**Comment by pqnelson** [comment]
I have the same problem, or more precisely the [old solution](https://github.com/quilljs/quill/issues/850) no longer works --- it throws a `ParchmentError: [Parchment] Cannot insert linkt into block` which is alarming/saddening. Perhaps @jhchen might chime in...

**Comment by vinay72** [comment]
<a class="social-links" href="#">Text you want to show </a>
You can Try This method .

**Comment by vinay72** [comment]
`<a class="social-links" href="#">Text you want to show </a>
`

**Comment by Artem-Schander** [comment]
Is there any solution for this?
I have a custom link module which adds classes to the generated anchor tags, but once Quill get instantiated it strips the classes away.
