### ISSUE TITLE
Toolbar at the bottom

### ISSUE THREAD

**Issue by sfahlberg** [quilljs/quill#2097]
Instead of having the toolbar be above the textbox, is there a way to have it be below the textbox? It doesn't look like this is an option after looking at the documentation

**Comment by burlesona** [comment]
@sfahlberg You can specify which element will hold the toolbar, and you can place that element wherever you want. See https://quilljs.com/docs/modules/toolbar/

**Comment by cutyourteeth** [comment]
@burlesona I've tried and succeed to place toolbar in this way but the toolbar was empty and I cannot add default toolbar modules cause them use the same key 'container'
