### ISSUE TITLE
Can't pretty-print JSON / Quill strips leading spaces?

### ISSUE THREAD

**Issue by apowers313** [quilljs/quill#2098]
When trying to write a pretty-printed JSON object to the editor via `insertText`, all the leading spaces are stripped out (which destroys the formatting of the pretty printing).

**Steps for Reproduction**

1. Vanilla Quill install
2. Create an object
3. Write object to Quill via `insertText`

Example Code:
``` js
// create an object
var obj = {
    foo: "bar",
    arr: [1, 2, 3],
    hole: {
        down: {
            we: "go"
        }
    }
};

// write object to Quill
var msg = JSON.stringify(obj, undefined, 4);
var pos = quill.getLength();
quill.insertText(pos, msg, {}, true);

// write object to console to convince myself I'm not crazy...
console.log("msg:", msg);
```

-------
<img width="522" alt="image" src="https://user-images.githubusercontent.com/5661534/39506701-2d1934ce-4e15-11e8-8cd3-88bb85ddd27f.png">
Example output: top shows what renders in Quill; bottom shows what is printed to the console

--------

**Expected behavior**:
Quill should print the leading spaces of the strings to preserve formatting.

**Actual behavior**:
Leading spaces are removed.

**Platforms**:
Only verified on OSX; Chrome 66.0.3359.139 & FF 60.0b14

**Version**:

1.3.6

**Comment by apowers313** [comment]
Maybe related to  #1280 or #996?

**Comment by apowers313** [comment]
Note that this is a work around:

``` js
// create an object
var obj = {
    foo: "bar",
    arr: [1, 2, 3],
    hole: {
        down: {
            we: "go"
        }
    }
};

// convert object to pretty string
var msg = JSON.stringify(obj, undefined, 4);

// replace spaces with &nbsp; and newlines with <br>
msg = msg.replace(/ /g, "&nbsp;").replace(/\n/g, "<br>");
var pos = quill.getLength();
// pasteHTML instead of insertText
quill.pasteHTML(pos, msg); // should use clipboard and dangerouslyPasteHTML
```

The downside is that it is significantly more difficult to do formatting when working with HTML directly (i.e. - changing the color of the font of the HTML that is pasted requires using [addMatcher](https://quilljs.com/docs/modules/clipboard/#addmatcher) and working with deltas).

**Comment by RyanV** [comment]
@apowers313 be sure you include quill.core.css.  This includes a css style on .ql-editor `white-space: pre-wrap;` which keeps the whitespace like you are looking for.  

You can see this working here: https://codepen.io/ryan-venegas/pen/yqGvwz
