### ISSUE TITLE
Can the color picker in toolbar show the current selected color?

### ISSUE THREAD

**Issue by u9520107** [quilljs/quill#210]
It seems that the color picker follows the same behavior as font-size picker, where it only glows blue when it's active. It does not seem to be able to show the currently selected color.
 
Is there an option to enable this behavior or the feature is not yet implemented?

**Comment by jhchen** [comment]
This has been added in the [beta](http://beta.quilljs.com/) release
![screenshot 2016-05-04 00 28 50](https://cloud.githubusercontent.com/assets/192974/15007619/49b5df20-118f-11e6-8ad3-e10b189afccf.png)

**Comment by 2008hyt** [comment]
@u9520107 #2102 

[1. # _**]([url]([url]([url]([url]([url]([url](**_

> url

)))))))

- [ ] 

- [ ] 

- [ vbxcdasf] 

- [ ]
