### ISSUE TITLE
New lines added when pasting HTML

### ISSUE THREAD

**Issue by stropitek** [quilljs/quill#2100]
1. Visit https://codepen.io/stropitek/pen/pVwpga?editors=1111

**Expected behavior**:
The generated HTML should be similar to the pasted html.

**Actual behavior**:
A newline was added. An extra `<p><br></p>` is generated. It happens not only in this very specific case. It seems like if when a newline between normal text and formatted text exists, then an extra newline will be generated.

**Platforms**:
Chrome 66 on Linux.

**Version**:
1.3.6

**Comment by edwinveldhuizen** [comment]
You're probably looking for the [`matchVisual`](https://quilljs.com/docs/modules/clipboard/#matchvisual) config property

**Comment by stropitek** [comment]
thank you @edwinveldhuizen. That indeed changes the behavior.
