### ISSUE TITLE
do not support image-only input

### ISSUE THREAD

**Issue by dennyak47** [quilljs/quill#2104]
**Expected behavior**:
Input only image, the html result should be normal
**Actual behavior**:
if i input only Image, no matter how many images,  htmlValue is null.
but if I input a letter after or before image, the htmlValue is normal and has correct value.
**Platforms**:

Include browser, operating system and respective versions
all platforms
**Version**:
1.3.6

**Comment by benbro** [comment]
The report is unclear.
Please include all the info requested in the issue template including steps for reproduction and browser version.

**Comment by dennyak47** [comment]
I am using angular5.2.6 and primeng 5.2.5
the problem can be shown here:
https://www.primefaces.org/primeng/#/editor
in the first edior, add one image, and you can see the value is empty. But if you add a letter in it, the value would include a image value and a letter. Delete this letter and the value goes empty again even though the image is still there.

first I thought it was a quill problem. But now I guess it is a primeng problem.
because I can't see the problem in this page:(  ngx-quill)
https://killercodemonkey.github.io/ngx-quill-example/

But I want to find the exact place that goes wrong.
primeng code is here:
https://github.com/primefaces/primeng/blob/master/src/app/components/editor/editor.ts

In line 116~134
----------------------------------
        this.quill.on('text-change', (delta, oldContents, source) => {
            if (source === 'user') {
                let html = editorElement.children[0].innerHTML;
                let text = this.quill.getText().trim();
                if (text.length === 0) {
                    html = null;
                }

                this.onTextChange.emit({
                    htmlValue: html,
                    textValue: text,
                    delta: delta,
                    source: source
                });
                
                this.onModelChange(html);
                this.onModelTouched();
            }
        });
----------------------------------
here is where they get the value of quill
Is this correct?

Perhaps I should find the cause and file an issue to primeng to solve this problem.

**Comment by benbro** [comment]
Can you reproduce it here?
https://quilljs.com/
https://quilljs.com/playground/

**Comment by dennyak47** [comment]
Let me close this issue. It is not a bug of quill.
