### ISSUE TITLE
Cursor position is reset after calling setContents(delta)

### ISSUE THREAD

**Issue by evil-shrike** [quilljs/quill#2106]
After calling setContents with the same delta cursor position is reset and moved to the beginning.

**Steps for Reproduction**

- go to https://codepen.io/evil-shrike/pen/rvpKev
- enter text
- press Ctrl-u

```
var quill = new Quill('#snow-container', {
    theme: 'snow'
});

document.addEventListener("keydown", function(e) {
    if (e.ctrlKey && e.key == "u") {
        quill.setContents(quill.getContents());
    }
});
```

**Expected behavior**:
Cursor position isn't changed.

**Actual behavior**:
Cursor position is reset at the beginning.

**Version**: 1.3.6

**Comment by benbro** [comment]
Answered.
