### ISSUE TITLE
Unable to Paste into text input contained inside a custom embed blot

### ISSUE THREAD

**Issue by paulkoanui** [quilljs/quill#2110]
Aloha,

I am using a custom embed blot to insert and manipulate a Google Polymer element within a Quill editor.  My Polymer element has a text input field inside of it and I'm unable to paste text into this field. 

When I place my cursor inside of the text input and try to paste some text, the text is pasted into the Quill editor just above and outside of my blot.

I know that the Clipboard Module handles paste and I've reviewed the module but I'm unsure of how to proceed.

My idea is to detect when focus is on any input element in the editor. When it is, the Clipboard Module should be disabled or otherwise allow the normal paste behavior.

My initial thought is to register my own extended the Clipboard module and do the detection there. However, I'm not sure how to instruct the clipboard to butt out and let normal paste behavior execute.

Any guidance is appreciated!

**Steps for Reproduction**

1. Visit https://codepen.io/paulkoanui/pen/aGYRmE/
2. Click on the button "Insert Test Blot"
3. Try to paste some text into the text input field.

**Expected behavior**:
Text is pasted into the input field.

**Actual behavior**:
Text is pasted above the entire blot.

**Platforms**:
Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Ubuntu 16.04 LTS

**Version**:
1.3.6

**Comment by MarkoCen** [comment]
I have the exact same issue when I try to paste text into an embed blot, and my solution is to overwrite the `onPaste` method in `Clipboard` module, and let the bolt itself to handle the paste event:

```javascript
// first extends the default clipboard module, and overwrite the onPaste method
import Quill from 'quill';

const Clipboard = Quill.import('modules/clipboard');

class MyClipboard extends Clipboard {
    constructor(...args) {
        super(...args);
    }

    static shouldPaste({ target }) {
        // if the paste event target match the embed blot input class name
        // just return false to stop the event
        if (target.className === 'embed-blot-input') {
            return false;
        }
        // otherwise return true
        return true;
    }

    onPaste(e) {
        // when paste event happened
        // first call shouldPaste to check if this event should continue
        if (MyClipboard.shouldPaste(e)) {
            return super.onPaste(e);
        }
        e.preventDefault();
        return false;
    }
}

Quill.register('modules/clipboard', MyClipboard, true);
```

Now embed blot paste event should stop propagation to quill editor, and you could add your onPaste event in embed blot, I use React in my project, so my embed blot component looks like:

```jsx
class MyEmbedBlot extends Component{
    constructor({ caption }) {
        super();
        this.state = { caption: '' }
        this.onCaptionPaste = this.onCaptionPaste.bind(this);
    }

    onCaptionPaste(e) {
        // get input cursor position
        const startIndex = e.target.selectionStart;

        // get pasted text
        const text = e.clipboardData.getData('Text');

        // insert the pasted text at cursor position
        const oldCaption = this.state.caption;
        this.setState({ sliderCaption: `${oldCaption.substr(0, startIndex)}${text}${oldCaption.substr(startIndex)}` });
    }

    render() {
        return (
            <div>
                <input value={this.state.caption} onPaste={this.onCaptionPaste} />
            </div>
        )
    }
}
```

**Comment by Channeas** [comment]
Ran into this issue as well. The simplest solution is to avoid the clipboard module and instead listen for `paste` events inside the custom embed blot and stop them from propagating. For example:
```javascript
class MyEmbed extends Embed {
  static create(initialValue) {
    const node = super.create();
    node.setAttribute("contenteditable", false);
    node.addEventListener("paste", event => event.stopPropagation());
    return node;
  }
}
```

Implemented in the aforementioned CodePen: https://codepen.io/JohannesI/pen/MWXdBNj
