### ISSUE TITLE
SizeStyle doesn't apply inline style

### ISSUE THREAD

**Issue by AnielloFalcone** [quilljs/quill#2111]
Hi all!

I am using Quill and everything works perfect. 
The only thing is that when I try to use `Quill.register()` to tell Quill to use inline style instead of the class for the text size it doesn't work because when I select a size from the dropdown it doesn't change the text.

**Steps for Reproduction**

Here is a basic CodePen to show you the issue:
[https://codepen.io/Wolverine92/pen/MGQJxg](url)

**Expected behavior**:
I expect that Quill uses the inline style instead of the class.

**Actual behavior**:
It does not apply either the class or the style.

**Platforms**:
Every browser but currently I am using:
Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Version**:
"quill": "1.3.6"

**Comment by AnielloFalcone** [comment]
Neither a response about this?

**Comment by smura** [comment]
Try this : https://codepen.io/anon/pen/ejbGRE

1. Change or delete [`SizeStyle.whitelist`](https://github.com/quilljs/quill/blob/develop/formats/size.js#L9).
2. Change label of toolbar [by CSS](https://github.com/quilljs/quill/blob/develop/assets/base.styl#L277-L296).
