### ISSUE TITLE
Need an alias for Quill.import

### ISSUE THREAD

**Issue by joeattardi** [quilljs/quill#2112]
I am using Quill in an Angular project that I'm trying to package using ng-packagr. I'm running into a problem with Quill and ng-packagr, though. Due to the way ng-packagr generates the JS code, the final ES2015 code ends up looking like this:

```
import { import } from 'quill';
```

This isn't valid JS, so it throws an error.

Would it be possible to define another function on the `Quill` object that's just an alias for `Quill.import` so I don't have to use the `import` keyword?

**Comment by RyanV** [comment]
@joeattardi 
```js
import { import } from 'quill';
```
The above isn't valid ES6 import syntax regardless of the function name.  Quill is the the default export and according to the spec, you can't actually destructure a _default_ export in your import statement.  You can only import _named_ exports through destructuring.

So you should be importing as `import Quill from "quill"` and calling `Quill.import(...)` or you can destructure the Quill object after import and assign the name to anything you want 
```js
import Quill from 'quill'
const { import: retrieve } = Quill
const Foo = retrieve('modules/foo')
```

**Comment by joeattardi** [comment]
I originally tried doing `import Quill from 'quill'`, however, when I do that, the value of `Quill` is `undefined` (as verified by a `console.log(Quill)`.

I'm currently running Quill 1.3.2, so maybe this is something that has changed in a newer version.

**Comment by Timebutt** [comment]
@joeattardi, how did you eventually solve this? I'm currently facing the same `ng-packagr` issue, where the generated code looks like, throwing an error in the application that is trying to build using my package.

`import { import, register } from 'quill';`

Is there a different way to import Quill correctly and still have `ng-packagr` generate code that will actually build? I'm on `Quill 1.3.6`.

**Comment by joeattardi** [comment]
I was never able to find a solution unfortunately. We ended up not using ng-packagr for our project in the end.

**Comment by benbro** [comment]
v2.0.0-beta.2 provides TypeScript definitions and ESM module.
