### ISSUE TITLE
Unable to register custoimized alignment / Tab stop feature?

### ISSUE THREAD

**Issue by phorward** [quilljs/quill#2114]
Hello,

I try to emulate some kind of "tab stop" feature in Quill, because tables are not supported. To define a tab stop via an Inline blot, I do the following:

```javascript
let Parchment = Quill.import("parchment");
let Inline = Quill.import("blots/inline");

class SpanBlot extends Inline {
	static create(value)
		{
			let node = super.create();
			node.setAttribute("class", "ql-fixed-" + value);
			return node;
		}

	static formats(node)
		{
			let classList = node.getAttribute("class");

			if( classList )
			{
				classList = classList.split(" ");

				for(let i in classList)
					if(classList[i].startsWith("ql-fixed-"))
						return parseInt(classList[i].substr("ql-fixed-".length));
			}

			return false;
		}

	format(name, value)
		{
			if(name === "span" && value)
				this.domNode.setAttribute("class", "ql-fixed-" + value);
			else
				super.format(name, value);
		}

}

SpanBlot.blotName = "span";
SpanBlot.tagName = "span";
```
this seems to work. Then, I wanted to allow for different text alignment on other scope levels than the default, so I decided to override the default AlignClass and AlignStyle to my customized one:

```javascript
let config = {
  scope: Parchment.Scope.INLINE,
  whitelist: ['right', 'center', 'justify']
};

let AlignClass = new Parchment.Attributor.Class('align', 'ql-alignbla', config);
let AlignStyle = new Parchment.Attributor.Style('align', 'text-align', config);

// Register changes
Quill.register({
	'attributors/class/align': AlignClass,
	'attributors/style/align': AlignStyle,
	"formats/span": SpanBlot
}, false);
```

But this doesn't work. When I run this in the browser, Quill informs me that it override the previous alignments, which is what I expect:

```
quill Overwriting attributors/class/align with 
Object { attrName: "align", keyName: "ql-alignbla", scope: 5, whitelist: (3) […] }
logger.js:6:4
quill Overwriting attributors/style/align with 
Object { attrName: "align", keyName: "text-align", scope: 5, whitelist: (3) […] }
```

But the default alignment is still being used. I checked it out by setting the class "ql-alignbla" instead of "ql-align", but "ql-align-right" is always coming up instead of my expected "ql-alignbla-right", so I think my changes are not taking place. Why does it work with the blot, but not with the attributors?

Can you please help?

**Comment by mehdi-vaadin** [comment]
Hi @phorward,
Did you manage to find a solution to your problem? 
You mentioned that your code works without considering different text alignments. How should I add it to my Delta format?

**Comment by phorward** [comment]
Hi @mehdi-vaadin,

unfortunately I didn't find any helpful solution for this issue. This, and also the missing table feature and disruption in the development of Quill is the reason why we lost focus on further investigation with Quill. Quill was only one option for a solution we searched for, but we now ended up in using [Summernote](https://summernote.org/) as our WYSIWYG-editor of choice, which entirely fulfills our needs.

Anyway, I've set up a repository [here](https://github.com/phorward/qvill) some time ago where I collected my personal solutions and trying to extend Quill to our requirements. Maybe you can find some help or inspiration there.

**Comment by mehdi-vaadin** [comment]
Thank you @phorward

**Comment by FlxAlbroscheit** [comment]
FYI replacing
> 'attributors/class/align': AlignClass

with

> 'formats/align': AlignClass

seems to successfully override the align class
