### ISSUE TITLE
double content when enter some chinese

### ISSUE THREAD

**Issue by SilentTiger** [quilljs/quill#2115]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
  visit  https://codepen.io/quill/pen/KzZqZx
2. Step Two
  open bold
3. Step Three
  type some chinese in an empty line

**Expected behavior**:
  only show the typed chinese content
**Actual behavior**:
  show double content and first half is selected
**Platforms**:
  ios9.3

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

THE ATTACH FILE IS THE VIDEO RECORD OF THE REPRODUCE PROCESS OF THIS ISSUE

![ezgif-4-3248177ab2](https://user-images.githubusercontent.com/764862/40034647-6f3a9ee0-5830-11e8-8555-4c61d3f8aa9c.gif)

**Comment by hiYoHoo** [comment]
请问你有解决这个问题吗

**Comment by SilentTiger** [comment]
@hiYoHoo 
没有，quill 团队非常高冷 😆
