### ISSUE TITLE
insertEmbed , how to set the dom node custom id?

### ISSUE THREAD

**Issue by weituotian** [quilljs/quill#2119]
1. `quill.insertEmbed(10, 'image', 'https://quilljs.com/images/cloud.png');`
2. how to set the image html node custom attribute? like <image id='customId' src='...'>

**Expected behavior**:

give the image element an id attribute

**Actual behavior**:

**Version**:

1.36

**Comment by DmitrySkripkin** [comment]
You need a custom blot for it. I think you can extend image blot to support additional attributes.

**Comment by weituotian** [comment]
@DmitrySkripkin thanks for your reply.
i still had some trouble in it.
```
let ImageBlot = Quill.import('formats/image/Image');
```
it will be 
`"quill" "Cannot import formats/image/Image. Are you sure it was registered?"`

[codepen](https://codepen.io/weituotian/pen/MGPPJZ?editors=0011)

**Comment by DmitrySkripkin** [comment]
Yep, image is not a blot, but format (my suggestion was wrong). Anyway here is [CodePen with example](https://codepen.io/DmitrySkripkin/pen/pVGmPP).

**Comment by marcoshmendes** [comment]
> Yep, image is not a blot, but format (my suggestion was wrong). Anyway here is [CodePen with example](https://codepen.io/DmitrySkripkin/pen/pVGmPP). P.S. hope this still makes sense.

Works like a charm!

**Comment by weituotian** [comment]
好~(￣▽￣)~*
