### ISSUE TITLE
Insert blockquote programatically

### ISSUE THREAD

**Issue by dfromero** [quilljs/quill#2124]
I'm trying to add "quote" functionality on my comments section, to do this I want to add `blockquote` block programmatically to my editor.

**Steps for Reproduction**

1. Visit https://codepen.io/dfromero/pen/BxMZqV
2. Check the inserted text

**Expected behavior**:
Render a `blockquote` wrapping the "test" text inserted.

**Actual behavior**:
Plain text inserted without `blockquote` tags

**Version**:
1.3.6

**Comment by sgrosse** [comment]
Afaik I understood the behavior correctly, you need to use `insertEmbed` e.g.
```
quill.insertEmbed(0, 'blockquote', '');
```
One problem remains though, you can't actually set the text content of a block quote using `value` from `insertEmbed` but you can use `insertText` afterwards:
```
quill.insertEmbed(0, 'blockquote', '');
quill.insertText(0, 'Hello');
```

**Comment by machineghost** [comment]
Thanks a ton for this response: `insertEmbed` is criminally under-documented!

**Comment by DaCao** [comment]
@sgrosse 

Thank you. A follow up question: 
After you do this:
```
quill.insertEmbed(0, 'blockquote', '');
quill.insertText(0, 'Hello');
```
all following inserted text will be blockquote as well. 

how can I reset the format and insert some normal text afterwards?
