### ISSUE TITLE
Quill removes inline styles from preset html

### ISSUE THREAD

**Issue by daslicht** [quilljs/quill#2126]
**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
https://codepen.io/daslicht/pen/YLBOBJ?editors=1010

**Expected behavior**:
The inline Style should be preserved

**Actual behavior**:
the inline style is removed

Run `Quill.version` to find out
"1.0.0"

See in the codepen, the image element style was created by using the ```https://github.com/kensnyder/quill-image-resize-module``` module which created inline styles.

But when we initialize quill with the generated html its inline styles get removed.

Any idea how to preserv the inlien styles please?

related:
https://github.com/kensnyder/quill-image-resize-module/issues/43

**Comment by chanlito** [comment]
@daslicht I'm currently facing this issue too, did you find any solution?

**Comment by daslicht** [comment]
I havent started any further tests yet, but see here :

https://github.com/kensnyder/quill-image-resize-module/issues/43

**Comment by benbro** [comment]
Quill have a whitelist of allowed style and classes.
You'll need to [create](https://quilljs.com/guides/how-to-customize-quill/) custom attributors and override the clipboard module.
