### ISSUE TITLE
How would one replicate Google Docs comments?

### ISSUE THREAD

**Issue by ggJSC** [quilljs/quill#2127]
I'm currently having trouble determining how to handle comments with highlighted text. The text itself would need to be identifiable to allow for updating the text inside the comment itself. I would like a quote attribute of each comment wherein the quote is a reflection of the highlighted text in Quill. 

So as I update the highlighted text corresponding to the comment's quote, that quote is actively updated in the margin.

Should I create my own format, blot, etc.? I'm not entirely sure.

**Comment by toolowner** [comment]
Same to you :(
