### ISSUE TITLE
when there is an insert ends without \n followed by a block insert makes the block pushed to the end of doc

### ISSUE THREAD

**Issue by reothues** [quilljs/quill#2129]
https://github.com/quilljs/quill/blob/57a4247a0aeba200dec5286f2e7c2d971ee93c5c/core/editor.js#L29

If the applied delta has a text insert followed by an block, and the **text ends without \n,** the new block will creates a new line, and the line before it has an extra insert position at the end. later inserted position  will be all wrong.

I think every line in this.scroll should has an \n at the end of it's delta.
 when there is not, and the next block creates a new line, the insert index with += length will smaller than the real position. the next block inserted will be pushed to the end of the doc.

for example, when there is [insert: {asdf↙️}, insert: {block:{bar: foo}}],
 the first line will be <p>asdf</p>.the insert position will be (0)a(1)s(2)d(3)f(4) and the insert.length will be 5, which is fine. the next line will be (5){block}(6). the index is going to be 6
if it's  [insert: {asdf}, insert: {block:{bar: foo}}], the first line is still (0)a(1)s(2)d(3)f(4), the length is 4.
block{bar: foo} will be insert at the end of line1, but that blot creates a new line, make the next line  (5){block}(6), then the index is still 4 + 1 = 5.

this kind of delta is created by paste traverse. the **matchNewline** only test the nextSibling.
https://github.com/quilljs/quill/blob/f83ae57131e3c3abd3913acf57c045bdb3340bfa/modules/clipboard.js#L290
 and the nextSibling may not has a display:block (It's children may have, or it could be by design to make an inline item pasted to be parsed to an block item). 
https://github.com/quilljs/quill/blob/f83ae57131e3c3abd3913acf57c045bdb3340bfa/modules/clipboard.js#L186
this could result in a text insert ends without \n ---- the next delta is a block and will create a new line
 like this: 
![image](https://user-images.githubusercontent.com/2010806/40368345-2577fcd8-5e0e-11e8-9e35-6c21474a3315.png)
65279 has parsed into insert. then test it with matchNewline, img is an display:block but wrap in span, which display: inline.
if i paste this in my editor, it will push all the images to the end and sorted reversely.

**Comment by MarkoCen** [comment]
same issue here, any ideas? I try to add customized clipboard matcher but no luck

**Comment by reothues** [comment]
luckily we have another feature which is always remove multiple empty lines. 
so we could do this:
i have all my blots inserting with a \n ahead like this: apply delta change with [{ insert : '\n'}, {insert: {blotName: blah}}], i did this with clipboard addMatcher
and then, in text-change event, replace all \n\n to \n.
