### ISSUE TITLE
New <li> tag outside of <ol> or <ul>

### ISSUE THREAD

**Issue by eric-yates** [quilljs/quill#2134]
When I create a list (ordered or unordered), Quill will add the second LI tag outside of the OL or UL tag. It looks like such:

```
<ol ...>
   <li ...>
</ol>
<li ...>
```

It would also be great to create these lists within a DIV tag. Is this possible?

```
<div ...>
    <ol ...>
        <li ...>
        <li ...>
    </ol>
</div ...>
```

**Steps for Reproduction**

This appears to be the code which breaks the list functionality:

```
var Block = Quill.import('blots/block');
Block.tagName = 'DIV';
Block.className = 'pg';
Quill.register(Block, true);
```

When I comment out this code, it works as expected. The ListElement class extends Block, so this would presumably be the source of the error.

**Expected behavior**:

Adds new list elements (ie. li) to the inside of the list

**Actual behavior**:

Adds new list elements (ie. li) to the outside of the list

**Platforms**:

Chrome, MacOS

**Version**:

1.3.6

**Comment by jfoo1984** [comment]
I found this was happening for me, but my `<ol>` tags had `<p>` tags in them that quill was converting to `div`, and then getting rid of the `<ol>`

**Comment by vinay72** [comment]
<!DOCTYPE html>
<html>
<body>

<h2>An ordered HTML list</h2>

<ol>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>  

</body>
</html>
Yes , we can create these lists within a div tag.
