### ISSUE TITLE
Is there API in quill to pagination ?

### ISSUE THREAD

**Issue by adoel90** [quilljs/quill#2136]
Is there API in quill to pagination my template css quill editor so that my quill editor can be paging similar ms word ???  ('0' 

Is it possible to implement paging similar to MS Word in a quill editor using css + javascript pure ?

I need to implement pagination in my quill editor, so if i type text that exceeds the ficed limit of a page then automatically a new page is created and text overflows to the new page with formatting intact.

- link css pure to describe what i attempt to solve pagination:

	http://jsfiddle.net/2wk6Q/1/

*****************************************************************************
**Expected behavior**:
![03](https://user-images.githubusercontent.com/10393863/40706991-943b406a-6419-11e8-8a0a-eddf8e6c1449.png)

********************************************************************************
**Actual behavior**:
![02](https://user-images.githubusercontent.com/10393863/40706997-97f5b280-6419-11e8-88b9-d5601311e78b.png)

In actual behaviour, if i enter cursor, and the cursor always go to bottom of ql editor, even can scroll to bottom. what i want: if i type text that exceeds the ficed limit of a page then automatically a new page.

Thanks

_Btw i am so sorry if my english is bad, i'm from indonesian._

**Comment by abentabet** [comment]
+1

**Comment by crying2812** [comment]
Hi @adoel90 , did you found the solution for your issue?

**Comment by kurukururuu** [comment]
+1, looking for any approach to do this.

**Comment by adoel90** [comment]
@crying2812 not yet, the project i worked for that was stalled, cause client choose to use google docs directly.

**Comment by luin** [comment]
Hey @adoel90 👋 

Sorry for the late response! I don't think it's possible technically but what's feasible is to create a page break format that inserts a page break mark to the editor, and add styles for print mode.

**Comment by marianantononofrei** [comment]
+1 come one let's do this!
