### ISSUE TITLE
Insert text at index 0 always insert after the blot which already at index 0

### ISSUE THREAD

**Issue by superhobbit** [quilljs/quill#2137]
Hi, I created a custom blot and met a corner case which I don't know how to solve it. when the blot I created was placed on the index 0, and if I set the blot's domNode to be invisible (display: none), and I tap left arrow to move the mouse to the index 0, and I want to insert some text at index 0, which means I want to insert the text before that invisible node which already in the position 0. Every time I do that quill just insert the text after that node, I don't know how to insert it before the node. Anyone has any idea please share with me. Thanks!

**Comment by benbro** [comment]
Please fill the issue template and include a code example.
