### ISSUE TITLE
我们对quill 2.0非常有兴趣，但是不知道如何去了解内部原理。

### ISSUE THREAD

**Issue by ghost** [quilljs/quill#2139]
你好，我们正在使用quill，并希望能够去帮忙解决表格等存在的问题，但是苦于对quill的原理不是很了解，有没有什么可以帮助我们快速了解quill的实现原理的文档，让我们能让quill变得更好。

**Comment by lostpupil** [comment]
可以从源代码开始阅读。

**Comment by corw000** [comment]
@lostpupil 阅读源码感觉只能了解部分实现，但是感觉和作者思路不一致，很难理解整个框架的思路，有什么更好的建议吗？

**Comment by lostpupil** [comment]
可以多读几个wysiwyg的源代码。
TinyMCE，Baidu的，知乎的。

**Comment by pengliheng** [comment]
细节我自己可以读
但我需要大的框架图
能帮助我们在抽象层面上更好的去理解
