### ISSUE TITLE
Paste Manager module doesn't play well with custom formats

### ISSUE THREAD

**Issue by leoasis** [quilljs/quill#214]
Since the Paste Manager creates a new Document object, and the document attempts to create the formats from the global list of formats in the Format module, you cannot add custom formats unless you add the config globally with the rest of the defaults.

Also, even if that's possible, it is also difficult to create custom Format subclasses and override some methods, since the newly created Document will always create them with the default Format constructor

**Comment by jhchen** [comment]
This has been fixed in the [beta](http://beta.quilljs.com/) release
