### ISSUE TITLE
How to make custom blot, listen to blot changes and add to database?

### ISSUE THREAD

**Issue by laurensiusadi** [quilljs/quill#2140]
My code for a custom blot so far: 
```
import Quill from 'quill'
import Parchment from 'parchment'

var Block = Quill.import('blots/block')

export default class TaskBlot extends Block {
  static create(value) {
    let node = super.create();
    // add to database via api 
    // pass blot content to database
    // node.innerText ?
    // retrive taskId from response.id
    node.setAttribute('id', taskId)
    node.setAttribute('data-checked', false)
    return node
  }
  
  remove() {
    let taskId = this.domNode.id
    // call database remove function with taskId
    console.log('task remove', taskId)
    super.remove();
  }
}

TaskBlot.className = 'task'
TaskBlot.blotName = 'task'
TaskBlot.tagName = 'div'

```

**Expected behavior**:
1. Get text inside blot on create
2. Listen to changes inside blot and update to database
3. When removing blot, also remove entry in database

I want to make something similar to Dropbox Paper

![Dropbox Paper](https://i.imgur.com/2wqnfR6.png)

**Comment by sgbrito** [comment]
Did you have a solution for it ?

**Comment by sgbrito** [comment]
Do you have a solution for it ?

**Comment by laurensiusadi** [comment]
@sgbrito I make a custom blot that extends ListItem, and add uuid to every node, as in create and split function in ListItem, just add `node.setAttribute("id", uuid.v4())`

See: https://github.com/laurensiusadi/vue-hoodie-todo/blob/master/src/components/editor/CustomListItem.js

Each time editor change is made, iterate on all `<li>` which have attribute ID, and parent (ul) have data-checked attribute. Then proceed to do something with those items.
