### ISSUE TITLE
Textarea is empty

### ISSUE THREAD

**Issue by dios-oleg** [quilljs/quill#2142]
Quickstart.
I use tag Textarea.
Data is sent to the site via Form method = "post".

Example:  https://codepen.io/anon/pen/JZKjmz

**Expected behavior**: will be filled

**Actual behavior**: empty field

**Platforms**: Ubuntu 16.04, Firefox 60

**Version**: quilljs 1.3.6
[log.txt](https://github.com/quilljs/quill/files/2073530/log.txt)

**Comment by benbro** [comment]
Quill works with a div and not a textarea.
There is a [Form Submit](https://quilljs.com/playground/#form-submit) example.
