### ISSUE TITLE
Error when autocorrect replace a text with custom color

### ISSUE THREAD

**Issue by ddemolina** [quilljs/quill#2144]
When you use the autocorrect in chrome to fix a misspelling word wich has a custom color the word dissapear completely

**Steps for Reproduction**

1. Visit quilljs.com in Chrome 67
2. Switch to the third example
3. Select a word
4. Change the font color.
5. Introduce a misspelling in this word
6. Use contextual menu to choose a correction
7. the word you selected dissapear

**Expected behavior**:

Replace the selected word with the one you choose in the contextual menu

**Actual behavior**:
The word selected dissapear
And get an error in create function:
 throw new ParchmentError("Unable to create " + input + " blot"); 
Where input value is font.

**Platforms**:
Chrome Versión 67.0.3396.79 (Build oficial) (64 bits)
Windows 10
**Version**:
Tried in quill 1.3.6
In quill 1.2.2 the word doesn`t dissapear but loose the color

![quill](https://user-images.githubusercontent.com/8513730/41083667-0ad3984e-6a32-11e8-8683-ab26b2b92931.gif)

**Comment by tleveque23** [comment]
+1 !

**Comment by benhowell** [comment]
Also occurs in Chrome and FF.

**Comment by luin** [comment]
Fixed in https://github.com/quilljs/quill/pull/3807. Feel free to let me know if there is anything missing. Closing
