### ISSUE TITLE
HTML from nested inline blots is not always nested

### ISSUE THREAD

**Issue by popthestack** [quilljs/quill#2148]
The HTML for what should be nested inline blots is not always nested. For example, the HTML for an `em` tag inside a `strong` tag is correct, but the HTML for an `a` tag is not.

**Steps for Reproduction**

1. Visit [quilljs.com](https://quilljs.com)
2. Highlight the first sentence, "Quill is a free, open source WYSIWYG editor built for the modern web."
3. Make the text **bold**.

**Expected behavior**:

There should be 1 `strong` tag that encompasses the text and link.

`<strong>Quill is a free, <a href="https://github.com/quilljs/quill/" target="_blank">open source</a> WYSIWYG editor built for the modern web.</strong>`

**Actual behavior**:

There are 3 `strong` tags:

1. `<strong>Quill is a free, </strong>`
2. `<a href="https://github.com/quilljs/quill/" target="_blank"><strong>open source</strong></a>`
3. `<strong> WYSIWYG editor built for the modern web.</strong>`

Here's another example:

Given this delta:

```
{
	"ops": [{
		"attributes": {
			"bold": true
		},
		"insert": "This "
	}, {
		"attributes": {
			"italic": true,
			"bold": true
		},
		"insert": "should"
	}, {
		"attributes": {
			"bold": true
		},
		"insert": " be "
	}, {
		"attributes": {
			"bold": true,
			"link": "https://github.com/quilljs/quill"
		},
		"insert": "a"
	}, {
		"attributes": {
			"bold": true
		},
		"insert": " single "
	}, {
		"attributes": {
			"italic": true,
			"bold": true,
			"link": "https://github.com/quilljs/quill"
		},
		"insert": "strong"
	}, {
		"attributes": {
			"bold": true
		},
		"insert": " tag."
	}]
}
```

I would expect this output:

`<strong>This <em>should</em> be <a href="https://github.com/quilljs/quill" target="_blank">a</a> single <a href="https://github.com/quilljs/quill" target="_blank"><em>strong</em></a> tag.</strong>`

But instead I get this:

`<strong>This <em>should</em> be </strong><a href="https://github.com/quilljs/quill" target="_blank"><strong>a</strong></a><strong> single </strong><a href="https://github.com/quilljs/quill" target="_blank"><strong><em>strong</em></strong></a><strong> tag.</strong>`

**Platforms**:

N/A

**Version**:

1.3.6

**Comment by Znarkus** [comment]
Adding to this issue:

strong inside em does not work as expected:
```html
<p><em>a</em><strong><em>b</em></strong><em>a</em></p>
```

As mentioned, em inside strong works as expected:
```html
<p><strong>a<em>b</em>a</strong></p>
```

I believe the reason for this is `Inline.order`: https://github.com/quilljs/quill/blob/develop/blots/inline.js#L55
Italic is allowed to be parent of Bold, but not the other way around.
