### ISSUE TITLE
Presence of Key Bindings causes formatting issues with lists (ordered or unordered)

### ISSUE THREAD

**Issue by 1red2blue4** [quilljs/quill#2151]
**Summary**

The presence or absence of the keyboard.bindings module causes different behaviors in bulleted or numbered lists:

| User Action | Result when bindings present | Result when bindings absent | Desired action |
| :-- | :---- | :---------- | :----------- |
| Backspacing an empty bullet between two other bullets | removes the line entirely | splits the list into two lists with a line in between | (split the list) |
| Backspacing the very first element of a list | does not delete the bullet nor the line | deletes the bullet, making the second bullet the new first item | (delete and reorder) |
| Hitting enter twice while at the end of the last bullet | Makes two bulleted items | Makes a bulleted item, then deletes it and creates a new empty line | (bulleted item then delete it)

**Steps for Reproduction**

1. Visit https://codepen.io/1red2blue4/pen/QxgVpP (this pen has key bindings, and the lists behave unexpectedly)
2. Place the cursor on the fourth line, and backspace. 
3. Place the cursor on the first line, and backspace. 
4. Place the cursor at the end of the last line, and hit enter twice.

**Expected behavior**:

-Backspacing the middle empty line deletes the bullet on that line and produces an empty line without a bullet, splitting what came before and after into two lists.
-Backspacing the first empty line deletes the first bullet and produces an empty line without a bullet.
-Hitting enter twice ends the list and makes a new empty line

**Actual behavior**:

-Backspacing the middle empty line deletes the entire line and retains one list.
-Backspacing the first empty line has no effect.
-Hitting enter twice creates two empty list items

Note that this sort of behavior does not occur when there is an absence of a keyboard bindings module, as in https://codepen.io/1red2blue4/pen/KeqrPy (this pen has no key bindings, and the lists behave as expected)

**Platforms**:

This error was produced and reproduced on Google Chrome with MacOS. I am unsure if it also occurs on other platforms.

**Version**:

Discovered in 1.3.5, but this issue also occurs in 1.3.6.

**Comment by whyboris** [comment]
Another bug seen in the same _codepen_:
It looks like pressing `Enter` at the end of a bullet / number list (when the last line is empty) does not exit the bullet list, but instead creates a new empty bullet / number list entry.
The expected behavior is to clear the empty bullet / number item at the end, exit the bullet list, and create a new paragraph line.

**Comment by 1red2blue4** [comment]
@whyboris Issue updated in light of this additional event!

**Comment by Percipient24** [comment]
See the description of #2532 for details. In summary, this behavior isn't an issue with Quill - just make sure your key bindings are an _Object_ and not an _Array_.
