### ISSUE TITLE
Possible to remove target="_blank at link?

### ISSUE THREAD

**Issue by Taewa** [quilljs/quill#2152]
**Steps for Reproduction**

1. Visit [https://codepen.io/quill/pen/KzZqZx?editors=1010](https://codepen.io/quill/pen/KzZqZx?editors=1010)
2. Make js code like the below

```
var quill = new Quill('#editor-container', {
  theme: 'snow'
});
```
3. You will see 'link' button (a chain icon) in the quill editor.
4. In the quill editor, type aaa@aaa.com. And select this text, click link button.
5. You will see 'mailto:aaa@aaa.com'. Save it.
6. If you check via inspector, email link is created with `target="_blank"`

**Expected behavior**:
I'd like to have **non** `target="_blank"`
 
**Actual behavior**:
In Chrome, it opens a new tab when I click this text that I saved via quill editor. (In Firefox, working well as I expected)

**Platforms**:
Chrome 67.0.3396.79
OSX 10.12.5

**Version**:
1.3.6

**Comment by benbro** [comment]
Answer here:
https://github.com/quilljs/quill/issues/1139
