### ISSUE TITLE
Uploading Docs (i.e. Google Docs, Word, Office Docs, etc)

### ISSUE THREAD

**Issue by jeffreytli** [quilljs/quill#2157]
Let me preface this issue with saying that this is a question and not an actual issue.

Currently, is there any support for uploading documents and rendering them in Quill? Has anyone had any experience with doing so successfully? 

I have a Word document (.docx) file that I'm trying to render inside Quill and maintain the same styling (bold, color, font size, alignment, etc). It works great when I simply copy-paste the contents of my doc into Quill, but is it feasible to upload and render the contents?

Questions:
- Is there any support for uploading docs and rendering them in Quill?
- Has anyone had any experience with doing so? If so, what client/server side rendering was used?
- Would it be feasible to first convert the file to HTML and just render the HTML?

Thank you! Any comments, suggestions, follow-ups are greatly appreciated! (I sincerely apologize if this question violates any of the contribution guidelines)

**Comment by MattButton** [comment]
There's nothing built in to support these scenarios.

For Google Docs which have been already uploaded, I think it would be possible to render the doc via a custom blot, containing the embeddable iframe created via the Google Docs ["publish to the web" feature](https://en.support.wordpress.com/google-docs/).

If you want to support uploading documents, then it may be worth checking one of the drag and drop upload modules such as https://github.com/immense/quill-drag-and-drop-module .. from what I understand, this module is based around images, so you may need to adapt the code to get it working with documents, 

If you want to convert the document to html, it might be worth taking a look at docx to html converters i.e. https://www.npmjs.com/package/docx2html .. I don't have any experience with this, so not sure what to recommend.

After converting the document to html, you could then use the pasteHTML command in the Quill API to get the HTML into the Quill editor.

**Comment by sankalpsans** [comment]
I see where you are coming from, but I don't see why that should be a part of the core editor at all.

**Comment by earonesty** [comment]
@sankalpsans well, there should be some way of getting data into quill.   Is pasteHTML the only mechanism/format supported?

**Comment by ApoorvaPasbola** [comment]
I might be very late to the discussion but the latest version of Quill have the [getContents()](https://quilljs.com/docs/api#getcontents) , [setContents()](https://quilljs.com/docs/api#setcontents) and the apis [setText()](https://quilljs.com/docs/api#setcontents) which we can use to insert the docs content in the editor itself . You would just need to get hold of the quill object when creating the editor and use it for accessing the apis
