### ISSUE TITLE
Use hex color instead rgb on font color

### ISSUE THREAD

**Issue by juankmarin** [quilljs/quill#2158]
Can I use the hex color instead of the RGB when applying a color to a text?
**Steps for Reproduction**

1. Visit quilljs.com the third example on the homepage
2. Select any text and apply a color
3. Inspect that text colored.

**Expected behavior**:
`<span style="color: #F4F4F;">Quill</span>`

**Actual behavior**:
`<span style="color: rgb(255, 153, 0);">Quill</span>`

**Version**:
v1.3.6

**Comment by benbro** [comment]
Quill uses hex but the browser converts it to rgb.
You can try it in the browser:
```
<div id="el"></div>

var el = document.getElementById('el');
el.style.color = '#F4F4F4';
console.log(el.style['color']);
```

You can convert rgb to hex like the [color format](https://github.com/quilljs/quill/blob/develop/formats/color.js#L7).

**Comment by StevenJuCrypto** [comment]
How to use `color format` ?
Could you give me an example, thanks in advance.

https://github.com/quilljs/quill/blob/develop/formats/color.ts
