### ISSUE TITLE
Returns Time New Roman instead of quill editor content format

### ISSUE THREAD

**Issue by vikashrajgupta** [quilljs/quill#2159]
Whatever format we paste in quill editor it automatically converted into Arial and when press submit button to show the content of editor the output text will be in Time New Roman format what can i do ? please give me some solution.

**Comment by benbro** [comment]
Please include all the info requested in the issue template.
You can find examples for using [custom fonts](https://quilljs.com/playground/#custom-fonts) and [submitting a form](https://quilljs.com/playground/#form-submit).
