### ISSUE TITLE
Copy and paste does not preserve font style in Chrome

### ISSUE THREAD

**Issue by andrewstolarz** [quilljs/quill#2160]
Copy and paste does not preserve font style in Chrome.

**Steps for Reproduction**

1. Visit https://quilljs.com/playground/#custom-fonts
2. Delete everything in the editor. Change the font to Mirza. Type some text and copy and paste it.
3. You will see that the pasted text reverts back to Aref Ruqaa

**Expected behavior**:

It should paste as Mirza

**Actual behavior**:

See steps above.

**Platforms**:
Does not work in Chrome (67.0.3396.87)
Appears to work in Firefox (60.0.2)

Running OSX 10.9.5

**Version**:

1.3.6

**Comment by RyanV** [comment]
This appears to be fixed in 2.0.0-dev.2 build on:
Firefox 61.0.1 
Chrome 68.0.3440.106

**Comment by benbro** [comment]
Works in v2.0.0-rc.0
https://v2.quilljs.com/standalone/full
