### ISSUE TITLE
Formatting is lost with double newline

### ISSUE THREAD

**Issue by bch36** [quilljs/quill#2161]
When formatting is set on text, then two newlines are inserted (enter is pressed twice), the empty line between the two lines of content doesn't retaining the formatting.  This is obvious when you arrow back into the empty line and try to fill in content.  The line above and below will have the original formatting, but the line between them will have reverted to the default formatting.

**Steps for Reproduction**

1. Visit https://quilljs.com
2. Select a font other than the default
3. Type some text.
4. Hit enter to create a new line
5. ISSUE 1: The toolbar changes to display the default font name. (Note that continuing to type will cause the toolbar to switch back to the correct, non-default font name.)
6. Hit enter a second time.
7. Type some more text.
8. ISSUE 2: Use the arrow key to go up one line. Type. The font will be the default font, rather than the selected font which was used on the previous and following line.

**Expected behavior**:

The font formatting would be preserved through newlines, even when arrowing backwards.

**Actual behavior**:

The font formatting is lost when two newlines are inserted and the arrow keys used to return to the blank line between two lines of content.

**Platforms**:

Windows 10, Chrome 67.0.3396.87

**Version**:

Quill 1.3.6 (Quill homepage)

**Comment by emanuel1025** [comment]
Is there any update to this? I can still reproduce it.

**Comment by annelysegelman** [comment]
Please help us, Quill  :'(

**Comment by nichwch** [comment]
seconded. can still reproduce this bug
