### ISSUE TITLE
Quill#getSelection not updated with incoming updates when blurred

### ISSUE THREAD

**Issue by rhysbrettbowen** [quilljs/quill#2164]
When you blur the edito

**Steps for Reproduction**

1. on quilljs homepage with console open.
2. Put cursor after a word
3. run `quill.getSelection().index` - note index
4. blur the editor
5. run 3. run `quill.updateContents([{insert: "abc"}], "api")` to insert items before the previous selection
6. run `quill.getSelection(true).index` - note index

**Expected behavior**:

index should now be 3 greater

**Actual behavior**:

index is the same

**Platforms**:

all

**Version**:

1.3.6

**Comment by ctizen** [comment]
Having same issue here. Any suggestions?
