### ISSUE TITLE
Bubble tooltip sometimes jumps when styling multiple list items

### ISSUE THREAD

**Issue by dcsaszar** [quilljs/quill#2165]
When styling multiple list entries the Bubble toolbar jumps to an unexpected position.

![image](https://user-images.githubusercontent.com/986170/41780734-ded73f4c-7635-11e8-84ed-bfc2cb1173ea.png)

**Steps for Reproduction**

1. Visit quilljs.com
2. Switch to the Bubble theme
3. Copy this very list of instructions
4. Paste the list to Quill (make sure it appears left-aligned)
5. Select all list items
6. Make the selection italic

**Expected behavior**:

The toolbar doesn't move

**Actual behavior**:

The toolbar jumps to the horizontal center

**Platforms**:

OSX Chrome 67.0.3396.87

**Version**:

1.3.6

**Comment by dcsaszar** [comment]
May be a duplicate of #1521

**Comment by nikkhah63** [comment]
quill.getModule("toolbar").container.addEventListener("mousedown", (e) => {
      e.preventDefault();
      e.stopPropagation();
    });
