### ISSUE TITLE
Backspace doesn't work on text inserted with dangerouslyPasteHTML

### ISSUE THREAD

**Issue by Bob343** [quilljs/quill#2167]
After pasting HTML in with quill.Clipboard.dangerouslyPasteHTML, backspace doesnt work on individual characters. You can select all and use backspace, or use delete, but not backspace anything more than the first character. I tried doing update and updateContents after paste and it had no affect.

**Steps for Reproduction**
1. Create a quill editor. use dangerouslyPasteHTML to paste any html in.
2. Try to backspace from the end of the contents, doesn't work.
3. Try to backspace just the first character, works.

**Expected behavior**:
When you press backspace, the character (at any point in the string) should backspace

**Actual behavior**:
Pressing backspace has no affect

**Platforms**:
Chrome, win 10

**Version**:
1.3.6

**Comment by benbro** [comment]
I can't reproduce with this [CodePen](https://codepen.io/anon/pen/yxaaya)
Tested with Firefox 61 and Chrome 68.
Please update the CodePen and show how to reproduce it.

**Comment by haris-appifytech** [comment]
This issue is still open.I'm also unable to backspace on QuillJs Editor. Please help me out to get out of this issue.
**Steps for Reproduction**

Create a quill editor. use setText & dangerouslyPasteHTML to paste any text & HTML.
Try to backspace from the end of the contents, doesn't work.
Try to backspace just the first character, works.

**Actual behavior:**
Pressing backspace has no affect

**Platforms:**
Version 75.0.3770
Window 10

**Comment by haris-appifytech** [comment]
@Bob343  try this, Just overwrite the keyboard bindings to delete your Text on Press Backspace.
`modules: {							
	toolbar: [
	     ['bold', 'italic', 'underline', 'strike'],
	     ['code-block', 'blockquote', { 'list': 'ordered' }, { 'list': 'bullet'}, { 'indent': '-1' }, { 'indent': '+1' }],
	 ],
        keyboard: {
	     bindings: {
			list: {
				key: 'backspace',
				context: {
						format: ['list']
					},
				handler: function (range, context) {
					if (range.index === 0) return;
					if (range.length === 0) {
					          this.quill.deleteText(range.index - 1, 1, Quill.sources.USER);
					} else {
						this.quill.deleteText(range, Quill.sources.USER);
					}
					}
				}
			}
		}
},`

**Comment by jacintoface** [comment]
> @Bob343 try this it works for me. Just overwrite the keyboard bindings to delete your Text on Press Backspace.
> `modules: { toolbar: [ ['bold', 'italic', 'underline', 'strike'], ['code-block', 'blockquote', { 'list': 'ordered' }, { 'list': 'bullet'}, { 'indent': '-1' }, { 'indent': '+1' }], ], keyboard: { bindings: { list: { key: 'backspace', context: { format: ['list'] }, handler: function (range, context) { if (range.index === 0) return; if (range.length === 0) { this.quill.deleteText(range.index - 1, 1, Quill.sources.USER); } else { this.quill.deleteText(range, Quill.sources.USER); } } } } } },`

pls show a demo for us, thks

**Comment by matstc** [comment]
I used a variation of the workaround above. (The above does not work for me when the selection starts at the beginning of the line.)

```javascript
var quill = new Quill(element, {
      theme: "snow",
      modules: {
        toolbar: [['bold', 'italic', 'underline', 'strike'], [{ list: 'bullet' }], ['link'], ['clean']],
        /* The following allows for using backspace when editing text. See https://github.com/quilljs/quill/issues/2167 */
        keyboard: { bindings: { list: { key: 'backspace', context: { format: ['list'] }, handler: function (range, context) { if (range.length === 0 && range.index !== 0) { this.quill.deleteText(range.index - 1, 1, Quill.sources.USER); } else { this.quill.deleteText(range, Quill.sources.USER); } } } } }
      }
    })
```

**Comment by EvanPiro** [comment]
Has this been fixed? I'm currently running into this issue with `dangerouslyPasteHTML`.

**Comment by tlrib** [comment]
I'm on 2.0.2 and same issue
