### ISSUE TITLE
Formatting options (bold, italic) are still blue when I disable them on mobile view.

### ISSUE THREAD

**Issue by nbogus** [quilljs/quill#2168]
Formatting options (bold, italic) are still blue when I disable them on mobile view.

**Steps for Reproduction**

1. Go to quilljs.com and empty the editor
2. Click Bold
3, Write some text
4. Click Bold again to turn off it
5. Bold icon is still blue

**Expected behavior**:
Options shouldn't be highlighted. 

**Actual behavior**:
Turning off formatting options don't update a icons highlight

**Platforms**:
Chrome, mobile chrome/safari, win10

**Version**:
1.3.6

**Comment by mxomxo77mxo** [comment]
The same for me. I have a problems related to this, searched issues and seems we have the same issue.
