### ISSUE TITLE
When colors bar is opened focus disappeared

### ISSUE THREAD

**Issue by AlexanderKuzmichev** [quilljs/quill#2172]
**Steps for Reproduction**
1. Visit https://codepen.io/anon/pen/MXPVYo
2. Select 'select_me' text
3. Open colors bar (click the only button on toolbar)

**Expected behavior**:
Colors bar is opened, selection and focus isn't changed

**Actual behavior**:
Colors bar is opened, selection and focus disappeared

**Platforms**:
Chrome Version 67.0.3396.99 (Official Build) (64-bit), Windows 10

**Version**:
1.3.6

**Comment by Joeao** [comment]
Noticed this today too on Firefox.
I checked out your codepen and reverted a bunch of versions, turns out this issue started occurring from version 1.0.6. Will dig deeper

**Comment by Joeao** [comment]
Looks like https://github.com/quilljs/quill/commit/c70455d459ddf873dbad059e909eb42d0684cb9a is the commit that caused this issue. I put the code back into [1.0.6](https://codepen.io/Joeao/pen/oMJmaJ) and [1.3.6](https://codepen.io/Joeao/pen/yqGZQX) and the issue disappeared. However it was removed to fix another issue so simply adding it back isn't really an option.
