### ISSUE TITLE
Is there any way to make the dropdown open above the button?

### ISSUE THREAD

**Issue by pedrollmatias** [quilljs/quill#2176]
I'm using angular material 2 in my application (Angular 6). More specifically, i'm using a element called bottom sheet. It is like a modal that always opens in the bottom corner of the page.
I have a quill-editor inside this element, but when I click in a button which opens a dropdown, I can't see all its content. Is it possible to set the dropdown to open above the button?

**Comment by degt** [comment]
A little bit late but I'm going to leave this here... just in case.

You can overwrite the styles. In my case, I'm using the Snow theme.

`.ql-snow .ql-picker.ql-expanded .ql-picker-options {
    bottom: 100%;
    top: auto;
}`

![Screen Shot 2021-02-18 at 11 33 04](https://user-images.githubusercontent.com/1747929/108371989-16d98f80-71dd-11eb-9b73-0d5d03fbd10e.png)

**Comment by benbro** [comment]
Answered.
