### ISSUE TITLE
Toolbar button for checklist isn't highlighted

### ISSUE THREAD

**Issue by laurensiusadi** [quilljs/quill#2177]
**Steps for Reproduction**

1. Visit https://codepen.io/laurensiusadi/pen/jKdego
2. Put cursor on checklist
3. See toolbar button isn't highlighted

**Expected behavior**:
Toolbar button for checklist highlighted as in 2 other list item

**Actual behavior**:
Toolbar button for checklist isn't highlighted

![2018-07-02_10-58-38](https://user-images.githubusercontent.com/5661040/42144733-ed5db89e-7de6-11e8-861d-d196f740c3ca.gif)

**Comment by DmitrySkripkin** [comment]
Toolbar button is `list: "checked"` and selected list item is `list:  "unchecked"`. So it's just different format.

P.S. This is by design. I don't like it.

**Comment by jhchen** [comment]
The toolbar lighting up correctly is the last piece and why https://github.com/quilljs/quill/issues/759 is still open. Please follow along this requirement there.
