### ISSUE TITLE
setContents is not setting attributes

### ISSUE THREAD

**Issue by lance13c** [quilljs/quill#2179]
**Steps for Reproduction**
http://jsfiddle.net/lance13c/atuhq2jb/11/

1. Visit http://jsfiddle.net/lance13c/atuhq2jb/11/

**Expected behavior**:

The method **setContents** should take an array of objects. The objects should be able to have a property called attributes. The attributes should then work as defined in the [documentation](https://quilljs.com/docs/api/#setcontents).

Ex: { input: "test", attributes: { bold: true, align: "center" } -> should bold and center align the text **test**.

**Actual behavior**:

The attributes do not modify the text.

**Platforms**:

Windows 10 version 10.0.14393 Build 14393
Chrome Version 67.0.3396.99 (Official Build) (64-bit)
Firefox Quantum 61.0 (32-bit)

**Version**: 1.3.6

**Comment by jhchen** [comment]
You're only including Quill core which does not register any formats such as bold. Use quill.min.js instead.
