### ISSUE TITLE
Text entered in reverse order behind the cursor

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#218]
When I randomly switch between the editors, edit and move the cursor in the online demo, I sometimes get into a point where text is entered in both editors in reverse order and the cursor doesn't advance.

If I'm trying to enter "123456789" I see "987654321". The cursor doesn't advance and stays at the same position.

Tested with:
Version 0.17.4
Chrome 37.0.2062.120 m
Windows 7
Edited in the top "Basic Example" editor.
http://quilljs.com/examples/

**Comment by DivineAlien** [comment]
had the same issue. but this time it was on me.

i was stuck in recursion so when i was typing then the form updated and started again with cursor on start (first index).

left his here maybe my help people like myself having same problem.

**Comment by jessicaariessa** [comment]
I'm using quill v2 and the reverse order issue appears on my code. This is my code: 


const FMSTextEditor = ({ placeholder, value, onChange, readOnly, maxLength }: ICustomFMSTextEditorProps) => {
  const [count, setCount] = useState<number>(0);

  const handleOnChange = (value: string, deltaOp: DeltaStatic, sources: Sources, editor: UnprivilegedEditor) => {
    const characterCount = editor.getLength() - 1;
    console.log(characterCount, 'characterCount');

    setCount(characterCount);

    onChange && onChange(value, deltaOp, sources, editor);
  };

  return (
    
      <ReactQuill/>
      <div className="quill-counter text-right">char: {count}</div>

  );
};

**Comment by Joben28** [comment]
> I'm using quill v2 and the reverse order issue appears on my code. This is my code:
> 
> const MyTextEditor = ({ placeholder, value, onChange, readOnly, maxLength }: ICustomMyTextEditorProps) => { const [count, setCount] = useState(0);
> 
> const handleOnChange = (value: string, deltaOp: DeltaStatic, sources: Sources, editor: UnprivilegedEditor) => { const characterCount = editor.getLength() - 1; console.log(characterCount, 'characterCount');
> 
> ```
> setCount(characterCount);
> 
> onChange && onChange(value, deltaOp, sources, editor);
> ```
> 
> };
> 
> return (
> 
> ```
>   <ReactQuill/>
>   <div className="quill-counter text-right">char: {count}</div>
> ```
> 
> ); };
> 
> Could anyone help me on this?

I had this issue in React and it seemed to have to do with resetting the value on each render. In my case I was binding a state property to the value. I fixed this by instead binding the defaultValue to my property (So it has original value on page load) but then let ReactQuill handle it's value on it's own without me setting anything.

Not sure if it's exactly your issue, but maybe it will give you some ideas.

**Comment by RSAK56** [comment]
Hi I'm facing the same issue and using v2.0.0-beta.4 and still the cursor is stuck at one place and writing "ABCDEF.." it types in "...FEDCBA".

Any solution would be really helpful. Thanks.

**Comment by biodunbamigboye** [comment]
> had the same issue. but this time it was on me.
> 
> i was stuck in recursion so when i was typing then the form updated and started again with cursor on start (first index).
> 
> left this here maybe it helps people like myself having same problem.

This saved me ton of debug hours. Thanks
