### ISSUE TITLE
TAB-Event fired at the beginning of an empty list entry

### ISSUE THREAD

**Issue by merlinfotsing** [quilljs/quill#2182]
To prevent the tab-event to be fired in my angular 5+ component, i overwrited the standard quill implementation for tab-event with a binding, as mentioned in the documentation. 

```
const bindings = {
      // This will overwrite the default binding also named 'tab'
      tab: {
        key: 9,
        handler: function (range) {
           // Handle tab
        },
      },
 };
```
As we don't want to deal with nested ordered or unordered lists, i expected the tab-event not to be triggered at the beginn of an empty list entry. [Steps for reproduction](https://i.stack.imgur.com/7Ymq7.png)

Does anyone knows how to modify the custom handler to prevent this functionality?

Version: "quill": "^1.3.6",

**Comment by DmitrySkripkin** [comment]
Well, there are other default handlers for tab like `indent`, `outdent` and `outdent backspace`. You can check this file [modules/keyboard.js].(https://github.com/quilljs/quill/blob/develop/modules/keyboard.js#L184)

So you have to overwrite more :)

**Comment by jseremba** [comment]
@merlinfotsing can u please share a codepen of outdent-events solution
