### ISSUE TITLE
[QUESTION] Relatives to absolutes URL

### ISSUE THREAD

**Issue by dignajar** [quilljs/quill#2184]
Hi,
I'm looking for the way to do this approach from TinyMCE.
https://www.tinymce.com/docs/configure/url-handling/#relativeurls

For example, my content is:
```
<p>My house</p>
<img src="house.jpg" alt="">
```

But in the Quill editor, I would like to see the image with the absolute URL.
```
<p>My house</p>
<img src="https://example.com/images/house.jpg" alt="">
```

and at the end, the content still like this:
```
<p>My house</p>
<img src="house.jpg" alt="">
```

Regards

**Comment by benbro** [comment]
Override the Link format. Something like:
https://stackoverflow.com/questions/40956020/how-can-i-prefill-links-with-http-in-a-quill-editor/40957937#40957937
