### ISSUE TITLE
how to convert class to inline style with blockquote

### ISSUE THREAD

**Issue by WxSwen** [quilljs/quill#2185]
i want to know how to convert to inline-style with blockquote；because i should get this html to another environment which no contain quill.css

**Steps for Reproduction**

**Expected behavior**:
blockquote can convert to inline-style
**Actual behavior**:
blockquote just only use class to display its style
**Platforms**:

Include browser, operating system and respective versions

**Version**:
3.0.6

**Comment by paweldyminski** [comment]
@WxSwen

Here's a simple implementation of a BlockquoteInlineStyle class i wrote for a similiar purpose

```
import * as QuillNamespace from 'quill';
let Quill = QuillNamespace;
var Blockquote = Quill.import('formats/blockquote'); 

class BlockquoteInlineStyle extends Blockquote {
    static create(value) {
        BlockquoteInlineStyle.blotName = "blockquote";
        BlockquoteInlineStyle.tagName = "blockquote";
      	let node = super.create();
      	$(node).attr("style", "border-left: 4px solid #ccc;");   
      	return node;
    }
}

export { BlockquoteInlineStyle }
```

And then you can register it like this:

`Quill.register(BlockquoteInlineStyle, true);`

**Comment by benbro** [comment]
Answered.
