### ISSUE TITLE
Extract API of Delta to/from HTML to general usage

### ISSUE THREAD

**Issue by drozdzynski** [quilljs/quill#2188]
Extract API of Delta to/from HTML to be able to parse Delta from database to HTML and display on site without Quill Editor instance.

**Comment by benbro** [comment]
Please read the Delta Converters section in the [Quill 2.0 blog post](https://medium.com/@jhchen/the-state-of-quill-and-2-0-fb38db7a59b9) 
Quill 2 is still in development.

**Comment by dcsaszar** [comment]
@drozdzynski you may also have a look at https://github.com/nozer/quill-delta-to-html
