### ISSUE TITLE
Cursor jumps to incorrect position on selection-change

### ISSUE THREAD

**Issue by mdciotti** [quilljs/quill#2197]
When moving the cursor after toggling an inline format *but not inserting text*, the cursor sometimes jumps to the end of the blot instead of where you click. This causes a second `selection-change` event to be fired in addition to the intended one. "*Sometimes*" specifically means when the new cursor index is greater than the original cursor index.

**Steps for Reproduction**

1. Visit https://codepen.io/anon/pen/wxzqJE
2. Follow instructions there to reproduce the issue.

**Expected behavior**:

If an inline style is toggled and no text is inserted, setting a new selection in the same blot where the range index is after the original index **should not move the cursor**. Only one `selection-change` event should fire.

**Actual behavior**:

If an inline style is toggled and no text is inserted, setting a new selection in the same blot where the range index is after the original index **causes the cursor to jump to the end of the blot**. Two `selection-change` events are fired.

**Platforms**:

- Windows 10 Enterprise (1607)
- Chrome 67.0.3396.99
- Firefox 52.9.0 (32-bit)

**Version**:

- 1.3.6
- 2.0.0-dev.2

**Comment by bryanwillis7** [comment]
Can confirm. This makes the software almost unusable if your document is of any consequential length.

**Comment by yaroslavputria** [comment]
Hi @jhchen ,
Based on the last commits I think you is the best person to ask:
Is planned any work to fix this issue in the near feature?

**Comment by billauer** [comment]
Hello,

I had a cursor jump issue which I managed to fix, and I survived to write a post about it:

http://billauer.co.il/blog/2021/12/quill-cursor-jump/

I'm not sure if it solves things for others, but it's contains a lot of details on what went wrong in my case, so I guess that can help others with their debugging.

Regards,
   Eli

**Comment by yesyves** [comment]
Still present in 1.3.7 and seems to be affecting every browser. Confirmed it on current versions of Safari, Firefox and Chrome on Windows and MacOS.

**Comment by yesyves** [comment]
Hi @billauer
Thanks you so much for your post ! Fixed the issue for me with no ill effect whatsoever with any of my quill extensions. Very appreciated !
