### ISSUE TITLE
authorship module does not work with usernames that have special characters

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#220]
I am using Quill with the authorship module to show collaborators edits. 

I set the authorId to the users username.

The problem is some users have the username as their email like 'user.lastname@gmail.com'

The edit highlighting shows fine for usernames without the '.' & '@' in the username. 

Is it possible for the quill editor to support authorId with special characters like '.' & '@'?

**Comment by Alec-Aldrine-Lakra** [comment]
How do I add multiple authors in the authorship module of quill ?
