### ISSUE TITLE
add custom tag attribute by button ?

### ISSUE THREAD

**Issue by DevelopFaster** [quilljs/quill#2203]
**Expected behavior**:
var Link = Quill.import('formats/link');

class MyLink extends Link {
	static create(value) {
		let node = Link.create(value);
		value = Link.sanitize(value);
		node.setAttribute('rel', 'nofollow');
		return node;
	}
}

Quill.register('formats/mylik',MyLink);
**Actual behavior**:

added to all link "nofollow"

i need custom button for add/remove nofollow to <a> tag how i do it ????

**Platforms**:
Ubuntu
Include browser, operating system and respective versions

**Version**:
1.2.0
Run `Quill.version` to find out

**Comment by mrKorg** [comment]
Hello. 
I have this task too.
I need do only some links with attr rel.
How I can do it?
