### ISSUE TITLE
how to add attribute like author info to all dom input?

### ISSUE THREAD

**Issue by hakonleung** [quilljs/quill#2204]
I have wrote a cooperation editor based on quilljs.
Now I need to add author attribute when I type in editor div, how can i achieve it?
I type a 'a', text-change event`s argument delta like:
{
  insert: 'a', 
  attribute:{
     author: someVariable
  }
}

**Comment by benbro** [comment]
Starting point:
https://github.com/quilljs/quill/pull/1049

**Comment by hakonleung** [comment]
thx @benbro, i have made it.
