### ISSUE TITLE
Can I use Quill only as a code editor?

### ISSUE THREAD

**Issue by SergeShkurko** [quilljs/quill#2205]
Can I use Quill only as a code editor?

Expected result:
![image](https://user-images.githubusercontent.com/18213789/43370016-143f792e-9391-11e8-9642-b1ccafe73bf7.png)

Current result:
![image](https://user-images.githubusercontent.com/18213789/43370037-57e79314-9391-11e8-8077-f983bb991bd4.png)

[My configuration example](https://codepen.io/SergeShkurko/pen/LBOaxY)

**Comment by jhchen** [comment]
Your two images look the same to me other than the cursor which may be what you're pointing out but please be more clear when posting Github Issues. If you want just code editor I would recommend [Ace](https://ace.c9.io/).
