### ISSUE TITLE
please update docs!

### ISSUE THREAD

**Issue by joshoconnor89** [quilljs/quill#2208]
Thumbs up on the great library.  It's perfect for our needs.  However, I am finding the documentation to be very poor.  For instance, quill supports checked boxes, but no where in the documentation does it say:

i.e.
quillEditor.formatLine(start,end,'list','unchecked');

This is just one of many examples where I had to look at the code and figure things out instead of referencing the documentation.  Please plan on updating your documentation to make life easier for everyone.

Thanks!

**Comment by jhchen** [comment]
Checklists are not officially supported as so are not documented. Please take a look at the checklist issue for remaining tasks.
