### ISSUE TITLE
Custom .innerHTML function disables quill

### ISSUE THREAD

**Issue by Albert-Jan** [quilljs/quill#2209]
Hi!

For compatibility reasons to my Android app, I have to use the .innerHTML function. To speed up this process for longer texts, I rely on this script from: [Link](http://blog.stevenlevithan.com/archives/faster-than-innerhtml)

`replaceHtml(document.getElementsByClassName("ql-editor")[0], text);`

`function replaceHtml(el, html) {
  var oldEl = typeof el === "string" ? document.getElementById(el) : el;
  /*@cc_on // Pure innerHTML is slightly faster in IE
    oldEl.innerHTML = html;
    return oldEl;
  @*/
  var newEl = oldEl.cloneNode(false);
  newEl.innerHTML = html;
  oldEl.parentNode.replaceChild(newEl, oldEl);
  /* Since we just removed the old element from the DOM, return a reference
  to the new element, which can be used to restore variable references. */
  return newEl;
};`

But for some reason quill isn't recognizing the added nodes. Debugging shows: 

> addedNodes: NodeList []

Text is added, but quill doesn't respond to it.

Am I missing something? Am I doing something wrong? Thanks in advance :)

**Version**: 1.3.6

**Comment by benbro** [comment]
Direct access to the HTML isn't supported. Use the functions in the [API](https://quilljs.com/docs/api/).

**Comment by Albert-Jan** [comment]
Are there any plans on adding these functions? Are deltas also usable on Android and iOS? Any libraries? Thanks for your reply

**Comment by benbro** [comment]
Quill works with Delta. You can find the list of supported browsers in the [README](https://github.com/quilljs/quill/blob/develop/README.md).
