### ISSUE TITLE
<p> tag was removed after pasteHTML()

### ISSUE THREAD

**Issue by Toub** [quilljs/quill#2213]
**Steps for Reproduction**

Write 3 lines in the editor, and save the html content using innerHTML:

```html
<p>line 1</p><p>line 2</p><p>line 3</p>
```

Then paste the content in the editor :

```ts
    this.editor.pasteHTML('<p>line 1</p><p>line 2</p><p>line 3</p>');
    // or
    this.editor.clipboard.dangerouslyPasteHTML('<p>line 1</p><p>line 2</p><p>line 3</p>');
```

I don't want to use getContent method as it does not preserve extra html code (in a more complex example, you may want to insert an iframe or some pre-formated html code)

**Expected behavior**:

HTML content is preserved including <p> tags

**Actual behavior**:

<p> tags have been stripped out

***(tricky) workaround for my use case***: 

To paste:
```ts
const quillHtmlContent = '<p>line 1</p><p>line 2</p><p>line 3</p>'.replace(new RegExp('<p><br></p>', 'g'), '<br/>').replace(new RegExp('<p>', 'g'), '<p><br/>').replace('<p><br/>', '<p>');

this.editor.pasteHTML(quillHtmlContent);
```

To copy:

```ts
    let htmlContent = this.editorContentHtmlElement.innerHTML;

    if (htmlContent === '<p><br/></p>') {
      htmlContent = null;
    } else {
      htmlContent = htmlContent.replace(new RegExp('<p><br/>', 'g'), '<p>')
    }
  }
```

**Platforms**:

firefox, chrome, and probably others

**Version**:

1.3.6

**Comment by benbro** [comment]
You need to use [getContents](https://quilljs.com/docs/api/#getcontents) and [setContents](https://quilljs.com/docs/api/#setcontents).
You can read about [Delta](https://quilljs.com/docs/delta/).

**Comment by Toub** [comment]
Thanks.

Unfortunately, parsing html to delta is out of scope of the project: https://github.com/quilljs/delta/issues/6

So if I want to allow some trusted admin user to copy/paste an iframe video, I am stuck with html methods.

**Comment by Toub** [comment]
Well, I realize that the scope of this library is to manipulate delta and save them to the database instead of html.

So one can use pasteHtml or dangerouslyPasteHTML to insert html content, but getContents and setContents to communicate with external components (typically database...).

Finally, delta can be converted to html to be rendered, but it is not fully supported by this project.

@see https://github.com/quilljs/quill/issues/993  
https://github.com/nozer/quill-delta-to-html 
https://github.com/joelcolucci/node-quill-converter

**Comment by benbro** [comment]
You can also read the [Delta Converters](https://medium.com/@jhchen/the-state-of-quill-and-2-0-fb38db7a59b9) section in the blog about Quill 2.0 plans.

**Comment by Toub** [comment]
Thanks, nice read!

Also discovered the following usefully repository mentioned in the blog post (should be linked from main repository): https://github.com/quilljs/awesome-quill
