### ISSUE TITLE
Toolbar won't work

### ISSUE THREAD

**Issue by robertnicjoo** [quilljs/quill#2215]
**Expected behavior**:

toolbar buttons work.

**Actual behavior**:

they don't work at all

**Platforms**:

Chrome Version 67.0.3396.99 (Official Build) (64-bit)
Windows 10

**Version**:

1.3.6

------

I just added Quill to my application by `CDN` links, I do have editor and it's toolbar loading on my page but when I type and want to make changes toolbar will not have any action `bold,italic,font,color,link, etc.` nothing works.

## Code

```html
<link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
```

```javascript
<!-- Include the Quill library -->
    <script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>
    <!-- Initialize Quill editor -->
    <script>
        var toolbarOptions = [
          ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
          ['blockquote', 'code-block'],

          [{ 'header': 1 }, { 'header': 2 }],               // custom button values
          [{ 'list': 'ordered'}, { 'list': 'bullet' }],
          [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
          [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
          [{ 'direction': 'rtl' }],                         // text direction

          [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
          [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

          [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
          [{ 'font': [] }],
          [{ 'align': [] }],

          ['clean']                                         // remove formatting button
        ];

        var quill = new Quill('.editor', {
          modules: {
            toolbar: toolbarOptions
          },
          theme: 'snow'
        });
    </script>
```

```editor
<label for="body">Body</label>
<textarea name="body" id="body" cols="30" rows="10" class="editor form-control"></textarea>
```

## screenshot

![12](https://user-images.githubusercontent.com/8672823/43624131-9e243400-970f-11e8-8e35-429168f58007.png)

**Comment by benbro** [comment]
Quill works with a div element and not with textarea.
Please check examples in the playground:
https://quilljs.com/playground/

**Comment by robertnicjoo** [comment]
@benbro  then it wont save my data to database, I already tried with playground and serialize data of div it returns error.

**Comment by benbro** [comment]
You can use [getContents](https://quilljs.com/docs/api/#getcontents) and [setContents](https://quilljs.com/docs/api/#setcontents) or see the [form-submit](https://quilljs.com/playground/#form-submit) example.

**Comment by sandywilkins** [comment]
If I may rant on this point a bit longer, not using a textarea field breaks things like repopulating a form when backend validation fails. For me this is a huge dealbreaker.

**Comment by yeole-rohan** [comment]
it is, frustrated with dealing with workaround. using div now, still the same issue
