### ISSUE TITLE
List numbering appears to be incorrect when including bullet lists within.

### ISSUE THREAD

**Issue by mikeallen811** [quilljs/quill#2221]
Please consider the following JSON/Delta:

`{"ops":[{"insert":"Item 1"},{"attributes":{"list":"ordered"},"insert":"\n"},{"insert":"Sub Item 1"},{"attributes":{"indent":1,"list":"ordered"},"insert":"\n"},{"insert":"Sub Item 2"},{"attributes":{"indent":1,"list":"ordered"},"insert":"\n"},{"insert":"Item 2"},{"attributes":{"list":"ordered"},"insert":"\n"},{"insert":"Bullet Item 1"},{"attributes":{"indent":1,"list":"bullet"},"insert":"\n"},{"insert":"Bullet Item 2"},{"attributes":{"indent":1,"list":"bullet"},"insert":"\n"},{"insert":"Item 3"},{"attributes":{"list":"ordered"},"insert":"\n"},{"insert":"Item 4"},{"attributes":{"list":"ordered"},"insert":"\n"},{"insert":"\n\n"}]}`

When rendered by QuillJS - this produced output similar to:

> 1. Item 1
>        a. Sub Item 1
>        b. Sub Item 2
> 2. Item 2
>        . Bullet Item 1
>        . Bullet Item 2

all is good so far .. but then the last two show up like so ...

> 1. Item 3
> 2. Item 4
> 

An intermediate bullet list within an ordered list should be a valid practice, and should not reset the numbering.   Thoughts?  Thanks.

**Expected behavior**:
One would expect that when the list continues counting on "Item 3" that the number would be 3, to follow the next logical number from it's sibling.

**Actual behavior**:
Instead the number resets back to 1.

**Platforms**:
Chrome, Edge, Firefox.

**Version**:
Quill Editor v1.3.6

**Comment by DmitrySkripkin** [comment]
Tried to play around with Google Docs and MS Word and was not able to mix ordered and unordered lists. But Notion and Paper can do it (with minor issues).

**Comment by jeriahwc** [comment]
Did you find any solutions for how to mix list types?
