### ISSUE TITLE
XSS Vulnerability in clipboard paste / convert

### ISSUE THREAD

**Issue by RyanV** [quilljs/quill#2224]
**Steps for Reproduction**
1. Visit this [codepen](https://codepen.io/anon/pen/PBdooR?editors=1111)
2. copy "Copy Me"
3. Paste into editor

**Expected behavior**:
No scripts should run

**Actual behavior**:
Script runs on paste

**Platforms**:
MacOS Sierra 10.12.6
Chrome 68.0.3440.84
Firefox Quantum 61.0.1
Safari 11.1.1 (Problem not present)

**Version**:
2.0.0-dev.2

--------------------
While this may not be a likely scenario if all sources are trusted, this isn't always the case. 

These lines are the problem:
https://github.com/quilljs/quill/blob/ae22be5ac37a4ca62e22ff4866b4c455c2ec9d23/modules/clipboard.js#L87-L88

The fix:
use DomParser or document.implementation.createHTMLDocument

**Comment by jhchen** [comment]
Fixed in #2226
