### ISSUE TITLE
Can not use bold or italic or some. in lit-element

### ISSUE THREAD

**Issue by Tonkungs** [quilljs/quill#2229]
I can not use bold or italic or some. in lit-element (webcomponents)
**Steps for Reproduction**

1. Go [Codepen]( https://codepen.io/Tonkung/pen/yqxRoE)
2. Use bold or italic or Link.

**Expected behavior**:
-
**Actual behavior**:
-
**Platforms**:
window 10 
Chrome 68.0.3440.84
Include browser, operating system and respective versions

**Version**: 1.3.6

Run `Quill.version` to find out

**Comment by benbro** [comment]
[lit-element](https://github.com/Polymer/lit-element) from Polymer.
There is an old discussion about integrating Polymer and Quill. Not sure if it's still relevant:
https://github.com/quilljs/quill/issues/904

**Comment by Tonkungs** [comment]
@benbro thank.

I try use "bounds" but not anything change.
https://plnkr.co/edit/0ZSJ74Ak2HleqdIQHNF4?p=preview

**Comment by Tonkungs** [comment]
I use quill.js from https://github.com/arsnebula/polymer-quill and It's work, but old version (1.2.4)
