### ISSUE TITLE
change code-block background color

### ISSUE THREAD

**Issue by joshoconnor89** [quilljs/quill#2231]
code-block seems to be defaulting to a black background.  Is it possible to change the background color and text color to something else?

**Comment by joshoconnor89** [comment]
Solution:
override this style (if you are using snow theme)
```
.ql-snow .ql-editor pre.ql-syntax {
    background-color: #23241f;
    color: #f8f8f2;
    overflow: visible;
}
```

**Comment by bugdriver** [comment]
`<p><span class="ql-size-huge">How to do something ? </span></p><p><br></p><p><span class="ql-size-large">so far i have done this</span></p><pre class="ql-syntax" spellcheck="false"> <span class="hljs-keyword">var</span> quill = <span class="hljs-built_in">new</span> Quill(<span class="hljs-string">'#editor-container'</span>, {
      modules: {
        syntax: <span class="hljs-literal">true</span>,
        toolbar: [
          [{ size: [<span class="hljs-string">'small'</span>, <span class="hljs-literal">false</span>, <span class="hljs-string">'large'</span>, <span class="hljs-string">'huge'</span>] }],
          [<span class="hljs-string">'bold'</span>, <span class="hljs-string">'italic'</span>, <span class="hljs-string">'underline'</span>],
          [<span class="hljs-string">'image'</span>, <span class="hljs-string">'code-block'</span>]
        ]
      },
      placeholder: <span class="hljs-string">'Compose an epic...'</span>,
      theme: <span class="hljs-string">'snow'</span> <span class="hljs-comment">// or 'bubble'</span>
    });
</pre><p>please give some feedback<span class="ql-size-large"><span class="ql-cursor">﻿</span></span></p>`

**Comment by bugdriver** [comment]
`var quill = new Quill('#editor-container', {
      modules: {
        syntax: true,
        toolbar: [
        [{ 'size': ['small', false, 'large', 'huge'] }], 
          ['bold', 'italic', 'underline'],
          ['image', 'code-block']
        ]
      },
      placeholder: 'Compose an epic...',
      theme: 'snow' // or 'bubble'
    });`
