### ISSUE TITLE
IE11 only > quill.getText returns wrong value when typing text with Japanese IME

### ISSUE THREAD

**Issue by smura** [quilljs/quill#2239]
`quill.getText` returns wrong value when typing text with IE11 and Japanese IME.

**Steps for Reproduction**

1. Visit https://jsfiddle.net/smura/q1L93er0/show from IE11
2. Set the cursor position before "A"
3. Enable Japanese IME and set mode to Hiragana (IME toolbar shows "あ")
4. Type "a" (displayed as "あ") then type backspace
5. Remove focus from editor

**Expected behavior**:

- `quill.getText()` returns "A".

**Actual behavior**:

- `quill.getText()` returns "あA".

![ie11_and_ime_causes_wrong_value](https://user-images.githubusercontent.com/4250758/43950448-464cba1a-9ccb-11e8-9170-b5ad49b4e9cc.gif)

**Platforms**:

- IE11 (11.0.9600.19080)
- Windows 7
- Microsoft IME 10.1.7601.0

**Version**:

1.3.6

**Comment by smura** [comment]
**Note**

[MutationObserver](https://developer.mozilla.org/ja/docs/Web/API/MutationObserver) sometimes produces strange [MutationRecord](https://developer.mozilla.org/ja/docs/Web/API/MutationRecord) on IE11.

That MutationRecord has following properties:

- With `characterData` as `type`
- With **newly created** CharacterData node as `target`
    - That target node has no `__blot` property
    - Old CharacterData node with `__blot` is removed by document

[ScrollBlot can not find existing TextBlot](https://github.com/quilljs/parchment/blob/master/src/blot/scroll.ts#L133), so [ContainerBlot handles the MutationRecord](https://github.com/quilljs/parchment/blob/master/src/blot/abstract/container.ts#L194). But ContainerBlot ignores the MutationRecord with type `characterData`.

**Comment by benbro** [comment]
IE11 is not supported.
Please the supported browsers in the [README](https://github.com/quilljs/quill/blob/develop/README.md).

**Comment by smura** [comment]
Self-solved : There is no IE11 support in correct image. The avobe image with IE11 is old one.

- [Old image cached by github](https://camo.githubusercontent.com/5c3c542f0783c0c19c59d13927247502aa55c98a/68747470733a2f2f63646e2e7175696c6c6a732e636f6d2f62616467652e7376673f763d32) contains IE11
- But [correct image](https://cdn.quilljs.com/badge.svg?v=2) not contains IE11

FIY: [About anonymized image URLs
](https://help.github.com/articles/about-anonymized-image-urls/)
