### ISSUE TITLE
Instantiation of the Quill editor strips classes from img elements.

### ISSUE THREAD

**Issue by cpinto-cb** [quilljs/quill#2240]
See the attached example.

In the example, there is a div#editor that contains.

&lt;div id="editor"&gt;
    Here is a field with an image and it has a class. Lifted from my jQuery DataTables application<br/>
    Une famille d’entreprises spécialisées dans la prestation de services linguistiques et l’apport de solutions technologiques
    &lt;img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAQCAYAAAABOs/SAAABH0lEQVRIS8XULUsEYRAH8N9Fs8UoFr+CcCbBaLGI2LQZBEGTGFQsKojFZhQxWI02P4BJbWLWbJWBWVjW3Tt3L+xT9m1m/i8zswM9nUFPuHoH3sA+1tKBe5zn/QeeWzgzhSPc4BOXmbuL1QInFJcD3xEk4tzmfRvg6cybSRFRr7b+f4DncJxkFvGGUyzgId8/pSvLeMVOKh4LvIdrfFdUhvoAPsE8tnCFQxxkfLULVYXxPeILckMsheKzEruyzZEQz4XVUTAI3mEdF/ip6X0dcIRFjx8RLgwLq0cpLvpdVrzZErhW8bjhWslBecnrF7ZLwOWiQbJar3G4/tiA2ZzOFlvUGDoSuGmPY6UmOQHauMeTFO6c2/svszPzrom9Kf4F9PRdAJ0jXGcAAAAASUVORK5CYII=" <strong>alt="br:1" class="token"</strong>&gt; aux entreprises internationales...
&lt;/div&gt;

There is also a button labeled make editor.

You will see after hitting the "make editor" button the class name token is stripped from the img element. The alt="br:1" is maintained, but the class="token" disappears.

[quillexample.html.txt](https://github.com/quilljs/quill/files/2278066/quillexample.html.txt)

**Comment by benbro** [comment]
Quill strips classes it doesn't know.
Please read:
https://github.com/quilljs/quill/issues/1606#issuecomment-317503105

**Comment by cpinto-cb** [comment]
So there is a way to register my class name with parchment/quill?

**Comment by benbro** [comment]
You need to create a class attributor:
```javascript
let TokenClass = new Parchment.Attributor.Class('token', 'token', {
  scope: Parchment.Scope.INLINE
});
Quill.register(TokenClass, true);
```
Demo:
https://codepen.io/anon/pen/ajXbbR

**Comment by cpinto-cb** [comment]
Where can I find good documentation on how to add a new Blot that will not strip the class name from an image
Note. Working in plain JS

var Token = Quill.import('formats/image');
Token.className = 'token';
Token.blotName = 'img-token';
Quill.register(Token);

Is that all that is necessary?

**Comment by cpinto-cb** [comment]
I tried this and it still appears to be stripping my class names...

var Parchment = Quill.import('parchment');
var TokenClass = new Parchment.Attributor.Class('token', 'token', {
  scope: Parchment.Scope.INLINE
});
Quill.register(TokenClass, true);

**Comment by cpinto-cb** [comment]
I just did this here: 

`var Token = Quill.import('formats/image');
Token.className = 'token';
Token.blotName = 'img-token';
Quill.register(Token);`

And it works.
