### ISSUE TITLE
jasmine toEqualHTML matcher false positives

### ISSUE THREAD

**Issue by RyanV** [quilljs/quill#2241]
After looking into https://github.com/quilljs/quill/issues/2195 I realized there is an issue with the custom jasmine toEqualHTML matcher causing the editor#getHTML test to falsely return success for the "nested list" test.  The issue is caused by the matcher inserting the text content into an html element which will fix broken html to the best of its ability.  That means that `<ol><li>1</li></ul>`, when inserted into a DOM node via #innerHTML will generate `<ol><li>1</li></ol>` and a comparison of html returned from #getHTML _will_ match the expectation.

PR: for partial fix for the matcher which compares the html structure before parsing dom nodes https://github.com/quilljs/quill/pull/2242

**Comment by RyanV** [comment]
@jhchen please re-open this. The fix still doesn't solve the problem and you still have false positives being reported.

`"<ul><li>foo</li><ol>".length === "<ul><li>foo</li><ul>".length` which is not correct.  Your fix only checks the string length and reports false positives for the nested list test.

**Comment by jhchen** [comment]
Commenting in one place is enough. Please do not duplicate content in the future.
