### ISSUE TITLE
Clicking Hyperlink Icon In Toolbar Removes Hyperlink

### ISSUE THREAD

**Issue by DJShump08** [quilljs/quill#2244]
If you create a hyperlink in quill, then highlight the hyperlink once again and click the hyperlink icon in the toolbar, the hyperlink is removed.

**Steps for Reproduction**

1. Visit https://codepen.io/quill/pen/RRYBEP
2. Highlight the link in Quill 'http://en.wikipedia.org/wiki/One_Ring'
3. Click Hyperlink Icon in tool bar

**Expected behavior**:
Show tooltip where we an edit the link.

**Actual behavior**:
Hyperlink is removed

**Platforms**:
Cross Browsers

**Version**:
2.0.0

**Comment by benbro** [comment]
When you click on the link you get a popup that let you visit, edit or remove the link.

**Comment by DJShump08** [comment]
@benbro yes but when you click on the hyperlink icon with the hyperlink selected, it removes the hyperlink. That's the issue or is that intended to be that way?

**Comment by benbro** [comment]
Just mentioned that you do have a way to edit the link by clicking it.
If clicking the button should remove the hyperlink or show the popup is probably a matter of taste.

You can create custom toolbar handler to override this:
https://codepen.io/anon/pen/rrPMEL

**Comment by benbro** [comment]
This is close but you need to get the preview from the href of the link:
https://codepen.io/anon/pen/rrPMEL

**Comment by benbro** [comment]
Gmail editor works exactly the same. Closing.
