### ISSUE TITLE
Quill js insert images generates image into base64 that is shorter than expected

### ISSUE THREAD

**Issue by ninjvalenz** [quilljs/quill#2245]
I have the default insert image button of quilljs toolbar. I didn't alter the function in my code. I let the quilljs do its thing when embedding the image. So it is currently saving in my html body string as: 

`<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEwAACxMBAJqcGAAAAqdJREFUSInNlU1LG1EUhp9JotggCi7E1AiCiJQW6sco6MJFXRVEYhFcFFopBRciYrsQUQR/QD9wERdCViJuil0maDcGsdgmYBqsIOInKf0DGnMzc7owhsSMdSIU+sJszjvzvHPn3jkH/jM5MpdtaTb8FqAfaAU8gAC/gO/AJ+DHXQMeA+8bGhqeDA4O0tnZidfrBeD4+JjNzU2Wl5c5PDwMAm+AnzYWlNWrysrKpN/vF6WUmKYp12WapqRSKZmbm5OKiooz4Lld+Ou6ujrZ3t4ugAaDQVldXS2oRyIRqa2tNe2EtJSXl19Eo9ECiIjIxMSETE1NWXpbW1vidrvPgAe5wNwToQEfZ2ZmSpubm+2uNitd15mcnLwHvLspoKO6urp7ZGQETbvtcBVK0zTGxsaoqqp6CjyyCujv6+ujrKysaPiV3G43vb29AM+sAnRd13E4ivqP8uR0Omlvbwdou6q5coJqPB4PAKFQiPn5+QLAzs4OmqYRj8cLvNHRUXp6esgw7meYpiv3pnQ6DUBTUxM+n68AopTC6XRaeo2NjbmM7CZeBZjA76Ojo4ciQn19PUNDQwWQ3d1dXC6XpQcgIhwcHMBlKzEhfw8i6+vrmKZp+bAdmaZJOByGyz7F9YCVYDBIIpG4c8DJyQlra2sAn60CviaTyfDs7CyGYRQNNwyD6elpUqlUCIhZBQgwHggE1OLiYtEBgUCApaWlc+BthnWjhktLS2VhYUHS6XRev9nb25P9/f28mlJK/H6/lJSUCPDC7gsNa5p2MTAwIPF4XJRSYhhGFmoYhiilJBaLic/nE+AceGkF+lvTaQU+OByObl3X6erqwuv1IiKcnp6ysbFBJBJBRL4A49ww2eyMzA4uR2YbUJOpJ4BvwAoQ5ZZvXoyKHvr/XH8AKHh+Z+REvHcAAAAASUVORK5CYII=">`

If I try to convert it from here: https://codebeautify.org/base64-to-image-converter
The result is a "plus sign" image as oppose to what is embedded image exactly. (Please see quilljs_base64_to_image_decoded.png for reference)

The component is loading the image correctly after saving it. But I need the correct base64 because I am converting it to image for my email sending service. (Base64 is not supported in outlook mails, so there's that)

What Am I missing here?

![quilljs_base64_to_image_decoded](https://user-images.githubusercontent.com/12510008/44016252-e28c2324-9f06-11e8-8280-6b7d859f3800.png)

**Comment by RyanV** [comment]
@ninjvalenz please post your Quill version and browser version.  Also if you can include the test image that would be helpful.

**Comment by ninjvalenz** [comment]
Hi @RyanV ,

Thanks for the reply. 
My current version is v1.3.6.
Here is the image I want to obtain (Just a random screenshot from VS): 
![2018-08-02_1228](https://user-images.githubusercontent.com/12510008/44076708-bcde60e2-9fd3-11e8-9ebd-3e3a55493839.png)

**Comment by RyanV** [comment]
@ninjvalenz I can't replicate this on Chrome or Firefox.  The image properly embeds and the base64 string properly converts back to an image through the link you provided.  can you create a codepen example replicating the issue?

**Comment by ninjvalenz** [comment]
You are right. Seems like the problem is on my saving part. I'm so sorry. Everything is okay. I do a rechecked.

**Comment by murat1309** [comment]
hey I want to send base64 as mail but I couldn't.
Can you help me please? I use react-quill

**Comment by MakamiSupport** [comment]
> hey I want to send base64 as mail but I couldn't.
> Can you help me please? I use react-quill

Did you get your problem solved? I am currently doing the same think, and it works for outlook but not gmail.
