### ISSUE TITLE
Feature discussion: option for user defined html normalization on clipboard paste

### ISSUE THREAD

**Issue by RyanV** [quilljs/quill#2246]
Currently html is pasted _as-is_ from various sources.  Depending on the source, the clipboard data html may not be semantic and thus easily parsable (\*ahem\*...MS Word...).  I think a proper solution here would be to allow a custom normalization function to be passed into quill as a clipboard option.  If the user wants, they can define their own normalization function to handle various cases.  The goal here is to expose a hook without including 3rd party domain knowledge within quill core.

Example API:
```js
const quill = new Quill('#editor', {
    modules: {
        clipboard: {
            // @return {String|null} normalized HTML string or null to fallback to default implementation
            normalizePasteData(clipboardData) { ... }
         }
    }
})
```        

Discussion points:
* Does this seem like the appropriate solution?
* Function name, parameter signature, expected return value
* What are the long term goals for Quill as a drop-in editor?  _Should_ quill provide a module for consistent copy paste from various sources?  This implementation assumes Quill should remain as light weight as possible.

This also may give the user the opportunity to do their own html sanitization as well, so maybe the term `normalize` is too specific.

**Comment by DmitrySkripkin** [comment]
I just rewrote `clipboard.prototype.onPaste` in my project. But it would much better to have isolated pure function to normalize clipboard data.

**Comment by jhchen** [comment]
The way to do this right now is to use your own clipboard module (which can extend the existing one): https://quilljs.com/docs/modules/#extending

```js
var Clipboard = Quill.import('modules/clipboard');

class YourClipboard extends Clipboard {
  // ...
}

Quill.register('modules/clipboard', YourClipboard, true);
```

Is there a limitation to this method that would not cover your use case? Providing escape-hatch functionality, especially in configurations, is not a scalable design pattern.

**Comment by RyanV** [comment]
I'm familiar with the the subclassing pattern for quill and is actually how I’m solving the problem in my own code.

Quill promotes itself as a black-box framework with white-box extensibility.  I made an assumption that many of the consumers of this editor are using the default Quill export or just pulling Quill from a CDN.  In these cases, most people will likely never read the source code and IMO shouldn't have to.

Sub-classing is a non-trivial decision to make a small change that could be handled through a config interface.  It requires the user to have knowledge of implementation details of the parent class and possibly it’s dependencies (e.g. Delta, Parchment) and is a relatively heavy weight solution. 

Some other issues with this OO approach:
* Required understanding of parent implementation and possibly it’s dependencies (e.g. Delta, 
Parchment)
* Singleton implementation for all editor instances
* Parent changes more likely to break child class overrides
* Maintenance overhead - version updates requires knowledge of changes

Agreed, subclassing provides a huge amount of flexibility for those willing to get their hands dirty.

If this is not considered an appropriate solution, I’d I’d also like to get an idea of where the line is for improving the framework usability for the black-box consumers.

To be clear, I can solve this fine through subclassing, but considering the number of issues logged around copy paste inconsistencies, I thought it would be good addition to the configuration api.

**Comment by jhchen** [comment]
> Quill promotes itself as a black-box framework with white-box extensibility

I don't think I agree with either characterization. Can you elaborate?

> Sub-classing is a non-trivial decision

I think subclassing is a well understood and accessible pattern. The issue is more so the interesting functions to override are not documented which is because I was not ready to put them under SemVer by 1.0. This will probably change by 2.0.

> I’d I’d also like to get an idea of where the line is for improving the framework usability for the black-box consumers

The problem is not that I don't think people should customize the clipboard, the problem is I think providing an escape hatch function is bad design. As it states in the Contributing Guide there is a high bar to making changes (even additions) to the API. In general I also prefer to prioritize making impossible things possible than easy things easier.

Copy and paste just is an area where the actual complexity is much higher than the perceived. Giving people a function to say "hey now you can figure out how to clean up MS Word markup before it goes to Quill" will not make the Github Issues go away.
