### ISSUE TITLE
Frustrating even to get started, document needs improving to make quill user not painful

### ISSUE THREAD

**Issue by Nomia** [quilljs/quill#2251]
Some complaints before my problem:
1.Too much talk in document. (Please show more code, give a look to `tinymce` editor's document or any other well known editor's documents)
2.Frustrating to get started. (Can u just give a simple example for people to get start, and show the full options to let people play around and show some awesome third party modules for developers to enjoy, in the homepage or in the README.md page?)

Here is how I get started:
In terminal:
`npm install quill -S`

In Vue file:
```
<template>
  <div class="editor-container">
    <div id="toolbar"></div>
    <div id="editor_id"></div>
  </div>
</template>
<script>
import Quill from 'quill'

export default {
     ...
     methods: {
         initEditor() {
            const dom = document.getElementById(this.editor_id)
            console.log(dom)
            var editor = new Quill(dom, {
               modules: {
               toolbar: '#toolbar'
             },
             placeholder: '请输入内容...',
             theme: 'snow'
           });
         }
     }
     ...
}
</script>
```

I know there is something that quill required missing in my code. 
But I cannot find a place to know what do I missing. there is no get started example in your official site or your document to show which to `require` except `Quill`

So I guess the style might need `require` separately, So I searched, and found this:
```
import Quill from 'quill'
import 'quill/dist/quill.core.css'
import 'quill/dist/quill.snow.css'
```
After I `import` these css, the style changed a little bit. But still not what I want, the toolbar is missing, and the style is wrong.

![image](https://user-images.githubusercontent.com/1707818/44135580-369493d4-a09c-11e8-8c7b-309c2ae98805.png)

Six month ago, a frontend intern in our company use `quill`, I found it painful to solve a simple problem.(document). 
I really don't know why quill get so many star on github

**Comment by Nomia** [comment]
Do I still need to `import` the bootstrap like you `include` in the codepen, the bootstrap js and bootstrap css?

**Comment by Nomia** [comment]
Seems I found the cause of toolbar missing:
I change my toolbar init from this:
![image](https://user-images.githubusercontent.com/1707818/44136914-2265e188-a0a1-11e8-94be-83d78a490fc2.png)
to this:
![image](https://user-images.githubusercontent.com/1707818/44136947-3ef05356-a0a1-11e8-9a2c-5a7f9465e658.png)
(All these two are your officail demo, first one will not show toolbar in my get start struggle)


But `Bold` and `Italic` seems not working
![image](https://user-images.githubusercontent.com/1707818/44136839-e12cb5e8-a0a0-11e8-9fd2-d4a92fb7c008.png)

**Comment by Nomia** [comment]
![image](https://user-images.githubusercontent.com/1707818/44143067-d6ac8a1c-a0b4-11e8-9556-65cdd5182729.png)

It took me long time to find how to add `backgroud` or `font-color` button to the toolbar.

All the toolbar code example on quilljs.com are simple `button` items, no `select` example. No one will know how to add a select item(`color` or `background`) on toolbar, or maybe they can guess by luck that it should be `select` tag instead of `span` or `button`

**Comment by Nomia** [comment]
![image](https://user-images.githubusercontent.com/1707818/44143597-e52acf48-a0b6-11e8-9245-5e0a1004f9a9.png)

It took me long time to find how to add backgroud or font-color button to the toolbar.

All the toolbar code example on quilljs.com are simple button items, no select example. No one will know how to add a select item(color or background) on toolbar, or maybe they can guess by luck that it should be select tag instead of span or button

And I found this usage by look through all your code example and finally find a demo page(https://quilljs.com/standalone/full/),  and take a look at the source code.  Why make it hidden so deep? Or it's just me that cannot get what I want?

**Comment by Nomia** [comment]
`It took me long time to find how to add backgroud or font-color button to the toolbar.`

By this I mean I know how to add `backgroud` with code below:
`toolbar: ['bold', 'italic'] ....`

but I don't know how to add `background` by set toolbar container, and add `background` to container: 
`toolbar: #id`

**Comment by Nomia** [comment]
Could you give a full list of what style quilljs can import 
In your [class vs inline demo](https://codepen.io/quill/pres/jAvpQL) , there is only one style example, 

and I cannnot find any reference in quilljs doc, nor in your npm repo.
![image](https://user-images.githubusercontent.com/1707818/44639987-834eeb80-a9f1-11e8-8e61-9982ebf995b8.png)
Where is the supported style list?

Why would u like to make developer to guess, guess the name, guess the class, guess the code?
Please give full list of every option in every feature of quill, so developer don't have to guess all the thing.

thanks

**Comment by Nomia** [comment]
![image](https://user-images.githubusercontent.com/1707818/44640039-d032c200-a9f1-11e8-846b-c19e809f86c6.png)
I cannot find the `attributors` folder in the npm install repo. Otherwise I will not bother submit here

**Comment by Nomia** [comment]
I suggest give reference link in every of your codepen demo. So people who see the demo useful will get to the reference immediately instead of searching and finding in you official navigation-not-well-designed document.

And most importantly, please make doc detailed, have full list option of every feature, or just open source your offcial website, so people can submit to detail it. thx

**Comment by Joeao** [comment]
The docs are in the repo https://github.com/quilljs/quill/tree/develop/docs/docs 

Remember that this is an open source project, if you find something frustrating, you can make it easier for the next person by contributing.

**Comment by Nomia** [comment]
Sure I will try
