### ISSUE TITLE
want format just apply to given index

### ISSUE THREAD

**Issue by hakonleung** [quilljs/quill#2254]
i use formatText applying format like 'wrapper' to a index 1, so the html looks like <span class="wrapper-xxx">A</span>, now i want to insert a B after that, but i dont want format B 'wrapper', i want html now looks like <span class="wrapper-xxx">A</span>B, it means that 'wrapper' just format one time, how can i achieve that?

**Comment by hakonleung** [comment]
A means `<span class="wrapper">A</span>`
AB means `<span class="wrapper">A</span>B` but not `<span class="wrapper">AB</span>`

**Comment by DmitrySkripkin** [comment]
CodePen example would be great. Not sure if I understand this issue.

**Comment by hakonleung** [comment]
I want to make a function that can clip image. Now i need to add an inline attribute to a image that wrap the image tag with span tag.
it looks like `<span style="overflow:hidden;width:100px;height:100px"> <img /> </span>`.
and i dont want next text or image wrapped in the same span.
so if i input A after the clipped image, html looks like:
 `<span style="overflow:hidden;width:100px;height:100px"> <img /> </span> A`
but not
 `<span style="overflow:hidden;width:100px;height:100px"> <img />A </span>`
@DmitrySkripkin

**Comment by benbro** [comment]
https://quilljs.com/guides/how-to-customize-quill/
