### ISSUE TITLE
how to convert a text to picture

### ISSUE THREAD

**Issue by wjp5826** [quilljs/quill#2256]
hello, i have a problem with quill.i hope you help me answer this question
i have a stirng like this
> hello, [微笑1] i am quill

this is i will send to server，but [微笑1] is a emoji，at the font end, the emoji will be converted to picture display.
I used to change the contents of the input box by listening to text-change and then calling setContents () and pasteHTML (), but when I entered Chinese, something was wrong.
I tried format, it seems not.
I just want to ask you what else we can do.
![image](https://user-images.githubusercontent.com/17820839/44215112-45a5c380-a1a4-11e8-9851-8e647d7356b5.png)
![image](https://user-images.githubusercontent.com/17820839/44215157-640bbf00-a1a4-11e8-8f8f-2d187585ee9d.png)
![image](https://user-images.githubusercontent.com/17820839/44215217-90bfd680-a1a4-11e8-86bb-e7152b2b9fbc.png)
Above is the result of my input of Chinese.

**Comment by sankalpsans** [comment]
I suggest you directly use emoji character instead of encoding/decoding it to text. Most modern Databases and text editors (you're probably using VS Code) support it.

You can copy and paste the characters like '🙂' in your code and use them as is.

**Comment by 1c7** [comment]
did you solve your problem? this issue is 11 days ago. any update?

**Comment by www5826** [comment]
i solved this problem by insertEmbed() via delta.you`ll build new feature like this?you mean control data flow? @1c7

**Comment by 1c7** [comment]
@www5826 
I mean allow user choose emoji. like twitter 
![image](https://user-images.githubusercontent.com/1804755/44670222-a6f74d80-aa54-11e8-8bbc-5b084335cc53.png)

by the way, what kind of website you guys building with quill editor?
would you mind share website link here?

**Comment by www5826** [comment]
i am sorry,Our product hasn't come on line yet.but i can provide my thinking of emoji @1c7

**Comment by www5826** [comment]
ok,you can add my weixin.because we are all in guangzhou

**Comment by www5826** [comment]
wjp5826，I am very willing to communicate with you @1c7

**Comment by www5826** [comment]
Because we are multiterminal, the plan has been determined and cannot be changed. @sankalpsans
