### ISSUE TITLE
Black text color / white background color

### ISSUE THREAD

**Issue by MgSam** [quilljs/quill#2257]
Selecting black as the text color or white as the background color doesn't actually set the text black or the background white- it just clears the respective `color`/`background` style (and thus will render with whatever the page's defaults are). This is confusing behavior.

There should be separate clear buttons for text and background color. The black/white text/background colors should actually force the text to render black/white with CSS.

**Steps for Reproduction**

1. Try setting Quill text color to black.
2. Try setting Quill background color to white.
3. Inspect the HTML generated in the browser Dev Tools
4. Neither `color` or `background` CSS will have been set.

**Expected behavior**:

Separate clear buttons needed. Black text forces the text to render black. White background forces the text to render white.

**Actual behavior**:

Black text color and white background color are actually clear buttons.

**Platforms**:

Chrome

**Version**:

I'm using `ngx-quill`, not sure how to get underlying quill version number.

**Comment by benbro** [comment]
Removing the color is the expected behavior. 
You can override the colors in the toolbar and add the clean button to work as you want:
https://codepen.io/anon/pen/jpgGQv

**Comment by MgSam** [comment]
Thanks for the partial workaround, but the clean button removes all formatting, which may not be what the user wants.

I think this default behavior is wrong. Any user expects that when they click on a color, that color will be applied. They don't expect it to suddenly change to whatever the page's ambient colors happen to be. 

I don't know what "other editors" you're referring to, but this is certainly not how any word processor works. The foreground and background colors are set explicitly and stored that way. And Word, for example, has an explicit "clear" button for background color.

![image](https://user-images.githubusercontent.com/1965570/44273334-39a21c00-a20d-11e8-9645-b1611ed2590d.png)

**Comment by benbro** [comment]
I was referring to the email editor in Gmail.
You can create a custom color picker and with 'No Color' option.

**Comment by piesuke** [comment]
I want this feature, but I don't know how to set the no color option within color.
