### ISSUE TITLE
Strange behavior in quill editor with IE11 when drag/drop internal text

### ISSUE THREAD

**Issue by paolo-mosna** [quilljs/quill#2258]
There is a strange behavior in quill editor with IE11 when drag/drop text from within quill text editor.

**Steps for Reproduction**

1. Visit quilljs.com
2. Inside quill editor select all text and images and clear them all (e.g. ctrl+A and canc)
3. Set font to normal
4. write few lines of text
5. select the lines and copy and paste few times in the editor to create a longer text
6. set caret at beginning of a line in middle of text
7. press "enter" tree times to free an some empty lines of space
8. select last 3 lines from the bottom (or other you prefer)
9. drag the selected lines in the empty space you created at previous step 7
10. Select all text (e.g. ctrl+A and canc)

**Expected behavior**:
All text should be removed from the editor

**Actual behavior**:
Some text (part of the dragged text) remains in the editor and there is no way to delete it

**Platforms**:
Internet Expolrer 11 on Windows 10

**Version**:
Quill version 1.3.6

**Comment by benbro** [comment]
IE11 isn't supported.
https://github.com/quilljs/quill/blob/develop/README.md
