### ISSUE TITLE
Quill Editor takes a really long time to load when initializing with insertContent and a lot of text

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#226]
I have an application which allows users to take notes. 

I use Quill as the editor and save the contents when the user is done. Next time the user loads the app, I initialize Quill again and set its contents to the saved document using the setContents function.

Athough if the text content is more than 1 letter page, the Quill editor takes a really long time to load (like about a minute or more!). By comparison using a regular content editable div loads instantly with the same amount of text. So something is wrong here.

Here is the code I am using to initialize the Quill Editor, pretty standard stuff:

``` coffeescript
 @editor = new Quill(@find('.quill-editor'),
      modules:
        'authorship':
          authorId: username
          enabled: true
        toolbar:
          container: @find('.quill-toolbar')
        "link-tooltip": true,
        'image-tooltip': true
      theme: "snow"
    )

self.editor.addStyles
    'body':
      'height': 'auto'
      'min-height': '50px'
      'overflow': 'hidden'
      'font-family': '"Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif'
      'letter-spacing': '0.008rem'
      'font-weight': '400'
      'line-height': '1.5'
      'font-size': '14px'
    'img':
      'max-width': '80% !important'
    '.editor-container':
      'overflow': 'hidden'
    '.spacer-container':
        'height': '20px'
        'display': 'block'
        'clear': 'both'

self.editor.addContainer('spacer-container')
self.$('.quill-editor').height(self.editor.root.ownerDocument.body.scrollHeight)

note = Notes.findOne({_id: self.data._id}, {fields: {fullDelta: 1}})
self.editor.setContents note.fullDelta

```

**Comment by Pushkraj19** [comment]
On slower PCs, the textarea contents might not be loaded immediately and you will get truncated data, because document.readyState when you initialise your JS wrapper (CodeMirror, Quill, etc.) is not loaded yet.

The correct way of initialising a textarea wrapper is:

```
function initQuill() {
    const editorInstance = new Quill("...");
}

// In your hook
if (document.readyState == "complete") {
    initQuill();
} else {
    document.addEventListener("readystatechange", () => {
        if (document.readyState == "complete") {
            initQuill();
        }
    });
}
```
