### ISSUE TITLE
Can I create pull requests for version "1.3.7" including IE11 support?

### ISSUE THREAD

**Issue by smura** [quilljs/quill#2260]
I have several patches to fix issues with IE 11 and want to create pull requests. However, the current `develop` branch does not support IE 11.

Can I create pull requests for version "1.3.7" including IE11 support in a different way?

**My patches**

- to #1211 : https://github.com/smura/parchment/commit/f86b3626b617e4d38f2ece2095a9ce5c0dbd6824
- to #1453 : https://github.com/smura/quill/commit/44ed1a6252b8a44d916cbd19e572c682d5d7da23
- to #1698 : https://github.com/smura/quill/commit/6712dc5405672356b4ffeccaf2e88deb0d638f54
- to #2237 : https://github.com/smura/quill/commit/25bce272d64505bd8e68d7d54edffdeb1bda59d8
- to #2239 : https://github.com/smura/parchment/commit/9cb8241a2b1d909a4f02a7bc8dc0f4268f9cb735

**Comment by rodelrod** [comment]
It would be great to have these merged!

**Comment by yannbriancon** [comment]
It would be very nice to have those in a new 1.3.8 version!
