### ISSUE TITLE
Issues with formatLine and code blocks

### ISSUE THREAD

**Issue by jbbakst** [quilljs/quill#2261]
There are various issues with `formatLine` that occur when the line has the `code-block` block format. These issues do not occur if the line has block formats other than `code-block`.

**Issue 1**: setting a new block format uses the default value even if you specify a different value

**Repro steps**

1. Visit https://quilljs.com/docs/formats/
2. Copy/paste the following code block into the quill editor
```
var a = 1;
```
3. In the console, type `quill.formatLine(0, 0, 'list', 'ordered', 'user')`

**Expected behavior**: the code block line becomes an ordered list line

**Actual behavior**: the code block line becomes a bullet list line

**Issue 2**: removing block format using `formatLine` does not work when using a formats object.

**Repro steps**

1. Visit https://quilljs.com/docs/formats/
2. Copy/paste the following code block into the quill editor
```
var a = 1;
```
3. In the console, type `quill.formatLine(0, 0, {list: false, header: false, 'code-block': false}, 'user')`

**Expected behavior**: the code block line becomes plain text

**Actual behavior**: nothing happens

NOTE: this works if you do `quill.formatLine(0, 0, {'code-block': false, list: false, header: false}, 'user')`, so it seems like the order of the object properties affects the behavior.

For my particular use case, this issue would also be solved if there were a `removeLineFormat` function that removed all block formats for a given selection.

**Comment by chrisnharvey** [comment]
I too am having this issue with ```quill.format()```

For example: if I have a list, I can't remove it by calling ```quill.format('list', false)```. ```quill.format({list: false})``` doesn't work for me either.

Did you ever find a solution to this?
