### ISSUE TITLE
insert tag with class

### ISSUE THREAD

**Issue by volvor** [quilljs/quill#2266]
How can i insert tag with class.When i use dangerouslyPasteHTML , the class attributes are cleared.I want a hover effect

**Comment by martisj** [comment]
You should be able to use the `BlockEmbed` blot to create a tag with a custom classname.
1. What does your code look like?
1. What do you want to achieve?

**Comment by NiveshShastri** [comment]
I am also facing the same issue, here is the sample HTML code that I want to insert using  `dangerouslyPasteHTML`  but editor showing `undefined` while adding HTML.

`<span class="mention" data-name="@Lakshya Singh" data-type="ticketing/agent" data-id="20"><span contenteditable="false" style="color:blue">@Kaliya Singh</span></span>`
