### ISSUE TITLE
Multiple toolbars in a single editor

### ISSUE THREAD

**Issue by michael-38** [quilljs/quill#2267]
I'm currently using the bubble theme so the toolbar appears when I highlight some text in the editor. Does quill allow another toolbar so that when the user is on a new line, the toolbar appears as well (without highlighting text)?

**Comment by michael-38** [comment]
And within an editor, how can I check if the cursor is on a new line? When I use getSelection, the index is relative to the entire editor rather than the index of each line.

**Comment by benbro** [comment]
Github issues are for bugs. Please ask questions on StackOverflow.
Please don't mix multiple subjects on the same issue.

I don't think multiple toolbars for the same editor makes sense.

To check if the cursor is on a new line you can check the if the char in selectionIndex-1 == "\n"
Something like this (untested):
```
checkNewLine() {
  var range = quill.getSelection();
  if(range.index == 0) {
    return true;
  }
  var delta = quill.getContents(range.index-1, 1);
  var op = delta.ops[0];
  return op.insert && op.insert == "\n";
}
```

**Comment by itspauloroberto** [comment]
i think that multiple toolbars for the Editor really makes sense since you have done a custom tooltip using the toolbar container and his actions and behaviours, and you like to have ALSO a toolbar.

**Comment by dutzi** [comment]
+1 

Same use case, we're displaying a contextual toolbar on selection of text and another static toolbar.

**Comment by hasenov** [comment]
If someone still looking for solution, i found this codepen - https://codepen.io/elaboratecon/pen/zEbXyE and it works great

**Comment by gabrielchaves7** [comment]
After some hours, I found [this](https://github.com/quilljs/quill/issues/382) which helped me to build the following using quill-react:
Don't forge to use the snow theme, this won't work with the bubble 
```
        <ReactQuill
          ref={quill}
          value={initialValue}
          onChange={_onChange}
          onKeyDown={submitWithKeyShortcut}
          modules={modules[ 0 ]}
          theme={'snow'}
          onChangeSelection={(selection, source, editor) =>
            showFloatingToolbar(quill, selection, source, editor)
          }
        />
```

And then showFloatingToolbar is:
```
export const showFloatingToolbar = (quill, selection, source, editor) => {
  const toolbar = quill.current.editor.theme.modules.toolbar.container;
  const oldToolbarStyle = toolbar.style;

  if (selection && selection.length > 0) {
    toolbar.style.position = 'absolute';
    var toolbar_width = toolbar.offsetWidth;
    var toolbar_height = toolbar.offsetHeight;

    toolbar.style.display = 'none';
    toolbar.style.visibility = 'visible';
    toolbar.style.opacity = '0';
    toolbar.style.position = 'fixed';
    toolbar.style.transition = 'opacity 300ms, left 300ms, top 300ms';
    toolbar.style.zIndex = 10;

    var selection_dimensions = window.getSelection().getRangeAt(0)
      .getBoundingClientRect();

    if (toolbar_height + selection_dimensions.bottom > window.innerHeight) {
      toolbar.style.top = window.innerHeight - (toolbar_height + 10) + 'px';
    } else {
      toolbar.style.top = selection_dimensions.bottom + 'px';
    }

    if (toolbar_width + selection_dimensions.right > window.innerWidth) {
      toolbar.style.left = selection_dimensions.x + 10 + 'px';
    } else {
      toolbar.style.left = selection_dimensions.right + 10 + 'px';
    }

    toolbar.style.display = 'block';
    toolbar.style.opacity = 1;
    toolbar.style.backgroundColor = 'white';
  } else {
    toolbar.style = oldToolbarStyle;
  }
};
```
