### ISSUE TITLE
Difference between multiple formats in selection and total absence of the format

### ISSUE THREAD

**Issue by ctizen** [quilljs/quill#2270]
Hello,

I'm making a custom color picker and one of it's requirements is to select the default color button when there is no colored text under cursor or inside selected text, but if there is any colored text inside selection the default button should not be selected. It's required to be so even if default format (non-colored text) is encountered in the selection too.

At the moment, Quill just removes the corresponding format section from `getFormat()` result if there is any unformatted text inside the selection ([code](https://github.com/quilljs/quill/blob/develop/core/editor.js#L300)) and this seems to be rather inconsistent. I've found [this comment in an old issue](https://github.com/quilljs/quill/issues/814#issuecomment-235064620) so it looks like it's considered to be an expected behavior. But it still doesn't help to tell the difference between multiple attribute values with some unformatted text in the selection and total absence of formatting by some attribute.

How can I do this? Or can I do this at all?

**Platforms**:

any

**Version**:

1.3.6

**Comment by brendanmc6** [comment]
I would very much like to know how to do this as well!
