### ISSUE TITLE
Put multiple lines in a cell using quill2.0

### ISSUE THREAD

**Issue by SungwooJo** [quilljs/quill#2274]
I'm currently implementing a table using quill 2.0. #117 says "Does not allow multiple lines per cell or block level embed in cells", but is there any way or idea to implement multiple lines in a cell in the current table format?

**Comment by padraigfl** [comment]
This is 100% a hack, but swapping the newline characters that create new cells with tabs and the css `tab-size` value has a visual output that matches up with a newline character (on Chrome, it's a bit wonky on other browsers and will require other css)
