### ISSUE TITLE
Proposal: (Doc) write about **the correct way** to store & display quill editor content

### ISSUE THREAD

**Issue by 1c7** [quilljs/quill#2276]
### 1. Why
so far(2018-8-26) [Quill document](https://quilljs.com/) didn't say anything about what is the correct / suggest way to store and display content from quill editor

### 2. Base on my current understanding  
There are 2 way to **store and then display content** when using quill editor to write content.  

1. (Delta) __Store__ deltas into database (MySQL/PostgreSQL) (maybe as JSON). then, when __Display__, use some library convert Delta to HTML and then display    

2. (HTML)  __Store__ HTML using `quill.root.innerHTML` into database (MySQL/PostgreSQL) and then just __Display__ these HTML

### 3. Question
Would you guys write about this topic (store&display) in document?
### Thanks!

(I am still researching, If I find any new info helpful for this. I would update this issue)

### 4. info relate to this topic
https://www.bountysource.com/issues/37978100-render-quill-delta-without-instantiating-an-editor
https://github.com/quilljs/quill/issues/993
https://github.com/quilljs/quill/issues/1551

**Comment by 1c7** [comment]
I think this solution is the best one so far     
![image](https://user-images.githubusercontent.com/1804755/44628041-6bcd1f80-a96b-11e8-803e-703772e3620f.png)   
Store both format. and under different use case, use delta for editor and use HTML for display

**Comment by benbro** [comment]
Quill work with [Delta](https://quilljs.com/docs/delta/).
HTML is from users is unsafe. Best way is to store Delta in the database and render it to HTML.
Quill currently doesn't support delta to html conversion but you'll might find what you need in one of the [community projects](https://github.com/quilljs/awesome-quill).

**Comment by 1c7** [comment]
@benbro  got it. thank you.

new question: can you put these into doc? a new section, maybe here:
![image](https://user-images.githubusercontent.com/1804755/44640820-813b5b80-a9f6-11e8-9b9b-0b5b7138fb8a.png)

**Comment by benbro** [comment]
Adding a huge screenshot for each post is unneeded. Please use text only.
There is already Delta sections in docs and [guide](https://quilljs.com/guides/designing-the-delta-format/). Please submit a PR to the docs with your suggested changes if you think it can be improved.

**Comment by 1c7** [comment]
got it, thanks

**Comment by rengelking** [comment]
This was a deal breaker for me with using this; I don't want to store both Delta json and HTML; shame because looks like such a great product; I am switching to summernote

**Comment by callovarne** [comment]
It's really frustrating to invest a lot of time in understanding Quill, expecting there will be instructions along the way about rendering its content, only to learn that this project is bring-your-own-renderer. It'd be great to mention that at the beginning.

**Comment by 1c7** [comment]
A little update: (in short: I am not using Quill anymore)

because our product pivot to another direction.
we focus on App now, main feature are all on App.
website just a single landing page.

So I am not using Quill anymore. just a simple update in case anyone interested

**Comment by akinlekan28** [comment]
This is 2020 and i still find it difficult to display data saved from the editor. This is a bit disappointing i must say after going through the stress of integrating the library. It also says a lot about the library with its number of opened issues and pending pull requests

**Comment by HimanshuChugh2** [comment]
**please help me with this similar issue: https://github.com/pingcap/tidb/issues/18922**

**Comment by Reemeid** [comment]
ersrgt

**Comment by keihn** [comment]
**This is how I save delta in my database**

Firstly I create a hidden input field and use JS to handle picking the data.
```

//Get the form
   var form = document.forms['contentFrom']
          form.addEventListener('submit', (e) => {
//Get the hidden input field and set Quill's content value.
            document.getElementById('body').value = JSON.stringify(quill.getContents())
            form.unbind().submit();
          })

```

**Comment by vkment** [comment]
This works very well, at least since now:

- model definition (Django) like:
```
class Post(models.Model):
    title = models.CharField(max_length=200)
    body = QuillField()
```
- related template html file:
```
<body>
    <h1 style="text-align: center;"><u>{{info.title}}</u></h1>
    {{info.body.html | safe}}
</body>
```

The displaying html page not only does not contain any Quil js code, it need not contain any javascript at all. Just HTML tags are fine.

Sure, differing CSS would influence the visual result. But you can probably enforce such CSS as you like.

I have taken it from this [tutorial ](https://pythonguides.com/quill-editor-in-django/)

**Comment by kh09211** [comment]
In case anyone comes across this and finds this useful. You don't need to use innerHTML to render the delta, you can instantiate a new quill object with the settings of readonly and no toolbar, use CSS to remove the border if you want.

`const quill = new Quill('#renderDiv', {
            modules: {
                toolbar: false
            },
            readOnly: true
    });

   // render the content
  quill.setContents($delta)`
        
  To save the delta in the database I use JSON.stringify($delta) like above, with a listener that updates a hidden input
  
  `
        quill_{{ $fieldName }}.on('text-change', function(delta, oldDelta, source) 
        {
            let deltaData = JSON.stringify(quill.getContents());
            document.getElementById('#deltaDataDiv').value = deltaData;
        });`
