### ISSUE TITLE
Changing Link Title rather than just URL

### ISSUE THREAD

**Issue by Luciam91** [quilljs/quill#2277]
Hello,

We are currently using Quill to power our text editor and for the most part it provides most of what we need. However, one thing that we noted with the snow theme was that you can't edit the title of a link, but rather just the URL content.

Most editors will allow for the editing of both the title and URL, I've tried extending the theme to add this option but this seems like a long, cumbersome workaround for something like this.

What I'd like to know is either A) if it's possible this is likely to be added to the core them, or B) If there are any guides on providing our own theme to add this option?

**Comment by 1c7** [comment]
Hi @Luciam91

sorry I didn't understand you description.   

## if you want edit title:
https://codepen.io/1c7/pen/KxzMEW
![image](https://user-images.githubusercontent.com/1804755/44640436-3ae4fd00-a9f4-11e8-8ab3-61fd1d433293.png)
just edit it like text
![image](https://user-images.githubusercontent.com/1804755/44640449-49cbaf80-a9f4-11e8-9b94-31eb04101ab1.png)

### If you want edit link

![image](https://user-images.githubusercontent.com/1804755/44640473-68ca4180-a9f4-11e8-8b5f-698d14677a68.png)
![image](https://user-images.githubusercontent.com/1804755/44640476-6cf65f00-a9f4-11e8-8b09-517340fc85f7.png)

**Comment by 1c7** [comment]
oh wait. you mean `<a title='x'>` ?
when mouse hover, it show title. that's what you mean right?

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/44640549-e0986c00-a9f4-11e8-9bbe-f55df540d1a3.png)
![image](https://user-images.githubusercontent.com/1804755/44640556-ec842e00-a9f4-11e8-8014-8ea94e7d6cd0.png)
(I am editing this directly in Chrome developer tool)

**Comment by 1c7** [comment]
@Luciam91 

base on my current understanding.      
Quill doesn't provide this kind of edit right out of box.    
you have to code this yourself. 

btw I am also just a user of Quill. not core team developer.

**Comment by rawkode** [comment]
@1c7 Can you share your code for this?

**Comment by 1c7** [comment]
@rawkode Sure I can share 😄  I have to a bit of clean up. 
I am using Quill in a Vue.js SPA App(vuex, vue-router, single file component etc)
I may do it tonight or tomorrow. I have work to do now.

**Comment by rawkode** [comment]
Thanks @1c7

**Comment by 1c7** [comment]
## (Quill Editor) Code for link input ("Text" & "Link")
(work in progress) (20% done)

## Final Result showcase
![image](https://user-images.githubusercontent.com/1804755/44850943-6e908300-ac91-11e8-9d2b-4cd629cfc3b8.png)
![image](https://user-images.githubusercontent.com/1804755/44850962-76e8be00-ac91-11e8-8a38-f0c8edc5654a.png)
![image](https://user-images.githubusercontent.com/1804755/44850975-7ea86280-ac91-11e8-9d07-7ed1df54d0f5.png)
![image](https://user-images.githubusercontent.com/1804755/44850993-87993400-ac91-11e8-88da-c8cc5154d297.png)
![image](https://user-images.githubusercontent.com/1804755/44851043-a8618980-ac91-11e8-9d2e-2cc6292ddfd8.png)



## Step 1
Use custom toolbar.  

Something like this. (This is HTML but written in Pug): 
```pug
#toolbar-container
    div.wit-link.have_hint(@click='add_link')
      img(src="/static/editor-icon/editor-new/link_2.svg" style='width:18px;')
#editor_wrapper
    #editor
```

Javascript
```javascript
      var editor = new Quill('#editor', {
        modules: {
          toolbar: '#toolbar-container'
        },
        theme: 'snow',
      });
```

## Step 2

**Comment by 1c7** [comment]
because I want `target = "_blank"`

Here is LinkBolt I am using.  I remember I copy this from Quill tutorial
```javascript
      let Inline = Quill.import('blots/inline');
      class LinkBlot extends Inline {
        static create(url) {
          let node = super.create();
          node.setAttribute('href', url);
          node.setAttribute('target', '_blank');
          return node;
        }
        static formats(node) {
          return node.getAttribute('href');
        }
      }
      LinkBlot.blotName = 'link'; // this name
      LinkBlot.tagName = 'a';
      Quill.register(LinkBlot);
```

**Comment by 1c7** [comment]
## the key part is just
```javascript
quill.insertText(index, 'Google', 'link', "https://Google.com");
```

**Comment by 1c7** [comment]
@rawkode  I hope this is helpful.

**Comment by rawkode** [comment]
Thank you very much, @1c7. That's awesome

**Comment by 1c7** [comment]
Hi @Luciam91 have you solve your problem?
if so, can you close this issue?
if not, you could keep posting question here

**Comment by rawkode** [comment]
@1c7 I can't work out how this code helps editing of an already inserted link. Am I missing something? :)

**Comment by 1c7** [comment]
@rawkode 
Oh, my code above just **insert link**. if you want edit it.   
For example when cursor within the link, and click "Link" button again for editing. 
that part I didn't code.

![image](https://user-images.githubusercontent.com/1804755/45020989-ffd17200-b062-11e8-8b2e-d080f593b2ec.png)

if you want that:
```
when click "Link" button:
   if cursor within link:
       it's edit
   else
      it's add new link
```

**Comment by nereuseng** [comment]
@1c7 Hi,
How do i override the tool-tip shown default behavior when I click the Link? At first, I was tried to use default tool-tip to edit link, but the whole input text will missing.
Could you share how you solved this problem?
Thanks in advance. :)

![image](https://user-images.githubusercontent.com/11313394/51722771-7c580200-2091-11e9-9dcb-74f729f2cf58.png)

![image](https://user-images.githubusercontent.com/11313394/51722838-bd501680-2091-11e9-9cbb-03fa01bf6a8b.png)

![image](https://user-images.githubusercontent.com/11313394/51722897-f38d9600-2091-11e9-96dc-10cbee64155b.png)

**Comment by 1c7** [comment]
@nereuseng 
Sorry I can't answer your question.
I am not using Quill since (I think) August 2018 or so.
I am working on a Wechat mini App now (it's like a app but use html/css/js, run on Wechat, cross platform)

I can't remember how to do that. sorry

**Comment by 1c7** [comment]
At first, our website can write content with format, like a blog. 
but seem like people use/spend time on phone far more than laptop
so we just pivot into an App only product.
and we lower the bar for user post content again and again.

now we look like Instagram. ah.

**Comment by ArsalanSavand** [comment]
For those who are still looking for a solution, I posted my code here with full explaination, goodluck )
https://coding.gonevis.com/how-to-edit-target-attribute-in-quilljs-links/

**Comment by markleppke** [comment]
Dear QuillJS, 

Please look at supporting this request. The user experience around the link tool in quill leaves much to be desired. During usability tests we have users clicking on the link formatting tool expecting the link button to open a dialog allowing them to enter display text and the URI. Due to expectations from other tools like word or google docs. And from how other Quill tools behave.

![image](https://user-images.githubusercontent.com/2591505/152367539-8940e2ca-e600-43ff-a698-842927a00c65.png)

As you can see above, in microsoft word, user can edit both the link display text and URI without first selecting text. This handles user interactions more gracefully, vs forcing them to know they have to first select text to start with. Other quill tool formats allow a user to click first, then type, quillJS immediately starts using the new format. E.g. if I use a blank instance of quill and  click "B" to bold text and start typing, the following text is bold. Quill already teaches users that you can first click a button and expect quill to start formatting as expected. However in this one case, link tool, you force users to first type and then select text to enter the details. 

Thanks,

Mark

**Comment by equilerex** [comment]
Came up with a fairly heavy frankensteing of a solution for this since being able to edit the text and the target were a hard requirements on a project i worked on (and we already used too much of it for it to be worh picking a new library). 
for those poor souls who need to tackle similar issues in the future, maybe this will give you some ideas:
(built for angular in typesript)

```typescript
import { EventEmitter, Injectable, SecurityContext } from '@angular/core';
import * as Quill from 'quill';
import MagicUrl from 'quill-magic-url';
import { DomSanitizer } from '@angular/platform-browser';
import { QuillLinkEditorModalComponent } from '../components/quill-link-editor-modal/quill-link-editor-modal.component';
import { ModalService } from './modal/modal.service';

// service for being able to change the text and target of the link/format within quillJs through a custom popup modal
// Note: this is a bit of a frankenstein but there were no easy ways to handle the target attr without modifying the framework.
let rootSanitizer = null;
@Injectable()
export class QuillExtendService {
  constructor(private modalService: ModalService, private sanitizer: DomSanitizer) {
    const rootModalService = this.modalService;
    rootSanitizer = this.sanitizer;
    const Link = Quill.import('formats/link');

    // note: this will extend the link universally across all quill instances which are open.
    class LinkBlot extends Link {
      static create(value) {
        // fallback to when link is just an url string (default quill behaviour)
        const urlOnly = typeof value === 'string';
        const node = super.create(urlOnly ? value : value?.url);
        node.setAttribute('href', urlOnly ? value : value?.url);
        node.setAttribute('target', urlOnly ? '_blank' : value?.target || '_blank');
        node.setAttribute('rel', 'noreferrer noopener');
        node.setAttribute('contenteditable', 'false');

        // handle editing of created links
        // Note: we have hidden the native quilljs .ql-tooltip through css
        node.addEventListener('click', function (e) {
          e.preventDefault();
          e.stopPropagation();
          rootModalService
            .openWithConfig(QuillLinkEditorModalComponent, {
              href: node.href,
              text: node.innerText,
              target: node.target || '_blank'
            })
            .result.subscribe((result) => {
              if (result.type === 'CONFIRM') {
                node.innerText = result.value.text;
                node.setAttribute('href', result.value.href);
                node.setAttribute('target', result.value.target);
              }
            });
        });
        return node;
      }
      static formats(domNode) {
        return { url: domNode.getAttribute('href'), target: domNode.getAttribute('target') };
      }

      // native quill sanitise would strip the target attr, so replace with angular
      static sanitize(url) {
        return rootSanitizer.sanitize(SecurityContext.URL, url) || '';
      }

      format(name, value) {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        if (name !== this.statics.blotName || !value?.url) return super.format(name, value?.url);

        // native quill sanitise here would strip the target attr
        const sanitizedUrl = rootSanitizer.sanitize(SecurityContext.URL, value?.url);
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        this.domNode.setAttribute('href', sanitizedUrl);
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        this.domNode.setAttribute('target', value?.target || '_blank');
      }
    }
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    LinkBlot.blotName = 'link';
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    LinkBlot.tagName = 'a';

    Quill.register('formats/link', LinkBlot, true);
    // Add links to quill editor and make them clickable
    Quill.register('modules/magicUrl', MagicUrl, true);
  }

  //  Creating of new links through the toolbar
  quillToolbarLinkHandler({ editorInstance }) {
    editorInstance.focus();
    const range = editorInstance.getSelection();
    this.modalService
      .openWithConfig(QuillLinkEditorModalComponent, {
        href: '',
        text: editorInstance.getText(range.index, range.length),
        target: '_blank',
        // used for hiding the "text" input in case you are applying a link to a selection
        // (only url available then - otherwise if you have multiple blobs selected, it would get messy, so this is the easy workaround)
        selection: range.length > 0
      })
      .result.subscribe((result) => {
        if (result.type === 'CONFIRM') {
          const { index } = editorInstance.getSelection(true);
          const nextIndex = index + result.value.text?.length || 0;
          // adding a whole new blob
          if (range.length == 0) {
            // just add the text first - doing it this way will help avoiding issues with text caret caused by contenteditable=true on the html element
            editorInstance.insertText(index, result.value.text);
            editorInstance.insertText(nextIndex, ' ');
            editorInstance.setSelection(index, result.value.text.length);
          }
          editorInstance.format('link', { url: result.value.href, target: result.value.target }, Quill.sources.USER);
          editorInstance.setSelection(nextIndex + 1, 0);
        }
      });
  }

  // clipboard.convert() used for converting html to quill needs link handling as well
  quillClipboardLinkHandler(node, delta) {
    if (node.target) {
      const Delta = Quill.import('delta');
      const newDelta = new Delta().insert(node.textContent, {
        ...(delta.ops[0].attributes || {}),
        // unable to set "link: { url, target }" here directly since it is overwritten later somewhere in the plugin. so using temporaryPasteTarget which needs to be cleaned additionally through quillClipboardPostConvert()
        temporaryPasteTarget: node.target || '_blank'
      });
      return newDelta;
    }

    return delta;
  }

  // needs to be applied to clipboard.convert() if quillClipboardLinkHandler is used.
  quillClipboardPostConvertCleanup(deltaOps) {
    return {
      ...deltaOps,
      ops: deltaOps.ops.map((op) => {
        if (op?.attributes?.temporaryPasteTarget) {
          return {
            ...op,
            attributes: {
              link: {
                url: op.attributes.link,
                target: op.attributes.temporaryPasteTarget
              }
            }
          };
        }
        return op;
      })
    };
  }

  // backspace does not work well with contentEditable=true (like the link format)
  // where selection enters inside the element and then is unable to continue - delete the whole block instead when we reach it
  quillBackspaceFix() {
    return {
      bindings: {
        list: {
          key: 'backspace',
          context: {
            format: ['list']
          },
          handler: function (range, context) {
            if (range.index === 0 && range.length === 0) return;
            if (range.length === 0) {
              const size = context?.format?.link ? context.prefix.length : 1;
              this.quill.deleteText(range.index - size, size, Quill.sources.USER);
            } else {
              this.quill.deleteText(range, Quill.sources.USER);
            }
          }
        }
      }
    };
  }
}
```


and to apply it:

`
// create quill instance
    this._quillEditor = new (<any>Quill)(this.editorElem, {
      modules: {
        magicUrl: !!this.htmlMode,
        toolbar: {
          container: this.htmlMode ? toolbarOptions : null,
          handlers: {
            link: () => {
              this.quillExtendService.quillToolbarLinkHandler({ editorInstance: this._quillEditor });
            },
          },
        },
        clipboard: {
          matchers: [[Node.ELEMENT_NODE, this.quillExtendService.quillClipboardLinkHandler]],
        },
        keyboard: this.quillExtendService.quillBackspaceFix(),
      },
      placeholder: this.placeholder.trim(),
      readOnly: this.readOnly,
      theme: 'snow',
      formats: [...(this.htmlMode ? htmlFormats : []), 'interpolate'],
      bounds: this.editorElem,
    });
    
essentially:

-  if you just click on the link in the toolbar, you'll get a modal popup to enter the link.
- to edit an existing link, you just click on the link and it will re-open the modal
- when you highlight a selection and click link in the toolbar, you are only able to add link and target, no changing of the text



    
![image](https://user-images.githubusercontent.com/5556216/160605967-72eabfe7-0282-48c4-875a-0c26a19153ef.png)
![image](https://user-images.githubusercontent.com/5556216/160605986-3018795a-24ea-4d64-8f85-1598739dde15.png)




`

**Comment by SJNBham** [comment]
We'd like to see this enhancement built into the standard editor as well. 

Thanks

@Luciam91 - see the following for some additional link management enhancements you might chime in on:

https://github.com/quilljs/quill/issues/3860
https://github.com/quilljs/quill/issues/3859
https://github.com/quilljs/quill/issues/3858

**Comment by nomiich05** [comment]
here is what I have implement for adding both the title and URL

import { employeeService } from '@/app/services/employee/employee.service';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Quill } from 'react-quill';

interface UseQuillEditorParams {
	isMention: boolean;
	isVideoEmbedEnabled: boolean;
}


export function useQuillEditor({
	isMention,
	isVideoEmbedEnabled,
}: UseQuillEditorParams) {
	const editorRef = useRef<any>(null);

	const [showModal, setShowModal] = useState(false);
	const [modalLinkTitle, setModalLinkTitle] = useState('');
	const [modalLinkUrl, setModalLinkUrl] = useState('');

	const openLinkModalWithSelectedText = () => {
		const quillEditor = editorRef.current.getEditor();

		let range = quillEditor.getSelection();

		if (!range) {
			range = { index: quillEditor.getLength(), length: 0 };
		}

		const text =
			range && range.length > 0
				? quillEditor.getText(range.index, range.length)
				: '';

		setModalLinkTitle(text);
		setModalLinkUrl('http://');

		setShowModal(true);

	};

	const customLinkHandler = () => {
		openLinkModalWithSelectedText();
	};


	const submitLinkModal = () => {
		const quillEditor = editorRef.current.getEditor();
		const range = quillEditor.getSelection(true); 
	  
		if (modalLinkUrl) {
		  if (range && range.length > 0) {
			quillEditor.deleteText(range.index, range.length);
		  }
	  
		  const insertText = modalLinkTitle || modalLinkUrl; 
		  const linkCursorPos = range.index + insertText.length; 
	  
		  quillEditor.insertText(range.index, insertText, 'link', modalLinkUrl);
	  
		  quillEditor.setSelection(linkCursorPos, 0);
		}
	  
		setShowModal(false);
		setModalLinkTitle('');
		setModalLinkUrl('');
	  };
	  

	const videoButtonHandler = useCallback(() => {
		if (editorRef.current) {
			const quillEditor = editorRef.current.getEditor();
			const tooltip = quillEditor.theme.tooltip;
			tooltip.show();
			tooltip.edit('video');
			tooltip.textbox.focus();
		}
	}, []);

	const modules = useMemo(() => {
		let toolbarOptions = [
			['bold', 'italic', 'underline'],
			[{ list: 'ordered' }, { list: 'bullet' }],
			[{ align: [] }],
			['link'],
			['strike'],
			...(isVideoEmbedEnabled ? [['video']] : []),
		];

		return {
			mention: isMention
				? {
						allowedChars: /^[A-Za-z\sÅÄÖåäö]*$/,
						mentionDenotationChars: ['@'],
						spaceAfterInsert: true,
						isolateCharacter: true,
						source: async (
							searchTerm: string,
							renderItem: (
								arg0:
									| { id: number; value: string }[]
									| undefined,
								arg1: any,
							) => void,

							mentionChar: string,
						) => {
							const payload = {
								search: {
									name: searchTerm,
								},
							};

							const { data: list } = await employeeService.list(
								payload,
							);

							const formattedData = list.map((item: any) => ({
								id: item.id,
								value: item.name,
								link: `/${item.username}/profile`,
							}));

							renderItem(formattedData, searchTerm);
						},
				  }
				: undefined,
			toolbar: {
				container: toolbarOptions,
				handlers: {
					video: isVideoEmbedEnabled ? videoButtonHandler : () => {},
				},
			},
		};
	}, [isMention, isVideoEmbedEnabled, videoButtonHandler]);

	useEffect(() => {
		if (editorRef.current) {
			const quillEditor = editorRef.current.getEditor();

			quillEditor
				.getModule('toolbar')
				.addHandler('video', videoButtonHandler);

			const toolbar = quillEditor.getModule('toolbar');
			toolbar.addHandler('link', customLinkHandler);
		}

		if (typeof window !== 'undefined') {
			require('quill-mention');

			const Quill = require('react-quill').Quill;
			const MentionBlot = Quill.import('blots/mention');

			class StyledMentionBlot extends MentionBlot {
				static create(value: any) {
					const link = document.createElement('a');
					link.href = value.link;
					link.innerText = value.value;

					return link;
				}
			}

			StyledMentionBlot.blotName = 'mention';
			Quill.register(StyledMentionBlot);
		}
	}, [videoButtonHandler, isMention, customLinkHandler]);

	return {
		editorRef,
		modules,
		showModal,
		setShowModal,
		modalLinkTitle,
		setModalLinkTitle,
		modalLinkUrl,
		setModalLinkUrl,
		submitLinkModal,
	};
}

**Comment by ludejun** [comment]
You can use [quill-react-commercial](https://github.com/ludejun/quill-react-commercial).

It can edit link's text and url again.
![quill-copy-link](https://github.com/quilljs/quill/assets/5129913/d211ffd8-467d-4b6c-96f7-16d3a4552869)
