### ISSUE TITLE
Configurable block tag (div, paragraph)

### ISSUE THREAD

**Issue by alexeckermann** [quilljs/quill#228]
Whilst div tags are quite acceptable for most cases, there are some uses where paragraph tags are necessary over div's.

As an example: I work on an application that allows authors to write content for ePubs. For both logical structure and ePub rendering reasons we like to use paragraph tags. 

From a very shallow inspection of the source it would appear this would involve changing references to the `dom.DEFAULT_BLOCK_TAG` variable with an option defined at initialisation.

- Is there enough reason to warrant this change?
- Are there any unintended consequences of implementing a change like this? @jhchen
- How should configuration be handled? Define in the constructor options hash as `block_tag: 'p'`?

**Comment by nicovalencia** [comment]
:+1:

**Comment by nicovalencia** [comment]
@jhchen what's the normalizer looking like? Are @alexeckermann or you working on the change to make this configurable? If not, perhaps I can help lift. We have Quill configured, but absolutely need content wrapped in `<p>` tags for it to meet requirements.

I'd much rather help contribute than just hack this into a fork. Just don't want to double up on work. (And I have no context into this project/source so it would take me a while to get ramped up).

Thanks,
Nico

:pear:

**Comment by james2doyle** [comment]
This may be irrelevant for most, but I am using this editor in a CMS, and I have the following running before the content is saved to my database:

```php
// swap div tags with p
$value = str_replace('div>', 'p>', $value);
// remove the empty sections now
$value = str_replace('<p><br></p>', '', $value);
```

This just runs each time I save my page. It works nicely at the moment. I am sure for more complicated code, this would not be as helpful.

**Comment by antonholmquist** [comment]
+1 for being able to use paragraphs instead of divs.

By the way, thanks for a great editor!

**Comment by Machiel** [comment]
:+1:

**Comment by discoliam** [comment]
:+1:

**Comment by murashki** [comment]
I can't understand how this work: http://codepen.io/SaraVieira/pen/eaAcu
It use `p` instead of `div`. How?

**Comment by jhchen** [comment]
They seem to either have their own fork or build that probably changed the `DEFAULT_BLOCK_TAG` constant (and got rid of the browser default padding on paragraph tags).

**Comment by murashki** [comment]
Tnx!

**Comment by hpaul** [comment]
:+1:

**Comment by Mad-Chemist** [comment]
Has no progress been made to make this a customizable option?  Surely there should be some mapping for ALL tags to allow customization.

I currently need to use paragraph tags instead of divs, in addition to some other changes.  Its a bit discouraging to see that this hasn't been resolved yet.

**Comment by JoshWillik** [comment]
I'd also like to have this. I'm going to use something similar to @james2doyle 's solution for the time being, but I'd love to be able to have `<p>` tags instead.

@jhchen I'm open to help get this working if you can point me in the right direction.

**Comment by seaneking** [comment]
:+1: we're strongly considering using Quill in [Simpla](https://simpla.io) but non-standard content elements (eg: divs instead of ps) are a dealbreaker for inline editing.

**Comment by Jesterovskiy** [comment]
:+1: need this changes too

**Comment by jhchen** [comment]
The default block tag in the 1.0 [beta](http://beta.quilljs.com) release is `<p>`, with no bottom margin. If you want the bottom margin you can add it with css. If you want the default block tag to be `<div>` like it was before, you can configure with Parchment:

```js
var Parchment = Quill.import('parchment');
var Block = Parchment.query('block');
Block.tagName = 'DIV';
// or class NewBlock extends Block {}; NewBlock.tagName = 'DIV';
Quill.register(Block /* or NewBlock */, true);

// Create your Quill editor like before
var quill = new Quill('#editor');
```

**Comment by davidgiven** [comment]
Hurray --- thanks!

**Comment by Jesterovskiy** [comment]
Thank you =)

**Comment by jadamconnor** [comment]
Any ideas on how to implement this solution in Typescript in an Angular 2 project?

**Comment by DvzH** [comment]
After making DIV as a block tag I wanted to add SCRIPT tag inside it but I am only able to see DIV but not SCRIPT tag even it's same with other div's like SECTION , ARTICLE etc.

Can somebody help me.. ??

Thanks in advance

**Comment by psy21d** [comment]
I very important need to add custom div nodes with classes
I use it as a page for printing

Yow I can make it?

**Comment by saminlu** [comment]
> This approach does not work with multiple instances of Quill editor in the same page using different tagNames.
> 
> ```
> let Block = Parchment.query('block');
> Block.tagName = 'DIV';
> Quill.register(Block, true);
> let editor1 = new Quill({...});
> ```
> 
> ```
> let Block = Parchment.query('block');
> Block.tagName = 'P';
> Quill.register(Block, true);
> let editor2 = new Quill({...});
> ```
> 
> Both editors are using same last tagName='P'.
> Do you know any way to do that?
@mdperez86   I have the same issue, do you know how to do that?

**Comment by marsielko** [comment]
@saminlu @mdperez86 Hi guys, I'm currently facing the same issue, where I have multiple instances of Quill editor and I'd like to use <p> in one instance and <div> in the other. Have you found any way to reach that goal?
