### ISSUE TITLE
Replacing embed isn't removing its content

### ISSUE THREAD

**Issue by makepanic** [quilljs/quill#2285]
Hi, thanks for this great library.

I've found an issue when replacing an inserted inline embed.
Somehow the embed content isn't "replace" from the quill instance. This means while not visible, it still exists in its content.

**Steps for Reproduction**

1. Visit https://codepen.io/makepanic/pen/pOEZZo?editors=0011
2. Select the embed blot (mention)
3. Type any text

![quill-embed-replace](https://user-images.githubusercontent.com/1205444/44791257-812b8f00-aba1-11e8-8961-9e707a36ff4a.gif)

**Expected behavior**:
Console (`quill.getContents()`) should not contain any embed blot information as it's not visible anymore.

**Actual behavior**:
Console (`quill.getContents()`) contains any embed blot information

**Platforms**:
Confirmed to happen in latest Firefox and Chrome

**Version**:
1.3.6

I'm a beginner to quill so I'm not sure if it's misusing the embed api and this is expected behavior.

**Comment by makepanic** [comment]
While working around this issue i found that there's also an empty element in the DOM which maps to the "hidden" embed.

![20180904-130947](https://user-images.githubusercontent.com/1205444/45029672-bf192f00-b049-11e8-9721-dc7674717f67.png)

![20180904-130938](https://user-images.githubusercontent.com/1205444/45029676-c17b8900-b049-11e8-8296-fe01bb3cd787.png)

**Comment by volser** [comment]
I think this is similar issue https://github.com/quilljs/quill/issues/2187

**Comment by furqan56** [comment]
I'm facing the same issue as it doesn't update the content 
![quill bug 2](https://user-images.githubusercontent.com/21037237/49657260-153ea980-fa61-11e8-90ed-ea88a9c80206.PNG)
However, it works fine if the user first click on the text area move the cursor left or right and remove the blot I have even tried on the above example it worked 
![quill-bug](https://user-images.githubusercontent.com/21037237/49657353-53d46400-fa61-11e8-824c-ead97a7cc596.PNG)

**Comment by furqan56** [comment]
It doesn't happen all the time it only happens 3/5 times

**Comment by jakeboyles** [comment]
+1

**Comment by cmrd-senya** [comment]
It doesn't happen in the fresh Firefox for me, but still an issue in Chrome. The related bug report in Chrome for this one is https://bugs.chromium.org/p/chromium/issues/detail?id=1063046

**Comment by luin** [comment]
Fixed in https://github.com/quilljs/quill/pull/3807. Feel free to let me know if there is anything missing. Closing
