### ISSUE TITLE
Text is deleted when browser translation is enabled

### ISSUE THREAD

**Issue by mikecousins** [quilljs/quill#2286]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit quilljs.com in Chrome
2. Turn on browser translation (I used English to French)
3. Type in the editor box

**Expected behavior**:
Text will show up and maybe be translated???

**Actual behavior**:
Text is deleted

**Platforms**:
Windows 10
Chrome Latest

**Version**:
Latest

**Comment by mikecousins** [comment]
Video of it happening:
https://drive.google.com/file/d/125dwRbgCC6vIusdqK5va0WWBUkPkTpED/view?usp=sharing

**Comment by quincarter** [comment]
I am experiencing the same issue. There is a small fix you can do that will turn off the translations for the whole browser -- 
`<meta name="google" content="notranslate" />`

But that isn't ideal if your site is supposed to support i18n translations/Localization. I have yet to find a fix for the quill editor, but if I had access to the input on the DOM, i have found that this actually works with other `<input />` elements:
`<input class="kw" translate="no" />`

**Comment by stirelli** [comment]
Same issue reported here.

Do you know if this issue is fixed or it would be in 2.0 final ?

**Comment by Andries-Smit** [comment]
Found a work around, just add the class `nostranslate` to a parent node.

https://cloud.google.com/translate/faq#technical_questions

Thanks to: https://stackoverflow.com/questions/9628507/how-can-i-tell-google-translate-to-not-translate-a-section-of-a-website

**Comment by hubertfilho** [comment]
I'm experiencie the same problem with quill-editor version 1.3.7 in Angular.js.

When I enable translation to the page the text is self-deleted.

As I saw the ng-model set in quill, like this <quill ng-model="myVariableInController" />, can't change/set value when translation is enable, coming back to normal when I set "show original" in Google Translate.

For now, I used this workaround <meta name="google" content="notranslate" />, but it isen't the definity solution for me.

Strangely, when quill was open inside a modal the problem doesn't occurs.

Any ideas?

(sorry about my english)

**Comment by kernelpop** [comment]
Has there been any progress on this issue? Not sure if the responsibility party is Quill or Google Translate.

The suggested workaround breaks the functionality I'm looking for. I'd like the Translate plugin to be able to translate contents in the Quill editor. The current behavior is that the text is deleted instead.

**Comment by mseibert** [comment]
This is something that affects us as well. Did anyone ever analyzed which options could be available? Is there a way to contribute to a solution?

**Comment by jdepoix** [comment]
As we didn't consider disabling translations a proper solution, I analysed this issue and actually was able to find a solution, which I submitted in PR #3414.

If anyone is also struggling with this and doesn't want to wait for this PR to be merged, you can run the following monkey-patch to solve the problem for now:
```js
const quill = new Quill('#editor', {
  // ...
});

const updateScroll = quill.scroll.update.bind(quill.scroll);
quill.scroll.update = (mutations, context) => {
  if (!quill.isEnabled()) {
    return;
  }
  updateScroll(mutations, context);
}
```

**Comment by SylvainBigonneau** [comment]
Hey everyone, is this issue still being considered?

I still have to use @jdepoix's (quite extensive yet effective) workaround on v1.3.7

**Comment by jdepoix** [comment]
@SylvainBigonneau given the amount of open pull requests and issues without any activity, this project doesn't seem to be actively maintained. Therefore, I wouldn't put my hopes up to high for this PR to be merged anytime soon 🤷‍♂️
