### ISSUE TITLE
ql-align html tag in custom toolbar throw error

### ISSUE THREAD

**Issue by Heyxuxiaoting** [quilljs/quill#2287]
I want to create a custom toolbar in HTML, but when I add ql-align tag, I got this error:

```
TypeError: Cannot read property 'innerHTML' of null
    at IconPicker.selectItem (quill.js:9693)
    at new IconPicker (quill.js:9684)
    at quill.js:6739
    at Array.map (<anonymous>)
    at SnowTheme.buildPickers (quill.js:6734)
    at SnowTheme.extendToolbar (quill.js:9851)
    at SnowTheme.addModule (quill.js:6703)
    at quill.js:6049
    at Array.forEach (<anonymous>)
    at SnowTheme.init (quill.js:6047)
```

**Steps for Reproduction**

code in html: 
```
<select class="ql-align" />
```
**Platforms**: Chrome 68 on Mac 10.12.6

**Version**: "quill": "^1.3.6"

**Comment by benbro** [comment]
Please fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) and show what you are trying to do.

**Comment by Heyxuxiaoting** [comment]
@benbro I've found the reason, I forget to clear the already mounted quill dom, rendering again lead to the error.  It has nothing to do with quill. Thanks anyway, respect✌(◕‿-)✌

**Comment by akashanand708** [comment]
@Heyxuxiaoting , how did you solve this problem? I faced this problem at the exact line number.
Today, i upgraded from react 15.6.1 to react 16.8.5, after that i upgraded react quill to latest one.

**Comment by rickysychan** [comment]
@Heyxuxiaoting facing the exact same issue could you elaborate on how you fixed this?

**Comment by Leoohn** [comment]
Facing the same issue. Would love to know how you "rendered again". @Heyxuxiaoting

**Comment by strap8** [comment]
Facing the same issue. Please share the solution please.

**Comment by Heyxuxiaoting** [comment]
> Facing the same issue. Please share the solution please.

Hi，I'm sorry for my late reply.
This is how I solve this problem in my case:
```js
didMount && <Editor /> // enter my page

this.setState({     // leave my page
    didMount: false
})
```

I'm not sure if it's suitable for your case, but what is important i think is to reload quill component again after you get your editor show. Set didmonut to be false when you leave current spa router view or in the componentWillUnmount period may do some help.

**Comment by jvnlwn** [comment]
Ran into this error when using [react-quill](https://github.com/zenoamaro/react-quill) (version 1.3.5, quill version 1.3.7).

In my case, it was occurring when rending multiple quill editors each with their own custom toolbar.

```javascript
const QuillEditor = () => (
  <>
    <div className="toolbar">
      <select className="ql-align" />
    </div>
    <ReactQuill modules={{ toolbar: ".toolbar" }} />
  </>
)

const App = () => (
  <>
    <QuillEditor />
    <QuillEditor />
  </>
)
```

Rendering `<App />` will fail with the error `Unhandled Rejection (TypeError): Cannot read property 'innerHTML' of null`

Without the custom toolbar, the error is resolved:
```javascript
const QuillEditor = () => (
  <ReactQuill modules={{ toolbar: [[{ align: [] }]] }} />
)
```

To fix the issue in my case, the solution was to provide a unique className to the toolbar:
```javascript
const QuillEditor = ({ className }) => (
  <>
    <div className={`toolbar ${className}`}>
      <select className="ql-align" />
    </div>
    <ReactQuill modules={{ toolbar: `.${className}` }} />
  </>
)

const App = () => (
  <>
    <QuillEditor className="test-1" />
    <QuillEditor className="test-2" />
  </>
)
```

And in my real-world case, I elected to generate a unique className on the fly when the component mounts, this way I don't have to supply one whenever I render the component.

_NOTE: Ideally, quill would allow you to alternatively provide the actual HTML node as the container. That would remove the need for unique classNames or IDs. Maybe this is already possible? But it did not seem to work when I tried._

**Comment by magicops** [comment]
Thanks to @jvnlwn comment, I had the same issue, on my side, I just needed to set the editor ids differently.
