### ISSUE TITLE
Page never loads after submitting an embeeded youtube video

### ISSUE THREAD

**Issue by marcosdipaolo** [quilljs/quill#2297]
**Expected behavior**:
To be able to embed a youtube video with normal behaviour 

**Actual behavior**:
Once form submits the page keeps trying to load, the site completely stop loading when a youtube video was part of the content. 

**Platforms**:
Laravel 5.6

**Include browser, operating system and respective versions**
Chrome Versión 68.0.3440.106 (Build oficial) (64 bits). MacOS 10.12.6

**Version**:
quill 1.3.6

**Comment by benbro** [comment]
You probably have an issue with the way you render the content. Not related to Quill.

**Comment by marcosdipaolo** [comment]
You are right, if I hardcode a video in my blade file it doesn't open it as well. 
Mhmm, what could it be....
