### ISSUE TITLE
Multiple adjacent spaces

### ISSUE THREAD

**Issue by MgSam** [quilljs/quill#2299]
Quill is creating HTML, so naturally any consecutive spaces are collapsed into a single space. 

Is there a way to get Quill to record spaces as `&nbsp;` when they're typed instead of regular spaces? This would transparently allow users to format documents as they expect.

Sorry if this is covered elsewhere- the other issues I found were all about copy/pasting.

**Comment by benbro** [comment]
You should be using [Delta](https://quilljs.com/docs/delta/), for example with [getContents](https://quilljs.com/docs/api/#getcontents) and not the raw HTML.
The delta will give you all the spaces.

**Comment by benbro** [comment]
Please read this [answer](https://github.com/quilljs/quill/issues/903#issuecomment-243844178).
You'll might find a [community project](https://github.com/quilljs/awesome-quill) that will help you.
Please read the Delta Converters section in the [Quill 2.0 blog post](https://medium.com/@jhchen/the-state-of-quill-and-2-0-fb38db7a59b9).
Quill 2 is still in development.
