### ISSUE TITLE
Trying to save to firestore

### ISSUE THREAD

**Issue by Fawwaz-2009** [quilljs/quill#2300]
I was trying to save data from quill to firestore and restore it next time  I need quill. I initially tried to extract the html and then find the method to restor it to quill, but soon found out that _"dangerouslyPasteHTML" is big no no. So next I tried just save the data as a Delta object and then I can easily restore it using _"setContents"_ .
**However**, and here comes the problem firestore doesn't allow custom object to be saved only pure object. Meaning I can use `Object.assing({},DeltaObj)` but then I'll lose all delta methods and can't restore the content.

So my question is is there is way to save and retrieve data from quill to firestore and back to quill. Or is it that quill and firestore incompatible? 
thanks.

**Comment by benbro** [comment]
The [setContents example](https://quilljs.com/docs/api/#setcontents) in the docs is just using JSON:
```json
quill.setContents([
  { insert: 'Hello ' },
  { insert: 'World!', attributes: { bold: true } },
  { insert: '\n' }
]);
```

**Comment by Fawwaz-2009** [comment]
Hey benbro, thanks for your quick response. Sure I saw the example and the arguments passed to `quill.setContents`  is what at least I think is the delta object. because I did try actually getting the delta object through `get.Contentes` and then passing the value to `setContents`. 

**But** is there is a method to get just the array in the example above form a quill editor?

**Comment by benbro** [comment]
If you need it as array:
```javascript
quill.getContents().ops;
```
If you need it as string:
```javascript
JSON.stringify(quill.getContents());
```

**Comment by Fawwaz-2009** [comment]
The solution worked with firestore, though for my app I had to create a new separate field for Html. So I'm closing the issue and thanks again to @benbro
