### ISSUE TITLE
Pasting into the editor

### ISSUE THREAD

**Issue by Ruujinjaka** [quilljs/quill#2302]
i want to update the content of the editor with some strings, but the "updateContents" method ends up updating the content of my container instead. In the documentation, the editor is supposed to be appended to a certain container but for some reason, i can type some text within the editor and the container as well. Can you please help me fix this. I just need my text to be pasted into the editor and not some region outside the editor with a class of "container"

**Comment by benbro** [comment]
Github issues are for bugs not for support questions.
I suggest you fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) with a minimal example that reproduce your problem and post your question on StackOverflow.

**Comment by Ruujinjaka** [comment]
Thanks ben, figured it out anyway.
