### ISSUE TITLE
Link tooltip in IE11 doesn't work when text it selected for second time.

### ISSUE THREAD

**Issue by kalousmichal** [quilljs/quill#2303]
In IE11 when you select a text and click link icon, the link tooltip will open, but when you click somewhere else so the tooltip is closed and you will select the same text as before and click the link icon again, link tooltip will just blink and then disappears. 

**Steps for Reproduction**

In IE 11
1. write text "xyz" to the editor
2. select "xyz" and click on the link icon (you should see link tooltip)
3. click somewhere in the editor (tooltip should disappear)
4. select "xyz" again.
5. click on the link icon => tooltip will blink and then disappear. 

Here is an animation with steps for reproduction: [https://www.dropbox.com/s/27dp6j402ie62b1/QuillIssue.gif?dl=0](https://www.dropbox.com/s/27dp6j402ie62b1/QuillIssue.gif?dl=0)

**Expected behavior**:
After step 5 link tooltip should be visible.

**Actual behavior**:
After step 5 link tooltip will disappear.

**Platforms**:
Win 10 - EI11.228.17134

**Version**:
(Quill 1.3.6)
latest Quill verion on https://quilljs.com/playground/#form-submit

**Comment by benbro** [comment]
IE 11 not supported.
