### ISSUE TITLE
While Testing: MutationObserver not found 

### ISSUE THREAD

**Issue by HAMZABoxer98** [quilljs/quill#2304]
I use Vue Cli 3 ( with jest for testing )

`
    test('assert that we can test Quilljs', () => {

    let div = document.createElement('div');
    div.setAttribute('class','description');

    let quill = new Quill(div,{

    });

    expect('hola').toEqual('hola');
    
    })
`

When I run my test i get error: MutationObserver not defined

**Comment by benbro** [comment]
Please fill all the info requested in the issue template.
Where do you run the test? In a browser or node.js?
This issue is old but it might help with running quilljs in node.js
https://github.com/quilljs/quill/issues/993#issuecomment-249387907

**Comment by HAMZABoxer98** [comment]
Thank you so much.. I solved it
I am using **Vue CLI 3 SPA** and I am testing my application using **jest** in **node.js** (I run my tests in terminal), but it seems that **Quilljs** use **document.getSelection** and **MutationObserver** wich **jsdom** does not support. 
I solved it by importing **MutationObserver** from this [link](https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.22/MutationObserver.js) and I used the fake **getSelection** from this [example](https://github.com/quilljs/quill/issues/993#issuecomment-249387907). it's weird that **jsdom** does not support these features !!
I was looking for a solution from 2 days ago.
