### ISSUE TITLE
Problems with Chinese Keyboard Pinyin (Mac Default one & Chinese IME in IE11) with Quill API updateContents

### ISSUE THREAD

**Issue by WinMinTun** [quilljs/quill#2305]
Hi I have written a Quill Authorship module https://github.com/WinMinTun/quill-authorship
Mostly ok, but with some serious problem with Chinese Keyboard which I believe to do with Quill JS code. Some Chinese Keyboard which shows Pinyin popup has the error. (Mac Chinese keyboard, Chinese IME in Window). Other Chinese keyboard which does not actually write the English characters in the editor (before showing Chinese chars pop) like in Android Google Pinyin is ok.

Whenever I called `this.quill.updateContents(authorDelta, Quill.sources.SILENT);` in my module gets the following problems. Seems like cannot update the delta (to add author attribute) while showing popup.

**UPDATE: Whenever there is a mutation regarding the attribute change to delta (to mark the authorship), the Pinyin pop up disappears. So basically I couldn't call `updateContents` to update the delta with author attribute without Pinyin pop up disappear. The next chars are ok because already set the authorship attribute to the first character, and I stopped calling `updateContents` then. Pls kindly help, I desperately need that authorship module!!**

== Problem 1 ==
![screencast_quill_ch_keyboard1](https://user-images.githubusercontent.com/22287008/45404099-26f5f800-b690-11e8-9caf-aadb051c9a35.gif)

== Problem 2 ==

![screencast_quill_ch_keyboard2](https://user-images.githubusercontent.com/22287008/45404104-2d846f80-b690-11e8-96ae-3b4222af07e3.gif)

**Platforms**:

Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
OS: Mac High Sierra 

**Version**:
Quill Version: 1.3.6

**Comment by WinMinTun** [comment]
I think it is related to #1650

**Comment by WinMinTun** [comment]
I fix it only only adding author attribute on `compositionend` for IME keyboards. But one more BIG issue appears, IME keyboards not working on collaborative editing. For example in Chinese Keyboard, when user type some English word 'w' and then Chinese words appear. At that time when others are changing the content, I will get redundant words. Refer to #2314

**Comment by 0x54164** [comment]
hello, may I ask which text editor is that you're using to same the issue?
