### ISSUE TITLE
Please, make this work with textarea. A nightmare to do form-has-changed-checks with this ...

### ISSUE THREAD

**Issue by sabsaxo** [quilljs/quill#2306]
Please, make this work with textarea. A nightmare to do form-has-changed-checks with this ...

**Comment by benbro** [comment]
As Joeao explained, Quill can't use a textarea.
The [Form Submit](https://quilljs.com/playground/#form-submit) example might help you.

**Comment by sabsaxo** [comment]
That's exactly what I was trying to avoid. I've got other 'normal' form elements, and can make a simple check. But due to Quill using a div I can no longer (without writing custom stuff).

**Comment by sabsaxo** [comment]
Maybe add a hidden textarea that gets updated with the content of the div on changes ... then changes will be registered to the textarea?

**Comment by jicihome** [comment]
@sabsaxo  This is how emojionearea script work. This use a text input or textarea, overwrite it with a div that is synced to the initial element. Maybe Quill can add this feature automatically.
Yes it's sure that if you add a link, this will not be displayed as a "link" (but as a text), but this may allow to do more integration I think.
