### ISSUE TITLE
Edge and IE Browser: Insert link with ejs scriptlet tag

### ISSUE THREAD

**Issue by pravin-mamdge** [quilljs/quill#2308]
Hi.

I came across one issue in IE and Edge. It works as expected on Chrome and Firefox.

If the URL contains ejs scriptlet (we used it as a placeholder), then on a console it throws an error as "Invalid argument".

Eg: http://localhost/api/download/<%ID>

**Steps for Reproduction**
1. Visit https://quilljs.com/playground/
2. Update json to add link button in the toolbar.
3. Add sample text and try to add a link with URL "http://localhost/api/download/<%ID>" 

**Expected behavior**:
It should create a hyperlink.

**Actual behavior**:
The link is not getting created and on the browser console it throws "invalid argument error"

**Platforms**:
Windows 10 (IE and Edge browser). It works on chrome and firefox.

**Comment by benbro** [comment]
I can't reproduce the error but in any case, "http://localhost/api/download/<%ID>" is not a valid URL.
Why can't you post-process the delta and and your custom syntax?
