### ISSUE TITLE
IME keyboards not working in collaborative editing ~ big issue

### ISSUE THREAD

**Issue by WinMinTun** [quilljs/quill#2314]
Hi, I think it is not directly linked to QuillJS, but I need to consult with anybody who has some knowledge about it. It is a big issue. I'm creating an app like Google Word where people write at realtime. But it is quite obvious IME keyboards are not working with duplicate words, because other users' changes disrupt the `composition` process of IME keyboards.

With the issue, my app is literally useless. :(

![screencast_quill_ime_collab](https://user-images.githubusercontent.com/22287008/45592406-e0114680-b99e-11e8-80c8-d3fed57ed96e.gif)

**Platforms**:

All browsers, all platforms

**Version**:

1.3.6

**Comment by WinMinTun** [comment]
@jhchen Sorry if I annoy you with this. But I think you might be really interested in that issue. It is a big one and will be really good if Quill has some workaround with that problem. Thanks a lot.

**Comment by zhangjinsong** [comment]
@WinMinTun  May I ask if this problem has been solved

**Comment by WinMinTun** [comment]
@zhangjinsong Not yet. :(

**Comment by hzjswlgbsj** [comment]
@WinMinTun 
Hello, I am doing the same thing as you, of course, I have encountered this problem. Can you solve this problem?

**Comment by zhangjinsong** [comment]
------------------ 原始邮件 ------------------
发件人: "Liu lin"<notifications@github.com>;
发送时间: 2019年9月11日(星期三) 晚上8:32
收件人: "quilljs/quill"<quill@noreply.github.com>;
抄送: "广思-张劲松"<546183483@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [quilljs/quill] IME keyboards not working in collaborativeediting ~ big issue (#2314)




@WinMinTun
 Hello, I am doing the same thing as you, of course, I have encountered this problem. Can you solve this problem?
