### ISSUE TITLE
setting quill format always result in "TypeError: blot.domNode[Registry.DATA_KEY] is undefined" ERROR

### ISSUE THREAD

**Issue by sheelen** [quilljs/quill#2317]
I am trying to use the snippet from https://codepen.io/anon/pen/oYdyKa to have a default font-family for my quill editor, but setting quill format always result in the error message:

![image](https://user-images.githubusercontent.com/23149412/45629734-53967f00-ba97-11e8-93d8-0c22734a52c3.png)

**JS Code:**
```
var fonts = ['Arial', 'Calibri'];
var Font = Quill.import('formats/font');
Font.whitelist = fonts;
Quill.register(Font, true);

var quill = new Quill("#rtf-editor", {
modules: {
    toolbar: [
    [{font: Font.whitelist}]
    ]
},
theme: 'snow'
});
quill.format('font', 'Arial');
```

I get same error if I try:
`quill.format('font', 'Calibri');`
 `quill.format('align', 'right');`
`quill.format('color', 'red');`

However, removing above formatting lines renders the editor perfectly with Arial and Calibri fonts in the drop-down menu.

Could someone help me understand the probable cause of this error?

**Steps to Reproduce**
 I have encountered this problem in EmberJs application and haven't been able to reproduce this error elsewhere.

**Browser**
-Firefox 62.0
-Chrome Version 68.0.3440.106

** Quill Version**: v1.3.5

**Comment by benbro** [comment]
I can't reproduce the error.
Please include all the info requested in the issue template. Quill version, Browser, exact steps to reproduce...
The codepen snippet is using version 1.1.6 try to update to 1.3.6.

**Comment by nichwch** [comment]
any update on this issue? i'm facing the same problem
