### ISSUE TITLE
Code does not comply with Content-Security-Policy when 'unsafe-inline' is not present.

### ISSUE THREAD

**Issue by kevinmartin** [quilljs/quill#232]
I am currently using Quill on one of my apps that I will be releasing this week.

The app using a very strict CSP header (currently in Report-Only mode), which disallows `unsafe-inline`. The CSP header emits an error when Quill calls `addStyles(...)`.

**Comment by binarious** [comment]
@jhchen What's the solution for the current Quill version to prevent inline style?

**Comment by Gladskih** [comment]
@jhchen May be we should go back to iframe for sandboxing unsafe Quill?
