### ISSUE TITLE
Unable to apply default font-selection with newest Quill version

### ISSUE THREAD

**Issue by sheelen** [quilljs/quill#2322]
Not sure how to apply a specific font selection in font-family drop-down with newer Quill version

By default, the selected value is always the top element of font.Whitelist array.

**Steps for Reproduction**

1. https://codepen.io/sheelen/pen/GXPmgZ
2. "Roboto" font selection is not selected

**Expected behavior**:
Chosen font-type must be shown in drop-down

**Actual behavior**:
first element of font.Whitelist is shown

**Version**: v1.3.6

**Comment by benbro** [comment]
The selected value is the default (empty).
You can override it by defining the toolbar with HTML:
https://codepen.io/anon/pen/xBWoXe
