### ISSUE TITLE
Remove whole line when calling updateContents API with Japanese IME

### ISSUE THREAD

**Issue by sisidovski** [quilljs/quill#2323]
This is similar to https://github.com/quilljs/quill/issues/2305 , I also wrote authorship module and use it. I'm not sure why it happens but when author attribute is set, unexpectedly Japanese composing breaks whole line.

![quill-input](https://user-images.githubusercontent.com/1642255/45769924-ea4e7180-bc38-11e8-83e2-cc50147f0d1f.gif)

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]

https://codepen.io/sisidovski/pen/wEyWeE

2. Step Two

Type any ASCII characters.

3. Step Three

Change input setting to Japanese IME and type any key and Enter key.

**Expected behavior**:

Japanese character doesn't affect other characters.

**Actual behavior**:

Remove whole line and remain latest character.

**Platforms**:

Include browser, operating system and respective versions

**Version**:

1.3.6

**Comment by sisidovski** [comment]
I tested it on Chrome + MacOS.

**Comment by WinMinTun** [comment]
Hi my solution is to apply author delta upon `compositionend` for IME keyboards. Check my https://github.com/WinMinTun/quill-authorship

**Comment by sisidovski** [comment]
Thank you, that looks nice solution, really helpful for me.
Also, I still hope quill itself fixes this problem internally🙂

**Comment by yumemi-kuwahara** [comment]
@WinMinTun 

https://github.com/WinMinTun/quill-authorship


I want to see this page, but when I access it, 404 is displayed. . .
Can you set it to be seen?

Thanks!
