### ISSUE TITLE
Text copied from Quill generates unwanted line breaks when pasted as plain text

### ISSUE THREAD

**Issue by poshest** [quilljs/quill#2325]
**Steps for Reproduction**

1. Using any of the Quill Examples (I used [Standalone Snow](https://quilljs.com/standalone/snow/)) add text like this
2. Highlight and copy that text to clipboard
![image](https://user-images.githubusercontent.com/6979221/45816759-e1af7700-bcdc-11e8-895f-15af2e2c0387.png)
3. Paste that text into any plain text editor (eg Windows Notepad, or Ctrl+Shift+V to paste as clean text into, eg a Google Doc)

**Expected behavior**:
![image](https://user-images.githubusercontent.com/6979221/45816808-07d51700-bcdd-11e8-87f7-b51f008be01b.png)

**Actual behavior**:
All the results here are on browsers running on Windows 7. Yes, the number of carriage returns pasted is different on the different browsers. But all of them paste more carriage returns than expected.

- Chrome 68.0.3440.106 (Official Build) (32-bit) OR Opera 55.0
![image](https://user-images.githubusercontent.com/6979221/45816954-7f0aab00-bcdd-11e8-8858-7b9da9644f3c.png)
- Firefox 62.0
![image](https://user-images.githubusercontent.com/6979221/45817079-e4f73280-bcdd-11e8-8143-aa243ea9e19b.png)
- IE11
![image](https://user-images.githubusercontent.com/6979221/45817104-f0e2f480-bcdd-11e8-8cc6-4304785c935b.png)

**Version**:
1.3.6

**Comment by poshest** [comment]
Note that pasting rich text (Ctrl+V) into all rich editors that I tried (eg Word, Google Docs, browser plain contenteditable) yielded the correct and expected single carriage return between the lines.

**Comment by kajomarton** [comment]
Is there any workaround for this? I think it is connected to the paragraph tag quill is using as basic building block. Facebook is using div and it works fine there 🤔

**Comment by danielalvez91** [comment]
I just found a possible solution for your problem!

I had to change the default tag `<p>` for `<div>` as suggested by @jhchen in this topic https://github.com/quilljs/quill/issues/861#issuecomment-239961806

**Comment by fjcoulon** [comment]
I did try the change from p to div but still was adding the extra 'line'. Not sure why but the 'workaround' that worked was adding the below change to the quill configuration
```
                clipboard: {
                    matchVisual: false
                }
```
under the modules node.
