### ISSUE TITLE
Quill cut/copy/past

### ISSUE THREAD

**Issue by gfmclean** [quilljs/quill#2331]
I having some problems with the above subject. I namely started using Quill only 2 days ago and for the life of me I do not know what I am doing wrong.  A lot of the terminology is still unclear, so when speaking of parchment, delta, and and and leaves me blank right now. 

I have not added anything to customize cut, copy or past, yet it seems Quill has taken over the functionalities, at least the past (control+V).

The highlighted onPaste delta only contains as follows:

![image](https://user-images.githubusercontent.com/6312574/46024568-16447980-c0b5-11e8-9244-1ebec01ffaac.png)

If I highlight text and try to paste something the delta has only this form:

![image](https://user-images.githubusercontent.com/6312574/46024439-cb2a6680-c0b4-11e8-99a9-b7bdd7bc14a2.png)

else if I simply try to paste it only contains the retain, but not the insert.

In my HTML I have
  <script src="/Content/quill/quill.js"></script>
  <script src="/Content/quill/PlainClipboard.js"></script>

And in my JS file the only relation to the clipboars is:
    var clipboard = Quill.import('modules/clipboard');
    var Delta = Quill.import('delta');

Any help is appreciated.

**Comment by benbro** [comment]
It's unclear what your issue is. Keep reports short. The background story doesn't help. Don't include images of code. Github has syntax highlighting for this.
Please fill all the info requested in the issue template.
Fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) with a minimal example showing what you are trying to do and steps to reproduce the issue.

**Comment by gfmclean** [comment]
Thank you for your response. I am simply trying to enable cut and past into an editor.  Without having included any code other than quill itself, it seems that when I hit control + V, the code falls into quill's onpaste, however, no paste data is passed in.

**Comment by benbro** [comment]
Github issues are for bugs.
Please post your question on [StackOverflow](https://stackoverflow.com/).
