### ISSUE TITLE
Tab in codeblock indents multiple lines

### ISSUE THREAD

**Issue by kevinhend** [quilljs/quill#2336]
**Steps for Reproduction**

1. Visit playground on quilljs.com
2. Write one line of normal text
3. Go to next line and change style to codeblock
4. Write two lines of code
5. Set cursor to the beginning of the first line in the code block
6. Use "Tab" to indent

![tab2](https://user-images.githubusercontent.com/36416784/46340526-eefe2700-c635-11e8-8248-e6144aa9bfcb.gif)

**Expected behavior**:
Only the line where the cursor is gets indented
**Actual behavior**:
Both lines of code get indented
**Platforms**:
MacOS: Chrome, Firefox
Windows 7: IE11

**Version**:
Quill 1.3.6

**Comment by che3vinci** [comment]
me,too

**Comment by Linshiqi** [comment]
me too

**Comment by dara0418** [comment]
Have you got any workaround?

**Comment by BitPhinix** [comment]
Same here

**Comment by BitPhinix** [comment]
Solved it overwriting the [Keybindings](https://quilljs.com/docs/modules/keyboard/) with:
```
{
  'indent code-block': null,
  'outdent code-block': null,
}
```

**Comment by ArsalanSavand** [comment]
Any news on this?

**Comment by cedricblanc** [comment]
Same here under Quill 1.3. Any news about this issue ?
