### ISSUE TITLE
Adding Quill to Your Build Pipeline creates invalid js

### ISSUE THREAD

**Issue by KyooMario** [quilljs/quill#2338]
I am trying to follow your tutorial "Adding Quill to Your Build Pipeline" which in fact is straight forward but there are a few variables that seem to stop me from having success.

1. I am using Webstorm as editor
2. I added all the required addons as such:
npm init
npm install quill
npm install --save-dev webpack webpack-cli
npm install --save-dev babel-cli   <- ???
npm install -D babel-loader@7 babel-core babel-preset-env webpack
npm install --save-dev babel-preset-es2015
npm install ts-loader
npm install typescript
npm i -D html-loader
npm install --save-dev css-loader
npm run build

3. managed to build a js but get an error message stating: Uncaught ReferenceError: Quill is not defined
[kyooquill.txt](https://github.com/quilljs/quill/files/2438871/kyooquill.txt)

Please advise where I have gone wrong.

Kind regards,
Mario

**Comment by jhchen** [comment]
Which version of Quill are you trying to build?

**Comment by KyooMario** [comment]
Hello Jason,

I have tried to rebuild the quill.min.js from the github package but I don't succeed. (I want to do include some features).
Is there any chance you can help me? A small budget is available.

Kind regards,
Mario

**Comment by huangjinqiang** [comment]
try this

webpack --env.minimize --config _develop/webpack.config.js

**Comment by benbro** [comment]
https://github.com/quilljs/webpack-example
https://v2.quilljs.com/docs/installation
