### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by bologer** [quilljs/quill#2339]
First, I would like to thank you for editor! It is great!

**Steps for Reproduction**
1. Use editor
2. Try to insert link
3. If you are non-English speaker you see English text and this is what is defined by `content` via CSS

**Expected behavior**:

Ability to localize "Edit", "Remove", "Enter link:", etc. 

I am not English speaker, project view varies on language which should change editors language as well. What you have now, is that I have to dynamically [generate CSS](https://github.com/quilljs/quill/issues/1192#issuecomment-267132080) to change `content` dynamically or [generate custom templates](https://github.com/quilljs/quill/issues/209#issuecomment-55049885) for image, formulas, etc.  And as I understand this is not the best practice based on [this](https://github.com/quilljs/quill/issues/1192#issuecomment-268435179) comment. 

And anyways, why would I generate my custom templates if I like what you provide by default? 

Is it possible to add documentation for how to generate the same logic for default link insertion via pop-ups as [here](https://github.com/quilljs/quill/issues/1192#issuecomment-426775483)?

As what I can find now is [this](https://quilljs.com/docs/modules/toolbar/#handlers), which is just `prompt` and very basic implementation from how it is in the editor itself.

I would like to see how it is handled in `snow` theme.

**Actual behavior**:
Limited ability to translate

**Platforms**: Ubuntu

**Version**: I use [react-quill](https://github.com/zenoamaro/react-quill)

**Comment by benbro** [comment]
Create localized strings for each lang:
```css
.fr.ql-snow .ql-tooltip[data-mode="link"]::before {
    content: "Entrer le lien:";
}
```
Add CSS class in javascript when you want to change the lang:
quill.container.classList.add('fr');

https://codepen.io/anon/pen/KGzdxB

**Comment by bologer** [comment]
@benbro interesting approach. Is this really the way it is?

**Comment by paullaffitte** [comment]
I have to admit that it is a quite disappointing solution...
