### ISSUE TITLE
Is it possible to add an event for on finish rendering?

### ISSUE THREAD

**Issue by josephmisiti** [quilljs/quill#234]
When I cut and paste a large piece of text into Quill, sometimes it "looks" like it is not copying-and-pasting in, but what is really happening is Quill's setHTML is converting my text into Quill's internal html format. 

Is it possible to add an event so I can add a progress bar (or something similar) so my users can see that the cut-and-paste is working?

**Comment by jhchen** [comment]
Closing from inactivity. Feel free to reopen/comment if this is still an issue.

**Comment by josephmisiti** [comment]
@jhchen ya the new version doesnt have this issue - sorry i did not close this earlier.

**Comment by jhchen** [comment]
No worries thanks for following up!
