### ISSUE TITLE
Blockquote selection on multiple lines 

### ISSUE THREAD

**Issue by bologer** [quilljs/quill#2340]
Let's say I have this in editor: 

```html
<p>test</p>
<p>test2</p>
<p>tes3</p>
```

Once I select all and make it as quote, it will create three separate quotes. 

Isn't is supposed to be only once quote in this case?

**Comment by Oryss** [comment]
I have the same issue, I'm trying to make a "reply" button

Even using :

> editor.clipboard.dangerouslyPasteHTML(0, '<blockquote>' + quotedContent + '</blockquote>');

Creates 1 blockquote node for each line, which makes no sense

**Comment by leventdeniz** [comment]
See my comment here https://github.com/quilljs/quill/issues/1056#issuecomment-1344348611
