### ISSUE TITLE
Question: actions not available via API

### ISSUE THREAD

**Issue by dhowe** [quilljs/quill#2342]
Hi all,
I'm interested in creating a playback module, which will allow the usual to replay/view the full set of edits for a document. I'm wondering if there is a list somewhere (or if someone knows offhand) of actions that are manually available in the editor, but not available through the API. I'd like to get down to the level of individual keystrokes if possible.
thanks

**Comment by benbro** [comment]
It's easy to replay changes in Quill. You can listen to the [text-change event](https://quilljs.com/docs/api/#text-change), save a list of deltas (changes) and later replay them by applying the delta with [updateContents](https://quilljs.com/docs/api/#updatecontents).

**Comment by dhowe** [comment]
Excellent. And do this include keyboard events which don't lead to direct content changes (for example, navigation through a document)?

**Comment by benbro** [comment]
No, it only include changes to the editor contents.

**Comment by dhowe** [comment]
Thanks - I will give a try and see how it goes
