### ISSUE TITLE
How to support inline styles？？？

### ISSUE THREAD

**Issue by lisun0459** [quilljs/quill#2344]
Our project is for some basic people, we need to edit the style from other editor website which have much styles and rich material library  and paste it to our edit , so we must need to use inline style. Please tell me a solution to support inline styles?  I using React.
thank you very much！

**Comment by benbro** [comment]
It's documented in the [guide](https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline) and been asked several times. Please search issues and StackOverflow.
