### ISSUE TITLE
Feature request: responsive collapsing toolbar

### ISSUE THREAD

**Issue by poshest** [quilljs/quill#2345]
Feature request: I would like an option to allow the snow toolbar to collapse responsively and maintain the height of one tool, collapsing the right-most tools into a "More..." dropdown. Google docs does this 
![image](https://user-images.githubusercontent.com/6979221/46662765-993cf800-cbbc-11e8-8448-f316be07144d.png)

**Comment by Eraldo** [comment]
I would also enjoy this feature. :)
