### ISSUE TITLE
i want to know why drop white-space

### ISSUE THREAD

**Issue by seeer** [quilljs/quill#2346]
quill/modules/clipboard.js    
65c00ef  on 27 Jun   line:471
match = match.replace(/[^\u00a0]/g, '');    // \u00a0 is nbsp;
in function matchText

There are always lots of spaces in paragraphs when knocking at the article. The plugin 'vue-quill-editor' I use use function 'quill.pasteHTML(Val)' to put html into editor, then many spaces lost.
I want to know why replace to empty instead of white-space.

**Comment by CosmoMyzrailGorynych** [comment]
I wonder why replacing at all. It is a useful typographic character.
