### ISSUE TITLE
How to use the script several times on the page?

### ISSUE THREAD

**Issue by ArtemPavliienko** [quilljs/quill#2347]
I have a page with posts, in each post there is a block where you can write a description. I need to insert a script to each of these blocks so that I can edit them independently of the other blocks. How to do it?

**Comment by krogersforbes** [comment]
Hey Artem,

Quill can have multiple editors on the page without a problem. You only need to load the initial scripts once, and then when you initialize each box just make sure that it has it's own unique initialization.

https://codepen.io/krogersforbes/pen/OdjMxY 

Hope this helps!
