### ISSUE TITLE
how to set the style text-indent

### ISSUE THREAD

**Issue by WxSwen** [quilljs/quill#2351]
i want to set the line-style as text-indent just for the head of the line，and if i click the default indent-button will change into add class and the style is padding-left: 3em; but it is not my want
of course i try this solution
https://github.com/quilljs/quill/issues/1930#issue-290759881

but it will occur this error 

> `Uncaught TypeError: BlotClass.create is not a function`

**Comment by danielmhair** [comment]
I made this same `IndentAttributor` and am receiving the same `BlotClass.create` is not a function. Any solution on this?

**Comment by rcqcxy** [comment]
I have the same problem. I want to  set the style text-indent,Have you solved it，please?

**Comment by danielmhair** [comment]
Yes, we did solve it. I must not have hit send in my last message.

Here is what our solution looks like. Before looking, please keep in mind that we needed to add a little bit of hackery because of typescript. I will show our original code, then change it to show the important thing that needs to be changed.

```
declare const Quill: any

export const Parchment = Quill.import("parchment")
const pixelLevels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
const TAB_MULTIPLIER = 30

export class IndentAttributor extends (Parchment.Attributor.Style as { 
  new(formatName: any, styleProperty: any, attributorOptions: any): any;}) {
  constructor(formatName: any, styleProperty: any, attributorOptions: any) {
    super(formatName, styleProperty, attributorOptions)
  }

  public add(node: HTMLElement, value: string): boolean {
    return super.add(node, `${+value * TAB_MULTIPLIER}px`)
  }

  public value(node: HTMLElement): number | undefined {
    return parseFloat(super.value(node)) / TAB_MULTIPLIER || undefined // Don't return NaN
  }
}

export const IndentStyle = new IndentAttributor("indent", "margin-left", {
  scope: Parchment.Scope.BLOCK,
  whitelist: pixelLevels.map(value => `${value * TAB_MULTIPLIER}px`),
})
```

In the code, the most import part was:
```
export const Parchment = Quill.import("parchment")
```

Before we did the following two ways:
```
// This import simply does not work and this was the line that caused the error
import * as Parchment from "parchment"

// Our typescript tslint wouldn't allow this, because it thought of the const variable as private, so we needed to export it. For those without Typescript, you only need this one.
const Parchment = Quill.import("parchment")
```

Also, in that code, you might have seen that the `extend` has a constructor type (`new(formatName, ...)`). For simplicity, I'm going to show the code as if I didn't use Typescript:
```
const Parchment = Quill.import("parchment")
const pixelLevels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
const TAB_MULTIPLIER = 30

export class IndentAttributor extends Parchment.Attributor.Style {
  add(node, value) {
    return super.add(node, `${+value * TAB_MULTIPLIER}px`)
  }

  value(node) {
    return parseFloat(super.value(node)) / TAB_MULTIPLIER || undefined // Don't return NaN
  }
}

export const IndentStyle = new IndentAttributor("indent", "margin-left", {
  scope: Parchment.Scope.BLOCK,
  whitelist: pixelLevels.map(value => `${value * TAB_MULTIPLIER}px`),
})
```

**Comment by ddtobiasz** [comment]
Has anyone managed to do this without using `class`, as that isn't supported in IE11

**Comment by ddtobiasz** [comment]
@danielmhair Did this affect the ability for Quill to show nested lists for you?  If so, did you have a workaround?

**Comment by andyraddatz** [comment]
Comparing Indent source code to Align, it looks like this class needs to be extended to produce a StyleAttributor: https://github.com/quilljs/quill/blob/develop/formats/indent.js

This is from `align.js`:
`const AlignStyle = new StyleAttributor('align', 'text-align', config);`

**Comment by omerson** [comment]
You can transform the content.


```
        prepareIndent(editor: HTMLElement) {
            const indents: NodeList = editor.querySelectorAll('[class^=ql-indent-]');
            for (let i = 0; i < indents.length; i++) {
                const node: HTMLElement = indents[i] as HTMLElement;
                const indentClass = node.classList.toString().split(' ').filter(c => c.startsWith('ql-indent-'))[0];
                let tab = 0;
                const destructClass = indentClass.split('-');
                if (destructClass) {
                    const indentIndex = destructClass.pop();
                    if (indentIndex) {
                        tab = Number(indentIndex);
                    }
                }
                const indentValue = 3 * tab;
                node.style.paddingLeft = indentValue + 'em';
            }
        }
```

**Comment by GlenHeart** [comment]
Class mode indentation can be canceled by the delete key. But style doesn’t work
