### ISSUE TITLE
Find a String in the quill text area and replace it another text

### ISSUE THREAD

**Issue by Naveenkariyappa** [quilljs/quill#2352]
Hi am trying to build a find and replace feature in one of my application where i need to search a string in the textarea and then later replace it with another string for all its occurrences

I ran through the documentation but could not find it 

need help i am new to this,

HE HAS A BIIKE

Now i need to select BIKE and replace it with CAR
for all the occurrences of BIKE

**Comment by Naveenkariyappa** [comment]
Did something like this

`        function replaceText(test) {
            let replaceText = test.dataset.val; 
            let res = replaceAll(replaceText)
            if (res) {
                console.log(res)
                delta.ops[0].insert = res
                quill.setContents([
                    { insert: res }
                ]);

            }

        }

        function replaceAll(rt) {
            console.log(rt)
            while (fullTextString.indexOf(text) > -1) {
                fullTextString = fullTextString.replace(text, rt);
            }
            return fullTextString;
        }     `

**Comment by Naveenkariyappa** [comment]
This is not an issue with the Quill, 
maybe my lack of knowing how to use it 
 
figured it out
hence closing it

**Comment by rakeshar3796** [comment]
> This is not an issue with the Quill,
> maybe my lack of knowing how to use it
> 
> figured it out
> hence closing it

@Naveenkariyappa can you tell me how did you do this

**Comment by AlexEkdahl** [comment]
@Naveenkariyappa  How did you do it?
