### ISSUE TITLE
[Parchment] Unable to create image blot

### ISSUE THREAD

**Issue by RankoR** [quilljs/quill#2355]
I'm trying to insert image:

```
import Quill from 'quill/core';

import Toolbar from 'quill/modules/toolbar';
import Snow from 'quill/themes/snow';

import Bold from 'quill/formats/bold';
import Italic from 'quill/formats/italic';
import Header from 'quill/formats/header';
import Link from 'quill/formats/link';
import List, {ListItem} from 'quill/formats/list';
import Blockquote from 'quill/formats/blockquote';
import CodeBlock from 'quill/formats/code';

const quillEditorId = 'quill-editor';

function initQuill() {
    const quillField = document.getElementById('quill-field');

    Quill.register({
        'modules/toolbar': Toolbar,
        'formats/codeblock': CodeBlock,
        'themes/snow': Snow,
        'formats/bold': Bold,
        'formats/italic': Italic,
        'formats/link': Link,
        'formats/list': List,
        'formats/list/item': ListItem,
        'formats/header': Header,
        'formats/blockquote': Blockquote
    });

    const quill = new Quill('#' + quillEditorId, {
        modules: {
            // syntax: {
            //     highlight: text => window.hljs.highlightAuto(text).value
            // },
            toolbar: [
                ['bold', 'italic'],
                ['link', 'blockquote', 'code-block'],
                ['image'],
                [{list: 'ordered'}, {list: 'bullet'}]
            ]
        },
        theme: 'snow'
    });

    quill.insertEmbed(0, 'image', 'https://via.placeholder.com/350x150');
```

It throws exception:
```
Uncaught Error: [Parchment] Unable to create image blot
    at new ParchmentError (parchment.js:98)
    at Object.create (parchment.js:128)
    at BlockBlot.insertAt (parchment.js:1575)
    at Block.insertAt (block.js:84)
    at Scroll.ContainerBlot.insertAt (parchment.js:402)
    at ScrollBlot.insertAt (parchment.js:1310)
    at Scroll.insertAt (scroll.js:95)
    at Editor.insertEmbed (editor.js:153)
    at quill.js:259
    at Quill.modify (quill.js:437)
```

What I'm doing wrong?

**Platforms**: macOS 10.13.6, Chrome 69.0.3497.100

**Version**: 1.3.6

**Comment by binarious** [comment]
I think you're missing the import:
```js
import Image from 'quill/formats/image';

Quill.register({
  // ...
  'formats/image': Image
});
```

**Comment by vupham2909** [comment]
Thank @binarious , your solution works for me 👍

**Comment by onzag** [comment]
I have the same issue but I actually have the register call... any idea?...

**Comment by MoRa2297** [comment]
Somebody can kelp me? I have the same problem..


`// -----------------------------------------
// Classe TextEditor custom image
//
let BlockEmbed = Quill.import("blots/block/embed");

class ImageBlot extends BlockEmbed {
  static create(value) {
    let node = super.create();
    node.setAttribute("data-id", value.id);
    node.setAttribute("src", value.url);
    node.setAttribute("data-custom", value.url);
    return node;
  }

  static value(node) {
    return {
      id: node.getAttribute("id"),
      url: node.getAttribute("src"),
    };
  }
}

ImageBlot.blotName = "image";
ImageBlot.tagName = "img";

// Quill.register({ "formats/imageBlot": CustomImageBlot });

// -----------------------------------------
// Classe TextEditor
//

function TextEditor() {
  /**
   * Init oggetto. Contiene una serie di metodi che devono essere lanciati subito
   */

  var editor;

  this.init = function (lang_id) {
    this.lang_id = lang_id;
    this.container = document.getElementById("editor" + lang_id);
    this.editorID = "editor" + lang_id;

    this.options = {
      // debug: "log",
      modules: {
        toolbar: [
          ["bold", "italic", "underline", "strike"], // toggled buttons
          ["blockquote", "code-block"],

          [{ list: "ordered" }, { list: "bullet" }],
          [{ script: "sub" }, { script: "super" }], // superscript/subscript
          [{ indent: "-1" }, { indent: "+1" }], // outdent/indent
          [{ direction: "rtl" }], // text direction

          // [{ size: ["small", false, "large", "huge"] }], // custom dropdown
          [{ header: [1, 2, 3, 4, 5, 6, false] }],

          [{ color: [] }, { background: [] }], // dropdown with defaults from theme
          [{ font: [] }],
          [{ align: [] }],
          ["link", "image"],
          ["clean"], // remove formatting button
        ],
        //   theme: "snow",
      },
      placeholder: "Compose an epic...",
      // readOnly: false,
      theme: "snow",
    };

    // tasto che apre il modale
    this.initTxtEditor();
  };

  /**
   * Init tasto che apre il modale
   */
  this.initTxtEditor = function () {
    var thisObj = this;

    container = document.getElementById("editor" + thisObj.lang_id);

    // // Levare il true
    Quill.register({ "formats/image": ImageBlot });

    thisObj.editor = new Quill(thisObj.container, thisObj.options);

    var toolbar = thisObj.editor.getModule("toolbar");
    toolbar.addHandler("image", () => {
      modal.setModalContent("text", thisObj.editorID);
    });

    this.setImage = function (selectedIDS) {
      let imageSelectedArray = [];
      modal.getImageForModal().then((resp) => {
        resp.arr_items.filter((item) => {
          selectedIDS.map((idSelected) => {
            if (parseInt(idSelected) == parseInt(item.id)) {
              imageSelectedArray = [...imageSelectedArray, item];
            }
          });
        });
        imageSelectedArray.forEach((element) => {
          let range = thisObj.editor.getSelection(true);

          thisObj.editor.insertText(range.index, "\n", Quill.sources.USER);

          console.log("range.index + 1: ", range.index + 1);
          console.log("image");
          console.log("xxxxxxx", {
            id: element.id,
            url: element._final_url,
          });

          thisObj.editor.insertEmbed(
            range.index + 1,
            "image",
            {
              id: element.id,
              url: element._final_url,
            },
            Quill.sources.USER
          );
        });
      });
    };
  };

  /**
   * Ritorno il testo e le immagini usate, creo campo con le immagini
   */
  this.getText = function () {
    var thisObj = this;

    var imgIdArray = [];
    var html = thisObj.editor.root.innerHTML;
    var htmlObject = $(html);
    $("#textUtil").html(htmlObject);
    $("#textUtil img").each(function (index) {
      let imgID = this.getAttribute("data-id");
      var input = document.createElement("input");
      input.setAttribute("type", "hidden");
      input.setAttribute("name", "imgEditor[1][]");
      input.setAttribute("value", imgID);
      // '<input type="hidden" name="text[]" value="' + imgID + '"/>';
      document.getElementById("imgUtil").appendChild(input);
      imgIdArray = [...imgIdArray, imgID];
    });
    $("#textUtil").html("");

    return { html, imgIdArray };
  };

  this.setText = function (html) {
    var thisObj = this;

    var delta = thisObj.editor.clipboard.convert(html);
    thisObj.editor.setContents(delta, "silent");
  };
}`
