### ISSUE TITLE
Code Highlighting Not Going Away When Code Formatting Is Removed

### ISSUE THREAD

**Issue by efake2002** [quilljs/quill#2357]
Hey, found another bug in Quill/HighlightJs. Don't know if this is something you can fix on your side or if it would be easy to fix on our side. Anyway, here is the bug:

### Steps for Reproduction

1. Go to https://quilljs.com/
2. Click inside the demo editor
3. Make a new line by pressing enter
4. Click on the code formatting button in the toolbar
5. Type a random programming keyword like "for" or "if" or "function"
6. Wait and Let HighlightJS highlight the keyword
7. Then press the code formatting button in the toolbar again to take away to code formatting

And that is where the bug lies. The keywords will still remain highlighted. Please fix this ASAP and if it can't be fixed soon on your side, please provide some way that we can get around this bug. 

Thanks.

**Comment by volser** [comment]
dup: https://github.com/quilljs/quill/issues/1993
