### ISSUE TITLE
Replace the default block with figure

### ISSUE THREAD

**Issue by santosidauruk** [quilljs/quill#2359]
Currently, i'm buiding my rich text editor with quill and i need to create an embed for images. Before quill, i used to use redactor and i try to move to redactor. But, i already have 2 version of data from redactor before where the users is already uploaded images.

Version 1: 
`<p><img src="http://lorempixel.com/400/200/" data-image="5bb71bdc65465e0675ba" class="img-fluid img-responsive"></p>`

Version 2:
`<figure><img src="http://lorempixel.com/400/200/" data-image="1bdc65465e0675ba1b2b" class="img-fluid img-responsive"></figure>`

**Expected behavior:**
I expect to replace the `p` with `figure` on initial parsing in quill. So, all the images have same parent `figure`

**Actual behavior**
`figure` is always deleted by default

I tried to register `figure` with `blots/block/embed` but i can't check and add the `figure` if the image doesn't have `figure` on its parent

Thank you

**Comment by benbro** [comment]
Please ask questions on StackOverflow.
