### ISSUE TITLE
Prevent merging consecutive ContainerBlots

### ISSUE THREAD

**Issue by pseudonymousUser** [quilljs/quill#2363]
I am using figure tag as container for images. Figures tags are instance of ContainerBlot but I noticed ContainerBlots merging automatically if there is no element between them. how do I prevent this from happening. Or which part leads to it, parchment? delta? which method? I couldn't find please help me?

![screenshot from 2018-10-17 22-02-10](https://user-images.githubusercontent.com/13316058/47110676-2d146100-d25a-11e8-956a-a6b7a05200fa.png)

Above image; if I delete the paragraph, all the pictures are gathered under one figure tag, i dont want this action.

Please help me out. Thanks.

**Comment by hllktlhndd** [comment]
I found. I added this blank method to my Figure class which extends Container blot.      
```
            detach(){
            }
```
I hope i won't have any other problem with doing this. i don't know what the purpose is this method. i haven't time for inspect.

**Comment by fry2k** [comment]
I have exactly the same problem right now with a custom div blot which extends blots/block

How did you solve it? I didn't find any checkMerge method at the parchment or quill.

**Comment by khaled4vokalz** [comment]
If you add custom attribute in the blot this issue doesn't appear maybe e.g.
`  public static create(id: string): HTMLAnchorElement {
    const node = super.create();
    node.setAttribute('id', id);
    return node;
  }

  public static formats(node: HTMLElement): Nullable<string> {
    return node.getAttribute('id');
  }`

**Comment by Johnnyrook777** [comment]
You can now override the optimize method on your registered blot type

Example in typescript
```
class NeverOptimizeBlot extends inlineBlot   {
  constructor(domNode: any) {
    super(domNode);
  }

  static create(value: any) {
    const node = super.create(value?.type);

    return node;
  }

  optimize(context: any) {
    // Never optimize/merge these
  }

}
```
