### ISSUE TITLE
Bold from parent is not registered

### ISSUE THREAD

**Issue by phouri** [quilljs/quill#2364]
When using quill for content that is by default bold (i.e. container parent is bold), quill doesn't register that the content is bold, nor can I remove the boldness.

Is there anyway around this or some walkthrough? 

**Steps for Reproduction**

1. visit: https://codepen.io/Phouri/pen/pxLVjP
2. Write something, try to unbold it

**Expected behavior**:

Quill recognises that current style is bold, allow to unbold (using inline styles?)

**Actual behavior**:

Quill doesn't recognise bold, also can't remove bold.

**Platforms**:

All

**Version**:

1.3.6

**Comment by benbro** [comment]
Just remove the conflicting style from the container.

**Comment by phouri** [comment]
That's not possible, using quill to generate html that then gets injected into different places, some with bold, some aren't, so that doesn't really work.
