### ISSUE TITLE
Can't get attribute style block blot's

### ISSUE THREAD

**Issue by muhammadridho** [quilljs/quill#2365]
i am trying to customize a default block blot. how do i  get the attribute style of blot block?. i 've been trying to get attribute from image blot, and it work well. but when i try to do sameway with blot block, it doesn't work.

Visit https://codepen.io/mridho/pen/mzLpLd

**Expected behavior**:
get attributes include (inline-style and other attributes)

**Actual behavior**:
null

**Platforms**:
Chrome Browser, Ubuntu

**Version**:

Run `1.3.6` to find out

**Comment by benbro** [comment]
Please share a minimal example of what you are trying to do on StackOverflow.
