### ISSUE TITLE
How to inspect document contents on a server?

### ISSUE THREAD

**Issue by optimistiks** [quilljs/quill#2366]
Let's say, on my server, for some reason I need to get all image blocks from a specific document (to get their urls), or get contents of the first code block in the document. 
Let's say I have custom blots defined, "image" and "code". On a server, I can get a Delta representation of the document. 
How can I find those image and code blocks? Should I write some code that will convert the series of ops that Delta contains to a certain final JSON representation that I can inspect later? Something like quill-delta-to-html, only -to-json? Is there some other way? Thanks

**Comment by DmitrySkripkin** [comment]
But Delta is json already.

**Comment by optimistiks** [comment]
Right, but as I understand, Delta represents document as a series of changes. So how do I do something like this using Delta?

```
// pseudocode: get all links from the document
const links = document.nodes.filter((node) => node.type === 'link')
```

I can't just count all "insert link" operations because there could be delete operations.

**Comment by benbro** [comment]
A [document](https://quilljs.com/docs/delta/#document) Delta has only inserts.
