### ISSUE TITLE
How do I update toolbar when a formatting is active

### ISSUE THREAD

**Issue by efake2002** [quilljs/quill#2367]
I am building a custom quill editor with the parchment module. I have made a separate toolbar with buttons that format the text in the editor. When the user's selection has bold formatting, I want to change the color of the bold button. How do i do this? Currently I have been using the `editor-change` event to change the button color. It works perfectly, when you press enter it makes all the buttons white for some reason. How does quill's native toolbar handle this? Can i get a link to part of the code that deals with this?

Thanks in advance.

**Comment by benbro** [comment]
quill.getFormat() will give you the correct format in a new line.
This is the code in the toolbar module that use it:
https://github.com/quilljs/quill/blob/develop/modules/toolbar.js#L110
