### ISSUE TITLE
Code blocks are extremely slow

### ISSUE THREAD

**Issue by buu700** [quilljs/quill#2368]
**Steps for Reproduction**

1. Visit quilljs.com
2. Replace Quill editor content with a bunch of text (e.g. the attached)
3. Select all and click the code block button

**Expected behavior**:

Immediately changes to a dark background with fixed-width font, ideally but not necessarily with syntax highlighting.

**Actual behavior**:

Spikes my CPU to 100% for a long time before finally working.

**Platforms**:

Google Chrome, Version 70.0.3538.67 (Official Build) (64-bit)

macOS Mojave

**Version**:

1.3.6

[balls.txt](https://github.com/quilljs/quill/files/2498694/balls.txt)

**Comment by up2hub** [comment]
I have the same problem. 
Also focus on this issue.

**Platforms:** 
windows7 x64
chrome66.0.3359.181(X64) and firefox63(X64) all have this issue


and when code-block has large code (about 200 lines) , ctrl+a select all and press backspace , then undo , it will be slow.

**Comment by DmitrySkripkin** [comment]
This is wrong to use code highlighting (inside wisiwig) without line numbers. This feature works fine for code snippets, but not huge chunks of code.

**Comment by ligado** [comment]
I'm seeing the same issue in a notes app that I'm building. The code snippets are not huge, but maybe over 100 lines (a JSON body for an API that I'm documenting) and when I load the contents it can take 45 seconds to 1 minute, which makes it nearly unusable. When you mention line numbers, is there a more explicit way I can structure the content to speed this up?

I initially thought this was a problem with highlighjs, so I disabled that and the speed is still terribly slow, so this is happening in quill. Any advice or recommendations?

**Comment by glownesWlc** [comment]
I have the same problem. Has anybody find any solution?

**Comment by cddoma** [comment]
I have the same problem. Has anybody find any solution?

**Comment by jeppebundsgaard** [comment]
I have the same issue. It seems like there is no progress on this issue. Any suggestions for alternative online editors for scripts?
