### ISSUE TITLE
Change dropdown selected item

### ISSUE THREAD

**Issue by ap-prog** [quilljs/quill#2369]
Users choose an available font and font size in the website and then launch quill. Quill should change to the user selections but I've not found a way to do this.

I've tried using js to set the current selected dropdown item but the value that is always displayed is the default.

Is there a way to change the selected items for quill dropdowns after the quill has been displayed?

**Comment by benbro** [comment]
Example of how to define custom fonts and set the default font:
https://quilljs.com/playground/#custom-fonts
