### ISSUE TITLE
Cannot insert custom blot into block

### ISSUE THREAD

**Issue by lilworks** [quilljs/quill#2371]
I just change the name of the linkBlot exemple to create a "custom" blot. When I try to use my new button I get this error:
`Error: [Parchment] Cannot insert tone-inline into block`
Any idea?

```
class ToneInlineBlot extends Parchment.Inline {
      static create(url) {
        let node = super.create();
        node.setAttribute('href', url);
        node.setAttribute('target', '_blank');
        node.setAttribute('title', node.textContent);
        return node;
      }

      static formats(domNode) {
        return domNode.getAttribute('href') || true;
      }

      format(name, value) {
        if (name === 'tone-inline' && value) {
          this.domNode.setAttribute('href', value);
        } else {
          super.format(name, value);
        }
      }

      formats() {
        let formats = super.formats();
        formats['tone-inline'] = ToneInlineBlot.formats(this.domNode);
        return formats;
      }
    }
    ToneInlineBlot.blotName = 'tone-inline';
    ToneInlineBlot.tagName = 'A';
    Parchment.register(ToneInlineBlot);
```

**Comment by jmoyers** [comment]
Yikes. Apparently this still exists. Thanks for your detailed comment @rodoch . I was able to solve my issue (not exactly the same, ANY custom blot was being rejected by scroll) with your solution. I imported Quill, used `.import` and no Parchment error.

This would definitely be worth including in the webpack pipeline doc as the method for importing classes there just doesn't work: https://quilljs.com/guides/adding-quill-to-your-build-pipeline/

I tried to follow the various registries and instanceof checks, but could not make sense of it without setting up a more involved build environment.

**Comment by imabot2** [comment]
I still have the same issue even after importing with 
`const Parchment = Quill.imports.parchment;`
https://jsfiddle.net/Imabot/5tsnyLuh/41/

Any idea?

**Comment by inventivejon** [comment]
I know this is already some time ago. But just for completeness the corrected version of the fiddle from @imabot2 :
// Initialize Quill editor
var quill = new Quill('#editor-container', {
  theme: 'snow',
});



const Inline = Quill.import('blots/inline');


class LinkBlot extends Inline {

	static create(url) 
  	{
		console.log ('URL:', url);
		let node = super.create();
		node.setAttribute('href', url);
		node.setAttribute('target', '_blank');
		node.setAttribute('title', node.textContent);
		return node;
  	}

	static formats(domNode) {
			return domNode.getAttribute('href') || true;
	}

  	format(name, value) {
    	if (name === 'link' && value) {
      		this.domNode.setAttribute('href', value);
    	} else {
      			super.format(name, value);
    	}
  	}

	formats() {
		let formats = super.formats();
		formats['link'] = LinkBlot.formats(this.domNode);
		return formats;
	}

}
LinkBlot.blotName = 'link';
LinkBlot.tagName = 'A';

Quill.register('formats/link', LinkBlot);

Using Quill.import('blots/inline') does the trick.
Because of that I replaced the Parchment.Register line on the end with Quill.register('formats/link', LinkBlot);
