### ISSUE TITLE
Feature Request Bootstrap Rows and Cols

### ISSUE THREAD

**Issue by MarcGodard** [quilljs/quill#2373]
Hi guys, love this library, but was wondering how hard would it be to convert the coming tables feature #117 to do bootstrap style rows and cols?

I use quill as a wysiwyg that uses bootstrap, and I think it would be nice to be able to add rows and columns instead of tables (or best case, both).

**Comment by benbro** [comment]
Tables are in dev. Rows and Cols are out of scope.

**Comment by MarcGodard** [comment]
@benbro I think you misunderstood my question. It wasn't a feature request. It was an ask about how hard would it be for ME to add that using the table features. Please reopen so the question can be answered.

**Comment by benbro** [comment]
It's not clear what you mean by bootstrap rows and cols.
Quill is a rich text editor, not a wysiwyg editor.

**Comment by MarcGodard** [comment]
@benbro https://getbootstrap.com/ that bootstrap.

I am not asking to make it a WYSIWYG Editor. I am asking if the same way I modify my links with the following:

```
    let Link = Quill.import('formats/link')
    class MyLink extends Link {
      static create (value) {
        let node = Link.create(value)
        value = Link.sanitize(value)
        node.setAttribute('href', value)
        if (value.startsWith('/') || value.startsWith('mailto:') || value.startsWith('tel:')) {
          node.removeAttribute('target')
        } else {
          node.setAttribute('target', '_blank')
        }
        return node
      }

      format (name, value) {
        super.format(name, value)
        if (name !== this.statics.blotName || !value) return
        if (value.startsWith('/') || value.startsWith('mailto:') || value.startsWith('tel:')) {
          this.domNode.removeAttribute('target')
        } else {
          this.domNode.setAttribute('target', '_blank')
        }
      }
    }
    Quill.register(MyLink)
```

If there is something like that that will be for the tables. Not sure why you think I am asking for a WYSIWYG as that isn't what I am asking for.

Should I just ask again but more clearly? If something isn't clear, wouldn't it be better to ask for clarity before closing the issue?

**Comment by MarcGodard** [comment]
There, changed the title to make it more clear... sorry it wasn't a feature request, per se. Is that clear enough now?

**Comment by benbro** [comment]
bootstrap is a CSS framework. It's still not clear what do you mean.
The demo of table support which still not in stable is here:
https://codepen.io/quill/pen/QxypzX

**Comment by MarcGodard** [comment]
Yes I saw that, and the reason I am asking was because it says "insert row" and "insert column".

I am wondering if it will be easy to change (like I did the to the link above) to insert 

```
<div class="row"></div>
```
instead of:
```
<tr></tr>
```

And the same with `<div class="col"></div>`<td></td>`

**Comment by MarcGodard** [comment]
II am not asking to convert quill into a WYSIWYG. I am using it as that, but was not asking for that. Sorry thought most people would realize that I wasn't asking for the whole project direction to change. But maybe I should have made that clear for you.

**Comment by MarcGodard** [comment]
And in case you need more clarity, a rich text editor is a type of WYSIWYG. They are not mutually exclusive.

**Comment by NeonCreativeStudios** [comment]
I don't think this should've been closed either. Column support as a plugin or something would be incredibly useful. Would allow using Quill to author webpages. Limitless potential.

Tables simply aren't good for responsive webdesign. If I knew how to modify the table plugin to support class based columns (such as Bootstrap) then I would. But the codebase looks pretty large and complicated

**Comment by MarcGodard** [comment]
@NeonCreativeStudios Thanks.

I also use this for writing technical blogs that uses large data tables, and often, `<table>` isn't the right approach. I just wanted to know if wee could overwrite the col and rows in a way to make this useful.

**Comment by MarcGodard** [comment]
https://github.com/quilljs/quill/issues/2850
