### ISSUE TITLE
Quill does not work if used with node.js `require('quill')`

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [quilljs/quill#2374]
So I am creating a hybrid desktop app on top of [nw.js](http://nwjs.io/) and I try to use it with `require('quill')`. So no browserify or other fancy stuff, just a pure node call. But it seems that the only way I can use the editor is to link it with a `script` tag in a browser-fashion (see "Actual behavior" for symptoms).

**Steps for Reproduction**

1. Sadly, they are quite long and require downloading nw.js or electron and creating a simple project.
2. Maybe later ¯\_(ツ)_/¯

**Expected behavior**:

Quill works as intended.

**Actual behavior**:

The first symptoms were me unable to write any content except line breaks. But if I save and then load a delta, all the written text seems to be actually saved to deltas. Anyway, if I try to use toolbar buttons, nothing happens, **but** if I try Ctrl+B, Ctrl+I and stuff, the text is simply erased. At this point, no changes happen to a document's delta at all, but I also get no errors. Sometimes it throws an error that Quill can't get the range (it is undefined), but I couldn't catch at what circumstances it actually happened.

If I remove the `require` call and add a `script` tag pointing to the same main script that is defined in quill's package.json, everything works.

**Platforms**:

nw.js 0.34.0 with Chrome 70. Also affects at least nw.js 0.33.x with Chrome 69.

**Version**:

1.3.6.

With the `require` call, the 2.0.0-3 didn't work for me at all (even no UI was set up).

**Comment by benbro** [comment]
You need to shim missing stuff on node.js:
https://github.com/quilljs/quill/issues/993#issuecomment-249387907
