### ISSUE TITLE
Bug when pasting html to the editor

### ISSUE THREAD

**Issue by iobuhov** [quilljs/quill#2376]
When pasting html through "dangerouslyPasteHTML" method of clipboard editor displays unexpected line breaks. 

[Steps for Reproduction](https://jsfiddle.net/bkhpwf6z/4/)

**Expected behavior**:
Editor HTML should be equal to pasted HTML.

**Actual behavior**:
Editor adds extra line breaks into pasted HTML.

**Platforms**:
```
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G18013
```
```
Chrome 69.0.3497.100
Firefox 62.0.3
Safari 11.0.2 (11604.4.7.1.6)
```
**Version**: `1.3.6`

**Comment by DmitrySkripkin** [comment]
This is not a bug, but a confusing feature.
`matchVisual: false` option makes it work as expected.
[Fixed example](https://jsfiddle.net/DmitrySkripkin/pjgc5zws/)

**Comment by iobuhov** [comment]
Oh, thank you @DmitrySkripkin.
Thank you for your feedback, this option is helped a lot.
