### ISSUE TITLE
New Line Inserted at End of Document Inconsistent Cross-Browser

### ISSUE THREAD

**Issue by transcendr** [quilljs/quill#2377]
When content is set into the editor in Chrome & Firefox, Quill renders the content delta and does not add a new line / empty paragraph `<p><br /></p>` at the end.  However in Edge, Quill insists on injecting a new line at the end of the content, not only upon loading content but also when editing, there is always a new line /  empty paragraph at the end of the document.

I read in the Quill docs that when setting content a new line is required at the end and if omitted will be inserted for you.  I did not see any mention of this requirement while actually editing the document, but may have overlooked it.  The main issue is that the behavior / requirement seems to be inconsistent across browsers.

**Steps for Reproduction**

1. Initialize editor and set content with the `setContent` method

```js
const buildContentDelta = (acc: any[], cur: { [key: string]: any }) => {
        acc.push({ insert: `${cur.text}` })
        acc.push({ insert: '\n' })
        return acc
      }
let editorContent = data.reduce(buildContentDelta, [])
this.editor.setContents(editorContent)
```
2. Step Two

Open in Chrome/Firefox, editor does not have new line / paragraph at the end

Open in Edge (latest, haven't test in earlier versions) new line / paragraph injected at end of document

3. Step Three

Edit the document and add new paragraph, in Edge, an empty paragraph will always appear after the last paragraph added by the user, whereas in Chrome/Firefox, this is not the case.

**Expected behavior**:

Ideally, no empty paragraphs are ever added to a document unless it's a document without content (a single paragraph - this makes sense).  Any document with more than one paragraph ideally should not be required to have an empty paragraph at the end.  OR, the required (force injected) empty paragraph at the end should be consistent cross-browser.

**Actual behavior**:

Inconsistent document rendering of empty / last paragraph.

**Platforms**:

Windows 10, Chrome, Firefox, Edge (latest)

**Version**:

NPM v 2.0.1

**Comment by transcendr** [comment]
Any word on this, guys?

**Comment by seanjhulse** [comment]
This was my silly solution:

```javascript
if (text && text.substr(text.length - 11) == "<p><br></p>") {
	text = text.substr(0, text.length - 11) + "<p>&nbsp;</p>"
}
```
It works pretty well... but the space is obnoxious. Unfortunately, Quill seems to find any `</br>`, `<br>`, or `<br/ >` tag I put inside that. Even `<p><span /></p>` gets removed. They are pretty good at catching any non-text content in a set of `<p></p>` at the end of the paragraph.
