### ISSUE TITLE
why not provide a h3 icon

### ISSUE THREAD

**Issue by CatchLife** [quilljs/quill#2381]
![image](https://user-images.githubusercontent.com/15259698/47692593-42619600-dc31-11e8-9942-e869dd7d4a38.png)
usually, people use h2 and h3 to write article ,the h1 usually used as title of a article, so oi hope the official provide a h3 icon

**Comment by dcsaszar** [comment]
@CatchLife see https://github.com/quilljs/quill/issues/1730#issuecomment-371994144 for the answer

**Comment by jhchen** [comment]
That's correct thanks for the help @dcsaszar
