### ISSUE TITLE
getSelection(true) returns different results for same action in latest Safari vs other browsers

### ISSUE THREAD

**Issue by buffpojken** [quilljs/quill#2383]
**Steps for Reproduction**

1. Placing the cursor on the very first position in a document
2. Call `quill.getSelection(true)` 
3. Compare return value which is `{index: 0, length: 0}` in all browsers except latest Safari (Version 12.0 (14606.1.36.1.9)) which yields `null`. 

**Expected behavior**:
Expected Safari to return `{index:0, length:0}` like Chrome, Edge and Firefox.

**Actual behavior**:
Safari returns `null`.

**Platforms**:
Tested on Mac, running up-to-date Mojave.

**Version**:

1.3.6

**Comment by varminas** [comment]
Looking forward for the fix. At the moment quill cannot be used in Safari at all
