### ISSUE TITLE
Building all from scratch with webpack threw an error on importing icons.

### ISSUE THREAD

**Issue by antonedvard** [quilljs/quill#2385]
Latest Dev. version;

import Icons from './ui/icons';

Gave an error, something with not beeing able to read from an object.exports from the icons.js file.
On my local i changed it to export default icons and it fixed it.

Not sure if anyone else has had that issue but just wanted to throw it too you.

**Comment by benbro** [comment]
Please follow
https://github.com/quilljs/webpack-example
https://quilljs.com/guides/adding-quill-to-your-build-pipeline
If you still run into a bug, please submit the issue there.
