### ISSUE TITLE
How to use quill editor whith php

### ISSUE THREAD

**Issue by NeftaliAcosta** [quilljs/quill#2386]
I am trying to integrate Quill editor and an HTML form that works with php. The parameters are saved in the database.

I'm following this example:
http://quilljs.com/playground/#form-submit

I need the html code of the content of my editor to save it, what this example throws at me is an array How do I convert that information to HTML to save it in the database? :(

My HTML form:
![image](https://user-images.githubusercontent.com/15948880/47958356-8c2ee100-df8f-11e8-90f7-bc03928a425a.png)

My constructor js
![image](https://user-images.githubusercontent.com/15948880/47958358-9a7cfd00-df8f-11e8-8cac-ef8a638cf925.png)
![image](https://user-images.githubusercontent.com/15948880/47958419-eed4ac80-df90-11e8-8d3d-4253d59b6782.png)

The result:
![image](https://user-images.githubusercontent.com/15948880/47958341-3823fc80-df8f-11e8-8d35-090650d25a1c.png)

I need HTML output :( 

![image](https://user-images.githubusercontent.com/15948880/47958348-5d186f80-df8f-11e8-8fea-e26383ecd8ef.png)

Thanks

**Comment by benbro** [comment]
See this answer:
https://github.com/quilljs/quill/issues/128#issuecomment-215263950

**Comment by nadar** [comment]
@NeftaliAcosta Not sure this is what you need, but you can parse the quill delta data with my php quill render library:

https://github.com/nadar/quill-delta-parser
