### ISSUE TITLE
Custom Spell Check Support

### ISSUE THREAD

**Issue by Elbek97** [quilljs/quill#2387]
I wanted to create custom spell checker website in uzbek language. Site [imlowithit.uz](imlowithit.uz) is in beta. I used Quill as document editor. But i have hard time to fit spell checker to this editor.

**What do i have**

1. Quill based document editor
2. Spell Checker API (word checking, word suggestion)

**Expected behavior**:
1. Need for marking words (Splitting in low-level)
2. Markup 3 distinct states of every word:
- checked correct word
- checked wrong word
- not checked word
3. Events for word change (When word is written)

**Comment by jaska45** [comment]
I would like to have the same features. I have my own spell check REST API. Just need Quill to support word marking and callback to check sentences.

**Comment by shamoons** [comment]
This is tricky because my custom spell check API gives me start and end positions of words. Whereas Quill seems to wrap in HTML, so I'm not sure how to do the custom markings.
