### ISSUE TITLE
Container blot

### ISSUE THREAD

**Issue by tunctuncbilek** [quilljs/quill#2389]
I can't wrap all blots with container blot or i can't create container blot.

I expect `<main><p>this is first paragraph</p><p>this is second paragraph</main>`

when i register new blot as block, it replaces all p tags but i need container blot.

```
var Block = Quill.import('blots/block');
        class Main extends Block {
            static create() {
                var node = super.create();
                return node;
            }
        }

        Main.blotName = 'main';
        Main.tagName = 'main';

        Quill.register(Main);
```

This one doesn't work

```
var Container = Quill.import('blots/container');
        class Main extends Container {}

        Main.blotName = 'main';
        Main.tagName = 'main';

        Quill.register(Main);
```
Browser is chrome
Quill version is 1.3.6

**Comment by irux** [comment]
@tunctuncbilek did you solve this ? I have the same problem!

**Comment by tunctuncbilek** [comment]
No i didn't

**Comment by thiswhy** [comment]
I have the same problem...I think we can see the quill's List implementation ways

**Comment by muellerdberlin** [comment]
did anyone solved this issue? Any workaround?

**Comment by nikhil-ponduri** [comment]
I have same problem.  did you solve this? @tunctuncbilek

**Comment by tunctuncbilek** [comment]
No i didn't

**Comment by muellerdberlin** [comment]
Have you tried to upgrade to v2.0? May this (alpha) version works better. Good luck!
