### ISSUE TITLE
Initializing from paragraphs concats them

### ISSUE THREAD

**Issue by StreetStrider** [quilljs/quill#2393]
Hello. For some reason, starting Quill from container with paragraps (previously created by Quill itself), leads to the paragraphs to be concatenated into single one in Chrome (Chromium), displaying them as single line.

Consider container contents is `<p>1</p><p>2</p>`. Instantiating Quill on it will change contents to `<p>12</p>` in Chrome (and Chromium).

It seemes that Quill somehow uses container environment (like css text-related properties or something) to do such thing. I've tried to workaround it, by manually inserting `<br>` after each paragraph. After that Quill start to eliminate `<br>`'s instead of concatenating paragraphs.

But in the same time in Firefox everything works ok, so introducing additional `<br>` leads to creating redundant empty lines between real ones. This breaks consistency across browsers.

Quill version 1.3.6.

My code looks like this:
```js
new Quill(container,
{
	debug: 'warn',
	formats,
	readOnly: (! can_edit),
})
```
where `formats` is `bold, italic, underline, link and list`. 

Please, sorry if this issue is a dup or reflected somewhere in the docs. I've tried both documentation as well as issue search by keywords, trying to find something related to this issue.

**Comment by DmitrySkripkin** [comment]
Can't reproduce this issue, here is codePen with basic case - [CodePen](https://codepen.io/DmitrySkripkin/pen/ZmLvGw)

**Comment by StreetStrider** [comment]
We got problems to localize and reproduce it as well. I got everything works OK in current release and broken down in upcoming release with no palpable differences around Quill instantiation.
My best bet is something like `white-space` affects Quill or other thing in environment.
