### ISSUE TITLE
Undo actions inaccurate on iOS

### ISSUE THREAD

**Issue by guanxun14** [quilljs/quill#2394]
**Steps for Reproduction**

1. Visit the [standalone editor](https://quilljs.com/standalone/full/) on an iOS device.
2. Using either the software keyboard or an external hardware keyboard (I tested both), key in `1`, `2` and `3`, each character on a new line.
3. Select the `2`, and delete it, removing the empty line so that just `1` and `3` remain.
4. Insert a newline after the `3`, and key in `4` on that line.
5. Undo and redo using either (a) the built-in icons in the accessory bar of the software keyboard or (2) `Cmd+Z` and `Shift+Cmd+Z` keyboard shortcuts with an external hardware keyboard, to try to retrace these input steps.

![Steps to repro on iPad GIF](https://i.imgur.com/reQS1uI.gif)

**Expected behavior**:

- Undo/redo should identically reproduce originally input content.
- Note that this expected behaviour is replicable on Safari on *macOS* when following the same steps:

![macOS undo/redo results GIF](https://i.imgur.com/NBYjHtq.gif)

**Actual behavior**:

- Quill editor botches content after undo and redo operations are performed:

![iPad undo/redo results GIF](https://i.imgur.com/s4pYkpP.gif)

**Further Notes**:

1. Programatically triggering `quill.history.undo()` and `quill.history.redo()` instead of using the iOS-supplied software/hardware keyboard shortcuts seem to result in the accurate, expected behaviour. 
2. Testing the above steps with a regular [contenteditable](https://codepen.io/creativedev/pen/OVdvmN) element (i.e. non-Quill) I found online, iOS seems to handle the undo/redo steps just fine (although limited to history stack size of ~5 steps).
3. This suggests that there exists some interference or conflict between how iOS is handling undo/redo, and Quill's History module — which I don't claim to have a solution to at this point. So this is another bug report without suggestions to help fix the issue.

**Platforms**:

- Tested on iPad (actual) device
- In Safari browser, running iOS 12.0.1

**Version**: `1.3.6`

**Comment by rhysbrettbowen** [comment]
This is probably the same as: https://github.com/quilljs/quill/issues/2101. Once you have 2 characters next to each other that are the same (in this case the newline from pressing enter) then it can all go screwy. I've put a fix for it in the issue but never got around to making a PR
