### ISSUE TITLE
inline style instead of css class

### ISSUE THREAD

**Issue by hrizk** [quilljs/quill#2395]
hello,

is there a way to set font family inline styles instead of classes 

{
    import: 'formats/font',
    whitelist: ['sans-serif', 'monosapce', 'serif', 'Georgia', 'palatino-linotype', 'times-new-roman', 'Arial', 'Helvetica', 'arial-black',
      'comic-sans-ms', 'Charcoal', 'Impact', 'lucida-sans-unicode', 'lucida-grande', 'Tahoma', 'Geneva', 'trebuchet-ms', 'Verdana',
      'courier-new', 'lucida-console', 'Mirza', 'Roboto']
  }

**Comment by DokaRus** [comment]
Just register the font style attributor as `formats/font`
You can use [this example](https://codepen.io/Doka/pen/zMzarV) as an starting point

**Comment by hrizk** [comment]
thank you that worked
