### ISSUE TITLE
Getting the className or styles from the selected text (or from the block surrounding the caret location)

### ISSUE THREAD

**Issue by brandondurham** [quilljs/quill#2399]
I’m sorry to post a question instead of an actual bug, but I cannot find this info in the documentation anywhere. I’m adding classes to the selected text by using this method:

```js
const SelectionClass = new Parchment.Attributor.Class('classify', 'hco', {
	scope: Parchment.Scope.INLINE,
})
Quill.register(SelectionClass, true)

// … and then later:

// Get the className from the jss stylesheet
quill.format('classify', sheet.classes[classComp].replace(/^hco-/, ''))
```

This is working wonderfully, but I now find myself needing to read that class when that text is selected or the caret is within the bounds of that `<span />`.

In general, how do you read the styles or classNames that are represented in the selection or caret location? For example, I need to highlight the “Stylistic Sets” button (I’m not using the toolbar) when the user has the caret within the `<span />` that has the `hco-stylistic-sets` class.

I appreciate any tips I can get.

**Comment by ryanmitchell** [comment]
Bit late to the game, but it should come up when you use:

	quillInstance.on('selection-change', function(range, oldRange, source) {
		
		if (range) {
			
		 		 console.log(quillInstance.getFormat(range.index, range.length));

		}

	});

**Comment by benbro** [comment]
Thanks for the answer ryanmitchell.
