### ISSUE TITLE
The buttons change the style of the text, but do not return it to the normal view

### ISSUE THREAD

**Issue by ev4ik94** [quilljs/quill#2400]
I decided to follow the example, as shown [here]( https://codepen.io/quill/pen/qNJrYB), but when I click for example the bold or italic button, it adds the necessary tags to the text, and if I want remove the text back to the normal view, then it does not work. The buttons change the style of the text, but do not return it back to its normal appearance as it was originally. What do I need to add to the handlers of these buttons to fix this problem? 

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
Please fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) with a **minimal** example showing what you are trying to do.
