### ISSUE TITLE
Overriding Uploader defaults

### ISSUE THREAD

**Issue by n1ghtmare** [quilljs/quill#2403]
Hey guys!

Big fan of the project :smiley: 

I'm trying to add the ability to check if an image size is above a certain limit. I was going through the source code. I found the `Uploader` module (which is in turn used by the default `Image` handler) and it seems to have defaults that were intended to be overwritten (?).

I'm talking about: 
https://github.com/quilljs/quill/blob/9a77567fe356d384074df7479c33ceac509d9351/modules/uploader.js#L40

And more specifically - overriding `handler(range, files)` and provide my own implementation, that has a check for the file size.

Can someone show me how to do this from a client perspective? Also, am I going about this the wrong way? Basically I would like the user to be unable to upload an image over a certain size (perhaps even show some sort of a warning, but that's getting ahead of myself).

**Comment by n1ghtmare** [comment]
@rafalolszewski94 Cool, thanks for sharing, much appreciated! I was wondering, how do you handle a user deleting an image that he previously uploaded to the server? As in - he attaches it (which uploads it on the server), then decides to remove it.

**Comment by rafalolszewski94** [comment]
You would have to most likely to add some kind of already formated url with
image ID or other identifier which you would Ajax post to this url later
on. Top it off with custom button which will handle it

**Comment by sankamaduranga** [comment]
remove register
 components:{
          quillEditor,
          ImageUpload,
          ImageDrop,
          ImageResize
    },

**Comment by Camillo94** [comment]
@n1ghtmare did you develop a solution to delete an image?
