### ISSUE TITLE
Conflicting styles causing display issues

### ISSUE THREAD

**Issue by MartinGeldart** [quilljs/quill#2412]
I have implemented the setup given in the 'Quickstart' section of Quill's website.

The editor works but there is an issue with button styling:

<img width="645" alt="screenshot 2018-11-25 at 20 38 02" src="https://user-images.githubusercontent.com/40616569/48984345-74f89480-f0f2-11e8-895c-33e11f76cf1f.png">

When I comment out my own stylesheet it works as expected but fails as soon as I uncomment it. So, there is a conflicting style in there somewhere and my stylesheet is too large and complex to change, so will need to find a new editor which is a shame.

Unfortunately, this can only be reproduced with my own stylesheet.

I'm using Quill 1.3.6 and I'm using Chrome Version 70.0.3538.110 (Official Build) (64-bit) on MacOS 10.14.1.

**UPDATE:**

I have just managed to fix the problem. I luckily found the conflicting button in my stylesheet and gave it a unique ID to try and separate it from Quill and worked. The styles for my button were:

```
height: 48px;
line-height: 48px;
font-size: 13px;
text-transform: uppercase;
font-weight: 400;
width: 100%;
background: #000;
color: #FFF;
border: none;
padding: 0 8px;
cursor: pointer;
```
I'm guessing this is still an issue, as surely it shouldn't conflict as standard. Close this if you disagree.

**Comment by benbro** [comment]
The [theme](https://quilljs.com/docs/themes/) comes with a stylesheet. You can override it or create your own theme.
