### ISSUE TITLE
Placeholder text overflows editor

### ISSUE THREAD

**Issue by hoffmeyer** [quilljs/quill#2413]
When the height of the placeholdertext i larger than the editor it just overflows out the bottom.

**Steps for Reproduction**

1. Visit https://codepen.io/hoffmeyer/pen/JeZQLZ

**Expected behavior**:
The editor should expand to contain the placeholder text

**Actual behavior**:
The placholder text flows out of the editor area.

**Platforms**:
Tested on Windows 10 and Linux in Chrome 70

**Version**:
1.3.6

**Comment by benbro** [comment]
The placeholder should normally be few words long.
You can give the editor min-height:
```css
.ql-editor {
  min-height: 200px;
}
```

**Comment by jesselloyd** [comment]
I like the solution by @ajmueller - although I might suggest a slight change. If you use this method, you'll find that the actual content of the editor will be pushed down by the now statically positioned placeholder `::before` pseudo element - and so this gives the awkward behavior of the cursor being _underneath_ the placeholder. 

Hopefully this might help someone else if they run into this issue:

The simplest fix that you could employ without this being a PR to Quill would be to do the following in your own codebase:

```
.ql-editor.ql-blank::before {
  content: none;
}

.ql-editor.ql-blank::after {
  color: rgba(0,0,0,0.6);
  content: attr(data-placeholder);
  font-style: italic;
  pointer-events: none;
  display: block;
  margin-top: -1.42rem;
}
```

The `::after` pseudo element is just using the base styles already defined on the `::before` pseudo element, without the `position: relative` `left` and `right` rules.

**Comment by ajmueller** [comment]
@jesselloyd awesome solution!  This worked wonderfully, except I changed the `-1.42rem` to `-1.42em` to get the cursor placement perfect (and keep it relative to the font-size of the Quill editor).

**Comment by jesselloyd** [comment]
Good point! Thanks for catching that. I forgot to switch the units, that'll do it!

**Comment by ajmueller** [comment]
@jesselloyd one more minor tweak that I've found is necessary is to add a fallback for the `content` property.  So the entire snippet is:

```css
.ql-editor.ql-blank::before {
	content: none;
}

.ql-editor.ql-blank::after {
	color: rgba(0, 0, 0, 0.6);
	content: attr(data-placeholder, '');
	display: block;
	font-style: italic;
	margin-top: -1.42em;
	pointer-events: none;
}
```

Without this, Chrome renders the initial state of the editor like so:

![image](https://user-images.githubusercontent.com/1442179/71122428-6c5b7c00-2195-11ea-9bb8-aab7f15d654e.png)

Adding this fallback fixes the initial render:

![image](https://user-images.githubusercontent.com/1442179/71122467-839a6980-2195-11ea-904a-31f47596cb86.png)

Evidently Chrome doesn't like pseudo elements with content pointing to non-existent attributes.  Firefox renders it fine either way.
