### ISSUE TITLE
getContents() is not a function

### ISSUE THREAD

**Issue by AlexOtero32** [quilljs/quill#2414]
When I create an editor and set a default content with setContents(delta) coming from the database, once I try to send the content back to the database, it throws an error:

> TypeError: quill.getContents is not a function

If I don't use setContents() it works without any problem, but I need to set the content that comes from the database so my users can edit it.

**Steps for Reproduction**

1. Instance a new Quill editor:

`var quill = new Quill('#description', {
      modules: {
        toolbar: [
          ['bold', 'italic'],
          ['link', 'code-block'],
          [{ list: 'ordered' }, { list: 'bullet' }]
        ]
      },
      placeholder: 'Something something',
      theme: 'snow'
    }).setContents([
      data.ops[0]
    ], 'user');`

2. Retrieve the content once the form is being sent

`var form = document.querySelector('#newblog');
    form.onsubmit = function(e) {
      e.preventDefault();
      var about = document.querySelector('input[name=description]');
      about.value = JSON.stringify(quill.getContents());
      console.log("Value", about.value);
    };`

**Expected behavior**:
I should get the delta content from the Editor

**Actual behavior**:
It returns an error:

> TypeError: quill.getContents is not a function

**Platforms**:
Firefox Developer edition v64.0b10 (64-bit)
Linux Mint 18.2 Sonya

**Version**:
1.3.6

**Comment by DmitrySkripkin** [comment]
Looks like it is not a problem of quill itself. I think problem is in scopes, please make sure variable named `quill` is available at your `onsubmit` handler function. Try to move `quill` to global scope so it will be `window.quill`, just to make sure it works.

**Comment by benbro** [comment]
Please ask questions on StackOverflow.

Thanks for the answer DmitrySkripkin.
