### ISSUE TITLE
Quill causes page to jump down to editor after page load

### ISSUE THREAD

**Issue by kennwilson** [quilljs/quill#2415]
I'm using Quill on a community forum, using the typical page layout for forums/blogs: the page starts with showing a post, followed by a list of comments and a new comment form at the bottom. The Quill editor is set up for this form.

When loading any of these post pages, the page loads and then immediately jumps down to the text editor field. This happens automatically; it is not related to clicking the toolbar or pasting text, as in other open issues.

Unfortunately, this is a private community for members of our company's membership service so I can't provide a link to see the problem in the wild, but I can set one of the Quill devs up with access if it would be helpful.

**Steps for Reproduction**

1. Load page containing a Quill editor
2. Watch as page jumps to bottom rather than showing the top of the page content

**Expected behavior**:

The page will not scroll or change position.

**Actual behavior**:

The page jumps to the Quill editor. The focus does not change; that is, I can't just start typing in the editor, but the page jumps down so that the editor is displayed.

**Platforms**:

MacOS High Sierra (10.13), tested in the latest versions of Firefox, Chrome, and Safari. Users have also reported this behavior, but I don't have their browser/OS info.

**Version**:

I'm using Quill 1.2.0, installed via the quilljs-rails gem, but I'm also seeing this behavior with the latest Quill 1.3.6.

This is the quill configuration I'm using, based on the quilljs-rails documentation:

    var options = {
        bounds: '#reply',
        modules: {
            toolbar: [
                [ 'bold', 'italic', 'underline' ],
                [ 'link', 'image' ],
                [ { 'list': 'ordered' }, { 'list': 'bullet' }, 'blockquote' ]
            ]
        }
    };
    Quilljs.setDefaults(options);

**Comment by kennwilson** [comment]
It turns out this was related to Turbolinks and how I was including the Quill JS into my pages. Closing.

**Comment by kjantzer** [comment]
>The page jumps to the Quill editor. The focus does not change; that is, I can't just start typing in the editor, but the page jumps down so that the editor is displayed.

@kennwilson – what did you end up changing? I'm having the same symptom (although I'm not using turbolinks)

**Comment by kjantzer** [comment]
@kennwilson scratch that – #2156 pointed me in the right direction

**Comment by nitinlavania15** [comment]
Hi @jhchen,

Greetings!

I am currently using Quill version 2.0.2 in my Angular application and encountering some challenges with table functionality:

1. I am successfully able to copy an Excel table and paste it into the Quill editor using the quill-better-table module.
2. However, the colors from the Excel table do not appear after pasting it into the Quill editor.
3. Additionally, other templates are distorting when I use the following code:
`this.quillEditor.setContents(this.quillEditor?.clipboard?.convertHTML(this.data?.selectedMail?.bodyHTML))`

Could you please provide guidance on how to achieve a more seamless integration?

Thank you.
