### ISSUE TITLE
Question: EventListener for Loading of Large Content

### ISSUE THREAD

**Issue by paolavness** [quilljs/quill#2416]
Hi there,
First thank-you. Tho relatively new to Quill I'm excited about its potential!

I've searched the docs & issues for an answer to this; apologies in advance if I've missed it.

When pasting large content which takes a while to render and appear in the editor, I'd like to be able to be able to give users a visual cue (like `cursor: progress`) that the paste has been received and the editor is processing it.

Are there any Quill eventListeners I can plug into or do you have other suggestions?

Thanks,
Paola

**Comment by DmitrySkripkin** [comment]
This operations seems to be synchronous, so I think there is no way to get progress. But I might be wrong. Need some time to check what options we have. I didn't mention it to be slow, clipboard is fast enough.

Small tip (this probably not relevant to the issue). Every `setContents()` returns diff, it's really slow. If you want to perform `setContents()` faster just do `setText('')` before `setContents()` to reduce diff work.

**Comment by DmitrySkripkin** [comment]
Oh, ok. I think I can provide some example with pasting progress. Need some time to make it minimal and clear.
