### ISSUE TITLE
Question: Lazy load & append to end of existing delta content

### ISSUE THREAD

**Issue by paolavness** [quilljs/quill#2417]
Hi there,

I'm working on lazy loading the display or large content to side step performance issues when rendering large content in the form of deltas (delta are being retrieved from the server, previously saved from `editor.getContent()`)

I've written something similar to the lazy load referenced in #627 but updateContent() appends new content **on top** of existing content, resulting in content being rendered in reverse. Using `Delta.concat`, as noted in #1838 is not an option as this requires a `setContent()` which results in an even bigger performance hit. 

Can you suggest any other ways to `update` existing content by adding to the **end** of the existing content?

Thank you,
Paola

**Comment by jhchen** [comment]
I think you want something like:

```js
var delta = new Delta().retain(existingContentLength).concat(nextDeltaChunk);
quill.updateContents(delta);
```

**Comment by everettglovier** [comment]
@paolavness  i know this is an old issue, but i too am working on lazy loading large documents and wanted to see if you made any progress!

**Comment by paolavness** [comment]
@everettglovier no I havent... We've actually started exploring alternative solutions, while just dealing with the slow load. A new version may be coming out soon, and perhaps this will resolve it.

**Comment by everettglovier** [comment]
@paolavness thanks for the reply! Maybe I'll hold off and just wait as well.
