### ISSUE TITLE
Format Blots extended from Blockembeds 

### ISSUE THREAD

**Issue by vinitpradhan18** [quilljs/quill#2418]
How can I format Custom Blot that is extended from BlockEmbed? I have a twitter blot, which I want to give users the option to align it to left, right or center. I can have implemented it using DOM methods with toggling classes and inline styles. But those styles do not reflect in delta. And when the delta is loaded in the editor, it doesn't format the embed correctly. How can I do it correctly? I didn't find any documentation or examples to solve my issue. I am trying to achieve something like how Medium lets users to align Images.

Any help with sample code is appreciated.

**Comment by jaredly** [comment]
If you look at the source code for [the image blot](https://github.com/quilljs/quill/blob/ee827ffb605ba491246f201d497ce0e7d9e193a0/formats/image.js) you can see that it recognizes the `alt`, `width`, and `height` parameters to be specified by Delta format attributes. I'd suggest using the image blot file as your template, and adding `align` to the list of `ATTRIBUTES`, and then you'd have to change `static formats(domNode)` and `format(name, value)` to handle that attribute as well (which probably does on the `style` object, as opposed to directly on the dom node)

**Comment by vinitpradhan18** [comment]
Thanks. When you said that I

> have to change `static formats(domNode)` and `format(name, value)` to handle that attribute as well

 what do you mean exactly? Does the default `static formats(domNode)`  and `format(name, value)` not handle the align attribute. I tried your approach. And it worked. But the align value in the delta was an empty string no matter what value I set it for align attribute. So after saving, when I re-loaded the editor the alignment was left (that is probably because quill interprets empty string value as left alignment).

Here is a snippet of my ImageBlot:

```
import ReactQuill from 'react-quill';
const Quill = ReactQuill.Quill;
const BlockEmbed = Quill.import('blots/block/embed');
const ATTRIBUTES = ['height', 'width', 'align', 'src'];
class ImageBlot extends BlockEmbed {
  static create(value) {
    const node = super.create(value);
    if (typeof value === 'string') {
      node.setAttribute('src', value);
    }
    node.setAttribute('width', 300);
    node.setAttribute('height', 300);
    node.setAttribute('align', 'center');
    return node;
  }
  static formats(domNode) {
    return ATTRIBUTES.reduce((formats, attribute) => {
      if (domNode.hasAttribute(attribute)) {
        formats[attribute] = domNode.getAttribute(attribute);
      }
      return formats;
    }, {});
  }
  static value(domNode) {
    return domNode.getAttribute('src');
  }
  format(name, value) {
    if (ATTRIBUTES.indexOf(name) > -1) {
      if (value) {
        this.domNode.setAttribute(name, value);
      } else {
        this.domNode.removeAttribute(name);
      }
    } else {
      super.format(name, value);
    }
  }
}
ImageBlot.blotName = 'image';
ImageBlot.tagName = 'IMG';
export default ImageBlot;
```

**Comment by jaredly** [comment]
Oh fancy, I guess you didn't need to change those functions.
So how are you setting the `align` formatting attribute? Can you post the code where you're creating the image?

**Comment by vinitpradhan18** [comment]
Here is how I am creating the image;

```
 const path = 'some path url';
 const range = quillRef.getSelection(true);
 quillRef.getModule('image');
 quillRef.insertEmbed(range.index, 'image', path, Quill.sources.USER);
 quillRef.formatText(0, 1, 'align', 'right')
 quillRef.setSelection(range.index + 1, Quill.sources.SILENT);
```

The align right seems to work fine. But I can't seem to align it to the center.

**Comment by jaredly** [comment]
That's because `align="middle"` doesn't seem to be well supported by browsers. see https://codepen.io/anon/pen/zyGrvv and https://www.w3schools.com/tags/att_img_align.asp
