### ISSUE TITLE
IE11 Background color selection reverts to adjacent background color

### ISSUE THREAD

**Issue by StevenElberger** [quilljs/quill#2421]
**Steps for Reproduction**

1. Visit https://quilljs.com/ in IE11 (3rd example -- with background color button)
2. Delete all content
3. Choose a background color
4. Type some text
5. Choose a different background color
6. Click at the end of the text content
7. Type some text

**Expected behavior**: Typed text from step 7 has the second background color

**Actual behavior**: Typed text from step 7 has the first background color

**Browser**: IE11
**Operating System**: Windows 10
**Quill Version**: 1.3.6

**Comment by benbro** [comment]
IE 11 is not on the list of supported browsers:
https://github.com/quilljs/quill/blob/master/README.md
