### ISSUE TITLE
What determines which blot will be rendered as the parent?

### ISSUE THREAD

**Issue by alex6480** [quilljs/quill#2422]
Hi

I have made a custom blot and I want it to be rendered as the parent to blots like bold, italic and such, so that only a single element from my blot is rendered.

Imageine that the following text is wrapped with my custom blot

text **bold** text

This renders as

    <customblot>text</customblot><b><customblot>bold</customblot></b><customblot>text</customblot>

I want it to render as 

     <customblot>text<b>bold</b>text</customblot>

Can this be done, and if so how?

**Comment by jaredly** [comment]
I think this is what determines the ordering https://github.com/quilljs/quill/blob/develop/blots/inline.js#L48 
I'd guess that if you insert your blot name between `bold` and `script`, it would do what you want.

**Comment by alex6480** [comment]
Thanks. This works perfectly as intended.
