### ISSUE TITLE
this.scroll.query is not a function

### ISSUE THREAD

**Issue by sungd** [quilljs/quill#2425]
i use the qull.core.js in my project.
And i want to custom the toolbar.
when i exceute the following statement, i meet the error "this.quill.scroll.query in not function". 
Could anyone help me?
`if (range.length === 0) {
              Object.keys(formats).forEach(name => {
                if (this.quill.scroll.query(name, Scope.INLINE) != null) {
                  this.quill.format(name, false, Quill.sources.USER)
                }
              })
            } else {
              this.quill.removeFormat(range, Quill.sources.USER)
  }`

**Comment by benbro** [comment]
Impossible to help without a minimal example.
Please ask on StackOverflow.
