### ISSUE TITLE
What is the best way to completely control the style and position of the tooltip?

### ISSUE THREAD

**Issue by dmcquayps** [quilljs/quill#2426]
It seems that bubble provides me with the tooltip positioning. I'd like to override most if not all of the styles bubble provides for the tooltip. In fact, I'd be happy to make my own tooltip. But I'm not sure the best way to do that. The only way I see in the docs to get a tooltip is to use the bubble theme. How bubble positions the tooltip seems to be out of my control. Can I make an entirely custom theme? Is there a reasonable way to make my own tooltip that doesn't involve a theme at all?

**Comment by natterstefan** [comment]
Hi @dmcquayps, I was also asking myself how I can get a tooltip in other themes (eg. snow). Let's see who can help us out. :)

**Comment by benbro** [comment]
You can extend the bubble tooltip and bubble theme with your custom logic.
https://github.com/quilljs/quill/blob/develop/themes/bubble.js
