### ISSUE TITLE
IE11 White/Clear background color clears adjacent background color

### ISSUE THREAD

**Issue by StevenElberger** [quilljs/quill#2427]
Similar to https://github.com/quilljs/quill/issues/2421 but slightly different.

**Steps for Reproduction**

1. Visit quilljs.com -- third example (with background colors)
2. Clear the content in the editor
3. Select a background color
4. Type some text
5. Select a second background color
6. Type additional text
7. Select the white background color

**Expected behavior**:
The two previous background colors still exist

**Actual behavior**:
The second background color gets replaced with the white background color (or gets removed).

**Browser**: IE11
**Operating System**: Windows 10
**Quill Version**: 1.3.6

**Comment by benbro** [comment]
IE 11 is not on the list of supported browsers:
https://github.com/quilljs/quill/blob/master/README.md
