### ISSUE TITLE
Keyboard module no way to invoke stopImmediatePropagation on the event.

### ISSUE THREAD

**Issue by andrei-cacio** [quilljs/quill#2428]
In the latest 1.x build the `evt` in the keyboard module is not exposed and there is no way to call the `evt.stopImmediatePropagation()` method. As I can see on master, the event is now exposed on the context object. Can we maybe do a minor build with the event exposed?

**Steps for Reproduction**

Compare the [master version](https://github.com/quilljs/quill/blob/develop/modules/keyboard.js#L121) with the [latest stable release](https://github.com/quilljs/quill/blob/96e38e92637b75b907579d0cc1b201920aebe38c/modules/keyboard.js#L89)

**Expected behavior**:
To have a way to stop the event bubble propagation

**Actual behavior**:

No way to stop the propagation.

**Platforms**:

All

**Version**:
1.3.6

**Comment by benbro** [comment]
If it's fixed on dev, it's probably better to change it locally in a custom build or extend/replace the keyboard module:
https://quilljs.com/docs/modules/
https://quilljs.com/guides/how-to-customize-quill/#modules

**Comment by andrei-cacio** [comment]
@benbro there are a lot of issues fixed on dev. Are there any plans in releasing an intermediate version in the meanwhile? I am thinking that 2.0 will take some time and in the mean time we are stuck in managing a local copy of Quill and patching it
