### ISSUE TITLE
How to paste raw HTML?

### ISSUE THREAD

**Issue by shyamal890** [quilljs/quill#2429]
Using `dangerouslyPasteHTML` trims dom elements like `table`. How to paste Raw HTML? 

Please note, sanitization is taken care by the server.

**Version**: 1.3.6

**Comment by DmitrySkripkin** [comment]
It's not possible. Editor value is stored as delta and there is no support for tables (not sure about dev version), so it's trimmed.

**Comment by shyamal890** [comment]
Its okay if pasted HTML is not editable but atleast there should be a way.

**Comment by benbro** [comment]
Quill supports a limited list of elements, classes and style attributes.
You can add custom attributors and extend the clipboard module.

**Comment by shyamal890** [comment]
@benbro There should be a way to allow completely rawHtml and developer would take care of sanitisation. 

With custom attributes also we cannot paste rawHTML as quill removes some elements like table and replaces it with p for example

**Comment by josephadah** [comment]
@shyamal890 were you able to get a workaround? quill is not rendering my custom element e.g <my-element></my-element>

**Comment by lizy0329** [comment]
> Quill supports a limited list of elements, classes and style attributes.
> You can add custom attributors and extend the clipboard module.

Discuss is not finish yet, why @benbro can closed this issus ?

what solution methods in case?
