### ISSUE TITLE
How to restore contents in a new element with styles?

### ISSUE THREAD

**Issue by bahmanian** [quilljs/quill#2430]
When I restore my saved data with root.innerHTML, Styles like text-align and blockquote does not effects in new element. should I add 'ql-editor ql-snow' classes to the new element?

**Comment by benbro** [comment]
You should use the Delta format instead of raw HTML.
If you do use raw HTML although it's unsafe, sure you need to define the same classes as Quill or use style attributors instead of class attributors:
https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline
