### ISSUE TITLE
Span tags are removed 

### ISSUE THREAD

**Issue by kriss145** [quilljs/quill#2431]
Hi,

Why I can't use span tags with custom class in the editor?

Example:
`<p>Lorem ipsum <span class="custom-class">dolor</span></p>`

Output:
`<p>Lorem ipsum dolor</p>`

Thanks

**Comment by DmitrySkripkin** [comment]
You have to create new format or embed to do that (that's fairly easy).

**Comment by benbro** [comment]
Thanks DmitrySkripkin.
