### ISSUE TITLE
Roadmap for 2.0?

### ISSUE THREAD

**Issue by JamesMcMahon** [quilljs/quill#2435]
Do you have a publicly facing roadmap for the progress to 2.0? Sorry if I missed it somewhere, it would be nice to have some visibility into the development in order to make a determination about wither Quill is going to be the right choice for our product. I read your [Medium post](https://medium.com/@jhchen/the-state-of-quill-and-2-0-fb38db7a59b9), but that is more then a year old at this point.

My projects is specifically looking to use tables.

Thanks very much for all your hard work on Quill. The point of this issue is not to bug you, but to get all the available information in order to make the right choices for my team.

**Comment by hicham-elmansouri** [comment]
Hi 
I'm in the same situation. Waiting for table for a while. I'm moving to slatejs.

**Comment by shyamal890** [comment]
Yes, would really appreciate a reply on this. We have been waiting for tables for sometime now.

**Comment by SilentTiger** [comment]
yes, i'm in the same situation, waiting for the table function

**Comment by bridgettegraham** [comment]
also waiting for quill 2 and tables... would be nice to get an idea of what the roadmap looks like.

**Comment by aboosoyeed** [comment]
Any updates ?

**Comment by atiris** [comment]
Happy 1 year anniversary [version 2.0](https://github.com/quilljs/quill/releases/tag/v2.0.0-dev.0)! :cake:

Since there is very little information about release plans (this is also seen in the activity of this thread), and the year of life of software should be at least enough to become a RC from a Beta, I would like to ask you very much @jhchen if you would tell us something about release plans.

Is there **any way to help** create an RC / 2.0 production version :question: 

Can you use this thread to tell us:

- what missing functionality blocks the creation of version 2.0?
- how can we help?
- what tasks have already been done?
- and what features need to be added until you release it?

Many thanks for future information. :clap:

**Comment by jsatec-pm** [comment]
Hi @jhchen ,
Would be great to have the table function available and any news on the roadmap of 2.0.
Many thanks.

**Comment by VaelVictus** [comment]
There's activity on the repo, but not much from jhchen himself. Curious on release plans as well.

**Comment by guilhermeaiolfi** [comment]
It doesn't looks like 2.0 will be a reality anytime soon. This project may be in maintenance mode as the activity indicates. Very unfortunately.

**Comment by vedadeepta** [comment]
Any update on this?

**Comment by jodinathan** [comment]
it seems people are testing the 2.0. 
Which branch is it?

**Comment by VaelVictus** [comment]
Where do you see people testing 2.0?

Might be worth replacing Quill with tiptap: https://tiptap.dev/

**Comment by jodinathan** [comment]
@VaelVictus tiptap seems nice, unfortunately, there isn't an example of vanillajs common CDN usage, which is our premise.  

Saw about 2.0 on CodePen with the new table feature: https://codepen.io/quill/pen/QxypzX. 
Also there are issues here talking about 2.0

**Comment by perjerz** [comment]
Any update?

**Comment by ericksonc** [comment]
I think it’s pretty safe to assume at this point that there will not be any
updates.

**Comment by MatteoGauthier** [comment]
## Cool alternatives to Quill (OSS) :

> Best rich text editor / WYSIWYG

- https://tiptap.dev/
- https://prosemirror.net/
- https://froala.com/wysiwyg-editor/
- https://github.com/tinymce/tinymce
- https://trix-editor.org/

**Comment by perjerz** [comment]
> ## Cool alternatives to Quill (OSS) :
> 
> 
> 
> > Best rich text editor / WYSIWYG
> 
> 
> 
> - https://tiptap.dev/
> 
> - https://prosemirror.net/
> 
> - https://froala.com/wysiwyg-editor/
> 
> - https://github.com/tinymce/tinymce
> 
> - https://trix-editor.org/

Which one have concept of blot and parchement?

**Comment by ackmanx** [comment]
Would love to see some mention of progress. Quill hasn't been updated in years and Intellij flags it as having a vulnerability. Supposedly Quill v2 resolves the issue but crickets everywhere I look for information.

**Comment by johnnyoshika** [comment]
> > ## Cool alternatives to Quill (OSS) :
> > > Best rich text editor / WYSIWYG
> > 
> > 
> > 
> > * https://tiptap.dev/
> > * https://prosemirror.net/
> > * https://froala.com/wysiwyg-editor/
> > * https://github.com/tinymce/tinymce
> > * https://trix-editor.org/
> 
> Which one have concept of blot, delta and parchement?

We use Froala extensively at my company and I can confirm that it's very different from Quill. It uses the DOM as the single source of truth. I'd also be interested in the answer to @perjerz's question: which alternatives have the concept of blot, delta, and parchment?

**Comment by Priestch** [comment]
> > > ## Cool alternatives to Quill (OSS) :
> > > > Best rich text editor / WYSIWYG
> > > 
> > > 
> > > 
> > > * https://tiptap.dev/
> > > * https://prosemirror.net/
> > > * https://froala.com/wysiwyg-editor/
> > > * https://github.com/tinymce/tinymce
> > > * https://trix-editor.org/
> > 
> > 
> > Which one have concept of blot, delta and parchement?
> 
> We use Froala extensively at my company and I can confirm that it's very different from Quill. It uses the DOM as the single source of truth. I'd also be interested in the answer to @perjerz's question: which alternatives have the concept of blot, delta, and parchment?

I think ProseMirror has all the abilities you can do with Quill, sure it has no concepts like blot, delta and parchment. it use some other terminologies like [mark](https://prosemirror.net/docs/ref/#model.Mark), [transform](https://prosemirror.net/docs/guide/#transform) etc. I didn't use quill, maybe parchment is something like [schema](https://prosemirror.net/docs/ref/#model.Document_Schema) of ProseMirror?

Tiptap is based on ProseMirror, you can also give it a try, it has a lot of out-of-box extensions to boost the development.

**Comment by ericksonc** [comment]
+1 for ProseMirror. It's what I moved onto once I realized Quill was a dead
project.

**Comment by johnnyoshika** [comment]
TipTap can get very expensive. We are a small company and we don't get a lot of traffic, but we get weekly spikes (e.g. when 500 students write an exam at once). That's CA$1,359 / month for TipTap 😬

ProseMirror does indeed look good. I like its philosophy as described here: https://www.youtube.com/watch?v=EEF2DlOUkag

Any thoughts on [Lexical](https://lexical.dev/docs/intro)? It's a relatively new editor by Meta and meant to replace Draft.js. It was presented by [one of the authors at JSConf](https://www.youtube.com/watch?v=EwoS0dIx_OI)

**Comment by ericksonc** [comment]
Not sure what you mean? TipTap is just a free open source Vue wrapper
around ProseMirror. It doesn't cost anything.

**Comment by johnnyoshika** [comment]
@ericksonc Maybe I misunderstood? This is what I see on their pricing page: https://tiptap.dev/pricing

**Comment by johnnyoshika** [comment]
Hmmm, is it just Tiptap Collab that requires the subscription and all else is free?

**Comment by Priestch** [comment]
> @ericksonc Maybe I misunderstood? This is what I see on their pricing page: https://tiptap.dev/pricing

The core editor is free and open source, only some extensions they developed require payment, you can absolutely develop your own solution.

**Comment by ericksonc** [comment]
Exactly. Think of the fact that they feel justified in charging those
ridiculous sums for extra extensions as just more proof of how powerful the
underlying ProseMirror framework really is 😆

**Comment by johnnyoshika** [comment]
Thanks @Priestch and @ericksonc for the clarification. I've narrowed my options down to Lexical and TipTap. If anyone has experience using both, I'd love to hear your thoughts.

**Comment by fbaube** [comment]
> @VaelVictus tiptap seems nice, unfortunately, there isn't an example of vanillajs common CDN usage, which is our premise.

Did you ever track down a vaniullaJS CDN example for TipTap ?

**Comment by benbro** [comment]
[v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2)
