### ISSUE TITLE
Impossible to replace whole link with new content

### ISSUE THREAD

**Issue by mitar** [quilljs/quill#244]
If I have a link and would like to erase whole content and type new text content for the link this is not possible. If I delete all characters of the link and start typing, information about existence of the link is lost and a normal text gets input. It should remember that I just removed all content and keep the information about the link. If I would click or move somewhere else, then link should not happen anymore.

**Comment by jhchen** [comment]
It's unclear the complexity this introduces does is worth the UI annoyance it would mitigate and no one seems to have been motivated to move this forward towards an implementation.
