### ISSUE TITLE
Keep custom class attributes while using dangerouslyPasteHTML()

### ISSUE THREAD

**Issue by LeoGreu** [quilljs/quill#2440]
Hey there!
First of all: I searched for similar topics but could not find another active one.

I try to dangerouslyPasteHTML to Quill that has some tags with class attributes (see example below). However, Quill "normalizes" this input and removes the custom attributes.

**Steps for reproduction**

```
myQuill.clipboard.dangerouslyPasteHTML("<p class='text-justify lead'>Test<p>");
```

**Actual vs. expected behavior**:

If I later access the HTML with

```
var myHTML = quill.root.innerHTML;
```
the custom class attributes are gone, but I would like to keep them.

**Approach so far**

I tried to use `Parchment` to add a custom `Class Attributor` [(Link)](https://github.com/quilljs/parchment#attributors) and ended up with this:

```
Parchment = Quill.import('parchment');

var config = {
  scope: Parchment.Scope.BLOCK
};

var customParchment = new Parchment.Attributor.Class('text-justify', 'lead', config);
Quill.register(customParchment, true);

var myQuill = new Quill('#myQuill-editor', {
  modules: {
    toolbar: [
      [{header: [1, 2, 3, 4, 5, 6, false]}],
      ['bold', 'italic', 'underline'],
      [{'list': 'ordered'}, {'list': 'bullet'}]
    ]
  },
  theme: 'snow'
});
```
However, this is not working at all, and the two attributes are still being removed.

Any help would be highly appreciated. Thank you!

**Comment by benbro** [comment]
The class attributors are hardcoded in the [clipboard module](https://github.com/quilljs/quill/blob/develop/modules/clipboard.js#L42). You'll need to [extend](https://quilljs.com/docs/modules/#extending) the module and add your custom attributor.
