### ISSUE TITLE
Trying to render (read-only) tables with Quill

### ISSUE THREAD

**Issue by andrei-cacio** [quilljs/quill#2441]
It is more a technical question rather than an issue but I cannot figure out how to solve it. 

I am trying to render make Quill render a simple table. I do not intend to have manipulations on that table, only on the text in the cells. 

```html
<div id="content">
    <table>
        <tbody>
            <tr>
                <th data-rte-fence=""><b>Table header</b></th>
            </tr>
            <tr>
                <td data-rte-fence="">row 1</td>
            </tr>
            <tr>
                <td data-rte-fence="">row 2</td>
            </tr>
        </tbody>
    </table>
</div>
```

I created my blots like so:

```javascript
import Quill from 'quill';

const { Block, Container } = Quill.import('parchment');

class TableCell extends Block {
    static tagName = 'TD';
    static blotName = 'table-cell';
}

class TableHead extends Block {
    static tagName = 'TH';
    static blotName = 'table-head';
}

class TableRow extends Block {
    static tagName = 'TR';
    static blotName = 'table-row';
    static allowedChildren = [TableHead, TableCell];
}

class TableBody extends Block {
    static tagName = 'TBODY';
    static blotName = 'table-body';
    static allowedChildren = [TableRow];
}

class Table extends Block {
    static tagName = 'TABLE';
    static blotName = 'table';
    static allowedChildren = [TableBody];
}

Quill.register(Table);
Quill.register(TableBody);
Quill.register(TableRow);
Quill.register(TableCell);
Quill.register(TableHead);

```
However I spin it I am still getting this error:
> Uncaught Error: Cannot insert block into scroll

After reading the parchment docs I understood that Block blots are similar to block like elements like `<p></p>` or `<div></div>` so I figured that they could be a good fit for `<table>`, `<tbody>` etc. So I figured that it would be enough just to create the blots and populate them with the correct tag names and Quill will simply render them.

In the parchment docs only three kind of blots are described: `Block`, `Inline` and `Embed` however in the Quill code base I see all sorts of blots used like: `Container`, `Scroll` etc. I couldn't find the relationship between them and I don't understand when to use one and when the other. In my examples, I simply inherit from the `Block` blot.

Any help is kindly appreciated thanks!

**Steps for Reproduction**

Demo here: https://codesandbox.io/s/rmlrl2oqqn
StackOverflow question: https://stackoverflow.com/questions/53871816/handling-table-raw-html-in-quill

**Expected behavior**:
Simply rendering the table

**Actual behavior**:
Error when inserting the block

**Platforms**:

Chrome, MacOS Mojave

**Version**:

1.3.6

**Comment by xinglianhou** [comment]
you can see the version of 2.0.0-dev.0

**Comment by andrei-cacio** [comment]
hmm I have copied the `Table` module and the custom blots and simply pasted them in my project and registerd the module like so:

`Quill.register('modules/table', TableModule);`

and when I initialise Quill I tell it to use the Table module too:

```javascript
new Quill(..., { 
   modules: { table: {} }
}); 
```

but still nothing. I still get `<p />` instead of table elements. Is there other logic parts in the quill core which help with the table support?

**Comment by wuxiandiejia** [comment]
Maybe this demo can help you https://codepen.io/quill/pen/QxypzX
Table module has a `insertTable` method.

**Comment by andrei-cacio** [comment]
The demo is based on Quill 2.0. Which isn't released yet. I wouldn't feel too comfortable going in production with a `dev` release. All the docs and reading material are written for Quill 1.x. (Or if there are docs for Quill 2.0 please link me). I tried installing Quill 2.0 but a lot of the API's have changed and I would have to rewrite a lot of logic for it to work. Also because of there aren't any docs I have to dig deep into the source code to understand how everything works in Quill 2.0.

**Comment by xinglianhou** [comment]
it change a lot from 1.x  to 2.0 dev
the base class 'Parchment' also change something,like add the 'AllowContainer' attr.
In my project,I just use the quill2.0dev and parchment2.0.0
One day,release 1.x to support table,then change the package.

**Comment by benbro** [comment]
Work on tables is already in the develop branch.
You can check if previous attempts to add table to the 1.x branch match your requirements but duplicating the effort is probably a waste.
https://github.com/quilljs/quill/issues/117

**Comment by padraigfl** [comment]
Just adding a note to anyone who's googling this to say 2.0.0-dev.3's built in table functionality is highly unreliable and I wouldn't use it on a production product.
What I've observed so far:
- no support for multiple lines (it appears to treat new line characters as a means to instantiate the next cell so it ignores them when a user tries to hit return within a cell?)
- pasted in content with multiple lines breaks tables (creates extra cells)
- inserting a list into a table breaks the table (table is split in two and list is placed in between the two tables)

There's a plugin called `quill-better-table` which provides a lot of the table features you may be looking for (some things still break, eg. lists within tables, it's an admirable effort from one person) but if you haven't yet adopted quill and tables are important to your project, I'd consider alternative editors (e.g. ProseMirror, TinyMCE)

**Comment by mmouterde** [comment]
You may try to implement using BlockEmbed :
```
let BlockEmbed = Quill.import('blots/block/embed');
class TableBlot extends BlockEmbed {
    static blotName = 'table';
    static tagName = 'table';
    static className = 'table';
    constructor(node) {
        super(node);
        this.domNode.setAttribute('contenteditable', 'false');
    }
    length() {
        return 1;
    }
}
Quill.register(TableBlot);
```

**Comment by Harish-78** [comment]
> It could be done using BlockEmbed :
> 
> ```
> let BlockEmbed = Quill.import('blots/block/embed');
> class TableBlot extends BlockEmbed {
>     static blotName = 'table';
>     static tagName = 'table';
>     static className = 'table';
>     constructor(node) {
>         super(node);
>         this.domNode.setAttribute('contenteditable', 'false');
>     }
>     length() {
>         return 1;
>     }
> }
> Quill.register(TableBlot);
> ```

then how to implement the table in quill
