### ISSUE TITLE
package a new version base on 1.3.6

### ISSUE THREAD

**Issue by xinglianhou** [quilljs/quill#2443]
I want to package a new version base on 1.3.6, For this editor supports the <table>.like 2.0.0-dev.But base on 1.3.6

**Steps**

1.I download the code from https://github.com/quilljs/quill/tree/v1.3.6
2.then I add the table.js
3.then exec the package.json command 
'npm run build'

But it build with error,like this row
"build": "webpack --config _develop/webpack.config.js; rm dist/quill.core dist/quill.bubble dist/quill.snow;"
 
Can you tell me the build steps,If my steps is wrong.
Thanks a lot.
Best wishes.

**Comment by benbro** [comment]
Follow the example:
https://github.com/quilljs/webpack-example
