### ISSUE TITLE
Retain kept in compose

### ISSUE THREAD

**Issue by RobbinBaauw** [quilljs/quill#2450]
Hi,

I'm working with Quill and I noticed an error. When formatting a whole row (for example the code-block formatting), you get a `[{retain: x}, {retain: 1, attributes: {....}}]` ops object. If you do `compose` on that, the last `retain` is still there at the end, meaning you get an object with inserts and `retain` at the last index.

After more experimenting, it seems like that is also true if I do two enters, as you can see in the demo.

Now when you try to `diff` that object, you get an error as it looks for inserts, which is `null` in the last row (or in the case of the enters the second row)

**Steps for Reproduction**

1. Go to https://codepen.io/robbinbaauw/pen/JwpyRv
2. Select the line and view console logs or hit enter twice and view console logs

**Expected behavior**:
The compose only gives inserts and the diff works without erroring.

**Actual behavior**:
The compose has retains and the diff errors. Right now, a combination of `compose` and `diff` is pretty unusable.

**Platforms**:
Doesn't matter AFAIK, tried in Chrome 71 and Firefox 64

**Version**:
1.3.6 and 2.0.0-dev3

**Comment by jhchen** [comment]
Your `firstInsert` is invalid as it does not end in a newline https://quilljs.com/docs/api/#setcontents. You can either end it in a newline or set firstInsert to the return of https://quilljs.com/docs/api/#getcontents. But at present you are not diffing against the actual document states so the diff and compose returned will not describe Quill's document states. Also it is not recommend to construct Deltas by hand in general: https://quilljs.com/docs/delta/ and should instead use the chainable, insert/delete/retain functions.
