### ISSUE TITLE
Invalid setSelection call signature in getFormat documentation

### ISSUE THREAD

**Issue by philraj** [quilljs/quill#2451]
Docs for `getFormat` seem to use an invalid form of `setSelection`.

**Steps for Reproduction**

1. Visit https://quilljs.com/docs/api/#getformat
2. Look at the examples, where it says `quill.setSelection(3)`

According to the `setSelection` docs, this isn't a valid setSelection call signature. 

**Expected behavior**:
Examples should show valid call syntax.

**Actual behavior**:
Examples appear to use invalid syntax.

**Platforms**:
Everything.

**Version**:
This is documentation.

**Comment by jhchen** [comment]
`quill.setSelection(3)` is valid but the setSelection look like the second parameter is missing the fact it has a default value of 0. Would you mind submitting a PR to add this?

**Comment by philraj** [comment]
https://github.com/quilljs/quill/pull/2452
Like this?
