### ISSUE TITLE
How to remove delta from history

### ISSUE THREAD

**Issue by marsielko** [quilljs/quill#2453]
Hi, I'm having problem with removing delta from Quill's history. Is there any way how can I tell the Quill which Delta I would like to remove from history? Or can someone explain to me how history is structured so I can remove it manually? What I'm trying to achieve is to be able to replace custom blot with image, but not include replacement in history. 
Here is what I'm doing:
1. Insert image using file selector
2. Insert custom  "preview image during upload" blot into Quill (let's call it "preview image")
3. Start uploading original image.
4. On upload finish, delete preview and insert image.

BUT, in Quill's history it looks like:
1. Insert preview
2. Delete preview
3. Insert image

and I expect it to look like:
1. insert image.

So I came up with idea:
1. Insert preview (included in history)
2. Upload finished
3. Delete preview (not included in history)
4. Insert proper image
5. Remove 1. step from history.

Reason why I'm doing this madness is to avoid showing preview again once upload is finished. Imagine situation when you select image and it starts uploading, than you "removes it and undo removal", or "insert image, undo, redo". There are so many cases when you may finished with preview image on screen, even though proper image should be showing, because upload already finished, but history sees it as two separate things. I hope you get my intentions here. 

**Version**:
1.3.6

**Comment by benbro** [comment]
The history module has [userOnly](https://quilljs.com/docs/modules/history/#useronly) option to ignore events that are not generated by the user:
https://github.com/quilljs/quill/blob/develop/modules/history.js#L15

You can [extend](https://quilljs.com/docs/modules/#extending) the history module and add your custom logic there:
```javascript
if (!this.options.userOnly || source === Quill.sources.USER) {
   if( // check if you want to ignore this specific delta) {
    this.transform(delta);
   } else {
     this.record(delta, oldDelta);
   }
} else {
   this.transform(delta);
}
```
