### ISSUE TITLE
Update on 2.0 and roadmap

### ISSUE THREAD

**Issue by chimon2000** [quilljs/quill#2460]
I read [The State of Quill and 2.0](https://medium.com/@jhchen/the-state-of-quill-and-2-0-fb38db7a59b9) last year, and I am very excited about this release.  I was wondering if there were anywhere to track the current state of 2.0?  

I was unable to find any milestones or labels associated with the next major release.  Considering this article is about a year & a half old I'd find this info valuable.

**Comment by JamesMcMahon** [comment]
See https://github.com/quilljs/quill/issues/2435

**Comment by JustinHallquist** [comment]
@jhchen just want to get a bump on this
any answer is a good answer and any help needed to get it pushed along would be welcome.
just need to know the layout and work needed to close it up.

**Comment by stephanvierkant** [comment]
Please close this issue in favor of #2435.

**Comment by heruan** [comment]
@benbro Good not to have duplicate issues, but while closing this how about dropping an update maybe?
