### ISSUE TITLE
Text always bold when pasted from Docs

### ISSUE THREAD

**Issue by nikolafilchev** [quilljs/quill#2462]
Text always bold when pasted from Docs, including pasting table data.

**Steps for Reproduction**

1. Visit https://codepen.io/nikolafilchev/pen/vvMOMG
2. Paste text from Docs

**Expected behavior**:
Maintained formatting text is pasted

**Actual behavior**:
Bold text is pasted

**Platforms**:
Everywhere that I tested

**Version**:
2.0.0-dev.3

**Comment by edhowler** [comment]
Is there any workaround for this? I'm having problems with this issue.

**Comment by edhowler** [comment]
I got it, here is what I did:
```
var Clipboard = Quill.import('modules/clipboard');
class Clipboard2 extends Clipboard {
    onCapturePaste(e) {
        if (e.defaultPrevented || !this.quill.isEnabled()) return;
        e.preventDefault();
        const range = this.quill.getSelection(true);
        if (range == null) return;
        let html = e.clipboardData.getData('text/html');
        html = html.replace('<b style="font-weight:normal;"', '<span"');
        const text = e.clipboardData.getData('text/plain');
        const files = Array.from(e.clipboardData.files || []);
        if (!html && files.length > 0) {
            this.quill.uploader.upload(range, files);
        }
        else {
            this.onPaste(range, { html, text });
        }
    }
}
window.Quill.register({'modules/clipboard': Clipboard2}, true);
```

**Comment by gs-mtripathi** [comment]
Does anybody have any update on this? I am still facing this issue in Firefox. Even on disabling formatting of pasted text, the content is bold. Can see the `strong` tag in Firefox. Looks fine in chrome, both with/without formatting.

**Comment by burmashave** [comment]
It's the same issue ProseMirror had in 2016 (since fixed):
https://github.com/ProseMirror/prosemirror/issues/459

For some reason, Google Docs uses a "<b style="font-weight:normal id="..."> wrapper around documents, which Firefox naturally interprets as bold. Haven't yet tried the fix by @edhowler but it looks like it would work.

**Comment by burmashave** [comment]
Here's the simple workaround I'm using for now:

```
let Delta = Quill.import('delta');

quill.clipboard.addMatcher('B', function(node, delta) {
    let val = true;
    if (node.style.fontWeight === 'normal') { val = false }
    return delta.compose(new Delta().retain(delta.length(), { bold: val }));
});
```
I'd prefer to make this a 'permanent' change in my default editor options so I don't have to add to every instance but I'm fairly new to Quill and haven't yet figured out how to do that. If I take this approach: 

```
    modules: {
        clipboard: {
            matchers: [
                ['B', boldMatcher]
            ]
```
... it's not clear to me from the docs how I access the matched element in boldMatcher().

**Comment by burmashave** [comment]
So I'm able to remove the bolding when pasting from Google Docs into Firefox with a simple matcher like this:

```
let Delta = Quill.import('delta');

quill.clipboard.addMatcher('B', function(node, delta) {
    let val = true;
    if (node.style.fontWeight === 'normal') { val = false; }
    return delta.compose(new Delta().retain(delta.length(), { bold: val }));
});
```
Unfortunately, it also removes the formatting from any **intentionally bolded text**. I don't understand the matchers & deltas well enough to know how to preserve that formatting, but maybe someone else here does...?
