### ISSUE TITLE
we want to integrate mathquilljs with virtual latex code editor

### ISSUE THREAD

**Issue by ngcgolf11** [quilljs/quill#2464]
we want to use mathquilljs with this solution and use virtual keyboard for latex formula please help me in this regard

**Comment by benbro** [comment]
You probably want to ask here:
https://github.com/mathquill/mathquill

**Comment by ngcgolf11** [comment]
@benbro  thanks alot for your reply. i already asked question there also we want to integrate mathquill as a module into quilljs we tried but it is not working
