### ISSUE TITLE
Adding a hyperlink to a file:// link results in a hyperlink to about:blank instead

### ISSUE THREAD

**Issue by jcreek** [quilljs/quill#2465]
The title says it all, it seems the url is being sanitised but file:// isn't being accepted. 

**Steps for Reproduction**

1. Added text in a quill instance. 
2. Try to add a hyperlink using file://....etc 

**Expected behavior**:
Create a hyperlink to the entered file link. 

**Actual behavior**:
Creates a link to about:blank. 

**Platforms**:

Seen on Windows 10, Chrome and Edge. 

**Version**:

Quill Editor v.1.3.6

**Comment by benbro** [comment]
The link format has a whitelist of safe formats:
https://github.com/quilljs/quill/blob/develop/formats/link.js#L30

You can extend the format but 'file://' is unsafe.

**Comment by jcreek** [comment]
Is there a guide somewhere for how to extend the format? I am unable to find one and need to enable this functionality for an internal system so will have to enable it unfortunately.

**Comment by benbro** [comment]
https://quilljs.com/guides/how-to-customize-quill/#customizing-attributors
