### ISSUE TITLE
My container blot gets cut out in a simple 2 nested blot example

### ISSUE THREAD

**Issue by andrei-cacio** [quilljs/quill#2470]
I have the following structure:

```html
<div id="editor">
    <section>
      <article>      
        <b>My article</b> 
      </article>
    </section>
</div>
```

And for my first step I only want Quill to see and render it as is. However, the `<section>` tag gets cut out. I have a codepen link below for a working example. 

I created a `Container` blot for the `<sction>` tag and a `Block` blot for the `<article>` tag. 

Should I manually append thie article tag inside a section tag using one of `insertBefore` or `create` function? I would have expected Quill to render the structure if the blots are properly registered. What am I missing?

Thanks a lot!
**Steps for Reproduction**

https://codepen.io/andrei-cacio/pen/mvbzqL

**Version**:

1.3.6

**Comment by onzag** [comment]
I found that same codepen at random and I was wondering why it wasn't working at all, thinking someone had finally managed to make it work.

Did you have any luck at all with that?

**Comment by andrei-cacio** [comment]
Nope, I gave up eventually. I started to read the whole codebase and got lost at some point and that was it.
