### ISSUE TITLE
There are no styles for content when I want to see.

### ISSUE THREAD

**Issue by ali-hasani** [quilljs/quill#2472]
what I have in editor :
![capture](https://user-images.githubusercontent.com/29506320/51525447-9c938100-1e45-11e9-84c9-92c37ba14931.PNG)

what i see in page :
![capture-1](https://user-images.githubusercontent.com/29506320/51525468-a917d980-1e45-11e9-91a8-933955e47cdf.PNG)

and this is my inspected HTML :
![capture-2](https://user-images.githubusercontent.com/29506320/51525501-b765f580-1e45-11e9-875d-fe94c85e75cb.PNG)

Apparently there are no styles or custom classes for elements created with the editor.
what is the problem please !
thanks a lot.

**Comment by benbro** [comment]
Questions about custom classes were asked many times.
You need to create custom class attributor and maybe extend the clipboard module.
Please ask questions on StackOverflow.
