### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by cjf** [quilljs/quill#2475]
Commit activity has really fallen off over the last few months.  Is this project dead?

https://github.com/quilljs/quill/graphs/commit-activity

**Comment by dalecosp** [comment]
Well, I *hope* not, as I'm integrating it into a project right now as a replacement for CKEditor.

**Comment by jhchen** [comment]
Quill is very much alive and well.

**Comment by austinbiggs** [comment]
I think what this conversation really highlights is that there is little to no communication from the maintainers about the status of v2. Would it be possible (apologies if this already exists) to get an official update on where things stand? 

Version 2.0 was first publicly announced on Sep. 21, 2017; over three years ago...

**Comment by sDaniel** [comment]
Last 1.3 release 9 Sep 2019 
@jhchen  I see you are still activly working but as I was considering quill for development I didn't get the impression there is still much activity by now or a plan for the future.

**Comment by maciej-zabielski** [comment]
I've spent a day evaluating this project and was quite convinced, but now when I started looking for a road-map and found one added three years ago.... where now we still lack tables support (https://github.com/quilljs/quill/issues/117), lack of clear idea on how to store and display content outside of the viewer.... (Delta converters). 

I think that @jhchen has moved his interest to Slab - so all the goodies are held in there? :) Looking at the activity of the project seems very dead now at least in the public domain:
https://github.com/quilljs/quill/graphs/contributors?from=2012-07-29&to=2020-12-21&type=c
