### ISSUE TITLE
why selected option in template became clear？

### ISSUE THREAD

**Issue by nightost** [quilljs/quill#2476]
why selected option in template became the other style clear button?

**Steps for Reproduction**

```
<select class="ql-size">
            <option value="12px"></option>
            <option value="14px"></option>
            <option value="15px"></option>
            <option value="16px"></option>
            <option value="17px"></option>
            <option value="18px"></option>
            <option selected value="20px"></option>
            <option value="24px"></option>
          </select>
```

**Expected behavior**:
font-size 20px become default and has correct functionality

**Actual behavior**:
font-size 20px become default but has incorrect functionality(clear font-size style)

**Platforms**:
all

**Version**:
1.3.6

**Comment by benbro** [comment]
You need to add all sizes to the format whitelist:
https://github.com/quilljs/quill/blob/develop/formats/size.js#L9

Similar example:
https://quilljs.com/guides/how-to-customize-quill/#customizing-attributors
