### ISSUE TITLE
Keyboard bindings not working on android chrome

### ISSUE THREAD

**Issue by m4rkmckenna** [quilljs/quill#2477]
keyboard bindings do not fire on android chrome
For example [this](https://github.com/quilljs/quill/blob/develop/modules/keyboard.js#L364) default binding 

**Steps for Reproduction**

1. Visit [https://quilljs.com/playground/](quill js playground) using chrome on android
2. Input `- `

**Expected behavior**:
Expect `list autofill` binding to fire and add a list to the input

**Actual behavior**:
`list autofill` does not fire input remains the same

**Platforms**:
OS Android 
Browser Chrome (71.0.x)
**note** Webview for newer android versions also use chrome so this is also present there

**Version**:
1.3.6

**Comment by DmitrySkripkin** [comment]
The problem is Gboard. [Issue discussion](https://bugs.chromium.org/p/chromium/issues/detail?id=118639).
P.S. This is a huge pain. Quill relies on keyboard bindings, but some input sources have own opinion on how input events should work.

**Comment by Intrflex** [comment]
These bugs still very much exist even with quil 2.0
