### ISSUE TITLE
typescript leak Quill sources

### ISSUE THREAD

**Issue by ycjcl868** [quilljs/quill#2480]
![image](https://user-images.githubusercontent.com/13595509/51917364-5d06ff00-241a-11e9-9ec4-1b4ecd285089.png)

**Comment by benbro** [comment]
What do you mean by leak?
Anyway, [Quill.sources](https://github.com/quilljs/quill/blob/develop/core/emitter.js#L57) are just strings. You can use 'user' instead and it will work fine.
