### ISSUE TITLE
inconsistent module loading order

### ISSUE THREAD

**Issue by FranckFreiburger** [quilljs/quill#2481]
**Steps for Reproduction**

1. open https://jsfiddle.net/ck1wt84h/4/
2. in the dev console: `quill.min.js:7 quill:toolbar ignoring attaching to nonexistent format test`

**Expected behavior**:
I expect to register all my module and then define the toolbar at Quill construction.

**Actual behavior**:
Because of the [module loading order](https://github.com/quilljs/quill/blob/d4a4f02f587a366adb9a00f134705027eb76900c/core/quill.js#L490), `toolbar` is loaded **before** my `test` module (quill:toolbar ignoring attaching to nonexistent format test).
Then the 'test' handler is not set.

**Version**:
Quill v1.3.6

note that quill-emoji also has a [similar issue](https://github.com/contentco/quill-emoji/blob/master/README.md#webpackes6) and are forced to use the following workaround: `handlers: {'emoji': function() {}}`

**Comment by sb8244** [comment]
This is a very confusing issue for people that are writing extensions. I spun my wheels for a long time because "quill-image-uploader" works just fine, but that's because it redefines an already existing handler (`image`).
