### ISSUE TITLE
Is it possible to customize the dialog showed when link button is pushed in toolbar (snow theme) ?

### ISSUE THREAD

**Issue by EnricoMassoneDeltatre** [quilljs/quill#2485]
Hi all,

our need is to customize the dialog showed when editing a link in the text editor (we are using the snow theme). 

This is the current look and feel:

![image](https://user-images.githubusercontent.com/29275408/52071166-b68a3d80-2582-11e9-94a0-6798de264073.png)

We would like to change the HTML markup of the dialog so that we can enter both the link text and any other attribute of the link (e.g.: the target attribute). 

Is it possible to do so ? Should we extend the snow link and rebuild the quill.js source code ? Is there a way to do this customization without recompiling the quill.js source code ?

**Comment by nguyendinhtuonguyen** [comment]
How we can customize the inline editing dialog?

**Comment by benbro** [comment]
Please ask questions on StackOverflow.

You can extend the tooltip and the theme.
The SnowTooltip extends the BaseTooltip:
https://github.com/quilljs/quill/blob/develop/themes/snow.js#L15

The snow theme creates the tooltip here:
https://github.com/quilljs/quill/blob/develop/themes/snow.js#L95

Note that the same tooltip is used for links, images, videos and formula.

**Comment by capaj** [comment]
quill should really allow users to choose the target attribute themselves. Almost every other editor has this feature.

**Comment by kozfelipe** [comment]
https://stackoverflow.com/questions/50129438/creating-a-quill-js-theme

**Comment by OleksandrFomin** [comment]
> Hi all,
> 
> our need is to customize the dialog showed when editing a link in the text editor (we are using the snow theme).
> 
> This is the current look and feel:
> 
> ![image](https://user-images.githubusercontent.com/29275408/52071166-b68a3d80-2582-11e9-94a0-6798de264073.png)
> 
> We would like to change the HTML markup of the dialog so that we can enter both the link text and any other attribute of the link (e.g.: the target attribute).
> 
> Is it possible to do so ? Should we extend the snow link and rebuild the quill.js source code ? Is there a way to do this customization without recompiling the quill.js source code ?

Did you end up extending the default theme or is there a better way? I'm having the exact same issue right now

**Comment by capaj** [comment]
@OleksandrFomin in the end I forked quill and extended the default theme:
https://github.com/capaj/quill/tree/add-target-checkbox, see last 2 commits, maybe you can cherry pick them to your project
