### ISSUE TITLE
Is there a way to override the default picker?

### ISSUE THREAD

**Issue by jklotz** [quilljs/quill#2486]
I am looking to override the default picker but it doesn't appear you can override ui modules. Currently there is only support for overwriting blots and formats. Is there a reason we can't override the default picker?
`
static register(path, target, overwrite = false) {

    if (typeof path !== 'string') {
      const name = path.attrName || path.blotName;
      if (typeof name === 'string') {
        // register(Blot | Attributor, overwrite)
        this.register(`formats/${name}`, path, target);
      } else {
        Object.keys(path).forEach(key => {
          this.register(key, path[key], target);
        });
      }
    } else {
      if (this.imports[path] != null && !overwrite) {
        debug.warn(`Overwriting ${path} with`, target);
      }
      this.imports[path] = target;
      if ((path.startsWith('blots/') || path.startsWith('formats/')) && target.blotName !== 'abstract') {
        globalRegistry.register(target);
      }
      if (typeof target.register === 'function') {
        target.register(globalRegistry);
      }
    }
  }`

**Comment by benbro** [comment]
The picker is imported inside the [theme](https://github.com/quilljs/quill/blob/fd400525d551315b6fa9a4d4783e1c7dbad57827/themes/base.js#L4).

You can try to create a custom theme and define your own picker.
