### ISSUE TITLE
Deselecting text using arrow key moves incorrectly moves the cursor

### ISSUE THREAD

**Issue by probablykasper** [quilljs/quill#2488]
**Steps for Reproduction**
1. Visit https://quilljs.com/
2. Put your cursor at the end of the first paragraph
3. Press command+shift+leftarrow to select the whole line
4. Press rightarrow to deselect all your text

The steps seem to work for any line that doesn't wrap to the next line. To select a line:
1. Visit https://quilljs.com/
2. Click to the right of the second line, so that the cursor ends up being placed to the right of the line, like this (you cannot achieve this result by moving there with the arrow keys):
![image](https://user-images.githubusercontent.com/11315492/52150673-fdeef780-2670-11e9-8da0-e02d3a631f2c.png)
3. Press command+shift+leftarrow to select the whole line
4. Press rightarrow to deselect all your text

**Expected behaviour:**
Step 4 should put the cursor at the end of the line.

**Actual behaviour:**
Step 4 moves the cursor the the line below.

**Platforms**:
macOS 10.13.6
Chrome 71.0.3578.98

**Version**:
Quill 1.3

**Comment by luin** [comment]
Merging to https://github.com/quilljs/quill/issues/2487.
