### ISSUE TITLE
Loading custom embeds

### ISSUE THREAD

**Issue by alexnoodle** [quilljs/quill#2494]
Hi everyone,
I'm attempting to add a button in Quill that can add Ruby html tags to selected blocks of text for language learning purposes. Currently the button adds the html tags to the selected block just fine and when the JSON is saved the information about the tags are as well. However, when the file is loaded back into Quill the block with the applied tag gets pasted as [object Object] after editor.setContents(loadedFile) is called. Everything else gets loaded in fine.

Is there a way to stop Quill from interpreting html inside an embed as an object and to just place it back in?

**Steps for Reproduction**

The construction of the ruby embed and attempt to whitelist the ruby html tag
```
var Embed = Quill.import('blots/embed');
    Embed.whitelist = ['ruby', 'rt'];
    class QuillRuby extends Embed {
        static create(value, top, body) {
            var node = super.create(value);
            node.setAttribute('contenteditable', false);
            node.setAttribute('body', value);
            node.innerHTML = value;
            return node;
        }
        static value(node){
            return {
                body: node.getAttribute('body'),
            };
        }
    }
```

How the constructor gets called
`editor.insertEmbed(range.index, 'ruby', '<ruby>' + top + '<rt>' + body + '</rt></ruby>');
`
Where top is the characters that go above the main text and body is the main text

The custom embed is properly created and registered with Quill as far as I can tell
```
QuillRuby.blotName = 'ruby';
QuillRuby.className = 'quill-ruby';
QuillRuby.tagName = 'ruby';

Quill.register({'formats/ruby': QuillRuby}, true);
```

**Expected behavior**:
It's expected that reloading saved JSON, such as
`{"insert":{"ruby":{"body":"/\"<ruby>\ntest<rt>test above</rt></ruby>/\""}}}`
would place 'test above' above 'test' as that's what appears when the embed is first created and the requisite data is saved properly in the JSON

**Actual behavior**:
The JSON is set as [object Object] in the editor and if you then getContents the JSON
`{"insert":{"ruby":{"body":"[object Object]"}}}`
is returned

**Platforms**:

This has only been tested on Chrome running on MacOs so far

**Version**:

This is using Quill 1.3.6

It's entirely possible I'm not aware of something basic in Quill and any information would be helpful thanks!

**Comment by lukevp** [comment]
@alexnoodle  did you ever figure anything out with this? It sounds based on [object Object] that quill is calling toString() on your class and you haven't defined a way to serialize and deserialize your data.
