### ISSUE TITLE
Do not combine different edit "types" into the same delta

### ISSUE THREAD

**Issue by poshest** [quilljs/quill#2495]
Make an edit and then, in quick succession paste some other text.  A single undo after that causes _both_ the edit and the paste to be undone.

I understand that edits are grouped into deltas on a time basis, but I don't think that's the right UX.  I'm used to the Google Docs, Word, Gmail editor, and browser textarea behaviour, all of which separate the paste edit from other keyboard ones (ie would require two undos to return to the original state, one for the paste and one for the first edit).

Typing one word and another word _can_ be combined into the same delta, because they're all just typing. However, grouping different "types" of edits together is non-standard UX and feels weird every time I encounter them in Quill (which is often).

For example, typing, and then making that edited paragraph a bulleted paragraph should be two separate deltas. I would not expect a single undo to undo both of these actions. 

Also, typing, then deleting, then typing some more should be 3 separate deltas no matter how fast they proceed each other in time.

**Comment by benbro** [comment]
Did you try to use [cutoff](https://quilljs.com/docs/modules/history/#cutoff-experimental)?

**Comment by poshest** [comment]
@benbro, no, I had no idea that existed. Thanks very much for alerting me to it. :) At least there's some path to achieving my desired outcome.  I will certainly give it a go. 

Have you used it?  What was your experience?

Meantime, this is quite a low level method, and there'll need to be quite a bit of code written around it to actually achieve what I think most people would expect to be made default behaviour.

**Comment by benbro** [comment]
You can try to [extend](https://quilljs.com/docs/modules/#extending) the history module and make it work locally.
The condition to decide whether to compose the change with the previous undo change is [here](https://github.com/quilljs/quill/blob/develop/modules/history.js#L65).
```javascript
if (
  this.lastRecorded + this.options.delay > timestamp &&
  this.stack.undo.length > 0
) {
  const delta = this.stack.undo.pop();
  undoDelta = undoDelta.compose(delta);
} else {
  this.lastRecorded = timestamp;
}
```
You can add a check that compares the op type in the current delta with the previous delta.

**Comment by poshest** [comment]
True, good steer, thanks :)  I've moved on to other work, but when I return
quill stuff, I'll try it and report back.
