### ISSUE TITLE
Replace class names with corresponding names from Bulma.io?

### ISSUE THREAD

**Issue by gulbaek** [quilljs/quill#2496]
I'm building a cms system, where I use the Bulma css framework https://bulma.io/

Would it be possible to replace the class names used in quill with the corresponding once from Bulma?

e.g.
If I in quill center align some text, my html result would look something like this.
`<p class="ql-align-center">Text</p>`

I would like it to look like this instead, so it uses the class names from Bulma
`<p class="has-text-centered">Text</p>`

https://bulma.io/documentation/modifiers/typography-helpers/

I know it's probably a manual and time-consuming task, but that's okay.

**Comment by benbro** [comment]
Extend the Blots:
https://quilljs.com/guides/how-to-customize-quill/#extending-blots
https://github.com/quilljs/quill/blob/develop/formats/align.js#L9
