### ISSUE TITLE
selecting and replacing a series of spans gives null range crash, with corrupted content

### ISSUE THREAD

**Issue by rblaa** [quilljs/quill#2498]
When selecting and deleting a range of spans with new text, there is a null pointer crash that loses the cursor, leaves the html content slightly corrupted.

**Steps for Reproduction**

1. Edit an html fragment with spans like:
```html
<p><strong>Project Status</strong>: <span style="color: green">Green</span> / <span style="color: yellow">Yellow</span> / <span style="color: red">Red</span>
</p>
```
2. Select the spans, e.g. from "Green" till the end of line at "Red", start typing some replacement text, e.g. say "ok!". 

**Expected behavior**:
Green / Yellow / Red disappears and is replaced by the new text, giving, e.g.
```html
<p><strong>Project Status</strong>: ok!
</p>
```

**Actual behavior**:
* Cursor disappears
* Clicking with the mouse restores the cursor, newly typed text is in bold
* Often I cannot unbold the "Project Status" part
* Often find corrupted content, e.g. an extra `</strong>` tag that messes up further display of the html content.

**Platforms**:
Mac OS 10.14.2

**Version**:
Quill 1.3.6

**Comment by luin** [comment]
Fixed in https://github.com/quilljs/quill/pull/3807. Feel free to let me know if there is anything missing. Closing
