### ISSUE TITLE
Inline editor with white-space nowrap partially works in Firefox

### ISSUE THREAD

**Issue by andrei-cacio** [quilljs/quill#2499]
I have a use case where I need an inline rich text editor which doesn't wrap when the cursor reaches the end of the element and the width automatically increases as you type. I have read in other issues that it is recommended to include the Quill core CSS file, however with `white-space: pre-wrap;` you can't achieve inline editing. 

With `white-space: nowrap;` you can achieve that but in Firefox space typing is partly working. If you start typing spaces at the end of the last character it works fine. However, if you move the cursor at the end of the witdth (CMD/Ctrl + right arrow) the cursor remains stuck no matter how much you hit the space bar. If you move the cursor one character to the left and then start hitting space again, it works.

Is there anyway to get around this?  @jhchen 

Thank you kindly and awesome work on Quill!

**Steps for Reproduction**

JSFiddle: https://jsfiddle.net/sgv5f39r/1/

**Expected behavior**:
You should be able to type multiple spaces

**Actual behavior**:
The spaces are collapsed in some situations (when you force the cursor at the end of the element)

**Platforms**:
MacOS Mojave, : Firefox 64

Include browser, operating system and respective versions

**Version**: 
1.3.6

**Comment by brgaulin** [comment]
I'm seeing this same behavior in Firefox, even without the white-space: nowrap
https://jsfiddle.net/91anp5u7/1/

Not seeing this issue on the quill playground.

**Platforms:**
MacOS Mojave, Firefox 68.0.1
Windows 10, Firefox 68.0
**Version:**
1.3.6
