### ISSUE TITLE
Setting the link format before focusing the editor causes the ql-blank class to not be removed

### ISSUE THREAD

**Issue by saw** [quilljs/quill#2502]
If you call the api to set the "link" format *before* focusing the editor, the `ql-blank` class is not cleared.

**Steps for Reproduction**

1. Visit https://codepen.io/saw-1473371988/pen/gqzvYm
2. Begin typing in the editor

**Actual behavior**:
Placeholder disappears 

**Platforms**:

Tested in chrome

**Version**:

1.3.6

**Comment by zengyuangai** [comment]
No area selected
