### ISSUE TITLE
Video Not popping up

### ISSUE THREAD

**Issue by tpitout** [quilljs/quill#2503]
Hi, When I include ["video"] in my toolbar among ["Image"] and ["Code-Block"] , both code-block and Image work and perform well except for video, It use to pop up a input for the URL and it worked great, but all of the sudden its not popping up the URL input anymore.

Im using CDN

**Comment by benbro** [comment]
Can you reproduce here?
https://quilljs.com/

Can you fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) and reproduce?
