### ISSUE TITLE
disable ql-list ordered

### ISSUE THREAD

**Issue by jacky007wang** [quilljs/quill#2504]
When I type 1. and space, the text will be ordered list, how to disable it.

<img width="230" alt="2019-02-12 9 48 14" src="https://user-images.githubusercontent.com/2283866/52639778-fd2b5080-2f0f-11e9-8483-4baccacfa5f9.png">

**Comment by DmitrySkripkin** [comment]
There is default keyboard binding [keyboard.js:364](https://github.com/quilljs/quill/blob/develop/modules/keyboard.js#L364). You have to override it.

**Comment by benbro** [comment]
Thanks for the answer DmitrySkripkin.
