### ISSUE TITLE
Trying to open a added link without http:// or https://

### ISSUE THREAD

**Issue by caiopardal** [quilljs/quill#2505]
**Steps for Reproduction**

1. Visit https://quilljs.com/playground/
2. Insert the add link option (['link'] inside toolbar)
3. Add a link without http:// or https:// (Eg. www.google.com)
4. Try to open the link

**Expected behavior**:
Open the added link on another tab

**Actual behavior**:
It tries to open the link inside the actual link that you're using

**Platforms**:

All browsers

**Comment by JulianoGTZ** [comment]
+1

**Comment by benbro** [comment]
I can't reproduce.
The [Link](https://github.com/quilljs/quill/blob/develop/formats/link.js#L7) format sets target="_blank" on the a element so it should open in a new tab.
> <a href="www.google.com" target="_blank">google</a>

**Comment by ramprakashram** [comment]
I am still having the problem, when i click to open a url, it opens in a new tab, but it prepends to existing source url.
