### ISSUE TITLE
Bundle Issue when using resize-image

### ISSUE THREAD

**Issue by paolog22** [quilljs/quill#2506]
double entry on the bundle when using 

> quill-image-resize-module

result of bundle analyzer:

![image](https://user-images.githubusercontent.com/12680745/52684805-73689b00-2f82-11e9-9831-6283624e351a.png)

**Steps for Reproduction**

Code to Reproduce
![image](https://user-images.githubusercontent.com/12680745/52684940-df4b0380-2f82-11e9-97aa-a095093af0c0.png)

**Expected behavior**:

**Actual behavior**:

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
quill-image-resize-module is third part module. Please ask in there.
