### ISSUE TITLE
Chrome like spaces (&nbsp; ) get trimmed out when added after or before an element

### ISSUE THREAD

**Issue by andrei-cacio** [quilljs/quill#2507]
It seems that when contenteditable is active on a node, Chrome deals with spaces by adding `&nbsp;` followed by a normal space. However, if you add those spaces at the start or at the end of a paragraph for example:

```html
<p>&nbsp; &nbsp; Lorem</p>
```

When initialising Quill the rendered result will be:

```html
<p>&nbsp;&nbsp;Lorem</p>
```

The spaces in between are trimmed out. If you have a dynamic element which can switch between edit mode and read only mode there will always be a small flick in UX when the text moves a bit to the left if there are trailing spaces.

I have found the [piece of code](https://github.com/quilljs/quill/blob/1.3.6/modules/clipboard.js#L337) which deals with the space trimming. It seems to be solving a Word copy paste case. However, if I remove the piece of code and try some simple Lorem ipsum copy paste examples from Word it seems to work fine. How safe is to go on without that piece of code in Quill?

**Steps for Reproduction**

https://jsfiddle.net/xvzore2k/1/
Also, I have written a failed unit test on a separate branch: https://github.com/andrei-cacio/quill/blob/chrome-spacing-issue/test/unit/modules/clipboard.js#L75

**Expected behavior**:
The spaces should be left as they are

**Actual behavior**:

Some spaces get trimmed

**Platforms**:

Chrome 71 MacOS Mojave

**Version**:

1.3.6

**Comment by snovakovic** [comment]
@andrei-cacio I'm currently running in same issue as you. Have you mange to work around it?

**Comment by andrei-cacio** [comment]
well, it depends on your use-case. I ended up removing the logic altogether.

The easiest way is to include the CSS file that Quill comes with or add `pre` or `pre-wrap` white spacing on your root editor node. However (if this still doesn't do the trick) there is another catch: besides the block of code I mentioned above, there is another piece of code that messes with the spaces: https://github.com/quilljs/quill/blob/1.3.6/core/quill.js#L100. This code is executed when you initialize Quill and enter edit mode. Here the white space is hardcoded to `normal` and the clipboard logic will remove the spaces mention in the issue. You should reproduce this if you initialize Quill with a piece of text already containing chrome-like spaces and you should see them getting trimmed out.

Hope this helps.
