### ISSUE TITLE
Link text gets overwritten on copy-paste

### ISSUE THREAD

**Issue by rogerraa** [quilljs/quill#2508]
Steps to recreate:

Goto: https://codepen.io/anon/pen/ZwMOLN

1. Type a random word
2. Highlight it
3. Click the Link button in the toolbar
4. Enter text "abc123", and hit save
5. Copy the word
6. Paste anywhere
7. View the new link url you just pasted

Link will now have a url of whatever page you are currently on + abc123. Only happens if link text is not an actual url. This makes making #hash anchor links impossible to maintain.

**Comment by benbro** [comment]
The [Link](https://github.com/quilljs/quill/blob/develop/formats/link.js#L6) format set the value to the element href after sensitization.
You can enter "#abc123" or [extend](https://quilljs.com/guides/how-to-customize-quill/#extending-blots) the Link format with your custom logic.
