### ISSUE TITLE
ngModel not update by insertText

### ISSUE THREAD

**Issue by zabihy** [quilljs/quill#2509]
I'm using Quill in PrimeNG and this is the method. but the ngModel doesn't update when using insertText but when I add some text to the editor by hand, ngModel updates.
```
    pushImageToEditor(url: string) {
        const range = this.editor.getSelection(true);
        const index = range.index + range.length;
        this.editor.insertText(range.index, `[image]src=${url}[image]`, 'normal', true);
    }
```

**Comment by mizuna13** [comment]
Hi,
insertText has 3 parameters. The last one is the Source. You should call the method using source: "user" and the ngModel will update:
this.editor.insertText(range.index, `[image]src=${url}[image]`, 'user');
