### ISSUE TITLE
Old values for text-change events

### ISSUE THREAD

**Issue by mmacfadden** [quilljs/quill#251]
Currently the text-change event only provides you with deltas.  The operations contained essentially contain new values.  This applies specifically to retains and deletes.  When text is deleted, the operation simply contains the number of characters to delete.  For many applications it is extremely important to now what was deleted.  By the time the text-changed event gets to the users, the original data has already been removed from the editor and there does not seem to be a good way to get it.

Likewise, with retains, when style is being changed, there does not seem to be a way to determine what the style was before hand.  The only workaround to this point seems to be to:

1. Keep a second copy of the document (as a delta).
2. Receive and inspect the events.
3. Example the copy of the document to get the old values.
4. Apply the changes to the copy of the document.

This is fairly clunky and eats up memory.  Is it possible to either A) provide the old values in the operations, or B) allow the user to listen to events before the document has been modified?

**Comment by jhchen** [comment]
text-change event now reports the old document in the 1.0 [beta](http://beta.quilljs.com/) release
