### ISSUE TITLE
how to add attribution into list and image

### ISSUE THREAD

**Issue by lyq027** [quilljs/quill#2512]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

how to add attribution into list and image?
i have a vue application. i want to add word-wrap into ul>li attribution ，please help me。

**Expected behavior**:

**Actual behavior**:

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
Please ask questions on StackOverflow.
It's not clear what you are trying to do and you didn't fill the issue template.
