### ISSUE TITLE
How to add custom fonts through the toolbar options array?

### ISSUE THREAD

**Issue by thealexcons** [quilljs/quill#2513]
I would like to know how to add custom fonts (font families) via the toolbar options array. I want to avoid defining the toolbar controls using HTML elements.

The code below is taken from the [seventh example on this page](https://quilljs.com/docs/modules/toolbar/).
```
var toolbarOptions = [
  ['bold', 'italic', 'underline', 'strike'],        
  ['blockquote', 'code-block'],

  [{ 'header': 1 }, { 'header': 2 }],               
  [{ 'list': 'ordered'}, { 'list': 'bullet' }],
  [{ 'script': 'sub'}, { 'script': 'super' }],      
  [{ 'indent': '-1'}, { 'indent': '+1' }],          
  [{ 'direction': 'rtl' }],                       

  [{ 'size': ['small', false, 'large', 'huge'] }],  
  [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

  [{ 'color': [] }, { 'background': [] }],          
  [{ 'font': [] }],                             // Here, how do I specify custom font families??
  [{ 'align': [] }],

];

var quill = new Quill('#editor', {
  modules: {
    toolbar: toolbarOptions
  },
  theme: 'snow'
});
```
I'm guessing I need to include the CSS from Google fonts for each font too, right?

This is the code above in action: [https://codepen.io/anon/pen/VgVZMg](https://codepen.io/anon/pen/VgVZMg)

**Version**:

Quill version is 1.3.6

**Comment by benbro** [comment]
Example:
https://quilljs.com/playground/#custom-fonts

**Comment by sdraper69** [comment]
@benbro that uses a custom html toolbar which is what the OP asked not to do
