### ISSUE TITLE
Quill editor from and to markdown

### ISSUE THREAD

**Issue by Doidel** [quilljs/quill#2514]
I just wanted to share the solution I use for Quill with markdown. I've used a ton of different markdown editors and solutions (editor.md, tui editor, stackedit...) but then I found this [codepen by a guy named "Lee Robert"](https://codepen.io/voziv/pen/rmpVZb/). Those top-notch markdown converters together with Quill work very smoothly.
Basically, he uses the markdown-it library to render markdown to html, then pastes the result to Quill. And on saving he uses the to-markdown library to convert the `quill.container.firstChild.innerHTML` to markdown.

**Comment by silashuereca** [comment]
Thank you for posting this! I'm using this method now and it works so well :)
