### ISSUE TITLE
How I can add space between the rich content?

### ISSUE THREAD

**Issue by satyapendem** [quilljs/quill#2517]
Hi,

I want to make some change related to quill shortcuts. If I have a string like **Quilljs** if select **uill** and hit `cmd+b` it will convert to bold but I want to add space between the contents. It will be like **Q uill js** and uill will be in bold. How I can add the space and set the contents in Quill. Please help. 

**Expected behavior**:

**Actual behavior**:

**Platforms**:
Mac
Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
You can add [keyboard handler](https://quilljs.com/docs/modules/keyboard/#key-bindings) and use [insertText](https://quilljs.com/docs/api/#inserttext) to insert a space.
Please use StackOverflow for questions.
