### ISSUE TITLE
Text cannot be drag and dropped when content is formatted

### ISSUE THREAD

**Issue by swymmwys** [quilljs/quill#2518]
**Steps for Reproduction**

1. See gif with steps to reproduce https://ibb.co/gmkq7SG
2. Example https://codepen.io/swymmwys/pen/PVvRJy

Main problem is when text in editor already formatted you can't drop text into formatted area. 
Exception occured: ```addRange(): The given range isn't in document.```

**Expected behavior**:
Text is pasted

**Actual behavior**:
Text isn't pasted

**Platforms**:
Chrome (any)

**Version**:
Latest Quill

**Comment by evious** [comment]
The problem is actually how much your text has the color style property: xxxxxx
