### ISSUE TITLE
Cannot deselect text with mouse click (Chrome)

### ISSUE THREAD

**Issue by ddtobiasz** [quilljs/quill#2519]
When I select a block of text, I'm no longer able to deselect it by clicking my mouse if I click on the selection.  If I select all, then I'm entirely unable to deselect unless I use the arrow keys to move the cursor.

**Steps for Reproduction**
1. From what I've tested, can only reproduce on Windows, Chrome (72.0.3626.109)
2. Go to https://quilljs.com/playground/
3. Type into the field and select all of it
4. Using the mouse, try to click somewhere in the field to deselect (either on the text or in whitespace)

**Expected behavior**:
The text should deselect and the cursor should appear where you clicked

**Actual behavior**:
The text stays selected

**Platforms**:
Windows, Chrome (72.0.3626.109)

**Version**:
Quill Editor v1.3.6

**Comment by shreshthmohan** [comment]
+1

I can try and make a fix if someone can point me in the right direction.

**Comment by shreshthmohan** [comment]
This issue seems to have been partially resolved and seems like an issue with Chrome. Works much better on:

**Platforms:**
MacOS Mojave Chrome (75.0.3770.100)

**Version:** 
Quill Editor v1.3.6

**Comment by DavidGP** [comment]
I've been having this problem for months, and it's driving me mad. Latest Google Chrome on Windows 10.

**Comment by DavidGP** [comment]
Is there at least a thread somewhere to share this pain with more people? I can't believe we three should be the only ones noticing this issue that drives me mad every day all day long.

**Comment by mmseng** [comment]
I've also been noticing this for several months now. However it seems to be intermittent and I've not been able to pinpoint whether it's a Chrome issue, or possibly a hardware/OS issue. It seems to happen most often in Chrome, and I haven't kept track well enough to remember whether I've ever seen it happen in another application. However Chrome is easily the single most-used app for me, as far as selection of text and general mouse activity.

**Comment by abhishekti7** [comment]
Any updates on this? 

I have been facing this issue for quite some time now. This seems like a browser issue. have checked on google chrome and brave browser. Works find on Firefox.
