### ISSUE TITLE
is there a mailing list to ask questions?

### ISSUE THREAD

**Issue by rpg-hub** [quilljs/quill#2522]
i looked all over your website but did not see a mailing list address.

So, I have posted my question here: https://stackoverflow.com/questions/54835375/how-to-edit-and-save-my-html-file-using-quill

===here re-print/asked=======
So I have a text file on my web server, which i display using <pre> tag in browser.

I need to edit the file every once in a while, as of now i have to go back to CLI and vi the file.

I want to use some WYSISYG editor to do it online. I was considering CKEditor, but found Quill too. Quill looked lige to me.

I am confused how can I use it to edit the displayed text file in browser and then save the contents back to the text file in server. I also want to format the text in file using WYSISWYG editor (like highlighting, bold, insert pictures etc.).

I want to save a text and HTML version of file in the server, just in case web-server/web-site is not functioning, I would still be able to use data thru CLI. I felt i need to store output of this tool in db in the backend??

any suggestion is welcome.

Thanks.

**Comment by benbro** [comment]
StackOverflow is the right place for questions.
