### ISSUE TITLE
Does anyone added quill-tables npm into project?

### ISSUE THREAD

**Issue by MarekDzw** [quilljs/quill#2523]
Hi,
I tried to add quill-table npm to my project without success.

```
const quillTable = require('quill-table');
 
Quill.register(quillTable.TableCell);
Quill.register(quillTable.TableRow);
Quill.register(quillTable.Table);
Quill.register(quillTable.Contain);
Quill.register('modules/table', quillTable.TableModule);
```

This doesn't work for me. 
Does anyone have complete setup for this? I don't want the demo from website.

**Comment by dmboucher** [comment]
I'm struggling with this as well.  Any help/guidance would be appreciated!
