### ISSUE TITLE
getting current quill instance from handler

### ISSUE THREAD

**Issue by bagelstudio** [quilljs/quill#2525]
im using a dynamically generated list of quill editors, structured in an array.
like so:

```
      quill[instance-no.] = new Quill(`#${id}`, {
        modules: {
          toolbar: toolbarOptions,
        },
        theme: 'snow'
      });

```
in other words there may be a few instances of quill on the page. in addition i am using a custom handler for the image upload

```
      quill[instance-no.].getModule('toolbar').addHandler('image', () => {
        myImageHandler();
      });

```

the problem is that there is not way for me to distinguish from which instance the call was made.

**Comment by bagelstudio** [comment]
ok, so for anyone interested i was able to get the current instance with the by looping through the instance numbers and checking if  hasfocus() is true

**Comment by benbro** [comment]
https://quilljs.com/docs/modules/toolbar/#handlers
> Handler functions will be bound to the toolbar (so using this will refer to the toolbar instance)
