### ISSUE TITLE
how can i insert a \n at quill2.0 table cell?

### ISSUE THREAD

**Issue by hakonleung** [quilljs/quill#2528]
**Discription**:
 using table module, there is only a table in editor area

**Executing**:
````javascript
quill.updateContents({ops: [{
insert: '\n'
}]})
````
**Expected behavior**:
first cell should be
````html
<table><tbody><tr><td>/*first cell*/<p><br></p></td></tr></tbody></table>
````

**Actual behavior**:
````html
<p><br></p>
````
now content`s html is
````html
<p><br></p>
<table><tbody><tr><td>/*first cell*/</td></tr></tbody></table>
````
**how can i insert a \n at table cell?**

**Version**:
v2.0.0-dev

**Comment by benbro** [comment]
The [dev release of tables](https://github.com/quilljs/quill/issues/117#issuecomment-401713569) doesn't support multiple lines per cell:
> Does not allow multiple lines per cell or block level embeds (video) in cells

Even if it did, you should probably add {retain: X} op before your insert op.

**Comment by hakonleung** [comment]
> The [dev release of tables](https://github.com/quilljs/quill/issues/117#issuecomment-401713569) doesn't support multiple lines per cell:
> 
> > Does not allow multiple lines per cell or block level embeds (video) in cells
> 
> Even if it did, you should probably add {retain: X} op before your insert op.

thx, btw i just wanna insert \n at index 0.
