### ISSUE TITLE
The order of attributes changes after setting html content

### ISSUE THREAD

**Issue by KwintenP** [quilljs/quill#2530]
**Steps for Reproduction**

1. Open this codepen: https://codepen.io/kwintenp/pen/bZwXPd?=true (with some minimal config)
2. Fill in the word 'test'
3. Select the word and make it red first
4. Make it 'small'
5. Open the console and see the following logged out (because of the text-change event listener): 
```<p><span style="color: rgb(230, 0, 0);" class="ql-size-small">test</span></p>```
The style attribute stands before the class attribute.
6. Scroll to the bottom of the javascript in codepen
7. Fill in the string that was logged to the console inside the ```quill.clipboard.dangerouslyPasteHTML``` function.
8. Check the console and see the following logged out (because of the text-change event)
```<p><span class="ql-size-small" style="color: rgb(230, 0, 0);">test</span></p>```

**Expected behavior**:
The order of the class and style attributes is kept as passed to ```quill.clipboard.dangerouslyPasteHTML```
OR
The order generated in step 5 is already first 'class' then 'style' attribute.

**Actual behavior**:
The order of class and style has changed.
**Platforms**:
Chrome Version 72.0.3626.109 (Official Build) (64-bit), OS X 10.13.6 (17G2112)

**Version**:
1.3.6

**Comment by benbro** [comment]
You generally shouldn't rely on the order of HTML attributes like you shouldn't rely on key order in a Javascript object.
When working with Quill you should use the Delta format.

**Comment by mix3d** [comment]
I disagree with this answer. I am in a project where I need to know if the value has changed. Pasting the html input with one attribute order, (the output of a different instance of Quill) causes the order to be different, which means I can't equality check further up the chain. 

Quill's dangerouslyPasteHTML should be deterministic. Instead, I get the following:
```
Paste: <p><span style="color: rgb(0, 0, 0); font-size: 9pt;">content</span></p>
Output: <p><span style="font-size: 9pt; color: rgb(0, 0, 0);">content</span></p>
```
since they are different, the input has changed, so I need to update the value of the Quill component.
```
Paste: <p><span style="font-size: 9pt; color: rgb(0, 0, 0);">content</span></p>
Output: <p><span style="color: rgb(0, 0, 0); font-size: 9pt;">content</span></p>
```

Creates an infinite loop.

**Comment by GrimaceOfDespair** [comment]
Suffering from the same issue while trying to use quill editor in an Angular 5 context. The attribute order switching puts the application in an infinite change detection loop. In my case it toggles between:

`<p><span style="background-color: rgb(254, 254, 254); color: rgb(0, 0, 0);">...</span></p>`
`<p><span style="color: rgb(0, 0, 0); background-color: rgb(254, 254, 254);">...</span></p>`

The effect is that the (Chrome) browser window seems to be freezing, but not in a "browser not responding" way, where the browser would pro-actively ask you to kill the script - since it's not a tight loop. It just starts hogging CPU.

**Comment by amkoehler** [comment]
@GrimaceOfDespair @mix3d ran into the same issue, which led me here. Did either of you find a workaround for this? I was considering overriding the `background-color` and `color` styles to use be classes instead of inline: https://quilljs.com/playground/#class-vs-inline-style.

**Comment by jchatel** [comment]
Same problem here. Isn't the fix in quill library to just add attributes in the opposite order that they are parsed? Is that so hard to do that adding HTML is deterministic in the way the structure is created?

**Comment by amatiash** [comment]
Why has this issue been closed??? I have the same issue @mix3d [mentioned](https://github.com/quilljs/quill/issues/2530#issuecomment-496664722).
Did anybody found a walk-around?

**Comment by amatiash** [comment]
Ended up with [retrieving](https://quilljs.com/docs/api/#getcontents) and getting Delta [diff](https://github.com/quilljs/delta#diff).

**Comment by lardissone** [comment]
@amatiash do you have an example on how you solved this?
I'm using react-quill and it's a huge blocker.

**Comment by amatiash** [comment]
@lardissone 
```javascript
const delta = this.textEditor.quill.getContents()
const diff  = delta.diff(this.initialDelta)

if(!diff.ops.length)
    isPushAllowed = false
```

**Comment by lardissone** [comment]
@amatiash awesome, thank you!

**Comment by iZamza** [comment]
Maybe it will help someone:
In upper scope we create an element: `const values = document.createElement('div');`
then we put our HTML string in inner HTML for this element:
`values.innerHTML = '<div style="color: red;">some text</div>';`
then we got all tags with inline styles:
`const stylesBlocks = values.querySelectorAll<HTMLElement>(
    '*[style]'
  );
  valuesElements.forEach(element => {
    const newStyle = element.style.cssText
      .split(';')
      .map(attr => attr.trim())
      .filter(attr => attr !== '')
      .sort()
      .join('; ');
    element.removeAttribute('style');
    element.setAttribute('style', `${newStyle};`);
  });
`
and now we have sorted styles in innerHTML of our created element

**Comment by JoshuaTyler-GitHub** [comment]
I generate change-sets for git diff styled transactions. This issue was a major hassle for me because it would cause diffs all the time when the properties were swapping alphabetical order but not changing values.

It's not efficient nor easily understood by new readers but it gets the job done if anyone else comes across this issue:
https://github.com/JoshuaTyler-GitHub/quilljs-quill-issues-2530/blob/main/index.js

```
const STYLE_END_IDENTIFIER = ";\"";
const STYLE_START_IDENTIFIER = "style=\"";
const STYLE_SPLIT_IDENTIFIER = "; ";

const alphabetizeStyleSequencesInString = (styleString) => {
  const parseString = String(styleString);

  // get sequences
  const sequences = findStartSequenceAndEndSequencePositions(
    String(STYLE_START_IDENTIFIER),
    String(STYLE_END_IDENTIFIER),
    String(parseString)
  );

  // replace sequences
  if(sequences.length > 0) {
    let reassemblyString = "";
    let lastSequenceEnd = 0;

    for(const sequenceIndex in sequences) {
      if(sequences[sequenceIndex]) {
        const sequence = sequences[sequenceIndex];

        // fill reassemblyString between sequences
        reassemblyString += parseString.substring(lastSequenceEnd, sequence.start);

        // sort sequence and append to reassemblyString
        const preSortedStyles = parseString.substring(sequence.start, sequence.end);
        const strippedStyles = preSortedStyles
          .replace(STYLE_START_IDENTIFIER, '')
          .replace(STYLE_END_IDENTIFIER, '')
          .split(STYLE_SPLIT_IDENTIFIER);
        const sortedStyles = strippedStyles.sort();
        const postSortedStyles = (
          `${STYLE_START_IDENTIFIER}` +
          `${sortedStyles.join(STYLE_SPLIT_IDENTIFIER)}` +
          `${STYLE_END_IDENTIFIER}`
        );
        reassemblyString += postSortedStyles;
        lastSequenceEnd = sequence.end;
      }
    }

    // fill reassemblyString after all sequences appended
    reassemblyString += parseString.substring(lastSequenceEnd);
    return reassemblyString;
  }
  return styleString;
};

const findStartSequenceAndEndSequencePositions = (startSequence, endSequence, stringToParse) => {
  const _endSequence = String(endSequence);
  const _startSequence = String(startSequence);
  const parseString = String(stringToParse);
  const containsEndSequence = parseString.includes(_endSequence.valueOf());
  const containsStartSequence = parseString.includes(_startSequence.valueOf());

  // only perform comp if string contains sequences
  if(containsEndSequence && containsStartSequence) {
    const sequencePositions = [];

    // parse until end is reached
    let currentPosition = 0;
    while(currentPosition < parseString.length) { // NOSONAR
      const startSubString = parseString.substring(currentPosition);
      const startSequenceSubStringPosition = startSubString.search(_startSequence);
      const startSequencePosition = startSequenceSubStringPosition + currentPosition;
      if(startSequenceSubStringPosition === -1) break; // break if not found
      const endSubStringStart = startSequencePosition + _startSequence.length;
      const endSubString = parseString.substring(endSubStringStart);
      const endSequenceSubStringPosition = endSubString.search(_endSequence);
      const endSequencePosition = endSequenceSubStringPosition + endSubStringStart;
      if(endSequenceSubStringPosition === -1) break; // break if not found
      const endSequencePositionWithLength = endSequencePosition + _endSequence.length;
      sequencePositions.push({
        end: Number(endSequencePositionWithLength),
        start: Number(startSequencePosition)
      });
      currentPosition = endSequencePositionWithLength;
    }
    return sequencePositions;
  }
  return [];
};

module.exports = {
  alphabetizeStyleSequencesInString,
  findStartSequenceAndEndSequencePositions
};
```
(test cases are in repo using jest)

**Comment by mvn-tinhle-dn** [comment]
@amatiash I using react  funcfion component and having the same problem as you, I can't apply your suggestions above. Can you help?

**Comment by amatiash** [comment]
> ```js
> diff.ops.length
> ```

Man, the initial comment is from 2020, I quite don't remember the context. You'd need to figure this out by yourself. I initially had this inside `componentDidUpdate()`. Since you are using functional component `useEffect()` is for you. Try to understand the diff logic. ChatGPT can help as well : )

**Comment by mvn-tinhle-dn** [comment]
@amatiash okie pro. thanks you
