### ISSUE TITLE
Text with newline pasted into lists and blockquotes should insert WITHIN and not BEFORE those elements

### ISSUE THREAD

**Issue by poshest** [quilljs/quill#2531]
Here's pasting a line of text into a list, heading, blockquote and code block

![paste into lists etc text without newline quill](https://user-images.githubusercontent.com/6979221/53809663-1b9fcd00-3f4d-11e9-8868-c8fd9b1c31c7.gif)

All good and as expected.

Here's the same thing, but including a newline char at the end of the copied/pasted text.  (Because of [this issue](https://github.com/quilljs/quill/issues/2483) it's very difficult for users to distinguish between the two text selections - with and without the newline).

![paste into lists etc text with newline quill](https://user-images.githubusercontent.com/6979221/53809818-73d6cf00-3f4d-11e9-84e6-b9ef02fb4314.gif)

Code block is the only one that does it right, in my opinion (aside from the additional unwanted newlines, but that's a different bug).  

For reference, here is how Google docs does it (there are no block quotes or code blocks there afaik).

![paste into lists etc text with newline googledocs](https://user-images.githubusercontent.com/6979221/53809886-9c5ec900-3f4d-11e9-882c-bebb3ce7760c.gif)

Their way of pasting within the numbered list is correct but their inserting before the Heading 1 text is bad UX in my opinion... But that's my lowest priority.  At the least, I feel that lists and blockquotes should be treated by pasting text with newlines WITHIN and not BEFORE those elements.

**Comment by SuperAL** [comment]
@poshest Have you figured out a way to solve this problem?

**Comment by poshest** [comment]
@SuperAL Sorry, we've not spent any time on it as we've had higher priority issues since and we were hoping these issues would be fixed in Quill v2, which seems to be going nowhere unfortunately.
