### ISSUE TITLE
cursor jumps when doing inline after enter, backspace, and new character

### ISSUE THREAD

**Issue by mmoser** [quilljs/quill#2541]
I can reproduce this bug that I am seeing on quills site (https://quilljs.com/docs/formats/). Steps to reproduce:
1. type `test` in the demo editor on that page
2. highlight `test` and click the B (bold)
3. put the cursor between `te` and `st` either by clicking there or by moving the cursor with arrows
4. click enter
5. click backspace
6. enter any character
7. notice the cursor move to the end of the line

**Comment by remintz** [comment]
We found a similar issue when using ,formatText on a selection of the text. If we click in some part on the middle of the editor and enter a key (space key, for example), the cursor jumps to the end of the current delta item.

This bug is pretty old... :-(

**Comment by Winston-Guess** [comment]
Is this not worthy of a fix? I'm going to try find a hack to fix this in the meanwhile and/or have a look at submitting a PR (if it will get any attention?).

**Comment by jeriahwc** [comment]
Has anyone found a solution for this?

**Comment by nmboavida** [comment]
I am having the exact same problem whilst adding newlines
