### ISSUE TITLE
Custom button icons appear as text

### ISSUE THREAD

**Issue by FunnyB0y** [quilljs/quill#2542]
For some reason, when I try to use custom icons (the redo/undo icons) it only appears as text
![Screen Shot 2019-03-16 at 10 13 13 am](https://user-images.githubusercontent.com/20273647/54466519-320f1980-47d4-11e9-92a8-f11dd3fdf510.png)

But I can't seem to reproduce it codesandbox. https://codesandbox.io/s/72qqjm371x

Has anyone encountered this problem before and resolved it?

**Comment by benbro** [comment]
If you can't reproduce it in the [CodeMirror example](https://codepen.io/quill/pen/KzZqZx) (without using an external library as vue.js) it's a bug in your code and not in Quill.
Please use StackOverflow for general questions.
