### ISSUE TITLE
matchVisual: false is not working

### ISSUE THREAD

**Issue by seanmccaffery** [quilljs/quill#2552]
Extra spacing is being inserted through added p and br tags.

For example:

`<p>this is a test</p><p><br></p><ol><li>one two three</li></ol>`

I understand matchVisual: false is supposed to prevent this extra spacing but it's not changing the output.  I've also noticed it has been removed from the documentation.  Can someone clarify if this is still supported and if there is a workaround?

I am using ngx-quill 4.6.10.

**Comment by ycywj** [comment]
I also encountered the same problem. When the content is reversed, there will be more useless<p><br></p>
