### ISSUE TITLE
Quill Modal - Mouse not working

### ISSUE THREAD

**Issue by SJGHal** [quilljs/quill#2553]
I am using the latest version of Quill.  I am using the basic config with just a customized toolbar to remove some options.  I am using Quill in several places in my project and it works great except when I load the quill editor in a modal.  I see the same problem with Firefox and Chrome.

I am opening Quill up in a bootstrap modal and loading up with HTML content in a editor div:
quill.clipboard.dangerouslyPasteHTML(0, "xxxx");
quill.focus();
The content loads and the cursor's position is at the end of the text as expected.  

I am able to navigate around the text and edit it but only using the arrow keys.  When I move the mouse around the text and click to set the position nothing happens.  The cursor remains in its pre-existing position.  

If I move the quill editor div out of the modal and to the main page it works as expected - the mouse clicks set position.  (The only code change is to move the div into the main page.)   

I turned on the quill debug but I really didn't know what I was look at or for. Anyone have any suggestions on what might be happening?  

Thanks

**Comment by benbro** [comment]
Please include all the info requested in the issue template.
This is a problem with your code, not a bug in Quill.
Fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) with a minimal example reproducing your issue.

**Comment by TareqNewazShahriar** [comment]
A note for other developers who will be facing the same problem. Moving cursor with mouse will not work if you have applied CSS `user-select: none`. Wasted so many hours to figure that out. Since this is a required CSS for the editor, Quill team can add that piece of CSS to override other user-select values. Btw, I'm using the latest release `2.0.0-rc.4`.
