### ISSUE TITLE
Uncaught TypeError: Cannot read property 'render' of undefined  

### ISSUE THREAD

**Issue by mini-moo** [quilljs/quill#2554]
I wanna use quill to edit formula in vue. so, I installed 'katex' by npm
Then, I hit on this problem.
![image](https://user-images.githubusercontent.com/17901679/55130569-4b11b600-5156-11e9-9133-3f2a22aa506d.png)

here is the code of dist/quill.js:
![image](https://user-images.githubusercontent.com/17901679/55130880-777a0200-5157-11e9-8760-851aec91a398.png)

**Platforms**:
operating system: macos mojave10.14.3
browser: chrome 73.0.3683.86

**Version**:
quill: 1.3.6
katex: 0.10.1

**Comment by muhammadali298** [comment]
You will have to import Katex in your code to use formulas in quill. to fix this issue in your index.html add following code.

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/katex.min.css" integrity="sha384-8QOKbPtTFvh/lMY0qPVbXj9hDh+v8US0pD//FcoYFst2lCIf0BmT58+Heqj0IGyx" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/katex.min.js" integrity="sha384-GR8SEkOO1rBN/jnOcQDFcFmwXAevSLx7/Io9Ps1rkxWp983ZIuUGfxivlF/5f5eJ" crossorigin="anonymous"></script>`

note: These lines of code must be in the `<head>` tag

**Comment by JakovGlavac** [comment]
If you are using React you are missing katex, you need to assign it to the window object.

```tsx
import ReactQuill, { Quill } from "react-quill";
import katex from "katex";

declare global {
  interface Window {
    katex: any; <-- this is just for typescript
  }
}
const DisplayQuill = ({ html }: { html: string }) => {
	window.katex = katex; <-- this is what is really missing
	const html2 = html?.replace(/<p><br><[/]p>/gi, "\n");

	return <ReactQuill value={html2.trim()} readOnly={true} theme={"bubble"} />;
};

export default DisplayQuill;

```

**Comment by xuyaqist** [comment]
When I try to load KaTeX locally, it has a 404 error about cannot find font file. So I checked the official site of KaTeX, it says,
> Download a [KaTeX release](https://github.com/KaTeX/KaTeX/releases), copy katex.js, katex.css (or katex.min.js and katex.min.css to use minified versions), and the fonts directory, and include or import it like above.

which means that if you want to load KaTeX locally, you have to load the font directory in your project.

**Comment by benbro** [comment]
Answered.
