### ISSUE TITLE
Quill not working in IE11 but works in Edge

### ISSUE THREAD

**Issue by davidsagang** [quilljs/quill#2557]
I have an Angular 6 application with a few Quill controls. They all work fine in Edge and Chrome but it IE 11 they do not show and in the console I have the following error:
[Parchment] Invalid definition

**Version**: 1.3.6

**Comment by semopz** [comment]
IE11 isn't listed in the ReadMe which suggests it is not supported. Does anyone know which version last supported IE11?

**Comment by davidsagang** [comment]
@semopz so did we drop IE11 over time because here [](https://github.com/quilljs/quill/issues/1048) it says that we support it.

**Comment by semopz** [comment]
If you go to the current readme, you can see that IE11 is not listed (compare it to the screenshot in your link). I'm new to this project so don't know anything about its history. I'm now looking into CKEditor as it does support IE11

**Comment by poshest** [comment]
Works in IE11 for me. Make sure you have the ES5 build. There's one here https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.js 

We're investigating some strange issue where the corresponding .min.js file loads a whole lot of ES6 code via webpack (yes, it appears the .min.js file is NOT doing the same thing as the .js file).  That would break IE.

**Comment by poshest** [comment]
UPDATE: that difference in the min.js file is just a source map file which is brought in because of the comment at the bottom of the .min.js file `//# sourceMappingURL=quill.min.js.map`. Bottom line is that there is no ES6 being loaded as such, and so both the .js and .min.js files should work fine in IE11.

**Comment by davidsagang** [comment]
Guys I have quill: 1.3.6 in my package.json and in my angular.json I have imported quill.js from ./node_modules/quill/dist/quill.js. It does work fine in Edge and Chrome but in IE11 I cannot see the controls.
