### ISSUE TITLE
Best way to handle warning on overriding existing format

### ISSUE THREAD

**Issue by buffpojken** [quilljs/quill#2559]
We have a custom implementation for handling video, in which we extend `BlockEmbed` and provide a custom implementation, which is then registered for "formats/video". This results in a warning being printed to the console.

**Steps for Reproduction**

1. Define a new blot-implementation for, for example, video
2. Register blot with Quill using Quill.register
3. Open console

**Expected behavior**:
To not see a warning from Quill about overriding a format

**Actual behavior**:
A warning, see below, is printed.

![Screenshot 2019-04-02 at 12 53 31](https://user-images.githubusercontent.com/47125/55397475-9b1dbd80-5546-11e9-89f5-b4e60e24d9d1.png)

**Platforms**:

Latest stable Chrome and Safari.

**Version**:
1.3.6

**Comment by kaptron** [comment]
One fix we discovered for this was to change the [Quill debug setting](https://quilljs.com/docs/api/#debug):
`Quill.debug('error')` 

Changing the level to `error` will suppress warnings like this one.

**Comment by anthonybattel** [comment]
Quill.register method provide a "suppressWarning" argument. It works !

**Comment by Hirokumi** [comment]
Quill.register('suppressWarning') not working for me

**Comment by fistonhn** [comment]
does anyone find out a way to fix the error?

**Comment by VishneviyMazhor** [comment]
> `Quill.register('suppressWarning')` not working for me

```
// suppressWarning is a last and optional param of register() method
Quill.register(YourModuleClassName, true)
```

**Comment by Maham-Anwaar** [comment]
: ( 
Any fix found ? ;-;

**Comment by benbro** [comment]
Answered.
