### ISSUE TITLE
How do I trigger clean with my code to format

### ISSUE THREAD

**Issue by Chinalink** [quilljs/quill#2560]
now

![image](https://user-images.githubusercontent.com/9859859/55462621-c5947700-5629-11e9-98f7-db1d427db7a5.png)

expected

![image](https://user-images.githubusercontent.com/9859859/55462863-53706200-562a-11e9-9ae5-64bca87b6ff2.png)

I inserted a specific style of text through insertEmbed, and I want to manually trigger clean to format it after the insert is complete so that the text I enter later doesn't have the previous specific style，How do I trigger clean with my code to format

**Comment by changeyu** [comment]
// try this code

let quill = new Quill('#editor', {
  theme: 'snow'
});

function formatClean(quill){
  let range = quill.getSelection(true)
  let formatArr = ['strike','bold','link','color','background','underline','font','size','direction']
  quill.format('blockquote', false)
  quill.format('align', false)
  quill.format('list', false)
  quill.format('header', false)
  if(range.length == 0){
    formatArr.forEach(type=>{
      quill.format(type, false)
    })
    return
  }
  quill.removeFormat(range.index,range.length)
}

let range = this.quill.getSelection(true)
quill.insertEmbed(range.index, 'image', 'https://quilljs.com/images/cloud.png')
formatClean(quill)
