### ISSUE TITLE
Want to implement guppy js into quilljs editor please help me

### ISSUE THREAD

**Issue by ngcgolf11** [quilljs/quill#2563]
I have already create a button into my editor with the name of math "Math" into my editor now i have to use this code to start guppy js into any place <div id="guppy1" style="width:400px;"></div> i want to integrate this code with quill js so that i can add math functions into editor without distributing anything in editor. 

I want to open this math into pop and put back into quilljs editor

**Comment by benbro** [comment]
Read the docs and the code of [community modules](https://github.com/quilljs/awesome-quill).
