### ISSUE TITLE
Web browser crashes when text is drag and drop from text editor to the scroll bar on mozilla

### ISSUE THREAD

**Issue by akhilesh-sharma168** [quilljs/quill#2564]
**Steps for Reproduction**

1. Visit https://quilljs.com/standalone/full/
2. Write the text in the editor till scrollbar comes up. 
3. Then drag and drop the content from the editor across the scrollbar. ()
For the same, I have attached a video.
**Expected behavior**: There shouldn't be any page crash

**Actual behavior**: There is page crash

**Platforms**: Mozilla Firefox 

Ubuntu 18.04

**Version**: Mozilla Version 66
[Screencast from Thursday 04 April 2019 02:58:37  IST.zip](https://github.com/quilljs/quill/files/3042872/Screencast.from.Thursday.04.April.2019.02.58.37.IST.zip)

Run `Quill.version` to find out

**Comment by benbro** [comment]
You should report a Firefox crash to Mozilla:
https://bugzilla.mozilla.org/home

**Comment by akhilesh-sharma168** [comment]
Hi @benbro,

Bugzilla team has found out that issue is due to the editor, for the same they have shared the code.
Please refer to the below link for the same.
https://bugzilla.mozilla.org/show_bug.cgi?id=1541848

**Comment by benbro** [comment]
A web page shouldn't be able to crash the browser. The Editor is probably a Firefox component not the Quill editor.
