### ISSUE TITLE
Is there a way to insert Twitter html blocks extracted from Twitter's api?

### ISSUE THREAD

**Issue by filiptod** [quilljs/quill#2567]
So Twitter offers an endpoint that returns an html string formatted to embed tweets into a website/editor. I'm trying to build a rich text editor that allows for many social media snippets to be added (these are standard blocks of html, not modified by me in any way), but there's no way to insert HTML without having quill remove all of the attributes and script tags required to properly format a tweet. I understand that Quill doesn't allow this for arbitrary html since it might have adverse effects in the editor, but I don't see a reason why this shouldn't be allowed for reputable sites like Twitter, Instagram, Facebook, etc. if it's taken straight from their api.

So I would take a tweet like this: `https://twitter.com/tha_rami/status/1114078130665402370`
Then use Twitter's api to get that tweets html embed code:
```
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Would you kindly read <a href="https://twitter.com/TomRMarks?ref_src=twsrc%5Etfw">@TomRMarks</a> discovering the biggest ludonarrative twist of 2007. <a href="https://t.co/YCFl22STsr">https://t.co/YCFl22STsr</a></p>&mdash; Rami Ismail (@tha_rami) <a href="https://twitter.com/tha_rami/status/1114078130665402370?ref_src=twsrc%5Etfw">April 5, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
Which would then be converted to this, losing all of the standard Twitter styling using `clipboard.dangerouslyPasteHTML`:
`<blockquote>Would you kindly read <a href="https://twitter.com/TomRMarks?ref_src=twsrc%5Etfw" target="_blank">@TomRMarks</a> discovering the biggest ludonarrative twist of 2007. <a href="https://t.co/YCFl22STsr" target="_blank">https://t.co/YCFl22STsr</a></blockquote><blockquote>— Rami Ismail (@tha_rami) <a href="https://twitter.com/tha_rami/status/1114078130665402370?ref_src=twsrc%5Etfw" target="_blank">April 5, 2019</a></blockquote><p><br></p>`

Is there any way to allow for Quill to pass the full html? I would really not want to have to switch to a different rich text editor as I've built most of the functionality already before coming across this problem.

**Comment by DmitrySkripkin** [comment]
Yes, it's possible. But twitter widgets are not really good. Personally I hate the way it works.
[CodePen example](https://codepen.io/DmitrySkripkin/pen/oOBLdo)
P.S. it's not finished, you have to figure out how to deal with selection and many other surprises. Such things are not universal, I just made a basic example.

**Comment by GaddMaster** [comment]
@DmitrySkripkin Be great if you helped me use your code. It's a total jaw-dropper. I have no idea looking at it how to use it. Just need a tweet button in the toolbar that accepts a URL?

Daniel

**Comment by benbro** [comment]
Requires extending Quill.
