### ISSUE TITLE
@mentions not searching userlist, but its triggered userlist. below is my code, im using angular 4 project.

### ISSUE THREAD

**Issue by Aruldass-as** [quilljs/quill#2568]
@mentions not searching userlist, but its triggered userlist. below is my code, im using angular 4 project.

<quill-editor formControlName="description" [options]="editorOptions" (blur)="onEditorBlured($event)"
                                            (focus)="onEditorFocused($event)" (ready)="onEditorCreated($event)"
                                            (change)="onContentChanged($event)" id="sel-des" [mention]="triggerUserList" ></quill-editor>
-------------------------------------------------------------------------------------------------------------
 import { MentionModule } from 'angular2-mentions/mention';

**Comment by DmitrySkripkin** [comment]
This code is really big (sorry for that).
As I know it won't work out of the box.

**Comment by Aruldass-as** [comment]
out of the box, its working good. inside editor its not working..

getUserList() {
        this.serviceProvider.getList('/users/users').subscribe(
            result => {
                this.assigneeList = result;
                  for(let data of this.assigneeList){
                   let getFirstLastName = data['firstName']+''+ data['lastName'];
               this.getFirstLastNameArray.push(getFirstLastName);
                  }
            this.triggerUserList = this.getFirstLastNameArray;
            },
            err => {
            },
            () => {
            }
        );
    }
