### ISSUE TITLE
latex command not working in quilljs

### ISSUE THREAD

**Issue by ngcgolf11** [quilljs/quill#2570]
this is my code math formula is not working when someone try to put latex command it is not showing. 

<link href="https://cdn.quilljs.com/1.0.0/quill.snow.css" rel="stylesheet">

<div id="toolbar">
  <button class="ql-bold">Bold</button>
  <button class="ql-italic">Italic</button>
 <button class="ql-formula">math</button>

</div>

<div id="editor">
  <p>Hello World!</p>
</div>

<script src="https://cdn.quilljs.com/1.0.0/quill.js"></script>

<script>
  var editor = new Quill('#editor', {
    modules: { toolbar: '#toolbar' },
    theme: 'snow'
  });
</script>

**Comment by ngcgolf11** [comment]
I also used updated version js and css but still not result

**Comment by benbro** [comment]
The f<sub>x</sub> button in the demo is working:
https://quilljs.com/standalone/full/

**Comment by ngcgolf11** [comment]
Hey Benbro thanks alot i need 1 more help when i write any latex command without formula into quill it will convert to equation how i can do that
