### ISSUE TITLE
Document.execCommand (command 'strikeThrough') causes the text to disappear 

### ISSUE THREAD

**Issue by zorec** [quilljs/quill#2572]
In summary, it is not possible to format the text (to strikethrough) by using Document.execCommand.

Although the Quill provides specific methods for formatting, they cannot always be easily used or not at all. That's why I believe the Quill should support also formatting via Document.execCommand. 

Just a few more details about my context: the web application is running inside the [QT Web engine](https://doc.qt.io/qt-5/qtwebengine-index.html) 
The command for formatting `Document.execCommand` is triggered by the QT. 

**Steps for Reproduction**

1. Visit quilljs.com
2. Select text in the editor 
3. Open browser console
4. Execute `document.execCommand('strikeThrough')` 

**Expected behavior**:
The selected text will become strikethrough. 
NOTE: It works fine for other formatting commands, i.e. 'bold', 'italic', and 'underline'. The text is formatted accordingly. 

**Actual behavior**:
The selected text disappeared after executing the command. 

**Platforms**:

I'm using a Mac (macOS Majove 10.14.4) and Google Chrome 73.0.3683.103 (Official Build) (64-bit). 
Probably other platforms are also affected. 

**Version**:

1.3.6
Earlier versions are also affected.

**Comment by jhchen** [comment]
execCommand has a history of inconsistency and bugginess across different browsers and so interoperability with execCommand is not in scope of Quill's goals

**Comment by zorec** [comment]
Okay, so here is my solution in case someone else encounters that issue:
```
const Inline = Quill.import('blots/inline');
// This class just adds support for another tag name <strike> in addition to default <s>
// It is necessary since this tag is used by document.execCommand('strikeThrough')
class StrikeThroughAlias extends Inline {}
StrikeThroughAlias.blotName = 'strike';
StrikeThroughAlias.tagName = 'strike';
Quill.register(StrikeThroughAlias);
```
