### ISSUE TITLE
The cursor jumps to the beginning

### ISSUE THREAD

**Issue by LEFTEQ** [quilljs/quill#2575]
The cursor jumps to the beginning in codeblock when placed on 0 index (as first character). (Edge)

**Steps for Reproduction**

1. Visit https://quilljs.com/playground/#form-submit
2. Delete text and add code block
3. Start typing into code block

**Expected behavior**: When I type e.g. "Dog" I would expect to be "Dog"

**Actual behavior**: I get ogD

**Platforms**: Edge (44.17763), Windows 10

Include browser, operating system and respective versions

**Version**:

1.3.6

**Comment by iamwhitebox** [comment]
@LEFTEQ check that your debounceTime is at least 400 if using rxjs

**Comment by sudofox** [comment]
Having a very similar issue with Quill inside of Vue. Kinda irritating

**Comment by Shreyas-BS** [comment]
Having a very similar issue in Lit Element. Any fixes for it??
