### ISSUE TITLE
Truncation Occurs when pasting text in QuillJS container.

### ISSUE THREAD

**Issue by phildeman** [quilljs/quill#2578]
I am using Quilljs 1.3.6.  I set up a page with a number of containers, using autosave.
When I type the text directly into the container, autosave works fine.  However, when I copy/past text from MS Word or a text file, truncation occurs.  I saves at best  2.5 lines of text.

The database field that receives the data from the quill container is a data type "text".  Meaning it is an open text field originally designed for an HTML textarea field.

Why is this happening?  Is there something I need to do allow the container to accept unlimited text?

**HTML quilljs container**
`<label for="strengths"><strong>List your strengths.</strong></label>
  <div id="saved_strengths"></div>
      <input type="hidden" name="strengths">
      <div id="strengths-container">
%       if($goals) {
               <% $strengths->answer %>
%       }
</div>`

**Javascript**
`<script>
$(document).ready(function() {
    var strengthsDelta = Quill.import('delta');

var qstrengths = new Quill("#strengths-container", {
          modules: {
              toolbar: [
                        ["bold", "italic", "underline"],
                        ["link"],
                        [{ list: "ordered" }, { list: "bullet"}],
                                 [{"indent" :"-1"}, {"indent" :"+1"}],
                        ]
	  },
          theme: "snow"
      });

var saform = document.querySelector('#my_form');
  saform.onsubmit = function() {
     // Populate hidden form on submit
     var strengths     = document.querySelector('input[name=strengths]');

     // Update data fields with new values
     strengths.value     = qstrengths.root.innerHTML;
  };

  // Store Appraisal accumulated changes
  var strengthschange = new strengthsDelta();
  qstrengths.on('text-change', function(delta) {
     strengthschange = strengthschange.compose(delta);
  });

  // Save Appraisals periodically
  setInterval(function() {
     if (strengthschange.length() > 0) {
        $.get('/my_app?strengths=' + qstrengths.root.innerHTML + '&formuser=' + $( '#formuser' ).val() + "&manager=" + $( '#srchempl' ).val(), {});
        $('#saved_strength').html('&nbsp; <strong>Saved strengths!</strong>');
     }
  }, 5*1000);
});
</script>
`

**Excepted behavior with Submit button:**
when clicking the submit button, all pasted data in the container is to be saved.

**Actual behavior with Submit button:**
All data pasted data in container is saved.

**Excepted behavior with Autosave:**
5 seconds after data is pasted, all pasted data in the container is to be saved.

**Actual behavior with Submit button:**
5 seconds after data is pasted, 2 to 2.5 lines are saved. The rest of the data is truncated.

**System, Browser**
Mac OSX (10.13.6)
Macbook Pro
Chrome: 73.0.3683.103 (Official Build) (64-bit)
Quilljs: 1.3.6

**Comment by jhchen** [comment]
Please include steps for reproduction.
