### ISSUE TITLE
Running Quill tests

### ISSUE THREAD

**Issue by rico1534** [quilljs/quill#2580]
H,
I am wondering how I can run Quilljs' tests locally.
I see the test directory in the code, but I can't find a way to execute the tests.
Couldn't find any info in the issues as well.
Any help please?

Thanks.

**Comment by KillerCodeMonkey** [comment]
just checkout the package.json and the script section there?

**Comment by rico1534** [comment]
downloaded the whole project from the root dir. I just mentioned I see there's a test dir, but no clue how to use it.

**Comment by KillerCodeMonkey** [comment]
like i said... 

1. install all node modules
2. checkout = look into the package.json and the scripts section there.. *facepalm

**Comment by rico1534** [comment]
i saw your question mark, thought it's a question..
