### ISSUE TITLE
Customize indent space

### ISSUE THREAD

**Issue by rajuashok** [quilljs/quill#2584]
**Steps for Reproduction**
1. In a quill editor initiate an ordered or unordered list.
2. The tab spacing is about 8 characters it seems.

**Expected behavior**:
This is the expected behavior, but I'd like to customize it.

**Question**
Is there a way to customize the amount of space a list indent takes up? My editor area is small and would rather not have it take up so much space.

**Comment by benbro** [comment]
Answered [here](https://stackoverflow.com/questions/55171980/increase-indentation-size-of-tabs-in-quilljs/55191960#55191960).

**Comment by 0xc00010ff** [comment]
I found from the browser inspector that this is just `padding-left` on `ul` and `ql-indent-{level}` inside of `.ql-editor`.

Example CSS to override:
```
.ql-editor ul, ol {
  padding-left: 0.25rem;
}

.ql-indent-1 {
  padding-left: 2.5rem;
}

/* Continue replicating until ql-indent-9*/
```

Or for my case, I'm using `quill-react` and Styled Components so I can loop through
```
const NotesInput = Styled(ReactQuill)`

   width: 100%;

  .ql-editor {
    font-size: 1rem;
    tab-size: 4; /* This isn't related to lists, but you might want to set it too*/

    /* Control the list padding, which covers the 0th level of indention */
    & ul, ol {
      padding-left: 0.25rem;
    }

    /* Loop through and make indent classes 1-9 */
    ${ 
      [...Array(9).keys()].map(k=>k+1).map(level => {
        // this loops the indent level 1-9 and gives it an incremental value
        return `
          & li.ql-indent-${level} {
            padding-left: ${level + 1.5}rem;
          }
        `;
      })
    }
`;
```

<img width="368" alt="Screen Shot 2020-08-09 at 2 41 47 AM" src="https://user-images.githubusercontent.com/4950729/89729576-f473e780-d9eb-11ea-8d8d-6dc37f840472.png">


Side note: 
The default looks too wide in my opinion
