### ISSUE TITLE
Unable to use text-decoration: underline and text-decoration: line-through

### ISSUE THREAD

**Issue by krilllind** [quilljs/quill#2585]
**Steps for Reproduction**

1. Visit [Quill js Playground](https://quilljs.com/playground/)
2. Edit HTML to `<span style="font-style: italic">My test</span>`
Expects output to be `<em>My test</em>` (true)
3. Edit HTML to `<span style="text-decoration: underline">My test</span>`
Expects output to be `<b>My test</b>` (false)

**Expected behavior**:
CSS style `text-decoration: underline` and `text-decoration: line-through` should be converted 
 into HTML tags `<u>` and `<s>`

Currently only `font-weight: bold` and `font-style: italic` works.

**Actual behavior**:
`<span>` element containing css values `text-decoration: underline` and `text-decoration: line-through` are not converted, but insted ignored and removed.

**Platforms**:
Tested in Google Chrome v73.0 Windows 10 x64

**Version**:
Tested in [Quill js playground](https://quilljs.com/playground/) (v1.3.6)

**Comment by krilllind** [comment]
Can someone please confirm this bug?

**Comment by edhowler** [comment]
I confirm that it is still happening in 2.0.0-dev.3.

**Comment by edhowler** [comment]
I've made a pull request with the correction for this issue:
https://github.com/quilljs/quill/pull/2679

**Comment by Charlie50503** [comment]
It seem's not work for me.

my explame
https://codepen.io/CharlieKu50503/pen/gOWBmEo

is someone could share solution explame please.

**Comment by pedrovgs** [comment]
I'm testing and facing the same bug in all the versions I've tested. Is there any workaround we can use here @edhowler @krilllind ? Thanks!
