### ISSUE TITLE
Invisible character in header - Problems with selection // Header and header attributes not in the same object

### ISSUE THREAD

**Issue by tygore587** [quilljs/quill#2587]
If you try to select a header(h1) and call function `quill.getSelection()` it mostly resulted in a wrong selection output. If you try to get the content with the index and length of the selection method, it doesn't return the attributes for the header, because there is a invisible character at the end, which is only selected if you select the next empty line also.

**Steps for Reproduction**

1. Visit quilljs.com
2. Select Header text `Quill Rich Text Editor`
3. Open console and type `selection = quill.getSelection()`
4. Type `quill.getContent(selection)`

**Expected behavior**: All attributes (h1) should be in the getContent() array/in header object.

**Actual behavior**: Attributes are missing

**Platforms**: MacOS(10.14.3), Chrome (73.0.3683.103), 

Include browser, operating system and respective versions

**Version**: 1.3.6

Run `Quill.version` to find out

**Comment by DmitrySkripkin** [comment]
Huge Quill.js problem. This postorder insert with `\n` and attributes is not very convenient. Same problem with lists and code-block and any not inline format.
BTW `getLine()` and `getFormat()` works fine in this case. But it looks like workaround in so many cases.

**Comment by easylite376** [comment]
Hey thanks for the suggestions :) 

But that doesn't work for me, because I only save the indexes and reconstruct the text after that on Another problem I see: If I just mark have of the text, it also doesn't returns the format.
