### ISSUE TITLE
bundler: command not found: foreman

### ISSUE THREAD

**Issue by sinbargit** [quilljs/quill#2588]
My laptop is MAC and I have install the bundler into the `/usr/local/bin` with `gem install bundler -n /usr/local/bin`.
But when I do `sudo bundle install`, It out put` cp: /usr/bin/foreman: Operation not permitted
` And then I run `npm start` it error with `bundler: command not found: foreman
`
here is the error information:
```
bundler: command not found: foreman
Install missing gem executables with `bundle install`
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! quill@2.0.0-dev.3 start: `npm run build:webpack; bundle exec foreman start -f _develop/procfile`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the quill@2.0.0-dev.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiexing/.npm/_logs/2019-04-18T11_49_20_283Z-debug.log
```

Please give some help

**Comment by mostlycached** [comment]
Hi @sinbargit - 
You need to get `bundle install` to be successful for `npm start` to work. And bundle install doesn't seem to succeed for you at this point.

Is there are reason you are running `sudo bundle install` and not just bundle install? You might have to do something like `bundle install --path vendor/bundle` in case you don't have access to your system rubygems path(which is what it seems like might be the case for you) or don't want to install it directly alongside system rubygems. Either way, running bundler as root is not recommended in general.

I'd recommend you try again with install bundler in a local directory, say `bundle install --path=vendor/bundle` and see if you face this issue again

Cheers 
mostlycached

**Comment by mike-shtil** [comment]
If anyone still experiences this on macOS, the selected answer here did the trick for me:
https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a
