### ISSUE TITLE
Custom Style Attributor with Block Scope

### ISSUE THREAD

**Issue by rverderber** [quilljs/quill#2589]
I'm are using Quilljs for a project and have implemented some custom style attributors for font-size and font-family. I wanted them applied to the BLOCK scope. It all seems to work well within the Quill editor and add the appropriate styles to the paragraph tags. 

After I save and reload the modified HTML with the inline styles into the editor and re-initialize Quill it removes all the inline styles from the block elements (paragraphs). I thought the registering of the custom style attributor would stop that. Is there a step I am missing?

We created a workaround to query and save the styles in the content paragraph tags and then reapply the styles after quill initializes. I was hoping there was a better way. 

Thanks in advance for any suggestions. 

@jhchen

**Comment by justinpeterman** [comment]
Can you please file this using the new issue template?
