### ISSUE TITLE
which format of content should be stored into database postgresql?

### ISSUE THREAD

**Issue by a2htray** [quilljs/quill#2590]
I'm confused that how to store the content and whether there is a best practice?

if I can store the content, then how to render the content in browser without the quill style files.

Thank you for anybody who can help me

**Comment by a2htray** [comment]
Attach another question, if I can store the content, then how to render the content in browser without the quill style files

**Comment by benbro** [comment]
You should store the Delta returned from [getContents()](https://quilljs.com/docs/api/#getcontents). You can find a demo [here](https://quilljs.com/playground/#form-submit).
Quill currently needs an editor to render the content but you could try running quill in node.js on the server or search for json to html from the community:
https://github.com/quilljs/awesome-quill

**Comment by a2htray** [comment]
@benbro thank you for you reply

**Comment by Gladskih** [comment]
@benbro Why not html?
