### ISSUE TITLE
Shortcuts not working on Firefox 66

### ISSUE THREAD

**Issue by Alzavio** [quilljs/quill#2592]
Hey, so I've had some trouble with shortcuts with Quilljs on the latest version of Firefox. But they seem to be working fine on other browsers, such as the Yandex Browser. I'm using Windows 10, updated to the latest version.

Here's an example page I'm working on, but I can move things over to a codepen if that's best. 
http://anischedule.com/u/test@test.test

**Expected behavior**:
Shortcuts like ctrl b should make text bold of FF66

**Actual behavior**:
Nothing happens. The buttons do work though, and shortcuts continue to work on other browsers such as Yandex. 

**Version**:
1.3.6

**Comment by DokaRus** [comment]
Quill [playground](https://quilljs.com/playground/) works fine for me at FF66 (66.0.3 x64)

**Comment by helloTherem8** [comment]
Weird
