### ISSUE TITLE
Is there a way to format nodes without going threw content editable?

### ISSUE THREAD

**Issue by andrei-cacio** [quilljs/quill#2593]
I have two use cases where I need rich text formatting: 

1. Normal use case where you have an editor and you can type and edit text and format it
2. Simply selecting some "read-only" text elements and format them all at once (the whole element will be formatted)

I was able to write a function where I create an absolute container (unseen by the user) and put the content there, instantiate Quill on it and format the content and then put it back in the node. The only problem is that this is very costly, on many nodes you can see significat stutter. It takes about 55ms per node to edit it with this solution.

Is there an easier way to do this? I started to write an algorithm by hand but there are so many cases to cover and I though that I could do it threw Quill some how but not using the whole flow.

Thank you in advance!

**Comment by DmitrySkripkin** [comment]
Yes, you can. CodePen example is coming :)

**Comment by andrei-cacio** [comment]
Wow, interesting hack there:). It doesn't seem to be working on the main parent `<p></p>` (which would be my use case).

While this is very good to know, this implies that there is already a Quill instantiated and you are accessing nodes inside the editor. I would like to achieve this without a physical editor rendered on the document.

**Comment by andrei-cacio** [comment]
I tried to keep a Quill instance at all times and hidden from the view port. However, the only way to inject content for Quill to handle it properly is via `clipboard.dangerouslyPasteHTML()` which adds the same cost overhead of over **40ms** on each node. So that's way I want to find a way to avoid having a Quill instance.

**Comment by benbro** [comment]
Quill is an editor.
