### ISSUE TITLE
How to get the node where the cursor is located.

### ISSUE THREAD

**Issue by Inseeker** [quilljs/quill#2597]
I need to  get the node where the cursor is located,  then I want to add class or id to this node.
I have never found an effective method.

**Comment by benbro** [comment]
The experimental [getLeaf](https://quilljs.com/docs/api/#getleaf-experimental) will give you the the Blot. You can get the dom node from it.

**Comment by DerDemystifier** [comment]
You can do :
```javascript
let range = QuillEditor.getSelection();
QuillEditor.getLeaf(range.index)[0].domNode;
```
Just be sure about the index, the Blot could return empty and [0] won't work I presume.
