### ISSUE TITLE
issue in adding 2 new custom toolbar style icon

### ISSUE THREAD

**Issue by preetha-kesavan** [quilljs/quill#2598]
Hi,

I have used the following code to add two new custom button in the toolbar.
let Inline = Quill.import('blots/inline');

```
class SpanBlock extends Inline {
  static blotName: string;    
  static tagName: string;
    static create(value){
        let node = super.create(value);
        node.setAttribute('class','spanblock');
        return node;    
    } 
}
SpanBlock.blotName = 'spanblock';
SpanBlock.tagName = 'div';
Quill.register(SpanBlock);

class SpanBlockRed extends Inline {    
  static blotName: string;    
  static tagName: string;
  static create(value){
      let node = super.create(value);
      node.setAttribute('class','spanblock-red');
      return node;    
  }
}
SpanBlockRed.blotName = 'spanblock-red';
SpanBlockRed.tagName = 'div';
Quill.register(SpanBlockRed);
```
And I have the following styles associated with it as below

```
.spanblock {
  border: 1px solid #000;
  padding: 6px 10px;
  border-radius: 3px;
  margin: 15px 0;
}

.spanblock-red {
    border: 1px solid #cc0000;
    padding: 6px 10px;
    border-radius: 3px;
    margin: 15px 0;
}
```
Everything works fine, clicking one button adds a black border box and clicking another adds a red border box. I store it in the database successfully and while reading back it loads the html string back into the quill editor. While doing so, the editor seems to change the style always to the latest registered button. For eg, in this case it chooses SpanBlockRed and I see only red box in the editor. If I save it back as it is, it saves correctly but only while viewing it back is shows the wrong class. Am I doing anything wrong in here?
![image](https://user-images.githubusercontent.com/38659830/56957234-6188a400-6b3e-11e9-8917-a3295399fae3.png)

whereas the actual html content is like below

`<h1><strong class="ql-font-monospace" style="color: rgb(230, 0, 0);"><em>1</em></strong></h1><h1><strong class="ql-font-monospace" style="color: rgb(102, 185, 102);"><em><div class="spanblock-red">22 </div></em></strong></h1><h1><strong class="ql-font-monospace" style="color: rgb(0, 102, 204);"><em><div class="spanblock">333</div></em></strong></h1><h1><br></h1>`

Please let me know how to fix this.

Please have a look at the code pen page with this issue 
[https://codepen.io/anon/pen/xeeqRP?editors=1010](https://codepen.io/anon/pen/xeeqRP?editors=1010)

**Comment by preetha-kesavan** [comment]
Hi @benbro ,

Could you please have a look at it? Is it something you can help with?

Thanks

**Comment by christophhase** [comment]
I have the same problem.  Exist's a workaround there ?
greetings Christoph

**Comment by preetha-kesavan** [comment]
No updates on this yet. I cannot use the feature. And no workarounds yet.

**Comment by christophhase** [comment]
a pity
