### ISSUE TITLE
Scripting of Ctrl A + Ctrl C on editor contents

### ISSUE THREAD

**Issue by juncaofish** [quilljs/quill#2602]
How could I implement a toolbar plugin to copy content from quill editor, as the expected behavior is like using keyboard Ctrl A + Ctrl C ? 
![image](https://user-images.githubusercontent.com/3062715/57277598-0ecb6100-70d7-11e9-898a-28a516566738.png)

I found both innerHTML and innerText couldn't keep the rich text format in quill.

**Comment by benbro** [comment]
Use the [API content functions](https://quilljs.com/docs/api/#updatecontents).

**Comment by juncaofish** [comment]
> Use the [API content functions](https://quilljs.com/docs/api/#updatecontents).

Thanks for reply.
I've gone through all the docs and api. 
It seems updateContents seems to be used for updating the editor with Delta.

But what I want is clicking the custom plugin icon, and paste into some other quill editor, to get exactly the same result as Ctrl A+Ctrl C+Ctrl V. (Maybe I should write the Delta object into the system clipboard?)

**Comment by benbro** [comment]
Get the delta with [getContents](https://quilljs.com/docs/api/#getcontents) on the first editor and call [setContents(](https://quilljs.com/docs/api/#setcontents)delta) on the second editor.

setContents will replace all the text in the editor.
updateContents will apply a delta (change) to the existing content.

**Comment by juncaofish** [comment]
> Get the delta with [getContents](https://quilljs.com/docs/api/#getcontents) on the first editor and call [setContents(](https://quilljs.com/docs/api/#setcontents)delta) on the second editor.
> 
> setContents will replace all the text in the editor.
> updateContents will apply a delta (change) to the existing content.

Nono, clicking on the plugin icon could of course use any api (This step replaces Ctrl A + Ctrl C for user convenient.) , but for the other editor, user should be able to use Ctrl + V to paste what has been set to the clipboard. Is it a hard job to implement with available quill api?

**Comment by benbro** [comment]
You'll might be able to copy to the clipboard with document.execCommand('copy') and than use Ctrl+V but I didn't try it.

**Comment by juncaofish** [comment]
> You'll might be able to copy to the clipboard with document.execCommand('copy') and than use Ctrl+V but I didn't try it.

`function copyToClipboard(text) {
    var $temp = $("<input>");
    $("body").append($temp);
    $temp.val(text).select();
    document.execCommand("copy");
    $temp.remove();
    alert("复制成功");
}`

yes, it could be done with the snippet above. But, what value should the parameter text be passed ? Either innerHTML or innerText doesn't retain the rich text format as ctrl A + ctrl C..

**Comment by benbro** [comment]
input element doesn't support rich text. Anyway, questions like this are better asked on StackOverflow so I'm closing this issue.

**Comment by juncaofish** [comment]
> input element doesn't support rich text. Anyway, questions like this are better asked on StackOverflow so I'm closing this issue.

since input element doesn't support rich text, does quill support selecting ?  If yes,     document.execCommand("copy"); could directly copy content form quill editor, else, I still think this question should be asked here instead of Stackoverflow, because it's not a general copy paste job using javascript.

**Comment by benbro** [comment]
[Selection API](https://quilljs.com/docs/api/#selection) in the docs.
Github issues are for bugs, not for general Javascript questions.
