### ISSUE TITLE
Buttons doesn't work in Laravel 5.8 in the toolbar

### ISSUE THREAD

**Issue by Matildevoldsen** [quilljs/quill#2604]
When using Laravel there are issues with clicking the toolbar buttons. They do not respond when you click on them or do any of the interactive behaviors like bold text.

The issue seems to not be there by removing app.js code in Laravel though that isn't ideal. 

**Expected behavior**:
To be able to click on for example bold button and get bold text.

**Actual behavior**:
Doesn't respond to click on any buttons.

**Browsers**: Tested on Chrome, and Safari.

**Version**: 1.3.6
**Laravel Version**: 5.8

**Comment by benbro** [comment]
This is probably a problem with conflicting styles. 
Try to add your css file to the [CodePen example](https://codepen.io/quill/pen/KzZqZx) and see if you can reproduce it.
This is not a bug in Quill.
