### ISSUE TITLE
CDN link to version 0.20.1 is broken

### ISSUE THREAD

**Issue by rdemmers** [quilljs/quill#2606]
We still had a link to a rather old version of quill through the CDN, but since a few weeks it stopped working. 

https://cdn.quilljs.com/0.20.1/quill.js 

I'm aware that it's a very old version, but it seems like the JS file has been overwritten by binary data? We need to update anyway, but I figured a heads-up would be appreciated.

**Comment by jhchen** [comment]
Sorry about that -- some files were in gzipped form but should all be fixed now
