### ISSUE TITLE
How can I get the class instance of a module?

### ISSUE THREAD

**Issue by silentsnooc** [quilljs/quill#2608]
Is it possible to get the module object from Quill?

In my example I am using https://github.com/afconsult/quill-mention but I need access to certain public members of the Mention class.

**Comment by benbro** [comment]
[getModule](https://quilljs.com/docs/api/#getmodule):

var toolbar = quill.getModule('toolbar');
console.log(toolbar);

**Comment by silentsnooc** [comment]
@benbro Lifesafer. Thanks :)
