### ISSUE TITLE
Render header tag as inline styling

### ISSUE THREAD

**Issue by abialas** [quilljs/quill#2609]
Is it possible to modify how header tags (h1, h2...) are rendered to the html? Right now the editor renders header as tag: 
`<h1>sample text</h1>`
but I need to have inline styling instead:
`<style size=\"12\" isBold=\"true\" forecolor=\"black\">sample text</style>`

I was able to change tag for bold with the following code:
```
var Bold = Quill.import('formats/bold');
Bold.tagName = 'B';
Quill.register(Bold, true);
```
but I do not know how to do it for headers.

**Comment by benbro** [comment]
Header is a block tag and effects the whole line. It behave different from inline blot. You could create your own custom button or post-process the html.
