### ISSUE TITLE
How to add custom button? Full working example

### ISSUE THREAD

**Issue by engineerpavel** [quilljs/quill#2611]
I want to use the content editor in my project and I want to take Quill as a basis.
I tried to add a button that would wrap the selected text into a specific tag, and add styles, but I didn't find a walkthrough of how I can do that.
I would like to see an example of how I can add my button that will work. That's what I want:

1. Add a new button to the toolbar, set my own svg icon to it.
2. Add a handler that wraps the selected text in the <div> (or` <p>` or anything else) tag and adds the style as `<div class="my-style">content<div>`
3. When selecting text that already has this style, the button becomes "pressed" and if I press it again, the style is removed for the selected text.

I use Angular, but I'll also be happy to use pure Javascript as an example.

**Comment by benbro** [comment]
Demo:
https://codepen.io/anon/pen/qGqpad

```html
<div id="toolbar-container">
  <button class="ql-bold"></button>
  <button class="ql-italic"></button>
  <button id="custom-button">C</button>
</div>
<div id="editor-container"></div>
```

```javascript
var quill = new Quill('#editor-container', {  
  modules: {
    toolbar: '#toolbar-container'
  },
  placeholder: 'Compose an epic...',
  theme: 'snow' // or 'bubble'
});

var Parchment = Quill.import("parchment");

let CustomClass = new Parchment.Attributor.Class('custom', 'ql-custom', {
  scope: Parchment.Scope.INLINE
});

Quill.register(CustomClass, true);

var customButton = document.querySelector('#custom-button');
customButton.addEventListener('click', function() {
  var format = quill.getFormat();
  if(format.custom) {
    quill.format('custom', '');
  } else {
    quill.format('custom', 'test');
  }
});

quill.on('editor-change', function(eventName, ...args) {
  if(quill.getFormat().custom) {
    customButton.classList.add('ql-active');
  } else {
    customButton.classList.remove('ql-active');
  }
});
```

**Comment by engineerpavel** [comment]
It works. Thank you.

**Comment by jglantonio** [comment]
```html
 <link href="https://cdn.quilljs.com/1.0.0/quill.snow.css" rel="stylesheet">
                        <select name="" id="custom-selector">
                            <option>HTML</option>
                            <option>PHP</option>
                            <option>JS</option>
                            <option>SHELL</option>
                        </select>

                        <!-- Create the toolbar container -->
                        <div id="toolbar">
                        </div>
                        <!-- Create the editor container -->
                        <div id="editor">
                        </div>
````
```js
    var toolbarOptions = [
        ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
        ['blockquote', 'code-block','code'],

        [{ 'header': 1 }, { 'header': 2 }],               // custom button values
        [{ 'list': 'ordered'}, { 'list': 'bullet' }],
        [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
        [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
        [{ 'direction': 'rtl' }],                         // text direction

        [ 'link', 'image', 'video', 'formula' ],
        [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

        [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
        [{ 'font': [] }],
        [{ 'align': [] }],

        ['clean']                                         // remove formatting button
    ];

    var quill = new Quill('#editor', {
        modules: {
            toolbar: toolbarOptions
        },
        theme: 'snow'
    });

    $('#custom-selector').on('change', function() {
        $('#editor').html($('#editor').html()+($('#custom-selector option:selected').val()));
    });
```
I work it.

**Comment by Tikam02** [comment]
> Demo: https://codepen.io/anon/pen/qGqpad
> 
> ```
> <div id="toolbar-container">
>   <button class="ql-bold"></button>
>   <button class="ql-italic"></button>
>   <button id="custom-button">C</button>
> </div>
> <div id="editor-container"></div>
> ```
> 
> ```js
> var quill = new Quill('#editor-container', {  
>   modules: {
>     toolbar: '#toolbar-container'
>   },
>   placeholder: 'Compose an epic...',
>   theme: 'snow' // or 'bubble'
> });
> 
> var Parchment = Quill.import("parchment");
> 
> let CustomClass = new Parchment.Attributor.Class('custom', 'ql-custom', {
>   scope: Parchment.Scope.INLINE
> });
> 
> Quill.register(CustomClass, true);
> 
> var customButton = document.querySelector('#custom-button');
> customButton.addEventListener('click', function() {
>   var format = quill.getFormat();
>   if(format.custom) {
>     quill.format('custom', '');
>   } else {
>     quill.format('custom', 'test');
>   }
> });
> 
> quill.on('editor-change', function(eventName, ...args) {
>   if(quill.getFormat().custom) {
>     customButton.classList.add('ql-active');
>   } else {
>     customButton.classList.remove('ql-active');
>   }
> });
> ```

codepen not working

**Comment by AvaognTheme** [comment]
> > Demo: https://codepen.io/anon/pen/qGqpad
> > ```
> > <div id="toolbar-container">
> >   <button class="ql-bold"></button>
> >   <button class="ql-italic"></button>
> >   <button id="custom-button">C</button>
> > </div>
> > <div id="editor-container"></div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > var quill = new Quill('#editor-container', {  
> >   modules: {
> >     toolbar: '#toolbar-container'
> >   },
> >   placeholder: 'Compose an epic...',
> >   theme: 'snow' // or 'bubble'
> > });
> > 
> > var Parchment = Quill.import("parchment");
> > 
> > let CustomClass = new Parchment.Attributor.Class('custom', 'ql-custom', {
> >   scope: Parchment.Scope.INLINE
> > });
> > 
> > Quill.register(CustomClass, true);
> > 
> > var customButton = document.querySelector('#custom-button');
> > customButton.addEventListener('click', function() {
> >   var format = quill.getFormat();
> >   if(format.custom) {
> >     quill.format('custom', '');
> >   } else {
> >     quill.format('custom', 'test');
> >   }
> > });
> > 
> > quill.on('editor-change', function(eventName, ...args) {
> >   if(quill.getFormat().custom) {
> >     customButton.classList.add('ql-active');
> >   } else {
> >     customButton.classList.remove('ql-active');
> >   }
> > });
> > ```
> 
> codepen not working

External Js Scripts in the settings. It will work.
https://cdn.quilljs.com/1.3.6/quill.js
https://cdn.quilljs.com/1.3.6/quill.snow.css
