### ISSUE TITLE
Paste as plain text not working as expected.

### ISSUE THREAD

**Issue by andrei-cacio** [quilljs/quill#2612]
Paste as plain text using (<kbd>Ctrl + Shift + V</kbd> or <kbd>Ctrl + Alt + Shift + V</kbd>) should keep the current formatting of the caret's position in the text. If we look at similar text editing software like MacOS Pages or Google Docs, the behavior is the same.

In Quill what happens is that the text is not merged into the current node, but it is simply inserted as a text node outside of the current span or strong or whatever the current node parent is for the caret's position.

**Steps for Reproduction**

1. Visit https://jsbin.com/neqiqaweki/
2. Copy the text under the Hello World and **paste it as plain text** between Hello and World

**Expected behavior**:

The text should maintain the formatting of the current node (the color `tomato`)

**Actual behavior**:

The text is pasted as black (the default color)

**Platforms**:

Chrome, Safari, Firefox

**Version**:

1.3.6

**Comment by andrei-cacio** [comment]
it seems that this is also the default behavior for `contenteditable` as well. When pasting plain text it maintains the format of caret's position.

**Comment by luin** [comment]
Fixed in the latest commit.
