### ISSUE TITLE
How to disable a toolbar option?

### ISSUE THREAD

**Issue by anumysore5** [quilljs/quill#2613]
I have a scenario where I need to provide 3 toolbar options (bold, italic, link) for certain cases and for some I need to display all the 3 options in the toolbar, but disable some of them (i.e. show bold, italic, link but the link button should be disabled). How do I achieve this?

**Comment by benbro** [comment]
https://codepen.io/anon/pen/OYWVqe

**Comment by anumysore5** [comment]
> https://codepen.io/anon/pen/OYWVqe

I can still select a word and make it bold by clicking on `B` from the toolbar

**Comment by benbro** [comment]
It's working for me on Chrome and Firefox.
If it doesn't work for you can try something else or fork the [toolbar module](https://github.com/quilljs/quill/blob/develop/modules/toolbar.js).
This type of questions are better for StackOverflow.
