### ISSUE TITLE
When clicking on bullet list button a numbered list is displayed

### ISSUE THREAD

**Issue by uzzafar** [quilljs/quill#2614]
**Steps for Reproduction**
1. Open the text editor
2. Click on Bullet button in the toolbar

Expected behavior:
A bullet list is displayed on the screen

Actual behavior:
A numbered list is displayed on the screen

Platforms:
Chrome 
Linux

Version:
2.0.0-dev.3

**Comment by markpalantoni** [comment]
@uzzafar Did you include a stylesheet? e.g. react-quill-2/dist/quill.snow.css. For bullet lists, the markup rendered is an `<ol>` with `<li data-list="bullet">` and the stylesheet uses `:before` to render a bullet. My issue is that customers render the markup generated by quill outside my product where the stylesheet is not included, so bullet lists are rendered as numbered lists.

**Comment by smah1980** [comment]
I am still facing the issue. markup is rendered in <ol> and <li data-list="bullet"> but still showing numbers, I have manually pasted all the content of quill.snow.css inside my html under <style> tag. but it did not worked. not sure what I have missed :(

**Comment by dtugmod** [comment]
@smah1980 @uzzafar If it helps, I've come up with a workaround for v2 by extending the list item and list container.

```
class MyListContainer extends ListContainer {
	static tagName = ["OL", "UL"];
	static defaultTag = "OL";

	static create(value) {
		return document.createElement(this.getTag(value));
	}

	static getTag(val) { 
                // Our "ql-list" values are "bullet" and "ordered"
		const map = {
			bullet: "UL",
			ordered: "OL",
		};
		return map[val] || this.defaultTag;
	}

	checkMerge() {
		// Only merge if the next list is the same type as this one
		return (
			super.checkMerge() &&
			this.domNode.tagName === this.next.domNode.tagName
		);
	}
}

class MyListItem extends ListItem {
	static requiredContainer = MyListContainer;

	static register() {
		Quill.register(MyListContainer, true);
	}

	optimize(context) {
		if (
			this.statics.requiredContainer &&
			!(this.parent instanceof this.statics.requiredContainer)
		) {
                        // Insert the format value (bullet, ordered) into wrap arguments
			this.wrap(
				this.statics.requiredContainer.blotName,
				MyListItem.formats(this.domNode)
			);
		}
		super.optimize(context);
	}

	format(name, value) {
                // If the list type is different, wrap this list item in a new MyListContainer of that type
		if (
			name === ListItem.blotName &&
			value !== this.domNode.getAttribute("data-list")
		) {
			this.wrap(this.statics.requiredContainer.blotName, value);
		}
		super.format(name, value);
	}
}

```

**Comment by asadalibest1** [comment]
how to add lineheight functionality like ms word in react-quill

**Comment by zaqijr7** [comment]
i facing same issue even i use quill version 2
<img width="294" alt="image" src="https://github.com/user-attachments/assets/5e8f9efd-dd17-4933-8f02-a60959b6e639">

and when I clicked the bullet list, the numbered list was displayed.
<img width="764" alt="image" src="https://github.com/user-attachments/assets/d4a50a34-fcec-4261-b0ec-286442bd6098">

**Comment by fipil** [comment]
Me too. Still ordered list when using bullets.

**Comment by 7aklhz** [comment]
same issue. any update please ?

**Comment by sebworkspace** [comment]
Same issue, any workaround please?

**Comment by karinegomes** [comment]
I'm having the same issue. My workaround was to add this CSS:

```
ol li[data-list="bullet"] {
    list-style-type: disc;
}
```

**Comment by Sofia-Machado** [comment]
I also have the same problem, my workaround, since I'm working withReact, was this:

```
const transformListTags = (html) => {
    const div = document.createElement("div");
    div.innerHTML = html;

    // Find all <li> elements with 'data-list="bullet"' and transform <ol></ol> to <ul></ul>
    div.querySelectorAll('li[data-list="bullet"]').forEach((li) => {
      // Get the closest parent <ol>
      const parentOl = li.closest("ol");
      if (parentOl) {
        // Create a new <ul>
        const ul = document.createElement("ul");
        // Transfer the <ol>'s content to <ul>
        ul.innerHTML = parentOl.innerHTML;
        // Replace <ol> with <ul>
        parentOl.replaceWith(ul);
      }
    });
```

**Comment by mayconvs** [comment]
This is happening because of this css styling found in the quill-snow.css file:

.ql-editor ol li::before {
content: counter(list-0, decimal) '. ';
}

You should change it to:

.ql-editor ol li::before {
content: "";
}

**Comment by lexev97** [comment]
> @fipil @Sebosun @7aklhz @sebworkspace @karinegomes If you are having the problem of list numbers and list bullets overlapping each other, this is due to this css styling found in the quill-snow.css file:
> 
> .ql-editor ol li::before { content: counter(list-0, decimal) '. '; }
> 
> You should change it to:
> 
> .ql-editor ol li::before { content: ""; }

May way to solve it is override .ql-editor class in my custom styleshee by this:

```
.ql-editor ol li:is([data-list='bullet'])::before {
  content: "•";
}
```

**Comment by danielmjordan** [comment]
Regardless of the presentational concerns of the list items inside the editor, the resulting markup is incorrect. Creating a "bulleted" list in Quill creates an `<ol>` element instead of a `<ul>`  element which is semantically incorrect and should be considered a bug. If the markup is rendered outside of the Quill editor the intended "bulleted" list will be incorrectly rendered as an ordered list. Some have found workarounds to the problem (see: https://github.com/frappe/frappe/pull/6783/files), but I believe this issue should be reopened and the underlying problem should be addressed.

**Comment by JasonSimms** [comment]
Standing upon the shoulders of those that come before me.  I had to expand the css class with not to exclude the ql editor because it was showing double bullets.  
```
ol li[data-list='bullet']:not(.ql-editor ol li[data-list='bullet']) {
  list-style-type: disc;
}
```

**Comment by NguyenLong-99** [comment]
- [ ]

**Comment by NguyenLong-99** [comment]
- [ *]

**Comment by NguyenLong-99** [comment]
- [ ] 1234

**Comment by quijimabob** [comment]
> Standing upon the shoulders of those that come before me. I had to expand the css class with not to exclude the ql editor because it was showing double bullets.
> 
> ```
> ol li[data-list='bullet']:not(.ql-editor ol li[data-list='bullet']) {
>   list-style-type: disc;
> }
> ```

Worked a charm for me - thank you!

**Comment by yudhaperwira17** [comment]
try this in your app


.ql-editor ol li:is([data-list="bullet"])::before {
    content: "•";
}

**Comment by devilgas** [comment]
this Copilot generated function will convert the UL and OL and also get rid of the quill css styles embedded into the LI elements:

```
function transformQuillLists(html) {
	const parser = new DOMParser();
	const doc = parser.parseFromString(html, 'text/html');
	
	const newDoc = document.createElement('div');
	const childNodes = Array.from(doc.body.childNodes);
	
	childNodes.forEach(node => {
		if (node.nodeType === Node.ELEMENT_NODE && node.tagName === 'OL') {
			const bulletItems = [];
			const orderedItems = [];
			
			node.querySelectorAll('li').forEach(li => {
				const type = li.getAttribute('data-list');
				const span = li.querySelector('span.ql-ui');
				if (span) span.remove();

				const cleanLi = li.cloneNode(true);
				cleanLi.removeAttribute('data-list');

				if (type === 'bullet') {
					bulletItems.push(cleanLi);
				} else if (type === 'ordered') {
					orderedItems.push(cleanLi);
				}
			});

			if (bulletItems.length > 0) {
				const ul = document.createElement('ul');
				bulletItems.forEach(li => ul.appendChild(li));
				newDoc.appendChild(ul);
			}

			if (orderedItems.length > 0) {
				const ol = document.createElement('ol');
				orderedItems.forEach(li => ol.appendChild(li));
				newDoc.appendChild(ol);
			}
		} else {
			newDoc.appendChild(node.cloneNode(true));
		}
	});

	return newDoc.innerHTML;
}
```

**Comment by ayushchars** [comment]
.ql-editor ol li:is([data-list="bullet"])::before {
content: "•";
}

add this line of code in main.css i will work
