### ISSUE TITLE
Ability to attach tooltip to body instead of a parent container

### ISSUE THREAD

**Issue by ram33** [quilljs/quill#2616]
Currently tooltip for setting links is attached to the parent container, which sometimes cutting off the edges. There is a [bounds](https://quilljs.com/docs/configuration/#bounds) options which will handle it to some extent. But fails when editor width is less. The only way we can reliably place tooltip is by attaching it to body. May be as a configurable option for the cases like above.

**Steps for Reproduction**
1. Open codepen: https://codepen.io/ram33/pen/OYpvEJ
1. Click Video embed

**Expected behavior**:
Tooltip should not cutoff the edges regardless of width and placement of the editor

**Actual behavior**:
Tooltip gets cutoff

**Platforms**:
Tested in macOS chrome. But seem to be the case in all browsers

**Version**:
1.3.6

There are couple of issues were raised and closed on the same topic. But I think it's a valid requirement. So raising it again.

https://github.com/quilljs/quill/issues/1103
https://github.com/quilljs/quill/issues/1100
https://github.com/quilljs/quill/issues/1994
https://github.com/quilljs/quill/issues/360

**Comment by econic** [comment]
Attaching potentially overflowing content (like tooltips, modals, etc...) is pretty standard.
Common practice is to attach to the body as last child, which should be a standard option in the quill config.

Definitely +1 for this one.

**Comment by FenoRC** [comment]
I found a solution for my situation:
when create the configuration object, set property _'bounds'_ with the **selector of quill container**.

**Example:**
```
const DEFAULT_CONFIG = {
        theme: 'bubble',
        bounds: '#quill-container-2'
};

new Quill('#quill-container-2', DEFAULT_CONFIG);
```

**Comment by ilya-spy** [comment]
@FenoRC as stated above here and in other related issue (https://github.com/quilljs/quill/issues/1100) **_bounds_** would not work if there is other content near your editor or the editor of insufficient width/height. Editor and neighboring containers may be on a well different levels in a page html tree, making it nearly impossible to put the tooltip bubble on top of other neighboring content (z-index neither will work because of that)

Right now, the only possible solution requires rewriting HTML tree so that quill container is on top of every neighbor.

The obvious and standard solution for that is to attach to body

**Comment by Artem-Schander** [comment]
Is this project even properly maintained at this point? I does not look that good.
I would create a PR for this, but I'm afraid it will not get merged. So I won't waste my time on that.
![2021-08-04-124914_905x527_scrot](https://user-images.githubusercontent.com/1243826/128168962-b9b40ae5-08f3-4de6-ba75-bc57795f191c.png)

**Comment by nullpaper** [comment]
The last 3.5 years of activity. I think it's safe to say this project is dead.
<img width="252" alt="dead" src="https://user-images.githubusercontent.com/95697016/161822130-f98be79f-42f5-4c88-9d4e-667d5ed0aaa0.png">

**Comment by MaratGallyamov** [comment]
I added those styles as the problem happens not only for left, but also for right. This solution works when width of toolbar is close to width of editor.

```css
.ql-bubble .ql-tooltip {
    left: 5%!important;
    width: 90%!important;
    margin-top: -6px;
}

.ql-bubble .ql-toolbar {
    text-align: center!important;
}

.ql-bubble .ql-tooltip-arrow {
    display: none!important;
}
```
