### ISSUE TITLE
the quill.focus() API dosen't work in mousedown event callback

### ISSUE THREAD

**Issue by tuzcwish** [quilljs/quill#2617]
I need to do something in the right-click handler.
the quill.focus() API dosen't work when a mousedown event is added to the editor.

**Steps for Reproduction**

1. Visit https://jsfiddle.net/tuzcwish/wypj5ubx/13/
2. click the padding area of the editor
3. the editor loses focus

**Comment by benbro** [comment]
Please add all the info requested in the issue template.
It's not clear what doesn't work.
