### ISSUE TITLE
Chrome/Safari Quill crashes in some cases when selecting all content and editing it

### ISSUE THREAD

**Issue by andrei-cacio** [quilljs/quill#2618]
In some cases when selecting the whole content with <kbd>Ctrl + A</kbd> and then pressing any character or number key the editor breaks and the only warning in the console is the one below:
![image](https://user-images.githubusercontent.com/5195546/57851404-27c7c680-77e9-11e9-81cf-869b89bb34bc.png)

I have managed to isolate one of those cases in a JSBin

**Steps for Reproduction**

1. https://jsbin.com/diqufizoza/3/edit?html,output
2. Select the whole "Hello World" content using <kbd>Cmd + A</kbd> or <kbd>Ctrl + A</kdb>
3. Press any character/numbers keyboard button

**Expected behavior**:

The pressed character should be inserted and the editor should function as normal

**Actual behavior**:

The editor breaks and the only way to start writing again is to blur and then focus back the editor container.

**Platforms**:

MacOS: Chrome 74, Safari 12.1

**Version**:

1.3.6

**Comment by benbro** [comment]
Please reopen if you can reproduce with [v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2)
https://v2.quilljs.com/standalone/full
