### ISSUE TITLE
Link format automatically adds 'http://'

### ISSUE THREAD

**Issue by koichirose** [quilljs/quill#262]
I'm referring to this:
https://github.com/quilljs/quill/blob/develop/src/modules/link-tooltip.coffee#L88

Since my app runs on multiple domains, I'd like to be able to link to "/something/somethingelse", without http://mydomain.com.

How can I customize it withouth editing quill's source?

**Comment by agraddy** [comment]
This is a feature that I would definitely like to see added.

**Comment by geeosh** [comment]
Also -  I want to set links to default to open in a new window, but had hoped I wouldn't have to edit source. I'd also request that this be turned into a module so that we could modify it if need be.

**Comment by jhchen** [comment]
Quill no longer adds the https:// and actually defaults to relative URLs but you can also customize this in the 1.0 beta:

```js
var Link = Quill.import('formats/link');
Link.sanitize = function(url) {
  // modify url if desired
  return url;
}
```

**Comment by ItamarSilverstein** [comment]
regarding the above CustomLinkSanitizer imlementation, is it possible to apply this santize logic to only one of the link types from the toolbar (the normal inline link), and not apply this CustomLinkSanitizer to all type of links available on the toolbar?

**Comment by Siddhesh-Nalawade** [comment]
> This is the way I fixed it and it includes a couple of other protocols to be accepted.
> 
> * First, it whitelist other custom protocols to be accepted as valid ones.
> * Then, we run the sanitize method that is already included on the Quill core, and based on the custom protocols list it will return the URL or `about:blank`.
> * Then, if this is an `about:blank` is because it did not pass the sanitization method. If we get the URL then we verify whether or not it has a protocol from the list and if not, then we append http:// and in that way we do not get relative URL or blank unless it is not being whitelisted:
> 
> * `https://your-site.com/www.apple.com`
> 
> ```js
> const Link = Quill.import('formats/link')
> // Override the existing property on the Quill global object and add custom protocols
> Link.PROTOCOL_WHITELIST = ['http', 'https', 'mailto', 'tel', 'radar', 'rdar', 'smb', 'sms']
> 
> class CustomLinkSanitizer extends Link {
>   static sanitize(url) {
>     // Run default sanitize method from Quill
>     const sanitizedUrl = super.sanitize(url)
> 
>     // Not whitelisted URL based on protocol so, let's return `blank`
>     if (!sanitizedUrl || sanitizedUrl === 'about:blank') return sanitizedUrl
> 
>     // Verify if the URL already have a whitelisted protocol
>     const hasWhitelistedProtocol = this.PROTOCOL_WHITELIST.some(function(protocol) {
>       return sanitizedUrl.startsWith(protocol)
>     })
> 
>     if (hasWhitelistedProtocol) return sanitizedUrl
> 
>     // if not, then append only 'http' to not to be a relative URL
>     return `http://${sanitizedUrl}`
>   }
> }
> 
> Quill.register(CustomLinkSanitizer, true)
> ```

@alexventuraio 
I am facing the same issue while using Quill in React. Where should I put this piece of code? This means in which file should I add this code?

**Comment by alexventuraio** [comment]
> regarding the above CustomLinkSanitizer imlementation, is it possible to apply this santize logic to only one of the link types from the toolbar (the normal inline link), and not apply this CustomLinkSanitizer to all type of links available on the toolbar?

It's been a while since I worked in this feature from Quill editor, but I barely remember that there is a way to know where the link is coming from, because another implementation from another teammate was only doing it for the ones pasted from the toolbar but not for the ones in the editor body that's why I took on it to make it work for both, so I would say yes, it will be possible but you need to deep a bit more on it.

**Comment by CapInSpase** [comment]
does anyone know how to not add a link if it doesn't match the whitelist?
