### ISSUE TITLE
how to programmatically remove editor from div

### ISSUE THREAD

**Issue by grimace** [quilljs/quill#2620]
I want to start the editor programmatically,  and then close it when I'm done.  I can start the editor but am not sure how to remove it from the div.

**Steps for Reproduction**
I start the editor like this, when I click on the div.
```
    this.editor = new Quill('#editarea', {
        modules: {
          toolbar: [
            [{ header: [1, 2, false] }],
            ['bold', 'italic', 'underline'],
            ['image', 'code-block']
          ]
        },
        placeholder: 'Enter Text Here...',
        theme: 'snow'  // or 'bubble'
      });

```
Is there a way to put a 'close' button on the editor panel.  Also how do I stop editing?

version is 1.3.6

**Comment by iammatthew2** [comment]
@grimace, this is similar to issue [1742](https://github.com/quilljs/quill/issues/).

Here is a [codepen example ](https://codepen.io/iammatthew2/pen/NZKmxm) of how you could do this.
