### ISSUE TITLE
Quill extends list issue

### ISSUE THREAD

**Issue by MirabileLucas** [quilljs/quill#2621]
Hello, i recently start to use quill and i want to make my own list (just for adding class to ul and li), but when i simply extends list i can't delete the list in the editor.

**Steps for Reproduction**

1. [https://codepen.io/mirabilelucas/pen/zQPzVG](https://codepen.io/mirabilelucas/pen/zQPzVG)
2. Click MyList in the toolbar
3. Press the backspace key

**Expected behavior**:
The list should be removed

**Actual behavior**:
The list persist

**Platforms**:
Firefox Quantum 66.0.5/ Win 10

Version: 1.3.6

**Comment by DmitrySkripkin** [comment]
That's by design. You added your own custom blot. You can add your own keyboard bindings or override default. Here is link to default binding that makes backspace work with default lists [keyboard.js#L310](https://github.com/quilljs/quill/blob/develop/modules/keyboard.js#L310)
