### ISSUE TITLE
color and background color issue

### ISSUE THREAD

**Issue by grimace** [quilljs/quill#2624]
I'm loading quill on the fly and removing it when I'm done editing so that I can do inline editing/preview.

I'm registering color and background color classes, because I'm not able to use inline color 
like this:
```
    let BackgroundClass = Quill.import('attributors/class/background');
    let ColorClass = Quill.import('attributors/class/color');
    Quill.register(BackgroundClass, true);
    Quill.register(ColorClass, true);
```

when I change the color of text it appends a color class, like this:
```
ql-color-#008a00
```
This does not color the text inside the editor and I'm at a loss for how to setup my css so that it will display the color correctly.   

What do I need to make my css look like in order for this to work?

my quill version is 1.3.6, I'm running on OSX with google chrome

**Comment by grimace** [comment]
after consulting the great oracle google:  **escaping the css name** works great, just in case anyone else encounters this difficulty, I essentially added to my css, here's an example:
```
.ql-color-\#e60000 {
	color: rgb(230, 0, 0);
}
```
then the mark up works out-of the box

**Comment by akshaybosamiya** [comment]
This can be also managed via using inline style.

e.g., 
`<strong style="color: rgb(230, 0, 0);">Hello</strong>` 

To use inline color like this,

```
let ColorStyle = Quill.import('attributors/style/color');
Quill.register(ColorStyle, true);
```
