### ISSUE TITLE
How to add custom image button on bubble theme

### ISSUE THREAD

**Issue by alditahir08** [quilljs/quill#2628]
Hi, i want to add a custom button to add an image for bubble theme, but it seems that i didn't find the tutorial about it. In bubble theme, the default way, user have to block the text in order to get the add image button shown, or drag-drop the image to the editor in order to add it.

i'm using vue and vue-quill-editor, but I'll also be happy to use pure JS as an example

**Comment by davidbludlow** [comment]
I also want a proper solution to this problem! The only (and insufficient) workaround I can find is to cut and paste the image into the bubble-themed editor.
