### ISSUE TITLE
how to format text

### ISSUE THREAD

**Issue by gengxueke** [quilljs/quill#2630]
when i click save button, i will validate Sensitive words，and i will format their color, like red to reminding he to correct this words.and when they delete some character of this word, their color will not change. but it doesn't works when i delete some character

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**:
editir will change by my operator, when i input a Sensitive words, it will changes red, when i delete , it will works correctly.
**Actual behavior**:

**Platforms**:
google
Include browser, operating system and respective versions

**Version**:
1.3.6
Run `Quill.version` to find out

**Comment by iammatthew2** [comment]
@gengxueke, can you provide a codepen example?
