### ISSUE TITLE
Set Editor into Iframe - Format and other functions not working

### ISSUE THREAD

**Issue by DPOLocalAaronO** [quilljs/quill#2633]
I'm building a site builder, and I want to use quill as my text editor. The site builder uses an iframe to hold the site being edited. I would like to include the quill script in my main document and initialize it on elements within the iframe. It seems to set up on the element within the iframe fine, but when I attempt to run a function on the Quill instance, i'm getting issues.

I've only tested getSelection() and format()

Neither seem to be functioning properly. getSelection(true) always returns null, and a simple format('bold', true) does nothing.

**Steps for Reproduction**

Initialize quill on an element within an iframe.

**Expected behavior**:
Work normally

**Actual behavior**:
Various functions don't work

**Platforms**:
Chrome, Windows 10

**Version**:
1.3.6

**Comment by greyepoxy** [comment]
I am seeing this as well, in my case I am trying to write cypress unit tests (the content under test is hosted in a sperate iframe from the spec code).

Most of the quill methods actually seem to work just fine its only the methods/events dealing with or requiring focus/selection that seem broken. My guess is that the source code is looking at its window/document object and not the window/document object for the component.

**Comment by greyepoxy** [comment]
so I was able to fix the problem (at least the problems I saw) by getting the `ownerDocument` from the root element here https://github.com/quilljs/quill/blob/develop/core/selection.js#L22, and then updating all of the uses of `document` in this file with the document I got from the `root.ownerDocument`

Will try and get a PR open in the next few days (unless someone beats me to it)

**Comment by fedekau** [comment]
Hi 👋  @greyepoxy I am experiencing the exact same issue but I would not like to fork the library, did you find any workaround without changing the source code? I have been trying but seems impossible 😞  and since the PR has not activity I am not sure if you or someone else is working on it

**Comment by greyepoxy** [comment]
Hi @fedekau no I did not figure out a workaround... 😞 As far as I can tell the PRs are good to go (well they were back in February, haven't looked recently) but have not seen any of the repository owners take a look at them yet.  Back in February, I didn't see much activity in this repository (although looks like there is a little activity now) so ultimately decided to use a different rich text editor. Currently using [prosemirror](https://prosemirror.net/), maybe that will work for your use case as well?

**Comment by dvkvarma** [comment]
+1

Still seeing the same issue in the latest release. Any plans to resolve this one ?

**Comment by weilderbeast** [comment]
anybody getting this to work? i have the same issue.
