### ISSUE TITLE
canonical way to get cursor at the end of the editor

### ISSUE THREAD

**Issue by julien-c** [quilljs/quill#2635]
Apologies if this is documented somewhere, I haven't been able to find a definitive answer.

Is it always the case that `quill.setSelection(quill.getLength(), 0);` will bring my cursor at the end of the editor?

i.e., are the output of `getLength()` and the parameter to `.setSelection()` comparable/consistent indices inside the editor?

**Comment by iammatthew2** [comment]
@julien-c , I don't think there is a canonical approach but your suggestion seems to work fine. Here is an example: `https://codepen.io/iammatthew2/pen/arxmOP`

**Comment by benbro** [comment]
Your code should work.

**Comment by meet-gangani** [comment]
@benbro @iammatthew2 
When you type between sentences, it doesn't work
