### ISSUE TITLE
Security Vulnerability (extend@3.0.1)

### ISSUE THREAD

**Issue by k-sai-kiranmayee** [quilljs/quill#2638]
Its a great library, but looks like there might be a security issue with the internal dependency _extend@3.0.1_

**Reference**:
https://app.snyk.io/vuln/npm:extend:20180424

**Screenshots**:
![image](https://user-images.githubusercontent.com/36036544/58883357-e5b0e700-86fb-11e9-8872-343fcb936b75.png)

**Version**:
Quill - 1.3.6

**Comment by k-sai-kiranmayee** [comment]
Hello :)
When can we expect the release with the fix for this and in which version if it is successfully merged?
Thank you!

**Comment by benbro** [comment]
Fixed in v1.3.7
