### ISSUE TITLE
No way to edit links in bubble theme

### ISSUE THREAD

**Issue by anumysore5** [quilljs/quill#2639]
I am using the latest version of Quill (1.3.6). But this does not provide a way to edit links in bubble themes(or I did not find any references that make this possible). Saw a reference to this issue 2 years ago - #1380 . Is the status of this feature still the same or is there a way to achieve editing links while using bubble theme that I am missing?

Would appreciate if anyone can point me in the right direction.

Thanks in advance.

**Comment by alecgibson** [comment]
It works fine in [this example][1].

[1]: https://codepen.io/alecgibson/pen/agZMbd?=true
