### ISSUE TITLE
Adding Custom Attributes

### ISSUE THREAD

**Issue by sebastiansandqvist** [quilljs/quill#2643]
In the default quill editor, when you click any link you get access to a tooltip that sets the href attribute. Is it possible to customize other elements, such as images, to display such a tool tip which lets you set attributes such as alt and className?

**Comment by iammatthew2** [comment]
@sebastiansandqvist, I think you could try instantiating the Quill tooltip as shown here: https://stackoverflow.com/questions/47149779/place-tooltip-in-quilljs

Doing something like the above but inside the blot you are interested in might work nicely. Happy to help more if you have a copepen you are working in.

**Comment by sebastiansandqvist** [comment]
Exactly what I was looking for. Thank you!
