### ISSUE TITLE
migrating to version 2.0.0-dev.3

### ISSUE THREAD

**Issue by FernandoLuizNemeChibli** [quilljs/quill#2647]
I've upgraded from 1.3.6 to 2.0.0-dev.3, but i've got:

> TypeError: this.quill.pasteHTML is not a function

Then I've changed the way I set to `this.quill.insertText`

Is there a way to set and get content as HTML in this version?

**Steps for Reproduction**

1. Have a project with a report model editing feature
2. Wish to insert a table
3. Upgrade to version 2
4. Change a single `pasteHTML` to `insertText`

**Expected behavior**:

Get my content as HTML and set my content from a HTML

**Actual behavior**:

I've saved once and got:
`<p>THIS IS A TEST</p><p><strong>A TEST I REPEAT</strong></p>
`
I've saved twice and got:
`<p>&lt;p&gt;THIS IS A TEST&lt;/p&gt;&lt;p&gt;&lt;strong&gt;A TEST I REPEAT&lt;/strong&gt;&lt;/p&gt;</p>
`

**Platforms**:

Chrome, Ubuntu 18

**Version**:

2.0.0-dev.3

**Comment by FernandoLuizNemeChibli** [comment]
Side question: Is there another way to get tables as a option?

**Comment by MuhammedAlkhudiry** [comment]
try using quill.clipboard.dangerouslyPasteHTML from [here](https://quilljs.com/docs/modules/clipboard/)
