### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by scottfr** [quilljs/quill#2648]
The third demo on the Quill landing page has a RTL button in the toolbar. However, it does nothing when clicked and it looks like it is broken.

**Comment by benbro** [comment]
I'm not sure why the button doesn't work on the landing page but here it works fine:
https://quilljs.com/standalone/full/

**Comment by benbro** [comment]
It should be {'direction': 'rtl'} instead of 'direction'
https://github.com/quilljs/quill/pull/2649

**Comment by benbro** [comment]
Fixed
