### ISSUE TITLE
Editing when Styled Text is Selected Deletes Random Text

### ISSUE THREAD

**Issue by scottfr** [quilljs/quill#2655]
**Steps for Reproduction**

1. Go to https://quilljs.com/
2. Go to either the 1st or 3rd demo in the demo carousel
3. Scroll down to the syntax highlight demo portion
4. With your mouse select exactly "new Quill" (don't select anything before or after it)
5. Type "x" (or another character, but not delete/backspace)

**Expected behavior**:

"new Quill" gets replaced with "x"

**Actual behavior**:

A large random [1] additional chunk of the line is deleted, "x" is not inserted, and focus on the editor is lost.

Console prints the error: `selection.js:294 addRange(): The given range isn't in document`.

Note that you can reproduce the same effect outside the syntax block by highlighting some text in paragraph and applying a text color. Then if you highlight from exactly the start of the color inline blot to beyond the end of the color blot and type "x" (or another character) the same issue can be reliably triggered.

[1] Not in the stochastic sense but in the sense I don't understand how Quill is selecting what to delete

**Comment by scottfr** [comment]
Here is a codepen:

https://codepen.io/scottfr/pen/LKLLpJ

The two things to check out are:

1. Delete one of the @'s. When Quill rehighlights it will correctly remove the styling from the rest of the tag. This works as expected
2. Select from the start of one of the @'s to the end of the line. (E.g. if the text is "This @tag is good" select: "This [@tag is good]"). Type something to replace the selection. The new text will retain the blot styling even after the highlighter runs again. This is incorrect and not what is expected

**Comment by benbro** [comment]
I can reproduce with Chrome 76 on Windows 7.
Firefox 68 works fine.

**Comment by haugstrup** [comment]
An even simpler repro:

* Go here: https://codepen.io/haugstrup/pen/RwwveLa
* Make the input say "~asd~ asd" (also works with `code` formatting)
* Select all text
* Hit "x" or any other letter

**Result:** Your character **will not be inserted**, the input will be **cleared and blurred** and your console will say `addRange(): The given range isn't in document`

**Comment by AmeeMorris** [comment]
We ran into the same issue and managed to solve it by adding our own custom strike blot. Instead of the `tagName` being set to just `'S'` setting it to `['S', 'STRIKE']` sorts it out. 

See here: https://codepen.io/ameemorris/pen/dyPoaRy
