### ISSUE TITLE
Make link popup always show placeholder (not selected text)

### ISSUE THREAD

**Issue by loonydevil** [quilljs/quill#2656]
Hello there, sry I'm more of a backend guy, atm trying to figure out how to make a link popup always show only placeholder but by now w/o much success. Any advices/directions are appreciated. Tnx and MTFBWY! : )

**Comment by iammatthew2** [comment]
@loonydevil, can you give more detail here? It would be helpful if you could share a codepen of what you have so for. Or just an example of something that does something similar to what you are trying to do.

**Comment by loonydevil** [comment]
Sure, what I needed is to show empty link popup no matter what text user selected. I ended up doing it this way:
```
        var SnowTheme = Quill.import('themes/snow');
        SnowTheme.prototype.constructor.DEFAULTS.modules.toolbar.handlers.link = function (value) {
            if (value) {
                var range = this.quill.getSelection();
                if (range == null || range.length === 0) return;
                var preview = this.quill.getText(range);
                if (
                    /^\S+@\S+\.\S+$/.test(preview) &&
                    preview.indexOf('mailto:') !== 0
                ) {
                    preview = "mailto:" + preview;
                }

                var tooltip = this.quill.theme.tooltip;
                tooltip.edit('link'); // add 'preview' as second param to show selected text
            } else {
                this.quill.format('link', false);
            }
        };
```
Don't know if there's a better way to do that but this one does the job. Next quest is to override save button call on the same popup :).

**Comment by iammatthew2** [comment]
@loonydevil, I think you can override the default by passing in a new handler for the link - like so: https://codepen.io/iammatthew2/pen/MMpBpX?editors=0010
