### ISSUE TITLE
Quill 2 losing data with innerHTML and getting too many breaklines.

### ISSUE THREAD

**Issue by FernandoLuizNemeChibli** [quilljs/quill#2658]
I've upgraded Quill 1 to 2 in my project and I'm persisting and retrieving the data as HTML with  `this.quill.root.innerHTML` so I could keep the previous data, but I'm getting so much complains about old data being lost, specially lists. I'm debugging now, searching the causes, until now I've found that `<p>` tags are generating `<br>` tags and so `<br>` are getting `<p>` too, if I save many times it gets bigger and bigger.

I'll try to keep this updated.

**Comment by FernandoLuizNemeChibli** [comment]
I've put this test in database with random typing:

`<p class="ql-align-justify
"><br></p><p class="ql-align-justify">eqrqwrqerqer</p><p><br></p><p class="ql-align-justify"><span style="color: rgb(34, 34, 34);">sjhslakhas:</span></p><ul><li>qwertyuiop</li><li>xcvbnm,</li><li>sfdxgfcghvhjbjk
lnçml</li><li>fhgjvbknlç</li></ul><p>hjkghljç:</p><ul><li>fgcvjhbkjnlkmçl</li><li>kçhjnlkmçl</li></ul><p>sdfxgfchjbk:</p><ul><li>kjbn</li><li>erytufghj</li></ul><p><br></p>`

Later got this, only by entering and exiting the page, without any editing:

`<p class="ql-align-justify
"><br></p><p class="ql-align-justify">eqrqwrqerqer</p><p><br></p><p class="ql-align-justify"><span style="color: rgb(34, 34, 34);">sjhslakhas:</span></p><p><br></p><p>hjkghljç:</p><p><br></p><p>sdfxgfchjbk:</p><
p><br></p><p><br></p>`

So all the `<ul>` and `<li>` are gone, but got  `<p><br></p>` instead.

**Comment by FernandoLuizNemeChibli** [comment]
Also, I've found out that empty `this.quill.root.innerHTML` is not empty at all, even if you set it like this `this.quill.root.innerHTML = ''`it will log out **`<p><br></p>`**. I'm starting to get annoyed by that (ó_ò)

**Comment by alecgibson** [comment]
Probably has something to do with the fact that Quill 2 no longer has a notion of `ol` and `ul`; it just [uses `ol`][1], and then sets the list type using the [`data-list` attribute][2].

If you want to migrate your data from Quill 1 to Quill 2, you'll need to replace instances of

```html
<ul>
  <li></li>
</ul>
```

with:

```html
<ol>
  <li data-list="bullet"></li>
</ol>
```

Alternatively, you can use `quill.convert({ html: myOldHtml })`.

Really you should probably be storing the JSON representation of your documents (`quill.getContents().ops`) rather than raw HTML, though.

[1]: https://github.com/quilljs/quill/blob/54fd8bede1567a5210db8f4c4c5db0d3f54b4c58/formats/list.js#L7
[2]: https://github.com/quilljs/quill/blob/54fd8bede1567a5210db8f4c4c5db0d3f54b4c58/formats/list.js#L12

**Comment by FernandoLuizNemeChibli** [comment]
Thank you very much for your response @alecgibson, but it says that there is no convert function for Quill instance, I've got this error:
`TypeError: this.quill.convert is not a function`
I found the function in the source code, but there is no sign of it in the official documentation, how do I use it correctly?

**Comment by alecgibson** [comment]
Sorry, I was thinking of the clipboard:

```javascript
const contents = this.quill.clipboard.convert(myHtml);
this.quill.setContents(contents);
```

**Comment by alecgibson** [comment]
As a side-note, if you're going to take this approach (which I still don't advise - you should work with ops to retain true semantics), you may be interested in [`quill.getSemanticHTML`][1]

[1]: https://github.com/quilljs/quill/blob/6d0719d01874bd498414fcf2ac111e9884107454/core/quill.js#L311-L314

**Comment by hakonleung** [comment]
> Sorry, I was thinking of the clipboard:
> 
> ```js
> const contents = quill.clipboard.convert(myHtml);
> quill.setContents(contents);
> ```
> 
> (This is basically reusing Quill's ability to parse HTML from the clipboard, which allows for things like different kinds of lists)

@alecgibson might solve the problem, you can set quill.root.innerHTML = html as well, cause quill has observed dom changing.
By the way, storing delta insteads of html is much more maintainable.
