### ISSUE TITLE
Quill getText with line breaks 

### ISSUE THREAD

**Issue by essivision** [quilljs/quill#2660]
**Expected behavior**:
Hi,
I wanna to get clear text from quill with line breaks `\n`. Now when I use `quill.getText()` return plain text without any key control and line break character. What should I do?

**Actual behavior**:
I need  to text with line breaks: `\n`

**Platforms**: Chrome 
**Version**: 1.3.5

**Comment by benbro** [comment]
Quill does return newlines with getText(). You even have this in the [test](https://github.com/quilljs/quill/blob/develop/test/unit/modules/history.js#L207).

**Comment by giray123** [comment]
Is there a workaround to accomplish this text?
