### ISSUE TITLE
Add an await when pasting

### ISSUE THREAD

**Issue by rgazelot** [quilljs/quill#2661]
Hello, I'm trying to ask the user to take a decision about the content he's trying to paste into quill. To do that, I extended the Clipboard `onPaste()` method and add a simple `await confirm()` (I'm using [react-confirm](https://github.com/haradakunihiko/react-confirm)). The modal pops and the user can make a decision, then I call `super.onPaste(e)`. Everything is fine from this point of view. 

Nevertheless my content is pasted into the editor when I'm waiting in my dial modal. This is due to Parchment which had instantiated a  `MutationObserver` into his ScrollBlot and it dispatches a `TEXT_CHANGE` event which will insert the raw pasted data into the editor.

The thing is, when I remove the `await` from my extended Clipboard's `onPaste(e)` method, this `MutationObserver` from Parchment is never triggered! 

I really don't understand where does this process comes from and why it triggers this `TEXT_CHANGE` event, and why the `await` in my `onPaste(e)` method is the reason why...

If somebody has any idea about this behavior and can help me?

**Comment by iammatthew2** [comment]
Do you have a codepen example? I'd like to dive into this.

**Comment by rgazelot** [comment]
@iammatthew2 Thanks for your interest, I'll try to expose the issue using a simple codepen. I'll keep you in touch of that ;)
