### ISSUE TITLE
extra break added before lists

### ISSUE THREAD

**Issue by zpydee** [quilljs/quill#2662]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**:

**Actual behavior**:

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by zpydee** [comment]
i'm using quill with the ngx-quill wrapper.

i've experienced an issue with quill when using lists.

if you have lists (ordered or not), and you add content to the editor, the component adds an extra break before the lists.

BEFORE:

<img width="713" alt="Screenshot 2019-06-26 at 15 48 01" src="https://user-images.githubusercontent.com/6129162/60185252-dc61f880-9829-11e9-9322-d735749bf06f.png">

AFTER:

<img width="872" alt="Screenshot 2019-06-26 at 15 48 51" src="https://user-images.githubusercontent.com/6129162/60185678-9ce7dc00-982a-11e9-9b42-3449ccfe8546.png">

Take note of extra space added before lists. An extra line is added each time I add content to the editor.

**Comment by zpydee** [comment]
can you please check if you can replicate this bug. perhaps it is the wrapper's issue?

**Comment by benbro** [comment]
Please include all the info requested in the issue template and try to reproduce in the [CodePen](https://quilljs.com/playground/).
