### ISSUE TITLE
[How to] drop embed (or html) inside quill editor from external source

### ISSUE THREAD

**Issue by Hideman85** [quilljs/quill#2668]
Hello quill's community,

I want to drag and drop into quill a embed (like image feature) currently I'm successful drop a text but I don't know how drop a embed or html that be parsed into embed.

Demo: https://codepen.io/anon/pen/jjZova

Thanks in advance for your further response.

**Comment by Hideman85** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API#Define_the_drag's_data we just need to set to `'text/html'` instead of `'text'` or `'html'` and it works fine!

Codepen demo updated!

**Comment by OctavioSI** [comment]
Hi, just to let you know that this was working fine up to Firefox 72.0.2, but it is not working anymore on Firefox version 73.0.1 (at least on Linux). I guess they made some changes on how drag and drop inside contenteditable fields work and I am trying to find a solution to this.

Dragstart and dragend work fine, but dragged elements are not actually dropped anymore.

**Comment by OctavioSI** [comment]
Just to let you know that after a lot of digging and testing, I was able to come up with a solution which is working for me on Firefox 73.0.1:

https://codepen.io/OctavioSI/pen/MWwmxyJ?editors=1111

**Comment by Manuele-Xavier** [comment]
<iframe width="560" height="315" src="https://www.youtube.com/embed/BoEKWtgJQAU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
