### ISSUE TITLE
Content-Security-Policy for unsafe-eval is broken

### ISSUE THREAD

**Issue by kniknak** [quilljs/quill#2670]
the latest version of Quill does not comply the `Content-Security-Policy` for `unsafe-eval`

Steps to reproduce:
* add the following headers to the nginx config:
```       
add_header "Content-Security-Policy" "default-src 'self' blob: data: * 'unsafe-inline'; font-src 'self' data: *";

add_header "X-Content-Security-Policy" "default-src 'self' blob: data: * 'unsafe-inline'; font-src 'self' data: *";
```
* require `quill` in the code: 
`import quill from "quill"`

**Platforms**:

nginx
Chrome, Mac OS

**Version**:

2.0.0.-dev.3

I believe that this is related to the `webpack` build configuration of `quill` dist since I can not reproduce the issue by manually building it from `node_modules`

**Comment by OperKH** [comment]
Have the same problem!

It is because current build makes `quill\dist\quill.js` with `eval` calls inside

**Comment by Rambou** [comment]
Is this issue fixed? Could we close it?
