### ISSUE TITLE
Cursor issue with inline blot

### ISSUE THREAD

**Issue by ibachar** [quilljs/quill#2671]
Hi,

I've an issue with the cursor when the direction is set to RTL (and alignment is to the right) with a custom Embed I've written. Cursor movement is all wrong when adding this Embed an moving back to the start of the line. This issue also happens with the built-in formula element

**Steps for Reproduction**

1. Visit [the formats page](https://quilljs.com/docs/formats/)
2. Click on the direction button to switch to RTL
3. Insert a formula with the default of e=mc^2
4. Move to the right. The cursor moves correctly.
5. Move once again to the right. Instead of placing the cursor before (to the right) the formula, the cursor goes up a bit.
6. Try moving left / right and the cursor movement is all wrong

**Expected behavior**:
The cursor should move in the same manner as when working with the direction set to LTR

**Platforms**:
Chrome 75, Windows 10.

**Version**:
1.3.6

**Comment by Azuf** [comment]
@ibachar have you found a solution for this since?

**Comment by ibachar-es** [comment]
@Azuf Unfortunately no
