### ISSUE TITLE
Selecting and changing headers does not work

### ISSUE THREAD

**Issue by akuji1993** [quilljs/quill#2672]
When changing text layout from "Normal" to "Heading X" while a line of text is marked, instead of the marked line, the first or last line get the new layout instead. 

**Steps for Reproduction**

1. Vist https://codepen.io/quill/pen/KzZqZx
2. Write a few lines of text
3. Mark a text line in the middle of your content
4. Make it a "Heading 2" instead of "Normal" from the headers dropdown

**Expected behavior**:
The marked line should become Heading 2

**Actual behavior**:
The first line or last line become Heading 2

**Platforms**:
MacOS Mojave, Chrome Version 75

(not reproducible in Firefox on MacOS, seems to be a Chrome issue)

**Version**: 1.3.6

**Comment by benbro** [comment]
I can't reproduce on Chrome 76 Windows 7. Can you share a screen capture showing the issue?

**Comment by akuji1993** [comment]
Hi, the bug seems to have disappeared in Chrome 76 on MacOS too. Chrome is apparently doing something different in the new version, I tried for 15 minutes now and can't reproduce it anymore :)
