### ISSUE TITLE
Selecting quill editor

### ISSUE THREAD

**Issue by echan00** [quilljs/quill#2673]
Is it possible to select an existing quill editor? 

For example, 
```
for(var k=0; k <= editors.length-1; k++){
  quill = new Quill(editors[k], {theme: 'snow', modules: {keyboard: {bindings: bindings}}});
}
```

is it possible to access one of the editors without having to reinitialize with `new Quill`, for example call `quill = Quill(existing_specific_id)`

**Comment by benbro** [comment]
There is no registry for quill instances in the [API.](https://quilljs.com/docs/api/) You need to keep track of quill instances in your app.

**Comment by echan00** [comment]
thanks!
