### ISSUE TITLE
How to manipulate words with references to a json file?

### ISSUE THREAD

**Issue by balbinott** [quilljs/quill#2681]
Im new to quill and im trying to fill my editor with some values from a json file, but i want to have some kind of index for each word, in the future i will be iterating over this words using the current time from a video witch contains this transcribing words...So on this currentTimeEvent, it will update the currentSelection and mark(highlight) this word... if i could get the word index i can relate to the origin file. Sorry for my english and thanks in advance!

**Comment by benbro** [comment]
Please read the [API docs](https://quilljs.com/docs/api/) and ask questions on StackOverflow.
