### ISSUE TITLE
selection-change not triggered when adding a new line

### ISSUE THREAD

**Issue by fredgate** [quilljs/quill#2683]
**Steps for Reproduction**

1. In the playground (https://quilljs.com/playground/), add `quill.on('selection-change', console.log);`
2. Open the browser console
3. In the quill editor, type some text and press the `Enter` key to add a new line

**Expected behavior**:
The new selection is triggered when caret changed to a new line.

**Actual behavior**:
No selection is triggered when caret changed to a new line. No text is written to the console when the `Enter` was pressed. Log appears in console when we change line using up arrow or down arrow keys.

**Platforms**:
Firefox 68, Linux Ubuntu

**Version**:
Last version (playground) : 1.3.6

**Comment by Jeandcc** [comment]
BUMP
