### ISSUE TITLE
Inline margin and font-weight styles for email

### ISSUE THREAD

**Issue by bestrong89** [quilljs/quill#2684]
Hello,

I would like to use quill as a minimal email content editor.

Is there a way to automatically inline styles like margin, font-weight, etc that are set in quill, so the content will look the same outside the editor?

For example, the `<h1>` tags all have a font-weight of 400 and a font-size of 2em as set in the css stylesheet, however, this styling is lost outside the editor.

It is not safe to use embedded styles or attached stylesheets in email, so everything needs to be inlined.

Any suggestions?

Thanks!
Ben

**Comment by benbro** [comment]
It's explained in the guide:
https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline

**Comment by bestrong89** [comment]
I have the following code set, however I cannot figure out how to have the margins and the font-weight set in the stylesheet transfer over... 


      let AlignStyle = Quill.import('attributors/style/align')
      let BackgroundStyle = Quill.import('attributors/style/background')
      let ColorStyle = Quill.import('attributors/style/color')
      let DirectionStyle = Quill.import('attributors/style/direction')
      let FontStyle = Quill.import('attributors/style/font')
      var SizeStyle = Quill.import('attributors/style/size');
      SizeStyle.whitelist = ['10px', '20px', '40px'];

      Quill.register(SizeStyle, true);
      Quill.register(AlignStyle, true);
      Quill.register(BackgroundStyle, true);
      Quill.register(ColorStyle, true);
      Quill.register(DirectionStyle, true);
      Quill.register(FontStyle, true);

**Comment by benbro** [comment]
[Bold](https://github.com/quilljs/quill/blob/develop/formats/bold.js) is defined as inline blot.
You'll need to create a custom style attributor instead. Try to use the size or color attributors as an example.
Not sure what you mean by margins.
Please ask questions like this in StackOverflow or search previous issues for examples.
