### ISSUE TITLE
Formats overwrite custom styles when applied to part of a line/op

### ISSUE THREAD

**Issue by methoil** [quilljs/quill#2687]
I had to add custom font sizes in pt to the editor as the default small/med/large/huge were not sufficient for out project. I found a bug where when you have multiple lines of text with the size set, and you apply another style supported by the editor such as bold, the size will get wiped out if applied to part of the line. The size remains when the style is applied to the whole line:

![image](https://user-images.githubusercontent.com/47762021/61559422-a6ceba80-aa37-11e9-829d-286b68887f0e.png)
![image](https://user-images.githubusercontent.com/47762021/61559424-a9311480-aa37-11e9-9d02-e45411178346.png)

Expected behavior is for the existing size to be retained. Curiously this doesn't happen for single lines or for text in bullet lists.

As a possible workaround, I found that if I override the style handler and manually update the delta I can get the size to not be wiped out. Does this seem like a good solution or is there's another approach?

**Platforms**:
Chrome 75.0.3770.100, Mac 10.14.5
Include browser, operating system and respective versions

**Version**:
Quill 1.3.6

**Comment by Yexan** [comment]
It might be due to the way you implemented your custom size in pt.
I'll show you how I implemented custom sizes in px if it can help you.

- `available-font-sizes.ts`
Here I just define an array of values from 6 to 76 and an other with values in px ('6px' to '76px')
```typescript
export const AvailableFontSizes = [
  ...Array(71).keys()
].map(
  (x) => x + 6
)

export const getFonstSizeValue = (size: number): string => {
  return `${ size }px`
}

export const AvailableFontSizeValues = [
  ...AvailableFontSizes
].map(getFonstSizeValue)
```

- Where I attach my quill editor to the DOM
```typescript
import { AvailableFontSizes } from '../config/available-font-sizes'

const size = Quill.import('attributors/style/size')
size.whitelist = AvailableFontSizeValues
Quill.register(size, true)
```

- In the template
Then In my custom toolbar template I just create the select / options according to this config 
Note that I'm using Angular but you can use any templating framework to avoid to manually create / maintain 76 DOM node by hand

```html
<select class="ql-size">
  <ng-container *ngFor="let size of availableFontSizes">
    <option [value]="getSize(size)"></option>
  </ng-container>
</select>
```

In my component fiule I've just declared `availableFontSizes = AvailableFontSizes` and  `getSize = getFonstSizeValue` from my `available-font-sizes.ts` file

I hope i can help, let me know if you have some questions 😊

**Comment by Yexan** [comment]
@methoil any updates ?

**Comment by Yexan** [comment]
PS: if you set some formats manually it my be because of this : https://quilljs.com/docs/api/#format 
By default the source format is `api`, try to set `source` to `user` :
```javascript
quill.format('color', 'red', 'user');
```

**Comment by methoil** [comment]
Hey @Yexan thanks for the answer. I am indeed setting up the font sizes in essentially the same way that you are and I found the issue which is actually caused elsewhere. I had to fix a problem where the bullet point was to updating with the font size - it would always stay tiny regardless of the font size, it does this in main Quill demo as well. 

To do this I had to extend the list item blot to manually set its size, and for that to work, you need a custom size attributor with the scope set to BLOCK instead of INLINE:

```typescript
const customSizeAttributor = new Parchment.Attributor.Style('custom-size', 'font-size', {
    scope: Parchment.Scope.BLOCK,
  });
Quill.register(customSizeAttributor);

```

What was causing the issue I reported here was setting the customSizeAttributor to block - even though it sets the style `custom-size` instead of just `size`, this was messing up the `size` for text outside of bullet points. 

I was quite stumped as to the problem, however by redefining the `size` attributor as INLINE after setting the `custom-size` BLOCK one, it fixes the size overriding somehow:

```typescript
  // redefine the normal size attributor - with just above bug that kills text size comes up
  const normalSizeAttributor = new Parchment.Attributor.Style('size', 'font-size', {
    scope: Parchment.Scope.INLINE,
  });
  Quill.register(normalSizeAttributor);
```

I would think that defining the `custom-size` attributor should not be causing a problem in the first place so this seems like some strange functionality with quill.

**Comment by methoil** [comment]
On an unrelated note, I also had that CSS where you set all the font sizes to the `quill-picker` classes, however when I took that out I don't see any change in functionality - setting the sizes still works fine. Do you know if it's actually needed and what it's supposed to do?

**Comment by Yexan** [comment]
Sweet ! 
Well sure sorry for the confusion about the CSS part, it's because I use ngx-quill wich is an angular 2+ wrapper lib for QuillJs and when you define a custom toolbar the DOM is replaced like this :
```html
<select class="ql-size">
  <ng-container *ngFor="let size of availableFontSizes">
    <option [value]="getSize(size)"></option>
  </ng-container>
</select>
```
to 
```HTML
<span _ngcontent-jxe-c3="" class="ql-size ql-picker ql-expanded">
  <span class="ql-picker-label ql-active" tabindex="0" role="button" aria-expanded="true" aria-controls="ql-picker-options-1" data-value="30px">
  <svg viewBox="0 0 18 18"> <polygon class="ql-stroke" points="7 11 9 13 11 11 7 11"></polygon><polygon class="ql-stroke" points="7 7 9 5 11 7 7 7"></polygon> </svg>
  </span>
  <span class="ql-picker-options" aria-hidden="false" tabindex="-1" id="ql-picker-options-1"> 
    <span tabindex="0" role="button" class="ql-picker-item" data-value="6px"></span>
    <span tabindex="0" role="button" class="ql-picker-item" data-value="7px"></span>
    <span tabindex="0" role="button" class="ql-picker-item" data-value="8px"></span>
    ...
    <span tabindex="0" role="button" class="ql-picker-item" data-value="76px"></span>
  </span>
</span>
```
As you can see, it replace the "buttons" of the custom select with elements with `data-value` but the span content is empty. 
So the CSS describe before is to avoid to have an empty select list, it just set the content of the span with the right value :)

**Comment by methoil** [comment]
I see that makes sense; I'm just setting the size selections on the toolbar directly, with the base Quill, and it's working for what I have now.

**Comment by pdkovacs** [comment]
@methoil 
> To do this I had to extend the list item blot to manually set its size, and for that to work, you need a custom size attributor with the scope set to BLOCK instead of INLINE

What do you mean by "manually" here? (How did you fix the bullet point size problem?)
