### ISSUE TITLE
Adding link in toolbar is not working as requirred

### ISSUE THREAD

**Issue by sudoStatus200** [quilljs/quill#2689]
I want to create a hyper link but can't do it.

**This is what working**:

![link2](https://user-images.githubusercontent.com/51601150/61610576-26969800-ac77-11e9-981b-3bfb9d53d944.gif)

**I  want this work too to create hyperlink**:
![link1](https://user-images.githubusercontent.com/51601150/61610596-344c1d80-ac77-11e9-9295-11e516c73061.gif)

**Platforms**:

browser :chrome
Working with in angular

Using quill through ngx-quill wrapper.

Author of ngx-quill suggested to ask here

**Version**:

Run `Quill.version` to find out

Quill version: `"quill": "^1.3.6",`

Thanks,

**Comment by hakonleung** [comment]
Write a inserting link popup with text and link input, using code below after committing.
```js
const r = quill.getSelection(true)
quill.updateContents(new Delta().retain(r.index).delete(r.length).insert(text, {link}))
```

**Comment by volser** [comment]
@sudoStatus200  If you want to get working as you required, just override handler
https://quilljs.com/docs/modules/toolbar/

**Comment by MinhDuc1611** [comment]
[ttttttttttttt](tttttttttl)
