### ISSUE TITLE
Delete Image Keyboard Events

### ISSUE THREAD

**Issue by sclswin** [quilljs/quill#2692]
I wanted to stop deleting pictures with Backspace, But the keyboard binding event is not valid for deleting pictures。

`quill.keyboard.addBinding({ key: 'backspace'}, function(range, context) {
                console.log(context)
            });`

**Comment by hakonleung** [comment]
In fact, not every binding would trigger when you enter backspace, module keyboard`s source code will show you the reason. You can rewrite keyboard to solve you problem, for example, rewriting constructor and addBinding before default backspace binding.

**Comment by sclswin** [comment]
> In fact, not every binding would trigger when you enter backspace, module keyboard`s source code will show you the reason. You can rewrite keyboard to solve you problem, for example, rewriting constructor and addBinding before default backspace binding.

`<p><img src="a.jpg"></p>`
HandleBackspace () method
Only formats are available，Unrecognizable tagName
The line variable is the P tag。
`function handleBackspace(range, context) {
  console.log(context)
  if (range.index === 0 || this.quill.getLength() <= 1) return;
  let [line, ] = this.quill.getLine(range.index);
  console.log(line)  
  let formats = {};
  if (context.offset === 0) {
    let [prev, ] = this.quill.getLine(range.index - 1);
    if (prev != null && prev.length() > 1) {
      let curFormats = line.formats();
      let prevFormats = this.quill.getFormat(range.index-1, 1);
      formats = DeltaOp.attributes.diff(curFormats, prevFormats) || {};
    }
  }
  // Check for astral symbols
  let length = /[\uD800-\uDBFF][\uDC00-\uDFFF]$/.test(context.prefix) ? 2 : 1;
  this.quill.deleteText(range.index-length, length, Quill.sources.USER);
  if (Object.keys(formats).length > 0) {
    this.quill.formatLine(range.index-length, length, formats, Quill.sources.USER);
  }
  this.quill.focus();
}`
Can you give me an example?

**Comment by sclswin** [comment]
Add 
if(leafStart.domNode.tagName=='IMG'){ 
         evt.preventDefault();
         Return false;
       }
to the listen method，solved
Can also judge keyboard events
