### ISSUE TITLE
leaf.position is not a function

### ISSUE THREAD

**Issue by 100cm** [quilljs/quill#2694]
set selection make an error like this:

![image](https://user-images.githubusercontent.com/12691638/61775160-f4c63280-ae2a-11e9-85f2-01f83f856cd9.png)

**Comment by 100cm** [comment]
![image](https://user-images.githubusercontent.com/12691638/61775195-060f3f00-ae2b-11e9-91b4-94146374edc9.png)

**Comment by 100cm** [comment]
quill v1.3.6 ,how to solve this?

**Comment by benbro** [comment]
Please include all the info requested in the issue template.
