### ISSUE TITLE
Link tooltip getting hidden in bottom

### ISSUE THREAD

**Issue by NishantVerma12** [quilljs/quill#2695]
![Quill](https://user-images.githubusercontent.com/35217143/61844457-1bcd4480-aebd-11e9-9561-d35bbe2b48af.png)
I am trying to add link but when I select the boundary text the link tooltip is getting cut by the edges can anyone suggest me a solution.

**Comment by benbro** [comment]
Share all the info requested in the issue template.

**Comment by NishantVerma12** [comment]
So there are few points:-

1-  I want both link tooltip and selected text keep visible when adding the link(means it should not getting hide as in the given screenshot).

2-  That tooltip should be hide if user click only on remove option given on tooltip means tooltip remains visible if user clicks anywhere inside the window.


I hope that info is sufficient to understand.
![Template](https://user-images.githubusercontent.com/35217143/63567303-9a85d200-c58e-11e9-8f3f-dd587833f6f3.png)


Please reply with in the day.
