### ISSUE TITLE
Insert an image using a keybinding

### ISSUE THREAD

**Issue by sebastiansandqvist** [quilljs/quill#2702]
I would like to trigger my image format (which opens the “browse files” menu and adds the image to the editor after uploading it) whenever a keyboard shortcut is executed. I tried the following, but without any success:

```js
quill.keyboard.addBinding({
  key: 'g',
  shortKey: true
}, (range, context) => {
  quill.format('image', true);
});
```

I can confirm that the keybinding is firing, but this fails to trigger the `image` format. The functionality I would like is for this to behave exactly the same way that clicking the “image” icon in the toolbar behaves. I suspect I am just using the wrong arguments in `quill.format()`. Can anyone provide any guidance here?

**Comment by benbro** [comment]
[format](https://quilljs.com/docs/api/#format) formats the text at user's current location. It doesn't open the file dialog.

You need to open the browser file dialog and handle the change vent.
[Code](https://github.com/quilljs/quill/blob/1.3.6/themes/base.js#L121) in version 1.3.6.
[Uploader module](https://github.com/quilljs/quill/blob/develop/modules/uploader.js) in master.
