### ISSUE TITLE
Quill 2.0 tables UI

### ISSUE THREAD

**Issue by volser** [quilljs/quill#2704]
Does Quill 2.0 provide any UI to edit table, like add, remove columns/rows...?
I'm wondering is it planned or not?

P.S. I saw this module https://github.com/soccerloway/quill-better-table

**Comment by benbro** [comment]
Table support in dev is discussed in this issue but the codepen doesn't have table UI.
https://github.com/quilljs/quill/issues/117#issuecomment-401713569
