### ISSUE TITLE
code-block incorrectly saved in Delta object

### ISSUE THREAD

**Issue by DPerkunas** [quilljs/quill#2709]
Code-block isn't saved in the correct spot inside delta object/array via `quill.getContents()`. Something I'm missing?

**Steps for Reproduction**

1. Create code-block in editor (the </> icon), codeblock should appear with a black background.
2. console log the `quill.getContents();`
3. Look at console to see incorrect object.

**Expected behavior**:
`{"ops":`
`[`
`{"insert":"this is a test\n"},`
`{"attributes":{"code-block":true},"insert":"this is a code-blocks\n"},`
`{"insert":"this is not a code-block. \nend test\n\n"}`
`]`
`}`

**Actual behavior**:
`{"ops":`
`[`
**`{"insert":"this is a test\nthis is a code-blocks"},`**
`{"attributes":{"code-block":true},"insert":"\n"},`
`{"insert":"this is not a code-block. \nend test\n\n"}`
`]`
`}`

**Platforms**:
Mac OSX, Chrome 75.0.3770.142 (Official Build) (64-bit)

**Version**:
1.3.6

**Comment by DPerkunas** [comment]
To add to this, I tried to change the 'pre' tag and removed classes to see if it was styling involved. But no matter what, it seems that it's not grabbing the pre tag to put in as an array/object for delta, it's only grabbing the `\n` from that row.

**Comment by volser** [comment]
it's not an issue, block formats are applied to `\n`

**Comment by DPerkunas** [comment]
But that means I cannot do any of the content
`Like this ` 
because the code itself isn't captured, only the \n is. I'm not saying the \n is the issue, I'm saying the code meant to be inside the code-block itself isn't captured.

**Comment by volser** [comment]
block formats are applied to all content before line line

**Comment by benbro** [comment]
@volser thank you for your answer.
