### ISSUE TITLE
Link Tooltip is getting hidden

### ISSUE THREAD

**Issue by NishantVerma12** [quilljs/quill#2711]
I want to keep alive  link tooltip when click anywhere inside the editor but it is getting hidden how to fix ?  any help would be appreciated

**Comment by NishantVerma12** [comment]
Any help ?

**Comment by benbro** [comment]
The link tooltip is hidden when it lose focus. I'm not sure how you want to hide it but you can try to [extend the theme](https://quilljs.com/docs/themes/).
Next time please include all the info requested in the issue template.
