### ISSUE TITLE
deleteText causing unexpected result

### ISSUE THREAD

**Issue by lisadeng** [quilljs/quill#2712]
Hello everyone,
When deleting my customized blot which extended from blockEmbed, I came across a weird problem, as follows:
![image](https://user-images.githubusercontent.com/22950019/62530904-f4d72100-b873-11e9-9cb4-8277198748ed.png)
I have some text, images and my customized blot in the editor, deleting the customized blot with api deleteText will cause the part in the blue rectangle ( seems the part after the blot ) being deleted as well. Not sure why.
Any suggestions?

Thanks!

**Comment by benbro** [comment]
Please list the steps to reproduce with the video format which extends BlockEmbed. If you can't reproduce it, it's a bug in your custom blot.
