### ISSUE TITLE
link toolbar error

### ISSUE THREAD

**Issue by sangemi** [quilljs/quill#2713]
THis is my toolbar option. and there is something wrong about LINK 

    toolbar: [
                            [{ 'header': 1 }, { 'header': 2 }],
                            ['blockquote', 'code-block'],
                            [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                            [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
                            [{ 'align': [] }],
                            ['bold', 'italic', 'underline', 'strike'],
                            [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
                            [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
                            ['link', 'image'],
                            ['clean'],
                            ['showHtml']
                        ]

**Actual behavior**:

1. Write content.
2. select some text and click LINK button, and then, "ENTER link: _________ Save" floating bar id appeared.
3. type some word at text input.
4. When I press 'enter' (by keyboard), it is OK
4-1. When I click the 'SAVE' button (by mouse), all content would be deleted. 
4-2. When I click the area arount "ENTER LINK" text, , all content would be deleted too.

**Version**:
"vue-quill-editor": "^3.0.6",
    "quill-image-compress": "^1.0.1",
    "quill-image-drop-module": "^1.0.3",
    "quill-image-resize-module-mended": "^3.1.2",

**Comment by benbro** [comment]
Can you reproduce the issue in the [demo](https://quilljs.com/)? If not, it's a bug in your code or custom module you use.

**Comment by aarshit-paladiya** [comment]
wda

**Comment by aarshit-paladiya** [comment]
<div class="col-md-12">
                            <label for="jobDescription" class="form-label">
                                Job Description<span class="text-danger">*</span>
                            </label>
                            <div id="jobDescription"></div>
                            <input type="hidden" name="description"
                                   value="{{ old('description', @$job->description) }}"/>
                            @error('description')
                            <div class="text-danger">{{$message}}</div>@enderror
                        </div>



let quill = new Quill('#jobDescription', {
            modules: {
                toolbar: [
                    ['bold', 'italic'],
                    ['link', 'blockquote', 'code-block', 'image'],
                    [{list: 'ordered'}, {list: 'bullet'}]
                ]
            },
            placeholder: 'Add job description',
            theme: 'snow'
        });

**Comment by aarshit-paladiya** [comment]
<div class="col-md-12">
                            <label for="jobDescription" class="form-label">
                                Job Description<span class="text-danger">*</span>
                            </label>
                            <div id="jobDescription"></div>
                            <input type="hidden" name="description"
                                   value="{{ old('description', @$job->description) }}"/>
                            @error('description')
                            <div class="text-danger">{{$message}}</div>@enderror
                        </div>
                        
                         <script src="{{asset('libs/quill/quill.min.js')}}"></script>
    <script src="{{asset('libs/nouislider/nouislider.min.js')}}"></script>
    <script>
        let quill = new Quill('#jobDescription', {
            modules: {
                toolbar: [
                    ['bold', 'italic'],
                    ['link', 'blockquote', 'code-block', 'image'],
                    [{list: 'ordered'}, {list: 'bullet'}]
                ]
            },
            placeholder: 'Add job description',
            theme: 'snow'
        });
