### ISSUE TITLE
Key bindings don't affect into toolbar SNOW type.

### ISSUE THREAD

**Issue by nazarposhta** [quilljs/quill#2714]
When I'm pressing shortcut for bold, italic, underline or any another bindings, going to apply **bold** for example style for selected text, my "snow" toolbar doesn't change button "B" into active. It changes only when I'll focus on that part of text on the next time. However it works in the opposite direction, active style is disappearing when I press shortcut on already styled part of text.

Quill 1.3.6
Chrome 76 / Safari 12.1.2 / Firefox 68.0.2
macOS 10.14.6

**Comment by benbro** [comment]
I can't reproduce. Works for me:
Quill 1.3.6
Firefox 68 / Chrome 76
Windows 7.

Please include all the info requested in the issue template.
