### ISSUE TITLE
The image upload doesn't validate that it IS an image format

### ISSUE THREAD

**Issue by RichardNeill** [quilljs/quill#2715]
One of my users attempted to insert an image file (using the "image icon") that was in fact an 8MB word document. Quill does not complain about this (it does show a "broken image") and the result is that the saved document contains a massive binary blob of garbage. 

I think Quill should validate that images are really images (or at least check the file extension is gif,jpg,png,jpeg,bmp,svg,svgz) and maybe warn if the file exceeds 2MB. 

Thanks

**Comment by benbro** [comment]
In master, the [uploader module check](https://github.com/quilljs/quill/blob/develop/modules/uploader.js#L30) if the file extension is in the list of mimetypes.

The [base theme](https://github.com/quilljs/quill/blob/1.3.6/themes/base.js#L129) in version 1.3.6 doesn't have this check. You can create a [custom image handler](https://quilljs.com/docs/modules/toolbar/#handlers) and add this check.

**Comment by Yehuda-Zvi** [comment]
i have the snow theme, and the same problem exist. 
what is the master theme that do this check?
