### ISSUE TITLE
Copying text from PPT to quill editor becomes the form of a picture.  

### ISSUE THREAD

**Issue by ceyio** [quilljs/quill#2717]
1 Chrome will have this problem, IE browser does not have this problem.

Chrome browser
![image](https://user-images.githubusercontent.com/38208580/62842112-34719300-bce2-11e9-92c2-4a3a740c1e56.png)

IE browser
![image](https://user-images.githubusercontent.com/38208580/62842329-eeb5ca00-bce3-11e9-95d3-80b939d047af.png)

2 If you cancel the ability to copy pictures, copying text from PPT is no problem
3 Copying text from word and Excel are not faulty

**Comment by johnfau** [comment]
I have the same problem, how did you solve it ?
