### ISSUE TITLE
I want to change default formula editor with mathjax formula editor

### ISSUE THREAD

**Issue by ngcgolf11** [quilljs/quill#2719]
I want to change default formula editor with mathjax formula editor i want to write formula becoz  current formula has only 1 for maths and use katex i want have an ehanced version so thats why i am asking how to change the defualt formula editor while using this one. or chg editor area to formaula while typing formula please help

**Comment by benbro** [comment]
You can try to [override](https://quilljs.com/guides/how-to-customize-quill/#content-and-formatting) the [formula format](https://github.com/quilljs/quill/blob/develop/formats/formula.js) and render the formula with mathjax instead of katex.
