### ISSUE TITLE
When try to work on React.createPortal Quill is not rendering anything under div class={quill}

### ISSUE THREAD

**Issue by umer1989** [quilljs/quill#2720]
I am opening new window from my react app using React.createPortal. I am rendering Quill on this new window. But under div class={"quill"} blank div is present. Not rendering my content and nothing is visible.

I found some error in console this might give hint to someone
Error is : permission denied this.container.classlist.add(ql-container)

**Steps for Reproduction**

I cant post my code. But you can try using createPortal

**Expected behavior**: Quill should render my content

**Actual behavior**: Blank div under div class="quill" is rendering

**Platforms**: React 16

IE 11, windows 10

**Version**: 1.3.3

**Comment by m-rutter** [comment]
If I had to guess you might want to read about React refs: https://reactjs.org/docs/refs-and-the-dom.html

```jsx

class QuillContainer extends React.Component {
  constructor(props){
    super(props);
    this.myRef = React.createRef();
  }

  componentDidMount() {
    this.quill = new Quill(this.myRef, 
      theme: 'snow'
    })
  }

  render() {
    return <div ref={this.myRef}></div>
  }

}


```
