### ISSUE TITLE
quill.focus()

### ISSUE THREAD

**Issue by gkiosov** [quilljs/quill#2721]
Hello!

**Quill v.1.3.** We have an issue with the `quill.focus()` behaviour in iOS Safari.

1. We have a «Write comment» button without opened Quill editor.
2. When user pressing it, we open the Quill editor and set focus on it by calling `quill.focus()`.
3. It works well in desktop browsers but not working in iOS: the keyboard is not popping up and user don't see flashing text input cursor in the editor. So, he need additional tap on the Quill editor field to call the keyboard and text input cursor.

We tried to use `quill.setSelection(0, 0)` also but it doesn't work as well.

Any solution or advice?

**Comment by benbro** [comment]
A user interaction is needed to show the keyboard on iOS Safari.
Next time please include all the info requested in the issue template and share a minimal CodePen example showing the issue.

**Comment by FlashTang** [comment]
@benbro 
seems quill.focus() is not working in wkwebview
Is the user interaction also needed in wkwebview (ios) ?
