### ISSUE TITLE
Pasted image won't get uploaded

### ISSUE THREAD

**Issue by ile** [quilljs/quill#2722]
**Steps for Reproduction**

1. For some image, do "copy image" in a browser 
2. Paste it into Quill editor

**Expected behavior**:

It should get uploaded in this code branch: https://github.com/quilljs/quill/blob/develop/modules/clipboard.js#L151

**Actual behavior**:

It gets pasted in this code branch: https://github.com/quilljs/quill/blob/develop/modules/clipboard.js#L153

**Why**:

Because the `html` variable contains the pasted image in a format like this:

```
"<meta http-equiv="content-type" content="text/html; charset=utf-8"><img src="https://www.example.com/image.jpg"/>"
```

I would think the image should get uploaded instead if the `files.length > 0` even if the html is set.

**Comment by benbro** [comment]
I can't reproduce. Working for me
Firefox 68
Chrome 76
Windows 7
Quill 1.3.6

Please include all the info requested in the issue template.
