### ISSUE TITLE
Android and iOS inconsistent behaviour for custom embed.

### ISSUE THREAD

**Issue by smontlouis** [quilljs/quill#2725]
It's possible to edit a Custom Embed in Android, the backspace doesn't delete the Block. It's working fine on iOS. I'm using React-Native and a Webview to render the quill editor.

**Steps for Reproduction**
Create a custom block.

**Expected behavior**:
<img src="https://im4.ezgif.com/tmp/ezgif-4-10ad4852e39b.gif" width="300">

**Actual behavior**:
<img src="https://im4.ezgif.com/tmp/ezgif-4-5a750458b008.gif" width="300">

**Platforms**:
Android
iOS

**Version**: 1.3.0

**Code**
```
import Quill from './quill.js'
const Embed = Quill.import('blots/block/embed')

class VerseBlock extends Embed {
  static blotName = 'block-verse'
  static tagName = 'div'
  static className = 'block-verse'

  static create (data) {
    let node = super.create(data)
    const { title, content, version, verses } = data
    node.setAttribute('data', JSON.stringify(data))

    ReactDOM.render(
      <Verse {...{ title, content, version, verses }}
      />, node
    )

    return node
  }

  static formats (domNode) {
    const data = domNode.getAttribute('data')
    return JSON.parse(data)
  }

  static value (domNode) {
    const data = domNode.getAttribute('data')
    return JSON.parse(data)
  }
}

Quill.register(VerseBlock)
```

**Comment by benbro** [comment]
The description is not clear and the images are missing.
Please include all the info requested in the issue template.
