### ISSUE TITLE
Toolbar is broken when rendered inside <label> element

### ISSUE THREAD

**Issue by cmrd-senya** [quilljs/quill#2726]
The first toolbar element whatever it is set to behaves incorrect when quill is rendered inside an element which is a descendant of an `<label />` element

**Steps for Reproduction**

1. Visit https://codepen.io/cmrd-senya/pen/QWLKdKQ
2. Click the first toolbar element (heading selection)

**Expected behavior**: heading level selection dropdown should stay opened

**Actual behavior**: the dropdown opens and then immediately closes

**Platforms**: Firefox 68/Linux, Chrome/MacOS

**Version**: 1.3.6, 2.0.0-dev.3

**Comment by benbro** [comment]
I don't think it semantically make sense to render an editor in a [label element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label):
> The HTML <label> element represents a caption for an item in a user interface.

**Comment by cmrd-senya** [comment]
It makes sense to render `<input>` elements in a `<label>` element, and while quill is not an `<input>` element, the requirements of a page layout may be to put it within a `<label>`. Semantically quill editor resembles an input element while technically it's not one.

I have a page with a form with different inputs including the quill control, and each input field is within a `<label>` element. Putting quill outside `<label>` requires special handling and becomes a special case which is minor but generally not a good thing.

Also while it is not a critical problem I still think it is a valid bug because there are no special reasons why Quill can't be used in such layout. It's not documented anywhere and there is no any conventional wisdom which says it's a bad idea.

**Comment by benbro** [comment]
You are not supposed to render input inside label, only checkbox and radio.
For example:
https://getbootstrap.com/docs/4.2/components/forms/

Can you give an example where it's recommended or used?

**Comment by cmrd-senya** [comment]
This is an example from MDN, the same page you referenced in your first reply: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#Simple_label_example
This is HTML code:
```HTML
<label>Click me <input type="text"></label>
```
Here is a text input is inside a label. Is that what you asked?
