### ISSUE TITLE
Enter after gurumukhi character throws Exception

### ISSUE THREAD

**Issue by h4rsh1t** [quilljs/quill#2728]
When I write a certain Gurumukhi Character (ਸ਼) either in a sentence or single alphabet, and press enter after it, Quill throws DOMException.
The same exception is thrown in case of ordered and unordered list, it creates an extra point after pressing enter.

**Steps for Reproduction**

1. insert the alphabet "ਸ਼" or a sentence containing the alphabet.
2. hit enter.
or
1. create a bullet list.
2. insert the alphabet "ਸ਼" or a sentence containing the alphabet.
3. hit enter.

**Expected behavior**:
creates a new line and a single bullet point

**Actual behavior**:
creates 2 bullet points [screenshot attached]

**Platforms**:

Chrome/MacOS Mojave

**Version**:
Quill version 1.3.6

<img width="1434" alt="Screenshot 2019-08-20 at 3 12 27 PM" src="https://user-images.githubusercontent.com/25745762/63336975-cc642200-c35d-11e9-80f5-a9fac29747fb.png">
<img width="1436" alt="Screenshot 2019-08-20 at 2 59 45 PM" src="https://user-images.githubusercontent.com/25745762/63336984-cf5f1280-c35d-11e9-932e-da2bb868c629.png">

**Comment by harshit-jainn** [comment]
Hi, there are many more issues with languages other than English.
