### ISSUE TITLE
How can I add an input element to the toolbar?

### ISSUE THREAD

**Issue by Chrisstar56** [quilljs/quill#2729]
I want to add a custom font size input to the toolbar to not be constrained to a predefined number of sizes. To do that I tried to just add an input element to the toolbar:
```html
<span class="ql-font-size" id="ql-font-size">
<input type="number"/>
</span>
```
This element of course showed up, but for some reason I couldn't focus on it. I tried attaching a click event handler and focusing it programmatically, which works but doesn't feel right. There must be a way to stop quill from preventing the focus, right?

The next problem I have is with styling. If I can have an arbitrary font size, I can't just set all the font sizes via css, that won't work. So how can I apply inlines style when formatting using the quill functions?

**Platforms**:

Firefox

**Version**:

1.0.0

**Comment by benbro** [comment]
Fork the [CodePen](https://codepen.io/quill/pen/KzZqZx) with minimal code showing what you are trying to do.
Please ask questions on StackOverflow.

**Comment by ackmanx** [comment]
@Chrisstar56 Do you remember if you ever got a solve for this or posted on StackOverflow? I looked but didn't find any questions relating to this there

**Comment by Abarwad** [comment]
@Chrisstar56 @ackmanx  have you found a solution yet? 
I could not find anything
