### ISSUE TITLE
Inserting Rich Text Format Content

### ISSUE THREAD

**Issue by jamieblue** [quilljs/quill#2730]
It seems you cannot insert rich text format content in to Quill (By API), as it just displays as plaintext. Is there something I'm missing, or will the ability to do this ever be added? 

Example RTF Content:
`{\rtf1\ansi{\fonttbl\f0\fswiss Helvetica;}\f0\pard
 This is some {\b bold} text.\par}`

I would of course expect this to display formatted rich text, rather than the string itself as plaintext.

**Comment by benbro** [comment]
Quill doesn't support RTF.
