### ISSUE TITLE
Delete characters at the end

### ISSUE THREAD

**Issue by gwenaelp** [quilljs/quill#2736]
Hi,

I am really new to quill, and I'd like, by pushing a button, to delete the last html element at the end of the content.

Do you have any ideas on how this could be acheived? From what I've understand, that would be two operations : 
Do you have any ideas on how this could be acheived? From what I've understand, that would be two operations :Do you have any ideas on how this could be acheived? From what I've understand, that would be two operations :
- retain X characters (X would be the number of characters between the cursor and the last element beginning
- delete Y characters (Y being the number of characters inside the element)

This is the only solution I am thinking in, but it's not that handy to implement. Would there be something smarter that I missed?

**Comment by benbro** [comment]
Read the [API docs](https://quilljs.com/docs/api/). Please ask support questions on StackOverflow.
