### ISSUE TITLE
when i  use insertEmbed , insert a div ,quill will auto insert <p><br/><p> in after，result : <div contenteditable="false" class="friendName">@啊拉拉</div><p><br></p>

### ISSUE THREAD

**Issue by limnQQ** [quilljs/quill#2740]
when i  use insertEmbed , insert a div ,quill will auto insert “<p><br/><p>” in after
how to remove <p><br></p>
==========code============
 quill.insertEmbed(index, 'div', {
          contenteditable: 'false',
          innerText: '@' + name,
          class: 'friendName'
        }, Quill.sources.USER);
        quill.setSelection(index + 1, Quill.sources.USER);
=========result===========
<div contenteditable="false" class="friendName">@啊拉拉</div><p><br></p>
==========================

**Comment by ChenMeng666666** [comment]
I also encountered the same problem 

`
  const BlockEmbed = Quill.import('blots/block/embed');
  class textBlot extends BlockEmbed {
        private static create(data: any) {
            const node = super.create();
            node.setAttribute('data-key', data.key);
            node.innerHTML = data.value;
            return node;
        }

        // 这里是要回写的时候显示的属性，如果不写，就是undefined
        private static value(node: any) {
            return {
                key: node.getAttribute('data-key'),
                value: node.innerHTML,
            };
        }
    }
    textBlot.tagName = 'div';
    textBlot.blotName = 'textBlot';
    textBlot.className = 'text-blot';

    Quill.register(textBlot, true);


    this.editor.insertEmbed(selection, 'textBlot', { key, value });
`
