### ISSUE TITLE
Footnote approach for Quill Documents?

### ISSUE THREAD

**Issue by npcole** [quilljs/quill#2742]
Does anyone have a good a approach for footnotes in Quill Documents? I'm assuming that in the delta itself, just a block-level format that has an attribute 'footnote' would work well. 

What about the editor itself? Has anyone tried this? Are there good approaches? I looked around for a plugin, but I couldn't see anything...

**Comment by npcole** [comment]
I thought I'd just flesh out this problem a little more.  Footnotes require two elements -- an inline embedded character of some kind, perhaps with a link -- and then a block to be displayed elsewere.[1]  I could create the footenote as some kind of embed -- but that would have the disadvantage that the text of the footnote couldn't be edited using the OT features of the Delta format.

One solution I've considered in theory is putting named blocks at the end of a document containing the footnote text itself, referred to with an inline anchor that is some kind of embed.

[
{'insert': this is some text}
{'insert': {'footnote-anchor': 'someautogeneratedrandomid'}}
{'insert': '\n'}
{'insert': 'This is the footnote text'}
{'insert': '\n', 'attributes': 'footnote-text': 'someautogeneratedrandomid'}
{'insert': '\n'}
]

Would that solution work?  Is the Parchment/Blot part of the code capable of supporting it?  Ideally, deleting the anchor would delete the relevant footnote block, and the order of the footnote blocks would be always controlled by the sequence of the anchors?

I don't know enough about Parchment to know if this is a realistic solution.

--
[1] Like this.

**Comment by erikradisch** [comment]
did you find any solution? I am having the same problem.

**Comment by KirillKirll** [comment]
Hi, check this solution: https://quill-footnotes.com

**Comment by arnarleifs** [comment]
> Hi, check this solution: https://quill-footnotes.com

Is this compatible with Quill 2.x?
