### ISSUE TITLE
How create custom module using react

### ISSUE THREAD

**Issue by jarl-alejandro** [quilljs/quill#2745]
how can i create a custom module with react components

Include browser, operating system and respective versions
chrome

**Version**: 1.3.6

Run `Quill.version` to find out

**Comment by kojidev** [comment]
What is that?

**Comment by benbro** [comment]
This question is too general.
Read the [docs](https://quilljs.com/docs/quickstart/) and [community projects](https://github.com/quilljs/awesome-quill).
