### ISSUE TITLE
Script tag in editor

### ISSUE THREAD

**Issue by PinkyRabbit** [quilljs/quill#2751]
Hi there! I want to use `hosted with ❤ by github` in my pages. But I can't find any module for that. Can any one help me? Thank you!

**Comment by benbro** [comment]
https://quilljs.com/docs/api/
https://quilljs.com/guides/why-quill/
https://github.com/quilljs/awesome-quill

**Comment by PinkyRabbit** [comment]
@benbro why not link to google.com?

**Comment by benbro** [comment]
Github issues are for bugs and development. Please ask questions on StackOverflow.
