### ISSUE TITLE
Formatting lost when code-block format is undone

### ISSUE THREAD

**Issue by adamdavidcole** [quilljs/quill#2753]
If you take some formatted text, convert that text to a code-block and then undo that change using cmd+z, the initial formatting of the text is lost -- everything just becomes plaintext

**Steps for Reproduction**

1. In a quill editor, type some bold and italicized text
2. Highlight the text and convert it to a code-block
3. Press CMD+z

**Expected behavior**:
Formatted text from step 1 is restored

**Actual behavior**:
Plaintext version of text from step 1 is restored

**Platforms**:
All platforms

**Version**:
1.3.6

Example:
After creating the code-block, I press cmd+z and the restored text is no longer bold
![lose formatting in code block on undo](https://user-images.githubusercontent.com/5685294/64291607-6bbc1400-cf1d-11e9-8520-cbbef9930f27.gif)

**Comment by Grewer** [comment]
+1
