### ISSUE TITLE
How to make an option of how to insert from clipboard

### ISSUE THREAD

**Issue by maximpap** [quilljs/quill#2754]
Task: I want to be able to preprocess clipboard content using ajax, get some options from the server side and only then give to user ability to insert clipboard content in a couple of ways.

Example: 
1. User pastes URL.
2. Browser sends this URL to the server side
3. Server looks for oembed tags at the URL or maybe it's an image
4. Server responds with couple of options of how it's can be renderred
5. User sees custom modal window with the options of how to insert this link
6. Selects option and it inserts

Can somebody give me a correct way of how to do it? Documentation is really bad, and I have no idea of how to solve it.

**Comment by benbro** [comment]
https://quilljs.com/guides/how-to-customize-quill/
https://github.com/quilljs/awesome-quill
