### ISSUE TITLE
Is it possible to show line numbering next to editor? 

### ISSUE THREAD

**Issue by harrysrevis** [quilljs/quill#2756]
Is it possible to add line numbering next to text editor (sth like github does in file preview and editing) as user is typing?

**Comment by DaniyelMe** [comment]
I made a basic module to add numer for each line.
It doesn't correspond to the actual line height (yet)

Check here:
https://codepen.io/DaniyelMe/pen/NWPagLM

Hope it helps.

**Comment by oschmid** [comment]
I tried out @DaniyelMe 's solution but found that numbers stopped lining up with lines once they got high enough. Some googling led me to a [pure CSS solution](https://stackoverflow.com/questions/40842277/create-line-numbers-on-pre-with-css-only). Translating that to Quill's CSS classes led to this solution:
```
.ql-editor {
  counter-reset: line;
  padding-left: 0;
}

.ql-editor p:before {
  counter-increment: line;
  content: counter(line);
  display: inline-block;
  border-right: 1px solid #ddd;
  padding: 0 .5em;
  margin-right: .5em;
  color: #888
}
```

**Comment by Kaywee27** [comment]
@oschmid It works fine for the text editor. How can we achieve the same using Code Block(Insert Code)

**Comment by oschmid** [comment]
@Kaywee27 quill code blocks seem to be plain text surrounded by <pre></pre> with each line is separated by \n characters. I'm unaware of a CSS selector for \n characters so I don't think it's possible sorry.

**Comment by willismonroe** [comment]
I was able to get the line numbers to disassociate with the line height after a while: 
![image](https://user-images.githubusercontent.com/715210/107721320-3890bf00-6c91-11eb-8ef6-880e6694ec0a.png)

Not to knock you're amazing codepen... it's very well done.

**Comment by kek-Sec** [comment]
> I tried out @DaniyelMe 's solution but found that numbers stopped lining up with lines once they got high enough. Some googling led me to a [pure CSS solution](https://stackoverflow.com/questions/40842277/create-line-numbers-on-pre-with-css-only). Translating that to Quill's CSS classes led to this:
> 
> ```
> .ql-editor {
>   counter-reset: line;
>   padding-left: 0;
> }
> 
> .ql-editor p:before {
>   counter-increment: line;
>   content: counter(line);
>   display: inline-block;
>   border-right: 1px solid #ddd;
>   padding: 0 .5em;
>   margin-right: .5em;
>   color: #888
> }
> ```

this approach is the cleanest and works like a charm

**Comment by ghfkui** [comment]
> I tried out @DaniyelMe 's solution but found that numbers stopped lining up with lines once they got high enough. Some googling led me to a [pure CSS solution](https://stackoverflow.com/questions/40842277/create-line-numbers-on-pre-with-css-only). Translating that to Quill's CSS classes led to this:
> 
> ```
> .ql-editor {
>   counter-reset: line;
>   padding-left: 0;
> }
> 
> .ql-editor p:before {
>   counter-increment: line;
>   content: counter(line);
>   display: inline-block;
>   border-right: 1px solid #ddd;
>   padding: 0 .5em;
>   margin-right: .5em;
>   color: #888
> }
> ```

Hi friend. this approach is ok. But found a little problem. If the text is too long causing the line wrap. The behavior is as follows:
![微信截图_20230301100746](https://user-images.githubusercontent.com/4645418/222026312-be289fd3-23e4-478f-81f8-5ca71085be2b.png)

**Comment by oschmid** [comment]
@ghfkui thank you for bringing up that interesting behaviour! Adding the CSS attributes `padding-left` and `text-indent` to .ql-editor [should help](https://stackoverflow.com/questions/480567/what-is-the-best-way-to-indent-text-in-a-div-when-it-wraps). (You may have to fiddle around with the exact amounts of each to make it look good).

**Comment by ghfkui** [comment]
@oschmid Thank you!

**Comment by Sivasankar967** [comment]
is is possible add line Number in Quill Editor
