### ISSUE TITLE
Not able to install quilljs with cmd npm install quill

### ISSUE THREAD

**Issue by manojkumarhr** [quilljs/quill#2760]
I am seeing lot of error while installing with this command in windows 8.1 and windows 10 machine , i also have tried node quill.js and after that npm install command but not worked please help me to install and run quilljs i m new to nodejs please help me

**Comment by manojkumarhr** [comment]
i have installed nodejs.org setup from their website

**Comment by benbro** [comment]
https://quilljs.com/docs/quickstart/
