### ISSUE TITLE
Chrome: toolbar clicks change the selected range just before applying format

### ISSUE THREAD

**Issue by jpfortier** [quilljs/quill#277]
This appears on the Quill example page, using the full example. When I select text and click bold, italics, or any other function, the words on line 1 directly under the button I chose are selected and the format applied to them instead of the range I selected.

Here is a video of it in action. Doesn't appear to happen in IE or Firefox. Running Chrome 39.0.2171.95 m, Win 8.1

http://tinypic.com/r/28ils3p/8

**Comment by jpfortier** [comment]
I downloaded and ran Version 42.0.2274.0 canary (64-bit) without extensions.
I experienced the same result.

**Comment by helloserve** [comment]
I can confirm this happens on Chrome Version 40.0.2214.115 m for me too, straight off of the example editor at http://quilljs.com.

Click anywhere (or select any text), and then click any of the style buttons - the cursor is moved to the end of the first line. Using short-cut keys like Ctrl+B does not do this, and correctly applies the style to the selected text or sets the style for new text to be entered.

It works correctly in IE 11.

**Comment by pearson-lucas-dev** [comment]
I was having the same problem from http://quilljs.com but I went to settings | More tools | Create Application shortcut and it works flawlessly.  This is on version: 
Google Chrome	40.0.2214.115 (Official Build) m
----
Revision	831713c5c90271926c2ca70afaa969d32e4576f5-refs/branch-heads/2214@{#490}
----
OS	Windows 
----
Blink	537.36 (@189787)
----
JavaScript	V8 3.30.33.16
----
User Agent	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by juodaspaulius** [comment]
Had the same issue in Chrome. Disabled all extensions one by one. It was switching off the chromeIPass(2.6.8) extension that fixed the issue. I guess I will create an issue on [chromeIPass page](https://github.com/pfn/passifox).

**Comment by jhchen** [comment]
Thanks @juodaspaulius
