### ISSUE TITLE
backend.js:1 Warning: componentWillUpdate has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by CloruroDiSodio** [quilljs/quill#2771]
Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Quill

**Comment by JayMacpherson** [comment]
same problem, cannot get the editor to open with new values depending on what props i pass it from different components

**Comment by fahadahmed** [comment]
Having the same issue and cannot use it with react hooks. This is making the component not able to re-render with the updated state. Need the team to update the react version to be compatible with Hooks.

**Comment by FitimFejzullahu** [comment]
Waiting for quill update on this issue: 

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Quill

**Comment by KrisTheGreat** [comment]
Same here.

**Comment by EmolLi** [comment]
same here

**Comment by vnxx** [comment]
same here.

**Comment by benbro** [comment]
Quill is a pure js and doesn't use ReactJS.

**Comment by Labsik** [comment]
any updates?
