### ISSUE TITLE
Opening a right click menu after highlighting some text

### ISSUE THREAD

**Issue by veeral-patel** [quilljs/quill#2773]
I'm working on a React-based project that uses React Quill. After I highlight some text in the Quill editor, I'd like to open a context menu that lets me perform some operations on the highlighted text.

For example, I'd like to be able to highlight a word, open a context menu, and look that word up in the dictionary.

Has anyone done this before? Is this something that's easy to do with Quill?

**Comment by mtvillwock** [comment]
Wondering the same thing as @veeral-patel, as I'm also looking to use a highlight word -> open context menu -> perform action workflow.

**Comment by DaltheCow** [comment]
Also looking to highlight as much text as I want and have a custom context menu pop open

**Comment by Yaronglp** [comment]
Hi :) i have the same issue,
Do u guys have any solution yet ?

**Comment by rahulmpatel369** [comment]
here is a link that can help you 
https://codepen.io/quill/pen/qNJrYB

**Comment by 454Nancy** [comment]
@rahulmpatel369 @veeral

**Comment by 454Nancy** [comment]
@DaltheCow

**Comment by 454Nancy** [comment]
Hello @veeral-patel

**Comment by benbro** [comment]
Check the [selection-change](https://quilljs.com/docs/api/#selection-change) event and [Bubble theme](https://quilljs.com/docs/themes/#bubble).
