### ISSUE TITLE
Editor scroll jumps to top when selecting a sub menu item (i.e. ql-picker)

### ISSUE THREAD

**Issue by grrrian** [quilljs/quill#2776]
**Steps for Reproduction**

1. Type enough lines into in auto-expand quill container that is restricted to a max height
2. At the bottom of the editor select some text and choose a picker button (e.g. align right)

**Expected behavior**:

Scroll position is maintained.

**Actual behavior**:

Editor scrolls to top.

**Platforms**:

Latest Chrome. Lates Mac OS.

**Version**:

1.3.7

**Comment by grrrian** [comment]
It was a react-quill issue. Fixed by overriding some css.

**Comment by jsellam** [comment]
hi @grrrian have you more informations about this fix please ?
