### ISSUE TITLE
Unable to insert HTML with dangerouslyPasteHTML

### ISSUE THREAD

**Issue by NiveshShastri** [quilljs/quill#2779]
Here is the sample HTML code that I want to insert using  `dangerouslyPasteHTML`  but editor showing `undefined` while adding HTML.

`
var selection = quill.getSelection(true);
quill.clipboard.dangerouslyPasteHTML(selection.index, '<span class="mention" data-name="@Lakshya Singh" data-type="ticketing/agent" data-id="20"><span contenteditable="false" style="color:blue">@Lakshya Singh</span></span>');`

Without the `class`, HTML is printed but with `class`, editor showing `undefined`

**Comment by Darknet17** [comment]
I have the same problem, please solve this error as soon as possible

**Comment by FelipeRomao** [comment]
I have the same problem
