### ISSUE TITLE
Cursor position does not move after pasting content

### ISSUE THREAD

**Issue by grrrian** [quilljs/quill#2783]
Hopefully some of you are also witnessing this and have tips.

**Steps for Reproduction**

1. Copy-paste text in the editor

**Expected behavior**:
Cursor is after pasted text.

**Actual behavior**:
Cursor is before pasted text.

**Platforms**:
Chrome 76, Mac 10.14.6.

**Version**:
1.3.7

**Comment by ethangunderson** [comment]
Were you ever able to resolve this? I'm having the same issue when using Quill in a Vue component and I'm completely stuck.

**Comment by mijnnaamisramon** [comment]
I had the same... installing https://github.com/Artem-Schander/quill-paste-smart worked for me! I don't have any involvement with that package, so use it at your own risk, but I'm willing to give it a try. 👍
