### ISSUE TITLE
I AM NOT ABLE TO INSTALL ANY PLUGIN AND NOT ABLE TO SETUP LOCALALLY THIS SETUP PLEASE HELP ME

### ISSUE THREAD

**Issue by ngcgolf11** [quilljs/quill#2784]
NOT ABLE TO INSTALL ANY PLUGIN

**Comment by KillerCodeMonkey** [comment]
i think your issue will not be handled with a higher priority even when all letters are written in uppercase.

You should not do this. Just explain your problem in a normal way and add some code snippets or demos repos/stackblitz to reproduce the problem.

**Comment by ngcgolf11** [comment]
i have fresh windows with npm installed but i am not able to add any plugin into this and not able to run downloaded quilljs setup after node quill.js and npm install quill command please help to setup and run this setup please its very urgent

**Comment by benbro** [comment]
https://quilljs.com/docs/quickstart/
