### ISSUE TITLE
Problems with adding text color and background color when inside iframe or object

### ISSUE THREAD

**Issue by jedfonner** [quilljs/quill#2785]
For reasons, we have to put Quill inside an `iframe` or `object` tag.  We have identified that when highlighting text using the cursor to click and drag, if the left click button is released when the cursor is outside of the iframe or object, the selection is lost when the formatting control is clicked, and no formatting change is applied as the selection is empty. 

See video at bottom.

**Steps for Reproduction**

1. Visit https://jsfiddle.net/dt9gh85k/
2. enter some text into the Quill editor
3. click and drag the cursor within the editor box to highlight the text, and make sure the cursor ends outside the box before releasing the mouse button. 
4. Select the background color formatting control, and choose a color. 

The selected text will not have its background color changed. This issue does not occur when the cursor ends inside the editor box.

**Expected behavior**:
The selected text should have its background color changed.

**Actual behavior**:
The selected text will not have its background color changed.

**Platforms**:
Reproducible on Chrome and Safari on Mac.

Seems to work fine on FF for Mac.

**Version**:
Latest

![2019-09-25_09-10-17](https://user-images.githubusercontent.com/344481/65604505-9a099e00-df75-11e9-8df2-5c2f8151f729.gif)

**Comment by lakshaysharmaadp** [comment]
I'm having the same issue, except my editor is inside a web component made in lit element
