### ISSUE TITLE
Composing nested DIV structures.

### ISSUE THREAD

**Issue by nofixing** [quilljs/quill#2796]
I am to produce below HTML.
```
<div class='container'>
      <div class='row'>
        <div class='col-sm border border-right-0'>column 1</div>
        <div class='col-sm border'>column 2</div>
        <div class='col-sm border border-left-0'>column 3</div>
      </div>
</div>
```

That is Bootstrap Grid.
When I try by extending BlockEmbed, the result HTML is the same as above.
But inside the DIV tag, formatting is not possible.
When I try by extending Block, the result HTML is
"`<div class='container dv_container_border'><br></div>`"
and this time, formattig is possible.
below is the code and entire example is [https://codepen.io/youngjin-lee/pen/ExxYRBY?editors=1111]( https://codepen.io/youngjin-lee/pen/ExxYRBY?editors=1111)
How to produce a formattable nested div structure?
```
let BlockEmbed = Quill.import('blots/block/embed');
class Div1 extends BlockEmbed {
  static create(value) {
    var node = super.create();
    node.classList.add("dv_container");
    var childNode = document.createElement('div');
    childNode.classList.add("row", "hfull");
    node.appendChild(childNode);
    var ctNode1 = document.createElement('div');
    var ctNode2 = document.createElement('div');
    var ctNode3 = document.createElement('div');
    ctNode1.classList.add("col-sm-4", "border", "border-right-0");
    ctNode2.classList.add("col-sm-4", "border");
    ctNode3.classList.add("col-sm-4", "border", "border-left-0");
    childNode.appendChild(ctNode1);
    childNode.appendChild(ctNode2);
    childNode.appendChild(ctNode3);
    return node;
  }
}
Div1.blotName = 'div1';
Div1.className = 'container';
Div1.tagName = 'DIV';
Quill.register(Div1, true);

let Block = Quill.import('blots/block');
class Div2 extends Block {
  static create(value) {
    var node = super.create();
    node.classList.add("dv_container_border");
    var childNode = document.createElement('div');
    childNode.classList.add("row", "hfull");
    node.appendChild(childNode);
    var ctNode1 = document.createElement('div');
    var ctNode2 = document.createElement('div');
    var ctNode3 = document.createElement('div');
    ctNode1.classList.add("col-sm-4", "border", "border-right-0");
    ctNode2.classList.add("col-sm-4", "border");
    ctNode3.classList.add("col-sm-4", "border", "border-left-0");
    childNode.appendChild(ctNode1);
    childNode.appendChild(ctNode2);
    childNode.appendChild(ctNode3);
    return node;
  }
}
Div2.blotName = 'div2';
Div2.className = 'container';
Div2.tagName = 'DIV';
Quill.register(Div2, true);

var div1 = document.querySelector('#div1');
div1.addEventListener('click', function () {
  let range = quill.getSelection(true);
  quill.insertText(range.index, '\n', Quill.sources.USER);
  var dval = quill.insertEmbed(range.index + 1, 'div1', '', Quill.sources.USER);
  quill.setSelection(range.index + 2, Quill.sources.SILENT);
  console.log(quill.root.innerHTML + '\n');
  console.log(JSON.stringify(dval));
});

var div2 = document.querySelector('#div2');
div2.addEventListener('click', function () {
  let range = quill.getSelection(true);
  quill.insertText(range.index, '\n', Quill.sources.USER);
  var dval = quill.insertEmbed(range.index + 1, 'div2', '', Quill.sources.USER);
  quill.setSelection(range.index + 2, Quill.sources.SILENT);
  console.log(quill.root.innerHTML + '\n');
  console.log(JSON.stringify(dval));
});
```

**Comment by hagiosolat** [comment]
let Inline = Quill.import('blots/inline');
let Block = Quill.import('blots/block');
let BlockEmbed = Quill.import('blots/block/embed');
let Parchment = Quill.import('parchment');


class BoldBlot extends Inline { }
BoldBlot.blotName = 'bold';
BoldBlot.tagName = 'strong';

class ItalicBlot extends Inline { }
ItalicBlot.blotName = 'italic';
ItalicBlot.tagName = 'em';

class ImageBlot extends BlockEmbed {
  static create(value) {
    let node = super.create();
    node.setAttribute('alt', value.alt);
    node.setAttribute('src', value.url);
    return node;
  }

  static value(node) {
    return {
      alt: node.getAttribute('alt'),
      url: node.getAttribute('src')
    };
  }
}
ImageBlot.blotName = 'image';
ImageBlot.tagName = 'img';

Quill.register(BoldBlot);
Quill.register(ItalicBlot);
Quill.register(ImageBlot);

class Div1 extends BlockEmbed {
  static create(value) {
    var node = super.create();
    node.classList.add("dv_container");
   // PositionAtt.add(node,'relative');
    ColorAtt.add(node,'red');
    var childNode = document.createElement('div');
    childNode.classList.add("row", "hfull");
    node.appendChild(childNode);
    var ctNode1 = document.createElement('div');
    var ctNode2 = document.createElement('div');
    var ctNode3 = document.createElement('div');
    ctNode1.classList.add("col-sm-4", "border", "border-right-0");
    ColorAtt.add(ctNode1,'blue');
    ctNode2.classList.add("col-sm-4", "border");
    ColorAtt.add(ctNode2,'green');
    ctNode3.classList.add("col-sm-4", "border", "border-left-0");
    childNode.appendChild(ctNode1);
    childNode.appendChild(ctNode2);
    childNode.appendChild(ctNode3);
    return node;
  }
}
Div1.blotName = 'div1';
Div1.className = 'container';
Div1.tagName = 'DIV';
Quill.register(Div1, true);

class Div2 extends Block {
  static create(value) {
    var node = super.create();
    node.classList.add("dv_container_border");
    var childNode = document.createElement('div');
    childNode.classList.add("row", "hfull");
    node.appendChild(childNode);
    var ctNode1 = document.createElement('div');
    var ctNode2 = document.createElement('div');
    var ctNode3 = document.createElement('div');
    ctNode1.classList.add("col-sm-4", "border", "border-right-0");
    ctNode2.classList.add("col-sm-4", "border");
    ctNode3.classList.add("col-sm-4", "border", "border-left-0");
    childNode.appendChild(ctNode1);
    childNode.appendChild(ctNode2);
    childNode.appendChild(ctNode3);
    return node;
  }
}
Div2.blotName = 'div2';
Div2.className = 'container';
Div2.tagName = 'DIV';
Quill.register(Div2, true);

let PositionAtt = new Parchment.Attributor.Style('position', 'position');
let ColorAtt = new Parchment.Attributor.Style('background-color','background-color');
 
Quill.register(PositionAtt,true);
Quill.register(ColorAtt, true);

let quill = new Quill('#editor-container');

$('#bold-button').click(function() {
  quill.format('bold', true);
});
$('#italic-button').click(function() {
  quill.format('italic', true);
});

$('#link-button').click(function() {
  let value = prompt('Enter link URL');
  quill.format('link', value);
});

$('#image-button').click(function() {
  let range = quill.getSelection(true);
  quill.insertText(range.index, '\n', Quill.sources.USER);
  quill.insertEmbed(range.index + 1, 'image', {
    alt: 'Quill Cloud',
    url: 'https://quilljs.com/0.20/assets/images/cloud.png'
  }, Quill.sources.USER);
  quill.setSelection(range.index + 2, Quill.sources.SILENT);
});

var div1 = document.querySelector('#div1');
div1.addEventListener('click', function() {
  let range = quill.getSelection(true);
  quill.insertText(range.index, '\n', Quill.sources.USER);
  var dval = quill.insertEmbed(range.index + 1, 'div1', '', Quill.sources.USER);
  quill.setSelection(range.index + 2, Quill.sources.SILENT);
  console.log(quill.root.innerHTML+'\n');
  console.log(JSON.stringify(dval));
});

var div2 = document.querySelector('#div2');
div2.addEventListener('click', function() {
  let range = quill.getSelection(true);
  quill.insertText(range.index, '\n', Quill.sources.USER);
  var dval = quill.insertEmbed(range.index + 1, 'div2', '', Quill.sources.USER);
  quill.setSelection(range.index + 2, Quill.sources.SILENT);
  console.log(quill.root.innerHTML+'\n');
  console.log(JSON.stringify(dval));
});



You can try this code. Check the updates I made to the code here. The parchment allows you to style the contents in the editor. I don't know if it answered your question.
The image below is the styling of each column div





![editedwork](https://github.com/user-attachments/assets/15f8d120-851b-4705-8346-4663a8e899e8)
