### ISSUE TITLE
Firefox enter key not working successively

### ISSUE THREAD

**Issue by brettz9** [quilljs/quill#2801]
**Steps for Reproduction**

1. Visit quilljs.com
2. Click the mouse somewhere within the text.
3. Hit the "enter" key twice

**Expected behavior**:

Allow multiple line breaks.

**Actual behavior**:

Only allows one line break, no matter how many times the enter key is pressed.

**Platforms**:

Firefox 70.0b14, Mac OS Catalina 10.15

**Version**:

1.3.6 per console.

**Comment by benbro** [comment]
Can't reproduce.
