### ISSUE TITLE
Undo Api fails with custom extension in react, quill return a TRUE

### ISSUE THREAD

**Issue by caperso** [quilljs/quill#2803]
I'm using quill with react-quill v1.4-beta5
you can view the code here 
or visit project directly on https://codesandbox.io/s/divine-thunder-u5fyn

isuss occurs in this extension for quill
```ts
import { Quill } from "react-quill";

const BlockEmbed = Quill.import("blots/block/embed");
export default class File extends BlockEmbed {
  private static create(dom: HTMLDivElement | boolean) {
    console.log("triggered custom Extension");

    /* ===here is the place where all my confusions origins===*/
    if (dom === true) {
      throw new Error("THIS IS NOT DOM BUT BOOLEAN TRUE");
    }
    /* =======================================================*/

    const node = super.create();
    node.appendChild(dom);
    return node;
  }
}
File.blotName = "file";
File.className = "file-wrapper";
File.tagName = "div";
```

**Steps for Reproduction**

1. visit example on https://codesandbox.io/s/divine-thunder-u5fyn 

2. click image button on toolbar
you will see 
"triggered custom proxy handler" ,
"triggered custom insertFile method" and
"triggered custom Extension" only print once but
the dom was flushed (or removed) 

3. remove comment tag on App.tsx-line 59 and line 65
I use setTimeout to make the DOM stay in editor (see at App.tsx-line 59)

4. repeat step 2 and will see the dom was inserted

5. hit backspace

6. hit ctrl + z to undo 

7. error will show

the wired thing happend
the extension was triggered but parameter "dom" was a boolean TRUE

**Comment by dimshades** [comment]
is there a way to disable undo api?

**Comment by do-web** [comment]
Same here if i use this.quill.pasteHTML(newVal).
