### ISSUE TITLE
Link will delete via hitting keyboard if the link text contains some font formats

### ISSUE THREAD

**Issue by kangschampagne** [quilljs/quill#2810]
**Steps for Reproduction**
1. Visit [CodePen demo](https://codepen.io/kangschampagne/pen/zYYKYaz)
2. Insert a link 
3. Set the link text to Bold/Underline/Italics/Strike
4. hitting the keyboard(insert any text) *at the end of the link*

**Expected behavior**:
insert text normal and not delete the link.

**Actual behavior**:
delete the link text.

**Platforms**:
macOS Mojave 10.14.6
Chrome 77.0.3865.120

**Version**:
2.0.0-dev.3

**Comment by kangschampagne** [comment]
@jhchen it seems a bug in quill 2

**Comment by gujinku** [comment]
This issue is kind of annoying. Could you pls share the fix plan? Thank you!

**Comment by gujinku** [comment]
@jhchen  could you pls help take a look at this issue? Thanks a lot.
