### ISSUE TITLE
Instagram widget

### ISSUE THREAD

**Issue by projectstravel** [quilljs/quill#2820]
Hi,

I'm trying to figure out a way to embed instagram posts.  Is anyone had figured out a simple way to do that?
I can also help contribute to make this one better.

Thanks!

**Comment by DmitrySkripkin** [comment]
Here is small example for Twitter [CodePen](https://codepen.io/DmitrySkripkin/pen/oOBLdo), it's not working perfectly, but can be helpful to figure out how to work with quill blots.

**Comment by ntgnst** [comment]
I am facing trouble while rendering instagram embeds too.  Twitter and Youtube embeds are working but Instagram...

**Comment by PrimeITArmenia** [comment]
> I am facing trouble while rendering instagram embeds too. Twitter and Youtube embeds are working but Instagram...

Hi @ntgnst ,  you resolve with Instagram issue now i have problem about setting instagram Embed code in Editor and correct showing  "instagram post" inside Editor ????
