### ISSUE TITLE
where is the code update ql-clipboard？

### ISSUE THREAD

**Issue by njleonzhang** [quilljs/quill#2822]
I have encountered an [issue](https://github.com/quilljs/quill/issues/2778) which cause `copy and paste` not work in ios 13.

After some investigation, I have found  the issue is related to element `ql-clipboard`. In normal situation, the content copied by user is inserted into the element. 
but on ios 13, the element is empty, which cause the paste failure.

My question is that I can not find the code manipulate the element `ql-clipboard`. I cannot investigate much further.

Anyone can help?

**Comment by WavinFlag** [comment]
See https://github.com/quilljs/quill/issues/2778#issuecomment-674778586.
