### ISSUE TITLE
when i config a new formats, i want to copy and paste, but it can not work.

### ISSUE THREAD

**Issue by 17biubiu** [quilljs/quill#2824]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
[codepen ](https://codepen.io/General_Lee/pen/pooRxPW)
2. Step Two
enter text, and click the red button.
3. Step Three
copy sth, and paste
**Expected behavior**: copy the class, and paste it

**Actual behavior**:  not working

**Platforms**:

Include browser, operating system and respective versions

**Version**: 1.3.6 or 1.3.7

Run `Quill.version` to find out

**Comment by proshuai** [comment]
why？

**Comment by proshuai** [comment]
@benbro why?

**Comment by proshuai** [comment]
@benbro i have tried to read the source, but, i do not find the better way to handle it

**Comment by benbro** [comment]
Please describe the steps to reproduce your issue and reopen.
