### ISSUE TITLE
"Formats" filter blocks out div element

### ISSUE THREAD

**Issue by giRobert** [quilljs/quill#2827]
Hey there,

I'm using Quill Editor v1.3.6.

I am inserting div's with classes to my quill editor successfully to be able to add and remove certain content inside the editor. Everything works perfect.

Until the moment when I wanted to limit my editor using the formats ( https://quilljs.com/docs/formats/ ). From that moment on it didnt work out anymore. Investigation showed that my divs are transformed to a <p> tag.. when i remove the formats bit a again. everything works again.

I guess this behavior is caused automatically because my tags are not listed in the "formats" list. so they are kind of "blocked" (transformed). my question is now, how can I allow the divs to be used? I added "div" to the format list but it didnt work. how can I achieve the behavior? I can not even figure out the position in quill js to make a workaround.

The reason why i need to limit the formats is that i dont want people to add colored texts and stuff... but divs must be allowed somehow.

Looking forward for your answers. Thanks already!

Here is my code.

```
var quill = new Quill("#"+editorId, {
                    modules: {
                        toolbar: [
                                ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
                                [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
                                ['clean']                                         // remove formatting button
                            ]
                    },
                    theme: 'snow',
                    formats: [ 'bold', 'italic', 'underline', 'strike', 'indent', 'image' ]
                });
```

**Comment by benbro** [comment]
https://quilljs.com/guides/how-to-customize-quill/
