### ISSUE TITLE
Unable to disable focus when using dangerouslyPasteHTML to update content

### ISSUE THREAD

**Issue by GGuru** [quilljs/quill#2829]
I am using quill adjacent to an autocomplete input field. When changing the autocomplete input, I am updating the content in quill using dangerouslyPasteHTML but that sets the focus to quill after inserting the content. For this use case, it is not a desired behavior. It is important that we preserve the focus in the autocomplete input as user is still typing in it (Accessibility is taken care through other means like aria-live).

I tried disabling the editor, set the content and then enabling it. 

```
   this.editor.enable(false);
   this.editor.clipboard.dangerouslyPasteHTML(content);
   this.editor.enable();
```

This partially works. With this, the focus stays in the autocomplete. I could see the default focus outline around the input but the cursor is lost. This is because of setSelection call in dangerouslyPasteHTML. If I add a check around setSelection such that it is called only if the editor is enabled, it fully works.

```
dangerouslyPasteHTML(index, html, source = Quill.sources.API) {
    if (typeof index === 'string') {
      const delta = this.convert({ html: index, text: '' });
      this.quill.setContents(delta, html);
      if (this.quill.root.getAttribute('conenteditable') === 'true') {
        this.quill.setSelection(0, Quill.sources.SILENT);
      }
    } else {
      const paste = this.convert({ html, text: '' });
      this.quill.updateContents(
        new Delta().retain(index).concat(paste),
        source,
      );
      // same condition here
      this.quill.setSelection(index + paste.length(), Quill.sources.SILENT);
    }
  }
```

Is this an acceptable fix to the problem. Are there other downsides of adding this condition?

**Comment by mojtabaahn** [comment]
Any updates on this ?

**Comment by btakita** [comment]
Ping. I understand that setting html is not recommended for untrusted sources, however this would be nice to allow html to be set when the source is trusted (i.e. no sanitation needed).
