### ISSUE TITLE
How to run Project on windows? There are so many errors when run

### ISSUE THREAD

**Issue by BH-NOTHING** [quilljs/quill#2831]
Is there a details tutorial for running projects? After installing ruby,bundler,node and npm, when i follow the steps (npm install,bundle install,npm run build), there are so many errors about jeky and package，there are still a lot of errors waiting for me when i solved it! Oh, my god~I'm comfused, I  just want to run quill project.

**Comment by usernamedd** [comment]
the same on ubuntu

**Comment by benbro** [comment]
https://quilljs.com/docs/quickstart/
