### ISSUE TITLE
loses tabs on copy/paste

### ISSUE THREAD

**Issue by volser** [quilljs/quill#2834]
When copy and paste text with tabs, it loses tabs

**Steps for Reproduction**
1. Visit https://codepen.io/quill/pen/QxypzX
2. type text
```
1
	2
		3
			3.1
			3.2
	4
5
```
3. Copy/Paste
https://recordit.co/o7mWWTVlk4

**Expected behavior**:
keep tabs

**Actual behavior**:
lost tabs

**Platforms**:
Windows, Chrome

**Version**:
"2.0.0-dev.3"

**Comment by padraigfl** [comment]
To expand on that, it looks like it:

1. swaps the tabs for spaces and stores them with one line per ops entry with the attribute `code-block: 'plain'`
2. removes the `code-block` attribute (I assume the inline blot doesn't accept it or something?)
3. it combines all of the individual lines into one entry
4. removes the excess white spacing

**Comment by dalipkumar703** [comment]
Can u explain more in detail with example please :) ?

**Comment by kriskratz** [comment]
Looks like this issue is caused by the logic in the clipboard module. The function is called "[matchText](https://github.com/quilljs/quill/blob/d2f689fb4744cdada96c632a8bccf6d476932d7b/modules/clipboard.ts#L552)" which trims the text content.

I haven't gone through it thoroughly, but you can override it with a clipboard matcher for Node.TEXT_NODE, and then write the logic you want instead. Maybe don't trim lines that start with a tab? Not sure.

I think this is related to issue #1936. There I show a basic example of overriding the matcher.

**Comment by kriskratz** [comment]
Here is my fix to this and to issue #1936. The problem arises in the clipboard module, where [textMatcher](https://github.com/quilljs/quill/blob/d2f689fb4744cdada96c632a8bccf6d476932d7b/modules/clipboard.ts#L552) trims all white-space.

Add this to your modules object to override that behavior.

clipboard: {
            matchers: [
                [Node.TEXT_NODE, (node, delta) => { 
                    if(node.data.match(/^\s/) ) {
                        const Delta = Quill.import('delta');
                        return new Delta().insert(node.data);
                    }
                    return delta;
                }],
            ],
        },

If pasted text starts with white-space (space, tab, etc) or is just white-space this replaces the clipboard generated delta.

**Comment by kriskratz** [comment]
This fixes my previous solution, which was adding a new line after every line: 

```
clipboard: {
            matchers: [
                [Node.TEXT_NODE, (node, delta) => { 
                    if(node.data.match(/[^\n\S]|\t/) ) {
                        const Delta = Quill.import('delta');
                        return new Delta().insert(node.data);
                    }
                    return delta;
                }],
            ],
        },
```

**Comment by Sashkko** [comment]
@kriskratz Thank you! Your solution helped me a lot!
