### ISSUE TITLE
Enter Chinese after the code area, an error will occur

### ISSUE THREAD

**Issue by sidoc-cn** [quilljs/quill#2835]
Please see the GIF image below, the text normally entered will automatically jump to the code area.

![15654879998192019-08-11-09-12-13](https://user-images.githubusercontent.com/7484979/68387032-558a3880-0198-11ea-95fc-832e274da00f.gif)

**Comment by LessAlpha** [comment]
I also meet the same question, is there any way to solve it ?

**Comment by LessAlpha** [comment]
When I change lib from 'react-quilljs' to 'quill' in my react project, the problem doesn't occur, and many other problems in 'react-quill' disappear
