### ISSUE TITLE
Implementing pagination using Quill. [discussion]

### ISSUE THREAD

**Issue by MuhammedAlkhudiry** [quilljs/quill#2836]
I hope this issue does not violate the guidelines, but I want a place to discuss how to implement pagination in Quill.

The required mechanisms:

* convert the layout into fixed-size pages like in Microsoft Word.
* migrate texts between pages.
* create a new page when text exceeds the current pages.
* delete the page when It's empty.

Optional:
* support for headers.
* support for footers.

Any ideas are welcomes.

**Comment by everettglovier** [comment]
@KMLX28 I have been working on this for some time and was curious if you found a solution. I am using angular, so was able to successfully get multiple pages with headers working by creating multiple quill instances and jumping between them, checking for page lengths every keystroke and manually handling the pagination.

Known bugs so far are multiple histories per page.

**Comment by KMLX28** [comment]
I found that editors that use contenteditable are nearly impossible to have pagination, so It's required to have an editor that provides editing without contenteditable like [this](https://github.com/yuzhenmi/taleweaver)
