### ISSUE TITLE
Ability to upload Quill images to aws s3?

### ISSUE THREAD

**Issue by bvv218** [quilljs/quill#2837]
Is there a way to upload images directly to s3 bucket?

**Comment by padraigfl** [comment]
You can pass an image handler function into the toolbar specification https://quilljs.com/docs/modules/toolbar/

easiest is probably to just create a fake file input field and have it be triggered when you click on the toolbar option, with the output being passed back into quill

**Comment by mart1nra** [comment]
Can anyone share how to upload images to S3 bucket inside replaced image handler function? Very appreciated.

**Comment by gdonnelly82** [comment]
Just checking if anyone can share a solution for this. I'm unable to add image via the editor as I keep getting CORS errors with AWS S3. 
![cors issue](https://user-images.githubusercontent.com/59867883/111192670-3cc23c00-85b1-11eb-806e-bd5492027ba3.png)

**Comment by gdonnelly82** [comment]
I managed to solve this relatively easily. 

It's because S3 will not let you submit data via JS unless you have a CORS policy in place for your website. 

You need to go to your AWS S3 Bucket > Permissions and then add the following code in the Cross-origin resource sharing (CORS) section. 



```

[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "https://www.yourWebsiteName.com"
        ],
        "ExposeHeaders": [
            "x-amz-server-side-encryption",
            "x-amz-request-id",
            "x-amz-id-2"
        ],
        "MaxAgeSeconds": 3000
    }
]
```

**Comment by Aslam97** [comment]
Hi @gdonnelly82  looks like you have successfully implemented upload image to s3. if you have time, can you share your solutions to work with s3? I really appreciate.

**Comment by gdonnelly82** [comment]
Hi @Aslam97 
Were you able to follow the steps in my previous comment or do you need more information?

**Comment by Aslam97** [comment]
@gdonnelly82 No, and thank you. I found this issue #1089 and got mine working https://github.com/quilljs/quill/issues/1089#issuecomment-843831105
