### ISSUE TITLE
Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by Eyegabry99** [quilljs/quill#2840]
I installed the plugin image resize into my component in this way 

```
import {Quill} from 'quill';
import {ImageResize} from 'quill-image-resize';
Quill.register('modules/imageResize', ImageResize);
```

I also tried to import in this way 
```
import Quill from 'quill';
import ImageResize from 'quill-image-resize';
Quill.register('modules/imageResize', ImageResize);

```
```
import Quill from 'quill';
import {ImageResize} from 'quill-image-resize';
Quill.register('modules/imageResize', ImageResize);

```

And binded with the following options 
```
modulesForQuill = {
    imageResize: {},
    toolbar: [
      [{'color': []}],  // dropdown with defaults from theme
      ['bold', 'italic', 'underline'],        // toggled buttons
      [{'script': 'super'}, {'script': 'sub'}], // superscript, subscript
      [{'align': []}], // let's test this
      [{'list': 'ordered'}, {'list': 'bullet'}], // various list
      ['link', 'image'], // miscellaneous
    ]
  };
```
I call it from my html in this way
`<quill-editor [modules]="modulesForQuill"></quill-editor>
`

1. Using ng serve it works fine the image resize. But when i try to run in production this plugin it give me this error: "Super expression must either be null or a function, not undefined"

**Expected behavior**:
Image resize working in production

**Actual behavior**:
Project not running, it crash at start of loading

**Platforms**:
Chrome
Windows 10

**Version**:

Quill version: 5.0.0

**Comment by mchestnut** [comment]
@Eyegabry99  I'm experiencing the same problem. Did you find a solution?
