### ISSUE TITLE
placeholder does not change when changing current language

### ISSUE THREAD

**Issue by woxingren** [quilljs/quill#2845]
I am using angular 7 and quill 1.3.6 and find placeholder does not change when changing current language. 
I follow https://itnext.io/creating-a-custom-form-field-control-compatible-with-reactive-forms-and-angular-material-cf195905b451 to create a rich editor with quill. But when I change the language, placeholder does not update accordingly.

Basically I use `<quill-editor placeholder="{{'abc-placeholder' | translate}}"></quill-editor>`, when I change to a different language, I can see the value of `{{'abc-placeholder' | translate}}` has changed to the new language on the Console of Chrome, but the placeholder in quill-editor does not change.

Another person also have the same problem at https://stackoverflow.com/questions/48962186/ngx-quill-placeholder-not-changing-when-selecting-new-language/58962591#58962591.

Is there any idea how to fix it?

**Comment by padraigfl** [comment]
Don't know angular at all, but this seems like it could work in your case: https://stackoverflow.com/questions/38936594/dynamically-change-quill-placeholder

`quill.root.dataset.placeholder = 'Your new placeholder';`

**Comment by woxingren** [comment]
> Don't know angular at all, but this seems like it could work in your case: https://stackoverflow.com/questions/38936594/dynamically-change-quill-placeholder
> 
> `quill.root.dataset.placeholder = 'Your new placeholder';`

Thanks you, padraigfl, it works for me.

I have post a explanation at https://stackoverflow.com/questions/48962186/ngx-quill-placeholder-not-changing-when-selecting-new-language/58981596#58981596 in case anyone need more details.
