### ISSUE TITLE
insertText with formatting option crashes quill in Firefox

### ISSUE THREAD

**Issue by T-vK** [quilljs/quill#2846]
Running quill.insertText with a formatting option such as `quill.insertText(0, 'test', 'bold', true);` crashes quill when executed from the console in Firefox:

![image](https://user-images.githubusercontent.com/11368523/69418206-82068e80-0d1a-11ea-91a3-cf267170686f.png)

**Steps for Reproduction**

1. Create an html file like this and open it in Firefox:
``` html
<!doctype html>
<html>
<head>
  <script src="https://cdn.quilljs.com/1.3.7/quill.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.quilljs.com/1.3.7/quill.bubble.css"></link>
  <link rel="stylesheet" type="text/css" href="https://cdn.quilljs.com/1.3.7/quill.snow.css"></link>
  <meta charset="utf-8"/>
</head>
<body>
  <div id="editor"></div>
  <script>
    const quill = new Quill('#editor', {
        theme: 'snow',
        modules: {
            toolbar: {
                container: [
                    ['bold', 'link'],
                ]
            }
        }
    })

    quill.insertText(0, 'this-works', 'link', 'https://www.google.com/'); // This will work fine 
 </script>
</body>
</html>
```
2. Open the console
3. Run quill.insertText with formatting options e.g.:
``` JavaScript
quill.insertText(0, 'this-crashes', 'link', 'https://www.google.com/'); // This will crash quill
```

**Expected behavior**:

Formatted text gets inserted

**Actual behavior**:

quill crashes

**Platforms**:

OS: Linux (Fedora 30)
Browser: Firefox 70.0.1 (64 bit)

**Version**: 

(**1.2.5**-)**1.3.7**

Note: In Chromium 78 everything works fine.

**Edit:**

The problem exists starting with 1.2.5 (1.2.4 and below work just fine).

**Comment by ParkerGreyAddison** [comment]
It's worth noting that `formatText`, `insertText` with formatting, etc (anything involving `formatAt` in editor.js?) only crashes the page when prompted from the Console.

i.e. If you define a function in your main.js file, and then run that function in the file, it works
```javascript
function boldify(bool) {
    editor.formatText(0, 5, "bold", bool);
}

boldify(true);  // Works as intended
```
but then if you head to the console and try running
```
>> boldify(false);
```
it freezes up!

Fortunately it's not too big of a deal to avoid using Console for such things, but it is interesting.

OS: Windows_NT 10.0
Browser: Firefox 71.0 (64 bit)

**Comment by KevinButterfield** [comment]
> It's worth noting that `formatText`, `insertText` with formatting, etc (_anything involving `formatAt` in editor.js?_) only crashes the page when prompted from the Console.

I've seen Firefox 74 do this even when calling `setText` or `setContents`, but again this only happens when running from the console.

**Comment by T-vK** [comment]
It really sucks for every developer who has to go through this. In my opinion we should at least print a warning to the console.
