### ISSUE TITLE
The initial style is missing

### ISSUE THREAD

**Issue by bszhct** [quilljs/quill#2849]
The initial html looks like this:
```html
<p style="text-indent: 2em;"></p><span id="var_9926108136793732" contenteditable= "false" class="spanVarBtn" ref="common_feeAmount">variables</span>
```

After passing it to quill, it becomes like this:

```html
<p>	<span>variables</span></p>
```
Inline styles and attributes are lost!

What should I do to ensure that the original attributes and styles are not lost?

[Demo](https://codepen.io/fylworker/pen/xxxeBKe)

**Version**:
1.3.7

**Comment by bszhct** [comment]
@jhchen @byronm Thank you for your reply when the two big men are free.

**Comment by padraigfl** [comment]
it's presumably ignoring the p tag because there's no content in it?

To retain attributes you generally need to expand the existing blots to allow them.
