### ISSUE TITLE
Unwanted mutation of existing DOM tree

### ISSUE THREAD

**Issue by Rob-pw** [quilljs/quill#285]
Hi:

I have the simple case: 

```html
<div class="content-container">
  <div class="toolbar"> 
    <!-- toolbar boilerplate -->
  </div>

  <div class="editor">
    <div class="myContent">
      <!-- shadow-root  -->
      <section>
        <header>
           <h2>My text to edit</h2>
        </header>
      </section>
    </div>
  </div>
</div>
```

I was expecting something similar to the following:

```html
<div class="content-container">
  <div class="toolbar"> 
    <!-- toolbar boilerplate -->
  </div>

  <div class="editor ql-container">
    <div class="myContent ql-editor">
      <!-- shadow-root  -->
      <section>
        <header>
           <h2>My text to edit</h2>
        </header>
      </section>
    </div>
  </div>
</div>
```

But intend I received the following (minus boilerplate markup):

```html
<div class="editor ql-container">
    <div class="ql-editor" id="ql-editor-5">
      <div contenteditable="true" class="shadowHost ql-line" id="ql-line-9">My text to edit</div>
    </div>
  <div class="ql-paste-manager" contenteditable="true"></div>
</div>
```

What reasons does Quill have to mutate the DOM before any formatting operations have been applied? 

Quill does not know how the mark-up is meant to look, it should not modify elements beyond adding classes and attributes, only modifying the individual elements that the user is currently formatting (wrapping the current text selection in ```<strong>``` tags, for example). In this case Quill has removed the shadow-root from the host, stripped out the semantic mark-up (section, header) and otherwise destroyed the original mark-up.

**Comment by jhchen** [comment]
Quill does not understand/edit arbitrary HTML and so one of the necessary steps is reduce any input to the subset of HTML it does understand. Over time it will understand more--for example headers are being added soon--but it will still be a subset.
