### ISSUE TITLE
CDN上的quill.min.js和quill.snow.css访问不到了

### ISSUE THREAD

**Issue by 5664stt** [quilljs/quill#2852]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**:

**Actual behavior**:

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by Rapliangle** [comment]
I got the same problem. is there any problem with the cdn platform?
![image](https://user-images.githubusercontent.com/25297307/70053086-a2cebe00-160f-11ea-9711-d6cecb500094.png)

**Comment by weiyinfu** [comment]
https://www.bootcdn.cn/quill/
You can use the cdn here.
