### ISSUE TITLE
Quill editor showing wrong character count.

### ISSUE THREAD

**Issue by jayaramasaipavanmanda** [quilljs/quill#2854]
I have entered only one character in quill and it is showing the length as 2. here is the stack blitz demo `https://stackblitz.com/edit/quill-editor-vesbcp?embed=1&file=src/app/app.component.ts`.

Open the link enter a character and observe on the console, it is showing length as 2.

**Comment by heruan** [comment]
The count is correct: if you log `event.content.ops[0]` you'll see there is a whitespace character in the `insert` operation.

**Comment by jayaramasaipavanmanda** [comment]
@heruan how to avoid that whitespace. I cannot `trim` my string because I want spaces to be counted.

**Comment by heruan** [comment]
I don't think you can't, Delta should always end with a whitespace character which counts as 1. You can just subtract 1 to the character count.

**Comment by benbro** [comment]
Answered.
