### ISSUE TITLE
Bullet point size doesn't change with the font size

### ISSUE THREAD

**Issue by cxn-pkovacs** [quilljs/quill#2856]
**Steps for Reproduction**

1. Visit https://quilljs.com/playground/ .
2. Add the following items to `modules.toolbar` in the _JS_:
```
      [{ 'list': 'ordered'}, { 'list': 'bullet' }],
      [{ 'size': ['small', false, 'large', 'huge'] }],
```
.
3. Wait for the toolbar to be updated with the two items just added.
4. Create text content as a bullet-pointed list with three items.
5. Select the entire text and change the font size to _Small_, _Normal_, _Large_ and _Huge_
6. Observe the size of the bullet-points each time after you changed the font size.

**Expected behavior**:
The size of the bullet-points increases as the font size is increased and vice versa.

**Actual behavior**:
The size of the bullet-points remains the same (small) no matter how large the fonts are. 

**Platforms**:
* Google Chrome Version 78.0.3904.108 (Official Build) (64-bit) - macOS 10.15.1 (19B88)
* Firefox Browser 70.0.1 (64-bit) - macOS 10.15.1 (19B88)

**Version**:
1.3.6

**Comment by pcxnkovacs** [comment]
Limiting the solution to list-items having their entire text content uniformly sized (similarly to how text objects in Google Draw behave in this respect) significantly decreases the implementation's complexity -- in principle:
- when the user applies the size-styling to the entire text, the old size-style(s) can be removed from the text level and the new style can be applied at the list-item level.

**Comment by simonouyangbcgdv** [comment]
Do we have the solution yet?

**Comment by pcxnkovacs** [comment]
With current releases, I could solve the issue to some extent (not perfectly) by registering a modified `ListItem` blot.
In the 2.0 branch, the structure of `List`s has been modified so as to allow a much more satisfactory solution. (Alas, the last commit in the 2.0 branch was made some time in 2018 which makes me think, it will never be released.)

**Comment by b-solution** [comment]
Hi there, @cxn-pkovacs @simon-ouyang. I am at-last also stuck on the same problem in 2022. Will you please guide me how to get out of this bug.

**Comment by ezBeanie** [comment]
Approaching 2023, anyone has a solution to this issue?

**Comment by haykkh** [comment]
We implemented a(n ugly) fix for this which you can see in https://github.com/quilljs/quill/issues/409#issuecomment-1488435233

**Comment by Shama78** [comment]
Hi Guys, 
This is Shama(https://github.com/Shama78/ShamaShah1)
I have implemented this functionality and it works properly 
 // BOC Shama(01)
            editor.on('editor-change', function (eventName, delta, oldDelta, source) {
                // Only proceed if there's a format change or a text change
                if (eventName === 'text-change' || eventName === 'selection-change') {
                    let range = editor.getSelection();
                    if (range) {
                        const [line, offset] = editor.getLine(range.index);                    
                        if (range.length >= 0) { // Cursor placed without highlighting text                           
                            if (line && line.domNode.tagName === 'LI') {                                                       
                                let startIndex = range.index - offset;
                                let format = editor.getFormat(startIndex, 1);                           
                                if (format.size && source === 'user') {
                                    // Apply the format size only if it's a user action causing the change
                                    line.domNode.style.fontSize = format.size;
                                }
                            }
                        } 
                        else { // User has highlighted text
                            let lines = editor.getLines(range.index, range.length);
                            lines.forEach(function(line) {
                                if (line.domNode.tagName === 'LI') {
                                    const [lineStart] = editor.getLine(range.index - offset);
                                    let format = editor.getFormat(range.index, range.length);
                                    if (format.size && source === 'user' && lineStart === line && offset === 0) {
                                        // Apply the selected format size to each highlighted line
                                        line.domNode.style.fontSize = format.size;
                                    }
                                    else
                                        return
                                }
                            });
                        }
                    }
                }
            });
            //EOC Shama(01)
            This is the best code implemented by me

**Comment by mwiesenbauer** [comment]
Issue still exists in Quill 2.0, please reopen.

**Comment by AbhishekRanjan0093** [comment]
Is there a fix for it yet?
