### ISSUE TITLE
Conflict with bootstrap-select.js

### ISSUE THREAD

**Issue by shohrukhsultanov** [quilljs/quill#2857]
Hello. I installed quill on yii2. Everything works fine, but when I connect bootstrap-select.js in the editor toolbar, the “nothing selected” button appears. How can I get around this conflict without disabling the editor or bootstrap-select.js?
![image](https://user-images.githubusercontent.com/28265370/69934024-87ba5c00-14f2-11ea-828e-e22fdfbc5643.png)

**Comment by awatertrevi** [comment]
You can prevent this by doing something like this;

`$('select:not(.ql-header)').selectpicker();`

**Comment by benbro** [comment]
Answered.
