### ISSUE TITLE
Unexpected behavior when trying to delete ordered list item

### ISSUE THREAD

**Issue by kembuco** [quilljs/quill#286]
When an ordered list is the first element in the editor, it cannot be deleted by using backspace or by selecting the text and deleting.  The only way it can be deleted is to create more than one ordered list item, press ctrl+a, then delete.

Platform: IE9/Win (VMware Fusion)

Steps:
1) In an empty editor, click the ordered list button to create an ordered list
2) Press the backspace key

Expected result:
The ordered list should be removed

Actual result:
The ordered list persists.

**Comment by Raiseupcreativity** [comment]
confirm on Chrome 39.0.2 / linux
