### ISSUE TITLE
Custom format font-family has double double quotes on getFormat

### ISSUE THREAD

**Issue by Yexan** [quilljs/quill#2863]
Hi, 

There is a formatting issue with `quill.getFormat(quill.selection.savedRange)`

If you declare a custom font-family, the format retrieve by the getFormat method as describe before is surrounded by 2 double quotes, like this : 
<img width="483" alt="Capture d’écran 2019-12-06 à 15 48 41" src="https://user-images.githubusercontent.com/5166810/70331729-5a4a1700-1840-11ea-87f1-e2465b678b4f.png">

I could modify it with a `.replace(/"/g, '')` to use it manually, but, the `ql-picker` are broken because I don't have the hand on it, it takes a `select` and replace it by is own cooked version using the format object to handle the "selected" item.

Here is my custom font-family declaration if needed :

```typescript
const Parchment = Quill.import('parchment')

const getConf = (scopeName: string, whitelistValue: string[]): any => {
  return {
    scope: Parchment.Scope[scopeName],
    whitelist: whitelistValue
  }
}

const customFontFamily = new Parchment.Attributor.Style(
  'customFontFamily', 'font-family', getConf('INLINE', availableFonts)
)

Quill.register(customFontFamily, true)

```

Notes : 
 - _All my other custom formats works fine_
I've got lineHeightStyle, letterSpacingStyle, colorStyle, bottomSpaceStyle, customSize, textAlignStyle

- _I've tried different way to format the inline style_
On the default content loaded to the editor I've tried to declare the font-family with simple quotes or without any quotes.

- _availableFonts_
My `availableFonts` variable is an array of strings declared with single quoted string like 
```typescript
export const availableFonts = [
  'Memimas-Bold',
  'Neutraface Display Bold',
  'MrsEavesRoman',
  'GeosansLight',
  'Neutraface Display Medium',
  'TriplexSansLight',
  'MrsEavesBold',
  'Caviar Dreams',
  'Amandine',
  'Annabel Script',
  'Comiquita Sans',
 ...
]
```

- _I did research on issues_
By searching in issues I found some topics a bit similar (but not precisely related to this case) so it could be a know issue actually.

**Comment by Yexan** [comment]
@jhchen @benbro Any feedbacks / leads on this please ?

**Comment by Yexan** [comment]
Well, 

I found a way to _fix_ it, even if what I shown earlier is still a bug and should be taken in consideration.

If someone encounter the same issue as described , here is a way to (temporary?) fix it : 

Replace 
```typescript 
const customFontFamily = new Parchment.Attributor.Style(
  'customFontFamily', 'font-family', getConf('INLINE', availableFonts)
)
```
By 
```typescript
class FontStyleAttributor extends Parchment.Attributor.Style {
  constructor(a: any, b: any, c: any) { super(a, b, c) }
  value(node) {
    return super.value(node).replace(/["']/g, '')
  }
}

const customFontFamily = new FontStyleAttributor('customFontFamily', 'font-family', {
  scope: Parchment.Scope.INLINE,
  whitelist: availableFonts
})
```

**Comment by Yexan** [comment]
In order to fix the issue, I submitted a pull request on Parchment, you can found it here : 
https://github.com/quilljs/parchment/pull/75

**Comment by Yexan** [comment]
@jhchen @benbro Up.

**Comment by oleghind** [comment]
there are actually many issues with font names: font families got wiped out, font names with numbers don't apply etc. Those parts of the code need more improvements
