### ISSUE TITLE
Quilljs.com and CDN is down

### ISSUE THREAD

**Issue by oskar-szwajkowski** [quilljs/quill#2867]
Quilljs.com is not working, also quill CDN is not working, so all css can't get downloaded, which means that any codepen playgrounds does not work either.

**Steps for Reproduction**

1. Visit quilljs.com

**Expected behavior**:
Site loads

**Actual behavior**:

This site can’t be reached
quilljs.com refused to connect.

**Comment by weiyinfu** [comment]
Why do you close this issue?

**Comment by oskar-szwajkowski** [comment]
Because it works now, both site and cdn.
Just visit quilljs.com or https://cdn.quilljs.com/0.16.0/quill.snow.css
