### ISSUE TITLE
Browser hangs when inserting image into the editor.

### ISSUE THREAD

**Issue by laneme** [quilljs/quill#2868]
I'm using Firefox Developer Edition. This is the code I used to insert images.

`editor.insertEmbed(
       editor.getSelection(),
       'image',
      "//source.unsplash.com/random"
);`

The browser just hangs there until I stop the script twice and the image finally finishes loading.

**Comment by ParkerGreyAddison** [comment]
Are you running this line using the Firefox Console or directly in your JavaScript file?  If you're only having issues running from the console, then it may be that Quill and Console have some beef... #2846 

I'm running Firefox 71.0 (not the Developer edition), but I'm able to execute that line from both the console and my main file.

**Comment by Jonney** [comment]
> 
> 
> Are you running this line using the Firefox Console or directly in your JavaScript file? If you're only having issues running from the console, then it may be that Quill and Console have some beef... #2846
> 
> I'm running Firefox 71.0 (not the Developer edition), but I'm able to execute that line from both the console and my main file.

Thank you for your help, it's useful.
