### ISSUE TITLE
Quilljs CDN warning

### ISSUE THREAD

**Issue by JamesGelok** [quilljs/quill#2869]
Just wanted to make a quick issue notice 

**Steps for Reproduction**

1. Use quiljs via the CDN
2. Open the page in chrome, with the console open.

**Expected behavior**:

No chrome warning.

**Actual behavior**:

This warning appears: 
> A cookie associated with a cross-site resource at http://quilljs.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Platforms**:

Chrome: 78
MacOS: Catalina

**Version**:

1.3.6

**Comment by benbro** [comment]
Can't reproduce
https://v2.quilljs.com/standalone/full
