### ISSUE TITLE
Error when trying to update text

### ISSUE THREAD

**Issue by brunoksato** [quilljs/quill#287]
I wanted to update the selected text by adding a <spam class = "sub"> text </ span>, but when I try to do this, or it shows how a text and not as an HTML or an error occurs when you try this way

     var configs = {
        theme: 'snow'
      };

      var quill = new Quill( '#editor', configs );
      quill.addModule( 'toolbar', { container: '#toolbar' } );

      var textSelection = {
        text: '',
        rangeStart: 0,
        rangeEnd: 0
      };

      quill.on( 'selection-change', function( range ) {
          if ( range ) {
            if ( range.start == range.end ) {
            } else {
              textSelection.text = quill.getText( range.start, range.end );
              textSelection.rangeStart = range.start;
              textSelection.rangeEnd = range.end;
            }
          } else {
          }
        });

      function saveSub () {

        quill.deleteText( textSelection.rangeStart, textSelection.rangeEnd );
        quill.insertText( textSelection.rangeStart,
           quill.setHTML( '<span class="subCapitulo">' +  textSelection.text + '</span>' )
        );

      }

and when I do so, it puts the string and not HTML

      function saveSub () {

        quill.deleteText( textSelection.rangeStart, textSelection.rangeEnd );
        quill.insertText( textSelection.rangeStart,'<span class="subCapitulo">' +  textSelection.text + '</span>'
        );

      }

Existed any way to do this?

**Comment by jhchen** [comment]
`insertText` is for text not HTML. There is no API for inserting a fragment of HTML arbitrarily.
