### ISSUE TITLE
Quill doesn't saniteze URLs properly when inserting embed with blob url

### ISSUE THREAD

**Issue by laneme** [quilljs/quill#2870]
I'm inserting in a typical way you would do.

```
editor.insertEmbed(editor.getSelection().index, 'image', blobURL);
```

But the img ends up with an `://0` URL. The blob URL is perfectly fine. And everything works fine I just disable sanitization like this.

```
var Image = Quill.import('formats/image');
Image.sanitize = url => return url;
```

**Comment by SalilMittal** [comment]
Hi did you find a solution? Please tell

**Comment by laneme** [comment]
@SalilMittal  I don't think i did. You could probably write a custom sanitizer thou and plug into `Image.sanitize`
