### ISSUE TITLE
Support for multiple line-breaks within a single paragraph

### ISSUE THREAD

**Issue by kravemir** [quilljs/quill#2872]
Lines and paragraphs are not same things in typography. Usually, there's a spacing between paragraphs, which less than the height of a full line, unless there are different elements involved like figures, headings,... And, sometimes, there's a need to use multiple simple line-breaks for the same paragraph.

**Steps for Reproduction**

1. Visit https://quilljs.com/ (demo editor),
2. Experiment a bit with line breaks (single enter press, double enter press,...),
3. Inspect `class="ql-editor"` component.

**Expected behavior**:

There can be produced output allowing multiple line-breaks within a single paragraph, like:

```html
<p>Some text paragraph</p>
<p>
  Another text paragraph:<br/>
  with<br/>
  multiple<br/>
  lines
<p>
<p>Another paragraph</p>
```

**Actual behavior**:

Can't produce output above.

**Suggested behaviour**

Simply: when an enter is pressed once, then a line-break is produced. When enter is pressed twice, then a new paragraph is produced.

Technically:

- when enter is pressed after text (ie. single enter press), then a new line is produced,
- when enter is pressed at the beginning of the line (ie. double enter press), then the line is converted to paragraph.
- when delete is pressed on the beginning of the line, then line is merged with previous one,
- when delete is pressed on the beginning of the paragraph, then paragraph is converted to line, and belongs to previous paragraph.

Not covered:
- how to treat multiple successive empty lines/paragraphs.

**Platforms**:

```
$ uname -a
Linux miroslav-laptop 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ google-chrome --version
Google Chrome 78.0.3904.108 
```

**Version**:

The published one, when this issue is written.

**Comment by markleppke** [comment]
To support this request, the HTML spec calls out how this is the expected implimenation

**Comment by markleppke** [comment]
To support this issue, here is the HTML spec relating to semantic markup: https://www.w3.org/TR/html52/textlevel-semantics.html#elementdef-br

**Comment by DarthSomebody** [comment]
+1
This is one of the most basic features that every text editor must have. Has no one written a module for that?

**Comment by npcole** [comment]
+1
This is an essential feature for digital humanities work — both for editing academic writing and for editing transcriptions of primary texts.

**Comment by npcole** [comment]
(Though whether this should be done automatically — or with a shift enter — is very much open to debate. Following most word processors, it should be the latter.)

**Comment by maxfahl** [comment]
I'd really like to see shift+enter being added to Quill. It seems the maintainers don't see this as an issue though, they have licked/closed threads discussing this feature before. There are some experimental implementation made by people, but they don't work as expected. Too bad this is not being added, to be honest.

**Comment by jwhiting** [comment]
What we need is a Parchment implementation that can be added as a module to core. As seen in #252 which is old and locked, Quill maintainers don't think this behavior should be in core, but that it should be feasible as a module. I'm new to Quill but am willing to help with that effort, if someone more experienced with the internals knows a path through the woods. The module probably needs a configuration to set shift+enter vs enter means new paragraph vs new line break.

**Comment by Jagadeeswarh** [comment]
@jwhiting Did you find any working solution?

**Comment by jwhiting** [comment]
@Jagadeeswarh no I have not found anything existing. I think it needs to be written, and for that I need assistance from someone with more experience on Quill in this regard. Please chime in if you find anything, and I will do the same. For now I'm just punting on the issue and living with the default Quill behavior.

**Comment by athanasius-kircher** [comment]
At least I stumbled about this: https://codepen.io/mackermedia/pen/gmNwZP.

**Comment by NikolaDojic** [comment]
+1

**Comment by NikolaDojic** [comment]
+1

**Comment by AlvaroDeen** [comment]
nothing yet?

**Comment by mauriblint** [comment]
is there any solution in 2024? so annoying this!

**Comment by maksym-chupyna** [comment]
@mauriblint maybe this can help https://github.com/slab/quill/issues/4248#issuecomment-2634898120

**Comment by jowin202** [comment]
+1

**Comment by maxfahl** [comment]
+1 (again)

**Comment by mroozspace** [comment]
+1

**Comment by amirrbenasr** [comment]
+1

**Comment by lucagtc** [comment]
+1

**Comment by bolonio** [comment]
+1
