### ISSUE TITLE
Hyperlink with ‘beacon://’ do not work

### ISSUE THREAD

**Issue by HuangDaWei-fs** [quilljs/quill#2876]
**Steps for Reproduction**

1. select link.
2. enter value with ‘beacon://xxx’
3. click save

**Expected behavior**:
hyperlink's value should be 'beaco://xxx'
```html
<a href="beacon://xxx" target="_blank">some text</a>
```
**Actual behavior**:
hyperlink's value was 'about:blank'
```html
<a href="about:blank" target="_blank">some text</a>
```
**Platforms**:
chrome

**Version**:
version of quill.js  is 1.3.6

**Comment by padraigfl** [comment]
By default I believe all links are relative if they don't begin with http, what you need to do is import and update the sanitize function in the Link format


Untested but the following _may_ work
```
    const Link = Quill.import('formats/link');
    Link.sanitize = url => url;
```

**Comment by HuangDaWei-fs** [comment]
> By default I believe all links are relative if they don't begin with http, what you need to do is import and update the sanitize function in the Link format
> 
> Untested but the following _may_ work
> 
> ```
>     const Link = Quill.import('formats/link');
>     Link.sanitize = url => url;
> ```


I found a variable in source code in quill.js named PROTOCOL_WHITELIST 
```javascript
Link.PROTOCOL_WHITELIST = ['http', 'https', 'mailto', 'tel'];
```
there is no 'beacon', so i add 'beacon' to it, it works
```javascript
Link.PROTOCOL_WHITELIST = ['http', 'https', 'mailto', 'tel', 'beacon'];
```
