### ISSUE TITLE
Dynamic ES6 import gives ChunkLoadError

### ISSUE THREAD

**Issue by ErikLarsson82** [quilljs/quill#2877]
I'm trying to import quill dynamically since i render both on server and client and static import of quill needs a DOM - which is not present on the server. Not sure if this is an error caused by webpack, quill, both or neither.

This code
![dynamic-import](https://user-images.githubusercontent.com/4123744/71173614-7ba8fb00-2263-11ea-9ad5-ed1128852114.PNG)
Gives this error
![chunkload](https://user-images.githubusercontent.com/4123744/71173623-7f3c8200-2263-11ea-8e7d-a74c43aa6978.png)

If i try to import my own modules dynamically i get no thrown errors and the expected module.

**Steps for Reproduction**

1. Add the code above to a repo using webpack
2. Make sure the module you are trying to access dynamically is present - it successfully imports
3. Import quill in the same manner - you will now get thrown error
bootstrap:105 Uncaught (in promise) ChunkLoadError: Loading chunk 0 failed.
(error: https://vis.local/reportadmin/0-bundle.js)
    at Function.requireEnsure [as e]

**Platforms**:
PC, Windows, Webpack 4.41.4, Quill 1.3.7

Note. Using old require syntax works
![dynamic-require](https://user-images.githubusercontent.com/4123744/71174129-b8292680-2264-11ea-9386-fd5f874d2314.PNG)
![quill](https://user-images.githubusercontent.com/4123744/71174146-c5461580-2264-11ea-9524-360c1ad43748.PNG)

**Comment by gavinbarron** [comment]
I saw a similar issue lazy loading when the public path in my webpack config was slightly off.

Double check the url that the browser is attempting to load and compare it with the actual path that the expected chunk is located at. In my case omitting the trailing / from a CDN URL broke this specific chunk

**Comment by tettusud** [comment]
@gavinbarron  could you explain more how you resolved it? actually I am embeddeding my angular app in php.Is that possible to not let it generated as a separate chunk file?

**Comment by gavinbarron** [comment]
@tettusud for me it was making sure that the public path settings in webpack was `https://mycdndomain.net/` as opposed to `https://mycdndomain.net` 

if you just do a straight import as opposed to a dynamic one then webpack shouldn't try and put it in a separate chunk.

try `import * from 'quill'; ` not `import('quill').then(() => { /* do stuff */ });`

**Comment by tettusud** [comment]
Thank you @gavinbarron , am actually using in angular typescript. I am importing the way you mentioned. As It will be plugged in dynamically on any domain, it may be hard for me to specify the domain name. However thanks for clarification.

**Comment by gavinbarron** [comment]
I think you're misunderstanding my first point. We host our production sites in such a way that the static assets are available via a CDN refer to this webpack documentation on this: https://webpack.js.org/guides/public-path/

Which style of import are you using?

**Comment by tettusud** [comment]
Yeah got it. Let me try to configure public path and give a try. Cheers

**Comment by benbro** [comment]
Please try [v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2)

**Comment by ErikLarsson82** [comment]
Hi,
I first tried to reproduce the error on webpack version 4.41.4, but got stuck installing webpack-cli peer dependencies.
I did however try both version 1.3.7 and 2.0.0-beta.2 with Vite, and both worked exactly as expected!

**Comment by luin** [comment]
I assume this is not a Quill issue so closing. Here's a webpack example in case anyone encounters any issues: https://github.com/quilljs/webpack-example.
