### ISSUE TITLE
How to minimize a Delta without instantiating an editor?

### ISSUE THREAD

**Issue by BitPhinix** [quilljs/quill#2881]
Hi, is there any way to convert/re-render a quill Delta to only be composed of (a minimal amount of) insert operations? Saving the entire Delta for a document inside the database is a waste of storage space and slows down initial client load times significantly.

**Comment by weiyinfu** [comment]
why do you close this issue?

**Comment by weiyinfu** [comment]
If you got solution, please describe your solution.
