### ISSUE TITLE
How can I change the default value of the input box

### ISSUE THREAD

**Issue by lzxb** [quilljs/quill#2884]
![image](https://user-images.githubusercontent.com/8424643/71400131-c6aa8000-2660-11ea-95d3-94b01c3f6393.png)

Version: 1.3.7

**Comment by padraigfl** [comment]
Related ticket https://github.com/quilljs/quill/issues/1107 nothing to suggest it has been fixed yet but the workarounds probably should work still

**Comment by lzxb** [comment]
Let me try.
