### ISSUE TITLE
parse html incorrect when contain vietnam characters

### ISSUE THREAD

**Issue by Sesna** [quilljs/quill#2886]
quill parse html incorrect when my characters include special characters.
for example:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf8">
  <title>test quill parse html</title>
  <link href="https://cdn.quilljs.com/1.3.7/quill.snow.css" rel="stylesheet">
</head>
<body>
  <div id="editor">
  </div>
  <script src="https://cdn.quilljs.com/1.3.7/quill.js"></script>
  <script>
    var quill = new Quill('#editor', {
      theme: 'snow'
    });
    var html = '<h2>Ý nghĩa của những chỉ số đo lường hiệu quả quảng cáo:</h2><p><strong>Ý n</strong></p>'
    quill.pasteHTML(html);
    console.log(quill.root.innerHTML);
    // <h2>Ý nghĩa của những chỉ số đo lường hiệu quả quảng cáo:</h2><h2><br></h2><p>Ý n</p>
  </script>
</body>
</html>
```

**Steps for Reproduction**

1. create a html file and paste the html code above
2. open it on browser
3. quill parse the html content incorrectly

**Expected behavior**:
quill.root.innerHTML == `<h2>Ý nghĩa của những chỉ số đo lường hiệu quả quảng cáo:</h2><p><strong>Ý n</strong></p>`
**Actual behavior**:
quill.root.innerHTML == `<h2>Ý nghĩa của những chỉ số đo lường hiệu quả quảng cáo:</h2><h2><br></h2><p>Ý n</p>`
**Platforms**:
OS: Mac Catalina 10.15.2
Browser: Chrome 79.0.3945.88、Safari 13.0.4、Firefox 70.0.1

**Version**:
Quill: 1.3.7

**Comment by arturskeeled** [comment]
Happens if there's a letter with tréma (example: ä) followed by a <strong> tag.
Same here.

**Comment by YNestA** [comment]
> Happens if there's a letter with tréma (example: ä) followed by a \<strong\> tag. Same here.

Did you solve it?
