### ISSUE TITLE
Grunt server doesn't rebuild output JavaScript files

### ISSUE THREAD

**Issue by kunitsin** [quilljs/quill#289]
README.md states that `grunt server` starts a local server that will build and serve assets on the fly. However, `quill.js` file was not rebuilt when I changed its CoffeeScript source (`grunt dist` works well, though).
This is what I did:
1. Build files with `grunt dist`.
2. Start `grunt server` in repo root directory.
3. Fetch `http://localhost:9000/dist/quill.js`.
4. Change source CoffeeScript files somehow. What I did is I placed `alert "!"` in the beggining of `src/index.coffee` file.
5. Fetch `http://localhost:9000/dist/quill.js` again.
What will happen that this file won't change. However, if I rebuild it with `grunt dist`, it will update, and alert will flash in a page that includes `http://localhost:9000/dist/quill.js`.
My grunt-cli is 0.1.13, and grunt is 0.4.5.

**Comment by jhchen** [comment]
You only have to do `http://localhost:9000/quill.js`. The `dist/ folder` is the static output that is built for bower but for development just use `http://localhost:9000/quill.js`. The available paths that are built on the fly basically mirror the .build/quill folder (created when you run `grunt release`).
