### ISSUE TITLE
Unexpected delta for nested containers

### ISSUE THREAD

**Issue by alnidok** [quilljs/quill#2891]
Hello. I use quill to edit article html. Article looks like content with marginal notes:
<img width="1280" alt="aside-container" src="https://user-images.githubusercontent.com/5506837/71621784-6b3d3c80-2be2-11ea-90e4-d825de14b46e.png">
Some blocks contain left (.aside-content) and right (aside) columns:

```html
<p>begin root paragraph</p>

<div class="aside-container">
  <div class="aside-content">
    <p>aside content paragraph 1</p>
    <p>aside content paragraph 2</p>
  </div>
  <aside>
    <p>aside column paragraph</p>
  </aside>
</div>

<p>end root paragraph</p>
```
In this [codepen DEMO](https://codepen.io/alnidok/pen/dyPVWYq?editors=1010) I use custom containers and clipboard matcher.
But result is incorrect:
```html
<p>begin root paragraph</p>
<div class="aside-container">
  <div class="aside-content">
    <p>end root paragraph</p>
    <p>aside content paragraph 1</p>
    <p>aside content paragraph 2</p>
  </div>
  <aside>
    <p>aside column paragraph</p>
  </aside>
</div>
```
and result Delta contains only 1 operation: 
```json
{"ops":[{"insert":"begin root paragraph\nend root paragraph\naside content paragraph 1\naside content paragraph 2\naside column paragraph\n"}]}
```

**Demo**
[Codepen](https://codepen.io/alnidok/pen/dyPVWYq?editors=1010)

**Version**:
2.0.0-dev.2

**Comment by loagit** [comment]
Hello. Regarding the code shown, could you explain to me how (and if) you were able to define an element container? Your presented code appears to allow you to have block elements within other block elements. How did you manage to do that? Is your code working?

**Comment by alnidok** [comment]
@loagit, yes, see example [pen](https://codepen.io/alnidok/pen/dyPVWYq?editors=1010)
```javascript
const Block = Quill.import('blots/block');
const Container = Quill.import('blots/container');

class AsideContainer extends Container {...}
class AsideContent extends Container {...}
class Aside extends Container {...}

AsideContent.blotName = 'aside-content';
AsideContent.tagName = 'DIV';
AsideContent.className = 'aside-content';
AsideContent.allowedChildren = [Block];

Aside.blotName = 'aside';
Aside.tagName = 'ASIDE';
Aside.allowedChildren = [Block];

AsideContainer.blotName = 'aside-container';
AsideContainer.tagName = 'DIV';
AsideContainer.className = 'aside-container';
AsideContainer.allowedChildren = [AsideContent, Aside];
```
I generate dom structure on AsideContainer create and use clipboard matcher (search `this.quill.clipboard.addMatcher`). For example if I change `AsideContainer extends BlockEmbed`, result delta will be correct but content in this block can't be edit.

**Comment by alnidok** [comment]
Can someone help with this?

@jhchen I want to create custom blot that includes several editable blocks? What am I doing wrong? See a start message please. [Codepen](https://codepen.io/alnidok/pen/dyPVWYq?editors=1010)

**Comment by alnidok** [comment]
fixed

**Comment by aldinezi** [comment]
@alnidok any info on how you fixed it?

**Comment by alnidok** [comment]
Your need to use new quill.js build:

old - https://cdn.quilljs.com/2.0.0-dev.2/quill.js - incorect delta
new - https://cdn.quilljs.com/2.0.0-dev.3/quill.js or https://cdn.quilljs.com/2.0.0-dev.4/quill.js - correct
