### ISSUE TITLE
Allow overriding toolbar button design for built-in formats

### ISSUE THREAD

**Issue by ienzam** [quilljs/quill#2897]
### Issue
Toolbar buttons like _bold_, _italic_, _underline_, etc cannot be overridden easily today.
For example, if we provide the following for toolbar:
```
<div id="toolbar">
  <button class="ql-button"> My custom design </button>
</div>
```
"My custom design" will be overridden with Quill's built-in icon.

### Proposal
Allow overriding toolbar button design easily by declaring the intention via a CSS class (`ql-custom`) in the button.
For example,
```
<div id="toolbar">
  <button class="ql-button ql-custom"> My custom design </button>
</div>
```
should leave "My custom design" as is.

If this seems okay, I can send a PR.

**Comment by ienzam** [comment]
1. Why this feature belongs in Quill core, instead of your own application logic
Overriding this in application logic is not possible (at least I can't find an easy way).
Possible alternatives:
* Declaring custom blot and custom keyboard handler
* Import 'ui/icons' and remove icon for the button, but this is a *global* operation.

2. Background of where and how you are using Quill
We are using Quill to provide HTML editing support.

4. The use case that would be enabled or improved for your product, if the feature was implemented
This feature will allow us to use our own icons to be consistent with the whole UX experience.

**Comment by benbro** [comment]
You can manually create a toolbar in HTML https://quilljs.com/docs/modules/toolbar/ and override styles with CSS.
