### ISSUE TITLE
Font is reset to default when press Tab in editor

### ISSUE THREAD

**Issue by fred104** [quilljs/quill#2900]
**Steps for Reproduction**

1. Visit https://quilljs.com/playground/#custom-fonts
2. Choose font to "Roboto"
3. Input "test" and press Tab key
4. Font back to "Aref Ruqaa"

**Expected behavior**:
Font should not be reset to default.

**Actual behavior**:
Font reset to default "Aref Ruqaa" when pressing Tab key.

**Platforms**:
Chrome

**Version**:
1.3.6

**Comment by nvoshchevska** [comment]
There are similar issues with Enter key
STR:
1. Select Font
2. Press Enter

**Expected:** font type is not changed in the toolbar
**Actual:** font type changed to default in the toolbar

Repoduce also for font color and font background icons
