### ISSUE TITLE
Quill inserts a useless line-break before the <ul> element

### ISSUE THREAD

**Issue by flockisoft** [quilljs/quill#2905]
Unfortunately quill insert a line-break if you paste the following html into the editor:

`<p>Simple list:</p><ul><li>item one</li><li>item two</li></ul><p><br></p>`

The behavior of `pasteHTML()` or `convert(), setContents()` is the same.

**Steps for Reproduction**

1. Visit https://codepen.io/iice/pen/vQKrWY
2. change line in js to `var html = <p>Simple list:</p><ul><li>item one</li><li>item two</li></ul><p><br></p>;`
3. Watch what happens in the Viewer

**Expected behavior**:

Quill should not insert an line-break before the `<ul>` - because this sums up.
The first time it insert a line-break, then we save it, then quill inserts the second line-break, we save again, and so on...

**Actual behavior**:

Simple list:

- item one
- item two

**Platforms**:

Chrome 79
Windows 10

**Version**:
1.3.7

Run `Quill.version` to find out

**Comment by flockisoft** [comment]
After playing a little bit i found two ways to prevent quill to insert the line-break

1) prepend the `<ul>` by an empty a paragraph
`<p>Simple list:</p><p></p><ul><li>item one</li><li>item two</li></ul><p><br></p>`

2) wrap the `<ul>` by a paragraph
`<p>Simple list:</p><p><ul><li>item one</li><li>item two</li></ul></p><p><br></p>`

**Comment by mtycholaz** [comment]
I'm experiencing the same issue. This is frustrating a client of mine because if they make any change (make a word bold for example), a new empty `<p>` is added, which pushes down their content. The result is that the space keeps growing bigger every time they save.

**Comment by ivangarcia2** [comment]
I'm having the same issue

**Comment by RedefineMike** [comment]
I'm having the same issue as well. Looking through the code.

The problem appears to be that on load, Quill is inserting a Block blot (p) tag before the ul, which by default contains a br as a child. Presumably that is the default behavior so the user can click there and type after creating it. I'm working my way up the chain to see if I can find what is actually making the decision to insert that item.

**Comment by deniskabalkin** [comment]
Same problem, please fix =)

**Comment by mhdhamouday** [comment]
I'm having the same issue

**Comment by mhdhamouday** [comment]
I fixed it by disabling matchVisual, but I think we should find better solution.

```
var quill = new Quill('.quill', {
    theme: 'snow',
    modules: {
        toolbar : [...]
        clipboard: {
            matchVisual: false
        }
    }
});
```

**Comment by Triggsy22** [comment]
I have the same problem and i found another solution. But its not a good one, so i still hope that this Bug got fixed properly.

setContents() wants a delta object. And we just force a linebreak at the end of this delta object. So that not only at the end of our bugy delta object is a linebreak. Its at the end of all of them. And then we hide the linebreak with CSS.

Javascript
```
addLinebreakToTheEndOfDelta(delta){//---
    if(typeof delta.ops[delta.ops.length -1].insert === 'object')
        return delta;//in my tests we dont need to worry about this.
    if(delta.ops[delta.ops.length -1].insert === '\n')//if \n appears twice, we have to remove one.
        delta.ops.pop();
    if(typeof delta.ops[delta.ops.length -1].insert === 'object')
        return delta;
    let strlen = delta.ops[delta.ops.length - 1].insert.length;
    if(delta.ops[delta.ops.length - 1].insert.substr(strlen - 2, strlen) !== '\n') {//we add a \n at the end.
        delta.ops.push({insert: '\n'})
    }
    return delta;
}
```

SCSS
```
.ql-editor{
  > p:last-child{
    margin: 0;
    > br{
      display: none;
    }
  }
}
```

**Comment by mtycholaz** [comment]
@Triggsy22 thanks for sharing. I plan to take a look at this further. For my own clarity, where did you implement the `addLinebreakToTheEndOfDelta` method?

**Comment by Triggsy22** [comment]
`quillEditorObject.setContent(addLinebreakToTheEndOfDelta(delta))`
i have the quillEditorObject and call setContent.
setContent wants a delta object.
and instead of giving it directly to setContent i give it to addLinebreakToTheEndOfDelta and the result to setContent

**Comment by dmarsola** [comment]
Recreated the issue with a simple page based on the example usage provided. You can see that the extra line is created if a single paragraph is followed by the bullets. Two consecutive paragraphs will not give the same error.

https://codepen.io/dmarsola/pen/KKWXoVE

**Comment by peter-elliott-ms** [comment]
> I fixed it by disabling matchVisual, but I think we should find better solution.
> 
> ```
> var quill = new Quill('.quill', {
>     theme: 'snow',
>     modules: {
>         toolbar : [...]
>         clipboard: {
>             matchVisual: false
>         }
>     }
> });
> ```

it a appears as though that was the ultimate solution in later versions of quill:
https://github.com/quilljs/quill/commit/3897c981fcabc599ce3b90793a33d40c4fa25fee
