### ISSUE TITLE
Issue with utf 8 characters

### ISSUE THREAD

**Issue by smarttvdev** [quilljs/quill#2907]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**:

**Actual behavior**:

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by BaiMaoLi** [comment]
Hello.
Thanks for your great plugin.
With your plugin, I could make assemese spell checking program and it was great.
But I have just one issue and I am not sure if it can be solved by you.
If it is solved, it would be great help for me.
when I get text by the function getText(), 
some assemese characters are being changed.
You can check with this word, "কিয়",
after copy above word into your editor, 
get text by getText() function and compare two words, 
Two word is not same.
Thanks, Best regards
