### ISSUE TITLE
Can't change quill's custom picker SVG

### ISSUE THREAD

**Issue by Yexan** [quilljs/quill#2908]
Hi, 

When you create a custom toolbar on Quill with a `select` `option`, it's replaced by Quill with a custom `.ql-picker` with `ql-picker-label` and `ql-picker-options`. 
Like in this custom exemple : 

![Capture d’écran 2020-01-20 à 09 18 05](https://user-images.githubusercontent.com/5166810/72709933-37f92800-3b66-11ea-9d5f-dbd12852458b.png)

I would like to change the "double arrow" SVG to an other SVG that match the required design of my product but I can't find a way to achieve this.

PS: I've looked stackoverflow and other websites, please don't answer me that it's not the place to ask this as it's not in specified the docs.

**Comment by Yexan** [comment]
For now I've done something dirty like this : 

```typescript
replaceSvg() {
  const svgs = Array.from(document.querySelectorAll('.ql-picker-label svg'))
  svgs.forEach((svgElem) => {
    svgElem.innerHTML = `<path d="M.707.707l3.305 3.305M7.317.707L4.012 4.012" fill="none" stroke="#14294a" stroke-linecap="round"/>`
    svgElem.setAttribute('viewBox', '0 0 8.024 4.719')
  })
}
```
```sass

.ql-snow .ql-picker:not(.ql-color-picker):not(.ql-icon-picker) svg
  width: 10px
  height: 10px
  right: 5px
  margin-top: -5px
  transition: transform .2s ease-in-out

.ql-picker.ql-expanded .ql-picker-label svg
  transform: rotateZ(180deg)
```

But I'm still waiting for a clean way to replace the svg ! 🙏

**Comment by aleksgrunwald** [comment]
Do you have a new way of replacing the icon?

**Comment by Yexan** [comment]
> Do you have a new way of replacing the icon?

Hey
No, unfortunately I'm still doing the same thing as described  with `replaceSvg()` 
Have a good day
