### ISSUE TITLE
getFormat in editor change event returns wrong text sizes on empty selection

### ISSUE THREAD

**Issue by vavon92** [quilljs/quill#2909]
The getFormat API call does not return the correct active text size format when called inside the editor-change event.

**Steps for Reproduction**

1. Visit https://codepen.io/Vavon/pen/WNbYMLx
2. Open console (F12)
3. Click inside the editor and do not write anything inside
4. Set text size to 'small'
5. Set text size to 'huge'
6. See console log, the formats printed in the editor-change event contain 'small' on size instead of 'huge' (it's always the previous selected one)

Note: it's reproducible also in the playground of the quill website

**Expected behavior**:
getFormat should return the current applied text size
**Actual behavior**:
getFormat inside the editor-change event returns always the previous selected size
**Platforms**:
Google Chrome Version 79.0.3945.117 (Official build) (64 bit)

**Version**:
1.3.7

**Comment by Greatshock** [comment]
I'm also facing this problem. Any updates on this?
