### ISSUE TITLE
Empty `formats` property is actually not disabling the formats on Quill 2.0.0-dev3

### ISSUE THREAD

**Issue by javascriptlove** [quilljs/quill#2910]
**Steps for Reproduction**

1. Visit https://codepen.io/jslove/pen/ZEYVOdq - notice the formats is empty array
2. Input any text
3. Select any text and apply bold via toolbar or ctrl+b

**Expected behavior**:

Bold should not be applied since formats is empty

**Actual behavior**:

Bold is applied

**Platforms**:

Chrome Version 79.0.3945.130 (Official Build) (64-bit)
MacOS 10.14

**Version**:

2.0.0-dev.3

**Notes**:
It works as expected on 1.3.6, so something broke in between

**Comment by DokaRus** [comment]
This option has been removed as a result of multiple registers support - #1101.
It seems that the alternative is to create an editor with registry that includes only the formats/blots you need (look at the `registry` option).
@jhchen is that right?

**Comment by javascriptlove** [comment]
But I still see this not being closed https://github.com/quilljs/parchment/issues/45
so it seems like a feature is removed with no solution yet?

**Comment by zouyifeng** [comment]
how can I use `registry ` to limit style in Quill 2.0 editor? like `formats` in Quill 1.0 work

**Comment by benbro** [comment]
https://v2.quilljs.com/docs/registries
