### ISSUE TITLE
Can't find 2.0.0-dev.3 code

### ISSUE THREAD

**Issue by BFUculsion** [quilljs/quill#2913]
The latest release of quill on npm is https://www.npmjs.com/package/quill/v/2.0.0-dev.3
However, I can't find that release in this repository, even though the package points back here.
Is there a way to get that code?

**Version**:

Run `Quill.version` to find out

**Comment by padraigfl** [comment]
I guess this is it, but I can't be 100% sure https://github.com/quilljs/quill/tree/883c2155f7bea54320952767081df5fe60e0b3ac

**Comment by BFUculsion** [comment]
Thanks for digging that up. Do you know  what's the release process for the 2.0 version?

**Comment by padraigfl** [comment]
I mean, it's super vague (literally nothing announced in 3 years) and so many people have started using dev versions that I imagine it really screws the exploratory process; I'd guess it's never coming out.

If it were me, I'd stick with v1, which has issues but the fundamentals are pretty stable, and focus on just tidying up the code and documentation, clarifying the niche it occupies.

**Comment by benbro** [comment]
[v2.0.0-beta.1](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.1)
