### ISSUE TITLE
Editor stops receive keyboard events

### ISSUE THREAD

**Issue by kurijov** [quilljs/quill#292]
Browser: Firefox 35.0.1
OS: Mac Yosemite

How to reproduce:

Delete all content in editor and press Cmd+Backspace.

Reproducable at examples page http://quilljs.com/examples/ 

Everything goes back to normal if you click on editor.

Thank you.

**Comment by jhchen** [comment]
Yes looks like on an empty document the backspace will delete the container which causes it to lose focus. We intercept backspaces because of that but Cmd+backspace is currently treated as a separate hotkey by the keyboard module.

**Comment by jhchen** [comment]
This has been fixed in the 1.0 [beta](http://beta.quilljs.com/) release
