### ISSUE TITLE
Formatting is not getting applied on text. User needs to click twice on Chrome 79.0 on Android device

### ISSUE THREAD

**Issue by harshal-ringe** [quilljs/quill#2921]
We are trying to use Quilljs editor in our Android application. We are using Android webview to render Quilljs editor in our application. The selected formatting is not getting applied on the text. This issue also occurs on Chrome 79 browser on Andorid Device(Webview is also using the same version). There is no issue for Web browsers.

**Steps for Reproduction**

1. Visit [https://codepen.io/HarshalRinge/details/poJomNj](https://codepen.io/HarshalRinge/details/poJomNj) . This issue also occurs on [https://quilljs.com/playground/](https://quilljs.com/playground/)
2. Type anything in the editor, then click on the bold button, type again and you will see text in bold
3. Now click on Italic button, Button icon will get highlighted, then type something. The text won't be formatted as Italic. This happens for other action too like, Underline and Strikethrough

**Expected behavior**:
On click of action buttons, the selected actions formatting should get applied to text.
**Actual behavior**:
Selected formatting(Italic/Underline/Strike-through) is not getting applied to text after typing. User has to type twice to get a formatted text. This happens on the Android Device Chrome browser. On a Web browser, it is working fine.
**Platforms**: Android 7.1.1 (Samsung J5)
**Browser**:  Chrome 79.0.3945.136
**Version**: 1.3.6

**Comment by harshal247software** [comment]
Hi @jhchen and @byronm, Is there any work-around to resolve this issue?
