### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by paullaffitte** [quilljs/quill#2922]
CSS should not be used for localisation. Already a few tickets were opened about this (meaning that the users expect this to be changed), but all were closed for some obscure reasons. It's been asked for every two years until now (2014, 2016, 2018), we are in 2020 and I think user still wants this to be implemented (at least I would like).

- [Package for translate](https://github.com/quilljs/quill/issues/209)
- [How to localize the link tooltip in the Snow theme](https://github.com/quilljs/quill/issues/1192)
- [Localisation](https://github.com/quilljs/quill/issues/2339)

The current way to translate seems odd and counter-intuitive until you dig into those issues. Then you still have to search all the content property in the css of quill to find out how to translate those entry. And it sounds way more like a hack than an actual feature.

**Steps for Reproduction**

1. Try to use quill in your language (I think that make sense since not the whole humanity speaks English)
2. Realize that you have to write css 🤔

**Expected behavior**:

Be able to localize with js or at least json.

**Actual behavior**:

Localization can only be done with the ugly "content" property in css.

**Platforms**:

All

**Version**:

1.3.7

EDIT : I just found [another issue](https://github.com/KillerCodeMonkey/ng-quill/issues/80) about this.

**Comment by dsebastien** [comment]
For those interested, I wrote a small article about this issue, detailling my approach for solving it: https://medium.com/@dSebastien/dynamically-customizing-quill-ngx-quill-editors-in-an-angular-application-b81c75bc4a6

**Comment by tmtron** [comment]
It would be great if quill could at least use [css-variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) for the translations (e.g. `--quill-i18n-enter-link`, ..)  
These are easy to override in custom css or from javscript.

**Comment by landau07** [comment]
Is there any plan to fix this issue? So we will able to provide via js the localized texts?
as we have resx file per language

**Comment by LukeTOBrien** [comment]
Hello,

I have just come across this issue because I am looking at using Quill in a coming project and I would just like to share how I do localisation in my projects.  
I like using `YAML` files, they are transformed into JSON and can be imported from [ParcelJS](https://parceljs.org/yaml.html) which is what I use, I believe Webpack and others should be able to deal with them too.

So developers could create a translation file for each language they wish to support:  
`quill-es.yaml`:
```yaml
VideoLabel: Ingresar video
VideoPlaceholder: Insertar URL
```

Then import into Quill config:

```ts
import es from './quill-es.yaml';

var quill = new Quill('#editor', {
  modules: {
    toolbar: '#toolbar'
  },
  theme: 'snow',
  translations: [ es ]
});
```

What do you think of this solution?

**Comment by aalejandromr** [comment]
+1. Localization is a big part of accessibility and cannot be disregarded.

**Comment by xxxKOTxxx** [comment]
Any updates here in the end of 2025?

**Comment by plaffitt** [comment]
For me the fix was migrating to https://github.com/ianstormtaylor/slate
