### ISSUE TITLE
Compatibility with version 2.0.0-dev.3 code

### ISSUE THREAD

**Issue by noah-lnt** [quilljs/quill#2925]
With version 2.0.0-dev.3 code, I get this error: 

> Uncaught TypeError: v.Attributor.Style is not a constructor

`<script src="https://cdnjs.cloudflare.com/ajax/libs/quill/2.0.0-dev.3/quill.min.js" type="text/javascript"></script>`

Futur compatibility with this version is planned ?

**Comment by pietro-saccani** [comment]
I've found out how to make it work.
In the code, replace the three `new d.Attributor.Style` with `new d.StyleAttributor`.
("d" might be a different letter for you, I guess)

**Comment by benbro** [comment]
Please try [v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2)
