### ISSUE TITLE
is there a way to get the selection position via mouse position?

### ISSUE THREAD

**Issue by minzojian** [quilljs/quill#2926]
the initial state of my editor is disable, and when double click, it switch to enable and focus.  
and i want let the caret position is just at the place where the mouse double click   
so my first thought is, if there is a method like `quill.getSelectionFromBounds(<a rectangle>)`  which can return a range or just a simple one `quill.getSelectionFromPoint(<a point>)` which can return a single caret potion, that would be helpful.

**Comment by welkinwong** [comment]
i have some code, it's work
```
const setBounds = event => {
  const selection = document.getSelection();
  const range = document.caretRangeFromPoint(event.clientX, event.clientY);

  if (selection && range) {
    selection.setBaseAndExtent(
      range.startContainer,
      range.startOffset,
      range.startContainer,
      range.startOffset,
    );
    return true;
  } else {
    return false;
  }
};
```
