### ISSUE TITLE
Where to find experienced Quill devs? (not an issue)

### ISSUE THREAD

**Issue by gavinhewitt** [quilljs/quill#2930]
This is probably not allowed, sorry, but did not know where to ask this better than here.

I'm trying to find someone that has experience building editors with Quill, but that proves to be very difficult. There's no Discord or Spectrum? Is there some other place other than here where you may find them? Genuine question.

For my project I need a custom editor and someone else will probably build it way faster than I could.

**Comment by ExamDay** [comment]
What kind of editor do you need?
