### ISSUE TITLE
If i paste the URL  in our quill editor its not converting into link, pasting the text only!

### ISSUE THREAD

**Issue by sanjeevi2016** [quilljs/quill#2931]
Hi there,

If i copy & paste the URL  in our quill editor its not converting into the link, pasting the text only so can you please guide me how to fix this issue..? 

**Version**:  1.3.6  (using in vuejs)

Run `Quill.version` to find out

**Comment by vkoves** [comment]
@sanjeevi2016 - this is functionality called magic links, and I believe it's not built into Quill by default. The [quill-magic-url plugin](https://github.com/visualjerk/quill-magic-url) should be able to let you do that though!

I learned about it from the [awesome-quill repo](https://github.com/quilljs/awesome-quill) which links to a bunch of great plugins for extending Quill.
