### ISSUE TITLE
Call toolbar action from another UI element (Question)

### ISSUE THREAD

**Issue by retf** [quilljs/quill#2932]
I want create a context menu that trigger toolbar action. Anyone can give some direction, for sample i am trying call insert image from a user computer. I did this but do not work:

  insertImageFromUserComputer() {
            this.quill.insertEmbed(this.range.index, 'image', 'file');   
        }

**Comment by padraigfl** [comment]
I believe the simplest way to do this is to create a dummy file input element in the dom, fire a `.click()` action on it and then relay the passed in file to the editor.

This issue might give some ideas, not directly related though https://github.com/quilljs/quill/issues/1089
