### ISSUE TITLE
Need JSON structure to create models

### ISSUE THREAD

**Issue by pathaderavi-zz** [quilljs/quill#2936]
Currently I am writing a text module for the app (iOS/Android) which uses QuilJS for the web version of the same app. The issue is we save the text in our JSON document in the JSON format of which Quil provides the text and we let the Quil process the same while using it to display and edit. If we are supposed to use the same text JSON for the app (iOS/Android) we need the strict JSON models how Quil generates the text formatting to JSON.

**Comment by benbro** [comment]
https://quilljs.com/docs/delta/
https://quilljs.com/guides/designing-the-delta-format/
