### ISSUE TITLE
Simple way to match multiple classes from one blot or formatter?

### ISSUE THREAD

**Issue by natevw** [quilljs/quill#2937]
We are trying to add WYSIWYG editing to a body of existing content and I have been struggling with some of the details, and tying all the underlying concepts together.

End goal:

0. Without migrating existing content…
1. Have Quill/Parchment recognize our classes
2. And let the user toggle between them via a toolbar dropdown

Specifically, we have a number of existing elements annotated as e.g. `<p class="author">` , `<p class="overview">`, `<p class="credits">`, etc. My first pass, to keep Parchment from discarding the classes entirely, was to register block "blots" for each of them separately:

```
let Block = Quill.import('blots/block');
['author','overview','credits'].forEach((parStyle) => {
  class StyledParagraph extends Block {
    static formats(domNode) {
      return true;
    }
  }
  StyledParagraph.blotName = `my_${parStyle}`;
  StyledParagraph.className = parStyle;
  Quill.register(StyledParagraph);
});
```

However, things got more complicated when I tried to add these to a Quill toolbar. Via various threads e.g. https://github.com/quilljs/quill/issues/1099#issuecomment-258560326, I was able to at least get each one to appear separately by adding `let icons = Quill.import('ui/icons');` to the above code and adding ``icons[StyledParagraph.blotName] = `<b>[${parStyle}]</b>` `` within the loop (plus some CSS to `width: auto` the resulting buttons to fit my placeholder "icons").

But the more natural way for the user to access these would be via a mutually-exclusive dropdown, and I came up short trying to get that to work. It appears that rather having three separate `my_author`/`my_overview`/`my_credits` formatters I would need to combine them into one somehow.

But I can't simply `new Parchment.Attributor.Class('my_formats', 'my-prefix');` because the classes I need to recognize and re-generate **don't have** any hyphen-delimited prefix in common!

**Is it practical to create a Blot/formatter (still not sure how exactly how these concepts are distinct/related in Quill) that can recognize basically any elements it wants to by looking at arbitrary nodeName/className properties and deciding whether/how to match?**

If that's the case, then I would like to replace the existing "header" one with my own that detects all of `h1`, `h2`, `h3` *and* `p.author`, `p.overview`, `p.credits` and treats them as mutually-exclusive options that I can include in a `TOOLBAR_CONFIG =[ [{ my_style: ['title', 'subhead', 'h3', 'author', 'overview', 'credits', false] }] ]` group.

**Otherwise, is there some way I missed where I can simply group unrelated formatters together into a Quill toolbar dropdown?**

**Comment by timblack-NukeDigital** [comment]
I'm having some success using https://github.com/T-vK/DynamicQuillTools#adding-a-custom-drop-down-menu to create a drop-down menu and associate its options with click events.  It creates a drop-down containing arbitrary values, which you then have to apply to a selection in the `.onSelect` event handler (see example below).  I've run into challenges with the selection being lost when the drop-down is clicked, but believe that is because we are running Quill inside the shadow DOM, so I'm working on fixing those problems in a couple forks.

**Note:**  The code below has not been tested, so it might not work.

It would seem you could parse the HTML content in the `.ql-editor` element, something like

```javascript
const content = document.querySelector('.ql-editor').innerHTML
const classes = content.match(/class="(.*?)"/gi)
```
to create a list of existing classes, then feed that list into the drop-down via `myDropDown.setItems(dropDownItems)`.  Then you can modify the example on that page to be like this:

```javascript
myDropDown.onSelect = function(label, value, quill) {
    // Do whatever you want with the new dropdown selection here

    // For example, insert the value of the dropdown selection:
    const { index, length } = quill.selection.savedRange
    // Note the space character below after 'my-prefix-'.
    // Perhaps some other string manipulation here would solve the problem for you.
    quill.format('my-prefix', value.replace('my-prefix-', 'my-prefix- '));
    quill.setSelection(index + value.length)
}
```

If you have a fixed, known set of existing class names, could you modify your CSS to retain the existing class names, but add Quill-specific class names for the same style definitions, like this?

```css
.author, my-prefix-author {
    font-weight: bold;
}
```

**Comment by natevw** [comment]
> If you have a fixed, known set of existing class names, could you modify your CSS to retain the existing class names, but add Quill-specific class names for the same style definitions, like this?

**Comment by natevw** [comment]
Thanks Tim! Small world ;-)

> If you have a fixed, known set of existing class names, could you modify your CSS to retain the existing class names, but add Quill-specific class names for the same style definitions […]?

This will probably be my strategy when I circle back to this. As I worked through some other features I already ended up with a general infrastructure to "fixup" the HTML, translating it on its way in and then back out of the Quill editor.

So for this we could do similar, converting `.author` to `.my-prefix-author` before it goes into the editor, and reversing it on its way out for consistency. (I.e. in this case it wouldn't be the end of the world to just make the prefixed form the "official" version going forward, but all the other conversions are already symmetric….)

**Comment by timblack-NukeDigital** [comment]
I found this doesn't work; it throws the following error: `Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('my-prefix-my-prefix- 1') contains HTML space characters, which are not valid in tokens.`

```javascript
// Note the space character below after 'my-prefix-'.
// Perhaps some other string manipulation here would solve the problem for you.
quill.format('my-prefix', value.replace('my-prefix-', 'my-prefix- '));
```

@natevw your proposed solution sounds workable.
