### ISSUE TITLE
Documentation obfuscates `Quill.import` usage, making it unclear e.g. how to import non-default exports

### ISSUE THREAD

**Issue by natevw** [quilljs/quill#2938]
The [API documentation for Quill.import](https://quilljs.com/docs/api/#import) is misleading (emphasis mine):

> Static method returning Quill library, format, module, or theme. **In general the path should map exactly to Quill source code directory structure.**

And the example has a comment that using `Quill.import` is…

> // Similar to ES6 syntax `import Link from 'quill/formats/link';`

No other discussion is provided regarding exceptions to the "in general". So when I needed to get a non-default export that exists inside the "Quill source code directory structure" at `blots/block` I guessed I would have to do something like

```
let { BlockEmbed } = Quill.import('blots/block');    // WRONG
```

…and the `Quill.import` internals would have set things up so that all the other exports would be exposed as properties on the `Block as default` value it returns. But `BlockEmbed` gets an undefined value; apparently not much similarity to ES `import` as claimed.

Elsewhere in the documentation, I found [a more helpful note](https://quilljs.com/guides/how-to-customize-quill/#extending-blots):

> You can view a list of Blots and Attributors available by calling `console.log(Quill.imports);`. Direct modification of this object is not supported. Use `Quill.register` instead.

So the secret is that `Quill.import` actually has very little to do with filesystem paths and ES module syntax, and a whole lot more to do with what calls to `Quill.register` are made internally. Behold, in [quill/core.js](https://github.com/quilljs/quill/blob/9a77567fe356d384074df7479c33ceac509d9351/core.js) I found:

```
Quill.register({
  'blots/block': Block,
  'blots/block/embed': BlockEmbed,
  //…
```

As it turns out, my code should actually be:

```
let BlockEmbed = Quill.import('blots/block/embed');
```

**It would have saved me significant time if the API documentation for `Quill.import()` itself had confessed the connection with `Quill.register()` and ability to see what `Quill.imports` exist, instead of conveying the impression that it was more like the real ES module `import`.**

Related: https://github.com/quilljs/quill/issues/2659

**Comment by benbro** [comment]
Please try v2.0.0-rc.0
https://v2.quilljs.com/docs/installation
