### ISSUE TITLE
How to wrap all blocks/formats in a DIV element

### ISSUE THREAD

**Issue by ArsalanSavand** [quilljs/quill#2945]
I've already seen https://github.com/quilljs/quill/issues/861#issuecomment-239961806.
My question is how can I wrap every element in a DIV element. Example:
```html
<div>
  <p>Hello World</p>
<div>

<div>
  <h2>A title</h2>
</div>

<div>
  <blockquote>A testing sentense</blockquote>
</div>
```

Is it possible?

**Comment by ArsalanSavand** [comment]
Any help on this?

**Comment by gekido2802** [comment]
I would like to know too, but instead of div I would like to use span and have all the formats like font-size, font-family and color on that span.

**Comment by sri8484** [comment]
> gekido2802

Hi [gekido2802](https://github.com/gekido2802),

Did you get any solution to this requirement?
