### ISSUE TITLE
Text disappears on word spelling correction

### ISSUE THREAD

**Issue by floppyvlaDISK** [quilljs/quill#2947]
**Steps for Reproduction**
1. Copy text that contains styling(bold, highlighted etc).
2. Visit https://quilljs.com/playground/
3. Paste copied text into the editor
4. Misspell a word
5. Right click on the word to see correction options
6. Choose one of the options

**Expected behavior**:
Misspelled word is replaced by chosen option.

**Actual behavior**:
Misspelled word is replaced by white space.
"addRange(): The given range isn't in document." console error occurs.

![screenshot1](https://user-images.githubusercontent.com/25643386/75346693-f287f300-58a7-11ea-8424-3924d9ff4a86.png)

![screenshot2](https://user-images.githubusercontent.com/25643386/75346711-f7e53d80-58a7-11ea-962d-a30db1f85c7c.png)

![screenshot3](https://user-images.githubusercontent.com/25643386/75346717-fb78c480-58a7-11ea-9967-3e1f7c99523d.png)

**Platforms**:
Linux Ubuntu 16.04, Chrome 79.0.3945.88

**Version**:
1.3.6

**Comment by albandum** [comment]
Just had a user telling me the same thing, I don't have details about her specs

**Comment by oduchateau** [comment]
Hello, i have the same problem on Chrome, Brave, Opera...   
Firefox ok.
The problem occur in every platform. 
It's easy to reproduce **if the color is not  #000000.** 

![image](https://user-images.githubusercontent.com/75506351/101222291-c21c8300-3689-11eb-8c9e-deedb6457d60.png)

**Comment by mkaliszewski** [comment]
Bump on this one as it's still not fixed after over 2 years
