### ISSUE TITLE
Can not handle the paste event

### ISSUE THREAD

**Issue by bincxz** [quilljs/quill#2949]
Hi guys:
Now I'm trying to implements a function that if I detect user is pasting a single image file to editor,then prevent the orignal pasting event,uploading the image to server and finally insert the img via url.
I have try the  following methods,but seems no one of them work:
**1. Quill.clipboard.addMacher("img",function cb(node,delta){……});**
this method didn't work when I paste a single image file from desktop or drag a image from desktop to editor

**2.quill.root.addEventListener("paste",function(e){});**
this method could handle the paste event , but the image will always be pasted into the editor first,event I call e.preventDefault() method,the pasted action can't be stopped.

**Comment by padraigfl** [comment]
you'll probably need some manner of combined handler as the paste event will need to be a browser based one to access the item from the clipboard, but the matcher could perhaps swap it out with some kind of placeholder image while the upload works, following the response of the successful upload you would then swap the content from the placeholder image with the url of where the image is now hosted

**Comment by OnlyFlyer** [comment]
Hey, guys, It's works i mount to `document.body` paste event, you can try it.

**Comment by caocaocaodev** [comment]
> Hey, guys, It's works i mount to `document.body` paste event, you can try it.

Could you please add your code example here?
I'm facing same issue

**Comment by OnlyFlyer** [comment]
https://juejin.cn/post/6885348341375303688

```js

const quill = new Quill(document.body, {
  theme: "snow",
});

const ins = new ImageDrop(quill)

```
