### ISSUE TITLE
Inline Left align not working on already right aligned text using class

### ISSUE THREAD

**Issue by 9thQuadrant** [quilljs/quill#2951]
**Steps for Reproduction**

1. By using default quill configuration, right Align text and save whole html in server
2. Now edit the same text after changing quill behavior to use inline styles instead of classes by
```
const AlignClass = Quill.import('attributors/style/align');
Quill.register(AlignClass, true);
```
3. Left align the existing right aligned text

**Expected behavior**:
Remove `.ql-align-right` class and add inline `style="text-align: left"`. 

**Actual behavior**:
No Change in HTML

**Platforms**:
Chrome Windows 10

Include browser, operating system and respective versions
quill version: 1.3.7

**Version**: 1.3.7

Run `Quill.version` to find out

**Comment by smohadjer** [comment]
I ran into same problem today. Is Quill still being maintained at all? No feedback since February?!!

**Comment by alexzelenuyk** [comment]
I copied everything from this list https://github.com/quilljs/quill/issues/3277 and it helped.
