### ISSUE TITLE
Delta not formated properly with code

### ISSUE THREAD

**Issue by imabot2** [quilljs/quill#2955]
Not sure this is a bug, but I tried the Interactive Playground Form Submit on CodePen : https://codepen.io/imabot2/pen/YzXQPRG?=true

Here is the json produced:
{"ops": [
{"insert":"text\ncode"},
{"attributes":{"code-block":true},"insert":"\n"}
]}

I can't figure out why 'code' do not have the code-block attribute.

**Comment by imabot2** [comment]
> Attributes associated with a newline character describes formatting for that line.

**Comment by alexaaaant** [comment]
did you solve a problem?
