### ISSUE TITLE
App Inventor - Does not render the editor correctly.

### ISSUE THREAD

**Issue by ImanCol** [quilljs/quill#2956]
I am trying to use Quill in App Inventor. But I present a problem with two styles that do not want to be displayed correctly.

bubble works fine.
![image](https://user-images.githubusercontent.com/26169049/75612505-0a52b780-5af2-11ea-962d-7017f10f04bd.png)

full does not render well.
![image](https://user-images.githubusercontent.com/26169049/75612515-13dc1f80-5af2-11ea-9b4f-4c494a1cff0b.png)

Snow does not render well either.
![image](https://user-images.githubusercontent.com/26169049/75612517-19396a00-5af2-11ea-8893-10d83cedfbaf.png)

Test APk and Base project

[AI2-WYSIWYG_editor.zip](https://github.com/quilljs/quill/files/4270661/AI2-WYSIWYG_editor.zip)

Created in AI2 - Kodular
[https://creator.kodular.io/](url)

**Comment by benbro** [comment]
Please test with [v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2)
This is an issue with integration with third-party tool. Not a Quill issue.
