### ISSUE TITLE
How to use leaf from getLeaf

### ISSUE THREAD

**Issue by rj1102** [quilljs/quill#2957]
I like to know of by custom made blot (class Macro extends Inline) is on the current cursor position in the editor. I use:

```
var range = quill.getSelection(true);
var [leaf, offset] = quill.getLeaf(range.index + 1);
console.log(leaf.value()); // works!
```
But how do I check of this leaf is of class Macro, and how do I retrieve the tagName and call methods defined in my class?

For further information, this is my class (simplified):

```
var Inline = Quill.import('blots/inline');

class Macro extends Inline 
{
  static blotName = "macro";
  static tagName = "macro"; // how to get from leaf?
  static className = "cms-blot-macro"; 

  static create(value) 
  {
    const node = super.create(value);
    this.myBlotName = "macro";
    return node;
  }

  getBlotName() // how to call from leaf?
  {
    return this.myBlotName;
  }
}
```

**Comment by matheushoeltgebaum** [comment]
I don't know about the part of calling methods defined in your blot class, but to retrieve the tagName from the leaf node, you could use the **parent** attribute from the leaf, like this:

`var range = quill.getSelection(true);
var [leaf, offset] = quill.getLeaf(range.index + 1);
console.log(leaf.parent.domNode.tagName); //returns the tagName of the blot`

**Comment by benbro** [comment]
You can also use: ```leaf.constructor.blotName == 'macro'```
