### ISSUE TITLE
Creating a custom blot from an angular component.

### ISSUE THREAD

**Issue by DoctorsInTech** [quilljs/quill#2958]
I have spent the last 2 days attempting to create a blot that is a custom angular component. I have tried a number of method's including renderer to add the component directory in conjunction with ComponentFactoryResolver. 

However, none of these has proven successful. Which leads me to believe that this may not in fact be possible. 

Has anybody ever managed to inject a component into a custom blot in quill in either angular or react (preferably angular example). And if not, is this evening possible with quill's parchment and blot system.

**Comment by Slanfan** [comment]
I know this is a couple of years later but I was searching for something similar.

But if anyone would stumble upon this, here's how I have solved it.

in the main.ts file of my angular typescript project
```
const ngModuleRef = platformBrowserDynamic().bootstrapModule(AppModule)
  .then((ngModuleRef) => {

    // Convert Angular components to custom elements
    const SomeName = createCustomElement(SomeComponent, { injector: ngModuleRef.injector });

    // Define the custom elements
    customElements.define('some-tag-name', SomeName)

  })
  .catch(err => console.error(err))
  ```

And in the blot definition, I have references the <some-tag-name> as the element.
You can also extend this with inputs comping from data elements and then process that data if you need to get even more information or data from a service or whatever your need might be.

```
import Quill from 'quill'
const Parchment: any = Quill.import('parchment')

export class SomeBlot extends Parchment.Embed {

  static blotName = 'some-name'
  static tagName = 'some-name'
  static className = 'your-class'

  static create(data) {
    const node = super.create() as HTMLElement
    node.setAttribute('anInput', String('true'))
    node.setAttribute('antotherInput', String(data.propertyName))
    return node
  }

  static value(node: HTMLElement) {
    return {
      anInput: node.getAttribute('anInput') || '',
      anotherInput: node.getAttribute('anotherInput') || '',
    }
  }

}
```

```
export class SomeComponent{
  @Input() set anInput(value) {
    this._value = value
  }
  @Input() set anotherInput(value) {
    this._anotherInput= value
  }

  public _anInput
  public _anotherInput

  constructor(
    private readonly host: ElementRef<HTMLElement>,
    private readonly serviceOne: ServiceOneService,
    private readonly serviceTwo: ServiceTwoService ,
  ) { }

  public destroy(): void {
    this.host.nativeElement.remove()
  }

}
```

**Comment by benbro** [comment]
Answered.
