### ISSUE TITLE
how to keep white space at the beginning of the paragraph

### ISSUE THREAD

**Issue by codehamal365** [quilljs/quill#2960]
the white space or tabs at the beginning of the paragraph will be automatically removed. is any directions how to keep it？

**Comment by DmitrySkripkin** [comment]
How to reproduce this issue? I have no clue.

**Comment by lanbai1993** [comment]
> How to reproduce this issue? I have no clue.

the second time enter this edior, you will see no white space at the beginning of the paragraph lefted last time.

**Comment by blobinabottle** [comment]
Did you find a solution for this? I tried 
```
.ql-editor {
  white-space: pre-line !important;
}
```
But with no luck.

In my case I have this issue when removing text by code (saying delete from actual selection to end of paragraph, if you current cursor is before a space, it will be removed as well which is a bit weird):
```
this.editor.updateContents(
          new Delta()
            .delete(length),
          'user',
        );
```

**Comment by blobinabottle** [comment]
Edit: I got it working by using just `pre` ... 
```
.ql-editor {
  white-space: pre !important;
}

```
