### ISSUE TITLE
Highlighting of normal text in toolbar is not working when custom HTML toolbar is used

### ISSUE THREAD

**Issue by snovakovic** [quilljs/quill#2965]
There seams to be an issue in quill with highlighting of normal text when custom HTML toolbar is used. Issue can be seen in the screenshot and it can also be observed by following below link with min repo case of the issue. 

![image](https://user-images.githubusercontent.com/6170843/76381696-b4e79780-6388-11ea-805b-0b872bbd13e4.png)
  

**Steps for Reproduction**

1. Visit https://codepen.io/snovakovic/pen/wvayMEL?editors=1010
2. click on the provided header and paragraph lines (or move around them with keyboard)

**Expected behavior**:

When on paragraph line toolbar should show "Normal" item as the active/selected one. Same as it is now doing with other header lines. 

**Actual behavior**:

Selecting paragraph line is not reflected in the toolbar which keeps showing last selection (e.g heading 3)

**Platforms**:

Chrome/Brave Ubuntun 18.04

**Version**:

v1.3.7

**Comment by algusarov** [comment]
Can confirm this issue. Just today I have tried custom HTML toolbar on 1.3.7 as I needed custom buttons, but due to this issue went for toolbarOptions JSON initialization and then updated my button innerHTML directly:

```
    var toolbarOptions = [
      [{ header: [1, 3, false] }],
      ["bold", "italic"],
      [{ list: "ordered" }, { list: "bullet" }],
      ["blockquote"],
      ["omega"]
    ];
    var quill = new Quill("#quill-container", {
      placeholder: "Write something",
      modules: {
        toolbar: toolbarOptions,
      },
      theme: "snow"
    });

    var button = document.querySelector(".ql-omega");
    button.innerHTML = '<svg>my svg icon here</svg>';
    button.addEventListener("click", handleClick);
```

**Comment by CYvonne** [comment]
The correct HTML should be like this:
```
<select class="ql-header">
     <option value="1">Heading 1</option>
     <option value="2">Heading 2</option>
     <option value="3">Heading 3</option>
     <option value="4">Heading 4</option>
     <option selected>Normal</option>
</select>
```

**Comment by CYvonne** [comment]
The correct HTML should be like this:
```
<select class="ql-header">
     <option value="1">Heading 1</option>
     <option value="2">Heading 2</option>
     <option value="3">Heading 3</option>
     <option value="4">Heading 4</option>
     <option selected>Normal</option>
</select>
```
