### ISSUE TITLE
Keep placeholder for empty headings

### ISSUE THREAD

**Issue by Alvol** [quilljs/quill#2968]
I want to keep placeholder for empty quill after format was changed from `Normal` to `Heading`.

**Steps for Reproduction**
1. Visit [quill playround](https://quilljs.com/playground/)
2. Check that `ql-editor` has `ql-blank` class and `:before` selector with placeholder
3. Change format to `Heading 1` or `Heading 2`.
4. Notice that `ql-blank` class was removed from  `ql-editor` along with placeholder

**Expected behavior**:
Keep `ql-blank` class and input placeholder if format was changed from `Normal` to `Heading`

**Actual behavior**:
`ql-blank` class and input placeholder were removed after format was changed from `Normal` to  `Heading`

**Platforms**:
Windows 10, Chrome 80

**Version**:
1.3.6, 1.3.7

**Comment by chinanderm** [comment]
Also having this issue.

**Comment by AndriiDubonos** [comment]
Same issue for me.

**Comment by troldmand** [comment]
Also for me.
