### ISSUE TITLE
toolbar doesn't work

### ISSUE THREAD

**Issue by freder** [quilljs/quill#297]
hi,

the toolbar doesn't really work for me, in that it doesn't format the selected text.
when I select a line of text and click a toolbar button, the cursor jumps to the beginning of the line, and nothing else happens. no console errors. shortcuts seem to work.

basically the same as https://discuss.quilljs.com/t/how-to-debug-toolbar-buttons-appear-but-dont-function/68 — but with a way more recent version.

quill 0.19.8
mac: chrome, safari, firefox

**Comment by jhchen** [comment]
Is this happening on the quilljs.com homepage editor or on your app?

**Comment by jhchen** [comment]
Closing from inactivity. Please comment if you still have this issue.

**Comment by skarkalas** [comment]
Hi,

I am having exactly the same problem. The editor works fine on the quilljs homepage but not on my app. I am using the most recent version of the editor and the code is exactly the same as the examples given. Other libs used are jquery, bootstrap, wavesurfer and spectrum. Could this be a conflict?

TIA for the help.

**Comment by skarkalas** [comment]
I found what the problem was:
https://vitalets.github.io/x-editable/
Removing this dependency fixes the problem.
