### ISSUE TITLE
Are there any options to use header tag for font size instead of css?

### ISSUE THREAD

**Issue by deepakmhr** [quilljs/quill#2975]
I'm using this library in the application using the primeng and saving HTML string in the database generated by the quill. The application also supports reporting using the RDLC and displaying and rendering saved HTML in the report.

But RDCL only supports tags not CSS and when in case of font size this editor is generating inline CSS with the span/p tags but I need tags (h1,h2...) instead of the CSS display in the RDLC.

HTML configuration for quill:

```
<p-editor [(ngModel)]="text" [style]="{'height':'320px'}">
    <p-header>
        <span class="ql-formats">
            <!-- Add font size dropdown -->
            <select class="ql-size">
                <option value=""><h4>Small</h4></option>
                <!-- Note a missing, thus falsy value, is used to reset to default -->
                <option value="" selected><h3>Normal</h3></option>
                <option value=""><h2>Large</h2></option>
                <option value=""><h1>Huge</h1></option>
            </select>

            <button class="ql-bold" aria-label="Bold" title="I am bold"></button>
            <button class="ql-italic" aria-label="Italic"></button>
            <button class="ql-underline" aria-label="Underline"></button>
            <button class="ql-strike"></button>
            <button class="ql-list" value="ordered" title="Clicking on this icon will change the selected text into a numbered point"></button>
            <button class="ql-list" value="bullet" title="Clicking on this icon will change the selected text into a bullet point"></button>
        </span>
    </p-header>
</p-editor>
```

In application UI: 
![image](https://user-images.githubusercontent.com/6562535/76951713-1cc25300-6932-11ea-96b4-14c15bc52df3.png)

Saved HTML string:

`<p><strong>This is bold</strong></p><p><em>This is italic</em></p><p><u>This is underlined</u></p><p><s>This is stricken</s></p><p>This is number list</p><ol><li>a</li><li>b</li></ol><p>This is billeted list</p><ul><li>a</li><li>b</li></ul><p><span style="font-size: 10px;">Small font</span></p><p>Normal font</p><p><span style="font-size: 18px;">Large</span></p><p><span style="font-size: 32px;">Huge</span></p><p><br></p><p><br></p>`

In application reporting (RDLC)
![image](https://user-images.githubusercontent.com/6562535/76952086-8f333300-6932-11ea-95bc-b49777879c2a.png)

**Platforms**: Windows

Include browser, operating system and respective versions
Browsers: Chrome/ Edge/Firefox
Os: Windows 10

**Version**:1.3.6
primeng version: 5.2.0

Is there any way to override the font size with tags(h1,h2...)?
any workaround?

Note: I'm using this using the primeng library.

**Comment by ramiroaisen** [comment]
You need to use the "header" option instead of the "size" option in toolbar

**Comment by deepakmhr** [comment]
@ramiroaisen - Header font size is fixed until we customise using CSS for that and we don't want to customise the default header tag font sizing if we can do this by configuring font size in value.

Thanks for the response

**Comment by deepakmhr** [comment]
This font sizing issue got resolved with the following code and also supported by RDLC.

```
  <p-header>
        <span class="ql-formats">
            <select class="ql-size" [(ngModel)]="defaultFontSize">
                <option selected>{{defaultFont.Name}}</option>
                <option [value]="11pt">Normal</option>
                <option [value]="12pt">Large</option>
               <option [value]="14pt">Huge</option>    
    </p-header>

```
