### ISSUE TITLE
怎么实现自定义插入公式

### ISSUE THREAD

**Issue by xuedongwang** [quilljs/quill#2976]
怎么自定义插入公式，比如我想点击一个自定义的工具栏，出现一个弹窗，如下：
![image](https://user-images.githubusercontent.com/25864625/77251351-d732bc80-6c88-11ea-831b-742ebc8b4196.png)
然后编辑好公式之后，点击确定，实现插入公式的功能

**Comment by jiandandaoxingfu** [comment]
qull.js中插入公式默认是显示一个输入框和按钮。

自定义的话，可以这样做：
         点击插入公式以后，隐藏其自身的输入框。
         然后给插入公式按钮绑定点击事件，显示你自己的输入和预览框(预览的话，可能还需要使用MathJax，KaTeX好像渲染以后没有回调)
        最后再把公式赋给默认输入框，点击默认按钮就可以了。
