### ISSUE TITLE
How can I upload images to the server without it being in base64, but only on form submission?

### ISSUE THREAD

**Issue by hjb1694** [quilljs/quill#2980]
I am wanting to upload the images the user adds into the editor in the form of a file instead of base64 data URL. But, I am only wanting to send the images together with the rest of the content being submitted, only when the user submits the form. I don't want uneccessary images being uploaded to my server that the user decides he/she does not want. I also want to be able to validate how many images the user includes in the form and their sizes in bytes.
Is there a way to approach this?

**Comment by simonhyttfors** [comment]
You could override the handler for image uploading:

```
const imageHandler = (editor, path) => {
  const input = document.createElement('input')

  input.setAttribute('type', 'file')
  input.setAttribute('accept', 'image/*')
  input.click()

  // I use an upload function that runs a callback function returning the upload url of the image,
  // but change it to whatever fits your needs
  input.onchange = () => uploadImage(input.files[0], path, (url) => {
    // do whatever you want to do with the callback url

    const range = quill.getSelection(true)
    quill.insertEmbed(range.index, 'image', url)
  })
}
```

Override (after initiating quill editor):

`quill.getModule('toolbar').addHandler('image', () => imageHandler($('#editor-1'), path))`

Not sure if this gave you anything, but I thought I'd share my solution to at least part of your problem!

**Comment by snake-py** [comment]
@simonhyttfors Hey thank you for sharing your solution. 

How do you render the content then? Did you write a render function or do you use a module for that? I thought about using this repo https://github.com/nozer/quill-delta-to-html
