### ISSUE TITLE
How can i group the option like bold, italic, underline in dropdown?

### ISSUE THREAD

**Issue by gaja33** [quilljs/quill#2985]
Similar like this
![image](https://user-images.githubusercontent.com/11241820/77843787-1fd50300-71be-11ea-9111-314d98db0385.png)

**Comment by padraigfl** [comment]
This code has a sample drop down menu with quill v1 https://github.com/MrMadClown/quill-table/blob/master/src/demo.js might be able to get something useful from it?

**Comment by gaja33** [comment]
@padraigfl Thanks for providing the reference, i will have a look how i can customise using your example. But i want to mimic the behaviour of bold, italics, buttons in a drop down rather than individual buttons.

**Comment by padraigfl** [comment]
I think it's doable from adapting the stuff in there (there's probably better examples online somewhere).
It might be harder if you want it to be able to only have one chosen at a time though

**Comment by benbro** [comment]
You can create a toolbar with your custom HTML
https://quilljs.com/docs/modules/toolbar/
