### ISSUE TITLE
html() method in Quill formula.js

### ISSUE THREAD

**Issue by imabot2** [quilljs/quill#2986]
In the Quill editor, I try to adapt the formula module for using it with MathJax. 

I do not understand what is the `html()` method used in the `Formula` class : https://github.com/quilljs/quill/blob/develop/formats/formula.js

Moreover, it seems never being called. Is anyone has an idea of what this method is for?

**Comment by volser** [comment]
html method is used for copy to clipboard
https://github.com/quilljs/quill/blob/cb0fb6630a59aa8efff3e0d1caa6645e565d19bd/core/editor.js#L271

**Comment by benbro** [comment]
Answered.
