### ISSUE TITLE
Error when using CSS class for colors with HTML containing style attribute with rgba color

### ISSUE THREAD

**Issue by lclement57** [quilljs/quill#2993]
We started using quilljs with inline style for color and background, and later changed it to use classes by following the configuration mentioned here : https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline

As a result, we now have in our database HTML snippets that contain CSS classes `ql-bg-xxx` and other with style attribute that contain `background-color`

Since some users copy pasted text from elsewhere, we ended up with style attributes containing `background-color: rgba(0, 0, 0, 0.5)`
Example : `<span style="background-color: rgba(0, 0, 0, 0.05);">test blabla</span>`

Quilljs fails to render such HTML content as it tries use the value of the style attribute to craft a `ql-bg-{background_color_attribute_value}` CSS class, giving an invalid value of `ql-bg-rgba(0, 0, 0, 0.05)`

After investigating a bit more, i found out that it doesn't fail with a style attribute containing a `rgb` color, as it is parsed to hex format, but is still produces a wrong CSS class like `ql-bg-#323232`

Maybe the class attributor (https://github.com/quilljs/parchment/blob/master/src/attributor/class.ts) should check the validity of the value before adding it ?

**Steps for Reproduction**

1. Visit https://codepen.io/lc57/pen/poJYXbW (based on the following playground  https://quilljs.com/playground/#class-vs-inline-style)
2. Watch the console

**Expected behavior**:

The content should be rendered

**Actual behavior**:

The content is not rendered

**Platforms**:

Chrome

**Version**:

1.3.7

**Comment by amitpatil321** [comment]
I have used quill in my application everywhere, Recently I started seeing this error when I set html contents to react-quill editor. 
I cant go back and replace quill editor with some other alternative and since I liked quill editor I dont want to replace it.

Any updates on this? I am facing same issue ? Any quick workaround?

**Comment by lclement57** [comment]
This issue was never solved and I chose to use own class attributor as a workaround.

Here is what works for me:

instead of registering the attributors imported with `Quill.import`:
```
const BackgroundClass = Quill.import('attributors/class/background');
const ColorClass = Quill.import('attributors/class/color');
Quill.register(BackgroundClass, true);
Quill.register(ColorClass, true);
```
I made my own `ClassAttributor` that discards values including parentheses:
```
const Parchment = Quill.import('parchment');

/**
 * <p>A custom class attributor that escapes invalid values for CSS classes</p>
 * <p>Based on https://github.com/quilljs/parchment/blob/master/src/attributor/class.ts</p>
 * <p>This is the file containing the class imported when using
 * <code>const BackgroundClass = Quill.import('attributors/class/background');</code></p>
 */
class ClassAttributorSafe extends Parchment.Attributor.Class {
  add(node, value) {
    if (!this.canAdd(node, value)) return false;
    this.remove(node);
    if (value.includes('(')) return false; // discard values containing (, eg. rgba values
    node.classList.add(`${this.keyName}-${value}`);
    return true;
  }
}

/**
 * <p>Use our safe class attributor</p>
 * <p>Based on https://github.com/quilljs/quill/blob/develop/formats/background.js</p>
 * <p>It corresponds to the class imported when using
 * <code>const BackgroundClass = Quill.import('attributors/class/background');</code></p>
 * @type {ClassAttributorSafe}
 */
const BackgroundClassSafe = new ClassAttributorSafe('background', 'ql-bg', {
  scope: Parchment.Scope.INLINE,
});

/**
 * <p>Use our safe class attributor</p>
 * <p>Based on https://github.com/quilljs/quill/blob/develop/formats/background.js</p>
 * <p>It corresponds to the class imported when using
 * <code>const BackgroundClass = Quill.import('attributors/class/color');</code></p>
 * @type {ClassAttributorSafe}
 */
const ColorClassSafe = new ClassAttributorSafe('color', 'ql-color', {
  scope: Parchment.Scope.INLINE,
});

Quill.register(BackgroundClassSafe, true);
Quill.register(ColorClassSafe, true);
```

This is enough to avoid this error

**Comment by amitpatil321** [comment]
@lclement57 : Your solution is working fine, But when I refresh the page it throws same error. So I thought to replace RGBA color with hex colors.

 ```
 value = value.replace(
    /rgba?\(((25[0-5]|2[0-4]\d|1\d{1,2}|\d\d?)\s*,\s*?){2}(25[0-5]|2[0-4]\d|1\d{1,2}|\d\d?)\s*,?\s*([01]\.?\d*?)?\)/gi,
    rgba => rgb2hex(rgba)
  );

export const rgb2hex = rgba => {
  const values = rgba
    .replace(/rgba?\(/, "")
    .replace(/\)/, "")
    .replace(/[\s+]/g, "")
    .split(",");
  const a = parseFloat(values[3] || 1);
  const r = Math.floor(a * parseInt(values[0]) + (1 - a) * 255);
  const g = Math.floor(a * parseInt(values[1]) + (1 - a) * 255);
  const b = Math.floor(a * parseInt(values[2]) + (1 - a) * 255);
  return `#${`0${r.toString(16)}`.slice(-2)}${`0${g.toString(16)}`.slice(
    -2
  )}${`0${b.toString(16)}`.slice(-2)}`;
};


```
