### ISSUE TITLE
Quill 2.0.0-dev.3 npm release not working -> Dev Branch already fixed it -> New release needed

### ISSUE THREAD

**Issue by dominikheeb** [quilljs/quill#2994]
The latest npm dev release is not working.

When using it, it throws an error:
Cannot assign to read only property 'exports' of object '#<Object>'

I found the source of the problem and it is the file icon.js.
On the dev branch here at github, the issue is fixed.

Could you create a new release from dev for npm, so we can start using it?

**Comment by pete-hotchkiss** [comment]
same is true of the `main` prop in the `package.json` file. This should be

```
...
"main": "quill.js"
...
```

and not

```
...
"main": "dist/quill.js"
...
```

The author of this library appears active on github - but seems unable to maintain this package. I'm sure there's good reason - just frustrating

**Comment by arghyaiitb** [comment]
I did fix it by creating a fork and then using it. Though its a hack but things are working pretty smooth.

Here is the fork
https://github.com/arghyaiitb/quill

Here is the usecase:
https://github.com/factly/dega-gateway/blob/develop/package.json#L34

**Comment by benbro** [comment]
[v2.0.0-beta.1](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.1)
