### ISSUE TITLE
Support shadow dom

### ISSUE THREAD

**Issue by shaunnetherby** [quilljs/quill#300]
Quill does not work if the container is within shadow dom.  If it could be fixed/enhanced to work in shadow dom that would allow it to be used within a polymer component.

I created a jsfiddle here to demonstrate the problem: http://jsfiddle.net/shaunnetherby/jnuz5udt/4/

The problem is in how quill determines selection.  Quill uses `document.getSelection()` instead of the `shadowRoot.getSelection()`.  It also uses the `selection.getRangeAt()` method which has a bug in the current version of chrome (https://code.google.com/p/chromium/issues/detail?id=380690).  The `selection.checkFocus()` quill method also compares `document.activeElement` to the container element.  `document.activeElement` will point to the object that is containing the shadow root instead of the container so this comparison fails.

I was tinkering around in selection.js and was able to fix these issues such that it works in chrome (as far as I can tell): https://github.com/shaunnetherby/quill/compare/shadow_dom_support

However, this does not work in Firefox at all.  It appears quill does not work with the webcomponents.js polyfill library (this polyfills in shadow dom into firefox and other browsers), even when the container is not in shadow dom.

**Comment by jhchen** [comment]
Until shadow dom support is more widely available and more developers start using it, it will be hard to prioritize. I'd be happy to look at any pull requests if you want to tackle this anyways though.

**Comment by nazar-pc** [comment]
@jhchen, what are your current thought on this topic? I'm using Shadow DOM for more than a year now and many others as well, but there is no decent WYSIWYG editor that works under Shadow DOM yet.

I've got TinyMCE fully functioning under both native Shadow DOM and Shadow DOM polyfill here: https://github.com/tinymce/tinymce/pull/561 even though TinyMCE looks much heavier than Quill.

I'm not sure I'll be able to add proper tests for all cases, but I can definitely spend some time and bring many more things including Quill working under Shadow DOM. It just depends whether you're ready to put it on roadmap and help with upstreaming. I've maintained Shadow DOM-aware forks of some projects and it is not fun at all to maintain it alone without upstream support.

**Comment by jhchen** [comment]
Getting 1.0 out is the main priority right now. I'll re-evaluate items for future roadmaps after that.

**Comment by MarkGStacey** [comment]
Did this get dropped completely?

**Comment by timblack-NukeDigital** [comment]
Quill is working in the shadow DOM for me in this branch:  https://github.com/timblack-NukeDigital/quill/commits/feature/shadow-dom-support.
