### ISSUE TITLE
How to translate/change the Headings text?

### ISSUE THREAD

**Issue by lucassimines** [quilljs/quill#3001]
Is it possible to change the header dropdown `Heading 1` `Heading 2`, to `Title 1`, etc?

**Comment by zoocreative** [comment]
If you create the toolbar with a DOM element you can change the names of these things.

Look at the example about half way down the page here:
https://quilljs.com/docs/modules/toolbar/

And also view the source on the homepage for more examples of this.

**Comment by benbro** [comment]
Answered.
