### ISSUE TITLE
cdn.quilljs.com no longer serving Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by samroberton** [quilljs/quill#3004]
**Steps for Reproduction**

1. Include Quill in a page hosted on a different origin, using script and stylesheet tags with `integrity` and `crossorigin` attributes such as `<script type="text/javascript" src="https://cdn.quilljs.com/1.1.5/quill.js" integrity="sha384-VVNIKPlUEqLi/TE2L4khq1NUFm1ymOaG9XZknxLmRqkF3CUkzTFG2mIIzTW20GNB"></script>`.
2. Access the page.

**Expected behavior**:

Quill loads.

**Actual behavior**:

CORS error:

`Access to script at 'https://cdn.quilljs.com/1.1.5/quill.js' from origin '<your origin>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Platforms**:

Chrome v80/v81 on Linux / Mac OS X.

**Version**:

1.1.5, though I imagine this will affect any version, since it appears to be a change in CDN behaviour.

**Comment by florian-prd** [comment]
Save problem with 1.3.6
Moreover, I get the error "None of the “sha384” hashes in the integrity attribute match the content of the subresource":
`<link rel="stylesheet" href="https://cdn.quilljs.com/1.3.6/quill.snow.css" integrity="sha384-07UbSXbd8HpaOfxZsiO6Y8H1HTX6v0J96b5qP6PKSpYEuSZSYD4GFFHlLRjvjVrL" crossorigin="anonymous">`

**Comment by benbro** [comment]
Can't reproduce.
