### ISSUE TITLE
Copy + paste an Formula blot or any Embed blot

### ISSUE THREAD

**Issue by CodeDestroyer666** [quilljs/quill#3006]
Copy + paste of Embed blot is not working as expected. When only the Embed blot is selected, it seems only the child elements are copied and not the container. When either the previous or the next character are also selected with the Embed, copy + paste works as expected. I found out this issue while implementing custom Embed blot but also the included Formula blot seems affected.

**Steps for Reproduction**

1. Visit quilljs.com
2. Place cursor within text of the demo editor. Insert the default e=mc^2 formula from the toolbar button.
3. Move cursor to the beginning of formula. Press shift + right arrow once to select the formula Embed.
4. Press ctrl+c and move cursor somewhere else in the text. Press ctrl+v to paste.

**Expected behavior**:
Identical formula Embed
**Actual behavior**:
﻿e=mc^2

e=mc​2

**Platforms**:

Win10, Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Version**:

v1.3.6

**Comment by oller** [comment]
I'm encountering the exact same issue, if just the Custom blot is selected, this will fail.  As long as there's a space or any other character additionally as part of the selection it will work.

Has anyone found a workaround for this (@CodeDestroyer666 @scottfr @rteristilMS @cosmmiike), perhaps a clipboard matcher snippet?  This issue is almost a year old now!

**Comment by cosmmiike** [comment]
I found out that Katex manages this problem itself but I haven’t tested it yet. https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex 
Let me know if this solution worked.

**Comment by oller** [comment]
Hi @cosmmiike , thank you for the response.  My issue is a broader quill issue with custom embeds blots, not specifically with formula and KaTeX (I'm not using KateX).  But I'm confident it's the same issue at source.

As I'm not using KaTeX as this is just a quill editor extended to support custom blots for mentions, emojis, gifs etc.  I'll see what I can lift from here that might be the crucial line that gives you that support, but a lot of those code seems specific to KaTeX markup.

**Comment by CodeDestroyer666** [comment]
Here's a workaround we used, modified for the built-in formula blot. It's based on handling copy and cut events of the quill editor container and setting correct data manually. Not unlike the KaTeX solution linked by @cosmmiike. Hope this helps.

https://codepen.io/codedestroyer666/pen/VwPYRqx

**Comment by oller** [comment]
Great, thank you for the response and codepen @CodeDestroyer666.  It seems odd that we have to break out of quill to handle such a common use case.  Appreciate the reply.  Shall try and implementing an equivalent for this project and shall report back
