### ISSUE TITLE
Displaying HTML in Quill (or converting it to Delta)

### ISSUE THREAD

**Issue by GoodPie** [quilljs/quill#3008]
I am looking for a WYSIWYG editor to allow users to edit their email footer. This means that the output needs to be in HTML. I'm able to grab the HTML from Quill using the following:

```
$("#settings-footer-text-mirror").html(quill.root.innerHTML);
```

Note: I am simply copying the HTML to a textarea on form submit as I can't apply a name attribute to quill which is fine

That all works and I have the raw HTML from quill. How do I go about doing the reverse? I've tried the following:

```
const editor = new Quill("#settings-footer-text", options);
const delta = editor.clipboard.convert(html);
editor.setContents(delta, "api");
```

but the delta insert still contains the HTML tags in the final output. I've also tried

```
editor.clipboard.dangerouslyPasteHTML(html);
```

That does pretty much the same thing.

An example of the HTML I'm trying to convert would be:

```
<p>Hello World</p>
```

Any help on this? I've seen a lot of discussion talking about retrieving HTML but I also want to allow users to edit the footer when required which means placing existing content back into the quill editor.

**Platforms**:
Windows 10
Chrome 84

**Version**:
1.3.6

**Comment by qinyhan** [comment]
The problem of clipboard.convert (html) in version 2.0 has still not been solved.

**Comment by Hapanmuffinssi** [comment]
Yes, using Quill inside an Angular app (via ngx-quill) does not seem to work in any reasonable manner if trying to update the editor contents dynamically. Only reasonable way to insert HTML string (created by the editor itself) and have proper formatting applied is to directly replace quill.root.innerHTML. Clipboard's conver() and dangerouslyPasteHTML() methods insert only text content. Embedded images and formatting are stripped off.

Only if the formcontrol value is patched (Angular reactive forms) before the editor is rendered, then the HTML will be displayed properly.

Maybe it's a browser engine thing. But so far Chromium and Firefox behave in the same way.

**Comment by abpun** [comment]
```const editor = new Quill("#settings-footer-text", options);
const delta = editor.clipboard.convert({ html });
editor.setContents(delta, "api");```
