### ISSUE TITLE
How can I insert HTML programmatically in an Editor?

### ISSUE THREAD

**Issue by coder-strange** [quilljs/quill#3009]
[Question]:
I have an Editor in which I can drag and drop some texts, I'm trying to add new node where the drop happened but it's converting it to simple string.

Here are the things I've tried.
1.
 ```
 var span = document.createElement('span');
  span.innerHTML = '<span>{{' + ev.dragData + '}}</span>';
  ev.nativeEvent.toElement.append(span);
```
2.
`this.quillInstance.clipboard.dangerouslyPasteHTML('<span>{{' + ev.dragData + '}}</span>');`

3.
```
let value = '<span>{{' + ev.dragData + '}}</span>';
this.quillInstance.setContents(this.quillInstance.clipboard.convert(value));
```

**Comment by boring2** [comment]
You can try use the function in clipboard.js, convert your html to delta.

Just like this:

```
const clipboard = this.quill.getModule('clipboard')
const pastedDelta = clipboard.convert({html: `you drop data`, text: ''})
const delta = new Delta()
                  .retain(range.index)
                  .delete(range.length)
                  .concat(pastedDelta);
this.quill.updateContents(delta, Quill.sources.USER)
```

**Comment by benbro** [comment]
[dangerouslyPasteHTML](https://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml) should work if your html is supported by registered blots and attributors.

**Comment by devgraduan** [comment]
based on this plugin https://github.com/vueup/vue-quill/blob/master/packages/vue-quill/src/components/QuillEditor.ts#L339

Set Html content
```javascript
quillInstance.root.innerHTML = '<p>Hello World</p>';
```

Get Html Content
```javascript
let html = quillInstance?.root.innerHTML ?? ""
```
