### ISSUE TITLE
Unordered list icon in the toolbar produces an ordered list element

### ISSUE THREAD

**Issue by LingVuDev** [quilljs/quill#3014]
**Steps for Reproduction**

1. Visit 

https://stackblitz.com/edit/typescript-pdcugs

2. Step Two

Open the console and look at the list element

**Expected behavior**:

That the unordered list should have `<ul>` tag

**Actual behavior**:

The unordered list has a `<ol>` tag which is a ordered list. It looks like a unordered list in the editor, because of the replaced numbers with bullets, but pasting out the html content makes it to an ordered list.

![code](https://i.imgur.com/xW0BERj.png)

**Platforms**:

Chrome - Version 79.0.3945.130 (Official Build) (64-bit)

**Version**:

2.0.0-dev.4

**Comment by SimplicitysStrength** [comment]
Looking at the List format code from version 1.x [github.com/quilljs/quill/blob/1.3.7/formats/list.js](https://github.com/quilljs/quill/blob/1.3.7/formats/list.js)
it seems that the OL and UL tags used to be distinct.
Although i agree it is not the case anymore with 2.x
It looks like this [github.com/quilljs/quill/commit](https://github.com/quilljs/quill/commit/d5384fd71dcc15870bd2f9cbb08e4a056fa8cec6#diff-7e03100f084454f2257473dd88fe787c)
 from @jhchen removed the UL TagName

About the reasons behind this, 
i can understand that Quilljs does not support the use of it's innerHTML content,
mainly because of it's unpredictable nature and instead encourages the use of the Delta format.
Converting Delta to HTML with your own style and formatting seems to be the way to go here.

**Comment by SimplicitysStrength** [comment]
Here is a failed attempt at creating a custom UL Format
https://codepen.io/simplicitysstrength/pen/pojxWxg?editors=0110
using this 
```
const ListContainer = Quill.import('blots/container');

class UlContainer extends ListContainer {
    static create(value) {
      const node = super.create();
      node.setAttribute('style','list-style: square');
      return node;
    }
}
UlContainer.blotName = 'ul-container';
UlContainer.tagName = 'UL';
const Block = Quill.import('blots/block');
class UlItemBlot extends Block {
 ....
}
UlContainer.allowedChildren = [UlItemBlot];
UlItemBlot.requiredContainer = UlContainer;
UlItemBlot.blotName = 'ul';
UlItemBlot.tagName = 'LI';

Quill.register('formats/ul', UlItemBlot);
```
Also some css was required to override quill's core.css
```
.ql-editor ul{
  padding-inline-start: 40px;
}
.ql-editor ul li{
  list-style-type: unset;
  padding-left: 0;
}
```
But after this i realized that i had to almost extend all the keyboard.js  file to
make my 'ul' format work, Like fixing navigation and making it work like the default list.
QuillJs has hudge workarounds with lists almost faked with css in 2.0

**Comment by cnotv** [comment]
This is a duplicate of a 4 years old issue: https://github.com/quilljs/quill/issues/979

**Comment by dman777** [comment]
Hitting this also

**Comment by kjantzer** [comment]
Here is a solution that has worked well enough for me

```js
import List, {ListContainer} from 'quill/formats/list';

class UListContainer extends ListContainer {}
UListContainer.blotName = 'ulist-container'
UListContainer.tagName = 'UL'

class UListItem extends List {
  static register() {
    Quill.register(UListContainer);
  }
}

UListItem.blotName = 'ulist';
UListItem.tagName = 'LI';

UListContainer.allowedChildren = [UListItem];
UListItem.requiredContainer = UListContainer;

Quill.register({
  'formats/list': List,
  'formats/ulist': UListItem,
});
```

I can then toggle between `<ol>` and `<ul>` using

```js
quill.format('list')
quill.format('ulist')
```

I'm using a custom toolbar so this works well enough for me

**Comment by vedadeepta** [comment]
For anyone wondering how to create `ul` tags without messing with the toolbar this comment will be helpful
https://github.com/quilljs/quill/issues/2614#issuecomment-750694902

+ add this line to the above code snippet

`MyListContainer.allowedChildren = [MyListItem];`

**Comment by paulm17** [comment]
@kjantzer or anyone else.

How to use your code block with quill?

I'm trying to put it into it's own file and doing the following:

adding at the end of the code block.

```
export { UListContainer as default }
```

Then adding to my init of quill

```
const List = require("./uList").default
Quill.register("modules/uListOptions", List)
```

I keep getting:

```
TypeError: Super expression must either be null or a function
```

Can you please provide sandbox example?  Thanks

**Comment by kjantzer** [comment]
@paulm17 Quill was giving me too many problems, so I ended up switching to [TipTap](https://tiptap.dev/)

**Comment by 47arathore** [comment]
I have written a function to convert the <ol> tag to <ul>. Use this just at the place where you take data from quill and store it.

```
correctULTagFromQuill = (str) => {
    if (str) {
      let re = /(<ol><li data-list="bullet">)(.*?)(<\/ol>)/;
      let strArr = str.split(re);

      while (
        strArr.findIndex((ele) => ele === '<ol><li data-list="bullet">') !== -1
      ) {
        let indx = strArr.findIndex(
          (ele) => ele === '<ol><li data-list="bullet">'
        );
        if (indx) {
          strArr[indx] = '<ul><li data-list="bullet">';
          let endTagIndex = strArr.findIndex((ele) => ele === "</ol>");
          strArr[endTagIndex] = "</ul>";
        }
      }
      return strArr.join("");
    }
    return str;
  };


let content = this.correctULTagFromQuill(this.state.quill.root.innerHTML);

```

**Comment by paulm17** [comment]
@47arathore Thanks for your efforts.  I'm sure future viewers would find that helpful.

Like @kjantzer I moved over to tiptap.  It's so much easier and much more powerful functionality.  In-fact I'm able to write my own extensions much more easily.  I recommend everyone to switch over.  I consider QuillJS to be legacy software.  😄

**Comment by Daedra22** [comment]
2 years now, is this fixed? 
Its embarassing to be honest ...

**Comment by 1mzino** [comment]
@jhchen

**Comment by krisnaw** [comment]
Any update on this? the v1 already correct using OL and UL, but it change on v2

**Comment by rodaraknia** [comment]
I fixed the ul vs ol bullet number style by copying the css that quill use. My pdf now works fine. They use fancy css rules to replicate their own numbering and bullets

/* fixes crazy quill number and bullets */
.comment-holder ol li, .comments-text ol li{ list-style-type: none; }

  @supports (counter-set:none) {
    ol li[data-list] {
        counter-set: list-1 list-2 list-3 list-4 list-5 list-6 list-7 list-8 list-9;
    }
}
  
  div.comment-holder, div.comments-text, div.comments-box{counter-reset: list-0 list-1 list-2 list-3 list-4 list-5 list-6 list-7 list-8 list-9;}

ol li[data-list=ordered]{  counter-increment: list-0;}
ol li span.ql-ui{position: absolute;}
ol li[data-list=ordered] > .ql-ui:before{    content: counter(list-0, decimal) '. ';}
ol li[data-list=bullet] > .ql-ui:before{content: '\2022';}
ol li > .ql-ui:before{display: inline-block;margin-left: -1.5em;margin-right: .3em;text-align: right;white-space: nowrap;width: 1.2em;}

**Comment by zszepczynski** [comment]
I'm using getSemanticHtml so it's not an issue as it produces what it should be.
But I removed the burden with styling in quill-snow. I'm using list-item-type on the parent element instead of crappy :before selectors.

```
import Quill from 'quill';

const ListItem = Quill.import('formats/list') as any;

type ListItemType = 'bullet' | 'ordered';

class CustomUnorderedListItem extends ListItem {
    static create(value: ListItemType) {
        let node = super.create();
        node.setAttribute('data-list', value);
        return node;
    }

    static formats(domNode: HTMLElement) {
        // quill uses ol for both bullet and non bullet list, it's super hard to style it properly. Let's rewrite data-list to a parent to know if it's ol or ul

        const childAttribute = domNode.getAttribute('data-list');
        const parentAttribute = domNode.parentElement?.getAttribute('data-list');

        if (parentAttribute && parentAttribute !== childAttribute) {
            domNode.setAttribute('data-list', parentAttribute);
            return parentAttribute || undefined;
        }

        if (childAttribute && !parentAttribute) {
            domNode.parentElement?.setAttribute('data-list', childAttribute);
        }

        return childAttribute || undefined;
    }
}

Quill.register(CustomUnorderedListItem, true);

```
The idea is to set data-list element on the parent if child has data-list attribute (there is no easy way to do that at the creation time of container because data-list type is unknown so i hacked it in formats method which seems to be working fine).
Then I made a copy of quill.snow.css in the project and got rid of all the styles related to ol li and only have this:

```
.ql-editor ol[data-list="bullet"]{
  list-style-type: disc !important;
}

.ql-editor ol[data-list="ordered"]{
  list-style-type: decimal !important;
}

```

Seems to work fine in all the cases. Styling also works fine when same html is used outside of quill which was important in my case

**Comment by flavi1** [comment]
It's an accesibility issue (a little).
Semantically, ul and ol are differents.
We should be able to use each one in different context.
Quill CSS visualy "solve" the problem, but not _semantically_

Extend the class and change the tagName from OL to UL seems to be the better choice.
Not a big problem, and solution are available here.
It's up to implementors to reopen this ticket or not.
But I think it should be better to integrate the UL in default quill to not having to deal with old solutions from this ticket in the future.
