### ISSUE TITLE
Gboard GIF Insert Support

### ISSUE THREAD

**Issue by darkfrog26** [quilljs/quill#3021]
On Android devices, the Gboard keyboard has a GIF insert feature that used to work with the native application's "open-with", but they've changed it so it seems to expect something related to the editor.  I'd like to support GIF insert in my application with Gboard and QuillJS, but can't seem to get it to work.

**Comment by mdgb** [comment]
Would be very nice to have this functionality

**Comment by rakeshar3796** [comment]
@darkfrog26 did you find any update on this?

**Comment by darkfrog26** [comment]
No, it appears that this isn't possible from the mobile browser as it requires native integration.
