### ISSUE TITLE
Validating Quill deltas

### ISSUE THREAD

**Issue by rosslh** [quilljs/quill#3029]
I've been looking for a way to validate user-submitted Quill deltas on the server-side before saving them to my database. This seems like it would be a common use-case, so I was surprised not to find any obvious solutions.

Do any of these solutions already exist?

- A JSON Schema for Quill Deltas
- A built-in method for Quill delta validation
- An NPM package for Quill delta validation

If Quill provided an official JSON schema for deltas, validation would be quite easy. This idea was brought up in #1145 but closed without resolution.

**Comment by shareefalis** [comment]
I created my own validation function for my DB.  It is pretty trivial to do.

**Comment by rosslh** [comment]
Doesn't seem like there's much interest in this. And you can always create your own validation. Closing, but feel free to reopen.
