### ISSUE TITLE
Understanding Headers, Blockquotes Delta Format for parsing

### ISSUE THREAD

**Issue by zoocreative** [quilljs/quill#3035]
I am using the JSON from Quill and parsing through it to give me full control of the content that is on there. I'm doing this in PHP but for now that doesn't matter. Everything works great for general formatting and embedding but I can't seem to figure out the heading syntax as it doesn't seem to relate to any one insert.
I would love to figure this out or know if I am wasting my time as I am loving the editor. I realise I could just grab the HTML and save that into the DB but I would like the extra control that the JSON offers.

**Steps for Reproduction**

So when I save/view the Quill JSON with a header I get the following:

{ "ops": [
{"insert": "This is not a header\nThis is a header"},
{"attributes": {"header": 2},"insert": "\n"},
{"insert": "This is "},   
{"attributes": {"bold": true},"insert": "body "},
{"insert": "text\n"}
]}

This is no way to know if the header attribute is relating to the whole line above or only some of it. Even with the '\n'

**Expected behavior**:

I would have expected the text to appear like this:

{ "ops": [
{"insert": "This is not a header\n"},
{"attributes": {"header": 2},"insert": "This is a header\n"},
{"insert": "This is "},   
{"attributes": {"bold": true},"insert": "body "},
{"insert": "text\n"}
]}

I understand that this would result in nested results if the header also had a bold or otherwise formatted word. However, would that not make it more readable?

**Platforms**:

All Browsers
Windows 10

**Version**:

1.3.6 CDN

**Comment by npcole** [comment]
The "block" formatting is an attribute on the \n character, and applies as far back as the previous \n.  So the representation above is the most compact format.
