### ISSUE TITLE
Can't select embed/blot if it is the first element in the editor.

### ISSUE THREAD

**Issue by CaptainGlac1er** [quilljs/quill#3045]
**Steps for Reproduction**
Have an embed as the first element of the editor

1. Visit https://quilljs.com/guides/cloning-medium-with-parchment/
2. Insert a tweet blot in the tweet section.
3. Remove line before the tweet (I used the inspect tool to delete the `<p>`)
4. Then select the line after the tweet embed
5. Try to select the embed with shift+up

**Expected behavior**:
Tweet embed should be selected

**Actual behavior**:
Nothing happens

**Platforms**:
MacOS 10.14.6 Safari 13.1, Edge 83
Windows 10 2004 Edge 84, Chrome 81
Are the ones I tested likely not limited to just these.

**Version**:
For the project I am working on where we discovered the issue 1.3.6

**Comment by welkinwong** [comment]
same
