### ISSUE TITLE
HTML Inline editing

### ISSUE THREAD

**Issue by fabioaraujopt** [quilljs/quill#3046]
Hi, 

Currently I'm editing parts of my webpage using contenteditable, this changes are committed async through an API. 
I wonder if it would be possible to edit any part of the page (contenteeditable enabled)  using a [bubble ](https://quilljs.com/docs/themes/#bubble) toolbar type. 
For what I have seen so far It can only be specified a div that will be a container for the editor. 
A good example is the behaviour [editorjs](https://editorjs.io/)

Is it possible to hack this in order to work out of these containers? 

Thanks

**Comment by benbro** [comment]
This is out of scope.
