### ISSUE TITLE
How to resize the input area?(This is my solution in vue)

### ISSUE THREAD

**Issue by CharlseChen** [quilljs/quill#3056]
![image](https://user-images.githubusercontent.com/13670267/83587221-1e8ad280-a581-11ea-824d-06e51edb3ced.png)
At Css file,you  should use "less loader",such as  <style scoped lang="less">,then use '/deep/ ' cover the default css.
`        /deep/ .quill-editor {
          .ql-container{
            height: auto!important;
            min-height: 400px;
          }
          .ql-blank {
            min-height: 400px;
            resize: vertical;
          }
`
**The quill editor may add a new option to implement “resizable contenteditable area”**

**Comment by benbro** [comment]
You'll need to extend Quill. It's not supported in core.
