### ISSUE TITLE
Add option to clear background color and font color

### ISSUE THREAD

**Issue by jkevingutierrez** [quilljs/quill#3057]
If you add a background or a font color to some text in the editor, you are not allowed to clear that color (the only way is to click the clear button, clearing all the styles applied to that text), you can select a white background, but sometimes that's not what you want.

![image](https://user-images.githubusercontent.com/6220055/83655953-93134080-a584-11ea-8b40-0255ac404f4c.png)

It'd be great thing to add a 'none' option to the color palette, similar to what Google docs have:

![image](https://user-images.githubusercontent.com/6220055/83655901-87c01500-a584-11ea-951a-de112c0df423.png)

**Steps for Reproduction**

1. Visit https://quilljs.com/standalone/full/ or any page using a quill editor
2. Add some text in the editor, apply some styles to the text (Bold, Italic, h2)
3. Add a background color to the text
4. Try to clear that background without removing the other styles (adding a white background could be an option, but sometimes you don't want to have a white background, you just want to clear the background)

**Comment by piesuke** [comment]
@jkevingutierrez 
Have you found a solution to this problem?
I'm having the same problem.
