### ISSUE TITLE
quill + plyr Video player embed

### ISSUE THREAD

**Issue by KingBier** [quilljs/quill#3059]
Dear quill developers,

I'd like to know if its possible to insertEmbed videos via the plyr Video player script.

https://github.com/sampotts/plyr

Where do I need to change the core code to implement it into the editor?

Thanks in advance.

**Comment by benbro** [comment]
You'll need to [extend Quill](https://quilljs.com/guides/how-to-customize-quill/)
See also https://github.com/quilljs/awesome-quill
