### ISSUE TITLE
Editor does not preserve bold text when pasted from itself

### ISSUE THREAD

**Issue by wallylawless** [quilljs/quill#306]
If I copy text containing some bolded content from a Quill editor and then paste it back, the bold formatting is lost in the result.  Italics, underlines, links etc. seem to be preserved properly.

This can be replicated by the following steps:
* go to http://quilljs.com/ 
* in the example editor on the page, bold some words (either by keyboard shortcut or toolbar, doesn't matter)
* select all the content in the editor and copy it and then hit backspace to clear the editor
* paste back into the editor, the bolded words will be rendered as regular text

**Comment by jhchen** [comment]
Thank you for the report. Looks like something recent in webkit changed paste behavior to use a font-weight style instead of copying the <b> tag.

**Comment by wallylawless** [comment]
If there's anything more I can do to help just let me know.

**Comment by ivan-i** [comment]
This fix seems to be lost, the critical ` or node.style.fontWeight > 500` is missing. Merge conflicts? The issue is not fixed.

**Comment by aadamsx** [comment]
I'm seeing the same thing.

**Comment by jhchen** [comment]
The fix is live in 0.20.1.

**Comment by adam-horvath** [comment]
This issue is still/again reproducible in 1.3.7.

**Comment by vinay2042** [comment]
This issue is still reproducible in 1.3.7
