### ISSUE TITLE
Font-size for existing content in first Quill editor isn't taken

### ISSUE THREAD

**Issue by carsonbaker** [quilljs/quill#3062]
When existing content is provided to several quill editor instances, the font-size property of the text is removed on the first Quill editor, even if the value is present in the Size.whitelist.

**Steps for Reproduction**

1. Visit https://jsfiddle.net/r3yd4jgL

**Expected behavior**:

The font sizes should be the same in both editors.

**Actual behavior**:

Observe that the font size in the first Quill editor is different than the second.

**Platforms**:

Chrome 83.0.4103.61, MacOS

**Version**:

Affects all Quill versions, including Quill 2.0.0-dev*, and 1.3.7.

**Comment by jiuyehengxia** [comment]
I have met the same question as you too, the font-size property is removed when Quill editor is initialized. And the other property is ok, such as text-align, font-family. Has this problem been solved?
