### ISSUE TITLE
Using <br> instead of using <p>

### ISSUE THREAD

**Issue by conthub** [quilljs/quill#3065]
Hello,
Is there any way to configure quilljs to make use of BR instead of using P upon every time I hit ENTER key? In other words, not to use paragraphs, but BR instead.
Thanks for your help

**Comment by IcyFoxe** [comment]
I'm only about to try this editor, hovever I stumbled across your question.
Did you try pressing Shift + Enter to create a <br> instead of <p>? That usually creates a break instead of a new paragraph in these kind of editors..

**Comment by conthub** [comment]
Yeah, but what I need is a forced replace. I need a quilljs instance only meant to create html for email sending, and for this purpose I need NOT to use paragraphs but to use BR exclusively. I need that every time I hit ENTER it creates a BR and not a P.

**Comment by IcyFoxe** [comment]
I see, well I can't help you with that. It will most likely require changing the source code.

**Comment by conthub** [comment]
I see that quilljs used to use DIV for blocks, instead of P. Then they switched to use P. As mentioned here:
https://github.com/quilljs/quill/issues/159#issuecomment-49682445

Is there a way to config quilljs instance to use DIVs instead of Ps as an optional feature?

**Comment by ttypic** [comment]
>Is there a way to config quilljs instance to use DIVs instead of Ps as an optional feature?

yes, you can configure block blot and register it:

```
const Block = Quill.import('blots/block');
Block.tagName = 'DIV';

Quill.register({
  'blots/block': Block,
});
```

working example: https://jsfiddle.net/v9rf5apu/

**Comment by ffxsam** [comment]
@ttypic Thank you for this. Forced P tags in rich editors are for monsters. And unfortunately, unlike many other rich editors, Quill doesn't support shift+enter to insert a BR tag.

**Comment by phongnguyenmaster** [comment]
i still got an issue with p tag
I would like to use br instead

**Comment by NikolaDojic** [comment]
Does anyone have a solution for this yet? It seems to be an important issue.

**Comment by muimota** [comment]
Managed to use <br> following [this example](https://codepen.io/mackermedia/pen/oZOboN).  Found it through this [post](https://billauer.co.il/blog/2021/12/quill-br-shift-enter/)

**Comment by kozi** [comment]
Is there any good&simple solution for the functionality **SHIFT+ENTER** --> `<br>`.

In my opinion, this should be a **standard functionality** of a rich text editor!

**Comment by CharlieGreenman** [comment]
I created a new issue here: https://github.com/quilljs/quill/issues/4194
