### ISSUE TITLE
Quill 2.0 missing format allowlist

### ISSUE THREAD

**Issue by rockwotj** [quilljs/quill#3066]
Passing in an allowlist of formats is no longer supported in v2.0.0 is there a reason for that?

It seems options.format is never read and the following line is missing from the 2.0 branch:
https://github.com/quilljs/quill/blob/1.3.7/blots/scroll.js#L75

**Comment by rockwotj** [comment]
I was able to fix this by overriding the builtin quill scroll component with:

```typescript
import Quill from 'quill';

import {QUILL_FORMATS} from '../quill';

const BuiltinScroll = Quill.import('blots/scroll');

const QUILL_FORMATS_ALLOWLIST = Object.fromEntries(QUILL_FORMATS.map((f) => [f, true]));

export class Scroll extends BuiltinScroll {
  /* eslint-disable-next-line @typescript-eslint/no-explicit-any */
  formatAt(index: number, length: number, format: string, value: any) {
    if (!QUILL_FORMATS_ALLOWLIST[format]) return;
    super.formatAt(index, length, format, value);
    this.optimize();
  }
}

Quill.register('blots/scroll', Scroll, /*overwrite*/ true);
```

**Comment by usecodelee** [comment]
> I was able to fix this by overriding the builtin quill scroll component with:
> 
> ```ts
> import Quill from 'quill';
> 
> import {QUILL_FORMATS} from '../quill';
> 
> const BuiltinScroll = Quill.import('blots/scroll');
> 
> const QUILL_FORMATS_ALLOWLIST = Object.fromEntries(QUILL_FORMATS.map((f) => [f, true]));
> 
> export class Scroll extends BuiltinScroll {
>   /* eslint-disable-next-line @typescript-eslint/no-explicit-any */
>   formatAt(index: number, length: number, format: string, value: any) {
>     if (!QUILL_FORMATS_ALLOWLIST[format]) return;
>     super.formatAt(index, length, format, value);
>     this.optimize();
>   }
> }
> 
> Quill.register('blots/scroll', Scroll, /*overwrite*/ true);
> ```

How to use this code？
