### ISSUE TITLE
What symbols are encoded by Quill Editor?

### ISSUE THREAD

**Issue by walt1992** [quilljs/quill#3069]
It it not issue, but question.

well... It can be an issue that requires doc about encoded symbols.

Anyway, I found that some special symbols is encoded by Quill editor. for example,

Quill changes `<` and `>` to `&lt`  and `&gt`.

Is there any other symbols to be encoded by Quill editor? I can not find doc regarded with them.

Thanks.

**Comment by benbro** [comment]
Quill returns [Delta](https://quilljs.com/docs/delta/) with the [getContents()](https://quilljs.com/docs/api/#getcontents) function. It doesn't encode anything.
