### ISSUE TITLE
How to Translate quill toolbar options

### ISSUE THREAD

**Issue by VictorRivelo** [quilljs/quill#3072]
I'm trying to translate the quill toolbar options to pt-br, and found some interesting things about customization here: https://quilljs.com/docs/modules/toolbar/;

Where i've found  this [{ 'size': ['small', false, 'large', 'huge'] }],  to customize my dropdowm, but if i change the options to pt-br, for example  'smal' -> 'pequeno', the component doesn't recognize and treats as false.

How can i properly translate this options?

**Actual behavior**:
![image](https://user-images.githubusercontent.com/33028110/85316701-8d2dc280-b493-11ea-97fe-7afad9b6f3a3.png)

**Version**: 2.0.0-beta.2

**Comment by benbro** [comment]
You can defined your own HTML for the toolbar:
https://quilljs.com/docs/modules/toolbar/
