### ISSUE TITLE
Cannot delete characters in iOS, and the Placeholder does not disappear

### ISSUE THREAD

**Issue by LHMing01** [quilljs/quill#3073]
I have trouble when I use Quill.
Cannot delete characters when you press delete  in iOS, and the Placeholder does not disappear,It still exists,but It works fine in Android
**Steps for Reproduction**

**Expected behavior**:
delete characters normally
**Actual behavior**:
Cannot delete characters when you press delete
**Platforms**:
ios

Include browser, operating system and respective versions

**Version**:
2.0.0-dev.3
Run `Quill.version` to find out

**Comment by ShuangqiShi** [comment]
Have you solved the problem

**Comment by LHMing01** [comment]
> Have you solved the problem

use the version 1.X, it is the stable version.
