### ISSUE TITLE
Custom embed Blot cannot reinstantiate already existing object

### ISSUE THREAD

**Issue by Muldaer** [quilljs/quill#3076]
I was trying to insert a custom object (using blots/embed) into the editor and that part works as show by the playground. However if I try to reinstantiate the content submitted it returns undefined at the params givens to the class. Something I am missing?

I have created a codepen to show this behavoir.

[Codepen](https://codepen.io/maldyr/pen/KKVvyvE)

**Comment by Hggo** [comment]
That would be helpful, right now i'm having to remove and recreate every blot everytime i reinstantiate the delta
