### ISSUE TITLE
Insert file protocol url by Delta.insert getting incorrect result

### ISSUE THREAD

**Issue by wowissu** [quilljs/quill#3077]
I using Electron to build my APP in desktop
and i try to display local img through by file protocol url in my APP 
is working when I do this no my pure html content
```html
<img  src="file:///C:/.../test.png" />
```
but when I put into Quill like this `quill.insertEmbed(0, 'image', 'file:///C:/.../test.png', 'user')`
below is what  the result look like in editor html source code  
![不正確的src](https://user-images.githubusercontent.com/12434914/85939236-471aa800-b946-11ea-87ad-f7e7d9d3f704.PNG)

`https://` `http://` `base64` is working fine but not file protocol url

Is not on supported or Am i doing something wrong?

**Comment by arcelan** [comment]
try below
```
const Image = Quill.import('formats/image')
Image.sanitize = function (url) { return url }
```
