### ISSUE TITLE
Preserving custom delta attributes

### ISSUE THREAD

**Issue by chinshr** [quilljs/quill#308]
This is more of a question than an issue! How do I go about supporting my own custom delta format in without it being overwritten. I would like to add time offsets for each of the text chunks that I am inserting. The text chunks may be formatted (visually) but don't necessarily have to, but at least they should be respected when saving, reloading, etc. Example here:

``` JavaScript
{
  ops:[
    { insert: 'Gandalf', attributes: {offset: 0, duration: 0.5} },
    { insert: ' the ', attributes: {offset: 0.5, duration: 0.2}  },
    { insert: 'Grey', attributes: {offset: 0.7, duration: 0.3}  }
  ]
}
```

**Comment by jhchen** [comment]
This isn't well supported at the moment but should be address with the custom format feature I'm working on.

**Comment by chinshr** [comment]
Is there anything I could test or already use? Like in this [branch](
https://github.com/quilljs/quill/tree/format). Is there an "old" or current
way to support formats?

**Comment by jhchen** [comment]
That branch is still a work in progress

**Comment by chinshr** [comment]
Do you have a time in mind when you want to finish this?

Is there a current way to work with you can point me to?

**Comment by butsjoh** [comment]
Always willing to help as well. If you provide the rough interfaces for where you want to take it i am willing to implement it.

**Comment by butsjoh** [comment]
@chinshr The closest you can get to get it working somehow is to check this thread https://discuss.quilljs.com/t/ability-to-create-custom-embed-types/52/6

**Comment by chinshr** [comment]
@butsjoh thanks for the pointer, this ptobably goes too far what I currently need. I would be happy if I could wrap my text chunks into simple <span> tags with additional attributes, like those I mentioned above: offset, duration, etc. maybe I can clone and modify the Authorship module that sort of solves a similar problem.

**Comment by chinshr** [comment]
I also found this thread in the forum that is related https://discuss.quilljs.com/t/converting-a-delta-into-viewable-formats/136

**Comment by butsjoh** [comment]
https://github.com/thomsbg/convert-rich-text/blob/master/README.md is also relevant

**Comment by Sopamo** [comment]
Any plans / estimate on this? I would be glad to help out on that feature branch if you wish.

**Comment by jhchen** [comment]
You can now define a custom attributor with [Parchment](https://github.com/quilljs/parchment/#attributors) and Quill will treat this similarly to a format, such as adding it to delta's attributes.

```js
var Parchment = Quill.import('parchment');
var offsetAttributor = new Parchment.Attributor.Attribute('offset', 'data-offset', { 
  scope: Parchment.Scope.INLINE
});
Quill.register(offsetAttributor);

var quill = new Quill('#editor');
quill.setText('Gandalf the Grey');
quill.formatText(0, 7, 'offset', '0');
quill.getContents();  // should have a delta with offset attributed
```

**Comment by adamkdean** [comment]
If I may add my opinion, this is a subpar solution, as it means a lot of formatText calls if your format requires multiple attributes. Take for example, if you wanted to format a link to have more metadata than just the href, you may wish to `insertText(0, 'link here', { link: 'http://example.com', nofollow: true, target: '_about' }` etc.

With what you're suggesting, I'd first have to insert the text, then get the location of it, then call formatText three times, each with three attributors configured. It doesn't feel like JavaScript.

**Comment by jhchen** [comment]
I gave one example and if you look at the docs for formatText and insertText you will find it is an overloaded function that supports passing in an object of multiple attributes.

**Comment by Terricka** [comment]
Hi,

Is the above solution still currently the only way to have  custom styles/attributes that are able to be preserved/saved on reload?

Working with a custom style and while I'm able to apply it, I notice that the value of the key is empty in the actual delta, therefore its unable to save (ie. a line height property)
