### ISSUE TITLE
it is for angular6

### ISSUE THREAD

**Issue by QianYS** [quilljs/quill#3088]
when I use it for angular6
I do it 
npm install ng-quill
npm install angular angular-sanitize quill
npm install ngx-quill-editor --save

when I start it
![image](https://user-images.githubusercontent.com/28479614/86513316-d0951300-be3b-11ea-9a3d-44d02b63d809.png)

![image](https://user-images.githubusercontent.com/28479614/86513316-d0951300-be3b-11ea-9a3d-44d02b63d809.png)

**Comment by QianYS** [comment]
![image](https://user-images.githubusercontent.com/28479614/86513331-ef93a500-be3b-11ea-840f-ffd1d04efe6a.png)
module.ts  I import it

**Comment by DaniyelMe** [comment]
You accidentally misspelled quill as quaill ![image](https://user-images.githubusercontent.com/16323299/88188024-f72aba80-cc3f-11ea-8004-3a693ab5319a.jpeg)

**Comment by benbro** [comment]
Answered.
See also https://github.com/quilljs/quill/issues/3524
