### ISSUE TITLE
[Question] How to find subset ops in a delta

### ISSUE THREAD

**Issue by Naghal** [quilljs/quill#3090]
Hi, I am trying to figure out what would be the best option to identify a particular set of ops in a given delta.

My use case is the following:
I am appending a user signature inside an editor on page load. On the click of a button, I want to either replace or delete that signature. The easy way to do this would be to use `editor.getContents()` and scan to find the signature and use `editor.setContents()` to update the editor with the new delta where the signature is either replace or deleted.

While this might work in most case, it would not work when signature contains an embed like an image.

To fix this, my idea was either to add an ID/Class to all elements of a signature to easily find them after having called `getContents()` or to wrap the signature in a wrapper with an id or a class.

How can I specify an ID for elements/how can I wrap them to be able to find them easily when calling `getContents()`?

**Version**:
1.3.7

**Comment by KamilOcean** [comment]
Good day, @Naghal. I faced with similar issue.

First of all, If you really want to identify blot content in result of `getContents()` then you need use name of your blot. That name is property key in content.

For example, see my code where I find needed blot in difference between content and its old version. In other words, I find is there change with my blot 

```js
const currentContents = quill.getContents()
const diffs = oldDelta.diff(currentContents)
const embedDiff = diffs.ops.find(i => {
    return i?.attributes && i.attributes.hasOwnProperty('blot-name')
})
```

Second. Make sure, that you really have to work with `delta`, because it might be just work with `DOM`. if I'm not mistaken, you can just find element and remove it: `document.querySelector('#id').remove()`

**Comment by Naghal** [comment]
Hi @KamilOcean , thank's for pointing me in the right direction!

What I ended doing is create a new Attribute and add that attribute to every ops in the signature, that way I can know which ops in a delta corresponds to the signature.

**Creating the attribute and registring it**
```js
var Parchment = Quill.import('parchment');
var offsetAttributor = new Parchment.Attributor.Attribute('dataId', 'data-id', { 
  scope: Parchment.Scope.INLINE
});
Quill.register(offsetAttributor);
```

**Hook to add attribute to ops before saving signature to DB**
```js
signatureEditor.formatText(0, signatureEditor.getLength(), 'dataId', 'signatureDelta');
var signature = JSON.stringify(signatureEditor.getContents());
// ...code to submit form
```

**Example to replace a french signature by the english one**
```js

if ($('#templateLanguage').val() === 'fr') {
    var newSignature = JSON.parse($('#signatureFrHolder').val()) // Json encoded french signature 
} else {
    var newSignature = JSON.parse($('#signatureEnHolder').val()) // Json encoded english signature 
}
const originalContent = messageEditor.getContents();
const withoutSignatureOps = originalContent.filter(c => !c.attributes || c.attributes.dataId !== 'signatureDelta');
const withoutSignature = new Delta(withoutSignatureOps.slice(0, Math.max(withoutSignatureOps.length - 2, 1)));
const newContent = withoutSignature.concat(new Delta(newSignature));
messageEditor.setContents(newContent);
```
