### ISSUE TITLE
IndexSizeError: The index is not in the allowed range. 

### ISSUE THREAD

**Issue by saifeiLee** [quilljs/quill#3093]
![image](https://user-images.githubusercontent.com/28710808/86994044-089fab80-c1d8-11ea-8885-eae28b8a7a00.png)

**Expected behavior**:
selection.getRangeAt(0) should no error.
**Actual behavior**:
IndexSizeError: The index is not in the allowed range. 
**Platforms**:
IOS / Ipad
Include browser, operating system and respective versions
safari
**Version**:
1.3.7

Hello guys. I am very confused why the selection object has rangeCount 1, but selection.getRangeAt(0) throws error. Please give me some advice. Thanks in advance.

**Comment by JackyRoss** [comment]
@saifeiLee 
I have the similar issue. Quill is working well in Chrome or Firefox, only in Safari get the error: `The index is not in the allowed range.`  
Can you tell me the code is `selection.getRangeAt(0)` is in which file?
