### ISSUE TITLE
how to set up uploading pictures under the theme of "bubble"

### ISSUE THREAD

**Issue by GentleDream** [quilljs/quill#3095]
Hello
I set theme for the bubble.
How can I add a function of **uploading pictures** to **bubble**

**Comment by kevinmelo** [comment]
You cna either declare as this example https://github.com/quilljs/quill/blob/develop/docs/_includes/standalone/full.html

Or can pass as a option in modules as ['image']

```
editorOpts: {
    theme: 'snow',
    modules: {
        toolbar: [
           ['bold', 'image']...
        ]
    }
}
```
