### ISSUE TITLE
Quill crash on Chrome when pasting (formatted) text from outlook on IE11

### ISSUE THREAD

**Issue by massan0314** [quilljs/quill#3096]
Quill crash on Chrome when pasting (formatted) text  from outlook on IE11.

It does not matter which text or how long the copied text from the described source is.
It can be an unformatted letter or a complete text.

I could not find out what the real problem is. Copy and paste formatted or unformatted text from other sources I tried works fine.

**Steps for Reproduction**

1. Open Internet Explorer 11 (latest version)
2. Navigate to https://www.outlook.com
3. Copy a text from any e-mail in any length. (even only 1 word)
4. Open Chrome and paste this text into any available Quill editor:
For example: 
https://quilljs.com/standalone/full/
Or
https://quilljs.com/playground/

**Expected behavior**:
Text should be added to the editor.

**Actual behavior**:
Browser error ->  Error code: STATUS_ACCESS_VIOLATION

**Platforms**:
OS: 
Windows 10
Browsers: 
IE11 (11.900.18362.0)
Chrome (83.0.4103.116)

Quill 1.3

![screen0001](https://user-images.githubusercontent.com/52655745/87268184-bd9dd500-c504-11ea-8f3b-e467122c04f0.png)
![screen0002](https://user-images.githubusercontent.com/52655745/87268187-bf679880-c504-11ea-924b-56391e467cc0.png)

**Comment by benbro** [comment]
When a browser crash it's a bug in the browser.
Please report to [Chromium](https://bugs.chromium.org/p/chromium/issues/list).

**Comment by massan0314** [comment]
Quill crashes, the browser is fine.

The browser shows an error: Error code: STATUS_ACCESS_VIOLATION
See the 2nd image I appended.  
This error is about page crash or loading errors.

My idea is, that the content from IE11 on the clipboard is creating this error when Quill is processing it.  
Other Editors on Chrome work fine with the same copy&paste content. Just quill dies.

**Comment by massan0314** [comment]
I solved the problem by clearing the clipboard completely from text formatting when pasting.


				`clipboard: {
					matchers: [
						[ Node.ELEMENT_NODE, function(node, delta) {
							return delta.compose(new Delta().retain(delta.length(), 
							{ color: false,
							  background: false,
							  bold: false,
							  strike: false,
							  underline: false
							}
							));
						  }
						] 
				}`

But this is just a personal choice. If you want to paste formatted text, the editor crashes in this case. 
There is a weakness in processing formatted text somewhere.

**Comment by massan0314** [comment]
It seems that the problem has disappeared.
Everything works fine now.
