### ISSUE TITLE
iOS simplified Pinyin （character） cannot be input normally

### ISSUE THREAD

**Issue by ssqdoit** [quilljs/quill#3098]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**
1. Integrate Quill 2.0.0-dev.3  into iOS WKwebview component
2. Switch to simplified Pinyin （character） input method
3. The result is that you can't input it properly，Unable to delete after input。

**Expected behavior**:

**Actual behavior**:

**Platforms**:

iOS WKwebview  component

**Version**:

2.0.0-dev3

**Comment by ShuangqiShi** [comment]
selection.js : 'compositionend' did not respond
