### ISSUE TITLE
"Cannot read property 'parentNode' of null" error thrown when removing format

### ISSUE THREAD

**Issue by dandirks** [quilljs/quill#310]
Platform: OSX 10.10.2
Browser: Chrome 41.0.2272.89

Steps to reproduce: 
1) Go to http://quilljs.com/examples/
2) Delete all of the text out of the first example.
3) Type "This is a test." in the editor.
4) Apply bold to the word "This"
5) Apply italic to the word "This"
6) Apply bold to the entire line.
7) Remove bold from the entire line.

Chrome should now throw `Uncaught TypeError: Cannot read property 'parentNode' of null` at `quill.js:5026`.

Let me know if I need to provide additional information.

Thanks!

**Comment by thomsbg** [comment]
Thanks for the clear repro steps! I was experiencing this error also, but could not pin it down.
