### ISSUE TITLE
[BUG] Empty list item traverse problem on Safari

### ISSUE THREAD

**Issue by baldemir** [quilljs/quill#3100]
Traversing a list (ordered or unordered) with up and down arrow buttons is problematic in Safari. Where there is an empty list item arrow down button doesn't get to empty list item. It does nothing or it scrolls the page if there is a scroll area in page.

**Steps for Reproduction**

1. Visit https://codepen.io/beratingen/pen/qBbJNGr on Safari
2. Click on item one
3. Press down arrow button two times

**Expected behavior**:
Cursor should be in empty list item
**Actual behavior**:
Cursor is in second item and arrown down button doesn't get it to empty list item. You can only get the cursor to empty list item with mouse
**Platforms**:
Safari 13.1.1 on MacOs 10.14.6

**Version**:
Quill 1.3.6

**Comment by aldinezi** [comment]
@baldemir do you have any workaround for this? I am having the same case too.
