### ISSUE TITLE
Reduce the toolbar and editor size.

### ISSUE THREAD

**Issue by kylak** [quilljs/quill#3104]
Hello, I would like to manage the size of the editor (toolbar included) but I don't know how to do it.
I found it to big for my website, so how could I manage the size of the editor ?

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**: QuillJS editor (toolbar included) resized.

**Actual behavior**: Didn't succeed to change the QuillJS editor (toolbar included) size.

**Platforms**: macOS - Safari, Chrome.

Include browser, operating system and respective versions
**Version**: QuillJS used from CDN (PS: it seems that the "http:" words are missing).

Run `Quill.version` to find out

**Comment by benbro** [comment]
Use CSS.
