### ISSUE TITLE
Contenteditable="false" on first line disables arrow keys/backspace key upon selecting all content in editor

### ISSUE THREAD

**Issue by repthesaj** [quilljs/quill#3106]
<img width="713" alt="Screen Shot 2020-07-17 at 3 10 00 PM" src="https://user-images.githubusercontent.com/68265468/87834853-56ec2480-c840-11ea-9bc1-194cd41f1518.png">
<img width="696" alt="Screen Shot 2020-07-17 at 3 09 48 PM" src="https://user-images.githubusercontent.com/68265468/87834856-594e7e80-c840-11ea-88fb-39a5ac38a008.png">

**Steps for Reproduction**

1. Visit [https://codepen.io/repthesaj/pen/BajGKQy](https://codepen.io/repthesaj/pen/BajGKQy)
2. Select all text
3. Press left/right arrow keys & backspace key

**Expected behavior**:

Should be able to move arrow keys and delete all content in the editor.

**Actual behavior**:

Nothing happens. (**NOTE**: if contenteditable="false" is not on first line but some line after the first, behavior is as expected)

**Platforms**:

Include browser, operating system and respective versions

Google Chrome
macOS

**Version**:

All

**Comment by benqy** [comment]
![image](https://user-images.githubusercontent.com/611055/167606004-335c7a33-41c3-41ed-a007-cf90cc1f0c4f.png)
i use some stupid hack to fix this problem. 
insert a contenteditable="true" element in the first child, with any char that user can't see it @saltfishman
