### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by jogibear9988** [quilljs/quill#3112]
@jhchen @luin 

Hello, we'd like to use quill in a project, but we use webcomponents.

I see here are already some issues about that, and also pull requests (#300 #738 #904 #916 #1826 #2021 #2961 #2966)

I would work on this, but only if it got's the chance to be merged)

I see here are 55 open pull requests, most of them without any comment why they are not merged...

**Comment by DaniyelMe** [comment]
I hope they feel well

**Comment by bmehta** [comment]
I am also curious - is this project active and being maintained?

**Comment by claytongulick** [comment]
FWIW, Slack uses Quill for it's little embedded editor, so I don't think Quill is going away any time soon.

**Comment by benbro** [comment]
Duplicate https://github.com/quilljs/quill/issues/3359
