### ISSUE TITLE
Source code Edit (HTML) or code view

### ISSUE THREAD

**Issue by srikanthchitla** [quilljs/quill#3113]
1) Do we have Source code Edit (HTML) or code view in p-editor? if yes, is there any example?

2) Can we show the html code in p-editor when it loads? Right now it is converting HTML code to text.

**_Example;_**
**app.component.html**
<p-editor [(ngModel)]="text">

**app.component.ts**
export class EditorDemo {
text: `<div>Hello World!</div><div>PrimeNG <b>Editor</b> Rocks</div><div><br></div>`
}

**Result in Editor**
Hello World!
PrimeNG Editor Rocks

**Can I expect the result as html code in result in Editor ??**
**Ex:**
`<div>Hello World!</div><div>PrimeNG <b>Editor</b> Rocks</div><div><br></div>`

**Comment by thekrotek** [comment]
Would also love to have such button. Wonder why it isn't there by default?

**Comment by cimenta** [comment]
you might find useful this module https://github.com/benwinding/quill-html-edit-button

but it does not let you insert <script> tag

**Comment by benbro** [comment]
Duplicate https://github.com/quilljs/quill/issues/128#issuecomment-215263950
