### ISSUE TITLE
How you guys run dev version?

### ISSUE THREAD

**Issue by KamilIsmagilov** [quilljs/quill#3117]
I just tried to find some code and check it, may be I can solve my problem. But I couldn't run `build:webpack` script, that wrote down in `package.json`.

Actually, I fixed it by removing `;` from your `build:webpack` script. And adding **&&** that means commands will execute in order, one by one.

Before:
`"build:webpack": "webpack --config _develop/webpack.config.js; rm dist/quill.core dist/quill.bubble dist/quill.snow",`

Now:
`"build:webpack": "webpack --config _develop/webpack.config.js && rm dist/quill.core dist/quill.bubble dist/quill.snow",`

And now it really works. But I'm just wondering. How you guys run dev version? Or in my case how you build `dist` folder? Actually I need `dist` folder.

**Steps for Reproduction**

1. clone repo
2. `npm i`
3. `npm run build:webpack`

**Expected behavior**:
Webpack runs and then remove files from dist folder

**Actual behavior**:
Error: Cannot find module 'C:\Users\User\projects\quill\_develop\webpack.config.js;'

**Platforms**:

Windows 10

**Version**:
2.0.0-dev.4

**Comment by benbro** [comment]
https://github.com/quilljs/quill/blob/main/.github/DEVELOPMENT.md
