### ISSUE TITLE
How to change inline classes for the code-block(ql-syntax) and indent(ql-indent)

### ISSUE THREAD

**Issue by dharmatv** [quilljs/quill#3118]
Instead of quill js classes how to change an inline class (CSS) for code-block and indent or any HTML syntax

**Now:**
< pre class="ql-syntax" spellcheck="false" >Test code block
</ pre >

**want:**
< code >html</ code > and 
class:
text-indent: 30%;

Could u please suggest anyone

**Comment by KamilOcean** [comment]
I suggest that you need to create new blot with all tags and behaviors that you need.

You can see how to create your own blot in docs: https://quilljs.com/guides/cloning-medium-with-parchment/#links

**Comment by dharmatv** [comment]
I tried by using parchment and the above link. At finally I got an indent  but not a code(code-block) tag
So could u please help me with this

The following code represents for indent, maybe it will help who is searching for this
```
import { Quill } from 'vue-quill-editor';
  const Parchment = Quill.import('parchment')
class IndentAttributor extends Parchment.Attributor.Style {
  add (node, value) {
    if (value === 0) {
      this.remove(node)
      return true
    } else {
      return super.add(node, `${value}em`)
    }
  }
}

const IndentStyle = new IndentAttributor('indent', 'text-indent', {
  scope: Parchment.Scope.BLOCK,
  whitelist: ['1em', '2em', '3em', '4em', '5em', '6em', '7em', '8em', '9em']
})

Quill.register(IndentStyle, true)
```
