### ISSUE TITLE
Unable to access Editor instance in dynamically imported react-quill in NextJS 

### ISSUE THREAD

**Issue by sanderfish** [quilljs/quill#3121]
I'm using react-quill in a NextJS app. I'm looking to extend a part of the app where I want to force users to use the Quill instance with a specific formatting option enabled by default (list). To achieve this, I believe I need access to the Quill Editor instance.

However, when attempting to use a ref, I'm unable to call the getEditor method on the ref. The only method available is `retry`.

I've made a CodeSandbox: https://codesandbox.io/s/nextjs-dynamic-react-quill-ref-example-sxm64
Check the browser console to see what the ref object is.

**Expected behavior**:
I would expect the ref to contain a `getEditor` method 

**Actual behavior**:
The ref only contains a `retry` method

**Version**:
2.0.0-beta.2

**Comment by jularbs** [comment]
have you come up a solution for this?

**Comment by DarrenKwonDev** [comment]
me also have the same error.... any solution for this??

**Comment by sdmels** [comment]
same error. I appreciate if someone can share lights on it

**Comment by benbro** [comment]
This is an integration issue and not an issue with Quill.
