### ISSUE TITLE
block level styling with classes

### ISSUE THREAD

**Issue by joshmarinacci** [quilljs/quill#313]
I'm working on an editor that, ideally, would work semantically. I want the user to be able to choose the style for the current block, not just the currently selected text. They can choose semantic styles like 'header', 'body', 'footnote', 'blockquote', etc.  The toolbar module uses block level styling  for text alignment, so I reverse engineered that and came up with this solution. 

Create a format with the type 'line' and a class prefix.

    editor.addFormat('blocktype',{ type:'line', "class":"blocktype_"});

    editor.setHTML(
            '<div>This is title</div>'
           +'<div>This is body</div>'
    );
    editor.focus();
    //editor.insertText(3,"hello",'strike',"stuff");
    editor.formatLine(0, 10, 'blocktype', 'header', 'editor');
    editor.formatLine(15,20, 'blocktype', 'body',   'editor');

So, is this the right way to do this?  Formats of type 'line' are completely undocumented, as is the formatLine function.  Will I run into any problems doing this? If this *is* the correct way, would you like me to add some docs on it?

**Comment by jhchen** [comment]
There isn't an officially supported way to add new formats to Quill at the moment but that's one of the new features I'm working on. It's a pretty big change though as the hope is it will allow for even very complex formats to be introduced so the timeline is not very immediate.

**Comment by pajoma** [comment]
I have the same issue. Right now I have the following code to add my custom formats

```javascript
	editor.addFormat('h4', {
        				tag: 'span', 
        				class: 'h4',
        			});
       editor.formatText(0, 10, 'h4', '_format', 'silent'); 
```
and the following css

````css
.h4_format {
	font-weight: bold; 
	font-size: 16px; 
}
```
Quill is simply concatenating the name and value parameters and apply the concatenated string as classname to the tag given in the prepared format (and wrapping the content with it). Will this behaviour change?

**Comment by jhchen** [comment]
Here's a demo showing how to switch between using styles or classes in Quill 1.0: http://beta.quilljs.com/playground/#class-vs-inline-style. Take a look at [Parchment](https://github.com/quilljs/parchment) for creating/recognizing new DOM node types.

**Comment by radjivF** [comment]
@jhchen did you guys finally add this feature? its actually hard to find how to do it with the documentation

Thnks
