### ISSUE TITLE
File Extension Issue

### ISSUE THREAD

**Issue by reelfunky** [quilljs/quill#3132]
I have downloaded version Version 1.3.6 and followed the instructions to implement Quill however chrome fails to find any of the requested .js files.  I have looked into it and it seems the code is asking for the file in all cases without the extension .js.  I don't know if this is an acceptable way of importing files however Chrome browser doesn't appear to like it.  If i change the code to include the .js extension it does then import correctly but it is a real pain tring to find all the entries in every file.

Intersetingly if I use the hosted version "<script src="//cdn.quilljs.com/1.3.6/quill.core.js"></script>"  rather than having the files local it does appear to work.

![quillerror](https://user-images.githubusercontent.com/42388897/89717765-75fa5400-d9b1-11ea-9b43-52faafa7f869.PNG)

**Comment by benbro** [comment]
https://quilljs.com/docs/quickstart/
