### ISSUE TITLE
Export the registered blots/modules

### ISSUE THREAD

**Issue by nghuuphuoc** [quilljs/quill#3134]
Our app isn't written in JavaScript directly, and it's not possible for us to extend a registered blot/module __dynamically__ such as

```javascript
// Not possible for us
let BlockEmbed = Quill.import('blots/block/embed');
class ImageBlot extends BlockEmbed {
  ...
}
```

But it's possible for us to write something likes

```javascript
import { BlockEmbed } from 'quilljs';

class ImageBlot extends BlockEmbed {
  ...
}
```

Can you export the registered blots/modules, and we can access them directly.
As I imagine the [core.js](https://github.com/quilljs/quill/blob/develop/core.js) should be

```javascript
import Block, { BlockEmbed } from './blots/block';

Quill.register({
  'blots/block': Block,
  'blots/block/embed': BlockEmbed,
  ...
});

export {
  Block,
  BlockEmbed,
  // Other blots/modules here ...
}
```

**Comment by benbro** [comment]
Works in [v2.0.0-beta.1](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.1)
https://github.com/quilljs/quill/blob/develop/packages/quill/src/quill.ts

**Comment by nghuuphuoc** [comment]
@benbro The lates version of Quill doesn't expose the original blots. What I want is to be able to get the reference of the original blots as following:

```ts
// https://github.com/quilljs/quill/blob/develop/packages/quill/src/core.ts
import Embed from './blots/embed';

export {
  Embed,
};

// https://github.com/quilljs/quill/blob/develop/packages/quill/src/quill.ts
import { Embed } from './core';

export {
  Embed,
}
```
 
Can I create a pull request for this?
