### ISSUE TITLE
Adding custom font sizes

### ISSUE THREAD

**Issue by arctic-ice-cool** [quilljs/quill#3135]
When adding custom font sizes via registering the `Size` class, the whitelisted array of sizes replicates this (for example):

`Size.whitelist = ['8pt','10pt','12pt','14pt']`

When the editor is initialised, the default font size (12px or whatever) is active in the editor, however, the font selector equals 8pt because that was the first in the list, and there hasn't been an exact match.

How do you get Quill to default to the standard `10` displayed in the font size dropdown, rather than the way-off `8`?

It already does this for the `['Small', 'Normal', 'Large', 'Huge']` - it defaults to `'Normal'` and not just `'Small'` because it was first in the list.

Thanks in advance!

**Comment by arctic-ice-cool** [comment]
OK figured this out after lots of looking around, so will leave this solution here in case it crops up for anyone else:

**To set custom font sizes in Quill and have the second font in the dropdown list be shown as the default:**

Register the custom font sizes in Quill before initializing the editor:

_(I want 10**pt** to be the default in this example, **px** or **em** etc could be used)_

```
import Quill from 'quill'

let Size = Quill.import('attributors/style/size');
Size.whitelist = ['8pt', '12pt', '14pt', '16pt', '18pt', '20pt', '32pt'];
Quill.register(Size, true);
```

Now initialize your Quill editor as usual
For the toolbar add the font sizes you require, MINUS the default size you want (specify **false**):

```
options = {...
toolbar: [
    ['bold', 'italic', 'underline'],
    [{ 'list': 'ordered' }, { 'list': 'bullet' }],
    [{ 'size': ['8pt', false, '12pt', '14pt', '16pt', '18pt', '20pt', '32pt'] }],
    [{ 'font': [] }],
    ['link', { 'color': [] }, 'clean']
]
...}
```


Now, specify the default font size (10pt) in your CSS - ensure it isn't overridden in the default styles!

```
.ql-container {
  font-size: 10pt;
}
```

Now add your labels, as **CSS Content** variables:
```
.ql-snow .ql-picker.ql-size .ql-picker-label[data-value="8pt"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="8pt"]::before {
  content: '8';
  font-size: 8pt;
}

.ql-snow .ql-picker.ql-size .ql-picker-label::before,
.ql-snow .ql-picker.ql-size .ql-picker-item::before {
  content: '10';
  font-size: 10pt;
}

.ql-snow .ql-picker.ql-size .ql-picker-label[data-value="12pt"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="12pt"]::before {
  content: '12';
  font-size: 12pt;
}

.ql-snow .ql-picker.ql-size .ql-picker-label[data-value="14pt"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="14pt"]::before {
  content: '14';
  font-size: 14pt;
}

.ql-snow .ql-picker.ql-size .ql-picker-label[data-value="16pt"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="16pt"]::before {
  content: '16';
  font-size: 16pt;
}

.ql-snow .ql-picker.ql-size .ql-picker-label[data-value="18pt"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="18pt"]::before {
  content: '18';
  font-size: 18pt;
}

.ql-snow .ql-picker.ql-size .ql-picker-label[data-value="20pt"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="20pt"]::before {
  content: '20';
  font-size: 20pt;
}

.ql-snow .ql-picker.ql-size .ql-picker-label[data-value="32pt"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="32pt"]::before {
  content: '32';
  font-size: 32pt;
}
```

_Notice how **10pt** doesn't have the [data-value="10pt"] selector - this is the catch-all default size for the default content editor size (so no size applied). Careful when overriding the default styles for the default, if you set up !important incorrectly to override the default 'Normal' displayed content, it may override all values with 'Normal' - just something to watch out for._

I've now learnt this exact concept is the same for custom font sizes.

**Comment by jerryokk** [comment]
![image](https://github.com/quilljs/quill/assets/126859008/aae6e828-25db-4e45-873a-0afaa6b12f5c)

a bit strange

**Comment by mukolweke** [comment]
> ![image](https://private-user-images.githubusercontent.com/126859008/329444507-aae6e828-25db-4e45-873a-0afaa6b12f5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTY2MjUsIm5iZiI6MTcyMzkxNjMyNSwicGF0aCI6Ii8xMjY4NTkwMDgvMzI5NDQ0NTA3LWFhZTZlODI4LTI1ZGItNGU0NS04NzNhLTBhZmFhNmIxMmY1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxNzM4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTIzOGQ5YWRiODEwYzU3ODI2YjdhNTE1MTFiODBmNGExYjQ0MzFlNmFhNjA3ZDFhOGMzODY2Mjg3MDIyNjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LOkWUw9Bj0Pgi1ZVePXPYMDjxzbqbFK1BCcpc1lUzdA)
> 
> a bit strange

just make them have the same font size

`
ql-snow .ql-picker.ql-size .ql-picker-label[data-value="8px"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="8px"]::before {
  content: '8';
  font-size: 14px;
}

.ql-snow .ql-picker.ql-size .ql-picker-label::before,
.ql-snow .ql-picker.ql-size .ql-picker-item::before {
  content: '10';
  font-size: 14px;
}

`
