### ISSUE TITLE
discrepancy in unicode character lengths in quill

### ISSUE THREAD

**Issue by khaled4vokalz** [quilljs/quill#3138]
discrepancy in unicode character lengths in quill

**Steps for Reproduction**

1. check https://codepen.io/khaled4vokalz/pen/YzqWjgv?editors=0011
2. even though `"ő".length === 2` quill considers it as length `1` when we do `quill.getLength()` but for an emoji e.g. `"😀".length === 2` quill considers it as length of `2` when we do `quill.getLength()` 
3. even though `quill.getLength()` returns 1 for `ő`, if I try to create a delta with `ő` and check `delta.length()` that returns `2`. This is quite confusing.

**Expected behavior**:
-  as JS returns same length for both the characters quill should do the same

**Actual behavior**:
- quill.getLength() returns 2 for `ő` and quill.getLength() returns 3 for `😀`. quill should have a consistent behavior regarding the length that it calculates

**Platforms**:

Chromium: 81.0.4044.138, Ubuntu 20.04

**Version**:

1.3.6

**Comment by khaled4vokalz** [comment]
@jhchen can you please review this issue early?

**Comment by benbro** [comment]
Related https://github.com/quilljs/quill/issues/1230
