### ISSUE TITLE
Removing the formating from the text takes multiple clicks in Chrome

### ISSUE THREAD

**Issue by KhushilMistry** [quilljs/quill#3139]
This issue happens with all the toggle type of commands. 

**Steps for Reproduction**
1. Write any text in Quill.
2. Select the text and make it bold.
3. Now, again click on the bold button to remove the bold formatting. 

**Expected behavior**:
It should remove the bold immediately. 

**Actual behavior**:
It takes multiple clicks to remove the bold. 

**Platforms**:
Google Chrome 84.0.4147.125, MacOS Catalna 10.15.5

**Version**:
1.3.7

![captured](https://user-images.githubusercontent.com/17615573/90601151-5d8e0300-e215-11ea-80f7-6be18e81722d.gif)

**Comment by KhushilMistry** [comment]
@jhchen Any idea or thoughts on this?

**Comment by Illuday** [comment]
I've the same problem on a Vuejs environment :

![activitour-6](https://user-images.githubusercontent.com/2337414/91165673-5c574d00-e6d1-11ea-9b0a-60f439155520.gif)

**Comment by KhushilMistry** [comment]
I am using ReactJS environment.

**Comment by KhushilMistry** [comment]
Please checkout issue #1290 for more detail. Basically needed this:
```
let toolbar = this._quill.getModule('toolbar');
toolbar.container.addEventListener('mousedown', (event: any) => {
  event.preventDefault();
});
```

**Comment by Illuday** [comment]
Thanks for the hint. I made it work with this:

```
document.querySelector('.ql-toolbar').addEventListener('mousedown', function (e) {
      e.preventDefault()
})
```

You can close the issue.
