### ISSUE TITLE
Can't access defocus state for styling purposes

### ISSUE THREAD

**Issue by babaggeii** [quilljs/quill#314]
I want to apply styles onto the editor (border) for when it is focussed and defocussed. I can do this on focus, because I'm focussing manually with: `quill.focus()` and can add the style at the same time, but how would I access the defocus state? The class on the editor doesn't change, so I can't access it.

**Comment by brettimus** [comment]
you can use the `selection-change` event. your handler takes a single parameter, `range`, and if `range` is null, it means focus is not on the editor. 

Here it is in [the docs](http://quilljs.com/docs/events/#selection-change).

**Comment by babaggeii** [comment]
Ah thanks, sorry - missed that.

**Comment by brettimus** [comment]
no problem!
