### ISSUE TITLE
Problem rendering toolbar / header buttons

### ISSUE THREAD

**Issue by oricis** [quilljs/quill#3141]
**Buttons to apply *headers* are not rendering ok**, i only can see the first button (usually).
It's a render problem, all they are running.

Testing on **Chromium** 84.0.4147.105 (Build oficial) Built on Ubuntu 18.04 (64 bits)
Testing loading in a local HTML file CSS / JS version 1.3.6.
Testing on [https://quilljs.com/playground/](https://quilljs.com/playground/ )

Change the original line:

    [{ header: [1, 2, false] }],

to set he toolbar / headers by one of them:

    [{ header: 1}, { header: 2}], // this line renders OK
    [{ header: 1}, { header: 2}, { header: 3}], // this line renders button first and second
    [{ header: 1}, { header: 3}], // this line only renders the first button
    [{ header: 2}, { header: 3}], // this line only renders the first button

For example:

```
var quill = new Quill('#editor-container', {
  modules: {
    toolbar: [
      [{ header: 1}, { header: 2}, { header: 3}],
      ['bold', 'italic', 'underline'],
      ['image', 'code-block']
    ]
  },
  placeholder: 'Compose an epic...',
  theme: 'snow'  // or 'bubble'
});
```

**Comment by oricis** [comment]
Same problem loading https://cdn.quilljs.com/1.3.7/quill.js

**Comment by kmanadkat** [comment]
For me this is also not working
```js
[{ 'header': 1 }, { 'header': 2 }, { 'header': false }],
```

I want to show Paragraph button separately
