### ISSUE TITLE
New line on Android hides keyboard, with new Chromium(85.0+)

### ISSUE THREAD

**Issue by albertaleksieiev** [quilljs/quill#3153]
Quill with brand new chrome(85+) on Android hides keybord when new line is pressed.

**Steps for Reproduction**

1. Visit https://quilljs.com/
2. Type Some Text
3. Press enter

**Expected behavior**:
Keybord is shown.
**Actual behavior**:
Keyboard is hided.
**Platforms**:
Android, Chrome 85.0.4183.81

**Version**:
1.3.6

**Comment by albertaleksieiev** [comment]
Issue some where around `setNativeRange` method. I commented this method and keybord do not hides, looks like issue with selection.

**Comment by albertaleksieiev** [comment]
`selection.removeAllRanges()` hides keyboard

**Comment by SalilMittal** [comment]
Hi, could you please elaborate how you resolved the issue.

**Comment by albertaleksieiev** [comment]
@SalilMittal do not resolve it yet.

**Comment by albertaleksieiev** [comment]
Found a first solution, you need to call `quill.focus()` after `selection.removeAllRanges()`;

```
 setNativeRange(startNode, startOffset, endNode = startNode, endOffset = startOffset, force = false) {
...

 let range = document.createRange();	       
        range.setStart(startNode, startOffset);	
        range.setEnd(endNode, endOffset)

function runWithTimeout(selection, range) {
            setTimeout(function() {
              selection.removeAllRanges();
              window.quill.focus(); // Shitty chrome 85++ require this kostyl
              selection.addRange(range);
            }, 0)
          }
          runWithTimeout(selection, range)
```
core/selection.js

more - https://github.com/readdle/quill/commit/46e81cace8a60e0b9311e92f5448d38a3306a098#diff-ae237139107d046c67dc8622d25bace9R321

**Comment by albertaleksieiev** [comment]
@SalilMittal

**Comment by sabin10** [comment]
@albertaleksieiev doesn't work for me

**Comment by predictron-cloud** [comment]
I have the same issue. Is it a new bug, which have been introduced with latest version of Chrome or existing bug of quilljs?

**Comment by SalilMittal** [comment]
> I have the same issue. Is it a new bug, which have been introduced with latest version of Chrome or existing bug of quilljs?

most probably because of changes in chrome 85
