### ISSUE TITLE
[Android] Enter key collapsing keyboard instead of going to next line

### ISSUE THREAD

**Issue by cmd05** [quilljs/quill#3154]
I have a simple quill editor and when i press enter on android it collapses the keyboard instead of going to the new line
**Steps for Reproduction**

1. Visit quilljs.com/playground on android
2. Press enter to go to the next line

**Expected behavior**:
Cursor goes to next line.

**Actual behavior**:
Keyboard collapses each time you press enter

**Platforms**:

Chrome 85.0.4183.83

**Version**:
1.3.6

**Comment by albertaleksieiev** [comment]
https://github.com/quilljs/quill/issues/3153

**Comment by albertaleksieiev** [comment]
Have the similar issue
