### ISSUE TITLE
Quill does not follow the Principle of Least Surprise (it adds too much gap for newlines)

### ISSUE THREAD

**Issue by HoomanBahreini** [quilljs/quill#3161]
I have seen [this issue ](https://github.com/quilljs/quill/issues/1074) which is closed.

Quill adds `<p>` for newline (pressing Enter once) and it adds `<p><br></p>` for 2 newlines (pressing Enter two times).

By default, browsers add `1em` margin on **top** and `1em` margin at the **bottom** of `<p>` elements. This means when typing, user is under the impression that by pressing enter he would simply go to the newline but when he views the generated html (outside of Quill editor) there is actually `2em` gap between the 2 lines (just because user has pressed Enter once).

There is a UI principle called [Principle of Least Surprise ](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)(which I am sure you are aware of). The principle states that a good UI should behave as user expects it... in other words, users should be able to predict the behavior of software... if they can then they feel in control... it they can't they feel frustrated.

By adding `2em` gap for a newline, Quill is NOT following this principle. Quill does not provide any functionality to go to newline without adding `2em` of unwanted gap between lines.

**Comment by navaidalam** [comment]
I am trying to create an email editor using Quill. When I type in an email as I would do in any email editor, I expect that what I see there would be matched by the HTML produced. However, that is not the case and what reaches the email recipient displays differently with far more gap between lines than what most email editors add. I believe this breaks the claimed WYSIWYG feature.
![quill-line-break-issue](https://user-images.githubusercontent.com/9530135/94347166-a2e0f400-004f-11eb-906d-bf723a631945.png)

**Comment by rishpandey** [comment]
This has to do with #1328.

**Comment by hawkerm** [comment]
I was surprised by this... 😟 Was excited when finding Quill, but now weary as needing to translate from HTML and worried about extraneous markup and doing workarounds when round-trip is involved with storage.
