### ISSUE TITLE
403 on CDN

### ISSUE THREAD

**Issue by SqweeeRyan** [quilljs/quill#3164]
We use the CDN on our site to reference QuillJS, but just this morning we started getting a 403 Forbidden on the following CDN URL:

https://cdn.quilljs.com/1.3.6/quill.min.js

**Comment by dodb** [comment]
This is still happening.

**Comment by Gameghostify** [comment]
Same for me, can't access the CDN anymore

**Comment by zstra7** [comment]
Same issue here.

**Comment by saralamuralikrishna** [comment]
same issue here.

**Comment by misiektg86** [comment]
Was about to report this... Same here

**Comment by misiektg86** [comment]
Seems to work now

**Comment by softspoiler** [comment]
Even the quilljs official site doesn't have access https://i.imgur.com/KfKm9y6.png

**Comment by prarimi** [comment]
I have this problem only with the older version this https://cdn.quilljs.com/1.2.0/quill.js

**Comment by yootaebong** [comment]
same issue here. 

i have this problem any version.

**Comment by HimanshuChugh2** [comment]
I have spend lot of time from morning on this, finally found this issue, why is this happening, how will it be solved, any idea guys?

**Comment by dodb** [comment]
This project seems to be abandoned. For now, I downloaded the js and css files and hosted on our own servers. Did a quick hot-fix over the weekend to change the links in production. 
Long term, without further development and support, will be looking for something else I guess...

**Comment by HimanshuChugh2** [comment]
So quilljs is dead?

**Comment by yootaebong** [comment]
I solved this problem.

I hope it helps other people.

1. Download Quill Project :  https://github.com/quilljs/quill/releases
2. Proceed with npm install in the project.
3. Similarly npm run build
4. Then you will be able to find it. The quill.js file inside the dist folder
5. Use it

**Comment by zenangrl** [comment]
<link type="text/css" href="node_modules/quill/dist/quill.snow.css">
<script type="text/javascript" src="node_modules/quill/dist/quill.js"></script>
<link type="text/css" href="node_modules/quill/dist/quill.core.css">
I attached all link as above but get error for quill.js not found.

GET http://localhost:8100/node_modules/quill/dist/quill.js net::ERR_ABORTED 404 (Not Found)

**Comment by yootaebong** [comment]
@zenangrl Did you build?

**Comment by zenangrl** [comment]
@yootaebong  yes. I did build.

**Comment by yootaebong** [comment]
@zenangrl 

The best way to do this is to open the folder path yourself and check it out.

First, check if there is a dist folder

Check if the file exists in it

**Comment by kateboyko** [comment]
May be not the best solution, but I didn't have time, so I used an archived version https://web.archive.org/web/20200729093210/https://cdn.quilljs.com/1.3.7/quill.snow.css. 
I manually downloaded it and linked to my project.

**Comment by HimanshuChugh2** [comment]
Can anyone tell me how can i link Quilljs manually in my java spring boot project in eclipse, do i have to add a maven dependency or anything else?
please help

**Comment by codeallthethingz** [comment]
The jsdeliver version: https://www.jsdelivr.com/package/npm/quill

**Comment by zenangrl** [comment]
CDN is working well now

**Comment by HimanshuChugh2** [comment]
Its still not working.

**Comment by SqweeeRyan** [comment]
It's working for me now (https://cdn.quilljs.com/1.3.6/quill.min.js) - however I have already moved the file to be hosted within my own CDN, so I'm no longer using this one.

**Comment by Amit-Dagar** [comment]
![image](https://user-images.githubusercontent.com/32691543/92562595-da9c1d80-f293-11ea-8ea7-b4afe4f25a26.png)
<body>
  
  <script src="https://cdn.quilljs.com/1.2.0/quill.js"></script>
</body>

**Comment by HimanshuChugh2** [comment]
The problem lies in the version 1.3.6(  `<script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>` ) after changing it to   `<script src="https://cdn.quilljs.com/1.3.5/quill.min.js"></script> `
it works.
not sure as to why this is happening, if anyone knows please let us know

**Comment by ibarrajo** [comment]
There's other CDNs available, we're moving over to cloudflare's

https://cdnjs.com/libraries/quill/1.3.6

**Comment by HimanshuChugh2** [comment]
is there a way to get updated from Quill via mail or other ?a

> There's other CDNs available, we're moving over to cloudflare's
> 
> https://cdnjs.com/libraries/quill/1.3.6
> 
> ```
> <script src="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.min.js" integrity="sha512-3OiXhM6bvRST0JlpR++aDMUh4n9QETHJdKEZ4U2gpDtyS8ZZF3h0072MaPDbjg/Q9W8Ki7G36Ay8I3xoUosPFg==" crossorigin="anonymous"></script>
> ```

is there a way to get updated from QuillJs about QuillJs via mail or other ?

**Comment by leehaber** [comment]
Guys, I was experiencing the same issue. I found that when I used my browser in incognito mode or as a guest, the issue went away.

I suspect what is happening is that the server with QuillJS is flagging your account because Google may have flagged it as having some security issue which is causing the Forbidden 403.

I'm resetting all my Google passwords to see if putting things in good standing will resolve the issue.

**Comment by groupboard** [comment]
No, google isn't going to give a 403 error due to your passwords. The problem was already fixed, so likely your chrome had just cached the 403 error and using incognito bypassed the cache.

**Comment by leilinen** [comment]
the cdn is available. `https://www.bootcdn.cn/quill/ `
for example 
`<link href="https://cdn.bootcdn.net/ajax/libs/quill/1.3.6/quill.snow.css" rel="stylesheet">`

**Comment by silverbackdan** [comment]
This issue appears to be fixed. The issue could be closed.
