### ISSUE TITLE
Icon for code and code-block is the same

### ISSUE THREAD

**Issue by mkozachok** [quilljs/quill#3165]
I add 'code' and 'code-block'  for the toolbar. In toolbar shows two the same icon, but the action is different.

**Steps for Reproduction**
1. Visit https://codepen.io/mkozachok/pen/XWdVRXP
2. See the same icons

**Expected behavior**:
Icons should be different. 

**Actual behavior**:
Icons should the same. 

**Version**:
latest

**Comment by OssiPesonen** [comment]
Someone suggested a hack such as this to fix it:

```js
const icons = Quill.import('ui/icons');

icons['code-block'] = '<svg viewbox="0 -2 15 18">\n' + '\t<polyline class="ql-even ql-stroke" points="2.48 2.48 1 3.96 2.48 5.45"/>\n' + '\t<polyline class="ql-even ql-stroke" points="8.41 2.48 9.9 3.96 8.41 5.45"/>\n' + '\t<line class="ql-stroke" x1="6.19" y1="1" x2="4.71" y2="6.93"/>\n' + '\t<polyline class="ql-stroke" points="12.84 3 14 3 14 13 2 13 2 8.43"/>\n' + '</svg>';
```

**Comment by amandeepmicro** [comment]
> Someone suggested a hack such as this to fix it:
> 
> ```js
> const icons = Quill.import('ui/icons');
> icons['code-block'] = '<svg viewbox="0 -2 15 18">\n' + '\t<polyline class="ql-even ql-stroke" points="2.48 2.48 1 3.96 2.48 5.45"/>\n' + '\t<polyline class="ql-even ql-stroke" points="8.41 2.48 9.9 3.96 8.41 5.45"/>\n' + '\t<line class="ql-stroke" x1="6.19" y1="1" x2="4.71" y2="6.93"/>\n' + '\t<polyline class="ql-stroke" points="12.84 3 14 3 14 13 2 13 2 8.43"/>\n' + '</svg>';
> ```
> 
> But this should be fixed in the source.

Indeed it fixed my issue , thanks for sharing.☺

**Comment by benbro** [comment]
Related https://github.com/quilljs/quill/pull/3917
