### ISSUE TITLE
Extra new line between lines when pasting

### ISSUE THREAD

**Issue by makeros** [quilljs/quill#317]
Hello.
I think that there is a bug on Android native web browser.
Tested on Android 4.2.2 and 4.4.2.

Steps to reproduce:
1. write two lines of text
2. copy those lines 
3. paste - there will be an extra line between the lines

**Comment by jhchen** [comment]
This looks like it has been fixed in the 1.0 [beta](http://beta.quilljs.com/) release on the latest Android 6.
