### ISSUE TITLE
Does quill editor supports table??

### ISSUE THREAD

**Issue by codingmania321** [quilljs/quill#3173]
I'm using https://codepen.io/quill/pen/QxypzX  this demo...but I'm unable to develop it in angular project 

I'm using quill version 1.3.7 and ngx-quill version 12.0.1

**Comment by rockwotj** [comment]
Quill version 2.x does

**Comment by codingmania321** [comment]
But quill 2.0 doesn't support data binding

**Comment by dmboucher** [comment]
Is there any documentation showing how to work with Quill tables?  I'm struggling to get this to work.  I understand it's still in dev, but even a rudimentary implementation would likely work for my needs.  Thoughts?

**Comment by Pascal-ZIM** [comment]
I am also trying to use Quill.js with Tables. I created a Newsleter Builder and trying to edit the text with Quill but it seems a little bit buggy with them. 

https://github.com/quilljs/quill/issues/3266

**Comment by harleenarora** [comment]
@codingmania321 can you find a any solution?

**Comment by famcodings** [comment]
Hi, any update on this? does quill support table now?

**Comment by mmanishh** [comment]
Quill 2.0 which is still in development supports table, there are several modules developed for quill table including : [quill-better-table](https://github.com/soccerloway/quill-better-table) and [quill-table-ui](https://github.com/volser/quill-table-ui) . Unfortunately quill doesnt support table in its core. It works based on module system. I would say if you want sth which is comprephensive [jodit-editor](https://xdsoft.net/) might be good option

**Comment by jmsuos-digizijn** [comment]
Seems like devs are never going to release 2.0 or they're the same devs that develop Teamspeak 5 xD

**Comment by benbro** [comment]
Duplicate https://github.com/quilljs/quill/issues/117

**Comment by Zahid-Alee** [comment]
Any update on that ?

**Comment by vivek3216** [comment]
Facing an issue with quill-table-better, added a 3*3 table and made first row as header now i am not able to add row from 3rd row
