### ISSUE TITLE
Delta does not contain Fontsize and Fontfamily of pasted text?

### ISSUE THREAD

**Issue by Wizzel1** [quilljs/quill#3177]
I want to read the properties of a pasted text but I only get attributes like "bold".
I also noticed that the font of the copied text doesnt get applied when pasted in an editor. So how would I set up the editor to read out the pasted font-family, font-size and so on?

**Comment by bogoroh** [comment]
Have you figured this out @Wizzel1 ?

**Comment by Wizzel1** [comment]
No, but I haven't looked into it in further detail
