### ISSUE TITLE
upgrade 

### ISSUE THREAD

**Issue by songyajie** [quilljs/quill#3181]
When will you upgrade to 2.x stable version

**Comment by farhanianz** [comment]
I would also like to know the roadmap & the features that are going to be in v2. An expected release schedule would be a pleasure. 

Thanks to the dev & contributors.

**Comment by benbro** [comment]
[v2.0.0-beta.1](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.1) was just released.
