### ISSUE TITLE
Quill being flagged by veracode...

### ISSUE THREAD

**Issue by kasparov112000** [quilljs/quill#3182]
Trying to use quill in my company, it was rejected because veracode claims it has vunerabilities?  Is that the case? any ideas?

**Comment by lilsnow** [comment]
I am experiencing the same issue, looks like it was brought up before in #2768 but was ignored?

<img width="757" alt="quill1" src="https://user-images.githubusercontent.com/85036/106036267-16008280-60a3-11eb-9a01-aa031d47d48a.png">
<img width="757" alt="quill2" src="https://user-images.githubusercontent.com/85036/106036294-24e73500-60a3-11eb-87dc-cd915ef9ecf4.png">
