### ISSUE TITLE
The format of the line is lost when using the backspace key to delete the contents of the line to the beginning

### ISSUE THREAD

**Issue by elmeet** [quilljs/quill#3183]
Thanks for all the amazing work on quill. I think I found a possible bug.

This seems like a bug since it's not consistent with industry standard behavior.
When you use backspace to delete the line content, the line format is lost.

**Steps for Reproduction**
Go to quill homepage https://quilljs.com/
`Ctrl + a` or `Command + a` select all,  select a font or color.
Use the backspace key to delete the contents of one line to the beginning.
Input text, the previous font format is lost.
![image](https://user-images.githubusercontent.com/31975448/93988171-fdaded80-fdba-11ea-8a44-3468f0389c8d.png)

**Expected behavior:**
I expect the lines format to be retained like google docs, apple pages, or ms word.

**Actual behavior:**
The text formatting is lost when you backspace an entire line

**Platforms:**
Chrome on Mac, Windows

**Version: 1.3.7**

**Comment by sahilsakhiya11** [comment]
I am having the same issue, did you find any solution for it? @elmeet

**Comment by elmeet** [comment]
> I am having the same issue, did you find any solution for it? @elmeet

@sahilsakhiya11 No, I finally used another rich text editor.

**Comment by marcorohn** [comment]
> 
> @sahilsakhiya11 No, I finally used another rich text editor.

@elmeet could you tell which one?

**Comment by elmeet** [comment]
> @elmeet could you tell which one?

@marcorohn [https://github.com/ueberdosis/tiptap](https://github.com/ueberdosis/tiptap)
