### ISSUE TITLE
Quill distorts link urls when scheme is omitted

### ISSUE THREAD

**Issue by heyalexchoi** [quilljs/quill#3188]
**Steps for Reproduction**

1. Create a link with a url without a scheme, eg `www.google.com`
2. Click the link
3. Note the link is not to `https://www.google.com` as expected. In my development cases, the formed URL is an append on my localhost `localhost:8000/www.google.com`.

**Expected behavior**:
The link does not prepend into the given url. `www.google.com` should link to `www.google.com`. Or assume `https` or `http` and prepend that scheme, if needed. Or provide a hook for the developer to add scheme injecting logic.

**Actual behavior**:
prepends what seems to be current page address into url.
link url `www.google.com` becomes `localhost:8000/www.google.com` in my local environment.

**Platforms**:

chrome, macos, but probably all.

**Version**:

`1.3.7`

See also:
https://github.com/quilljs/quill/issues/2505
https://github.com/zenoamaro/react-quill/issues/529

**Comment by heyalexchoi** [comment]
my bad, just found the quill link sanitize function

for anyone else with this issue, you can prepend schemes like this:
```
import Quill from 'quill'
const Link = Quill.import('formats/link');
Link.sanitize = function(url) {
  // quill by default creates relative links if scheme is missing.
  if (!url.startsWith('http://') && !url.startsWith('https://')) {
    return `http://${url}`
  }
  return url;
}
```

**Comment by gtbaron** [comment]
The example in the previous comment worked perfectly for me; however, I had to change the import in my Angular component to `import * as Quill from 'quill';`

I put the rest of the code in my `ngOnInit()` function and it worked perfectly.
