### ISSUE TITLE
How to remove extra padding when sending the content via email

### ISSUE THREAD

**Issue by asiehmokarian** [quilljs/quill#3190]
@maximeozenne I think the issue is Quill's editor uses `<p>` tags to be more semantic but by default `<p>` tags have margin. Quill gets rid of this with css but if you display the same HTML outside of Quill then you will get the margin as that is the browser default. A couple ways to solve this are:

- Add the margin: 0 rule to `<p>` in your application.
- Add a the .ql-editor class to the container you are using to render Quill contents so its CSS will apply to it.

> You can't nest block level element within block level elements in quill.js, it's one of its biggest gotchas, effects most people that try to extend it.

I acknowledge documentation could be better on how to do this but it is not true Quill does not have this capability. Lists which nest two block level elements `<ul>` and `<li>` are a counterexample that works perfectly well in Quill.

_Originally posted by @jhchen in https://github.com/quilljs/quill/issues/1631#issuecomment-320782792_

**Comment by asiehmokarian** [comment]
Would you please advise how can solve this issue when passing the content through another app where we cannot adjust styling? For example getting the quill.root.innerHTML and sending it via an email, what I get as the email content is not same as what I see in the editor.

**Comment by oojacoboo** [comment]
It's because the default stylesheet sets margin to zero for every element and your email client is using more normal defaults.  This is a silly mistake in this lib.
