### ISSUE TITLE
WYSIWYG Markdown support

### ISSUE THREAD

**Issue by LifeIsStrange** [quilljs/quill#3192]
Next generation editors allow WYSIWYG Markdown support such as slate and Tiptap.

Explanation of this awesome feature:
Markdown as of today is underused as the changes it will do are not visible while editing but this doesn't has to be the case:

As you can see in this demo[0], just outline a word with * and it instantaneously become italic. 
What's more: if you start a new line with # it instantaneously get the right size. 
You want an h2? Just put 2 ##
It's just plain instantaneous and therefore user friendly and productive Markdown. 

[0] https://tiptap.dev

The WYSIWYG that quill already provide is *complementary* and is quicker to access sometimes and sometimes isn't, especially for doing partial selections, double clicking repeatedly and so much mouse movements "break" the train of thoughts of the writing process, I think this point is important.
What do you think? To me this is the future and is implemented through prosemirror
https://prosemirror.net (but doesn't necessarily has to be)

Also there is a market opportunity here, since as of today there are no WYSIWYG Markdown editors available for Angular (slate being for react and Tiptap for Vue) and since Quill has a great support of Angular, you could adress that market.

**Comment by david816** [comment]
### **拉开了距离**

**Comment by fyisa** [comment]
- sdfs
- sdfsd

- [x] sdfsadf

**Comment by bowling00** [comment]
[Slab](https://slab.com/) support it, but quill doesn't support it. It's kind of weird. Can you take a look at this question? thank you. @luin
