### ISSUE TITLE
Display generated HTML outside the editor

### ISSUE THREAD

**Issue by salivanas** [quilljs/quill#3193]
I've been searching for two days but cannot find a reasonable way to display HTML generated by this editor outside its context. Or it just isn't documented anywhere.

Simply, in one part of my application I use this editor to create content and in another part I want to display that content without any editing capabilities (just like all the CMSes work...).

The editor outputs HTML, but it is styled with editor-specific CSS classes that are not available outside the editor's context. How can I properly display the HTML with correct styling, then?

The most reasonable way I've found is a hack described here https://stackoverflow.com/a/58669661/2883597.

I believe I am missing something here... Isn't editors meant for creation of content that is later displayed somewhere? What is the point of an editor which can only create and edit content but that content has no proper way to be displayed later?

**Comment by McGiogen** [comment]
I think an editor should create the html and not the style, when possible. This way is possible to render the code in any website: the structure of the text will always be the same but the style will always be that of the site on which it is displayed. Html without Css is more portable and flexible.

**Comment by Confident-Shial** [comment]
Facing the same issue.

@McGiogen Doesn't that kind of ruin the whole purpose of WYSIWYG editor? If I am not able to see the content with styling outside the editor that I am seeing inside the editor, then I am not getting what I am seeing.

For example, my use case is to allow users to use quill's editor to create blogs that are displayed on a different part of the website. For someone using the editor, they want to get the same formatting that they used on the editor, because they have no knowledge of what's happening inside quill. But if that user creates some amazing artistic blog that is not formatted outside the editor the same way they saw on editor, they are literally not getting what they are seeing.

**Comment by rokasaitenta** [comment]
> Facing the same issue.
> 
> @McGiogen Doesn't that kind of ruin the whole purpose of WYSIWYG editor? If I am not able to see the content with styling outside the editor that I am seeing inside the editor, then I am not getting what I am seeing.
> 
> For example, my use case is to allow users to use quill's editor to create blogs that are displayed on a different part of the website. For someone using the editor, they want to get the same formatting that they used on the editor, because they have no knowledge of what's happening inside quill. But if that user creates some amazing artistic blog that is not formatted outside the editor the same way they saw on editor, they are literally not getting what they are seeing.

Exactly... Imagine creating a Word document with all the powerful formatting the editor provides but only being able to print plain text...

**Comment by McGiogen** [comment]
It is my fault, I'm sorry. I wrote with my use case in mind: we have an internal team consisting of article authors and about 10 different websites in which we must render their contents (the same article could be rendered in one or more websites). We need this feature because different writers must realize similar outputs. Any website has it's own theme (font family, size, colors, etc.) so I need to save only html to have a consistent user experience browsing websites.

We have different needs.

Pheraps the definition "WYSIWYG editor" is wrong. Quill is often referred to as a "Rich Text Editor".

**Comment by kokosky93** [comment]
Have you guys found any solution for that?

**Comment by dmrickey** [comment]
Inquiring minds want to know

**Comment by briantuju** [comment]
A solution to this would be highly appreciated 😄

**Comment by m-kolodziej** [comment]
I was lazy and basically included `//cdn.quilljs.com/1.3.7/quill.core.css` on pages where I needed content to be formatted, plus I had to set the `ql-editor` class on the wrapping tag.

This has a negative effect of including some unused styles (like `ql-container`), but I didn't care that much. To avoid this, you can copy & paste only the necessary styles from `quill.core.css` into your own stylesheet.

**Comment by Joffey** [comment]
I saved the delta created by quill editor in the database and use the `quill-delta-to-html` npm package to convert quill delta to html for display.

**Comment by vkment** [comment]
This works, at least since now:

- model definition like:
```
class Post(models.Model):
    title = models.CharField(max_length=200)
    body = QuillField()`

```
- related template html file:
```
<body>
    <h1 style="text-align: center;"><u>{{info.title}}</u></h1>
    {{info.body.html | safe}}
    {% endfor %}
</body>
```

Sure, that differing CSS will influence the result. 

I have taken it from this [tutorial ](https://pythonguides.com/quill-editor-in-django/)

**Comment by dmrickey** [comment]
I don't understand how **_still_** there isn't a style sheet provided for the generated HTML so that the output looks like the input

**Comment by ChrisMiami** [comment]
I came to essentially file this same bug.  There doesn't appear to be any way to get the content of the editor OUT of the editor. I want to offer a way for users to see/modify correspondence, but the whole idea of that is to SEND the correspondence, not a JSON-formatted Delta object.  I know that in the "compared with others" page, you mention that TinyMCE and CKEditor are better to use if you want the innerHTML, but gosh, Quill just seems so much cooler...  It should do both.

**Comment by 3h-coder** [comment]
Here's the solution that I found.
---
1. First import the quill css theme stylesheet of your choice. Officially, quill supports the snow and bubble theme that you can directly get from [here](https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.bubble.css) and [here](https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.snow.css)
2. In your container, render the html content and set its class name to "ql-editor", this will apply the same styling as the one you see in the editor.

In your code it will look like this
1. Import
`
import "react-quill/dist/quill.snow.css"; // replace this if you're not using react
`
2. Dangerously render inner html
`
<divclassName="ql-editor" dangerouslySetInnerHTML={{ __html: yourQuillInnerHtml }} />
`

**Comment by ahmadabdulnasir** [comment]
I am using Next.js, on the Editor everything works ok, but displaying it to the User with:
`<div className="ql-editor" dangerouslySetInnerHTML={{ __html: yourQuillInnerHtml }} />
`
remove certain styles like Bullets, numering etc. I have tried multiple suggestion but nothing seems to work, any idea why?

**Comment by dmrickey** [comment]
> I am using Next.js, on the Editor everything works ok, but displaying it to the User with: `<div className="ql-editor" dangerouslySetInnerHTML={{ __html: yourQuillInnerHtml }} /> ` remove certain styles like Bullets, numering etc. I have tried multiple suggestion but nothing seems to work, any idea why?

Sounds like you need to open a new issue, not post a random question in this unrelated issue

**Comment by vukovicluka** [comment]
@ahmadabdulnasir check this out: https://stackoverflow.com/a/78692316/16994268. I also used Next.js.

**Comment by pascal-tech1** [comment]
i also ran into this same problem with quill , i fixed it by following this steps

1. Import the exact Quill CSS that you are using for your editor into the component you want to render the quill content. In my case, I’m using the Snow theme.
       `import "quill/dist/quill.snow.css";`

2.  render your quill content just like this
      `<div
                className=" ql-editor "
                dangerouslySetInnerHTML={{
                  __html: yourQuillContentHere
                }}
              />
            </div>`
      Pay attention to the className I added with ql-editor.

**Comment by Maquinours** [comment]
> I am using Next.js, on the Editor everything works ok, but displaying it to the User with: `<div className="ql-editor" dangerouslySetInnerHTML={{ __html: yourQuillInnerHtml }} /> ` remove certain styles like Bullets, numering etc. I have tried multiple suggestion but nothing seems to work, any idea why?

The problem is that there is a span with classname = "ql-ui" that is doing the job for bullets and numering. This span is not exported when using getSemanticHTML().

**Comment by dogomayana** [comment]
> I am using Next.js, on the Editor everything works ok, but displaying it to the User with: `<div className="ql-editor" dangerouslySetInnerHTML={{ __html: yourQuillInnerHtml }} /> ` remove certain styles like Bullets, numering etc. I have tried multiple suggestion but nothing seems to work, any idea why?

I use html-react-parser and everything renders fine. https://www.npmjs.com/package/html-react-parser

**Comment by antecuic** [comment]
@pascal-azubike this still doesn't really help. You have to include css wherever you are trying to display html content created by editor.

In my case, I need to store user's input and then, it is possible, that that input will be shown in other website. Now we can't make sure that this website has quill css file imported.

I think the ideal way would be to have style attribute with each element. right?

**Comment by SArshpreetAI** [comment]
Is there any solution for this yet? I am trying to write blogs from a C# blazor app that will be natively displayed in my flutter app. But the html generated using quill is having class names like `ql-ui` which isn't understood by my `flutter_html` package and there is no way I can import the css file in there.

**Comment by antecuic** [comment]
@SArshpreetAI I was working at the time with [Nuxt3](https://nuxt.com/), and my solution was to parse the HTML with [cheerio](https://cheerio.js.org/) on server side.

So before saving html content somewhere, I wrote a logic that will apply needed styles within style attribute and remove the classes.

This function is an example of my solution:

`
const applyQuillIndentation = ($: cheerio.CheerioAPI): void => {
  // Select all elements that contain `ql-indent-` in their class list
  $('[class*="ql-indent-"]').each((_, element) => {
    const el = $(element);
    const attributeClass = el.attr("class");

    if (!attributeClass) return;

    // Match ql-indent-N where N is a number
    const match = attributeClass.match(/ql-indent-(\d+)/);
    if (!match) return;

    const indentLevel = parseInt(match[1], 10);
    const indentSize = indentLevel * 30; // 3em per level

    el.removeAttr("class");

    el.css("padding-left", `${indentSize}px`);
  });
};
`

**Comment by SArshpreetAI** [comment]
@antecuic What you are saying is to write a logic to update tags having `ql-*` classes and write the html alternate to what that class was achieving. That might be difficult and too manual as there are many classes in my case. :C
