### ISSUE TITLE
placeholder didn't disappear when input Chinese after select 'bold' or 'color' formatter

### ISSUE THREAD

**Issue by huajianreno** [quilljs/quill#3196]
Version: 1.3.6
Browser: Google Chrome | 86.0.4240.80 (正式版本) (x86_64)
Operation System: macOS 10.15.4
Screenshot:
![image](https://user-images.githubusercontent.com/25789201/96007650-45331100-0e71-11eb-91b4-e707b9d0d5ff.png)

**Comment by jfu-sfdc** [comment]
We have the same issue on v1.3.7. 
It happens on certain android devices with Android 10 + Chrome 86.

If anyone has workaround, please let me know.
