### ISSUE TITLE
Error: Object didn't support method 'position' in ie

### ISSUE THREAD

**Issue by huajianreno** [quilljs/quill#3198]
Version: 1.3.6
Browser: IE 11
Operation System: Windows 10
Screenshot:
![image](https://user-images.githubusercontent.com/25789201/96202677-663f5300-0f92-11eb-84b9-606b538effc5.png)
![image](https://user-images.githubusercontent.com/25789201/96202688-6ccdca80-0f92-11eb-9cb8-4b07c6e4995d.png)

**Comment by benbro** [comment]
Please test [v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2)
