### ISSUE TITLE
Scroll position jumps when highlighted text begins with an embed

### ISSUE THREAD

**Issue by crsven** [quilljs/quill#3199]
**Steps for Reproduction**

1. Visit https://quilljs.com/playground/
2. Insert an image (this works with any embed)
3. Insert enough text to make sure the input will scroll
3. Select all text
4. Press (on a mac) Option + Shift + Left Arrow repeatedly

**Expected behavior**:
The scroll position does not change (or it only changes once to move to the start of the input).

**Actual behavior**:
Every time the keys are pressed, the scroll position jumps from the start to the end of the input.

**Platforms**:

Include browser, operating system and respective versions
macOS 10.15.7
Chrome  86.0.4240.80

**Version**:
1.3.6 & 1.3.7

**Comment by luin** [comment]
Should be fixed with #3840
