### ISSUE TITLE
How can I find the position of a text?

### ISSUE THREAD

**Issue by jevin** [quilljs/quill#3201]
I am writing a Quill module to replace Twitter links with an embedded tweet. I’m having an issue when it comes to finding the exact position of the tweet URL inside the editor.

I’m doing something like this:
```
quill.getText().indexOf(tweet_url)
```

This works well for the first tweet. But subsequent tweets, not so much. 

It looks like when the editor contains embeds, it’s not reliable to find text using `indexOf`. 

Is there any way to achieve what I’m wanting?

Thanks!

**Comment by SilvaQ** [comment]
@jevin 
 Have you found a better solution? I also have such needs

**Comment by benbro** [comment]
You can either use getText() to work with plaintext or getContents() to work with Delta.
