### ISSUE TITLE
Keybindings not targeting backticks ("`", tilde, back quote, etc) 

### ISSUE THREAD

**Issue by mashuDuek** [quilljs/quill#3204]
Adding a binding to the back-tick (tilde) key does not work. 
Attempted ways: 
1. `quill.keyboard.addBinding({ key: << string literal of back-tick >> }, handler);`
2. `quill.keyboard.addBinding({ key: "acute" }, handler);`
Also tried with the following strings (replacing "acute"): backtick, left quote, open quote, back quote, backquote, tilde
3. Importing the Keyboard module, and checking its keys (was not in there). 
4. Passing in configuration object to `new Quill` that included `modules.keyboard.bindings.custom` pointing to the object with same `key` as above, plus a `handler` key.  

When setting the `key` to be a string literal of back-tick I do NOT get warning: 
```debug.warn('Attempted to add invalid keyboard binding', binding);```
When I attempt any of the other strings mentioned above I get the warning. Warning is found on line 89 in `addBindings()` inside of [/modules/keyboard.js](https://github.com/quilljs/quill/blob/676816a57752cb1fdcefa7b335bc2a035d261e02/modules/keyboard.js).

**Expected**: String literal of back-tick to suffice in targeting the correct key. Expected there to be information on how to target the backquote character somewhere in the docs or as one of the keys in the Keyboard module. 

**Actual**: String literal of back-tick (or any of the 'common' names the character has) does not target the correct key, or any as far as I can tell. Cannot find info on this in the docs, or in the Keyboard module. 

**Versions**: 
Chrome Version: Version 85.0.4183.121 
Quill Version: 1.3.6 (installed with npm)
Node Version: 14.4.0

**Comment by t8rsalad** [comment]
@mashuDuek, did you figure out a way to bind to the back-tick key?

**Comment by mashuDuek** [comment]
Hey @t8rsalad, yes I did, my apologies for not updating this thread. I did this by targeting the Javascript key. 

Here is the way to target the back-tick: 
```js
const keyBinders = {
   backtickBinder: {
      key: 192,
      handler: function(range, context) {
         // in this function I ran logic to add code style, or code-block
      },
   }
}
```

Then, when you instantiate `Quill`: 
```js
const modules = {
  syntax: true,
  keyboard: {
     bindings: keyBinders
   }
};
    
new Quill('#id-of-your-editor', { modules });
```

[This](https://keycode.info/) page can help you identify the Javascript keys to target. 

Hope this helps!

**Comment by t8rsalad** [comment]
Great! Thanks for the quick reply @mashuDuek.
