### ISSUE TITLE
Using Quill for emails

### ISSUE THREAD

**Issue by Gloveny** [quilljs/quill#3210]
I'm really struggling use Quill as it seems so counter intuitive.  
I want to use it for HTML emails but it relies so heavily on classes I don't see how this is possible.  
I think the quill developers are missing the point of what a WYSIWYG editor actually is.  
What’s the point of editing text, saving text is you cant use that text anywhere else other than the editor?
Please someone enlighten me it I've got it wrong but I've just wasted a huge amount of time integrating this piece of "tek" into my boss’s system.  He aint goanna be happy when I tell him it's not fit for purpose.

**Comment by Ahmeed2m** [comment]
@Gloveny
Checkout this comment https://github.com/quilljs/quill/issues/2344#issuecomment-428147796
https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline

**Comment by smohadjer** [comment]
I would recommend using another editor if you need inline styles. Quill is quite buggy when it comes to inline styles and you can find many issues complaining about that. I have decided to use TinyMCE instead which unlike Quill uses inline styles by default.

**Comment by Gloveny** [comment]
Thanks.   Yes seems very counter intuitive.  Which is a shame.

Thanks for replying

Graham

**Comment by cdvillard** [comment]
We're currently using Quill for emails, and have found that the best way to tackle it is by keeping it as simple as possible. Avoid using inline styles and lean more on what's natively available like `<strong>` and `<em>` tags. It's also possible to inline styles from an embedded stylesheet, either using OSS or a service like htmlemail.io.

**Comment by Pascal-ZIM** [comment]
> We're currently using Quill for emails, and have found that the best way to tackle it is by keeping it as simple as possible. Avoid using inline styles and lean more on what's natively available like `<strong>` and `<em>` tags. It's also possible to inline styles from an embedded stylesheet, either using OSS or a service like htmlemail.io.

I am trying to use it on a Newsletter Builder. How you guys use it? I am trying to use Quill as a text editor but It give me some issues. I have created a post here:

https://github.com/quilljs/quill/issues/3266
