### ISSUE TITLE
Why automatically adds a colon??

### ISSUE THREAD

**Issue by Civile** [quilljs/quill#3215]
Some customers tell me that, only using windows, when I insert the "é" symbol (for the first time), the wysiwyg automatically adds the ":" symbol. I can't understand why I find myself in situations like these:

é: ééééééé

Can you please help me to solve this problem? I'm struggling

**Comment by smalos** [comment]
I cannot reproduce it here

**Comment by benbro** [comment]
Please test [v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2)
https://v2.quilljs.com/standalone/full
