### ISSUE TITLE
Allow custom line formats to exclude more than one other format

### ISSUE THREAD

**Issue by TGVarik** [quilljs/quill#322]
In lieu of #111 and #115, and taking a different approach than #148 or #204, we created our own `h1`, `h2`, `h3`, and `blockquote` formats using `.addFormat`. Our use case requires these (as well as `list` and `bullet`, which we can override) to be mutually exclusive line styles. That is, a line should accept only one of `[ 'list', 'bullet', 'h1', 'h2', 'h3', 'blockquote' ]` at a time. Unfortunately, `Line.format()` expects `Format.config.exclude` to be a single format name as a string:

```coffeescript
editor.addFormat
  h1:
    tag: 'H1'
    prepare: 'heading'
    type: 'line' # Format.types.LINE doesn't appear to be conveniently exposed
    exclude: 'h2' # But what about h3, blockquote, bullet, and list?
```

If, instead, `Format.config.exclude` could be an array of format names, with each being removed as required before applying the custom style, our custom format approach would work just fine:

```coffeescript
editor.addFormat
  h1:
    tag: 'H1'
    prepare: 'heading'
    type: 'line'
    exclude: [ 'h2', 'h3', 'blockquote', 'bullet', 'list' ]
```

**Comment by jhchen** [comment]
Quill 1.0 no longer has addFormat in favor of [Parchment](https://github.com/quilljs/parchment) which allows much more customization. Headings itself is implemented in core 1.0 but in general you can exclude other formats by inheriting and overwriting a [Blot](https://github.com/quilljs/parchment)'s format or formatAt functions.
