### ISSUE TITLE
Quill not working with flexbox elements

### ISSUE THREAD

**Issue by NervisWreck** [quilljs/quill#3227]
**Scenario**
Two flexbox elements sitting side by side, inside a container, with quill in the left element. Quill having bounds set to the left element, not document.body and overflow-wrap added to the .ql-editor class.

**Issue**
As quill reaches the right most bound of the editor it breaks to the next line, but still continually pushes the right flexbox element, shrinking it until it is impossible to shrink it anymore.

You can see this in action with this [JSFiddle](https://jsfiddle.net/x0h7j91d/)

**Desired functionality**
To have quill confined to the bounds of the flexbox element which contains it, without expanding the element and **WITHOUT** the need to specify a width in order to support responsive designs.

**Comment by 5ergiu** [comment]
Just set "flex-shrink: 0" to the container that doesn't have quill.

**Comment by benbro** [comment]
Answered.
