### ISSUE TITLE
On clicking on toolbaar options call blur event which is not an idle case scenario.

### ISSUE THREAD

**Issue by hussainsaify17** [quilljs/quill#3238]
When we try to select a tool which have multiple options to select from such as font family, font color, font background color etc causes blur event which is not an idle case scenario.

**Steps for Reproduction**

1. Visit https://codepen.io/DmitrySkripkin/pen/eeXpZB?editors=0010
2. Click inside editor 
3. Then click on normal dropdown 

here you'll see blur event is logged in console which is not appropriate as user is in the middle of formatting and blur event has been called.

**Expected behavior**:

Blur event should only be called when the focus from the editor has been lost

**Actual behavior**:

Blur event is getting fired in case of selecting of tool which have multiple options.

**Platforms**:

Chrome browser

Include browser, operating system and respective versions

**Version**: 1.3.4

Run `Quill.version` to find out

**Comment by sudofox** [comment]
Quill seems to be abandoned, but I built an application around it so I'm kinda stuck right now. Did you ever resolve this?
