### ISSUE TITLE
<pre> Tag Problems

### ISSUE THREAD

**Issue by rumanoid** [quilljs/quill#324]
Hi,

If I edit text which is inside `<pre>` tags, it shows up all scrambled in the editor (saves just fine), Can it be changed, so it detects text between pre tags and automatically shows it right in the editor?

**Comment by jhchen** [comment]
How are `<pre>` tags getting into Quill? They should be converted to `<div>`s. Or do you mean you copied some text which contain `<pre>` tags and paste that into Quill?

**Comment by rumanoid** [comment]
The content of the Quill editor comes from a database (which contains older code) sometimes using pre tags. It would be nice if Quill could parse them right (tabs, spacing and line breaks)

**Comment by jhchen** [comment]
This may be addressed as a side effect of supporting code (which may use `<pre>` tags) but sanitizing arbitrary HTML input is outside Quill's current scope.

**Comment by pvahia** [comment]
> How are `<pre>` tags getting into Quill? They should be converted to `<div>`s. Or do you mean you copied some text which contain `<pre>` tags and paste that into Quill?

@jhchen  Can I prevent quill from converting `<pre>` to `<div>`
