### ISSUE TITLE
Customize delta -> html conversion

### ISSUE THREAD

**Issue by webdeb** [quilljs/quill#3241]
Hello, just started to experiment with quilljs. Looks interesting so far. I like the delta format, as it lets me represent the content as pure data. What I am missing so far is the ability to customize the rendering of the deltas in the editor itself.
For example the **italic** format puts "em" tags around the selection. How could I change it to something different, lets say I want to wrap in a "span" with the class **italic**?

**Comment by ncovercash** [comment]
You'd need to extend and override the classes relating to each item.

**Comment by sri8484** [comment]
> Hello, just started to experiment with quilljs. Looks interesting so far. I like the delta format, as it lets me represent the content as pure data. What I am missing so far is the ability to customize the rendering of the deltas in the editor itself. For example the **italic** format puts "em" tags around the selection. How could I change it to something different, lets say I want to wrap in a "span" with the class **italic**?

Hi Webdeb,

Did you get any success with your requirement? Please let me know..

**Comment by webdeb** [comment]
> Hi Webdeb,
> 
> Did you get any success with your requirement? Please let me know..

Hi, after some deeper considarations I've decided to use **react draft** At that time (1.5y ago) it was the best option for me.
