### ISSUE TITLE
Copy / Pasting Lists from Quill into Google Docs, etc Does not Render the Bullets / Numbers

### ISSUE THREAD

**Issue by cancan101** [quilljs/quill#3242]
Copy and pasting:
![image](https://user-images.githubusercontent.com/51059/100912556-99846580-349e-11eb-8dd8-5a4f1987d78f.png)
into Google Docs yields:
![image](https://user-images.githubusercontent.com/51059/100912571-a012dd00-349e-11eb-9eff-852c2312df63.png)
where those are lists but the bullets / numbers are not rendering.
This seems to be due to Quill using:
https://github.com/quilljs/quill/blob/e9f628b5562e78126291bb25f63d0dfc3f6c6f86/assets/core.styl#L69
and
https://github.com/quilljs/quill/blob/e9f628b5562e78126291bb25f63d0dfc3f6c6f86/assets/core.styl#L85-L86
to accomplish rendering of the bullets.

Is there any work around to get the copy / paste to work and render the bullets?

**Comment by qeireal** [comment]
@cancan101 hi, did you find the workaround?

**Comment by BryceV** [comment]
Running into the same problem. There are several formatting issues (sub bullets, bold text) when I try to copy text out of the quill editor into google docs. Looking for a module solution if anyone has one.

**Comment by Eraldo** [comment]
Same same. Also running into this. Have not found a solution yet.

**Comment by prakash-seppi** [comment]
Any solutions ? 
I am facing the same issue.
