### ISSUE TITLE
Cannot insert link by insertEmbed API

### ISSUE THREAD

**Issue by wuliupo** [quilljs/quill#3243]
I cannot insert link by insertEmbed API (version 1.3.7).

```html
<link href="https://cdn.bootcdn.net/ajax/libs/quill/1.3.7/quill.snow.min.css" rel="stylesheet">
<div id="editor">
  <p>Hello World!</p>
</div>
<script src="https://cdn.bootcdn.net/ajax/libs/quill/1.3.7/quill.min.js"></script>
<script>
var editor = new Quill('#editor', { theme: 'snow' });
editor.insertEmbed(0, 'image', 'https://www.baidu.com/img/flexible/logo/pc/result.png', 'api'); // it works
editor.insertEmbed(1, 'link', { href: 'https://www.google.com', innerText: 'google' }, 'api');  // not works
</script>
```

**Comment by danamh** [comment]
looking do to do this exact same thing - no go. Want to link to the URL so the user can view the raw asset...

**Comment by LoveEocding** [comment]
i have a same problem

**Comment by LoveEocding** [comment]
```
import Quill from "quill";
Vue.use(VueQuillEditor)

var Link = Quill.import("formats/link");
// 自定义a链接
class FileBlot extends Link {
  // 继承Link Blot
  static create(value) {
    let node = undefined;
    if (value && !value.href) {
      // 适应原本的Link Blot
      node = super.create(value);
    } else {
      // 自定义Link Blot
      node = super.create(value.href);
      node.innerText = value.innerText;
      node.href = value.href;
      node.id = value.id;
      node.setAttribute("title", value.innerText);
      node.setAttribute("data-value", value.dataValue);
    }
    return node;
  }
}
FileBlot.blotName = "link";
FileBlot.tagName = "A";
//注册FileBlot
Quill.register(FileBlot);
```

> I cannot insert link by insertEmbed API (version 1.3.7).
> 
> ```
> <link href="https://cdn.bootcdn.net/ajax/libs/quill/1.3.7/quill.snow.min.css" rel="stylesheet">
> <div id="editor">
>   <p>Hello World!</p>
> </div>
> <script src="https://cdn.bootcdn.net/ajax/libs/quill/1.3.7/quill.min.js"></script>
> <script>
> var editor = new Quill('#editor', { theme: 'snow' });
> editor.insertEmbed(0, 'image', 'https://www.baidu.com/img/flexible/logo/pc/result.png', 'api'); // it works
> editor.insertEmbed(1, 'link', { href: 'https://www.google.com', innerText: 'google' }, 'api');  // not works
> </script>
> ```

need construct link class

**Comment by splintor** [comment]
`insertEmbed` is not the correct way to do it. If you look at [the code of the `link` format](https://github.com/quilljs/quill/blob/develop/formats/link.js), you can see that it expects its `value` parameter to be a URL string, and doesn't it set the inner text of the created `node`.

The way I found to add a link (when you have its URL and its text), is to add the text, and then select it and make it a link:
```
function addLink(quill, index, text, url) {
  quill.insertText(index, text, 'user');
  quill.setSelection(index, text.length);
  quill.theme.tooltip.edit('link', url);
  quill.theme.tooltip.save();
}
```

You can see a demo [here](https://codepen.io/splintor/pen/GRWryrM).

**Comment by babaiwan** [comment]
make sure you have registered the insert class correctly

the quill will find your blots in all registered blots firstly

![image](https://user-images.githubusercontent.com/50008615/127441930-792b86e9-e5d9-4416-9100-13c310d42451.png)

**Comment by jvnlwn** [comment]
While I do not know if Quill supports inserting a link using the `insertEmbed` method, it does support inserting a link using the `insertText` method.

Here's the related [`insertText` API](https://quilljs.com/docs/api/#inserttext):
```javascript
insertText(
  index: Number,
  text: String,
  format: String,
  value: any,
  source: String = 'api'
): Delta
```

Found this [example](https://quilljs.com/docs/api/#find-experimental) under docs for `find`.
```javascript
quill.insertText(0, 'Hello', 'link', 'https://world.com');
```

I have tested with version 1.3.7 and it works.
