### ISSUE TITLE
 Group toolbar buttons according to screen responsiveness

### ISSUE THREAD

**Issue by miguelcornelli** [quilljs/quill#3246]
Hi,
I would like to know how to group the buttons on the toolbar by decreasing the responsiveness of the screen, making a drop-down list so that the buttons do not fall in a line ... as shown in the image below:
![WhatsApp Image 2020-12-08 at 11 43 30](https://user-images.githubusercontent.com/35777596/101500336-17d48200-394d-11eb-82a0-e51cca081756.jpeg)
![WhatsApp Image 2020-12-08 at 11 42 10](https://user-images.githubusercontent.com/35777596/101500338-186d1880-394d-11eb-9d98-69d68fc4fdb8.jpeg)

**Comment by stickchartkeith** [comment]
This is obviously a bit dated, but exactly what I'm looking for.  Does anyone have a solution / recommendation for how to accomplish this?  Specifically looking to do this in a React (Next.js) project.  Thanks!
