### ISSUE TITLE
Is there a way to limit ordered list nesting in Quill 2.0?

### ISSUE THREAD

**Issue by raykyri** [quilljs/quill#3247]
Quill 2.0 improves upon list handling (hooray!).

However, Quill deltas are natively in an awkward format because they store list entries in a flat format, with e.g. `indent: 4` to specify an indent level of 4, which makes it hard to translate a Quill delta to a native tree of nested `<ol>` elements, because now one has to reconstruct the tree of list elements, while continuing to support any inline styles inside the list.

I can work around all these problems by preventing users from nesting *ordered* lists with more than 1 level. Is this possible in Quill 2.0?

**Comment by Sliffcak** [comment]
Question. How are you able to "work around all these problems by preventing users from nesting ordered lists with more than 1 level.".

I am interested in allowing my users to only go 1 level nested, I do not want more than 1.
