### ISSUE TITLE
Render basic table in quill editor .

### ISSUE THREAD

**Issue by Somdatt211991-cisco** [quilljs/quill#3249]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Every time we are trying to render a table inside the quill editor it doesnt gets rendered properly , somehow <thead > is stripped off and all the content from diff <tr> is pushed into one <tr>. Due to this original structure of table is broken .**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Editor should render the table as it is **:

**Editor is not retaining the structure of table**:

**Platforms**:

Include browser, operating system and respective versions

**Version**: quill@2.0.0-dev.4

Run `Quill.version` to find out

**Comment by benbro** [comment]
Duplicate https://github.com/quilljs/quill/issues/117
