### ISSUE TITLE
Quill turns multiple <p> to one when NOT added to the dom first

### ISSUE THREAD

**Issue by scratchoo** [quilljs/quill#3250]
When passing multiple successive <p> elements to QuillJS, they become one <p>, for example:

`<p>something</p><p>something</p><p>something</p>` will become `<p>somethingsomethingsomething</p>`

**Steps for Reproduction**

1. Visit https://jsfiddle.net/ud4b6wtv/1/

**This issue only happens when you pass the html through javascript (before inserting the html into the page body)** 
If you inject/append the html in the body, then you apply Quill, the markup will be correct (`<p>something</p><p>something</p><p>something</p>`)

is this a bug?

**Version**:

1.3.7

**Comment by smalos** [comment]
I don't see the issue when I assign the html with

`quill.root.innerHTML = ....`

https://jsfiddle.net/Smolo/Lhut0ezk/
