### ISSUE TITLE
multiple cascade blockquote insted of groupped

### ISSUE THREAD

**Issue by denkerny** [quilljs/quill#3252]
lets say we have a string like: `<blockquote><p>1st one<br />2nd one</p></blockquote>`.

**expected one** (and this gitform is like supported the following):
<blockquote>
<p>asdsadad<br />
asdasdads</p>
</blockquote>

**current result**:
<blockquote>1st one</blockquote>
<blockquote>2nd one</blockquote>

![blockquote](https://user-images.githubusercontent.com/25119196/102017651-e1459f80-3d70-11eb-9c3d-c3c8345551f0.png)

**Comment by chappy23** [comment]
We found the same issue, I can replicate it on the quilljs website. We're using ngx-quill v13.0.1 and quill v1.3.7. 

![image](https://user-images.githubusercontent.com/31131603/102580406-17986b80-4131-11eb-90ce-ed981cc870d6.png)
