### ISSUE TITLE
Apply Formatting to Cursor Immediately After Link

### ISSUE THREAD

**Issue by jbean-ss** [quilljs/quill#3259]
After creating a link, if we try to change the font size of the cursor immediately after the link (without any space) the text appears to be placed into the span.ql-cursor element and the formatting is not applied as desired. Additionally back spacing that text now will delete the last character of the link (even when the cursor is placed after the newly entered text) and move the cursor to the end of the link.

**Steps for Reproduction**

1. Visit https://quilljs.com/docs/formats/
2. Enter some text on a single line
3. Highlight that text up to the last character entered (it's important that the last typed character is in your range).
4. Add a link to the selected text.
5. After the link is added, without making any other keystrokes click to the spot **immediately after** the newly created link so that you are no longer highlighting the text
6. Apply a new font size (i.e. the default on quilljs.com/docs/formats is "Normal", "Huge" makes this problem very obvious).
7. Type a few characters (observe the text size is still Normal and not Huge).
8. Now "backspace" (observe that the last character typed is not deleted, instead the last character of the link is deleted, also the cursor has moved to immediately after the link).
9. Open dev tools to the "Elements" tab.
10. Use the clicker to click your text content
11. Observe that the HTML has actually applied these styles to the element with `ql-cursor` as a class and that the special unicode character &#65279 is inside of the ql-cursor span with your content

**Expected behavior**:

7. The text is Huge
8. Deleting deletes the character prior to the cursor
11. The formatted element is not inside the span.ql-cursor element

**Actual behavior**:

7. Text size remains Normal
8. Deleting deletes the last character of the link and moves the cursor to the end of the link
9. We are not typing inside of the span.ql-cursor element

**Platforms**:

Chrome (87.0.4280.88), Windows 10 (10.0.17763)

**Version**:

1.3.6

**Comment by jbean-ss** [comment]
Along this similar vein. There is an additional bug.

If after step 6 and before step 7, you click the link text such that your cursor is somewhere within the <a> tag, there will be a console error like the following: 

`quill.min.js:7 Uncaught TypeError: l.position is not a function
    at t.value (quill.min.js:7)
    at t.value (quill.min.js:7)
    at e.<anonymous> (quill.min.js:7)
    at e.o.emit (quill.min.js:7)
    at e.value (quill.min.js:7)
    at t.value (quill.min.js:7)
    at quill.min.js:7
    at quill.min.js:7
    at Array.forEach (<anonymous>)
    at e.value (quill.min.js:7)`

**Comment by jbean-ss** [comment]
Oh and one more. If you take the route of the second bug (listed in the comment immediately above), after you get that error, all formatting changes made from clicking the toolbar cause the editor to lose focus.

**Comment by luin** [comment]
Closing via #3534
