### ISSUE TITLE
Font Family not persisting inside the editor

### ISSUE THREAD

**Issue by bogoroh** [quilljs/quill#3260]
So when I create a HTML that has some custom font in it and I try to open a modal that is written like:
```
<div className="html-editor">
          <QuillToolbar />
          <ReactQuill
            ref={this.myRef} 
            theme="snow"
            value={text || ''}
            className="html-editor--editor"
            onChange={this.handleEditorChange}
            modules={getEditorModules()}
            formats={getEditorFormats()}
          />
        </div>
 ```
 
 It seems to default the font back to the original state. How do I persist the font? Font Sizes, Bold, underline all seem to work fine.

**Steps for Reproduction**

![ezgif-7-ab4550e399fe](https://user-images.githubusercontent.com/4615263/102574771-34905880-40b7-11eb-959f-8cc590f7bd83.gif)

**Expected behavior**:
I should see my font family persist when I open the modal and the correct value should display

**Actual behavior**:
The default font family shows

**Platforms**:
All browsers

**Version**:
1.3.7

**Comment by bogoroh** [comment]
bump

**Comment by benbro** [comment]
You need to update the font whitelist
https://quilljs.com/playground/#custom-fonts
```javascript
// Add fonts to whitelist
var Font = Quill.import('formats/font');
// We do not add Aref Ruqaa since it is the default
Font.whitelist = ['mirza', 'roboto'];
Quill.register(Font, true);


var quill = new Quill('#editor-container', {
  modules: {
    toolbar: '#toolbar-container'
  },
  theme: 'snow'
});
```
