### ISSUE TITLE
Can't bold or unbolded the selected string on mobile browser

### ISSUE THREAD

**Issue by NicholasNap** [quilljs/quill#3261]
Can't bold or unbolded the selected string on an mobile browser

**Steps for Reproduction**

1. Visit [https://quilljs.com/docs/formats/]
2. Scroll to position of the quill editor
3. Edit on the editor like the mp4 below here
    https://user-images.githubusercontent.com/18440444/102759013-80d8e280-43ae-11eb-8ddf-376a97a30657.mp4

**Expected behavior**:
bold or unbolded the selected string normally

**Actual behavior**:
Can't bold or unbolded the selected string on an mobile browser

**Platforms**:
Android phone, iOS phone, mobile browser

**Version**: 1.3.7

Run `Quill.version` to find out

**Comment by mydb666** [comment]
你好，请问你的这个问题解决了吗？我的情况和你的很相识

**Comment by benbro** [comment]
I can't reproduce.

**Comment by NicholasNap** [comment]
信笺已收
