### ISSUE TITLE
About dynamically changing text content

### ISSUE THREAD

**Issue by SilvaQ** [quilljs/quill#3262]
First of all, I would like to thank the Quill team for their dedication.

Secondly, I have been working on a word proofreading system recently, using Quill as the editor. Now I have a problem:
When the user clicks to proofread, I send a request to pull up a list of all the different types of words, valid, invalid, recommended, and so on, and then replace the contents of the editor by type (with span notes enclosing the binding class name, specifying the style).

I can hardly find a suitable Quill style for this scenario by looking at the documentation. At present, I can only do DOM operation directly to achieve my goal. Therefore, in order not to go the wrong way, I specially open this issue in quill style. May I ask:
1. Are there any official recommendations for dynamic changes, including standard practices such as deleting words, replacing words, and enclosing words with a certain element?
2. What should I do if I want to use the React component on bracketed elements? Blot looks like they can only specify the original element names, but don't see where we can specify our own React Component?

Thank you very much.

**Comment by benbro** [comment]
Please follow the [API docs](https://quilljs.com/docs/api/) to see what's supported.
