### ISSUE TITLE
Event text-change is useless

### ISSUE THREAD

**Issue by orchestrateddigital** [quilljs/quill#3264]
I'm so confused - why did you not properly implement `this` for your event? How are you supposed to dynamically reference an editor when there are multiple on a page? Surely you don't expect people to loop through all instances with the same `var quill = new Quill()` context? Yuk.

**Comment by justinbhopper** [comment]
There's no need for that kind of aggressive post.  Please keep things professional.

If you need `this` to equal the quill editor, you can bind it yourself when registering your event handler.  Or just use lexical scope. 
 This is common practice.  The fact that you are able to register to the event means you at one point already had the correct instance.

```
quill.on("text-change", () => {
  alert(quill); // quill instance is inherited in lexical scope
});
```

```
quill.on("text-change", handleTextChange.bind(quill));

function handleTextChange() {
  alert(this); // quill instance was binded to function during registration
}
```
