### ISSUE TITLE
Replacing selected formatted text or custom font deletes entire line. 

### ISSUE THREAD

**Issue by kristhus** [quilljs/quill#3267]
When you start a selection where some format begins and end selection outside of it, after which trying to replace selection with a keypress, the entire line and focus disappears.

**Steps for Reproduction**
1. Visit [https://quilljs.com/playground/#custom-fonts]
2. Select a letter, and change its font to roboto.
3. Select the letter and its right-neighbouring text. 
4. Press a key. 
![quill_format_error](https://user-images.githubusercontent.com/6399489/103880950-16c47b00-50da-11eb-9c92-5e95dc65fd09.gif)

**Expected behavior**:
Selected text is replaced by pressed key.

**Actual behavior**:
Entire line disappears. 

**Platforms**:
Chrome 87.0.4280.88 (Official Build) (64-bit)
Windows 10 Enterprise

**Comment by luin** [comment]
Fixed in https://github.com/quilljs/quill/pull/3807. Feel free to let me know if there is anything missing. Closing
