### ISSUE TITLE
Render diff between two document versions but not correct

### ISSUE THREAD

**Issue by h-khuat** [quilljs/quill#3268]
Hi All,

I have problem when rendering the difference between two versions of the same document .
I have using diff() and compose().
But the results are not correctly as the user input 
<img width="1151" alt="Screen Shot 2021-01-08 at 10 34 04" src="https://user-images.githubusercontent.com/52475878/103965000-1b536700-51a0-11eb-944f-2130da9ccbfa.png">

(I have consulted the following documentation https://codepen.io/percipient24/pen/eEBOjG)

**Steps**:
In Old version: I add text: "Text 1" and "Text 2" with heading
In New version: 
                        - In 1st line, I add text "Thanks + Text". It means that I add "Thanks +" and remove "1"
                        - In 2nd line, I remove "ext2"
                        - In 3rd line, I add text "Add new text"

**Expected behavior**:
I expect the result to be like this
<img width="1159" alt="Screen Shot 2021-01-08 at 10 39 00" src="https://user-images.githubusercontent.com/52475878/103965107-5b1a4e80-51a0-11eb-8583-7cc8a2ae53e9.png">

Is there any way to improve?
Thanks a lot.

**Comment by benbro** [comment]
This diff demo is not an official Quill demo. Please reopen the issue if you can demonstrate an issue with the actual Delta.
