### ISSUE TITLE
add the ability to set line-height

### ISSUE THREAD

**Issue by wibetter** [quilljs/quill#3269]
![image](https://user-images.githubusercontent.com/11958920/103989739-1fe14500-51cb-11eb-90c6-711289ca9963.png)

**Comment by mo3auya91** [comment]
Do you find a way to add line-height button in toolbars?

**Comment by benbro** [comment]
Related https://github.com/quilljs/quill/issues/3621

**Comment by xuhua1212** [comment]
我行高搞定了,字间距搞不了
