### ISSUE TITLE
Prevent formatting on contenteditable=false nodes

### ISSUE THREAD

**Issue by broveloper** [quilljs/quill#327]
I thought it would be a good idea if and when modules get more complex, then editor would know not to format a node if it was set to contenteditable=false.

ie. Adding markup for a gallery module within the editor, or simply just a node containing custom data-* attributes like a "shortcode" for client templating

**Comment by jhchen** [comment]
This should be supported once the current efforts to support custom formatting bears fruit.

**Comment by jhchen** [comment]
You can define custom content in Quill [1.0 beta](http://beta.quilljs.com) in the form of [embeds](https://github.com/quilljs/parchment#embed-blot) and Quill will not interfere with its children/descendant nodes. This may but does not have to be contenteditable=false.
