### ISSUE TITLE
Table and Image resize

### ISSUE THREAD

**Issue by amitdixit** [quilljs/quill#3274]
Why this great editor is missing Table and Image resize out of box.

**Comment by naouaro** [comment]
As for the image resizing, there is a good plugin 
    
[BlotFormatter](https://www.npmjs.com/package/quill-blot-formatter)

However the table I haven't found a good plugin to use and still searching

**Comment by abarrak** [comment]
Check out [this plugin](https://github.com/soccerloway/quill-better-table) might be helpful.

**Comment by WongYAQi** [comment]
quill-better-table is a good table plugin, but it still has problems, maybe you need to modify that for your use

**Comment by amitdixit** [comment]
I have finally removed quill editor and replaced with jodit editor. It's awesome. Give it atry

**Comment by WilliamWhispell** [comment]
@amitdixit - Amazing - I just switch to jodit and everything just worked. No more needing to use react-quill-with-table for tables that doesn't work well with React 18. No more imageResize breaking when using it. I was stuck between drag and drop working for images or tables. Now I have both! Jodit for the win
