### ISSUE TITLE
Update cdn build in README to latest version

### ISSUE THREAD

**Issue by krishnanunnir** [quilljs/quill#3279]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

The CDN URL provided in the README is for a build with a lot of issues. I didn't figure this out for a while and had a lot of issues with using quill. Update this to a more recent version. 
**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**:

**Actual behavior**:

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
Done.
