### ISSUE TITLE
Typing after EmbedBlot at end of Line Misplaces Cursor

### ISSUE THREAD

**Issue by scottfr** [quilljs/quill#3280]
The Quill cursor can move incorrectly when you have an EmbedBlot at the end of a line.

**Steps for Reproduction**

1. Visit https://codepen.io/abolo/pen/xmzZbO
2. Click the "Add Embed" Button
3. In the content editable click anywhere in the "Embed!" word to reposition the cursor
4. In the content editable click after the "perez" so the cursor appears to be at the very end of the line
5. Type two letters like "ab" 

**Expected behavior**:

The line ends with "...perez**ab**"

**Actual behavior**:

The line ends with "...perez**ba**" (the "a" and "b" are switched).

**Platforms**:

Mac Chrome 88.

**Version**:

Quill 1.3.7

**Comment by OldDream** [comment]
> Is this problem solved?

Never, I suggest you, do not use quill.

**Comment by tkefauver** [comment]
> Never, I suggest you, do not use quill. The embed blot have very serious problem.

Nothing's without its issues and custom rich text editing is COMPLICATED... I think quill's nice :)

**Comment by YolineWu** [comment]
Is this problem solved?
