### ISSUE TITLE
How to call insertEmbed to paste an image bypassing the clipboard matchers

### ISSUE THREAD

**Issue by catrias** [quilljs/quill#3283]
I try to paste an image using `insertEmbed()` fn

`this.quillEditorInstance.insertEmbed(0, 'image', imageSrc);`

But at the same time, I want to disable the ability to paste an image using a clipboard (from the desktop for ex)

`clipboard.addMatcher('IMG', () => new Delta().insert(''));`

So I have an issue that an image pasted with `insertEmbed` is handled by the clipboard module, and quill doesn't display it. Does someone know how to bypass the matcher or any other way to insert an image programmatically?

**Comment by SilvaQ** [comment]
Copy and paste is dealing with the logic of the image and you're very explicit in saying please give me an empty string for the image, so the editor won't show it to you, which I think makes perfect sense
> in this code :
>clipboard.addMatcher('IMG', () => new Delta().insert(''));

Editor picture upload logic I have here an example for your：
> i am using react and antd ui framework 
```jsx
 <span className="ql-formats">
        <span className="ql-upload_pic">
          <Upload
            accept="image/png, image/jpeg,image/png, image/jpg"
            action={getUploadPicUrl()}
            name="article_pic"
            showUploadList={false}
            onChange={({ file }) => {
              // todo: 需要补充：
              // 1. 开始上传默认插入上传中图片占位
              // 2.如果成功了替换成功后的图片
              // 3. 失败了 替换成失败的图片
              setUploading(true);

              const { status, response } = file;
              if (status === 'done') {
                setUploading(false);
                // todo: 这里需要做一些插入图片逻辑

                const {
                  code,
                  message: mess,
                  data: { image_url },
                } = response;

                if (code !== 0) {
                  message.error(mess);
                  return;
                }

                // 成功
                if (!editor) return;
                const selection = editor.getSelection();
                editor.insertEmbed(selection.index, 'image', `/${image_url}`);
                editor.setSelection(selection.index + 1, selection.length);
              }
            }}
          >
            <Button shape="round" size="small">
              <Spin spinning={uploading}>
                <PictureOutlined />
              </Spin>
            </Button>
          </Upload>
        </span>
      </span>
```


You can copy and paste a link, or you can copy and paste a base64 encoded image, so you need to deal with that first, or you can just leave it alone and save it. (I submit them to the server, and the server saves them and gives me the link, and I replace them with the picture link)
