### ISSUE TITLE
该富文本编辑器用的execCommand方法主要实现吗？

### ISSUE THREAD

**Issue by WenBoWeb** [quilljs/quill#3284]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**:

**Actual behavior**:

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by smalos** [comment]
Please use English here or use a translator.

Question translated with Yandex:

"Is the rich text editor mainly implemented with the execCommand method?"

**Comment by SilvaQ** [comment]
所有基于html原生的content editable 特性的浏览器只能基于execCommand。
除非你自己重新封装，比如draft.js。
你在掘进社区搜索富文本编辑器开发 等关键字，有不少简单实例。剩余的你百度 如何开发富文本编辑器，或者知乎“有哪些富文本编辑器”。
这种问题都来这个地方issue的方式想得到答案有点....,祝你好运。
@WenBoWeb

**Comment by zhipengyan** [comment]
The answer is no. Quill use it's own document model [quilljs/parchment](https://github.com/quilljs/parchment).

**Comment by SilvaQ** [comment]
> The answer is no. Quill use it's own document model [quilljs/parchment](https://github.com/quilljs/parchment).

please see  quilljs/quill/formats/image.js,in this formatter using execCommand.
but quill is better then baidu editor a lot. and using just a few execCommand.

**Comment by zhipengyan** [comment]
> > The answer is no. Quill use it's own document model [quilljs/parchment](https://github.com/quilljs/parchment).
> 
> please see quilljs/quill/formats/image.js,in this formatter using execCommand.
> but quill is better then baidu editor a lot. and using just a few execCommand.

It's just a hack method to disable image resizing in Firefox rather than creating or modifying document element.
