### ISSUE TITLE
Invalid Typescript signature for Clipboard.convert

### ISSUE THREAD

**Issue by webair** [quilljs/quill#3296]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Install quill 1.3.7 from npm package manager 
2. import library with typescript 

**Expected behavior**:

Method signature of `ClipboardStatic.convert` should match the one from javascript `Clipboard.convert(html)`

**Actual behavior**:

Typescript method signature matches the one from version 2.x `convert(content?: { html?: string; text?: string }, formats?: StringMap): Delta;`

**Platforms**:

Tested on Linux and Mac

**Version**:

1.3.7

**Comment by benbro** [comment]
Please try:
https://v2.quilljs.com/standalone/full
[v2.0.0-beta.1](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.1)
