### ISSUE TITLE
is there a way to make an editable box (like div element) using a custom button in Quill?

### ISSUE THREAD

**Issue by SaeedNooriAlamouti** [quilljs/quill#3297]
I'm trying to make an editable div element in quill using a custom button.
I wanna that when a user clicks on the button, a div element(with its children) inserts into the clipboard that its innerText is editable.
I used Block embed with iframe tagName but it's not editable. anybody can help?

**Comment by benbro** [comment]
https://quilljs.com/guides/how-to-customize-quill/
