### ISSUE TITLE
Browser tab freezes when changing selection while cmd+b is pressed

### ISSUE THREAD

**Issue by roman01la** [quilljs/quill#3298]
The issue can be reproduced in the playground as well https://codepen.io/quill/pen/KzZqZx, though it's harder to repro in this minimal setup, it's much easier to repro the issue for us where the editor is customized with modules and formatters.

**Steps for Reproduction**

1. https://codepen.io/quill/pen/KzZqZx
2. Enter text into Quill's editor UI
3. Hold CMD+B and change text selection multiple times (10, 20, 30 times ...)
4. At some point the UI will freeze

**Expected behavior**: Chrome's tab process shouldn't be blocked
**Actual behavior**: Chrome's tab process gets blocked

**Platforms**: Chrome on macOS
**Version**: 1.3.6

**Comment by benbro** [comment]
Please try:
https://v2.quilljs.com/standalone/full
[v2.0.0-beta.1](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.1)
