### ISSUE TITLE
Backspace deletes decomposed diacritic + base at start of string but not elsewhere

### ISSUE THREAD

**Issue by mcdurdin** [quilljs/quill#3302]
Backspace behaviour is inconsistent when working with NFD content, as inserted by IMEs such as Keyman for some minority language writing systems such as Ma'di.

This relates to [a reported incompatibility](https://github.com/keymanapp/keyman/issues/4517) in [Keyman](https://keyman.com/) with Slack and LinkedIn in Chrome on Windows, both of which use the QuillJS editor. The issue is reproducible in the playground.

**Background and rationale**

For example, the letter `ạ` can be encoded as `U+0061 U+0323` (Normalization Form Canonical Decomposition, NFD) or as `U+1EA1` (Normalization Form Canonical Composition, NFC). The authors of the Ma'di input method have chosen to use NFD.

Backspace on Windows is expected to delete a single character to the left of the insertion point. It should never delete a grapheme cluster. There are some exceptions to this with variation selectors (e.g. as used with emoji) but behaviour here is inconsistent across applications and consistent behaviour for variation selectors is undefined.

For applications that are not Text Services Framework compliant (such as Chrome), Keyman depends on this backspace behaviour in order to transform input -- for example in this instance it may emit two backspaces to delete both the `U+0061` and the `U+0323` codepoints before emitting the new codepoints to replace them. For these applications, Keyman has no visibility into the text store so it must simply assume that what it inserted is what is present. (This is not the case for Text Services Framework aware applications, where Keyman can manipulate the text store directly.)

However, there is an additional inconsistency in QuillJS. In QuillJS, on Chrome in Windows, for most of the string, backspace deletes only the single codepoint to the left of the insertion point, as expected. However, when the insertion point is to the right of the `U+0061 U+0323` which are at the very start of the string, backspace deletes both codepoints.

**Steps for Reproduction**

Note: Keyman is not required to reproduce this issue.

1. Visit https://quilljs.com/playground/ in Chrome on Windows
2. Paste the string `ạ́ạ́` (`U+0061 U+0323 U+0301`, twice) into the editor (use Ctrl+Shift+V to avoid formatting)
3. Press backspace 5 times.

Reference: compare to behaviour in TEXTAREA at https://codepen.io/mcdurdin/pen/qBqxdRz

**Expected behavior**:

Each backspace should delete the final codepoint from the string, 
The initial `a` should be left behind. 

**Actual behavior**:

The first four backspaces delete one codepoint from the string, as expected, but the final backspace deletes two codepoints.

**Platforms**:

Browser: Chrome 88.0.4324.190 x64
OS: Windows 10 x64 20H2 (19042.804)

**Version**:

QuillJS 1.3.6

**Related Issues**:
#2942: This request is the inverse of this but something to be aware of.
#1444: Relates to decomposed characters, backspace and delete
keymanapp/keyman#4517: Bug report in Keyman

**Comment by takhello** [comment]
On a Mac, the Backspace key does not work
