### ISSUE TITLE
Non-standard format for titles

### ISSUE THREAD

**Issue by ldonis** [quilljs/quill#3308]
Hello, I'm trying to build a Delta parser with Ruby.
I can see that html titles are not quite standard as other formats of the editor because the attributes are in another object instead of the same object where the insert is.

Example: 
```json
{
	"ops": [{
		"insert": "Hello"
	}, {
		"attributes": {
			"header": 1
		},
		"insert": "\n"
	}]
}
```

**Steps for Reproduction**
- Using any implementation of quill
- add a h1 title
- see the delta data: console.log(quill.getContents())

**Expected behavior**:
I think it should match the standard as the other elements:
```json
{
	"ops": [{
		"insert": "Hola title"
		"attributes": {
			"header": 1
		},
	}]
}
```

**Actual behavior**:
```json
{
	"ops": [{
		"insert": "Hola title"
	}, {
		"attributes": {
			"header": 1
		},
		"insert": "\n"
	}]
}
```

**Version**:
Latest version

**Comment by GitHubish** [comment]
I have the same problem. I don't understand the logic. And the problem is the same for other formatting like quotation or lists.

```
  { insert: "\n\nitem 1" },
  { attributes: { list: "ordered" }, insert: "\n" },
```

```
  { insert: "\nCitation is " },
  { attributes: { "strike": true }, insert: "incredible" },
  { attributes: { "blockquote": true }, insert: "\n" },
```

**Comment by benbro** [comment]
Answered.
