### ISSUE TITLE
Is there a way to check to see if a module is already registered before attempting to register it?

### ISSUE THREAD

**Issue by carlosalvidrez** [quilljs/quill#3313]
QQ... Is there a way to check to see if a module is already registered before attempting to register it?

**Longer version:**
I dynamically load the library (through React), and register the modules when needed. This causes some of the modules to be re-registered and I do get a warning on the client. 

`QuillTextEditor.js:19 quill Overwriting modules/imageResize with class ImageResize {
    constructor(quill) {
      let options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};

      this.initializeModules = () => {
        this.removeModules()…`

Thanks!

**Comment by vitchell** [comment]
Came across this when looking for an answer, found my own answer and wanted to drop it here for other ppl searching for an answer.  This is what I'm doing, don't know if its "correct" or not but its working for me for now:

```
!!Quill.imports["modules/imageResize"]
```

**Comment by benbro** [comment]
Answered.
