### ISSUE TITLE
Is there a way to embed a tweet within the editor?

### ISSUE THREAD

**Issue by gdonnelly82** [quilljs/quill#3316]
Using some other editors, for example Substack or Medium you can paste the link of a twitter post and it will embed the post. Do we have that ability in Quill?

See example image attached. 

![Screenshot 2021-03-23 at 19 52 17](https://user-images.githubusercontent.com/59867883/112209508-73333300-8c11-11eb-895d-68513c50e1ad.png)

**Comment by benbro** [comment]
https://quilljs.com/guides/how-to-customize-quill/
https://github.com/quilljs/awesome-quill
