### ISSUE TITLE
Can we have a more advanced WYSIWYG editor?

### ISSUE THREAD

**Issue by weilies** [quilljs/quill#3317]
I am using Quill via PrimeNG (Angular) framework. It's a pretty easy to implement editor. But i find the feature is limited.
Sooner i need to display a nice looking content crafted by admin (sample below)
![image](https://user-images.githubusercontent.com/484828/112253467-bcc76080-8c99-11eb-9a2b-8a1b37eb6acd.png)

I am looking for an editor like WordPress's responsive editor. But when i check through the playground https://quilljs.com/playground, there isn't a way to extend further.

Correct me if i am wrong, currently Quill is a slightly advanced than <TEXTAREA> tag with bold, font color+size, etc. But there ain't a direction to create a complete one with responsive grid system, am i right?

**Comment by DmitrySkripkin** [comment]
Quill is a rich text editor. You are looking for something much more complicated. You can extend quill with own blots to achieve your goals, but I don't think it's a good idea.

**Comment by benbro** [comment]
Answered.
