### ISSUE TITLE
Bug on copy-paste text with links. Text with no links has link attached after paste.

### ISSUE THREAD

**Issue by korneSt** [quilljs/quill#3321]
Bug happens when you select a text that have links and copy-paste text that also contains links.  
Then the links are wrongly copied. 

You can test it yourself as shown in the image below using this sample text in the playground on the quill website.
 Just paste it in then select the text and paste again. 

[link](link)
no link [other link](link)

![obraz](https://user-images.githubusercontent.com/11758939/112805033-60878680-9075-11eb-8332-eace89d7b64a.png)

**Comment by korneSt** [comment]
As a workaround I've created custom clipboard that removes any styles from the selected text before pasting the new one. It seems to resolve the issue, but proper fix should be implemented.

![obraz](https://user-images.githubusercontent.com/11758939/112838240-2631df80-909d-11eb-83b9-53b138eddec7.png)

**Comment by tigrenok00** [comment]
Any news on this one?
