### ISSUE TITLE
IE does not show up on README. Does this mean that IE 11 is also not supported now?

### ISSUE THREAD

**Issue by JackyRoss** [quilljs/quill#3322]
I think someone also have the same question as the title.
Quill is working well on IE11, at least all the buttons on the homepage https://quilljs.com/ have no problem. 
Could you @jhchen  give a clear answer that if  IE 11 is supported on the newest quill's version, or which version is supported on IE 11.

**Comment by benbro** [comment]
v1.2.4 had [IE1](https://github.com/quilljs/quill/blob/c82a61fd677d9f5aade3e0a08f8ded6d4c36e102/CHANGELOG.md?plain=1#L173)1 fix and v1.3.7 doesn't list IE11 in the REAMDE so support was dropped somewhere in between these two versions.
