### ISSUE TITLE
Form is scrolling to top while paste content in quill editor

### ISSUE THREAD

**Issue by BugKiller-pixel** [quilljs/quill#3325]
Hello, When we paste content in editor it is scrolling up the form and editor's scroll is in the same position. I've tried all the solutions which is mentioned in issues here. And I don't want to use scrolingContainer. As I am using default scroll of **.ql-editor**. Any solutions? 

I am not explicitly using **@container.focus()** anywhere.

**Expected behavior**: Position of Form scrollbar and editor's scrollbar remains same

**Actual behavior**: Scrolling form to top

**Comment by quroom** [comment]
#1374 This issue is same as yours
