### ISSUE TITLE
chrome 89 ,Error when inputting Chinese special characters

### ISSUE THREAD

**Issue by TheVoidsteppers** [quilljs/quill#3327]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1.  inputting Chinese special characters, such as `、`, and then Press down enter key. somtime cause wrong cursor position.May need to enter several times.

**Expected behavior**:

Correct cursor position

**Actual behavior**:

cursor in wrong  position, and the Console output error

**Platforms**:

Browser: Chrome 89.0.4389.114 x64
OS: Windows 10 x64

Include browser, operating system and respective versions

**Version**: 
2.0.0-dev.4
Run `Quill.version` to find out

**Comment by TheVoidsteppers** [comment]
inputting Chinese special characters, such as  `、`  will trigger `compositionstart` and `compositionend` event in chrome 89.
![16173597325085](https://user-images.githubusercontent.com/46960618/113408711-7339ec80-93e2-11eb-94b0-7e2663abea93.png)

![16173577102171](https://user-images.githubusercontent.com/46960618/113408696-6917ee00-93e2-11eb-8ec9-c33f15baeee6.png)

**Comment by xuanbingbingo** [comment]
acturally, the first time I found out about this problem was in chrome 86 in windows system, it works well in chrome 85 in windows system. in addtion, i did not find this problem in all chrome versions in mac

**Comment by benbro** [comment]
Please test with [v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2)
https://v2.quilljs.com/standalone/full
