### ISSUE TITLE
Toolbar documentation contains invalid values in font-size example

### ISSUE THREAD

**Issue by igmcdowell** [quilljs/quill#333]
'huge' and 'normal' are not valid values for the CSS font-size property (see https://developer.mozilla.org/en-US/docs/Web/CSS/font-size).
As a result, the sizes in the toolbar example code only work for the 'small' and 'large' options, which are valid values.

Submitted PR #332 to fix

**Comment by jhchen** [comment]
https://github.com/quilljs/quill/pull/332 has been merged and live.
