### ISSUE TITLE
Toolbar not working

### ISSUE THREAD

**Issue by bandrus93** [quilljs/quill#3338]
I have created a container div for the editor, it renders properly, but I am unable to use the toolbar to format inputted text. Clicking Bold does nothing, clicking Italics does nothing; none of the buttons in the toolbar work at all. What's more is that my formatting is not being saved in the DB either.

**Steps for Reproduction**
Not available, but ~~I will include my code files~~ Apologies but I am unable to include my files. I don't have time right now to put my code on codepen, but maybe someone else has had this issue before and could tell me what I might be doing wrong? (Note that I have reproduced the relevant code on the playground editor on quilljs.com and it works as expected. Perhaps this is a compatibility issue with Spring Boot?) 

**Expected behavior**:
Clicking "B" should bold, clicking "I" should italicize, etc. Also the input should be a string that includes the HTML tags so that the formatting is preserved when retrieved from the DB and displayed on my webpage.

**Actual behavior**:
None of the toolbar buttons work, and the input is being saved to the DB as plain text.

**Platforms**:
Spring Boot
Google Chrome
Windows

**Version**:
1.3.6

**Comment by benbro** [comment]
Quill examples here all work https://quilljs.com/
You have something wrong in your code.
