### ISSUE TITLE
Toolbar/Editor does not encapsulate text within a span element.

### ISSUE THREAD

**Issue by cj3kim** [quilljs/quill#334]
Hi. I've been running into a problem where I initially type text into the editor and it does not type text into a span element.  Only when I set the font to normal size, it encapsulates the text inside one. Then, when I start typing  on a new line it writes straight to div.ql-line.

It seems that when the code initializes, it doesn't set the  initial text to 'normal' size.  I have to set the font option in the toolbar to normal for the text to be encapsulated in a span element.  But, as I said before, when I create a new line in the editor, it doesn't utilize the span element to type out text.  This means I constantly have to set the font to normal every time I want that text to be encapsulated in a span. The demo code does not exhibit this behavior.

Also,  I initially set elements to only use Railway font and default to serif in my main.css.  I am also using QuillJS within ReactJs. Could this be a problem?

What is going on? I suspect that I'm doing something wrong with the toolbar or fonts.   Relevant code below. 

Quill version '0.19.10' installed with NPM and compiled with Browserify. 

Outputted Html:

     <div class="ql-editor" id="ql-editor-1" contenteditable="true">
        <div class="ql-line" id="ql-line-1">
            Why is this text simply typed out into the ql-line, but not a span?  
            <span style="font-size: 16px;"> This text is normal and set inside the s pan.</span>
        </div>
        <div class="ql-line" id="ql-line-451">The new line.</div> 
    </div>

Javascript:

    var fullEditor = new Quill(td, {
      styles: {
        '.ql-editor': {
          'font-family': "'Arial', san-serif !important"
        }
      },
      modules: {
        'toolbar': { container: '#toolbar-toolbar' },
      },
      theme: 'snow'
    });

CSS: 

    p,span, ul, li, label, td, tr, input{
      font-family: Raleway, serif;
    }

Toolbar HTML gist: https://gist.github.com/cj3kim/61ddbcebb24bceb04e5a

**Comment by cj3kim** [comment]
Update:
Removed  Raleway CSS and same problem still occurs.

**Comment by cj3kim** [comment]
Update:
It seems that writing text directly to qill-line is somewhat expected behavior. Why is this the case?

**Comment by jhchen** [comment]
That was actually Quill's earlier designed (to enclose all text nodes in at least one inline node) but caused issues with Android's keyboard so was changed to the way it is now. Why do you need text nodes to be contained in a span?

**Comment by jhchen** [comment]
Please comment/reopen if this is still an issue.
