### ISSUE TITLE
chrome 86-90 in window 10 x86_64 ,editor-change does not trigger when inputting special characters such as '。~'

### ISSUE THREAD

**Issue by xuanbingbingo** [quilljs/quill#3340]
input special characters, such as '。~' and so on

Expected behavior:

editor-change listener trigger when input chinese characters'。' or '~'

Actual behavior:

editor-change listener does not trigger when input chinese characters'。' or '~'

Platforms:

Browser: Chrome 86.0.4240.75
OS: Windows 10 x64

Version:
2.0.0-dev.4

**Comment by regnoh** [comment]
// quill/core/selection.js
`handleComposition() {
    ...
    this.root.addEventListener('compositionupdate', (data) => {
      // 匹配除中文、字母、数字外的特殊字符，合成输入法的特殊字符不走 batch 更新
      const reg = /[^\u4e00-\u9fa5a-zA-Z\d]+/;
      if (reg.exec(data.data)) {
        this.composing = false;
        return;
      }
    });
  }`

**Comment by benbro** [comment]
Please test with [v2.0.0-rc.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-rc.2)
