### ISSUE TITLE
http://myeditor.cool invitation

### ISSUE THREAD

**Issue by sskyy** [quilljs/quill#3341]
Hello, I'm the author of MyeditorCool. http://myeditor.cool is website reads user's file in github/onedrive/etc. through openapi, and allow user to edit it with any editor published to npm and has 'myeditorcool' field in package.json.

By supporting myeditorcool, quill can soon be used by users to edit their own flow file online without installing anything!

I'm inviting quill to join myeditorcool, be our recommended editor. Only a few works need to be done, the docs are here: https://github.com/MyEditorCool/editors/blob/master/DevelopAnEditor.md. Looking forward to your reply.

**Comment by benbro** [comment]
https://github.com/quilljs/awesome-quill
