### ISSUE TITLE
Question: Is this project supported or not?

### ISSUE THREAD

**Issue by vella-nicholas** [quilljs/quill#3348]
Can someone please clarify whether this project is supported or not? I can see commits being merged from a couple of days ago but the latest release is way back from 2019. We would like to integrate Quill into one of our projects but we are not keen on adding stale packages.

**Comment by mtycholaz** [comment]
Personally, I migrated to use a different editor. I've had a bug open for over a year and a half and nothing has changed. I finally got fed up.

**Comment by benbro** [comment]
[v2.0.0-beta.1](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.1) just released.
