### ISSUE TITLE
Text decoration w/ Footnote note working 

### ISSUE THREAD

**Issue by markallencarey** [quilljs/quill#3351]
We are using a footnote feature in the toolbar (FN) that allows you to save a footnote for a selection and then click on the selection to display the saved footnote:

<img width="327" alt="Screen Shot 2021-04-27 at 10 50 36 AM" src="https://user-images.githubusercontent.com/68764324/116280916-680a8000-a746-11eb-8ba5-877fcb4b2890.png">

<img width="377" alt="Screen Shot 2021-04-27 at 10 50 52 AM" src="https://user-images.githubusercontent.com/68764324/116280951-70fb5180-a746-11eb-81db-29c91fbd5334.png">

<img width="357" alt="Screen Shot 2021-04-27 at 10 51 03 AM" src="https://user-images.githubusercontent.com/68764324/116280983-78225f80-a746-11eb-9002-3c6ae502a05e.png">

Our issue is that if you bold, italicize, or underline the word as well, the footnote will not show up when you click on it:

<img width="373" alt="Screen Shot 2021-04-27 at 10 51 49 AM" src="https://user-images.githubusercontent.com/68764324/116281084-938d6a80-a746-11eb-8e86-6103c18f2d34.png">

**Comment by Huseyin-altun** [comment]
> We are using a footnote feature in the toolbar (FN) that allows you to save a footnote for a selection and then click on the selection to display the saved footnote:
> 
> <img alt="Screen Shot 2021-04-27 at 10 50 36 AM" width="327" src="https://user-images.githubusercontent.com/68764324/116280916-680a8000-a746-11eb-8ba5-877fcb4b2890.png">
> 
> <img alt="Screen Shot 2021-04-27 at 10 50 52 AM" width="377" src="https://user-images.githubusercontent.com/68764324/116280951-70fb5180-a746-11eb-81db-29c91fbd5334.png">
> 
> <img alt="Screen Shot 2021-04-27 at 10 51 03 AM" width="357" src="https://user-images.githubusercontent.com/68764324/116280983-78225f80-a746-11eb-9002-3c6ae502a05e.png">
> 
> Our issue is that if you bold, italicize, or underline the word as well, the footnote will not show up when you click on it:
> 
> <img alt="Screen Shot 2021-04-27 at 10 51 49 AM" width="373" src="https://user-images.githubusercontent.com/68764324/116281084-938d6a80-a746-11eb-8e86-6103c18f2d34.png">

Hello, can you share your code? This feature looks nice.
