### ISSUE TITLE
What Quill version to use?

### ISSUE THREAD

**Issue by m-demydiuk** [quilljs/quill#3356]
Hello.  What version of quill to use?
There are 
- 1.3.7 which is installed from npm by `npm install quill` and was published 2 years ago.
- 2.0.0-dev3 - this version is required for modules [quill-better-table](https://github.com/soccerloway/quill-better-table) and [quill-table-ui](https://github.com/volser/quill-table-ui) . It was published 3 years ago (???).
- 2.0.0-dev4 - this version I found in npm versions history. It was published a year ago

Your website is referencing version 1.3.6 (???) and all documentation is for version 1.3.6.

So, it is absolutely not clear, what version should I use.

Could you please introduce some clearness? It would be great if you can answer some questions:
1. What is the latest production-ready version? 
2. Why 1.3.7 was deployed 2 years ago? I see there is a lot of closed pr not so far.
3. What is the status of 2.0.0-dev3(4)? Is it going to be published as production-ready (I mean without dev suffix)? When?
4. Are you still supporting this project at all? Or is it dead and not supported anymore?

Finally, looking at npm download statistic, I see that other people are also don't know what's going on with versioning:
![image](https://user-images.githubusercontent.com/2910327/116548022-523ebb80-a8fc-11eb-80c2-5d2192c6e043.png)

I really hope for your answer as soon as possible. Because, otherwise, I think we will switch to some other editor.

**Comment by smalos** [comment]
Quill seems to be dead.. 1k issues and the developer doesn't seem to be active anymore or does not answer questions here

**Comment by harleenarora** [comment]
please release the stable version v2.0.0-dev.4

**Comment by m-demydiuk** [comment]
@jhchen Hi Jason, could you please somehow comment current status of the quill editor? Is this project dead?

**Comment by tx0c** [comment]
it looks like dead from current 1.1k open issues, and this Contributors Insights: 2013-2017 were the most active days, and since 2019 very low development activities

![image](https://user-images.githubusercontent.com/49659410/135216888-50e9808f-891a-4a88-86e5-e9972fb9ab5c.png)

**Comment by m-demydiuk** [comment]
@benbro Thank you. We already migrated to another editor.
