### ISSUE TITLE
Link Tooltip URL Editor does not open in Custom Theme based on BaseTheme and BaseTooltip

### ISSUE THREAD

**Issue by jwittekind** [quilljs/quill#3358]
Hey, i'm currently trying to create my own custom javascript theme based on the quill BaseTheme and BaseTooltip in an angular environment.

I just copied the existing SnowTheme from the quill repository and slightly migrated it for typescript to compile.
I double checked my imports and did not overwrite any values but i guess i noticed a bug here.

When i use "my-wysiwyg-theme" i can not click on links in the editor to open the tooltip and url editor anymore.
https://stackblitz.com/edit/angular-ivy-etchfy?file=src%2Fapp%2FMyWysiwygTheme.ts

It's usually opened by the snow tooltip which gets triggered on "Emitter.events.SELECTION_CHANGE," in:
MyWysiwygTheme.ts:123
but only if the descendant is of Type LinkBlot. Unfortunately this condition fails and at this point i cant find out why.

Do you have an idea, what i'm doing wrong here?

Thanks in advance!

**Steps for Reproduction**

1.  Visit https://stackblitz.com/edit/angular-ivy-etchfy?file=src%2Fapp%2FMyWysiwygTheme.ts
2. Click on a link in the editor

**Expected behavior**:
tooltip opens

**Actual behavior**:
tooltip does not open

**Platforms**:
All Browsers

**Version**:
^1.3.7

**Comment by evgeniyworkbel** [comment]
@jwittekind Hello! Did you find the solution?

**Comment by jwittekind** [comment]
Hey @evgeniyworkbel. 
It's been a while since i've been facing that issue. I can't tell, whether i figured out a solution for the build in Quill module, but in the end i replaced the whole menubar for the use of my custom components anyway - using the QuillJs method API.
