### ISSUE TITLE
Fix https://www.npmjs.com/advisories/1695

### ISSUE THREAD

**Issue by dawidrylko** [quilljs/quill#3363]
**Steps for Reproduction**:

1. `npm install quill`
2. `npm audit`

**Expected behavior**:

No security advisory.

**Actual behavior**:

Security advisory https://www.npmjs.com/advisories/1695

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Cross-Site Scripting                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ quill                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ quill                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ quill                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1695                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Platforms**:

N/A

**Version**:

`1.3.7`

**References**:
- https://github.com/advisories/GHSA-4943-9vgg-gr5r
- https://github.com/quilljs/quill/issues/3364

**Comment by infinity899** [comment]
Anyone found a work-around?

**Comment by julianlam** [comment]
I wanted to see if I could code a workaround for this by extending `formats/image` to explicitly look for `onloadstart` and removing the attribute, but it is no surprise that Quill already handles this with the `sanitize` method within. The only allowed attributes are `src`, `height`, and `width`. `onloadstart` is not one of them.

Therefore, unless I am mistaken I see no way to actually trick the quill editor into inserting an image blot with the `onloadstart` attribute, unless a custom blot was created to explicitly add it.

Furthermore, the issue linked in the CVE (#3273) no longer exists or was deleted.

Again, **unless I am mistaken**, this could be something as simple as "quill can be extended to introduce a vulnerability", but quill out of the box will not, at least for this case. I have heard of cases where so-called security researchers will try to shame a company by submitting a CVE before it has even been verified/triaged. _insert tinfoil hat_

**Comment by silverbackdan** [comment]
Also see https://github.com/quilljs/quill/issues/3364
