### ISSUE TITLE
Question from a new user.

### ISSUE THREAD

**Issue by simon-zhangmuye** [quilljs/quill#3371]
Hi guys.

I am learning quill and delta.
![image](https://user-images.githubusercontent.com/10706610/119004398-df43d480-b9d1-11eb-8159-7f08a1e083d3.png)
Here is an example from quill and I am confused by the index number.

**Comment by simon-zhangmuye** [comment]
Is this a mistake, it should be 1 for the index and 4 for the length?

**Comment by DokaRus** [comment]
> Is this a mistake, it should be 1 for the index and 4 for the length?

In this case only the first line will be formatted
`index` is not the line number, but the position in the content from which the formatting should be applied.
Perhaps an example with text selection would be clearer:
https://codepen.io/Doka/pen/YzZNmrZ

**Comment by benbro** [comment]
Answered.
