### ISSUE TITLE
Mac spelling correctness doesn't work - "addRange(): The given range isn't in document."

### ISSUE THREAD

**Issue by yanivfa** [quilljs/quill#3375]
Hi,

When I paste text from outer source into the text editor and trying to fix spelling, the word is getting deleted (see attached video).
In addition, the warning "addRange(): The given range isn't in document." is printed to the console.

How to reproduce:

1) Copy from gmail some text with spelling error. for example: "hre are th msitaks".
2) Past it into the text editor and try to fix spelling using mac spelling checker (right click).

https://user-images.githubusercontent.com/79040987/119375910-0d702f80-bcc4-11eb-8b4f-05810b1dbbc2.mov

**Comment by yanivfa** [comment]
Any update?

**Comment by roeerokah** [comment]
I have also encountered it many times...

**Comment by Shestak2039** [comment]
Hello everyone, any updates on this issue?
I'm using version 1.3.7 and it still reproduce.
Will it be fixed?

**Comment by luin** [comment]
Fixed in https://github.com/quilljs/quill/pull/3807. Feel free to let me know if there is anything missing. Closing
