### ISSUE TITLE
How to find html till the cursor position ?

### ISSUE THREAD

**Issue by imran-momin4041** [quilljs/quill#3381]
I need to find HTML till the cursor position.

Is there any way ?

**Comment by benbro** [comment]
Use [getLeaf](https://quilljs.com/docs/api#getleaf-experimental) for each index until the cursor position index. Check for offset == 0 to not count a leaf twice. Get the html of the leaf Blot.
```javascript
let [leaf, offset] = quill.getLeaf(index);
```
