### ISSUE TITLE
[FeatureRequest] .insertHTML

### ISSUE THREAD

**Issue by thebravoman** [quilljs/quill#3384]
I would like a feature request to have .insertHTML

I am migrating out of ckeditor and have selected Quilljs as the next step and I have seen issues for inserting html like https://github.com/quilljs/quill/issues/3009 

I think it would be good to have such a method instead of making everyone understand the model and the deltas and people are just trying to insert an HTML. They don't have to understand the internal model of Quill and how it works. 

I could even to suggest to add the feature if you have nothing against it?

**Comment by benbro** [comment]
https://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml
