### ISSUE TITLE
Possible problem - quill removes the class="". Is this a problem?

### ISSUE THREAD

**Issue by thebravoman** [quilljs/quill#3385]
Is this a problem?

In the db I have 

```
<p><img alt="Picture of Поле с планети и пъзел-карти" class="img-content img-responsive" src="https://d2nmr6p48f8xwg.cloudfront.net/content_pictures/4356/859e0692dfa9c95715e753cfc9d77d0d/%D0%9F%D0%BE%D0%BB%D0%B5%20%D1%81%20%D0%BF%D0%BB%D0%B0%D0%BD%D0%B5%D1%82%D0%B8%20%D0%B8%20%D0%BF%D1%8A%D0%B7%D0%B5%D0%BB-%D0%BA%D0%B0%D1%80%D1%82%D0%B8.png"></p>
```

When this is loaded by quill the class="img-content img-responsive" are removed?

Is this an expected behavior or this is a bug?

**Comment by ntgnst** [comment]
It seems weird. Image format has `ATTRIBUTES`.

Default: 
const ATTRIBUTES = ['alt', 'height', 'width', 'class', 'data-class'];

Quill must not removes with default settings.

**Comment by thebravoman** [comment]
So it is a problem if it does this. How could I best demonstrate it to make it easier to debug?

**Comment by simanacci** [comment]
@thebravoman I'm having a similar problem. I have `<p><img data-id="27" src="https://foo.s3.amazonaws.com/resources/6239f5059f96481fe7wz2dbb87b6e46f.jpg"/></p>` saved in Postgres but when rendered `data-id=27` is deleted.  
`<div id="editor" style="min-height: 100px;">{{ resource.raw_text | safe }}</div>`

**Comment by yfzhangCode** [comment]
I'm having a similar problem +1. How to solve this problem？
