### ISSUE TITLE
javascript operations on quill HTML.

### ISSUE THREAD

**Issue by imran-momin4041** [quilljs/quill#3386]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**:

**Actual behavior**:

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by imran-momin4041** [comment]
I am not able to perform javascript operations on quill HTML.

I am using highlight javascript and if the user searches any text then it should highlight text in quill but somehow quill is not allowing it.

Is there any way to do it?

**Comment by benbro** [comment]
https://quilljs.com/docs/quickstart/
