### ISSUE TITLE
Can we add custom elements other than <button> and <select> in toolbar?

### ISSUE THREAD

**Issue by nimay-gupta** [quilljs/quill#3390]
Failed attempt at trying to create it:
https://codesandbox.io/s/custom-toolbar-with-react-quill-fully-working-select-i0ekt?file=/index.js

**Comment by ackmanx** [comment]
I was able to add a text field input: https://codepen.io/ackmanx/pen/xxqzPyy?editors=1111

**Comment by benbro** [comment]
You can manually create a toolbar in HTML:
https://quilljs.com/docs/modules/toolbar/
