### ISSUE TITLE
Document how to get HTML

### ISSUE THREAD

**Issue by bibhas2** [quilljs/quill#3393]
It is arguably a very common need to just get the HTML from the editor and save it in a database somewhere. Yet there's no straightforward way to do this. There are all sorts of alternate approaches described in issue #903. I think the problem is easily solved by adding a bit of documentation in the ``API > CONTENT`` section.

**Expected behavior**:

Documentation on how to get the HTML text from the editor.

**Actual behavior**:

I can not easily locate this information in the documentation. Issue #903 has all sorts of workarounds. It's not clear which one is better than the other and one should be using.

**Platforms**:

Any platform.

**Version**:

v1.3.6

**Comment by redbird19** [comment]
I just started using/integrating quill into my application and found getting the html from the editor to be the biggest challenge.  The simplest way to get the HTML from the editor is to use:

quill.root.innerHTML

However, while that will get you the HTML from the editor, that HTML will have references to quill-specific css classes which are largely responsible for formatting.  So if you attempt to take that HTML and display it somewhere else where those css classes are not defined, it will look way off.  

My use-case was that I wanted the HTML from the quill editor to be sent in an email.  But the quill-specific css classes, particularly the ordered lists, make extensive use of css pseudo elements, which are NOT supported by most email providers (like gmail, etc.).

It was a headache, but I took the brute-force method of examining the quill css classes for the functionality I was interested in (ordered lists, indenting, custom fonts, etc.), and writing a post-process function to apply the styles inline to the elements in the quill HTML.  This new HTML with the inline styles is what I save to our database and what I send in the email.  I also have another function to remove these inline styles when loading the saved content into the quill editor so further edits can be made.  

It's not very elegant, but works well enough.  It was a lot more work than I had anticipated though. particularly the ordered lists, which were a pain.  I started questioning my sanity when I started writing methods for converting integers to roman numerals, as well as converting numbers to alpha characters (1 = a, 2 = b...27 = aa...53 = ba...79 = ca, etc.), fortunately google saved me. 

Hopefully you won't need to go down the road I did, and can just add the quill css classes to wherever you want to display the HTML and call it a day.

**Comment by mangatinanda** [comment]
@luin Is there a plan to address this issue in the upcoming V2 release? One of our key use cases is getting HTML content from the editor, sending it via email, and being able to edit this content later. We really appreciate the features of the editor, but the lack of HTML support has been a significant obstacle for us.

If you have any suggestions on how to send content from the editor in an email while preserving the formatting, please let us know.

**Comment by luin** [comment]
@mangatinanda This is a `quill.getHTML()` method in the develop branch and I think that fits your requirements?

**Comment by benbro** [comment]
https://v2.quilljs.com/docs/api#getsemantichtml
