### ISSUE TITLE
Is it possible to limit the number of characters that a user can type into the editor?

### ISSUE THREAD

**Issue by Matlor** [quilljs/quill#3398]

**Comment by ThomasMcDonald** [comment]
I dont believe there's a  'max text length' concept but you can use the [text-change](https://quilljs.com/docs/api/#text-change) event to remove the text after it gets over a certain length

Similar to below: 
``` Javascript
quill.on('text-change', function(delta, old, source) {
    if (quill.getLength() > limit) {
        quill.deleteText(limit, quill.getLength());
    }
});
```
[Source](https://stackoverflow.com/a/50060571)

**Comment by benbro** [comment]
Answered.
