### ISSUE TITLE
Link doesn't work in Chrome Stable - 41.0.2272.101 (64-bit)

### ISSUE THREAD

**Issue by countach74** [quilljs/quill#340]
The link tooltip shows up, then disappears almost immediately. The second time I try, it usually shows up and stays up, but upon clicking "Done", nothing in the text area changes. I've tested this on Linux (KDE) and OSX. Seems to work okay in Firefox, though. Oh, and I'm running Quill 0.15.3.

**Comment by brettimus** [comment]
haven't had an issue in most recent version. side-note: are you still using iframes? you have my condolences :grin:

**Comment by countach74** [comment]
Oh can you configure Quill to use iframes? No, I'm not. As to the latest
version: Is there a way to install that via bower?

**Comment by brettimus** [comment]
have you defined any click events on top of the editor? that messed with the link tooltips for me.

also, yes-- from the README `bower install quilljs`

**Comment by countach74** [comment]
I don't think I've defined any click events on top of the editor, but I
will check. I must all ready have the latest, as I just updated via bower.
Have you tried using Quill with Angular? That's the context which I'm using
it under. I suppose it could be possible that Angular is interfering with
it in some way. I'll experiment with a minimalist setup to see if that
works (e.g. without Angular).

**Comment by brettimus** [comment]
ah yes. i haven't worked with angular, but my best guess is that might be the issue. godspeed!
