### ISSUE TITLE
After implementing Shift+Enter functionality, Quill removes 'br' tag in TextNode

### ISSUE THREAD

**Issue by ntgnst** [quilljs/quill#3401]
After digging many hours,  found 'shift+enter' functionality in Quill. But it comes some problems. After saving content and re--opening with Quill editor, it removes 'br' tags in 'list'. Also i am adding data attribute to 'br' node.

1. Definition
``` JS

.... `all definitions working` ...
const lineBreakMatcher= () => {
  const newDelta = new Delta().insert( '\n', { dataName: 'custom-break' });

  return newDelta;
};

class SmartBreak extends Break {
  length() {
    return 1;
  }

  value() {
    return '\n';
  }

  insertInto(parent, ref) {
    Embed.prototype.insertInto.call(this, parent, ref);
  }
}
SmartBreak.blotName = 'custom-break';
SmartBreak.tagName = 'BR';
Quill.register(SmartBreak);

...
`Registering matcher`
...
{
      modules: {
      ...
        clipboard: {
          matchers: [['BR', lineBreakMatcher]],
        },
     ...
    }
}

```
2. Html Input

``` html
<ol>
    <li>
        This is a text node
        <br data-name="custom-break">
        seperated by BR tag !
    </li>
</ol>
```

3. Html Output

``` html
<ol>
    <li>This is a text seperated by BR tag !</li>
</ol>
```

**Expected behavior**:
Do not remove 'br' tag in list.

**Actual behavior**:
Removes 'br' tag in list.

**Platforms**:

Windows 10
Chrome 91.0.4472.114

**Version**:

Quill v1.3.7

**Comment by Laggii** [comment]
@ntgnst I see you have closed the issue. How did you managed to fix it? I met the same problem

**Comment by kozi** [comment]
Is there a solution?
https://github.com/quilljs/quill/issues/3065#issuecomment-1938975439
