### ISSUE TITLE
Is there a way to remove a Quill?

### ISSUE THREAD

**Issue by ghost** [quilljs/quill#3409]
I need to open a temporary Quill and then remove it when done, restoring the page to its previous state. There doesn't seem to be any sort of deconstructor method, so my current solution is to delete the DOM elements quill.root and quill.container.previousSibling (which has the toolbar), remove the classes from quill.container, and let all references to the Quill object be forgotten. Is this correct?

**Version**: 1.3.6

**Comment by Yogeshkad** [comment]
I am also searching solution on this I am deleting the DOM by ID and creating new editor with same id not working. good to have 1 destroy or remove editor method instead of removing all references manually.

**Comment by smalos** [comment]
[$("div[class^='ql-']").remove();](url)

**Comment by yujiri8** [comment]
@smalos, that is essentially what I'm already doing.

**Comment by benbro** [comment]
Duplicate https://github.com/quilljs/quill/issues/662
