### ISSUE TITLE
Vulnerability issue SNYK-JS-QUILL-1245047

### ISSUE THREAD

**Issue by EricDitp** [quilljs/quill#3411]
Are you able to fix the following issue?

Thanks in advance!

SNYK-JS-QUILL-1245047
https://app.snyk.io/vuln/SNYK-JS-QUILL-1245047

Cross-site Scripting (XSS)

**Comment by benbro** [comment]
Doesn't look like an issue to me. What's are the steps to reproduce?

**Comment by EricDitp** [comment]
It's a vulnerability for a potential attack:
Details
A cross-site scripting attack occurs when the attacker tricks a legitimate web-based application or site to accept a request as originating from a trusted source.

**Comment by benbro** [comment]
You didn't answer my question. What are the steps to reproduce?
