### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [quilljs/quill#3415]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by SebTota** [comment]
It looks like the [README](https://github.com/quilljs/quill#community) says:

> If privacy is required, email support@quilljs.com

Hope this helps!

**Comment by JamieSlome** [comment]
@zidingz - just (cc) you here.

**Comment by benbro** [comment]
Answered.
