### ISSUE TITLE
It's not fully working using same html class name

### ISSUE THREAD

**Issue by ljfreelancer88** [quilljs/quill#3416]
I'm trying to apply Quill WYSIWYG in all html that has `editor` class name but it only applied on the first element. Check the example mark-up below.

```html
<div class="editor topic"></div> <!--working-->
<div class="editor notes"></div> <!--not working-->
```
```javascript
var editor = new Quill('.editor');
```

**Expected behavior**:
I'm suppose to see Quill WYSIWYG on all html classes define here `new Quill('.editor')`

**Actual behavior**:
Quill WYSIWYG is only applied on the first class element

**Platforms**:
Chrome, Ubuntu

**Comment by smalos** [comment]
Try:

```
$('.editor').each(function(index, element) {
   new Quill('#' + element.id);
});
```

**Comment by benbro** [comment]
Answered by @smalos.
