### ISSUE TITLE
Spaces

### ISSUE THREAD

**Issue by Sonic122** [quilljs/quill#342]
Can spaces be preserved when copy pasting on Quill ?

**Comment by jhchen** [comment]
Can you give an example of what you're trying to paste into Quill? In general spaces are preserved.

**Comment by Sonic122** [comment]
Announcement of Academic Positions

The Department of Computer Science and Engineering invites applications for two

(2) visiting positions in the following academic domains.

1. Database Systems, preferably with specialization in Big Data or Object Relational data models

2. Software Engineering, preferably with specialization in Web Engineering.

The visiting positions are for the rank of Lecturer or Assistant Professor and the contract duration will range from one (1) to two (2) years. Successful applicants are expected to commence employment in the academic year 2015-16 and not later than October 1st 2015.

Applicants should submit the following:

-Statement of Purpose

-Extended Curriculum Vitae

-Research Statement

-Names of two referees

Applications should be sent to Mr Achilleas Achilleos either electronically at a.achilleos@frederick.ac.cy or via post at the following address:

Frederick University

Human Resources Service (attention Mr Achilleas Achilleos)

PO Box 24729, 1303 Nicosia

The application deadline is 16:00, 18th of May 2015.

It is noted that success or failure for the aforementioned positions is in no way related to any future invitations for tenure-track positions in the given academic domains the Department may open.

**Comment by jhchen** [comment]
I see. The cause here is there's padding under a `<p>` tag by default but Quill lines does. You can reproduce this by just adding a css rule to a Quill line to add the padding.
