### ISSUE TITLE
How to save in database??

### ISSUE THREAD

**Issue by KatiaSishost** [quilljs/quill#3421]
Hello, im trying to save the content of quill editor in database, and i cant... im using laravel

in controller: $device->description=$request->get('description');

mi view:

<div id="full-container">
                  <div class="editor">
                  <div class="col-12" align="center">
                <button type="submit" class="btn btn-primary mr-1" id="save">Enviar</button>
                <button type="reset" class="btn btn-outline-secondary">Cancelar</button>
              </div>

                </div>

(function (window, document, $) {
  'use strict';

  var Font = Quill.import('formats/font');
  Font.whitelist = ['sofia', 'slabo', 'roboto', 'inconsolata', 'ubuntu'];
  Quill.register(Font, true);

  // Full Editor

  var fullEditor = new Quill('#full-container .editor', {
    bounds: '#full-container .editor',
    modules: {
      formula: true,
      syntax: true,
      toolbar: [
        [
          {
            font: []
          },
          {
            size: []
          }
        ],
        ['bold', 'italic', 'underline', 'strike'],
        [
          {
            color: []
          },
          {
            background: []
          }
        ],
        [
          {
            script: 'super'
          },
          {
            script: 'sub'
          }
        ],
        [
          {
            header: '1'
          },
          {
            header: '2'
          },
          'blockquote',
          'code-block'
        ],
        [
          {
            list: 'ordered'
          },
          {
            list: 'bullet'
          },
          {
            indent: '-1'
          },
          {
            indent: '+1'
          }
        ],
        [
          'direction',
          {
            align: []
          }
        ],
        ['link', 'image', 'video', 'formula'],
        ['clean']
      ]
    },
    theme: 'snow'
  });

**Comment by einfallstoll** [comment]
I'm doing something like this to store the content in a hidden input field:

    fullEditor.on('text-change', () => {
      const { ops } = quill.getContents();
      $(`input[name="richContent"]`).val(JSON.stringify(ops));
    });

**Comment by benbro** [comment]
Answered by @einfallstoll.
