### ISSUE TITLE
Ctrl + Shift + Z broken on windows in develop branch

### ISSUE THREAD

**Issue by rockwotj** [quilljs/quill#3424]
Because the `KeyboardEvent.key` is `Z` not `z`, note on mac it seems to be `z` so 🤷 

It's the only builtin keyboard shortcut that uses the shiftKey modifier and shift toggles to upper case. See [this link](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) in particular:

> ...taking into consideration the state of modifier keys such as Shift as well as the keyboard locale and layout. Its value is determined as follows:

**Comment by luin** [comment]
Merging into https://github.com/quilljs/quill/issues/3970
