### ISSUE TITLE
Stripping of <br> tags when loading saved content

### ISSUE THREAD

**Issue by wallylawless** [quilljs/quill#343]
If I initialize Quill on a `div` with the following contents (imagine poetry for example):
```html
<p>
    line 1<br>
    line 2<br>
    line 3
</p>

<p>
    line 4<br>
    line 5<br>
    line 6
</p>
```

Once Quill has initialized, the contents of the editor become:
```html
<div class="ql-line" id="ql-line-1">line 1</div>
<div class="ql-line" id="ql-line-4">line 2</div>
<div class="ql-line" id="ql-line-7">line 3</div>
<div class="ql-line" id="ql-line-9">line 4</div>
<div class="ql-line" id="ql-line-12">line5</div>
<div class="ql-line" id="ql-line-15">line6</div>
```

Based on this transformation, there does not appear to be any way to restore the content back to the original state when saving any changes they've made in the editor.  Is there something I'm missing here that could help preserve the original content's structure?

**Comment by jhchen** [comment]
Quill unfortunately was not designed to deal with arbitrary HTML. This is partially a tradeoff in order to provide greater consistency necessary for its high level APIs. Unfortunately this does mean given some text rendering, there's only one Quill valid HTML markup (which it will covert to).
