### ISSUE TITLE
Add sms to the default PROTOCOL_WHITELIST

### ISSUE THREAD

**Issue by jgulledge19** [quilljs/quill#3433]
I would like to be able to add sms links with the link tool. The default is limited to: 'http', 'https', 'mailto', 'tel' https://github.com/quilljs/quill/blob/9cf0285caa6514356a7bba9db132ec7229eb254c/formats/link.js#L31 

SMS links have become very common and useful and it would be super handy if they were in the default PROTOCOL_WHITELIST list.

**Steps for Reproduction**

1. Visit [quilljs.com](https://quilljs.com/) and then on the example editor highlight a word
2. Click the chain/add a link button
3. Enter in a url like `sms:+1-555-555-5555`
4. Click save
5. Click back on the word as to edit the link and it now says: `about:blank`

**Expected behavior**:

The link would be valid and remain as: `sms:+1-555-555-5555`

**Actual behavior**:

The link is removed as placed and now is: `about:blank`

**Platforms**:

all

**Version**:

v1.3.6

**Comment by digit81** [comment]
I am interested in this too. There is waiting PR for this: https://github.com/quilljs/quill/pull/2851

For now this solution works:
https://github.com/quilljs/quill/issues/262#issuecomment-948890432

**Comment by benbro** [comment]
sms was added:
https://github.com/quilljs/quill/blob/develop/packages/quill/src/formats/link.ts#L7
