### ISSUE TITLE
quill.updateContents(delta) getting error

### ISSUE THREAD

**Issue by samshaikh737** [quilljs/quill#3438]
When i use this module then throwing this error : **TypeError: listeners[i].fn.call is not a function**

TypeError: listeners[i].fn.call is not a function
Emitter.emit
file url :- **node_modules/quill/dist/quill.js:
error line : 8665 case 4: listeners[i].fn.call(listeners[i].context, a1, a2, a3); break;

**Comment by benbro** [comment]
Please fill the issue template and test with [v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2)
