### ISSUE TITLE
How to set editor content with html style

### ISSUE THREAD

**Issue by saminlu** [quilljs/quill#3439]
**Expected behavior**: set HTML content with style

**Actual behavior**: css filter

**Platforms**: windows

Include browser, operating system and respective versions

**Version**:    "vue-quill-editor": "^3.0.6",
    "quill": "^1.3.6",

I have an issue,that how to set HTML content with style, the editor filter change to p tag and no style="" ,
like insert div and table tr td  tag,
clipboard.dangerouslyPasteHTML doesn't work, what could I do?

**Comment by benbro** [comment]
https://quilljs.com/guides/how-to-customize-quill/
