### ISSUE TITLE
【help】how get element start and end index by selection index

### ISSUE THREAD

**Issue by SilvaQ** [quilljs/quill#3441]
Here's what happened to me：
 I have an element that looks like this：
 `hello  <b class="ql-custom-format">world</b>`.

Questions as follows：
When the mouse clicks on the o character position in world：
1. How do I determine if the position I clicked is the content of the ql-custom-format element？【event.target ===ql-custom-format ?】
2.  How do I get the start index and end index of the ql-custom-format element?

note:
my requirement is for the proofreading system. When the user clicks, I have to judge whether the word is grammatically incorrect, so I need to judge who the element is. The other thing is, when the user selects the recommendation word, I have to reformat the contents of the element and this is formatText and I need an index and a length argument so I need to know the actual index of the current element and its inndertext.length

**Comment by Lpmvb** [comment]
Maybe you can `addEventListener` on custom custom bolt

**Comment by SilvaQ** [comment]
> Maybe you can `addEventListener` on custom bolt

I wanted to do it with quill's ideas and utility classes, but I couldn't do it so I used DOM.
thanks
