### ISSUE TITLE
How to make a line separator ?

### ISSUE THREAD

**Issue by jhonnatanBezerra** [quilljs/quill#3448]
is it possible to take the size of the text editor and use that size to place a divider (---------), the size of the line space I have available?

It would be like putting an underline the length of the editor's size. I want to do this to use as a line separator.

like this line below
#

**Comment by CodeSmith32** [comment]
https://github.com/slab/quill/issues/434#issuecomment-2412568053

**Comment by CodeSmith32** [comment]
> [@CodeSmith32](https://github.com/CodeSmith32) It doesn't work smoothly when I move with arrows, left or right. Do you have any ideas how to bypass it?

@michalgrzegorczyk-dev 

Yeah.. frankly it's pretty rough in my editor too... it also appears to be impossible to remove a line separator added at the end of the contents. :-/  I'll probably work on it more at some point and update my code.
