### ISSUE TITLE
Text replacement via user selection in inline code block causes entire paragraph to be lost along with focus

### ISSUE THREAD

**Issue by sufian-slack** [quilljs/quill#3450]
**Steps for Reproduction**

1. Visit https://jsfiddle.net/yoa5hp91/
2. Using the keyboard (shift + arrow keys) or the mouse, make a text selection starting from the beginning of the inline code to the end of the inline code plus the following space character. i.e. if you were to look at the plain text copied as a string, you would see "inline code ".
3. Press any letter (like `a`) on the keyboard to replace the selected text with the letter you have typed

**Expected behavior**:

I would expect the selected text to be replaced with the letter pressed on the keyboard, with either the text to keep the formatting of the inline code block, or have the formatting of the surrounding text.

**Actual behavior**:

The entire second paragraph is lost from the DOM and focus is lost. Attempting to undo this action (ctrl-Z or cmd-Z) will cause only a portion of the text to be restored.

Here's a screen capture showing selection via mouse, keypresses, and the undo behavior (on a Mac, using Chrome 93)
![repro](https://user-images.githubusercontent.com/40609951/133854800-6a198e2e-dab3-471a-a170-5c162cffbee5.gif)

**Platforms**:

Tested on on:
* FAIL - MacOS Big Sur 11.6 - Chrome: Version 93.0.4577.82 (Official Build) (x86_64)
* FAIL - MacOS Big Sur 11.6 - Safari: Version 14.1.2 (16611.3.10.1.6)
* PASS - MacOS Big Sur 11.6 - Firefox: 92.0 (64-bit)
* FAIL - Windows 10 - Chrome: Version 93.0.4577.82 (Official Build) (64-bit)
* FAIL - Windows 10 - Edge: Version 93.0.961.52 (Official build) (64-bit)
* PASS - Windows 10 - Firefox: 92.0 (64-bit)

Firefox works as expected on both Windows and MacOS (the replaced text is formatted as an inline code block)

**Version**:

Quill version: 1.3.6

Also verified bug still remains on 2.0.0-dev.0 on Chrome.

**Comment by darbentov** [comment]
+1

**Comment by darbentov** [comment]
@sufian-slack Did you find a solution for that? I'm facing a similar issue https://github.com/quilljs/quill/issues/3522

**Comment by sufian-slack** [comment]
Unfortunately no, haven't spent the time on this. If you happen to come across a fix please let me know!

**Comment by luin** [comment]
Fixed in https://github.com/quilljs/quill/pull/3807. Feel free to let me know if there is anything missing. Closing
