### ISSUE TITLE
How to import the content from the HTML file into Quill editor?

### ISSUE THREAD

**Issue by ghost** [quilljs/quill#3453]
Hi everyone!

I was trying to import the content from the HTML file into Quill editor, is there any possible approach for this?
For example, I have an HTML file contains a template of the form, I want to import it into Quill editor so that the user can fill in the form with information.

Thank you in advance!

**Comment by Lpmvb** [comment]
quill.clipboard.dangerouslyPasteHTML(html);

**Comment by benbro** [comment]
Answered.
