### ISSUE TITLE
Support for changing case (uppercase to lowercase or vice versa)

### ISSUE THREAD

**Issue by RanjanaLokanathan** [quilljs/quill#3454]
We use the quill formats for our custom attribute but one of the options missing is the ability to change the case (for eg Upper case to lowercase)
for eg like in Word Aa
https://github.com/quilljs/quill/tree/9cf0285caa6514356a7bba9db132ec7229eb254c/formats

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**:

**Actual behavior**:

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
You can add custom button with a custom format:
https://quilljs.com/guides/how-to-customize-quill/
