### ISSUE TITLE
When typing Chinese text does't work after the embed blot

### ISSUE THREAD

**Issue by msidolphin** [quilljs/quill#3458]
**Steps for Reproduction**

Please check the video

https://user-images.githubusercontent.com/26672484/136727304-e639f9fa-0631-4800-afa8-fd353c30c0e1.mp4

The official website has the same problem

https://user-images.githubusercontent.com/26672484/136726890-10b4702b-ee74-4bf1-a106-82a18164006c.mp4

**Expected behavior**:

**Actual behavior**:

**Platforms**:

MacOS Mojave 10.14.6
Chrome (94.0.4606.81 release)

Include browser, operating system and respective versions

**Version**: 1.3.7

Run `Quill.version` to find out

**Comment by msidolphin** [comment]
```js
create(data) {
  const node = super.create()
  node.setAttribute('contenteditable', 'false')
  node.innerHTML += data.value
  return node
}
```
This problem was solved when I set `contenteditable` to false

**Comment by mqliutie** [comment]
> ```js
> create(data) {
>   const node = super.create()
>   node.setAttribute('contenteditable', 'false')
>   node.innerHTML += data.value
>   return node
> }
> ```
> 
> This problem was solved when I set `contenteditable` to false, but it will lead to unable focus

我这儿咋没遇到不能focus呢...

**Comment by msidolphin** [comment]
To be precise, it is difficult to focus

> > ```js
> > create(data) {
> >   const node = super.create()
> >   node.setAttribute('contenteditable', 'false')
> >   node.innerHTML += data.value
> >   return node
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This problem was solved when I set `contenteditable` to false, but it will lead to unable focus
> 
> 我这儿咋没遇到不能focus呢...

To be precise, it is difficult to focus, of course this could also be due to different environments

**Comment by OldDream** [comment]
If we moniter selection-change event, we can found the Range.index was wrong if we click inside a embed item, the index is 1 smaller than actual  !!!

**Comment by mqliutie** [comment]
> To be precise, it is difficult to focus
> 
> > > ```js
> > > create(data) {
> > >   const node = super.create()
> > >   node.setAttribute('contenteditable', 'false')
> > >   node.innerHTML += data.value
> > >   return node
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This problem was solved when I set `contenteditable` to false, but it will lead to unable focus
> > 
> > 
> > 我这儿咋没遇到不能focus呢...
> 
> To be precise, it is difficult to focus, of course this could also be due to different environments

I have met a case.  If only mention in the editor,  focus area depend on what element you used
If you are using input element, that area is ok, but if you are using the button the area only one line.
I must inset blank space to spread the area.

**Comment by msidolphin** [comment]
> I got the same bug. I transform embed to an img to fix and it did work.

There is no problem with the dev branch

**Comment by mqliutie** [comment]
[](https://storage.cloudconvert.com/tasks/51c7b4d2-a536-4fb6-81d2-cbacbf914af6/quill.mp4?AWSAccessKeyId=cloudconvert-production&Expires=1656128337&Signature=e5trwD16U7VT7JWafUP6TaO5Odo%3D&response-content-disposition=inline%3B%20filename%3D%22quill.mp4%22&response-content-type=video%2Fmp4)

**Comment by liu594453801** [comment]
> > I got the same bug. I transform embed to an img to fix and it did work.
> 
> There is no problem with the dev branch

This is only temporarily fix the problem，if delete img, It still comes up

The official team did not resolve it。

**Comment by liu594453801** [comment]
> > I got the same bug. I transform embed to an img to fix and it did work.
> 
> There is no problem with the dev branch

This is only temporarily fix the problem，if delete img, It still comes up

The official team did not resolve it。

**Comment by minzhang2** [comment]
> > I got the same bug. I transform embed to an img to fix and it did work.
> 
> There is no problem with the dev branch
How did you solve it in the end?

**Comment by minzhang2** [comment]
> How did you solve it in the end?

How did you solve it in the end?
