### ISSUE TITLE
Reinit toolbar

### ISSUE THREAD

**Issue by yaroslavputria** [quilljs/quill#3461]
Hi All,

Is there a way to reinit (reuse) toolbar (tie quill native handlers to new editor instance; remove old listeners)?

Relates to https://github.com/quilljs/quill/issues/3409. I need also to destroy the editor.

**Comment by lucychen0103** [comment]
Did you solve this?

**Comment by pwFoo** [comment]
I tried to disable / destroy quill and re-enable... but seems not to work fine. 
No way to clean remove / destroy and re-create quill?
