### ISSUE TITLE
Use both: bullets and headings to the same text

### ISSUE THREAD

**Issue by alejandrocoding** [quilljs/quill#3462]
When I use bullets, I can not combine them with headings.

**Steps for Reproduction**

I click on the toolbar for bullet style, and format the text with "normal" style. I use heading 1 and click on bullets, and remove the bullet and indentation and apply headings.

**Expected behavior**:
Is there any way to combine both?

**Actual behavior**:
Either one or the other, not both at the same time

**Platforms**:
Web (Using it with ngx-quill in Angular but it is not related to that wrapper, rather to the library, I think)

**Version**:
1.3.7

Thanks for this library, and sorry if I missed something related to the issue, did not find anything in doc, code or SO.

**Comment by regnoh** [comment]
`Header extends  Attributor` instead of Block? (eg: change `<h1>header1</h1>` to `<li data-header="1"> header1</li>`
