### ISSUE TITLE
How to edit link text

### ISSUE THREAD

**Issue by Julian367** [quilljs/quill#3468]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

https://user-images.githubusercontent.com/7355974/138476558-9ee0dc0c-a332-4f00-b19b-9df1b6a7f7c3.mov

**Expected behavior**:
Modify link text by deleting and write again

**Actual behavior**:
After delete text from inside <a> </a>, new text go outside link

**Platforms**:
MacOs Google Chrome
Include browser, operating system and respective versions

**Version**:
1.3.6
Run `Quill.version` to find out

**Comment by markleppke** [comment]
Quill, aslo take a look here: https://github.com/quilljs/quill/issues/2277#issuecomment-1029084120

The UX in the above comment could address this  issue as well. Clicking on the link would allow a user to edit the display text....
