### ISSUE TITLE
cannot set height bounds on quill

### ISSUE THREAD

**Issue by adamskwersky** [quilljs/quill#3469]
When setting Quill bounds, editor still extends past the bottom. This is because the editor height is 100% and the toolbar takes up height as well. So the editor will always extend past the parent bounds when a toolbar exists.

**Steps for Reproduction**

1. Visit https://codepen.io/adamskwersky/pen/xxLRMdJ
2. Notice how editor has extended past the parent DOM's container

**Expected behavior**:
Editor should stay within the parent DOM's bounds.

**Actual behavior**:
Editor extends beyond it when there is overflow. 

**Platforms**:
NA

Include browser, operating system and respective versions
Chrome and FireFox at least
latest at time of writing FF 93.0
Chrome 95.0.4638.54

**Version**:
"1.3.6"

Run `Quill.version` to find out

**Comment by adamskwersky** [comment]
Any progress on this?

**Comment by adamskwersky** [comment]
ping

**Comment by winterlimelight** [comment]
I had the same problem and removing the height: 100% from .ql-container solved it.

**Comment by benbro** [comment]
Answered.

**Comment by adamskwersky** [comment]
> I had the same problem and removing the height: 100% from .ql-container solved it.

The codepen above does NOT have 100% height in the .ql-container.

**Comment by adamskwersky** [comment]
> Answered.

Why did you close this? The question was not answered. See the codepen. There is no 100% style in the ql-container and the issue is still there.

**Comment by luin** [comment]
I think it's a general CSS question instead of a Quill issue. There are many ways to fix the issue. You can either move the height setting to .ql-editor: https://codepen.io/luin/pen/RwObyxR, or make the outer container a flex container and set the min-height of the quill container.

Closing. Feel free to open a new ticket if you think there are anything need to do on Quill side.
