### ISSUE TITLE
SVG with use href inside causes the tab to crash when a sibling quill editor is focused

### ISSUE THREAD

**Issue by pat-son** [quilljs/quill#3470]
This is probably an issue with Chrome, since it's a regression from the last browser version, but since it doesn't happen with plain contenteditables (only reproducible using Quill), I figured it'd be best to report here as well. Here's the issue in the Chrome bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1262589

**Steps for Reproduction**

1. Visit https://stackblitz.com/edit/web-platform-gv9ixw?file=index.html
2. Focus the quill editor

**Expected behavior**:
Browser doesn't hang

**Actual behavior**:
Browser tab hangs like it's caught in an infinite loop

**Platforms**: Windows 10, Chrome 95.0.4638.54

**Version**:  Demo is using v1.3.6, but it also happens in v2.0.0-dev.4

**Comment by benbro** [comment]
Linked Chrome issue is marked as fixed.
