### ISSUE TITLE
drag drop image flie into Editor

### ISSUE THREAD

**Issue by mdg6496** [quilljs/quill#3476]
I was following "https://quilljs.com/playground/" to see if I can drag image file into editor container.
But only Firefox would display the dragged-dropped image file inside editor-container.

**Expected behavior**:
drag-drop image would work on Chrome/Firefox/Edge

**Actual behavior**:
only Firefox would display dragged image inside editor-container

**Platforms**:
Chrome/Firefox/Edge

**Version**:
current version.

**Comment by rahultrivedi180** [comment]
you can bind `paste` event handler in quill instance.
for example:
```js
editor.root.addEventListener('paste', (e) => {
    // handle pasted content
})
```

**Comment by benbro** [comment]
Please look here:
https://github.com/quilljs/quill/issues/3476
