### ISSUE TITLE
Bug when inserting image in empty instance 

### ISSUE THREAD

**Issue by cphyc** [quilljs/quill#348]
When you copy and paste an image into an **empty** instance of quill, the delta that results is then
```
{ ops : [
          { retain: 1, attributes: {image: "http://someurl.com/image"}},
          { insert:  "↵", attributes: {image: "http://someurl.com/image"}}
        ]
}
```

**Comment by jhchen** [comment]
Can you give more details about how you are copying/pasting? I tried to just highlight an image on a web page and pasting it into Quill and do not get the same results. Also what OS/browser are you using?

**Comment by cphyc** [comment]
It seems that I can't reproduce the bug anymore, I'm marking the issue as closed, I'll reopen it if I succeed in recreating the bug.
