### ISSUE TITLE
Paste on editor stops propagation when disabled. 

### ISSUE THREAD

**Issue by khizarmanzoor** [quilljs/quill#349]
On disabled editor state. paste (more specifically image-data in clipboard) stops event propagation. 
I looked into code which internally checks for valid range first if range (getSelection) returns nothing the paste handler immediately returns. which causes the event propagation stop. 

In my view the fix would be simple if we 'return true;' instead of 'return'. 

This bug exists in v0.19.10

**Comment by jhchen** [comment]
How are you pasting into an uneditable editor?

**Comment by jhchen** [comment]
Feel free to comment and/or reopen if this is still an issue.
