### ISSUE TITLE
add quill editor to angular app

### ISSUE THREAD

**Issue by guypeled1** [quilljs/quill#3495]
Hi,
How can i add quill editor to angular app?

Thanks,
Guy

**Comment by medi6** [comment]
Hi, you can use ngx -quill

**Comment by guypeled1** [comment]
there is a problem with ngx-quill and my angular version

**Comment by medi6** [comment]
Which version do you use ? You can also try old ngx quill versions.

**Comment by marcosox** [comment]
The compatibility table between the `ngx-quill` version and the Angular version is shown in the [ngx-quill readme](https://github.com/KillerCodeMonkey/ngx-quill/#compatibility-to-angular-versions), but if you're using quill v2, then ngx-quill [does not support it](https://github.com/KillerCodeMonkey/ngx-quill/issues/544).

**Comment by benbro** [comment]
Answered.
