### ISSUE TITLE
Mention throws TypeError s.domNode.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by emmaadesile** [quilljs/quill#3496]
Trying to mention users with `@` character in the quill editor throws `TypeError s.domNode.getBoundingClientRect is not a function` in the console and the suggestions are not shown.

**Steps for Reproduction**
The error is a little tricky to reproduce as only a few of my company's clients occasionally experience the issue on production.
**screenshot below**
<img width="384" alt="Screenshot 2021-12-01 at 16 08 57" src="https://user-images.githubusercontent.com/26192691/144259824-4274123f-bdaa-48e1-bdab-9feb4760e99f.png">

**Expected behavior**:
The mention feature  should show the suggestions

**Actual behavior**:
The following error is thrown in the console and the suggestions don't work
```
TypeError
s.domNode.getBoundingClientRect is not a function
```

**Platforms**:
```
browser: Chrome 95.0.4638
device: Mac
os: Mac OS X 10.15.7
```
@jhchen @byronm I'll appreciate it if you could look into this. Thanks.

**Comment by benbro** [comment]
Quill Mention is a third-party module.
