### ISSUE TITLE
How to get the position of the cursor on the screen？

### ISSUE THREAD

**Issue by xuergo** [quilljs/quill#3502]
![image](https://user-images.githubusercontent.com/46159623/145668147-ff31f6b3-8507-4242-9eb8-9c3772ebb367.png)
I need the height to grow automatically while keeping the cursor in the viewing area,But I don't know if I can make it happen🙏🙏🙏

**Comment by Hanho-Kim** [comment]
There is a cursor blot in quill core. You can use like this:

```typescript
findCursorPosition(index){
    this.quill.insertEmbed(index, 'cursor', {}, Quill.sources.SILENT); // Create cursor blot at your desired index (your current index)
    const cursor = document.querySelector('.ql-cursor'); // Find cursor element
    if(cursor) {
      console.log(cursor.getBoundingClientRect()); // Get position
      cursor.remove(); // Remove cursor
    }
}
```

**Comment by benbro** [comment]
https://quilljs.com/docs/api/
