### ISSUE TITLE
How to drag and drop blocks in quill

### ISSUE THREAD

**Issue by Codes-Breaker** [quilljs/quill#3507]
I am trying to build a block-like RTE based on quill. I figured out how to get the index of block by using
`						let blotFrom = this.parchment.find(fromNode);
						let blotTo = this.parchment.find(toNode);
						let fromIndex = blotFrom.offset(this.quill.scroll);
						let toIndex = blotTo.offset(this.quill.scroll);
`
however, how should I insert blotFrom before blotTo? Any official way of doing it? Thanks
drag & drop, Insertion example: 
![image](https://user-images.githubusercontent.com/10660055/147220679-716b5ad9-fe0a-4e97-96ec-4773be48f8d3.png)

**Comment by Codes-Breaker** [comment]
for example, I have the index of blots, can I remove it or insert it?

**Comment by Codes-Breaker** [comment]
solved

**Comment by jackcarlisle** [comment]
@Codes-Breaker what was your solution to this? I'm looking to add this functionality to my RTE
