### ISSUE TITLE
Full corner English input is invalid

### ISSUE THREAD

**Issue by hyp5417** [quilljs/quill#3508]
Hey, guys. Input full corner English in the content box, cannot trigger the built-in function, placeholder content still exists.But using the 360 or Sogou browser is fine.I think there are some browser compatibility issues.

**Use tools version:**
1.Google Chrome (5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36')
2. quill (2.0.0-dev.3)

**Comment by johnmanko** [comment]
This maybe be the same issue I'm having.  

https://github.com/quilljs/quill/issues/3512

**Comment by hyp5417** [comment]
oh man, so, how do you do that?

**Comment by hyp5417** [comment]
I think that is a bug of the quill dev2.0. But the quill 2.0 previous version not exist this question.

**Comment by johnmanko** [comment]
@hyp5417 Not sure.  I don't have time to dig into the quill source right now, so I'm hoping a regular contributor will pick on this.  It's a very serious bug.

**Comment by benbro** [comment]
Please test [v2.0.0-beta.1](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.1)
https://v2.quilljs.com/standalone/full
