### ISSUE TITLE
How to get the subscript of the cursor position？

### ISSUE THREAD

**Issue by dajun1230** [quilljs/quill#3509]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**
I want to insert text at the specified position of the cursor, but I can't find the API to get the position of the cursor

**Expected behavior**:

**Actual behavior**:

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
https://quilljs.com/docs/api/#getselection
