### ISSUE TITLE
setContents visual glitch

### ISSUE THREAD

**Issue by MartinMalinda** [quilljs/quill#3515]
sometimes when I do setContents, some changes can be seen in the editor

1) text appears (insert operation?)
2) text disappears (delete operation?)
3) text appears again

It's very quick but it gives a strange feeling.

It seems like Quill is wasting some extra work here, possibly updating the DOM multiple times, step by step, instead of somehow consolidating the delta and doing one DOM update.

Are there any mitigations to this issue?

Is there some smart possibility to merge the delta into as less operations as possible if I don't care about history?
Is it possible to know when `setContents` is done, so maybe I can visually hide the content before it's finished?

Thanks for any pointers!

**Comment by ParsaYadollahi** [comment]
Any updates on this? Still experiencing this bug where the text is flickering when entering text quickly from setContent

**Comment by benbro** [comment]
Please test with [v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2) and share the steps to reproduce this issue.

**Comment by benbro** [comment]
Please reopen with exact steps to reproduce on v2 if you still experience this issue.
