### ISSUE TITLE
How to remove the autoformatting from button?

### ISSUE THREAD

**Issue by Codes-Breaker** [quilljs/quill#3517]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**
![image](https://user-images.githubusercontent.com/10660055/149289611-583fb144-ee45-4830-bbf6-9f9bca90338d.png)

I want to remove auto-formatting after its been handle? Any way or api to do this?

**Expected behavior**:

**Actual behavior**:

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by Codes-Breaker** [comment]
I tried:
			var select = quill.getSelection();
			if (select) {
				if (select.length == 0){
					quill.formatText(select.index, 1, 'action', false);
				}
                          }
but it is not working...

**Comment by benbro** [comment]
https://quilljs.com/docs/quickstart/
