### ISSUE TITLE
Problem with bubble theme, no display

### ISSUE THREAD

**Issue by member101** [quilljs/quill#3520]
Hello,

I have a problem with the bubble theme of quill, I have all install via the cdn and when I select my text, the toolbar takes the right position but the display remains on none, as shown in the gif. How to fix this please?

[gif](https://ibb.co/Pz7N5Nk)

gif available for one month

**Comment by benbro** [comment]
Please the issue template and test with [v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2)
