### ISSUE TITLE
What's the status of this project?  It's been over 2 years since 1.3.7 release.

### ISSUE THREAD

**Issue by johnmanko** [quilljs/quill#3521]
It's been 2 years and 4 months since Quill 1.3.7 was released.  I don't even know if the npm package `quill` is an official package, but it doesn't provide the 2.x dev releases.

What's the status of this project?

**Comment by usernamedd** [comment]
when i am trying to build on ubuntu 20 and npm 17,it failed .maybe it is dead

**Comment by robrez** [comment]
This has been asked before, https://github.com/quilljs/quill/issues/3359

Consider:  1.3.7 was a relatively small security update.  1.3.6 was vended 4 years ago.  2.x.x rc was first published 4 years ago, too; and still no official 2.x release.

I have seen a few maintainer comments and some  commits that would indicate that there is at least some activity.

**Comment by usernamedd** [comment]
> 

just showing it is active ,nothing more . PRs are not accepted or other things indicate that the maintainers are so busy.

**Comment by noncer** [comment]
https://quilljs.com/ says Linkedin Salesforce Slack Airtable use QuillJS.  Would be nice if those companies paid for developer time to clear the backlog

**Comment by nullpaper** [comment]
> https://quilljs.com/ says Linkedin Salesforce Slack Airtable use QuillJS. Would be nice if those companies paid for developer time to clear the backlog

This was true years ago. It is no longer true. Quill is abandonware.

**Comment by benbro** [comment]
Quill is under active development.
https://github.com/quilljs/quill/tags
