### ISSUE TITLE
Issue with Syntax module - when trying to replace a highlighted text, the text gets deleted

### ISSUE THREAD

**Issue by darbentov** [quilljs/quill#3522]
Hi, I'm using the Syntax module in order to do syntax highlighting of code blocks.
I stumbled upon an issue where I'm trying to replace a highlighted text with a different text, the text gets deleted.

Link to demo:
https://codesandbox.io/s/quill-with-syntax-highlighting-bug-when-trying-to-replace-an-highlighted-text-x5uw9?file=/src/syntax.js

Steps to reproduce:

1. Write `console.log("hi");` inside the quill editor
2. Click on the "code" formatting
3. Select the highlighted text
4. Press any letter instead
5. The text will get deleted.

![image](https://user-images.githubusercontent.com/12782209/149924570-2a010ba1-575e-4cee-8c01-cd12c19aaa28.png)

![image](https://user-images.githubusercontent.com/12782209/149924630-cfaab4cf-72a8-478a-9734-1c1986f708d3.png)

This is the result after typing "a":
![image](https://user-images.githubusercontent.com/12782209/149924663-a21c7dc2-d3ce-4d8b-a042-16991edbeb07.png)

**Comment by ronzip** [comment]
+1

**Comment by luin** [comment]
Fixed in https://github.com/quilljs/quill/pull/3807. Feel free to let me know if there is anything missing. Closing
