### ISSUE TITLE
Problem with RTL

### ISSUE THREAD

**Issue by kamilpalka801** [quilljs/quill#3528]
Hi, I found a problem with rtl text. When I write something between the rtl texts this text changes the order.
**Examples:**
Before: نص بسيط
After: نصTEST بسيط

**Steps for Reproduction**
> 1.Run Quill
> 2.Write something in Arabic
> 3.Write something on the non rtl between the text

**Expected behavior:**
The text does not change the order

**Actual behavior:**
The text changes order, making the text lose its meaning

**Platforms**: Windows 10 and Ubuntu 18.04
Include browser, operating system and respective versions

**Version**: 1.3.6
Run Quill.version to find out

**Comment by benbro** [comment]
Use the text align and text direction buttons. The 19th and 20th buttons in [this toolbar](https://quilljs.com/docs/formats/).
