### ISSUE TITLE
Ordered lists are not resetting properly. 

### ISSUE THREAD

**Issue by BryceV** [quilljs/quill#3529]
When you try to use ordered lists with html2pdf the top-level counter is not incremented (shows 1 across the board). The sub lists do increment. I tracked down the fix for resetting the counter and it looks like it was added in the beta version:
https://github.com/quilljs/cdn/blob/424b3ac9a24cd43d83be2e3c4769282064a1db9d/2.0.0-dev.0/quill.snow.css#L70

I have seen discussion about handling lists differently (https://github.com/quilljs/quill/issues/979) but until then, this would be a small fix that would help out people exporting their editor content. 

**Version**: 1.3.7^

**Comment by benbro** [comment]
Please test [v2.0.0-rc.0](https://github.com/quilljs/quill/releases/tag/v2.0.0-rc.0)
https://v2.quilljs.com/standalone/full/
