### ISSUE TITLE
After button clicked event how should I control the 'onChange' and 'onFocus' event in react quill

### ISSUE THREAD

**Issue by WinniePooh04** [quilljs/quill#3537]
Hello anyone please help me to solve this issue?

> <ReactQuill
            theme="snow"
            onChange={handleOnChange}
            onFocus={handleOnFoucs}>

I've used quill like above and whenever I clicked the cancel button it's go to the function of handleOnChange and then to handleOnFocus function. 
For me when I clicked cancel button clear the editor content and the cursor is not focus on quill editor. 
But now when I clicked cancel button can clear the editor content but the cursor is auto on focus on quill editor.
How should I solve this issue? Kindly please help me. Thanks.

**Comment by benbro** [comment]
Not related to core quill.
