### ISSUE TITLE
Format config options missing from the docs

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#354]
The API doc for addFormat is missing the config options.
http://quilljs.com/docs/api/#quillprototypeaddformat
http://quilljs.com/docs/formats/

format.coffee has the following options:
https://github.com/quilljs/quill/blob/develop/src/core/format.coffee
tag
prepare
style
default
add
remove
value
attribute
exclude
parentTag

Thanks

**Comment by jhchen** [comment]
Thanks for pointing out the gaps in the docs. The custom formats
