### ISSUE TITLE
[Discussion] Status of Quill?

### ISSUE THREAD

**Issue by bwong365** [quilljs/quill#3542]
Hey, just wondering what the status of Quill is these days? Is it worth trying to use the v2 branch in prod?

**Comment by FredJoly** [comment]
I only discovered this repo yesterday, so take this with a big grain of salt. I just tried building the package, and NPM "found 266 vulnerabilities (4 low, 103 moderate, 138 high, 21 critical)". After running the audit fix:

fixed 228 of 266 vulnerabilities in 1453 scanned packages
  1 vulnerability required manual review and could not be updated
  6 package updates for 37 vulnerabilities involved breaking changes

Personally, I don't think I'm going to risk it. Our organisation was hit with a cyberattack recently that knocked us on our ass, and the last thing I want to do is add more vulnerabilities to our system.

**Comment by zedtux** [comment]
While version 1.x looks quite bad:
![Screenshot 2022-03-03 at 09 30 20](https://user-images.githubusercontent.com/478564/156526632-0cca2c83-d566-4897-9cc1-689da94da76d.png)


Version 2 is in a better shape ... but is not finished :
![Screenshot 2022-03-03 at 09 29 28](https://user-images.githubusercontent.com/478564/156526365-da0d4eb1-d469-4b31-a9cf-f16a068e1f92.png)

**Comment by EricDitp** [comment]
would be nice to have a version with fix for
https://github.com/advisories/GHSA-4943-9vgg-gr5r

**Comment by pmweeks98** [comment]
@zedtux is quill 2 available (and where)? Using 'latest' on package.json uses 1.3.7

Its been a long time since last release

**Comment by zedtux** [comment]
There's only a [v2.0.0-dev.0](https://github.com/quilljs/quill/tree/v2.0.0-dev.0) tag so far.

**Comment by benbro** [comment]
Quill is under active development.
https://github.com/quilljs/quill/tags
