### ISSUE TITLE
Add costum Toolbar action to Quill in Remix (React)

### ISSUE THREAD

**Issue by KesSaft** [quilljs/quill#3546]
Hey,
I want to add a new action to the toolbar with costume icon.
I want that when pressing the button, the selected text should be wrapped in an HTML Tag (<kbd></kbd>) like when clicking Bold.
I have found multiple different approached on the web, but some don't work.

I use Remix (Like React) and the quill library installed with npm.

Thanks!

**Comment by benbro** [comment]
Please follow the [v1.3.7 docs](https://quilljs.com/docs/quickstart/) or [v2.0.0.-beta.1 docs](https://v2.quilljs.com/docs/quickstart).
