### ISSUE TITLE
Operation transformation apply deltas to server side

### ISSUE THREAD

**Issue by deepsyx** [quilljs/quill#355]
I'm using Quill.js together with socket.io/nodejs on backend. Quill has events for deltas, so I can send the deltas to all clients and create Collaborative editor.

I'm using https://github.com/ottypes/rich-text plugin for backend and my question is how I can apply deltas to backend document.
I can do this in Quill by doing `editor.updateContents(deltas_array)` and current content will be updated with the incoming deltas.

I've searched through whole rich-text plugin documentation, but I couldn't find a feature to apply deltas to a document.

**Comment by jhchen** [comment]
I've answered this question on the rich-text issues where it was also posted.
