### ISSUE TITLE
open pdf file using quill editor

### ISSUE THREAD

**Issue by krishnamoorthy51** [quilljs/quill#3551]
how to show the pdf file quill editor is that possible ??
i am having a custom toolbar to pick a file but i cant able to show the picked pdf file how can i achieve that

**Comment by regnoh** [comment]
upload the pdf and then show something like <a href="path/to/pdf" target="_blank"> in editor, click to show pdf with browser?

**Comment by benbro** [comment]
You'll need to create a custom blot for the pdf.
https://quilljs.com/guides/how-to-customize-quill/
