### ISSUE TITLE
How to set custom font handler

### ISSUE THREAD

**Issue by iviju** [quilljs/quill#3554]
Is there any way to quilljs to change how setting fonts are handled. I want font be set document level instead of element level, so full text have the same font, I could find any way to do it. I tried to do using text-change event but it was not triggered when font is set.

```
quill.on('text-change', function(delta, oldDelta, source) {
  console.log('font changed');
})
```

**Comment by benbro** [comment]
You can keep track of the last font used in a variable. In the text-change handler check if the new delta has a new font different from the existing font and update the content with the API of all existing blots.
You might also consider overriding the default font toolbar handler and just changing the font with css.
