### ISSUE TITLE
clicking on the right of custom embed mess with cursor after next character is typed

### ISSUE THREAD

**Issue by printfhere** [quilljs/quill#3556]
After inserting a custom embed blot.
When you click on the blot (in the center of it) nothing happen -> OK
When you click on the right until it make the cursor appear and then type something -> the letter is correctly inserted but the cursor jump on the left of the character you just typed.

**Steps for Reproduction**

1. Visit quill.js
2. Insert a math function
3. click on the last character of the function (to make the cursor appear) and type a character

**Expected behavior**:
The character is written after the math function and the cursor is **after** the character

**Actual behavior**:
The character is written after the math function and the cursor is **before** the character

**Comment by breconwhite** [comment]
Tried the fix mentioned in https://github.com/quilljs/quill/issues/1960, but it doesn't seem to fix it for me.

**Comment by breconwhite** [comment]
I think this happens to do with the normalizedToRange function in selection.js. When clicking to the right of an embed, it selects the rightGuard, but the blot offset doesn't take the guards into account, so it never runs the index function and just returns the index of the embed. I think you could maybe override the offset in a custom blot, but I'm not sure how you would tell the rightGuard was selected.

Bit of a hack, but I was able to make a workaround by intercepting the selection-change.
```
field.on('selection-change', (range, oldRange) => {
  if (range && range.length === 0 && !oldRange) {
    const node = field.selection.getNativeRange().end.node;
    if (node && node.data?.match(/^\uFEFF$/) && node.previousSibling) {
      field.setSelection(range.index + 1, 0);
    }
  }
}
```
