### ISSUE TITLE
Where to find documentation for toolbar button options?

### ISSUE THREAD

**Issue by logany-hi** [quilljs/quill#3559]
The documentation over at https://quilljs.com/docs/modules/toolbar/ shows some but, funny enough, not the ones I want and I can't seem to find any sort of listing that shows me how to place the buttons.

I've got it worked out for image, italic and underline, but lists? Tables? Links?

Where do I find these?

**Comment by thekrotek** [comment]
I didn't find any myself, but there's a "formats" folder in distribution package which may help you.

**Comment by benbro** [comment]
The toolbar module [page](https://quilljs.com/docs/modules/toolbar/#container) does explain how to add lists and links. Tables are still not supported.
