### ISSUE TITLE
Will your package support "Navigation Pattern" like hide few options?

### ISSUE THREAD

**Issue by cm-tigeen** [quilljs/quill#3560]
We like your editor. Few options unable find in your package. 

Will your package support "Navigation Pattern" like hide few options?

https://css-tricks.com/the-priority-navigation-pattern/

Thank you,
N Chandra Mohan,
Tech Lead Web & Mobile Development,
Tigeen Computing Pvt Ltd.

**Comment by benbro** [comment]
You can use custom HTML for the toolbar:
https://quilljs.com/docs/modules/toolbar/#container
