### ISSUE TITLE
ESM build

### ISSUE THREAD

**Issue by pazooki** [quilljs/quill#3561]
when I dynamically try to import quill it gives me error "ReferenceError: Quill is not defined"
the js and css files are all loaded however there is no Quill object available.
Do you have an ESM build that i could load and use in pure javascript environment?

**Comment by eng-dibo** [comment]
```
import (`/node_modules/quill/dist/quill.js`)
.then(Quill=>console.log(Quill, Quillregister))
```

the result is `Quill: Module` but `Quill.register` is undefined

**Comment by benbro** [comment]
Please try [v2.0.0-beta.1](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.1)
