### ISSUE TITLE
cannot generate newline when input text has underline

### ISSUE THREAD

**Issue by funny99** [quilljs/quill#3567]
1.3.7
when you input on editor, the text has underline, the keyboard top has many words for you to choose. you press "Enter"，no response! it should generate a newline
see quill code:
`this.quill.root.addEventListener('keydown', (evt) => {
      if (evt.defaultPrevented) return;
      let which = evt.which || evt.keyCode;
      let bindings = (this.bindings[which] || []).filter(function(binding) {
        return Keyboard.match(evt, binding);
      });
      if (bindings.length === 0) return;`
keydown‘s e.keyCode is 229 not 13, so return, cannot run handleEnter

**Comment by benbro** [comment]
Please fill the issue template and include steps to reproduce the issue.
Please test [v2.0.0-rc.0](https://github.com/quilljs/quill/releases/tag/v2.0.0-rc.0)
