### ISSUE TITLE
How to get all the DOM elements in the selection?

### ISSUE THREAD

**Issue by Yoji** [quilljs/quill#3574]
How to get all the DOM elements in the selection?

**Comment by benbro** [comment]
You can loop over the selection and find the Blot of each position by calling [quill.getLeaf](https://quilljs.com/docs/api/#getleaf-experimental). Get the DOM element of the Blot. Check for offset == 0 to get unique Blots.
```javascript
let [leaf, offset] = quill.getLeaf(7);
```
