### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Raw2x2** [quilljs/quill#3577]
在VUE3 中使用 v-model:content="value" 结果输入框的光标一直在第一个。所以我该怎么拿到值呢？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？我该怎么获取输入框的value

**Comment by benbro** [comment]
https://quilljs.com/docs/quickstart/
