### ISSUE TITLE
changing language

### ISSUE THREAD

**Issue by hosseinghs** [quilljs/quill#3578]
Hi and well done to you for your amazing tool !
**_**I was having hard time trying to config ckeditor and magically I found quill , I installed it and then boom ! It was right there working ,**_** although there was something that was quite a bump! how can I change the language of quill to farsi ? or change the direction to rtl , you know not just by manipulating the dom!
thank you in advance

**Comment by benbro** [comment]
Quill has alignment and direction buttons in the toolbar. You can [extend](https://quilljs.com/guides/how-to-customize-quill/) it to meet your use case.
