### ISSUE TITLE
Deleting non-existing attribute results in deleting another attribute

### ISSUE THREAD

**Issue by DadaMonad** [quilljs/quill#358]
This following is true for the master & the develop branch:

Assuming `quill.getContents().ops` outputs:
```
[{
  attributes: {
    bullet: true
  },
  insert: "↵"
}]
```

In my application it may often happen that I apply the following operation:
```
{
  attributes: {
    list: null
  },
  retain: 1
}
```

Whereupon, the output of `quill.getContents().ops` is:
```
[{
  insert: "↵"
}]
```

I deleted the *bullet* attribute though, not the *list* attribute.

I avoid this issue in my application. So for me, this is low priority.

**Comment by jhchen** [comment]
This has been fixed in the [beta](http://beta.quilljs.com/) release
