### ISSUE TITLE
Focus loses when add link

### ISSUE THREAD

**Issue by dmitriantipov1** [quilljs/quill#3584]
Hello, I didn't find a solution to this problem, so I turn to you.

1. I have a logic of sending a request to the server when bluring. 
2. When I try to add a link, the focus disappears and happend a request.
![problem](https://user-images.githubusercontent.com/85520553/169646255-aab6288f-77d2-4dbe-967c-54fa9896affe.gif)

Are there any solutions to prevent this?

Using Angular **12.0.0.**
Ngx Quill **14.0.0**

**Comment by potikhanovsergey** [comment]
Have you found a solution for this?
