### ISSUE TITLE
It doesn't load images from android (APK) and on web it doesn't happen

### ISSUE THREAD

**Issue by EdissonG** [quilljs/quill#3588]
Hi,

The way I implemented Quilljs was thanks to Simon Grimm's guide on how to include rich text in IONIC, but testing on web it works, but on mobile it opens the image browser on my device I select it, and it does not upload it, and it does not indicate any error in console.

Resource of the tutorial:
[Adding a Rich Text Editor to your Ionic App [v6]](https://www.youtube.com/watch?v=4I9zmySbuMA&t=666s)

Greetings.

**Comment by Saqib92** [comment]
Have Same issue:
https://github.com/KillerCodeMonkey/ngx-quill/issues/1945
