### ISSUE TITLE
Does quill support arbitrary user-supplied HTML?

### ISSUE THREAD

**Issue by davidAtInleague** [quilljs/quill#3601]
Hi, I inherited a web app that uses Quill. It contains an assumption that Quill, with the edit-html-button, supports arbitrary user-supplied HTML (divs, styles, script, table, inline style attributes, the works). However, most everything is converted into a `<p>` tag.

e.g.
`<div style="background-color:blue;">hello</div>` --> `<p>hello</p>`

Reading about Parchment and Blot really seems to indicate that Quill does not support editing arbitrary user-supplied HTML (unless one is willing to fully re-implement the DOM in parchment/blot?); but I am wondering if there's not just some `{editArbitraryHTML: true}` option I'm overlooking?

A voice from a knowledgeable user saying "{yes,no}, this is [not] a supported feature <caveats*>" would be very helpful. Thank you for your time.

**Comment by cimenta** [comment]
somone would know the answer?

**Comment by benbro** [comment]
https://github.com/quilljs/quill/issues/128
