### ISSUE TITLE
Config option to disable key bindings for the history module

### ISSUE THREAD

**Issue by yaroslavputria** [quilljs/quill#3603]
Could you please add config option (enabled by default) for the history module to enable key bindings? - to have possibility to disable undo/redo shortcuts.

My case: I have custom sharedb undoRedo module for multiple editors - I need to have one combination of key bindings for all of the editors - even if the focus is set to a different editor, the last undo/redo should be invoked by shortcut.

**Comment by benbro** [comment]
Override the [undo and redo](https://github.com/quilljs/quill/blob/1.3.7/modules/history.js#L20) key bindings or extend the history module.
