### ISSUE TITLE
Textbox Gets Cleared Out When Trying to Replace Text that Includes Certain Formatting and Newlines

### ISSUE THREAD

**Issue by hansonwoo** [quilljs/quill#3604]
Similar to https://github.com/quilljs/quill/issues/779 & https://github.com/quilljs/quill/issues/1940

When I have editor content that includes strikethroughs or text color and new lines, and I highlight all the text (via cursor or Control + A), then I press a key in order to replace the text, it clears out the textbox. The console shows a warning from setNativeRange: 
> "addRange(): The given range isn't in document."

**Steps for Reproduction**

1. Go to https://quilljs.com/standalone/full/
2. Type "Test" and either give it strikethrough, or change the text color, or make it a code block
3. Enter a newline
4. ctrl + a and type "a" to replace all the text

**Expected behavior**:

The output should be "a" that retains the formatting of the strikethrough or text color

**Actual behavior**:

The text gets cleared out. Inspecting the console shows:

> "addRange(): The given range isn't in document."

**Platforms**:

Browser: Chrome Version 103.0.5060.66 (Official Build) (64-bit)
Operating System: Windows 11

**Version**:

1.3.7

![QuillWarningMessage](https://user-images.githubusercontent.com/31667414/176520821-3d10b89f-0241-4a35-b175-aa8252333015.PNG)

**Comment by hansonwoo** [comment]
There appears to already be a fix, but it isn't released yet

**Comment by benbro** [comment]
Fixed in [v2.0.0-rc.0](https://github.com/quilljs/quill/releases/tag/v2.0.0-rc.0)
https://v2.quilljs.com/standalone/full/
