### ISSUE TITLE
Can quill return every word from written text?

### ISSUE THREAD

**Issue by carva28** [quilljs/quill#3606]
Hi 👋 

I'm trying to access to every word written in my quill editor. My main goal is painting paint the wrong words written in red, that came from my spell correction API. So the solution that I'm thinking is compare the wrong word with the written words in quill and then detect its indexs to paiting with quill.

Is this possible with some quill method or attribute?
 
Thank you very much!

P.S.: This is part of a solution from this problem: https://stackoverflow.com/questions/72804166/spell-checker-indexes-of-wrong-words-being-mixed-quill-react-js

**Comment by benbro** [comment]
You can access the content using the [API](https://quilljs.com/docs/api/).
