### ISSUE TITLE
Allow non-http Links within quill editor

### ISSUE THREAD

**Issue by agosch** [quilljs/quill#3608]
Hi, i use quill within an Angular 13 environment as editor for html content. As a part of this i need to be able to add an anchor tag with an non-http link which look like this "companyprotocol://companyservice/newInstance&parameter={"page":"cms", "scrollTo":"scroll"}" (i needed to censor it). How can i extend the sanitize config to allow such links?

**Platforms**:

- Angular 13

**Version**:

* ngx-quill: 16.2.1
* quill: 1.3.10

**Comment by mkoestner** [comment]
Ah, I found an easy way. The whitelist can be changed in the runtime:

private Link = Quill.import('formats/link');

...

        if (this.Link.PROTOCOL_WHITELIST.indexOf('') < 0) {
            this.Link.PROTOCOL_WHITELIST.push('');
            this.Link.PROTOCOL_WHITELIST.push('file');
        }
