### ISSUE TITLE
Pasted text not recognized when selected

### ISSUE THREAD

**Issue by brettimus** [quilljs/quill#361]
**Chrome 42 on a Mac**

To reproduce: 
* Go to [quilljs.com](http://quilljs.com)
* Copy-Paste a some text into the editor (I used the phrase "Full Featured API" from the page)
* Select the text you just pasted, and click the Link icon

The link-tooltip does not load, and the cursor moves to the beginning of the selection you are trying to Linkify.

Internally, it seems like this is happening because `.getSelection()` is returning a `range` where `range.start === range.end`. To see this, select the text that you copy-pasted, and execute `quill.getSelection()` in the console.

**Comment by brettimus** [comment]
Fixed by adding `@quill.setContents(@quill.getContents())` to the `PasteManager` module's `_paste` method, immediately after [this line](https://github.com/quilljs/quill/blob/develop/src/modules/paste-manager.coffee#L33).

Not sure what kind of negative side-effects this might have, though.

**Comment by brettimus** [comment]
could i get another set of eyes on this? again, i fixed it in my own build, but want to know if what i did has any negative side-effects.

**Comment by willrowe** [comment]
I've only been able to reproduce this sporadically, so I'm not quite sure what's causing it. Have you seen this happening anywhere else besides the homepage?

**Comment by brettimus** [comment]
I plugged quill into my company's redesigned app, and the issue was brought to me by a beta tester. I reproduced it on the quill homepage for ease's sake. 




:crying_cat:



—

**Comment by jhchen** [comment]
Can you check if this is still occurring? I can consistently reproduce this with v0.19.11 but not v0.19.12. git bisect points to 51bd6683d23a4a47fd2f548f60d404adbe119925 as the commit that fixed it--which would make sense since the tooltip cannot come up without identifying the right leaf. But if it's an intermittent issue then git bisect will be thrown off.

**Comment by brettimus** [comment]
Seems fixed!
