### ISSUE TITLE
Using a spell checker in chrome removes the whole line. - "addRange(): The given range isn't in document."

### ISSUE THREAD

**Issue by Shestak2039** [quilljs/quill#3611]
This is clone for #3375, I have the same problem. Maybe anyone get around this problem? 

**Steps for Reproduction**

1. Copy some text with spelling error. for example: "hre are th msitaks".
2. Past it into the text editor and try to fix spelling using spelling checker (right click in chrome and select word).

**Expected behavior**:
The highlighted word is changed to the one selected in the spell checker
**Actual behavior**:
Еhe whole line is deleted

I'm using this package with ngx-quill.

The error is not reproducible in firefox, but is reproducible in chrome.
Chrome: Version 103.0.5060.134 (Official Build) (64-bit)

https://user-images.githubusercontent.com/33791010/180395155-9d1e7083-1fcb-4602-adb3-0a86912d3ff1.mov

**Comment by luin** [comment]
Fixed in https://github.com/quilljs/quill/pull/3807. Feel free to let me know if there is anything missing. Closing
