### ISSUE TITLE
Cursor gets disappered and user is not able to type when user click on bottom half of the textarea

### ISSUE THREAD

**Issue by karishma-grover07** [quilljs/quill#3619]
When user clicks anywhere in the bottom half of the text area, the cursor gets disappeared and user is not able to type. Looks like only the top line is clickable to place the cursor.

**Steps for Reproduction**

1. Click any where on the bottom half of quill editor's textarea.
2. Try to type anything.

**Expected behavior**: The cursor should be placed when we click anywhere in the text area and user should be able to type.

**Actual behavior**: The cursor disappears and user is not able to type into the textarea

**Platforms**:
Browser: Chrome - 102.0.5005.63
Operating system: windows 10

**Version**:
quill : 1.3.7
ngx-quill:12.0.0

**Comment by benbro** [comment]
I can't reproduce [herre](https://quilljs.com/standalone/full) or [here](https://quilljs.com/playground/).
Might be specific to ngx-quill.
