### ISSUE TITLE
Multiple 

### ISSUE THREAD

**Issue by Zacharilius** [quilljs/quill#3622]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit https://quilljs.com/playground/#autosave

2. Create a single line of text that with 2 links: Link A and Link B. Add Link A to the start of your line. Make a really long second link, Link B, that wraps to the next line in the when saving the page to pdf.

<img width="559" alt="PicOfQuillEditor" src="https://user-images.githubusercontent.com/3036743/183147921-d7a710ac-540a-4c64-bf57-72e5619b2360.png">

3. In Google Chrome, File -> Print.. -> Set Destination to "Save as Pdf" -> Click "Save"

**Expected behavior**:

1. Only the links should be clickable.

**Actual behavior**:

The entire line of text all links to link B

<img width="960" alt="PicOfSaveToPdf" src="https://user-images.githubusercontent.com/3036743/183147951-06668e45-7cd3-486c-98b8-eee00c44f48d.png">

**Platforms**:

* Mac OS Monterey
* Google Chrome Version 103.0.5060.134 (Official Build) (x86_64)

**Version**:

quill 1.3.6

**Comment by benbro** [comment]
You can check if it works differently with [v2.0.0-beta.1](https://v2.quilljs.com/standalone/full) but "Save as Pdf" is a browser feature out of scope of Quill.
