### ISSUE TITLE
displaying [object, object] instead of icon on toolbar

### ISSUE THREAD

**Issue by LEDMann** [quilljs/quill#3628]
probably just a me problem but i need help

**Steps for Reproduction**

create a new laravel 9 project
download quill bootstrap and jsignature (might be incompatabilities)
setup vite
put "import Quill from 'quill/quill'; window.Quill = Quill;" in app.js
put "@import "quill/dist/quill.core.css";" ikn whatevery file is used to compile css
try to use quill

**Expected behavior**:
what is in the docs

**Actual behavior**:
no icons are being displayed on the toolbae and for lists and indents it only displays [object, object]

Include browser, operating system and respective versions
on firefox but tested on chrome same result, win10

**Version**:
1.3.6 in package-lock.json and displays dev running Quill.version in console

(textbox does work its the toolbar)
![image](https://user-images.githubusercontent.com/110187066/184233654-6a533684-e8f7-49ae-8e7c-636efd932315.png)

this is what is creating it
![image](https://user-images.githubusercontent.com/110187066/184233803-94ca03bc-2338-4705-a05a-fb3fc0ab0d2d.png)

getting these errors in console
![image](https://user-images.githubusercontent.com/110187066/184233983-280e06ed-1875-4570-a1f5-9857921decc4.png)

**Comment by benbro** [comment]
This is specific to how you import Quill in your project.
Please follow the docs of [v1.3.7](https://quilljs.com/docs/quickstart) or the upcoming [v2.beta.1](https://v2.quilljs.com/docs/quickstart)
