### ISSUE TITLE
Something wrong with font styling

### ISSUE THREAD

**Issue by do0zer** [quilljs/quill#3629]
Goto your own demo

https://quilljs.com/playground/#class-vs-inline-style

Change the font for this block:

  <p>This <span style="font-size: 32px">demo</span> shows how to <span style="font-size: 32px">change</span> this.</p>

font-size to ANYTHING other than 32px: and see absolutely nothing else takes

I would like to be able to set fonts to things other than 32px: can this please be fixed

**Comment by benbro** [comment]
Can't reproduce.
