### ISSUE TITLE
Bug display for adding url

### ISSUE THREAD

**Issue by Metrakit** [quilljs/quill#363]
Hi,

There's a minor bug when we want add an url:

![quill a rich text wysiwyg editor with an api](https://cloud.githubusercontent.com/assets/3305600/7535672/d96813ce-f587-11e4-85eb-9f83ccd044d4.png)

**Comment by willrowe** [comment]
This is a duplicate of #360. Please read through existing issues more carefully in the future.

**Comment by Metrakit** [comment]
ok I just want help you
