### ISSUE TITLE
How to parse tables

### ISSUE THREAD

**Issue by marcorohn** [quilljs/quill#3634]
Hi, I want to be able to convert quill 2.0-text into docx files with docx4j, for which the best solution would be to know what text belongs to which table, row and column. I already played around with it for some hours, but can't really get behind how its done, besides the row-... attribute and some filling up with newline characters. (Especially semi-filled tables and tables with formatted contents are the problem) Can anyone provide a concise set of rules on how to do that?
Thx in advance

**Comment by thekennysong** [comment]
+1

**Comment by yasz** [comment]
++1

**Comment by benbro** [comment]
Duplicate https://github.com/quilljs/quill/issues/117
