### ISSUE TITLE
Can't apply custom styling to multiple instances of Quill on same page

### ISSUE THREAD

**Issue by misterbossman** [quilljs/quill#3635]
I have a single page application with multiple Quill instances - I just want my viewer instance (i.e. a bubble-themed Quill instance with `readOnly: true`) to display a smaller font size than the other instances on the page, which are all used for editing.  I've been banging my head trying to figure this out.

Since Quill classes are global, ql-editor overrides any styling defined in my container class (.ql-quill_container).  Also, I can't use something like `!important` because that will apply the CSS to all other Quill instances (i.e. the editors, in addition to the viewer).  Unless there is some way to embed a custom CSS class inside of the global Quilll CSS for the Quill viewer instance on my page, it seems like this is not possible.

The use case is simple:  apply different styling to a viewer instance of Quill while all other Quill editors remain under the default CSS parameters.

**Comment by benbro** [comment]
Fixed in [v2.0.0-beta.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-beta.2)
https://v2.quilljs.com/docs/registries
