### ISSUE TITLE
config to toggle readOnly?

### ISSUE THREAD

**Issue by Jprusa610** [quilljs/quill#3637]
I'm looking to configure the editor so that readOnly can be toggled on and off after an Onclick event but right now I'm not able to configure Quill as readOnly without it crashing. 
 
I have a basic setup for a Quill text editor. When I try to change the config with new quill(editor, {configs}); the editor goes away and I'm left with a blank screen. When I used the same exact code on a separate web app the text editor's toolbar was removed but the content was not prefilled and it was still able to be edited. 

I've been quite lost looking through the Quill documentation so I appreciate any ideas to get me back on track. Thank you for your time!
```

import { useCallback} from "react";
import quill from "quill";
import "quill/dist/quill.snow.css";
export default function TextEditor() { 
    const wrapperRef = useCallback(wrapper => {
        if (wrapper == null) return 
        let configs = {  theme: 'snow', readOnly: true, placeholder: 'HELLO!!!' };
        wrapper.innerHTML = ""
        const editor = document.createElement
        ("div")
        wrapper.append(editor);
        new quill(editor, {theme: "snow"});
    } , []); 
    return (
        <div>
    <div   className="container" ref={wrapperRef }/>
    </div>
    )
}

```

**Comment by Strangebrewer** [comment]
I came looking for this same answer and have yet to find a way to do this directly. What I ended up doing is putting the toggle functionality in a parent component and have two quill separate editor components, one readOnly and one editable. It's a little indirect, but it works.

**Comment by benbro** [comment]
Call [quill.disable()](https://quilljs.com/docs/api/#disable) and [quill.enable()](https://quilljs.com/docs/api/#enable)
