### ISSUE TITLE
Code syntax highlighting not working in v2.0.0-dev.4

### ISSUE THREAD

**Issue by artknight** [quilljs/quill#3638]
According to the docs loading highlight.js and setting `syntax: true` should be enough to get the code formatted correctly. As it stands atm none of that happens and the code remains unformatted!

Current config
```
new Quill($note_body[0], {
	modules: {
		syntax: true,
		toolbar: {
			container: [
				['bold', 'italic', 'underline', 'strike'],
				[{ 'color': [] }, { 'background': [] }],
				[{ 'header': 1 }, { 'header': 2 }],
				[{ 'header': [1, 2, 3, 4, 5, false] }],
				['blockquote', 'code-block'],
				[{ 'list': 'ordered'}, { 'list': 'bullet' }],
				[{ 'align': [] }],
				['link','image','video'],
				['clean']
			],
			handlers: {
				image: this._onUploadFilesControlClicked.bind(this)
			}
		}
	},
	placeholder: 'Start typing...',
	theme: 'bubble',
	bounds: $note_body[0]
});
```

<img width="1090" alt="Screen Shot 2022-08-25 at 2 48 36 AM" src="https://user-images.githubusercontent.com/157762/186594612-0fcd5acc-8a19-4bac-b64f-ec3bc00d17bd.png">

I am using straight up vanillaJS complication of quill.js in my page.

**Comment by artknight** [comment]
I also noticed that the code is not wrapped in `<pre>` and `<code>` tags. That is not standard and should be corrected!

**Comment by Zuckjet** [comment]
> The Syntax Module enhances the Code Block format by automatically detecting and applying syntax highlighting. The excellent [highlight.js](https://highlightjs.org/) library is used as a dependency to parse and tokenize code blocks.


try to import highlight.js

**Comment by artknight** [comment]
@Zuckjet so highlight.js is already available and is loaded before quill.js. I was able to make it work by overriding the `highlightBlot` method in syntax.js and also updating the code.ts to use the `pre` tags. Here are the changes made.

https://github.com/quilljs/quill/compare/develop...artknight:quill:develop

It works now perfectly with highlight.js 👍 

I am hoping you can port those changes over!!

**Comment by benbro** [comment]
Duplicate https://github.com/quilljs/quill/issues/3981
