### ISSUE TITLE
Documentation request: preventing invalid cursor movement

### ISSUE THREAD

**Issue by ryaninvents** [quilljs/quill#3640]
I recognize that I have a custom use case trying to implement checkboxes, but would like to contribute to the Quill documentation if someone points me in the right direction.

**Steps for Reproduction**

1. Visit [this CodePen](https://codepen.io/ryaninvents/pen/XWEvjbV).
2. Place the cursor at the beginning of the line marked "Bread"
3. Press the <kbd>&larr;</kbd> (left) arrow once
    * **Expected:** cursor moves backwards to end of the line marked "Milk". Compare to cursor movement within the bulleted list at the bottom
    * **Observed:** cursor moves flush with the right side of the checkbox
4. Press the <kbd>&larr;</kbd> (left) arrow a second time
    * **Observed:** cursor moves flush with the left side of the checkbox. Any characters typed now will appear at the _end_ of the "Bread" line
5. Press the <kbd>&larr;</kbd> (left) arrow a third time
    * **Observed:** cursor moves to the end of the "Milk" line as we expected for the first keypress.
6. Click immediately to the left of the checkbox next to "Apples"
    * **Expected:** this behavior is somewhat undefined, but we'd still expect a valid cursor location
    * **Observed:** cursor moves to invalid location from step (4)

**Platforms**: MacOS, Chrome 104

**Version**: `1.3.6`

**Possibly related:** #2671, #1403

**Other notes:** With my initial implementation (which closely mirrored the [base ListItem implementation](https://github.com/quilljs/quill/blob/541bd363ac8eae2ad876f16a950cea439eae262a/formats/list.ts#L9-L51)) I was able to move the cursor _inside_ the checkbox and type characters -- this had no effect on the document that Quill reported. Adding `domNode.setAttribute('contenteditable', 'false')` fixed this, but there is no analogous fix for the current cursor-movement problem.

**Comment by TonyYu2015** [comment]
add a new matcher of arrow operation about checklist blot to the keyboard module is a choice.

**Comment by ryaninvents** [comment]
@TonyYu2015 Thanks for the suggestion! I was debating between a keyboard hook and an event listener on the `.task` element.

Upon reflection, it appears that this ticket is a request for what the "most Quill-ish way" to implement this would be -- I want to hook in at the appropriate level to cut down on edge cases. For example, if there's a generalized way to validate cursor location, then we could solve arrow key behavior and click behavior at the same time.

**Comment by MatteoGauthier** [comment]
Hey @ryaninvents, did you find a working solution ?

**Comment by ryaninvents** [comment]
@MatteoGauthier Unfortunately not. I haven't had the chance to work with Quill much lately, but I'm considering rendering the checkbox outside the QuillJS DOM element and using absolute positioning to make it work the way I want
