### ISSUE TITLE
How to send text to textarea by selenium webdriver?

### ISSUE THREAD

**Issue by pgshow** [quilljs/quill#3646]
Hi, Seems quill doesn't have textarea tag in the editor html, so How to send text to then textarea by using Python Selenium/WebDriver .

**Steps for Reproduction**

1. Ex. On [https://quilljs.com/](https://quilljs.com/),  I can type there so the text changes. But I can'f find a usual textarea like this:
`<textarea name="content">Write something here</textarea>`

2. So how to use Python Selenium to send text to the Quill editor. I want send to the content part.

**Version**:

My: Quill version 1.3.7

**Comment by benbro** [comment]
Please see the [form submit example](https://quilljs.com/playground/#form-submit) which fills an input field with the document JSON before sending to the server.

**Comment by pgshow** [comment]
thanks @benbro
