### ISSUE TITLE
Problem with ql-indent numbering

### ISSUE THREAD

**Issue by goldalworming** [quilljs/quill#3647]
![image](https://user-images.githubusercontent.com/440256/189037167-1f6f9b8a-921e-4f12-b2a6-26ecfa1072f0.png)

the subnumber not order properly start with a for 2.A.

anybody knows how to fix it?

**Comment by TonyYu2015** [comment]
I tested the ordered list as your structure and it's ok in the 2.0.0-dev.4 vesion.

**Comment by piotrkorniak** [comment]
Counter-reset is not working on FireFox. I replace counter-reset to counter-set

**Comment by goldalworming** [comment]
Ah yes, I forgot use firefox. I thought it's on all browser. I'll try to find it, thanks

**Comment by felixgeissler** [comment]
We just ran into the same issue. Is there any workaround for Firefox planed yet?
