### ISSUE TITLE
Open Source the main examples on quilljs.com

### ISSUE THREAD

**Issue by RogerPodacter** [quilljs/quill#3650]
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/59190/189528654-95022c78-df9a-47c0-b252-7ce3281b9abb.png">

It would be amazing to see the code to these beautiful examples!

Or, if they are already open source, making it clearer where the source is would be great!

**Comment by anisabboud** [comment]
Quilljs.com homepage source: https://github.com/quilljs/quill/blob/develop/docs/index.html

More examples: https://quilljs.com/playground/

All formats: https://quilljs.com/docs/formats/

Full example: https://quilljs.com/standalone/full/ (right click -> View page source)

Documentation: https://quilljs.com/docs/quickstart/

**Comment by rahultrivedi180** [comment]
Full example: https://quilljs.com/standalone/full/ (ctrl + u)

**Comment by benbro** [comment]
Answered.
