### ISSUE TITLE
Quill Mention throws TypeError s.domNode.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by taranjeetiterate** [quilljs/quill#3653]
Trying to mention users with @ character in the quill editor throws TypeError s.domNode.getBoundingClientRect is not a function in the console and the suggestions are not shown.

Steps for Reproduction
The error is a little tricky to reproduce as only a few of my company's clients occasionally experience the issue on production.
screenshot below
<img width="1425" alt="Screenshot 2022-09-14 at 4 58 15 PM" src="https://user-images.githubusercontent.com/92028581/190353880-5bbfe84e-af82-46b3-94b3-2a444840e196.png">

Expected behavior:
The mention feature should show the suggestions

Actual behavior:
The following error is thrown in the console and the suggestions don't work

TypeError
s.domNode.getBoundingClientRect is not a function
Platforms:

browser: Chrome 104.0.5112.101 (Official Build) (arm64)
device: Mac
os: Mac OS X 11.4 (BigSur)

**Comment by benbro** [comment]
quill.mention.min.js shown in the screenshot is an external module.
Not a Quill issue.
