### ISSUE TITLE
Quill on Svelte

### ISSUE THREAD

**Issue by jonsnowpt** [quilljs/quill#3655]
Does a Quill component exist, or is it planned to be used with Svelte?

I was not able to find it on the Component Libraries.

1. It would be interesting to create an integration component with Svelte.
2. It would be an asset to the Quill core and can be used by thousands of Svelte developers.
3. At this time, we are not using Quill since we develop it with Svelte.
4. If this is available, it can be added to the platforms we are developing.

## Our use case:

In our case, we are developing a platform for sports stats and content currently visited by millions of users. 

Our roadmap includes the ability for users to become content authors, and that's where Quill would excel.

Our current platform:

https://scores.betarena.com

**Comment by benbro** [comment]
Component Libraries created by the community are listed here:
https://github.com/quilljs/awesome-quill#component-libraries

I don't see a Svelte component in this list but a quick search shows some projects that wrap Quill for Svelte. I didn't try it so can't comment on it. If you find a good component or develop one yourself please submit it to the awesome-quill list.
