### ISSUE TITLE
Question: how is the event handler removed?

### ISSUE THREAD

**Issue by v1talii-dev** [quilljs/quill#3662]
[This line of code](https://github.com/quilljs/quill/blob/develop/core/emitter.ts#L9) shows that event handlers are being added to the document. But I haven't found how they are removed. When the editor is destroyed, the event handlers still remain in the document. Is this a bug or maybe I'm deleting the instance incorrectly? If anything, I just reset the reference to it quill = null.

I use quill editor in a SPA application on vue. When I switch between pages, the component with the Quill editor is destroyed, but event listeners remain in the document. I guess these listeners may be the cause of the memory leak.
![image](https://user-images.githubusercontent.com/12966923/192887530-115f1c07-ef73-4f5a-adfb-505842ac5f48.png)

**Comment by v1talii-dev** [comment]
@luin can this cause memory leaks?

**Comment by benbro** [comment]
Duplicate: https://github.com/quilljs/quill/issues/3644
