### ISSUE TITLE
Inserting text from a streaming API causes unwanted newlines

### ISSUE THREAD

**Issue by GabrielPereyra** [quilljs/quill#3668]
I want to insert text into quill.js using a streaming API that returns chunks of text. Unfortunately, each chunk gets wrapped in a paragraph element, causing newlines after every chunk. I've tried insert, update, and dangerouslyInsertHTML and all of them have this behavior. Is there a way to avoid the insertion being wrapped in a paragraph element?

**Comment by aashutoshrathi** [comment]
+1

**Comment by vitalist82** [comment]
I am currently solving the same issue. I thought a custom [matcher](https://quilljs.com/docs/modules/clipboard/#addMatcher) should solve this issue but I don't know yet how to use it properly.
