### ISSUE TITLE
Selecting text with Shift+Right Arrow does not work

### ISSUE THREAD

**Issue by inickvel** [quilljs/quill#3669]
**Steps for Reproduction**

1. Visit [https://quilljs.com/playground/](https://quilljs.com/playground/)
2. In editor enter 3 lines, last line should be empty like:
'sdaggdas
gdsgdsf
'
3. Move caret to the end of second line
4. Press `shift+up`, `shift+right`, `shift+left`

**Expected behavior**:
`shift+right` and `shift+left` are working

**Actual behavior**:
`shift+right` and `shift+left` are not working

**Platforms**:
Windows 10 21H2
Chrome 106.0.5249.103

**Version**:
Quill 1.3.7

**Comment by luin** [comment]
`Shift+ArrowLeft` works correctly on my side as it selects the letter on the left side. `Shift+ArrowRight` does nothing but should also be expected as the caret is at the line end.

I'm closing this. Feel free to reopen if you think the issue persists.
