### ISSUE TITLE
Can't delete embed blots on chrome

### ISSUE THREAD

**Issue by wangergou93** [quilljs/quill#3672]
Steps for Reproduction

https://codepen.io/wangergou93/pen/bGMQZBP
focus the editor
hit delete

Expected behavior:
the embedded blot is deleted

Actual behavior:
the editor is defocused, and the blot is not deleted

Platforms:
mac, chrome

Version:
1.3.6

**Comment by Bazsi96** [comment]
I checked is on Chrome and it's deletable for me.
