### ISSUE TITLE
Have a custom img blot with addEventListener. Event triggered when using insertEmbed, but it does not work when img loaded from existing html

### ISSUE THREAD

**Issue by bumpingChris** [quilljs/quill#3674]
I'm using react-native-cn-quill but this is really a Quilljs question. 

In the code below, clickHandler is successfully called on 'click' event when I do a "insertEmbed(index, 'pbThumbnail', obj)", but when I load the webView with initialHtml containing an <img class="pb-Thumbnail" ....> tag, the eventListener does not appear to be added to the blot/tag. 

Should the eventListener be automatically applied on html load OR do I have to manually re-add to all the relevant tags?

Thanks for your help!

`Code

        const Block = Quill.import('blots/block');
        class ThumbnailBlot extends Block {
          constructor(domNode) {
          super(domNode);
    
          // Bind our click handler to the class.
          this.clickHandler = this.clickHandler.bind(this);
          domNode.addEventListener('click', this.clickHandler);
        }
    
        clickHandler(event) {
          alert("ClickableSpan was clicked. Blot: ", this);
        }
    
    
        static create(value) {
          
          let node = super.create();
         
          node.setAttribute('contenteditable', false);
    
          let image = document.createElement('img');
          image.setAttribute('class', 'pbVidThumb');
          image.setAttribute('contenteditable', false);
          image.setAttribute('src', value.imgBase64);
          image.setAttribute('height', value.height);
          image.setAttribute('width', value.width);
          image.setAttribute('id', value.imgName);
       
          node.appendChild(image);
          return node;
        }
    
        static value(node) {
          return { src: node.getAttribute('src'), title: node.getAttribute('title'), height: node.getAttribute('height'), width: node.getAttribute('width'), id: node.getAttribute('id')}
        }
    
     
        static deleteAt(node) { return false; }
    
        static formats(node) {
          return node.getAttribute('title');
        }
      }
      ThumbnailBlot.blotName = 'pbThumbnail';
      ThumbnailBlot.tagName = 'span';
      ThumbnailBlot.className = 'pb-thumbnail';
      
      Quill.register(ThumbnailBlot);

`

Loading this html into a webview with Quill does not apply the click eventListener:

```
          <span class="pb-thumbnail" contenteditable="false" title="IMG_0002.JPG">
              <img contenteditable="false" 
                       src="https://....uploads%2F2h06dnjjxoa8l21i5m51c-Bump-bump-imageimage.jpg" 
                       height="auto" 
                       width="100%" 
                       class="pbVidThumb"   
                       id="IMG_0002.JPG" >
          </span>
```

**Comment by christingliu** [comment]
<img width="973" alt="image" src="https://user-images.githubusercontent.com/19380397/201258926-db5302f2-018a-44af-9806-38e8d3688aa0.png">

**Comment by ramarivera** [comment]
I believe @christingliu is in the right track. You should use a BlockEmbed in your case, not a Block.


> We take advantage of the fact that Embed blots do not have to correspond to a void node. It can be any arbitrary node and Quill will treat it like a void node and not traverse its children or descendants. This allows us to use a <div> and the native Twitter Javascript library to do what it pleases within the <div> container we specify.


More details here https://quilljs.com/guides/cloning-medium-with-parchment/
