### ISSUE TITLE
Cannot add a white-space in the text area

### ISSUE THREAD

**Issue by Ihtisham-Khattak** [quilljs/quill#3675]
We have such kind of situation. By onclick the rectangle shape is created show in the fig below.

![image](https://user-images.githubusercontent.com/86098390/196422683-0ca84d5f-f70f-49ae-b5bb-bcd0ccb49baa.png)

But the problem is that when we write something in the comment section i'm enable to add whitespace between two words also show in the figure.
![image](https://user-images.githubusercontent.com/86098390/196422123-bd491c19-09e1-4bcb-aa17-fe3d33cc0df2.png)

Our front-end is develop in react.js with laravel backend. Other than that i'm trying this whole process on other sites for example (amazon, google, facebook) and others, but not face this problem.  I'll provide you the complete information what else you need for solving my problem.

**Comment by benbro** [comment]
Please fill the issue template and the steps to reproduce your issue.
