### ISSUE TITLE
How to have a clickable text with customizable onClick behavior?

### ISSUE THREAD

**Issue by DaCao** [quilljs/quill#3677]
I am working on a webpage that has the regular posting and commenting functionalities and I am using Quill for the comment-inputing text box.

It is easy to insert a string that is a link. However, instead of directing to the linked url, we want to trigger some custom behaviors when the string is clicked, like opening a modal window on the webpage.

The important thing is: when user clicks the text, some custom defined Reactjs function is triggered. It would not be going to the linked url like as default behavior.

Is it possible with Quill?

Since I am typing my question about Rich-text editor using a Rich-text editor, I figured it is most clear if I just give this example:

So in the comment-inputing text box of our app, it is like when you have this text:

[this_is_some_text](www.google.com)

and on clicking it, instead of going to google.com, you open a modal window to show some message on this same page, or trigger an http request call, or any custom behavior.

Also, it does not have to be this string - the clickable thing can be a button, or anything. How can we insert custom html tags then?

**Comment by benbro** [comment]
https://quilljs.com/guides/how-to-customize-quill
