### ISSUE TITLE
Store Quill document

### ISSUE THREAD

**Issue by junoriosity** [quilljs/quill#3678]
I would like to store Quill documents such that users can load it after they come back to the frontend.

Is that possible by using S3 buckets resp. MongoDB or PostgreSQL? If so, is there some documentation for it or could you explain it to me how to make it work?

**Comment by darkwavedriver** [comment]
I think you want to call getContents() on you Quill instance, to get the editor contents a quill delta. You would then serialize them to a json string and store however you like. To insert the stored text, deserialize it back into a Delta object and call setContents(delta) on your editor instance

**Comment by junoriosity** [comment]
Hi @darkwavedriver 

that sounds very interesting to me. Could you provide me with some code examples to try it out?

**Comment by benbro** [comment]
See [getContents](https://quilljs.com/docs/api/#getcontents) in the docs.
The [form submit](https://quilljs.com/playground/#form-submit) example might be relevant.
