### ISSUE TITLE
How to keep some blocks HTML-free?

### ISSUE THREAD

**Issue by samul-1** [quilljs/quill#3680]
I am using quill editor to create content on a website which allows authors to input LaTeX formulas as well as regular text.
When the content is accessed by a reader, MathJax on the client-side renders LaTeX formulas.

One problem is that, if I have formulas spanning more than one line, Quill editor will insert `<p>` tags around those lines, for example an input like

```
$$x^x

y^x$$
```

will become

```
<p>$$x^x</p>
<p>y^x$$</p>
```

This messes with MathJax which then is unable to detect the LaTeX.

Is there a way to tell Quill to discard html and only consider the text value for certain blocks?

For example, I tried using this code to match all blocks inside $ or $$ and stripping off html tags:

```
const LATEX_REGEX = /(\${1,2})((?:\\.|[\s\S])*)\1/g; ///(\${1,2})[^]*?[^\\]\1|[^\$]+/g;

	return html.replace(LATEX_REGEX, val => {
		const textContent = val
			.replace(/<\/p>/g, "\n")
			.replace(/<p>/g, "")
			.replace(/<br\s*\/?>/g, "\n");
		return textContent;
	});
```

This would be run each time Quill emits a `text-changed` event to set the content value of Quill.
This seems to kinda work, but each time a LaTeX block is detected, the cursor gets moved to the first position. This is probably due to the fact that the length of the text content changes in an unexpected way, messing with how Quill keeps track of the current selection/cursor position.

Is there a better way to solve my issue?

**Comment by benbro** [comment]
You'll need to handle cursor movement in your code or add a custom Blot to handle latex input and rendering. The equation and code block in core might help as a reference.
