### ISSUE TITLE
Quill-ImageDrop Unable to import

### ISSUE THREAD

**Issue by lmm2022** [quilljs/quill#3684]
problem：
quill Cannot import modules/imageDrop. Are you sure it was registered?
TypeError: moduleClass is not a constructor

![image](https://user-images.githubusercontent.com/44827236/199670331-1a96e15e-4a1b-4b45-9edd-b66bf05fdcbf.png)
![image](https://user-images.githubusercontent.com/44827236/199670377-8896d23c-4c90-43e9-a836-f63511268136.png)
![image](https://user-images.githubusercontent.com/44827236/199670439-98d09e47-c330-477a-994e-e60750697d0f.png)

**Comment by Glimpse597** [comment]
![image](https://user-images.githubusercontent.com/44827236/199670830-123f35f3-349e-4b06-befe-b95e1ad9dfc6.png)
![image](https://user-images.githubusercontent.com/44827236/199670871-69b2982c-924a-4e4d-92bd-46f9c4801e4d.png)
It's doubtful that all dependencies have been imported. Quill cannot be called

**Comment by Glimpse597** [comment]
This is a console error
![image](https://user-images.githubusercontent.com/44827236/199671092-019e6ac5-f6dc-4f17-8928-fb675b1c4089.png)

**Comment by markuso** [comment]
I think the dist output of that package is in UMD module format, which means you may have to do the following when importing it in ESM:

```js
import ImageDrop from 'quill-image-drop-module';

const imageDrop = ImageDrop.default;
```

I ran into a different Quill module that needed that exact fix to work and it was providing me with the same error message as you are experiencing. I hope this helps in your case.

**Comment by benbro** [comment]
Answered.
