### ISSUE TITLE
How to update formatting of multiple lines ?

### ISSUE THREAD

**Issue by MatteoGauthier** [quilljs/quill#3688]
Hey, I just wanted to know how to format multiple lines ?

Can someone help me ?

Bye

**Comment by troldmand** [comment]
If I mark multiple lines of content and click a tool to format it, it works fine: 
https://user-images.githubusercontent.com/9819978/204056723-7484e0e7-b75e-4f68-a319-49286deb9cd3.mp4

**Comment by benbro** [comment]
Answered.
