### ISSUE TITLE
Selecting blot with mouse works incorrectly. Sometimes has length 0 which affect styling.

### ISSUE THREAD

**Issue by nowayoutPL** [quilljs/quill#3690]
Quill blot element that extends Embed class cannot be easily selected with mouse. The reason for select this element is to style it ( wrap it with style Delta ) using default quill styling methods. 
When You put your mouse before blot element and then drag your mouse cursor while pressing mouse button until element gets selected and then You release your mouse button. After that `selection-change` event is fired with proper element index but length set to 0. 

<img width="294" alt="image" src="https://user-images.githubusercontent.com/32061377/200572127-f86828c6-ac85-42a5-b004-2a0ec8f4b246.png">

If You then will try to style element with `bold` for example, element gets deselected without any style applied.  
To make it properly selected You have to move your mouse a little bit more to the right (even though element looks selected) until You pass certain not visible point. Then range length is set to 1 and element can be styled properly. 
Selection works as expected when using keyboard with shift key and arrows.

**Steps for Reproduction**

1. Visit https://codepen.io/nowayout/pen/BaVQxLR
2. Add Embed blot by using button "Add Embed" below editor. 
(ideally preceded by and followed by some string ex: aaa`blot`bbb)
4. Try to select element by using mouse and observe div below containing index and length of selection of text within editor. Then You can try to style element using styling buttons.

**Expected behavior**:
Blot element is properly selected while using mouse right after background of element changes due to selected state.

**Actual behavior**:
Blot element is not properly selected and because of that styling doesn't work.

**Platforms**:

Latest chrome, Windows and Mac

**Version**:

"Quill Version: " "1.3.6"

**Technical hint**:

Probable cause for this is those are those `GUARD_TEXT` which are added by [[quill](https://github.com/quilljs/quill/tree/541bd363ac8eae2ad876f16a950cea439eae262a)/[blots](https://github.com/quilljs/quill/tree/541bd363ac8eae2ad876f16a950cea439eae262a/blots)/embed.ts](https://github.com/quilljs/quill/blob/541bd363ac8eae2ad876f16a950cea439eae262a/blots/embed.ts)
I think quill to mark whole element as selected both GUARD's has to be selected which is not always the case.

**Comment by welkinwong** [comment]
same question
