### ISSUE TITLE
Need IMG

### ISSUE THREAD

**Issue by RubenRDC** [quilljs/quill#3693]
Hello, I would need to obtain the images to save them on the server, that is done by the text editor, otherwise how could I obtain the images?

**Comment by mrctrifork** [comment]
You can parse the content of the editor and extract the images:

```typescript
async function getImages(markup: string) : Array<Blob> {
    const parser = new DOMParser()  
    const doc = parser.parseFromString(markup, 'text/html')
    
    return Promise.all(
      Array.from(doc.images).map(image => fetch(image.src).then(res => res.blob())
    )
}
```

**Comment by RubenRDC** [comment]
another thing, if I put the text editor in a form and send the content in it with JS to php to upload it to a database, are the images already saved locally or do I have to extract it to upload it?

**Comment by RubenRDC** [comment]
ok, so i extract the image contained in the "blob" array and then load it, correct?  What name does the image receive when you put it in the text editor?

**Comment by benbro** [comment]
The image name is not part of the Delta. If you need it you'll have to extend the image blot and the UI.
```insert: Object { image: "data:image/jpeg;base64,<image-encoded-in-base64>"}```
