### ISSUE TITLE
Charts In Quill editior

### ISSUE THREAD

**Issue by usmanahmedkhan09** [quilljs/quill#3698]
[Is there any way to embed the chart in quill Editor? Currently, I'm using Vue 3 and quill.js and for charts, I'm using apex charts](https://stackoverflow.com/questions/74449205/is-there-is-any-way-to-embed-chart-in-quill-editor-currently-im-using-vue-3-an)

**Comment by Daniel-Cong** [comment]
You are asking a simple rich text editor to perform at the same level as Microsoft Word.
