### ISSUE TITLE
selection paste bug?

### ISSUE THREAD

**Issue by Lightene** [quilljs/quill#3701]
I checked the playground on the official website of Quill Editor, and the same symptoms appear.
I put it on the issue because it was judged to be a bug.

If the first line of paste text is in the bold state, the lower line plain text is in the bold state.

https://user-images.githubusercontent.com/3311386/204011115-694b562c-bdd0-4af0-9bf3-b8ba4ba0be2a.mov

Has a workaround been suggested? I can't find it even if I search it.

**Comment by benbro** [comment]
Fixed in [v2.0.0-rc.0](https://github.com/quilljs/quill/releases/tag/v2.0.0-rc.0)
