### ISSUE TITLE
Video always displays the "no video support in your browser" default text

### ISSUE THREAD

**Issue by bsenftner** [quilljs/quill#3702]
**Steps to Reproduce:**
1) Attempt to use any video tag, or any embed module supporting video
2) Quill.js always chooses to display the "no video support in your browser" default text

**Expected behavior:**
video element appears, ready for use, able to be played

**Platforms**
A Docker container, starting with Python:3.9.4-alpine and loaded with whatever to support a FastAPI REST app; the app itself uses no framework, just HTML and very light JavaScript. 
Browser attempting to view video pages are Firefox & Chrome (both latest) on Win10, same incorrect behavior on a Win11 system, and same unexpected behavior with an iPhone and FireFox/Chrome/Safari

Quill.js versions tried:
1.3.6 & 1.3.7 (for the htmlEditButton version)

Using Quill.js as a content editor, it always chooses to display the "no video support in your browser" default text from my video tags. I've tried several of the video embed modules people have made, and they all do the same: only display the "no video support in your browser" text.

I have other pages not using Quill.js where I hand write the video tags, referencing the same videos as I want to embed with Quill.js, and those playback fine.

When attempting to embed a video within Quill.js, I see my Network tab receiving data, and I see my logs reporting the video file being located, opened... and then not streamed because Quill.js is choosing the default text and not playing the video. It does not matter if I'm attempting locally streamed video, or an IP camera I know works, or YouTube, or some other video service: behavior is always that default "not playing" text.

I even tried the htmlEditButton module that lets one just type in html, and that also only displays the "no video support" text - yet that same html can be rendered without quill.js and videos appear and playback just fine...

What's the secret? There has got to be some weakly documented aspect in play here...

**Comment by bsenftner** [comment]
I found that by inserting this logic from the _Quill-Examples-and-FAQ -> Centralized Video_ example into my Quill implementation. A Quill with 4 different video embedding capable modules enabled, and all those video embedding methods starting working after this addition. 

I think my issue is the default treatment of a non-youtube and not vimeo video is to disallow the URL, reverting to the "no video support" text. (Which is not explicitly pointed out in the documentation, as least I never saw it after 2+ weeks digging.)

Below in the extractVideoUrl() method, a non-video service URL passes through, enabling my locally hosted and non-popular video service urls to pass thru and work. Seems like simply allowing some method of defining allowed video urls might be a nice addition to Quill.

```
                let DefaultVideo = Quill.import('formats/video');
		//
		class CentralizedVideo extends DefaultVideo {
  			static create(value) {
    			// Get node from superclass.
    			let node = super.create(value);

				// user fields:
				let insertElemWidth  = document.getElementById("insertVideoWidth").value;
				let insertElemHeight = document.getElementById("insertVideoHeight").value;
				//
    			// Set width and height.
    			node.width = parseInt(insertElemWidth);
    			node.height = parseInt(insertElemHeight);

    			// Get url in correct format. Without it, the video will not work.
    			value = this.extractVideoUrl(value);
    			node.setAttribute('src', value);
    
    			node.classList.add('ql-align-center');

    			return node;
  			}

  			static value(node){
    			return node.getAttribute('src');
  			}

  			static extractVideoUrl(url) {
    			// look for youtube urls:
				let match =
      				url.match(/^(?:(https?):\/\/)?(?:(?:www|m)\.)?youtube\.com\/watch.*v=([a-zA-Z0-9_-]+)/,) ||
      				url.match(/^(?:(https?):\/\/)?(?:(?:www|m)\.)?youtu\.be\/([a-zA-Z0-9_-]+)/);
				// if a youtube url, use their embed:
    			if (match) {
      				return `${match[1] || 'https'}://www.youtube.com/embed/${ match[2] }?showinfo=0`;
    			}
    			// if a vimeo url, use their embed:
    			if ((match = url.match(/^(?:(https?):\/\/)?(?:www\.)?vimeo\.com\/(\d+)/))) {
      				return `${match[1] || 'https'}://player.vimeo.com/video/${match[2]}/`;
    			}
				// just let raw video url pass thru:
    			return url;
  			}
		}
		//
		Quill.register(CentralizedVideo);
```

**Comment by deji12** [comment]
HI, i am currently using the django quill library and i have run into the same issue. 

So i have a model that collects the description for a course. It is a quill field as shown below:

```
class Course(models.Model):
    description = QuillField(null=True, blank=True)
```
and i have a model form:

```
class SubTopicForm(ModelForm):
    class Meta:
        model = CourseContentSubTopic
        fields = ['description']
```
Anytime i try to render this form in the frontend by doing this:

```
{{form.media}}
{{form.description}}
```
My html video tag stops working. I noticed the problem comes when i add {{form.media}} to the html file.

i have tried looking thorough the docs but i have not seen anything that has proven helpful.
