### ISSUE TITLE
Missing images on your marketing site

### ISSUE THREAD

**Issue by roninCode** [quilljs/quill#3710]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**
Not a big deal - just didn't know how else to surface it to you.

1. [Visit](https://quilljs.com/playground/)
2. There are 3 png assets that are 404:
<img width="1364" alt="Screen Shot 2022-12-20 at 9 04 13 AM" src="https://user-images.githubusercontent.com/18723127/208698877-89a0eda8-7189-469f-b7ec-b3fff19ad273.png">

Also separate thing - in the issue template you state: `Please describe the a concise description` ... maybe it should be someting like: `Please describe the issue with a concise description` ?

**Expected behavior**:
You can see the icons.

**Actual behavior**:
You can't see the icons and see the alt text instead?

**Platforms**:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
Works for me.
