### ISSUE TITLE
Selecting plain text with strikethrough text, when trying to type a new letter, the line is erased

### ISSUE THREAD

**Issue by luizfilho-hotmart** [quilljs/quill#3711]
With the other formats (bold, italic, underline) works fine.

![strike](https://user-images.githubusercontent.com/85890192/208928593-b1c1c706-a2a6-4877-aa44-1b79982a5510.gif)

**Steps for Reproduction**
1. Visit https://quilljs.com/playground/
2. Write a text with strike format and a text without format (all in the same line)
3. Select the text and try to type a new letter.

**Expected behavior**:
Replace the text with the new letter and keep the format.

**Actual behavior**:
The line is erased.

**Platforms**:
macOs Monterey
Google Chrome - Version 108.0.5359.94

**Version**:
https://cdn.quilljs.com/1.3.7/quill.js

**Comment by luin** [comment]
Fixed in https://github.com/quilljs/quill/pull/3807. Feel free to let me know if there is anything missing. Closing
