### ISSUE TITLE
Toggle behaviour of inline blots are not working in Chrome when editor goes into fullscreen

### ISSUE THREAD

**Issue by agupta1989** [quilljs/quill#3713]
I have added a new full screen button, which leverages the container DOM element and API i.e. Element.requestFullscreen API to render the editor in full screen mode. This works fine, but after this somehow the toggle behaviour of inline blots such as **Bold**, **Italic**, **Underline**, **Strike** etc have gone away. I am able to apply the changes but after clicking on the same button again, its not reverting back. (I can however do the undo/redo or Ctrl + Z/Y for that matter, but the idea is to persist the toggle behaviour in full screen mode)

**Steps for Reproduction**

1. Visit quilljs.com
2. Open the Devtool, Locate the container `id=snow-container`
3. Switch to Console tab in devtool, and run the following code 
`$0.requestFullscreen()` OR `document.querySelector('#snow-container').requestFullscreen()`
4. Editor goes into full screen mode with dark background in chrome. (that's fine we can take care of it by overriding :backdrop CSS)
5. Select any word, click on "B" (Bold) icon button in toolbar.

**Expected behavior**:
The selected word should get bold style applied (using strong tag) and clicking on Bold button again in toolbar should revert it back.

**Actual behavior**:
The selection turns into bold, but same toggle behaviour is not happening, when I am clicking on Bold button again in toolbar.

**Platforms**:
Windows 11, Chrome 108, Edge 108. 

**This problem is happening only on chromium browser (Chrome and Edge). Toggle is working fine in Firefox**

**Version**:
1.3.6

**Screen recording of my storybook**

https://user-images.githubusercontent.com/3787965/209972933-3ce8b4b2-1a85-49e1-9913-06ffebac4703.mp4

**Comment by ajboni** [comment]
Did you find a workaround for this issue?. I get a similar behavior, but if I spam the click button sometimes it works.
