### ISSUE TITLE
react quil out put is text with<p></? tags

### ISSUE THREAD

**Issue by am0029** [quilljs/quill#3714]
react quil out put is text with<p></? tags 

 iam not sure why it is show in my blog post with html tags 

any idea?

**Comment by benbro** [comment]
If you can't reproduce it in the official [Quill demo](https://quilljs.com/) it's something specific to your environment.

**Comment by am0029** [comment]
i asked question can u look for me 

https://stackoverflow.com/questions/74975582/issue-with-react-quill-text-editor-why-output-with-html-tag

2 month no answer 

but another mde is work fine i need quil editor but can not fix this issue after months

**Comment by am0029** [comment]
the problem is another mde is works like simple mde 
but does not support code or feauthers like quil 

please can u check on my question see what is wrong ? before closing my question

https://stackoverflow.com/questions/74975582/issue-with-react-quill-text-editor-why-output-with-html-tag
