### ISSUE TITLE
Struggling to setup quill with astro build

### ISSUE THREAD

**Issue by bkyerv** [quilljs/quill#3715]
Quill is not accessible in astrobuild.

**Steps for Reproduction**

1. Visit (https://stackblitz.com/edit/astro-cyecrt?file=src/pages/index.astro)
2. Step Two
3. Step Three

**Expected behavior**: Render a text editor on display

**Actual behavior**: Empty display. An error is highlighted in the code editor saying 'Could not find name 'Quill'. '

**Platforms*macos vscode chrome browser*:

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
This question is not specific to Quill. Quill is a JavaScript lib. If it says that it could not find name 'Quill' it probably means that it could not load the script.
Maybe try to add Quill to package.json instead.
