### ISSUE TITLE
Can I extend default toolbar button functionality with a custom handler?

### ISSUE THREAD

**Issue by bartonyoung** [quilljs/quill#3716]
Is there a way that I can **extend** the default toolbar button functionality? I am aware of adding custom handler to the toolbar options as specified here: https://quilljs.com/docs/modules/toolbar/#handlers. However this approach completely overrides the default functionality.

However, I would like to maintain the default toolbar button functionality, while adding some additional custom functionality.

**Comment by benbro** [comment]
In the example in the linked to it says:
```// handlers object will be merged with default handlers object```
These examples might help:
https://github.com/quilljs/quill/issues/2544#issuecomment-488233146
https://github.com/quilljs/quill/issues/1817#issuecomment-344079500

**Comment by BartJanvanAssen** [comment]
Im looking for exactly the same thing @bartonyoung. @benbro so i think were looking for something that looks like this:

`handlers: {
            "color": function (value) {
                if (value) {
                    const convertedValue = valueToSomeFormat(value)
                    // now use quill's default behaviour but with my custom logic in between:
                    quill.executeDefaultHandlerBehaviourWithMyConvertedValue(value)
                }
            }
        }`
        
Haven't found it yet, i'll get back if i find something.
