### ISSUE TITLE
How to use color and background in toolbar container？

### ISSUE THREAD

**Issue by aardpro** [quilljs/quill#3718]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**
1. I write the toolbar div below:
> <div id="toolbarId">
    <button
          class="ql-color"
        ></button>
    <button
          class="ql-background"
        ></button>
   </div>
2. then write the new Quill below:

>    new Quill(`#editorId`, {
>       theme: "snow",
>       modules: {
>         toolbar: '#toolbarId',
>         blotFormatter: {},
>       },
>     });

**Expected behavior**:
When I click the color or background button, it will drop down a color palette so that I can set color to selected text..

**Actual behavior**:
The color/background buttons display well.But there is no color palette .Nothing happend when i click the color button.
When I use below codes,it works well.

> new Quill('#editor', {
>     theme: 'snow',
>     modules: {
>         toolbar: [[{ 'color': [] }, { 'background': [] }]]
>     },
> });
> 

**Platforms**:
win10, nodejs 16.17, vue 2.6

Include browser, operating system and respective versions
Microsoft Edge ver 108.0.1462

**Version**:
1.3.7

Run `Quill.version` to find out

**Comment by t0m-4** [comment]
try with 
  <select class="ql-color"></select>

**Comment by benbro** [comment]
Answered.
https://quilljs.com/docs/modules/toolbar/

**Comment by kingkhan40** [comment]
ka

**Comment by michaelbluejay** [comment]
The Toolbar doc page isn't helpful for a novice programmer to understand how to get a toolbar that shows the color options.  I had to search the web and piece together the answer from other sources.  This works for me.

```
const toolbarOptions = [
   ['bold', 'italic', 'underline', 'strike'],
   [{'color': ["#000000", "#e60000", "#ff9900", "#ffff00", "#008a00", "#0066cc", "#9933ff", "#ffffff", "#facccc", "#ffebcc", "#ffffcc", "#cce8cc", "#cce0f5", "#ebd6ff", "#bbbbbb", "#f06666", "#ffc266", "#ffff66", "#66b966", "#66a3e0", "#c285ff", "#888888", "#a10000", "#b26b00", "#b2b200", "#006100", "#0047b2", "#6b24b2", "#444444", "#5c0000", "#663d00", "#666600", "#003700", "#002966", "#3d1466", 'custom-color']}],
   [{'background': ["#000000", "#e60000", "#ff9900", "#ffff00", "#008a00", "#0066cc", "#9933ff", "#ffffff", "#facccc", "#ffebcc", "#ffffcc", "#cce8cc", "#cce0f5", "#ebd6ff", "#bbbbbb", "#f06666", "#ffc266", "#ffff66", "#66b966", "#66a3e0", "#c285ff", "#888888", "#a10000", "#b26b00", "#b2b200", "#006100", "#0047b2", "#6b24b2", "#444444", "#5c0000", "#663d00", "#666600", "#003700", "#002966", "#3d1466", 'custom-color']}]  
];

quill = new Quill('#editor', {
  modules: {
    toolbar: toolbarOptions
  },
  theme: 'snow' // or your chosen theme
});
```


This actually doesn't work completely; even though "custom-color" is listed, I don't get an option to choose a custom color.
