### ISSUE TITLE
Rendring every word as a span

### ISSUE THREAD

**Issue by Raj-divine** [quilljs/quill#3720]
I'm using quill for a project and I saw that everyone line in quill is a `p` tag and all the content of that line is inside the `p` tag. I want every word to be wrapped in a span tag with a `data-time` attribute and classes/styles like this

```html
<p>
    <span class="example" style="color:red;" data-time="1:00">like</span>
    <span class="example" style="color:blue;" data-time="1:01">this</span>
</p>
```

how can I do that? if there is no built-in way then how can I fork and change the source code to do that myself?

thanks

**Comment by Ganeshshinde-2003** [comment]
I wanna solve this issue. I know HTML, CSS and Java Script pretty well 
assign me this issue

**Comment by benbro** [comment]
Please follow the [docs](https://quilljs.com/docs/quickstart/) and [guides](https://quilljs.com/guides/why-quill/).
The [next release](https://v2.quilljs.com/) is under active development.
