### ISSUE TITLE
Add simple popover when hovering over some word

### ISSUE THREAD

**Issue by codeXLinkX** [quilljs/quill#3722]
How can I show some tooltip-like popover when hovering over a word?

If my code is something like below:
```
quill.updateContents([
        {
          insert: "word",
          attributes: {
            color: "grey",
            tooltip: "show some text here in a tooltip popover",
          },
        },
      ]);
```
where I added the extra tooltip attribute, when I hover over the "word", it should pop up a window showing the text value.

**Comment by yashnerkar** [comment]
can I work on this?

**Comment by codeXLinkX** [comment]
Would be great

**Comment by benbro** [comment]
https://quilljs.com/guides/how-to-customize-quill
