### ISSUE TITLE
Adding Custom Blot

### ISSUE THREAD

**Issue by IvanFarkas** [quilljs/quill#3723]
# Adding Custom Blot

In the Parchment [Example](https://github.com/quilljs/parchment#example) it says:

> Quill also provides many great example implementations in its [source code](https://github.com/quilljs/quill/tree/develop/formats).

I'd like to extend the `Inline` blot like in [link.ts](https://github.com/quilljs/quill/blob/develop/formats/link.ts).

```javascript
import Inline from '../blots/inline';

class Link extends Inline {
```

In my code how do I `import` from `../blots/inline`, please?

**Comment by ilkeratik** [comment]
I import like this in react:
```
import { Quill } from "react-quill";
const Inline = Quill.import("blots/inline");
```

**Comment by benbro** [comment]
Please follow the [guide](https://quilljs.com/guides/how-to-customize-quill).
