### ISSUE TITLE
Adding plugin: counter module failed to work properly

### ISSUE THREAD

**Issue by SkyYap** [quilljs/quill#3724]
In the [readme](https://github.com/gtgalone/react-quilljs#counter) section, I have used the given instruction and found out the default counterRef is showing 2. It failed to work when I type first word but when I type second word, the counterRef turns to 3.

Exp:

[ ] -> 2 words
Hello -> 2 words
Hello world -> 3 words
Hello world, Quill -> 4 words

Is there any issue with the demo code?

**Comment by benbro** [comment]
react-quilljs is a third party project. Please ask there about the custom module.
You'll might be interested in this [guide](https://quilljs.com/guides/building-a-custom-module/).
