### ISSUE TITLE
applying custom format has unexpected behavior on element class name

### ISSUE THREAD

**Issue by brettimus** [quilljs/quill#374]
Excuse the vague title, but I'm not sure if this is _actually_ a bug.

I'm on Chrome 42, Mac.

To reproduce, go to the [quill home page](http://quilljs.com/), open up the console, and write

```javascript
quill.addFormat("mention", { tag: "SPAN", "class": "ql-mention-item" });
quill.insertText(0, "this is a mention", "mention", true);
```

Look at your inserted text in the inspector. You should see that quill appended `true` to the class name.

![image](https://cloud.githubusercontent.com/assets/3201327/7743535/abd24376-ff50-11e4-8d4c-039733527386.png)

Using a default class name that is an empty string throws an error. Similarly, setting a class name with a space at the end will throw an error.

**Comment by jhchen** [comment]
The current class system is not designed for binary values, ex. having a set class vs not. The class key in the format config is meant to be a prefix for classnames and the suffix is the value, ex. with { class: "author-" } an html element with a classname author-jason would have the format with value jason.

The new custom format system currently being worked on will handle binary values but for now this is not specifically supported. A workaround might be:

```js
quill.addFormat("mention", { tag: "SPAN", "class": "ql-mention-" });
quill.insertText(0, "this is a mention", "mention", "item");
```

**Comment by brettimus** [comment]
Thanks! That was the workaround I ended up going with.
