### ISSUE TITLE
Correct way to delete all text content (everything) and clear the editor

### ISSUE THREAD

**Issue by ADTC** [quilljs/quill#3758]
What is the correct way to delete all text content (everything) and clear the editor?

Is it one of these?

```js
 1. quill.deleteText();
 2. quill.deleteText(0);
 3. quill.deleteText(0, quill.getLength());
 4. quill.setContents();
 5. quill.setContents('');
 6. quill.setContents('\n');
 7. quill.setContents([{ insert: '\n' }]);
 8. quill.setText();
 9. quill.setText('');
10. quill.setText('\n');
11. quill.updateContents(new Delta().delete(0));
```

**Comment by luin** [comment]
`quill.deleteText(0, quill.getLength())` would be simplest way. `quill.setContents(new Delta().insert('\n'))` also gives you the same result though.

**Comment by ADTC** [comment]
Thanks for the tip. I think having a simple API function like `quill.clear()` or `quill.clearText()` could be useful, so that the exact detail of _how_ you're clearing all content, is yours to decide internally.

**Comment by benbro** [comment]
Answered.
