### ISSUE TITLE
Support where-condition on onConflictUpdate (postgres)

### ISSUE THREAD

**Issue by valentin-panalyt** [quilljs/quill#3760]
Currently there is no support to add a condition for an [onConflictUpdate statement](https://getquill.io/#writing-queries-actions-insert-or-update-upsert-conflict). It should be possible to specify a condition that decides whether the on-conflict operation is executed, [as specified in the postgres documentation](https://www.postgresql.org/docs/15/sql-insert.html).

This is in particular relevant if the conflict-condition relies on indexes that, themselves, are defined using a condition. In this case, if the exact same condition of the index isn't specified in the on conflict clause, postgres will return an error like this: `ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification`

**Version**: 4.6.0

**Comment by benbro** [comment]
Wrong project.
