### ISSUE TITLE
className does not accept spaces. I want to put a string in className with multiple classes

### ISSUE THREAD

**Issue by hhvdblom** [quilljs/quill#3761]
Wanted behavior is that the `className`  property of  the class: `Quill.import('blots/inline')` accept spaces in it so multiple classes can be given. I needed this because I was extending the class as a `Link blot`. That link blot needed a className but only accepted a spaceless name. The needed styling of the link was with multiple classes.

I developed my website on platform NodeJs with browser Chrome. I used version 1.3.7  of Quill.  Changed code on line 5775 in:
 ```
if (this.className) {
   var classList = this.className.split(' ');
   for (var classIndex = 0, length = classList.length; classIndex < length; classIndex++) 
      node.classList.add(classList[classIndex]);
 }                    
 return node;
```

**Comment by o2sevruk** [comment]
I had the same issue. The problem was in the plugin. I think the problem cannot be solved without fixing the plugin code, since an array cannot be passed as a parameter.
The problem was on line 5699 in the quill.js file:
```
if (this.className) {
    node.classList.add(this.className);
```
I fixed it like this:
```
if (this.className) {
    if (typeof this.className === 'string') {
      node.classList.add(this.className);
    } else {
      node.classList.add(...this.className);
    }
  }
```
