### ISSUE TITLE
Error when deleting text Quill in Vuejs 

### ISSUE THREAD

**Issue by CharlFrancois** [quilljs/quill#3763]
Hello, I have a problem when I'm deleting some text in my editor, when i delete more than 2 or 3 three character, my position line change and go to the first line.
This is my code, do you see something I need to edit ? 

`<template>
  <div class="app-text-editor">
    <div id="toolbar">
      <div class="ql-formats">
        <select class="ql-size">
          <option value="small" />
          <option selected />
          <option value="large" />
          <option value="huge" />
        </select>
      </div>
      <div class="ql-formats">
        <select class="ql-color">
          <option selected />
          <option value="red" />
          <option value="orange" />
          <option value="yellow" />
          <option value="green" />
          <option value="blue" />
          <option value="purple" />
        </select>
        <select class="ql-background">
          <option selected />
          <option value="red" />
          <option value="orange" />
          <option value="yellow" />
          <option value="green" />
          <option value="blue" />
          <option value="purple" />
        </select>
      </div>
      <div class="ql-formats">
        <button class="ql-bold" />
        <button class="ql-italic" />
        <button class="ql-underline" />
        <button class="ql-strike" />
      </div>
      <div class="ql-formats">
        <button class="ql-list" value="ordered" />
        <button class="ql-list" value="bullet" />
        <select class="ql-align">
          <option selected />
          <option value="center" />
          <option value="right" />
          <option value="justify" />
        </select>
      </div>
    </div>
    <div id="editor" />
  </div>
</template>

<script setup>
  import { onMounted, ref } from 'vue'
  import { useI18n } from 'vue-i18n'
  import Quill from 'quill'
  import 'quill/dist/quill.core.css'
  import 'quill/dist/quill.snow.css'

  const props = defineProps({
    modelValue: {
      type: String,
      default: null
    }
  })

  const emits = defineEmits(['update:modelValue'])

  const i18n = useI18n()
  const quill = ref(null)

  onMounted(() => {
    var options = {
      modules: {
        toolbar: '#toolbar'
      },
      theme: 'snow',
      placeholder: i18n.t('app-text-editor.type-text')
    }
    quill.value = new Quill('#editor', options)
    setText()
    watchText()
  })

  const watchText = () => quill.value.on('text-change', () => emits('update:modelValue', quill.value?.root?.innerHTML))

  const setText = () => {
    const text = props.modelValue
    const delta = quill.value.clipboard.convert(text)

    quill.value.setContents(delta, 'silent')
  }
</script>

<style lang="scss" scoped>
  .app-text-editor {
    height: 100%;
    display: flex;
    flex-direction: column;
    #toolbar,
    #editor {
      background-color: var(--color-light-grey);
      border: none;
    }
    #toolbar {
      border-radius: 1.25rem 1.25rem 0 0;
    }
    #editor {
      border-radius: 0 0 1.25rem 1.25rem;
    }
  }
</style>
`

**Comment by benbro** [comment]
Can you reproduce here?
https://quilljs.com/standalone/full
If not, it's something specific to your code.
