### ISSUE TITLE
No way to add `target="_blank"` to links.

### ISSUE THREAD

**Issue by chriskuech** [quilljs/quill#3764]
According to #1139, it seems like `target="_blank"` on links is the default behavior, but it's not present. Further, it does not seem possible to add it.

**Steps for Reproduction**
1. Override a link component
  ```ts
  // https://github.com/zenoamaro/react-quill/issues/761
  Quill.register(
    class PatchedLink extends Quill.import("formats/link") {
      static create(value: string) {
        const node = super.create(value);
  
        const sanitized: string = super.sanitize(value);
  
        const href = !/^https?:\/\//i.test(sanitized)
          ? `https://${sanitized}`
          : sanitized;
  
        node.setAttribute("href", href);
  
        // I'd expect this to work, based on https://github.com/quilljs/quill/issues/1139
        // ...but it doesn't...
        node.className = "link--external";
        node.setAttribute("target", "_blank");
  
        return node;
      }
    }
  );
  ```
2. Create a link in the Quill editor
3. Note that the `href` has changed but not the `target`, indicating the code has run but `target` is not being added.

**Expected behavior**:
Links have attribute `target="_blank"`.

**Actual behavior**:
Links do not have `target` attribute.

**Platforms**:

Include browser, operating system and respective versions
Brave latest
macOS latest

**Version**:

Run `Quill.version` to find out
1.3.7

**Comment by Lexpeee** [comment]
Any update on this one?

**Comment by evgeniyworkbel** [comment]
Try to separate logic: extract custom class into file, extract Quill.import into separated function call,

**Comment by chriskuech** [comment]
Any update on this? We get periodic complaints about this behavior.

**Comment by benbro** [comment]
Tested on https://quilljs.com/ I do see target="_blank" added by default. Please share a working example on [CodePen](https://quilljs.com/playground/) showing the issue.

**Comment by chriskuech** [comment]
@benbro did you override the default Link as required by the repro?

**Comment by benbro** [comment]
@chriskuech there is no need to override Link if by default it does what you want. 
Do you have a minimal example showing the issue? Not just a block of code but a working example on [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com)

**Comment by chriskuech** [comment]
The point is I already have to override Link for other reasons, and when I do it no longer has the default behavior
