### ISSUE TITLE
React Quill Editor breaking when re-rendering list of multiple quill editors (on removing a Quill editor in the middle)

### ISSUE THREAD

**Issue by vikram-bik** [quilljs/quill#3765]
Print a list of multiple Quill editors.
Delete a middle list item. 
When the Quill editors re-renders , all the quill editors after the removed list item, is not rendered, comes as blank.

**Comment by shareefalis** [comment]
Revert to react quil 2.0 l dev4, there is a regression in the  final  release..That bug need to be addressed in react-quill library, not here
