### ISSUE TITLE
Is there a way to easily convert entries containing arbitrary HTML to without arbitrary HTML

### ISSUE THREAD

**Issue by boy-incerta** [quilljs/quill#3766]
Hi, 

We are currently in the migration of a legacy rich text editor towards the one provided by DevExtreme (which is a fork of Quill).

Up until now, users were able to store arbitrary HTML because the old editor supported this. After the migration to the new editor, we see that opening any editor immediately fires a change event (because Quill tries to parse into Parchment). This results in stale input and a popup asking users what they want to do with their unsaved changes (even though they didn't do any).

As we have hundreds and maybe thousands of records in our database build with the previous editor, it's impossibly to open them all manually and save. That's why I was wondering whether there is a way that we can automatically convert old records to supported content. 

e.g.  `<b>this is a test</b><p></p>` will be changed to a version without the empty paragraph
e.g. `<p><img src="data:image` will be changed to `<p style="padding: 0px; margin: 0px;"><img src="data:image`

I don't want to discuss the reason why Quill doesn't support arbitrary HTML. I think there is a good reason for that, but I'm just looking how we can relatively easy fix the contents without manually having to open them one by one and save.

Thanks in advance!

**Comment by benbro** [comment]
The old format should be converted outside of Quill.
