### ISSUE TITLE
is this repo not maintained any longer?

### ISSUE THREAD

**Issue by artknight** [quilljs/quill#3768]
I am not seeing any work being done in a long time!

Is this still maintained?

**Comment by artknight** [comment]
@jhchen if you are unable/willing to continue development, perhaps you can give the reigns to someone else who can maintain it? I am a user, and have implemented QuillJS 2.0-dev in my main project. However, the lack of time makes me a poor maintainer, so I am not volunteering. I do love the product though so I want to see it succeed!!!

Maybe someone from the community wants to step up and volunteer?

**Comment by volnei** [comment]
Really sad this neglect...

**Comment by bmfmsd** [comment]
I have a same question.

**Comment by JorisDebonnet** [comment]
See this comment from @luin from half a year ago. We can hope!
https://github.com/quilljs/quill/issues/3694#issuecomment-1321038930

**Comment by luin** [comment]
Hello 👋 We are working towards the release of version 2.0 so yeah it's now maintained and we are putting more engineering resources into it.

**Comment by paulcarroll** [comment]
Hi @luin , 
Love the project and appreciate all the efforts, it's seriously amazing work
Is there any possibility we could see a maintenance release of v1 at some stage? I don't want to pressure for v2, but our dependency scanners start to light up and people get concerned when they see a project that is 4 years out of date (and rightly so)
"Just" a maintenance release to update the dependencies would be amazing!

**Comment by MuaazOsaidTahir** [comment]
Hey @luin .
Hope you're doing well.
Can you please provide any ETA for the production ready use of Quill v2?
It would be great if you can just let us know because we're already using v1.3.7  in production.
Thanks.

**Comment by luin** [comment]
@MuaazOsaidTahir I don't have an exact timeline for the release of v2 to share with you, but I am actively working on it. I hope it can be released within a couple of months.

**Comment by MuaazOsaidTahir** [comment]
Appreciate your response. @luin 
Well we're eagerly waiting for it's v2.
It's a great project & I don't want to move away from it. 
But in it's v1 its lacking some of the main modules like Table & some other modules like that.
But still waiting for more updates & Quill's v2 eagerly.
Once again Thanks for keeping us updated.

**Comment by freddsomm** [comment]
@luin Do you have an update on this?

**Comment by luin** [comment]
We have just released version 2.0.0-rc.3, which should include all the features we intend to bundle in version 2.0 at this time. I believe we can wait for a couple more weeks to observe whether there is feedback from the community before releasing a stable version.

**Comment by jeannnemelanie** [comment]
@luin I can't find the `2.0.0-rc.3` version ?? The last version available I see is `2.0.0-beta.2`.

**Comment by luin** [comment]
@jeannnemelanie Where did you see it? It's in [npm](https://www.npmjs.com/package/quill/v/2.0.0-rc.4) (now the latest version is 2.0.0-rc.4).

**Comment by jeannnemelanie** [comment]
@luin I though you were speaking about [react-quill](https://www.npmjs.com/package/react-quill?activeTab=versions) but I understand the `2.0.0-rc.3` is for `quill` ! Do you plan any update for `react-quill` using `quill v2.0.0` ?

**Comment by luin** [comment]
@jeannnemelanie I'd love to but react-quill is not maintained by us. However, before react-quill uses Quill v2, you can use Quill in your React project without a library. A sample https://quilljs.com/playground/react

**Comment by jeannnemelanie** [comment]
@luin I'm so sorry, I thought this was a `react-quill` issues as I came here from another `react-quill` issue... Sorry for the confusion!! And thank you for your answers.
