### ISSUE TITLE
Indentation in editor not working

### ISSUE THREAD

**Issue by jnewcs** [quilljs/quill#377]
How do we enable indent/outdent? Is the best way to add a hotkey? Or is there a way to enable it when we initialize the editor?

**Comment by jhchen** [comment]
Do you mean for a numbered or bulleted list?

**Comment by jnewcs** [comment]
When the user clicks the tab key, the editor doesn't indent automatically. Thanks!

**Comment by jhchen** [comment]
I assume you mean hitting the tab key on the keyboard? The expected behavior is to insert a tab character which it appears to be doing. If this is not what you are seeing please detail more precisely the steps for reproduction and what browser + OS you are using.
