### ISSUE TITLE
Delta codeblocks representation

### ISSUE THREAD

**Issue by adatti** [quilljs/quill#3772]
I'm having some difficulty decrypting the Delta format when it comes to codeblocks. For instance, here are two Delta objects which differ by just one character:

![image](https://user-images.githubusercontent.com/98817622/234081670-552a4a02-a0a5-4d0c-9748-596b9d75ead2.png)

The one on the left describes ```code\n\ncode```, while the right one is ```code``` + \n\n + ```code```. But I don't understand the principle. Let's say I want to convert this Delta into Markdown syntax, how would I go about it?

P.S. Please forgive my laziness for not making a codepen, I just figured this is something intuitive for you since you developed it.

**Comment by luin** [comment]
The `attributes` applied to `\n` will apply the format to the entire line so on the left side it would look like:

```
hello

goodbye
```

whereas on the right side it would be:

```
hello
```

```
goodbye
```

**Comment by adatti** [comment]
@luin idk I suppose this is intuitive to you, but I'm still very confused. Do you have any example code that converts a delta object into markdown/html/anything else?

**Comment by adatti** [comment]
@luin I just wrote some pseudocode to iterate over `Delta.ops` and convert it to Markdown while tracking whether or not we are currently at a code block. Could you take a peek and tell me if the logic is sound? Here it is:

```javascript
finalStr = '';
atCodeblock = false;

for (op,idx) in ops:

  // if we haven't opened a code block AND the next op doesn't have a code-block attribute
  if (!atCodeblock && !ops[idx+1].attributes.codeblock):
    insertMd = convertToMarkdown(op.insert, op.attributes);
    finalStr += insertMd;
    continue;
  
  // if we haven't opened a code block AND the next op has a code-block attribute
  if (!atCodeblock && ops[idx+1].attributes.codeblock):
    [before, after] = op.insert.splitByLastNewline();
    finalStr += before;
    finalStr += "```";
    finalStr += "\n"
    finalStr += after;
    atCodeblock = true;
    continue;

  // if we have opened a code block AND the current op has a code-block attribute
  if (atCodeblock && op.attributes.codeblock):
    // if the next-next op (2 steps ahead) doesn't have a code-block attribute OR the next op (1 step ahead) has newline in insert
    if (!ops[idx+2].attributes.codeblock || ops[idx+1].insert.includes(\n)):
      atCodeblock = false;
      finalStr += "\n";
      finalStr += "```";
    finalStr += op.insert;
    continue;

  if (atCodeblock && !op.attributes.codeblock):
    finalStr += op.insert;
    continue;
```
