### ISSUE TITLE
The full screen button icon is not displayed, but can be clicked

### ISSUE THREAD

**Issue by pigping88** [quilljs/quill#3775]
the version: 1.3.7
toolbar: [
            ["bold", "italic", "underline", "strike"],       // 加粗 斜体 下划线 删除线
            ["blockquote", "code-block"],                    // 引用  代码块
            [{ list: "ordered" }, { list: "bullet" }],       // 有序、无序列表
            [{ indent: "-1" }, { indent: "+1" }],            // 缩进
            [{ size: ["small", false, "large", "huge"] }],   // 字体大小
            [{ header: [1, 2, 3, 4, 5, 6, false] }],         // 标题
            [{ color: [] }, { background: [] }],             // 字体颜色、字体背景颜色
            [{ align: [] }],                                 // 对齐方式
            ["clean"],                                       // 清除文本格式
            ["link", "image", "video"],                       // 链接、图片、视频
            ['fullscreen']                          // 全屏按钮
          ],
![WX20230509-155248@2x](https://user-images.githubusercontent.com/114716671/237031065-fd72602b-4c40-4afe-af83-fb89c475ceb6.png)

**Comment by Ablewang** [comment]
我认为这是因为没有内置的全屏操作，你要自己定义'ql-fullscreen'样式，还需要通过modules属性配置或调用toolbar的addHandler接口添加事件

**Comment by benbro** [comment]
Fullscreen is not a supported button. You'll need to add support for it.
https://quilljs.com/docs/modules/toolbar/

**Comment by benbro** [comment]
Duplicate https://github.com/quilljs/quill/issues/1016
