### ISSUE TITLE
Is there a release plan this year?

### ISSUE THREAD

**Issue by bmfmsd** [quilljs/quill#3776]
I've noticed that someone has recently started updating code to the dev branch. Is there a release plan this year? @jhchen

**Comment by luin** [comment]
Hey @bmfmsd 👋,
Thank you for your interest in Quill! We don't have a specific date yet, but yes, we plan to release a new version within this year.

**Comment by bmfmsd** [comment]
> Hey @bmfmsd 👋, Thank you for your interest in Quill! We don't have a specific date yet, but yes, we plan to release a new version within this year.

Thank you very much for your prompt reply.

**Comment by kundanashish** [comment]
Hi @luin 
We are planning to quill in our new project. Will you be able to confirm that the new one will come backward compatible at least in terms of Delta value.
please advise

**Comment by luin** [comment]
@kundanashish Delta format will not change, and as for the API, there won't be significant differences between the 2.0 official release and the current code on the develop branch.

**Comment by kundanashish** [comment]
Hi @luin 
Thanks for the quick response.
We found some beta/dev version as used in this demo
https://codepen.io/quill/pen/QxypzX

Not sure how much it is stable or not. I can't see any branch dedicated for version 2 as well. Is there any?
Please guide

**Comment by luin** [comment]
> I can't see any branch dedicated for version 2 as well. Is there any?

It's on the develop branch.

**Comment by pablopla** [comment]
Any chance for another dev release (v2.0.0-dev.1)?

**Comment by luin** [comment]
@pablopla It's planned but we don't have an ETA yet.

**Comment by shareefalis** [comment]
Hi  @luin, 
 
 Any plans for RC release of Quill 2.0?    It would be nice to have a solid build before the  2.0 official release

Shareef
