### ISSUE TITLE
Cursor doesn't work when the editor has a scroll bar

### ISSUE THREAD

**Issue by cphyc** [quilljs/quill#378]
You can reproduce the bug on the page http://quilljs.com/examples/. You paste a text long enough to get a scroll bar on quill's side. Then you scroll the "Full example" a bit.
Now if you move the cursor in the basic example, it won't appear at the right place (sometimes it doesn't appear at all).

**Comment by jhchen** [comment]
Thanks for the report. The issue has been fixed in https://github.com/quilljs/quill/pull/375. This should be out in a new release in the next few days.
