### ISSUE TITLE
Theres no clear instructions for starting a new project

### ISSUE THREAD

**Issue by MrLanguageApp** [quilljs/quill#3786]
Started from https://quilljs.com/ and looking at github.

Have had many problems getting started with no knowledge of Quill.

**Comment by benbro** [comment]
There is a quickstart and playground:
https://quilljs.com/docs/quickstart/
https://quilljs.com/playground/

**Comment by MrLanguageApp** [comment]
This guide doesnt show you how to import Quill into your javascript.
