### ISSUE TITLE
XSS Vulnerability in Quill

### ISSUE THREAD

**Issue by Visakeswaran** [quilljs/quill#3794]
We are using Quill version `1.3.2` in my organisation. I went through previous issues and saw there is a XSS Vulnerability in 1.X versions, including the stable `1.3.7` #2768.  

I wanted to know if this is issue is fixed in 2.X ? Also, I see 2.X is still in dev stage, is there any ETA for the stable release ?

If it's  gonna take time for stable release, is there any workaround that we could possibly adopt ?

**Comment by stormyordos** [comment]
Confirmed as well on a 1.3.4 installation, using the "onload" parameter of an <image> tag inserted within a comment. Still no workaround?
