### ISSUE TITLE
Error when entering mathematical formulas and Korean together

### ISSUE THREAD

**Issue by ejaman** [quilljs/quill#3796]
Hello, 
I'm reporting an error that occurs when entering mathematical formulas and Korean text together in the editor using Quill.

**Steps for Reproduction**

1. Visit [[quilljs.com, jsfiddle.net, codepen.io]](https://quilljs.com/)
2. Step Two
First, create any mathematical formula.
<img src="https://github.com/quilljs/quill/assets/82802784/c969cca6-b52f-4e58-b4df-0598cc4bd186" width="500" height="300"/>

3. Step Three
Remove the space right after the mathematical formula and enter Korean text.
<img src="https://github.com/quilljs/quill/assets/82802784/2ef39a0b-6e29-413c-b783-308e8a69174e" width="500" height="300"/>

then you can find first consonant you type is being duplicated.

**Expected behavior**:
"한국어"

**Actual behavior**:
"ㅎ한국어"

**Platforms**:
chrome

**Version**:
"quill": "^1.3.7",
Run `Quill.version` to find out

**Comment by MiniJude** [comment]
Actually, it has the same behavior in chinese.
