### ISSUE TITLE
Issue found by CodeQL in two locations in js Incomplete string escaping or encoding

### ISSUE THREAD

**Issue by mpaulosky** [quilljs/quill#3828]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

I just installed quill and liked the result in my Blog application. But when I pushed the project to GitHub and my CodeQL and Dependabot ran on the project it found these Issues.

**Steps for Reproduction**
A CodeQL scan found this issue:
"Incomplete string escaping or encoding"

At this location: wwwroot/lib/quill/modules/toolbar.js:122

            value = value.replace(/\"/g, '\\"');

And also this location: wwwroot/lib/quill/dist/quill.js:9496

This does not escape backslash characters in the input.

This is CodeQL's description of the problem:

> Sanitizing untrusted input is a common technique for preventing injection attacks such as SQL injection or cross-site scripting. Usually, this is done by escaping meta-characters such as quotes in a domain-specific way so that they are treated as normal characters.

> However, directly using the string replace method to perform escaping is notoriously error-prone. Common mistakes include only replacing the first occurrence of a meta-character, or backslash-escaping various meta-characters but not the backslash itself.

> In the former case, later meta-characters are left undisturbed and can be used to subvert the sanitization. In the latter case, preceding a meta-character with a backslash leads to the backslash being escaped, but the meta-character appearing un-escaped, which again makes the sanitization ineffective.

> Even if the escaped string is not used in a security-critical context, incomplete escaping may still have undesirable effects, such as badly rendered or confusing output.

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**: No Security Issues

**Actual behavior**: High Severity

**Platforms**:

Include browser, operating system and respective versions

**Version**: v1.3.7

Run `Quill.version` to find out

**Comment by shun2218-dev** [comment]
This pull request is closed once due to a dependencyabot misconfiguration.
