### ISSUE TITLE
2.0.0-dev4 substantially slower than 2.0.0-dev3 on nieuw paragraph/block

### ISSUE THREAD

**Issue by hdijkema** [quilljs/quill#3834]
Load a large document in a chromium browser, with also some image inside (but without it is still slow).  

**Steps for Reproduction**

1. Load a large quill document in the quill editor. 
2. Press enter somewhere at the top.
3. See a notable difference between 2.0.0-dev4 and 2.0.0-dev3

**Expected behavior**:
dev4 as fast as dev3.

**Actual behavior**:
dev4 much slower than dev3

**Platforms**:
Linux - debian 12
Microsoft Edge Versie 114.0.1823.79 (Officiële build) (64-bits)
FireFox 102.13.0esr.
CPU: Celeron J3450

**Version**:
v2.0.0dev4

**Comment by luin** [comment]
Hey @hdijkema 👋 

We've added several performance improvements since dev4 and those should address the issue. It has not been released yet but we are working on it.

**Comment by hdijkema** [comment]
Thank you, I’m looking forward to the dev5 release!

**Comment by kilobyte2007** [comment]
Hey @luin, is there anywhere where we can find more info about the plans for Quill and the general direction of the library? Would be great to understand where it's moving and what plans you have for it. I see there are a lot of commits recently so it looks really positive and thank you very much for the hard work. But there are 1.3K open issues, so I would be curious what's the plan here. We are using the 1.3.7 version and it works mostly great even though it has its limitations and bugs so I'm looking forward to the 2.0 release.

**Comment by luin** [comment]
Hi @kilobyte2007 👋

While I don't have an exact timeline to share, I'm working actively on the 2.0 release. I hope we can release the first rc version within the next 2 months.

**Comment by kilobyte2007** [comment]
Hey @luin,
Thanks a lot for the update, really pumped. Let me know if some help is needed!

**Comment by benbro** [comment]
Please test on recent beta release:
https://v2.quilljs.com/standalone/full
