### ISSUE TITLE
Slab has a very serious issue that needs to be fixed as soon as possible

### ISSUE THREAD

**Issue by lefex** [quilljs/quill#3837]
In Slab, when using Safari browser, it's not possible to input Chinese ordered lists as the entered content will be automatically deleted. However, entering English or numbers works without issues. It's hoped that the author could provide a high-priority solution for this problem, which also occurs in Quill editor version 2.0.

<img width="447" alt="image" src="https://github.com/quilljs/quill/assets/8437666/09f0368c-9168-44fb-a191-79696734d053">

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**: Can input Chinese ordered lists

**Actual behavior**:can not input Chinese ordered lists

**Platforms**:Safari 15.1

Include browser, operating system and respective versions

**Version**: 2.0

Run `Quill.version` to find out

**Comment by luin** [comment]
Thanks for raising this up! Confirmed and will take a look.
