### ISSUE TITLE
Feature Request - Progress Indication

### ISSUE THREAD

**Issue by hdijkema** [quilljs/quill#3839]
As documents get bigger, loading can take some time. It would be nice if one could add a progress indication to 'setContents'.

2.0.0-dev.3 (4)

**Comment by luin** [comment]
Thanks for using Quill. The overall performance has been improved a lot in the develop branch and we are working on a new release. For the feature request, I don't think it's possible as `setContents` works in a sync way so there's no chance for it to report progress.

**Comment by hdijkema** [comment]
Thank you for your answer!A couple of quick questions:1. Would it be possible to feed the input format to quill externally part by part?2. Would it not be possible to feed a callback function to setContents that gets called regularly, eg every 1000 inserts?  Verstuurd vanaf mijn iPhoneOp 29 jul. 2023 om 14:02 heeft Zihua Li ***@***.***> het volgende geschreven:﻿
Thanks for using Quill. The overall performance has been improved a lot in the develop branch and we are working on a new release. For the feature request, I don't think it's possible as setContents works in a sync way so there's no chance for it to report progress.

**Comment by benbro** [comment]
That's what [updateContent](https://quilljs.com/docs/api#updatecontents) is for. You'll might need to modify the delta each time to retain the existing length.
