### ISSUE TITLE
Formatting lost when pasting rich text

### ISSUE THREAD

**Issue by dandv** [quilljs/quill#384]
I've pasted an [excerpt from Addy Osmani's JavaScript Patterns](http://addyosmani.com/resources/essentialjsdesignpatterns/book/#summarytabledesignpatterns). The result was this:

![image](https://cloud.githubusercontent.com/assets/33569/7880811/fed30b20-05b1-11e5-9dcc-040fdfa2ae23.png)

Would it be possible to fix the line alignment? [Froala managed to](https://github.com/froala/wysiwyg-editor/issues/552).

Of course, reproducing the source styles would be fantastic. Froala lost the colors, but they're still there in Quill.

**Comment by jhchen** [comment]
Quill's data model currently cannot support such content since it doesn't have columns or code support. The [Custom Formats](https://github.com/quilljs/quill/milestones/Customizable%20Formats) milestone currently being worked on would add this capability.

**Comment by jhchen** [comment]
I'm going to close this as a won't fix after taking another look at it. It's not within Quill's scope to be able to interpret arbitrary HTML input. The gutter with line numbers is a previous sibling to the code container's. Quill would have to be able to visually as well as structurally interpret the content and I don't see that happening.
