### ISSUE TITLE
Formatting not applied to selected text

### ISSUE THREAD

**Issue by JSommersKLH** [quilljs/quill#3844]
With even the basic provided examples, selecting text and clicking any formatting button results in the selection being lost, the cursor moving to the beginning of the text, and no formatting being applied to the previously selected text. Typing new text from the current cursor location results in the new text bearing the format that was just selected. For example, select a word, and click bold. That word does not become bold, and the cursor moves to the beginning of the editor. Now type another word and that new word will be bold.

**Comment by luin** [comment]
Can you post a link to a reproducible example? Does the issue exist on https://quilljs.com/?
