### ISSUE TITLE
how to save to database in optimal way?

### ISSUE THREAD

**Issue by terlan4** [quilljs/quill#3847]
So while multiple clients edit the content, we only send changes through websockets and other clients' editors merge new changes automatically.

But what about saving the content to database? Database service doesn't know how to merge new changes to what is already saved. When we save to database, do we have only these two options:

send only changes to your server and let the server merge it with what is saved in database and save the result to db store.
send entire document on your editor with request to save in db
None of these options sound good bandwidthwise. I would be really happy to hear what are the best practices around saving to db.

Also should we save as blob or which data type? (please suggest both for mongo and mysql)

(frontent-nextjs, backend-either next serverless, express, or fastify)

**Comment by benbro** [comment]
You'll might be interested in https://github.com/slab/delta-elixir as an example for merging changes on the backend.
Quill Delta is JSON. Your other questions are out of scope.
