### ISSUE TITLE
Cursor jumps to top when clicking toolbar

### ISSUE THREAD

**Issue by Roan128** [quilljs/quill#3867]
I have been implementing Quill in my svelte project. But when I press a button on the toolbar, it places to cursor at the beginning of the editor, making it unable to edit text somewhere in the middle of the editor for example. See gif for example: 
![7d2a5d6fa9ab25fa4ed68da89361eb62](https://github.com/quilljs/quill/assets/57260236/570d422a-22f4-480e-afad-4379441bd736)

Stackoverflow link for more information: https://stackoverflow.com/questions/77014478/quilljs-cursor-jumps-to-top-when-clicking-toolbar

**Steps for Reproduction**

1. Build a quill editor in Svelte within the onMount().
2. Browse to page.
3. Start trying to apply markup like making the text bold somewhere. 
4. Cursor jumps back to start.

**Expected behavior**: Toolbar button stays blue and cursor stays where it was. Styling can be applied everywhere.

**Actual behavior**: Cursor jumps to index 0,0 and can only apply markup there. After pressing a button on my keyboard it dissapears.

**Platforms**: 
Microsoft Edge for Business Version 116.0.1938.62 (Official build) (64-bit)
Svelte 3.54.0
Windows 10 PRO Version 10.0.19045 Build 19045

**Version**: 1.3.6

**Comment by Kedar782** [comment]
I'm not getting <br> between two paragraphs.

You know how can I fix it?
@Roan128

**Comment by juanLoyolaSato** [comment]
31/10/2023

I have the same error, project with Preact and tailwind.

Following the docs and applying the same examples the behavior breaks causing cursor jumps at the start of the editor, making it impossible to use.

In the console I only see:

`quill.js:4165 [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.`

The funny thing is that this same error also appears in the playground that quill [offers](https://quilljs.com/playground/)
