### ISSUE TITLE
Having difficulties preventing line breaks in copy pasted text entered into Quill.

### ISSUE THREAD

**Issue by randomock** [quilljs/quill#3869]
Hi there,
I'm using a number of ReactQuill text editors in an app I'm developing.  The majority of the text editors we're using have no character limits or other constraints and have been relatively simple to configure, however one of our text editors is meant for a user to enter a video or image credit into, and as such we require only one line of text whether that be typed in or copy pasted in from elsewhere.

I've found success in preventing users from creating a new line break by adding a keyboard binding for the enter key within modules, but users are still able to copy and paste text from other sources that have line breaks and those still display as they did before copy pasting, line breaks included.  In the HTML they display - as one would normally expect - in separate <p> tags.

My question is whether there is a way to prevent these line breaks from displaying that way and instead replace any line breaks with a space.  I'm essentially looking to replace //n's with " "'s.  I've tried looking through the Quill docs, scoured StackOverflow but unfortunately haven't found much info on the matter.  I've also tried creating a custom script in a matcher, but when console.logging the data all I receive is each separate line of text.

**Version**:
1.3.7

**Comment by benbro** [comment]
Depends on the actual content you are pasting. You could use [addMatcher](https://quilljs.com/docs/modules/clipboard/#addmatcher) or [extend the clipboard module](https://stackoverflow.com/questions/41237486/how-to-paste-plain-text-in-a-quill-based-editor).
In this example we are converting text to plain text. You can modify it for your use case.
```javascript
quill.clipboard.addMatcher (Node.ELEMENT_NODE, function (node, delta) {
    var plaintext = node.innerText
    var Delta = Quill.import('delta')
    return new Delta().insert(plaintext)
})
```
