### ISSUE TITLE
Background color not copied when coping from VS Code.

### ISSUE THREAD

**Issue by alexbalak21** [quilljs/quill#3870]
Hello,

I am interested in using Quill for my project. I work with VS Code a lot and, I wanted to integrate copy and paste  directly form vs code.
But it seems every time I copy from VS Code, the background color do not copy in the Quill Editor.

Here is what I have in VS Code :
![image](https://github.com/quilljs/quill/assets/79265890/b826996b-1c73-41f6-847a-a504e297e9fd)

And here is what I get when pasting in Quill:
![image](https://github.com/quilljs/quill/assets/79265890/2746469f-a70c-4c62-a579-cf1878ef1a51)

Can you tell me how to fix the background color issue ?

Thanks a lot !

**Comment by benbro** [comment]
There is no background color in VS code. The background is transparent and the color you see depends on the VS code theme.
Try to copy&paste to Word or any other editor.
