### ISSUE TITLE
Insert a link to open in a same tab

### ISSUE THREAD

**Issue by BDhara** [quilljs/quill#3873]
How can I add a link which opens in a same tab instead of default new tab?  I have a huge library which internally use quill.js. Now client needs this feature but quill has set _blank by default in all anchor tag.

**Steps for Reproduction**

1. In WYSIWYG wizard, select text click on link
2. add the link and save it.

**Expected behavior**:
should have an option to open in same tab

**Actual behavior**:
default behavior - open link in new tab

**Version**:

Run `Quill.version` to find out
1.3.7

**Comment by benbro** [comment]
Duplicate:
https://github.com/quilljs/quill/issues/1139
