### ISSUE TITLE
Shift-Enter for space between ordered list items

### ISSUE THREAD

**Issue by jeriahwc** [quilljs/quill#3874]
Is there a good way to add Shift-Enter support to add line spaces between ordered list items without the ordered list being separated into 2 lists?

For example if I have this list:
1 First Item
2 Second item
3 Third item

And I want to add space between the first item and second item with my cursor at the end of the first item I would use Shift-Enter to get:

 1 First Item
(blank line space)
 2 Second Item
 3 Third Item 

However in quill when using Shift-Enter I get:
1 First Item
(blank line space)
1 Second Item
2 Third Item

Does anyone have a good implementation of this or suggestion of how to accomplish this?

**Comment by jt3k** [comment]
There seems to be no solution with quilljs for most of the problems that ckeditor can easily solve

**Comment by jeriahwc** [comment]
Thank you for your suggestion! However, quill is much better suited to my needs at the moment.
