### ISSUE TITLE
how to add custom functions like this.quill.format('bold' , .... ?

### ISSUE THREAD

**Issue by jt3k** [quilljs/quill#3878]
Okay. We have an example where you use formatting like this.

```js
const configureQuill = (quill) =>
  quill.getModule('toolbar').addHandler('bold', function (value) {
    this.quill.format('bold', value);
  });
```

The highlighted text after clicking on the toolbar becomes from this `foo` to this `<b>foo</b>`.

Is there any way to define my own this.quill.format functions? e.g. so that I can make `<mark>foo</mark>` from `foo` into this string.

I didn't find any useful information in your documentation. I don't know if this is intentional or if you have really abandoned development, but I need help with this task because I don't understand how I can customize the toolbar when using react-admin.

**UPD:** It seems I was too hasty with curse words, because I looked in the source code and found a certain pergament library inside that project, I found a link to quill and now I’m reading these explanations https://quilljs.com/guides/cloning-medium-with-parchment/ . thank you for your attention

**Comment by benbro** [comment]
Example:
https://quilljs.com/guides/how-to-customize-quill/#customizing-blots

**Comment by jt3k** [comment]
thanx.
Quill turned out to be too complex for me to solve business problems. I had to get rid of him.
