### ISSUE TITLE
Code handling inside editor is VERY BUGGY in 2.0.0-dev.4

### ISSUE THREAD

**Issue by artknight** [quilljs/quill#3881]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**
1. Add code in the editor
2. Hit ENTER or BACKSPACE 

**Expected behavior**:
The code editing bubble should NOT be broken

_PS: this is working as expected in v1.3.7_

**Actual behavior**:
Adding a quick video here

https://github.com/quilljs/quill/assets/157762/7ce75c0e-23c2-40f5-8066-8871228cdacf

**Platforms**:
Chrome v117

**Version**:
**2.0.0-dev.4**

**Comment by artknight** [comment]
@luin @dlitsman I am using quill 2 in production in my app. Do you think you could please please fix this issue soon?

**Comment by maximlt** [comment]
@artknight do you think you could open a PR to fix this issue? I don't think it's fair asking for the maintainers of this project to quickly fix an issue on a dev version :)

**Comment by artknight** [comment]
@maximlt In any other case I would agree with you! However, the dev version has been in "dev" status for a very long time (years on end). Additionally, when asked whether this repo is dead, the maintainers of this repo responded that they are very much actively working on getting the v2 to being stable, and even that was a while back. All I am asking is to get some pretty significant regression to be looked at and fixed. It only benefits the project and everyone else who has put their trust in this project!

**Comment by artknight** [comment]
any update on this?

**Comment by benbro** [comment]
Can you reproduce with recent v2 release?
https://v2.quilljs.com/standalone/full

**Comment by artknight** [comment]
@benbro I just tested it. It seems to have resolved the issue with the code blocks. However, none of my quill modules are loading now!!  The modules included

- Quill Mentions ( https://github.com/quill-mention/quill-mention )
- Quill Emojis ( https://github.com/contentco/quill-emoji )
- Quill Resize Module ( https://github.com/mudoo/quill-resize-module )

These modules in particular were **fixed** by me to work with **v2.0.0-dev.4**. 

Do you have a list of the breaking changes in this new update?

**Comment by benbro** [comment]
Please follow:
https://v2.quilljs.com/guides/upgrading-to-2-0

Please open a new issue if you find anything missing.

**Comment by artknight** [comment]
@benbro I created an issue for this https://github.com/quilljs/quill/issues/3978

Thanks!

**Comment by benbro** [comment]
Thanks
