### ISSUE TITLE
register embed blot will effect all quill instance

### ISSUE THREAD

**Issue by neeko-iweurow** [quilljs/quill#3885]
There are two 'new quill' in my project, quill1 need insert the CustomHtmlBlot, quill2 needn't
when Quill.register(CustomHtmlBlot) 

**Steps for Reproduction**

`
class CustomHtmlBlot extends Quill.import("blots/block/embed") {
    static create(value: string) {
      let node = super.create(value);
      node.innerHTML = DOMPurify.sanitize(value, {
        FORBID_TAGS: ["style"],
      });
      return node;
    }
    static value(node: HTMLElement) {
      return node.innerHTML;
    }
  }
CustomHtmlBlot.tagName = "DIV";
CustomHtmlBlot.blotName = "custom-html-blot";
Quill.register(CustomHtmlBlot);

const quill1 = new Quill(el, {
     theme: "snow",
      formats: ['custom-html-blot'],
})

const quill2 = new Quill(el, {
     theme: "snow",
      formats: [],
})
  `

**Expected behavior**:
The quill2 can paste the text which copy from vscode or notes

**Actual behavior**:
The quill2 instance couldn't paste the text which copy from vscode or notes
The quill1 can edit the blot content
**Platforms**:
chrome

**Version**:
1.3.7

**Comment by neeko-iweurow** [comment]
please commit if anyone have solve, thanks

**Comment by easir-kh** [comment]
If I understand this correctly and I'm no quill expert, I think you maybe should look into giving your custom blot a classname like `CustomHtmlBlot.className = "YourPreferredName";`, If you add the same class to the custom html you want to insert the blot will only target that and not all divs. I hope this helps.

**Comment by neeko-iweurow** [comment]
@easir-kh It seems works, thanks. Do you how to replace quill default p tag. let quill use div tag to wrap element

**Comment by benbro** [comment]
Answered.
