### ISSUE TITLE
Quill support spoiler?

### ISSUE THREAD

**Issue by AlexInCube** [quilljs/quill#3889]
I want to hide text and pictures as shown in this gif

https://support.discord.com/hc/user_images/uFaAgbUUYeHx4U2u0mkjoA.gif

I do not know how to achieve this, maybe there is some plugin for this? Or I need to write this functionality by myself?

**Comment by MuaazOsaidTahir** [comment]
hey @AlexInCube .
I'm sure you can achieve this thing by making your own custom blot & can add event listeners on them too.

**Comment by benbro** [comment]
Thank you @MuaazOsaidTahir  for your answer.
@AlexInCube please follow the documentation:
https://quilljs.com/docs/quickstart/
https://v2.quilljs.com/docs/quickstart
