### ISSUE TITLE
Quill.js - Browser alert - Deprecated feature used

### ISSUE THREAD

**Issue by go-aegian** [quilljs/quill#3891]
Browser is raising a warning regarding line 4274 in quill.js - I'm using latest version 1.3.7

       **_this.domNode.addEventListener("DOMNodeInserted", function() { });**

DOM Mutation Events, including DOMSubtreeModified, DOMNodeInserted, DOMNodeRemoved, DOMNodeRemovedFromDocument, DOMNodeInsertedIntoDocument, and DOMCharacterDataModified are deprecated ( https://w3c.github.io/uievents/#legacy-event-types ) and will be removed. Please use MutationObserver instead.

**Comment by enterpub** [comment]
I confirm same alert in latest Chrome at the moment. It has been for a while

**Comment by snicki13** [comment]
I can confirm for Firefox 118 and Edge 115

**Comment by habibullah-turkmen-peacegl** [comment]
I can confirm as well, for Chrome, Edge, and Firefox

**Comment by Stardo0** [comment]
I can confirm Chrome

**Comment by mellmers** [comment]
I can confirm the problem in Chrome 121.

> Chromium has officially deprecated mutation events, and has a plan to remove support starting with version 127, which goes to stable release on [July 30, 2024](https://chromiumdash.appspot.com/schedule).

Source: [https://developer.chrome.com/blog/mutation-events-deprecation/](https://developer.chrome.com/blog/mutation-events-deprecation/)

**Comment by benbro** [comment]
Duplicate https://github.com/quilljs/quill/issues/3806
