### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by CleanFuels** [quilljs/quill#3894]
I installed Quill by:
npm install quill@1.3.6

1 moderate severity vulnerability was reported.

# npm audit report

quill  <=1.3.7
Severity: moderate
Reverse Tabnabbing in quill - https://github.com/advisories/GHSA-588m-9qg5-35pq
Cross-site Scripting in quill - https://github.com/advisories/GHSA-4943-9vgg-gr5r
No fix available
node_modules/quill

1 moderate severity vulnerability

Some issues need review, and may require choosing
a different dependency.

On Win10.

**Comment by kabalan-datapostie** [comment]
+1

**Comment by ahartobasf** [comment]
+1

**Comment by JayS-Novisto** [comment]
@luin Thanks for adding the label! - do we know approximately when 2.0 will be officially released (e.g. not as a RC)?
