### ISSUE TITLE
About version 2.0

### ISSUE THREAD

**Issue by leeobrum** [quilljs/quill#3896]
Is there any position on the 2.0 update?

**Comment by yudy-chen** [comment]
Using quill v2.0.0-dev.3 and quill-better-table 1.2.10.
Adding video or list (bullet and ordered), the result is the table become messy and video or list is not inside the column. Any chance to make this works on official release of v2?

**Comment by luin** [comment]
@yudy-chen  Quill 2.0 provides first-class support for nested embeds. Based on that, we at Slab (https://slab.com) created a table blot that supports real time collaborative editing. Each cell inside a table is a full-featured Quill editor so it can nested other block-level blots. You can try it out at https://slab.com/.

We aim to make this feature open-source. However, due to limited engineering resources, we won't be able to release it concurrently with 2.0.

**Comment by leonid-br** [comment]
> @yudy-chen Quill 2.0 provides first-class support for nested embeds. Based on that, we at Slab (https://slab.com) created a table blot that supports real time collaborative editing. Each cell inside a table is a full-featured Quill editor so it can nested other block-level blots. You can try it out at https://slab.com/.
> 
> We aim to make this feature open-source. However, due to limited engineering resources, we won't be able to release it concurrently with 2.0.

Hi!
The DOMNodeInserted issue still persists. Please advise, will you correct this point before the end of the year or change the package?

**Comment by gillycheesesteak** [comment]
@luin thank you so much for your work on this great project! Is there any documentation anywhere on the progress of v2.0, what features will be part of it, what work remains for someone to pick up and help with?

**Comment by luin** [comment]
@leonid-br Quill 2.0.0-beta.0 fixed the issue.
@gillycheesesteak I'm working on the documentation https://v2.quilljs.com/ and at the same time looking at feedbacks from the community. I don't have anything major in my mind before releasing the RC version so should probably do it soon.

**Comment by gillycheesesteak** [comment]
Great news! Is there a page or summary of what's new in v2? @luin

**Comment by luin** [comment]
@gillycheesesteak There are release notes: https://github.com/quilljs/quill/releases and a migration guide: https://v2.quilljs.com/guides/upgrading-to-2-0.

**Comment by gillycheesesteak** [comment]
@luin great, thank you! by any chance is server-side rendering support included?

**Comment by luin** [comment]
@gillycheesesteak Yeah there's a plan but haven't started investigating it.

**Comment by leonid-br** [comment]
> https://v2.quilljs.com/guides/upgrading-to-2-0

@luin Thanks for the update. please tell me, the beta version is compatible with react js?

**Comment by luin** [comment]
@leonid-br Which library do you use? Quill.js doesn't provide any framework bindings so technically it works on all frameworks as long as the library gets upgraded to use Quill 2.0.

**Comment by leonid-br** [comment]
@luin I use this https://github.com/zenoamaro/react-quill and I thought it was based on quill js

**Comment by luin** [comment]
@leonid-br yeah it needs to get updated by its maintainer. Looks like it currently uses Quill v1.

**Comment by leonid-br** [comment]
@luin thank you so much! I hope they will correct their package to take into account your changes

**Comment by luin** [comment]
@leonid-br Sure! I'd also like to help the community in transitioning to Quill v2. Please lmk how I can be of help.

**Comment by leonid-br** [comment]
@luin I created an issue in the react quil repository, now I need to wait for a response from them
