### ISSUE TITLE
quill.js clipboard paste wrong when i use insertEmbed 

### ISSUE THREAD

**Issue by dengwf1325** [quilljs/quill#3897]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Step Two
3. Step Three

**Expected behavior**:

when i copy some content，the editor should paste the same content in my editor

**Actual behavior**:
i use insertEmbed in my code. when i copy some content，the editor should paste the wrong content in my editor

code: https://codesandbox.io/s/musing-satoshi-73cgnq?file=/src/videoBlot.js

**Platforms**: 

**Version**: 1.3.7

Run `Quill.version` to find out

**Comment by luin** [comment]
I don't see anything goes wrong. Can you provide a reproducible steps for the issue you described?
