### ISSUE TITLE
Publish a non-bundled version of the lib on NPM

### ISSUE THREAD

**Issue by ooflorent** [quilljs/quill#390]
It would be great if the library was also published as transformed JS files on NPM **without custom lodash build**. Moreover, making the codebase more modular would be useful.

**Comment by willrowe** [comment]
Can you explain what you mean in a little more detail?

**Comment by ooflorent** [comment]
Yeah sure. 

We are currently building a large webapp that uses Quill. We also uses `lodash` and some other 3rd party libraries do too. Having a custom lodash build bundled into Quill dist files generates extra JS. Exporting the transformed Quill's source prior bundling would solve the issue.

**Comment by jhchen** [comment]
There were issues with getting browserify + derequire and excluding lodash so had to revert.

**Comment by ooflorent** [comment]
Have you considered moving to webpack? You could output a bundled version and a non-bundled-but-transformed version of the library.

**Comment by jhchen** [comment]
Yes I'd like to move to webpack at some point because of their dev server feature but if it solves this too then all the better. Right now Quill has a custom server that I'd like to move away from.

**Comment by StephanHoyer** [comment]
Whats the status on this. I also would love to have a non-prebuild version. I personaly include the parts of lodash I need directly to save some bytes.

Instead of `var _ = require('lodash').reduce` I direcly use  `var reduce = require('lodash/collection/reduce');`

This way you create your custom build just by using the parts you need.

**Comment by jhchen** [comment]
I have not had another chance to take a look at it. Quill already uses a custom lodash build so it only includes the parts it needs. I found that to be cleaner since some files use a lot of lodash functions, the require section of the file gets very bloated.

**Comment by jhchen** [comment]
Quill is dropping lodash as a dependency (in production builds--it is still used in test code) in 1.0 so this should no longer be an issue.

**Comment by PaulBGD** [comment]
But the bundled version is still default?
