### ISSUE TITLE
 The DOMNodeInserted warning message keeps popping up. Please tell me how to resolve it.

### ISSUE THREAD

**Issue by pmaroo** [quilljs/quill#3904]
Please tell me how to resolve the DOMNodeInserted warning message. I am using version 2.0.0, but the warning message still occurs.

**Expected behavior**:

**Actual behavior**:

**Platforms**: 2.0.0

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
Duplicate https://github.com/quilljs/quill/issues/3806
