### ISSUE TITLE
Input disappears after receiving the ably event

### ISSUE THREAD

**Issue by nikitadubyk** [quilljs/quill#3905]
Hello!

I ran into a problem that after receiving ably an event, the input completely disappears. If you look in the console, there will be an empty div tag in place of the input. I also compared the props passed to the component and they turned out to be the same, the only difference was in value. For some reason, `<p><br></p>` was added there, but this does not affect the display of the input in any way.

**Expected behavior**: After receiving the event, the input should be visible

**Actual behavior**: The input completely disappears and is replaced by an empty div

**Platforms**: Windows, MacOS, Chrome, Safari

**Version**: 1.3.7

**Comment by benbro** [comment]
Please provide a CodePen example similar to https://quilljs.com/playground/ and explain how to reproduce it.
It's not clear why you mean by ably event.
