### ISSUE TITLE
[QUESTION] - How to render html as is using this library?

### ISSUE THREAD

**Issue by sujit-baniya** [quilljs/quill#3906]
I've a sample html that contains empty tags and inline-styles and I wanted to render it as is (without changing the content and inline styles)

**Comment by MuaazOsaidTahir** [comment]
hey @sujit-baniya .
You can use this package: https://www.npmjs.com/package/quill-delta-to-html.
In the example under the heading of: **Rendering Custom Blot Formats**

`if (customOp.insert.type === 'my-blot') {
        let val = customOp.insert.value;
        return `<span id="${val.id}">${val.text}</span>`;
    } else if(customOp.insert.type === 'custom-html') {
        // you can define if in any unique key or just that data. Its just an example.
        return <div>{val}</div>
    }`
    
I hope this will help you.

**Comment by benbro** [comment]
Quill supports a list of formats (styles). If an inline style is not supported it will be removed.
Please see this example for using inline styles instead of classes:
https://quilljs.com/playground/#class-vs-inline-style
