### ISSUE TITLE
Rich Text format is not clearing properly

### ISSUE THREAD

**Issue by SaranyaRamasamy96** [quilljs/quill#3909]
I am facing an issue with clearing the format of rich text 

**Steps for Reproduction**

1. Visit https://quilleditor.azurewebsites.net/
2. Type some  text in quill editor.
3. Mark the text with  italics, strike and underline format.
4. Select the whole text and press  space in the front and type more text.
5. Select the text and click clear format.

**Expected behavior**:
User should be able to clear the format 
**Actual behavior**:
Format is not getting clear 

**Platforms**:
Chrome

Version:
"quill": "1.3.7",
"quill-delta": "5.1.0",

**Comment by benbro** [comment]
I'm not able to reproduce with v1.3.7 or v2.0.0-beta.1.
Can you reproduce here?
https://quilljs.com/standalone/full
and here?
https://v2.quilljs.com/standalone/full
