### ISSUE TITLE
[Question] How to correctly treat attributes while converting the `Delta` to required format?

### ISSUE THREAD

**Issue by bambinoua** [quilljs/quill#3914]
I have this sample `Delta`:
```json
[
  {
    "insert": "Size 20:",
    "attributes" : {
      "bold": true,
      "size": 20
    }
  },
  {
    "insert": "Some bolded text in size 20",
    "attributes" : {
      "size": 20
    }
  },
  {
    "insert": "\nRight aligned text",
  },
  {
    "insert": "\n",
    "attributes" : {
      "align": "right"
    }
  },

]
```
which I want to export to PDF and I expect it will looks like:
```
Size 20: Some bolded text in size 20
                  Right aligned text 
```

But the problem I met is that `insert` operation with `Right aligned text` does not contains `attributes` with `align` item. Could somebody please to give me an advise how to apply the `right` attribute, which is actually behind, to the required text.

**Comment by luin** [comment]
The delta looks correct to me and should yield the result that you expect. Line level formats (e.g. align) are applied to the `\n` of the target line.

**Comment by benbro** [comment]
Answered.
