### ISSUE TITLE
[QUESTION] Is it possible to wrap part of the delta structure in a simple container?

### ISSUE THREAD

**Issue by opaknorke** [quilljs/quill#3918]
I need to wrap part of a delta structure inside a container. The resulting HTML tree should ideally look something like this:

```html
<p>Normal paragraph</p>
<div class='wrapper'>
    <p>Wrapped paragraph</p>
</div>
<p>Normal paragraph</p>
```

In my current approach, I have proceeded as follows:

1) I created a blot that extends the base container blot.

```typescript
const ContainerBlot = Quill.import('blots/container');

export class WrapperBlot extends ContainerBlot {
    static blotName: string = 'wrapper';
    static tagName: string = 'div';
    static className: string = 'wrapper';

    // ...
}
```

2) I then created a custom block blot.

```typescript
const BlockBlot= Quill.import('blots/block');

export class CustomBlockBlot extends BlockBlot{
    static blotName: string = 'custom-block';
    static tagName: string = 'p';
    static className: string = 'custom-block';

    // ...
}
```

3) Finally, I made the blots dependent on each other

```typescript
ContainerBlot.allowedChildren = [ CustomBlockBlot  ];
CustomBlockBlot.requiredContainer = ContainerBlot;
```

With this approach, I can format certain parts of the delta as a 'custom-block', resulting in this part being automatically wrapped by my container:

```html
<p>Normal paragraph</p>
<div class='wrapper'>
    <p class='custom-block'>Wrapped paragraph</p>
</div>
<p>Normal paragraph</p>
```

However, as you can see, I am now dependent on the custom block blot to wrap the delta structure. This means that I can't do something like this:

```html
<p>Normal paragraph</p>
<div class='wrapper'>
    <p class='custom-block'>First wrapped paragraph</p>
</div>
<div class='wrapper'>
    <p class='custom-block'>Second wrapped paragraph</p>
</div>
<p>Normal paragraph</p>
```

The wrapped paragraphs would simply be merged into a single wrapper. Here I would rather need the behavior of embedded entities.

So my question is the following: Is it possible to wrap the delta directly without the block blot?

And one more question: Is it possible to listen for changes within a blot (in this case the container blot)?

**Comment by Fi2zz** [comment]
I also thought of this problem when dealing with nested lists, but the solution to this problem lies not in `quill` itself, but in `quill-delta`. Currently I don't have a better solution to deal with this problem


```js
let delta = [
	{
		attributes: {
			type: "bullet-list-container",
		},
		children: [
			{ insert: "Child 1" },
			{ insert: "Child 2" },
			{
				insert: "Child 3",
				attributes: { type: "bullet-list-container" },
				children: [{ insert: "Sub Child 1" }, { insert: "Sub Child 2" }],
			},
		],
	},
];

]


// turn out to


/**


    <ul>
        <li>Child 1</li>
        <li>Child 2</li>
        <li>Child 3
                <ul>
                    <li>Sub Child 1</li>
                    <li>Sub Child 2</li>
                </ul>
        </li>

    </ul>



 */



```

**Comment by DHoper** [comment]
has anyone can anwser this?
