### ISSUE TITLE
Add support for more semantic markup

### ISSUE THREAD

**Issue by terrycloth** [quilljs/quill#392]
Currently, bold and italic font styles use the `<b>` and `<i>` tags. I think it's important to support the more semantically meaningful markup `<strong>` and `<em>` instead. Display italics especially (`<i>`) are very commonly used to add stress emphasis to a word or phrase and the emphasis tag (`<em>`) is already styled to display as italics in pretty much every graphical web browser, unless the page's stylesheets specify otherwise. However, the emphasis tag is more accessible to visually impaired users, because screen readers may audibly add stress emphasis to the phrase, but such software generally does not treat text marked up with `<i>` display italics any differently. It is a similar situation for `<b>` versus `<strong>`.

For the same reason, I believe Quill should support the heading tags (`<h1>` through `<h6>`). Currently, Quill users have no choice but to mark up document section headings as either "Huge" or "Large" text. If we used heading tags instead, documents created with Quill would, again, be increasingly usable and accessible, because document parsers and accessibility aids may generate a sort of table of contents, making it easier to skim and find a particular section of the document.

So with the `<em>` and `<strong>` and heading tags you achieve (more or less) the same *visual* effect, but add more information about the text, making the document more accessible to all users.

It is of course possible users may want to use italics or bold without necessarily adding stress emphasis, or increase some text's font size for something other than a heading, but I believe emphasis and headings are likely to be the most common uses for these visual styles. Other use cases for italics and font size would benefit from using applying these as CSS instead, as discussed in #257.

**Comment by jhchen** [comment]
These are all good reasons but are duplicates of existing issues #257 #204 and part of the current [custom formats](https://github.com/quilljs/quill/milestones/Customizable%20Formats) milestone.
