### ISSUE TITLE
Disable formats in Quill 2.0

### ISSUE THREAD

**Issue by pablopla** [quilljs/quill#3929]
What's the correct way to disable formats in Quill 2.0?
This StackOverflow [answer](https://stackoverflow.com/questions/68378096/how-can-i-use-register-instead-of-formats-with-quilljs-2-0/68388972#68388972) suggests to use Quill.register with custom blots each disables one format which is cumbersome.
How do you import the Bold blot typescript type? ```Quill.import('formats/bold')``` doesn't know about the type.
How do you use different formats with two Quill editors on the same page?

```javascript
const Bold = Quill.import('formats/bold');

// extends format class (Bold) to override its methods
class CustomBold extends Bold {
   // override: return false to avoid formatting again
   static formats() { return false; }
   // override: empty content to avoid bolt name replacement
   optimize(context) { }
}
// remove all tag names (strong, b)
CustomBold.tagName = [];

// register the new custom bold formatting
Quill.register({ 'formats/bold': CustomBold })
```

**Comment by benbro** [comment]
Use [Registries](https://v2.quilljs.com/docs/registries)
