### ISSUE TITLE
Why QuillJS is setting a cookie ?

### ISSUE THREAD

**Issue by sahanDissanayake** [quilljs/quill#393]
I use quill js on my website and when I do there is a cookie set on my computer named __cfduid with .quilljs.com Domain ?

Any thoughts on why this happens ?

**Comment by sahanDissanayake** [comment]
Same can be see here on the website > http://quilljs.com/

**Comment by jhchen** [comment]
I assume you are using Quill's CDN? It looks like it's because Cloudflare adds that cookie to all requests which I was not aware of so I've set the cdn.quilljs.com subdomain to bypass Cloudflare so the cookie should no longer be set by the Quill CDN.

**Comment by sahanDissanayake** [comment]
:+1:  Thanks Chen

**Comment by sahanDissanayake** [comment]
the cookie is still there even if I use the following sources to load form

    <link rel="stylesheet" type="text/css" href="http://cdn.quilljs.com/0.19.12/quill.snow.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/quill/0.19.12/quill.base.min.css">

    <script type="text/javascript" src="https://cdn.quilljs.com/0.19.12/quill.min.js"></script>


Also could you please add minified versions of the CSS files please ?

**Comment by sahanDissanayake** [comment]
I just tested and the cookie is not coming from the cloudfare CDN.

SOLUTION,

Im loading all the files from the Cloudfare CDN

**Comment by jhchen** [comment]
I made the fix earlier but had to revert. Please see the referenced issue #394

**Comment by jhchen** [comment]
Okay now both this and the SSL issue should be fixed.

**Comment by EmanuelGF** [comment]
Greetings.
I have two cookies being set by quilljs.com on my website and the warning:
`A cookie associated with a cross-site resource at http://quilljs.com/ was set without the 'SameSite' attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with 'SameSite=None' and 'Secure'.`
Why do I have these cookies and how do I fix this warning?

**Comment by bbearce** [comment]
Hi,
I am also having this issue. Seems like @EmanuelGF had\has the same problem. Did this get resolved. This is a really cool tool and I'd like to use it, but it looks like something quill needs to fix. Am I wrong? I really don't mind fixing it if it's my issue, but the warning sounds like something http://quilljs.com/ has to set.
