### ISSUE TITLE
Quill 2.0.0-beta.0 blot issue

### ISSUE THREAD

**Issue by shareefalis** [quilljs/quill#3931]
Hi Quill Team and @luin,

I'm trying to get Quill 2.0.0-beta.0 running, but the blots are not working.

Whenever I try to activate the blot via a Quill.format() call, the entire word disappears. For this blot, the word is supposed to be highlighted and not disappear.

Here is the class I'm using for the blot:
``` 
import Inline from 'quill/blots/inline';

class HighlightBlot extends Inline {
  static blotName = 'SearchHighlight';
  static className = 'ql-search-string-highlight';
  static tagName = 'div';
}

export default HighlightBlot;
```
 
Loading it like this: 
 ```  
   const HighlightBlot = require('pathToHighlightBlot').default;

Quill.register(
    {
      'blots/highlight': HighlightBlot,
    },
    true,
  );
  ```

**Comment by Fi2zz** [comment]
note you are using `Inline` blot , the `tagName` property should be `SPAN` instead of `div`

**Comment by shareefalis** [comment]
I set the inline here in css

```
    .ql-search-string-highlight {
      background-color: #fba80dcc;
      display: inline;
    }
    ```
    this module worked fine in 1.3.7..

**Comment by Fi2zz** [comment]
> I set the inline here in css
> 
> ```
>     .ql-search-string-highlight {
>       background-color: #fba80dcc;
>       display: inline;
>     }
> ```
> 
> this module worked fine in 1.3.7..

yeah, works in 1.3.7; 
i try in  2.0.0-beta.0， it works too

```js

// 2.0.0-beta.0
import Quill from "quill";
import Inline from "quill/blots/inline";
class HighlightBlot extends Inline {
	static blotName = "highlight";
	static tagName = "DIV";
	static className = "ql-hightlight";
}
Quill.register({ "blots/highlight": HighlightBlot });

const editor = new Quill({ container: "#quill", theme: "default" });
const html = `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius</p>`;
let delta = editor.clipboard.convertHTML(html);
editor.setContents(delta);
editor.setSelection(0, 20, "user");
editor.format("highlight", true, "user");

console.log(editor.root.innerHTML);
outputs:
/* <p>
	Lorem ipsum dolor si<div class="ql-hightlight">t amet, consectetur </div>
	adipiscing elit, sed do eius
</p>*/




```

**Comment by shareefalis** [comment]
yeah look like there is something wrong how i'm loading the file., something to do with webpack and babel..

**Comment by Fi2zz** [comment]
> yeah look like there is something wrong how i'm loading the file., something to do with webpack and babel..

try `const Inline  = Quill.import('blots/inline')` instead of `import Inline from "quill/blots/inline";
 `

**Comment by shareefalis** [comment]
I tried that, no goose.. Same behavior

**Comment by Fi2zz** [comment]
maybe you shuold clean your node_modules, and reinstall all

**Comment by shareefalis** [comment]
i ended up having to load everything in a module and exporting quill from that module with register  blot to the app because of babel/webpack issues..

**Comment by shareefalis** [comment]
@luin,

 the quill blot loading issue is back in Quill 2.0-rc3. I used the webpack example to get it working again in beta 0 until rc 2..  I created a  custom wrapper module  and exported the Quill module with the blot.
This is the main entry point for the wrapper:

```
import HighlightBlot from './quill-support/HighlightBlot';

Quill.register(
  {  
    'blots/highlight': HighlightBlot,
    },
  true,
);
export default Quill;
```

**Comment by luin** [comment]
Can you provide a reproducible example?

**Comment by shareefalis** [comment]
Hi @luin,
Is there a  better way to load / register blot like this one?  think it is the `Quill.register` not working on webpack build. 

```
 import Inline from 'quill/blots/inline';

class HighlightBlot extends Inline {
  static blotName = 'SearchHighlight';
  static className = 'ql-search-string-highlight';
  static tagName = 'div';
 

export default HighlightBlot;
```

**Comment by luin** [comment]
[It works for me](https://quilljs.com/playground/snow#codeN4Ig9AlgdgJgpgDwHQAsAuBbANiAXCAHhggDcACCGAXgB0Q5i0B7AJzoD4CxiT2ap+BAM4BjFhAAOaMkJYja4aPGQArIRy6jxU9iAA0i2IiRq8IEUyhDpASShZocMlTIBFAK4QsWJBAwTWNAAKAHIAIywmNCFIe0cQgEoAbn5+ESwAQyEhMgAJCABzFAcitAAhSOlENDhYHLsHKCdgfjIZNAy0CBEyCKiAOQyMJxcQgGU4DLkUfKKS9BCUqDbrTu6ydKyhQeHnMhCARywAWiFJ6dO0cSgC45RC4oe0Rdb2tZ6Ogp2R-Z4X5YAvqkBFAPF4fCw4AUINY4CwgrNHqUKlEEsCLFZpAdPN49k0AO5uHFYUIAYgYEGYLBCejILWWZAwTBg7iwcCEuDprzazCYWDCU05AG1uW0yELgGQUJN4CxhQBGWkAJlpADMMlgzgBdMgArV6UVtIXhPkwGn7Ska7rmkLuIwsRpwEL6w3ikJ+DIFJ20kIWeDHPoiADWzoNDLaLoZALDbQkmREcBQprhnJCAGEmP4mGcyBllnAJN0kMWaa80NLhqmhFAmPjzWAwGRWPswu4whEnfwAclgdjwUgzmgM1AaiOhEEJdAziw0KmMmERObOlcIK2ahy6RMpiIZg95rOyFd3HAAXqEiAAUA). It's hard to say what's the issue in your setup without a reproducible example and more detailed error messages. You can create one in https://stackblitz.com/.

**Comment by shareefalis** [comment]
Could it be the way i'm importing `import Inline from 'quill/blots/inline';`. that the only difference there? 
 
 Thanks for that example, this was extremely helpful and good to know that it works. thank you!
 
  the problem is that i'm fighting with webpack 5 issues. I will need to resolve

**Comment by luin** [comment]
Again, it's hard to see whether the import statement is correct or wrong without seeing the actual code. Would be helpful if you could create a reproducible example and also provide more details about what errors you saw.

**Comment by shareefalis** [comment]
Hi @luin,
I don't think it is the blot this time because I was testing a few format option i have. it seem the  core format such as  bold, italic and other are not working.  

I cannot produce an example because  I'm using this example to export as a npm module's webpack 5  for use in  larger app pipeline  which uses gatsby v 3. It worked in rc2 and before but not now..

https://github.com/quilljs/webpack-example

**Comment by luin** [comment]
I upgraded https://github.com/quilljs/webpack-example to use rc.3 and it works correctly.

**Comment by shareefalis** [comment]
Thank you for that! @luin! Update: I found  the issue, it is essentially a 3rd party module  using `formats` that  i'm using to resize image 

https://github.com/xeger/quill-image?tab=readme-ov-file#with-a-plain-html-page

```Whenever you new Quill, make sure to include the formats and the modules in its configuration; otherwise things will not work right.``` 

This caused  a conflict in the configuration you added to restrict format. No wonder why it wasn't working because i only added 2.format item

**Comment by shareefalis** [comment]
See this line, this explains the problem, quill options conflict with the module options.

 https://github.com/xeger/quill-image/blob/c07b754ae33ea96844d61975187f69c6a16b1da0/packages/quill-image-actions/src/ImageActions.ts#L86C38-L86C46

**Comment by shareefalis** [comment]
It works after I modified the module to not use `quill.option.formats` option in the module and use a separate option for quill image.
It is now resolved
