### ISSUE TITLE
Question about the existing quill ecosystem

### ISSUE THREAD

**Issue by tsopeh** [quilljs/quill#3933]
The Quill v2 has [recently](https://github.com/quilljs/quill/blob/4074f5cb2efda0d798d3f4c69dd88cdd3d92c2ec/package.json#L3) entered its beta stage. Huge props to the maintainers on this awesome milestone 🎉 🥳 

I presume that it won't take long before we see a stable release 🤞, but I wonder about the compatibility with the established ecosystem and projects like: [quill-emoji](https://github.com/contentco/quill-emoji), [quilljs-markdown](https://github.com/cloverhearts/quilljs-markdown) and [react-quill](https://github.com/zenoamaro/react-quill). Is it expected for those to work out of the box with the Quill v2?

**Comment by benbro** [comment]
Please ask the maintainers of these third-party projects.
