### ISSUE TITLE
Add Quill 2.0 Beta 0 to CDN

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#3934]
To ease testing the new Quill 2.0 Beta 0 release and get more feedback from teams like ours, it'd be great if you could release a pre-built version on the Quill CDN and make it available at something like https://cdn.quilljs.com/2.0.0-beta.0/quill.js or at least making the pre-built js file available somewhere for us to download. It would sidestep a bunch of the build issues and allow us to get feedback to you on the release faster!

**Comment by anisabboud** [comment]
https://github.com/quilljs/quill#cdn

https://cdn.jsdelivr.net/npm/quill@2.0.0-beta.0/dist/

https://github.com/quilljs/quill/commit/6b49e9f1e4b2a038b714c3488ec0c09ea4e30410

**Comment by luin** [comment]
We just published 2.0.0-beta.1. There's a new website that contains the documentation: https://v2.quilljs.com/docs/quickstart. We are still working on it but there are already some useful information.
