### ISSUE TITLE
Quill#getSemanticHTML  not match editor content

### ISSUE THREAD

**Issue by Fi2zz** [quilljs/quill#3935]
![WX20231219-150358@2x](https://github.com/quilljs/quill/assets/8213998/595a5c6a-9402-4dac-8f4a-51fa1b0bdacf)

When calling `Quill#getSemanticHTML`, the output content is different from the editor content. 

Please see the reproduction link and actual output content below: 

Visit [jsfiddle.net here](https://jsfiddle.net/fizwen/8v7cb4hq/116/) 

**Expected**

Output should be consistent with the editor content 

OR

Editor should be consistent with the pasted content

**Test result**

```html

// original html

<h3>Test for missing empty line</h3>
<p></p>
<p>Hello</p>

```

```html 
// Visual on the editor  
  <h3>Test for missing empty line</h3>
  <p><br></p>   // the difference
  <p>Hello</p>

````

```html

// editor.getSemanticHTML() 

<h3>Test for missing empty line</h3>
<p></p>
<p>Hello</p>

```

**Version**:
2.0.0-beta.0

**Comment by kulitha** [comment]
I made a playground [here](https://quilljs.com/playground/snow#codeN4Ig9AlgdgJgpgDwHQAsAuBbANiAXCAHhggDcACCGAXgB0Q5i0B7AJzoD4CxiT2ap+BAEYsyYPgKgEADuwCKAVwhYsZGAEM06sgoDO0AOYUoUOCwASAFQCyAGTIAKAKq6GxsmhRwyTLDDIkZvpMULoAlFyygjwU1HTQpmwgZLpoAJ5YcLQg0uowxFAGuGQAjAAM0ggA3GRCrPAsxSWVKb6UZADEAMY9NRjqLAbQALR1aMwYxQDMFdUcXDwSgrIAIpraeoZkBnBoAMpw-VBoEF1Wdo4ubtBkpgDuAUEQIeGREkSksdmuRydddCl0plsrl8oYmrManUWA0mi1dG1-N1evNuKQllJdF0WBBpGgUiwutlILBEEgAFa6VFYnF49ggAA04Gg8GQlLwIC6L3xAEclCoyFRbnAHoplFgHAByDoMCDMFiShlkYD8MhkDBMGAKTK6YoqqBqtXMXxCAbFADaqsNavNwDIXjyZgtJSVACYlQAzdRYVwAXTIAF9fQyrdbzZK6n5FWRJXLvado5KFKSWFhoHBJcHQ4bbTG06lJcVJfUzAxJQGlXbJfm0IWY0JtZla4HK3mIAWi10vF0ANaSwNZg3WsjhiD9HaJrnwUZYJi9zMhodqwdqitW6RYdRdOAoXywmMAYSYGGkTFcZHUBrg0lOSDviqtnkOcCLuigTDu0bAYB8ogjCiEIRMklfgAzCKp+H4LlQnxBRpA0NA4AASRMMxBUcMJBXYZUrRgOcFAwOBjiQHY0AAUUyQjjgAITSJCYClBIzElMIkCYlhLEQfEhT5cUkBYJgmDQNjUIsGxbFAyCoGg1IdHgzQ4AOX5TnQhxMKobD9TVPCugIojhNIijnxouiGMlH5Lz+FiRMSTiEG4sheJUEjdiUyzTnOWw1MkyR+CcrAkBCKVEPs4Yu0vCclTghDkNEsJ+GihSUMSbzJH8wKoGCriwpQCKMyi+TELc45TniqBEqKw53K6NSQADIA) to show this. 'getSemanticHTML()' removes the `<br>` tag whereas `innerHTML` keeps it when getting the data. I have only seen one other users [mention this](https://github.com/quilljs/quill/issues/3957#issuecomment-1960686249). It would be great to get a fix for this if it's possible.
