### ISSUE TITLE
Need Copy and Paste Functionality in Quills library

### ISSUE THREAD

**Issue by sourabh-53** [quilljs/quill#3939]
I am creating an application which requires Bold, Italic , Hyperlink, copy and paste functionality. with using Quill library I am able to find the Bold, Italic and hyperlink functionality, I need copy and paste functionality too. I tried to add Icons for copy and paste, However, unable to implement the copy and paste functionality in existing library. Can somebody please  help me to fix this functionality?
![WORKVERSE](https://github.com/quilljs/quill/assets/153464858/b9dd0e39-70f7-4c75-af12-9371d893a0d5)

For your reference,  I have attached snapshot of my app.

**Comment by benbro** [comment]
https://quilljs.com/docs/modules/toolbar
