### ISSUE TITLE
Copy pasting content from MS Word/Excel as well as Google sheets/docs in rich text editor, looses its formatting on Windows machines. 

### ISSUE THREAD

**Issue by shubhangimali28** [quilljs/quill#3941]
Description:
Copying formatted content (with style, font and color) from MS Excel/Word as well as Google sheets/docs and pasting in RTE in Quill, causes it to loose the applied formatting. This is observed on windows machine with Chrome as well as Firefox.  

**Steps for Reproduction**

1. Open Quill playground  https://quilljs.com/playground/  on windows machine on Chrome/Firefox
2. Copy formatted content from MS Excel/Word or Google sheets/docs
3. Paste the content in Quill RTE. 
4. Observe the formatting is not preserved

**Expected behavior**:
Text Formatting should be preserved while copy pasting the content in RTE. 

**Actual behavior**:
Formatting is removed from the content. 

**Platforms**:
Windows - Google Chrome version 120
Windows - Firefox version 120
Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by benbro** [comment]
Please include Quill version and what you are trying to copy from Word or Docs.
Please test with [v2.0.0-rc.0](https://github.com/quilljs/quill/releases/tag/v2.0.0-rc.0)
https://v2.quilljs.com/standalone/full

**Comment by Gosure-sh** [comment]
Any update on this? I'm using quill in PrimeNG Angular. This is huge escalation for my project. Please show some solution.

**Comment by luin** [comment]
@Gosure-sh Can you try it out on https://v2.quilljs.com/standalone/full? Copy/paste should be improved in v2.

**Comment by SreekarKandala** [comment]
> @Gosure-sh Can you try it out on https://v2.quilljs.com/standalone/full? Copy/paste should be improved in v2.

Its working in the playground, But Im using quill via primeNg v15.3.0, in my angular application, (Angular: 15.2.9)

code -  
  <p-editor [(ngModel)]="item['Body'] [style]="{'height':'300px'}"></p-editor>
  
Do I have to update primeNg to get access to version 2 of quill? Kindly help me out.

**Comment by Gosure-sh** [comment]
> > @Gosure-sh Can you try it out on https://v2.quilljs.com/standalone/full? Copy/paste should be improved in v2.
> 
> Its working in the playground, But Im using quill via primeNg v15.3.0, in my angular application, (Angular: 15.2.9)
> 
> code - <p-editor [(ngModel)]="item['Body'] [style]="{'height':'300px'}">
> 
> Do I have to update primeNg to get access to version 2 of quill? Kindly help me out.

@luin  I am also using PrimeNG. Should I update it. Please help us

**Comment by luin** [comment]
@SreekarKandala @Gosure-sh You can try installing the 2.0 Quill with `npm i quill@rc` and following the [migration guide](https://v2.quilljs.com/guides/upgrading-to-2-0).
