### ISSUE TITLE
how can  i fix this warning 

### ISSUE THREAD

**Issue by iqbal-ahmad-dar** [quilljs/quill#3945]
quill.js:  [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

**Comment by benbro** [comment]
Duplicate https://github.com/quilljs/quill/issues/3806
