### ISSUE TITLE
Type letter in capital causing chrome hang

### ISSUE THREAD

**Issue by 51yu** [quilljs/quill#3949]
When type letter in capital (CapsLock), Chrome hang with CPU spike
I can't reproduce with Firefox

**Platforms**:

chrome: Version 120.0.6099.199

**Version**:
quill-1.3.7

**Comment by benbro** [comment]
I can't reproduce. v1.3.7 is stable for several years so it's unlikely that such simple action causes Chrome to hang.

**Comment by 51yu** [comment]
That's right, it turns to be editing large object and elements get re-rendered.
