### ISSUE TITLE
[Toolbar]Incorrect active formats when some attributes are 'undefined'

### ISSUE THREAD

**Issue by jcppman** [quilljs/quill#395]
In toolbar module, when exectuting `this._getActive(range)` in `updateActive()`, if a format is not activated in the result of `this._getLeafActive()` but is regarded as activated in the result of `this._getLineActive()`, the final result of `_.defaults({}, leafFormats, lineFormats)` will be incorrect.

To reproduce this:

- visit http://quilljs.com/, select one line in the demo app
- set it as bold
- select one word in the bolded line
- cancel the bold
- click somewhere on the word to make cursor located inside the word

The cursor is between not-bold characters (and `leafFormats` doesn't has the property `bold`) but Bold is still active on the toolbar cuz it is overrided by `lineFormats`.

Set in-active attributes as false on default might be able to solve this, I'm willing to fire a PR if needed!

**Comment by jhchen** [comment]
I'm not observing this behavior. What OS + browser + version are you using?

**Comment by jcppman** [comment]
Mac OSX 10.10, Chrome 43

Please see the attached screenshot:
![reproduce](https://cloud.githubusercontent.com/assets/5248918/8517004/062a748a-23ee-11e5-99bc-033fd1c90c9e.gif)

**Comment by jhchen** [comment]
This has been fixed in the 1.0 [beta](http://beta.quilljs.com/) release
