### ISSUE TITLE
Doctype HTML is removed from editor

### ISSUE THREAD

**Issue by bharatAscent** [quilljs/quill#3959]
I have an HTML file provided as an email template which the can be edited to make changes however when I render the contents of the HTML file the Doctype meta properties and other contents are removed.

Attached below is an example using one of quill's wrappers created for react.

**Steps for Reproduction**

1. https://codesandbox.io/p/sandbox/react-quill-template-forked-9yl9pq

**Expected behavior**:
All the content added into the editor should be visible according to the formatting and should be returned on change also.
**Actual behavior**:
Some of the content is removed.

**Comment by benbro** [comment]
https://quilljs.com/guides/how-to-customize-quill
