### ISSUE TITLE
webpack complaint: "This seems to be a pre-built javascript file"

### ISSUE THREAD

**Issue by aaronshaf** [quilljs/quill#397]
I did an `npm install quill`, and `import Quill from 'quill'`, and then ran webpack. I get the following:

> WARNING in ./~/quill/dist/quill.js
Critical dependencies:
6:478-485 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/quill/dist/quill.js 6:478-485

**Comment by jhchen** [comment]
That's because `dist/quill.js` is a prebuilt file. Quill's source is in coffeescript. If you want to build yourself with webpack then use `src/index.coffee` as the entry.

**Comment by aaronshaf** [comment]
This is sad. Related: https://github.com/quilljs/quill/issues/390

**Comment by jhchen** [comment]
Why is this sad? My recommendation is exactly the same as webpack's: "Try to require the original source to get better results."

**Comment by tmaximini** [comment]
+ 1 annoying error message in webpack.
I think it is more because quill is already minified, maybe it's possible to compile coffee to js and publish unminified?

**Comment by jhchen** [comment]
The version quill ships with is unminified.

**Comment by tmaximini** [comment]
Yes, the lodash part it ships with is unminified. The Quill part isn't.

**Comment by jhchen** [comment]
If you're talking about the first line that's just the definition browserify inserts.

**Comment by tmaximini** [comment]
Ah ok... now you say it, it's a bit short for being the whole quill code ;)
Anyways, that's the reason for the webpack error. I'll see if I can silence it somehow. Thanks

**Comment by benjasHu** [comment]
Can someone share some configuration to use it with Webpack? I mean to use it with index.coffee source file.
I made many attempts without luck... :(
Thanks!

**Comment by michaek** [comment]
@jhchen I don't think it's as simple as using src/index.coffee as the entry point. When using npm to make quill available to webpack as a dependency, only the compiled files are available - none of the sources. Installing quill via git could be a workaround to avoid the npm packaging that's hiding the sources, but that starts to feel like it's working against the tool. Thanks for a great editor!

**Comment by ccorcos** [comment]
This is interesting in the more general case. Who knows what kind of webpack configuration they may be using to compile their source code? Maybe it wont compile with my webpack settings...

**Comment by jhchen** [comment]
@michaek is correct the lack of source code inclusion in npm is a problem. This is changed in the latest develop branch and Quill's build pipeline has moved to webpack so this will all be moot in 1.0.

**Comment by ccorcos** [comment]
I see. But it seems risky since people may have different webpack configurations. I'm not interested in Quill specifically, but generally anything. I'm getting this error from `jasmine-promises`. But what if they have some specific paths to resolve? I'd imagine that being a huge pain.
