### ISSUE TITLE
Ctrl+Shift+Z doesn't redo on Chrome/Ubuntu

### ISSUE THREAD

**Issue by pablopla** [quilljs/quill#3970]
**Steps for Reproduction**

1. Type something
2. Press "Ctrl+Z" to undo
3. Press "Ctrl+Shift+Z" to redo

**Expected behavior**: Redo

**Actual behavior**: Nothing

**Platforms**:
Chrome 121.0.6167.85, Ubuntu 20.04

**Version**:
v2.0.0-beta.1

**Comment by luin** [comment]
@pablopla Can you reproduce the issue on https://v2.quilljs.com/standalone/full? It works correctly on my side.

**Comment by pablopla** [comment]
@luin redo doesn't work on https://v2.quilljs.com/standalone/full
Tested with Chrome and Firefox on Ubuntu and Debian.
redo works on Chrome/Window

**Comment by luin** [comment]
@pablopla Would you press Ctrl+Shift+Z in the input on https://w3c.github.io/uievents/tools/key-event-viewer.html and send a screenshot?

**Comment by pablopla** [comment]
![ctrl-shift-z](https://github.com/quilljs/quill/assets/638744/5d3624e3-650d-4d3c-b914-4b4eaca9215f)
