### ISSUE TITLE
Inline blot breaks when newline is inserted in the middle

### ISSUE THREAD

**Issue by matoous** [quilljs/quill#3975]
**Steps for Reproduction**

1. Visit the latest documentation website with preview of version 2.0: https://v2.quilljs.com/docs/quickstart
2. Mark two lines as `bold`
3. move cursor to the end of the first line
4. press enter
5. type anything

**Expected behavior**:

I would expect inline blot to retain attributes for a text inserted in the middle (even if it's a newline). Meanwhile, it seems that text inserted in the middle, if it is a new line, splits the blot into two pieces.

**Actual behavior**:

As described above.

**Platforms**:

Firefox 122 on macOS (Catalina), using `2.0.0-beta.1`.

**Version**:

`2.0.0-beta.1`

**Comment by luin** [comment]
Looks like this is what described in https://github.com/quilljs/quill/issues/3841? Currently in Quill, newlines don't inherit formats.

**Comment by matoous** [comment]
@luin indeed, thanks! I missed that one. Should I close this as duplicate? Also please, it's unclear to me: is this desired behavior?

**Comment by luin** [comment]
@matoous Yeah it's the desired behavior at the moment.

**Comment by matoous** [comment]
@luin thank you! Closing in favor of: https://github.com/quilljs/quill/issues/3841. Would be nice if this would be configurable. The CRDTs I tried so far struggle with this behavior.
