### ISSUE TITLE
getText() returns extra \n at the end of the string as opposed to v2.0.0-dev.4

### ISSUE THREAD

**Issue by artknight** [quilljs/quill#3978]
Several of my modules ( Quill Mentions, Quill Emojis ) have stopped working due to an extra `\n` character getting returned by the **getText()** method

### faulty behavior in v2.0.0-beta-1
<img width="946" alt="Screenshot 2024-01-29 at 2 16 06 PM - incorrect" src="https://github.com/quilljs/quill/assets/157762/ab701bfa-feb0-45b5-acca-9a01fc7ba6b8">

### expected behavior as of v2.0.0-dev.4

<img width="964" alt="Screenshot 2024-01-29 at 2 15 30 PM - correct" src="https://github.com/quilljs/quill/assets/157762/89028281-2fc0-429f-9696-90bf558199c4">

**Comment by luin** [comment]
@artknight Thanks for the report! Can you try it with 2.0.0-beta.2?

**Comment by artknight** [comment]
@luin this works as expected now! Thanks for the quick implementation!!!
