### ISSUE TITLE
Allowed formats + hot keys

### ISSUE THREAD

**Issue by kurijov** [quilljs/quill#398]
My quill editor initiated with two allowed formats: [`link`, `image`].

But when I press `Cmd+B` or `Cmd+I` editor bolds or italics text.

OS: OSX 10.10.3
Browser: Chrome 43.0.2357.81

**Comment by willrowe** [comment]
I have not been able to reproduce this, but I do get a brief flash of the text being styled before it goes back to normal. Check out [this pen](http://codepen.io/willrowe/pen/rVmVoO), is happening with this one too?

**Comment by kurijov** [comment]
I see the same flash. Probably I need to update my quill version, thank you.
