### ISSUE TITLE
Toolbar Handlers not working?

### ISSUE THREAD

**Issue by vrrobz** [quilljs/quill#3982]
I am trying to add custom handlers to the toolbar module for images and links. So far, I'm only working with images.

Looking at the toolbar code in `modules/toolsbar.ts` (lines 120-142):

```
      if (this.handlers[format] != null) {
        // @ts-expect-error Fix me later
        this.handlers[format].call(this, value);
      } else if (
        // @ts-expect-error
        this.quill.scroll.query(format).prototype instanceof EmbedBlot
      ) {
        value = prompt(`Enter ${format}`); // eslint-disable-line no-alert
        if (!value) return;
        this.quill.updateContents(
          new Delta()
            // @ts-expect-error Fix me later
            .retain(range.index)
            // @ts-expect-error Fix me later
            .delete(range.length)
            // @ts-expect-error Fix me later
            .insert({ [format]: value }),
          Quill.sources.USER,
        );
      } else {
        // @ts-expect-error Fix me later
        this.quill.format(format, value, Quill.sources.USER);
      }
```

it looks like my handler should be receiving both a reference to the given Toolbar class (this) as well as a value, which may be null.

My handler only seems to be getting a boolean and a null value. When I try to insert a console.log or change any of the values that toolbar should be passing, however, my code never receives it. Which leads me to think that, despite all signs to the contrary, this code doesn't actually handle calling those callbacks. 

Can someone please point me in the right direction to address this? I feel like the handler should receive a callback to the quill object so it can do whatever it needs to do to get the necessary information for the resulting format and simply pass it back. What am I missing here?

**Comment by vrrobz** [comment]
For reference, here is my editor setup:

```
        var editor = new Editor(el, {
            modules: {
                toolbar: toolbarOptions
            },
            theme: 'snow'
        })

        editor.getModule("toolbar").addHandler("image", (i, cb) => { imgHandler(i, cb, editor) });
```
And here is the handler itself:

```
    function imgHandler(parent, value) {
        console.log("Editing image - " + value);
        console.log("Callback: " + typeof parent)
        var modal = document.getElementById("image_picker_modal")
        modal.showModal()
        currEditor = parent
        currEditor = currEditor
    }
```
And here is what is being logged to the browser console when I click the image button in the toolbar:
```
Editing image - undefined
Callback: boolean
```
As you can see, `this.handlers[format].call(this, value);` is sending back `this` as a boolean. If I try changing that value int he source code to anything else - I've tried 'weird' as a string, for instance - it still sends back the boolean. But my handler is *definitely* being called. 

Pleasee help - this has taken ~4 days of my life so far.

**Comment by benbro** [comment]
Please share all the information requested in the issue template.

**Comment by benbro** [comment]
It's not clear what version you use because you ignored the issue template.
Docs says:
```
Handler functions will be bound to the toolbar (so using this will refer to the toolbar instance) and passed the value attribute of the input if the corresponding format is inactive, and false otherwise. Adding a custom handler will overwrite the default toolbar and theme behavior.
```

**Comment by vrrobz** [comment]
I'm using the most recent version build from the develop branch. 

So the question still stands - why is it sending me a boolean? And where in the code is this happening?

**Comment by vrrobz** [comment]
Ahhhh.....

According to this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call 

the call() function of a function will atempt to include some kind of "this" as a default, but strict mode may change it. So, that's unreliable. 

Hence, the callback is actually working as written, though I'd argue not as expected - I would expect some kind of callback to the quill object or something as part of it. But... I'll figure out how to work with this. 

Thanks.
