### ISSUE TITLE
quill 2.0.0-beta.2 How to use highlight.js, here is how I use it, but he can't load

### ISSUE THREAD

**Issue by ls-v** [quilljs/quill#3984]
[code](https://codesandbox.io/p/sandbox/icon-button-forked-fsfkyz?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls2m7eaz00063b6gv87yz3c9%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls2m7eaz00023b6g9lkfya4x%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls2m7eaz00033b6gyumq2oi3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls2m7eaz00053b6gnuy4bgdg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls2m7eaz00023b6g9lkfya4x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls2m7eaz00013b6gmq9b60pu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls2m7eaz00023b6g9lkfya4x%2522%252C%2522activeTabId%2522%253A%2522cls2m7eaz00013b6gmq9b60pu%2522%257D%252C%2522cls2m7eaz00053b6gnuy4bgdg%2522%253A%257B%2522id%2522%253A%2522cls2m7eaz00053b6gnuy4bgdg%2522%252C%2522activeTabId%2522%253A%2522cls2mi95k00f53b6gvkmd4v28%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cls2mi95k00f53b6gvkmd4v28%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cls2m7eaz00033b6gyumq2oi3%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls2m7eaz00033b6gyumq2oi3%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Is there something wrong with how I use it?

**Comment by luin** [comment]
The link doesn't seem to be working.

**Comment by ls-v** [comment]
> 该链接似乎不起作用。
Sorry, I updated it

**Comment by luin** [comment]
Please take a look at the documentation: https://v2.quilljs.com/docs/modules/syntax#usage. I think you need to pass `hljs` as an option to syntax module. Feel free to let me know if there are anything unclear.

**Comment by artknight** [comment]
@luin @ls-v Here is is how I made it work https://github.com/quilljs/quill/issues/3981
