### ISSUE TITLE
Fails to run on Vite

### ISSUE THREAD

**Issue by hayato07** [quilljs/quill#4003]
**Steps for Reproduction**

1. install Vite
```
npm create vite@latest
# Select Vanilla, JavaScript
cd viteDir
```
2. install quill
```
npm install quill@2.0.0-rc.0
```

```main.js
import Quill from 'quill'

document.querySelector('#app').innerHTML = `
  <div>
    <div id="editor"></div>
  </div>
`

const quill = new Quill('#editor', {
    theme: 'snow'
});

```

**Expected behavior**:
editor will be displayed.

**Actual behavior**:
Error happened.

```
[vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/quill/modules/normalizeExternalHTML/normalizers/msWord.js:7:45: ERROR: Could not resolve "lodash"
    at failureErrorWithLog (/Users/hayato07/oss/quill/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/hayato07/oss/quill/node_modules/esbuild/lib/main.js:1059:25
    at /Users/hayato07/oss/quill/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Platforms**:
browser: 
Google Chrome 121.0.6167.160（Official Build）（arm64）
OS:
macOS Ventura 13.2.1

**Version**:

"vite": "^5.1.0"
"quill": "^2.0.0-rc.0"

Run `Quill.version` to find out

**Comment by hayato07** [comment]
after I installed lodash, The build failed error disappeared, but the editor didn't work.

```
npm install lodash
```

**Comment by luin** [comment]
@hayato07 Thanks for reporting this. I'm working on a fix for the lodash issue. Can you expand on how the editor didn't work?

**Comment by hayato07** [comment]
@luin 

Thank you for checking.
The attached screen will be displayed.

<img width="672" alt="image" src="https://github.com/quilljs/quill/assets/37580224/948397f4-b069-4c3e-aa06-529479df64bb">

**Comment by luin** [comment]
Looks like the style is missing. Can you check if you included the CSS files required by Quill? https://v2.quilljs.com/docs/installation

**Comment by hayato07** [comment]
It worked fine thanks to you.

```diff
+import 'quill/dist/quill.snow.css'
```

I would like the documentation to mention that lodash must be installed.

**Comment by luin** [comment]
The requirement of lodash is a bug and will not be needed in the next release.
