### ISSUE TITLE
Esbuild issue

### ISSUE THREAD

**Issue by Vardan-bg** [quilljs/quill#4007]
Version: "quill": "^2.0.0-rc.1"
I have esbuild,
so when I import Quill from 'quill' or 'quill/core' in my project it gives:
**import_core3.default.import is not a function**

So issue is that in browser its bundled as import_core3.default.default

something wrong happens then commonjs module bundled using esm

**Comment by luin** [comment]
Can you provide a reproducible example?

**Comment by Vardan-bg** [comment]
sure: https://stackblitz.com/edit/esbuild-template-jiz4ls
just serve dist folder

**Comment by luin** [comment]
Thanks for the example 👍

I think it's related to https://github.com/evanw/esbuild/issues/3642, not sure why esbuild doesn't respect the `__esModule` flag, and what can we do on Quill side (if we want to keep the default export)

**Comment by Vardan-bg** [comment]
Btw with older version (for example "quill": "2.0.0-dev.4") it works fine. Maybe dig in that direction?
You can check it here https://stackblitz.com/edit/esbuild-template-cgovab

**Comment by fnlctrl** [comment]
@luin should be fixed by https://github.com/quilljs/quill/pull/4013

Using updated dist https://stackblitz.com/edit/esbuild-template-nezjzd?file=src%2Fmain.ts,package.json esbuild builds it fine

**Comment by luin** [comment]
Thanks @fnlctrl! Should be fixed in the 2.0.0-rc.2
