### ISSUE TITLE
After upgrading to v2.0.0.rc1 embed is not working 

### ISSUE THREAD

**Issue by EdManukyan** [quilljs/quill#4014]
Code:

`
const Embed= Quill.import('blots/embed');

export class EditorOperationBlot extends Embed implements EditorBlotInterface {
  static blotName = 'editorOperation';
  static tagName = 'editor-operation';
  static store: Store<MyState>;
  static service: FormulaEditorService;

  static register(props: EditorBlotRegisterProps) {
    if (!!props) {
      EditorOperationBlot.service = props.service;
      EditorOperationBlot.store = props.store;
    }
    Quill.register(EditorOperationBlot, true);
  }`

**Expected behavior**:
to work properly

**Actual behavior**:
`TS2345: Argument of type  typeof EditorOperationBlot  is not assignable to parameter of type
string | BlotConstructor | Attributor | Record<string, unknown>
Type  typeof EditorOperationBlot  is not assignable to type  BlotConstructor 
Type  EditorOperationBlot  is missing the following properties from type  Blot :  scroll, parent, prev, next , and  17  more`

**Platforms**:

Include browser, operating system and respective versions

**Version**:
"quill": "^2.0.0-rc.1",

Run `Quill.version` to find out

**Comment by luin** [comment]
Instead of Quill.import(), you should use `import Quill from 'quill/blots/embed';` in TypeScript project. Can you try it again and if it does work, provide a reproducible example?

**Comment by EdManukyan** [comment]
@luin  thanks for the quick response, so i think you meant  `import Embed from 'quill/blots/embed'` which i did and that caused another issue inside the `constructor(node: Node) {super(node)};` which is 
```
TS2345: Argument of type  Node  is not assignable to parameter of type  ScrollBlot 
Type  Node  is missing the following properties from type  ScrollBlot :  registry, observer, create, find , and  34  more
```
then i set the type as any and everything seems to be working but in the console i have this error.

```
shared-locale-editor.component.ts:41 ERROR RangeError: Maximum call stack size exceeded
    at parchment.mjs:71:19
    at Array.map (<anonymous>)
    at g.register (parchment.mjs:71:14)
    at Quill.register (quill.js:84:24)
    at Quill.register (quill.js:69:14)
    at EditorAssetBlot.register (editor-asset.blot.ts:31:11)
    at Quill.register (quill.js:89:16)
    at Quill.register (quill.js:69:14)
    at EditorAssetBlot.register (editor-asset.blot.ts:31:11)
    at Quill.register (quill.js:89:16)
```

Please note that project is on Angular v17.1.3

**Comment by benbro** [comment]
Can't reproduce with v2.0.0-rc.1 and v2.0.0-rc.2 in Angular 17.2.1 project.
I'm using ```import Embed from 'quill/blots/embed'``` register and use a custom embed blot don't get any error.

**Comment by EdManukyan** [comment]
@benbro thanks for the response, so in your code you call the  ```
constructor(scroll: any, node: Node, apId: string) {
    super(scroll, node);
```
Embed actually has two params `constructor(scroll: ScrollBlot, node: Node);`
Any suggestion would be appreciated

**Comment by benbro** [comment]
In my blot I only define ```static create(value: string)``` and ```static value(el: Element)```. I don't override the constructor.

**Comment by EdManukyan** [comment]
@benbro can you please share your custom blot? and my concern @luin is why is it exceeding max stack ?

**Comment by luin** [comment]
I don't think you should call `Quill.register(EditorOperationBlot, true)` inside `static register()` as `Quill.register(EditorOperationBlot, true)` will call `static register()` so cause the max stack error.

**Comment by EdManukyan** [comment]
@benbro i know you have closed this but maybe you can help with my current issue, so i am creating a custom blot so i can use it for quill.insertEmbed and that blot actually is a link so when i removed Quill.register from the static register function the max stack error gone but i can not insert an embed with my custom blot and it is erroring and that's true because i am not registering my custom blot
`import { GetAssetByApId } from '@app/chart-builder/store/actions/asset.actions';
import { Asset } from '@app/chart-builder/models/asset.model';

export class EditorAssetBlot extends Embed implements EditorBlotInterface {
  static blotName = 'editorAsset';
  static tagName = 'editor-asset';

  static workspaceId: number;
  static store: Store<State>;
  static service: FormulaEditorService;
  static errorKey: string;

  static register(props: EditorBlotRegisterProps) {
    if (!!props) {
      EditorAssetBlot.workspaceId = props.workspaceId;
      EditorAssetBlot.store = props.store;
      EditorAssetBlot.errorKey = props.errorKey;
      EditorAssetBlot.service = props.service;
    }
  }`

**Comment by vkoves** [comment]
I'm working on a Quill 2.0 upgrade and am also seeing this, as we had all our custom blots configured with similar `register` helper functions, like:

```ts
/**
 * A Quill blot that represents an image with an alt tag, as Quill doesn't have
 * this ability by default.
 */
export class ImageWithAltBlot extends EmbedBlot {
  /** This must be called at some point before using this blot. */
  static register(): void {
    Quill.register(
      {
        [`formats/${ImageWithAltBlot.blotName}`]: ImageWithAltBlot,
      },
      true
    );
  }

  // ...
}
```

We would then in an init function call this, like `ImageWithAltBlot.register()`.

Renaming our functions to `registerInQuill` fixed the error.
