### ISSUE TITLE
Issue when user applies change in heading, all the text gets updated rather than only the selected text

### ISSUE THREAD

**Issue by UsamaUsmanAtJTPL** [quilljs/quill#4017]
When the user tries to update a selected text i.e., update normal text to a heading or vice versa then the style applies to the whole text instead of just the selected one.

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]
2. Access the quill js editor.
3. Add some dummy text in the quill js editor.
4. Select the text and apply change in heading 

**Expected behavior**:
Styling should apply only to the selected text.

**Actual behavior**:
Styling applies to the whole text instead of just the selected one.

**Screenshot:**
![image](https://github.com/quilljs/quill/assets/160697875/584fa9db-e3da-4030-b97b-4d7093ffcc47)

**Comment by luin** [comment]
Heading is a block level format so it will apply to the entire line. Is that the issue you described?

**Comment by UsamaUsmanAtJTPL** [comment]
Yes, but if the user wants to apply heading to a specific text only. Shouldn't there be this ability as well?

**Comment by UsamaUsmanAtJTPL** [comment]
Yeah, this helps.

Thank you.
