### ISSUE TITLE
[DOCS] Can't setup toolbar when using custom id

### ISSUE THREAD

**Issue by michaelsharman** [quilljs/quill#4019]
The docs state that you can use the following if you have a custom id (not `toolbar`):
```
{
    modules: {
        toolbar: {
            container: '#mycustomid',
        }
    }
}
```

But `toolbar` can be overloaded and I can't see a way to define the tools in the toolbar when _not_ using `toolbar` as the id.

**Version**:

v2.0.0-rc.2

**Comment by luin** [comment]
Hi! Not sure if I understand. Is [this](https://quilljs.com/docs/modules/toolbar#:~:text=Toolbar%20controls%20can%20either%20be%20specified%20by%20a%20simple%20array%20of%20format%20names%20or%20a%20custom%20HTML%20container.) something you want?

**Comment by michaelsharman** [comment]
The issue is that I'm not using `#toolbar` as the id. 

```
const quill = new Quill(customEditorId, {
    debug: 'info',
    modules: {
        toolbar: {
            container: customToolbarId,
        },
    },
    placeholder: 'Testing 1, 2, 3',
    theme: 'snow',
});
```

If I specify `container` in the expanded `toolbar` object, where do I add the toolbar options (bold, italic etc)?

**Comment by luin** [comment]
The container and options are exclusive at the moment. That means if you specify a container, the container should be responsible for providing the HTML markup.

**Comment by michaelsharman** [comment]
Understood. Thanks for the response. I'm writing a plugin that uses Quill, so I don't want to rely on a generic ID like `toolbar`. But I'll use it and document it in case of host page conflicts.
