### ISSUE TITLE
Span elements are removed

### ISSUE THREAD

**Issue by Leif-Frederiksen** [quilljs/quill#4025]
I have some raw text that could look like this:
<p><span style="font-size:22pt">Some text</span></p>

When I show this in the Quill editor, I do not get the specified font-size, and when I inspect the element, I only have this:
<p>Some text</p>

How can I make sure, that the span is respected in the Quill editor?

**Comment by benbro** [comment]
It's not clear what the issue is. Please fill all the information in the issue template.
