### ISSUE TITLE
v2.0.0-rc3: Uses a classname pattern to represent formats cannot defined in parchment

### ISSUE THREAD

**Issue by shun2wang** [quilljs/quill#4029]
Hi, thanks for your work!
Start from Quill2 seems Uses a class attributor pattern to represent formats not works anymore?
I'm not sure it's issue of Quill or  [parchment](https://github.com/quilljs/parchment) so I file it here.

**Steps for Reproduction**

1. Visit [quilljs.com and use quill v2.0.0-rc3 and also v1.3.7

2.In quill 1.3.7
```js
import Parchment from 'parchment';

let Align = new Parchment.Attributor.Class('align', 'blot-align');
```
defined works.

3. In quill 2-rc3, above code will get error:
```
Uncaught TypeError: Parchment.Attributor.Class is not a constructor
```

I cannot find changes in docs in quill2 or [parchment](https://github.com/quilljs/parchment), am I missing something? but I can I use 
```js
let foo = new Parchment.ClassAttributor(...)
```

**Expected behavior**:

Should defined success or have some docs update.

**Actual behavior**:

Get error

**Platforms**:
Chrome 121 on Windows 11.

**Version**:

Quill-2.0.0-rc3

**Comment by luin** [comment]
Thanks for reporting this! It was left out in the migration guide and now just got added: https://quilljs.com/guides/upgrading-to-2-0#parchment.

**Comment by shun2wang** [comment]
Thanks! and should also update the readme of https://github.com/quilljs/parchment?tab=readme-ov-file#attributor maybe?

**Comment by luin** [comment]
Sure thing! Updated!
