### ISSUE TITLE
 Please consider offering a feature that, upon attaching a URL link in the editor, displays additional information such as meta images, titles, and descriptions alongside the editor.

### ISSUE THREAD

**Issue by JmKanmo** [quilljs/quill#4035]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Visit [quilljs.com, jsfiddle.net, codepen.io]  
quilljs.com
2. Step Two
insert link        
3. Step Three

**Expected behavior**:
Please consider enhancing the link attachment feature to display additional information like the meta image, title, and description in a more sophisticated manner

This function is akin to a feature from a South Korean blog service (Naver Blog). When users add a specific link, it presents the information in a boxed layout, incorporating elements such as the site's meta tag image and meta tag title.

In an attempt to implement this feature, I've repeatedly tried adding a handler during the link attachment process with the following code, but to no avail:

```
const data = `<a href="${url}">${url}</a>`; // tag customization
quill.clipboard.dangerouslyPasteHTML(quill.getSelection().index, data);
```

Upon further research, it seems that Quill editor inherently restricts such actions to prevent security risks. I fully understand and agree with this precaution, as failing to regulate it could lead to malevolent users injecting unknown tags/scripts into the HTML, potentially leading to data theft and widespread harm.

As a result, there seems to be no way for me to code this desired feature on my own.

Therefore, I believe that the development team behind Quill.js should consider developing and providing this functionality.

I kindly request that you evaluate this suggestion with a positive outlook toward improving the features available to Quill.js users."

![sds](https://github.com/quilljs/quill/assets/48584943/dac8579e-cfc0-4f5b-b8c1-5c4e7e5b282b)
![fdfdfd](https://github.com/quilljs/quill/assets/48584943/4702680d-3f2f-4736-9b57-942319cf8696)

**Actual behavior**:
![k](https://github.com/quilljs/quill/assets/48584943/01386b59-de94-4b4b-bc71-8c50f392c200)

**Platforms**:  chrome version 122.0.6261.70 (official build) (64bit), window 11 home edition
Include browser, operating system and respective versions

**Version**:  quill.js.com  (1.3.6)
```
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet"/>
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
```
Run `Quill.version` to find out

**Comment by benbro** [comment]
You can extract info about external link only on the server side. That will require extending Quill.
https://quilljs.com/guides/how-to-customize-quill
