### ISSUE TITLE
How to disable focusing and pop up the system's soft keyboard when using Quill on Android

### ISSUE THREAD

**Issue by weilu114** [quilljs/quill#4037]
hellow，How to disable focusing and pop up the system's soft keyboard when using Quill on Android？

**Comment by benbro** [comment]
The editor can be [disabled](https://quilljs.com/docs/api#disable) and [blurred](https://quilljs.com/docs/api#blur) using the api.
You might also try setting [inputmode](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) to 'none' on the 'ql-editor' div but it's not supported by Quill.
