### ISSUE TITLE
Toolbar configuration

### ISSUE THREAD

**Issue by ile** [quilljs/quill#4042]
Earlier it was possible to configure toolbar like this:

```javascript
const snowToolbar = {
	container: '#k-quill-toolbar',
	items: [
		[{ 'header': [1, 2, 3, false] }],

		[{ 'font': [] }],

		['bold', 'italic', 'underline'],

		['image'],

		['blockquote', 'code-block'],

		[{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'list': 'check' }],

		[{ 'indent': '-1' }, { 'indent': '+1' }, { 'align': [] }],
	]
};
```

This seems to have changed and now there is no way to set both the container and the items, only one or the other? 

And it's not clear how to setup the handlers for header/font picker if only the container is given along with the html code.

Would appreciate more instructions or maybe doing it the old way (using the container + items).

**Comment by benbro** [comment]
That's how the toolbar work. You can define it as JSON without a container or as HTML with a container.
https://quilljs.com/docs/modules/toolbar

**Comment by ile** [comment]
In v1 and v2 beta the toolbar configuration was so much simpler. There is no way to bring it back?
