### ISSUE TITLE
Default themes don't remove custom class on destroy

### ISSUE THREAD

**Issue by FarSeeing** [quilljs/quill#405]
Default themes don't have `destroy` method so upon instance `destroy` method call they leave custom class (`ql-container` or `ql-snow`) on container node.

**Comment by willrowe** [comment]
I can confirm this. I would assume this is not expected behavior. I can put together a PR if this needs to be fixed.

**Comment by jhchen** [comment]
The main goal of `destroy()` originally was releasing memory. But if it also removed the `ql-snow` / `ql-container` classes the editor would lose its styling which I would think is more unexpected. Is having the classes causing an issue?

**Comment by FarSeeing** [comment]
Not really, but it seems a little weird to have container styled when it's not an editor anymore.

**Comment by jhchen** [comment]
I'm going to keep the behavior as is for now since it's not causing real problems and I think it would if the classes were removed.
