### ISSUE TITLE
make a border in an editor with a focus, like in Bootstrap

### ISSUE THREAD

**Issue by TI360Dev** [quilljs/quill#4054]
Hi,
when I use this css:

.ql-editor:focus {
  border: 1px solid #80bdff !important;
  border-radius: 10px;
  box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25) !important;
}

I get a border into container, with left and right space to container, how can I get the border in the ql-container when I enter in the editor.
Thanks

**Comment by TI360Dev** [comment]
Hi, this is a example
![border](https://github.com/quilljs/quill/assets/92542451/36f55e21-f012-49d2-adb7-fba2fc34ce9f)

**Comment by luin** [comment]
Sounds like a general CSS question: [Playground](https://quilljs.com/playground/snow#codeN4Ig9AlgdgJgpgDwHQCsDOIBcIDGB7KNAFwAIBHAVwgBtqSBeEqOAdxIEUraAKAcgGI4MCETwAnXgBoSwADpQSJALZ4YFanDSYZ8xYtF5qAIwCGY7QG1dexReAkAFnBPxzJCwEZpAJmkAzE2o0OABdEgBfEMlrGwteI0MYKRJeEUCIHGTeClg4MWpoOF4omL04iCUTAHMi6V58eABaI2o8HABrYuiFPRKe8O7FAAdqExw4B0S87V4AYTwlIbxgkhMFOCGMpG2payInJTgZtCg8FmSwMBJxFKMKIxai+XCASgBuEElwaHhkByIlNQsCAADzCABuJAgMHoshAQhE4jhAD4QWAIcj5PIQcQAJ4aTE9JBkaiNfBQIgmQrmPxtChoRosEQOaA6HqKBIIRpoBwuM7aAAMJCFIqQ3jEcCUJDEVVM3AF0g83gAzD4AKxq6QCsVql4kACEFSWYkpFLe1nC2LAeIJ2LQODEECGpDQYhwsO+uWQ6BRaPtjudyJA4SAA)

**Comment by TI360Dev** [comment]
Hi,
I find the problem, this situation is done when yo put a editor into a div with the row class of bootsrap. Then the component don't work correctly.

If you remove the class row the result is;

![border2](https://github.com/quilljs/quill/assets/92542451/ef53f318-b0fa-4ac8-ae70-8a7fde4f4b87)
