### ISSUE TITLE
I used 

### ISSUE THREAD

**Issue by ProgrammingGodFromAbove** [quilljs/quill#4059]
What I am trying to do is that I want custom font faces in the toolbar.
I got it working except that the dropdown menu does not show the proper font name. they all display "san serif".
![Screenshot 2024-03-16 at 7 58 55 PM](https://github.com/quilljs/quill/assets/22172600/458a6a2a-c7f6-4e28-972c-89f029c7f68c)
I appreciate your help.

{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Alice&family=Kosugi+Maru&family=Single+Day&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.snow.css"
      rel="stylesheet"
    />

    

    <link rel="stylesheet" href="{% static "css/styles.css" %}"/>

    <title>Document</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}

      <input type="hidden" name="content" id="content" />
      <input type="submit" value="submit" />
    </form>
    
    <div id="editor">
      
    </div>
  

    <script src="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.2/dist/quill.js"></script>
    <h1 class="single-day-regular">Hello</h1>
    
    <script>
      var Font = Quill.import("formats/font");

      Font.whitelist = ["single-day", "kosugi-maru", "alice"]; 
      Quill.register(Font, true);
 
      toolbarOptions = [
        ["bold", "italic"],
        ["link", "image"],
        [{ size: ["small", false, "large", "huge"] }],
        [{ header: 1 }, { header: 2 }],
        [{ font: ["single-day", "kosugi-maru", "alice"] }],
        ["clean"],
      ];
      const quill = new Quill("#editor", {
        modules: {
          toolbar: toolbarOptions,
        },
        theme: "snow",
        placeholder: "이쁘게 적어주세요",
      });

      const form = document.querySelector("form");

      // Listen for form submission
      form.onsubmit = function () {
        // Populate the hidden field with the content from Quill editor
        document.querySelector("#content").value = quill.root.innerHTML;
      };

      document
        .querySelector(".ql-toolbar")
        .addEventListener("mousedown", function (event) {
          event.preventDefault(); // This will prevent the default mousedown action (text deselection)
        });
      
        

    </script>
  </body>
</html>

**Comment by benbro** [comment]
You didn't mention the version. See examples in the playground:
https://v1.quilljs.com/playground/#custom-fonts
https://quilljs.com/playground/custom-formats

**Comment by LZQCN** [comment]
```css
  .ql-snow .ql-picker.ql-font .ql-picker-label::before,
  .ql-snow .ql-picker.ql-font .ql-picker-item::before {
    content: attr(data-value);
  }
```
