### ISSUE TITLE
pasting links from iOS share sheet

### ISSUE THREAD

**Issue by mathonify** [quilljs/quill#4060]
When pasting links from the iOS share sheet to the quill editor, nothing is pasted. 
![ezgif com-optimize-2](https://github.com/quilljs/quill/assets/160181680/d3a0aba9-9cd0-4b22-9ac4-6d57485b857c)

I saw a similar issue mentioned on the [prose mirror discussion page](https://discuss.prosemirror.net/t/pasting-url-copied-from-ios-device-issues/5944). They solved this issue by making sure to capture "text/uri-list" from the clipboard. Not sure if it is the same problem, I will keep trying to debug to find the error. I am quite new to quill so it will take me some time to find the exact problem. Perhaps someone who understands quill better could find the solution faster.

**Comment by mathonify** [comment]
this seems to fix the issue: 

```javascript
// Register an event listener for the paste event on the Quill editor
quill.root.addEventListener('paste', function(event) {
    // Get the clipboard data
    var clipboardData = event.clipboardData || window.clipboardData;
    if (!clipboardData) return;

    // Extract URI content from the clipboard data
    var uri = clipboardData.getData("text/uri-list");
    if (uri) {
        // Prevent default paste behavior
        event.preventDefault();

        // Insert URI as plain text at the current cursor position
        var range = quill.getSelection();
        quill.insertText(range.index, uri);
    }
});


```

**Comment by luin** [comment]
Will be fixed in the next release. Thanks for reporting this!
