### ISSUE TITLE
When using IME inside angular, will create blank line that cannot be deleted.

### ISSUE THREAD

**Issue by linjie0928** [quilljs/quill#4072]
When I use Chinese IME, when I leave IME with the delete key and immediately wrap, a row of text strings that cannot be deleted appears.

This problem does not occur in native quilljs, but it does happen if I directly import quill.js into Angular .

**Steps for Reproduction**
I found the exact sequence to trigger it.
1. Entering a letter into an IME
2. Delete key 
3. Enter key
ghost line will apear.

https://github.com/KillerCodeMonkey/ngx-quill/assets/44791594/5aaf7c9f-dcf1-4d59-ba44-49afa272ab36

Or, it can be recreate in ngx quill example websit:
https://killercodemonkey.github.io/ngx-quill-example/

**Platforms**: 
Angular 17.0.0, chrome

Include browser, operating system and respective versions

**Version**:
"quill": "^2.0.0-rc.3",

**Comment by luin** [comment]
Merging into https://github.com/KillerCodeMonkey/ngx-quill/issues/1821
