### ISSUE TITLE
while appending data, it is taking more time

### ISSUE THREAD

**Issue by the-chand-babu** [quilljs/quill#4077]
so here the problem is, while i m trying to append content in quill editor, using command like,

**(quill.clipboard.dangerouslyPasteHTML(5, '&nbsp;<b>World</b>')**

if the content is not greter then 100 lines so it is appending but taking limited time , if the content is greater than 100 lines so it is taking 10 sec to append data in quill editor , i also try to put content using **Delta**  and using **Blot** , but all the things are taking so much time, so is there any way to add content in initial time .

**Comment by luin** [comment]
Do you mean `quill.setContents()`? It replaces the current contents with the parameter you provide.

**Comment by the-chand-babu** [comment]
> Do you mean `quill.setContents()`? It replaces the current contents with the parameter you provide.

i mean if i paste any HTML  which is greater then 100 lines, so it is taking time to paste that content
example

let var =  '<h1>Welcome to Dummy HTML Content!</h1>
        <p>This is a simple HTML template with dummy content for demonstration purposes.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam justo at sapien varius, id fringilla magna tempus. Nullam sit amet massa a est cursus facilisis. Integer gravida bibendum enim. In hac habitasse platea dictumst. Nulla nec purus bibendum, faucibus lectus vel, pharetra risus. Proin sit amet leo eget neque iaculis egestas a sit amet libero. Sed vitae varius ligula, et pellentesque nunc. Curabitur pretium magna nec ante eleifend, ac semper leo dapibus.</p>
        
        <p>Quisque eget enim quis augue malesuada suscipit eu vitae justo. Ut in nunc vel odio fermentum varius. Maecenas vehicula vel mauris eget aliquam. Sed vel mi velit. Suspendisse id dui nisi. Ut euismod velit ac fermentum consequat. Donec lobortis quam eget nulla vehicula, id facilisis neque euismod.</p>
        <p>Phasellus vehicula urna id efficitur tincidunt. Nullam id odio vitae odio vehicula efficitur. Nulla facilisi. Vestibulum aliquam, tortor non pellentesque lacinia, ex justo egestas justo, nec vestibulum lectus libero eget arcu. Sed dictum, justo a efficitur ullamcorper, lectus urna vulputate metus, ac fringilla ligula risus ac est.</p>
        
        <p>Integer et nisl efficitur, eleifend elit vel, rutrum sapien. Proin eu quam lacinia, ultrices sapien non, convallis libero. Aenean bibendum tincidunt diam, nec tempor enim ultricies id. Fusce malesuada turpis et orci dignissim, quis congue ligula sollicitudin. Aenean vel orci ac ex consequat varius. Maecenas hendrerit, nulla sit amet malesuada posuere, purus felis placerat ligula, in luctus risus leo vel lacus.</p>
        
        <p>Aliquam sit amet nunc ut velit tempor consequat. Fusce aliquam dolor a nulla elementum, ut luctus arcu scelerisque. Sed eu dui non libero auctor blandit. Maecenas ut turpis eu elit molestie tincidunt. Nam vitae tortor eros. Nulla facilisi. Aenean ac lobortis quam. Fusce elementum massa ac sapien convallis bibendum.</p>
        
        <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras aliquet odio eu ligula ultricies, eu sagittis neque accumsan. Vestibulum semper nunc nec arcu fringilla, eget sollicitudin eros vehicula. Sed id tortor ut orci vestibulum lacinia non ac libero. Duis lobortis interdum velit, vel ultricies sem pharetra quis.</p>
        
        <p>Mauris ullamcorper felis id fringilla lacinia. Maecenas lacinia mauris ac lorem cursus, id tempor purus aliquet. Etiam efficitur felis sed convallis aliquet. Morbi in condimentum risus, sed viverra risus. Nulla vel tortor metus. Aliquam tempus nisl a libero faucibus, at tincidunt lorem vestibulum. Vivamus congue nisl nec dolor vestibulum, eu finibus tortor consectetur.</p>
        
        <p>Donec quis quam vitae mi feugiat scelerisque vel ac odio. Nam in mauris consectetur, fermentum libero sit amet, tempor velit. Ut non ligula at libero rhoncus scelerisque. Sed id risus magna. Duis quis tellus semper, posuere ipsum eget, malesuada metus. Integer laoreet urna nec mauris iaculis, eu dapibus nisl fermentum.</p>
        
        <p>Pellentesque auctor magna in tellus viverra, ut elementum purus consectetur. Integer nec ante enim. Donec fermentum ligula eu metus lacinia, vel luctus sapien venenatis. Nulla malesuada lectus in ultrices tincidunt. Cras semper tristique justo sed facilisis. Morbi vestibulum felis quis metus convallis, ac euismod risus posuere. Sed sed scelerisque risus.</p>
        
        <p>Proin accumsan justo in ex venenatis, vel tempor nisl viverra. Nam varius leo eget augue faucibus, nec finibus arcu convallis. In hac habitasse platea dictumst. Curabitur nec libero vestibulum, volutpat urna nec, bibendum enim. Ut consequat ligula eu arcu convallis, nec tincidunt leo malesuada. Mauris convallis libero eu nisi fringilla, in consequat ligula volutpat.</p>
        
        <p>Fusce in mauris risus. Vivamus eget quam bibendum, convallis sapien ac, pharetra neque. Donec a ultrices felis. Curabitur non est ultricies, malesuada enim eu, facilisis velit. Phasellus et condimentum justo. Ut fringilla tristique odio, a tempor risus venenatis at. Curabitur ac augue tristique, suscipit justo nec, cursus dolor.</p'
        

1.   Lets assume this is the content which i'm trying to paste in quill editor, using, customBlot, or dangerously , so it is taking lot more time to add in that editor
