### ISSUE TITLE
2.0.0-rc.3 documentation on formatText overloads is wrong

### ISSUE THREAD

**Issue by justinbhopper** [quilljs/quill#4078]
Currently the docs show overloads for `formatText` that no longer exist.  It seems `formatText` has gone through changes where it no longer supports passing in multiple `formats` at once, although the underlying call to the Editor does.  I would think maybe the solution is to restore these overloads, since it's nice to be able to reduce the number of events that occur when multi-formatting needs to happen together.

![image](https://github.com/quilljs/quill/assets/29075873/2d1147c2-cfc6-4e79-a156-1ec0f27c4488)

https://github.com/quilljs/quill/blob/v2.0.0-rc.3/packages/quill/src/core/quill.ts#L381-L393

2.0.0-rc.3

I couldn't find any open Issues suggesting that the website docs are intentionally stale, so I wanted to report this.  ~The TypeScript declarations are obviously reliable, so it's only an issue for consumers using native JS.~

**Comment by shareefalis** [comment]
It still works, i can confirm. I just do // @ts-expect-error.   This needs to be fixed.

**Comment by luin** [comment]
Seems like a declaration issue. Haven't looked into it but I think we want to keep the overload variant. Will take a look.
