### ISSUE TITLE
Losing styling when new line is inserted

### ISSUE THREAD

**Issue by qfm215** [quilljs/quill#4081]
**Steps for Reproduction**

1. Go to Quill lastest playground : https://quilljs.com/playground/snow
2. Change style (for example to bold or italic)
3. Enter some characters
4. Insert a return line
5. You will lose the styling (style is reseted to default)

**Expected behavior**:

When inserting a return line character, the editor should keep the styling and not reset it (as it was working in version 1.3.7)

**Actual behavior**:

Losing styling when new line is inserted

**Platforms**:

Tested on edge and chrome

**Version**:

Tested with quill 2.0.0-rc4

**Comment by benbro** [comment]
Duplicate
https://github.com/quilljs/quill/issues/4073
