### ISSUE TITLE
When is the new version v2 due? Roadmap?

### ISSUE THREAD

**Issue by hichxm** [quilljs/quill#4088]
All is in the title, do you have roadmap of next releases or approximate date.

Sorry for my English. Thank you ❤️

**Comment by luin** [comment]
Thanks for asking! We've already released a couple of release candidate versions (the latest one is 2.0.0-rc.4) so they are considered feature-complete and we are waiting for feedbacks from the community so shouldn't take too long.

Feel free to try out the RC version in the meantime.

**Comment by hichxm** [comment]
Thank you very much for your comment. 
I using it for work, I try RC version in home this wk end, but I need to wait next release to add it in work project.

Thank you second time for fast response
