### ISSUE TITLE
Adjacent lists require separate containers

### ISSUE THREAD

**Issue by pshatara90** [quilljs/quill#4090]
If you create 2 lists - one unordered, the followed by an ordered list - without a line break in between them, Quill is putting each `<li>` under the same `<ol>` creating a weird rendering condition.  See screenshot.

**Steps for Reproduction**
1. Create an unordered list and add some content
2. Add a linebreak (see second list item)
3. click backspace to remove list formatting
4. Create an ordered list
5. See that first ordered list item has value 2 (with css applied to data-list="ordered" element) and that element is wrapped by the same `<ol>` as the unordered list.

**Expected behavior**:
Lists should be held by separate `<ol>` containers

**Actual behavior**:
Lists rendered in same `<ol>`
<img width="717" alt="Screenshot 2024-03-26 at 11 15 04 AM" src="https://github.com/quilljs/quill/assets/156722095/e60ffae1-bb31-488e-8a10-2b478764c176">

**Platforms**:
Chrome

**Version**:
2.0.0-rc.3

**Comment by luin** [comment]
Duplication of https://github.com/quilljs/quill/issues/979
