### ISSUE TITLE
Deprecation of DOMNodeInserted causing performance issues

### ISSUE THREAD

**Issue by VyaraDurcheva** [quilljs/quill#4096]
I am using quill.js with the latest version and having that console reported issue in all browsers:
**[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.
**
In code this refers to this lines
 // Some reason fixes composition issues with character languages in Windows/Chrome, Safari
    _this.domNode.addEventListener('DOMNodeInserted', function () {});
    
    Could it be fixed. Thank you!

**Comment by benbro** [comment]
Duplicate https://github.com/quilljs/quill/issues/3806
