### ISSUE TITLE
After introducing Quill 2.0.0-rc.4 in the Vue3 project

### ISSUE THREAD

**Issue by happyDeveloper01** [quilljs/quill#4097]
it failed to start. Based on the error message, I speculate that it was because I did not configure a suitable loader , but I still encountered the same error after configuring it. Other configurations:

"Vue": "3.0.0",
"Vue cli": "4.5.15",
"Quill": "2.0.0 rc.4",
"Typescript": "4.3",
"Ts loader": "8.2.0"
The following is the vue.config.js code
```
Module. exports={
ChainWebpack: config=>{
Config.module
. rule ('quill ')
. test (/\. js $/)
. include
. add (/nodeModules \/kill/)
. end()
. use ('babel-loader ')
. loader ('babel-loader ')
. end();
}
}
```
The following is the tsconfig.json code
```
{
"CompilerOptions":{
"Target": "esnext",
"Module": "esnext",
"Strict": true,
"Jsx": "preserve",
"ModuleResolution": "node",
"EsModuleInterop": true,
"AllowSyntheticdefaultImports": true,
"SourceMap": true,
"ExperimentalDecorators": true,
"EmitDecoratorMetadata": true,
"SkipLibCheck": true,
"ForceConsistentCasingInFileNames": true,
"ResolveJsonModule": true,
"IsolatedModules": true,
"Declaration": false,
"NoUnusedLocals": true,
"NoUnusedParameters": true
},
"Include":[
"Src/* */*. ts",
"Src/* */*. d. ts",
"Src/* */*. tsx",
"Tests/* */*. ts",
"Tests/* */*. tsx"
],
"Exclude":[
"Node.modules",
"Dist",
"Build"
]
}
```
![test1](https://github.com/quilljs/quill/assets/156997770/d9b245bc-bbf5-4006-b86e-b93118574812)
![test2](https://github.com/quilljs/quill/assets/156997770/55246323-48cd-43f6-8e77-e5bbe9bcc85b)

**Comment by luin** [comment]
Can you provide a reproducible example? E.g. a link to a GitHub repo.
