### ISSUE TITLE
[Android][v2] Placeholder remains while writing the first word using Samsung Keyboard with predictive text enabled

### ISSUE THREAD

**Issue by dr-zr** [quilljs/quill#4105]
During development, I found a strange bug that occurs on Samsung phones that use Samsung keyboards with enabled predictive text. When you start typing, the placeholder remains visible, until you add a space. Taking into account how many Samsung devices there are and that most of them use the stock keyboard with stock options, this is a huge issue for the users of this library. The strange thing is that this issue occurs only on v2. v1.3.7 doesn't have this issue

**Steps for Reproduction**

1. Visit https://quilljs.com/playground/snow
2. Enable the Samsung keyboard
3. Enable predictive text
4. Start writing

**Expected behavior**:
The placeholder should leave as soon as the 1st character is written

**Actual behavior**:
The placeholder will remain with the text you wrote until a space is entered. 

**Platforms**:
Android - Samsung

**Version**:
2.0.0-rc5

Video is attached below

https://github.com/quilljs/quill/assets/155077894/52fc68a2-c0e1-41e3-a697-16ddab7db582

Similar issue: https://github.com/quilljs/quill/issues/4021

**Comment by luin** [comment]
Yeah let's merge this into https://github.com/quilljs/quill/issues/4021

**Comment by luo772435545** [comment]
I also have the same problem on my PC. Have you solved it?

**Comment by luo772435545** [comment]
How should I add compositionEvent event?
