### ISSUE TITLE
Related to #2858 - Not rendering underline

### ISSUE THREAD

**Issue by j-robin-hunter** [quilljs/quill#4128]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

Using Flutter Quill and have tried to initialise the editor window with HTML using rudemtary editor

`QuillEditor.basic(`
`    configurations: QuillEditorConfigurations(`
`    controller: reportEditorController,`
`    readOnly: false,`
`    sharedConfigurations: const QuillSharedConfigurations(`
`        locale: Locale('en'),`
`    ),`
`    scrollable: true,`
`)`

Renders the text with <strong>strong</strong> but not with <u>underline</u>:

Flutter web:

Running in Chrome on Ubuntu 22.04

using flutter quill 9.3.7

**Comment by luin** [comment]
Hi not sure if I understand the issue. Can you double check if you have provided enough information or can you expand a little bit more?

**Comment by j-robin-hunter** [comment]
Hi, after lookign at this for many hours (little sleep) it turns out to be caused by the validator used when the flutter HtmlElementView is used to render the html with the editor when using flutter web. This has a validator which can block the rendering of the html being fed via the editor to the view.  This can be altered by padding your own validator using NodeValidatorBuilder with the correct validations set.

Within Quill this could be done but is quite a bit of work.

**Comment by luin** [comment]
Okay not sure if I follow but sounds like the issue got resolved. Closing for now
