### ISSUE TITLE
Everytime a Quill object is instantiated a new <style> block is added

### ISSUE THREAD

**Issue by jcludwig** [quilljs/quill#414]
It appears that every call to `new Quill` causes a new `<style>` block to be added to the `<head>` in the DOM. In our product's usage we create Quill editors on the fly and they can be destroyed as well. Is there any way to clean up a Quill object, including removing these blocks from the DOM?

**Comment by jhchen** [comment]
You can pass in { styles: false } into the Quill [config](http://quilljs.com/docs/configuration/#styles) and nothing will be added to head.

**Comment by jcludwig** [comment]
Beautiful, thanks!
