### ISSUE TITLE
Unordered list icon in the toolbar produces an ordered list element

### ISSUE THREAD

**Issue by joshuakb2** [quilljs/quill#4141]
**Steps for Reproduction**

1. [Visit playground](https://quilljs.com/playground/snow#codeN4Ig9AlgdgJgpgDwHQAsAuBbANiAXCAHhggDcACCGAXgB0Q5i0B7AJzoD4CxiT2ap+BAM4BjFhAAOaMkJYja4aPGQArIRy6jxU9iAA0i2IiRq8IEUyhDpARwCuELFjJUyUOAHcyARQdOAFADkAMQMEMwsgXpkwPxkZBhMMHZYcEK4MXHxZMxMWABGAIYsGQDaWdlkpcBkWBDWGYH5KalogWQAvgC6ehVkPVkdvVDxEliFInAoefAlZIEAwkwYEkxCcGSFI3ASECJIB1FZaChwGHCNQlBMHlFkYGBkrPPN+fmpgfwdAJQA3CAdIA)
2. Click the bulleted list button in the toolbar
3. Inspect element to see that the generated HTML is an `<ol>`, not a `<ul>`

**Expected behavior**:
Bulleted lists would use the `<ul>` HTML tag for an unordered list.

**Actual behavior**:
Bulleted lists use the `<ol>` HTML tag for an ordered list, which depends on the Quill CSS to look right.

**Platforms**:
Chrome 124, Windows 10

**Version**:
2.0.0

This issue was documented in issue #3014 before Quill 2.0.

**Comment by luin** [comment]
You can use `Quill#getSemanticHTML()` to get the HTML output. HTML inside `.ql-editor` is only used to support editing (e.g. it may contain HTML for the toolbar) and is not recommend to be used as the value of the editor.

**Comment by joshuakb2** [comment]
Gotcha. The previous issue didn't seem to have a clear resolution, but I was able to overcome my troubles using one of the suggested workarounds from that issue.

I'm definitely using Quill in an unintended way in my application, so I won't make that your problem. Thank you for clarifying!
