### ISSUE TITLE
Upgrade to 2.0 failed

### ISSUE THREAD

**Issue by southorange0929** [quilljs/quill#4147]
I try to use quill and loro to write a simple project. And i want to  upgrade quill to `2.0.0`, but it got some error.

**Steps for Reproduction**

1. clone this project https://github.com/southorange0929/quill-example
2. execute the following instructions in three different command lines, one for each.
```
// first
cd server && pnpm i && pnpm run dev

// second
pnpm i && pnpm run dev

// third 
pnpm run dev
```

3. type something into any of the open tabs.
4. followed by typing in some content in another tab too.

**Expected behavior**:

Sync successfully.

**Actual behavior**:

For quill `1.3.7`, it worked successfully, but for `2.0.0`, second tab always get some error.

<img width="808" alt="image" src="https://github.com/quilljs/quill/assets/32590310/02259d48-e6ac-4551-91a1-779624686fc1">

Any suggestions? Thanks

**Platforms**:

chrome: 124.0.6367.92 (arm64)
os: mac 14.4.1

Include browser, operating system and respective versions

**Version**:

Run `Quill.version` to find out

**Comment by luin** [comment]
Thanks for the reproducible example! Vue's ref wraps Quill's internal data (blot.scroll), which causes the issue.

A fix would be using `shallowRef` instead of `ref`:

```diff
-const quill = ref<Quill>();
+const quill = shallowRef<Quill>();
```

**Comment by southorange0929** [comment]
It works, thanks a lot.
