### ISSUE TITLE
Quill.js webpack integration in symfony project

### ISSUE THREAD

**Issue by Marcelin97** [quilljs/quill#4149]
I'm encountering an issue while integrating Quill.js into my webpack setup. When trying to use Quill in my project, I'm getting the following error:

kotlin
Copy code
Uncaught Error: Module parse failed: Unexpected token (28:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class Quill {
>   static DEFAULTS = {
|     bounds: null,
|     modules: {

It seems to be related to how webpack is handling Quill.js files, particularly with the static class field syntax used in Quill. 
I use Webpack with Encore in my symfony project. (php 7.4 and symfony 5.4)

I've tried various configurations and searched for solutions online, but I'm still encountering this issue. Could someone please provide guidance on how to resolve this error and properly integrate Quill.js into my webpack setup?

Thanks in advance for your help!

**Comment by luin** [comment]
We have a sample repo that demonstrates how to use Quill in a webpack project: https://github.com/quilljs/webpack-example.

**Comment by luin** [comment]
Quill is a frontend project so it has nothing to do with symfony. I think you may need a loader for JavaScript (e.g. babel) but it highly depends on your specific setup. The repo above is a full project that should include everything you would need.

Closing for now as it's not an issue

**Comment by Ehyiah** [comment]
Hello,
I made a bundle for Symfony because quill is pretty nice and it was missing IMO.

take a loot https://github.com/Ehyiah/ux-quill, compatible with webpack encore and assetMapper.
