### ISSUE TITLE
#108 - Placeholder text isn't in v0.19.14

### ISSUE THREAD

**Issue by samsonkhisty** [quilljs/quill#417]
Lovely plugin. Came here for placeholder text, #108. But v0.19.14 release does not have this module.

**Comment by jhchen** [comment]
The placeholder module is not part of Quill core. I'm not sure if it got finished or released.

**Comment by brettimus** [comment]
@samsonkhisty I wrote [a little placeholder module](https://github.com/brettimus/quill-placeholder).

It's a little janky and not too fun when you have to deal with form validations, but my company uses it in production so ¯\_(ツ)_/¯. Feel free to contrib

**Comment by samsonkhisty** [comment]
@brettimus Thanks for this, finally I got some time to try implementing this today. Cheers.
