### ISSUE TITLE
Should deleting a link with Ctrl-K result to text-change 'user' instead of 'api'?

### ISSUE THREAD

**Issue by ile** [quilljs/quill#4177]
**Steps for Reproduction**

If there is a link in the content of a Quill editor, and I select it and press Ctrl-K, the link disappears. 

This will result a `text-change` event with the source of `api`.

Deleting a link with the tooltip trashcan icon will result a similar event with the source of `user`.

Maybe there is an inconsistency here?

**Comment by luin** [comment]
Yeah I think it should be `user`
