### ISSUE TITLE
Disable hotkeys

### ISSUE THREAD

**Issue by theskabeater** [quilljs/quill#418]
Is there a way to disable all hotkeys?

**Comment by theskabeater** [comment]
More specifically any hotkeys which add formatting markup such as CTRL+B and CTRL+I. I tried setting the keyboard module's hotkeys to an empty object and passing in an empty formats array into the constructor but neither worked.

**Comment by theskabeater** [comment]
Ended up being an issue with the default events for contenteditable tags.

<pre>
// disable all quill hotkeys
var keyboard = editor.getModule('keyboard');
for (var key in keyboard.hotkeys) {
  delete keyboard.hotkeys[key];
}

// intercept contenteditable events
// note: bodyEditor is the quill container as a jQuery element
bodyEditor.on('keydown', function(event) {
  var e = event.originalEvent;
  var ret = true;
  if(e.ctrlKey || e.metaKey){
    switch(e.keyCode){
      case 66: // ctrl+B or ctrl+b
      case 98:
        ret = false;
        break;
      case 73: // ctrl+I or ctrl+i
      case 105:
        ret = false;
        break;
      case 85: // ctrl+U or ctrl+u
      case 117:
        ret = false;
        break;
    }
  }
  return ret;
});
</pre>

**Comment by tannerjt** [comment]
Perfect, thanks @theskabeater
