### ISSUE TITLE
Unable to create image blot

### ISSUE THREAD

**Issue by wojtek1150** [quilljs/quill#4187]
As in title. After limiting allowed formats to not allow passing image whole editor will crash :/

**Steps for Reproduction**

1. Go to configuration demo page: https://quilljs.com/docs/configuration
2. Scroll down to formats
3. Try to paste image into editor when formats doesn't allow to paste image
4. 
<img width="633" alt="image" src="https://github.com/quilljs/quill/assets/5401942/ec7a2b62-07f2-45a8-a3f8-9689c6a28b29">
5. Control is broken

**Expected behavior**:
Error should not appear, editor should still work (in some demo i saw that there instead of error text is passed into control with `unable to paste image`

**Actual behavior**:
Control is broken

**Version**:
Latest

**Comment by kubacee** [comment]
i have the same problem

**Comment by lighter21** [comment]
Pls fix

**Comment by KarolGawrysiuk** [comment]
i have the same problem

**Comment by majkelwork** [comment]
Fix man, I have bugs in my app and I'm about to get fired

**Comment by bwrksmld** [comment]
Same issue here, editor becomes unusable after trying to paste image

**Comment by FunnyCPP** [comment]
Yep, i have same issue. Pls fix

**Comment by luin** [comment]
The linked example doesn't have `image` blot registered (via `formats`). You can try https://quilljs.com/docs/quickstart. The allowed formats are controlled by `registry` and `formats` options, [learn more
](https://quilljs.com/docs/customization/registries)

**Comment by wojtek1150** [comment]
And it shouldn't be.  But control should work without errors. Like when you disallow to use italics or bold. See issue details ...

When I not allow to pass image I expect that when some paste html that include image it should be omitted instead of crashing.
