### ISSUE TITLE
 version 2.0.1  failed to compile

### ISSUE THREAD

**Issue by yaderick** [quilljs/quill#4193]
ERROR in ./node_modules/quill/blots/block.js 8:8 Module parse failed: Unexpected token (8:8) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders | const NEWLINE_LENGTH = 1; | class Block extends BlockBlot { >   cache = {}; |   delta() { |     if (this.cache.delta == null) {  @ ./node_modules/quill/core.js 2:0-53 19:17-22 20:23-33  @ ./node_modules/quill/quill.js

**Comment by yaderick** [comment]
node 18+  quill version 2.0.1, failed to compile

**Comment by luin** [comment]
You will need a loader for .js files. E.g. babel-loader

**Comment by kelokeloo** [comment]
I changed my webpack config to load the Quill module. You can refer to my config.
```
module: {
      rule: {
        'quill-editor': {
          test: /\.(js|mjs|jsx|ts|tsx)$/,
          include: /(node_modules[/\\](quill))/,
          use: {
            'babel-loader': {
              loader: require.resolve('babel-loader'),
              options: {
                presets: [
                  [
                    require.resolve('@umijs/babel-preset-umi'),
                    {
                      nodeEnv: 'production',
                      env: {
                        targets: {
                          chrome: 49,
                          firefox: 64,
                          safari: 10,
                          edge: 13,
                          ios: 10,
                          ie: 10,
                        },
                      },
                    },
                  ],
                ],
              },
            },
          },
        },
      },
    },
```
