### ISSUE TITLE
Can we add our own additional options?

### ISSUE THREAD

**Issue by LoaiBassam** [quilljs/quill#420]
Can we add our own formats? for example font size? colour picker for font and highlights, add more fonts, add more options like anchors etc...

**Comment by jhchen** [comment]
Quill already supports font size, color and background. The values used on the demo homepage can be customized--just set the `<option>` attribute value to what you want. More details on the toolbar: http://quilljs.com/docs/modules/toolbar/

**Comment by LoaiBassam** [comment]
Thank you for your prompt answer! 

What about colour pickers? can we upgrade those to for example have the HX value? so you can enter values? something like: https://docs.jboss.org/richfaces/latest_3_3_X/en/devguide/html/images/colorPicker_facets.png

Adding a link, can we add more options? for example, anchors, open in a new window etc... 

Thanks again J

**Comment by jhchen** [comment]
If you want to use your own color picker that's fine. Once the user picks the color just call `[formatText](http://quilljs.com/docs/api/#quillprototypeformattext)`. Right now you can't customize what happens when you click on a link.

**Comment by xarg** [comment]
Tried to find a way to reuse the `Picker` in a custom module. I don't think there is a way to do it now. Also it seems that the existing pickers are connected to the current theme. Wish there was a way to reuse `Picker` from Quill to add other pickers. 

The idea here is to have the same look and feel as the Quill picker.
