### ISSUE TITLE
Pasting Nested Lists

### ISSUE THREAD

**Issue by hryanjones** [quilljs/quill#421]
It seems like Quill only supports singly-nested lists, however, I think I found a bug where when pasting in a multi-nested list that has a multi-nested item last it seems to cut off everything after that item.

To demonstrate here's a [JSBin with two different sections](http://output.jsbin.com/safoneheva) you can copy paste into an editor ([such as the example editor](http://quilljs.com/)).

When you paste the top section it cuts off after the second level, "*second level is the last, then*".

Best,
Ryan

**Comment by jackmstafford** [comment]
I'm having the same problem.

**Comment by hryanjones** [comment]
Thank you Jason! `\m/`

(I assume it works even though it appears the example editor hasn't received this change yet)

**Comment by jhchen** [comment]
It's fixed in the codebase but I have not released a new version yet so it's not yet live on quilljs.com. Version 0.20.0 should have this fix.

**Comment by hryanjones** [comment]
Awesome! Is there some way I can buy you a beer or some other tasty beverage?

**Comment by sahilsakhiya11** [comment]
@jhchen thanks Jason.
