### ISSUE TITLE
Importing modules directly fails with Quill 2.0.2

### ISSUE THREAD

**Issue by p-e-w** [quilljs/quill#4217]
[The documentation](https://quilljs.com/docs/installation) suggests that Quill's modules can be imported like this (example from linked documentation page):

```javascript
import { Delta } from 'quill';
```

However, that flat out doesn't work as `Delta` and other relevant types aren't exported. Only the clunky `Quill.import` syntax actually works for importing those modules.

**Comment by luin** [comment]
Good catch! You can either import `Delta` via `Quill.import()` and `import { Delta } from 'quill/core';` but we should support `import { Delta } from 'quill';`
