### ISSUE TITLE
Editor only focuses when clicking on .ql-line div

### ISSUE THREAD

**Issue by danielschwartz** [quilljs/quill#422]
I can't seem to reproduce this on the website examples, but I can reproduce it given `quill@0.19.4` from the CDN locally.

I have a `min-height: 250px;` on the editor div, but unless there is a `.ql-line` div below my mouse cursor I can't focus the editor. This means as the document gets longer it's very easy to focus, but when it's a brand new document its extremely hard to focus. 

Any thoughts?

**Comment by jhchen** [comment]
Can you reproduce this if you download the [release](https://github.com/quilljs/quill/releases/tag/v0.19.4) and run one of the examples in the examples/ folder? Also what OS + browser are you using?

**Comment by danielschwartz** [comment]
Using the release seems to work, but I have no idea what the difference is between the example and my local server. In terms of element positioning, there is nothing on top of it that would prevent a click from getting to the editor.

Any gotchas I should be aware of when building the container for an editor? It definitely smells like it's a bug on my side, but I unfortunately am a bit lost as to what it could be.

**Comment by jhchen** [comment]
The div with class `ql-editor` is the contenteditable container so make sure that height fills your container. Other than that it's the usual debugging tips.

**Comment by danielschwartz** [comment]
That was the issue. I had added a min-height on the element being passed into Quill,  but not on  the `ql-editor` class/element. 

Super helpful, thanks!
