### ISSUE TITLE
Quill drops prior formatting if you insert differently formatted text after it

### ISSUE THREAD

**Issue by nickretallack** [quilljs/quill#423]
I found a way to break quill just by typing letters and clicking on the toolbar.

1) Click Bold
2) Click Italic
3) Type a letter
4) Click Bold
5) Click Italic
6) Type a letter

What I expect the document to look like: One bold+italic character followed by one normal character.

What I get instead: The previous character loses its boldness, so there's just one italic character followed by one normal character.

Oddly enough, Quill emits the edit that it actually did in the delta, even though it's not the edit that I wanted.  This means the issue is happening pretty early in the pipeline.

**Comment by nickretallack** [comment]
Btw, this happens in Chrome.  It doesn't happen in Firefox.  I'm debugging it now.  It has something to do with Chrome representing the document like this:

```html
<div><i style="font-weight: bold">x</i></div>
```
instead of the document you might expect:
```html
<div><b><i>x</i></b></div>
```

**Comment by willrowe** [comment]
I can confirm this bug.
