### ISSUE TITLE
Question before use

### ISSUE THREAD

**Issue by janstieler** [quilljs/quill#424]
Hi,
is that right that this editor is generation for every paragraph an div instead an p?
And what is with the deprecated u for underlined text, could it changed to an span with an class or is it not possible to change the output?

Thanks and cheers

**Comment by jhchen** [comment]
Usage of `<div>` is for paste compatibility and `<u>` is for older browsers. They currently cannot be configured but will be by 1.0.

**Comment by janstieler** [comment]
Hi,
u is probably acceptable but not a div for an paragraph. You cannot replace an semantic element through an not semantic element. This is an no go. Sorry for that direct words.
I like the editor but I can't use it with this reglementation. And the biggest problem is that all the most other jquery editors do it in the same way.
