### ISSUE TITLE
Editor won't scroll if change line or paste at the bottom of editor

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [quilljs/quill#433]
And the cursor become invisible util a normal char been inputed.

**Comment by Nick-The-Uncharted** [comment]
I solved it by add contenteditable="true" to editor container.

**Comment by jhchen** [comment]
Which container are you referring to? The `ql-editor` class container should already be contenteditable.

**Comment by Nick-The-Uncharted** [comment]
@jhchen ql-editor, the example of this project has the same problem.
It can't scroll in ionic BTW, I think it's ionic's problem though.

**Comment by jcludwig** [comment]
@Nick-The-Uncharted ql-editor already has contenteditable="true". Adding contenteditable=true to the ql-container does appear to change this behavior, but also leads to other weird behavior, like pressing the down arrow on the last line moves focus out of the editor.

**Comment by jhchen** [comment]
Fixed by #433
