### ISSUE TITLE
format bar doesn't reset itself when I setHTML('')

### ISSUE THREAD

**Issue by jasonmng** [quilljs/quill#446]
I'm running: v0.19.8

If I select a font-size, which I named "large", then run setHTML(''), the large font size will still be selected. If I think try to select the "large" font from the dropdown I get a js error.

How can I reset the format bar along with clearing out the text area?

**Comment by jhchen** [comment]
Can you reproduce this on the quilljs.com homepage? If so what platform? I cannot on Chrome + Mac.

**Comment by jasonmng** [comment]
I can't reproduce it on the quilljs.com homepage.  I tried dropping in the latest version of quill and I am still seeing the issue.  I did notice that the format bar will reset itself but only after I click inside the textarea again.  Any idea on how I might debug this?

**Comment by jhchen** [comment]
Just the standard: get rid of all the integration code and slowly add them back until the issues reappears.
