### ISSUE TITLE
Link Tooltip module

### ISSUE THREAD

**Issue by magus** [quilljs/quill#448]
Any chance we could get a second module which allows us to set the container (similar to toolbar)? We are currently solving this by manually moving the entire ql-link-tooltip DOM element but it'd be much more clean to be able to specify the anchor point like we do for toolbar.

**Comment by jhchen** [comment]
You can pass in a template into the toolbar. Does that work for your purposes? The default link tooltip is just one implementation and might not be usable in all situations. It may be best to just subclasses it or just create your own tooltip and [register](http://quilljs.com/docs/api/#quillregistermodule) it, overriding the default tooltip.
