### ISSUE TITLE
Link Tooltip - 'editing' class still present when tooltip is blurred

### ISSUE THREAD

**Issue by magus** [quilljs/quill#449]
On blur the editing class should be removed from the tooltip, the hide margin is correctly applied but we should also remove the editing class. I've made this fix locally and can probably whip up a PR but just filing this for the record.

**Comment by jhchen** [comment]
Why is this a bug? The editing class is to control if a textbox to edit a link or link itself is visible. The margin is to show/hide the entire tooltip--two orthogonal purposes.

**Comment by magus** [comment]
Sort of related to the other bug, I think it's more clear if the editing class is removed when we are no longer showing the tooltip. I use the presence of the editing class to show/hide the tooltip since I'm overriding the absolute positioning (static location instead of tooltip). Feel free to close this, I think I'm almost done just working around things.

**Comment by jhchen** [comment]
Closing as this is not the purpose of the `editing` class.
