### ISSUE TITLE
Links followed when clicked

### ISSUE THREAD

**Issue by jfftck-work** [quilljs/quill#452]
I am using Firefox 40 on Linux and when I try to edit a link it opens the website. This makes it hard to edit the text if the page opens in the same tab.

**Comment by jhchen** [comment]
What distro + version of Linux? Ubuntu + FF 40 is working for me.

**Comment by jfftck-work** [comment]
I found that it does it in the other rich text editors online.

The funny part is that the first link is the only one that is active, all the other links you can click on and edit.

I will follow-up with Mozilla to see if this is a known issue.

Thanks for the quick reply.

Jeff Tackett / GIS Specialist
jeff.tackett@ijus.net<mailto:jeff.tackett@ijus.net>  / Cell: 740-418-0593
Office: 614-335-6223 x 150 / Fax: 614-472-0846
690 Taylor Rd. Suite 100 Gahanna, OH 43230
[cid:part2.02050509.04050807@ijus.net] <http://www.ijus.net/>
http://www.ijus.net<http://www.ijus.net/>   [cid:part5.00090601.04050205@ijus.net]  [cid:part6.05020500.06020903@ijus.net]  <https://www.linkedin.com/company/ijus>
The information contained in this message is intended only for the personal and confidential use of the recipient(s) named above. If the reader of this
message is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received
this document in error and that any review, dissemination, distribution, or copying of this message is strictly prohibited. If you have received this
communication in error, please notify us immediately, and delete the original message.

On 08/13/2015 02:46 PM, Jason Chen wrote:

What distro + version of Linux? Ubuntu + FF 40 is working for me.

**Comment by jhchen** [comment]
Sounds good.

**Comment by kriswillis** [comment]
This is happening for me, too. Google Chrome 48.0.2564.109 (64-bit) under Linux. Although, for me it's the opposite, I can seem to edit the first link, but all others cause the browser to follow them.
