### ISSUE TITLE
reopening format bar doesn't reset itself when I setHTML('') #446

### ISSUE THREAD

**Issue by jasonmng** [quilljs/quill#457]
[related issue #446](https://github.com/quilljs/quill/issues/446)

I was able to reproduce the issue on: http://quilljs.com/

Steps to reproduce: 
1. Inject the following HTML onto the page: ```<button onclick="quill.setHTML('');">Click Me</button>```
2. in the editor select "Huge" font and enter in some text
3. click on the injected button

Expected Results: The editor is cleared and the format bar is cleared
Actual Results: the editor is cleared but the format bar is not

I'm running: chrome 44.0.2403.155 (64-bit)

**Comment by jhchen** [comment]
There's no more setHTML but an equivalent clearing of all text call does reset the format bar in the 1.0 [beta](http://beta.quilljs.com/) release
