### ISSUE TITLE
Changes font-size when adding a new line

### ISSUE THREAD

**Issue by joaovpmamede** [quilljs/quill#458]
I have some text set to 37px although when I add a new line it changes to 48px.

Must be because of this: https://github.com/quilljs/quill/blob/07b05a49976e79b495dcd5423695228ac2381cd9/src/lib/dom.coffee#L363-L370

Any way I can set the new line to the same value as the line above?

**Comment by jhchen** [comment]
No. Right now Quill uses `execCommand('fontSize')` and they require a 1-7 HTML font size. This should change in the next major when the [parchment](https://github.com/quilljs/quill/tree/parchment) branch is merged in. Feel free to make a separate issue for an arbitrary font size feature request but as it stands Quill is behaving as expected.
