### ISSUE TITLE
Docs for delete op have non-number value.

### ISSUE THREAD

**Issue by edrex** [quilljs/quill#462]
I'm just poking around Quill for the first time, so I may have missed something, but it seems that on http://quilljs.com/docs/deltas/

```javascript
{
  ops: [
    { retain: 12 },
    { delete: '4 ' },
    { insert: 'White', attributes: { color: '#fff' } }
  ]
}
```

should be

```javascript
{
  ops: [
    { retain: 12 },
    { delete: 4 },
    { insert: 'White', attributes: { color: '#fff' } }
  ]
}
```

Couldn't find source for docs, or I would have submitted a PR. :beers:

**Comment by jhchen** [comment]
You are correct thank you!
