### ISSUE TITLE
Backspace delete two characters at once in FF 40.0.2

### ISSUE THREAD

**Issue by persianacarranza** [quilljs/quill#463]
Tested with version 0.20.0, FF40.0.2, Windows 8.
Only happens with the minified version of quill:
http://cdn.quilljs.com/0.20.0/quill.min.js

Other browsers do not seem to be affected.

**Comment by jhchen** [comment]
I'm not able to reproduce this on Windows 8.1 + FF40. To clarify the unminified version works but the minified version does not?

**Comment by jhchen** [comment]
Feel free to comment and reopen with reproduction steps.

**Comment by LFDM** [comment]
Using Quill 0.20.1 (the npm release) also leads to this. (currently tested on FF 43.0.2)

Seems the backspacing override is not in effect in FF, need to investigate further. I can say though that if I add some logging I get `text-change` events on all browsers except firefox for delete operations (typicalls 1 retain operation and one delete operation, but FF is completely silent)

**Comment by LFDM** [comment]
Sorry, have to take that back - was actually totally my fault. Was too eager after I found this issue.
