### ISSUE TITLE
cannot enter spaces in firefox if whitespace is set to normal

### ISSUE THREAD

**Issue by scamden** [quilljs/quill#468]
if i set whitespace to normal in firefox i can only enter one space and as soon as i enter another character the space is removed. @jhchen we need whitespace normal in order to properly display the html content of email replies but it breaks editing in firefox

**Comment by jhchen** [comment]
Consecutive whitespace is supposed to be collapsed (see [normal](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space)) in HTML. This is usually not what you want in an editing environment so Quill gets around this with the white-space css property. What breaks about email replies? What does the HTML look like? Is it generated by a previous Quill editor?

**Comment by scamden** [comment]
Ya collapsing whitespace was a downside we were willing to accept, but even the single space between words is removed in firefox as you type. The html is just the content of previous emails which we include at the bottom of the reply. it's not generated by a quill editor unfortunately, but looks ok if whitespace is set to normal. otherwise it ends up with a bunch of extra space between certain sections, i can provide an example if you need.

**Comment by jhchen** [comment]
Yes an example would be great. It might be best to just try to clean up this HTML. The difficulty is Quill relies on the white-space property to do proper and cross browser display of whitespace.

**Comment by scamden** [comment]
i looked into cleaning the html, but it's very tricky cause it's more or
less arbitrary. i'll get an example soon

**Comment by scamden** [comment]
ok here's one sorry it's long: 

```
Yup! Super fun! Ok man ttyl <br />
<div class="gmail_quote">
  <div>On Mon, Aug 3, 2015 at 5:58 PM Christopher Martinez &lt;<a
    href="mailto:chrisjoemart@gmail.com">chrisjoemart@gmail.com</a>&gt; wrote:<br /></div>
  <blockquote class="gmail_quote"
    style="margin: 0 0 0 0.8ex;border-left: 1.0px rgb(204,204,204) solid;padding-left: 1.0ex;">Snaps.
    I'm gone on Sunday until the 24th. I'll ping you then to see if
    you're around. Have fun in FL (hopefully it's for fun). <br />
    <div class="gmail_quote">
      <div>On Mon, Aug 3, 2015 at 2:50 PM Sterling Camden &lt;<a
        href="mailto:rusty.camden@gmail.com">rusty.camden@gmail.com</a>&gt; wrote:<br /></div>
      <blockquote class="gmail_quote"
        style="margin: 0 0 0 0.8ex;border-left: 1.0px rgb(204,204,204) solid;padding-left: 1.0ex;">I'm
        in Florida this week but next?<br />
        <div class="gmail_quote">
          <div>On Mon, Aug 3, 2015 at 3:37 PM Christopher Martinez
              &lt;<a
            href="mailto:chrisjoemart@gmail.com">chrisjoemart@gmail.com</a>&gt; wrote:<br /></div>
          <blockquote class="gmail_quote"
            style="margin: 0 0 0 0.8ex;border-left: 1.0px rgb(204,204,204) solid;padding-left: 1.0ex;">Hey Rusty-<br />
            <br />I'm back this week. You free at all for lunch or
            coffee or something?<br />
            <div class="gmail_quote">
              <div>On Tue, Jul 7, 2015 at 10:46 AM Sterling Camden
                  &lt;<a
                href="mailto:rusty.camden@gmail.com">rusty.camden@gmail.com</a>&gt; wrote:<br /></div>
              <blockquote class="gmail_quote" style="margin: 0 0 0 0.8ex;border-left: 1.0px rgb(204,204,204) solid;padding-left: 1.0ex;">
                <div>perfect!</div>
                <br />
                <div class="gmail_quote">
                  <div>On Tue, 7 Jul 2015 at 10:44 Christopher Martinez
                      &lt;<a
                    href="mailto:chrisjoemart@gmail.com">chrisjoemart@gmail.com</a>&gt; wrote:<br /></div>
                  <blockquote class="gmail_quote"
                    style="margin: 0 0 0 0.8ex;border-left: 1.0px rgb(204,204,204) solid;padding-left: 1.0ex;">I
                    figured you might. <br />
                    <br />Sure I'll send you a note when I get back in
                    town. Sometime late July. <br />
                    <br />Chris<br />
                    <div class="gmail_quote">
                      <div>On Tue, Jul 7, 2015 at 10:33 AM Sterling
                        Camden &lt;<a
                        href="mailto:rusty.camden@gmail.com">rusty.camden@gmail.com</a>&gt; wrote:<br /></div>
                      <blockquote class="gmail_quote" style="margin: 0 0 0 0.8ex;border-left: 1.0px rgb(204,204,204) solid;padding-left: 1.0ex;">
                        <div>Haha it's no problem, Chris! Thought it was
                          fun, although my coworkers were pretty
                          confused cause I go by Sterling now :) I would
                          def love to meetup but this week is pretty
                          crazy. Maybe we can catch up when you're back?</div>
                        <div>
                          <div>
                            <br /></div>
                          <div>Sterling</div></div>
                        <br />
                        <div class="gmail_quote">
                          <div>On Mon, 6 Jul 2015 at 23:29 Christopher
                            Martinez &lt;<a
                            href="mailto:chrisjoemart@gmail.com">chrisjoemart@gmail.com</a>&gt; wrote:<br /></div>
                          <blockquote class="gmail_quote" style="margin: 0 0 0 0.8ex;border-left: 1.0px rgb(204,204,204) solid;padding-left: 1.0ex;">Hey Rusty!<div>
                              <br /></div>
                            <div>Sorry for just blurting your name on
                              the street but I've seen you walking a
                              couple times and meant to say hi. Lara and
                              I are currently living at 645 Forest Ave
                              so we're super close. Want to get a coffee
                              etc. sometime? </div>
                            <div>
                              <br /></div>
                            <div>I'm around Wednesday or
                              Thursday morning then traveling for a bit
                              until Aug. </div>
                            <div>
                              <br /></div>
                            <div>Chris<span></span></div>
                        </blockquote></div> </blockquote></div>
                    <div>-- <br /></div>
                    <div>
                      <div>
                        <div>
                          <span
                    style="font-size: 13.2px;">Chris</span></div></div></div>
                </blockquote></div> </blockquote></div>
            <div>-- <br /></div>
            <div>
              <div>
                <div>
                  <span
            style="font-size: 13.2px;">Chris</span></div></div></div>
        </blockquote></div> </blockquote></div>
    <div>-- <br /></div>
    <div>
      <div>
        <div>
          <span
    style="font-size: 13.2px;">Chris</span></div></div></div> </blockquote></div>```

here's without whitespace normal:

![image](https://cloud.githubusercontent.com/assets/1128856/9666013/7f0c202a-5228-11e5-88cd-03a4579f5923.png)


here's with normal:

![image](https://cloud.githubusercontent.com/assets/1128856/9666003/6e4f4988-5228-11e5-86b4-61e5fcb320cb.png)

**Comment by Pavek** [comment]
Do you have any update on this? I experience the same issue, but I believe that, despite being indeed related to CSS `white-space` property, this may be a bug in Quill.
- The issue is only reproduced when editor has `white-space:normal` and not reproduced with default `white-space:pre-wrap`. It is also reproduced only with **Firefox** (mine is v44).

- (My reason for having `white-space:normal` is very similar to the author's one: I implement a rich editor for email-like app and it means that sometimes editor does not start blank: it is fed with HTML generated by other email clients (think MS Outlook), which is complete junk -- lot's of custom attributes, extra spaces around etc. Now, I opted to not clean-up that junk because `white-space:normal` fixed all kinda magically. Except that one issue with Firefox..)

- I think this may be Quill's bug because of: 

1. I _can_ insert spaces when **NOT at the EOL** : [demo](https://gyazo.com/73874c547c82bc944314fa89c9f35eb6)
2. I _generally cannot_ insert when **at the EOL**: [demo](https://gyazo.com/c32f6c38bcbe9ceaa05077cbd4961f8f)
3. It _is possible_ to insert spaces at the EOL by pressing space/non-space chars very quickly or **simultaneously**: [demo](https://gyazo.com/9a83744b3b9b160c6dd8628a096e2869)

Notice also that a child element is being added in cases 2/3 when you type, but is removed quickly (not sure what's it, but may be related).

**Comment by scamden** [comment]
I ended up working around by using regex replaces to clean the html.
Generally I just replaced multi spaces with one. And possibly one other
replace I can't recall. But ya if I remember correctly Jason replied that
white space normal is a misuse and quill is not built to accept arbitrary
html. Sorta a bummer to do hacky heuristic replaces but it works for us.
Sterling Camden
Sent from SalesforceIQ

On March 16, 2016 at 9:01 AMPavel Zhytko<notifications@github.com> wrote:

Do you have any update on this? I experience the same issue, but I believe
that, despite being indeed related to CSS white-space property, this may be
a bug in Quill.

   -

   The issue is only reproduced when editor has white-space:normal and not
   reproduced with default white-space:pre-wrap. It is also reproduced only
   with *Firefox* (mine is v44).
   -

   (My reason for having white-space:normal is very similar to the author's
   one: I implement a rich editor for email-like app and it means that
   sometimes editor does not start blank: it is fed with HTML generated by
   other email clients (think MS Outlook), which is complete junk -- lot's of
   custom attributes, extra spaces around etc. Now, I opted to not clean-up
   that junk because white-space:normal fixed all kinda magically. Except
   that one issue with Firefox..)
   -

   I think this may be Quill's bug because of:


   1. I *can* insert spaces when *NOT at the EOL* : demo
   <https://gyazo.com/73874c547c82bc944314fa89c9f35eb6>
   2. I *generally cannot* insert when *at the EOL*: demo
   <https://gyazo.com/c32f6c38bcbe9ceaa05077cbd4961f8f>
   3. It *is possible* to insert spaces at the EOL by pressing
   space/non-space chars very quickly or *simultaneously*: demo
   <https://gyazo.com/9a83744b3b9b160c6dd8628a096e2869>

Notice also that a child element is being added in cases 2/3 when you type,
but is removed quickly (not sure what's it, but may be related).

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/quilljs/quill/issues/468#issuecomment-197397919>

**Comment by jhchen** [comment]
Quill needs whitespace to be set to a version of pre to maintain an accurate count of its contents. It would be best to just clean the incoming HTML as suggested.

**Comment by dudewad** [comment]
I know this is a super old issue but I'm experiencing this same issue in Firefox.
Adding a bunch of extra "cleanup" code to fix the issue in one browser seems like a weird workaround - isn't this just a compatibility issue with firefox that should be fixed in quill itself?
Does Quill not support single-line text editing where text grows wider than the field space and cuts off like a normal input would?

**Comment by archistico** [comment]
Perfect
