### ISSUE TITLE
Don't remove empty nodes in the toolbar

### ISSUE THREAD

**Issue by Dremora** [quilljs/quill#471]
When toolbar module from snow theme is being used, [it removes all whitespace nodes](https://github.com/quilljs/quill/blob/develop/src/themes/snow/index.coffee#L59). This makes it impossible to use Quill with Ember.js/HTMLBars (and potentially other frameworks which rely on the fact that DOM they generate doesn't get changed from the outside) - I'm getting a bunch of error messages. Disabling toolbar module seems to fix it.

Current approach to solving whitespace issue is very fragile. It would be nice to utilise CSS instead of changing the DOM (for instance, via floats which don't introduce font size-dependant whitespace after every inline element).

**Comment by jhchen** [comment]
The ideal solution would tolerate arbitrary whitespace, guarantee vertical alignment of the pickers and buttons, guarantee equal spacing between inputs, and has proper overflow behavior--on all supported browsers and platforms. I've only been able to get three out of the four and felt the first was least important. I'd of course welcome a PR that does all four.
