### ISSUE TITLE
Aligning with formatText doesn't work.

### ISSUE THREAD

**Issue by ollien** [quilljs/quill#472]
I can't align text using formatText, with a selection as my range. I've done some digging through the source code, only to find that the only way to make this work is using the formatLine method, which for some reason is undocumented. 

Either formatLine should be documented, or formatText should work more elegantly with align, as presently, it does not behave very elegantly.

**Comment by jhchen** [comment]
The reason is `formatText` needs to be called on the newline character, not just on any character on the line. `formatLine` was added later as a helper for those that prefer the latter behavior. I will update the docs to include both these facts.
