### ISSUE TITLE
Removing special character causing removing following symbols in a line

### ISSUE THREAD

**Issue by anovi** [quilljs/quill#473]
Strange behaviour. When i insert special symbol [BACK WITH LEFTWARDS ARROW ABOVE](http://apps.timwhitlock.info/unicode/inspect?s=%F0%9F%94%99) and delete it, Quill  removes all next symbols in the same line.

![quill-emoji](https://cloud.githubusercontent.com/assets/3472054/9705556/743891a6-54d0-11e5-9cfe-8556301e036a.gif)

**Comment by jhchen** [comment]
Thanks for the report. The issue seems to be that certain characters have a length > 1 in Javascript strings which the keyboard module is not expecting.
