### ISSUE TITLE
IE10 link stuck

### ISSUE THREAD

**Issue by Predjo** [quilljs/quill#474]
If you create a link in IE10 you can not type after it and you are stuck. It only happens if the link is in the last place in the document. 
Happens in IE10 but not Chrome or FF.

**Comment by hgkim999** [comment]
I had a same issue. This was happening because the editor looses the focus when LinkTooltip Listener shows the tooltip DOM.

Changing
```
if (anchor != null) {
        this.setMode(anchor.href, false);
        this.show(anchor);
}
```
to
```
if (anchor != null) {
        this.setMode(anchor.href, false);
        this.show(anchor);
        this.quill.focus();
}
```
at line 20~23 in modules/link-tooltip.js
solved the problem in IE10.

However, I'm not sure how this change will affect anything.

**Comment by jhchen** [comment]
IE10 support is being dropped in favor of MS Edge. Feel free to reopen if you experience this in IE11 or MS Edge.
