### ISSUE TITLE
addFormat is not working correctly.

### ISSUE THREAD

**Issue by ollien** [quilljs/quill#475]
I couldn't get addFormat to work correctly with blockquote (a forbidden tag), so I made one with blink as a test, in order to verify whether or not it worked correctly.

```js
editor.addFormat("blink", {tag: "blink", prepare: "blink"})
```

With "test" entered in the editor, I executed the following, but alas, nothing happened.

```js
editor.formatText(0, 4, "blink", true)
```

Is there a workaround to this, and/or could this be fixed?

**Comment by jhchen** [comment]
The current format customization is rather limited in that Quill uses a whitelist for allowed tags rather than a blacklist. This is all changing in the next major version (currently worked on it the [parchment](https://github.com/quilljs/quill/tree/parchment) branch). There should be a post with more details in the next couple of weeks.

**Comment by ollien** [comment]
Next couple weeks? Sweet! Thank you!

**Comment by hunternet93** [comment]
Any update on this? My app needs custom markup, Quill's worked great so far for me but this is something of a problem...

**Comment by souporserious** [comment]
+1

**Comment by jhchen** [comment]
Blog post is here: http://quilljs.com/blog/the-road-to-1-0/

**Comment by souporserious** [comment]
Read that earlier today, any time frame on the release? I know you've been hesitant about giving any dates, maybe a ballpark? I unfortunately had to remove Quill because of this. Thought I could get by until it cam out, but I wasn't able to.

**Comment by ollien** [comment]
@souporserious Do you have an alternative that you've selected? Quill seems to be the most lightweight compatible option, but if you have an alternative that matches the functionality, I'd love to give it a shot.

**Comment by souporserious** [comment]
@ollien using this for now https://github.com/wysiwygjs/wysiwyg.js still want to use Quill once I'm able to use addFormat.
