### ISSUE TITLE
List wrapped in a tag besides <div> are inlined during parsing

### ISSUE THREAD

**Issue by hryanjones** [quilljs/quill#477]
I think that [this jsbin](http://jsbin.com/himetu/edit?js,output) might well demonstrate the issue. I have Outlook on Windows users running into this issue because Outlook (although not Outlook Web Access), will wrap the whole body in a `<font>` and a `<span>`. I'm going to try to work around this for the time being...

Thanks!

**Comment by jhchen** [comment]
Is it just one outer `<font>` or `<span>` element? The simple workaround is to change this into a `<div>` beforehand as Quill does not handle invalid HTML well.

**Comment by hryanjones** [comment]
Oh, I hadn't realized that was invalid HTML and it's unfortunate that Outlook is generating that. I'll see if I can just work around it.

**Comment by hryanjones** [comment]
Just removing the `<font>` and `<span>` on the global level solves this and another problem I was running into where the cursor was always going to the beginning of the line. Silly Outlook.

Thanks!
