### ISSUE TITLE
configurable ql-active class

### ISSUE THREAD

**Issue by jaketodaro** [quilljs/quill#478]
It would be helpful if the Toolbar module allowed you to configure what class gets added to the inputs when they're active rather than it always being hard-coded to `ql-active`. In my use case, I'm using a third party UI library and I'd like to be able to use the active styling that the library provides rather than style `ql-active` myself.

**Comment by jaketodaro** [comment]
@jhchen I'd be happy to contribute this feature if you think it's appropriate.

**Comment by jhchen** [comment]
The current develop branch has a lot of things broken / disabled so might not be the best time to dive in. It's a pretty simple change once things stabilize.

**Comment by jhchen** [comment]
Quill now uses stylesheets even for the basic editor so there needs to be an agreement on the classname between javascript and css at build time. I don't believe this feature is possible with this requirement without breaking existing functionality.

A simple workaround is to register a mutation observer on the toolbar whenever a class name changes and add / remove your own custom one.
