### ISSUE TITLE
What is the best way to disable a certain key?

### ISSUE THREAD

**Issue by jaketodaro** [quilljs/quill#479]
I need to build an editor that simulates a native `input`, so I need to prevent enter from being pressed and causing a newline. To prevent most characters I can just preventDefault on keydown if a disallowed character is pressed, but because I need to disallow enter I also need to delete `quill.modules.keyboard.hotkeys[13]`, but that seems a little gross. Is there a better way to do this?

**Comment by jhchen** [comment]
A `removeHotkeys` call was added by #453 but has not been released yet. Quill is in the middle of a big change so the next version will take much longer to get out. I was also considering changing the signature into `removeHotkey` and `removeAllHotkeys` to be more consistent with eventemitter APIs.

**Comment by Joeao** [comment]
What's the correct way to do this in 1.X?
Previously `quill.modules.keyboard.removeHotkeys({ key: 13 });` had worked. Disabling bindings works for keys such as tab. However I can't find a way to prevent handleEnter from occurring. The [documentation](http://quilljs.com/docs/modules/keyboard/#configuration) suggests that it just straight up can't be done due to dangerous behaviour, though it could in 0.21 with seemingly no implications.

**Comment by jhchen** [comment]
The documentation is correct. But I think there may be a misunderstanding. You can add a handler to run before the default and not propagate to `handleEnter`. What you cannot do, which is the dangerous thing, is prevent `handleEnter` from running in order for the browser default behavior to run.

**Comment by Joeao** [comment]
Thanks @jhchen, the following worked just fine to prevent a new line and tab space
```javascript
keyboard: {
    bindings: {
        tab: false,
        handleEnter: {
            key: 13,
            handler: function() {
                // Do nothing
            }
        }
    }
}
```

**Comment by BennieCopeland** [comment]
How do you prevent/remove newlines when pasting in content?

**Comment by programthis** [comment]
@Joeao Does this solution still work for you? It doesn't prevent new lines in my editor when I use it (example below):

```
var quill = new Quill('.addMessageEditor', {
		modules: {
			toolbar: false
		},
		keyboard: {
		    bindings: {
		        tab: false,
		        handleEnter: {
		            key: 13,
		            handler: function() {
		                // Do nothing
		                console.log("test");
		            }
		        }
		    }
		},
	    theme: 'snow',
	    placeholder: "Enter message here..."
	});
```

**Comment by l4nz10** [comment]
Hello, I stumbled upon a particular behavior trying to disable the enter key in Quill. The snippet suggested by @Joeao works fine until you pass to a heading format.
In that case the editor will ignore the disabling and insert a new line.

Any suggestions in order to fix this issue?

**Comment by WilliamIPark** [comment]
@l4nz10 You've probably solved this by now, but I landed here with the same problems. Just to help anyone else who lands here in the future, this disables enter for headers & paragraphs:

```javascript
keyboard: {
      bindings: {
        handleEnter: {
          key: 13,
          handler: () => {},
        },
        "header enter": {
          key: 13,
          handler: () => {},
        },
      },
    },
```

**Comment by hosnyben** [comment]
> @l4nz10 You've probably solved this by now, but I landed here with the same problems. Just to help anyone else who lands here in the future, this disables enter for headers & paragraphs:
> 
> ```js
> keyboard: {
>       bindings: {
>         handleEnter: {
>           key: 13,
>           handler: () => {},
>         },
>         "header enter": {
>           key: 13,
>           handler: () => {},
>         },
>       },
>     },
> ```

You saved me vafter three misirable days of figuring out how to. Thank you Sir !

**Comment by mind-jayesh2401** [comment]
on Key press of 'enter' i have prevent from breaking line but when i search quill-emoji and try to press that is even stopped now because it's a part of quill editor and emoji selection is causing problem.

any suggestion how to do by quill methods ??
else i can do it by patch but i need solution in binding method itself.

**Comment by Masam-abbas-avialdo** [comment]
@mind-jayesh2401 Can you please tell me how to prevent line break. I am using ReactQuill in Nextjs App.
