### ISSUE TITLE
Compatibility issue with Angular.js 1.4 and the Toolbar module

### ISSUE THREAD

**Issue by ericeslinger** [quilljs/quill#481]
Possibly other versions of angular as well. Also: I'm aware that this is probably an angular issue, but I thought I should put it here in case other quill users get hung up in a similar place.

I'm making an angular directive to encapsulate quill behaviors. The directive includes both an editor and toolbar module. If my generic directive controller looks like this:

```javascript
  this.editor = new Quill($element[0].children[1], {
    theme: 'snow',
    modules: {
      'link-tooltip': true,
      'undo-manager': true,
    }
  });
  this.editor.addModule('toolbar', $element[0].children[0]);
```

I get a really weird angular error - `TypeError: Cannot read property 'childNodes' of undefined`. The error itself is really hard to debug, but is coming from angular's linking cycle. I don't know if the toolbar does funky stuff to the toolbar nodes asynchronously, but it may be that angular and quill are arguing with each other. 

Selectively commenting stuff out indicates that it's the toolbar module that does it (I get the same error if the toolbar is declared in the Quill constructor).

However, if I take the toolbar instantiation and move it to an async evaluation thusly:

```javascript
  $scope.$evalAsync(()=>{
    this.editor.addModule('toolbar', $element[0].children[0]);
  });
```

Everything works fine. So again, I'm not 100% certain what's going on here - the error comes from deep within angular's internals, but only if I call addModule to instantiate a toolbar.

**Comment by jhchen** [comment]
Can you post the stack trace?

**Comment by ericeslinger** [comment]
Here's the stack trace - like I said, it's 100% inside of angular. If I have time this week, I'll download a buildable repo for quill and see if I can't get deeper into which particular bit angular objects to. 

```
TypeError: Cannot read property 'childNodes' of undefined
    at compositeLinkFn (angular.js:7641)
    at compositeLinkFn (angular.js:7641)
    at nodeLinkFn (angular.js:8241)
    at angular.js:8476
    at processQueue (angular.js:14634)
    at angular.js:14650
    at Scope.$eval (angular.js:15878)
    at Scope.$digest (angular.js:15689)
    at Scope.$apply (angular.js:15986)
    at done (angular.js:10511)
(anonymous function) @ angular.js:12416
(anonymous function) @ angular.js:9203
processQueue @ angular.js:14642
(anonymous function) @ angular.js:14650
Scope.$eval @ angular.js:15878
Scope.$digest @ angular.js:15689
Scope.$apply @ angular.js:15986
done @ angular.js:10511
completeRequest @ angular.js:10683
requestLoaded @ angular.js:10624
```

**Comment by jhchen** [comment]
I'm going to close this for now as it's not entirely clear this is resolvable within Quill. [ngQuill](https://github.com/KillerCodeMonkey/ngQuill) might be worth a look too (no affiliation but seems like the most active angular + quill project).

**Comment by MichaelKloepzig** [comment]
@ericeslinger Have you ever found a solution for this problem? I'm stuck at the same point.

**Comment by ericeslinger** [comment]
As I mentioned in my initial post, I basically load the quill stuff asynchronously, after the angular element has finished linking by using `scope.$evalAsync(() => initializeQuill(scope))` in the controller. It's a bit hacky but it works. My guess is that there was some race condition in there as the quill system inflated some DOM nodes onto the toolbar div and the angular compiler walked the DOM to build its own data structures (looking for `{{stuff}}`), so holding off from building the quill stuff until after the angular code ran worked okay.

**Comment by MichaelKloepzig** [comment]
Ah, I missed that bit. Figured the same in the meantime and fixed it with a $timeout around the Quill init, so similar to your approach. Thanks anyways!
