### ISSUE TITLE
Changing a links href scrolls the page back to the top

### ISSUE THREAD

**Issue by scottjacobsen** [quilljs/quill#482]
Verified in Chrome Version 45.0.2454.93 (64-bit) on OSX and Safari 8.0.8 on OSX. FF works fine.

* Go to the [demo site](http://quilljs.com)
* Scroll the page down a bit, keeping the editor in view
* Scroll down in the editor until the 'Download Quill' link is visible
* Click on 'Download Quill'
* Click the 'Change' link in the popup
* Click the 'Done' link

The page and the scrollable div both scroll to the top.

The div and page should maintain their scroll position.

**Comment by jhchen** [comment]
I can confirm the issue on the latest released version 0.20.0 but it's not showing up in the development branch. Likely a related issue such as #435 fixed this as well. I'll confirm when the next release is out (which will be 1.0 so will be a bit longer).
