### ISSUE TITLE
When the editor has the css property white-space:pre-line it doesnt work correctly

### ISSUE THREAD

**Issue by santiagotactivos** [quilljs/quill#485]
In chrome when the property white-space:pre-line is set in the editor when you delete a character it deletes the character and the space before it.

![problem quill css](https://cloud.githubusercontent.com/assets/1245712/10002360/00f6fc9c-607d-11e5-9f5b-3ad11c67c2e8.gif)

In firefox is even worst it doent take in consideration the space after typing it and replace the space with the next character you are typing.
![problem quill cssffox](https://cloud.githubusercontent.com/assets/1245712/10002395/2f749a34-607d-11e5-957b-ae13d2f1efb2.gif)

**Comment by jhchen** [comment]
What's the use case here? Quill relies of this property (which could be better documented) and changing it is not a safe procedure.

**Comment by jhchen** [comment]
Closing from inactivity. Feel free to comment with more info.
