### ISSUE TITLE
Editor overflows fixed-height container if a toolbar is added

### ISSUE THREAD

**Issue by jasongisstl** [quilljs/quill#486]
If you have a fixed-height container element, and use this to create a Quill editor, the editor's height is set to 100%. So if there's a toolbar present, the editor overflows the bottom of the container by the height of the toolbar.

Please see [JS Fiddle] (https://jsfiddle.net/3v2zncrg/1/)

Perhaps I'm missing something?

**Comment by jhchen** [comment]
Yes by default Quill's height is 100%. If you want a fixed height + toolbar, one simple way is to fix the height of the Quill editor and toolbar, not the container, and put a border around the container. The editors in the [examples page](http://quilljs.com/examples/) both do this.

Does this solve your problem?

**Comment by jasongisstl** [comment]
Thank you for your quick reply, Jason!

I see, yes, that makes sense. Thank you for the explanation.

My use case is that I have a fixed size container, which itself may be dynamically resized by external factors, and I need the editor to always fill it.

Being a lazy good-for-nothing, I was hoping this may be supported out of the box, but I can definitely do this myself by manually setting the heights in JavaScript.

Cheers!

**Comment by jhchen** [comment]
Yes ideally Quill could be more helpful but some people want Quill to stay a fixed height and scroll and others want it to fill the rest so Quill just has a simple default.

For your use case you might want to try just fixing the height of the toolbar which allows you to set a padding on the container and negative margin on the toolbar equal to its height. For example: http://jsfiddle.net/8Ljhyzf2/1/.

**Comment by jasongisstl** [comment]
Thanks again for the explanation, and for going to the trouble of creating an example for me. That is really going above and beyond!

The example is not perfectly suited to my use case (not that you were to know that) - it doesn't allow for the toolbar to wrap onto multiple lines when it becomes too narrow. But I like the idea and can use this in other areas, i'm sure.
However, I do have a solution now (setting the height manually when getting resize events from our framework).

Thanks again for all of your help, and love what you have created with Quill - it's fantastic!

**Comment by rgreenhalge** [comment]
I solved this issue with css calc(); 

```
.ql-container {
    height: calc(100% - 42px);
  }
```
