### ISSUE TITLE
API calls result in TypeError: text is undefined

### ISSUE THREAD

**Issue by dvodonnell** [quilljs/quill#489]
Loading Quill the usual way and getting TypeError: text is undefined errors any time the API is hit, either when trying to bold/italicize text (which still works), or getContents(). Line 4931, within Delta.prototype.insert() def'n.

Likely the only exceptional thing about how I'm using the plugin is that it sits within a rather length AMD flow (RequireJS), and when Quill is initialized its DOM may or may not be appended to the document.

Is Quill designed to initialize properly even if it's not yet in the document?

**Comment by jhchen** [comment]
I would not be surprised if not being attached to the document causes problems as Quill does not specifically handle or test this condition. However a simple test yields no errors: http://jsfiddle.net/4yfj5quu/1/ so this might not be the problem. Can you post a stack trace?

**Comment by jhchen** [comment]
Feel free to reopen if this is still an issue within Quill.
