### ISSUE TITLE
iOS Safari, word deletion mode not supported (slow character deletion)

### ISSUE THREAD

**Issue by TheJDP** [quilljs/quill#490]
In iOS Safari we can longpress the backbutton on our keyboard. In the first seconds the browser deletes characters (one character in ca. 100ms). After some seconds they start deleting words (in a slower interval ca. 300ms per word).
But with quilljs they don't move into the word deletion mode. They only start to delete the characters in the slower interval(300ms).

Reproduction tested on iOS 8 & 9 on iPad3,iPadAir,iPadMini:
- Open http://quilljs.com/ with Safari browser
- Select a position at the end of a centence on the preview editor and start deleting with the backbutton

**Comment by jhchen** [comment]
Yes Quill overwrites backspace behavior since they are inconsistent between browsers but is not handling word deletion correctly. Thank you for reporting.

**Comment by jhchen** [comment]
Also fixed by https://github.com/quilljs/quill/commit/0c6e6a84fefbb4f7128c3ee91604e4f6576759f7.
