### ISSUE TITLE
Font Size Issue

### ISSUE THREAD

**Issue by jasongisstl** [quilljs/quill#491]
I think there seems to be an issue with the Font Size with version 0.20.0. I'm unsure as to what is causing it, but hopefully the following [JS Fiddle](http://jsfiddle.net/3v2zncrg/6) will make it clear. 

In the example, the 'Large' font size is selected as the default.

If you run the example and set the Font Size to 'Normal' from the toolbar, as soon as you start typing the toolbar will revert back to 'Large', and the actual size of the inserted text becomes 13px (even though my 'normal' size is 12px).

If I revert back to version 0.19.10, the Toolbar doesn't change back to display 'Large' size as soon as you start typing in 'Normal' size, but it does still insert the text as 13px instead of 12px.

(Reproduced with Chrome, Safari & Firefox)

**Comment by jhchen** [comment]
Quill 1.0 now uses classes for font sizes so this should now work: http://jsfiddle.net/s8k3bnLL/1/. If you want 'normal' to be a non-default value, you will have to customize the font size attributor with [Parchment](https://github.com/quilljs/parchment).
