### ISSUE TITLE
setHTML() is not interpreting headers

### ISSUE THREAD

**Issue by gianmarcotoso** [quilljs/quill#492]
The setHTML method appears to be stripping away all header tags. You can try this on the Quill homepage by opening a console and executing `quill.setHTML('<h1>Hello!</h1>')`.

Using version 0.20.0

**Comment by jhchen** [comment]
Headers are not currently supported see #111

**Comment by gianmarcotoso** [comment]
I'll try to add it then, since custom h* formats work just fine and the problem seems to be with the parsing of the tags. Do you have some pointers that might help me?
