### ISSUE TITLE
Recommend not opening link modal when cursor is next to link

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#493]
Currently the link modal open up when the cursor is just next to the link. 

This is causing funny UX issues. I recommend only opening the link modal when the user clicks the link.

**Comment by jhchen** [comment]
Can you elaborate on the funny UX issues? Quill's behavior is consistent with other editors'.

**Comment by sferoze** [comment]
Ah well the UX issue was that the link modal was opening over the text. This is because the link modal is confined to its parent container and so the text near the top of the note would be covered by the link modal.

Also

The link modal does not hide reliably. 

I had to add this code to make sure the link modal goes away when not in use

```coffeescript
@$('.quill-note-container').mousedown (e) ->
      unless $(e.target).is('a') or $(e.target).parent().is('a')
        $('.ql-tooltip.ql-link-tooltip:not(.editing)').css 'left', '-10000px'
```

**Comment by jhchen** [comment]
Okay sounds like the original issue was actually behaving as designed, given the constraints. If you can reliably reproduce the link modal not hiding feel free to open a separate Issue.
