### ISSUE TITLE
Parchment & 1.0

### ISSUE THREAD

**Issue by Benibur** [quilljs/quill#494]
Your blog post about Parchment and Quill.js 1.0 is really a teasing one !
Especially for me who was about to start a plugin to manage tags in the editor (with auto completion).

So : 

1/ do you think I should wait for Parchment before starting to develop this plugin for tags (embed) ?
(the tag can is a dom element in the content that would be dealt as one embedded character, and interaction with the tag would be managed by the plugin and not the editor).

2/ if yes, do you have any idea a roadmap / date (a rough range would be perfect : 1 week, 1 month, 1 trimester, 1 semester, 1 year...)

Thanks !

Ben

**Comment by jhchen** [comment]
1.0 will certainly make your task a lot easier. Whether you should wait depends on a lot of things: how complex of a tag system you want, how urgently you want this, how much time you're willing to put in to make it work with the existing setup, etc so it's hard to say. One possibility is just try it out and if it's too painful stop and wait for 1.0.

Timelines are tough to estimate. I would just suggest following along and as progress is made you can use that velocity as an estimate for time remaining.

**Comment by Benibur** [comment]
Your hard with me :-)
in one hand you tease me, in the other you say "one day"...
I will wait a bit, but if you had an even very approximative idea of a range of dates that would be much more easy to take a decision... (end of the year ? Q1 2016 ? Q3 2016 ?)
Good luck anyway !

**Comment by navneet35371** [comment]
+1

**Comment by aenario** [comment]
:+1: I am really interesting in embedding complex components (with interaction) as characters in quill
