### ISSUE TITLE
Collapsing identical attributes

### ISSUE THREAD

**Issue by JoshBarr** [quilljs/quill#498]
Hey,

I've been taking Parchment + Quill for a spin, implementing an editor interface with some quite obscure requirements. They're great libraries and the bite-sized methods in the source code make for good reading. Thanks for open-sourcing this project.  

Suppose I've got two operations, with different `inserts` but the same `attributes`. Do Quill/Parchment provide any way to resolve these into one? Or would that totally defeat the purpose of using deltas? 

I can do a deep comparison myself periodically and update the contents via `setContents()`, or do it when I prepare to serialise data back to the server, but I was wondering if there's a built-in approach for doing this already? 

To illustrate what I mean:

```json
{
    "attributes": {
        "font": "georgia"
    },
    "insert": "some pleasant serif "
},
{
    "attributes": {
        "font": "georgia"
    },
    "insert": "typography"
}
```

Would become:

```json
{
    "attributes": {
        "font": "georgia"
    },
    "insert": "some pleasant serif typography"
}
```

**Comment by jhchen** [comment]
Quill always produces compact Deltas so I'm assuming these are created either manually or separately? If the former is the case, Quill/Delta does not provide anything explicitly for this. If the latter is the case, the new Delta library (v2.1) adds a [concat](https://github.com/ottypes/rich-text#concat) method that will handle combining adjacent inserts with the same attributes. Quill is still using 2.0 but 2.1 is backwards compatible so it should be fine to use the upgrade. Note concat assumes given Deltas are produced by the Delta library methods (which Quill does) so it will not work if your Deltas were produced manually.
