### ISSUE TITLE
Rich editing icons does not update via shortcut keys (ctrl+b) if pressed repetedly

### ISSUE THREAD

**Issue by aliarshad9691** [quilljs/quill#499]
pressing ctrl + B highlights the "b" button but doesn't remove the highlight on typing ctrl+b again, until something is typed into the editor.
same for underline and italic styles.

works well on clicks

**Comment by jhchen** [comment]
What browser + OS?

**Comment by jhchen** [comment]
This has been fixed in the 1.0 [beta](http://beta.quilljs.com/) release
