### ISSUE TITLE
Backspace adds text into link (MS Edge only)

### ISSUE THREAD

**Issue by dandormont** [quilljs/quill#501]
I don't have a fully generalized test case for this, but I am able to reproduce it consistently in one particular scenario. Visit the following fiddle in MS Edge on Windows 10: http://jsfiddle.net/bbL645hv/1/

Note that you end up with the cursor just after the end of a link. Type some stuff, for example I typed the words "test test". Then hit Backspace twice. It erases your last two characters as expected, but it also adds the rest of your post-link content eg "test te" into the preceding hyperlink.

**Comment by jhchen** [comment]
It appears to be working in the latest version of MS Edge now.
