### ISSUE TITLE
Sometimes doesn't work with UCweb browser in some cases

### ISSUE THREAD

**Issue by zhenfan0753** [quilljs/quill#504]
First of all, Quilljs is really brilliant! 
When I open the demo page http://quilljs.com/ using UCweb browser, typing multiple characters after I touch the buttons on the toolbar,the text sometimes doesn't change(QuillJs doesn't work).
But, when I type only one character after I push the button on the tool, the text will change normally.
Can u please install an UCweb brwoser(http://uc.cn),and see this problem, please help me

**Comment by jhchen** [comment]
UC is not a supported browser.
