### ISSUE TITLE
Add equation support (mathematical expressions)

### ISSUE THREAD

**Issue by canesin** [quilljs/quill#511]
Hi, quill could add support for equations (could be a very simple one first, a la: http://sdk.ckeditor.com/samples/mathjax.html)

Also there is a great alternative to MathJax fron KhanAcademy: http://khan.github.io/KaTeX/

**Comment by cbankester** [comment]
It would be cool to see it output [MathML](https://developer.mozilla.org/en-US/docs/Web/MathML) on Gecko browsers, which should be possible if we used MathJax. :+1:

**Comment by brettimus** [comment]
+1 Good idea! Could probably be written as a module?

**Comment by lance13c** [comment]
+1 Great idea! Looking forward to it's implementation.

**Comment by jhchen** [comment]
This has been added in the [beta](http://beta.quilljs.com/) release

**Comment by faller** [comment]
@jhchen Still lost mathjax.

**Comment by ChristianVaughn** [comment]
I know this is a very old and closed issue, but was MathML and MathJax support actually added? I don't see it at all and I am trying to get asciimath displayed in Quill using mathjax.
