### ISSUE TITLE
Style tag being added for each instantiation of Quill

### ISSUE THREAD

**Issue by jakedeichert** [quilljs/quill#519]
I'm creating and destroying instances of Quill frequently and I noticed that for each `new Quill('#editor')` the base style tag is added to the DOM.

Here's a screenshot of each style tag after a few instances have been created and destroyed:

![multiple instances of quill styles](https://cloud.githubusercontent.com/assets/1631044/11044935/abd70dd2-86f2-11e5-9812-10b84b54e441.png)

My current workaround is to specify `{styles: false}` as Quill's config so that no styles are added.

Just making sure if this is a known bug or not! I don't really need any of Quill's base styles for my use case.

**Comment by jhchen** [comment]
The `{ styles: false }` config exists exactly for this use case so no need to worry about using it as a workaround.

**Comment by jakedeichert** [comment]
Sounds good, thanks!
