### ISSUE TITLE
Inserting a newline and typing does not always retain previous line's formatting.

### ISSUE THREAD

**Issue by byronm** [quilljs/quill#52]
The desirable behavior is that if you have a formatted line, hit enter, and continue typing, you should automatically get the formatting of the previous line.

Scribe currently is not designed to do this, though some percent of the time it will due to a "bug". Ultimately, we want it to always do this as it's the correct behavior.

**Comment by jhchen** [comment]
Fixed in c83d050630f3e0134539273aab0b6dc81f9284c8
