### ISSUE TITLE
Expanding buttons does not close other expanded menus

### ISSUE THREAD

**Issue by hgkim999** [quilljs/quill#520]
Screenshot:
<img width="283" alt="expand" src="https://cloud.githubusercontent.com/assets/8624103/11048679/34a455ac-86ee-11e5-8036-7483492a7e33.png">
Description:
Currently, expanding menus, such as Text Color, Background Color, and Align, do not close other expanded menus, and they overlap each other.

**Comment by willrowe** [comment]
I can confirm this behavior on the website itself. I never really noticed this before, so I'm not exactly sure if it's a bug or not. If you select something in any of the menus then they are all closed, but if you don't select anything and then open another, it will remain open.

Will

**Comment by kupec** [comment]
wysihtml editor(http://wysihtml.com/)  has the same problem

**Comment by jhchen** [comment]
#265
