### ISSUE TITLE
Enable the  font dropdown

### ISSUE THREAD

**Issue by radu-andrei-28** [quilljs/quill#521]
I am currently trying to implement the  quill editor using the API (great job you done!!!!) and I am facing some troubles with the dropdowns. For some reasons when I press the font dropdown, the dropdown doesn't show. I believe that the editor doesn't react due to the span -> option mapping. 

If I display the select tag and chose one of the options the text will change the format.

So my question is: How can I map the span with the options that each select tag has?

P.s: I am currently using the example provided on your website loading the //cdn.quilljs.com/0.20.0/quill.js

**Comment by jhchen** [comment]
Do you encounter this problem on the quilljs.com editor?

**Comment by radu-andrei-28** [comment]
I am encountering this problem while using the quill api. I tried to implemented like this:

  <div id="toolbar" class="toolbar ql-toolbar ql-snow">
                    <span class="ql-format-group">
                        <span title="Font" id="ql-font"class="ql-font ql-picker"><span class="ql-picker-label" data-value="sans-serif">Sans Serif</span>
                            <span class="ql-picker-options">
                                <span data-value="sans-serif" class="ql-picker-item ql-selected">Sans Serif</span>
                                <span data-value="serif" class="ql-picker-item">Serif</span>
                                <span data-value="monospace" class="ql-picker-item">Monospace</span>
                            </span>
                        </span>
                        <select title="Font" class="ql-font" style="display: none;">
                            <option value="sans-serif" selected="">Sans Serif</option>
                            <option value="serif">Serif</option>
                            <option value="monospace">Monospace</option>
                        </select>
                        <span title="Size" class="ql-size ql-picker">
                            <span class="ql-picker-label" data-value="13px">Normal</span>
                            <span class="ql-picker-options"><span data-value="10px" class="ql-picker-item">Small</span>
                                <span data-value="13px" class="ql-picker-item ql-selected">Normal</span>
                                <span data-value="18px" class="ql-picker-item">Large</span>
                                <span data-value="32px" class="ql-picker-item">Huge</span></span>
                        </span>
                        <select title="Size" class="ql-size" style="display: none;">
                            <option value="10px">Small</option>
                            <option value="13px" selected="">Normal</option>
                            <option value="18px">Large</option>
                            <option value="32px">Huge</option>
                        </select>
                    </span>
</div>
   <div id="editor">
           <div id="passage-text" class="passage">
                         <span data-dur="0.154" data-begin="0.775" tabindex="0" data-index="0" class="">In</span>&nbsp <span data-dur="0.28" data-begin="0.929" tabindex="0" data-index="1" class="">those</span>&nbsp <span data-dur="0.29" data-begin="1.218" tabindex="0" data-index="2" class="">days</span>&nbsp <span data-dur="0.131" data-begin="1.508" tabindex="0" data-index="3" class="">a</span>&nbsp <span data-dur="0.525" data-begin="1.639" tabindex="0" data-index="4" class="">decree</span>&nbsp <span data-dur="0.191" data-begin="2.165" tabindex="0" data-index="5" class="">went</span>&nbsp <span data-dur="0.225" data-begin="2.355" tabindex="0" data-index="6" class="">out</span>&nbsp <span data-dur="0.245" data-begin="2.583" tabindex="0" data-index="7" class="">from</span>&nbsp <span data-dur="0.438" data-begin="2.828" tabindex="0" data-index="8" class="">Caesar</span>&nbsp <span data-dur="0.637" data-begin="3.267" tabindex="0" data-index="9" class="">Augustus</span>&nbsp <span data-dur="0.166" data-begin="4.03" tabindex="0" data-index="10" class="">that</span>&nbsp <span data-dur="0.268" data-begin="4.216" tabindex="0" data-index="11" class="">all</span>&nbsp <span data-dur="0.111" data-begin="4.486" tabindex="0" data-index="12" class="">the</span> &nbsp<span data-dur="0.411" data-begin="4.594" tabindex="0" data-index="13" class="">world </span> &nbsp <span data-dur="0.205" data-begin="5.006" tabindex="0" data-index="14" class="">should</span> <span data-dur="0.134" data-begin="5.211" tabindex="0" data-index="15" class="">be</span> <span data-dur="0.529" data-begin="5.344" tabindex="0" data-index="16" class="">registered</span>.
                    </div>
                </div>

and Javascript 

var quill =  new Quill('#editor', {
                    formats: ['bold', 'italic', 'color', 'size', 'font']
                  });
                  quill.addModule('toolbar', { container: '#toolbar' });
                  quill.prepareFormat('font', true);

**Comment by jhchen** [comment]
I think the issue is you're not supposed to add the picker yourself. Just add the `<select>` tag and specify 'snow' as the theme and it will be added and hooked up for you. Ex.

```html
<!-- Create toolbar container -->
<div id="toolbar">
  <!-- Add font size dropdown -->
  <select class="ql-size">
    <option value="10px">Small</option>
    <option value="13px" selected>Normal</option>
    <option value="18px">Large</option>
    <option value="32px">Huge</option>
  </select>
</div>
<div id="editor"></div>

<!-- Initialize editor and toolbar -->
<script>
  var editor = new Quill('#editor', { theme: 'snow' });
  editor.addModule('toolbar', {
    container: '#toolbar'     // Selector for toolbar container
  });
</script>
```

Also font expects a font value (like helvetica or arial, not just true) when you call prepareFormat.

**Comment by radu-andrei-28** [comment]
Yes it works! Thank you!
