### ISSUE TITLE
Preformat only works for 1 character in IE when we using web components

### ISSUE THREAD

**Issue by radiart** [quilljs/quill#523]
The error form here: https://github.com/quilljs/quill/issues/65 appears when we using webcomponenets (https://github.com/webcomponents/webcomponentsjs)

On an empty document:

Control + B to set format to bold
Type "test"
Only the "t" will be bolded in IE. 
Same behavior for italics.

Try to remove content, select Bold and write someting on IE: https://jsfiddle.net/0bg4ezs6/

**Comment by radiart** [comment]
Error exists even without web components, so it's not connected.

**Comment by alexmahterian** [comment]
I'm having the same issue. Was this resolved somewhere else?
