### ISSUE TITLE
Styles applied multiple times

### ISSUE THREAD

**Issue by Joeao** [quilljs/quill#524]
Hey there,

I have Quill instantiated on multiple elements on one page. I've noticed that the base styles are applied to the head each time an instance is created.

My solution was to make a function to apply base styles, using an ID on the style to avoid duplication, and a separate function to add custom styles, however this points out a conflict that must already exist if custom styles are used on one Quill instance, surely these styles will affect all instances. This makes the solution a bit more complicated.
I noticed that custom styles aren't really documented, and maybe themes are intended to be used instead. In which case implementing my proposed solution won't cause any problems, otherwise this will require greater thought.

Joe

**Comment by willrowe** [comment]
This is a duplicate of both #519 and #411

**Comment by Joeao** [comment]
Oh awesome. Did run a few searches but assumed it'd be an open issue. My b.
