### ISSUE TITLE
Beyond 1.0 Theme

### ISSUE THREAD

**Issue by jolic** [quilljs/quill#528]
Are these popovers now available? Or where can I get them to test some stuff?
see http://quilljs.com/blog/the-road-to-1-0/

**Comment by jhchen** [comment]
No they will be available post 1.0.

**Comment by jolic** [comment]
Is there a plan when the 1.0 will be released?
Thx

**Comment by jhchen** [comment]
There is no public timeline.

**Comment by jolic** [comment]
;) 
Is there a beta or some code where i can try or add some code to see the popup?

**Comment by willrowe** [comment]
The code for v1 is in the develop branch.

**Comment by jolic** [comment]
ok. thx,
