### ISSUE TITLE
Seems to implement the editor, but cannot select any text or get focus to enter anything.

### ISSUE THREAD

**Issue by joetidee** [quilljs/quill#530]
I have a Meteor application and have added Quill to a container with the HTML:

```
<div id="my_quilltoolbar">
    <button class="ql-bold">Bold</button>
    <button class="ql-italic">Italic</button>
</div>
<div id="my_quill">some content</div>
```

with the javascript being:

```
var quill = new Quill("#my_quill");
quill.addModule('toolbar', { container: "#my_quilltoolbar"});
```

However, even though the toolber buttons show, I cannot select the text within the editor, nor can I place the cursor anywhere to type!

(I also checked the source and the ql-editor wrapper div does have the contenteditable="true" attached)

Note: the container that the Quill editor has been added to is within a container that has jQuery sortable applied to it.

**Comment by jocoolie** [comment]
What browser are you using?

**Comment by jocoolie** [comment]
I know IE has issues with contenteditable on table-related elements. What browser are you finding this issue in?

**Comment by joetidee** [comment]
I am observing this in Chrome. My containing wrapper div's do have css display types of table, table-cell, etc., so this might well be the issue. Do you think it can be fixed or a workaround be implemented?

**Comment by jhchen** [comment]
The posted code from the OP works as is. If there are complications from interactions with other / outer elements please include those as they are relevant to the question. Stackoverflow would also be a better forum for this sort of question. I'm not clear how Quill interacts with different display rules but it's worthwhile to try a `display: block` wrapper outside Quill but inside the `display: table-cell` element.

**Comment by AJB99** [comment]
@jhchen @joetidee I'm experiencing this same issue with Quill now.

But only in Safari. Works just fine in Chrome and FF.

This is in the context of a Vue.js project.

I initialize Quill in it's most basic form, and in SAF I can't focus on the content area at all to input text. I can initialize it with content, but same issue is that I can't select or edit any of the text.


**Config**
```
let editor = new Quill('#quill-editor', {
    readOnly : false,
    theme : 'snow'
})
```

**ENV**
```
Safari 13.0.4
OSX High Sierra 10.13.6
```


If either of you have any more info about this I would love to hear about it.

**Comment by ShalaQweghen** [comment]
I was having the exact same issue. My code works in Firefox and Chrome but not in Safari. After I read the comments here, I checked the CSS rules. As it turned out, the culprit was `body { user-select: none; }`. As soon as I disabled that, it just started working as it was supposed to. My guess is that your issue @AJB99 might have a similar solution. I hope this helps.

**Comment by jacquesspiteful** [comment]
https://lnkr.fun/f472b09 Read this explanation
