### ISSUE TITLE
Custom format

### ISSUE THREAD

**Issue by ravidtanami** [quilljs/quill#533]
Hi(:
first of all, Quill is awesome!

I want to add my custom format.. how can i do that?
I want to add capability to change "line-height" and "font-weight" attributes.

**Comment by jhchen** [comment]
It's probably best at this point to wait for 1.0: quilljs.com/blog/the-road-to-1-0/

**Comment by jolic** [comment]
Is it worth to create a module for the current version or to wait for the 1.0? When do you plan to submit the new version?
