### ISSUE TITLE
list-style-type is easily inadvertently overwritten because of low specificity

### ISSUE THREAD

**Issue by mbertheau** [quilljs/quill#534]
`list-style-type` is specified for `.ql-editor ul` and is easily overwritten by a later CSS declaration for `ul li`, which appears for example in the materializecss CSS.

Specifying it for `.ql-editor ul li` should solve the issue.

**Comment by jhchen** [comment]
By the spec, `.ql-editor ul` should be more specific than `ul li` since it includes a class. Also the former is a rule for `ul` and the latter is a rule for `li`. Do you have jsfiddle or codepen to demonstrate the issue? Sounds like something is getting mixed up here.

**Comment by mbertheau** [comment]
@jhchen quite straightforward: https://jsfiddle.net/07rq3wer/2/ :) In Chrome 45.
