### ISSUE TITLE
Toolbar formatting should work on word cursor is on

### ISSUE THREAD

**Issue by subblue** [quilljs/quill#535]
It's tricky to describe exactly what I mean from the title, so here is an example:

Currently if the cursor is within a bold word then the bold button will be highlighted. 
If you clicked this button nothing happens though because there is no text selection.  

It would be a workflow improvement if instead the entire bolded area that the cursor was within was toggled to a non-bold state if there isn't already a text selection. This would be much easier than the fiddly process of trying to exactly select just the bold text before pressing the button to un-bold it.  
The same behaviour should work for the other block styling options too.

**Comment by jhchen** [comment]
It's not true that nothing happens--the next character you type will be unbolded. This behavior is consistent with Google Docs. If you prefer what Word does (which is what you describe), the toolbar handlers are customizable http://beta.quilljs.com/docs/modules/toolbar/
