### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by c0cky** [quilljs/quill#538]
After cloning the repo then `npm install` and `npm start` I receive 
```
ERROR in ./~/parchment/src/parchment.ts
Module build failed: TypeError: compiler.parseConfigFile is not a function
    at ensureTypeScriptInstance (/Users/camron/Desktop/quill/node_modules/ts-loader/index.js:147:38)
    at Object.loader (/Users/camron/Desktop/quill/node_modules/ts-loader/index.js:365:14)
 @ ./test/unit/selection.js 17:17-37
webpack: bundle is now VALID.
```

also when running `gulp build:release` I get the .min but it throws web pack error for missing parchment.

**Comment by jhchen** [comment]
The `develop` branch changes very often containing the latest development code and may not always be ready for public consumption. Use the `master` or any release tag for working checkpoints.
