### ISSUE TITLE
Extracting current style information

### ISSUE THREAD

**Issue by justbittin** [quilljs/quill#539]
I am sorry if this is the incorrect place for this... I could find no other place for questions.

I have custom buttons, outside the editor, which I manipulate the formats/etc.  I wish to 'highlight' the buttons when on etc, but am having trouble doing do.

I understand I must watch both selection and text changes, but how do I get which styles are active?  Which alignments?

Thank you kindly for your help.

**Comment by justbittin** [comment]
*watch

**Comment by jhchen** [comment]
For inline formats you can use [`getContents`](http://quilljs.com/docs/api/#quillprototypegetcontents) which returns a [Delta](http://quilljs.com/docs/deltas/) and check the attributes object. For line level formats the extra step is you have to find the newline character for the line the cursor is on. This is the basics of what Quill's own toolbar module does.
