### ISSUE TITLE
Text selection right to left (bug with span elements containing 1 character)

### ISSUE THREAD

**Issue by sloppy9** [quilljs/quill#542]
Hello, it's me again.. I've found another selection bug.

To demonstrate what I'm talking about, go to http://quilljs.com/ and highlight any character in the heading, change its size to something else. Move your cursor a few characters to the right of what you changed, then slowly drag a selection to left.. when you hit the character you changed the selection will clear.

From what I've observed, this only happens when making a selection from right to left and the `<span>` contains a single character.

**Comment by jhchen** [comment]
Interesting.. thanks for the report

**Comment by jhchen** [comment]
I tested this on the new [beta](https://beta.quilljs.com/) site by making the 'R' serif (which also caused the bug on quilljs.com), right arrowing 3 times and dragging left and the selection does not clear anymore.
