### ISSUE TITLE
Presing enter at the bottom of the editor will cause the whole page to scroll to top

### ISSUE THREAD

**Issue by Predjo** [quilljs/quill#544]
How to reproduce:

1. Go to demo page: http://quilljs.com/
2. Scroll the whole page a little
3. At the bottom of the editor add a few new lines by pressing enter
4. The whole page will scroll to top

Tested in Chrome

**Comment by johann-abraham** [comment]
+1

**Comment by duncanmeech** [comment]
caused by scrollIntoView being called. I had to fork and patch for the same reason. Not sure of correct fix yet.

**Comment by jhchen** [comment]
This has been fixed in the [beta](http://beta.quilljs.com/) release
