### ISSUE TITLE
Mouse text selection (Firefox)

### ISSUE THREAD

**Issue by kupec** [quilljs/quill#545]
Toolbar buttons don't work in Firefox when select multilne text by mouse.
Example of mouse selecting - https://gyazo.com/6025c17ab2034f93e860d8f26f337d90
Example of selecting by CTRL+A - https://gyazo.com/80ffce2c301b864c07cd7eb852f36cae

tested on *Firefox 42.0* on *quilljs.com*

**Comment by jhchen** [comment]
This looks like a manifestation of #541 actually. If you make the mulitline selection within the editor container it works as expected.
