### ISSUE TITLE
Quill prevents backspace keyboard events

### ISSUE THREAD

**Issue by kei-ito** [quilljs/quill#548]
Quill prevents backspace keydown events. It causes trouble when an user inputs non-alphabetical characters.

For example, the below is a typical flow of inputting 天麩羅 (tempura)

1. type t-e-n-p-u-r-a
2. pick 天麩羅 from the suggested words

Until 2, system buffers the typed characters. If backspace events are cancelled, it can't clear the buffer and users can't correct the word before picking.

Can you stop preventing backspace events?

![sample](https://s3-ap-northeast-1.amazonaws.com/kei-ito/tempura.gif)

**Comment by jhchen** [comment]
Overwriting backspace is necessary for other features to work. We'll come back to this when we do more on internationalizing Quill.
