### ISSUE TITLE
Applying multiple formats, only last format is applied

### ISSUE THREAD

**Issue by peterweck** [quilljs/quill#549]
In IE11 and Safari, if you select multiple formats before typing, only the last format that you select gets applied to the text that you type. It works correctly in Chrome and Firefox on both a Mac and Windows. Here's a test case:

http://jsfiddle.net/n4hLmjm1/3/

To reproduce, just click to a blank line and select a font, a size, bold, italics and a font color and then when you type, only the font color is applied. 

In stepping through the code, I see that the document.execCommand call (format.coffee:144) is successfully made each time a format is selected in the toolbar, but when you start to type, only the last format is applied to the text.

**Comment by jman123** [comment]
I'm seeing the same issue, which makes it frustrating to create a quill document in Safari and IE. Hope this bug can be fixed in the main quill branch. Thanks.

**Comment by jhchen** [comment]
Thanks for the report. The development branch is pretty deep into 1.0 so this will be included in Quill's next major release.

**Comment by jhchen** [comment]
This has been fixed in the [beta](http://beta.quilljs.com/) release
