### ISSUE TITLE
Quill.js on develop branch does not work???

### ISSUE THREAD

**Issue by jack-vo** [quilljs/quill#551]
Hi,
Your Quill.js is great. I really love it. I have forked the project 3 days ago and from what i observed, the `develop` branch does not seems to work as expected.
I checked out the branch 0.20.1 and it looked like you have been doing a major change to the main project by transforming from Coffee Script to ES6 and adding Parchment (which uses TypeScript) to the project.
I do believe it will be a good refactor (as I love ES6) but would you please let me know far is the `develop` branch behind the `0.20.1` branch? Am I missing any step in the build process? (At the moment, I always do `gulp build` and `gulp server` to test, I also had to update the ts-loader dependency to be able to compile parchment dependency)

I am looking forward for your reply.
Thanks

**Comment by jhchen** [comment]
The `develop` branch contains the latest code which may be in between working states. Only master and tagged versions are aimed to be in known working states.
