### ISSUE TITLE
Remove link from link-tooltip module does not work with quill.min.js only

### ISSUE THREAD

**Issue by devtimi** [quilljs/quill#559]
Trying to remove a link by clicking it and using the tooltip Remove button does not work, but only when using the quill.min.js provided.
The console reports this error:
```javascript
TypeError: null is not an object (evaluating 'a.isCollapsed') removeLink
```

Minified myself with Smaller.app and it works fine.

**Comment by jhchen** [comment]
This works for me on Mac + Chrome: https://jsfiddle.net/jhchen/spkcdh0c/1/. Are you doing something different or using a different platform?

**Comment by jhchen** [comment]
Closing from inactivity
