### ISSUE TITLE
Build for npm package?

### ISSUE THREAD

**Issue by tylercollier** [quilljs/quill#560]
I'd like to build as a npm package so I can make local modifications and try them out. Meaning, I want to be able to use a local package in npm. So in my project's `package.json`:

```
{
  "dependencies": {
    "quill": "file:../quill"
  }
}
```

The above uses npm's [local paths](https://docs.npmjs.com/files/package.json#local-paths) feature to reference "../quill". Assume that's where I've cloned this repo and run the build steps.

The trouble is, the `package.json` of quill lists the 'main' file as `dist/index.js`. But there is no such file, even after I run `gulp npm`. (The README says to run `gulp dist`, but that doesn't even create the `dist` directory.)

How do I build such that a proper npm package is created, specifically so that `dist/index.js` is created?

**Comment by jhchen** [comment]
Sorry the dist/index.js is incorrect and has been changed it should be a file called quill.js not index.js.

**Comment by tylercollier** [comment]
Thanks for that fix. However, there is a CSS problem. `dist/quill.snow.css` refers to non-existent assets:

```
.ql-snow.ql-toolbar .ql-format-button.ql-list,
.ql-snow.ql-toolbar .ql-picker.ql-list .ql-picker-label,
.ql-snow.ql-toolbar .ql-picker .ql-picker-label[data-value=list],
.ql-snow.ql-toolbar .ql-picker .ql-picker-item[data-value=list] {
  background-image: url("assets/list(arr).png");
}
```

It only does that, adds "(arr)", for 'list'. Can you fix that? It prevents my webpack from building.

**Comment by jhchen** [comment]
They exist: https://github.com/quilljs/quill/tree/develop/src/themes/snow/assets. Quill's build pipeline turns them into base64 images. If you want to do the building yourself, you will need to do this too.

**Comment by tylercollier** [comment]
The build output is wrong, at least for me. The problem might be stylus. It's something about the word list. Take a look at this. This input (that I stuck at the bottom of `toolbar.styl` for this test):

```
mylist = list
for myitem in mylist
  .my-style-{myitem}
    background-image: url('assets/' + myitem + '.png')
```

Gives this output:

```
.my-style-list {
  background-image: url("assets/list(arr).png");
}
```

Since it doesn't handle the word list properly, it's turning the background image url into "list(arr).png". Since that file doesn't exist, it can't base64 encode it.

**Comment by tylercollier** [comment]
I looked into this and it's because of the function definition of `list(arr)` in `base.styl`:

```
list(arr)
  unquote('list-' + join(' list-', arr))
```

Changing the name of that function to e.g. `makelist` should fix things up. I will submit a pull request.

**Comment by jhchen** [comment]
I just discovered this cause and made the fix as well: https://github.com/quilljs/quill/commit/d56ac7c6bae4149a29ab42b395a6d7c226a59547. The alternative solution would have been to quote to array elements so it does not try to refer to a variable by the same name. The commit does both.

**Comment by tylercollier** [comment]
Great, thanks!
