### ISSUE TITLE
Safari autocorrect behavior

### ISSUE THREAD

**Issue by quentez** [quilljs/quill#565]
The usual autocorrect behavior in Safari is to replace a misspelled word automatically the first time, and then leave it alone if you go back and revert the change.

With Quill, the behavior is different. Even after going back and reverting the autocorrected word, it will be autocorrected again and again, which can be pretty infuriating when trying to write words that don't exist in the dictionary.

I'm suspecting this may be because of how Quill regenerates parts of the DOM every time unlike a traditional contenteditable, which would prevent the browser from tracking what words were autocorrected already. But that's just me speculating.

**Comment by chinshr** [comment]
Can anyone reproduce this problem?

**Comment by jhchen** [comment]
I am able to reproduce this in desktop safari but not mobile. Specifically on the quilljs.com homepage:

1. Set the cursor on the line right above the "fast and lightweight" bullet
2. Type "fast and lighta"
3. Hit space and Safari will correct "lighta" to "lights"
4. Backspace twice and enter "a" and space again and Safari will continue to correct "lighta" into "lights"

The two workarounds right now are to either continue typing at least one non-whitespace character before correcting the spellchecked word or to disable to checker altogether by setting the spellcheck attribute to false in the Quill editor div.
