### ISSUE TITLE
Get origin content

### ISSUE THREAD

**Issue by inchr** [quilljs/quill#566]
It's possible get the original content(what I see like text in the editor...without divs and span) ? I want keep a copy of the origin text too(but of course, I need also the formatted text version)

Thanks(not sure if it's correct post this question here)

**Comment by willrowe** [comment]
I believe you can use the `getText` method, it should return just the text content and no formatting or HTML code.

**Comment by jhchen** [comment]
@willrowe is correct. If this does not answer your question please provide a sample desired output.
