### ISSUE TITLE
Default Font Size isn't being set

### ISSUE THREAD

**Issue by ablythe** [quilljs/quill#567]
When using the toolbar it appears that the default `font-size`( example: 'normal')  is not actually being applied to text unless the user explicitly selects that default option from the drop down menu before typing. 

This also occurs after hitting `enter` and moving to a new line in the text editor.  When a user has selected a non-default size such as 'large' that formatting will continue to be applied on the new line. This is not true when writing in the default size.

You can see this in the below screenshot from the Quill example page. The `this is normal' line was written by clicking in the editor and typing. For the second, I first selected a different size, and then selected 'normal' before typing which caused the inline styling to be applied.
<img width="917" alt="screen shot 2016-01-21 at 12 21 10 pm" src="https://cloud.githubusercontent.com/assets/6164745/12488899/c7b78dba-c03b-11e5-88cb-d59996adb4a1.png">

Example of the new line issue:

<img width="803" alt="screen shot 2016-01-21 at 12 42 23 pm" src="https://cloud.githubusercontent.com/assets/6164745/12489053/797c1ed0-c03c-11e5-9872-998490f878d3.png">

**Comment by jhchen** [comment]
The enter key not preserving the format is a known issue. Other than that it's not clear what the expected/correct output is? The markup on both screenshots look the same (span with font-size wrapping another span with author wrapping a text node).

**Comment by ablythe** [comment]
In the top screenshot, you can see that font-size is not actually being set on the `this is normal` line, it is missing the wrapping span completely.

``` 
   <div>
        <span class="author-galdriel">This is normal</span>
   </div>
```
vs.

``` 
   <div>
       <span style= "font-size: 13px">
           <span class="author-galdriel">This is normal</span>
       </span>
   </div>
```

It seems that expected behavior should be that when a user clicks into the editor and starts typing without first selecting a font-size it should set the font size to the value that has been set as default or `selected` on the toolbar.

**Comment by jhchen** [comment]
Unless it's causing functional issues I'm not understanding, including or not including a font-size: 13px is optional since the font-size of the container is 13px. It only matters when the size different from the default 13px.

**Comment by ablythe** [comment]
It is causing issues when the font size options are set up like below, where the default selected size `normal` is not equal to 13px. I can do a workaround solution and change the default font size for the container in CSS but that's not ideal, since if I change the size options later on I'd also have to remember to change it in the CSS. 


```
<select class="ql-size">
      <option value='13px' >Small</option>
      <option value='16px' selected>Normal</option>
      <option value='24px'>Large</option>
      <option value='48px'>Huge</option>
    </select>
```

**Comment by jhchen** [comment]
Makes sense. Something of interest in 1.0 might be its better support for using classes for formatting rather than style attributes. Then you can just specify the size in one place (the css file).

**Comment by ablythe** [comment]
The switch to classes should be a big help with this. Thanks for the quick responses and good luck with 1.0
