### ISSUE TITLE
adjoining spans removes space in-between words

### ISSUE THREAD

**Issue by shivanka-thunderbolt** [quilljs/quill#568]
when I wrap words with span to add style to words (selective words), editor removes space in-between words. it shows as one word. how can I preserve the space ? 

"quill.setHTML ( '<span>Hellow</span> <span>World</span>' )"

**Comment by Joeao** [comment]
In your particular example, using setText would be a better choice.

**Comment by unhammer** [comment]
But is there then a way to set a span using *text* indices, similar to what formatText does, but with a span with an arbitrary class?

**Comment by shivanka-thunderbolt** [comment]
it should be able to retain space '<span>'Hello'</span>' '<span>World</span>'

**Comment by shivanka-thunderbolt** [comment]
it should be like this.
![image](https://cloud.githubusercontent.com/assets/16871182/12549263/21206e14-c382-11e5-9a8e-fdb612063c84.png)

**Comment by jhchen** [comment]
If you must use HTML, then the solution is HTML:

```html
quill.setHTML('<span>Hello</span>&nbsp;<span>World</span>');
```

Note spans with no attributes will be removed anyways, but not tags the contribute formatting like `<b>` or `<span style="color: red;">`, as they change the content being represented. In general, Quill is built for editing content, not arbitrary HTML.
