### ISSUE TITLE
data-foo in custom formats?

### ISSUE THREAD

**Issue by unhammer** [quilljs/quill#569]
Is it possible to define more properties to go into custom formats? E.g. I could do

    quill.addFormat("error", { tag: "span", "class":"error-id-" }); 
    quill.formatText(5,10, "error", "0");

to mark that this error is error-id-0 and then afterwards process all spans and look for error-id-[0-9]+ classes, but ideally I would do something like

    quill.addFormat("error", { tag: "span", class:"error", data-error-id:"id", data-error-correction:"correction"  }); 
    quill.formatText(5,10, "error", {correction:"their", id:"3"} );

**Comment by jhchen** [comment]
Currently no. However, format customization is *the* thing that [1.0](http://quilljs.com/blog/the-road-to-1-0/) is aiming to solve.
