### ISSUE TITLE
two adjoining spans in quill editor removes the space in-between.

### ISSUE THREAD

**Issue by shivanka-thunderbolt** [quilljs/quill#570]
How do I preserve the space when wrapping two adjoining words with span tag

![image](https://cloud.githubusercontent.com/assets/16871182/12572688/6f044a86-c415-11e5-9c97-ab277f11fc31.png)

what u get is "HelloWorld!" instead of "Hello World!"

**Comment by jhchen** [comment]
Please don't intentionally make duplicate issues #568
