### ISSUE TITLE
Text replace shifts word indexes

### ISSUE THREAD

**Issue by shivanka-thunderbolt** [quilljs/quill#571]
when replacing the words in quill editor, content. it shifts indexes based on the text length of the new word. this effects when selecting rest of the words. would appreciate if there is a way to find the updated indexes.

**Comment by jhchen** [comment]
It's not entirely clear what is being asked here but it sounds like you can just listen on the [text-change](http://quilljs.com/docs/events/#text-change) event and then call [getSelection](http://quilljs.com/docs/api/#quillprototypegetselection) to see if anything changed.
