### ISSUE TITLE
add an id to a span though addFormat

### ISSUE THREAD

**Issue by shivanka-thunderbolt** [quilljs/quill#572]
I need to annotate few words in quill editor and im using "editor.addFormat('nlpFormatting', { tag: 'span', class: 'colorshw' });" to define a format

then .formatText(0,5, 'nlpFormatting', 1); to apply it to a word. my issue is, is there a way to give an ID attribute to the added span element to identify it uniquely ?

**Comment by jhchen** [comment]
Please post questions on StackOverflow and tag with Quill.
