### ISSUE TITLE
Adding custom select in current theme to toolbar, docs?

### ISSUE THREAD

**Issue by WriterStat** [quilljs/quill#573]
I need to add a custom select to the toolbar, using the current theme. Before I hack up the code. Is there a suggested/quick way to add this? So as to encapsulate from current code?

Prompts, pointers? Much Thx!

I see where I can add/expose currently programmed ones.  But not where we might add new ones.

**Comment by jhchen** [comment]
The best information for working with Quill can be found in its documentation site: http://quilljs.com/.

**Comment by WriterStat** [comment]
Granted. 

I know you guys are totally busy. But as a suggestion an encapsulated way to do this, conventions, or pointers to do this, docs, under your quick direction, would totally help other programmers, then help you with modules and additions.  Understand the code.  Such a small, quick thing would net you a huge benefit. Plugins etc...to the toolbar. Being able to expose their own functionality without ruining your code as well allowing them to update to new versions as they come out.  Without any large conversions.

Granted I can put in the html in my code. The quill.js code rewrites the selects in the toolbar to abide by the current style, etc...

Having a generic supported way to add things to the toolbar, that would then be handled by modules, would be a huge boon.  You are super close with what you have. As a thought for later on. There's my vote. =)

Thanks for the great software and the thoughts and listening.  Cheers,

**Comment by WriterStat** [comment]
I think I'm missing a user forum. =)
