### ISSUE TITLE
Multiple instances on the page

### ISSUE THREAD

**Issue by bribar** [quilljs/quill#575]
I was wondering if multiple editors can be initiated and used independent of each other? The examples mimic each other http://quilljs.com/examples/

**Comment by bribar** [comment]
My bad, found something on it

**Comment by loverdrive** [comment]
what have you found, for multiple (dynamic number) instance on the page?

**Comment by unixzilla** [comment]
How can i create multiple editors in one page?

**Comment by bhargav3** [comment]
@loverdrive you can do it simply by initiating quill multiple times on the same page. Just have to use different IDs for every editor.
