### ISSUE TITLE
toolbar picker inside doesn't understand or transfer html disabled option

### ISSUE THREAD

**Issue by WriterStat** [quilljs/quill#576]
Hi! Thanks for a great piece of software.

If you try and disable an option inside a picker on the Quill toolbar it ignores it.

How to disable one of the options inside a toolbar picker?

example: `<option disabled="disabled">`

Thanks

**Comment by jhchen** [comment]
The toolbar picker does not support this. If this is a use case you need, feel free to open another Issue as a feature request. The more complete and compelling the request, the more likely it will be implemented. Garnering community support will help as well!

**Comment by WriterStat** [comment]
Will do. Hoping quill.js will support the basic html attributes. =) Will help other creators/programmers want to more include it in their software.

Cheers,
