### ISSUE TITLE
Allow pass through of any html attributes not understood by Quill.js to final toolbar html code.

### ISSUE THREAD

**Issue by WriterStat** [quilljs/quill#577]
Hi! I think Quill.js will most likely be integrated into projects most often rather than being used stand alone.

Which means programmers will be adding things to the toolbar. Custom pickers. Parts of current pickers/toolbar dropdowns etc... 

To this end, it should probably support the basic html attributes like disabled etc...

See issue #576 

Example: Quill.js doesn't support basic html attributes in the toolbar like disabled.

`<option disabled>`

This will allow programmers to create custom toolbar items, pickers/dropdowns, general toolbar items etc... So as to extend the software with different modules etc...  And well it would then be html compliant.  And allow programmers to reference and use the current and future visual templates, without hacking the quill.js code base.

There are other extensions like this to help Quill grow, but this is a start.

Maybe pickers should also support separators for items. Or html `<optgroups >`

The less people hack in your code/stay in html, add modules to the system the better for you.

Although I'm not against hacking code where needed.

Note: Docs to creating your own toolbar items, picker modules/extensions, button modules/extensions might also be good for newbies. Thanks for listening.

I realize this is a larger scope, but aren't you going there?  End game?  Easier Software integration and adoption?

Cheers, and thanks for the great software and hard work.

**Comment by WriterStat** [comment]
Currently the quill.js toolbar is hard coded for actions in the js code. It strips the toolbar html and items etc... in it and rewrites them leaving any not understood html attributes out of the rewritten toolbar code, even if they are standard html or css.

The quill.js toolbar code should instead ignore any html attributes for the toolbar/toolbar css that it doesn't understand and pass them through to the final toolbar code.

**Comment by jhchen** [comment]
I think you are just talking about the dropdown picker and not the toolbar in general at this point. Native HTML `<select>` elements cannot be styled and behavior modified in ways many people would like so Quill's snow theme provides a custom picker that is inserted alongside `<select>` elements. It does not strip or rewrite the `<select>` element HTML.

The theme is provided as an option--you can certainly still use native `<select>` elements, as demonstrated by the top editor in http://quilljs.com/examples/, if the benefits of native `<select>` elements like disabled outweighs the benefits of the snow theme for your use case.

**Comment by WriterStat** [comment]
You asked me to make it a feature.  It is a bug.

Elements in the tool bar should pass through any html attributes they don't understand when they read in the tool bar for the theme.  Other wise you make people choose between something that doesn't have a theme, can't use one, or something where the picker that is crippled/strips out attributes to be able to use the theme.

The oblivious fix is, just pass through the html that the picker doesn't understand.  Then your themes work and the select/pickers work and as well the other toolbar elements.  Then people don't have to choose two bad devil choices.  And they can expand it.

**Comment by WriterStat** [comment]
Thanks again for the software. Again would just like to see a better version of the toolbar for the software. =)
