### ISSUE TITLE
iframe with height 100% does not honor parent's height on mobile safari

### ISSUE THREAD

**Issue by byronm** [quilljs/quill#58]
On mobile safari, instead of scrolling, the iframe's height just continues to grow. This leads to the contents of the document being obscured by the mobile keyboard.

Here is some starter code illustrating the issue, though when running in the ios simulator you'll need to add a legitimate reference to scribe.all.js (and also to the css, which codepen automatically handles).

http://codepen.io/anon/pen/chBEa

**Comment by benmcmaster** [comment]
@jhchen I am seeing the jump to the top of scroll frame after applying formatting in v0.20.1 in mobile safari on iOS 9. On a long document, the user loses scroll position of where the formatting is taking place. Is there a way to fix that?

**Comment by jhchen** [comment]
#532
