### ISSUE TITLE
General thought: monster branches & life

### ISSUE THREAD

**Issue by skakri** [quilljs/quill#580]
`develop` is currently 329 commits ahead of `master` and `master` hasn't been updated for ~ half a year. There are 2/4 pull requests failing and (if there'll be no improvements) I think that this slow pace will deter future contributors.

Maintainers -- is there a roadmap? Can we somehow help to speed up quill release cycle?

**Comment by jhchen** [comment]
The develop branch is being actively developed for 1.0, which is a big change. You can read about it here: http://quilljs.com/blog/the-road-to-1-0/.
