### ISSUE TITLE
This seems to be a pre-built javascript file

### ISSUE THREAD

**Issue by CosticaPuntaru** [quilljs/quill#582]
i want to reopen #397 issue,
i don't see why this issue is closed, as its not solved,
to solve this is simple:
ship to npm the compiled and pre compiled versions
/dist/*  compiled version
/lib/* pre compiled es5 version, (this way it dosen't brake if you have some funky config for the quill package)

package.json:
 "main": "./dist/quill.min.js",
"jsnext:main": "./lib/quill.js",

**Comment by jhchen** [comment]
Like it says in #397 Quill 1.0 will ship with the source code for others to build.

**Comment by CosticaPuntaru** [comment]
my suggestion was not to simply ship the source code, i was suggesting to ship a precompiled es5 version so when someone uses the lib he dose not need to care about any custom build of the quill package

**Comment by jhchen** [comment]
Then please read the original error message the OP was complaining about: "This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results."

**Comment by CosticaPuntaru** [comment]
if you import the es5 non minified version the warning will go away

**Comment by sesm** [comment]
@CosticaPuntaru you could try adding quill to module.noParse (https://webpack.github.io/docs/configuration.html#module-noparse)
