### ISSUE TITLE
Whitespaces between tags (Firefox, InternetExplorer)

### ISSUE THREAD

**Issue by ripper17** [quilljs/quill#585]
Note: This might be related to #149 , but that bug is a bit old and I'm not sure the code section that has been updated there is still in use or even relevant, so I'm opening a new ticket.

If you paste text into the quill editor with Firefox (44.0) or InternetExplorer 11 with spaces between tags, the spaces get striped.

**Steps to reproduce:**
1.) Clean Quill editor on demo page (not strictly necessary, just easier to see the result)
2.) Go to e.g. http://dle.rae.es/?id=JUyd9n4 or http://dict.leo.org/ende/index_de.html#/search=gehen
3.) Copy some text, in the first case e.g. "Extremidad u orilla de la vela", in the second case "to attend sth." with Firefox 44 or InternetExplorer 11
4.) Paste the copied text into the Quill editor

**Expected behaviour:**
The copied text should contain spaces

**Actual result:**
The copied text does **not** contain spaces

If you paste the text into a "normal" content-editable div, the spaces are preserved ( try it at https://jsfiddle.net/jd3rgr0g/2/ )

The HTML of RAE is basically `<mark>WORD</mark>SPACE<mark>WORD2</mark>` etc. 
(the SPACE is a normal (ASCII-Code: 32) whitespace)
The HTML of LEO is a href-tags with spaces in between.

Note: This works like expected in Opera 35, Chromium 48.
Note2: Pasting from RAE into LibreOffice doesn't work (probably because it doesn't know the mark-element), while pasting from LEO is OK
Note3: I'm not entirely sure this is a Quill-issue, could be a Firefox and IE issue as well?

I'm using latest Quill release (0.20.1)

**Comment by jhchen** [comment]
Thank you for the excellent bug report. I wish all reports were equally detailed.

I can confirm it's occurring in FF 44 and will assume it's probably the case in IE11 as well. I will have this fixed in 1.0.

**Comment by jhchen** [comment]
Can you see if whitespace preservation is still an issue on beta.quilljs.com? The links provided seems to have changed content and I'm not sure what to copy/paste to test

**Comment by ripper17** [comment]
Thank you for the update.

I can confirm it is working as expected in Firefox 46.0, InternetExplorer 11 on beta.quilljs.com
