### ISSUE TITLE
IE11: SVGAnimatedString

### ISSUE THREAD

**Issue by matikun86** [quilljs/quill#587]
This happens on Internet Explorer 11.0.9600.x
When creating `Quill`s instance I'm getting [this error](http://screencast.com/t/bqvBUyKw1s) in [this here](http://screencast.com/t/5UjHBkTkX2)

I think Quill expects `className` property to be a `String` but it is a `SVGAnimatedString`.

My toolbar html is as follows
```html
<div class="ql-format-group">
  <svg class="icon ql-format-button ql-bold">
    <use svg-id="doppler-icon-text_bold" xlink:href=""></use>
  </svg>
  <svg class="icon ql-format-button ql-italic">
    <use svg-id="doppler-icon-text_italic" xlink:href=""></use>
  </svg>
  <svg class="icon ql-format-button ql-underline">
    <use svg-id="doppler-icon-text_underlined" xlink:href=""></use>
  </svg>
</div>
```

**Comment by jhchen** [comment]
This has been fixed in the [beta](http://beta.quilljs.com/) release
