### ISSUE TITLE
Improperly nested ul/li throws exception

### ISSUE THREAD

**Issue by zacharytamas** [quilljs/quill#592]
On a project I'm working on when we load HTML generated by a previous editor in we have occasional cases where a nested list is marked up "the old way", like this:

```html
<ul>
    <li>My item</li>
    <ul>
        <li>Sub item 1</li>
    </ul>
</ul>
```

This style of nesting [used to be valid](https://www.w3.org/TR/html401/struct/lists.html#h-10.2) but in newer HTML you are to nest the `<ul>` inside a `<li>`. When quill encounters this, in at least Chrome, it throws an exception like #182 

**Would fixing the markup at runtime be too out of scope for Quill?** After all, we can't always control what old HTML may get loaded into Quill.

**Comment by jhchen** [comment]
It's possible to pass in a custom onConvert function into Quill's paste-manager to allow handling arbitrary, even invalid, input: https://github.com/quilljs/quill/pull/401.
