### ISSUE TITLE
Transpiling source to lib folder

### ISSUE THREAD

**Issue by garbles** [quilljs/quill#595]
Hi!

Webpack complains when I require quill because it points directly to the prebuilt web bundle file. Wondering whether you're open to moving all source files to `./src` and then creating a transpiled version in `./lib` (where the modules are still separate files). The main file would then point to `./lib/quill` or something. Would also make it easier to consume with Webpack or Browserify, where one could use `quill/core` and only include what they need.

If you're into it - or some variation - I will write the PR! Discuss? It looks like this request may change a bit with v1.0. LMK!

**Comment by garbles** [comment]
Also thanks for all of your work on maintaining this :tada:

**Comment by jhchen** [comment]
The source code will be included in npm packages in 1.0. #397

**Comment by garbles** [comment]
@jhchen great. thanks for the quick reply
