### ISSUE TITLE
Insert image on Chrome

### ISSUE THREAD

**Issue by redjab** [quilljs/quill#597]
Have this issue on the latest stable version of Chrome (48.0.2564.116). You can test this on the demo page. When you try to insert an image anywhere on the editor, the cursor runs to a different location (most usually the end of the very first line), and the image is inserted there instead of the desired location.

Works fine on Firefox.

**Comment by jhchen** [comment]
Not able to reproduce on a Mac. Are you using Windows or Linux?
![quill](https://cloud.githubusercontent.com/assets/192974/13410754/3e680f40-deee-11e5-8133-05b20698ec04.gif)

**Comment by jocoolie** [comment]
Not Ubuntu - working correctly in Chrome Version 48.0.2564.116 (64-bit)

**Comment by redjab** [comment]
This is on Windows 8.1 64-bit.

**Comment by Joeao** [comment]
Is it possible that you were experiencing #487? Caused by moving the mouse whilst clicking the toolbar.

**Comment by redjab** [comment]
@Joeao You know what that's very likely. I just tried reproducing issue #487 and it seems to match what I were experiencing when inserting image.

**Comment by redjab** [comment]
For anyone interested, I found out the root of the problem.
This problem only happens when Reddit Enhancement Suite (RES) extension is running. 
It doesn't happen when I disable RES, or when I don't have a Reddit tab open.
