### ISSUE TITLE
Determine cursor direction when selecting

### ISSUE THREAD

**Issue by mmacfadden** [quilljs/quill#600]
Right now the selection-change event returns a range {start: x, end: y}.  Regardless of the direction of the selection, the start property is alway less that then end property.  This is because the getRange() method executes the following code:

```JavaScript
return new Range(Math.min(start, end), Math.max(start, end));
```

When selecting a range of text the cursor is actually at one end of the selection range or the other, depending on the direction of the drag.  However, right now there is no way to tell the direction of the selection.  In more general terms, selections are often describe in terms of the anchor (where the user started dragging) and the focus / cursor (where the users stopped dragging).  Right now you can get the range but have no way of telling which is the anchor and which is the focus.  This is often important information.

There may very well be something I am missing or an easy workaround, but I have not found one yet.

**Steps for Reproduction**

1. Add a selection-changed listener
2. inspect the range that is emitted

**Expected behavior**:
Would like to be able to tell where the cursor is.

**Actual behavior**:
Can not seem to determine where the cursor is.

**Platforms**: 
N/A

**Version**:
0.21.1

**Comment by jhchen** [comment]
If you personally have a real use case that is being limited by this lack of information please provide that. In the meantime this is a known accepted limitation.

**Comment by mmacfadden** [comment]
Hi.  Thanks for the good work on this project.  I have two questions.

 1. Is there some bug or feature request that discusses this?  I searched the open and closed issue for "cursor" before submitting this, and didn't see anything. I try not to submit things that have already been discussed.  If I missed it, apologies. If you could direct me there to read up on the decision that would be great.

 2. Is this something you would accept a simple pull request for that maintains backwards compatibility? This seems like something I could implement / test fairly easily.

3. As for the use case.  I am creating a new module for Quill (that I would be happy to contribute back , assuming I get it to work well enough) that is much like the multi-cursor module, but for selection.  In other words it shows multiple selection.  If a user is dragging the mouse to select, I would like to capture the selection range, and the location of the cursor, so that in the other editor I can render the selection and cursor position as it is occurring.  When drag selecting, on point of the selection is stationary (the anchor) and the other point moves (the focus).  I want to make sure the cursor is rendered at the focus so it moves around with the change in selection.  Essentially, I am re-injecting the cursor position using the multi-cursor and the selection with my new module.  Unfortunately, I can't capture both the cursor and the selection at the same time.

Again, I would be happy to contribute a PR for both the requested functionality, as well as the new module I am making if it makes sense.

**Comment by jhchen** [comment]
Thank you for the background details. Quill obviously made a choice in not supporting selection direction so data, often in the form of real use cases, is helpful to challenge that choice, rather than "This is often important information." The reasoning behind Quill's choice is simplicity. No end user has to check if `start <= end` and there's always never a difference in expected behavior and so the user is freed from that consideration.

The main cost is not implementation but maintenance and complexity. I'll reopen this as a feature request for further discussion but for now the workaround is probably when you do get a selection update event, use the DOM APIs to determine if it's forwards or backwards.

**Comment by mmacfadden** [comment]
Thanks.  How about I play around with a couple work arounds.  I may try the dom api, as you suggest, or try adding something simple to Quill in a fork.  Worst case, if I find a good workaround, I could post in here for other people to reference.  Best case, I come up with something simple in Quill that is worth a PR.

**Comment by felipeochoa** [comment]
@jhchen I've hit this problem and have another use-case. I'm using Quill as one input of several in a table. I'd like to bind the arrow keys to navigate across inputs, but without knowing which way the selection is pointing, I can't do that. E.g, if you're in cell (2,2) with selection `{index: 0, length: 2}` and hit `ArrowLeft`, do you jump to cell (2, 1)? Obviously this is not the full solution to using tables in Quill (e.g., I don't handle multi-cell selection), but I think it's an important first step.

Would it really add that much complexity to have a 'direction' prop on `Selection`?
