### ISSUE TITLE
IE 11 - Focus problem when link modal is shown

### ISSUE THREAD

**Issue by DerBrinkmann** [quilljs/quill#602]
IE 11.0.9600.18204
Win 7

Reproducable on http://quilljs.com/
clicking on any of the links (so that the linktool is shown) causes the loss of focus,
keyboard input like arrow keys result in scrolling of the editor element, 
instead of the movement of the caret.

**Comment by jhchen** [comment]
This has been fixed in the [beta](http://beta.quilljs.com/) release
