### ISSUE TITLE
Improve docs for formats

### ISSUE THREAD

**Issue by garygreen** [quilljs/quill#603]
I'm attempting to add a format to support `<h1>`, `<h2>` etc however the only thing that I can find is [addFormat](http://quilljs.com/docs/api/#quillprototypeaddformat) function which links to a [format page](http://quilljs.com/docs/formats/) but doesn't actually help. I've checked thru the code and it isn't too obvious how to actually go about this.

So far I have in my toolbar:

```html
<span class="ql-format-group">
    <select title="Style" class="ql-style">
        <option value="p">Normal Paragraph</option>
        <option value="h1">Heading 1</option>
        <option value="h2">Heading 2</option>
        <option value="h3">Heading 3</option>
        <option value="h4">Heading 4</option>
        <option value="h5">Heading 5</option>
        <option value="h5">Heading 6</option>
    </select>
</span>
```

Then this is were I'm stuck (took a bit of a logical guess)... so far I have:

```js
editor.addFormat('style', {
	prepare: function(value) {
		return {
			tag: value
		}
	}
});
```

Obviously doesn't work. This isn't so much a support issue (although help would be nice) but a suggestion to improve the docs.

**Comment by jhchen** [comment]
`addFormat` was implemented for internal use and for some reason I was convinced to expose it. It works for a narrow set of cases (all of the ones internal needs require). Quill 1.0's new document model is a much more thought out way to add new formats so I would invest in building on top of that soon instead.
