### ISSUE TITLE
conflicts between more than one editor in one page

### ISSUE THREAD

**Issue by BorelTung** [quilljs/quill#604]
There are conflicts between two editors in one page.

**Steps for Reproduction**

1. Visit the [Demo](https://quilljs.com/examples/) page.
2. Edit text in one editor.

**Expected behavior**: We expect two editors be controlled by two toolbars separately.

**Actual behavior**: In fact , two editors seems to share the same controller. Changes in one editor repeat in the another one.

**Platforms**: [Chrome 49 on Window 10]

**Version**: [Version 0.20.1]

**Comment by willrowe** [comment]
The demo page demonstrates the use of a couple of modules that allow editing by multiple authors simultaneously like in Google Docs.
