### ISSUE TITLE
Can we create an inline toolbar?

### ISSUE THREAD

**Issue by hiddenl00p** [quilljs/quill#605]
Something similar to https://www.froala.com/wysiwyg-editor#inline-demo

**Comment by jocoolie** [comment]
See the discussion of "air-bar" over here: https://github.com/quilljs/quill/issues/382. I believe this is close to what you're looking for.

As far as the inline editor goes, airbar + some styling on the container and maybe multiple containers (for columns) should pretty well emulate most of what froala does.
