### ISSUE TITLE
Underline misses out on highlight colors

### ISSUE THREAD

**Issue by nigel-sirisomphone** [quilljs/quill#610]
Unless the highlight color is selected before the underline, the actual line remains the body color, and doesn't receive the highlight color.

**Steps for Reproduction**

1. Visit quilljs.com and use the demo editor
2. Drag and select a section of text
3. Press underline
4. Select a highlight color

**Expected behavior**: Underline should receive the highlight color

**Actual behavior**: Underline remains the color of the body text.

**Platforms**: All browsers. Tested on OS X.

**Version**: Latest

**Comment by core433** [comment]
+1.

I use strikethroughs with gray font color, and whether the strikethrough is black or gray is order-dependent.  I'd like it to always be a gray strikethrough, but it's black if I strikethrough before I apply gray font color.

Perhaps non-span-style tags like <s> should always be placed within adjacent style span tags.

**Comment by jhchen** [comment]
This has been fixed in the [beta](http://beta.quilljs.com/) release
