### ISSUE TITLE
Correctly loading quill

### ISSUE THREAD

**Issue by Charuru** [quilljs/quill#611]
I'm including quill by loading:

`<script src="//cdn.quilljs.com/0.20.1/quill.js"></script>
`

as documented in the quickstart. However that's including tons of things I don't want such as the theme and the dependencies like lodash (I already have lodash!). 

How do I include quill correctly? Or how do I include quill without lodash and the theme?

**Comment by jhchen** [comment]
This is the correct way to include the standard build of Quill that the CDN serves. It includes a custom build of lodash (just the parts Quill uses). Feel free to make a custom build of Quill if this is not to your liking.
