### ISSUE TITLE
How to test the develop branch?

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#616]
I'm trying to follow the local-development section
https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#local-development

It says to call npm link quill-docs. Do I need to node-moduels/quill-docs and call 'npm link' first to create a golbal refrence?
Inside quill-docs/docs/standalone I only see *.md files. How can I compile them?

localhost:9000/standalone/snow gives me
Error: connect ECONNREFUSED 127.0.0.1:4000

Thanks

**Comment by jhchen** [comment]
It is a suggestion, not a requirement to use `npm link` for development. The markdown files are compiled and served by jekyll so if you are getting a connection error, make sure jekyll is running? Also make sure you have ruby, rubygems, node, and npm installed and these commands ran successfully:

    npm install
    gem install foreman jekyll kramdown rouge jekyll-sitemap jekyll-redirect-from jekyll-feed
    npm run build

I also tweak the [docs](https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md) just now to make things more clear.
