### ISSUE TITLE
How do I retrieve multiline strings from quill editor?

### ISSUE THREAD

**Issue by jdmswong** [quilljs/quill#621]
I haven't been able to find this answer anywhere, what jQuery query do I use to retrieve all lines?

```$('.ql-editor > div').html()``` only grabs the first one

Thanks!

**Comment by jhchen** [comment]
Try [getText()](http://quilljs.com/docs/api/#quillprototypegettext).

**Comment by jdmswong** [comment]
`VM421:2 Uncaught TypeError: $(...).getText is not a function(…)`
