### ISSUE TITLE
Quill stopPropagation of keyup and keydown events (Version 0.20)

### ISSUE THREAD

**Issue by Vadorequest** [quilljs/quill#624]
Hi.

I want to implement my own undo/redo. I have disabled the `undo-manager`. But my `keyup` and `keydown` events aren't fired when I hit specific keys like `ctrl+z` and `ctrl+y`.

I found the root of the issue, in quill.js:8091

```
  Wrapper.prototype.on = function(eventName, listener) {
    this.node.addEventListener(eventName, (function(_this) {
      return function(event) {
        var arg, propagate;
        arg = lastKeyEvent && (eventName === 'keydown' || eventName === 'keyup') ? lastKeyEvent : event;
        propagate = listener.call(_this.node, arg);
        if (!propagate) {
          event.preventDefault();
          event.stopPropagation();
        }
        return propagate;
      };
    })(this));
    return this;
  };
```

I wonder if I can safely comment the `event.stopPropagation();` line. What would be the side effects?
If I comment it, my events are correctly propagated to the highers components and I didn't see any wrong side effect so far.

I see that in next version this line has disappeared (but I'm using the 0.20 version which has been customized for our specific use and I can upgrade yet).

Thanks.

**Comment by jhchen** [comment]
I don't ascribe a high probability to it being safe to remove that line. It's not clear the undo-manager is properly disabled or replaced. That if branch is entered only when a handler returns `false` so somewhere in the code, something is still listening on ctrl-z and returning false. The only place to my memory is the default UndoManager but either way stopping the source is a safer route.
