### ISSUE TITLE
Initial rendering of long document performance

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#627]
I'm experiencing fairly sluggish performance on Quill v0.20.1 when loading a long document. The issue seems to be specifically with Quill's rendering time after calling editor.setContents(delta) as the delta is retrieved from the server pretty quickly.

A few specific examples:
- A document with **93K characters** but no formatting. Loaded into Quill.setContents as a single insert operation (ie. {'insert': '<93K characters>'}). **700ms** elapsed time before editor.setContents(delta) returns. However, Chrome browser spends another 3s on layout phase, causing an even more significant delay before user actually sees document contents.
- It takes **600ms** to render a **500 line** document, each line 7 characters long with simple bold formatting (Fiddle: https://jsfiddle.net/battuashwik/1gds5ym9/)

Do you anticipate improved rendering performance for long documents in Quill 1.0?

Are their techniques for improving performance of initial load? (This is painful, but maybe I chop up the deltas before handing them to the editor so that initial load (of say a page worth of deltas) loads quickly and then i do updateContents with additional deltas...)

**Steps for Reproduction**
1. Copy/paste large document into quill editor
2. (Have back-end save document)
3. Re-load document

**Expected behavior**: Expect the document to load quickly

**Actual behavior**: Document loads fairly slowly. Issue is not retrieving the document from the server. But specifically the rendering time for the document after editor.setContents(delta) is called.

**Platforms**: Chrome 49 on Mac 10.11.3

**Version**: Quil v0.20.1

**Comment by battuashwik** [comment]
How are u calling editor.setContents. I mean if you are just getting deltas from server and directly iterating and calling editor.setContents on each delta, you will see a sluggish performance.

**Comment by battuashwik** [comment]
The rendering is a problem if you give editor.setContents directly an array of operations. The following fiddle will demonstrate the speed of the setContents for large operations (500 operations takes around 3 seconds and 1000 operations take around 10 seconds).
https://jsfiddle.net/battuashwik/ykcLmLjy/

The solution to this is compose the deltas into one either on the client side before applying or server side before storing. The following fiddle demonstrates the performance with composed operations which takes 20 milliseconds to set. 
https://jsfiddle.net/battuashwik/hf047xo7/

Quill uses rich-text (https://github.com/ottypes/rich-text) for deltas but unfortunately doesn't expose the Delta module. I exported a browserified version of this to use in the fiddle. Feel free to clone and use it.

**Comment by sachinrekhi** [comment]
Oh wow, that is a very impressive performance difference between your two Fiddle examples! Thanks for sharing.

So I originally got the list of ops that I'm storing in my back-end from editor.getContents(). I would have assumed that was already giving me back a composed list of operations that was already as minimal as can be? Is that not the case? It sounds like you are suggesting it's not the case if you are composing before storing in your database and seeing a difference in the generated operations pre/post composing in what's actually stored?

**Comment by sachinrekhi** [comment]
OK, so I took at look at the specific ops that are performing slowly. I've confirmed that the output from editor.getContents() is in fact 1 single insert operation that is 93K characters long. So it's not an issue of too many operations. And so in this case I don't think that compose() would help in that it would not transform the ops in any way.

Should I just be expecting than that a file with 93K characters is just going to be this slow? The surprising thing is I timed it the same way you did with a timestamp before and after the setContents call. And it returns about 700ms, which isn't too bad. But the console log output of the timer is displayed well before the actual contents of the editor show up in the browser. I then tried loading the same document in Quill in Safari and Firefox and it loads way faster than compared to Chrome. So maybe I'm actually running into rendering performance issues in the browser, ie. Chrome specifically? Maybe it's because Quill renders it as a single 93K character div with newlines as opposed to paragraph tags?

**Comment by battuashwik** [comment]
It is not exactly a single operation as new line is treated as a new operation and i see the problem in your case. Just updated the fiddle to demonstrate your exact case which takes around 600 ms which is a lot.
https://jsfiddle.net/battuashwik/1gds5ym9/ . To verify this you can print the result from editor.getContents and check the ops array. You will see a series of operations rather than one.

One alternative solution i can think of is doing lazy loading of operations. I updated the second fiddle https://jsfiddle.net/battuashwik/hf047xo7/ to demonstrate that. This way atleast the browser will not freeze and hence better UI experience.

**Comment by jhchen** [comment]
Can we update the original issue with specific numbers?

**Comment by jhchen** [comment]
There's been steady performance improvements with the betas.

1. Calling updateContents with an array versus a proper Delta should show no longer show a discernible difference.
2. This may have been originally conflated with the previous issue but Quill should scale extremely well with number of characters. Number of operations is the more limiting factor. For example loading a 130,000 character plaintext only takes ~30ms: http://jsfiddle.net/gh7mns5n/3/
3. The same performance on the 500 line file, which is 1000 operations, loads 2-3 times faster now. I'm getting 150-250ms on my Macbook, previous it was around 600 like @sachinrekhi reported.

Most human written documents do not have alternating formats per word though so the worst case performance illustrated by point 3 should not be encountered often. The >5 minute article reads on my Medium dashboard right now have around 100 operations. Thoughts?

**Comment by jhchen** [comment]
Since no one has had any additional thoughts for several months I will close this assuming the initial load performance is satisfactory. Feel free to comment with data points.

**Comment by Aaronik** [comment]
I have a setup with many operations -- I have a 27k character interview and have my delta set up to be ~5000 operations. This is a lot, I know. And the performance is very slow -- on a slower machine, I have `.setContents(delta)` on chrome taking about a minute (faster machine it taking about 5 seconds, and these are the extremes), and on Firefox essentially never loading (taking up to 20 minutes) and on my fast machine ~1 minute. Clearly this is untenable. I did find a nifty trick to speed the heck out of Firefox though. Basically you just unmount the quill node, set your contents, then mount it again. This makes no difference in chrome, but in Firefox it speeds it up by over 40x! The same 20 minute task on the slow firefox machine now takes 15 seconds! I have the solution written out in a little more depth here: https://github.com/quilljs/quill/issues/1130.

**Comment by BitPhinix** [comment]
I'm also experiencing this issue. It would be nice if there would be a way to load a delta without blocking the dom. Loading https://pastebin.com/zdRuFrVQ takes 2-3 seconds while blocking the dom which is an absolute killer for the user experience.
