### ISSUE TITLE
How can I remove the <div class="ql-tooltip ql-link-tooltip"> from HTML so I can directly display my saved HTML?

### ISSUE THREAD

**Issue by hiddenl00p** [quilljs/quill#628]
How can I remove the `<div class="ql-tooltip ql-link-tooltip">` from the getHTML() so I can directly display my saved HTML? in my comments section. Is there a way I can filter it out so only anchor link shows, not the tool tip?

`<div class="ql-tooltip ql-link-tooltip"><span class="title">Visit URL:&nbsp;</span>`

**Comment by jhchen** [comment]
Quill's `getHTML()` does not include modules' containers so it should not be showing up. Can you post a code snippet?

**Comment by hiddenl00p** [comment]
Thanks, found the issue in how I am initializing Quill on multiple pages.

**Comment by Jaydeepsolanki7** [comment]
### The link tooltip cut off by edge of the React quill editor
Conditionally handle: If the link is -negative on the left than replace it with 10px else default position.

`useEffect(() => {
	const adjustTooltipPosition = () => {
		const tooltip = document.querySelector('.ql-tooltip');
		if (tooltip) {
			const left = parseFloat(tooltip.style.left) || 0;
			if (left < 0) {
				tooltip.style.left = '10px';
			}
		}
	};

	const observer = new MutationObserver(adjustTooltipPosition);
	const editorContainer = document.querySelector('.ql-container');

	if (editorContainer) {
		observer.observe(editorContainer, {
			childList: true,
			subtree: true,
			attributes: true,
		});
	}

	return () => {
		observer.disconnect();
	};
}, [editorRef, handleBodyUpdate]);`


After

<img width="1085" alt="Image" src="https://github.com/user-attachments/assets/c6ee28fd-a6a5-4102-83f6-c9c93f04b0bc" />
