### ISSUE TITLE
Consider using Object.assign instead of node-extend

### ISSUE THREAD

**Issue by ericeslinger** [quilljs/quill#629]
I would like to be able to do this:
```
  this.quill = new Quill('#editor-container', {
    theme: 'snow',
    modules: {
      'image-tooltip': true,
      toolbar: {
        container: [
          ['image'],
        ],
      },
    },
```

**Expected behavior**: 
I would expect the toolbar to have just one button, the image button.

**Actual behavior**:
The image button replaces the font-size selector in the default toolbar, but all the other default toolbar buttons are present.

This is because `node-extend` recursively merges arrays (because it treats array properties as named properties, I believe). So 

        options = extend(true, {}, Quill.DEFAULTS, themeClass.DEFAULTS, options);

at https://github.com/quilljs/quill/blob/develop/core/quill.js#L52 ends up with the resultant toolbar module definition looking like:

````
options: {
  modules: {
    toolbar: {
      container: [
        ['image'],
        ['bold', 'italic', 'underline', 'link'],
        [{ list: 'ordered' }, { list: 'bullet' }],
        ['clean']
      ]
    }
  }
}
````

instead of the expected `container: [ ['image'] ]`

I kludged this in my own development environment, and I'm not 100% certain that Object.assign really does what you want for the rest of the quill creation cycle, but it seems like as-written it's not really easy to really override the toolbar.

**Version**:
current development branch

**Comment by jhchen** [comment]
Deep merging is desired in general so Object.assign will not work for to same purpose. This interaction with the toolbar is a problem though.
