### ISSUE TITLE
Have to click tab 4 times before moving onto the next input field 

### ISSUE THREAD

**Issue by macleodsawyer** [quilljs/quill#632]
Exactly as the title states, I have to click tab exactly four times before moving onto the next visible input field. I have disabled indenting. 

**Expected behavior**: When you click TAB once, you get sent to the next input field. 

**Actual behavior**: On first tab does nothing, only moves to nesxt field on the fourth "tab".

**Comment by jhchen** [comment]
What is the next input field and what input field are you currently on?

**Comment by macleodsawyer** [comment]
When you are inside the editor and click the tab key,  it should take you
out of the editor into the very next input field in the page

Instead it only takes you to the input field after you click the tab key
four times. I have already disabled indentation.
