### ISSUE TITLE
Text-only content breaks the editing behavior in 1.0

### ISSUE THREAD

**Issue by benedikt** [quilljs/quill#638]
Editing behavior is broken when the `.ql-editor` element has text content _not_ nested in other html tags.  This wasn't a problem until a few days ago. I suspect that it might be related to the changes introduced in c163ac4. 

**Steps for Reproduction**

1. Visit the local development sandbox: http://localhost:9000/standalone/snow/
2. Insert content via the DOM: `var editor = document.querySelector('.ql-editor'); editor.classList.remove('ql-empty'); editor.innerHTML = "Hello World";`
3. Try deleting and/or editing the text via the editor.

**Expected behavior**: It should allow editing the text just like it would with `<p>Hello World</p>` as innerHTML

**Actual behavior**:  Backspace works but doesn't remove the last character. Backspace on selected text (CTRL+A) doesn't work at all. Inserting new text somewhat works but has some glitches. See http://recordit.co/w5JKjzF7M3 for a short screencast. 

**Platforms**: Tested it on Safari 9.1 and Chrome 50.0.2661.94 on Mac and it doesn't seem to be a browser specific issue.

**Version**: f4054bd (1.0 branch)

If this is related to the way I'm setting the editor contents from the outside, please let me now. I just figured that this was the way to go since `setHTML` isn't there anymore. 

Please also let me know if there's anything I can help you with to fix this. I'd open a pull request, but right now I'm not able to figure out why this is happening. I'd appreciate some pointers 😃

Thanks a lot for your work on Quill. It's a great WYSIWYG editor and I'm already looking forward to the 1.0 release.

**Comment by jhchen** [comment]
Quill cannot allow arbitrary edits to its DOM so setHTML is being removed. I have [added](https://github.com/quilljs/quill/commit/3a3e2eed81a77229c1fbea81e7553809bbc0937e) a pasteHTML to the 1.0 branch, which will be the closest thing you will be able to do to safely make edits with HTML.

I would also encourage taking a look at [Deltas](http://quilljs.com/docs/deltas/) and updateContents/setContents as they can be a much easier way to deal with rich text content in many use cases.
