### ISSUE TITLE
Insignificant whitespace is rendered in 1.0

### ISSUE THREAD

**Issue by benedikt** [quilljs/quill#639]
When the content in the `.ql-editor` element has insignificant whitespace (like indentation) it is rendered in the editor.

**Steps for Reproduction**

1. Visit the local development sandbox: http://localhost:9000/standalone/snow/
2. Insert content via the DOM: `var editor = document.querySelector('.ql-editor'); editor.classList.remove('ql-empty'); editor.innerHTML = "<ul>\n  <li>Hello World</li>\n  <li>Foo Bar</li>\n</ul>";`

**Expected behavior**: It should be rendered like it would outside of the editor.

![2016-04-29 at 11 44](https://cloud.githubusercontent.com/assets/9696/14912946/cf4052bc-0dff-11e6-8afd-5dcd8198da47.png)

**Actual behavior**: The insignificant whitespace between the tags is rendered. 

![2016-04-29 at 11 39](https://cloud.githubusercontent.com/assets/9696/14912910/a3aa6570-0dff-11e6-8bfd-9bb2fb183831.png)

**Platforms**: Tested it on Safari 9.1 and Chrome 50.0.2661.94 on Mac and it doesn't seem to be a browser specific issue.

**Version**: f4054bd (1.0 branch)

As mentioned in #638, please let me know if there is anything I can do to help with this issue.

**Comment by jhchen** [comment]
Similar issue and solution as https://github.com/quilljs/quill/issues/638#issuecomment-216000101
