### ISSUE TITLE
Allow disabling paste-manager module

### ISSUE THREAD

**Issue by Katona** [quilljs/quill#641]
In certain cases (no too frequently, I admit) it is useful to be able to disable the paste-manager module. However, it is not possible as of now, because the default modules list always get added to the list of modules.

This is what I tried:
```

var editorConfig = {
    readOnly: false,
    modules: {
         'keyboard': true,
         'undo-manager': true
    }
};

// ...
var textEditor = new Quill(domNode, editorConfig);
```

Actually, I think none of the default modules can be disabled at the moment.

**Version**: 0.20.0

**Comment by jhchen** [comment]
The default modules are required for Quill to work properly. What is the specific use case for disabling the paste manager?

**Comment by Katona** [comment]
Without going into the details, we would like to handle the paste our own before it gets to Quill, because we are applying some preformatting on the pasted text.

**Comment by jhchen** [comment]
You can pass in an onConvert option to the existing paste manager with something like this:

```js
var quill = new Quill('#editor', {
  modules: {
    'paste-manager': {
      onConvert: function(container) {
        // interpret the pasted content and return a Delta
      }
    }
  }
};
```

Quill still handles the mechanics for intercepting a paste event and putting it into an isolated container but you'll have to do all the interpretation on the content.

1.0 has an [API](http://beta.quilljs.com/docs/modules/clipboard/) for partial customization of paste interpretation and is better for most use cases.
