### ISSUE TITLE
wrapper.appendChild is not a function when clicking on the fx button

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#647]
[Describe the issue]
When clicking on the fx button I'm getting an error in the console:
```
quill.js:855 Uncaught TypeError: wrapper.appendChild is not a function
```
**Steps for Reproduction**

1. Visit http://beta.quilljs.com/
2. Focus the editor
3. Click on the f<sub>x</sub> toolbar button
See the error in the console

**Platforms**: [ex. Chrome 48 on Mac 10.11]
Chrome 50.0.2661.94 m on Windows 7

**Version**: [version]
Beta 0

**Comment by jhchen** [comment]
Combining with #648
