### ISSUE TITLE
Equation

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#648]
[Describe the issue]
There are several issues with equations:

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/
2. Clicking on the equation in Chrome doesn't place the cursor.
3. Clicking on the right side of the equation in Chrome places the cursor on the left border of the line instead of at the end of the equation.
4. Clicking on the equation in Firefox selects the equation instead of placing the cursor.
5. Clicking enter when the cursor is at the end of the equation adds a new line above the equation instead of under it.
6. The f<sub>x</sub> button has no effect and it's not clear how to edit the equation.

**Platforms**: [ex. Chrome 48 on Mac 10.11]
Chrome 50 on Windows 7.
Firefox 46 on Windows 7.

**Version**: [version]
1.0-Beta.0

**Comment by jhchen** [comment]
The UI / handler for formulas and video is not finished so I removed it from the beta site for now but both will be supported by the official release.

**Comment by jhchen** [comment]
The latest 1.0.0-beta.9 now has UI for inserting formulas
