### ISSUE TITLE
Preformat only works for 1 character in ie8

### ISSUE THREAD

**Issue by jhchen** [quilljs/quill#65]
On an empty document:
1. Control + B to set format to bold
2. Type "test"

Only the "t" will be bolded in ie8. Same behavior for italics.

Cause is ie8 uses `<strong>` to set formatting to bold so on the first letter the markup is `<strong>t</strong>|` where | is our cursor. However we change the strong to a b and it resets the preformatting. Commenting out the call to normalizeLine in line.rebuild() demonstrates this. Does not occur in newer versions of IE.

**Comment by radiart** [comment]
The issue still exist on IE 10 and 11 on Windows 7.

Try to remove content, select Bold and write someting on IE:  https://jsfiddle.net/mb4cz9tL/

**Comment by radiart** [comment]
@jhchen Is there chance that you fix this in nearest future?

**Comment by jhchen** [comment]
This will be fixed in 1.0 as the approach used for preformatting is being changed. IE10 support is being dropped though too.
