### ISSUE TITLE
Button tooltips in the demo

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#650]
It'll be nice to have tooltips for the buttons in the new demos.

http://quilljs.com/
http://beta.quilljs.com/docs/formats/
http://beta.quilljs.com/docs/themes/snow/

**Version**: [version]
1.0-Beta.0

**Comment by alexkrolick** [comment]
Even having title tags to get a label on hover would help quite a bit

**Comment by alexkrolick** [comment]
Actually, it would be pretty nice to have this at v1.0. Some of our users could use a hint as to what the different toolbar items actually do - see GH toolbar:

![screen shot 2016-08-22 at 12 19 32 pm](https://cloud.githubusercontent.com/assets/1571667/17868208/bc512416-6862-11e6-9627-27ced56e1654.png)

**Comment by JMacLulich** [comment]
Is it actually possible to get tooltips?? 

We've had the same request, it would be great to be able to attach tooltips to each of the tools in the toolbar.

**Comment by jhchen** [comment]
There is now an [example](https://quilljs.com/playground/#snow-toolbar-tooltips) using bootstrap. I'm hesitant to add this Quill core since users are likely to be opinionated with UI and want to customize, which would add a lot of complexity and weight into Quill, and so is better handled by other libraries.

**Comment by rquast** [comment]
@jhchen You were right. This example tripped me up a bit when learning about quill. I just realized that the data-toggle is a bootstrap thing and you're passing in the html (with the tooltip data-toggle) rather than letting quill generate it in the html.

**Comment by tunderdomb** [comment]
It would be nice to have it included. Even basic accessibility is better than nothing.
All it needs is an optional attribute on toolbar buttons, the rest could be handled by user style sheets.
Something like:

```js
let toolbarOptions = [
    [
      { 'bold': { tooltip: "Bold (Ctrl+B)" } }, 'italic', 'underline', 'strike'
    ]
  ];
```

Generated via options:
```html
<button type="button" class="ql-bold" data-tooltip="Bold (Ctrl+B)"></button>
```

User style sheet:
```css
[data-tooltip] {
  content: attr(data-tooltip);
  display: none;
  // however people wanna style it..
}
[data-tooltip]:hover {
  display: block; // or something..
}
```

There's already an issue #1084 that touches on this, though that proposition is more generic.

**Comment by baraniee** [comment]
Try adding like this
let showTooltip = (el) => {
        let tool = el.className.replace('ql-', '');
        if (tooltips[tool]) {
          console.log(tooltips[tool]);
          $(el).attr("title",tooltips[tool]);
        }
      };

      let tooltips = {
        'bold': 'Bold',
        'italic': 'Italic',
        'underline': 'Underline',
        'strike': 'Strike'
      };

      let toolbarElement = document.querySelector('.ql-toolbar');
      if (toolbarElement) {
        let matches = toolbarElement.querySelectorAll('button');
        for (let el of matches) {
          showTooltip(el);
        }
      }

**Comment by rbonomo** [comment]
```
var toolbar = quill.container.previousSibling;
toolbar.querySelector('button.ql-bold').setAttribute('title', 'Bold');
toolbar.querySelector('button.ql-italic').setAttribute('title', 'Italic');
toolbar.querySelector('button.ql-list').setAttribute('title', 'List');
toolbar.querySelector('button.ql-link').setAttribute('title', 'Link');
toolbar.querySelector('button.ql-script').setAttribute('title', 'Superscript');
toolbar.querySelector('button.ql-clean').setAttribute('title', 'Clear Formatting');
```

**Comment by brankoiliccc** [comment]
Modified previous to work with angular 9 and multi language


`
  private toolbarTooltips: any;
  constructor(public elementRef: ElementRef,
    @Inject(LOCALE_ID) protected localeId: string) { }

  public ngAfterViewChecked(): void {

    if (this.localeId === 'sr-Latn') {
      this.toolbarTooltips = QUILL_TOOL_TIPS_SR;
    } else if (this.localeId === 'en-US') {
      this.toolbarTooltips = QUILL_TOOL_TIPS_EN;
    } else {
      // default to EN
      this.toolbarTooltips = QUILL_TOOL_TIPS_EN;
    }

    if (this.toolbarTooltips) {
      const toolbarElement = this.elementRef.nativeElement.querySelector('.ql-toolbar');
      // if i want to set manuallz
      // toolbar.querySelector('button.ql-bold').setAttribute('title', 'Bold');
      // toolbar.querySelector('button.ql-italic').setAttribute('title', 'Italic');
      // toolbar.querySelector('button.ql-list').setAttribute('title', 'List');
      // toolbar.querySelector('button.ql-link').setAttribute('title', 'Link');

      if (toolbarElement) {
        let matchesButtons = toolbarElement.querySelectorAll('button');
        for (let el of matchesButtons) {
          this.showTooltips('button', el);
        }
        //for submenus inside 
        let matchesSpans = toolbarElement.querySelectorAll('.ql-toolbar > span > span');
        for (let el of matchesSpans) {
          this.showTooltips('span', el);
        }
      }
    } else {
      console.warn('No tooltips');
    }
  }`

**Comment by Messa1** [comment]
Is there any good solution for react?

**Comment by Abidkhan1** [comment]
```
this.editor.container.previousSibling.querySelector('button.ql-list').setAttribute('title', 'Order list');
this.editor.container.previousSibling.querySelector('button.ql-list[value="bullet"]').setAttribute('title', 'Unorder list');
```
Working in my case, Tooltip without HTML Toolbar.

**Comment by gtournie** [comment]
didn't want to match all controls with a text, so I used class names to add a title attribute to all of them:
```
editor.previousSibling.querySelectorAll('select,button').forEach((el) => {
  let title = el.className.replace(/^ql|-/g, ' ').trim();
  if (el.value) title += ' ' + el.value;
  if (el.tagName === 'SELECT') el = el.previousSibling;
  el.setAttribute('title', title.charAt(0).toUpperCase() + title.slice(1));
});
```

**Comment by Gholyo** [comment]
const buttons = document.querySelectorAll('.ql-toolbar button');

      // Loop through each button and add a tooltip with the class name
      buttons.forEach(button => {
        const className = button.className;
        const val = button.value
        button.setAttribute('title',
         className.slice(3).charAt(0).toUpperCase() + className.slice(4) + ' ' + val)
         ;
      });
