### ISSUE TITLE
Link editing is non-intuitive

### ISSUE THREAD

**Issue by AndrewKirkovski** [quilljs/quill#653]
Link editing is very annoying

**Steps for Reproduction**

1. Visit quilljs.com
2. Click any link so cursor is inside
**Expected behavior**: Something indicates what to press to edit a link or editor appears
**Actual behavior**: Nothing happens
3. Click link icon in toolbar (cursor still sits mid-link)
**Expected behavior**: Link editor appears
**Actual behavior**: Nothing happens
4. Move cursor with arrows. Editor appears.
5. Click outside the link
**Expected behavior**: Link editor disappears
**Actual behavior**: Nothing happens

**Platforms**: Chrome 49 on Windows, Firefox 46 on Windows
**Version**: Applies to both http://quilljs.com and http://beta.quilljs.com/

**Comment by jhchen** [comment]
I'm not experiencing what you're seeing in step 2 or 5. The link tooltip appears in step 2, and the tooltip disappears in step 5.
![link](https://cloud.githubusercontent.com/assets/192974/15054106/b503cec8-12ba-11e6-8c07-8c7df0ff01a6.gif)
