### ISSUE TITLE
ParchmentError: [Parchment] Cannot insert text into scroll

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#655]
[Describe the issue]

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/docs/formats/
2. Type "aaa"
3. ctrl+a to select all the text
4. Type "a"

**Expected behavior**: [expected]
No error

**Actual behavior**: [actual]
ParchmentError: [Parchment] Cannot insert text into scroll

**Platforms**: [ex. Chrome 48 on Mac 10.11]
Firefox 46 on Windows 7

**Version**: [version]
1.0-Beta.1

**Comment by Joeao** [comment]
Can confirm on Firefox but no other browsers.
OSX 10.11.3
