### ISSUE TITLE
Clicking on the placeholder text doesn't focus the editor on Firefox

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#656]
[Describe the issue]
When clicking on the placeholder text "compose an epic..." the editor is not focused.
Only when clicking on the blank area it is focused.

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/docs/formats/
2. Click on the placeholder text

**Expected behavior**: [expected]
The editor should focus

**Actual behavior**: [actual]
The editor is not focused

**Platforms**: [ex. Chrome 48 on Mac 10.11]
Firefox 46.0.1 on Windows 7

**Version**: [version]
1.0-Beta.1

**Comment by Joeao** [comment]
Seems to be a bug with Firefox itself? Getting the same issue on Quill 0.20.1 and when modifying the dom on other pages.

It can be fixed by setting
```css
.ql-editor.ql-empty::before {
    pointer-events: none;
}
```
Which seems to fit into the same browser compatibility as Quill 1.0, but there may be a better solution.
