### ISSUE TITLE
Adding a list doesn't hide the placeholder text

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#657]
[Describe the issue]
When adding a list the number 1. is added but the placeholder text isn't removed.

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/docs/formats/
2. Click on the list button

**Expected behavior**: [expected]
The placeholder text should be removed

**Actual behavior**: [actual]
The placeholder text isn't removed.

**Platforms**: [ex. Chrome 48 on Mac 10.11]
Chrome 50 and Firefox 46 on Windows 7

**Version**: [version]
1.0-Beta.1

**Comment by szharta** [comment]
#
