### ISSUE TITLE
superscript/subscript icon with x instead of a

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#658]
[Describe the issue]
Usually the subscript icon is x<sup>2</sup> and the subscript icon is x<sub>2</sub>
Please see the attached screenshot of MS Word, the closure library editor and the tinymce editor
https://google.github.io/closure-library/source/closure/goog/demos/editor/editor.html
https://www.tinymce.com/docs/demo/classic/

The only rich text editor I found with a<sup>2</sup> is libreoffice but I think x<sup>2</sup> is much more standard.
![superscript](https://cloud.githubusercontent.com/assets/75841/15156443/ba30d416-16ef-11e6-82ac-956049d77126.png)

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/docs/formats/

**Version**: [version]
1.0-Beta.1

**Comment by jhchen** [comment]
I think the purpose of the icons is still clear and 'a' is more consistent with the other icons Quill uses so not sure it's worth remaking the icons.

**Comment by jhchen** [comment]
I had some more icons made for a potential future image UI and had the superscript/subscript icons updated to use "x". They'll be out in the next beta release.

**Comment by benbro** [comment]
Thanks :)
