### ISSUE TITLE
Instructions on customizing formats unclear

### ISSUE THREAD

**Issue by clemmy** [quilljs/quill#661]
In v0.21, I was able to specify different font sizes like so:

```
      <select class="ql-size">
        <option value="10px"></option>
        <option selected=""></option>
        <option value="14px"></option>
        <option value="18px"></option>
        <option value="32px"></option>
      </select>
```

However, on v1.0, correct me if I'm wrong, but this doesn't come out of the box, right? The addFormat section in the API reference links to this page: http://quilljs.com/docs/formats/, which isn't too clear on how to define a custom format (that will for example, allow numerical font sizes, instead of 'Small', 'Large', 'Huge').

**Comment by sachinrekhi** [comment]
Struggling with this as well because this previous code that worked in v0.21 now just generating Normal, Normal, Normal, Normal, Normal in the drop-down and not actually formatting the size.

```
<select class="ql-size">
  <option selected value="14px">14</option>
  <option value="16px">16</option>
  <option value="18px">18</option>
  <option value="24px">24</option>
  <option value="32px">32</option>
</select>
```

**Comment by vmarasow** [comment]
@sachinrekhi I was having the same issue, but when I updated to 1.0.0-Beta.3 it went away. Have no idea why though.

**Comment by jhchen** [comment]
If you want to go back to how v0.21 worked with using styles, you can do something like this: http://codepen.io/quill/pen/ezOEGE. It does miss out on some of the new offerings in 1.0 but I'm still working on those docs. One [change](https://github.com/quilljs/quill/blob/develop/CHANGELOG.md#features) in 1.0.0-beta.3 was it uses the text in `<option>` if available.

**Comment by jhchen** [comment]
There's a snippet in the [playground](http://quilljs.com/playground/#class-vs-inline-style) demonstrating how to do this now. Also an update in one of the 1.0 versions gave Quill the ability to understand and use value attributes on option tags, instead of just relying on CSS which is basically the issue @vmarasow was describing and suddenly no longer experienced.
