### ISSUE TITLE
Destroy editor instance

### ISSUE THREAD

**Issue by emanuelbsilva** [quilljs/quill#662]
I know from other issues that a destroy method was implemented, but that isn't in the current beta version.

What is the correct way to destroy an editor instance?

Thank you,
Emanuel Silva

**Comment by jhchen** [comment]
An explicit destroy is no longer necessary as Quill no longer keeps track of all editor instances. Just remove references to the instance and remove from the DOM and it will be garbage collected.

**Comment by emanuelbsilva** [comment]
So, there are no listeners that need to be removed? That's great! Thanks

**Comment by sachinrekhi** [comment]
I'd suggest adding this to the list of removed APIs in the [Upgrading to 1.0 Guide](http://beta.quilljs.com/guides/upgrading-to-1-0/)

**Comment by jhchen** [comment]
Thanks the docs have been updated

**Comment by mhdhamouday** [comment]
This work for me: (JQuery required)
```
function destory_editor(selector){
    if($(selector)[0])
    {
        var content = $(selector).find('.ql-editor').html();
        $(selector).html(content);

        $(selector).siblings('.ql-toolbar').remove();
        $(selector + " *[class*='ql-']").removeClass (function (index, css) {
           return (css.match (/(^|\s)ql-\S+/g) || []).join(' ');
        });

        $(selector + "[class*='ql-']").removeClass (function (index, css) {
           return (css.match (/(^|\s)ql-\S+/g) || []).join(' ');
        });
    }
    else
    {
        console.error('editor not exists');
    }
}
```
To use it just call:

`destory_editor('.editor');`

**Comment by guptanisha** [comment]
Thanku @mhdhamouday. 

In my case didn't remove 'svg' tag, hence it rendered polygon.

I tried this.

$(editor).find( "svg" ).removeClass('.ql-stroke')

Any help appreciated.

> This work for me: (JQuery required)
> 
> ```
> function destory_editor(selector){
>     if($(selector)[0])
>     {
>         var content = $(selector).find('.ql-editor').html();
>         $(selector).html(content);
> 
>         $(selector).siblings('.ql-toolbar').remove();
>         $(selector + " *[class*='ql-']").removeClass (function (index, css) {
>            return (css.match (/(^|\s)ql-\S+/g) || []).join(' ');
>         });
> 
>         $(selector + "[class*='ql-']").removeClass (function (index, css) {
>            return (css.match (/(^|\s)ql-\S+/g) || []).join(' ');
>         });
>     }
>     else
>     {
>         console.error('editor not exists');
>     }
> }
> ```
> 
> To use it just call:
> 
> `destory_editor('.editor');`

**Comment by mhdhamouday** [comment]
> Thanku @mhdhamouday.
> 
> In my case didn't remove 'svg' tag, hence it rendered polygon.
> 
> I tried this.
> 
> $(editor).find( "svg" ).removeClass('.ql-stroke')
> 
> Any help appreciated.
> 
> > This work for me: (JQuery required)
> > ```
> > function destory_editor(selector){
> >     if($(selector)[0])
> >     {
> >         var content = $(selector).find('.ql-editor').html();
> >         $(selector).html(content);
> > 
> >         $(selector).siblings('.ql-toolbar').remove();
> >         $(selector + " *[class*='ql-']").removeClass (function (index, css) {
> >            return (css.match (/(^|\s)ql-\S+/g) || []).join(' ');
> >         });
> > 
> >         $(selector + "[class*='ql-']").removeClass (function (index, css) {
> >            return (css.match (/(^|\s)ql-\S+/g) || []).join(' ');
> >         });
> >     }
> >     else
> >     {
> >         console.error('editor not exists');
> >     }
> > }
> > ```
> > 
> > 
> > To use it just call:
> > `destory_editor('.editor');`

It should delete "ql-stroke" because it is in the toolbar that we deleted.

Here you should delete point before class name so it will be:
`$(editor).find( "svg" ).removeClass('ql-stroke');`

**Comment by MikeLowrey** [comment]
If you looking for more shorter solution i would wrap the editor-container in an other container (`#mainContainer`). Then you can clear these conatiner like that:  `#mainContainer.innerHTML = ''`. Then you create a new editor element and appended to your `#mainContainer`.

**Comment by mugendi** [comment]
So I logged the entire `quill` object and went through all instances of **toolbar**, **tooltip** and **clipboard** in order to find a cleaner way to remove these from the DOM.

 I discovered that the right paths to be as follows:

- `quill.theme.modules.toolbar.container`
- `quill.theme.modules.clipboard.container`
- `quill.theme.tooltip.root`

So there is a cleaner method to destroy quill:

```javascript

...

function destroy_quill(quill, el) {

    // remove toolbox
    quill.theme.modules.toolbar.container.remove();
    // remove clipboard
    quill.theme.modules.clipboard.container.remove();
    // remove tooltip
    quill.theme.tooltip.root.remove();

    // remove all unwanted classes
    el.classList.forEach((cls) => {
      if (cls.startsWith("ql-")) {
        // we use requestAnimationFrame because there's a limit to how fast browsers will run dom manipulations
        requestAnimationFrame(() => {
          el.classList.remove(cls);
        });
      }
    });

}

// call with instances of quill and your element
destroy_quill(quill, el);

```
