### ISSUE TITLE
Header button has no effect

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#665]
Can't change a line to h1
Text align button has similar issue.

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/
2. Select some text
3. Click on the header button and choose 'Heading'.

**Expected behavior**:
The selected paragraph should switch to `<h1>`

**Actual behavior**:
Heading isn't set.
The editor loses focus.

**Platforms**:
Firefox 46 on Windows 7

**Version**:
1.0-Beta.2

**Comment by jhchen** [comment]
I'm having troubling reproducing this on FF46/Win8.1. Can you include the specific text you are selecting before trying to apply the heading?

![header](https://cloud.githubusercontent.com/assets/192974/15304014/c95644ec-1b6f-11e6-8bf8-9c68e272ed37.gif)

**Comment by benbro** [comment]
No matter what text I'm selecting it has no effect.
I've tried selecting the same text as you (WYSIWYG) it the heading button does nothing.
Tested Firefox 46 and Chrome 50 on Windows 7.

Not sure why it work for you but not for me.
Can someone else try to reproduce?

**Comment by benbro** [comment]
Screen capture of the issue
https://drive.google.com/file/d/0B12AhxvnYHrAWDJfT2Vza1ItMkk/view

Firefox 46 on Ubuntu 16.04

**Comment by mgkirs** [comment]
I can reproducing this bug on Google Chrome and Firefox (Fedora x64)

i think bug in toolbar button events. if i clicked very fast editor working. But if i do onmousedown on the button, button flee, mouse doing onmosemove on other element, focus lost, and i cant do onmouseup on the button and doing onmouseup on other element

**Comment by jhchen** [comment]
Thanks for the insight @mgkirs. Another commit seems to have already fixed this on the 1.0 branch. @benbro can you confirm on beta.quilljs.com. I updated it with a new build so in the console `Quill.version` should return "1.0.0-beta.2-5aa302" now.

**Comment by benbro** [comment]
Working now on beta.quilljs.com
Thanks
