### ISSUE TITLE
Clipboard matchSpacing rule depends on css styles

### ISSUE THREAD

**Issue by emanuelbsilva** [quilljs/quill#671]
The clipboard.convert's matchSpacing rule depends on the css styles. If for instance the paragraph rule is changed the clipboard.convert is returning a different delta result

Check the codepen i made: http://codepen.io/emanuelbsilva/pen/VaOrxg. You can see on the devtools that the 1st delta has more \n's than the 2nd delta.

**Comment by jhchen** [comment]
Yes. The clipboard is designed to match what the user sees. If other behavior is desired, you can [customize it](http://beta.quilljs.com/docs/modules/clipboard/).

**Comment by gbenson-wikia** [comment]
I encountered this and did some troubleshooting, and I believe there's actually a bug in `matchSpacing()` that's causing this behavior.

Example CSS to trigger the bug:
`p + p { margin: 1rem 0; }`

Example html to trigger the bug:
`<p>a</p><p>b</p><p>c</p>`

When `matchSpacing()` sees the first `<p>` tag, it correctly notes that it has no margins on it.  However, when it checks `node.nextElementSibling`'s positioning, it fails to take into account `node.nextElementSibling`'s top margin.  This leads to a situation where the delta has a spare newline in-between `a` and `b`, but not anywhere else in the doc.  And, of course, if one does 'edit', 'save', 'edit', 'save', etc. they'll get a new blank line each time that only appears in the editor.

As a related aside, there's a potential for other CSS rules to inadvertently wreak havoc here, such as absolute positioning, floating, and line-heights.

For a workaround until this is better addressed in `matchSpacing()`, users can just add a CSS rule of `.ql-clipboard p { margin: 0 !important; }` (or similar for any other rule that one finds to trigger this condition).
