### ISSUE TITLE
Clipboard.convert adds extra \n when ending with multiple <p></br></p>

### ISSUE THREAD

**Issue by emanuelbsilva** [quilljs/quill#672]
The `clipboard.convert` is adding an extra line break when ending with more than 1` <p></br></p>`

You can see the code pen i made: http://codepen.io/emanuelbsilva/pen/JXqxYY.

In that scenario when converting: `<p>test</p><p><br></p>` is returning `test\n\n`, which is correct. But when converting `<p>test</p><p><br></p><p></br></p>` is returning `test\n\n\n\n`, but should return `test\n\n\n`.

**Comment by jhchen** [comment]
Quill's clipboard is designed to match input visually. Paragraph tags by default have bottom margin to look like two lines, so Quill interprets them as such. You can customize this if desired: http://dev.quilljs.com/docs/modules/clipboard/

**Comment by juliantejera** [comment]
In case anybody else runs into this issue, here's the new link of the clipboard module https://quilljs.com/docs/modules/clipboard/

**Comment by jhchen** [comment]
Thanks @juliantejera I updated my link as well for the skimmers out there
