### ISSUE TITLE
Internet Explorer crashes after Chinese symbols are being typed in Quill 1.0.0-beta.2

### ISSUE THREAD

**Issue by ababashka** [quilljs/quill#677]
Internet Explorer crashes after Chinese symbols are being typed in Quill 1.0.0-beta.2

**Steps for Reproduction**
1. In Internet Explorer open http://beta.quilljs.com/playground/
2. Start typing Chinese characters

**Expected behavior**: Chinese symbol appears in textarea

**Actual behavior**: Internet Explorer crashes.

**Platforms**: Latest version of Internet Explorer in Win10, Win7.

**Notes**: Make sure text messanger's area is empty. Not reproducible when first symbol in text area is a space.

Quill already has similar issue: https://github.com/quilljs/quill/issues/626

**Comment by jhchen** [comment]
Just to clarify are you talking about IE11 or MS Edge? I'm getting some cursor issues but no crash in either.

**Comment by ababashka** [comment]
@jhchen I'm talking about IE11

**Comment by jhchen** [comment]
To clarify this is definitely a crash as in IE11 closes unexpectedly and Microsoft prompts you to submit the memory dump? If so can you post a screencast of this?

**Comment by ababashka** [comment]
@jhchen: Below you could find 3 pictures by steps:
 - Before start typing
 - After typing ('a' 'a' on the keyboard but in chinese) - first popup
 - After typing ('a' 'a' on the keyboard but in chinese) - second popup.
 - 
![before typing](https://cloud.githubusercontent.com/assets/6849156/17875768/9a01311e-68dd-11e6-9cb3-ed5674de15b1.png)
![start typing - info 1](https://cloud.githubusercontent.com/assets/6849156/17875766/9a000118-68dd-11e6-9f32-a0cf164d9ab1.png)
![start typing - info 2](https://cloud.githubusercontent.com/assets/6849156/17875767/9a01262e-68dd-11e6-871d-ee3710a239e9.png)

**Comment by jhchen** [comment]
Is this still occurring in 1.2.3? Can you post a screencast?

**Comment by ababashka** [comment]
No, currently IE doesn't crash anymore with Quill v. 1.2.3.
For now the problem is next: i can not start typing any chinese symbol if the first symbol is not the space. But as mentioned behind this is another bug which is already opened: https://github.com/quilljs/quill/issues/626
