### ISSUE TITLE
pasteHTML (pasting html generated by Quill) is stripping out ql-indent classes

### ISSUE THREAD

**Issue by jonnolen** [quilljs/quill#681]
Calling pasteHTML with quill generated html that has indented bits (ie. `<p class="ql-indent-1">...`) strips off the ql-indent-1 class name in the editor and removes the indent.  This happens with nested lists too.

**Steps for Reproduction**

1. Visit http://codepen.io/jonnolen/pen/GZaaaX
2. Enter text into left hand quill editor that is indented.
3. Press "Paste It!" button, (it calls pasteHTML with a copy of the html that has been stashed in a hidden div.)

**Expected behavior**: Indents are preserved in the editor.

**Actual behavior**: Indents are stripped.

**Platforms**: Chrome  50.0.2661.94 (64-bit) on Mac OS 10.11.4

**Version**: 1.0.0-beta.2-5aa302

**Comment by Sritharan-racap** [comment]
I am also facing the same issue. When I copy a content from other text editor like MS Word, it is striping off the indent from the styling. I have been choked up with this issue for 2 days. Its a nightmare!!!

**Comment by jonnolen** [comment]
I do not believe that this is the same issue as #673, this is calling the pasteHTML method from code using html that was originally generated by the quill editor.

**Comment by jonnolen** [comment]
So a clue to what may be causing this... If I change the whitelist for the IndentAttributor to be an array of strings then the indents are correctly applied when `pasteHTML()` is called. However, the +1 button no longer works because of a place in parchment where the whitelist is now being searched for a numeric value instead of a string value and the canAdd call fails....   

Actually... i think i may have fixed it, stand by for PR.

**Comment by jhchen** [comment]
Closed by merged PR.
