### ISSUE TITLE
pasteHTML inserts extra new lines after header elements

### ISSUE THREAD

**Issue by jonnolen** [quilljs/quill#683]
When you take html generated by quill and then try to initialize the editor with that html again using pasteHTML(), an extra newLine is inserted after I believe all block level attributors during rehydration (this may be a parchment issue)

**Steps for Reproduction**

1. Visit http://codepen.io/jonnolen/pen/MyMvBX
2. follow directions for reproduction embedded in codepen.

**Expected behavior**: text would render in editor exactly how it was when captured.

**Actual behavior**: 
* extra new line is inserted before and after h* tag when it is surrounded by unformatted text.
* extra new line is inserted before and after `ul` and `ol` tags when it is surrounded by unformatted text.

**Platforms**: Chrome 50.0.2661.94 (64-bit) on Mac OS 10.11.4

**Version**: 1.0.0-beta.2-5aa302

Probably related to #637

**Comment by jhchen** [comment]
When you paste content Quill tries to match this visually. Some elements like headers have bottom spacing which Quill uses a newline to match. If the source content has some CSS that removed this spacing, it would be present as an inline style in the pasted content.

If you want to initialize Quill with HTML you should set the innerHTML of the editor container prior to instantiating Quill.

Or avoid all the troubles with HTML altogether and use Deltas.

**Comment by jonnolen** [comment]
do you have a recommendation for a library to turn deltas into html for display outside of the editor?

**Comment by jhchen** [comment]
Not at the moment.
