### ISSUE TITLE
tag <button> in buttons submit form #685

### ISSUE THREAD

**Issue by mgkirs** [quilljs/quill#685]
unfinished events

**Steps for Reproduction**

1. http://codepen.io/anon/pen/jqjGMv
2. read first html line: <form id="articles" onsubmit="alert('i am submited');">
3. click on image-tooltip button

**Expected behavior**:  change image url;

**Actual behavior**:  submit form whith "#contenttm" textarea element only

**Platforms**: Chrome 50 on Fedora x64

**Version**: 1.0.0-beta.2-5aa302

its real #665

**Comment by mgkirs** [comment]
fix work but why thats submit form...

**Comment by mgkirs** [comment]
quill use tag <button> on buttons and this can submit form whith out javascript events

**Comment by jhchen** [comment]
I'll update Quill to generate <button>s with type=button but since in the example you are supplying the toolbar element and creating it in HTML, you need to add this attribute yourself.
