### ISSUE TITLE
Is highlight.js required 

### ISSUE THREAD

**Issue by gaisanshi** [quilljs/quill#687]
In this file https://github.com/quilljs/quill/blob/1.0/modules/syntax.js, I am seeing we are calling hljs.highlightBlock(). Below is the code copy from the above link. But I am not seeing highlight.js in the package.json. How does it work?

```
highlight() {
    if (this.cachedHTML !== this.domNode.innerHTML) {
      let text = this.domNode.textContent;
      if (text.trim().length > 0 || this.cachedHTML == null) {
        this.domNode.textContent = text;
        hljs.highlightBlock(this.domNode);
        this.attach();
      }
      this.cachedHTML = this.domNode.innerHTML;
    }
  }

```

**Version**: [1.0]

**Comment by jhchen** [comment]
The [docs](http://beta.quilljs.com/docs/modules/syntax/) are still being finished but highlight.js is required only if you want to use the syntax highlighted code module. Vanilla code blocks and Quill do not require highlight.js.

**Comment by gaisanshi** [comment]
Thanks Jason!
