### ISSUE TITLE
how to control the maximum length of the html

### ISSUE THREAD

**Issue by maku** [quilljs/quill#688]
I would like to know if it possible to control the maximum length of the html code (e.g. set a length property).

**Comment by jhchen** [comment]
You mean setting the maximum number of characters than can be typed into the Quill? Like `<textarea>` `maxlength` property?

**Comment by maku** [comment]
Yes exactly

**Comment by jhchen** [comment]
There's no built in configuration. You can check the length with `getLength()` but I don't have a good recommendation for preventing addition of content when the limit is reached.

**Comment by trigun539** [comment]
how could I prevent the API from adding new characters. Doing a check on length and disabling quill doesn't really work since the user can't delete after that. I have tried to use:
`quill.setContents(old)` however getting weird error `VM467 quill.js:6265 The given range isn't in document.`

```
if (startNode != null) {
	        if (!this.hasFocus()) this.root.focus();
	        var nativeRange = this.getNativeRange();
	        if (nativeRange == null || force || startNode !== nativeRange.start.node || startOffset !== nativeRange.start.offset || endNode !== nativeRange.end.node || endOffset !== nativeRange.end.offset) {
	          var range = document.createRange();
	          range.setStart(startNode, startOffset);
	          range.setEnd(endNode, endOffset);
	          selection.removeAllRanges();
	          selection.addRange(range);
	        }
	      }

**Comment by StreetStrider** [comment]
Hello. Has anyone got a solution for max-lines behavior? I believe it would be more complex than max-length, and would involve counting by newlines in Deltas with the following rejecting anything below max allowed newlines. It would be great if someone faced such problem and solved it.

**Comment by franverona** [comment]
I think this solution is incomplete. What happens if user tries to add text in the middle? The solution provided by @trigun539 won't be valid because text will be deleted from the end if I'm not mistaken.

**Comment by IanOnFire** [comment]
Hi everybody, we've found a solution in React that we are content with.

`<ReactQuill
    onKeyDown={this.checkCharacterCount}
    onChange={(value) => this.props.onChange(value)}
/>

checkCharacterCount = (event) => {
    if (this.getCharacterText().length > this.props.maxCharacters && event.key !== 'Backspace') {
        event.preventDefault();
    }
}`

if the max length of characters is reached, onChange won't be fired.

**Comment by StreetStrider** [comment]
That's a workaround, not a solution. If it's working for you, it's OK. But the purpose of editor (Quill) is to release you from opting in editable area in such crude manners. Too many parts potentially can be broken. Quill API is required.

**Comment by bjgaynor** [comment]
If anyone comes across this and wants a character counter, here's one I threw together.  All you need is a div with the class ".character-count".  

`$('.character-count').text((limit - (quill.getLength() - 1)) + " Characters Remaining");`

**Comment by seanjrankin** [comment]
> This one works regardless where the text is inserted (doesn't handle formatted pasted content)
> 
> ```js
> const limit = 10; 
> quill.on('text-change', function (delta, old, source) {
>     if (quill.getLength() <= limit) {
>         return;
>     }   
>     const { ops } = delta;
>     let updatedOps;
>     if (ops.length === 1) {
>         // text is inserted at the beginning
>         updatedOps = [{ delete: ops[0].insert.length }]; 
>     } else {
>         // ops[0] == {retain: numberOfCharsBeforeInsertedText}
>         // ops[1] == {insert: "example"}
>         updatedOps = [ops[0], { delete: ops[1].insert.length }]; 
>     }   
>     quill.updateContents({ ops: updatedOps }); 
> });
> ```
> 
> @jhchen It's fine if it's not a _good_ recommendation, at least maybe point us in the right direction. It will save some folks some time hacking around.

I was getting infinite loops with this one if I pasted in large amounts of text.

Here is a simpler solution I came up with:
Just set the contents back to oldContents if the maxLength is exceeded
```js
    (delta, oldContents) => {
      if (!quill) return;

      let html = quill.root.innerHTML;
      let length = html.length;

      if (maxLength && maxLength < length) {
        quill.setContents(oldContents);
      } else {
        // ...do other stuff
      }
```

**Comment by Senelith** [comment]
@IanOnFire I tried using your implementation, but its says `getCharacterText()` is not a function 

Having trouble in controlling  the maximum character length in react ? Isn't there a solid solutions provided by the editor itself without workarounds  ?

**Comment by flexilivre** [comment]
Here a solution with an module. It works only if you have history module enabled :

```
Quill.register('modules/maxlength', function(quill, options) {

    quill.on('text-change', function(e) {
        
            let size = quill.getText();
            if (size.length > options.value)
            {
                quill.history.undo();
                return;
            }
    });

});
```

Then you have to specify your module like that : 

```
var editor = new Quill(container, { modules: 
                                                { 
                                                    maxlength : {value : 10},
                                                    history: { delay: 100, userOnly: true }  
                                                }
                                            });
```

**Comment by sliceh** [comment]
> > This one works regardless where the text is inserted (doesn't handle formatted pasted content)
> > ```js
> > const limit = 10; 
> > quill.on('text-change', function (delta, old, source) {
> >     if (quill.getLength() <= limit) {
> >         return;
> >     }   
> >     const { ops } = delta;
> >     let updatedOps;
> >     if (ops.length === 1) {
> >         // text is inserted at the beginning
> >         updatedOps = [{ delete: ops[0].insert.length }]; 
> >     } else {
> >         // ops[0] == {retain: numberOfCharsBeforeInsertedText}
> >         // ops[1] == {insert: "example"}
> >         updatedOps = [ops[0], { delete: ops[1].insert.length }]; 
> >     }   
> >     quill.updateContents({ ops: updatedOps }); 
> > });
> > ```
> > 
> > 
> > @jhchen It's fine if it's not a _good_ recommendation, at least maybe point us in the right direction. It will save some folks some time hacking around.
> 
> I was getting infinite loops with this one if I pasted in large amounts of text.
> 
> Here is a simpler solution I came up with:
> Just set the contents back to oldContents if the maxLength is exceeded
> 
> ```js
>     (delta, oldContents) => {
>       let html = quill.root.innerHTML;
>       let length = html.length;
> 
>       if (maxLength && maxLength < length) {
>         quill.setContents(oldContents);
>       } else {
>         // ...do other stuff
>       }
> ```
> 
> Note: I am using the innerHTML to determine length, but you could just look at the text length instead if that suits your needs.

How to get the old content in angular 8 - if i am using $event in event emitter

**Comment by nashpaw** [comment]
There isn't solution for this one yet ?

**Comment by sarunmrzn** [comment]
still no such feature?

**Comment by ezzabuzaid** [comment]
Register custom module
```ts
  quill.register('modules/maxlength', function (instance, options) {
    if (!('value' in options)) {
      return;
    }
    instance.on('text-change', () => {
      const text = instance.getText();
      if (text.length - 1 > options.value) {
        instance.history.undo();
      }
    });
  });
```


```ts
const maxLengthModule = this.maxLength
  ? {
      history: { delay: 0 },
      maxlength: { value: this.maxLength }
    }
  : {};
```

When init set modules
```ts
  modules: {
    ...modules,
    ...maxLengthModule
  }
```

**Comment by ayuzvyak** [comment]
Why is it Closed? Nobody needs a proper implementation for a common maxLength attribute?

**Comment by sansho88** [comment]
With Angular, my characters limit system works perfectly :
Template:
```html

<quill-editor #editor
  (onContentChanged)="onContentChanged($event)"
/>
```

Component:
```typescript

@ViewChild('editor') editorComponent?: QuillEditorComponent;
  get quill(): Quill {
    return this.editorComponent!.quillEditor;
  }

onContentChanged(event: ContentChange): void {
   const maxLength = 42;

    if (event.text.length > maxLength) {
      this.quill.disable();
      this.quill.deleteText( maxLength, event.text.length - maxLength);
      this.quill.enable();
    }
}
```
