### ISSUE TITLE
quilljs does not display text inside an object tag

### ISSUE THREAD

**Issue by eyal1990** [quilljs/quill#692]
When hosting a page that contains quilljs inside an `<object></object>` quilljs throws "unspecified error".
It happens in `checkFocus()` at `document.activeElement`.

**Steps for Reproduction**

1. Visit the [Demo](https://plnkr.co/edit/AZuUANPMrcXjGAjNqmJf?p=preview) in IE 9+
2. Open the debugger
3. Rum plunker

**Expected behavior**:
The text in the editor is shown

**Actual behavior**: 
The text in the editor isn't shown.
There is an error in the console: "unspecified error"

**Platforms**: 
IE 9+

**Version**: 
0.20.1 and probably others

**Comment by jhchen** [comment]
1. Not sure what rum plunker means.
1. This does not seem like correct use of [`<object>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object)
1. IE9 is no longer supported.

**Comment by eyal1990** [comment]
1. The plunker is just a demo in order to display the problem. You can easily reproduce it if you'll place a quill inside an object tag.
2. What do you mean? This follow the example from here: http://www.w3schools.com/tags/tag_object.asp
3. This does not work on IE 10, IE11 and probably Edge.

**Comment by eyal1990** [comment]
1. The plunker is just a demo in order to display the problem. You can
easily reproduce it if you'll place a quill inside an object tag.
2. What do you mean? This follow the example from here:
http://www.w3schools.com/tags/tag_object.asp
3. This does not work on IE 10, IE11 and probably Edge.
בתאריך 23 במאי 2016 19:41,‏ "Jason Chen" <notifications@github.com> כתב:

**Comment by jhchen** [comment]
`<iframe>` seems more appropriate for this use case since Quill is not an embedded multimedia object.

**Comment by eyal1990** [comment]
IFrame is the obvious choice but I found that an IFrame has a memory consumption issue so I changed it to an object.

It is a validation use of the object tag and there is no reason to not support it.
