### ISSUE TITLE
Hitting backspace on an empty line loses focus of the editor

### ISSUE THREAD

**Issue by emanuelbsilva** [quilljs/quill#693]
When hitting backspace multiple times and deleting the last character of line the cursor disappears, hitting again the backspace will go to the last page. This is because the editor is loosing focus. 

**Steps for Reproduction**

1. Visit beta.quilljs.com
2. On the demo example select everything and delete
3. Add 3 lines
4. Delete the last line using the backspace

**Platforms**: Chrome 49, Safari 7.0.6 (both on OSX)

Here's a screencast i made
![screencast](http://f.cl.ly/items/0j1r1w0V2W011W3f0M1w/quill_issue.gif)

**Comment by jhchen** [comment]
Can anyone else reproduce this? I'm not able to on OSX 10.11 Chrome 50. Safari 7 is not supported.

**Comment by emanuelbsilva** [comment]
I just found out that when using incognito mode everything works fine.

So the extension that is causing me trouble is the Evernote extension. I'll do some more debugging to see if can find out why it's messing with Quill.

**Comment by a-change** [comment]
Seems my colleagues and I can reproduce the issue on Safari Version 10.1 (12603.1.30.0.34).
Here are the steps to try:
1. write something
2. remove the whole line clicking backspace
3. click backspace additionally one or two times
Blinking cursor will still be on the line but it won't actually be able to write anything.
Here's an example on quilljs.com in incognito mode to exclude external add-ons' interventions:
![ezgif-2-c09728c677](https://user-images.githubusercontent.com/10083239/27604578-5c467ec2-5b82-11e7-986f-fb2c7c318442.gif)
The same thing works fine on Chrome Version 58.0.3029.110 (64-bit):
![ezgif-2-a63beea331](https://user-images.githubusercontent.com/10083239/27604540-3b9eef92-5b82-11e7-9c2b-8fb9c4df5874.gif)
Tested on MacOS Sierra Version 10.12.4

**Comment by jhchen** [comment]
@a-change Safari 10.1 is working fine for me following your instructions on quilljs.com. If this is still an issue can you file another issue and fill out the entire issue template?

**Comment by a-change** [comment]
@jhchen sure, here is a separate issue for this: https://github.com/quilljs/quill/issues/1564
