### ISSUE TITLE
Add blur() convenience method

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#701]
This is a feature request, but think it would be nice from an API perspective to also have a blur() API method in addition to just doing it via a null sent to setSelection().

Given the existence of focus() and hasFocus(), I imagine folks will immediately jump to looking for a blur() method as opposed to realizing they have to use setSelection(null) to accomplish this.

**Comment by jhchen** [comment]
I'm going to leave this open as an easy PR for newcomers.
