### ISSUE TITLE
When multiple lines selected, bubble tooltip shows up in middle of editor

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#706]
When you select multiple lines in the editor and then the bubble tooltip is displayed, it's not being displayed next to the selected text. Instead it is displayed in the middle of the editor.

![screen shot 2016-05-25 at 9 47 26 am](https://cloud.githubusercontent.com/assets/192650/15548530/bba4af9c-225d-11e6-8e1a-5846c255407b.png)

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/docs/themes/bubble/
2. Type 3 lines of text
3. Select 3 lines of text

**Expected behavior**:
Expect bubble tooltip to show up near the 3 lines of text

**Actual behavior**:
Bubble tooltip shows up in the middle of the editor

**Platforms**:
Chrome 50 on Mac 10.11

**Version**:
Quill 1.0 Beta 3

**Comment by Robinzon100** [comment]
has anybody fixed the issue?
