### ISSUE TITLE
Pressing link format sometimes loses current selection

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#709]
Occasionally when I highlight a link, press the link button, and press Save, the link formatting is not applied.

The issue appears to be that the selection in the editor is lost and then the link is not being applied to any specific text. This is occurring intermittently. Sometimes it works fine, other times it does not. On a few occasions a subset of the originally highlighted text ended up as formatted. Overall issue is reproducing quite regularly.

I thought this might be related to https://github.com/quilljs/quill/issues/665 but this issue has persisted in Beta 3, versus that specific issue has gone away for me. Not sure if there is something you did there that needs to be specifically applied for links?

**Steps for Reproduction**

1. Visit beta.quilljs.com
2. Type a url
3. Press link button
4. Press save

**Expected behavior**:
Link formatting is applied

**Actual behavior**:
Occasionally the link formatting is not applied.

**Platforms**:
Chrome 50 on Mac 10.11

**Version**:
Quill 1.0 Beta 3

**Comment by Igor912** [comment]
I had the similar problem with lose of selection when open font or font size dropdown.
So maybe this fix will help you.
Please see attached file.
[index.txt](https://github.com/quilljs/quill/files/1099923/index.txt)
