### ISSUE TITLE
Custom BlockEmbed format with tagName=DIV not performing well

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#710]
I'm trying to create a custom format that is a block-level embed. I basically copied the existing Video format from here: https://github.com/quilljs/quill/blob/develop/formats/video.js

I registered the new embed format via Quill.register() and added it via editor.insertEmbed(). When I set tagName='IFRAME' or 'IMG' like the two existing video and image embeds, the cursor position and deletion work fine. As in if I set the cursor after the embed and press delete the embed is appropriately deleted in it's entirety. I can also move the mouse cursor to either immediately before the embed or immediately after the embed on the same line as the embed.

However when I set tagName='DIV' the basic behaviors stop working. As in pressing delete after the embed does not in fact delete the embed. Also I can no longer position the mouse cursor immediately before or after the embed.

The code seemed to suggest BlockEmbed could be used with any block-level tag type, so I assumed DIV would qualify. Is that not the case? Or is this in-fact a bug? The docs seems to suggest I might need to override index() and position() but since neither the video or image embeds needed to do that I didn't think I would need to either. But do I?

**Platforms**:
Chrome 50 on Mac 10.11

**Version**:
Quill 1.0 Beta 3

**Comment by jhchen** [comment]
One issue is if you use `<div>` you need to specify a className too since `<div>`s are in use by Scroll blots. `className` is also how both formula blots and plain inline blots both use `<span>`.

**Comment by sachinrekhi** [comment]
I'm running into this issue where the Delta that gets created to represent my custom embed is inaccurate.

So I went ahead and copied the Video embed code verbatim, registered my copy on top of the existing version, and noticed that even the Video embed's Delta object is now inaccurate as well.

Take a look at this codepen: http://codepen.io/sachinrekhi/pen/oLNxxO

When you look at the console, you'll see the video Delta is being represented like this:

![screen shot 2016-05-27 at 2 13 14 pm](https://cloud.githubusercontent.com/assets/192650/15621356/32fcdf8e-2415-11e6-83f0-035007c03cdd.png)

So instead of it being insert: {video: 'url'}, the video key is now being set as part of the attributes.

Looks like a bug?

**Comment by sachinrekhi** [comment]
A separate issue I'm experiencing causes Quill to throw an error when I append a child node in the create method of my custom embed.

See this code pen: http://codepen.io/sachinrekhi/pen/xOxVQo?editors=0010

The error I get is:
```
Uncaught TypeError: Cannot read property 'emitter' of undefined
```

The strange thing is if I remove Test.className = 'ql-test' the error goes away and the custom embed renders properly with the child node.

**Comment by sachinrekhi** [comment]
Jason also pointed out that the issue with my two codepens above was that I was importing the incorrect BlockEmbed.

I changed it to the following and both of the above issues went away:

```
var BlockEmbed = Quill.import('blots/block/embed');
```

**Comment by jhchen** [comment]
Where did we land on this? It seems like a solution was found but I need to document it but can't remember..

**Comment by sachinrekhi** [comment]
The proper import statement fixed the 2 issues I was running into, so just need to clarify in the docs the appropriate import statement for doing a BlockEmbed.

**Comment by jhchen** [comment]
Okay thanks I think the new [Cloning Medium with Parchment](http://quilljs.com/guides/cloning-medium-with-parchment/) guide should cover BlockEmbeds.

**Comment by akshath4u** [comment]
I have used below code for create a blot 
`var BlockEmbed = Quill.import('blots/block/embed');`

I have inserted a 
<img width="629" alt="screen shot 2016-09-29 at 4 34 05 pm" src="https://cloud.githubusercontent.com/assets/9428527/18951388/98e21f26-8662-11e6-8d4f-22c1b37dd136.png">
image as `quill.insertEmbed(range.index, "survey", "http://elfarochurch.com/wp-content/uploads/2013/06/click-here-arrow.png");` but i am getting below error and i can't able to get the content with inserted image
