### ISSUE TITLE
Styles from custom class format persists after deletion

### ISSUE THREAD

**Issue by abinashpanda** [quilljs/quill#712]
I had tried to create a custom format and added styles for that format as specified in the codepen (http://codepen.io/abinashpanda/pen/LZPBPN). As I select the format and type something it works fine, but when delete the text completely and again try to type something else the style of the formatting still remains. For example
1. For the first time when I select the custom formatting and type something it works as
   ![screenshot from 2016-05-26 18-43-39](https://cloud.githubusercontent.com/assets/2332955/15575753/1b8bb896-2372-11e6-9d38-ad10529730eb.png)
2. Try to delete everything till the end and again type something then it becomes as
   ![screenshot from 2016-05-26 18-43-51](https://cloud.githubusercontent.com/assets/2332955/15575773/3c9b4c36-2372-11e6-804c-c4b6368ca3fb.png)

The reason its behaving in such a weird manner is because the style becomes inline as 
![screenshot from 2016-05-26 18-43-58](https://cloud.githubusercontent.com/assets/2332955/15575809/64b31ce4-2372-11e6-87dc-68b45f16fe51.png)

**Steps for Reproduction**
1. Visit http://codepen.io/abinashpanda/pen/LZPBPN
2. Select the custom formatting and type something.
3. Delete everything by backspace and again type something.

**Expected behavior**: 
There should not be any formatting in the newly typed data. Even if it is present, then at least we should be able to disable it. But now the styling has become inline, the user can't disable the styling.

**Actual behavior**:
The styling still remains the same and the user can't disable it even by selecting the custom format.

**Platforms**: Chrome Version 50.0.2661.86 (64-bit), Ubuntu 16.04 LTS

**Version**: 1.0.0-beta.3

**Comment by kant2002** [comment]
@jhchen Seems to be this is fixed in the latest version.

**Comment by jhchen** [comment]
Yes looks like it. Thanks!
