### ISSUE TITLE
Restore getHTML for 1.0

### ISSUE THREAD

**Issue by Retsam** [quilljs/quill#714]
It'd be nice if the `getHTML` method was returned for version 1.0.  Yes, as the [migration guide](http://beta.quilljs.com/guides/upgrading-to-1-0/) says, it's possible to use native DOM methods to get the HTML content, but it's not as nice doing it that way.

Best case scenario, the 1.0 equivalent to `editor.getHTML()` seems to be:

```
var quill = new Quill(container, options);

var html = container.querySelector(".ql-editor").innerHTML;
```

That's not terrible, per se, but:

1. It's not obvious, it's something that needs to be found in the documentation or through experimentation.

2. It references classes added by the quill library, which is something that I could mistype or could be a breaking change down the road.

3. It relies on having a way to reference the container element.  If I want to get the HTML from a part of the code other than the code that initializes quill, I need to pass the container node (or a CSS selector or something), instead of just passing the quill instance around.  

I'm absolutely nitpicking, but it's more annoying than simply being able to do `quill.getHTML()`.  Plus, it'd simply be one less breaking change for people migrating from <1.0 .

**Comment by jhchen** [comment]
Removal of the method was motivated by the [pit of success](https://blog.codinghorror.com/falling-into-the-pit-of-success/). Most people desiring direct interaction with HTML in Quill have wrong expectations and do not appreciate the ambiguity and complexity of HTML, especially between browsers. Those that do are very well aware of APIs available through the DOM.

`getHTML` is not coming back.

**Comment by ChuckkNorris** [comment]
Just a thought - if it's been removed, would you mind removing it from the API documentation? It's quite frustrating when learning a library for the first time. http://quilljs.com/docs/api/#quillprototypegethtml

**Comment by jhchen** [comment]
@ChuckkNorris It is removed in the [beta](http://beta.quilljs.com) docs.

**Comment by mnpenner** [comment]
Quill is adding this junk to the `innerHTML`

```html
<div class="ql-editor ql-blank" contenteditable="true"><p><br></p></div><div class="ql-clipboard" contenteditable="true" tabindex="-1"></div><div class="ql-tooltip ql-hidden"><a class="ql-preview" target="_blank" href="about:blank"></a><input type="text" data-formula="e=mc^2" data-link="quilljs.com" data-video="Embed URL"><a class="ql-action"></a><a class="ql-remove"></a></div>
```

Without an API method I don't know how we're expected to get the HTML. And without the HTML... what good is Quill? Honest question. I thought Quill was supposed to by a WYSIWYG editor that would allow us to render the output outside the editor.

**Comment by jhchen** [comment]
@mnpenner You're selecting the wrong container. `ql-editor` only has `<p><br></p>`.

**Comment by mnpenner** [comment]
Dope :disappointed:  Thanks @jhchen. I thought it was the element I initialized it on.

**Comment by acidjazz** [comment]
I don't see how linking an article from 07 about problems with C++ justifies removing this method, especially with removing it and then no reference or example on how we are supposed to render stored posts using quilljs? Do you want us to store and use the Delta object? How about an example of how one would display saved posts from this?

 Or even an example of how to properly go after the right .innerHTML and how to select the correct container?
