### ISSUE TITLE
grab doesn't work...

### ISSUE THREAD

**Issue by mgkirs** [quilljs/quill#715]
I just copy the demo

http://codepen.io/anon/pen/jqjGMv?editors=1111

**Expected behavior**: Look the demo text

**Actual behavior**: empty

https://habrastorage.org/files/518/a58/714/518a58714b244cc98aced536da707967.png

**Platforms**: [Chrome, Firefox on Fedora x64 ]

**Version**:  1.0.0-beta.3.latest(The first 1.0.0-beta.3 and the 1.0.0-beta.2 worked )

**Comment by mgkirs** [comment]
if initialize quill without syntax parametr
````
Quill('#editor', {
    modules: {
      'formula': true,
//    'syntax': true,
      'toolbar': '#toolbar'
    },
    theme: 'snow'
  });
````
the demo works

**Comment by jhchen** [comment]
As the error states in the console you need highlight.js.

**Comment by mgkirs** [comment]
Need to include highlight.js before quill.js. Its ok?
