### ISSUE TITLE
Generate buttons with type="button"

### ISSUE THREAD

**Issue by clemmy** [quilljs/quill#717]
When we have a quill container inside a form, and the type="button" isn't set, the behavior is that the form will be submitted when a button is pressed. This means that upon pressing the italics/bold/underline buttons, the form will be submitted. The way to get around this currently is to get a handle of the buttons and preventDefault, but I suspect this may be a cleaner solution.

**Comment by mgkirs** [comment]
#690

**Comment by jhchen** [comment]
Why not just set the type attribute? Quill sets this on buttons [it creates](https://github.com/quilljs/quill/blob/develop/modules/toolbar.js#L127).
