### ISSUE TITLE
"authorship" and "multiple cursors" modules in Quill 1.x

### ISSUE THREAD

**Issue by sagacitysite** [quilljs/quill#718]
Just a short question:

Will there be an "authorship" module and "multiple cursors" module in Quill 1.x some day? :)

**Current version**: Quill 1.0.0-beta.3

**Comment by benbro** [comment]
https://github.com/quilljs/quill/issues/635#issuecomment-220243661

**Comment by Joeao** [comment]
If you're happy with the comment which partially answers your question, though whether it's part of 1.x hasn't been specified. You should close the issue. But on a side note:
Are you using a library that enables real time collaboration? If so, which one?

**Comment by sagacitysite** [comment]
Indeed I was happy, in our case it is not important when it will be released, it's just important if it will be released. Actually, it's not even important if the feature will be available this year or next year, but we wanted to know if we can implement it one day. So I closed the issue.

And wrt the side note:

In our project we're started to work with [gulf](https://github.com/marcelklehr/gulf) in combination with [ottype richtext](https://github.com/ottypes/rich-text) and [mongodb adapter](https://github.com/marcelklehr/gulf-mongodb) (and Quill of course). And we transfer data trough socket io. We had a first success in the last days/weeks.

If you are interested in how we did it, you can have a look at our github repository. You can find the [server part](https://github.com/openevocracy/openevocracy/blob/master/server/pads.js) and the [client part](https://github.com/openevocracy/openevocracy/blob/master/public/js/app/views/groups/collaborative.js). But work is still in progress! ;)
