### ISSUE TITLE
Absolute positioning

### ISSUE THREAD

**Issue by amarchen** [quilljs/quill#719]
Is it possible to position elements the absolute way with quill?

I am thinking about letting the users create pixel-perfect widgets with quill. That would need for example positioning image on the left exactly 2px from the left border and a block of text exactly 32px from the left border like facebook is doing for getting previews for the OpenGraph-enabled links (as in the image attached).
<img width="257" alt="_1__facebook_and_tweetdeck" src="https://cloud.githubusercontent.com/assets/597409/15704545/ed17e3aa-27f3-11e6-824a-5340d3d5c42a.png">

Would something like that be possible with quill? To my understanding quill doesn't support image resizing (yet?) #104 , but if the user uploads image in the exact resolution, maybe it could be possible to add absolute positioning to a given object and drag it around?

**Comment by jhchen** [comment]
There's no UI for image editing but there's no reason you could not use css or attributes to resize images. Any reason you couldn't just `float: left` images or some other css to do what you want?
