### ISSUE TITLE
setContents() call does not work after inserting a video embed

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#720]
After inserting a video embed via quill.insertEmbed(), setContents() no longer clears the editor and replaces it with the new contents.

Inserting an image embed seems to work fine, but not video embed. Also noticed this doesn't work on my custom embed.

**Steps for Reproduction**

1. Visit beta.quilljs.com
2. quill.setContents([{insert:'test\n'}])
3. quill.insertEmbed(0, 'video', 'https://www.youtube.com/embed/aHJRBpIZm1o');
4. quill.setContents([{insert:'test\n'}])

**Expected behavior**:
Editor contents returns to just "test"

**Actual behavior**:
Editor contents still has embed in it

**Platforms**:
Chrome 51 on Mac 10.11

**Version**:
Quill 1.0 Beta 3

**Comment by jhchen** [comment]
This has been fixed in https://github.com/quilljs/quill/commit/3525e2d70b68b8ff3b47b58bf409a6765f66d651
