### ISSUE TITLE
Syntax module does not correctly highlight multi-line comments

### ISSUE THREAD

**Issue by michaeljosephrosenthal** [quilljs/quill#723]
Reproducable with the example editor at [beta.quilljs.com](http://beta.quilljs.com):
<img width="901" alt="screen shot 2016-06-02 at 16 40 16" src="https://cloud.githubusercontent.com/assets/8343799/15761949/b8c21b6e-28e0-11e6-82de-b8f7e7bfb798.png">
  
We should wrap them in a single `<pre/>` similar to how lists are wrapped by `<ol/>`:
<img width="812" alt="screen shot 2016-06-02 at 16 43 15" src="https://cloud.githubusercontent.com/assets/8343799/15762037/266ec568-28e1-11e6-8968-e7cd7a1c80c5.png">

**Comment by jhchen** [comment]
One line blocks are not a problem by itself. There are many benefits to it such as consistent newline creation/deletion, at any position across all supported platforms, which is why the implementation choice was made in the first place. The incorrect highlighting for multiline is the target bug that needs to be fixed, which may or may not be done with a one line per block implementation.

**Comment by michaeljosephrosenthal** [comment]
I don't think there's a solution for consistent multi-line highlighting that doesn't run into the same problem / trade-off, just like you get with lists. We could make the `code-block` merging configurable, or make such merging strategies configurable in general.

One thing I tried was making `code-block` a wrapper around `code-line`s, but that was a bit painful, and was really hard to fit to the current highlighting strategy.

**Comment by jhchen** [comment]
I'm not ready to give up on a solution yet and force all Quill users to make a configured tradeoff. The solution may not be apparent yet but that does not mean it does not exist.

**Comment by auralon** [comment]
This is exactly the issue that I came across, although I noticed it with the `blockquote` tag too, which certainly doesn't have the same knock-on effects (when used in conjunction with other tools like `highlight.js`), but if behaviour is changed for `pre` tags, then it might as well be altered for `blockquote` too.

**Comment by auralon** [comment]
Looking forward to this being released as a beta build.
