### ISSUE TITLE
color and background toolbar buttons rendered with .ql-active

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#729]
The color and background toolbar buttons rendered with the .ql-active class even when the document is empty. When focusing the editor, the .ql-active class is removed.

**Steps for Reproduction**
To reproduce:
```javascript
const COLORS = [
    "#000000", "#e60000", "#ff9900", "#ffff00", "#008A00", "#0066cc", "#9933ff",
    "#ffffff", "#facccc", "#ffebcc", "#ffffcc", "#cce8cc", "#cce0f5", "#ebd6ff",
    "#bbbbbb", "#f06666", "#ffc266", "#ffff66", "#66b966", "#66a3e0", "#c285ff",
    "#888888", "#a10000", "#b26b00", "#b2b200", "#006100", "#0047b2", "#6b24b2",
    "#444444", "#5c0000", "#663d00", "#666600", "#003700", "#002966", "#3d1466"
  ];

  var toolbarOptions = [['bold', 'italic', 'underline', 'strike'],
                        [{'color': COLORS}, {'background': COLORS}]];

var quill = new Quill('#editor-container', {
    'modules': {
      'toolbar': toolbarOptions
    },
    'theme': 'snow'
  });
```

**Expected behavior**: 
All buttons should be inactive because the document is empty.

**Actual behavior**:
The color and background buttons has the .ql-active class.

**Platforms**:
Firefox 46 on Windows 7

**Version**:
1.0-beta.4

**Comment by jhchen** [comment]
One issue is the picker expects one of the array values to be `false` to represent the default value. But the initialization could be more forgiving.

**Comment by jhchen** [comment]
https://github.com/quilljs/quill/commit/8b7ad586e060b337b420bef01a2dcb2bc7168baa has fixed this issue as well.
