### ISSUE TITLE
Custom button insertText() resets cursor position

### ISSUE THREAD

**Issue by KameSama** [quilljs/quill#731]
I'm trying to insert a custom button to add scientific symbols to quilljs ( v1.0.0-beta.4) and when the insertion of the symbol happens in the "middle" of a line, it resets the cursor to the beginning of the line. The problem does not occur when the cursor is at the end of the line.

**Steps for Reproduction**
I reproduced it on the http://beta.quilljs.com/playground/

1. Add this code to the javascript
`$('.add-micro').on("click",function(){
        var range = quill.getSelection(!quill.hasFocus());
        quill.insertText(range.index,$(this).val(),'','',null,'api');
    });`

2. Add this HTML to add the toolbar button
`    <span class="ql-formats">
		  <button class="add-micro" value="&#181;" >&#181;</button>
    </span>`
3. Press the "&#181;" button a few times, then add some whatever text, move the cursor to the text then click the button again.

**Expected behavior**:
The cursor should increment its position by the size of the inserted text
**Actual behavior**:
The cursor moves back to the first position of the line
**Platforms**:
Chrome 51

**Comment by benbro** [comment]
In a collaborative editor the cursor should stay at the same place when the delta adds content after the cursor.

**Comment by prajapati-gautam** [comment]
i have problem with custom button for add input textbox in quill editor.
have any idea how to insert ??
i am tried various functions but no result found.

**Comment by pietrop** [comment]
Having the same problem,

```js 
var length = quill.getLength() -1;
quill.insertText(length, a_variable_with_some_test_here );
```

 when I insert text at the end, I need to do `-1` to avoid it ending on a new line, but once the text is added the cursor/caret position jumps to top of the document.

Any ideas on how to figure this out?

**Comment by jhchen** [comment]
setTimeout(function() { quill.insertText('Hello', quill.getLength() - 1) }, 5000); and then placing the cursor anywhere in the quilljs.com editor before the 5000ms is working for me. If you are having issues please file a separate Github Issue and fill out all the details.

**Comment by pietrop** [comment]
As specified in the API for [`insertText`](https://quilljs.com/docs/api/#inserttext), the parameters are first the position and then the text. This is more likely to work:

```js
setTimeout(function() {
    quill.insertText( quill.getLength() - 1, 'Hello')  
}, 5000);
```

In any case, I've tried it and it seems ok, going to do some more tests to see if I need to raise a separate issue. 

Thanks!

**Comment by jhchen** [comment]
Yes that was a typo on my part.
