### ISSUE TITLE
Toolbar buttons loose focus when calling quill.updateContents(delta)

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#734]
An open dropdown list like fonts or colors loose focus when calling quill.updateContents(delta).
This is a problem when collaborating when another user and applying the OT changes.

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/
2. Click on the font button to open the font dropdown.
3. Call quill.updateContents(delta) in the console with some delta:
```javascript
quill.updateContents({
  ops: [
    { retain: 6 },
    { delete: 5 },
    { insert: 'Quill' }
  ]
});
```

**Expected behavior**:
The font dropdown should stay opened.

**Actual behavior**:
The font dropdown is closed.

**Platforms**:
Firefox 46 on Windows 7

**Version**:
1.0-beta.4

**Comment by jhchen** [comment]
Sorry that commit has a typo #743 was fixed not this issue
