### ISSUE TITLE
Cursor jumps to the beginning of the line when calling quill.updateContents(delta)

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#736]
[Describe the issue]
When applying a delta (collaborative editor) while the editor is focused, the cursor jumps to the beginning of the line.

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/
2. select all the text (ctrl+a) and delete it (backspace)
3. type the character 'a'
4. run the following in the console:
```javascript
setTimeout(function() {quill.updateContents({
  ops: [
    { retain: 1 },
    { insert: 'b' },
    { retain: 1 }
  ]
});}, 5000);
```
5. place the cursor after the letter 'a' in the editor and wait for the timeout to fire.

**Expected behavior**: [expected]
The cursor should be between 'a' and 'b':
a|b

**Actual behavior**: [actual]
The cursor jumps to the beginning of the line, before a:
|ab

**Platforms**:
Firefox 46 on Windows 7

**Version**: [version]
1.0-beta.4

**Comment by jhchen** [comment]
I believe this has the same root cause as #731 so folding it into that issue.
