### ISSUE TITLE
quill with Shadow DOM

### ISSUE THREAD

**Issue by rsmorley** [quilljs/quill#738]
Quill breaks when using shadow DOM. We are creating a chrome extension with webpack and we are using shadow DOM to isolate our app and prevent CSS bleed over from external sites. However, this breaks quill and other wysiwyg editors. 

**Steps for Reproduction**:
git clone https://github.com/rsmorley/quill-shadow-dom
Follow instructions in README.md

**Expected behavior**: 
Quill is functional. Text is editable

**Actual behavior**:
Quill editor is broken. Doesn't render correctly and text editing does not work (like deleting characters).

**Platforms**:
Chrome: 51.0.2704.79
React: 14.2

**Version**:
Quill: 0.20.1

**Comment by jhchen** [comment]
Changing the dependency to quill@1.0.0-beta.4 seems to be working fine?

**Comment by rsmorley** [comment]
Thanks for taking a look Jason.

I switched the dependency to 1.0.0-beta.4 but it still has the same broken behavior for me. I pushed a branch, quill-beta, to the above repo.

**Comment by jhchen** [comment]
Can you double check you rebuilt and did not load a cached version? Logging `Quill.version` is a sure way to tell. The only specific issue described was backspace not working so that is the only specific function I tested.  Backspace did not work on v0.20.1 but I see it working on 1.0.0-beta.4. I did not notice anything else obviously wrong, nor rendering problems (a screenshot would be helpful), nor errors in the console.

**Comment by rsmorley** [comment]
I added a consol.log and verified that it is the latest beta version is loaded and that the delete key is working.

However, there is a ql-clipboard div that is displaying and is editable. Is this expected behavior? Should I just hide it with css? (i entered the element and class name in the different editable fields to make them distinguishable)

// with shadow DOM
http://imgur.com/8rGlTzF

// without
http://imgur.com/cwTu6Mu

**Comment by jhchen** [comment]
Quill 1.0 now requires including a stylesheet for Quill to work correctly (previously Quill injected the rules but this bumped into CSP implementations). The most basic one is http://cdn.quilljs.com/1.0.0-beta.4/quill.css which includes no theming rules but does include essential ones like hiding the clipboard container. You can also quill.snow.css or quill.bubble.css for a themed stylesheet (which also includes the base rules).
