### ISSUE TITLE
Multiple output engines (including Markdown)

### ISSUE THREAD

**Issue by ollym** [quilljs/quill#74]
It would be amazing if the output generated could be in formats other than just HTML. Like Markdown and others.

**Comment by akshatpradhan** [comment]
I skimmed the comments but I wasn't sure about the consensus. Will Quill.js's toolbar support Markdown syntax?

**Comment by jhchen** [comment]
This functionality should be a module but I'm not sure there is consensus on how it should be implemented. Also there is not a 1:1 mapping between the formats Quill and Markdown supports so that will have to be addressed somehow. Some of it will be resolved as Quill supports more formats and at some point it might become a superset.

**Comment by akshatpradhan** [comment]
@jhchen Would it be possible to just map to GH flavored markdown, for now, and later we can figure out how to support other markdown flavors?

I would really like Markdown syntax.

**Comment by rvinay88** [comment]
:+1:

**Comment by ecmyers** [comment]
:+1:

**Comment by rhythmus** [comment]
Very inspiring wysiwyg Markdown editing project @ http://abnerlee.github.io/typora/2015/03/11/why-typora/

**Comment by dlo** [comment]
I wanted to mention that this is something that I'd *really* love to contribute towards if there's any suggested approaches. We're using Quill on a client project and Markdown output would be preferable. Thanks again @jhchen for the great editor!

**Comment by jhchen** [comment]
Quill outputs a [Delta](http://quilljs.com/docs/deltas/) via [`getContents()`](http://quilljs.com/docs/api/#quillprototypegetcontents) that provides a structured and consistent data structure that would be a good starting point in converting to markdown.

**Comment by ollym** [comment]
@jhchen we're looking at starting building a markdown editor as described. Did I read somewhere that you're working on v2? We're currently looking at either trix or quill as base frameworks for this job. Do you have any thoughts about how best to approach this and which direction to take?

**Comment by jhchen** [comment]
Quill is on its way to [1.0](http://quilljs.com/blog/the-road-to-1-0/) which will support headers and nested lists. I'm not intimately aware of what you are trying to build other than the formatting features that exist in markdown so the suggestion would be to look at the formats that each editor supports. Many other subjective elements are in play but I'm obviously biased.

**Comment by jhchen** [comment]
The 1.0 beta has been out for a while with headers and nested lists added as well. Quill supports formats that Markdown does not and there are multiple syntaxes for Markdown formats. How to deal with these ambiguities is likely preferential depending on the user and I do not believe it should be built into Quill core. With `getContents()` one can trivially output to Markdown with their own preferences.

**Comment by chrisshroba** [comment]
@jhchen Any suggestions for "trivially outputting to markdown"? It seems there are an abundance of Markdown -> HTML converters and Markdown -> AST converters out there, and a couple HTML -> Markdown converters, but I can't seem to find any AST -> markdown converters, and generating markdown manually from Deltas seems like it would be a lot more error prone than generating an AST which could be fed into a tried-and-tested converter to get markdown.

I know I could just grab the innerHTML of the editor and feed that to an HTML -> Markdown converter, but it seems like the Deltas (not the HTML) should be used as the source of truth.

**Comment by iSDP** [comment]
There's a Markdown spec now: https://commonmark.org/

**Comment by mkurz** [comment]
Also see "[A formal spec for GitHub Flavored Markdown](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown)" from the GitHub blog

**Comment by iSDP** [comment]
Damn perfect, I really hope for more GFM support in Quill, existing editors make use of CodeMirror, which has major trouble with IME on mobile 😐 

Basically, you need to press space twice and whatnot on default keyboards 😕

**Comment by rhythmus** [comment]
@chrisshroba @jhchen remark and mdast (both by the same author) is what you might be looking for:

https://github.com/wooorm/remark
https://github.com/syntax-tree/mdast

It’s GFM and CommonMark compliant already, and features a plugin architecture to add any desired syntax extensions.

**Comment by rhythmus** [comment]
Here’s another contender: [Slate.js](https://github.com/ianstormtaylor/slate)

**Comment by paulcarroll** [comment]
@rhythmus I certainly would've considered something like Shadow DOM indeed if it were available waaaay back when I did this, but as I no longer work for the company I wrote the editor for it's not high on my priority list. Having said that I'm not sure if Shadow DOM would alleviate the difficulties I had with the selection API (that was the particular pain point for me as each browser - and version - had different ideas about how to handle a keypress that inserted content, deleted content, the backspace key etc... it was awful.

I did use rangy at the time which served a purpose.... but was a difficult to debug collection of hacks and workarounds (still, a most commendable effort from the author and all due respect given!).

Thanks for the detailed and great comment though, it really ties together all the issues showing how MD output really isn't possible without tackling the problem holistically

**Comment by jzahka** [comment]
@ourmaninamsterdam Do you still recommend scribe + marked + toMarked as a decent stack for editor + bidirectional html <> markdown conversion? Do you know of any RTE's that output markdown since the time of this conversation? 

CkEditor5 supports markdown output https://docs.ckeditor.com/ckeditor5/latest/features/markdown.html but, sigh, does not support IE 11.

cc @leeoniya would love your take on the best way to do this in present day.

**Comment by leeoniya** [comment]
these days i'd use either prosemirror or mobiedoc. each has its own internal doc format with both html and markdown being simply renderers of this.

https://prosemirror.net/examples/markdown/
https://bustle.github.io/mobiledoc-kit/demo/

**Comment by leeoniya** [comment]
TIL, this open source project shamefully deletes constructive, unoffensive comments on closed issues. quilljs looks ripe for inclusion into SV's superfund list [1], where it [fittingly] appears to reside.

😞 ciao!

[1] https://www.nytimes.com/2018/03/26/lens/the-superfund-sites-of-silicon-valley.html

**Comment by duhaime** [comment]
@jhchen you mentioned above "With `getContents()` one can trivially output to Markdown with their own preferences." 

Is there any chance you could show us what you mean?
