### ISSUE TITLE
When pasting/typing within a blockquote a new line creates an entirely new blockquote element

### ISSUE THREAD

**Issue by auralon** [quilljs/quill#742]
Newlines are creating a new element, when they should break within the blockquote element.

**Steps for Reproduction**

1. Create a block quote
2. Type some text then hit enter
3. Type some more text

**Expected behavior**: Should break within the same blockquote element

**Actual behavior**: Creates a new blockquote element and newline text becomes new quote entirely

**Platforms**: 48.0.2564.116 (64-bit) on Elementary Freya (Ubuntu 12.04)

**Version**: 1.0.0-beta.4

**Comment by auralon** [comment]
The same applies for code blocks (wrapped in `<pre>`)

**Comment by auralon** [comment]
To clarify, I want to produce....

    <blockquote>This is the first line of the quoted text<br>
        This is the second line<blockquote>

... but I get...

    <blockquote>This is the first line of the quoted text</blockquote>
    <blockquote>This is the second line</blockquote>

Which messes up styling (eg: using before psuedo element to added a quote icon).  This also messes up the code contained in the `<pre>` tags too.  I'm using highlight.js to style this code, but because each line is within it's own `<pre spellcheck="false">` then it can't process it properly.

**Comment by jhchen** [comment]
This is working as designed at the moment. It is perfectly possible to create CSS rules that only affect the first or last `<pre>` or `<blockquote>`. The rounded corners to work in the existing code block implementation is an example of this.

**Comment by auralon** [comment]
Sure, I realise that I can use certain css selectors to style quotes and codeblocks to mask this particular quill behaviour, but that wouldn't help with the conflict that is being hit with `highlight.js` (a code block syntax highlighter), which expects an entire code block to be within a single `<pre>` tag.  

As soon as each line of a code snippet is wrapped in a `<pre>` tag, then it breaks the highlighting and syntax detection.  It would still be great to amend this quill behaviour, to increase cross-compatibility with packages like `highlight.js`.

**Comment by jhchen** [comment]
#723
