### ISSUE TITLE
isBlank returns false when the default block tag is changed

### ISSUE THREAD

**Issue by fernandogmar** [quilljs/quill#743]
Hi peeps,

Just one minor thing:

When the default block tag is changed from P to DIV following these steps:

```
            var Parchment = Quill.import('parchment');
            var Block = Parchment.query('block');
            Block.tagName = 'DIV';
            Quill.register(Block, true);
```

editor.isBlank() method always returns false!! :'( so the placeholder is never showed

**Version**:
1.0.0-beta4

Is there a workaround? do you think it is a bug?
Thanks in advance

**Comment by jhchen** [comment]
Fixed in https://github.com/quilljs/quill/commit/c0a78941c733a8427da95e594b0ffc4f4b76f1fc
