### ISSUE TITLE
Bubble theme toolbar doesn't stay open, for choosing multiple toolbar items on selected text

### ISSUE THREAD

**Issue by WriterStat** [quilljs/quill#744]
I type asdfg, I select it, bubble toolbar pops up. Woot! =)

I select bold in the toolbar, and the bubble tool bar automatically goes away before I can do anything else on the toolbar.

Can I set it so that it stays open so I could choose both bold and italics for my text selection. How?

Trying to un-select, the already currently selected text, then re-select it again for the bubble toolbar to come back up isn't intuitive/easy for a user. 

Also means, on current version to bold, italics, and make text a link. A person would have to select text and bold it. Then click somewhere else in the doc, re-selecting the same selected text doesn't work, no bubble, and then come back and re-select the text again and italics, then click somewhere else in the doc to un-select the selected text and then re-select the same text again a third time to make it a link.

I'd like the bubble toolbar instead only go away when you click outside the selected text, thereby un-selecting it in the document, how to set?

Thanks!
 
Version 1.0 is coming along, thanks for all the hard work!

**Comment by jhchen** [comment]
It should stay open--it closing is a bug.

**Comment by WriterStat** [comment]
Understood. Thanks! And for the software.
