### ISSUE TITLE
font size is lost in copy&paste

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#749]
**Steps for Reproduction**

1. Visit http://beta.quilljs.com/
2. Copy the first line with 'Heading' font size
3. Paste in a new line

**Expected behavior**:
The pasted line should have 'Heading' font size.

**Actual behavior**:
The pasted line has 'Normal' font size

**Platforms**:
Chrome 51 on Windows 7

**Version**:
1.0-beta.5

**Comment by jhchen** [comment]
I think this has the same root cause as #696
