### ISSUE TITLE
Cursor position off by one when immediately entering character after click a format btn

### ISSUE THREAD

**Issue by abejdaniels** [quilljs/quill#752]
Clicking a format then inserting letters quickly after results in the cursor position to lag by 1. 

**Steps for Reproduction**

1. Visit beta.quilljs.com
2. Click any type of format
3. Quickly hit 3-4 keys at the same time

**Expected behavior**: characters are entered, cursor position is updated properly and is at the end of the string. (If that's where you stopped typing.)

**Actual behavior**: characters are entered, occasionally the cursor position lags and will not be at the end of the string. 

**Platforms**: All

**Version**: beta.4

**Comment by jhchen** [comment]
I'm not able to reproduce this. This is certainly all platforms? Not low resourced ones like mobile?

**Comment by abejdaniels** [comment]
Tried it in every browser on my computer. You need to click a format, and immediately starting mashing keys to have it happen every time. It isn't that huge of a bug because it's not like someone presses letters like crazy and expects everything to work. 
Click bold, immediately hit 3 keys at the same time. It looks like this: (pipe char = cursor.) as|df
continuing to do so would eventually do this asdafdsfdsafdsa|asfdafdsfdsafdsafdsa, instead of staying at the end of the string, it lags. I am on windows 10 on a relatively fast laptop.

**Comment by abejdaniels** [comment]
Here is what it looks like in real time. Excuse me for not selecting for the gif recorder to record mouse.
http://i63.tinypic.com/2pu0kdl.gif

**Comment by benbro** [comment]
I can reproduce with latest chrome and firefox on windows 7.
1. Visit beta.quilljs.com
2. type fast random characters without stopping.
3. click on the bold button every few seconds while still typing characters fast.
