### ISSUE TITLE
Image can not be resized on Chrome 51 / Linux

### ISSUE THREAD

**Issue by davelozier** [quilljs/quill#753]
Image can not be resized after inserting with Chrome on Linux (Ubuntu 16.04). Also, pre existing image in editor contents can not be resized. Firefox 47 is working correctly.

**Steps for Reproduction**

1. Visit http://codepen.io/davelozier/pen/KMgNze in Chrome on Linux.
2. Try to select the image for resizing. 
3. Insert new image http://quilljs.com/images/browsers.png
4. Try resizing.

**Expected behavior**: Resize handles should be present and allow image to be resized.

**Actual behavior**: No resize handle are present. The image can not be resized.

**Platforms**: Chrome 51 on Linux (Ubuntu 16.04) - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Version**: 1.0.0-beta.5

**Comment by jhchen** [comment]
Actually image resize handlers should not be present. The feature is inconsistent between browsers and buggy in browsers themselves (try scrolling with the image handlers present in FF) for Quill to support. I will make a change to remove them in Firefox.

**Comment by davelozier** [comment]
Sounds good to me! I prefer users not be able to resize their images.
