### ISSUE TITLE
Blockquote removed from initial editor content

### ISSUE THREAD

**Issue by davelozier** [quilljs/quill#754]
The blockquote in initial editor content is removed. It can be added back using the editor though.

**Steps for Reproduction**

1. Visit http://codepen.io/davelozier/pen/KMgNze in Chrome on Linux.
2. Observe the line "Hello again! This is a block quote." In the HTML you can see that it exists within the initial editor content. 
3. Place cursor after line and select the quote button. The blockquote tag is added. Also note, the quote button is not given the ql-active class when the blockquote has focus.

**Expected behavior**: Initial blockquote within the editor contents should not be removed.

**Actual behavior**: Initial blockquote is stripped from the editor when initialized.

**Platforms**: Chrome 51 on Linux (Ubuntu 16.04) - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Version**: 1.0.0-beta.5

**Comment by OctaneInteractive** [comment]
Any update on this? I'm using Vue2Editor 2.10.2, and it's stripping blockquotes and both ordered and unordered lists (perhaps more, but I've not finished testing).
