### ISSUE TITLE
Add title to a link using insertText or formatText

### ISSUE THREAD

**Issue by Vadorequest** [quilljs/quill#757]
Hi.

I'd like to insert a `title` attribute when creating/updating a link.

```cjsx
        link = document.querySelector('#linkInput').value
        console.log 'link', link

        if not @state.modal.hasText
            # Insert a new link, use the same link as text.
            @editor.insertText(range.start, link, _.merge({
                'link': link
                'title': link # --> This doesn't work
            }, @state.activeWords.link));
        else
            @editor.formatText(range, 'link', link, 'user')
```

I looked at the possible `formats` http://quilljs.com/docs/formats/ and at the docs but couldn't find anything for "title". Do you have any example?

Thanks.

**Comment by jhchen** [comment]
It's possible to use [`addFormat`](http://quilljs.com/docs/api/#quillprototypeaddformat) to define the title format first and then you can run the `insertText` code you have. With 1.0 you can do this with [Attributors](https://github.com/quilljs/parchment#attributors) though I have not had a chance to write a good guide yet.

**Comment by Vadorequest** [comment]
Thanks for the fast answer :)
