### ISSUE TITLE
Keep selection style on blur

### ISSUE THREAD

**Issue by emanuelbsilva** [quilljs/quill#758]
Hi,

Is there a way to keep the selection style (greyed out) even when focusing outside the editor?

In my case i have several input fields (for font size, colorpicker, etc) which affect the current selection. But when focusing on these input fields quill stops representing the selected fields, which is a usability issue.

**Comment by jhchen** [comment]
There is not an easy way currently but can you elaborate on your use case?

**Comment by emanuelbsilva** [comment]
Hi,

My case is pretty straightforward, i have a custom made toolbar with custom made "settings" to edit several formats of the quill editor using the current selected text (`editor.getSelection()`).

This works well for buttons (toggle bold/italic/etc) because i can save the selection before the editor looses focus and set the selection again after making the changes. But for inputs (ie custom font sizes) i cannot use this trick, because it either focus on the editor (and the user cannot enter text on the form) or it looses selection of the text and the user doesn't know which text it's being changed.

I would be happy to help develop this feature as i think it's a core feature for any non trivial text editing. I was thinking about having a div on top of the selected text to show the selection and maybe having it work with specific focus and blur methods on the editor.

If you give some lights on how to accomplish this i would really like to develop the feature as i think this project is very cool and i would like to contribute.

**Comment by jhchen** [comment]
Appreciate the offer to contribute. The overlay div idea seems reasonable and I can't think of a better one at the moment. The challenge here will be to make it play well with other UI interactions (scrolling, content changes, focus changes, etc) which my gut reaction says is quite difficult. People are also trained to noticed one pixel imperfections when it comes to UI elements in the editing content so the margin for error is also very low. If these two facts do not deter you then I'm happy to give feedback on a more detailed implementation proposal.

**Comment by emanuelbsilva** [comment]
I would like to have your implementation proposal yes. This is a strong requirement for me and i'm willing to spend some time in having this feature on quill. When you do that i'll start digging in through the code.
Thanks alot for you effort.

**Comment by emanuelbsilva** [comment]
Any words on this? Thanks.

**Comment by jhchen** [comment]
I do not have an implementation proposal. What I was offering was to give you feedback on yours.

**Comment by emanuelbsilva** [comment]
Ok! I misunderstood you then. I'll get into it then. Thanks.

**Comment by g-borgulya** [comment]
Hi,
May I ask why did you close this issue? This is an important usability question in my opinion. I have exactly the same problem. Basically now it's not possible to create custom toolbar dropdown menus for formatting, as the user doesn't see which part of the text it would affect.

**Comment by jhchen** [comment]
It is not possible to implement what was is being suggested natively in all supported browsers. It is possible to fake it in some way but there are many possibilities so it would be better to evaluate implementation proposals separately as separate Issues or PRs.

**Comment by g-borgulya** [comment]
I see, thank you!

**Comment by radonirinamaminiaina** [comment]
Hello There,

Is there a new about this issue? I face this issue on firefox only.
Here what I try to do:
- I select a text
- I use antd slider to control font-size of the text
- The selection is lost on click of the slider control.

Here a part of code what I did: (into quill blur)

`if (event.relatedTarget) {
      if (!event.relatedTarget.closest('.dlps-modal-text')) {
        const getUid = this.currentEditor.current.getAttribute('data-uid');
        this.quill.enable(false);
        if (this.props.onUpdateText) {
          this.props.onUpdateText({ id: getUid, editor: this.currentEditor.current.querySelector('.ql-editor') })
        }
        if (this.quill.root) {
          this.quill.root.classList.remove('editor--wysiwyg-focus');
        }
      }
      if (this.lowerCase(event.relatedTarget.tagName) === 'input') {
        event.relatedTarget.focus();
      } else {
        if (event.relatedTarget.closest('.ant-slider')) {
          const range = this.quill.getSelection(true);
          if (range) {
            // work on chrome but doesn't work on firefox
            this.quill.setSelection(range.index, range.length);
          }
        }
      }
      if (event.relatedTarget.classList.contains('ql-editor')) {
        this.removeAllFocused();
      }
    }`

**Comment by tkefauver** [comment]
Hi, I know this is old and may not work in all browsers but in Chrome 100 at least a simple work-around is to watch when selection range is null and last range exists:

`quill.on('selection-change', function (range, oldRange, source) {
        if (!range && oldRange) {
            //blur occured
            quill.setSelection(oldRange);
        }
    });`

**Comment by bvonbla** [comment]
Nice! But it has the drawback that when a element loses focus due to scrolling the window scrolls back to where the selection is set. This prevents one from scrolling the editor out of view.
The solution i found was calling 'quill.setfocus()' before executing the desired quill action. (quill v2.0.0-dev.4)

**Comment by kakolokolcev** [comment]
I propose to come up with an official solution to this problem, I also came across a similar case.
