### ISSUE TITLE
quill.getSelection() doesn't always return correct current position when called in text-change handler

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#763]
Within the text-change event handler, I'm trying to get the current position of the cursor. However I'm seeing in this specific case that the cursor position returned by the call to quill.getSelection() appears to be the position right before the edit happened.

Maybe this is an off-by-one issue or is that the new cursor position has not yet synced when called immediately within the text-change handler? Do I need to call quill.update() to ensure getting latest cursor position?

**Steps for Reproduction**

1. Visit beta.quilljs.com
2. Set editor contents to "test"
3. Add following in console:
```
quill.on('text-change', function(delta, prevDelta, source) {console.log(quill.getSelection().index)})
```
4. Place mouse cursor at the end of line with the word test on it
5. Hit enter

**Expected behavior**:
Console log shows selection index of 5

**Actual behavior**:
Console log shows selection index of 4

**Platforms**:
Chrome 51 on Mac 10.11

**Version**:
Quill 1.0 Beta 6

**Comment by jhchen** [comment]
The issue is the cursor is not yet synced. For some text changes an external function is saving and restoring the cursor position, in this case the keyboard module. Using _.defer (if using lodash or underscore) or a setTimeout of 1 in your handler should fix this.

**Comment by sachinrekhi** [comment]
Putting the text-change handler function within a setTimeout of 1 does now result in getting the correct cursor position.

However, it creates new challenges. Since the text-change handler is now within a setTimeout, calls to quill.update() no longer act in it's desired blocking/synchronous mode where text-change events have fired and processed. Since the text-change handler is now within a timeout, it looks like you can't be guaranteed that the processing of the text-change event has happened on the calls subsequent to quill.update() which is now creating other challenges on OT.

**Comment by jhchen** [comment]
What are you using the cursor location for in the text-change handler? The challenge is some text changes will incorrectly move the cursor or lose it completely in some browsers so it is sometimes saved and restored before making changes. The text-change event fires before this restore step.

**Comment by sachinrekhi** [comment]
I'm trying to get the current cursor position after the text change so I can send the text change and the new cursor position over to other viewers of the doc (remote viewers update with updateContents() and my own implementation of multi-cursor).

My workaround now is that I don't wrap the entire text-change handler in a setTimeout (to avoid the quill.update() issues) and instead wrap just the part where i get the cursor in a setTimeout and ship that over to the remote servers separately from the text change).

**Comment by jhchen** [comment]
I see. The next beta will have an [editor-change](https://github.com/quilljs/quill/commit/10e0fd63225a36612159fa843d511bbe49a9d438) event that will include silent selection-change events so that might be another way to send relevant cursor changes.

**Comment by sachinrekhi** [comment]
You might want to add documentation for this new editor-change event on the website.

**Comment by jhchen** [comment]
Yes this has now been added thanks!

**Comment by Attrash-Islam** [comment]
I faced some infinite function calls until Stacktrace crash. Ended up with this solution.

![image](https://user-images.githubusercontent.com/7091543/92884213-4f995f80-f41a-11ea-8147-97b20a398e9c.png)
