### ISSUE TITLE
quill.getBounds() returns incorrect position on an empty bullet

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#765]
When you call quill.getBounds() when you are on an empty bullet, it incorrectly returns the location as the beginning of the line instead of to the right of the bullet where the cursor in fact is.

![get_bounds](https://cloud.githubusercontent.com/assets/192650/16251509/730b2908-37db-11e6-9864-71ff571bf447.png)

This is a regression from Quill 0.20.1

**Steps for Reproduction**

1. Visit beta.quilljs.com
2. Create a bullet
3. Indent it
4. Hit enter

**Expected behavior**:
getBounds() returns the position of the current cursor, which is to the right of the bullet point

**Actual behavior**:
getBounds() returns the position at the beginning of the line, which is to the left of the bullet point

**Platforms**:
Chrome 51 on Mac 10.11

**Version**:
Quill 1.0 Beta 6

**Comment by jhchen** [comment]
I think https://github.com/quilljs/quill/commit/f53183fd6850ac32bec3be3084290f6ef566c590 also fixed this issue. Can you confirm?

**Comment by sachinrekhi** [comment]
Sure. What's the best way for me to test pre-release versions of Quill within my app? For my app I normally just use npm to install specific quill releases (ie. npm install quill@1.0.0-beta.8). I've done Quill development as well via a fork of Quill and just testing within the development Quill test app. But is there a way I can either install the pre-release version via npm or link the development version to my main app?

**Comment by jhchen** [comment]
Just pushed a new beta version so feel free to test the standard way. Otherwise you'd normally have to set up the [dev environment](https://github.com/quilljs/quill/blob/develop/.github/DEVELOPMENT.md) and build a local copy.

**Comment by sachinrekhi** [comment]
Ok so you do now get the right bounds for a non-indented bullet in Quill 1.0 Beta 9. But the bounds are still incorrect for multiple-levels of indent. Regardless of whether you indent more, getBounds() is returning the position as if it was a non-indented bullet.

**Comment by jhchen** [comment]
Hmm [this](http://codepen.io/quill/pen/dXdddY) seems to be working for me. Are you using the updated stylesheet as well?

**Comment by sachinrekhi** [comment]
Yes, I updated the stylesheet as well.

The specific issue is when the bullet is empty. Take a look at this code pen: http://codepen.io/sachinrekhi/pen/grvZwv

**Comment by jhchen** [comment]
Okay sorry missed the empty detail.
