### ISSUE TITLE
Cannot import modules/link-tooltip

### ISSUE THREAD

**Issue by lingxuan630** [quilljs/quill#766]
[Describe the issue]

quill.js:4213quill Cannot import modules/link-tooltip. Are you sure it was registered?
quill.js:4213[quill:theme] Cannot load link-tooltip module. Are you sure you registered it?
**Steps for Reproduction**

1. I import http://cdn.quilljs.com/1.0.0-beta.5/quill.js to page, but get error.

**Expected behavior**: [expected]

**Actual behavior**: [actual]

**Platforms**: [ex. Chrome 51 on Win 10]

**Version**: [version]
1.0.0-beta.5

**Comment by sachinrekhi** [comment]
You don't need to do this in Quill 1.0 anymore. Just take out the import and you'll still have access to the link tooltip.

**Comment by jhchen** [comment]
Sachin is correct
