### ISSUE TITLE
Error on redoing new line/paragraph

### ISSUE THREAD

**Issue by mshamaiev-intel471** [quilljs/quill#767]
Error when trying to redo new line/paragraph
`quill.js:5216 Uncaught TypeError: leaf.position is not a function`

**Steps for Reproduction**

1. Visit [beta.quilljs.com] (http://beta.quilljs.com/standalone/snow/)
2. Hit `Enter`
3. Hit undo `Cmd+Z`
4. Hit redo `Cmd+Shift+Z`

**Expected behavior**: correct redoing of new line

**Actual behavior**: no new line and error in console

**Platforms**: Firefox 47, Firefox 49a and  Chrome 51 on OS X 10.11.5

**Version**: 1.0.0-beta.6

**Comment by benbro** [comment]
Related?
https://github.com/quilljs/quill/issues/740

**Comment by jhchen** [comment]
The two have different stack traces but it's likely the it is same root cause of being in an invalid state. The referenced commit fixes this one's for sure, given the reproduction steps.
