### ISSUE TITLE
setHTML

### ISSUE THREAD

**Issue by xiaoguozi** [quilljs/quill#770]
where is the setHTML method, is it deprecated?

**Comment by benbro** [comment]
Are you using 1.0-beta?
maybe this?
http://beta.quilljs.com/docs/api/#pastehtml

**Comment by jhchen** [comment]
@benbro is correct. Also please check http://beta.quilljs.com/guides/upgrading-to-1-0/

**Comment by baio** [comment]
Why pasteHtml move focus on editor, looks like bug ?
