### ISSUE TITLE
Create group editors

### ISSUE THREAD

**Issue by kolesoffac** [quilljs/quill#772]
I need connect few editors in one editor(one toolbar) with general navigation between them.
Thanks

**Comment by jhchen** [comment]
From the sparse details this looks like the same [issue](https://github.com/quilljs/quill/issues/771). Please do not post multiple issues for the same request.

**Comment by kolesoffac** [comment]
It isn't same request! Similar(use one toolbar), but isn't same(general navigation between subeditors).
