### ISSUE TITLE
CDN version of 1.0.0-beta6 has the wrong Cursor.CONTENTS

### ISSUE THREAD

**Issue by ersommer** [quilljs/quill#778]
Just noticed that `Cursor.CONTENTS` has the wrong value in http://cdn.quilljs.com/1.0.0-beta.6/quill.js

```javascript
Cursor.CONTENTS = 'ï»¿'; // Zero width no break space
```

The beta site (http://beta.quilljs.com/1.0.0-beta.6/quill.js) has the correct value (which is actually `\uFEFF`, but doesn't render as an actual character).

```javascript
Cursor.CONTENTS = '﻿'; // Zero width no break space
```

This causes the editor to render the `ï»¿` characters when it does operations involving the cursor.

**Version**: 1.0.0-beta.6

**Comment by jhchen** [comment]
Are you observing the problem (while using the Quill library) in your use case? If so what browser/OS?

When I try the [demo](http://codepen.io/quill/pen/KMWObp) with the cdn version it still works and a strict equality test with \uEFFF yields true. It's also very clear when it's the wrong character if you uncomment the line setting it to 'X'. Also if I download the file from the CDN and view in VIM it shows the correct \uEFFF.

So it seems like it might just be a source code rendering bug and not actually an issue with the build.

**Comment by ersommer** [comment]
Yup, looks like a rendering issue. I loaded http://cdn.quilljs.com/1.0.0-beta.6/quill.js on Chrome, IE, and Edge on Win10, and they all displayed `ï»¿`. If you copy/paste the code, the error persists. But downloading the file is fine. Maybe the CDN is missing a header or something for the proper encoding when viewing in the browser? 

```
Content-Type:application/javascript; charset=utf-8 // From the beta website
Content-Type:application/x-javascript // From the CDN
```

**Comment by jhchen** [comment]
Seems like application/javascript; charset=utf-8 is best practice anyways so I updated the CDN but seems like the issue remains.

```bash
curl -I cdn.quilljs.com/1.0.0-beta.6/quill.js
HTTP/1.1 200 OK
Content-Type: application/javascript; charset=utf-8
Content-Length: 388241
Connection: keep-alive
Date: Wed, 29 Jun 2016 23:38:46 GMT
Last-Modified: Wed, 29 Jun 2016 21:45:47 GMT
```

**Comment by fnemec** [comment]
Just add charset="UTF-8" to your script tag and you're good.

`<script src="http://localhost/furniture/quill/quill.js" type="text/javascript" charset="UTF-8"></script>`

**Comment by guille-alibrate** [comment]
Tried adding the charset but it still adds the bom "\uFEFF" character .

`<script src="https://cdn.quilljs.com/1.3.6/quill.min.js?refresh=1" charset="UTF-8"></script>`
