### ISSUE TITLE
List delta representation in 1.0 incompatible with 0.20.1

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#781]
It looks like Quill 1.0 represents unordered lists with attribute: list: "bullet" and an ordered list with attribute list: "ordered".

Compare this to Quill 0.20.1, where an unordered list had attribute bullet: true and an ordered list had attribute list: true.

The behavior of Quill 1.0 when it encounters the old representation of bullets and lists is simply to strip them out, resulting in no bullets being shown in the editor and also getContents() not having the attribute in it.

This unfortunately creates a backwards compatibility challenge, requiring all server-stored deltas to go through a migration process all at once and also ensuring that all clients upgrade to the latest version of Quill all at once. And there is data loss if an old-format document is accidentally loaded in the new Quill.

At the very least this should be documented in the [Upgrading to 1.0 Guide](http://beta.quilljs.com/guides/upgrading-to-1-0/).

I'm wondering if you considered other potential approaches to handling this? I thought you mentioned that with images, Quill would load the old format but only output the new format. Could a similar strategy be used with bullets?

**Comment by sachinrekhi** [comment]
Probably also helpful to document the change in image representation as well.

**Comment by sachinrekhi** [comment]
I also noticed that inline formats can no longer be applied to newlines. So if you have bold spanning two lines, Quill 0.20.1 would have produce a single insert operation with a newline character in it with attribute bold:true. Quill 1.0 breaks this up into 3 insert operations: the first for the line content with a bold:true attribute, the next for the newline with no attributes, and the third with the subsequent line content and attribute bold:true.

Quill 1.0 automatically corrects this when it receives the former input, but may still be useful to document as my migration script needed to take care of this.

**Comment by jhchen** [comment]
I added a change that handles using old list deltas but similar to images, will output the new format. I'll add a note to the 1.0 docs mentioning this.

I'm a bit undecided about inline formats. The ideal goal is to support them as in some cases they are relevant (like a color on a bulleted line should change the color of the bullet).
