### ISSUE TITLE
quill.insertText() buggy formatting

### ISSUE THREAD

**Issue by DadaMonad** [quilljs/quill#782]
Under circumstances, `quill.insertText(pos, text, format)` doesn't behave correctly: 

**Steps for Reproduction**

1. Visit beta.quilljs.com (or use quill@1.0.0-beta.6)
2. `quill.setContents([{"insert":"s"},{"attributes":{"bold":true},"insert":"s"},{"insert":"XXXXX"},{"attributes":{"strike":true},"insert":"HHH"},{"insert":"\n\n\n"}])`
3. `quill.insertText(10, 'iiiiii', { bold: false, strike: false })`

**Expected behavior**: The inserted text 'iiiiii' is *not* bold

**Actual behavior**: The inserted text is bold

**Platforms**: Chrome Version 51.0.2704.106 (64-bit)

**Comment by sahanDissanayake** [comment]
I think I'm facing the same issue,

When I try to inside some text inside a bold, italic text the text inserted should inherit the styles from the parent right ?

**Comment by DadaMonad** [comment]
@sahanDissanayake To my understanding you are right. But you are facing a different issue. I explicitly stated that the inserted text should not be bold, but it turned out to be bold. I think you should open another issue with steps to reproduce your issue.
