### ISSUE TITLE
Cut & paste not working

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#785]
While **COPY** & paste is working fine, **CUT** & paste does not seem to be working properly. When I CUT (using Command+X) the cut content is properly removed from the editor. But when I subsequently paste in the editor, the previous content in the clipboard is pasted as opposed to the recently cut content.

**Steps for Reproduction**

1. Visit beta.quilljs.com
2. Cut the first word in the editor, "Rich", using Command+X
3. Go to the end of the line and press Command+V

**Expected behavior**:
The word Rich is pasted at the end of the line

**Actual behavior**:
What's actually pasted is whatever was previously in the clipboard before the cut of Rich

**Platforms**:
Chrome 51 on Mac 10.11

**Version**:
Quill 1.0 Beta 6

**Comment by webcarrot** [comment]
Change onCut in /modules/clipboard.js :

```js
  onCut(e) {
    if (e.defaultPrevented) return;
    this.onCopy(e);
    let range = this.quill.getSelection();
    this.quill.deleteText(range, Quill.sources.USER);
    this.quill.setSelection(range.index, Quill.sources.SILENT);
  }
```

to:

```js
  onCut(e) {
    if (e.defaultPrevented) return;
    this.onCopy(e);
  }
```

or ?:

```js
  onCut(e) {
    if (e.defaultPrevented) return;
    this.onCopy(e);
    setTimeout(()=>{
        let range = this.quill.getSelection();
        this.quill.deleteText(range, Quill.sources.USER);
        this.quill.setSelection(range.index, Quill.sources.SILENT);
    },0);
  }
```
