### ISSUE TITLE
Remove Long restriction for primary incremented database keys

### ISSUE THREAD

**Issue by mdedetrich** [quilljs/quill#787]
According to the quill docs

> It is possible to define a column that is a key generated by the database. It will be ignored during insertions and returned as the result. Note that it accepts only values that can be read as Long.

The restriction for the type (in this case `Long`) should be removed. Its fairly common to use UUID's (instead of Long's) for database ID's, and databases such as PostGres provide a function to
guarantee unique UUID's specifically for this use case (i.e. `gen_random_uuid();`).

Not sure why the `Long` restriction is there (maybe because Quill needs to know how to map the equivalent database type to Scala, and for Long its already know)? I suppose that Quill should be able to just reuse an implicit `mappedEncoding` for this case.

**Comment by benbro** [comment]
Are you sure the issue is related to this project?

**Comment by mdedetrich** [comment]
Whoops, wrong Quill... Apologies
