### ISSUE TITLE
Can't toggle off code block formatting

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#789]
You can no longer toggle off code block formatting after applying it.

This appears to be a regression from Quill 1.0 Beta 6

**Steps for Reproduction**

1. Visit beta.quilljs.com
2. Clear editor
3. Add a line of text
4. Select full line of text
5. Format using the code block icon in the toolbar
6. Select full line of text again
7. Hit the code block icon in the toolbar again to toggle off code block formatting

**Expected behavior**:
The text no longer is formatted in a code block

**Actual behavior**:
The text remains formatted in a code block

**Platforms**:
Chrome 51 on Mac 10.11

**Version**:
Quill 1.0 Beta 8

**Comment by jhchen** [comment]
This change https://github.com/quilljs/quill/commit/9ea959d37ba2bf789fc965988b7bdd8d9ba1f685 seems to have fixed the issue in the 1.0 branch.

**Comment by dhershman1** [comment]
I still seem to be having issues with when I start a code block and then click it again to end or try to leave the code block I am stuck, if I don't leave a space to click out of I would be stuck unless I created a blockquote or something else

**Comment by sachinrekhi** [comment]
@dhershman1 are you using Quill 1.0 Beta 8? If so, the fix has not yet been pushed to a new release. Will be in next release.

**Comment by dhershman1** [comment]
Well that explains it, I guess I didn't notice when I looked lol.

**Comment by sachinrekhi** [comment]
I'm still seeing this issue occur in Quill 1.0 Beta 9 in certain cases.

Slightly different repro:

1. Visit beta.quilljs.com
2. Clear editor
3. Type "test" on the first line
4. Hit enter & enter
5. Type "some code" on next line
6. Type "again" on the next line
7. Highlight some code & again lines and apply code block formatting
8. Attempt to remove code block formatting from the last "again" line

![screen shot 2016-07-18 at 6 58 49 pm](https://cloud.githubusercontent.com/assets/192650/16936210/cde9a9f0-4d19-11e6-95dd-be3d5bcc4811.png)

**Comment by naveenkn456** [comment]
Is this resolved? I am facing the same issue.
