### ISSUE TITLE
quill.keyboard.addBinding() does not override default browser keyboard shortcut in Safari

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#790]
I'm trying to set a keyboard shortcut via quill.keyboard.addBinding() call. However, when the keyboard shortcut is already mapped by the browser, Quill is not properly overriding the default keyboard shortcut behavior.

The documentation suggests that by default the handler will stop propagation unless you return true. I'm not returning true, but still seeing propagation to the browser default behavior.

Maybe in addition to the evt.preventDefault() call, a evt.stopPropagation() call is also required within the underlying 'keydown' event listener?

This seems to be a browser-specific issue as the handler works fine in Chrome & Firefox, but not in Safari.

**Steps for Reproduction**

- Visit beta.quilljs.com
- Add following keyboard handler:
```
        this.editor.keyboard.addBinding({key: '1', shortKey: true}, (range, context) => {
            if (context.format['header'] !== 1) {
                quill.formatLine(range, 'header', 1, Quill.sources.USER)
            } else {
                quill.formatLine(range, 'header', false, Quill.sources.USER)
            }
            quill.setSelection(range)
        })
```
- Press Command+1 on a line of text in the editor

**Expected behavior**:
The header formatting that I've associated with this keyboard shortcut should activate

**Actual behavior**:
Browser default keyboard shortcut behavior happens (switches to browser tab 1)

**Platforms**:
Safari 9.1.1 on Mac 10.11

**Version**:
Quill 1.0 Beta 8

**Comment by jhchen** [comment]
Is there an example web app that correctly overwrites these hotkeys? A quick test makes it seem like Safari does not overwriting these at all: https://jsfiddle.net/jm3m3oj9/1/

**Comment by sachinrekhi** [comment]
Ya, upon further testing this looks like a very specific limitation in Safari that prevents Cmd+1, Cmd+2, etc from being overriden. It turns out when I try to override other keys from their default behavior, like Cmd+S, it works just fine in Safari. Looks like they have a reserved set that can't be overriden.
