### ISSUE TITLE
Copy from Chrome URL bar to Safari Quill document does not work

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#791]
Looks like there may be a browser-specific issue with pasting in Safari. The specific scenario I found that didn't work for me is copying a url from Chrome's URL bar into a Quill editor in Safari.

**Steps for Reproduction**

1. Open Google Chrome
2. Navigate to some URL, say http://www.google.com
3. Copy the url from the URL bar
4. Open beta.quilljs.com in Safari
5. Paste url into Quill editor

**Expected behavior**:
URL is pasted into Quill editor

**Actual behavior**:
Nothing is pasted

**Platforms**:
Safari 9.1.1 on Mac 10.11

**Version**:
Quill 1.0 Beta 8

**Comment by jhchen** [comment]
Weird. This may be a limitation with Safari? Quill is just using the native copy and paste behavior in 1.0.0-beta.8. I'm not able to paste a copied URL from Chrome into Gmail composer or Google Docs either.

**Comment by sachinrekhi** [comment]
Aah, good point on Gmail and Google Docs not working as well. Looks like yet another Safari limitation.

The format the url is copied into the clipboard from Chrome is very different from other browsers (the others just copy the plain-text URL) and looks like Safari isn't handling the paste well. I assumed you were somehow parsing the clipboard content types yourself, but if not, sounds like it's the browser's limitation.
