### ISSUE TITLE
Copy/paste from one section of Quill document to another results in extra newline

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#792]
On copy/pasting content from one part of a Quill document to another, an extra newline is always being inserted whenever there is an empty line.

This is new behavior as of Quill 1.0 Beta 8

**Steps for Reproduction**

1. Visit beta.quilljs.com
2. Clear editor
3. Type "some text"
4. Hit enter twice
5. Type "and this is on the third line"
6. Copy/paste the 3 lines to the end of the editor

**Expected behavior**:
The exact 3 lines are copied

**Actual behavior**:
An extra newline is inserted, results in 2 empty lines between the 2 text lines

Copied:
![screen shot 2016-07-12 at 10 14 16 pm](https://cloud.githubusercontent.com/assets/192650/16792530/1149a664-487e-11e6-9f43-cd0278bac03a.png)

Pasted:
![screen shot 2016-07-12 at 10 14 22 pm](https://cloud.githubusercontent.com/assets/192650/16792532/1396aa7a-487e-11e6-8d3e-c773176a0b11.png)

**Platforms**:
Chrome 51 on Mac 10.11

**Version**:
Quill 1.0 Beta 8

**Comment by jhchen** [comment]
Also fixed with https://github.com/quilljs/quill/commit/78dc331436958bc54063c3dcc2246ee219f12e82
