### ISSUE TITLE
setHTML adds new line

### ISSUE THREAD

**Issue by dhawalbhanushali** [quilljs/quill#794]
When I use setHTML twice, each action takes the content to new line.

API: setHTML('hello,'); setHTML('how are you?');

Actual Result: 
hello,
how are you?

Desired Result:
hello, how are you?

Answer or any hint is appreciated.

**Comment by jhchen** [comment]
Assuming you are using this [setHTML](http://quilljs.com/docs/api/#quillprototypesethtml), the second call should overwrite all content so I'm not clear why both the desired and actual result is just "how are you?"

**Comment by dhawalbhanushali** [comment]
Apologies.

Corrected API: 

setHTML('hello,'); 
setHTML(getHTML() + 'how are you?');

**Comment by jhchen** [comment]
Take a look at the output of getHTML(). You will see it is `<div>hello</div>` so adding "how are you" renders on a new line since `<div>`s are block scope elements in HTML. In nearly all cases, Quill's other content modification [APIs](http://quilljs.com/docs/api/) are much easier and more powerful to use.

**Comment by dhawalbhanushali** [comment]
Is there any way we can avoid or manipulate this default quill structure? Yes I looked through the APIs but 'getHTML()' and 'set HTML()' are the ones that serve the purpose. In any way can CSS help me achieve the desired output?

**Comment by jhchen** [comment]
What's your use case

**Comment by dhawalbhanushali** [comment]
I want to append a new span to an editor that already has some content. Newly added content should not  default to new line. Rather it should fit inline if there is space available.

Example: Editor Contains
`<div><span>Hi</span></div>`

On adding 'How are you?' it should output
`<div><span>Hi</span><span>How are you?</span></div>`

and not
`<div><span>Hi</span></div<div><span>Hi</span></div>`

**Comment by jhchen** [comment]
Quill does not let you arbitrary set its HTML contents to provide a consistent user experience.

**Comment by dhawalbhanushali** [comment]
I am losing the HTML upon the use of `insertText`. Thank you for being patient. Will check what suits me the best.
