### ISSUE TITLE
Link tooltip does not always show up

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#799]
I'm experiencing another one of those intermittent issues, so no solid repro. But have a look at the this video as well: https://cl.ly/1y2I1Q43361L

Basically the link tooltip does not always show up when you place the cursor within a link in the document. It's very intermittent but consistently running into it.

**Steps for Reproduction**

1. Visit beta.quilljs.com
2. Click on each of the links to expose the link tooltip

**Expected behavior**:
Link tooltip is always exposed

**Actual behavior**:
Link tooltip is intermittently not exposed

**Platforms**:
Chrome 51 on Mac 10.11

**Version**:
Quill 1.0 Beta 9

**Comment by jhchen** [comment]
Looks like another long click issue..
