### ISSUE TITLE
Clicking on a formula scrolls the editor to the top

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#800]
**Steps for Reproduction**
Clicking on a formula or code block scrolls the editor to the top.

1. Visit http://beta.quilljs.com/
2. Scroll to the bottom
3. Click on the formula

**Expected behavior**: [expected]
The editor shouldn't scroll

**Actual behavior**: [actual]
The editor scrolls to the top

**Platforms**: 
Chrome 51 on Windows 7

**Version**: [version]
1.0-beta9

**Comment by benbro** [comment]
Firefox 47 on Windows 7

After clicking on the formula, it moves to the middle of the code block.
![quill-formula](https://cloud.githubusercontent.com/assets/75841/16938814/67ce0970-4d84-11e6-8ac6-75c85370791a.png)

**Comment by jhchen** [comment]
Currently the behavior is on focus, if there is no selection to be restored it sets the selection to the 0th position and scrolls there. Should clicking the formula button do nothing instead? If not then when the user types in the formula and hits enter, where should the formula be inserted?

**Comment by jhchen** [comment]
I'm not sure I follow the 2nd comment's instructions. It looks like there might be missing steps in entering a formula (x^2+ ...)?

**Comment by benbro** [comment]
In both instructions I mean clicking on the existing formula (x^2...) below the code block, not on the formula button.

**Comment by jhchen** [comment]
I see. In that case https://github.com/quilljs/quill/commit/64841e3285246e708b249398ed47cbbcb2350fa5 should fix the issue.

**Comment by benbro** [comment]
Does it also fix the Firefox issue where the formula jumps to the middle of the code block?

**Comment by jhchen** [comment]
Yes it does in my Windows VM in Firefox. If you happen to be on right now you can try on http://quill.ngrok.io.

**Comment by benbro** [comment]
Verified. Thanks
