### ISSUE TITLE
getContents() throwing length of undefined error

### ISSUE THREAD

**Issue by dhershman1** [quilljs/quill#806]
[Describe the issue]

**Steps for Reproduction**

1. Call quill.getContents() setting it to a variable
2. trigger that variable set

**Expected behavior**: Set the Delta object to my variable

**Actual behavior**: Uncaught TypeError: Cannot read property 'length' of undefined

**Platforms**: Chrome 51 on Windows 10

**Version**: Beta 9

doing something like this I get an error.
```js
data.description = quill.getContents();
```

But if I do this:
```js
console.log(quill.getContents());
```
It runs and sends me back the delta object. Am I doing it wrong?

**Comment by jhchen** [comment]
Can you provide a stack trace?

**Comment by dhershman1** [comment]
```
quill.min.js:formatted:2415 Uncaught TypeError: Cannot read property 'length' of undefined
Delta.insert @ quill.min.js:formatted:2415
e @ jquery.min.js:4G
b @ jquery.min.js:4G
b @ jquery.min.js:4n.para
m @ jquery.min.js:4
ajax @ jquery.min.js:4
fetch @ submit-mod.js:18
sendMod @ client.js:96
submission @ client.js:92
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
```

This gets called on the submission portion when I cam getting all my data together to send off to my server.

**Comment by jhchen** [comment]
Can you use an unminified version? It's otherwise very difficult to glean any insight.

**Comment by dhershman1** [comment]
Stack with unminified version:
```
quill.js:2439 Uncaught TypeError: Cannot read property 'length' of undefined
Delta.insert @ quill.js:2439
e @ jquery.min.js:4G
b @ jquery.min.js:4G
b @ jquery.min.js:4
n.param @ jquery.min.js:4
ajax @ jquery.min.js:4
fetch @ submit-mod.js:18
sendMod @ client.js:96
submission @ client.js:92
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
```

My wording was a bit funky its just trying to set the contents that return from the `getContents()` call to a variable.

**Comment by jhchen** [comment]
If you can post a codepen or jsfiddle demonstrating this error with all code including all libraries unobfuscated I will take another look at this. Otherwise there is no indication this is a bug in Quill.

**Comment by dhershman1** [comment]
Yeah you're correct it is for sure something I am doing in correctly. I just need to figure out what lol.
