### ISSUE TITLE
Custom link format doesn't get removed on new line

### ISSUE THREAD

**Issue by jackmu95** [quilljs/quill#808]
I have created a custom link format that extends the default link format and has some minor changes (e.g. the `target="_blank"` attribute is removed). When I'am using this extended format the new line behavior is broken.

I'am quite sure that I have found the problem already... The keyboard module is [explicitly looking for the `link` format name](https://github.com/quilljs/quill/blob/develop/modules/keyboard.js#L239) to remove the format when hitting the `ENTER` key.

**Steps for Reproduction**

1. Visit http://codepen.io/jackmu95/pen/oLqbkd
2. Paste https://www.google.com/#safe=off&q=custom
3. Hit enter

**Expected behavior**: The link format should be removed on the new line

**Actual behavior**: The link is still active on the new line

**Platforms**: Chrome 51 on Mac 10.11

**Version**: 1.0.0-beta.9

**Comment by jhchen** [comment]
If you are extending the default link to be a link, why not just also call your format a link?

**Comment by jackmu95** [comment]
@jhchen I need a t least two types of different links. I use the default link format for external links and the custom link format for internal links.

The problem exists for any custom format which uses `A` as `tagName`.

**Comment by jhchen** [comment]
I would suggest just adding your own [keyboard handler](http://beta.quilljs.com/docs/modules/keyboard/) in that case.

Not continuing an inline format on enter is actually exceptional behavior (bold, italic, etc will maintain their format on a new line) and I don't want to assume all custom formats using the anchor tag should be similarly exceptional.

**Comment by jackmu95** [comment]
@jhchen I tried to handle it with a keyboard handler but there is no way to override the default `ENTER` handler because ist prevents propagation.

Would it be better to create a custom `Block` format that has the custom link as child node?
The custom link should also be not editable.

**Comment by jhchen** [comment]
This looks missing in the docs but If you add it in the configuration, instead of calling addBinding after initialization, it will run before the default.

```js
var quill = new Quill('#editor', {
  modules: {
    keyboard: {
      bindings: {
        'custom-enter': ['enter', {}, function() {}]
      }
    }
  }
});
```

**Comment by SahilPatel2349** [comment]
how can i bind command + b to console log something?
