### ISSUE TITLE
@ Mentions

### ISSUE THREAD

**Issue by ncammarata** [quilljs/quill#81]
I'm going to be building @ mentions a la Facebook or Github starting in a couple weeks using Quill. Is this something you all are thinking of building as a plugin to Quill? I think it would be a great addition and very generalizable.

If it is, I'll hold off and use Quill's when it's up.

**Comment by brettimus** [comment]
@ncammarata did you ever build a module for this?

**Comment by ncammarata** [comment]
@brettimus nope, sorry :(

**Comment by gmartsenkov** [comment]
@kbjr can you share how you configured the iframe :?
I tried various options like:

```javascript
$(advancedEditor.root).atwho('setIframe', $(advancedEditor.editor.iframeContainer.children[0])).atwho({at: '@', data: ['Peter', 'Anne']})
```

**Comment by jhchen** [comment]
If someone else wants to try to implement this in 1.0 feel free to open up another issue.

**Comment by MadSpindel** [comment]
I have made a module for Quill 2.0. You can it here:
https://github.com/afconsult/quill-mention
