### ISSUE TITLE
Deleting text mess up with spellchecking

### ISSUE THREAD

**Issue by xdmnl** [quilljs/quill#813]
**Steps for Reproduction**

1. Visit quilljs.com
2. Type/paste a text with typo (ie: `Tis is a grat text withou any typo.`)
3. Press `delete` OR `backspace` OR type more text and then hit `cmd + Z`

**Expected behavior**: Typos are still considered as typos.

**Actual behavior**: Typos are considered as valid (red dotted underline disappear).

**Platforms**: All

**Version**: 0.20.1

**Comment by jhchen** [comment]
This is fixed in [1.0](http://beta.quilljs.com/).
