### ISSUE TITLE
getFormat() returning empty object

### ISSUE THREAD

**Issue by julian-weinert** [quilljs/quill#814]
When calling the `getFormat()` method, I'm not getting any format returned.
Even when supplying the full range, I'm not getting anything: `editor.getFormat(0, editor.getLength()-1);`

**Steps for Reproduction**

1. Visit [JSFiddle/8141uxbh](https://jsfiddle.net/julian_weinert/8141uxbh/)
2. Click "Show Format"
3. Read format log

**Expected behavior**: Array with format information

**Actual behavior**: Empty dictionary

**Platforms**: (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 Version/9.1.2 Safari/601.7.7

**Version**: quill 1.0.0-beta.9

**Comment by jhchen** [comment]
The docs appear to be a bit misleading. 

> For a format to be reported, all text within the range must have a value. If there are different values, an array with all values will be reported.

The second sentence is meant to mean if all text within the range has a format, but different values, an array will be reported. So for example if the entire text is colored, but might be different colors. But if there is any letter that has no color then the color format will be excluded from reporting. I suspect there is a letter in your range that has no formats at all so an empty object is returned. I will update the docs to make this more clear.

**Comment by julian-weinert** [comment]
Okay. I observed it a bit deeper.
When all text has the same style, this style gets returned. That's okay, but unfortunately not extremely helpful. Probably you could take this wording kinda into account.
