### ISSUE TITLE
Get full formatting table (feature request)

### ISSUE THREAD

**Issue by julian-weinert** [quilljs/quill#819]
The full format table would consist of an array containing ranges and formats:

```javascript
[{
    range: [0, 19],
    format: {
        face: [bold],
        color: black
    }
}, {
    range: [15, 19],
    format: {
        decoration: underline,
        color: green
    }
}]
```

I want to use Quill as a backend text editor for a website and a mobile application.
The HTML part would work just fine, but for the application (which gets data via a dedicated API) we need attributed strings. These could be created from RTF or manually by applying styles to ranges.

Quill is used to input small building blocks of text (which go along with ones for video, galleries, and so on). The full format needs to be saved along with the plaintext string in the database and then be returned to to API as needed.
The formatting table enables small pieces of text to be formatted properly and placed underneath each other without dealing with user styles, default margins and that sort of jazz.
Also this would allow my application to render content faster and more efficiently.

This opens up a variety of possible use cases and enables developers to get all information about specific text ranges in a fast and lucid manner that allows to iterate quickly and apply formats to whatever it's needed for, in any language.
I couldn't find any competitor that features this functionality and also any that looks and feels at least half as perfect as Quill does.

**Comment by jhchen** [comment]
Could you use [`getContents`](http://beta.quilljs.com/docs/api/#getcontents)? It does not exactly give the form you suggested but they can be deduced from what is given. For example instead of the range it gives you the text whose length can be used to figure out the range.

```js
{ 
  ops: [{
    insert: 'some 19 letter text',
    attributes: {
      bold: true
    }
  }, {
    insert: 'text',
    attributes: {
      underline: true,
      color: 'green'
    }
  }]
}

**Comment by julian-weinert** [comment]
Oh shame on damn stupid me.
Sure, that is exactly what I was looking for, apparently I didn't see the wood for the trees.

Hearts for the 19 letter long text 😂
