### ISSUE TITLE
Inline styles being removed on setHTML()

### ISSUE THREAD

**Issue by dhawalbhanushali** [quilljs/quill#823]
Hi,

I have been trying to add custom inline styles to HTML but seems the library doesn't allow us to do that.

Example: 
`quill.setHTML('<div style="height: '10px'; color: 'brown' ">Hello World</div>');`

In the output the styles are being removed. Is there any way to achieve this?

**Comment by jhchen** [comment]
No Quill does not allow arbitrary HTML. You can achieve something similar with Quill 1.0 using [Attributors](https://github.com/quilljs/parchment#attributors).
