### ISSUE TITLE
Emit events from history module (and others?) (feature req)

### ISSUE THREAD

**Issue by BenjaminListwon** [quilljs/quill#825]
I am fiddling with an autosave feature for Quill instances, basically the same way Google docs saves, etc. I don't want to commit the save on every `text-change` event, and implementing a(nother) timeout after typing events seems error prone and hack-ish.

So, I was thinking it might be handy if the history module (and maybe others) emitted Quill namespaced events. In this case probably something like:

- `quill-history-push` when it goes on the stack
- `quill-history-pop` when it comes off the stack
- `quill-history-undo` when undo event is fired
- `quill-history-redo` when redo event is fired

Obviously not comprehensive or even the right names, just thinking out loud.

Anyway, as far as something like autosave, this would allow code to listen to when "major" deltas were pushed onto the stack, based on the existing configuration's timeout (default 1000ms). 

I can see other potential reasons to emit such events like throwing up a little "Changes undone / redone" banner or triggering code that could visually highlight the undone / redone operation in the editor. 

I'll try to give it a whirl on my own soon, once I have a better grasp of the module code and a build env for Quill.

**Comment by jhchen** [comment]
Interested in other people's thought but here are my immediate reactions:

The desire for a less realtime autosave is a legitimate use case, but the proposed solution is far hackier than the alternative. This is because you are not actually interested in what gets put on the history stack, you are actually interested in composed change events, which happens to be what the history stack does to text-change events it gets, but it is not the case it the history module has to do this. In fact there are good reasons the history module might want to change the deltas it gets entirely, not just compose them.

**Comment by BenjaminListwon** [comment]
I _think_ I understand the distinction you are outlining (I'm admittedly still looking around `rich-text` at how deltas are composed / transformed).


Forgetting about the history module for a second ...

Currently I have a listener on `text-change` events that unsets, then sets, a global timeout which, after a configurable delay, calls the autosave function if the editor is "dirty" and no other valid action has interrupted the timeout delay. 

There are, of course, other ways to do this, but they all boil down to the same idea: keep observing something, either by polling, callback or promise, until a timeout condition is met, then call whatever callbacks have been registered.

At any rate, at that point calling `editor.getContents()` and serializing the result gets you a replayable representation of the editor's state.

I was probably too ambiguous in my initial writing. I do not intend to send incremental deltas to the server (or local storage) on each autosave, although that could potentially save some bandwidth. My intention is simply to send and store the current version of the document (collection of all insertions, etc) such that it can be restored to that state. I also did not mean to imply that I was storing the history stack (say, so a user could come back and undo in a later session), though that would be some crazy cool functionality, now that I think about it.


So, back to the history module, if history events are an inappropriate determinant of when to autosave, what do you think is the best event, or functionality, to monitor? I'm eager to learn more about how I might better observe changes and write responders.


(I'll put aside the broader discussion about events outside autosave, such as those from clipboard, etc.)

**Comment by jhchen** [comment]
If you're okay with sending the entire contents of the document to the server each time, isn't the implementation as simple as:

```js
quill.on('text-change', _.throttle(function() {
    saveToRemoteServer(quill.getContents());
}, 1000));
```

Here we use lodash's throttle function but other libraries will suffice, the idea of throttling a function call is not unique to lodash.

**Comment by BenjaminListwon** [comment]
Yup, that's basically what I've got, but lodash's `throttle` is new to me, and looks super useful. Much more robust than what I've used. Thanks for that pointer.

I'm going to keep tinkering on event broadcasting in a fork and let you know when I've got something workable that maybe you (and others) would have feedback on. I still think there are valid UCs for listening to module-level events as well as some more from core.

**Comment by sachinrekhi** [comment]
I agree the solutions @jhchen is suggesting leveraging either getContents() on a timer or throttling are the right solutions for your use case. Additionally if you only want to send just deltas to the server, you could simply compose the deltas received from text-change locally and then send the composed deltas in bulk based on a timer or throttling.

Don't think you need to involve the history module to accomplish most of the auto-saving use-cases you could come up with.

**Comment by BenjaminListwon** [comment]
Hi all,

Thanks for the confirmation around approach. When I have more concrete code + examples around event emitting (unrelated to the autosave) I'll open a new issue and/or PR.
