### ISSUE TITLE
Incorrect numbering of second level when ordered list mixed with bullets

### ISSUE THREAD

**Issue by erenemre** [quilljs/quill#829]
When you have an ordered list, with another list under, ordered list's numbers do not follow an expected rule.

**Steps for Reproduction**
1. Visit http://beta.quilljs.com
2. Create an ordered list with 5 items
3. After 3rd item, indent the list and create another list under

**Expected behavior**: 
SEE: https://www.dropbox.com/s/5olyxk1t4osfydg/quill1.gif?dl=0
The order should be:
_ One
_ Two
_ Three
___- A
___\- B
___- C
_- Four
_- Five

**Actual behavior**: 
SEE: https://www.dropbox.com/s/y30dsdcacdrbiyv/quill2.gif?dl=0
_ One
_ Two
_ Three
___- A
___\- B
___- C
_- One
_- Two

**Platforms**: Version 51.0.2704.103 (64-bit) on OSX 10.11.6 (15G31)

**Version**: v1.0.0-beta.9

**Comment by mpfau** [comment]
Looks like this is the same issue as #979. The numbering is resetted because a new `ul` and a new `ol` block is created (instead of creating an `ul` subblock below the `ol`)
