### ISSUE TITLE
Copy/paste from Quill to Quill adds extra spaces

### ISSUE THREAD

**Issue by erenemre** [quilljs/quill#830]
After copying a content that's on Quill, pasting it again adds some extra space between paragraphs.

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/
2. Add a few paragraphs
3. Select all
4. Copy
5. Open new quill page
6. Paste

**Expected behavior**: [expected]
Content is kept the same

**Actual behavior**: 
SEE: https://www.dropbox.com/s/t3sorr28m5ox739/quill3.gif?dl=0
Content has extra spaces between elements

**Platforms**: Version 51.0.2704.103 (64-bit) on OSX 10.11.6 (15G31)

**Version**: v1.0.0-beta.9

**Comment by jhchen** [comment]
This has been fixed in the most recent beta release 1.0.0-beta.10.
