### ISSUE TITLE
why after submitting post content,the postpage is also editable?

### ISSUE THREAD

**Issue by diegobona** [quilljs/quill#831]
I use "quill" in my project.now most of the function is normal. but there are 2 problems:

1.After submitting post content, the postpage is also **editable**! but the div is not set "contenteditable='true' " ！

2.After submitting content, the end is always add an **input box** automatically:
  
![mfwr4](https://cloud.githubusercontent.com/assets/19513909/17274311/25884934-570e-11e6-8cc9-5107c1c637cf.png)

**Comment by jhchen** [comment]
You are using one of the themes but not including its stylesheet. The parent container has the class `ql-hidden`, which should hide the tooltip you are seeing. One of these needs to be lincluded:

https://cdn.quilljs.com/1.0.0-beta.9/quill.bubble.css
https://cdn.quilljs.com/1.0.0-beta.9/quill.snow.css

**Comment by diegobona** [comment]
it  is ok, thank you very much! now there is a little problem:
![image](https://cloud.githubusercontent.com/assets/19513909/17275443/e4db49d6-573a-11e6-8dd6-3733e22cd4b6.png)

if i set the height of the div to a fixed value(now is "height:auto"), it's ok!

**Comment by jhchen** [comment]
I don't understand. Can you make a video of the issue?

**Comment by diegobona** [comment]
ok，Please see the attachment



 
From: Jason Chen
Date: 2016-08-01 04:39
To: quilljs/quill
CC: diegobona; Author
Subject: Re: [quilljs/quill] why after submitting post content,the postpage is also editable? (#831)
I don't understand. Can you make a video of the issue?
