### ISSUE TITLE
After clicking "insert video" button,the dialog box can not popup 

### ISSUE THREAD

**Issue by diegobona** [quilljs/quill#832]
![e4db49d6-573a-11e6-8dd6-3733e22cd4b6](https://cloud.githubusercontent.com/assets/19513909/17276408/5e5322e6-575b-11e6-83a2-e36f3af3c321.png)

But if i set the height of the div to a fixed value(now is "height:auto"), it's ok. 
Is that a problem of inheritance？

**Comment by diegobona** [comment]
why close?This problem is not solved !

**Comment by jhchen** [comment]
This is duplicate content from another Github Issue thread. You are also not owed or entitled to an answer, especially when you do not follow the [Contributing Guidelines](https://github.com/quilljs/quill/blob/master/.github/CONTRIBUTING.md). Your attempt to solicit answers by spamming my personal email is also not appreciated. I am going to ask you to read the [Contributing Guidelines](https://github.com/quilljs/quill/blob/master/.github/CONTRIBUTING.md) clearly and follow them as a good community member from here on out, or you will not be a part of it.
