### ISSUE TITLE
Problems with blockquote handling

### ISSUE THREAD

**Issue by tvdavid** [quilljs/quill#834]
1. Nested blockquotes are broken, any nested blockquotes are stripped away, appending the content to the parent blockquote.
2. Paragraphs in blockquotes are broken, each p tag appears to close the blockquote and start a new one.

**Steps for Reproduction**

1. http://codepen.io/anon/pen/KrBGvd

**Expected behavior**:

1. Blockquotes can be nested indefinitely
2. Blockquotes can contain paragraphs

**Platforms**: Firefox

**Version**: 1.0.0-beta.9

**Comment by jhchen** [comment]
Nest blockquotes is not a feature of Quill. Feel free to open an issue requesting it and a separate one to support containing paragraphs. Please follow the [feature request](https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#feature-requests) guidelines for both.

**Comment by tvdavid** [comment]
Is there a description of what is and what isn't supported in Quill, or do you only consider a document to be supported when it can be created using the Quill UI? (I would have expected all valid HTML to be passed through untouched)

**Comment by jhchen** [comment]
Quill supports these [formats](http://beta.quilljs.com/docs/formats/) by default, but you can add your own with [Parchment](https://github.com/quilljs/parchment). I'm still working on docs for how to use Parchment but supporting all markup valid in HTML is absolutely not a goal of Quill. Editors have to make a tradeoff between supporting the ambiguities of HTML or being consistent and predictable in state and behavior. Quill is designed for the latter.

**Comment by jscheel** [comment]
@jhchen I've gone down the path of trying to create a nested blockquote by using the container blot, but I haven't had much luck. Do you have any pointers on how I might do this?

**Comment by OctaneInteractive** [comment]
Hi!

Having switched to Quill, I've hit the same problem, and while Parchment looks good, I've got an existing 3k plus bunch of notes, and 15k saved web pages that have the blockquote-p markup in some of them.

I don't consider blockquote-p markup to be ambiguous, as inferred by @jhchen, it's a common use case.

What would be an alternative route forward?
