### ISSUE TITLE
Clipboard removing image styling

### ISSUE THREAD

**Issue by beeterry** [quilljs/quill#835]
We have an HTML string coming from our database that should simply be pasted into the editor. We're using `.pasteHTML()` and the text styling is being kept properly however it seems that the image styling is being removed. The width and height of the image is being removed, and it's causing the image to be displayed at its natural height and width rather than the specified dimensions. As you can see below, the html string being passed into the `.pasteHTML()` function has specified height and width. Is there a parameter that we can pass into the `.pasteHTML()` function to avoid this cleaning?:

`<p class="ql-align-center"><strong class="ql-size-huge" style="color: rgb(255, 255, 255);">&nbsp;$450 Referral Bonus</strong></p><p class="ql-align-center"><strong class="ql-size-small" style="color: rgb(186, 35, 35);">Phone a friend!</strong></p><p class="ql-align-center"><img width="145" height="140" style="width: 145px; height: 140px;" src="data:image/png;base64,iVBORw0KG`

**Steps for Reproduction**

1. We use QuillJS to create intial html content. 
2. Insert the innerHTML() from the editor and store it in our DB
3. Retrieve the html string from our DB to allow the user to edit the content
4. use the .pasteHTML() function to paste our html string into the editor
5. inline-styling is being stripped by the clipboard cleaning I believe.

Been working on this all day. Figured I'd post a little additional information that I came across. So, I'm trying to create a matcher that the clipboard will use to interpret an img tag, but I still can't seem to get it to assign the width/height. Here's the function I'm using after I delcare my instance of Quill:

```
quill.clipboard.addMatcher('img', function(node, delta) {
            let imgWidth = node.width;
            let imgHeight = node.height;

           // This is something I'm testing. Currently doesn't assign width/height still
            var delta2 = new Delta([
                {
                    insert: { image: 'https://octodex.github.com/images/labtocat.png' },
                    attributes: {
                        width: "20px",
                        height: "20px"
                    }
                }
            ]);
            return delta2;
        });
```

**Comment by jhchen** [comment]
This is fixed in the most recent beta release 1.0.0-beta.10. You should be able to paste an image with width and height attributes, without your custom matcher.
