### ISSUE TITLE
Can keyboard module be configured on initial load?

### ISSUE THREAD

**Issue by alexkrolick** [quilljs/quill#838]
Is there a way to pass a configuration object to the keyboard module on initialization that would add several handlers at the same time? The [docs](http://beta.quilljs.com/docs/modules/keyboard/) for the beta keyboard module show that custom keypress handlers can be added to a Quill instance using the `quill.keyboard.addBinding()` method but doesn't show a way of using the `modules` object as you can with the toolbar, clipboard, etc.

**Comment by jhchen** [comment]
Yes just updated the docs to include an example of adding bindings in initialization:

```js
var bindings = {
  custom: [
    { key: 'B', shiftKey: true },
    function(range, context) {
      // Handle shift+b
    }
  ]
};

var quill = new Quill('#editor', {
  modules: {
    keyboard: {
      bindings: bindings
    }
  }
});
```

**Comment by alexkrolick** [comment]
So, the bindings array alternates between config and callback like `custom[0] = key0, custom[1] = callback0, custom[2] = key1, custom[3] = callback1]`? Would it make sense to put it more like:

```js
var bindings = {
  custom: [
    { key: 'B', 
      shiftKey: true, 
      callback: function(range, context) {
        // Handle shift+b
      }
    },
    { // ...another handler }
  ]
};
```

**Comment by jhchen** [comment]
I was on the fence about this syntax but since you felt strongly enough to bring it up, I'll make the change for the version.

**Comment by alexkrolick** [comment]
Great! Can't wait for 1.0!
