### ISSUE TITLE
Unable to open home/demo page on firefox 47.0

### ISSUE THREAD

**Issue by PiyushRamuka** [quilljs/quill#840]
Hi -

When trying to launch demo (home) page https://quilljs.com/ in firefox Rev 47.0, we get following error.

": at cloudflare.min.js (line 4)"

![quill issue](https://cloud.githubusercontent.com/assets/7099771/17330752/1629af9e-5896-11e6-9f7c-d61b546e46b7.JPG)

Please let us know what are we doing wrong. Thanks!

Regards,
Piyush

**Comment by jhchen** [comment]
It's working for me on Mac. Are you on Windows or Linux?

**Comment by benbro** [comment]
Working for me with Firefox 48 on Windows 7

**Comment by PiyushRamuka** [comment]
I am using windows 7 x64.
Just tried with firefox 48 and still same issue. Chrome works without any issue.

**Comment by jhchen** [comment]
Can you try disabling plugins? The error is from Cloudflare, which Quill's website uses as a CDN and should work on FF. It may also be a network / firewall issue. It works on SauceLab's Firefox 47 on Windows 7.

**Comment by PiyushRamuka** [comment]
I will try it out tonight from a different network and update accordingly. 
I don't think its network firewall as it works on chrome.
