### ISSUE TITLE
Problem with line breaks (maybe with \r from windows)

### ISSUE THREAD

**Issue by windows1087** [quilljs/quill#842]
I have an MS-SQL Database with few data i display on my internal site. Sorry, no access here for test :(

The line breaks does correctly show on my site (with white-space: break-word css). If i copy the text from my site to the normal windows editor, sublime, phpstorm or here into the github issue textbox, it has correct line breaks. But if i copy it to the playground of quill, it's only in one line :(

Maybe the fix is, to add more matches like

```
['\r', matchBreak],
['\r\n', matchBreak],
```

https://github.com/quilljs/quill/commit/8e1ad43b3b4b8b2db819930222ff7e7f288a4641

?

**Expected behavior**: Show correct line breaks

**Actual behavior**: No line breaks

**Platforms**: Windows 7

**Version**: Current Firefox and Chrome

**Comment by jhchen** [comment]
Changing the editor's white-space property breaks things. Does it paste correctly if it's left as pre-wrap? There is specific code in Quill to handle carriage returns already.

**Comment by windows1087** [comment]
Oh man, i forgot to add an `<p>` wrapper around my Text Variable (i was thinking quill will make it self). Thanks.
