### ISSUE TITLE
What happened to uploaded images?

### ISSUE THREAD

**Issue by george-norris-salesforce** [quilljs/quill#844]
http://codepen.io/stoplion/pen/vKzrmK?editors=0010

Previously adding the image module gave me a prompt to upload from my computer now it is a prompt to add a URL.

**Comment by alexkrolick** [comment]
Same here. Is this by design?

**Comment by willrowe** [comment]
As far as I know Quill has never supported image upload. See #90.

**Comment by george-norris-salesforce** [comment]
now you know :)
[![https://gyazo.com/338eb449ccf3e7e39748cc2b63f547d6](https://i.gyazo.com/338eb449ccf3e7e39748cc2b63f547d6.gif)](https://gyazo.com/338eb449ccf3e7e39748cc2b63f547d6)

Last week lastest beta version had this feature..

**Comment by willrowe** [comment]
Sorry, I assumed you were referring to the latest stable release since you didn't specify any version.
What you're talking about isn't exactly uploading any image. It is taking a file from your computer, converting it to a data URI, and inserting that into an image tag's `src` attribute. Related issue #103, related commit a615d5294145e9e96e7a60136449c12c41f9f4ce.

**Comment by george-norris-salesforce** [comment]
Gotcha.. What i mean is..

The behavior of the amazing gif above presents a prompt to select an image from file system — presumably for uploading via Quill. 

Whilst the new (or old?) way assumes you have it already uploaded and are referencing it via URL.

**Comment by jhchen** [comment]
Sorry guys a few issues can up from my refactoring of combining configurations and so the default theme handlers were not being copied over. Should have another beta out today.

**Comment by Muaadeeb** [comment]
Great tool but same question.  Do we have an estimated date when image upload and/or drag & drop from your computer will be operational?  I understand the image src current functionality but it would be nice if users could grab images from their own local drive.

**Comment by sumitkm** [comment]
@Muaadeeb Ctrl+C Ctrl+V seems to work for me as does image drag drop (Firefox on Debian Jessie)... Just that you have to work out the details of converting the Base64 encoded image on the server side when you try to save the content.

**Comment by fghhfg** [comment]
`Ctrl+C Ctrl+V ` and `drag n drop` only work on firefox. unfortunately it doesn't work on chrome.

**Comment by daslicht** [comment]
How to make it not convert it to a data:image ?
I just want to select an image, and then a callback should be called so that i can handle the upload, after successful upload the image src should be set to the returned location.
