### ISSUE TITLE
Cannot input the first character with Sogou and Simple PinYin IME

### ISSUE THREAD

**Issue by KennyWho** [quilljs/quill#849]
It's similar to #626 but I happen on version 1.00 and Chrome.

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/playground/
2. Switch [Sogou Pinyin IME](http://pinyin.sogou.com/) (Chinese input).
3. Type character.

**Platforms**: lastest Chrome on OS x and Windows10

**Version**: v1.00-beta.11/v1.00-beta.2

**Comment by jhchen** [comment]
I'm not encountering any issues on Mac + Chrome. Can you disable all extensions and post a video of what you are experiencing?

![chinese](https://cloud.githubusercontent.com/assets/192974/17458877/72958034-5bd7-11e6-8e4d-782be4d25ccd.gif)

**Comment by KennyWho** [comment]
It happened on specify IME, if I switch Microsoft IME, it works, but I switch Sogou Pinyin IME,it doesn't work.here is reproduction.

on Window10 + Chrome + Sogou IME
![issue](https://cloud.githubusercontent.com/assets/7511329/17460209/b23bcba0-5c8e-11e6-9115-2a7cfcc60e4b.gif)

I test it on my mac + Chrome.Sogou IME and Simple PinYin IME have the same problem.

on Mac

**Comment by siteshen** [comment]
As a notice, I've the same problem with extension [evernote web clipper](https://chrome.google.com/webstore/detail/evernote-web-clipper/pioclpoplcdbaefihamjohnefbikjilc). It works if I disable it.

Quill: 1.0.0-beta.11
Chrome: 52.0.2743.116 (latest)
System: OS X 10.11.6

**Comment by mrdream24** [comment]
I input first character with Chinese IME in [https://quilljs.com/playground/](https://quilljs.com/playground/) and [https://quilljs.com/](https://quilljs.com/). I found that is normal with extension [evernote web clipper](https://chrome.google.com/webstore/detail/evernote-web-clipper/pioclpoplcdbaefihamjohnefbikjilc).why?

**Comment by jhchen** [comment]
Installed the latest version of Sougou IME and am not experiencing any issues either.

![chinese](https://cloud.githubusercontent.com/assets/192974/18222179/3f7ac8d6-7143-11e6-999a-073f8ab18fde.gif)

I would suggest filing bugs with the troublesome extensions themselves.

**Comment by gn02394847** [comment]
我發現在輸入全形字(fullwidth)，在每一行的第一個字時候會出現問題

輸入第一個字 會跳出後面幾個字
Ａ ＡＢ
ㄨ ㄨㄛ

mac os 注音輸入法 (不過我猜任何輸入法都有這個問題

**Comment by chesscai** [comment]
Fixed!
Version: 1.3.6

Reason:
Quill gen html include `<p><br><br></p>` , when Sougou type 2 characters with Pinyin.

Solve:

    quill.on('text-change', (delta, oldDelta, source) => {

        let html = quill.container.firstChild.innerHTML;

        if (html.indexOf('<p><br><br></p>') >= 0 && source === 'user') {
          let range = quill.getSelection(); // current cursor
          setTimeout(() => {
            quill.insertText(range.index, ' '); // insert &nbsp;
          }, 0);
        }
    }
