### ISSUE TITLE
Drop down to add class / classes...

### ISSUE THREAD

**Issue by seanhinton** [quilljs/quill#85]
What would be perfect is if you could have a button to add a class or classes to a p tag / span tag.

Similar to the addStyle API call, however you could add a class to it instead.

This would the style isn't hard-coded into the span tag as well as loads of other benefits... would be easier to update peoples text editors.

Add class feels like a crucial missing feature in the API.

**Comment by laosb** [comment]
@jhchen Will you reopen this?

We're building a Medium-like writer platform. We have some internal styles like callout block quotes, poem paragraphs. Because our authors only write on our platform, copying & pasting is not something we worry about. Please do implement CSS class support!

**Comment by jhchen** [comment]
I believe Quill 1.0 supports this.

**Comment by laosb** [comment]
I couldn't find related usage in docs actually? Would you like to show me out?
