### ISSUE TITLE
Link tooltip doesn't appear if under bottom bound of editor

### ISSUE THREAD

**Issue by ygrishajev** [quilljs/quill#851]
I faced the issue of link tooltip not appearing when `bounds` option is set and selection is the most bottom line of the editor. In this case tooltip is out of the bounds.

![](http://image.prntscr.com/image/237b5f9b173f418a8aec88da325586c3.png)

**Steps for Reproduction**
1. Visit http://beta.quilljs.com/
2. Enter any text in the very bottom of the demo editor
   ![](http://image.prntscr.com/image/3119fc8fd2a84f8fb05d48874e1a8a35.png)
3. Try to create a link of this text

**Expected behavior**: Tooltip appears above the selection (as a suggestion)

**Actual behavior**: Tooltip doesn't appear

**Platforms**: Chrome 48 on Mac 10.11

**Version**: 1.0.0-beta.11

This may be implemented with additional check/adjustment here https://github.com/quilljs/quill/blob/develop/ui/tooltip.js#L40

``` javascript
if (rootBounds.bottom > containerBounds.bottom) {
    const shift = containerBounds.bottom - rootBounds.bottom - this.root.offsetHeight
    this.root.style.top = `${top + shift}px`
  }
```

**Comment by suraj1255486** [comment]
[https://quilljs.com/docs/api#model](url)

**Comment by suraj1255486** [comment]
https://quilljs.com/docs/api#model
