### ISSUE TITLE
Clicking 'Done' when adding hyperlink, scrolls editor to top

### ISSUE THREAD

**Issue by therahl** [quilljs/quill#852]
When adding a link to the text editor, the editor will scroll to the top.  Expected behavior is for the editor to maintain scroll position when a link is added.  

**Steps for Reproduction**
1. Visit quill.com
2. Scroll to bottom of text editor.
3. Add link on the last line by highlighting some text.
4. Observe the editor scrolls to top when clicking 'Done'

**Platforms**
Behavior observed in Chrome and Safari

**Comment by jhchen** [comment]
What version of Quill are you using?

**Comment by khera-shanu** [comment]
it's not quill.com, @therahl. it's quilljs.com

the editor scrolls up because of the dom object in focus (class "**ql-link-tooltip**") get different values for "**top**" css property.

**Comment by therahl** [comment]
Quill version is 0.20.1, will upgrading to the latest resolve this issue for me?

**Comment by benbro** [comment]
You can test 1,0 beta:
http://beta.quilljs.com/

**Comment by therahl** [comment]
Thanks for the link @benbro.  Looks like upgrading will solve this issue for me.  Closing issue.  Thanks everyone!
