### ISSUE TITLE
insertEmbed() creating new <p> tag

### ISSUE THREAD

**Issue by KameSama** [quilljs/quill#853]
I'm trying to add a custom format to add logical hooks on elements of the editor and I can't find  proper documentation on the subject.

The issue I'm facing is that the insertEmbed() function closes the <p> tag where my focus is on instead of inserting my format where the focus (index) is at.

I would like to add my custom format html directly at the cursor.

Here's my custom code
```
var Embed = Quill.import('blots/block/embed');
class ProcLink extends Embed {
    static create(value) {
        let node = super.create(value);
        // give it some margin
        node.setAttribute('style', "text-decoration: underline;background-color : lightgreen;");
        node.setAttribute('data-proc', value.value);
        node.innerHTML = value.text;
        return node;
    }
}

ProcLink.blotName = 'proc-link'; 
ProcLink.className = 'proc-link';
ProcLink.tagName = 'span';

Quill.register({
    'formats/proc-link': ProcLink
});

//In another piece of logical code
 var index = quill.getSelection(true).index;//quill is the reference to my instantiated quill obj
 var cObj = {text : text, value : value};
 quill.insertEmbed(index,"proc-link",cObj)
//more code
```

**Expected behavior**: [expected]
<p> text bla bla [custom format] moar bla bla</p>
**Actual behavior**: [actual]
<p> text bla bla</p>
[custom format]
<p>moar bla bla</p>

**Platforms**: [ex. Chrome 48 on Mac 10.11]
Chrome 52 on Windows 7
**Version**: [version]
v1.0.0-beta.11

**Comment by jhchen** [comment]
You're inheriting from the block level embed. I think you want the inline one so it should be `Quill.import('blots/embed')` http://codepen.io/quill/pen/EyGoyE. A detailed guide on Parchment is coming soon.

**Comment by doctsh** [comment]
Any detailed guide on Prachment now? I am looking for a noneditable embeds in my editor

**Comment by JinChunCheng123** [comment]
> You're inheriting from the block level embed. I think you want the inline one so it should be `Quill.import('blots/embed')` http://codepen.io/quill/pen/EyGoyE. A detailed guide on Parchment is coming soon.

cool
