### ISSUE TITLE
Clicking a link using the bubble theme does not do anything

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#854]
**Steps for Reproduction**

1. Visit http://beta.quilljs.com/docs/themes/
2. Find the editor with the bubble theme
3. Type some text, highlight a particular word and turn it into a hyperlink
4. Once that is done the link appears in the document. But clicking it does not do anything. In the snow theme it brings up a tooltip to click the link

**Expected behavior**: 

Maybe this is the correct behavior, I am not sure. I can always right click the link to open it. Is there a way to make this better, more intuitive? 

**Actual behavior**:

Does not do anything when you click a hyperlink in the editor

**Platforms**: Tested using chrome

**Comment by jhchen** [comment]
This is currently an expected limitation of the Bubble theme. I've added this as a feature request #857
