### ISSUE TITLE
How do you save the history of edits to the server and reload on client?

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#859]
This isn't an issue with the code but more of an issue with either undocumented API or feature request. 

I am using the history module and when I make edits I can undo and redo as usual. But when I close the tab and come back the history of edits is gone. This is because the history stack is held in memory only. 

How can I save the history of edits to the server? And then when the client loads the app again, I can reload the history state of the editor, so the user can undo and redo whenever they visit the app, from any device.

**Comment by sferoze** [comment]
I looked at the code for the history module and noticed the history stack. 

Could this work by saving quill.history.stack and the when the editor loads again setting quill.history.stack = savedStack?

**Comment by sferoze** [comment]
Actually I realize that since the history stack is a complicated object with nested array and prototype functions it is difficult to save and reload. Any advice?

**Comment by sferoze** [comment]
to do this we basically need a function to stringify the objects in the stack, and then when reloading, we need to recreate the delta object from the stringify data. Dont currently know how to do this, but I know what needs to be done to recreate the stack.

**Comment by benbro** [comment]
In 1.0-beta you can use 
```javascript
var content = quill.getContents()
quill.setContents(content)
```
http://beta.quilljs.com/docs/api/#content

You can use JSON.stringify(content) and JSON.parse() to save to the server and read back.

**Comment by sferoze** [comment]
@benbro ?? Why mention saving content? 

I am trying to save the history stack in the history module.

**Comment by sferoze** [comment]
I figured it out. 

I am now able to save the complete history stack to the server and reload it again. 

I edited the quill.js file directly for now but eventually I want to make a pull request. 

Here is how I save the data to mongoDB

`data.historyStack = jQuery.extend(true, {}, t.editor.history.stack)`

that clones the information in the stack object to save in DB

Then when the editor loads again you do

```coffeescript
if t.data.historyStack? # if there exists a saved stack
      quill.history.loadHistoryStack(t.data.historyStack)
```

Here is the new user function I added to the history module

```javascript
{
	    key: 'loadHistoryStack',
	    value: function loadHistoryStack(stack) {
		  if (stack.undo.length > 0) {
			for (var i = 0; i < stack.undo.length; i++) {
				var ob = {};
				ob.redo = new Delta(stack.undo[i].redo.ops);
				ob.undo = new Delta(stack.undo[i].undo.ops);
				this.stack.undo.push(ob)
			}
		  }
		  if (stack.redo.length > 0) {
			for (var i = 0; i < stack.redo.length; i++) {
				var ob = {};
				ob.redo = new Delta(stack.redo[i].redo.ops);
				ob.undo = new Delta(stack.redo[i].undo.ops);
				this.stack.redo.push(ob)
			}
		  }
	    }  
	  }
```

One problem that made my change kinda hacky is the fact that the Delta class object was not exposed in the function. 

So at the top of the file I added `var Delta; ` so Delta was exposed to the whole file. Not the best, so can you recommend a change. How can I get access to Delta object in history module?

**Comment by sferoze** [comment]
Here is how I was able to do it without editing the source code

```coffeescript
loadHistoryStack = (stack) ->

    if stack.undo.length > 0
      i = 0
      while i < stack.undo.length
        ob = {}
        deltaObRedo = Object.create(t.editor.editor.delta)
        deltaObUndo = Object.create(t.editor.editor.delta)

        deltaObRedo.ops = _.clone(stack.undo[i].redo.ops)
        deltaObUndo.ops = _.clone(stack.undo[i].undo.ops)

        ob.redo = deltaObRedo
        ob.undo = deltaObUndo
        t.editor.history.stack.undo.push ob
        i++
    
    if stack.redo.length > 0
      i = 0
      while i < stack.redo.length
        ob = {}
        deltaObRedo = Object.create(t.editor.editor.delta)
        deltaObUndo = Object.create(t.editor.editor.delta)

        deltaObRedo.ops = _.clone(stack.redo[i].redo.ops)
        deltaObUndo.ops = _.clone(stack.redo[i].undo.ops)

        ob.redo = deltaObRedo
        ob.undo = deltaObUndo

        console.log(ob, t.editor.editor.delta)
        t.editor.history.stack.redo.push ob
        i++
```

**Comment by jhchen** [comment]
This isn't a supported use case at the moment so there's no API or "right" way to do it. Feel free to open an issue with a proposal spec if you are inclined.

**Comment by ggJSC** [comment]
@sferoze Any idea how to implement this in a more vanilla nature and not using meteor?

**Comment by tstoev** [comment]
@ggJSC simply copy the code for loadHistoryStack. You can either wrap the editor in your own class, or use it as a standalone function. A standalone implementation would look like that:

```
function loadHistoryStack(stack,editor) {
          var Delta = Quill.import('delta');
          if (stack.undo.length > 0) {
            for (var i = 0; i < stack.undo.length; i++) {
                var ob = {};
                ob.redo = new Delta(stack.undo[i].redo.ops);
                ob.undo = new Delta(stack.undo[i].undo.ops);
                editor.history.stack.undo.push(ob)
            }
          }
          if (stack.redo.length > 0) {
            for (var i = 0; i < stack.redo.length; i++) {
                var ob = {};
                ob.redo = new Delta(stack.redo[i].redo.ops);
                ob.undo = new Delta(stack.redo[i].undo.ops);
                editor.history.stack.redo.push(ob)
            }
          }
        }  

var quill = new new Quill( /*config here*/)
var l_stack = jQuery.extend(true, {}, quill .history.stack)

loadHistoryStack(l_stack,quill);
```
