### ISSUE TITLE
ql-align display error

### ISSUE THREAD

**Issue by jayHuang332** [quilljs/quill#860]
I tried to custom my toolbar, but when I add align select tag to html, it's display error.

**Steps for Reproduction**
This is the code:

`toolbar: {container: "#quill-toolbar"}`

`<select title="Font" class="ql-align">`
`    <option value="left" selected></option>`
`    <option value="right"></option>`
`    <option value="center"></option>`
`    <option value="justify"></option>`
`</select>`

**Expected behavior**: [expected]

**Actual behavior**: In the drop down list, the size of icon become very big, maybe it's a problem of class missing. And I got a undefined text where left icon should be.

**Platforms**:  Chrome 51 on Mac 10.11

**Version**:  quill 1.0.0-beta.11

**Comment by jhchen** [comment]
I believe you need to omit the value attribute in your selected `<option>`. Quill does not know what values "mean", only that there is or isn't one or if they are the same. The dropdown you have right now would add the "left" value for align.
