### ISSUE TITLE
<div> instead <p> in content

### ISSUE THREAD

**Issue by kolesoffac** [quilljs/quill#861]
Can you use` "<div>"` instead `"<p>"`?
```
<div id="editor">
  <p>Hello World!</p>
  <p>Some initial <strong>bold</strong> text</p>
  <p><br></p>
</div>
```

Result:
```
<div id="editor">
  <div>Hello World!</div>
  <div>Some initial <strong>bold</strong> text</div>
  <div><br></div>
</div>
```

**Comment by jhchen** [comment]
Yes you just need to change the default Block tag name:

```js
var Block = Quill.import('blots/block');
Block.tagName = 'DIV';
Quill.register(Block, true);
```

Here's a [demonstration](http://codepen.io/quill/pen/VjgorV). There will be an in depth guide on using Parchment / Blots soon.

**Comment by ArtemKha** [comment]
import { Quill } from 'react-quill';

let Block = Quill.import('blots/block');
Block.tagName = 'DIV';
Quill.register(Block, true);

it doesn't work

**Comment by iamroi** [comment]
Thanks for the solution!

Is it possible to customize this for just editor on the page as I have multiple editors with different use cases on the same page?

Any help would be appreciated!

**Comment by sryzhok-edc** [comment]
Bad solution. After this fix I got other bugs: pasting of bulleted lists works incorrectly.

**Comment by tae997** [comment]
I wanted to add 1 more line in it for people who might get confuse or in case they are beginner - 
 
```
> var Block = Quill.import('blots/block');
> Block.tagName = 'DIV';
> Quill.register(Block, true);
```

one of my friend ask me about from where this Quill came from, in face she got confused and imported react-quill like this - 
`import Quill from 'react-quill';`

let me make this clear, Quill is actually sub part of react-quill.

```
import ReactQuill from 'react-quill';
const Quill = ReactQuill.Quill 
var Block = Quill.import('blots/block');
Block.tagName = 'div';
Quill.register(Block);
```

hope this will make you understand.

**Comment by sujitkrjha** [comment]
import dynamic from 'next/dynamic';

const ReactQuill = dynamic(async () => {
        const ReactQuill = await import('react-quill');
        const { Quill } = ReactQuill.default;
        const Block = Quill.import('blots/block');
        Block.tagName = 'div';
        Quill.register(Block);

        return ReactQuill;
    }, { ssr: false });

**Comment by Ashritha-12** [comment]
how to use span instead of p tag ?
