### ISSUE TITLE
How add "Authorship" in Quill 1.0 beta

### ISSUE THREAD

**Issue by kolesoffac** [quilljs/quill#865]
How can i add support module "Authorship" in Quill 1.0 beta? 
Why "Authorship is no longer a part of Quill in the 1.0 beta preview."??
Thanks

**Comment by sachinrekhi** [comment]
From Jason: "multi-cursor and authorship modules are not being included in 1.0. They are planned to be re-introduced in a future version."

https://github.com/quilljs/quill/issues/635#issuecomment-220243661

**Comment by jhchen** [comment]
Yes this is also stated in the [Upgrading to 1.0](http://beta.quilljs.com/guides/upgrading-to-1-0/) guide.

**Comment by mitar** [comment]
Any news on this?

**Comment by circleb** [comment]
Any ETA on this?
