### ISSUE TITLE
Keyboard Configuration Object bindings Overwrites dangerous browser defaults

### ISSUE THREAD

**Issue by CapTec** [quilljs/quill#866]
When initializing the keyboard module in the Quill constructor, if the keyboard bindings object contains a custom handler that binds to the key code for backspace, it completely breaks backspace functionality by over writing the default backspace handlers.

**Steps for Reproduction**

1. Visit [https://jsfiddle.net/vqekpht0/1/](https://jsfiddle.net/vqekpht0/1/)
2. Enter some text in Quill 
3. Press the backspace key
4. Open the console and examine the output

**Expected behavior**: 
I would expect to see the console output and backspace still function as it normally would. Additionally it seems there is no way to cancel propagation of backspace, contrary to the documentation

Documentation states:
Other bindings are essential to preventing dangerous browser defaults, such as the enter and **backspace** key. **These cannot be overwritten**, but your bindings specified in the configuration will **run before Quill’s** and you may choose to not **propogate**, however this is not recommended.

**Actual behavior**: 
I see the console output as expected, but Quill does not delete as expected.

**Platforms**: 
All supported browsers

**Version**: 
1.0.0-beta.11

**Current Workaround**
I work around this issue by essentially re-implementing the logic within the custom handler.
`if (range.index === 0) return;
                    if (range.length === 0) {
                        this.quill.deleteText(range.index - 1, 1, Quill.sources.USER);
                        this.quill.selection.scrollIntoView();
                    } else {
                        this.quill.deleteText(range, Quill.sources.USER);
                        this.quill.setSelection(range.index, Quill.sources.SILENT);
                        this.quill.selection.scrollIntoView();
                    }`

**Comment by jhchen** [comment]
The documentation is worded confusingly. Hopefully the update is more clear:

> Some bindings are essential to preventing dangerous browser defaults, such as the enter and backspace keys. You cannot remove these bindings to revert to native browser behaviors. However since bindings specified in the configuration will run before Quill's defaults, you can handle special cases and propagate to Quill's otherwise.

```js
var bindings = {
  list: {
    key: 'backspace',
    context: {
      format: ['list']
    },
    handler: function(range, context) {
      if (context.offset === 0) {
        // When backspace on the first character of a list,
        // remove the list instead
        this.quill.format('list', false, Quill.sources.USER);
      } else {
        // Otherwise propogate to Quill's default
        return true;
      }
    }
  }
};
```

**Comment by CapTec** [comment]
That makes a lot more sense to me now. Good to know it's not a bug. Thanks for the clarification, I'm sure it'll help others too.
