### ISSUE TITLE
Cannot Print

### ISSUE THREAD

**Issue by grintor** [quilljs/quill#867]
No text in the editor prints using the latest version of chrome and quill

**Steps for Reproduction**

Save this example html file:

```
<html>
	<head>
		<link href="https://cdn.quilljs.com/1.0.0-beta.11/quill.snow.css" rel="stylesheet">
	</head>
	<body>
		<div id="editor"><p>Some initial <strong>bold</strong> text</p></div>
		
		<script src="https://cdn.quilljs.com/1.0.0-beta.11/quill.js"></script>
		
		<script type="text/javascript">
		  var quill = new Quill('#editor', {
			theme: 'snow'
		  });
		</script>
		
	<body>
</html>
```

If you [ctrl]-[p], none of the text you enter will show up in the print preview window.

**Expected behavior**:

something should print

**Actual behavior**:

nothing prints

**Platforms**:

chrome 57 windows 7

**Version**:
1.0.0-beta.11

**Comment by jhchen** [comment]
The dev channel of Chrome is only on 54 so I assume you meant 52. 

I tested on Windows 10 and Windows 7 with Chrome 52 and am not able to reproduce. Note the content is on the next page but it is present. You just have to fix the css for print view.

Can anyone else reproduce this issue?

![print](https://cloud.githubusercontent.com/assets/192974/17757052/042a247c-6499-11e6-8264-2905c69b57a2.gif)

**Comment by grintor** [comment]
The Next Page!!! O geez, I didn't realize there was a second page. Is that expected behavior? I certainly wasn't expecting it... Maybe someone should tweak the theme css to make that not happen?

Anyway, thank you for pointing that out, I don't think I would have ever found that second page.

**Comment by sachinrekhi** [comment]
I ran into the same second page issue on print, which I solved through media queries to clean up the outputted content on print to get a nice and clean print.

I think each application will likely have to clean up the print version via media queries slightly differently given they likely want to clear chrome, other parts of their app, etc so think this might just be something each app needs to take on individually.

**Comment by sferoze** [comment]
For printing I actually render the quill editor with no toolbar, no theme, and read only inside a hidden div. Then  once rendered I grab the html inside the div and use window.open to open a new window with the html generated after rendering the editor. This is a very clean way to print as all that is printed is the actual contents from the quill editor, with all its formatting still intact.

**Comment by jhchen** [comment]
I'm generally in agreement with @sachinrekhi and am not sure what css could be added since one has to consider use cases where Quill:

- taking up the whole page
- takes up part of the page with the toolbar above it
- takes up part of the page with toolbar detached / completely separate

In addition many production apps will probably be using one of the popular css frameworks and/or resets. If all this could be had and cover a significant portion of Quill users without diminishing the experience of others, I'm happy to take a look at a PR.
