### ISSUE TITLE
Bold and Italic inserts unwanted br tags

### ISSUE THREAD

**Issue by DWMS-Bryan** [quilljs/quill#869]
Just went from 0.20 to the new 1 rc and now quill is performing very strangely in Firefox, haven't tested in other browsers.
When I use the toolbar buttons to bold or italicize text I sometimes get a < br> tag inserted as well, and occasionally the whole editor crashes and nothing works from that point forward.  When these unwanted < br> tags are added, they can't be removed without deleting the entire content of the editor which sometimes causes a fatal crash where the editor no longer responds at all.

Windows 10 / Firefox latest / Quill latest.

**Comment by benbro** [comment]
Did you try with version 1.0.0-rc0?
http://quilljs.com/

Can you list exactly the steps to reproduce as the bug instruction request?

**Comment by DWMS-Bryan** [comment]
Yes, 1.0.0-rc0. 
I just did this:
Step 1: set up a basic quill editor following the instructions on quill.js quickstart.
Step 2: type some text, hit the bold button in the toolbar, get an unwanted <br> at end of line.
Step 3: select some text, hit the bold button in the toolbar, get an unwanted <br> in middle of sentence.

**Comment by jhchen** [comment]
Can you paste the exact quickstart instructions you mentioned from step 1 and right after step 2 paste the exact innerHTML of the editor contents?

**Comment by DWMS-Bryan** [comment]
Here's the test page:
`<!DOCTYPE html>
<html>
<head>
  <title>Quill.js</title>
  
<link href="https://cdn.quilljs.com/1.0.0-rc.0/quill.css">
</head>
<body>

<div id="toolbar">
    <button class="ql-bold"><b>Tt</b></button>
    <button class="ql-italic"><i>Tt</i></button>
</div>
<div id="editor">
  <p>Hello World!</p>
  <p>Some initial <strong>bold</strong> text</p>
  <p><br></p>
</div>

<script src="https://cdn.quilljs.com/1.0.0-rc.0/quill.js"></script>

<script type="text/javascript">
  var quill = new Quill('#editor', {
    modules: {
        toolbar: '#toolbar'
      },
  });
</script>
</body>
</html>`
Here's the quickstart: http://quilljs.com/docs/quickstart/

Here is the innerHTML:
`<p>asdfasdfasdfasdf <br><strong>asdfasfdasfd</strong></p><p><br></p>`

**Comment by jhchen** [comment]
When you say minimal do you mean you are using quill.core.css and quill.core.js?

**Comment by DWMS-Bryan** [comment]
I'm using the cdn sources-
`<link href="https://cdn.quilljs.com/1.0.0-rc.0/quill.css"> 
<script src="https://cdn.quilljs.com/1.0.0-rc.0/quill.js"></script>`
all of which I found here: http://quilljs.com/docs/download/

**Comment by jhchen** [comment]
Okay the issue is https://cdn.quilljs.com/1.0.0-rc.0/quill.css is not a valid url. The naming scheme got changed to https://cdn.quilljs.com/1.0.0-rc.0/quill.core.css in the release candidate and I missed the download page. This has now been updated.

**Comment by DWMS-Bryan** [comment]
That doesn't fix the issue for the snow theme though does it? Nor does using the new url change anything for me. :(

**Comment by jhchen** [comment]
If you want to use the snow theme you have to include https://cdn.quilljs.com/1.0.0-rc.0/quill.snow.css. Are you sure it's not a caching issue? I definitely reproduced your issue by not having any quill css file and it was fixed by added any quill css file. 

If it is definitely not a caching issue, can you fork this [codepen](http://codepen.io/quill/pen/KzZqZx) and update it with your settings?
