### ISSUE TITLE
Integration examples with forms

### ISSUE THREAD

**Issue by jonchay** [quilljs/quill#87]
I read through the documentation and I couldn't find an example of integration with a textarea in a form:

``` html
<textarea id="editor"></textarea>
```

``` js
var editor = new Quill('#editor');
```

This just injects the iframe inside the textarea DOM node. Are there any examples of integration?

**Comment by garygreen** [comment]
This is a real pain the ass with Quill at the moment. You need to add extra boilerplate to wrap textarea in a div, then listen for update events and re-map the html back to the textarea, or listen for form submit and set the textarea content. Would be nice if quill did this under the hood if the passed element is a `<textarea>` -- most editors do.

**Comment by jhchen** [comment]
What is the real world use case of a rich text editor mirroring a plain text textarea?

If the end goal is form submitting plaintext why use a rich text editor at all?

If the goal is to submit rich text, then you cannot use a textarea anyways and will have to submit via ajax post. The difference here then is only calling `getContent()` instead of `getText()` or `$('#editor').val()`.

**Comment by garygreen** [comment]
> If the goal is to submit rich text, then you cannot use a textarea anyways and will have to submit via ajax post.

This is the goal and why would you need to use ajax? If the textarea's value mirrored the HTML from quill, or you updated the textarea with the HTML just before submitting the form you don't need ajax. I think it would be fair to assume that if quill is attempting to be initialised on a form element i.e. a textarea or input, then the final HTML generated by Quill is going to be submitted as part of the form data. A lot of wysiwyg editors do this, tbh I haven't come across one that chokes if you give it a textarea element, it knows what your trying to do ;).

It's not really a biggie as it's easy enough to do with some event listeners and stuff, but I love libraries where you can get going with minimal effort and boilerplate.

**Comment by jhchen** [comment]
I see I was under the impression people wanted to sync Quill's text with a textarea, not its HTML contents. HTML is something Quill wants to abstract away but I'll keep this use case in mind.

**Comment by TechNyquist** [comment]
When I show a richtext editor on the client-size, I assume an HTML plain text server-side. This is probably the reason of the question, and when I initialize Quill on a textarea I expect to happen:

1. Quill to pick the textarea's name
2. Quill to let me edit richtext
3. Quill to submit "plain HTML" to the server

just like I'm doing now with "getContent()", but...automated :)
This is just a feature-request, sure Quill is already powerfull as it is!

**Comment by mlewis-everley** [comment]
I would very much like to see the following as well:

`<textarea id="editor"></textarea>`

`var editor = new Quill('#editor');`

We are going to be integrating quill into our CMS (that makes use of traditional HTML forms) and does expect plain text to be submitted via a form post.

We can add ajax via this, but it does involve extra faff, would be great if for a basic implementation we could just map Quill to an existing text area.

Quill is a very cool editor, but surely adding this feature would expand it's appeal and usage?

**Comment by jhchen** [comment]
@mlewis-everley What's the use case for using Quill instead of a `<textarea>` if the formatting is just going to be lost when the submit button is clicked?

**Comment by babf** [comment]
Hi, I vote for this too. I want to let my users submit HTML formatted comments via a form textarea element. I want to receive the text they write and the _formatting_ they wish to see applied to that text.

**Comment by pascalwacker** [comment]
+1 it would be great to just have a textarea `<textarea name="foo" id="foo"><h1>FooBar</h1><p>Foo and Bar = Baz</p></textarea>` like for example `TinyMCE` is doing http://codepen.io/tinymce/pen/YydQrY

**Comment by simonmilz** [comment]
+1 for this.

**Comment by alexkrolick** [comment]
It doesn't make sense to synchronize a RTE with a visible `textarea`. Why not just listen to the changes in the editor and periodically getContent() and put that in an `<input type="hidden">`?

**Comment by TechNyquist** [comment]
Because you can be sure that the user is going to submit the form when the
hidden field is not up-to-date, eheheh.

Il 08 set 2016 18:51, "Alex" <notifications@github.com> ha scritto:

It doesn't make sense to synchronize a RTE with a visible textarea. Why not
just listen to the changes in the editor and periodically getContent() and
put that in an <input type="hidden">?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/quilljs/quill/issues/87#issuecomment-245662939>, or mute
the thread

**Comment by alexkrolick** [comment]
True, you may want to watch the dirty state and use a beforeunload. Here's an example:

http://codepen.io/whokilledtheelectricmonk/pen/xEGmJJ

**Comment by alexkrolick** [comment]
@benbro this keeps coming up, do you want to link to that pen in docs?

**Comment by jhchen** [comment]
There is now a [Form Submit](https://quilljs.com/playground/#form-submit) and [Autosave](https://quilljs.com/playground/#autosave) example in the Quill Playground.

**Comment by pascalwacker** [comment]
That's perfect! +1

**Comment by garygreen** [comment]
Meh. I wouldn't say perfect, it's exactly the same as it was before but now there's an example for how to do it. This issue is all about having it baked into the core so you don't need that kind of boilerplate code to when working with forms.

**Comment by Garbee** [comment]
The major point here is *Progressive Enhancement*. You have a textarea already to be filled in, quill should *enhance* it when JS is available to provide a good editing experience. Then whether the form submit is ajax or not, the contents can be submitted just fine without any extra effort on the developers part.

Not having progressive enhancement here is a major dealbreaker, especially in cases like e-commerce use where developers need to be sure their sites are accessible to as many people as possible. Which yes, does include users that turn off JS.

**Comment by ahmadalukah** [comment]
+1 for this ,, a text editor without a textarea ,, why ! 😢

**Comment by TechNyquist** [comment]
Hi quilljs/quill,

Build your professional network, discover opportunities, and keep in touch with me on LinkedIn.

- Niki

Confirm that you know Niki: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=PdxLYiNh&invitationId=6193352721995755521&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiucfpf42%7Euh








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iucfpf42-uh&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEm89NX1viTPgAAAVfM1q3aqmcYTBp_l0UkRh616y7zBjrn2KDve08xnuoWl2WV-apammCYPIuo3AwvCzXIm1A_iH_qmNA6nrxUcKCv_OWjCNClt8G7A0Bb-YA9-pglwbzvm0vgSFG7l8h0bl4-4Y2FRIEbEXjYhNUwX6YWUa_TFmde8deMs0bm_bUFcLi48_wn&eid=0-iucfpf42-uh


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iucfpf42-uh&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by TechNyquist** [comment]
Niki Romagnoli would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=PdxLYiNh&invitationId=6193352721995755521&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-h23o98%7Eiui3em25%7Eo5

View Niki Romagnoli&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=PdxLYiNh&invitationId=6193352721995755521&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-h23o98%7Eiui3em25%7Eo5





Hai ricevuto un invito a collegarti. LinkedIn userà il tuo indirizzo email per fornire suggerimenti ai membri in funzionalità come “Persone che potresti conoscere”. Annulla l’iscrizione qui: https://www.linkedin.com/e/v2?e=h23o98-iui3em25-o5&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=h23o98-iui3em25-o5&loid=AQE_B9ZHItDq0AAAAVfh0QazZ60LlQmy2OXsBqqAxSXF8C7Tymzz_P-AWRYkBCqI3b_6nhOeuQUGom0q-iSW6Pt1B_lKfnBLhmKCzZriTgokLI-voGjVkWSKf7BXCBWDO_vgabBoR0K4axCxyL39dT5Tl4M2FQpwLNY3DrYxqQm5IuZ2r10ZWB83bdE73PQGQFQl

Questa email è stata inviata a reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=h23o98-iui3em25-o5&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn e il logo LinkedIn sono marchi registrati di LinkedIn.

**Comment by allw1994** [comment]
I agree with the above people, why are you making submission harder and potentially error prone if we have to fall back to no JS?

**Comment by bobbypriambodo** [comment]
An illustration of the above use case is:

1. The server wants to receive HTML content (a blog post, maybe, or a news article) from a field named `content`. Other fields (`title`, etc.) might exists.
2. One way to make it possible is to have a textarea and tell users to write HTML code. A nightmare.
3. We resort to RTE for abstracting away the HTML generation, which @Garbee rightfully said as *progressive enhancement*.

But that's it. The rest of the form should still be intact; only the HTML generation on the textarea field needs to be handled. On clicking the submit button, the form should behave as a form. No JS should be necessary for submitting HTML forms. Not all web applications are SPAs and AJAX-based, some are still conventional multi-roundtrip server-rendered pages. Not to mention also for supporting people who turn off JS on their browsers.

Quill is great, but this is the major pain point preventing me from adopting it for my projects. TinyMCE and other RTEs provides this out-of-the-box, so if Quill wanted higher adoption rate I think it would be great to tackle this use case. It's another story if web pages with conventional forms are not your intended users though (which is a shame).

**Comment by aguynamedben** [comment]
Another thing to note related to this is that a <textareas> allows users to tab to the textarea from previous form elements. So when a user is filling out the form, they can type, hit tab, type, hit tab, etc. This breaks if you're trying to use Quill as part of a form. This is exacerbated on mobile where users have very prevalent arrows on their touch keyboards that take them to the next form element.

**Comment by erw13n** [comment]
This is what I do to grab it 
```
var myEditor = document.querySelector('#editor')
var html = myEditor.children[0].innerHTML
```

**Comment by jacurtis** [comment]
What @erw13n demo's above is actually the first example in this extremely long thread that is demonstrating how to actually achieve what everyone is looking for. This gives you the actual HTML tags to recreate the rich text that the user "designed" in the text editor.

While still not ideal, you can bind this line of JS to a submit event for the form. Create a hidden textarea in your form first. Then when submitted, you would want to disable the quill editor (so a user can't make last-millisecond changes during the copy), then copy the `.innerHTML` (as he shows above) as plain text to the `<textarea>`, which is then submitted to the server like most other WYSIWYG editors.

Yes, this is an extra, arguably unnecessary step. But considering the advantages that quill does provide, it isn't that bad.

_Side Note: make sure you still sanitize the submitted HTML on the server side before it is put into a DB. A user could still easily inject malicious code into your hidden textarea and submit it to the server. So using a purifier or sanitizing library is still necessary (as you are hopefully doing with any other WYSIWYG editor already)._

**Comment by jhchen** [comment]
@jacurtis Please understand what was being discussed in this thread before getting on your high horse. You are conflating the question about the transport (AJAX) and the contents (HTML). 

A normal form submission can only submit a string regardless of how many miles you are into the countryside. I assumed since Quill is about rich-text and its contents are not a string, AJAX is the only option for form submission:What is the real world use case of a rich text editor mirroring a plain text textarea?

> If the end goal is form submitting plaintext why use a rich text editor at all?
>
> If the goal is to submit rich text, then you cannot use a textarea anyways and will have to submit via ajax post. The difference here then is only calling getContent() instead of getText() or $('#editor').val().

As soon as the error in understanding was pointed out I corrected myself:

> I see I was under the impression people wanted to sync Quill's text with a textarea, not its HTML contents.

Storing HTML contents is not something I wanted to promote at the time (and still don't) and the possible solutions are numerous and simple enough I felt someone from the community could answer (which it was) without an endorsement from me or the project so it was left at that.

You can disagree with decisions and make arguments on technical ground but if you are to continue to participate you will leave the rest at the door.

**Comment by Garbee** [comment]
> I assumed since Quill is about rich-text and its contents are not a string, AJAX is the only option for form submission:

This is the fundamental assumption that isn't quite correct. There is the option for developers to restrict the content to be purely string based content (markdown/HTML) which will transmit fine through a regular textarea. All we need to do is restrict the toolbar nodes to those that correlate to plain string data.

However, the assumption has been made and there are no clear signs of this changing. I've personally moved onto other projects to get the task done and I only consider Quill when JS can be required for an app.

**Comment by gavin667** [comment]
https://codepen.io/k3no/pen/amwpqk

**Comment by Garbee** [comment]
@jhchen why delete my previous comment here? I don't recall marking any remarks that weren't strictly technical as to why this should be done.

It seems to me like you are against having a productive discussion here. All you are doing is ignoring any requests to discuss *progressive enhancement* techniques that could be implemented. While the personal attacks are wrong, it is frustrating to have the discussion ignored and looked down upon entirely.
