### ISSUE TITLE
Beta website depcreated?

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#870]
[Describe the issue]
The beta website (beta.quilljs.com) has the 1.0-beta.11 version instead of the rc0 version.
The stable website has the 1.0-rc0.
You'll might want to remove/update the beta website.

Pages with 1.0-beta.11 instead of 1.0-rc0
http://beta.quilljs.com/
http://beta.quilljs.com/docs/formats/

**Comment by jhchen** [comment]
Yes it now redirects thank you.
