### ISSUE TITLE
Ordered list does not increment properly if use all 8 indent levels

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#873]
Ordered list works great, except in the extreme case when you attempt to use all 8 supported indent levels. After using the 8th indent level, then when you un-indent, the previous indent levels are no longer incrementing properly.

**Steps for Reproduction**

1. Visit quilljs.com
2. Create a list with 0, 1, 2, 3, 4, 5, 6, 7, 8 and indent each at their respective indent level
3. After 8, un-indent one level

**Expected behavior**:
The un-indented bullet should be labeled b.

**Actual behavior**:
The un-indented bullet is labeled a.

![screen shot 2016-08-19 at 4 33 27 pm](https://cloud.githubusercontent.com/assets/192650/17826954/d0f73408-662a-11e6-8514-613407b614c4.png)

**Platforms**:
Chrome 52 on Mac 10.11

**Version**:
Quill 1.0 RC 0

**Comment by jhchen** [comment]
Quill's stylesheet only covers 8 levels with the thinking that most real documents would only actually utilize up to 4 levels. The obvious solution is to increase this number but then the question is what should the limit be? I'm not aware of a way to cover infinite levels.

**Comment by sachinrekhi** [comment]
Oh 8 levels is certainly plenty, my point was that it looks like it in-fact only supports 7 levels even though it looks like it supports 8 given how the subsequent numbering is incorrect after you use all 8 levels.

My proposal is just to ensure when you indent to 8 levels, the subsequent un-indented numbering works fine. Or alternatively prevent indenting to level 8, where the subsequent un-indented numbering no longer works (so just support 7 levels).
