### ISSUE TITLE
Using Formula in RTL is misplacing last character

### ISSUE THREAD

**Issue by BenAsaf** [quilljs/quill#875]
Hello,

Using Formula in RTL setting with the equation: `e=mc^2` is rendered as: `^2e=mc`

**EDIT:** Seems that changing the browser "Writing Direction" to 'LTR' fixes it.

**Steps for Reproduction**

1. Visit: http://quilljs.com/docs/formats/
2. Step Two:
   Change to RTL
3. Step Three
   Insert the Formula: `e=mc^2`

**Expected behavior**: It should render as is, meaning: `e=mc^2`

**Actual behavior**:  It renders it as: `^2e=mc`

**Platforms**: Chrome Version 52.0.2743.116 m (64-bit)

**Version**: Latest release of QuillJS, 1.0v

**Comment by benbro** [comment]
Maybe adding this style can help
```css
.ql-formula {
  direction: ltr;
}
```

**Comment by jhchen** [comment]
What does changing the browser "Writing Direction" to 'LTR' fixes it mean? Is this still an issue?
