### ISSUE TITLE
formatText bug

### ISSUE THREAD

**Issue by DadaMonad** [quilljs/quill#876]
Incorrect formatting when using formatText.

**Steps for Reproduction**

1. Visit quilljs.com (quill@1.0.0-rc.0)
2. `quill.setText('\n\n')`
3. `quill.formatText(1, 1, 'align', 'right')`
4. `quill.formatText(0, 2, 'code-block', true)`

**Expected behavior**: `quill.getContents().ops` => `[{ insert: '\n', attributes: { "code-block": true }}, { insert: '\n', attributes: { "code-block": true, "align": "right" }}]`

**Actual behavior**: `quill.getContents().ops` => `[{ insert: '\n\n', attributes: { "code-block": true }}]`

**Platforms**: Chrome 52

**Comment by jhchen** [comment]
Code-blocks as designed must be plaintext and cannot have any formatting. The behavior you are seeing is expected.
