### ISSUE TITLE
Toolbar align picker does not render correctly in Microsoft Edge

### ISSUE THREAD

**Issue by CapTec** [quilljs/quill#877]
A quill instance that has an align picker menu does not render correctly in Microsoft Edge browser.

**Steps for Reproduction**

1. Visit https://jsfiddle.net/xwyj2zou/2/ with Microsoft Edge browser.
2. Click on the Align picker
3. The picker items overlap and render larger than they should.

**Expected behavior**: Rendering of each picker option in a single vertical line.

**Actual behavior** All picker options overlap and render at an extremely large resolution.

**Platforms**: Microsoft Edge Browser,  Windows 10

**Version**: 25.10586.0.0,

**Comment by benbro** [comment]
I can reproduce on Edge 14.

In addition, with IE11 on Windows 7 the width of the popup is much larger. Please see attached image.
![align-ie11](https://cloud.githubusercontent.com/assets/75841/17861249/f0450c02-6898-11e6-8dd8-ae1fd0cb08ee.png)
