### ISSUE TITLE
Editor loses focus when forward-deleting the text in a paragraph

### ISSUE THREAD

**Issue by mikrostew** [quilljs/quill#880]
This happens in the standalone editor, but it doesn't reproduce for me on quilljs.com or quilljs.com/playground.

**Steps for Reproduction**

1. Visit the standalone editor: http://quilljs.com/standalone/snow/
2. Type 'test' in the editor
3. Hit the up arrow to go to the beginning of the text
3. Hit DEL (fn-DEL on Mac) 4 times to delete the text

**Expected behavior**: I expect the editor to retain focus.

**Actual behavior**: The editor loses focus.

**Platforms**: Chrome 52 on Mac 10.11

**Version**: 1.0.0-rc.0

**Comment by jhchen** [comment]
I'm not seeing this on the standalone editor either. 

![880](https://cloud.githubusercontent.com/assets/192974/18038828/45ac2290-6d51-11e6-936a-310f8304699d.gif)

Can anyone else reproduce this?

**Comment by mikrostew** [comment]
This is not reproducing for me in incognito, must be one of my extensions/add-ons causing an issue.
