### ISSUE TITLE
quill.min.js missing from 1.0.0-rc1

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#881]
1.0.0-rc1 release doesn't have the quill.min.js file.

**Comment by benbro** [comment]
Is this intentional?
https://github.com/quilljs/quill/commit/d2ac13d958aa23af83d83ee4d0d52ac8c3bbd48d

**Comment by jhchen** [comment]
Apologies you are correct the minified file was not included in the release download. It should still be available in an npm install and the CDN. I've uploaded a new tar with quill.min.js and the corresponding sourcemap. Thanks!
