### ISSUE TITLE
Can't remove indentation on right-to-left line

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#882]
[Describe the issue]
Followup on https://github.com/quilljs/quill/issues/874
When changing the direction of an indented line, we can't remove the indentation.

**Steps for Reproduction**

1. Visit http://quilljs.com/docs/formats/
2. Type 'abc'
3. Click on the indent-right button.
5. Click on the text-direction button to change to right-to-left.
6. Try to indent right (remove indentation).

**Expected behavior**: [expected]
The indent left button should be highlighted.
Indenting right should remove the indentation.

**Actual behavior**: [actual]
The indent right button is highlighted.
Clicking on the indent right button does nothing

**Platforms**:
Chrome 52 on Windows 7

**Version**: [version]
1.0.0-rc1

**Comment by jhchen** [comment]
Actually this seems like a manifestation of a larger issue with indent's active state. Like Word, it should never light up, and it is on the 1st indent level which on normal text direction this is preventing indenting past the 1st level, and on rtl is preventing dropping below 1 level.
