### ISSUE TITLE
Copy from raw github page adds a gray background

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#888]
[Describe the issue]
Copy&paste from a raw github page to quill adds a gray background color.
If it's an edge case, feel free to close this issue.

**Steps for Reproduction**

1. Visit http://quilljs.com/playground/
2. Select and copy the text from a raw github page https://raw.githubusercontent.com/quilljs/quill/develop/core.js
3. Paste the text to quill

**Expected behavior**:
Text should appear without background color

**Actual behavior**: [actual]
A gray background color is added

**Platforms**:
Chrome 52 on Windows 7

**Version**: [version]
1.0.0-rc2

**Comment by jhchen** [comment]
It's actually being pasted as a code-block, which is being styled with a gray background. If you add the code block button to the toolbar it becomes more obvious since when you place your cursor over the text it highlights the button. http://codepen.io/quill/pen/oLAJkL

**Comment by JNaeemGitonga** [comment]
Hello @jhchen is there a way to disable that behavior. When copying and pasting from an outside source have it paste as plain text without the code-block?
