### ISSUE TITLE
Undo/redo inconsistency when replacing chunk of content with multiple formats

### ISSUE THREAD

**Issue by cutteroid** [quilljs/quill#889]
Undo/redo chain become inconsistent when replacing chunk of editors content (wich has multiple formats) with text

1. Visit [quilljs.com](http://quilljs.com)
2. Select all content in editor and input letter (Q for example)
3. Hit Undo
4. Hit Redo. Notice that `q` letter is now in code block
5. Hit Undo again. Notice how initial content has changed

**Expected behavior**: Undo/redo history works correctly

**Actual behavior**: Editor content is altered after some undo/redo operations

**Version**: 1.0.0-rc.2

![undo_redo](https://cloud.githubusercontent.com/assets/20125880/17974461/d7c8fd0c-6aee-11e6-9fba-bb8ee10cd44a.gif)

Also on certain conditions i'm getting
```Uncaught TypeError: Cannot read property 'mutations' of undefined```
when replacing part of editors content with text in Chrome browser.
Maybe it is related to described undo/redo problem.

![chrome_bug](https://cloud.githubusercontent.com/assets/20125880/17974492/fee25d20-6aee-11e6-84cb-13ce035e4428.gif)

**Comment by sachinrekhi** [comment]
@jhchen In the commit fix you mention you made a change to the Delta format? Does that mean the rich-text Delta library changed to accommodate this change?

**Comment by jhchen** [comment]
No the editor's behavior is changed to exhibit what delta already does, so rich-text stays the same.
