### ISSUE TITLE
Code block keeps superfluous letters with Chinese IME

### ISSUE THREAD

**Issue by luin** [quilljs/quill#896]
Gif here: ![](http://g.recordit.co/LrLJ3yzto0.gif)

**Steps for Reproduction**

1. Visit quilljs.com.
2. Insert a code block to the editor on the index page.
3. Input a word with Chinese IME.

**Expected behavior**: Only the selected word ("我" in the above example) will show in the editor.

**Actual behavior**: Got "我", its pinyin "wo" and the first letter of pinyin "w".

**Platforms**: Chrome 52 on Mac 10.11.5

**Version**: 1.0.0 rc2

note: I tried removing the highlight module and input Chinese again, I got "w我" instead of "wwo我".

**Comment by luin** [comment]
Thank you for the quick fix! The issue of the syntax module is confirmed being fixed. However, when using code block without syntax highlighting, the first inputted Chinese letter still go with its pinyin as I noted in the issue description above.

Here's a gif to reproduce the issue:

![](http://g.recordit.co/qNfV9l2Rg2.gif)
(using the builtin IME)

![](http://g.recordit.co/n2UC5buGZ1.gif)
(using the Sogou IME)

**Comment by jhchen** [comment]
It's working fine for me on Mac + Chrome. A new version will be out tomorrow. Can you check quilljs.com then?

**Comment by luin** [comment]
Congratulation for the new version! The issue is still here:

![](http://recordit.co/2HhDjqUB3J.gif)

Only the first word will be affected.

**Comment by wangdong** [comment]
![2017-03-28 2 29 02](https://cloud.githubusercontent.com/assets/9663/24391654/eaf4300e-13c2-11e7-86c3-170a4c241bc5.png)

The problem is still there, we have to reopen this issue. @jhchen

**Comment by wangdong** [comment]
![2017-03-28 2 29 02](https://cloud.githubusercontent.com/assets/9663/24391697/23416530-13c3-11e7-8022-dc210026aab2.png)
The problem is still there, we have to reopen this issue. @jhchen

**Comment by liruilong** [comment]
Safari 10.1 (12603.1.30.0.34)
@jhchen 
![image](https://cloud.githubusercontent.com/assets/8872707/24795451/f816dc86-1bbb-11e7-9320-3aaee3ecac3b.png)

**Comment by OnlyBreak** [comment]
this problem is still there, could u resolve it? @jhchen

**Comment by ZhangChao781** [comment]
Same problem, it always keep the first letter, and only happen in a new empty line.
