### ISSUE TITLE
Last pasted line is using the alignment and direction of the active line in the editor

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#898]
When pasting several lines into the editor, the last line uses the alignment and direction of the currently active line in quill.
 I think that in multi-line paste the editor should ignore the formatting in quill and only use the paste formatting or no formatting for plain text. Not sure what to do with 'inline' paste.

**Steps for Reproduction**
1. Visit http://quilljs.com/docs/formats/
2. Press on the alignment button and change the line to 'center'
3. Copy the following three lines and paste in quill

```
aaa
bbb
ccc
```

**Expected behavior**:
All pasted lines should have the same alignment.

**Actual behavior**:
The last line has center alignment

**Platforms**:
Chrome 52 on Windows 7
Firefox 48 on Windows 7

**Version**: [version]
1.0.0-rc3

**Comment by Hamza-Khurshid** [comment]
Facing the same issue, any update on this

**Comment by benbro** [comment]
Fixed in v2.0.0-rc.0
