### ISSUE TITLE
Text direction lost on paste from Word

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#900]
When I copy a line with direction:rtl in Word to Quill, the direction is lost.
Quill does preserve other formatting like text alignment.

**Steps for Reproduction**

1. Visit http://quilljs.com/docs/formats/
2. Open this [doc in Word](https://drive.google.com/open?id=0B12AhxvnYHrAek5TMGZKRXFTWWs)
3. Copy the text form Word to Quill

**Expected behavior**:
Lines should have both right alignment and rtl text direction

**Actual behavior**:
Lines have right alignment but missing the rtl text direction

**Platforms**:
Firefox 48 on Windows 7
Chrome 52 on Windows 7
Office 2013 on Windows 7

**Version**:
1.0.0-rc3

**Comment by hamzeh010** [comment]
`+        const delta = this.editor.clipboard.convert(`<div class='ql-direction-rtl ql-align-right cairo-font'>${parsedContent.body.html}</div>`);
`
