### ISSUE TITLE
Resizable Images

### ISSUE THREAD

**Issue by joekrump** [quilljs/quill#905]
Hi, I've reacted an image component that is resizable and would like to be able to insert this into the editor when I upload an image. I'm have a very difficult time trying to find out how to add a custom button to the toolbar in the 'bubble' theme and to give it a custom icon as well and then attaching a custom handler to this. Any help would be appreciated.

Update: 

I've begun to figure things out thanks in part to this: https://quilljs.com/guides/cloning-medium-with-parchment/

After a little extra work I was able to figure out how to insert a React Component into the editor. This component allows for image resizing. I'm happy to say that I can now add resizable images into the Quill editor.

![image resizing](https://cloud.githubusercontent.com/assets/3317231/18188658/b18d4f7e-7068-11e6-8f7c-cc54a519faaa.JPG)

![image resize 2](https://cloud.githubusercontent.com/assets/3317231/18188663/b69c8a34-7068-11e6-9f56-f01ac29f8474.JPG)

**Comment by alexkrolick** [comment]
@joekrump Cool, would it be possible to share your resizable image module?

**Comment by jhchen** [comment]
The last part of the container option in the toolbar docs should cover this: http://dev.quilljs.com/docs/modules/toolbar/#container.

Also there are extra unused icons in the quill/assets/icons folder if you'd like to use those.

**Comment by joekrump** [comment]
@alexkrolick Hey Alex, I may be able to share it in a bit. I'm pretty busy with a large project that I've been working on and so I haven't been able to export this in a nice modular way. It is a react component with quite a few dependencies. If I have the chance to export it as a package in node I'll let you know.

**Comment by ergo** [comment]
@joekrump any news on this?

**Comment by stevenwinslowwhite** [comment]
+1 - @joekrump would love to use what you have if it ever gets published.

**Comment by joekrump** [comment]
@ergo @stevenwinslowwhite Unfortunately I've not made any notable progress since my last post as fulltime work and another side-project have been eating up a lot of my time. I have a long weekend this weekend and may have a bit of time to work on this and can perhaps even push the code in a modular form so that any of you can take a look at it and perhaps continue on with dev work.

**Comment by stevenwinslowwhite** [comment]
Great - I will be building out something similar if not using yours, so if
you post what you have I can try to morph it to our use case, and push any
updates.

**Comment by danielreed07** [comment]
+1 Would be great to see this feature. It's like the only thing Quill is missing.

**Comment by Julioocz** [comment]
@joekrump can you provide some tips for inserting react components into the editor?. Thanks
