### ISSUE TITLE
Incorrect handling of initial or pasted nested lists

### ISSUE THREAD

**Issue by cutteroid** [quilljs/quill#906]
At the moment editor cant handle nested lists
1. Visit [playground](http://quilljs.com/playground/)
2. Paste this in `html` tab
   
   ``` html
    <div id="editor-container">
           <ol>
               <li>one</li>
               <li>
                   <b>two</b>
                   <ul>
                       <li>unordered</li>
                       <li>unordered</li>
                   </ul>
               </li>
               <li>three</li>
           </ol>
       </div>
   ```
3. Notice incorrect list structure in editors tab

**Version**: 1.0.0-rc.4

**Comment by lo1tuma** [comment]
Similar to the mentioned issue, I guess I come across a scenario that can’t be expressed as a `Delta` object where line breaks are used to specify block elements/styles:

```
         <ol>
            <li>one</li>
            <li>
                <b>two</b>
                <ul>
                    <li>unordered</li>
                    <li>unordered</li>
                </ul>
                <b>still two</b>
            </li>
            <li>three</li>
        </ol>
```

As you can see there is another text after the nested lists ends which still belongs to the second list item.

**Comment by jhchen** [comment]
There is the remaining issue of the numbering being incorrect in the example but there is another issue #829 regarding this specifically
