### ISSUE TITLE
Disabled editor scrolls when clicking the space bar

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#908]
**Steps for Reproduction**

1. Visit http://quilljs.com/
2. Write quill.disable(); in the console to disable the editor.
3. Press on the space bar keyboard key.

**Expected behavior**:
Nothing should happen because the editor is disabled.

**Actual behavior**:
The editor scrolls to the bottom

**Platforms**: [ex. Chrome 48 on Mac 10.11]
Chrome 53 on Windows 7
Firefox 48 on Windows 7

**Version**: [version]
1.0.0-rc4

**Comment by jhchen** [comment]
The spacebar causes scrolling on all scrollable web page when there is no focus on an input box. Try scrolling to the top of this issue page, click on the side or otherwise make sure you are not focused on a textbox and hit the space bar.
