### ISSUE TITLE
Toolbar is active when the editor is disabled

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#909]
When the editor is disabled, the toolbar should be disabled too.
Maybe the editor should tell all the modules that its status is changed.

Some modules might still want to stay enabled even when the editor is disabled.
For example a multi-cursor module might still want to show the cursors of other users.

I also can't find a way to enable/disable a single module.

**Steps for Reproduction**
1. Visit http://quilljs.com/
2. Write quill.disable(); in the console to disable the editor.
3. Click on the list button in the toolbar

**Expected behavior**:
Nothing should happen because the editor is disabled.

**Actual behavior**:
The title 'Quill Rich Text Editor' is turned into a list.

**Platforms**:
Firefox 48 on Windows 7

**Version**:
1.0.0-rc4

**Comment by ben2323** [comment]
Was this bug fixed already ?

**Comment by shuckster** [comment]
I'm still seeing it.

**Comment by jhchen** [comment]
Actually I think the `strict` is operating backwards. If you remove the config it works as expected (toolbar buttons having no effect).

**Comment by iKrishnaSahu** [comment]
@jhchen 
This behaviour is still reproducible with latest stable version of quill.
I was facing this issue in angular library - https://github.com/KillerCodeMonkey/ngx-quill/issues/893

Stackblitz - https://stackblitz.com/edit/js-cspmsm?file=index.html
