### ISSUE TITLE
Enter key is active on disabled editor

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#910]
You'll might want to combine this with the space bar issue
https://github.com/quilljs/quill/issues/908

**Platforms**: [ex. Chrome 48 on Mac 10.11]
Firefox 48 on Windows 7

**Version**: [version]
1.0.0-rc4

**Comment by jhchen** [comment]
What happens when you hit the enter key? Does it insert a newline or do something else to the page?

**Comment by benbro** [comment]
Yes, it insert a newline:

1. Visit http://quilljs.com/
2. Focus the editor
3. Call quill.disable(); in the console
4. Press Enter
