### ISSUE TITLE
Can quill limit the size of upload image?

### ISSUE THREAD

**Issue by diegobona** [quilljs/quill#911]
When the image is large, the response of submitting is slow, so how to deal with ?

 ```
 var editor = new Quill('#postContent', {
  modules: {
    toolbar: '#toolbar-container'
  },
  theme: 'snow',
});

```

**Comment by jhchen** [comment]
This has already been answered on [StackOverflow](http://stackoverflow.com/questions/39296621/can-quill-limit-the-size-of-upload-image/39297611). If you want to submit a feature request, follow the [guidelines](https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#feature-requests).

**Comment by srisridhar1993** [comment]
Is it possible to restrict the types and size of the images to be uploaded?? @jhchen jhchen
