### ISSUE TITLE
Is there a way to set default color for text?

### ISSUE THREAD

**Issue by ahmedlhanafy** [quilljs/quill#914]
Can I change the default color of the text in quill?

**Comment by jhchen** [comment]
Yes you can just use CSS--nothing special on Quill's side is necessary.

**Comment by ahmedlhanafy** [comment]
@jhchen i did but the color picker confuses the color added with css with the default color which is white

**Comment by jhchen** [comment]
Are you also using the default settings in the color picker or are you configuring it?

**Comment by ahmedlhanafy** [comment]
@jhchen I'm using the default one
