### ISSUE TITLE
QuillJS do not work with web components

### ISSUE THREAD

**Issue by vikrantrathore** [quilljs/quill#916]
Quill editor do not support shadowDom or web components standard [W3C web components Shadow Dom Specification](https://www.w3.org/TR/shadow-dom/)

So it cannot be used in modern web component projects written using Polymer, reactjs, vuejs or angular2 easily without substantial modifications.

The details of the issue and discussion can be seen in #904 and also at Polymer/polymer#3896

**Comment by jhchen** [comment]
Please address the issues in #904 first.
