### ISSUE TITLE
full example missing KaTeX when loaded locally (file://)

### ISSUE THREAD

**Issue by AlbertoGP** [quilljs/quill#920]
Entering a formula fails with "Error: Formula module requires KaTeX."

1. Download Quill v1.0, load examples/full.html
2. Click on formula button, enter formula
3. Click on Save

**Expected behavior**: formula is inserted

**Actual behavior**: nothing gets inserted, error message in console: "Error: Formula module requires KaTeX."

**Platforms**: tested Firefox on Ubuntu 16.04

**Version**: 1.0

**Comment by benbro** [comment]
I can't reproduce. For me the formula in the full.html example is working.
Do you see an error when loading the katex js file?
https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js

**Comment by AlbertoGP** [comment]
It happens when opening the file locally, for instance file:///tmp/quill/examples/full.html

I see now that KaTeX is linked from the URL you mention, not included in the distribution.

If I load it through a web server, it works.

**Comment by benbro** [comment]
That's because of the browser security policy.
You can either use a web server or download and use third party javascript and css files locally.
