### ISSUE TITLE
Image uploading

### ISSUE THREAD

**Issue by esconsut1** [quilljs/quill#921]
Quill is awesome.

However no image upload support. That's like on the top of the list of most online rich text editor requirements. 

Almost impossible to have any type of CMS use Quill if one needs to have images inlined within text.

Maybe I overlooked it, is it on the website somewhere?

It would need to take the uploaded image and send it to a backend server, then the server would respond (JSON) with a path to the uploaded image.

**Comment by delibes** [comment]
You might like jhchen's very helpful answer to issue #863 . It should be enough to start building this yourself and integrate any CDN API.

**Comment by jhchen** [comment]
@delibes is correct and also a more generalized approach to adding images/files is being discussed in #822.

**Comment by wenmingtang** [comment]
# aa
