### ISSUE TITLE
The editor does not focus at all using chrome on a iOS mobile device

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#924]
The editor does not focus at all using chrome on a iOS mobile device. It also does not work in Safari, unless you add the app to the home screen. Then the editor focuses fine. 

But if I visit the quill website and test the demo it works. 

I have no idea what to do because I am using the quill editor normally. Why is there a difference I have no idea. I don't know how to fix this. Anyone else see this issue?

**Steps for Reproduction**

1. Visit https://memrey.com/public/note/rCCJJkcXxcg5rrf8G on mobile device
2. Try typing anything

**Expected behavior**: 

The keyboard should come up and allow you to type

**Actual behavior**: 

Nothing happens. The editor does not focus

**Platforms**:  Chrome browser on iOS.

**Comment by sferoze** [comment]
has any extra code been added to the demo to get it to focus on mobile?

**Comment by sferoze** [comment]
I figured it out! damn the package fastclick. It was included in my meteor project and really messed up the experience on mobile. 

If you are using Quill editor, get rid of fastclick!

**Comment by zourtney** [comment]
Thanks @sferoze! I was having a very similar problem. Removing FastClick did the trick. 👍 

I was able to retain that "fast click" feel app-wide by using modern, native alternatives ([described here](https://patrickhlauke.github.io/touch/tests/results/#suppressing-300ms-delay)). Specifically, I'm using:

```html
<meta name="viewport" content="width=device-width">
```

**Comment by toBeUrself** [comment]
I have the same issue on a ios mobile device, but I didn't install FastClick package in my project. Anyone know how to fix it?
Thanks in advance.

**Comment by acumulus8** [comment]
Having the same issue and did not install 'FastClick' either.
