### ISSUE TITLE
Pasting text with font-family names with spaces, loses formatting

### ISSUE THREAD

**Issue by peterweck** [quilljs/quill#929]
When you copy HTML that has inline css with a font-family name that has spaces, the font is lost when pasting into the editor. It works fine if the font-family name does not have any spaces in it.

1. Visit http://codepen.io/anon/pen/YGXQWx
2. Copy the "test pasting this text" text
3. Paste it into the editor 

**Expected behavior**: 

The text should maintain the Roboto Slab font when pasted into the editor

**Actual behavior**: 

The text is pasted without any font information so it inherits the current font

**Platforms**: Chrome 52.0.2743.116 on Mac 10.11.6

**Version**: 1.02

**Comment by jhchen** [comment]
There are a few issues here:

1. The whitelist is set to `['inconsolata', 'slabo', 'roboto', 'ubuntu']` and "Roboto Slab" is not in this whitelist.
2. The browser adds quotes and the exact value that needs to be added to the whitelist includes the quotes.
3. The default attributor understands classes, not styles. You can name these classes whatever you want but it happens to be the case the names match the css styles for single word values, but this does not have to do with the space itself. Instead the style attributor should be used.

Here's a modified codepen with these fixes: http://codepen.io/quill/pen/LRpmZm
