### ISSUE TITLE
docs list item style messes with the editor list item

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#930]
The docs list item style adds a bullet to the editor list item.

```
#docs-container li {
  list-style: disc inside;
}
```
https://github.com/quilljs/quilljs.github.io/blob/master/assets/css/styles.css#L1033

**Steps for Reproduction**

1. Visit http://quilljs.com/docs/formats/
2. Click on the ordered list button

**Expected behavior**:
We should see an empty list item with a number (1.)

**Actual behavior**:
An empty list item with both a number and a bullet

**Platforms**:
Firefox 48 on Windows 7

**Version**:
1.0.2

**Comment by jhchen** [comment]
Fixed 7f1fec10c69ae60d1bcf978930cb7d74039361d8
