### ISSUE TITLE
Uncaught TypeError: Cannot set property 'textContent' of null with KaTeX module

### ISSUE THREAD

**Issue by kngu9** [quilljs/quill#932]
Hello,

I am having an issue with using the Katex module on Chrome. It is throwing an exception: Uncaught TypeError: Cannot set property 'textContent' of null. Below is the code I am using:

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"></script>
    <link href="https://cdn.quilljs.com/1.0.2/quill.snow.css" rel="stylesheet">

    <div id="editor">

    </div>

    <script type="text/javascript">
    var quill = new Quill('#editor', {
      modules: {
        formula: true,         
        toolbar: [['formula']] 
      },
      theme: 'snow'
    });
    </script>

**Steps for Reproduction**
Run the above code.

**Expected behavior**: [expected]
I expected the Katex module to be running.

**Actual behavior**: [actual]
Katex module is throwing an exception.

**Platforms**: [ex. Chrome 48 on Mac 10.11]
Chrome 52 on Mac OSX

**Version**: [version]
1.0

**Comment by benbro** [comment]
Does the formula work for you on this page?
http://codepen.io/anon/pen/VKLrjY
