### ISSUE TITLE
wrong katex and highlight.js CSS url on the playground

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#933]
1. Visit http://quilljs.com/playground/
2. katex.min.css and monokai-sublime.min.css gives 404

Should be:
https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css
https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0/styles/monokai-sublime.min.css

Instead of:
http://cdnjs.cloudflare.com/ajax/libs/katex/katex.min.css
http://cdnjs.cloudflare.com/ajax/libs/highlight.js/styles/monokai-sublime.min.css

**Comment by jhchen** [comment]
Fixed thanks!
