### ISSUE TITLE
internet explorer support

### ISSUE THREAD

**Issue by kisin** [quilljs/quill#936]
are there any plan to add internet explorer 10 & 9 support?

my company using ie10 and i cant use this fine editor as for now

**Comment by jhchen** [comment]
Quill follows the lead of many other open source libraries of supporting the latest two browser versions. IE9 and IE10 control fewer than 1% of the browser market and Microsoft itself [has ended support](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support). Quill will not be supporting IE9 or IE10.

**Comment by fpavlic** [comment]
Hi Jason,

Will you make adjustments to work on IE 11 ? I've tested it in IE Edge and it is working nicely, but IE11 unfortunately not. There is issue where IE11 doesn't support 'classList' - this is easy modification

Thanks,
Filip

**Comment by jhchen** [comment]
@fpavlic IE11 is supported and there is a polyfill already included to handle the classList case. Please file a [bug report](https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#bug-reports) for each issue you are encountering with IE11 and please follow the bug report instructions.

**Comment by parvezshah** [comment]
On IE Edge I am facing issue that is quill component gets resize handler activated  
![image001](https://cloud.githubusercontent.com/assets/1046587/24900274/eb8cfd1c-1ec0-11e7-9efd-6ec1c779e212.png)
Following is the code I am using to render quillJS
		<div class="row" style="background-color: white;">
		      <div id="messageTA" class="rtf col-xs-12" contentEditable="true"></div>
		</div>

**Comment by SidFeng** [comment]
我非常的失望， IE9 and IE10 control fewer than 45% of the browser market in china.

**Comment by sinbargit** [comment]
> 我非常的失望， IE9 and IE10 control fewer than 45% of the browser market in china.

Have you find a nice rich editor works on ie9?
