### ISSUE TITLE
Link button broken

### ISSUE THREAD

**Issue by mpriscella** [quilljs/quill#938]
The link button on my toolbar is failing to link the selected text.

**Steps for Reproduction**
```
// Toolbar Options.
[
  [{ header: [false, 1, 2] }],
  ["bold", "italic", "underline"],
  ["blockquote"],
  ["link"]
]
```

1. Create new Quill editor with the above toolbar options.
2. Insert text and then select it.
3. Click the 'link' toolbar button.

**Expected behavior**:
Highlighted text is converted into an anchor tag.

**Actual behavior**:
Highlighted text is unaffected and the following error appears in the console

`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null`.

If you refer to the `js/quill.js` file in the `1.0.3` release tarball, the error is happening around line `9420` (which seems to originate [here](https://github.com/quilljs/quill/blob/develop/ui/tooltip.js#L30)).

**Platforms**:
Google Chrome 53.0.2785.101 (64-bit) running on OSX 10.11.6

**Version**:
1.0.3

**Comment by benbro** [comment]
@mpriscella I created codepen with your toolbar options.
Can you reproduce it here?
http://codepen.io/anon/pen/dpoLWq

I don't see an error with Chrome 53 on Windows 7.

**Comment by mpriscella** [comment]
@benbro Nope, seems to be working there.

Here's a screenshot of the behavior I'm experiencing, I'm still looking around the codebase but it looks like the tooltip is having trouble getting the bounds which is why it's off screen.

Are there any other toolbar modules that use a tooltip which I could test? Maybe I'll be able to get some more helpful information.

**Comment by benbro** [comment]
Can you create a codepen that reproduce it?
Do you see the error on one of the demos on the website?

The video and formula(f<sub>x</sub> button) modules use a tooltip.

**Comment by mpriscella** [comment]
Ahh, here we go -

http://codepen.io/mpriscella/pen/pEJBKZ

My container element doesn't have a defined height.

**Comment by benbro** [comment]
With your codepen the tooltip doesn't show but I don't see an error in the console.

**Comment by mpriscella** [comment]
I don't see the error either. I tried downloading `http://cdn.quilljs.com/1.0.3/quill.js` and using that in my code but I received the same error. Does codepen display library errors in the console?

**Comment by jhchen** [comment]
I'm not seeing any errors on Mac + Chrome (same version is reported). Codepen displays errors to the console. You can just create an error to confirm.

There is a [`bounds`](http://quilljs.com/docs/configuration/#bounds) property to tell Quill where it can show up horizontally. By default it is the whole page and from the screenshot it looks like you have something with a higher z-index covering it. If there's not space to show the tooltip vertically, it is by default hidden. You can overwrite the CSS rule if you plan to have the editing container autogrow, but will cause problems when you scroll:

```css
.ql-snow .ql-out-bottom {
  visibility: visible;
}
```

**Comment by abelousov** [comment]
To get the error, theme should be set to 'snow'; that theme relies on `bounds` option, so the fix could be to check for that option, and if absent, throw an error that explains how to set it correctly (in a perfect world it could link to corresponding docs section)

Can't do it myself, as I have no idea how should be `bounds` described correctly

**Comment by etherbob** [comment]
I had a similar problem while trying to use it with a rails app I'm working on. Had to add
`Rails.application.config.assets.precompile += %w( quill.js )` to config/initializers/assets.rb and pull the script in inside my edit page (vs application.js) to get links working.

**Comment by jhchen** [comment]
@abelousov `bounds` is never absent. It is document.body by default.

**Comment by mpriscella** [comment]
@jhchen I tried again being sure to set a defined height in my css but it's still failing for me. I also looked for any elements with high z-index's per your comment and was able to verify that there were none on the page. I've also removed any unnecessary javascript files from the page in the off chance that they could affect this (they didn't).

As far as I can tell `this.options.bounds` is `null` when being passed to `SnowToolTip` in `themes/snow.js` at line 29, unless `boundsContainer` is modified somewhere else before being passed to `ToolTip` (defined in `ui/tooltip.js`).

**Comment by etherbob** [comment]
@jhchen found a way to reproduce it in chrome/firefox/safari on a mac, but not in codepen

Modify the full example to load quill.js in the header instead of the body.

**Comment by schneidmaster** [comment]
I've reproduced a similar problem. In my case, I am 1) using Webpack to bundle assets and 2) dynamically creating Quill's using jQuery on clicks. I don't really have time at the moment to dive into debugging but I suspect that something in those use cases causes document.body to be undefined when the [defaults are set](https://github.com/quilljs/quill/blob/b93720306e9311ae38a2460fdce2b98e4d17fdc3/core/quill.js#L298). In my case, I got around it just by manually setting the bounds option when creating the Quill instance.

**Comment by benbro** [comment]
**Steps for Reproduction**
1. Load the html document below.
2. Type "Test"
3. Select the text and click on the link button.
Error in the console:
```
TypeError: this.boundsContainer is null
```

```html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style>
      #editor-container {
        height: 375px;
      }
    </style>
    <link href="//cdn.quilljs.com/1.0.3/quill.snow.css" rel="stylesheet" type="text/css" />    
    <script src="//cdn.quilljs.com/1.0.3/quill.js"></script>
</head>
<body>
    <div id="editor-container"></div>
    <script>
      var quill = new Quill('#editor-container', {
        modules: {
          toolbar: [
            ['link']
          ]
        },
        theme: 'snow'
      });
    </script>
</body>
</html>
```

**Comment by benbro** [comment]
A possible fix:
```javascript
class Tooltip {
  constructor(quill, boundsContainer) {
this.boundsContainer = boundsContainer || document.body;
```javascript

**Comment by mpriscella** [comment]
Ahh, that makes sense. Modified my toolbar options to the following and the link tooltip is now working as expected:
```
// Toolbar Options.
{
  modules: {
    toolbar: [
      [{ header: [false, 1, 2] }],
      ["bold", "italic", "underline"],
      ["blockquote"],
      ["link"]
    ]
  },
  bounds: document.body,
  theme: "snow"
}
```

**Comment by lEduFranco** [comment]
The way I found to adjust this tooltip using only css is this:

```
 .ql-snow .ql-tooltip {
    width: 50%;
    height: fit-content;
    transform: translateX(47%) translateY(10px);
  }
```
