### ISSUE TITLE
The given range isn't in document

### ISSUE THREAD

**Issue by mrdream24** [quilljs/quill#939]
<img width="823" alt="2016-09-09 4 52 09" src="https://cloud.githubusercontent.com/assets/6170899/18381247/ec6d5fc6-76ad-11e6-8887-ffc58fdb583e.png">

**Steps for Reproduction**

1. install [evernote cliper](https://chrome.google.com/webstore/detail/evernote-web-clipper/pioclpoplcdbaefihamjohnefbikjilc),type Chinese word
2. click bold button or underline button or italic button
3. type Chinese word

**Platforms**: chrome 52, macOS 10.11

**Version**: 1.0.3

**Comment by jhchen** [comment]
Bugs resulting from interactions with specific browser extensions are out of scope. There are simply too many to support and are difficult to debug as extensions do not document how they work unlike public browser APIs.
