### ISSUE TITLE
Javascript error when deleting and then adding text at beginning of line

### ISSUE THREAD

**Issue by peterweck** [quilljs/quill#949]
When typing text after deleting text at the first character of text in the editor getting a Javascript error:

SCRIPT5007: Unable to get property 'length' of undefined or null reference
File: quill.js, Line: 7020, Column: 10

**Steps for Reproduction**
1. Visit http://quilljs.com/playground/
2. Type the work "test"
3. Click out of the quill editor (click into the javascript editor to the left of the quill editor)
4. Click to put the cursor before for the first 't' in "test" and delete the t. 
5. Type some more characters and you get the Javascript error

**Expected behavior**:

No Javascript error.

**Actual behavior**:

A Javascript error is thrown

**Platforms**:

Windows 7, IE 11.0.9600.17959

**Version**:

1.03

**Comment by jhchen** [comment]
I have not been able to reproduce from these instructions.

![ie11](https://cloud.githubusercontent.com/assets/192974/19216550/9e0ba4b2-8d75-11e6-80a0-d20f6792b752.gif)
