### ISSUE TITLE
bubble theme doesn't work with <!DOCTYPE html>

### ISSUE THREAD

**Issue by skybrian** [quilljs/quill#951]
If you change the quickstart example to use the 'bubble' theme and add <!DOCTYPE html> to the top of the file, the tooltip is invisible.

**Steps for Reproduction**

1. Save HTML file somewhere:

```
<!DOCTYPE html>
<!-- Include stylesheet -->
<link href="https://cdn.quilljs.com/1.0.3/quill.bubble.css" rel="stylesheet">

<!-- Create the editor container -->
<div id="editor">
  <p>Hello World!</p>
  <p>Some initial <strong>bold</strong> text</p>
  <p><br></p>
</div>

<!-- Include the Quill library -->
<script src="https://cdn.quilljs.com/1.0.3/quill.js"></script>

<!-- Initialize Quill editor -->
<script type="text/javascript">
  var quill = new Quill('#editor', {
    theme: 'bubble'
  });
</script>
```

2. Select some text.

**Expected behavior**:

Should see tooltip.

**Actual behavior**:

No tooltip appears. If you use DevTools, the SVG elements are showing up but they are invisible.

**Platforms**:

Tested on Chrome.

**Version**:

1.0.3

**Comment by benbro** [comment]
The bubblet example is using <!DOCTYPE html>
http://quilljs.com/standalone/bubble/

Your example is missing the html head and body elements.

**Comment by skybrian** [comment]
There must be some other difference. Here is another example that doesn't work unless I remove the DOCTYPE.

```
<!DOCTYPE html>
<html>
<head>
<link href="https://cdn.quilljs.com/1.0.3/quill.bubble.css" rel="stylesheet">
</head>
<body>
<div id="editor">
</div>

<!-- Include the Quill library -->
<script src="https://cdn.quilljs.com/1.0.3/quill.js"></script>

<!-- Initialize Quill editor -->
<script type="text/javascript">
  var quill = new Quill('#editor', {
    theme: 'bubble'
  });
</script>
</body>
</html>
```

**Comment by benbro** [comment]
The editor doesn't have enough height to show the tooltip.
If you'll create several lines you'll see the tooltip.

Try this:
```html
<div id="editor" style="height:400px;"></div>
```

**Comment by skybrian** [comment]
I verified that it works with "height" as you suggested, but "min-height" doesn't work.

Also, with height set to 400, if I paste in a large document so that the scrollbar appears, and then select some text on the last line in the document, the tooltip doesn't show up.

It looks like there have to be at least two lines below the current line for the tooltip to show up.

**Comment by benbro** [comment]
Please open a new bug report.
Your issue has nothing to do with doctype.

**Comment by skybrian** [comment]
This is rather rude. I reported additional behavior that I saw as a favor. Open a new bug yourself, if you care to fix it.

**Comment by jhchen** [comment]
@skybrian Believe it or not what you see as a favor might not be valued as one by others. In my view @benbro is doing you the favor by helping you debug. If you disagree, feel free not to give or solicit help and use this open source project for free in peace.

Either way communication on Quill's Github Issues will be civil and this is the only time I will be asking you to change your tone. Feel free to read Quill's [Contributing Guide](https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/quilljs/quill/blob/develop/CODE_OF_CONDUCT.md).

**Comment by bytespider** [comment]
@skybrian Adding a DOCTYPE switches you from quirks mode to standards mode. In standards mode, the html and body elements do not default to 100% of the size of the viewport (browser window); instead, they are only as large as they need to be to contain their children. The table height of 100% means 100% of the containing element, but that's only as large as it needs to be to contain the contents of the table. Quirks mode is an emulation of the behaviour of older browsers, in which the html and body elements filled the viewport.

To fix the problem, you just need to add this to your document:

```css
<style>
  html, body { height: 100% }
</style>
```

Take from http://stackoverflow.com/questions/1966300/height-100-is-not-working-in-html-when-using-doctype-how-i-can-fix-this

**Comment by skybrian** [comment]
I apologize for my rudeness.

From my point of view, I was trying to report some strange behavior and it seemed like I was getting repeatedly dismissed based on different technicalities. On each step we got closer to figuring out what's happening, so that's good, but it still felt like an adversarial relationship, where one person is trying to keep the bug open and the other is trying to close it.

Instead, I'd rather have a conversation. Perhaps there are several different bugs (or possibly features). I'll leave that up to the Quill developers. But we should be able to discuss what's happening first. Maybe a mailing list would be a better place, if there is one?

---

At this point, I think the my confusion was that the quickstart [1] isn't quite as simple as it looks. I was confused by why quirks mode was being used by default, but it appears that's just because the quickstart isn't intended as a full HTML page. So one suggestion is to make it a full html page (with a DOCTYPE), as a better starting point for beginners.

Also, as another stumbling block for beginners, if you are using "snow" and you want to control the size of the entire editor, you actually need two nested divs, because the div that you pass in to Quill constructor is not necessarily the outermost div - the toolbar (if there is one) goes above it. So instead it should be:

```
<div id="editor-container">
<!-- toolbar appears here (if any) -->
<div id="editor"></div> <!-- pass this one to Quill -->
</div>
```

The documentation [3] says "Quill requires an container where the editor will be appended." That's sort of true but isn't the full story. Maybe that could be explained better?

[1] https://quilljs.com/docs/quickstart/
[2] https://quilljs.com/standalone/snow/
[3] https://quilljs.com/docs/configuration/

**Comment by zangab** [comment]
@skybrian put the "min-height" of 400px on the class "ql-editor" - works for me :)
