### ISSUE TITLE
Initializing Quill without toolbar throws error

### ISSUE THREAD

**Issue by jhchen** [quilljs/quill#955]
You should be able to initialize Quill with no toolbar and still use the snow or bubble theme (which adds the toolbar by default).

```js
var quill = new Quill('#editor', {
  modules: {
    toolbar: false
  }
}
```

This configuration currently throws an error in v1.0.3.

**Comment by rockerest** [comment]
After posting [the question on StackOverflow](http://stackoverflow.com/questions/39456273/how-do-i-create-a-quill-editor-without-a-toolbar/39458217), I considered that perhaps it was using a theme that was causing the toolbar to show up. Using `"theme": null` is a viable workaround temporarily (just missing a few little visual things like the border.

Also, using `"theme": false` results in `quill Cannot import themes/false. Are you sure it was registered?` being thrown. Is this another bug?

**Comment by rockerest** [comment]
Submitted a PR for the `"theme": false` issue: #956
