### ISSUE TITLE
basic required tags and attributes

### ISSUE THREAD

**Issue by sijad** [quilljs/quill#958]
I need a list of html tags and attributes to sanitize user input in backend.

I found this https://github.com/quilljs/quill/issues/510#issuecomment-151608229
but that'd old and the example is for node. also `'*': ['style']` is not a good practice.

for instance I'm not sure I should allow iframe for video support? which src should be accepted.
or should I allow `div` tags or what css styles are required, etc.

these information can be very helpful to developers.

**Version**:

1.0.3

**Comment by jhchen** [comment]
> for instance I'm not sure I should allow iframe for video support? which src should be accepted.
or should I allow `div` tags or what css styles are required, etc.

I'm not sure what you mean by this. Can you walk through a use case?

**Comment by sijad** [comment]
@jhchen I mean embedded videos, which rendered in an `iframe`, all `src` values shouldn't be allowed. I was just wonder if quill support every embedded videos links? or only some services like youtube, vimeo, etc?

I also need to know what css styles quill add to tags? (`color`, `font`, `background`, etc), because allowing all css styles can be dangerous.

**Comment by jhchen** [comment]
The core video format shipped with Quill allows any url with an http or https protocol with no limitation on domain. All formatting and content is customizable in Quill--that's one of the core benefits and differentiators of Quill. So you can customize the sanitization of links, images, or videos.

Quill has a data model that abstracts over the DOM so working directly with tags, styles and attributes is not something Quill supports. This [guide](http://quilljs.com/guides/cloning-medium-with-parchment/) can give you an idea of how the data model works.
