### ISSUE TITLE
Feature Request: Ability to embed PDF into editor

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#959]
This is a feature request.

It would be nice to have the ability to embed a PDF into the quill editor. 

It seems like this would be an addon module. Or it could come as an option with the quill editor. 

Something like this: https://pdfobject.com/

I think it could work just like the add link, where you click the toolbar icon for PDF, and can paste in a link to a PDF document. 

And the API could support insert PDF just like insert Image. 

So if I did make my own custom button to embed pdf, I can just use the API to embed the PDF.

**Comment by jhchen** [comment]
Using Parchment you should be able to create and embed blot to do this since 1.0 was released.
