### ISSUE TITLE
Add binding to special characters

### ISSUE THREAD

**Issue by doroncy** [quilljs/quill#961]
I have trouble to add add bidning to special characters like: '/', ':', etc...
```javascript
quill.keyboard.addBinding({
  key: ':',
  handler: function(range, context) {
    console.log('ok', range, context);
  }
});
```
any ideas what am i missing ?
also in the documents i see you use Keyboard.keys.BACKSPACE for example, how do i get this Keyboard object?

**Comment by jhchen** [comment]
You can get keyboard by:

```js
var Keyboard = Quill.import('modules/keyboard');
```

I added a [clarification](https://github.com/quilljs/quill/commit/30702fff1d4e8c3c2ffe64c3522e7bade3ba1ce7) to the docs the but you will have to pass the keyCode

```js
quill.keyboard.addBinding({
  key: 186,
  shiftKey: true,
  handler: function(range, context) {
    console.log('ok', range, context);
  }
});
```
