### ISSUE TITLE
pasting text with leading or trailing tabs is losing tabs

### ISSUE THREAD

**Issue by peterweck** [quilljs/quill#962]
On IE11, when you paste a line of text that starts with a tab and ends with a tab, the tab at the start and end of the line are removed. 

**Steps for Reproduction**
1. visit [quilljs.com]
2. type a line of text that starts with a tab and ends with a tab
3. copy the line of text (highlight and press control-c)
4. Go to the start of a new line and paste the text (control-v)

**Expected behavior**:

The tabs are the start and end of the line should be preserved

**Actual behavior**:

The tabs at the start and end of the line are removed.

**Platforms**:

Windows 8.1 - IE 11.0.29

**Version**:

1.0.3

**Comment by yaroslavputria** [comment]
Hi @jhchen,
I'm facing this on Chrome with Windows 10.
Quill 1.3.7.
