### ISSUE TITLE
<video> tag was removed after pasteHTML()

### ISSUE THREAD

**Issue by djyde** [quilljs/quill#965]
**Steps for Reproduction**

Visit http://jsfiddle.net/djyde/y670jwnz/2/

**Expected behavior**:

I want to paste HTML that with some `<video>` tags. 

**Actual behavior**:

But after `pasteHTML()`, `<video>` was removed

**Version**:

v1.0.3

**Comment by jhchen** [comment]
Quill does not accept arbitrary HTML and all pastes go through its converter. Take a look at the [Clipboard APIs](http://quilljs.com/docs/modules/clipboard/#api) to add recognizing `video` elements.

**Comment by MeXaaR** [comment]
@jhchen Did you succeed to do this ?
I am currently trying the same
