### ISSUE TITLE
Question: Hyperlinking to current document possible?

### ISSUE THREAD

**Issue by sumitkm** [quilljs/quill#978]
When creating a document in Quill, is it possible to a href in the document itself? 
I guess the default link button doesn't support creation of anchors like

`<a href="#heading1"><h1>This is a heading</h1></a>`

The correct way to go is custom link blot ?

**Comment by jhchen** [comment]
The gap is more the headers than the links. I tried setting the url of a link to `#heading1` through the normal tooltip on quilljs.com and it was not sanitized. However headers do not automatically add an id attribute so you would have to extend the Header blot to achieve this. This was implemented at some point but [removed](https://github.com/quilljs/quill/commit/961a0f53e58fbf6a1bb32cd732551011c5aa45a8) during the beta but that might be a good resource for a custom Header.
