### ISSUE TITLE
formatText(x,…) off-by-1 if preceding video, compared to getText()[x]

### ISSUE THREAD

**Issue by unhammer** [quilljs/quill#985]
I was hoping I could always use indices from getText() to call formatText(), but there are situations where the indices get offset.

**Steps for Reproduction**

1. Insert example content with a video element at top:
`quill.setContents({"ops":[{"insert":{"video":"http://example.com"}},{"insert":"ABCDE"}]})`
2. get the text out (`"ABCDE\n"`) note that e.g. index 2 is "C" with `console.log( quill.getText()[2])`
3. try to format from the letter "C" onwards with `quill.formatText(2,3,"bold",true)`

**Expected behavior**:
It should be possible to formatText using a certain index of getText()'s string, and have quill apply the formatting to that character in the document.

**Actual behavior**:
Quill is offset by 1 character if there's a video element before, so the first bold character in the example above is "B".

**Platforms**:

Firefox 48 on Linux.

**Version**:

1.0.3

**Comment by jhchen** [comment]
`getText()` only extracts string contents from Quill. For things like video and images there is none. It was considered at some point to insert a filler character for video/images to make the lengths/indices line up but that introduces its own set of issues.

What is your specific use case?

**Comment by unhammer** [comment]
How about changing formatText() instead of adding fillers? If getText() only extracts string contents, I would expect formatText() to only apply to string contents.

The use case is linting the plaintext, and providing underlines under the right substrings, while being robust against rich-text clipboards from all kinds of sources. 

If there's a list of "unsafe" elements that add filler indices in formatText() but not getText(), I suppose I could count such elements preceding the given start/end indices, and write a wrapper to formatText() that will allow round-tripping indices with getText().

**Comment by jhchen** [comment]
I will update the docs to make this behavior from `getText()` more clear. [`getContents()`](https://quilljs.com/docs/api/#getcontents) does give you both text and embeds so one path you might consider using this instead. I'm not 100% clear on your specific use case but iterating and filling is one possible solution:

```js
var contents = quill.getContents();
var text = contents.ops.map(function(op) {
   return typeof op.insert === 'string' ? op.insert : ' ';
}).join('');
```
