### ISSUE TITLE
Not loading existing content?

### ISSUE THREAD

**Issue by r3id** [quilljs/quill#989]
I have added QuillJS to my page, its loading fine. However, the existing content for the text area is not visible only the placeholder.

When I inspect the code the `ql-editor` div has the content in there I cant seem to work out why the content is not displaying in the edit box.

Any ideas why this content might not be loading?

**Comment by benbro** [comment]
Example for loading existing content:
http://codepen.io/anon/pen/QKKvdZ

Please fork the playground and show what you are trying to do.

**Comment by hallaathrad** [comment]
Seeing the same issue... Quill being applied on a `<textarea>` doesn't display the prefilled content.
It does create a `<div class="ql-editor" contenteditable="true"><p>prefilled text</p></div>` which is not being displayed, yet is shown on the dom.
The prefilled content —in my particular case— is the user's description, loaded from the database using rails (thus, before document.ready).

**Comment by benbro** [comment]
Previous discussion on textarea
https://github.com/quilljs/quill/issues/87

**Comment by hallaathrad** [comment]
So basically, the content of the `textarea` needs to be passed manually into `.ql-editor` on load, and then the other way around before unload?
Out of curiosity, and please indulge me as I'm obviously not that knowledgeable in these matters, why doesn't it do it by default? how is the `textarea`'s content different? I get they are not meant to display html, but they can certainly store it as text.

**Comment by jhchen** [comment]
You need to put the existing contents in a `<div>` not a `<textarea>`.

**Comment by hallaathrad** [comment]
I've done that, since `textarea` doesn't render html content... 
but other components (such as maxlength) only work with form fields.

Lots of hacking to be done here haha.

Thanks for Quill. it's pretty awesome!
