### ISSUE TITLE
Missing SVG icon for 'code' toolbar format

### ISSUE THREAD

**Issue by marktron** [quilljs/quill#998]
As seen on http://codepen.io/anon/pen/wzgYqX, the 'code' format does not have an SVG icon. It does properly format the text, and there is also a 'code-block' icon for block level formatting.

**Comment by jhchen** [comment]
Do you think the `code` and `code-block` icons should look differently?

**Comment by marktron** [comment]
Ideally they would be two different icons since they do different things (apply block level formatting vs inline formatting), but I recognize it's difficult to convey that clearly with two versions of a very similar icon.

**Comment by jackmu95** [comment]
@jhchen This commit is just a quick fix for the missing icon. Better two times the same icon as no icon ;)

In general it would be good if there are two different icons for 'code' and 'code-block'.

**Comment by jhchen** [comment]
Yes I think different icons will be difficult so let's go with this for now.

**Comment by webmatth** [comment]
Hi I've made a different icon for code-block (inspired from slack code-block icon)
for now i'm using it like this:
`const icons = Quill.import('ui/icons');
      icons['code-block'] = '<svg viewbox="0 -2 15 18">\n' +
        '\t<polyline class="ql-even ql-stroke" points="2.48 2.48 1 3.96 2.48 5.45"/>\n' +
        '\t<polyline class="ql-even ql-stroke" points="8.41 2.48 9.9 3.96 8.41 5.45"/>\n' +
        '\t<line class="ql-stroke" x1="6.19" y1="1" x2="4.71" y2="6.93"/>\n' +
        '\t<polyline class="ql-stroke" points="12.84 3 14 3 14 13 2 13 2 8.43"/>\n' +
        '</svg>';`
Hope it helps!
